Bib.ret([
[1001,"Quello che era da principio, quello che noi abbiamo udito, quello che abbiamo veduto con i nostri occhi, quello che contemplammo e che le nostre mani toccarono del Verbo della vita -"],
[1002,"la vita infatti si manifestò, noi l'abbiamo veduta e di ciò diamo testimonianza e vi annunciamo la vita eterna, che era presso il Padre e che si manifestò a noi -,"],
[1003,"quello che abbiamo veduto e udito, noi lo annunciamo anche a voi, perché anche voi siate in comunione con noi. E la nostra comunione è con il Padre e con il Figlio suo, Gesù Cristo."],
[1004,"Queste cose vi scriviamo, perché la nostra gioia sia piena."],
[1005,"Questo è il messaggio che abbiamo udito da lui e che noi vi annunciamo: Dio è luce e in lui non c'è tenebra alcuna."],
[1006,"Se diciamo di essere in comunione con lui e camminiamo nelle tenebre, siamo bugiardi e non mettiamo in pratica la verità."],
[1007,"Ma se camminiamo nella luce, come egli è nella luce, siamo in comunione gli uni con gli altri, e il sangue di Gesù, il Figlio suo, ci purifica da ogni peccato."],
[1008,"Se diciamo di essere senza peccato, inganniamo noi stessi e la verità non è in noi."],
[1009,"Se confessiamo i nostri peccati, egli è fedele e giusto tanto da perdonarci i peccati e purificarci da ogni iniquità."],
[1010,"Se diciamo di non avere peccato, facciamo di lui un bugiardo e la sua parola non è in noi."],
[2001,"Figlioli miei, vi scrivo queste cose perché non pecchiate; ma se qualcuno ha peccato, abbiamo un Paraclito presso il Padre: Gesù Cristo, il giusto."],
[2002,"È lui la vittima di espiazione per i nostri peccati; non soltanto per i nostri, ma anche per quelli di tutto il mondo."],
[2003,"Da questo sappiamo di averlo conosciuto: se osserviamo i suoi comandamenti."],
[2004,"Chi dice: \"Lo conosco\", e non osserva i suoi comandamenti, è bugiardo e in lui non c'è la verità."],
[2005,"Chi invece osserva la sua parola, in lui l'amore di Dio è veramente perfetto. Da questo conosciamo di essere in lui."],
[2006,"Chi dice di rimanere in lui, deve anch'egli comportarsi come lui si è comportato."],
[2007,"Carissimi, non vi scrivo un nuovo comandamento, ma un comandamento antico, che avete ricevuto da principio. Il comandamento antico è la Parola che avete udito."],
[2008,"Eppure vi scrivo un comandamento nuovo, e ciò è vero in lui e in voi, perché le tenebre stanno diradandosi e già appare la luce vera."],
[2009,"Chi dice di essere nella luce e odia suo fratello, è ancora nelle tenebre."],
[2010,"Chi ama suo fratello, rimane nella luce e non vi è in lui occasione di inciampo."],
[2011,"Ma chi odia suo fratello, è nelle tenebre, cammina nelle tenebre e non sa dove va, perché le tenebre hanno accecato i suoi occhi."],
[2012,"Scrivo a voi, figlioli, perché vi sono stati perdonati i peccati in virtù del suo nome."],
[2013,"Scrivo a voi, padri, perché avete conosciuto colui che è da principio. Scrivo a voi, giovani, perché avete vinto il Maligno."],
[2014,"Ho scritto a voi, figlioli, perché avete conosciuto il Padre. Ho scritto a voi, padri, perché avete conosciuto colui che è da principio. Ho scritto a voi, giovani, perché siete forti e la parola di Dio rimane in voi e avete vinto il Maligno."],
[2015,"Non amate il mondo, né le cose del mondo! Se uno ama il mondo, l'amore del Padre non è in lui;"],
[2016,"perché tutto quello che è nel mondo - la concupiscenza della carne, la concupiscenza degli occhi e la superbia della vita - non viene dal Padre, ma viene dal mondo."],
[2017,"E il mondo passa con la sua concupiscenza; ma chi fa la volontà di Dio rimane in eterno!"],
[2018,"Figlioli, è giunta l'ultima ora. Come avete sentito dire che l'anticristo deve venire, di fatto molti anticristi sono già venuti. Da questo conosciamo che è l'ultima ora."],
[2019,"Sono usciti da noi, ma non erano dei nostri; se fossero stati dei nostri, sarebbero rimasti con noi; sono usciti perché fosse manifesto che non tutti sono dei nostri."],
[2020,"Ora voi avete ricevuto l'unzione dal Santo, e tutti avete la conoscenza."],
[2021,"Non vi ho scritto perché non conoscete la verità, ma perché la conoscete e perché nessuna menzogna viene dalla verità."],
[2022,"Chi è il bugiardo se non colui che nega che Gesù è il Cristo? L'anticristo è colui che nega il Padre e il Figlio."],
[2023,"Chiunque nega il Figlio, non possiede nemmeno il Padre; chi professa la sua fede nel Figlio possiede anche il Padre."],
[2024,"Quanto a voi, quello che avete udito da principio rimanga in voi. Se rimane in voi quello che avete udito da principio, anche voi rimarrete nel Figlio e nel Padre."],
[2025,"E questa è la promessa che egli ci ha fatto: la vita eterna."],
[2026,"Questo vi ho scritto riguardo a coloro che cercano di ingannarvi."],
[2027,"E quanto a voi, l'unzione che avete ricevuto da lui rimane in voi e non avete bisogno che qualcuno vi istruisca. Ma, come la sua unzione vi insegna ogni cosa ed è veritiera e non mentisce, così voi rimanete in lui come essa vi ha istruito."],
[2028,"E ora, figlioli, rimanete in lui, perché possiamo avere fiducia quando egli si manifesterà e non veniamo da lui svergognati alla sua venuta."],
[2029,"Se sapete che egli è giusto, sappiate anche che chiunque opera la giustizia, è stato generato da lui."],
[3001,"Vedete quale grande amore ci ha dato il Padre per essere chiamati figli di Dio, e lo siamo realmente! Per questo il mondo non ci conosce: perché non ha conosciuto lui."],
[3002,"Carissimi, noi fin d'ora siamo figli di Dio, ma ciò che saremo non è stato ancora rivelato. Sappiamo però che quando egli si sarà manifestato, noi saremo simili a lui, perché lo vedremo così come egli è."],
[3003,"Chiunque ha questa speranza in lui, purifica se stesso, come egli è puro."],
[3004,"Chiunque commette il peccato, commette anche l'iniquità, perché il peccato è l'iniquità."],
[3005,"Voi sapete che egli si manifestò per togliere i peccati e che in lui non vi è peccato."],
[3006,"Chiunque rimane in lui non pecca; chiunque pecca non l'ha visto né l'ha conosciuto."],
[3007,"Figlioli, nessuno v'inganni. Chi pratica la giustizia è giusto come egli è giusto."],
[3008,"Chi commette il peccato viene dal diavolo, perché da principio il diavolo è peccatore. Per questo si manifestò il Figlio di Dio: per distruggere le opere del diavolo."],
[3009,"Chiunque è stato generato da Dio non commette peccato, perché un germe divino rimane in lui, e non può peccare perché è stato generato da Dio."],
[3010,"In questo si distinguono i figli di Dio dai figli del diavolo: chi non pratica la giustizia non è da Dio, e neppure lo è chi non ama il suo fratello."],
[3011,"Poiché questo è il messaggio che avete udito da principio: che ci amiamo gli uni gli altri."],
[3012,"Non come Caino, che era dal Maligno e uccise suo fratello. E per quale motivo l'uccise? Perché le sue opere erano malvagie, mentre quelle di suo fratello erano giuste."],
[3013,"Non meravigliatevi, fratelli, se il mondo vi odia."],
[3014,"Noi sappiamo che siamo passati dalla morte alla vita, perché amiamo i fratelli. Chi non ama rimane nella morte."],
[3015,"Chiunque odia il proprio fratello è omicida, e voi sapete che nessun omicida ha più la vita eterna che dimora in lui."],
[3016,"In questo abbiamo conosciuto l'amore, nel fatto che egli ha dato la sua vita per noi; quindi anche noi dobbiamo dare la vita per i fratelli."],
[3017,"Ma se uno ha ricchezze di questo mondo e, vedendo il suo fratello in necessità, gli chiude il proprio cuore, come rimane in lui l'amore di Dio?"],
[3018,"Figlioli, non amiamo a parole né con la lingua, ma con i fatti e nella verità."],
[3019,"In questo conosceremo che siamo dalla verità e davanti a lui rassicureremo il nostro cuore,"],
[3020,"qualunque cosa esso ci rimproveri. Dio è più grande del nostro cuore e conosce ogni cosa."],
[3021,"Carissimi, se il nostro cuore non ci rimprovera nulla, abbiamo fiducia in Dio,"],
[3022,"e qualunque cosa chiediamo, la riceviamo da lui, perché osserviamo i suoi comandamenti e facciamo quello che gli è gradito."],
[3023,"Questo è il suo comandamento: che crediamo nel nome del Figlio suo Gesù Cristo e ci amiamo gli uni gli altri, secondo il precetto che ci ha dato."],
[3024,"Chi osserva i suoi comandamenti rimane in Dio e Dio in lui. In questo conosciamo che egli rimane in noi: dallo Spirito che ci ha dato."],
[4001,"Carissimi, non prestate fede ad ogni spirito, ma mettete alla prova gli spiriti, per saggiare se provengono veramente da Dio, perché molti falsi profeti sono venuti nel mondo."],
[4002,"In questo potete riconoscere lo Spirito di Dio: ogni spirito che riconosce Gesù Cristo venuto nella carne, è da Dio;"],
[4003,"ogni spirito che non riconosce Gesù, non è da Dio. Questo è lo spirito dell'anticristo che, come avete udito, viene, anzi è già nel mondo."],
[4004,"Voi siete da Dio, figlioli, e avete vinto costoro, perché colui che è in voi è più grande di colui che è nel mondo."],
[4005,"Essi sono del mondo, perciò insegnano cose del mondo e il mondo li ascolta."],
[4006,"Noi siamo da Dio: chi conosce Dio ascolta noi; chi non è da Dio non ci ascolta. Da questo noi distinguiamo lo spirito della verità e lo spirito dell'errore."],
[4007,"Carissimi, amiamoci gli uni gli altri, perché l'amore è da Dio: chiunque ama è stato generato da Dio e conosce Dio."],
[4008,"Chi non ama non ha conosciuto Dio, perché Dio è amore."],
[4009,"In questo si è manifestato l'amore di Dio in noi: Dio ha mandato nel mondo il suo Figlio unigenito, perché noi avessimo la vita per mezzo di lui."],
[4010,"In questo sta l'amore: non siamo stati noi ad amare Dio, ma è lui che ha amato noi e ha mandato il suo Figlio come vittima di espiazione per i nostri peccati."],
[4011,"Carissimi, se Dio ci ha amati così, anche noi dobbiamo amarci gli uni gli altri."],
[4012,"Nessuno mai ha visto Dio; se ci amiamo gli uni gli altri, Dio rimane in noi e l'amore di lui è perfetto in noi."],
[4013,"In questo si conosce che noi rimaniamo in lui ed egli in noi: egli ci ha donato il suo Spirito."],
[4014,"E noi stessi abbiamo veduto e attestiamo che il Padre ha mandato il suo Figlio come salvatore del mondo."],
[4015,"Chiunque confessa che Gesù è il Figlio di Dio, Dio rimane in lui ed egli in Dio."],
[4016,"E noi abbiamo conosciuto e creduto l'amore che Dio ha in noi. Dio è amore; chi rimane nell'amore rimane in Dio e Dio rimane in lui."],
[4017,"In questo l'amore ha raggiunto tra noi la sua perfezione: che abbiamo fiducia nel giorno del giudizio, perché come è lui, così siamo anche noi, in questo mondo."],
[4018,"Nell'amore non c'è timore, al contrario l'amore perfetto scaccia il timore, perché il timore suppone un castigo e chi teme non è perfetto nell'amore."],
[4019,"Noi amiamo perché egli ci ha amati per primo."],
[4020,"Se uno dice: \"Io amo Dio\" e odia suo fratello, è un bugiardo. Chi infatti non ama il proprio fratello che vede, non può amare Dio che non vede."],
[4021,"E questo è il comandamento che abbiamo da lui: chi ama Dio, ami anche suo fratello."],
[5001,"Chiunque crede che Gesù è il Cristo, è stato generato da Dio; e chi ama colui che ha generato, ama anche chi da lui è stato generato."],
[5002,"In questo conosciamo di amare i figli di Dio: quando amiamo Dio e osserviamo i suoi comandamenti."],
[5003,"In questo infatti consiste l'amore di Dio, nell'osservare i suoi comandamenti; e i suoi comandamenti non sono gravosi."],
[5004,"Chiunque è stato generato da Dio vince il mondo; e questa è la vittoria che ha vinto il mondo: la nostra fede."],
[5005,"E chi è che vince il mondo se non chi crede che Gesù è il Figlio di Dio?"],
[5006,"Egli è colui che è venuto con acqua e sangue, Gesù Cristo; non con l'acqua soltanto, ma con l'acqua e con il sangue. Ed è lo Spirito che dà testimonianza, perché lo Spirito è la verità."],
[5007,"Poiché tre sono quelli che danno testimonianza:"],
[5008,"lo Spirito, l'acqua e il sangue, e questi tre sono concordi."],
[5009,"Se accettiamo la testimonianza degli uomini, la testimonianza di Dio è superiore: e questa è la testimonianza di Dio, che egli ha dato riguardo al proprio Figlio."],
[5010,"Chi crede nel Figlio di Dio, ha questa testimonianza in sé. Chi non crede a Dio, fa di lui un bugiardo, perché non crede alla testimonianza che Dio ha dato riguardo al proprio Figlio."],
[5011,"E la testimonianza è questa: Dio ci ha donato la vita eterna e questa vita è nel suo Figlio."],
[5012,"Chi ha il Figlio, ha la vita; chi non ha il Figlio di Dio, non ha la vita."],
[5013,"Questo vi ho scritto perché sappiate che possedete la vita eterna, voi che credete nel nome del Figlio di Dio."],
[5014,"E questa è la fiducia che abbiamo in lui: qualunque cosa gli chiediamo secondo la sua volontà, egli ci ascolta."],
[5015,"E se sappiamo che ci ascolta in tutto quello che gli chiediamo, sappiamo di avere già da lui quanto abbiamo chiesto."],
[5016,"Se uno vede il proprio fratello commettere un peccato che non conduce alla morte, preghi, e Dio gli darà la vita: a coloro, cioè, il cui peccato non conduce alla morte. C'è infatti un peccato che conduce alla morte; non dico di pregare riguardo a questo peccato."],
[5017,"Ogni iniquità è peccato, ma c'è il peccato che non conduce alla morte."],
[5018,"Sappiamo che chiunque è stato generato da Dio non pecca: chi è stato generato da Dio preserva se stesso e il Maligno non lo tocca."],
[5019,"Noi sappiamo che siamo da Dio, mentre tutto il mondo sta in potere del Maligno."],
[5020,"Sappiamo anche che il Figlio di Dio è venuto e ci ha dato l'intelligenza per conoscere il vero Dio. E noi siamo nel vero Dio, nel Figlio suo Gesù Cristo: egli è il vero Dio e la vita eterna."],
[5021,"Figlioli, guardatevi dai falsi dei!"]
])
