Bib.ret([
[1001,"Pietro, apostolo di Gesù Cristo, ai fedeli che vivono come stranieri, dispersi nel Ponto, nella Galazia, nella Cappadocia, nell'Asia e nella Bitinia, scelti"],
[1002,"secondo il piano stabilito da Dio Padre, mediante lo Spirito che santifica, per obbedire a Gesù Cristo e per essere aspersi dal suo sangue: a voi grazia e pace in abbondanza."],
[1003,"Sia benedetto Dio e Padre del Signore nostro Gesù Cristo, che nella sua grande misericordia ci ha rigenerati, mediante la risurrezione di Gesù Cristo dai morti, per una speranza viva,"],
[1004,"per un'eredità che non si corrompe, non si macchia e non marcisce. Essa è conservata nei cieli per voi,"],
[1005,"che dalla potenza di Dio siete custoditi mediante la fede, in vista della salvezza che sta per essere rivelata nell'ultimo tempo."],
[1006,"Perciò siete ricolmi di gioia, anche se ora dovete essere, per un po' di tempo, afflitti da varie prove,"],
[1007,"affinché la vostra fede, messa alla prova, molto più preziosa dell'oro - destinato a perire e tuttavia purificato con fuoco - torni a vostra lode, gloria e onore quando Gesù Cristo si manifesterà."],
[1008,"Voi lo amate, pur senza averlo visto e ora, senza vederlo, credete in lui. Perciò esultate di gioia indicibile e gloriosa,"],
[1009,"mentre raggiungete la meta della vostra fede: la salvezza delle anime."],
[1010,"Su questa salvezza indagarono e scrutarono i profeti, che preannunciavano la grazia a voi destinata;"],
[1011,"essi cercavano di sapere quale momento o quali circostanze indicasse lo Spirito di Cristo che era in loro, quando prediceva le sofferenze destinate a Cristo e le glorie che le avrebbero seguite."],
[1012,"A loro fu rivelato che, non per se stessi, ma per voi erano servitori di quelle cose che ora vi sono annunciate per mezzo di coloro che vi hanno portato il Vangelo mediante lo Spirito Santo, mandato dal cielo: cose nelle quali gli angeli desiderano fissare lo sguardo."],
[1013,"Perciò, cingendo i fianchi della vostra mente e restando sobri, ponete tutta la vostra speranza in quella grazia che vi sarà data quando Gesù Cristo si manifesterà."],
[1014,"Come figli obbedienti, non conformatevi ai desideri di un tempo, quando eravate nell'ignoranza,"],
[1015,"ma, come il Santo che vi ha chiamati, diventate santi anche voi in tutta la vostra condotta."],
[1016,"Poiché sta scritto:  Sarete santi, perché io sono santo ."],
[1017,"E se chiamate Padre colui che, senza fare preferenze, giudica ciascuno secondo le proprie opere, comportatevi con timore di Dio nel tempo in cui vivete quaggiù come stranieri."],
[1018,"Voi sapete che non a prezzo di cose effimere, come argento e oro, foste liberati dalla vostra vuota condotta, ereditata dai padri,"],
[1019,"ma con il sangue prezioso di Cristo, agnello senza difetti e senza macchia."],
[1020,"Egli fu predestinato già prima della fondazione del mondo, ma negli ultimi tempi si è manifestato per voi;"],
[1021,"e voi per opera sua credete in Dio, che lo ha risuscitato dai morti e gli ha dato gloria, in modo che la vostra fede e la vostra speranza siano rivolte a Dio."],
[1022,"Dopo aver purificato le vostre anime con l'obbedienza alla verità per amarvi sinceramente come fratelli, amatevi intensamente, di vero cuore, gli uni gli altri,"],
[1023,"rigenerati non da un seme corruttibile ma incorruttibile, per mezzo della parola di Dio viva ed eterna."],
[1024,"Perché ogni carne è come l'erba e tutta la sua gloria come un fiore di campo. L'erba inaridisce, i fiori cadono,"],
[1025,"ma la parola del Signore rimane in eterno. E questa è la parola del Vangelo che vi è stato annunciato."],
[2001,"Allontanate dunque ogni genere di cattiveria e di frode, ipocrisie, gelosie e ogni maldicenza."],
[2002,"Come bambini appena nati desiderate avidamente il genuino latte spirituale, grazie al quale voi possiate crescere verso la salvezza,"],
[2003,"se davvero avete gustato che buono è il Signore."],
[2004,"Avvicinandovi a lui, pietra viva, rifiutata dagli uomini ma scelta e preziosa davanti a Dio,"],
[2005,"quali pietre vive siete costruiti anche voi come edificio spirituale, per un sacerdozio santo e per offrire sacrifici spirituali graditi a Dio, mediante Gesù Cristo."],
[2006,"Si legge infatti nella Scrittura: Ecco, io pongo in Sion una pietra d'angolo , scelta, preziosa, e chi crede in essa non resterà deluso ."],
[2007,"Onore dunque a voi che credete; ma per quelli che non credono la pietra che i costruttori hanno scartato è diventata pietra d'angolo"],
[2008,"e sasso d'inciampo, pietra di scandalo. Essi v'inciampano perché non obbediscono alla Parola. A questo erano destinati."],
[2009,"Voi invece siete stirpe eletta, sacerdozio regale, nazione santa, popolo che Dio  si è acquistato perché proclami le opere ammirevoli  di lui, che vi ha chiamato dalle tenebre alla sua luce meravigliosa."],
[2010,"Un tempo voi eravate  non-popolo , ora invece siete popolo di Dio; un tempo eravate  esclusi dalla misericordia , ora invece avete ottenuto misericordia."],
[2011,"Carissimi, io vi esorto come stranieri e pellegrini ad astenervi dai cattivi desideri della carne, che fanno guerra all'anima."],
[2012,"Tenete una condotta esemplare fra i pagani perché, mentre vi calunniano come malfattori, al vedere le vostre buone opere diano gloria a Dio nel giorno della sua visita."],
[2013,"Vivete sottomessi ad ogni umana autorità per amore del Signore: sia al re come sovrano,"],
[2014,"sia ai governatori come inviati da lui per punire i malfattori e premiare quelli che fanno il bene."],
[2015,"Perché questa è la volontà di Dio: che, operando il bene, voi chiudiate la bocca all'ignoranza degli stolti,"],
[2016,"come uomini liberi, servendovi della libertà non come di un velo per coprire la malizia, ma come servi di Dio."],
[2017,"Onorate tutti, amate i vostri fratelli, temete Dio, onorate il re."],
[2018,"Domestici, state sottomessi con profondo rispetto ai vostri padroni, non solo a quelli buoni e miti, ma anche a quelli prepotenti."],
[2019,"Questa è grazia: subire afflizioni, soffrendo ingiustamente a causa della conoscenza di Dio;"],
[2020,"che gloria sarebbe, infatti, sopportare di essere percossi quando si è colpevoli? Ma se, facendo il bene, sopporterete con pazienza la sofferenza, ciò sarà gradito davanti a Dio."],
[2021,"A questo infatti siete stati chiamati, perché anche Cristo patì per voi, lasciandovi un esempio, perché ne seguiate le orme:"],
[2022,"egli  non commise peccato e non si trovò inganno sulla sua bocca ;"],
[2023,"insultato, non rispondeva con insulti, maltrattato, non minacciava vendetta, ma si affidava a colui che giudica con giustizia."],
[2024,"Egli portò i nostri peccati  nel suo corpo sul legno della croce, perché, non vivendo più per il peccato, vivessimo per la giustizia; dalle sue piaghe siete stati guariti ."],
[2025,"Eravate  erranti come pecore , ma ora siete stati ricondotti al pastore e custode delle vostre anime."],
[3001,"Allo stesso modo voi, mogli, state sottomesse ai vostri mariti, perché, anche se alcuni non credono alla Parola, vengano riguadagnati dal comportamento delle mogli senza bisogno di discorsi,"],
[3002,"avendo davanti agli occhi la vostra condotta casta e rispettosa."],
[3003,"Il vostro ornamento non sia quello esteriore - capelli intrecciati, collane d'oro, sfoggio di vestiti -"],
[3004,"ma piuttosto, nel profondo del vostro cuore, un'anima incorruttibile, piena di mitezza e di pace: ecco ciò che è prezioso davanti a Dio."],
[3005,"Così un tempo si ornavano le sante donne che speravano in Dio; esse stavano sottomesse ai loro mariti,"],
[3006,"come Sara che obbediva ad Abramo, chiamandolo signore. Di lei siete diventate figlie, se operate il bene e non vi lasciate sgomentare da alcuna minaccia."],
[3007,"Così pure voi, mariti, trattate con riguardo le vostre mogli, perché il loro corpo è più debole, e rendete loro onore perché partecipano con voi della grazia della vita: così le vostre preghiere non troveranno ostacolo."],
[3008,"E infine siate tutti concordi, partecipi delle gioie e dei dolori degli altri, animati da affetto fraterno, misericordiosi, umili."],
[3009,"Non rendete male per male né ingiuria per ingiuria, ma rispondete augurando il bene. A questo infatti siete stati chiamati da Dio per avere in eredità la sua benedizione."],
[3010,"Chi  infatti vuole amare la vita e vedere giorni felici trattenga la lingua dal male e le labbra da parole d'inganno,"],
[3011,"eviti il male e faccia il bene, cerchi la pace e la segua,"],
[3012,"perché gli occhi del Signore sono sopra i giusti e le sue orecchie sono attente alle loro preghiere; ma il volto del Signore è contro coloro che fanno il male ."],
[3013,"E chi potrà farvi del male, se sarete ferventi nel bene?"],
[3014,"Se poi doveste soffrire per la giustizia, beati voi!  Non sgomentatevi per paura di loro e non turbatevi,"],
[3015,"ma adorate il Signore , Cristo, nei vostri cuori, pronti sempre a rispondere a chiunque vi domandi ragione della speranza che è in voi."],
[3016,"Tuttavia questo sia fatto con dolcezza e rispetto, con una retta coscienza, perché, nel momento stesso in cui si parla male di voi, rimangano svergognati quelli che malignano sulla vostra buona condotta in Cristo."],
[3017,"Se questa infatti è la volontà di Dio, è meglio soffrire operando il bene che facendo il male,"],
[3018,"perché anche Cristo è morto una volta per sempre per i peccati, giusto per gli ingiusti, per ricondurvi a Dio; messo a morte nel corpo, ma reso vivo nello spirito."],
[3019,"E nello spirito andò a portare l'annuncio anche alle anime prigioniere,"],
[3020,"che un tempo avevano rifiutato di credere, quando Dio, nella sua magnanimità, pazientava nei giorni di Noè, mentre si fabbricava l'arca, nella quale poche persone, otto in tutto, furono salvate per mezzo dell'acqua."],
[3021,"Quest'acqua, come immagine del battesimo, ora salva anche voi; non porta via la sporcizia del corpo, ma è invocazione di salvezza rivolta a Dio da parte di una buona coscienza, in virtù della risurrezione di Gesù Cristo."],
[3022,"Egli è alla destra di Dio, dopo essere salito al cielo e aver ottenuto la sovranità sugli angeli, i Principati e le Potenze."],
[4001,"Avendo Cristo sofferto nel corpo, anche voi dunque armatevi degli stessi sentimenti. Chi ha sofferto nel corpo ha rotto con il peccato,"],
[4002,"per non vivere più il resto della sua vita nelle passioni umane, ma secondo la volontà di Dio."],
[4003,"È finito il tempo trascorso nel soddisfare le passioni dei pagani, vivendo nei vizi, nelle cupidigie, nei bagordi, nelle orge, nelle ubriachezze e nel culto illecito degli idoli."],
[4004,"Per questo trovano strano che voi non corriate insieme con loro verso questo torrente di perdizione, e vi oltraggiano."],
[4005,"Ma renderanno conto a colui che è pronto a giudicare i vivi e i morti."],
[4006,"Infatti anche ai morti è stata annunciata la buona novella, affinché siano condannati, come tutti gli uomini, nel corpo, ma vivano secondo Dio nello Spirito."],
[4007,"La fine di tutte le cose è vicina. Siate dunque moderati e sobri, per dedicarvi alla preghiera."],
[4008,"Soprattutto conservate tra voi una carità fervente, perché  la carità copre una moltitudine di peccati."],
[4009,"Praticate l'ospitalità gli uni verso gli altri, senza mormorare."],
[4010,"Ciascuno, secondo il dono ricevuto, lo metta a servizio degli altri, come buoni amministratori della multiforme grazia di Dio."],
[4011,"Chi parla, lo faccia con parole di Dio; chi esercita un ufficio, lo compia con l'energia ricevuta da Dio, perché in tutto sia glorificato Dio per mezzo di Gesù Cristo, al quale appartengono la gloria e la potenza nei secoli dei secoli. Amen!"],
[4012,"Carissimi, non meravigliatevi della persecuzione che, come un incendio, è scoppiata in mezzo a voi per mettervi alla prova, come se vi accadesse qualcosa di strano."],
[4013,"Ma, nella misura in cui partecipate alle sofferenze di Cristo, rallegratevi perché anche nella rivelazione della sua gloria possiate rallegrarvi ed esultare."],
[4014,"Beati voi, se venite insultati per il nome di Cristo, perché lo Spirito della gloria, che è  Spirito di Dio ,  riposa  su di voi."],
[4015,"Nessuno di voi abbia a soffrire come omicida o ladro o malfattore o delatore."],
[4016,"Ma se uno soffre come cristiano, non ne arrossisca; per questo nome, anzi, dia gloria a Dio."],
[4017,"È questo il momento in cui ha inizio il giudizio a partire dalla casa di Dio; e se incomincia da noi, quale sarà la fine di quelli che non obbediscono al vangelo di Dio?"],
[4018,"E  se   il giusto a stento si salverà, che ne sarà dell'empio e del peccatore?"],
[4019,"Perciò anche quelli che soffrono secondo il volere di Dio, consegnino la loro vita al Creatore fedele, compiendo il bene."],
[5001,"Esorto gli anziani che sono tra voi, quale anziano come loro, testimone delle sofferenze di Cristo e partecipe della gloria che deve manifestarsi:"],
[5002,"pascete il gregge di Dio che vi è affidato, sorvegliandolo non perché costretti ma volentieri, come piace a Dio, non per vergognoso interesse, ma con animo generoso,"],
[5003,"non come padroni delle persone a voi affidate, ma facendovi modelli del gregge."],
[5004,"E quando apparirà il Pastore supremo, riceverete la corona della gloria che non appassisce."],
[5005,"Anche voi, giovani, siate sottomessi agli anziani. Rivestitevi tutti di umiltà gli uni verso gli altri, perché Dio  resiste ai superbi, ma dà grazia agli umili ."],
[5006,"Umiliatevi dunque sotto la potente mano di Dio, affinché vi esalti al tempo opportuno,"],
[5007,"riversando su di lui ogni vostra preoccupazione, perché egli ha cura di voi."],
[5008,"Siate sobri, vegliate. Il vostro nemico, il diavolo,  come leone ruggente  va in giro cercando chi divorare."],
[5009,"Resistetegli saldi nella fede, sapendo che le medesime sofferenze sono imposte ai vostri fratelli sparsi per il mondo."],
[5010,"E il Dio di ogni grazia, il quale vi ha chiamati alla sua gloria eterna in Cristo Gesù, egli stesso, dopo che avrete un poco sofferto, vi ristabilirà, vi confermerà, vi rafforzerà, vi darà solide fondamenta."],
[5011,"A lui la potenza nei secoli. Amen!"],
[5012,"Vi ho scritto brevemente per mezzo di Silvano, che io ritengo fratello fedele, per esortarvi e attestarvi che questa è la vera grazia di Dio. In essa state saldi!"],
[5013,"Vi saluta la comunità che vive in Babilonia e anche Marco, figlio mio."],
[5014,"Salutatevi l'un l'altro con un bacio d'amore fraterno. Pace a voi tutti che siete in Cristo!"]
])
