Bib.ret([
[1001,"Paolo e Silvano e Timoteo alla Chiesa dei Tessalonicesi che è in Dio Padre e nel Signore Gesù Cristo: a voi, grazia e pace."],
[1002,"Rendiamo sempre grazie a Dio per tutti voi, ricordandovi nelle nostre preghiere"],
[1003,"e tenendo continuamente presenti l'operosità della vostra fede, la fatica della vostra carità e la fermezza della vostra speranza nel Signore nostro Gesù Cristo, davanti a Dio e Padre nostro."],
[1004,"Sappiamo bene, fratelli amati da Dio, che siete stati scelti da lui."],
[1005,"Il nostro Vangelo, infatti, non si diffuse fra voi soltanto per mezzo della parola, ma anche con la potenza dello Spirito Santo e con profonda convinzione: ben sapete come ci siamo comportati in mezzo a voi per il vostro bene."],
[1006,"E voi avete seguito il nostro esempio e quello del Signore, avendo accolto la Parola in mezzo a grandi prove, con la gioia dello Spirito Santo,"],
[1007,"così da diventare modello per tutti i credenti della Macedonia e dell'Acaia."],
[1008,"Infatti per mezzo vostro la parola del Signore risuona non soltanto in Macedonia e in Acaia, ma la vostra fede in Dio si è diffusa dappertutto, tanto che non abbiamo bisogno di parlarne."],
[1009,"Sono essi infatti a raccontare come noi siamo venuti in mezzo a voi e come vi siete convertiti dagli idoli a Dio, per servire il Dio vivo e vero"],
[1010,"e attendere dai cieli il suo Figlio, che egli ha risuscitato dai morti, Gesù, il quale ci libera dall'ira che viene."],
[2001,"Voi stessi infatti, fratelli, sapete bene che la nostra venuta in mezzo a voi non è stata inutile."],
[2002,"Ma, dopo aver sofferto e subito oltraggi a Filippi, come sapete, abbiamo trovato nel nostro Dio il coraggio di annunciarvi il vangelo di Dio in mezzo a molte lotte"],
[2003,"E il nostro invito alla fede non nasce da menzogna, né da disoneste intenzioni e neppure da inganno;"],
[2004,"ma, come Dio ci ha trovato degni di affidarci il Vangelo  così noi lo annunciamo, non cercando di piacere agli uomini, ma a Dio, che prova i nostri cuori."],
[2005,"Mai infatti abbiamo usato parole di adulazione, come sapete, né abbiamo avuto intenzioni di cupidigia: Dio ne è testimone."],
[2006,"E neppure abbiamo cercato la gloria umana, né da voi né da altri,"],
[2007,"pur potendo far valere la nostra autorità di apostoli di Cristo. Invece siamo stati amorevoli in mezzo a voi, come una madre che ha cura dei propri figli."],
[2008,"Così, affezionati a voi, avremmo desiderato trasmettervi non solo il vangelo di Dio, ma la nostra stessa vita, perché ci siete diventati cari."],
[2009,"Voi ricordate infatti, fratelli, il nostro duro lavoro e la nostra fatica: lavorando notte e giorno per non essere di peso ad alcuno di voi, vi abbiamo annunciato il vangelo di Dio."],
[2010,"Voi siete testimoni, e lo è anche Dio, che il nostro comportamento verso di voi, che credete, è stato santo, giusto e irreprensibile."],
[2011,"Sapete pure che, come fa un padre verso i propri figli, abbiamo esortato ciascuno di voi,"],
[2012,"vi abbiamo incoraggiato e scongiurato di comportarvi in maniera degna di Dio, che vi chiama al suo regno e alla sua gloria."],
[2013,"Proprio per questo anche noi rendiamo continuamente grazie a Dio perché, ricevendo la parola di Dio che noi vi abbiamo fatto udire, l'avete accolta non come parola di uomini ma, qual è veramente, come parola di Dio, che opera in voi credenti."],
[2014,"Voi infatti, fratelli, siete diventati imitatori delle Chiese di Dio in Cristo Gesù che sono in Giudea, perché anche voi avete sofferto le stesse cose da parte dei vostri connazionali, come loro da parte dei Giudei."],
[2015,"Costoro hanno ucciso il Signore Gesù e i profeti, hanno perseguitato noi, non piacciono a Dio e sono nemici di tutti gli uomini."],
[2016,"Essi impediscono a noi di predicare ai pagani perché possano essere salvati. In tal modo essi colmano sempre di più la misura dei loro peccati! Ma su di loro l'ira è giunta al colmo."],
[2017,"Quanto a noi, fratelli, per poco tempo privati della vostra presenza di persona ma non con il cuore, speravamo ardentemente, con vivo desiderio, di rivedere il vostro volto."],
[2018,"Perciò io, Paolo, più di una volta ho desiderato venire da voi, ma Satana ce lo ha impedito."],
[2019,"Infatti chi, se non proprio voi, è la nostra speranza, la nostra gioia e la corona di cui vantarci davanti al Signore nostro Gesù, nel momento della sua venuta?"],
[2020,"Siete voi la nostra gloria e la nostra gioia!"],
[3001,"Per questo, non potendo più resistere, abbiamo deciso di restare soli ad Atene"],
[3002,"e abbiamo inviato Timoteo, nostro fratello e collaboratore di Dio nel vangelo di Cristo, per confermarvi ed esortarvi nella vostra fede,"],
[3003,"perché nessuno si lasci turbare in queste prove. Voi stessi, infatti, sapete che questa è la nostra sorte;"],
[3004,"infatti, quando eravamo tra voi, dicevamo già che avremmo subito delle prove, come in realtà è accaduto e voi ben sapete."],
[3005,"Per questo, non potendo più resistere, mandai a prendere notizie della vostra fede, temendo che il tentatore vi avesse messi alla prova e che la nostra fatica non fosse servita a nulla."],
[3006,"Ma, ora che Timoteo è tornato, ci ha portato buone notizie della vostra fede, della vostra carità e del ricordo sempre vivo che conservate di noi, desiderosi di vederci, come noi lo siamo di vedere voi."],
[3007,"E perciò, fratelli, in mezzo a tutte le nostre necessità e tribolazioni, ci sentiamo consolati a vostro riguardo, a motivo della vostra fede."],
[3008,"Ora, sì, ci sentiamo rivivere, se rimanete saldi nel Signore."],
[3009,"Quale ringraziamento possiamo rendere a Dio riguardo a voi, per tutta la gioia che proviamo a causa vostra davanti al nostro Dio,"],
[3010,"noi che con viva insistenza, notte e giorno, chiediamo di poter vedere il vostro volto e completare ciò che manca alla vostra fede?"],
[3011,"Voglia Dio stesso, Padre nostro, e il Signore nostro Gesù guidare il nostro cammino verso di voi!"],
[3012,"Il Signore vi faccia crescere e sovrabbondare nell'amore fra voi e verso tutti, come sovrabbonda il nostro per voi,"],
[3013,"per rendere saldi i vostri cuori e irreprensibili nella santità, davanti a Dio e Padre nostro, alla venuta del Signore nostro Gesù con tutti i suoi santi."],
[4001,"Per il resto, fratelli, vi preghiamo e supplichiamo nel Signore Gesù affinché, come avete imparato da noi il modo di comportarvi e di piacere a Dio - e così già vi comportate -, possiate progredire ancora di più."],
[4002,"Voi conoscete quali regole di vita vi abbiamo dato da parte del Signore Gesù."],
[4003,"Questa infatti è volontà di Dio, la vostra santificazione: che vi asteniate dall'impurità,"],
[4004,"che ciascuno di voi sappia trattare il proprio corpo con santità e rispetto,"],
[4005,"senza lasciarsi dominare dalla passione, come i pagani che non conoscono Dio;"],
[4006,"che nessuno in questo campo offenda o inganni il proprio fratello, perché il Signore punisce tutte queste cose, come vi abbiamo già detto e ribadito."],
[4007,"Dio non ci ha chiamati all'impurità, ma alla santificazione."],
[4008,"Perciò chi disprezza queste cose non disprezza un uomo, ma Dio stesso, che vi dona il suo santo Spirito."],
[4009,"Riguardo all'amore fraterno, non avete bisogno che ve ne scriva; voi stessi infatti avete imparato da Dio ad amarvi gli uni gli altri,"],
[4010,"e questo lo fate verso tutti i fratelli dell'intera Macedonia. Ma vi esortiamo, fratelli, a progredire ancora di più"],
[4011,"e a fare tutto il possibile per vivere in pace, occuparvi delle vostre cose e lavorare con le vostre mani, come vi abbiamo ordinato,"],
[4012,"e così condurre una vita decorosa di fronte agli estranei e non avere bisogno di nessuno."],
[4013,"Non vogliamo, fratelli, lasciarvi nell'ignoranza a proposito di quelli che sono morti, perché non siate tristi come gli altri che non hanno speranza."],
[4014,"Se infatti crediamo che Gesù è morto e risorto, così anche Dio, per mezzo di Gesù, radunerà con lui coloro che sono morti."],
[4015,"Sulla parola del Signore infatti vi diciamo questo: noi, che viviamo e che saremo ancora in vita alla venuta del Signore, non avremo alcuna precedenza su quelli che sono morti."],
[4016,"Perché il Signore stesso, a un ordine, alla voce dell'arcangelo e al suono della tromba di Dio, discenderà dal cielo. E prima risorgeranno i morti in Cristo;"],
[4017,"quindi noi, che viviamo e che saremo ancora in vita, verremo rapiti insieme con loro nelle nubi, per andare incontro al Signore in alto, e così per sempre saremo con il Signore."],
[4018,"Confortatevi dunque a vicenda con queste parole."],
[5001,"Riguardo poi ai tempi e ai momenti, fratelli, non avete bisogno che ve ne scriva;"],
[5002,"infatti sapete bene che il giorno del Signore verrà come un ladro di notte."],
[5003,"E quando la gente dirà: \"C'è pace e sicurezza!\", allora d'improvviso la rovina li colpirà, come le doglie una donna incinta; e non potranno sfuggire."],
[5004,"Ma voi, fratelli, non siete nelle tenebre, cosicché quel giorno possa sorprendervi come un ladro."],
[5005,"Infatti siete tutti figli della luce e figli del giorno; noi non apparteniamo alla notte, né alle tenebre."],
[5006,"Non dormiamo dunque come gli altri, ma vigiliamo e siamo sobri."],
[5007,"Quelli che dormono, infatti, dormono di notte; e quelli che si ubriacano, di notte si ubriacano."],
[5008,"Noi invece, che apparteniamo al giorno, siamo sobri, vestiti con la corazza della fede e della carità, e avendo come elmo la speranza della salvezza."],
[5009,"Dio infatti non ci ha destinati alla sua ira, ma ad ottenere la salvezza per mezzo del Signore nostro Gesù Cristo."],
[5010,"Egli è morto per noi perché, sia che vegliamo sia che dormiamo, viviamo insieme con lui."],
[5011,"Perciò confortatevi a vicenda e siate di aiuto gli uni agli altri, come già fate."],
[5012,"Vi preghiamo, fratelli, di avere riguardo per quelli che faticano tra voi, che vi fanno da guida nel Signore e vi ammoniscono;"],
[5013,"trattateli con molto rispetto e amore, a motivo del loro lavoro. Vivete in pace tra voi."],
[5014,"Vi esortiamo, fratelli: ammonite chi è indisciplinato, fate coraggio a chi è scoraggiato, sostenete chi è debole, siate magnanimi con tutti."],
[5015,"Badate che nessuno renda male per male ad alcuno, ma cercate sempre il bene tra voi e con tutti."],
[5016,"Siate sempre lieti,"],
[5017,"pregate ininterrottamente,"],
[5018,"in ogni cosa rendete grazie: questa infatti è volontà di Dio in Cristo Gesù verso di voi."],
[5019,"Non spegnete lo Spirito,"],
[5020,"non disprezzate le profezie."],
[5021,"Vagliate ogni cosa e tenete ciò che è buono."],
[5022,"Astenetevi da ogni specie di male."],
[5023,"Il Dio della pace vi santifichi interamente, e tutta la vostra persona, spirito, anima e corpo, si conservi irreprensibile per la venuta del Signore nostro Gesù Cristo."],
[5024,"Degno di fede è colui che vi chiama: egli farà tutto questo!"],
[5025,"Fratelli, pregate anche per noi."],
[5026,"Salutate tutti i fratelli con il bacio santo."],
[5027,"Vi scongiuro, per il Signore, che questa lettera sia letta a tutti i fratelli."],
[5028,"La grazia del Signore nostro Gesù Cristo sia con voi."]
])
