Bib.ret([
[1001,"Ai fratelli Giudei dimoranti in Egitto, salute! I fratelli Giudei che sono a Gerusalemme e nella regione della Giudea augurano una pace sincera."],
[1002,"Dio voglia concedervi i suoi benefici e ricordarsi della sua alleanza con Abramo, Isacco e Giacobbe, suoi servi fedeli."],
[1003,"Doni a tutti voi un cuore per adorarlo e per compiere i suoi voleri con spirito generoso e animo pronto."],
[1004,"Vi apra il cuore alla sua legge e ai suoi precetti e vi conceda pace."],
[1005,"Esaudisca le vostre preghiere, si riconcili con voi e vi sia propizio e non vi abbandoni nell'ora dell'avversità."],
[1006,"Così ora noi qui preghiamo per voi."],
[1007,"Sotto il regno di Demetrio, nell'anno centosessantanove, noi Giudei vi abbiamo scritto: \"Nelle calamità e nell'angustia che si è abbattuta su di noi in questi anni, da quando Giasone e i suoi partigiani hanno tradito la terra santa e il regno,"],
[1008,"incendiando il portale e versando sangue innocente, noi abbiamo pregato il Signore e siamo stati esauditi; abbiamo offerto un sacrificio e del fior di farina, abbiamo acceso le lampade e presentato i pani\"."],
[1009,"Vi scriviamo per esortarvi a celebrare i giorni delle Capanne nel mese di Chisleu. L'anno centoottantotto."],
[1010,"I Giudei che sono a Gerusalemme e nella Giudea, il consiglio degli anziani e Giuda, ad Aristobulo, maestro del re Tolomeo, appartenente alla stirpe dei sacerdoti consacrati con l'unzione, e ai Giudei dell'Egitto salute e prosperità."],
[1011,"Da grandi pericoli salvati da Dio, lo ringraziamo molto, in quanto abbiamo potuto schierarci contro il re."],
[1012,"In realtà è lui che ha respinto quanti si erano schierati contro la santa città."],
[1013,"Infatti il loro capo, recatosi in Persia con il suo esercito creduto invincibile, fu fatto a pezzi nel tempio della dea Nanea, grazie a un tranello tesogli dai sacerdoti di Nanea."],
[1014,"Con il pretesto di celebrare le nozze con lei, Antioco con i suoi amici si era recato sul posto per prelevarne le immense ricchezze a titolo di dote."],
[1015,"Dopo che i sacerdoti del tempio di Nanea gliele ebbero mostrate, egli entrò con pochi nel recinto sacro e quelli, chiuso il tempio alle spalle di Antioco"],
[1016,"e aperta una porta segreta nel soffitto, scagliarono pietre e fulminarono il condottiero e i suoi. Poi, fattili a pezzi e tagliate le loro teste, le gettarono a quelli di fuori."],
[1017,"In tutto sia benedetto il nostro Dio, che ha consegnato alla morte i sacrileghi."],
[1018,"Apprestandoci a celebrare la purificazione del tempio il venticinque di Chisleu, abbiamo creduto necessario darvi qualche spiegazione, perché anche voi celebriate la festa delle Capanne e del fuoco, apparso quando Neemia offrì sacrifici dopo la ricostruzione del tempio e dell'altare."],
[1019,"Infatti, quando i nostri padri furono deportati in Persia, i pii sacerdoti di allora, preso il fuoco dall'altare, lo nascosero con cautela nella cavità di un pozzo che aveva il fondo asciutto e là lo misero al sicuro, in modo che il luogo rimanesse ignoto a tutti."],
[1020,"Dopo un buon numero di anni, quando piacque a Dio, Neemia, inviato dal re di Persia, mandò i discendenti di quei sacerdoti, che avevano nascosto il fuoco, a farne ricerca; quando però ci riferirono che non avevano trovato il fuoco, ma un'acqua spessa, comandò loro di attingerne e portarne."],
[1021,"Poi, quando furono pronte le offerte per i sacrifici, Neemia comandò ai sacerdoti di aspergere con quell'acqua la legna e quanto vi era sopra."],
[1022,"Appena questo avvenne e fu trascorso un po' di tempo, il sole, che prima era coperto da nubi, cominciò a risplendere e si accese un gran rogo, con grande meraviglia di tutti."],
[1023,"Mentre il sacrificio veniva consumato, i sacerdoti facevano la preghiera e con loro tutti gli altri: Gionata intonava, gli altri continuavano in coro insieme a Neemia."],
[1024,"La preghiera era formulata in questo modo: \"Signore, Signore Dio, creatore di tutto, tremendo e potente, giusto e misericordioso, tu solo re e buono,"],
[1025,"tu solo generoso, tu solo giusto e onnipotente ed eterno, che salvi Israele da ogni male, che hai fatto i nostri padri oggetto di elezione e santificazione,"],
[1026,"accetta il sacrificio offerto per tutto Israele, tuo popolo, custodisci la tua porzione e santificala."],
[1027,"Riunisci i nostri dispersi, libera quelli che sono schiavi in mano alle nazioni, guarda benigno i disprezzati e gli oltraggiati; sappiano così le nazioni che tu sei il nostro Dio."],
[1028,"Punisci quelli che ci opprimono e ci ingiuriano con superbia."],
[1029,"Trapianta il tuo popolo nel tuo luogo santo, come ha detto Mosè\"."],
[1030,"I sacerdoti a loro volta cantavano inni."],
[1031,"Poi, quando le vittime furono consumate, Neemia ordinò che il resto dell'acqua venisse versato sulle pietre più grosse."],
[1032,"Fatto questo, si accese una fiamma, la quale tuttavia fu assorbita dal bagliore del fuoco acceso sull'altare."],
[1033,"Quando il fatto fu divulgato e al re dei Persiani fu annunciato che, nel luogo dove i sacerdoti deportati avevano nascosto il fuoco, era comparsa acqua, con la quale poi i compagni di Neemia avevano purificato le cose necessarie al sacrificio,"],
[1034,"il re fece cingere il luogo e lo dichiarò sacro, dopo aver accertato il fatto."],
[1035,"Il re ricevette molti doni da quelli che aveva favorito e ne diede loro a sua volta."],
[1036,"I compagni di Neemia chiamarono questo liquido neftar, che significa purificazione; ma i più lo chiamano nafta."],
[2001,"Si trova scritto nei documenti che il profeta Geremia ordinò ai deportati di prendere del fuoco, come si è detto,"],
[2002,"e che il medesimo profeta, dando agli stessi deportati la legge, raccomandò loro di non dimenticarsi dei precetti del Signore e di non lasciarsi traviare nei loro pensieri, vedendo i simulacri d'oro e d'argento e il fasto di cui erano circondati,"],
[2003,"e che con altre simili espressioni li esortava a non ripudiare la legge nel loro cuore."],
[2004,"Si diceva anche nello scritto che il profeta, avuto un oracolo, ordinò che lo seguissero con la tenda e l'arca. Quando giunse presso il monte, dove Mosè era salito e aveva contemplato l'eredità di Dio,"],
[2005,"Geremia salì e trovò un vano a forma di caverna e vi introdusse la tenda, l'arca e l'altare dell'incenso e sbarrò l'ingresso."],
[2006,"Alcuni di quelli che lo seguivano tornarono poi per segnare la strada, ma non riuscirono a trovarla."],
[2007,"Geremia, quando venne a saperlo, li rimproverò dicendo: \"Il luogo deve restare ignoto, finché Dio non avrà riunito la totalità del popolo e si sarà mostrato propizio."],
[2008,"Allora il Signore mostrerà queste cose e si rivelerà la gloria del Signore e la nube, come appariva sopra Mosè, come già avvenne quando Salomone chiese che il luogo fosse solennemente santificato\"."],
[2009,"Si narrava anche come questi, dotato di sapienza, offrì il sacrificio per la dedicazione e il compimento del tempio."],
[2010,"E come Mosè aveva pregato il Signore ed era sceso il fuoco dal cielo a consumare le vittime immolate, così anche Salomone pregò e il fuoco sceso dal cielo consumò gli olocausti."],
[2011,"Mosè aveva detto: \"Poiché non è stata mangiata la vittima offerta per il peccato, essa è stata consumata\"."],
[2012,"Allo stesso modo anche Salomone celebrò gli otto giorni."],
[2013,"Si descrivevano le stesse cose nei documenti e nelle memorie di Neemia e come egli, fondata una biblioteca, avesse curato la raccolta dei libri dei re, dei profeti e di Davide e le lettere dei re relative alle offerte."],
[2014,"Anche Giuda ha raccolto tutti i libri andati dispersi per la guerra che abbiamo avuto e ora si trovano presso di noi."],
[2015,"Se ne avete bisogno, mandate qualcuno che ve li porti."],
[2016,"Vi abbiamo scritto mentre stiamo per celebrare la purificazione; farete ottima cosa se celebrerete anche voi questi giorni."],
[2017,"Poiché Dio ha salvato tutto il suo popolo e ha concesso a tutti l'eredità e il regno e il sacerdozio e la santificazione,"],
[2018,"come ha promesso mediante la legge, noi poniamo in Dio la speranza che egli ci usi presto misericordia e ci raduni nel luogo santo, da ogni regione posta sotto il cielo; egli infatti ci ha liberati da grandi mali e ha purificato questo luogo."],
[2019,"I fatti riguardanti Giuda Maccabeo e i suoi fratelli, la purificazione del grande tempio e la dedicazione dell'altare,"],
[2020,"come anche le guerre contro Antioco Epifane e il figlio di lui Eupatore,"],
[2021,"le manifestazioni venute dal cielo sopra coloro che si erano battuti con valore per il giudaismo, riuscendo in pochi a impadronirsi di tutta la regione e a scacciare una moltitudine di barbari,"],
[2022,"a riconquistare il tempio famoso in tutto il mondo, a liberare la città e a ristabilire le leggi che stavano per essere soppresse, quando il Signore si rese loro propizio con ogni benevolenza:"],
[2023,"questi fatti, narrati da Giasone di Cirene nel corso di cinque libri, cercheremo di riassumerli in uno solo."],
[2024,"Considerando infatti la caterva delle cifre e l'effettiva difficoltà per chi desidera inoltrarsi nei meandri delle narrazioni storiche, a causa della vastità della materia,"],
[2025,"ci siamo preoccupati di offrire diletto a coloro che amano leggere, facilità a quanti intendono fissare nella memoria, utilità a tutti gli eventuali lettori."],
[2026,"Per noi, certo, che ci siamo sobbarcati la fatica di questo riassunto, l'impresa non si presenta facile: ci vorranno sudori e veglie,"],
[2027,"così come non è facile preparare un banchetto e accontentare le esigenze altrui. Allo stesso modo per fare cosa gradita a molti, ci sarà dolce sopportare la fatica,"],
[2028,"lasciando all'autore la completa esposizione dei particolari, preoccupandoci invece di procedere secondo le linee essenziali di un riassunto."],
[2029,"Come infatti l'architetto di una casa nuova deve pensare a tutta la costruzione, mentre chi è incaricato di decorarla con pitture a encausto deve badare solo all'ornamentazione, così, penso, è per noi."],
[2030,"Certo, l'addentrarsi a spaziare nei fatti, investigandone i particolari, spetta all'ideatore dell'opera storica;"],
[2031,"ma a chi ne fa un riassunto si deve concedere di guardare alla brevità del discorso e di trascurare la completezza della trattazione."],
[2032,"Di qui dunque cominceremo la narrazione, senza nulla aggiungere a ciò che già abbiamo detto: sarebbe certo sciocco abbondare nei preamboli e abbreviare poi la narrazione storica."],
[3001,"Nel periodo in cui la città santa godeva completa pace e le leggi erano osservate perfettamente per la pietà del sommo sacerdote Onia e la sua avversione al male,"],
[3002,"gli stessi re avevano preso a onorare il luogo santo e a glorificare il tempio con doni insigni,"],
[3003,"al punto che anche Seleuco, re dell'Asia, provvedeva con le proprie entrate a tutte le spese riguardanti il servizio dei sacrifici."],
[3004,"Ma un certo Simone, della tribù di Bilga, nominato sovrintendente del tempio, venne a trovarsi in contrasto con il sommo sacerdote intorno all'amministrazione della città."],
[3005,"Non riuscendo a prevalere su Onia, si recò da Apollonio di Tarso, che in quel periodo era governatore della Celesiria e della Fenicia,"],
[3006,"e gli riferì che il tesoro di Gerusalemme era colmo di ricchezze immense, tanto che l'ammontare delle somme era incalcolabile e non serviva per le spese dei sacrifici; era quindi possibile trasferire tutto in potere del re."],
[3007,"Apollonio si incontrò con il re e gli riferì delle ricchezze a lui denunciate; quegli designò Eliodoro, l'incaricato d'affari, e lo inviò con l'ordine di effettuare la confisca delle suddette ricchezze."],
[3008,"Eliodoro si mise subito in viaggio, in apparenza per visitare le città della Celesiria e della Fenicia, in realtà per eseguire l'incarico del re."],
[3009,"Giunto a Gerusalemme e accolto con deferenza dal sommo sacerdote della città, espose l'informazione ricevuta e disse chiaro il motivo per cui era venuto; domandava poi se le cose stessero realmente così."],
[3010,"Il sommo sacerdote gli spiegò che i depositi erano delle vedove e degli orfani,"],
[3011,"che una parte era anche di Ircano, figlio di Tobia, persona di condizione assai elevata, che l'empio Simone andava denunciando la cosa a suo modo, ma complessivamente si trattava di quattrocento talenti d'argento e duecento d'oro e"],
[3012,"che era assolutamente impossibile permettere che fossero ingannati coloro che si erano fidati della santità del luogo e del carattere sacro e inviolabile di un tempio venerato in tutto il mondo."],
[3013,"Ma Eliodoro, in forza degli ordini ricevuti dal re, rispose recisamente che quelle ricchezze dovevano essere trasferite nell'erario del re."],
[3014,"Venne, in un giorno da lui stabilito, per farne un inventario, mentre tutta la città era in grande agitazione."],
[3015,"I sacerdoti, rivestiti degli abiti sacerdotali, si erano prostrati davanti all'altare ed elevavano suppliche al Cielo che aveva sancito la legge dei depositi, perché conservasse intatti questi beni a coloro che li avevano depositati."],
[3016,"Chi guardava l'aspetto del sommo sacerdote sentiva uno strazio al cuore, poiché il volto e il cambiamento di colore ne mostravano l'intimo tormento."],
[3017,"Tutta la sua persona era pervasa da paura e da un tremito del corpo, da cui appariva manifesta, a chi osservava, l'angoscia che aveva in cuore."],
[3018,"Dalle case uscivano in folla per una pubblica supplica, perché il luogo santo stava per essere violato."],
[3019,"Le donne, cinto sotto il petto il cilicio, riempivano le strade; anche le fanciulle, di solito ritirate, in parte accorrevano alle porte, in parte sulle mura, altre si sporgevano dalle finestre."],
[3020,"Tutte, con le mani protese verso il Cielo, moltiplicavano le suppliche."],
[3021,"Muoveva a compassione il pianto confuso della moltitudine e l'ansia tormentosa del sommo sacerdote."],
[3022,"Supplicavano il Signore onnipotente che volesse conservare intatti, in piena sicurezza, i depositi per coloro che li avevano consegnati."],
[3023,"Eliodoro però metteva ugualmente in esecuzione il suo programma."],
[3024,"Ma appena fu arrivato sul posto con gli armati, presso il tesoro, il Signore degli spiriti e di ogni potere si manifestò con un'apparizione così grande, che tutti i temerari che avevano osato entrare, colpiti dalla potenza di Dio, si trovarono stremati e atterriti."],
[3025,"Infatti apparve loro un cavallo, montato da un cavaliere terribile e rivestito di splendida bardatura, il quale si spinse con impeto contro Eliodoro e lo percosse con gli zoccoli anteriori, mentre il cavaliere appariva rivestito di armatura d'oro."],
[3026,"Davanti a lui comparvero, inoltre, altri due giovani dotati di grande forza, splendidi per bellezza e meravigliosi nell'abbigliamento, i quali, postisi ai due lati, lo flagellavano senza posa, infliggendogli numerose percosse."],
[3027,"In un attimo fu gettato a terra e si trovò immerso in una fitta oscurità. Allora i suoi lo afferrarono e lo misero su una barella."],
[3028,"Egli, che era entrato poco prima nella suddetta camera del tesoro con numeroso seguito e con tutta la guardia, fu portato via impotente ad aiutarsi, dopo aver sperimentato nel modo più evidente la potenza di Dio."],
[3029,"Così, mentre egli, prostrato dalla forza divina, giaceva senza voce e privo d'ogni speranza di salvezza,"],
[3030,"gli altri benedicevano il Signore, che aveva glorificato il suo luogo santo. Il tempio, che poco prima era pieno di trepidazione e confusione, dopo che il Signore onnipotente si fu manifestato, si riempì di gioia e letizia."],
[3031,"Subito alcuni compagni di Eliodoro pregarono Onia che supplicasse l'Altissimo e impetrasse la grazia della vita a costui che stava irrimediabilmente esalando l'ultimo respiro."],
[3032,"Il sommo sacerdote, temendo che il re avrebbe potuto sospettare che i Giudei avessero teso un tranello a Eliodoro, offrì un sacrificio per la salute di costui."],
[3033,"Mentre il sommo sacerdote compiva il rito propiziatorio, apparvero di nuovo a Eliodoro gli stessi giovani adorni delle stesse vesti, i quali, restando in piedi, dissero: \"Ringrazia ampiamente il sommo sacerdote Onia, per merito del quale il Signore ti ridà la vita."],
[3034,"Tu poi, che hai sperimentato i flagelli del Cielo, annuncia a tutti la grande potenza di Dio\". Dette queste parole, disparvero."],
[3035,"Eliodoro offrì un sacrificio al Signore e innalzò grandi preghiere a colui che gli aveva restituito la vita, poi si congedò da Onia e fece ritorno con il suo seguito dal re."],
[3036,"Egli testimoniava a tutti le opere del Dio grandissimo, che aveva visto con i suoi occhi."],
[3037,"Quando poi il re domandava a Eliodoro chi fosse adatto a essere inviato ancora una volta a Gerusalemme, rispondeva:"],
[3038,"\"Se hai qualcuno che ti è nemico o insidia il tuo governo, mandalo là e l'avrai indietro flagellato per bene, se pure ne uscirà salvo, perché in quel luogo c'è veramente una potenza divina."],
[3039,"Colui che ha la sua dimora nei cieli è custode e difensore di quel luogo, ed è pronto a percuotere e abbattere coloro che vi accedono con cattiva intenzione\"."],
[3040,"Così dunque si sono svolti i fatti relativi a Eliodoro e alla difesa del tesoro."],
[4001,"Il suddetto Simone, che si era fatto delatore dei beni e della patria, diffamava Onia, come se avesse percosso Eliodoro e fosse stato l'organizzatore dei disordini;"],
[4002,"osava definire nemico della cosa pubblica il benefattore della città, il protettore dei cittadini, il difensore delle leggi."],
[4003,"L'odio era giunto a tal punto che si compirono omicidi da parte di uno dei gregari di Simone;"],
[4004,"allora Onia, vedendo l'aggravarsi della rivalità e che Apollonio, figlio di Menesteo, governatore della Celesiria e della Fenicia, aizzava la perfidia di Simone,"],
[4005,"si recò dal re, non per fare la parte di accusatore dei suoi concittadini, ma per provvedere al bene comune del popolo e di ciascuno in particolare."],
[4006,"Vedeva infatti che, senza un provvedimento del re, era impossibile ristabilire la pace nella vita pubblica e che Simone non avrebbe messo freno alla sua pazzia."],
[4007,"Ma, essendo passato all'altra vita Seleuco e avendo preso le redini del governo Antioco, chiamato anche Epifane, Giasone, fratello di Onia, volle procurarsi con la corruzione il sommo sacerdozio"],
[4008,"e, in un incontro con il re, gli promise trecentosessanta talenti d'argento e altri ottanta talenti riscossi con un'altra entrata."],
[4009,"Oltre a questi prometteva di versargli altri centocinquanta talenti, se gli fosse stato concesso di erigere di sua autorità un ginnasio e un'efebia e di costituire una corporazione di Antiocheni a Gerusalemme."],
[4010,"Avendo il re acconsentito, egli, ottenuto il potere, fece subito assumere ai suoi connazionali uno stile di vita greco,"],
[4011,"annullando i favori concessi dai re ai Giudei per opera di Giovanni, padre di quell'Eupolemo che compì l'ambasciata presso i Romani per negoziare il patto di amicizia e di alleanza; quindi, abolite le istituzioni legittime, instaurò usanze perverse."],
[4012,"Intraprese con zelo a costruire un ginnasio, proprio ai piedi dell'acropoli, e indusse i giovani più distinti a portare il petaso."],
[4013,"Ciò significava raggiungere il colmo dell'ellenizzazione e passare completamente alla moda straniera, per l'eccessiva corruzione di Giasone, empio e non sommo sacerdote."],
[4014,"Perciò i sacerdoti non erano più premurosi del servizio all'altare, ma, disprezzando il tempio e trascurando i sacrifici, si affrettavano a partecipare agli spettacoli contrari alla legge nella palestra, appena dato il segnale del lancio del disco."],
[4015,"Così, tenendo in poco conto l'onore ricevuto in eredità dai loro padri, stimavano nobilissime le glorie elleniche."],
[4016,"Ma appunto per questo li sorprese una grave situazione ed ebbero quali avversari e punitori proprio coloro le cui istituzioni seguivano con zelo e ai quali cercavano di rassomigliare in tutto."],
[4017,"Non resta impunito il comportarsi empiamente contro le leggi divine, come dimostrerà chiaramente il successivo periodo storico."],
[4018,"Celebrandosi a Tiro i giochi quinquennali con l'intervento del re,"],
[4019,"lo scellerato Giasone inviò come rappresentanti alcuni Antiocheni di Gerusalemme, i quali portavano con sé trecento dracme d'argento per il sacrificio a Ercole; ma coloro che le portavano ritennero non conveniente usarle per il sacrificio, bensì impiegarle per altra spesa."],
[4020,"Così il denaro destinato al sacrificio a Ercole da parte del mandante, servì, per iniziativa dei latori, alla costruzione delle triremi."],
[4021,"Antioco, avendo mandato Apollonio, figlio di Menesteo, in Egitto per l'intronizzazione del re Filometore, venne a sapere che costui era diventato contrario al suo governo e quindi si preoccupò della sua sicurezza. Perciò si recò a Giaffa, poi mosse alla volta di Gerusalemme."],
[4022,"Fu accolto magnificamente da Giasone e dalla città e fu ricevuto con un corteo di fiaccole e acclamazioni. Così riprese la marcia militare verso la Fenicia."],
[4023,"Tre anni dopo, Giasone mandò Menelao, fratello del già menzionato Simone, a portare al re del denaro e a presentargli un memoriale su alcuni affari importanti."],
[4024,"Ma quello, fattosi presentare al re e avendolo ossequiato con un portamento da persona autorevole, si accaparrò il sommo sacerdozio, superando l'offerta di Giasone di trecento talenti d'argento."],
[4025,"Munito delle disposizioni del re, si presentò al ritorno senza avere nulla con sé che fosse degno del sommo sacerdozio, ma soltanto le manie di un tiranno unite alla ferocia di una belva."],
[4026,"Così Giasone, che aveva tradito il proprio fratello, fu tradito a sua volta da un altro e fu costretto a fuggire nel paese dell'Ammanitide."],
[4027,"Menelao si impadronì del potere, ma non s'interessò più del denaro promesso al re,"],
[4028,"sebbene gliene avesse fatto richiesta Sostrato, comandante dell'acropoli; questi infatti aveva l'incarico della riscossione dei tributi. Per questo motivo tutti e due furono convocati dal re."],
[4029,"Menelao lasciò come sostituto nel sommo sacerdozio Lisimaco, suo fratello; Sostrato lasciò Cratete, capo dei Ciprioti."],
[4030,"Mentre così stavano le cose, le città di Tarso e di Mallo si ribellarono, perché erano state date in dono ad Antiochide, concubina del re."],
[4031,"Il re partì in fretta per riportare all'ordine la situazione, lasciando come luogotenente Andronico, uno dei suoi dignitari."],
[4032,"Menelao allora, pensando di aver trovato l'occasione buona, sottrasse alcuni oggetti d'oro del tempio e ne fece omaggio ad Andronico; altri poi riuscì a venderli a Tiro e nelle città vicine."],
[4033,"Ma Onia lo biasimò, dopo essersi accertato della cosa ed essersi rifugiato in una località inviolabile a Dafne, situata presso Antiochia."],
[4034,"Per questo Menelao, incontratosi in segreto con Andronico, lo sollecitò a sopprimere Onia. Quello, recatosi da Onia e ottenutane con inganno la fiducia, dandogli la destra con giuramento lo persuase, sebbene non avesse allontanato ogni sospetto, a uscire dall'asilo e subito lo uccise senza alcun rispetto per la giustizia."],
[4035,"Per questo fatto non solo i Giudei, ma anche molti di altre nazioni restarono indignati e afflitti per l'empia uccisione di quell'uomo."],
[4036,"Quando il re tornò dalle località della Cilicia, si presentarono a lui i Giudei della città, insieme con i Greci che condividevano l'esecrazione per l'uccisione arbitraria di Onia."],
[4037,"Antioco fu profondamente rattristato e, preso da compassione, pianse per la saggezza e la grande prudenza del defunto."],
[4038,"Poi, acceso di sdegno, tolse subito la porpora ad Andronico, ne stracciò le vesti e lo condusse attraverso tutta la città proprio fino al luogo dove egli aveva sacrilegamente ucciso Onia e lì stesso eliminò dal mondo quell'assassino. Così il Signore gli rese il meritato castigo."],
[4039,"Intanto, poiché erano avvenuti molti furti sacrileghi in città da parte di Lisimaco, d'accordo con Menelao, e se ne era sparsa la voce al di fuori, il popolo si ribellò a Lisimaco, quando già molti oggetti d'oro erano stati portati via."],
[4040,"La folla era eccitata e piena di furore. Lisimaco allora, armati circa tremila uomini, diede inizio ad atti di violenza, sotto la guida di un certo Aurano, già avanzato in età e non meno in stoltezza."],
[4041,"Ma quelli, appena si accorsero dell'aggressione di Lisimaco, alcuni afferrarono pietre, altri grossi bastoni, altri ancora raccolsero a manciate la polvere sul posto e si gettarono contro quelli di Lisimaco."],
[4042,"A questo modo ne ferirono molti, ne abbatterono alcuni, costrinsero tutti alla fuga, misero a morte lo stesso saccheggiatore del tempio presso la camera del tesoro."],
[4043,"Per questi fatti fu intentato un processo contro Menelao."],
[4044,"Venuto il re a Tiro, i tre uomini mandati dal consiglio degli anziani esposero davanti a lui l'atto di accusa."],
[4045,"Menelao, ormai sul punto di essere abbandonato, promise una buona quantità di denaro a Tolomeo, figlio di Dorimene, perché persuadesse il re."],
[4046,"Tolomeo invitò il re sotto un portico, come per fargli prendere il fresco, e gli fece mutare parere."],
[4047,"Così il re prosciolse dalle accuse Menelao, causa di tutto il male, e contro quegli infelici che, se avessero discusso la causa anche presso gli Sciti sarebbero stati prosciolti come innocenti, decretò la pena di morte."],
[4048,"Così senza dilazione subirono l'ingiusta pena coloro che avevano difeso la città, il popolo e le suppellettili sacre."],
[4049,"Gli stessi cittadini di Tiro, indignati per questo fatto, provvidero generosamente quanto occorreva per la loro sepoltura."],
[4050,"Menelao invece, per la cupidigia dei potenti, rimase al potere, crescendo in malvagità e facendosi grande traditore dei concittadini."],
[5001,"In questo tempo Antioco decise la seconda spedizione in Egitto."],
[5002,"Accadde allora che sopra tutta la città, per circa quaranta giorni, si vedessero cavalieri che correvano per l'aria con vesti d'oro, armati di lance roteanti e di spade sguainate,"],
[5003,"schiere di cavalieri disposti a battaglia, attacchi e scontri vicendevoli, trambusto di scudi, selve di aste, lanci di frecce, bagliori di bardature d'oro e corazze d'ogni specie."],
[5004,"Tutti, perciò, pregavano perché l'apparizione fosse di buon augurio."],
[5005,"Essendosi poi diffusa la falsa notizia che Antioco era passato all'altra vita, Giasone, prendendo con sé non meno di mille uomini, all'improvviso sferrò un assalto alla città. Si accese la lotta sulle mura e, quando la città era ormai presa, Menelao si rifugiò nell'acropoli."],
[5006,"Giasone fece strage dei propri concittadini senza pietà, non considerando che un successo contro i propri connazionali era il massimo insuccesso, credendo invece di riportare trionfi sui nemici e non sulla propria gente."],
[5007,"Non riuscì però a impadronirsi del potere e alla fine, conscio della vergogna del tradimento, corse di nuovo a rifugiarsi nell'Ammanitide."],
[5008,"Alla fine incontrò una pessima sorte. Accusato presso Areta, re degli Arabi, fuggendo di città in città, perseguitato da tutti e odiato come traditore delle leggi, considerato con orrore come carnefice della patria e dei concittadini, andò a finire in Egitto."],
[5009,"Colui che aveva mandato in esilio numerosi figli della sua patria morì poi presso gli Spartani, fra i quali si era ridotto quasi a cercare riparo in nome della comunanza di stirpe."],
[5010,"E ancora, colui che aveva lasciato insepolta una moltitudine di gente, finì non pianto da alcuno, privo di esequie ed escluso dal sepolcro dei suoi padri."],
[5011,"Quando il re venne a conoscenza di questi fatti, concluse che la Giudea stava ribellandosi. Perciò, tornando dall'Egitto, furioso come una belva, prese la città con le armi"],
[5012,"e diede ordine ai soldati di colpire senza pietà quanti incontravano e di trucidare quelli che si rifugiavano nelle case."],
[5013,"Vi fu massacro di giovani e di vecchi, sterminio di uomini, di donne e di fanciulli, stragi di fanciulle e di bambini."],
[5014,"In tutti quei tre giorni vi furono ottantamila vittime: quarantamila nel corso della lotta, e non meno degli uccisi furono quelli venduti schiavi."],
[5015,"Non sazio di questo, Antioco osò entrare nel tempio più santo di tutta la terra, avendo a guida quel Menelao che si era fatto traditore delle leggi e della patria;"],
[5016,"afferrò con mani impure gli arredi sacri, e saccheggiò con le sue mani sacrileghe quanto dagli altri re era stato deposto per l'abbellimento e lo splendore del luogo e per segno d'onore."],
[5017,"Antioco si inorgoglì, non comprendendo che il Signore si era sdegnato per breve tempo a causa dei peccati degli abitanti della città e perciò quel luogo era stato abbandonato."],
[5018,"Se essi non si fossero trovati implicati in molti peccati, come era avvenuto per Eliodoro, mandato dal re Seleuco a ispezionare la camera del tesoro, anche egli, appena giunto, sarebbe stato subito flagellato e distolto dalla sua audacia."],
[5019,"Ma il Signore aveva eletto non già il popolo a causa di quel luogo, ma quel luogo a causa del popolo."],
[5020,"Perciò anche il luogo, dopo essere stato coinvolto nelle sventure piombate sul popolo, da ultimo ne condivise i benefici; esso, che per l'ira dell'Onnipotente aveva sperimentato l'abbandono, per la riconciliazione del grande Sovrano fu ripristinato in tutta la sua gloria."],
[5021,"Antioco dunque, portando via dal tempio milleottocento talenti d'argento, fece ritorno in fretta ad Antiochia, convinto nella sua superbia di aver reso navigabile la terra e transitabile il mare, per effetto del suo orgoglio."],
[5022,"Egli lasciò sovrintendenti per opprimere la stirpe: a Gerusalemme Filippo, frigio di origine, ma nei modi più barbaro di colui che l'aveva istituito nella carica,"],
[5023,"e sul Garizim Andronico; oltre a loro Menelao, il quale più degli altri era altezzoso con i concittadini, nutrendo un'ostilità dichiarata contro i Giudei."],
[5024,"Mandò poi il misarca Apollonio, con un esercito di ventiduemila uomini, con l'ordine di uccidere quanti erano in età adulta e di vendere le donne e i fanciulli."],
[5025,"Costui, giunto a Gerusalemme e fingendo intenzioni pacifiche, si tenne quieto fino al giorno sacro del sabato. Allora, sorpresi i Giudei in riposo, comandò ai suoi una parata militare"],
[5026,"e trucidò quanti uscivano per assistere alla festa; poi, irrompendo con gli armati in città, mise a morte un gran numero di persone."],
[5027,"Ma Giuda, detto anche Maccabeo, che faceva parte di un gruppo di dieci, si ritirò nel deserto, vivendo tra le montagne alla maniera delle fiere insieme a quelli che erano con lui; cibandosi di erbe, resistevano per non aver parte nella contaminazione."],
[6001,"Non molto tempo dopo, il re inviò un vecchio ateniese per costringere i Giudei ad allontanarsi dalle leggi dei padri e a non governarsi più secondo le leggi di Dio,"],
[6002,"e inoltre per profanare il tempio di Gerusalemme e dedicare questo a Giove Olimpio e quello sul Garizim a Giove Ospitale, come si confaceva agli abitanti del luogo."],
[6003,"Grave e intollerabile per tutti era il dilagare del male."],
[6004,"Il tempio infatti era pieno delle dissolutezze e delle gozzoviglie dei pagani, che si divertivano con le prostitute ed entro i sacri portici si univano a donne, introducendovi pratiche sconvenienti."],
[6005,"L'altare era colmo di cose detestabili, vietate dalle leggi."],
[6006,"Non era più possibile né osservare il sabato né celebrare le feste dei padri né semplicemente dichiarare di essere giudeo."],
[6007,"Si era trascinati con aspra violenza ogni mese, nel giorno natalizio del re, ad assistere al sacrificio e, quando giungevano le feste dionisiache, si era costretti a sfilare in onore di Dioniso coronati di edera."],
[6008,"Su istigazione dei cittadini di Tolemaide, fu poi emanato un decreto per le vicine città ellenistiche, perché anch'esse seguissero le stesse disposizioni contro i Giudei, li costringessero a mangiare le carni dei sacrifici"],
[6009,"e mettessero a morte quanti non accettavano di aderire alle usanze greche. Si poteva allora capire quale tribolazione incombesse."],
[6010,"Furono denunciate, per esempio, due donne che avevano circonciso i figli: appesero i bambini alle loro mammelle, e dopo averle condotte in giro pubblicamente per la città, le precipitarono dalle mura."],
[6011,"Altri che si erano raccolti insieme nelle vicine caverne per celebrare il sabato, denunciati a Filippo, vi furono bruciati dentro, perché essi avevano riluttanza a difendersi per il rispetto di quel giorno santissimo."],
[6012,"Io prego coloro che avranno in mano questo libro di non turbarsi per queste disgrazie e di pensare che i castighi non vengono per la distruzione, ma per la correzione del nostro popolo."],
[6013,"Quindi è veramente segno di grande benevolenza il fatto che agli empi non è data libertà per molto tempo, ma subito incappano nei castighi."],
[6014,"Poiché il Signore non si propone di agire con noi come fa con le altre nazioni, attendendo pazientemente il tempo di punirle, quando siano giunte al colmo dei loro peccati;"],
[6015,"e questo per non doverci punire alla fine, quando fossimo giunti all'estremo delle nostre colpe."],
[6016,"Perciò egli non ci toglie mai la sua misericordia, ma, correggendoci con le sventure, non abbandona il suo popolo."],
[6017,"Ciò sia detto da noi solo per ricordare questa verità. Dobbiamo ora tornare alla narrazione."],
[6018,"Un tale Eleazaro, uno degli scribi più stimati, uomo già avanti negli anni e molto dignitoso nell'aspetto della persona, veniva costretto ad aprire la bocca e a ingoiare carne suina."],
[6019,"Ma egli, preferendo una morte gloriosa a una vita ignominiosa, s'incamminò volontariamente al supplizio,"],
[6020,"sputando il boccone e comportandosi come conviene a coloro che sono pronti ad allontanarsi da quanto non è lecito gustare per attaccamento alla vita."],
[6021,"Quelli che erano incaricati dell'illecito banchetto sacrificale, in nome della familiarità di antica data che avevano con quest'uomo, lo tirarono in disparte e lo pregarono di prendere la carne di cui era lecito cibarsi, preparata da lui stesso, e fingere di mangiare le carni sacrificate imposte dal re,"],
[6022,"perché, agendo a questo modo, sarebbe sfuggito alla morte e avrebbe trovato umanità in nome dell'antica amicizia che aveva con loro."],
[6023,"Ma egli, facendo un nobile ragionamento, degno della sua età e del prestigio della vecchiaia, della raggiunta veneranda canizie e della condotta irreprensibile tenuta fin da fanciullo, ma specialmente delle sante leggi stabilite da Dio, rispose subito dicendo che lo mandassero pure alla morte."],
[6024,"\"Poiché - egli diceva - non è affatto degno della nostra età fingere, con il pericolo che molti giovani, pensando che a novant'anni Eleazaro sia passato alle usanze straniere,"],
[6025,"a loro volta, per colpa della mia finzione, per appena un po' più di vita, si perdano per causa mia e io procuri così disonore e macchia alla mia vecchiaia."],
[6026,"Infatti, anche se ora mi sottraessi al castigo degli uomini, non potrei sfuggire, né da vivo né da morto, alle mani dell'Onnipotente."],
[6027,"Perciò, abbandonando ora da forte questa vita, mi mostrerò degno della mia età"],
[6028,"e lascerò ai giovani un nobile esempio, perché sappiano affrontare la morte prontamente e nobilmente per le sante e venerande leggi\". Dette queste parole, si avviò prontamente al supplizio."],
[6029,"Quelli che ve lo trascinavano, cambiarono la benevolenza di poco prima in avversione, ritenendo che le parole da lui pronunciate fossero una pazzia."],
[6030,"Mentre stava per morire sotto i colpi, disse tra i gemiti: \"Il Signore, che possiede una santa scienza, sa bene che, potendo sfuggire alla morte, soffro nel corpo atroci dolori sotto i flagelli, ma nell'anima sopporto volentieri tutto questo per il timore di lui\"."],
[6031,"In tal modo egli morì, lasciando la sua morte come esempio di nobiltà e ricordo di virtù non solo ai giovani, ma anche alla grande maggioranza della nazione."],
[7001,"Ci fu anche il caso di sette fratelli che, presi insieme alla loro madre, furono costretti dal re, a forza di flagelli e nerbate, a cibarsi di carni suine proibite."],
[7002,"Uno di loro, facendosi interprete di tutti, disse: \"Che cosa cerchi o vuoi sapere da noi? Siamo pronti a morire piuttosto che trasgredire le leggi dei padri\"."],
[7003,"Allora il re irritato comandò di mettere al fuoco teglie e caldaie."],
[7004,"Appena queste divennero roventi, il re comandò di tagliare la lingua a quello che si era fatto loro portavoce, di scorticarlo e tagliargli le estremità, sotto gli occhi degli altri fratelli e della madre."],
[7005,"Dopo averlo mutilato di tutte le membra, comandò di accostarlo al fuoco e di arrostirlo quando ancora respirava. Mentre il vapore si spandeva largamente tutto intorno alla teglia, gli altri si esortavano a vicenda con la loro madre a morire da forti, dicendo:"],
[7006,"\"Il Signore Dio ci vede dall'alto e certamente avrà pietà di noi, come dichiarò Mosè nel canto che protesta apertamente con queste parole: \"E dei suoi servi avrà compassione\"\"."],
[7007,"Venuto meno il primo, allo stesso modo esponevano allo scherno il secondo e, strappatagli la pelle del capo con i capelli, gli domandavano: \"Sei disposto a mangiare, prima che il tuo corpo venga straziato in ogni suo membro?\"."],
[7008,"Egli, rispondendo nella lingua dei padri, protestava: \"No\". Perciò anch'egli subì gli stessi tormenti del primo."],
[7009,"Giunto all'ultimo respiro, disse: \"Tu, o scellerato, ci elimini dalla vita presente, ma il re dell'universo, dopo che saremo morti per le sue leggi, ci risusciterà a vita nuova ed eterna\"."],
[7010,"Dopo costui fu torturato il terzo, che alla loro richiesta mise fuori prontamente la lingua e stese con coraggio le mani,"],
[7011,"dicendo dignitosamente: \"Dal Cielo ho queste membra e per le sue leggi le disprezzo, perché da lui spero di riaverle di nuovo\"."],
[7012,"Lo stesso re e i suoi dignitari rimasero colpiti dalla fierezza di questo giovane, che non teneva in nessun conto le torture."],
[7013,"Fatto morire anche questo, si misero a straziare il quarto con gli stessi tormenti."],
[7014,"Ridotto in fin di vita, egli diceva: \"È preferibile morire per mano degli uomini, quando da Dio si ha la speranza di essere da lui di nuovo risuscitati; ma per te non ci sarà davvero risurrezione per la vita\"."],
[7015,"Subito dopo condussero il quinto e lo torturarono."],
[7016,"Ma egli, guardando il re, diceva: \"Tu hai potere sugli uomini e, sebbene mortale, fai quanto ti piace; ma non credere che il nostro popolo sia stato abbandonato da Dio."],
[7017,"Quanto a te, aspetta e vedrai la grandezza della sua forza, come strazierà te e la tua discendenza\"."],
[7018,"Dopo di lui presero il sesto che, mentre stava per morire, disse: \"Non illuderti stoltamente. Noi soffriamo queste cose per causa nostra, perché abbiamo peccato contro il nostro Dio; perciò ci succedono cose che muovono a meraviglia."],
[7019,"Ma tu non credere di andare impunito, dopo aver osato combattere contro Dio\"."],
[7020,"Soprattutto la madre era ammirevole e degna di gloriosa memoria, perché, vedendo morire sette figli in un solo giorno, sopportava tutto serenamente per le speranze poste nel Signore."],
[7021,"Esortava ciascuno di loro nella lingua dei padri, piena di nobili sentimenti e, temprando la tenerezza femminile con un coraggio virile, diceva loro:"],
[7022,"\"Non so come siate apparsi nel mio seno; non io vi ho dato il respiro e la vita, né io ho dato forma alle membra di ciascuno di voi."],
[7023,"Senza dubbio il Creatore dell'universo, che ha plasmato all'origine l'uomo e ha provveduto alla generazione di tutti, per la sua misericordia vi restituirà di nuovo il respiro e la vita, poiché voi ora per le sue leggi non vi preoccupate di voi stessi\"."],
[7024,"Antioco, credendosi disprezzato e sospettando che quel linguaggio fosse di scherno, esortava il più giovane che era ancora vivo; e non solo a parole, ma con giuramenti prometteva che l'avrebbe fatto ricco e molto felice, se avesse abbandonato le tradizioni dei padri, e che l'avrebbe fatto suo amico e gli avrebbe affidato alti incarichi."],
[7025,"Ma poiché il giovane non badava per nulla a queste parole, il re, chiamata la madre, la esortava a farsi consigliera di salvezza per il ragazzo."],
[7026,"Esortata a lungo, ella accettò di persuadere il figlio;"],
[7027,"chinatasi su di lui, beffandosi del crudele tiranno, disse nella lingua dei padri: \"Figlio, abbi pietà di me, che ti ho portato in seno nove mesi, che ti ho allattato per tre anni, ti ho allevato, ti ho condotto a questa età e ti ho dato il nutrimento."],
[7028,"Ti scongiuro, figlio, contempla il cielo e la terra, osserva quanto vi è in essi e sappi che Dio li ha fatti non da cose preesistenti; tale è anche l'origine del genere umano."],
[7029,"Non temere questo carnefice, ma, mostrandoti degno dei tuoi fratelli, accetta la morte, perché io ti possa riavere insieme con i tuoi fratelli nel giorno della misericordia\"."],
[7030,"Mentre lei ancora parlava, il giovane disse: \"Che aspettate? Non obbedisco al comando del re, ma ascolto il comando della legge che è stata data ai nostri padri per mezzo di Mosè."],
[7031,"Tu però, che ti sei fatto autore di ogni male contro gli Ebrei, non sfuggirai alle mani di Dio."],
[7032,"Noi, in realtà, soffriamo per i nostri peccati."],
[7033,"Se ora per nostro castigo e correzione il Signore vivente per breve tempo si è adirato con noi, di nuovo si riconcilierà con i suoi servi."],
[7034,"Ma tu, o sacrilego e il più scellerato di tutti gli uomini, non esaltarti invano, alimentando segrete speranze, mentre alzi la mano contro i figli del Cielo,"],
[7035,"perché non sei ancora al sicuro dal giudizio del Dio onnipotente che vede tutto."],
[7036,"Già ora i nostri fratelli, che hanno sopportato un breve tormento, per una vita eterna sono entrati in alleanza con Dio. Tu invece subirai nel giudizio di Dio il giusto castigo della tua superbia."],
[7037,"Anch'io, come già i miei fratelli, offro il corpo e la vita per le leggi dei padri, supplicando Dio che presto si mostri placato al suo popolo e che tu, fra dure prove e flagelli, debba confessare che egli solo è Dio;"],
[7038,"con me invece e con i miei fratelli possa arrestarsi l'ira dell'Onnipotente, giustamente attirata su tutta la nostra stirpe\"."],
[7039,"Il re, divenuto furibondo, si sfogò su di lui più crudelmente che sugli altri, sentendosi invelenito dallo scherno."],
[7040,"Così anche costui passò all'altra vita puro, confidando pienamente nel Signore."],
[7041,"Ultima dopo i figli, anche la madre incontrò la morte."],
[7042,"Ma sia sufficiente quanto abbiamo esposto circa i pasti sacrificali e le eccessive crudeltà."],
[8001,"Intanto Giuda Maccabeo e i suoi compagni, passando di nascosto nei villaggi, chiamavano a sé i loro congiunti e, raccolti quanti erano rimasti fedeli al giudaismo, misero insieme circa seimila uomini."],
[8002,"Alzarono allora suppliche al Signore, perché volgesse lo sguardo al popolo da tutti calpestato, avesse pietà del tempio profanato da uomini empi,"],
[8003,"usasse misericordia alla città devastata e prossima a essere rasa al suolo, porgesse orecchio al sangue che gridava al suo cospetto,"],
[8004,"non dimenticasse l'iniquo sterminio di fanciulli innocenti e le bestemmie pronunciate contro il suo nome e mostrasse il suo sdegno contro la malvagità."],
[8005,"Il Maccabeo, postosi a capo del gruppo, divenne ormai invincibile per le nazioni, mentre l'ira del Signore si volgeva in misericordia."],
[8006,"Piombando all'improvviso su città e villaggi, li incendiava e, impadronendosi delle posizioni più opportune, metteva in fuga non pochi nemici,"],
[8007,"scegliendo di preferenza la notte come tempo favorevole a queste incursioni. La fama del suo valore risuonava dovunque."],
[8008,"Filippo, osservando che quest'uomo a poco a poco otteneva successi e progrediva continuamente, scrisse a Tolomeo, stratega della Celesiria e della Fenicia, perché intervenisse a favore degli interessi del re."],
[8009,"Quello incaricò subito Nicanore, figlio di Patroclo, uno dei primi amici del re, e, affidando ai suoi ordini truppe di uomini di ogni nazione in numero non inferiore a ventimila, lo inviò a sterminare totalmente la stirpe dei Giudei. Gli associò anche Gorgia, un generale di professione, esperto in tattica militare."],
[8010,"Nicanore si propose di pagare il tributo che il re doveva ai Romani, che era di duemila talenti, con la vendita degli schiavi giudei."],
[8011,"Anzi, spedì senz'altro alle città della costa l'invito ad acquistare schiavi giudei, promettendo di barattare novanta prigionieri per un talento; non immaginava che la vendetta dell'Onnipotente stava per piombare su di lui."],
[8012,"Giuda fu informato della spedizione di Nicanore e annunciò ai suoi uomini l'avvicinarsi dell'esercito."],
[8013,"Allora i paurosi e quanti non confidavano nella giustizia di Dio fuggirono, portandosi lontano dalla zona."],
[8014,"Altri vendevano tutte le cose che erano loro rimaste e insieme pregavano il Signore di salvare coloro che l'empio Nicanore aveva venduto prima ancora dello scontro:"],
[8015,"questo, se non per loro merito, almeno per l'alleanza con i loro padri e per riguardo al suo augusto e glorioso nome invocato sopra di loro."],
[8016,"Il Maccabeo poi, radunati i suoi uomini in numero di seimila, li esortava a non scoraggiarsi davanti ai nemici, né a lasciarsi prendere da timore di fronte alla moltitudine delle nazioni venute ingiustamente contro di loro, ma a combattere da forti,"],
[8017,"tenendo davanti agli occhi le violenze che quelli avevano iniquamente perpetrato contro il luogo santo, lo strazio della città vilipesa e ancora la soppressione dell'ordinamento politico degli antenati."],
[8018,"\"Costoro - disse - confidano nelle armi e così pure nel loro ardire; noi confidiamo nel Dio onnipotente, capace di abbattere quanti vengono contro di lui e il mondo intero con un solo cenno\"."],
[8019,"Ricordò loro distintamente gli interventi a favore dei loro antenati, quello contro Sennacherib, quando morirono centoottantacinquemila uomini,"],
[8020,"e quello avvenuto in Babilonia nella battaglia contro i Galati, quando tutti si trovarono in necessità, ottomila insieme con quattromila Macedoni: mentre i Macedoni soccombevano, gli ottomila sterminarono centoventimila uomini con l'aiuto venuto loro dal Cielo, ricevendone un grande vantaggio."],
[8021,"Con queste parole li rese coraggiosi e pronti a morire per le leggi e per la patria. Poi divise in qualche modo l'esercito in quattro parti"],
[8022,"e mise al comando di ogni schieramento i suoi fratelli Simone, Giuseppe e Gionata, affidando a ciascuno millecinquecento uomini."],
[8023,"Vi aggiunse Eleazaro, lesse poi in pubblico il libro sacro e, data la parola d'ordine \"Aiuto di Dio\", si pose lui stesso a capo del primo reparto e attaccò Nicanore."],
[8024,"L'Onnipotente si fece loro alleato ed essi uccisero più di novemila nemici, ferirono e mutilarono nelle membra la maggior parte dell'esercito di Nicanore e costrinsero tutti a fuggire."],
[8025,"Si impadronirono dei beni di quanti erano convenuti per il loro acquisto; inseguirono poi i nemici per un lungo tratto, ma impediti dall'ora tarda tornarono indietro."],
[8026,"Era la vigilia del sabato e per questa ragione non protrassero l'inseguimento."],
[8027,"Raccolte le armi dei nemici e tolte loro le spoglie, passarono il sabato benedicendo incessantemente e ringraziando il Signore che li aveva salvati in quel giorno, cominciando ad aver misericordia per loro."],
[8028,"Dopo il sabato distribuirono parte delle spoglie ai danneggiati, alle vedove, agli orfani; il resto se lo divisero tra loro e i loro figli."],
[8029,"Compiute queste cose, fecero una supplica in comune, scongiurando il Signore misericordioso di riconciliarsi pienamente con i suoi servi."],
[8030,"Poi, si scontrarono anche con gli uomini di Timoteo e Bacchide e ne uccisero più di ventimila, si impadronirono saldamente di alte fortezze e divisero l'abbondante bottino in parti uguali tra loro, i danneggiati, gli orfani, le vedove e anche i vecchi."],
[8031,"Raccolte le loro armi, con molta cura riposero il tutto in luoghi opportuni e portarono il resto del bottino a Gerusalemme."],
[8032,"Uccisero anche l'ufficiale preposto alle guardie di Timoteo, uomo scelleratissimo, che aveva fatto soffrire molto i Giudei."],
[8033,"Mentre si celebrava la vittoria in patria, bruciarono coloro che avevano incendiato le sacre porte, compreso Callistene, che si era rifugiato in una casupola; ricevette così una degna ricompensa per la sua empietà."],
[8034,"Il tristissimo Nicanore, colui che aveva convocato mille mercanti per la vendita dei Giudei,"],
[8035,"umiliato, con l'aiuto del Signore, da coloro che erano da lui ritenuti insignificanti, deposta la splendida veste, fuggiasco come uno schiavo attraverso la campagna e ormai privo di tutto, arrivò ad Antiochia, già troppo fortunato per essere sopravvissuto alla rovina dell'esercito."],
[8036,"Così, chi si riprometteva di assicurare il tributo per i Romani con la vendita dei prigionieri a Gerusalemme, confessava ora che i Giudei avevano un difensore e che i Giudei per questa ragione erano invincibili, perché obbedivano alle leggi da lui stabilite."],
[9001,"In quel periodo Antioco ritornò con disonore dalle regioni della Persia."],
[9002,"Infatti egli era giunto nella città chiamata Persepoli e si era accinto a depredare il tempio e a impadronirsi della città; ma i cittadini, ricorsi in massa all'aiuto delle armi, lo respinsero e accadde così che Antioco, messo in fuga dagli abitanti, dovette ritirarsi vergognosamente."],
[9003,"Mentre si trovava presso Ecbatana, gli giunse notizia di ciò che era accaduto a Nicanore e agli uomini di Timoteo."],
[9004,"Mosso da gran furore, pensava di sfogarsi sui Giudei anche per lo smacco inflittogli da coloro che lo avevano messo in fuga. Perciò diede ordine al cocchiere di compiere il viaggio spingendo i cavalli senza sosta; ma incombeva ormai su di lui il giudizio del Cielo. Così diceva nella sua superbia: \"Farò di Gerusalemme un cimitero di Giudei, appena vi sarò giunto\"."],
[9005,"Ma il Signore che tutto vede, il Dio d'Israele, lo colpì con piaga insanabile e invisibile. Aveva appena terminato quella frase, quando lo colpì un insopportabile dolore alle viscere e terribili spasimi intestinali,"],
[9006,"ben meritati da colui che aveva straziato le viscere altrui con molti e strani generi di torture."],
[9007,"Ma egli non desisteva affatto dalla sua alterigia, anzi era pieno ancora di superbia, spirando fuoco d'ira contro i Giudei, e comandando di accelerare la corsa. Gli capitò perciò di cadere dal carro in corsa tumultuosa e di rovinarsi tutte le membra del corpo nella violenta caduta."],
[9008,"Colui che poco prima, nella sua sovrumana arroganza, pensava di comandare ai flutti del mare, e credeva di pesare sulla bilancia le cime dei monti, ora, gettato a terra, doveva farsi portare in lettiga, rendendo a tutti manifesta la potenza di Dio,"],
[9009,"a tal punto che nel corpo di quell'empio si formavano i vermi e, mentre era ancora vivo, le sue carni, fra spasimi e dolori, cadevano a brandelli e l'esercito era tutto nauseato dal fetore e dal marciume di lui."],
[9010,"Colui che poco prima credeva di toccare gli astri del cielo, ora nessuno poteva sopportarlo per l'intollerabile intensità del fetore."],
[9011,"Allora finalmente, malconcio a quel modo, incominciò a deporre gran parte della sua superbia e ad avviarsi al ravvedimento per effetto del divino flagello, mentre senza tregua era lacerato dai dolori."],
[9012,"Non potendo più sopportare il suo proprio fetore, disse: \"È giusto sottomettersi a Dio e non pretendere di essere uguale a Dio, quando si è mortali!\"."],
[9013,"Quindi quello scellerato si mise a pregare quel Signore che ormai non avrebbe più avuto misericordia di lui, e diceva"],
[9014,"che avrebbe dichiarato libera la città santa, che prima si affrettava a raggiungere per raderla al suolo e farne un cimitero."],
[9015,"Diceva inoltre che avrebbe reso pari agli Ateniesi tutti i Giudei, che prima aveva stabilito di non degnare neppure della sepoltura, ma di gettare in pasto alle fiere insieme con i loro bambini,"],
[9016,"e che avrebbe adornato con magnifici doni votivi il sacro tempio, che prima aveva saccheggiato, e avrebbe restituito in numero ancora più grande tutti gli arredi sacri e avrebbe provveduto con le proprie entrate ai contributi fissati per i sacrifici."],
[9017,"Prometteva, infine, che si sarebbe fatto Giudeo e si sarebbe recato in ogni luogo abitato per annunciare la potenza di Dio."],
[9018,"Ma poiché i dolori non diminuivano per nulla - era arrivato infatti su di lui il giusto giudizio di Dio - e disperando ormai di sé, scrisse ai Giudei la lettera riportata qui sotto, nello stile di una supplica, così concepita:"],
[9019,"\"Ai Giudei, ottimi cittadini, il re e condottiero Antioco augura perfetta salute, benessere e prosperità."],
[9020,"Se voi state bene e i figli e le vostre cose procedono secondo il vostro pensiero, io, riponendo la mia speranza nel Cielo,"],
[9021,"mi ricordo con tenerezza del vostro onore e della vostra benevolenza. Ritornando dalle province della Persia e trovandomi colpito da una malattia insopportabile, ho creduto necessario pensare alla comune sicurezza di tutti."],
[9022,"Non dispero del mio stato, avendo molta fiducia di scampare alla malattia."],
[9023,"Considerando d'altra parte che anche mio padre, quando aveva intrapreso spedizioni nelle province settentrionali, designava il successore,"],
[9024,"perché, se fosse accaduto qualche cosa di inaspettato o si fosse diffusa la notizia di qualche grave incidente, gli abitanti del paese, sapendo in mano a chi era stato lasciato il governo, non si agitassero,"],
[9025,"e oltre a questo, constatando che i sovrani vicini e confinanti con il nostro regno spiano il momento opportuno e attendono gli eventi, ho designato come re mio figlio Antioco, che già più volte, quando intraprendevo i viaggi nei distretti settentrionali, ho raccomandato e affidato a moltissimi di voi. A lui indirizzo la lettera qui unita."],
[9026,"Vi prego dunque e vi scongiuro di ricordarvi dei benefici ricevuti, pubblicamente o privatamente, e prego ciascuno di conservare la vostra benevolenza verso di me e mio figlio."],
[9027,"Ho fiducia che egli, seguendo le mie direttive, si comporterà con voi con moderazione e umanità\"."],
[9028,"Quest'omicida e bestemmiatore, dunque, soffrendo crudeli tormenti, come li aveva fatti subire agli altri, finì così la sua vita con miserabile morte in terra straniera, sui monti."],
[9029,"Curò il trasporto della salma Filippo, suo compagno d'infanzia, il quale poi, diffidando del figlio di Antioco, si ritirò in Egitto presso Tolomeo Filometore."],
[10001,"Intanto il Maccabeo e i suoi uomini, guidati dal Signore, rioccuparono il tempio e la città"],
[10002,"e distrussero gli altari innalzati dagli stranieri sulle piazze e i recinti sacri."],
[10003,"Purificarono il tempio e vi costruirono un altro altare; poi, facendo scintille con le pietre, ne trassero il fuoco e offrirono sacrifici, dopo un'interruzione di due anni e prepararono l'altare degli incensi, le lampade e l'offerta dei pani."],
[10004,"Fatto ciò, prostrati a terra, supplicarono il Signore di non farli più incorrere in quei mali ma, qualora peccassero di nuovo, di venire da lui corretti con clemenza, e non abbandonati in mano a un popolo di barbari e bestemmiatori."],
[10005,"La purificazione del tempio avvenne nello stesso giorno in cui gli stranieri l'avevano profanato, il venticinque dello stesso mese, cioè di Chisleu."],
[10006,"Con gioia passarono otto giorni come nella festa delle Capanne, ricordando come poco tempo prima avevano passato la festa delle Capanne dispersi sui monti e nelle caverne come animali selvatici."],
[10007,"Perciò, tenendo in mano bastoni ornati, rami verdi e palme, innalzavano inni a colui che li aveva felicemente condotti alla purificazione del suo proprio tempio."],
[10008,"Poi con pubblico editto, confermato da una deliberazione comune, decretarono che tutta la nazione dei Giudei celebrasse ogni anno questi giorni."],
[10009,"Tali furono le vicende riguardanti la morte di Antioco, chiamato Epifane."],
[10010,"Ora invece esporremo le cose accadute sotto Antioco Eupatore, figlio di quell'empio, sintetizzando le principali sventure causate dalle guerre."],
[10011,"Costui, dunque, succeduto nel regno, nominò incaricato degli affari un certo Lisia, governatore generale della Celesiria e della Fenicia."],
[10012,"Infatti Tolomeo, chiamato Macrone, che aveva cominciato a praticare la giustizia verso i Giudei, a causa dei torti che erano stati fatti loro, cercava di trattare con loro pacificamente."],
[10013,"Per questo motivo fu accusato dagli amici presso l'Eupatore. Sentendosi poi chiamare spesso traditore per aver abbandonato Cipro, a lui affidata dal Filometore, ed essere passato dalla parte di Antioco Epifane, non potendo esercitare con onore la carica, datosi il veleno, pose fine alla propria vita."],
[10014,"Gorgia, divenuto stratega della regione, assoldava stranieri e manteneva viva la guerra contro i Giudei."],
[10015,"Insieme con lui anche gli Idumei, che occupavano fortezze importanti, lottavano contro i Giudei e, dando asilo a tutti i fuorusciti da Gerusalemme, cominciarono a fomentare la guerra."],
[10016,"Gli uomini del Maccabeo pertanto, dopo aver innalzato preghiere e supplicato Dio che si facesse loro alleato, mossero contro le fortezze degli Idumei"],
[10017,"e, attaccandole con energia, si impadronirono delle posizioni, respinsero tutti quelli che combattevano sulle mura e trucidarono quanti erano venuti a tiro; ne uccisero così non meno di ventimila."],
[10018,"Non meno di novemila tuttavia fuggirono in due torri saldamente fortificate e fornite di tutto l'occorrente per sostenere l'assedio."],
[10019,"Allora il Maccabeo, lasciando Simone e Giuseppe, Zaccheo e i suoi uomini, sufficienti per quell'assedio, si recò in zone più critiche."],
[10020,"Ma gli uomini di Simone, vinti dalla prospettiva del guadagno, si lasciarono persuadere per denaro da alcuni che erano nelle torri e, ricevute settantamila dracme, ne lasciarono fuggire alcuni."],
[10021,"Quando fu riferito al Maccabeo l'accaduto, radunati i capi del popolo, li accusò di aver venduto per denaro i loro fratelli, mettendo in libertà i loro nemici."],
[10022,"Fece giustiziare coloro che si erano resi colpevoli di tradimento e senza indugio espugnò le due torri."],
[10023,"Essendo riuscito in ogni impresa con le armi in mano, mise a morte nelle due fortezze più di ventimila uomini."],
[10024,"Timoteo, che prima era stato battuto dai Giudei, assoldò forze straniere in grande numero, radunò buona parte della cavalleria dell'Asia e avanzò con l'intenzione di soggiogare la Giudea con le armi."],
[10025,"Gli uomini del Maccabeo, al suo avvicinarsi, si cosparsero il capo di polvere per la preghiera a Dio e, con i fianchi cinti di sacco,"],
[10026,"si prostrarono davanti all'altare e supplicarono Dio di mostrarsi loro propizio e di farsi nemico dei loro nemici e avversario dei loro avversari, come attesta la legge."],
[10027,"Terminata la preghiera, presero le armi e uscirono dalla città per un bel tratto. Quando furono vicini ai nemici, si fermarono."],
[10028,"Appena spuntata la luce del mattino, iniziò l'attacco dalle due parti, gli uni avendo a garanzia del successo e della vittoria gloriosa la fiducia nel Signore, gli altri assumendo come guida nel conflitto il loro ardire."],
[10029,"Si era accesa una lotta durissima, apparvero dal cielo ai nemici cinque uomini splendidi su cavalli dalle briglie d'oro, che si misero alla guida dei Giudei."],
[10030,"Essi presero in mezzo il Maccabeo e, riparandolo con le loro armature, lo rendevano invulnerabile; scagliavano invece dardi e folgori contro gli avversari i quali, confusi e accecati, si dispersero in preda al disordine."],
[10031,"Ne furono uccisi ventimilacinquecento e seicento cavalieri."],
[10032,"Timoteo si rifugiò in una fortezza chiamata Ghezer, saldamente difesa, dove era comandante Cherea."],
[10033,"Ma i soldati del Maccabeo assediarono con entusiasmo la fortezza per quattro giorni."],
[10034,"Gli assediati, fidando nelle fortificazioni del luogo, bestemmiavano in modo orribile e lanciavano orrende frasi."],
[10035,"Alle prime luci del quinto giorno, venti giovani del Maccabeo, accesi di sdegno per le bestemmie, presero d'assalto le mura coraggiosamente e, con selvaggio furore, travolsero chiunque trovavano."],
[10036,"Anche altri, attaccando con una manovra di aggiramento, incendiarono le torri e, accesi dei fuochi, bruciarono vivi i bestemmiatori; altri ancora sfondarono le porte e, fatto entrare il resto dell'esercito, affrettarono la presa della città."],
[10037,"Trucidarono Timoteo che si era nascosto in una cisterna, suo fratello Cherea e Apollofane."],
[10038,"Compiuta l'impresa, con canti e inni di lode benedicevano il Signore, che aveva tanto favorito Israele e concesso loro la vittoria."],
[11001,"Poco tempo dopo, Lisia, tutore e parente del re e incaricato degli affari di stato, mal sopportando l'accaduto,"],
[11002,"raccolti circa ottantamila uomini e tutta la cavalleria, mosse contro i Giudei, contando di ridurre la città a residenza dei Greci,"],
[11003,"di imporre tasse al tempio come agli altri edifici di culto delle nazioni e di mettere in vendita ogni anno il sommo sacerdozio."],
[11004,"Egli non teneva in nessun conto la potenza di Dio, ma confidava soltanto nelle sue miriadi di fanti, nelle migliaia di cavalieri e negli ottanta elefanti."],
[11005,"Entrato nella Giudea e avvicinatosi a Bet-Sur, che era una posizione fortificata distante da Gerusalemme circa venti miglia, la cinse d'assedio."],
[11006,"Quando gli uomini del Maccabeo vennero a sapere che quello assediava le fortezze, tra gemiti e lacrime supplicarono con tutto il popolo il Signore che inviasse l'angelo buono a salvare Israele."],
[11007,"Lo stesso Maccabeo, cingendo per primo le armi, esortò gli altri a esporsi con lui al pericolo per andare in aiuto dei loro fratelli: tutti insieme partirono con coraggio."],
[11008,"Mentre si trovavano ancora vicino a Gerusalemme, apparve come condottiero davanti a loro un cavaliere in sella, vestito di bianco, che brandiva armi d'oro."],
[11009,"Tutti insieme benedissero Dio misericordioso e si sentirono rincuorati, pronti ad assalire non solo gli uomini ma anche le bestie più feroci e mura di ferro."],
[11010,"Procedevano in ordine, con un alleato venuto dal cielo, per la misericordia che il Signore aveva avuto di loro."],
[11011,"Gettatisi come leoni sui nemici, stesero al suolo undicimila fanti e milleseicento cavalieri e costrinsero tutti a fuggire."],
[11012,"Costoro in gran parte riuscirono a salvarsi feriti e spogliati. E lo stesso Lisia si salvò fuggendo vergognosamente."],
[11013,"Ma, non privo di intelligenza, pensando alla sconfitta subita e constatando che gli Ebrei erano invincibili, perché il Dio potente combatteva al loro fianco,"],
[11014,"mandò a proporre un accordo su tutto ciò che fosse giusto, assicurando che a questo scopo avrebbe persuaso il re, facendo pressione su di lui perché diventasse loro amico."],
[11015,"Il Maccabeo, badando a ciò che più conveniva, acconsentì a tutto quanto Lisia chiedeva. Infatti, quanto il Maccabeo aveva presentato a Lisia per iscritto riguardo ai Giudei, il re lo accordò."],
[11016,"Il contenuto della lettera scritta da Lisia ai Giudei era del seguente tenore:"],
[11017,"\"Lisia al popolo dei Giudei, salute! Giovanni e Assalonne, inviati da voi, ci hanno consegnato il documento sotto riportato e hanno chiesto la ratifica dei punti in esso contenuti."],
[11018,"Quanto era necessario riferire anche al re, gliel'ho esposto ed egli ha accordato quanto era accettabile."],
[11019,"Se dunque continuerete a essere favorevoli agli interessi del regno, cercherò anche in avvenire di procurarvi dei favori."],
[11020,"Su questi punti e sui particolari ho dato ordine ai vostri e ai miei incaricati di trattare con voi."],
[11021,"State bene. L'anno centoquarantotto, il ventiquattro del mese di Dioscorinzio\"."],
[11022,"La lettera del re si esprimeva così: \"Il re Antioco al fratello Lisia, salute!"],
[11023,"Dopo che nostro padre è passato tra gli dei, vogliamo che i cittadini del regno possano tranquillamente attendere ai loro interessi."],
[11024,"Avendo sentito che i Giudei non intendono accettare l'ellenizzazione voluta da nostro padre, ma, attaccati al loro sistema di vita, chiedono di attenersi alle proprie leggi,"],
[11025,"volendo perciò che anche questa nazione sia libera da turbamenti, decretiamo che il tempio sia loro restituito e si governino secondo le tradizioni dei loro antenati."],
[11026,"Farai bene, dunque, a inviare loro messaggeri e a dare loro la destra, perché, conosciuta la nostra decisione, si sentano rincuorati e riprendano a loro agio la cura delle proprie cose\"."],
[11027,"La lettera del re indirizzata alla nazione era così concepita: \"Il re Antioco al consiglio degli anziani dei Giudei e agli altri Giudei, salute!"],
[11028,"Se state bene, è appunto come noi vogliamo; anche noi godiamo ottima salute."],
[11029,"Menelao ci ha rivelato che voi volete tornare a vivere nelle vostre sedi."],
[11030,"A quelli che si metteranno in viaggio entro i trenta giorni del mese di Xantico sarà garantita sicurezza e facoltà"],
[11031,"di usare, come Giudei, delle loro regole alimentari e delle loro leggi, come prima, e nessuno di loro potrà essere molestato da alcuno per le mancanze commesse per ignoranza."],
[11032,"Ho anche mandato Menelao per rassicurarvi."],
[11033,"State bene. L'anno centoquarantotto, il quindici del mese di Xantico\"."],
[11034,"Anche i Romani inviarono loro questa lettera: \"Quinto Memmio e Tito Manio, legati dei Romani, al popolo dei Giudei, salute!"],
[11035,"Riguardo a ciò che Lisia, parente del re, vi ha concesso, anche noi siamo d'accordo."],
[11036,"Riguardo invece a quei punti che egli ha giudicato dover riferire al re, mandate subito qualcuno, dopo averli esaminati, perché possiamo riferire le cose in modo conveniente per voi. Noi siamo in viaggio per Antiochia."],
[11037,"Mandate dunque in fretta dei messaggeri per farci conoscere di quale parere siete."],
[11038,"State bene. L'anno centoquarantotto, il quindici del mese di Xantico\"."],
[12001,"Conclusi questi accordi, Lisia ritornò presso il re; i Giudei invece si diedero a coltivare la terra."],
[12002,"Ma alcuni dei comandanti dei distretti, e precisamente Timoteo e Apollonio, figlio di Genneo, Girolamo e Demofonte e, oltre questi, Nicanore, il comandante dei mercenari di Cipro, non li lasciavano tranquilli né vivere in pace."],
[12003,"Gli abitanti di Giaffa perpetrarono un'empietà di questo genere: invitarono i Giudei che abitavano con loro a salire con le mogli e con i figli su barche allestite da loro, come se non ci fosse alcuna cattiva intenzione a loro riguardo,"],
[12004,"ma fosse un'iniziativa di tutta la cittadinanza. Essi accettarono, desiderosi di rinsaldare la pace, e lontani da ogni sospetto. Ma quando furono al largo, li fecero affondare in numero non inferiore a duecento."],
[12005,"Quando Giuda fu informato di questa crudeltà compiuta contro i suoi connazionali, diede ordini ai suoi uomini"],
[12006,"e, invocando Dio, giusto giudice, mosse contro gli assassini dei suoi fratelli e nella notte incendiò il porto, bruciò le navi e uccise di spada quanti vi si erano rifugiati."],
[12007,"Poi, dato che il luogo era sbarrato, abbandonò l'impresa con l'idea di tornare un'altra volta e di estirpare tutta la cittadinanza di Giaffa."],
[12008,"Avendo poi appreso che anche i cittadini di Iamnia volevano usare lo stesso sistema con i Giudei che abitavano con loro,"],
[12009,"piombando di notte sui cittadini di Iamnia, incendiò il porto con la flotta, così che si vedeva il bagliore delle fiamme fino a Gerusalemme, che è distante duecentoquaranta stadi."],
[12010,"Quando si furono allontanati di là per nove stadi, mentre marciavano contro Timoteo, non meno di cinquemila Arabi con cinquecento cavalieri irruppero contro Giuda."],
[12011,"Ne nacque una zuffa furiosa, ma gli uomini di Giuda, con l'aiuto di Dio, ebbero la meglio. I nomadi invece, sopraffatti, supplicarono Giuda che desse loro la destra, promettendo di cedergli bestiame e di aiutarlo in tutto il resto."],
[12012,"Giuda, prevedendo che gli sarebbero stati veramente utili in molte cose, acconsentì a fare la pace con loro ed essi, strette le destre, tornarono alle loro tende."],
[12013,"Attaccò anche una città difesa da contrafforti, circondata da mura e abitata da gente d'ogni stirpe, chiamata Casfin."],
[12014,"Quelli di dentro, sicuri della solidità delle mura e delle riserve di viveri, si mostravano insolenti con gli uomini di Giuda, insultandoli e anche bestemmiando e pronunciando frasi che non è lecito riferire."],
[12015,"Ma gli uomini di Giuda, invocato il grande Signore dell'universo, il quale senza arieti e senza macchine ingegnose aveva fatto cadere Gerico al tempo di Giosuè, assalirono furiosamente le mura."],
[12016,"Presa la città per volere di Dio, fecero innumerevoli stragi, cosicché il lago adiacente, largo due stadi, sembrava pieno del sangue che vi colava dentro."],
[12017,"Allontanatisi di là settecentocinquanta stadi, giunsero a Caraca, presso i Giudei chiamati Tubiani;"],
[12018,"da quelle parti però non trovarono Timoteo, il quale era già partito dalla zona, senza avere intrapreso alcuna azione, ma lasciando in un certo luogo un presidio molto forte."],
[12019,"Dositeo e Sosipatro, due capitani del Maccabeo, in una sortita sterminarono gli uomini di Timoteo lasciati nella fortezza, che erano più di diecimila."],
[12020,"Il Maccabeo ordinò il suo esercito dividendolo in reparti, pose costoro al comando dei reparti e mosse contro Timoteo, il quale aveva con sé centoventimila fanti e duemilacinquecento cavalieri."],
[12021,"Quando Timoteo seppe dell'arrivo di Giuda, mandò avanti le donne, i fanciulli e tutto il bagaglio nel luogo chiamato Karnion: era questa una posizione inespugnabile e inaccessibile per la strettezza di tutti i passaggi."],
[12022,"All'apparire del primo reparto di Giuda, si diffuse tra i nemici il panico e il terrore, perché si verificò contro di loro l'apparizione di colui che dall'alto tutto vede, e perciò cominciarono a fuggire precipitandosi chi da una parte chi dall'altra, cosicché spesso erano colpiti dai propri compagni e trafitti dalle punte delle loro spade."],
[12023,"Giuda li inseguì con ogni energia, trafiggendo quegli scellerati e uccidendone circa trentamila."],
[12024,"Lo stesso Timoteo, caduto in mano agli uomini di Dositeo e Sosipatro, supplicava con molta astuzia di essere rilasciato sano e salvo, perché tratteneva come ostaggi i genitori di molti di loro e di altri i fratelli, ai quali sarebbe capitato di essere trattati senza riguardo."],
[12025,"Avendo egli con molti discorsi prestato solenne promessa di restituire incolumi gli ostaggi, lo lasciarono libero per la salvezza dei propri fratelli."],
[12026,"Giuda mosse poi contro Karnion e l'Atargateo e uccise venticinquemila uomini."],
[12027,"Dopo la sconfitta e lo sterminio di questi, marciò contro la fortezza di Efron, nella quale si trovava Lisia con una moltitudine di gente di ogni razza. Davanti alle mura erano schierati i giovani più forti, che combattevano vigorosamente, mentre nella città stavano pronte molte riserve di macchine e di proiettili."],
[12028,"Ma, invocato il Signore che con potenza distrugge le forze dei nemici, fecero cadere la città nelle proprie mani e uccisero venticinquemila di coloro che vi stavano dentro."],
[12029,"Partiti di là, mossero contro Scitopoli, che dista seicento stadi da Gerusalemme."],
[12030,"Ma poiché i Giudei che vi abitavano testimoniarono che i cittadini di Scitopoli avevano dimostrato loro benevolenza e buona comprensione nel tempo della sventura,"],
[12031,"li ringraziarono e li esortarono a essere ben disposti anche in seguito verso il loro popolo. Poi raggiunsero Gerusalemme; era già vicina la festa delle Settimane."],
[12032,"Dopo questa festa, chiamata Pentecoste, mossero contro Gorgia, stratega dell'Idumea."],
[12033,"Questi avanzò con tremila fanti e quattrocento cavalieri."],
[12034,"Si schierarono in combattimento; cadde però un piccolo numero di Giudei."],
[12035,"Un certo Dositeo, valoroso cavaliere degli uomini di Bacenore, aveva afferrato Gorgia e lo teneva per il mantello, mentre lo trascinava con forza, poiché voleva prendere vivo quello scellerato; uno dei cavalieri traci si gettò su di lui tagliandogli il braccio e Gorgia poté fuggire a Maresà."],
[12036,"Poiché gli uomini di Esdrin combattevano da lungo tempo ed erano stanchi, Giuda supplicò il Signore che si mostrasse loro alleato e guida nella battaglia."],
[12037,"Poi, intonato nella lingua dei padri il grido di guerra accompagnato da inni, diede un assalto improvviso alle truppe di Gorgia e le mise in fuga."],
[12038,"Giuda poi radunò l'esercito e venne alla città di Odollam; poiché stava per iniziare il settimo giorno, si purificarono secondo l'uso e vi passarono il sabato."],
[12039,"Il giorno dopo, quando ormai la cosa era diventata necessaria, gli uomini di Giuda andarono a raccogliere i cadaveri dei caduti per deporli con i loro parenti nei sepolcri dei loro padri."],
[12040,"Ma trovarono sotto la tunica di ciascun morto oggetti sacri agli idoli di Iamnia, che la legge proibisce ai Giudei. Così fu a tutti chiaro il motivo per cui costoro erano caduti."],
[12041,"Perciò tutti, benedicendo Dio, giusto giudice che rende palesi le cose occulte,"],
[12042,"si misero a pregare, supplicando che il peccato commesso fosse pienamente perdonato. Il nobile Giuda esortò tutti a conservarsi senza peccati, avendo visto con i propri occhi quanto era avvenuto a causa del peccato di quelli che erano caduti."],
[12043,"Poi fatta una colletta, con tanto a testa, per circa duemila dracme d'argento, le inviò a Gerusalemme perché fosse offerto un sacrificio per il peccato, compiendo così un'azione molto buona e nobile, suggerita dal pensiero della risurrezione."],
[12044,"Perché, se non avesse avuto ferma fiducia che i caduti sarebbero risuscitati, sarebbe stato superfluo e vano pregare per i morti."],
[12045,"Ma se egli pensava alla magnifica ricompensa riservata a coloro che si addormentano nella morte con sentimenti di pietà, la sua considerazione era santa e devota. Perciò egli fece offrire il sacrificio espiatorio per i morti, perché fossero assolti dal peccato."],
[13001,"Nell'anno centoquarantanove giunse notizia agli uomini di Giuda che Antioco Eupatore muoveva contro la Giudea con numerose truppe;"],
[13002,"era con lui Lisia, suo tutore e incaricato d'affari, che aveva con sé un esercito greco di centodiecimila fanti, cinquemilatrecento cavalieri, ventidue elefanti e trecento carri falcati."],
[13003,"A costoro si era unito anche Menelao, il quale incoraggiava con molta astuzia Antioco, non per la salvezza della patria, ma per la speranza di tornare al potere."],
[13004,"Ma il re dei re eccitò l'ira di Antioco contro quello scellerato e, avendogli Lisia dimostrato che era causa di tutti i mali, ordinò che fosse condotto a Berea e messo a morte secondo l'usanza del luogo."],
[13005,"Vi è là una torre di cinquanta cubiti piena di cenere, dotata di un ordigno girevole che da ogni lato pende a precipizio sulla cenere."],
[13006,"Di lassù tutti possono spingere verso la morte chi è reo di sacrilegio o chi ha raggiunto il colmo di altri delitti."],
[13007,"In tal modo morì Menelao, che non ebbe in sorte nemmeno la terra per la sepoltura."],
[13008,"Giusto castigo poiché, dopo aver commesso molti delitti attorno all'altare, il cui fuoco è sacro quanto la cenere, nella cenere trovò la sua morte."],
[13009,"Il re avanzava con barbari sentimenti e con l'intenzione di far provare ai Giudei trattamenti peggiori di quelli che avevano subito sotto suo padre."],
[13010,"Quando Giuda seppe queste cose, ordinò al popolo di pregare il Signore giorno e notte perché, come altre volte, così anche ora aiutasse coloro che correvano il rischio di essere privati della legge, della patria e del tempio santo"],
[13011,"e non permettesse che il popolo, che aveva appena goduto di un breve respiro, cadesse in mano a quelle nazioni infami."],
[13012,"Quando tutti insieme ebbero fatto ciò, supplicando il Signore misericordioso con gemiti e digiuni e prostrazioni per tre giorni consecutivi, Giuda li esortò e comandò loro di tenersi pronti."],
[13013,"Quindi, incontratosi da solo con gli anziani, decise che con l'aiuto di Dio si doveva risolvere la situazione uscendo a battaglia prima che l'esercito del re entrasse nella Giudea e si impadronisse della città."],
[13014,"Affidando poi ogni cura al Creatore dell'universo, esortò i suoi a combattere da prodi fino alla morte per le leggi, il tempio, la città, la patria, le loro istituzioni, e pose il campo vicino a Modin."],
[13015,"Data ai suoi uomini la parola d'ordine \"Vittoria di Dio\", con giovani, scelti tra i più valorosi, piombò di notte sulla tenda del re nell'accampamento, uccise circa duemila uomini e trafisse il più grosso degli elefanti insieme con l'uomo che era nella torretta."],
[13016,"Alla fine, riempito il campo di terrore e confusione, se ne tornarono soddisfatti per il successo ottenuto."],
[13017,"Quando già spuntava il giorno, l'impresa era compiuta, per la protezione del Signore che aveva assistito Giuda."],
[13018,"Il re, avuto questo saggio dell'audacia dei Giudei, tentò di prendere con astuzia quei luoghi."],
[13019,"Marciò contro Bet-Sur, una ben munita fortezza dei Giudei, ma fu respinto, ostacolato e battuto,"],
[13020,"poiché Giuda fece giungere il necessario agli assediati."],
[13021,"Intanto un certo Rodoco, dell'esercito dei Giudei, aveva rivelato i segreti ai nemici: fu ricercato, catturato e tolto di mezzo."],
[13022,"Il re tornò a trattare con quelli che erano a Bet-Sur, diede e ricevette la destra e se ne andò. Assalì gli uomini di Giuda, ma ebbe la peggio."],
[13023,"Venne poi a sapere che Filippo, lasciato ad Antiochia come incaricato d'affari, era uscito di senno. Costernato, invitò i Giudei a trattare, si sottomise, si obbligò con giuramento a rispettare tutte le giuste condizioni, ristabilì l'accordo e offrì un sacrificio, onorò il tempio e beneficò il luogo santo."],
[13024,"Poi ricevette il Maccabeo e lasciò Egemonide come stratega da Tolemaide fino al paese dei Gerreni."],
[13025,"Venne a Tolemaide, ma i cittadini di Tolemaide si mostrarono malcontenti per quegli accordi; erano irritati contro coloro che avevano voluto abolire i loro privilegi."],
[13026,"Lisia allora salì sulla tribuna, fece la sua difesa meglio che poté, li persuase, li calmò, li rese ragionevoli; poi tornò ad Antiochia. Così si svolsero i fatti relativi alla spedizione del re e alla sua ritirata."],
[14001,"Dopo un periodo di tre anni, giunse notizia agli uomini di Giuda che Demetrio, figlio di Seleuco, sbarcato nel porto di Tripoli con un grande esercito e la flotta,"],
[14002,"si era impadronito del paese, eliminando Antioco e il suo tutore Lisia."],
[14003,"Un certo Àlcimo, che era stato prima sommo sacerdote, ma che si era volontariamente contaminato al tempo della rivolta, avendo capito che non si apriva a lui in alcun modo una via di salvezza e non vi era più la possibilità di accedere al sacro altare,"],
[14004,"andò dal re Demetrio verso l'anno centocinquantuno, offrendogli una corona d'oro e una palma, oltre ai tradizionali ramoscelli di ulivo del tempio. Per quel giorno restò tranquillo."],
[14005,"Ma colta l'occasione favorevole alla sua follia, quando da Demetrio fu convocato a consiglio e interrogato su quali fossero lo stato d'animo e le intenzioni dei Giudei, rispose:"],
[14006,"\"I Giudei che si dicono Asidei, a capo dei quali sta Giuda il Maccabeo, alimentano guerre e ribellioni e non lasciano che il regno trovi la calma."],
[14007,"Per questo anch'io, privato della dignità ereditaria, intendo dire del sommo sacerdozio, sono venuto qui,"],
[14008,"spinto anzitutto da schietta premura per gli interessi del re, ma in secondo luogo mirando anche ai miei concittadini, perché, a causa dell'irragionevolezza di dette persone, tutto il nostro popolo si va impoverendo non poco."],
[14009,"Ora che conosci bene ognuna di queste cose, tu, o re, provvedi al paese e alla nostra stirpe che va decadendo, con quella cortese benevolenza che hai con tutti."],
[14010,"Fin quando Giuda è vivo, è impossibile che la situazione torni pacifica\"."],
[14011,"Dopo queste sue parole, gli altri amici, irritati per i successi di Giuda, si affrettarono a infiammare Demetrio."],
[14012,"Questi, designato subito Nicanore, che era a capo degli elefanti, e nominatolo stratega della Giudea, ve lo inviò"],
[14013,"con l'ordine di eliminare Giuda, di disperdere i suoi uomini e di costituire Àlcimo sommo sacerdote del tempio massimo."],
[14014,"Allora le nazioni della Giudea, che erano fuggite davanti a Giuda, si unirono in massa a Nicanore, pensando che le sfortune e le calamità dei Giudei sarebbero state apportatrici di fortuna per loro."],
[14015,"Quando seppero della venuta di Nicanore e dell'aggressione delle nazioni, i Giudei, cosparsi di polvere, elevarono suppliche a colui che ha costituito il suo popolo per sempre e che con segni palesi protegge sempre coloro che sono la sua porzione."],
[14016,"Poi, dati gli ordini, il capo mosse rapidamente di là e si scontrò con loro presso il villaggio di Dessau."],
[14017,"Simone, fratello di Giuda, aveva già attaccato Nicanore, ma per l'improvvisa comparsa dei nemici, lentamente aveva dovuto cedere."],
[14018,"Tuttavia Nicanore, conosciuto il valore che avevano gli uomini di Giuda e il loro entusiasmo nelle lotte per la patria, non osava decidere la questione con spargimento di sangue."],
[14019,"Per questo mandò Posidonio e Teodoto e Mattatia a dare e ricevere la destra."],
[14020,"La cosa fu discussa lungamente e, quando il comandante ne diede comunicazione alle truppe, il parere risultò unanime e accettarono gli accordi."],
[14021,"Fissarono il giorno nel quale sarebbero venuti a un incontro privato. Dall'una e dall'altra parte avanzò un carro e collocarono dei seggi."],
[14022,"Giuda tuttavia dispose degli uomini armati nei luoghi opportuni, per paura che si verificasse d'improvviso qualche tradimento da parte dei nemici. Così in buon accordo conclusero l'incontro."],
[14023,"Nicanore si trattenne a Gerusalemme e non fece alcun male; anzi licenziò le turbe raccogliticce che a lui si erano unite."],
[14024,"Aveva sempre Giuda con sé e nutriva un intimo affetto per lui."],
[14025,"Lo esortò a sposarsi e ad avere figli; si sposò, se ne stette tranquillo e visse normalmente la sua vita."],
[14026,"Ma Àlcimo, vedendo la loro reciproca simpatia e procuratosi copia degli accordi intercorsi, andò da Demetrio e gli disse che Nicanore seguiva una linea contraria agli interessi dello stato: aveva infatti nominato suo successore Giuda, il sobillatore del regno."],
[14027,"Il re, contrariato e acceso di sdegno per le calunnie di quel genio malefico, scrisse a Nicanore, dichiarandogli di essere scontento delle alleanze concluse e ordinandogli che gli mandasse subito ad Antiochia il Maccabeo in catene."],
[14028,"Nicanore, quando gli giunse quest'ordine, rimase sconcertato ed era riluttante a rompere i patti senza che quell'uomo avesse commesso alcuna colpa."],
[14029,"Ma, poiché non gli era possibile agire contro la volontà del re, cercava l'occasione per effettuare la cosa con qualche stratagemma."],
[14030,"Il Maccabeo, notando che Nicanore era più freddo nei suoi confronti e aspro nei consueti incontri, arguendo che questa freddezza non presagiva niente di buono, raccolti non pochi dei suoi, non si fece più vedere da Nicanore."],
[14031,"Questi, accortosi di essere stato giocato abilmente da Giuda, salì al massimo e santo tempio, mentre i sacerdoti stavano compiendo i sacrifici prescritti, e ordinò che gli fosse consegnato quell'uomo."],
[14032,"I sacerdoti dichiararono con giuramento che non sapevano dove fosse il ricercato."],
[14033,"Allora egli, stendendo la destra contro il tempio, giurò: \"Se non mi consegnerete Giuda in catene, spianerò questa dimora di Dio, abbatterò dalle fondamenta l'altare e innalzerò qui uno splendido tempio a Dioniso\"."],
[14034,"Detto questo, se ne andò. I sacerdoti, alzando le mani al cielo, invocarono il protettore sempre vigile del nostro popolo, dicendo:"],
[14035,"\"Tu, Signore, che di nulla hai bisogno, ti sei compiaciuto di porre il tempio della tua abitazione in mezzo a noi."],
[14036,"Ora, Signore, santo di ogni santità, custodisci per sempre incontaminata questa tua casa, che da poco è stata purificata\"."],
[14037,"Fu denunciato a Nicanore un certo Razis, degli anziani di Gerusalemme, uomo pieno di amore per la città, che godeva grandissima fama, chiamato padre dei Giudei per la sua benevolenza."],
[14038,"Egli infatti, nei giorni precedenti la rivolta, si era attirato l'accusa di giudaismo e realmente per il giudaismo aveva impegnato corpo e anima con piena generosità."],
[14039,"Volendo Nicanore far nota a tutti l'ostilità che aveva verso i Giudei, mandò più di cinquecento soldati per arrestarlo;"],
[14040,"pensava infatti che, prendendo costui, avrebbe arrecato loro un grave colpo."],
[14041,"Ma, quando quella truppa stava per occupare la torre e tentava di forzare la porta del cortile, dando ordine di portare il fuoco e di appiccarlo alle porte, egli, accerchiato da ogni lato, rivolse la spada contro se stesso,"],
[14042,"preferendo morire nobilmente piuttosto che divenire schiavo degli scellerati e subire insulti indegni della sua nobiltà."],
[14043,"Non avendo però portato a segno il colpo per la fretta della lotta, mentre la folla premeva fuori delle porte, salì arditamente sulle mura e si gettò giù coraggiosamente sulla folla."],
[14044,"Questa, subito indietreggiando, fece largo e così egli cadde in mezzo allo spazio vuoto."],
[14045,"Poiché respirava ancora, con l'animo infiammato, si alzò, mentre il sangue gli usciva a fiotti e le ferite lo straziavano, di corsa passò in mezzo alla folla, salì su di un tratto di roccia"],
[14046,"e, ormai completamente esangue, si strappò gli intestini e prendendoli con le mani li gettò contro la folla. Morì in tal modo, invocando il Signore della vita e dello spirito perché di nuovo glieli restituisse."],
[15001,"Nicanore, avendo saputo che gli uomini di Giuda si trovavano nella regione della Samaria, decise di assalirli a colpo sicuro nel giorno del riposo."],
[15002,"Poiché i Giudei che l'avevano seguito per necessità gli dicevano: \"Assolutamente non devi ucciderli in modo così crudele e barbaro; piuttosto rispetta il giorno che è stato onorato e santificato da colui che tutto vede\","],
[15003,"quell'uomo tre volte scellerato chiese se c'era in cielo un Signore che aveva comandato di celebrare il giorno del sabato."],
[15004,"Essi risposero: \"C'è il Signore vivente; egli è il sovrano del cielo, che ha comandato di celebrare il settimo giorno\"."],
[15005,"L'altro ribatté: \"E io sono sovrano sulla terra, che comando di prendere le armi e di eseguire le disposizioni del re\". Tuttavia non riuscì a mandare a effetto il suo crudele intento."],
[15006,"Nicanore, dunque, che si era montato la testa con tutta la sua arroganza, aveva deciso di erigere un pubblico trofeo per la vittoria sugli uomini di Giuda."],
[15007,"Il Maccabeo invece era fermamente convinto e sperava pienamente di ottenere protezione dal Signore."],
[15008,"Esortava perciò i suoi uomini a non temere l'attacco delle nazioni, ma a tenere impressi nella mente gli aiuti che in passato erano venuti loro dal Cielo e ad aspettare ora la vittoria che sarebbe stata loro concessa dall'Onnipotente."],
[15009,"Confortandoli così con le parole della legge e dei profeti e ricordando loro le lotte che avevano già condotto a termine, li rese più coraggiosi."],
[15010,"Avendo così rinfrancato i loro sentimenti, espose e denunciò la malafede delle nazioni e la loro violazione dei giuramenti."],
[15011,"Dopo aver armato ciascuno di loro non tanto con la sicurezza degli scudi e delle lance quanto con il conforto di quelle efficaci parole, li riempì di gioia, narrando loro un sogno degno di fede, anzi una vera visione."],
[15012,"La sua visione era questa: Onia, che era stato sommo sacerdote, uomo onesto e buono, modesto nel portamento, mite nel contegno, spedito ed elegante nel parlare, occupato fin dalla fanciullezza in tutto ciò che è proprio della virtù, con le mani protese pregava per tutta la comunità dei Giudei."],
[15013,"Poi, allo stesso modo, era apparso un uomo distinto per età senile e maestà, circonfuso di dignità meravigliosa e piena di magnificenza."],
[15014,"Presa la parola, Onia disse: \"Questi è l'amico dei suoi fratelli, che prega molto per il popolo e per la città santa, Geremia, il profeta di Dio\"."],
[15015,"E Geremia stendendo la destra consegnò a Giuda una spada d'oro, pronunciando queste parole nel porgerla:"],
[15016,"\"Prendi la spada sacra come dono di Dio; con questa abbatterai i nemici\"."],
[15017,"Incoraggiati dalle parole di Giuda, molto belle e tali da spingere all'eroismo e da rendere virile anche l'animo dei giovani, stabilirono di non restare nel campo, ma di intervenire coraggiosamente e decidere la sorte attaccando battaglia con tutto il coraggio, perché la città e le cose sante e il tempio erano in pericolo."],
[15018,"Minore era il loro timore per le donne e i figli come pure per i fratelli e i parenti, poiché la prima e principale preoccupazione era per il tempio consacrato."],
[15019,"Anche per quelli rimasti in città non era piccola l'angoscia, essendo tutti turbati per l'ansia del combattimento in campo aperto."],
[15020,"Tutti ormai attendevano la prova imminente, poiché i nemici già avevano cominciato ad attaccare e l'esercito era in ordine di battaglia, gli elefanti erano piazzati in posizione opportuna e la cavalleria schierata ai lati."],
[15021,"Il Maccabeo, dopo aver osservato la moltitudine dei presenti, la varietà delle armi pronte e la ferocia delle bestie, alzò le mani al cielo e invocò il Signore che compie prodigi, convinto che non è possibile vincere con le armi, ma che egli concede la vittoria a coloro che ne sono degni, secondo il suo giudizio."],
[15022,"Nel pregare il Signore, si esprimeva in questo modo: \"Tu, Signore, inviasti il tuo angelo al tempo di Ezechia, re della Giudea, ed egli fece perire nel campo di Sennacherib centoottantacinquemila uomini."],
[15023,"Anche ora, sovrano del cielo, manda un angelo buono davanti a noi per incutere paura e tremore."],
[15024,"Siano atterriti dalla potenza del tuo braccio coloro che bestemmiando sono venuti qui contro il tuo popolo santo\". Con queste parole egli terminò."],
[15025,"Gli uomini di Nicanore avanzavano al suono delle trombe e degli inni di guerra."],
[15026,"Gli uomini di Giuda invece si gettarono nella mischia contro i nemici tra invocazioni e preghiere."],
[15027,"In tal modo, combattendo con le mani, ma pregando Dio con il cuore, travolsero non meno di trentacinquemila uomini, rallegrandosi grandemente per la manifesta presenza di Dio."],
[15028,"Terminata la battaglia, mentre facevano ritorno pieni di gioia, riconobbero Nicanore caduto con tutte le sue armi."],
[15029,"Levarono alte grida dandosi all'entusiasmo, mentre benedicevano l'Onnipotente nella lingua dei padri."],
[15030,"Quindi colui che era stato sempre il primo a combattere per i suoi concittadini con anima e corpo, colui che aveva conservato l'affetto dell'età giovanile verso i suoi connazionali, comandò che tagliassero la testa di Nicanore e la sua mano con il braccio e li portassero a Gerusalemme."],
[15031,"Quando vi giunse, convocati tutti i connazionali e collocati i sacerdoti davanti all'altare, mandò a chiamare quelli della Cittadella"],
[15032,"e mostrò loro la testa dello scellerato Nicanore e la mano che quel bestemmiatore aveva steso contro la sacra dimora dell'Onnipotente, pronunciando parole arroganti."],
[15033,"Tagliata poi la lingua del sacrilego Nicanore, la fece gettare a pezzi agli uccelli e ordinò di appendere davanti al tempio la ricompensa della sua follia."],
[15034,"Tutti allora, rivolti verso il cielo, benedissero il Signore glorioso dicendo: \"Benedetto colui che ha conservato la sua dimora inviolata\"."],
[15035,"Fece poi appendere la testa di Nicanore alla Cittadella alla vista di tutti, perché fosse segno manifesto dell'aiuto di Dio."],
[15036,"Quindi deliberarono tutti insieme, con voto pubblico, di non lasciar passare inosservato quel giorno, ma di commemorarlo il tredici del dodicesimo mese - che in lingua aramaica si chiama Adar - il giorno precedente la festa di Mardocheo."],
[15037,"Così andarono le cose riguardo a Nicanore e, poiché da quel tempo la città è rimasta in mano agli Ebrei, anch'io chiudo qui la mia narrazione."],
[15038,"Se essa è riuscita ben ordinata, era quello che volevo; se invece è di poco conto e mediocre, questo solo ho potuto fare."],
[15039,"Come il bere solo vino o bere solo acqua è nocivo, mentre vino mescolato con acqua è amabile e procura un delizioso piacere, così un discorso ben elaborato delizia gli orecchi di coloro che leggono la narrazione. E qui sia la fine."]
])
