Bib.ret([
[1001,"Paolo, apostolo di Cristo Gesù per volontà di Dio e secondo la promessa della vita che è in Cristo Gesù,"],
[1002,"a Timoteo, figlio carissimo: grazia, misericordia e pace da parte di Dio Padre e di Cristo Gesù Signore nostro."],
[1003,"Rendo grazie a Dio che io servo, come i miei antenati, con coscienza pura, ricordandomi di te nelle mie preghiere sempre, notte e giorno."],
[1004,"Mi tornano alla mente le tue lacrime e sento la nostalgia di rivederti per essere pieno di gioia."],
[1005,"Mi ricordo infatti della tua schietta fede, che ebbero anche tua nonna Loide e tua madre Eunice, e che ora, ne sono certo, è anche in te."],
[1006,"Per questo motivo ti ricordo di ravvivare il dono di Dio, che è in te mediante l'imposizione delle mie mani."],
[1007,"Dio infatti non ci ha dato uno spirito di timidezza, ma di forza, di carità e di prudenza."],
[1008,"Non vergognarti dunque di dare testimonianza al Signore nostro, né di me, che sono in carcere per lui; ma, con la forza di Dio, soffri con me per il Vangelo."],
[1009,"Egli infatti ci ha salvati e ci ha chiamati con una vocazione santa, non già in base alle nostre opere, ma secondo il suo progetto e la sua grazia. Questa ci è stata data in Cristo Gesù fin dall'eternità,"],
[1010,"ma è stata rivelata ora, con la manifestazione del salvatore nostro Cristo Gesù. Egli ha vinto la morte e ha fatto risplendere la vita e l'incorruttibilità per mezzo del Vangelo,"],
[1011,"per il quale io sono stato costituito messaggero, apostolo e maestro."],
[1012,"È questa la causa dei mali che soffro, ma non me ne vergogno: so infatti in chi ho posto la mia fede e sono convinto che egli è capace di custodire fino a quel giorno ciò che mi è stato affidato."],
[1013,"Prendi come modello i sani insegnamenti che hai udito da me con la fede e l'amore, che sono in Cristo Gesù."],
[1014,"Custodisci, mediante lo Spirito Santo che abita in noi, il bene prezioso che ti è stato affidato."],
[1015,"Tu sai che tutti quelli dell'Asia, tra i quali Figelo ed Ermogene, mi hanno abbandonato."],
[1016,"Il Signore conceda misericordia alla famiglia di Onesiforo, perché egli mi ha più volte confortato e non si è vergognato delle mie catene;"],
[1017,"anzi, venuto a Roma, mi ha cercato con premura, finché non mi ha trovato."],
[1018,"Gli conceda il Signore di trovare misericordia presso Dio in quel giorno. E quanti servizi egli abbia reso a Èfeso, tu lo sai meglio di me."],
[2001,"E tu, figlio mio, attingi forza dalla grazia che è in Cristo Gesù:"],
[2002,"le cose che hai udito da me davanti a molti testimoni, trasmettile a persone fidate, le quali a loro volta siano in grado di insegnare agli altri."],
[2003,"Come un buon soldato di Gesù Cristo, soffri insieme con me."],
[2004,"Nessuno, quando presta servizio militare, si lascia prendere dalle faccende della vita comune, se vuol piacere a colui che lo ha arruolato."],
[2005,"Anche l'atleta non riceve il premio se non ha lottato secondo le regole."],
[2006,"Il contadino, che lavora duramente, dev'essere il primo a raccogliere i frutti della terra."],
[2007,"Cerca di capire quello che dico, e il Signore ti aiuterà a comprendere ogni cosa."],
[2008,"Ricordati di Gesù Cristo, risorto dai morti, discendente di Davide, come io annuncio nel mio Vangelo,"],
[2009,"per il quale soffro fino a portare le catene come un malfattore. Ma la parola di Dio non è incatenata!"],
[2010,"Perciò io sopporto ogni cosa per quelli che Dio ha scelto, perché anch'essi raggiungano la salvezza che è in Cristo Gesù, insieme alla gloria eterna."],
[2011,"Questa parola è degna di fede: Se moriamo con lui, con lui anche vivremo;"],
[2012,"se perseveriamo, con lui anche regneremo; se lo rinneghiamo, lui pure ci rinnegherà;"],
[2013,"se siamo infedeli, lui rimane fedele, perché non può rinnegare se stesso."],
[2014,"Richiama alla memoria queste cose, scongiurando davanti a Dio che si evitino le vane discussioni, le quali non giovano a nulla se non alla rovina di chi le ascolta."],
[2015,"Sforzati di presentarti a Dio come una persona degna, un lavoratore che non deve vergognarsi e che dispensa rettamente la parola della verità."],
[2016,"Evita le chiacchiere vuote e perverse, perché spingono sempre più all'empietà quelli che le fanno;"],
[2017,"la parola di costoro infatti si propagherà come una cancrena. Fra questi vi sono Imeneo e Fileto,"],
[2018,"i quali hanno deviato dalla verità, sostenendo che la risurrezione è già avvenuta e così sconvolgono la fede di alcuni."],
[2019,"Tuttavia le solide fondamenta gettate da Dio resistono e portano questo sigillo:  Il Signore conosce   quelli che sono suoi, e ancora:  Si allontani dall'iniquità chiunque invoca il nome del Signore."],
[2020,"In una casa grande però non vi sono soltanto vasi d'oro e d'argento, ma anche di legno e di argilla; alcuni per usi nobili, altri per usi spregevoli."],
[2021,"Chi si manterrà puro da queste cose, sarà come un vaso nobile, santificato, utile al padrone di casa, pronto per ogni opera buona."],
[2022,"Sta' lontano dalle passioni della gioventù; cerca la giustizia, la fede, la carità, la pace, insieme a quelli che invocano il Signore con cuore puro."],
[2023,"Evita inoltre le discussioni sciocche e da ignoranti, sapendo che provocano litigi."],
[2024,"Un servo del Signore non deve essere litigioso, ma mite con tutti, capace di insegnare, paziente,"],
[2025,"dolce nel rimproverare quelli che gli si mettono contro, nella speranza che Dio conceda loro di convertirsi, perché riconoscano la verità"],
[2026,"e rientrino in se stessi, liberandosi dal laccio del diavolo, che li tiene prigionieri perché facciano la sua volontà."],
[3001,"Sappi che negli ultimi tempi verranno momenti difficili."],
[3002,"Gli uomini saranno egoisti, amanti del denaro, vanitosi, orgogliosi, bestemmiatori, ribelli ai genitori, ingrati, empi,"],
[3003,"senza amore, sleali, calunniatori, intemperanti, intrattabili, disumani,"],
[3004,"traditori, sfrontati, accecati dall'orgoglio, amanti del piacere più che di Dio,"],
[3005,"gente che ha una religiosità solo apparente, ma ne disprezza la forza interiore. Guardati bene da costoro!"],
[3006,"Fra questi vi sono alcuni che entrano nelle case e circuiscono certe donnette cariche di peccati, in balia di passioni di ogni genere,"],
[3007,"sempre pronte a imparare, ma che non riescono mai a giungere alla conoscenza della verità."],
[3008,"Sull'esempio di Iannes e di Iambres che si opposero a Mosè, anche costoro si oppongono alla verità: gente dalla mente corrotta e che non ha dato buona prova nella fede."],
[3009,"Ma non andranno molto lontano, perché la loro stoltezza sarà manifesta a tutti, come lo fu la stoltezza di quei due."],
[3010,"Tu invece mi hai seguito da vicino nell'insegnamento, nel modo di vivere, nei progetti, nella fede, nella magnanimità, nella carità, nella pazienza,"],
[3011,"nelle persecuzioni, nelle sofferenze. Quali cose mi accaddero ad Antiochia, a Iconio e a Listra! Quali persecuzioni ho sofferto! Ma da tutte mi ha liberato il Signore!"],
[3012,"E tutti quelli che vogliono rettamente vivere in Cristo Gesù saranno perseguitati."],
[3013,"Ma i malvagi e gli impostori andranno sempre di male in peggio, ingannando gli altri e ingannati essi stessi."],
[3014,"Tu però rimani saldo in quello che hai imparato e che credi fermamente. Conosci coloro da cui lo hai appreso"],
[3015,"e conosci le sacre Scritture fin dall'infanzia: queste possono istruirti per la salvezza, che si ottiene mediante la fede in Cristo Gesù."],
[3016,"Tutta la Scrittura, ispirata da Dio, è anche utile per insegnare, convincere, correggere ed educare nella giustizia,"],
[3017,"perché l'uomo di Dio sia completo e ben preparato per ogni opera buona."],
[4001,"Ti scongiuro davanti a Dio e a Cristo Gesù, che verrà a giudicare i vivi e i morti, per la sua manifestazione e il suo regno:"],
[4002,"annuncia la Parola, insisti al momento opportuno e non opportuno, ammonisci, rimprovera, esorta con ogni magnanimità e insegnamento."],
[4003,"Verrà giorno, infatti, in cui non si sopporterà più la sana dottrina, ma, pur di udire qualcosa, gli uomini si circonderanno di maestri secondo i propri capricci,"],
[4004,"rifiutando di dare ascolto alla verità per perdersi dietro alle favole."],
[4005,"Tu però vigila attentamente, sopporta le sofferenze, compi la tua opera di annunciatore del Vangelo, adempi il tuo ministero."],
[4006,"Io infatti sto già per essere versato in offerta ed è giunto il momento che io lasci questa vita."],
[4007,"Ho combattuto la buona battaglia, ho terminato la corsa, ho conservato la fede."],
[4008,"Ora mi resta soltanto la corona di giustizia che il Signore, il giudice giusto, mi consegnerà in quel giorno; non solo a me, ma anche a tutti coloro che hanno atteso con amore la sua manifestazione."],
[4009,"Cerca di venire presto da me,"],
[4010,"perché Dema mi ha abbandonato, avendo preferito le cose di questo mondo, ed è partito per Tessalonica; Crescente è andato in Galazia, Tito in Dalmazia."],
[4011,"Solo Luca è con me. Prendi con te Marco e portalo, perché mi sarà utile per il ministero."],
[4012,"Ho inviato Tichico a Èfeso."],
[4013,"Venendo, portami il mantello, che ho lasciato a Troade in casa di Carpo, e i libri, soprattutto le pergamene."],
[4014,"Alessandro, il fabbro, mi ha procurato molti danni: il Signore gli renderà secondo le sue opere."],
[4015,"Anche tu guardati da lui, perché si è accanito contro la nostra predicazione."],
[4016,"Nella mia prima difesa in tribunale nessuno mi ha assistito; tutti mi hanno abbandonato. Nei loro confronti, non se ne tenga conto."],
[4017,"Il Signore però mi è stato vicino e mi ha dato forza, perché io potessi portare a compimento l'annuncio del Vangelo e tutte le genti lo ascoltassero: e così fui liberato dalla bocca del leone."],
[4018,"Il Signore mi libererà da ogni male e mi porterà in salvo nei cieli, nel suo regno; a lui la gloria nei secoli dei secoli. Amen."],
[4019,"Saluta Prisca e Aquila e la famiglia di Onesiforo."],
[4020,"Erasto è rimasto a Corinto; Trofimo l'ho lasciato ammalato a Mileto."],
[4021,"Affrettati a venire prima dell'inverno. Ti salutano Eubulo, Pudente, Lino, Claudia e tutti i fratelli."],
[4022,"Il Signore sia con il tuo spirito. La grazia sia con voi!"]
])
