Bib.ret([
[1001,"Paolo e Silvano e Timoteo alla Chiesa dei Tessalonicesi che è in Dio Padre nostro e nel Signore Gesù Cristo:"],
[1002,"a voi, grazia e pace da Dio Padre e dal Signore Gesù Cristo."],
[1003,"Dobbiamo sempre rendere grazie a Dio per voi, fratelli, come è giusto, perché la vostra fede fa grandi progressi e l'amore di ciascuno di voi verso gli altri va crescendo."],
[1004,"Così noi possiamo gloriarci di voi nelle Chiese di Dio, per la vostra perseveranza e la vostra fede in tutte le vostre persecuzioni e tribolazioni che sopportate."],
[1005,"È questo un segno del giusto giudizio di Dio, perché siate fatti degni del regno di Dio, per il quale appunto soffrite."],
[1006,"È proprio della giustizia di Dio ricambiare con afflizioni coloro che vi affliggono"],
[1007,"e a voi, che siete afflitti, dare sollievo insieme a noi, quando si manifesterà il Signore Gesù dal cielo, insieme agli angeli della sua potenza, con"],
[1008,"fuoco ardente, per punire quelli che non riconoscono Dio e quelli che non obbediscono al vangelo del Signore nostro Gesù."],
[1009,"Essi saranno castigati con una rovina eterna, lontano dal volto del Signore e dalla sua gloriosa potenza."],
[1010,"In quel giorno, egli verrà per essere glorificato nei suoi santi ed essere riconosciuto mirabile da tutti quelli che avranno creduto, perché è stata accolta la nostra testimonianza in mezzo a voi."],
[1011,"Per questo preghiamo continuamente per voi, perché il nostro Dio vi renda degni della sua chiamata e, con la sua potenza, porti a compimento ogni proposito di bene e l'opera della vostra fede,"],
[1012,"perché sia glorificato il nome del Signore nostro Gesù in voi, e voi in lui, secondo la grazia del nostro Dio e del Signore Gesù Cristo."],
[2001,"Riguardo alla venuta del Signore nostro Gesù Cristo e al nostro radunarci con lui, vi preghiamo, fratelli,"],
[2002,"di non lasciarvi troppo presto confondere la mente e allarmare né da ispirazioni né da discorsi, né da qualche lettera fatta passare come nostra, quasi che il giorno del Signore sia già presente."],
[2003,"Nessuno vi inganni in alcun modo! Prima infatti verrà l'apostasia e si rivelerà l'uomo dell'iniquità, il figlio della perdizione,"],
[2004,"l'avversario, colui che s'innalza sopra ogni essere chiamato e adorato come Dio, fino a insediarsi nel tempio di Dio, pretendendo di essere Dio."],
[2005,"Non ricordate che, quando ancora ero tra voi, io vi dicevo queste cose?"],
[2006,"E ora voi sapete che cosa lo trattiene perché non si manifesti se non nel suo tempo."],
[2007,"Il mistero dell'iniquità è già in atto, ma è necessario che sia tolto di mezzo colui che finora lo trattiene."],
[2008,"Allora l'empio sarà rivelato e il Signore Gesù lo distruggerà con il soffio della sua bocca e lo annienterà con lo splendore della sua venuta."],
[2009,"La venuta dell'empio avverrà nella potenza di Satana, con ogni specie di miracoli e segni e prodigi menzogneri"],
[2010,"e con tutte le seduzioni dell'iniquità, a danno di quelli che vanno in rovina perché non accolsero l'amore della verità per essere salvati."],
[2011,"Dio perciò manda loro una forza di seduzione, perché essi credano alla menzogna"],
[2012,"e siano condannati tutti quelli che, invece di credere alla verità, si sono compiaciuti nell'iniquità."],
[2013,"Noi però dobbiamo sempre rendere grazie a Dio per voi, fratelli amati dal Signore, perché Dio vi ha scelti come primizia per la salvezza, per mezzo dello Spirito santificatore e della fede nella verità."],
[2014,"A questo egli vi ha chiamati mediante il nostro Vangelo, per entrare in possesso della gloria del Signore nostro Gesù Cristo."],
[2015,"Perciò, fratelli, state saldi e mantenete le tradizioni che avete appreso sia dalla nostra parola sia dalla nostra lettera."],
[2016,"E lo stesso Signore nostro Gesù Cristo e Dio, Padre nostro, che ci ha amati e ci ha dato, per sua grazia, una consolazione eterna e una buona speranza,"],
[2017,"conforti i vostri cuori e li confermi in ogni opera e parola di bene."],
[3001,"Per il resto, fratelli, pregate per noi, perché la parola del Signore corra e sia glorificata, come lo è anche tra voi,"],
[3002,"e veniamo liberati dagli uomini corrotti e malvagi. La fede infatti non è di tutti."],
[3003,"Ma il Signore è fedele: egli vi confermerà e vi custodirà dal Maligno."],
[3004,"Riguardo a voi, abbiamo questa fiducia nel Signore: che quanto noi vi ordiniamo già lo facciate e continuerete a farlo."],
[3005,"Il Signore guidi i vostri cuori all'amore di Dio e alla pazienza di Cristo."],
[3006,"Fratelli, nel nome del Signore nostro Gesù Cristo, vi raccomandiamo di tenervi lontani da ogni fratello che conduce una vita disordinata, non secondo l'insegnamento che vi è stato trasmesso da noi."],
[3007,"Sapete in che modo dovete prenderci a modello: noi infatti non siamo rimasti oziosi in mezzo a voi,"],
[3008,"né abbiamo mangiato gratuitamente il pane di alcuno, ma abbiamo lavorato duramente, notte e giorno, per non essere di peso ad alcuno di voi."],
[3009,"Non che non ne avessimo diritto, ma per darci a voi come modello da imitare."],
[3010,"E infatti quando eravamo presso di voi, vi abbiamo sempre dato questa regola: chi non vuole lavorare, neppure mangi."],
[3011,"Sentiamo infatti che alcuni fra voi vivono una vita disordinata, senza fare nulla e sempre in agitazione."],
[3012,"A questi tali, esortandoli nel Signore Gesù Cristo, ordiniamo di guadagnarsi il pane lavorando con tranquillità."],
[3013,"Ma voi, fratelli, non stancatevi di fare il bene."],
[3014,"Se qualcuno non obbedisce a quanto diciamo in questa lettera, prendete nota di lui e interrompete i rapporti, perché si vergogni;"],
[3015,"non trattatelo però come un nemico, ma ammonitelo come un fratello."],
[3016,"Il Signore della pace vi dia la pace sempre e in ogni modo. Il Signore sia con tutti voi."],
[3017,"Il saluto è di mia mano, di Paolo. Questo è il segno autografo di ogni mia lettera; io scrivo così."],
[3018,"La grazia del Signore nostro Gesù Cristo sia con tutti voi."]
])
