Bib.ret([
[1001,"Parole di Amos, che era allevatore di pecore, di Tekoa, il quale ebbe visioni riguardo a Israele, al tempo di Ozia, re di Giuda, e al tempo di Geroboamo, figlio di Ioas, re d'Israele, due anni prima del terremoto."],
[1002,"Egli disse: \"Il Signore ruggirà da Sion e da Gerusalemme farà udire la sua voce; saranno avvizziti i pascoli dei pastori, sarà inaridita la cima del Carmelo\"."],
[1003,"Così dice il Signore: \"Per tre misfatti di Damasco e per quattro non revocherò il mio decreto di condanna, perché hanno trebbiato Galaad con trebbie ferrate."],
[1004,"Alla casa di Cazael manderò il fuoco e divorerà i palazzi di Ben-Adad;"],
[1005,"spezzerò il catenaccio di Damasco, sterminerò chi siede sul trono di Bikat-Aven e chi detiene lo scettro di Bet-Eden, e il popolo di Aram sarà deportato in esilio a Kir\", dice il Signore."],
[1006,"Così dice il Signore: \"Per tre misfatti di Gaza e per quattro non revocherò il mio decreto di condanna, perché hanno deportato popolazioni intere per consegnarle a Edom."],
[1007,"Manderò il fuoco alle mura di Gaza e divorerà i suoi palazzi,"],
[1008,"sterminerò chi siede sul trono di Asdod e chi detiene lo scettro di Àscalon; rivolgerò la mia mano contro Ekron e così perirà il resto dei Filistei\", dice il Signore."],
[1009,"Così dice il Signore: \"Per tre misfatti di Tiro e per quattro non revocherò il mio decreto di condanna, perché hanno deportato popolazioni intere a Edom, senza ricordare l'alleanza fraterna."],
[1010,"Manderò il fuoco alle mura di Tiro e divorerà i suoi palazzi\"."],
[1011,"Così dice il Signore: \"Per tre misfatti di Edom e per quattro non revocherò il mio decreto di condanna, perché ha inseguito con la spada suo fratello e ha soffocato la pietà verso di lui, perché la sua ira ha sbranato senza fine e ha conservato lo sdegno per sempre."],
[1012,"Manderò il fuoco a Teman e divorerà i palazzi di Bosra\"."],
[1013,"Così dice il Signore: \"Per tre misfatti degli Ammoniti e per quattro non revocherò il mio decreto di condanna, perché hanno sventrato le donne incinte di Galaad per allargare il loro confine."],
[1014,"Darò fuoco alle mura di Rabbà e divorerà i suoi palazzi, tra il fragore di un giorno di battaglia, fra il turbine di un giorno di tempesta."],
[1015,"Il loro re andrà in esilio, egli insieme ai suoi comandanti\", dice il Signore."],
[2001,"Così dice il Signore: \"Per tre misfatti di Moab e per quattro non revocherò il mio decreto di condanna, perché ha bruciato le ossa del re di Edom per ridurle in calce."],
[2002,"Manderò il fuoco a Moab e divorerà i palazzi di Keriot e Moab morirà nel tumulto, al grido di guerra, al suono del corno."],
[2003,"Eliminerò dal suo seno chi governa, ucciderò, insieme con lui, tutti i suoi principi\", dice il Signore."],
[2004,"Così dice il Signore: \"Per tre misfatti di Giuda e per quattro non revocherò il mio decreto di condanna, perché hanno rifiutato la legge del Signore e non ne hanno osservato i precetti, si sono lasciati traviare dagli idoli che i loro padri avevano seguito."],
[2005,"Manderò il fuoco a Giuda e divorerà i palazzi di Gerusalemme\"."],
[2006,"Così dice il Signore: \"Per tre misfatti d'Israele e per quattro non revocherò il mio decreto di condanna, perché hanno venduto il giusto per denaro e il povero per un paio di sandali,"],
[2007,"essi che calpestano come la polvere della terra la testa dei poveri e fanno deviare il cammino dei miseri, e padre e figlio vanno dalla stessa ragazza, profanando così il mio santo nome."],
[2008,"Su vesti prese come pegno si stendono presso ogni altare e bevono il vino confiscato come ammenda nella casa del loro Dio."],
[2009,"Eppure io ho sterminato davanti a loro l'Amorreo, la cui statura era come quella dei cedri e la forza come quella della quercia; ho strappato i suoi frutti in alto e le sue radici di sotto."],
[2010,"Io vi ho fatto salire dalla terra d'Egitto e vi ho condotto per quarant'anni nel deserto, per darvi in possesso la terra dell'Amorreo."],
[2011,"Ho fatto sorgere profeti fra i vostri figli e nazirei fra i vostri giovani. Non è forse così, o figli d'Israele? Oracolo del Signore."],
[2012,"Ma voi avete fatto bere vino ai nazirei e ai profeti avete ordinato: \"Non profetate!\"."],
[2013,"Ecco, vi farò affondare nella terra, come affonda un carro quando è tutto carico di covoni."],
[2014,"Allora nemmeno l'uomo agile potrà più fuggire né l'uomo forte usare la sua forza, il prode non salverà la sua vita"],
[2015,"né l'arciere resisterà, non si salverà il corridore né il cavaliere salverà la sua vita."],
[2016,"Il più coraggioso fra i prodi fuggirà nudo in quel giorno!\". Oracolo del Signore."],
[3001,"Ascoltate questa parola, che il Signore ha detto riguardo a voi, figli d'Israele, e riguardo a tutta la stirpe che ho fatto salire dall'Egitto:"],
[3002,"\"Soltanto voi ho conosciuto tra tutte le stirpi della terra; perciò io vi farò scontare tutte le vostre colpe."],
[3003,"Camminano forse due uomini insieme, senza essersi messi d'accordo?"],
[3004,"Ruggisce forse il leone nella foresta, se non ha qualche preda? Il leoncello manda un grido dalla sua tana, se non ha preso nulla?"],
[3005,"Si precipita forse un uccello a terra in una trappola, senza che vi sia un'esca? Scatta forse la trappola dal suolo, se non ha preso qualche cosa?"],
[3006,"Risuona forse il corno nella città, senza che il popolo si metta in allarme? Avviene forse nella città una sventura, che non sia causata dal Signore?"],
[3007,"In verità, il Signore non fa cosa alcuna senza aver rivelato il suo piano ai suoi servitori, i profeti."],
[3008,"Ruggisce il leone: chi non tremerà? Il Signore Dio ha parlato: chi non profeterà?"],
[3009,"Fatelo udire nei palazzi di Asdod e nei palazzi della terra d'Egitto e dite: \"Adunatevi sui monti di Samaria e osservate quanti disordini sono in essa e quali violenze sono nel suo seno\"."],
[3010,"Non sanno agire con rettitudine - oracolo del Signore -; violenza e rapina accumulano nei loro palazzi\"."],
[3011,"Perciò così dice il Signore Dio: \"Il nemico circonderà il paese, sarà abbattuta la tua potenza e i tuoi palazzi saranno saccheggiati\"."],
[3012,"Così dice il Signore: \"Come il pastore strappa dalla bocca del leone due zampe o il lobo d'un orecchio, così scamperanno i figli d'Israele che siedono a Samaria nell'angolo di un letto, sulla sponda di un divano."],
[3013,"Ascoltate e attestatelo nella casa di Giacobbe, oracolo del Signore Dio, Dio degli eserciti:"],
[3014,"Quando colpirò Israele per i suoi misfatti, colpirò gli altari di Betel; saranno spezzati i corni dell'altare e cadranno a terra."],
[3015,"Demolirò la casa d'inverno insieme con la casa d'estate, e andranno in rovina le case d'avorio e scompariranno i grandi palazzi\". Oracolo del Signore."],
[4001,"Ascoltate questa parola, o vacche di Basan, che siete sul monte di Samaria, che opprimete i deboli, schiacciate i poveri e dite ai vostri mariti: \"Porta qua, beviamo!\"."],
[4002,"Il Signore Dio ha giurato per la sua santità: \"Ecco, verranno per voi giorni in cui sarete portate via con uncini e le rimanenti di voi con arpioni da pesca."],
[4003,"Uscirete per le brecce, una dopo l'altra, e sarete cacciate oltre l'Ermon\". Oracolo del Signore."],
[4004,"\"Andate pure a Betel e peccate, a Galgala e peccate ancora di più! Offrite ogni mattina i vostri sacrifici e ogni tre giorni le vostre decime."],
[4005,"Offrite anche sacrifici di lode con pane lievitato e proclamate ad alta voce le offerte spontanee, perché così vi piace fare, o figli d'Israele\". Oracolo del Signore Dio."],
[4006,"\"Eppure, vi ho lasciato a denti asciutti in tutte le vostre città, e con mancanza di pane in tutti i vostri villaggi; ma non siete ritornati a me\". Oracolo del Signore."],
[4007,"\"Vi ho pure rifiutato la pioggia tre mesi prima della mietitura, facevo piovere sopra una città e non sopra l'altra; un campo era bagnato di pioggia, mentre l'altro, su cui non pioveva, seccava."],
[4008,"Due, tre città andavano barcollanti verso un'altra città per bervi acqua, senza potersi dissetare; ma non siete ritornati a me\". Oracolo del Signore."],
[4009,"\"Vi ho colpiti con ruggine e carbonchio, vi ho inaridito i giardini e le vigne; i fichi e gli olivi li ha divorati la cavalletta; ma non siete ritornati a me\". Oracolo del Signore."],
[4010,"\"Ho mandato contro di voi la peste, come un tempo contro l'Egitto, ho ucciso di spada i vostri giovani, mentre i vostri cavalli diventavano preda; ho fatto salire il fetore dai vostri campi fino alle vostre narici; ma non siete ritornati a me\". Oracolo del Signore."],
[4011,"\"Vi ho travolti come Dio aveva travolto Sodoma e Gomorra, eravate come un tizzone strappato da un incendio; ma non siete ritornati a me\". Oracolo del Signore."],
[4012,"Perciò ti tratterò così, Israele! Poiché questo devo fare di te: preparati all'incontro con il tuo Dio, o Israele!"],
[4013,"Ecco colui che forma i monti e crea i venti, che manifesta all'uomo qual è il suo pensiero, che muta l'aurora in tenebre e cammina sulle alture della terra, Signore, Dio degli eserciti è il suo nome."],
[5001,"Ascoltate questa parola, questo lamento che io elevo su di voi, o casa d'Israele!"],
[5002,"È caduta, non si alzerà più, la vergine d'Israele; è stesa al suolo, nessuno la fa rialzare."],
[5003,"Poiché così dice il Signore Dio: \"La città che mandava in guerra mille uomini resterà con cento, e la città che ne mandava cento per la casa d'Israele, resterà con dieci\"."],
[5004,"Poiché così dice il Signore alla casa d'Israele: \"Cercate me e vivrete!"],
[5005,"Non cercate Betel, non andate a Galgala, non passate a Bersabea, perché Galgala andrà certo in esilio e Betel sarà ridotta al nulla\"."],
[5006,"Cercate il Signore e vivrete, altrimenti egli, come un fuoco,  brucerà la casa di Giuseppe, la divorerà e nessuno spegnerà Betel!"],
[5007,"Essi trasformano il diritto in assenzio e gettano a terra la giustizia."],
[5008,"Colui che ha fatto le Pleiadi e Orione, cambia il buio in chiarore del mattino e il giorno nell'oscurità della notte, colui che chiama a raccolta le acque del mare e le riversa sulla terra, Signore è il suo nome."],
[5009,"Egli fa cadere la rovina sull'uomo potente e fa giungere la devastazione sulle fortezze."],
[5010,"Essi odiano chi fa giuste accuse in tribunale e detestano chi testimonia secondo verità."],
[5011,"Poiché voi schiacciate l'indigente e gli estorcete una parte del grano, voi che avete costruito case in pietra squadrata, non le abiterete; voi che avete innalzato vigne deliziose, non ne berrete il vino."],
[5012,"So infatti quanto numerosi sono i vostri misfatti, quanto enormi i vostri peccati. Essi sono ostili verso il giusto, prendono compensi illeciti e respingono i poveri nel tribunale."],
[5013,"Perciò il prudente in questo tempo tacerà, perché sarà un tempo di calamità."],
[5014,"Cercate il bene e non il male, se volete vivere, e solo così il Signore, Dio degli eserciti, sarà con voi, come voi dite."],
[5015,"Odiate il male e amate il bene e ristabilite nei tribunali il diritto; forse il Signore, Dio degli eserciti, avrà pietà del resto di Giuseppe."],
[5016,"Perciò così dice il Signore, Dio degli eserciti, il Signore: \"In tutte le piazze vi sarà lamento, in tutte le strade si dirà: \"Ohimè! ohimè!\". Si chiameranno i contadini a fare il lutto e quelli che conoscono la nenia a fare il lamento."],
[5017,"In tutte le vigne vi sarà lamento, quando io passerò in mezzo a te\", dice il Signore."],
[5018,"Guai a coloro che attendono il giorno del Signore! Che cosa sarà per voi il giorno del Signore? Tenebre e non luce!"],
[5019,"Come quando uno fugge davanti al leone e s'imbatte in un orso; come quando entra in casa, appoggia la mano sul muro e un serpente lo morde."],
[5020,"Non sarà forse tenebra, non luce, il giorno del Signore? Oscurità, senza splendore alcuno?"],
[5021,"\"Io detesto, respingo le vostre feste solenni e non gradisco le vostre riunioni sacre;"],
[5022,"anche se voi mi offrite olocausti, io non gradisco le vostre offerte, e le vittime grasse come pacificazione io non le guardo."],
[5023,"Lontano da me il frastuono dei vostri canti: il suono delle vostre arpe non posso sentirlo!"],
[5024,"Piuttosto come le acque scorra il diritto e la giustizia come un torrente perenne."],
[5025,"Mi avete forse presentato sacrifici e offerte nel deserto per quarant'anni, o Israeliti?"],
[5026,"Voi avete innalzato Siccut come vostro re e Chiion come vostro idolo, e Stella come vostra divinità: tutte cose fatte da voi."],
[5027,"Ora, io vi manderò in esilio al di là di Damasco\",  dice il Signore, il cui nome è Dio degli eserciti."],
[6001,"Guai agli spensierati di Sion e a quelli che si considerano sicuri sulla montagna di Samaria! Questi notabili della prima tra le nazioni, ai quali si rivolge la casa d'Israele!"],
[6002,"Andate a vedere la città di Calne, da lì andate a Camat, la grande, e scendete a Gat dei Filistei: siete voi forse migliori di quei regni o il loro territorio è più grande del vostro?"],
[6003,"Voi credete di ritardare il giorno fatale e invece affrettate il regno della violenza."],
[6004,"Distesi su letti d'avorio e sdraiati sui loro divani mangiano gli agnelli del gregge e i vitelli cresciuti nella stalla."],
[6005,"Canterellano al suono dell'arpa, come Davide improvvisano su strumenti musicali;"],
[6006,"bevono il vino in larghe coppe e si ungono con gli unguenti più raffinati, ma della rovina di Giuseppe non si preoccupano."],
[6007,"Perciò ora andranno in esilio in testa ai deportati e cesserà l'orgia dei dissoluti."],
[6008,"Ha giurato il Signore Dio, per se stesso! Oracolo del Signore, Dio degli eserciti. \"Detesto l'orgoglio di Giacobbe, odio i suoi palazzi, consegnerò al nemico la città e quanto contiene\"."],
[6009,"Se sopravvivranno in una sola casa dieci uomini, anch'essi moriranno."],
[6010,"Lo prenderà il suo parente e chi prepara il rogo, per portare via le ossa dalla casa; dirà a chi è in fondo alla casa: \"C'è ancora qualcuno con te?\". L'altro risponderà: \"No\". Ed egli dirà: \"Silenzio!\", perché non si pronunci il nome del Signore."],
[6011,"Poiché ecco: il Signore comanda di fare a pezzi la casa grande, e quella piccola di ridurla in frantumi."],
[6012,"Corrono forse i cavalli sulla roccia e si ara il mare con i buoi? Poiché voi cambiate il diritto in veleno e il frutto della giustizia in assenzio."],
[6013,"Voi vi compiacete di Lodebar dicendo: \"Non abbiamo forse conquistato Karnaim con la nostra forza?\"."],
[6014,"\"Ora, ecco, io susciterò contro di voi, casa d'Israele - oracolo del Signore, Dio degli eserciti -, un popolo che vi opprimerà dall'ingresso di Camat fino al torrente dell'Araba\"."],
[7001,"Ecco ciò che mi fece vedere il Signore Dio: quando cominciava a germogliare la seconda erba, quella che spunta dopo la falciatura per il re, egli formava uno sciame di cavallette."],
[7002,"Quando quelle stavano per finire di divorare l'erba della regione, io dissi: \"Signore Dio, perdona! Come potrà resistere Giacobbe? È tanto piccolo\"."],
[7003,"Il Signore allora si ravvide: \"Questo non avverrà\", disse il Signore."],
[7004,"Ecco ciò che mi fece vedere il Signore Dio: il Signore Dio chiamava a una lite per mezzo del fuoco che consumava il grande abisso e divorava la campagna."],
[7005,"Io dissi: \"Signore Dio, desisti! Come potrà resistere Giacobbe? È tanto piccolo\"."],
[7006,"Il Signore allora si ravvide: \"Neanche questo avverrà\", disse il Signore Dio."],
[7007,"Ecco ciò che mi fece vedere il Signore Dio: il Signore stava sopra un muro tirato a piombo e con un filo a piombo in mano."],
[7008,"Il Signore mi disse: \"Che cosa vedi, Amos?\". Io risposi: \"Un filo a piombo\". Il Signore mi disse: \"Io pongo un filo a piombo in mezzo al mio popolo, Israele; non gli perdonerò più."],
[7009,"Saranno demolite le alture d'Isacco e saranno ridotti in rovina i santuari d'Israele, quando io mi leverò con la spada contro la casa di Geroboamo\"."],
[7010,"Amasia, sacerdote di Betel, mandò a dire a Geroboamo, re d'Israele: \"Amos congiura contro di te, in mezzo alla casa d'Israele; il paese non può sopportare le sue parole,"],
[7011,"poiché così dice Amos: \"Di spada morirà Geroboamo, e Israele sarà condotto in esilio lontano dalla sua terra\"\"."],
[7012,"Amasia disse ad Amos: \"Vattene, veggente, ritirati nella terra di Giuda; là mangerai il tuo pane e là potrai profetizzare,"],
[7013,"ma a Betel non profetizzare più, perché questo è il santuario del re ed è il tempio del regno\"."],
[7014,"Amos rispose ad Amasia e disse: \"Non ero profeta né figlio di profeta; ero un mandriano e coltivavo piante di sicomoro."],
[7015,"Il Signore mi prese, mi chiamò mentre seguivo il gregge. Il Signore mi disse: Va', profetizza al mio popolo Israele."],
[7016,"Ora ascolta la parola del Signore: Tu dici: \"Non profetizzare contro Israele, non parlare contro la casa d'Isacco\"."],
[7017,"Ebbene, dice il Signore: \"Tua moglie diventerà una prostituta nella città, i tuoi figli e le tue figlie cadranno di spada, la tua terra sarà divisa con la corda in più proprietà; tu morirai in terra impura e Israele sarà deportato in esilio lontano dalla sua terra\"\"."],
[8001,"Ecco ciò che mi fece vedere il Signore Dio: era un canestro di frutta matura."],
[8002,"Egli domandò: \"Che cosa vedi, Amos?\". Io risposi: \"Un canestro di frutta matura\". Il Signore mi disse: \"È maturata la fine per il mio popolo, Israele; non gli perdonerò più."],
[8003,"In quel giorno i canti del tempio diventeranno lamenti. Oracolo del Signore Dio. Numerosi i cadaveri, gettati dovunque. Silenzio!"],
[8004,"Ascoltate questo, voi che calpestate il povero e sterminate gli umili del paese,"],
[8005,"voi che dite: \"Quando sarà passato il novilunio e si potrà vendere il grano? E il sabato, perché si possa smerciare il frumento, diminuendo l' efa e aumentando il siclo e usando bilance false,"],
[8006,"per comprare con denaro gli indigenti e il povero per un paio di sandali? Venderemo anche lo scarto del grano\"\"."],
[8007,"Il Signore lo giura per il vanto di Giacobbe: \"Certo, non dimenticherò mai tutte le loro opere."],
[8008,"Non trema forse per questo la terra, sono in lutto tutti i suoi abitanti, si solleva tutta come il Nilo, si agita e si abbassa come il Nilo d'Egitto?"],
[8009,"In quel giorno - oracolo del Signore Dio - farò tramontare il sole a mezzogiorno e oscurerò la terra in pieno giorno!"],
[8010,"Cambierò le vostre feste in lutto e tutti i vostri canti in lamento: farò vestire ad ogni fianco il sacco, farò radere tutte le teste: ne farò come un lutto per un figlio unico e la sua fine sarà come un giorno d'amarezza."],
[8011,"Ecco, verranno giorni - oracolo del Signore Dio - in cui manderò la fame nel paese; non fame di pane né sete di acqua, ma di ascoltare le parole del Signore\"."],
[8012,"Allora andranno errando da un mare all'altro e vagheranno da settentrione a oriente, per cercare la parola del Signore, ma non la troveranno."],
[8013,"In quel giorno verranno meno per la sete le belle fanciulle e i giovani."],
[8014,"Quelli che giurano per il peccato di Samaria e dicono: \"Viva il tuo Dio, Dan!\", oppure: \"Viva la via sacra per Bersabea!\", cadranno senza più rialzarsi!"],
[9001,"Vidi il Signore che stava sopra l'altare e diceva: \"Colpisci con forza i capitelli e siano scossi gli architravi, falli cadere sulla testa di tutti e io ucciderò il resto con la spada; nessuno di loro riuscirà a fuggire, nessuno di loro scamperà."],
[9002,"Anche se si rifugiassero negli inferi, di là li prenderà la mia mano; se salissero al cielo, di là li tirerò giù;"],
[9003,"se si nascondessero in cima al Carmelo, là li scoverò e li prenderò; se si occultassero al mio sguardo in fondo al mare, là comanderò al serpente di morderli;"],
[9004,"se andassero in schiavitù davanti ai loro nemici, là comanderò alla spada di ucciderli. Io volgerò il mio sguardo su di loro in male e non in bene\"."],
[9005,"Il Signore, Dio degli eserciti, colpisce la terra ed essa vacilla e sono in lutto tutti i suoi abitanti; essa si solleva tutta come il Nilo e si abbassa come il Nilo d'Egitto."],
[9006,"Egli costruisce nei cieli il suo palazzo e fonda la sua volta sulla terra; egli chiama a raccolta le acque del mare e le riversa sulla terra. Signore è il suo nome."],
[9007,"\"Non siete voi per me come gli Etiopi, figli d'Israele?  Oracolo del Signore. Non sono io che ho fatto uscire Israele dal paese d'Egitto, i Filistei da Caftor e gli Aramei da Kir?"],
[9008,"Ecco, lo sguardo del Signore Dio è rivolto contro il regno peccatore: io lo sterminerò dalla terra, ma non sterminerò del tutto la casa di Giacobbe. Oracolo del Signore."],
[9009,"Ecco, infatti, io darò ordini e scuoterò, fra tutti i popoli, la casa d'Israele come si scuote il setaccio e non cade un sassolino per terra."],
[9010,"Di spada periranno tutti i peccatori del mio popolo, essi che dicevano: \"Non si avvicinerà, non giungerà fino a noi la sventura\"."],
[9011,"In quel giorno rialzerò la capanna di Davide, che è cadente; ne riparerò le brecce, ne rialzerò le rovine, la ricostruirò come ai tempi antichi,"],
[9012,"perché conquistino il resto di Edom e tutte le nazioni sulle quali è stato invocato il mio nome. Oracolo del Signore, che farà tutto questo."],
[9013,"Ecco, verranno giorni - oracolo del Signore - in cui chi ara s'incontrerà con chi miete e chi pigia l'uva con chi getta il seme; i monti stilleranno il vino nuovo e le colline si scioglieranno."],
[9014,"Muterò le sorti del mio popolo Israele, ricostruiranno le città devastate e vi abiteranno, pianteranno vigne e ne berranno il vino, coltiveranno giardini e ne mangeranno il frutto."],
[9015,"Li pianterò nella loro terra e non saranno mai divelti da quel suolo che io ho dato loro\", dice il Signore, tuo Dio."]
])
