Bib.ret([
[1001,"Cantico dei Cantici, di Salomone."],
[1002,"Mi baci con i baci della sua bocca! Sì, migliore del vino è il tuo amore."],
[1003,"Inebrianti sono i tuoi profumi per la fragranza, aroma che si spande è il tuo nome: per questo le ragazze di te si innamorano."],
[1004,"Trascinami con te, corriamo! M'introduca il re nelle sue stanze: gioiremo e ci rallegreremo di te, ricorderemo il tuo amore più del vino. A ragione di te ci si innamora!"],
[1005,"Bruna sono ma bella, o figlie di Gerusalemme, come le tende di Kedar, come le cortine di Salomone."],
[1006,"Non state a guardare se sono bruna, perché il sole mi ha abbronzato. I figli di mia madre si sono sdegnati con me: mi hanno messo a guardia delle vigne; la mia vigna, la mia, non l'ho custodita."],
[1007,"Dimmi, o amore dell'anima mia, dove vai a pascolare le greggi, dove le fai riposare al meriggio, perché io non debba vagare dietro le greggi dei tuoi compagni?"],
[1008,"Se non lo sai tu, bellissima tra le donne, segui le orme del gregge e pascola le tue caprette presso gli accampamenti dei pastori."],
[1009,"Alla puledra del cocchio del faraone io ti assomiglio, amica mia."],
[1010,"Belle sono le tue guance fra gli orecchini, il tuo collo tra i fili di perle."],
[1011,"Faremo per te orecchini d'oro, con grani d'argento."],
[1012,"Mentre il re è sul suo divano, il mio nardo effonde il suo profumo."],
[1013,"L'amato mio è per me un sacchetto di mirra, passa la notte tra i miei seni."],
[1014,"L'amato mio è per me un grappolo di cipro nelle vigne di Engaddi."],
[1015,"Quanto sei bella, amata mia, quanto sei bella! Gli occhi tuoi sono colombe."],
[1016,"Come sei bello, amato mio, quanto grazioso! Erba verde è il nostro letto,"],
[1017,"di cedro sono le travi della nostra casa, di cipresso il nostro soffitto."],
[2001,"Io sono un narciso della pianura di Saron, un giglio delle valli."],
[2002,"Come un giglio fra i rovi, così l'amica mia tra le ragazze."],
[2003,"Come un melo tra gli alberi del bosco, così l'amato mio tra i giovani. Alla sua ombra desiderata mi siedo, è dolce il suo frutto al mio palato."],
[2004,"Mi ha introdotto nella cella del vino e il suo vessillo su di me è amore."],
[2005,"Sostenetemi con focacce d'uva passa, rinfrancatemi con mele, perché io sono malata d'amore."],
[2006,"La sua sinistra è sotto il mio capo e la sua destra mi abbraccia."],
[2007,"Io vi scongiuro, figlie di Gerusalemme, per le gazzelle o per le cerve dei campi: non destate, non scuotete dal sonno l'amore, finché non lo desideri."],
[2008,"Una voce! L'amato mio! Eccolo, viene saltando per i monti, balzando per le colline."],
[2009,"L'amato mio somiglia a una gazzella o ad un cerbiatto. Eccolo, egli sta dietro il nostro muro; guarda dalla finestra, spia dalle inferriate."],
[2010,"Ora l'amato mio prende a dirmi: \"Àlzati, amica mia, mia bella, e vieni, presto!"],
[2011,"Perché, ecco, l'inverno è passato, è cessata la pioggia, se n'è andata;"],
[2012,"i fiori sono apparsi nei campi, il tempo del canto è tornato e la voce della tortora ancora si fa sentire nella nostra campagna."],
[2013,"Il fico sta maturando i primi frutti e le viti in fiore spandono profumo. Àlzati, amica mia, mia bella, e vieni, presto!"],
[2014,"O mia colomba, che stai nelle fenditure della roccia, nei nascondigli dei dirupi, mostrami il tuo viso, fammi sentire la tua voce, perché la tua voce è soave, il tuo viso è incantevole\"."],
[2015,"Prendeteci le volpi, le volpi piccoline che devastano le vigne: le nostre vigne sono in fiore."],
[2016,"Il mio amato è mio e io sono sua; egli pascola fra i gigli."],
[2017,"Prima che spiri la brezza del giorno e si allunghino le ombre, ritorna, amato mio, simile a gazzella o a cerbiatto, sopra i monti degli aromi."],
[3001,"Sul mio letto, lungo la notte, ho cercato l'amore dell'anima mia; l'ho cercato, ma non l'ho trovato."],
[3002,"Mi alzerò e farò il giro della città per le strade e per le piazze; voglio cercare l'amore dell'anima mia. L'ho cercato, ma non l'ho trovato."],
[3003,"Mi hanno incontrata le guardie che fanno la ronda in città: \"Avete visto l'amore dell'anima mia?\"."],
[3004,"Da poco le avevo oltrepassate, quando trovai l'amore dell'anima mia. Lo strinsi forte e non lo lascerò, finché non l'abbia condotto nella casa di mia madre, nella stanza di colei che mi ha concepito."],
[3005,"Io vi scongiuro, figlie di Gerusalemme, per le gazzelle o per le cerve dei campi: non destate, non scuotete dal sonno l'amore, finché non lo desideri."],
[3006,"Chi sta salendo dal deserto come una colonna di fumo, esalando profumo di mirra e d'incenso e d'ogni polvere di mercanti?"],
[3007,"Ecco, la lettiga di Salomone: sessanta uomini prodi le stanno intorno, tra i più valorosi d'Israele."],
[3008,"Tutti sanno maneggiare la spada, esperti nella guerra; ognuno porta la spada al fianco contro il terrore della notte."],
[3009,"Un baldacchino si è fatto il re Salomone con legno del Libano."],
[3010,"Le sue colonne le ha fatte d'argento, d'oro la sua spalliera; il suo seggio è di porpora, il suo interno è un ricamo d'amore delle figlie di Gerusalemme."],
[3011,"Uscite, figlie di Sion, guardate il re Salomone con la corona di cui lo cinse sua madre nel giorno delle sue nozze, giorno di letizia del suo cuore."],
[4001,"Quanto sei bella, amata mia, quanto sei bella! Gli occhi tuoi sono colombe, dietro il tuo velo. Le tue chiome sono come un gregge di capre, che scendono dal monte Galaad."],
[4002,"I tuoi denti come un gregge di pecore tosate, che risalgono dal bagno; tutte hanno gemelli, nessuna di loro è senza figli."],
[4003,"Come nastro di porpora le tue labbra, la tua bocca è piena di fascino; come spicchio di melagrana è la tua tempia dietro il tuo velo."],
[4004,"Il tuo collo è come la torre di Davide, costruita a strati. Mille scudi vi sono appesi, tutte armature di eroi."],
[4005,"I tuoi seni sono come due cerbiatti, gemelli di una gazzella, che pascolano tra i gigli."],
[4006,"Prima che spiri la brezza del giorno e si allunghino le ombre, me ne andrò sul monte della mirra e sul colle dell'incenso."],
[4007,"Tutta bella sei tu, amata mia, e in te non vi è difetto."],
[4008,"Vieni dal Libano, o sposa, vieni dal Libano, vieni! Scendi dalla vetta dell'Amana, dalla cima del Senir e dell'Ermon, dalle spelonche dei leoni, dai monti dei leopardi."],
[4009,"Tu mi hai rapito il cuore, sorella mia, mia sposa, tu mi hai rapito il cuore con un solo tuo sguardo, con una perla sola della tua collana!"],
[4010,"Quanto è soave il tuo amore, sorella mia, mia sposa, quanto più inebriante del vino è il tuo amore, e il profumo dei tuoi unguenti, più di ogni balsamo."],
[4011,"Le tue labbra stillano nettare, o sposa, c'è miele e latte sotto la tua lingua e il profumo delle tue vesti è come quello del Libano."],
[4012,"Giardino chiuso tu sei, sorella mia, mia sposa, sorgente chiusa, fontana sigillata."],
[4013,"I tuoi germogli sono un paradiso di melagrane, con i frutti più squisiti, alberi di cipro e nardo,"],
[4014,"nardo e zafferano, cannella e cinnamomo, con ogni specie di alberi d'incenso, mirra e aloe, con tutti gli aromi migliori."],
[4015,"Fontana che irrora i giardini, pozzo d'acque vive che sgorgano dal Libano."],
[4016,"Àlzati, vento del settentrione, vieni, vieni vento del meridione,  soffia nel mio giardino, si effondano i suoi aromi. Venga l'amato mio nel suo giardino e ne mangi i frutti squisiti."],
[5001,"Sono venuto nel mio giardino, sorella mia, mia sposa, e raccolgo la mia mirra e il mio balsamo; mangio il mio favo e il mio miele, bevo il mio vino e il mio latte. Mangiate, amici, bevete; inebriatevi d'amore."],
[5002,"Mi sono addormentata, ma veglia il mio cuore. Un rumore! La voce del mio amato che bussa: \"Aprimi, sorella mia, mia amica, mia colomba, mio tutto; perché il mio capo è madido di rugiada, i miei riccioli di gocce notturne\"."],
[5003,"\"Mi sono tolta la veste; come indossarla di nuovo? Mi sono lavata i piedi; come sporcarli di nuovo?\"."],
[5004,"L'amato mio ha introdotto la mano nella fessura e le mie viscere fremettero per lui."],
[5005,"Mi sono alzata per aprire al mio amato e le mie mani stillavano mirra; fluiva mirra dalle mie dita sulla maniglia del chiavistello."],
[5006,"Ho aperto allora all'amato mio, ma l'amato mio se n'era andato, era scomparso. Io venni meno, per la sua scomparsa; l'ho cercato, ma non l'ho trovato, l'ho chiamato, ma non mi ha risposto."],
[5007,"Mi hanno incontrata le guardie che fanno la ronda in città; mi hanno percossa, mi hanno ferita, mi hanno tolto il mantello le guardie delle mura."],
[5008,"Io vi scongiuro, figlie di Gerusalemme, se trovate l'amato mio che cosa gli racconterete? Che sono malata d'amore!"],
[5009,"Che cosa ha il tuo amato più di ogni altro, tu che sei bellissima tra le donne? Che cosa ha il tuo amato più di ogni altro, perché così ci scongiuri?"],
[5010,"L'amato mio è bianco e vermiglio, riconoscibile fra una miriade."],
[5011,"Il suo capo è oro, oro puro, i suoi riccioli sono grappoli di palma, neri come il corvo."],
[5012,"I suoi occhi sono come colombe su ruscelli d'acqua; i suoi denti si bagnano nel latte, si posano sui bordi."],
[5013,"Le sue guance sono come aiuole di balsamo dove crescono piante aromatiche, le sue labbra sono gigli che stillano fluida mirra."],
[5014,"Le sue mani sono anelli d'oro, incastonati di gemme di Tarsis. Il suo ventre è tutto d'avorio, tempestato di zaffiri."],
[5015,"Le sue gambe, colonne di alabastro, posate su basi d'oro puro. Il suo aspetto è quello del Libano, magnifico come i cedri."],
[5016,"Dolcezza è il suo palato; egli è tutto delizie! Questo è l'amato mio, questo l'amico mio, o figlie di Gerusalemme."],
[6001,"Dov'è andato il tuo amato, tu che sei bellissima tra le donne? Dove ha diretto i suoi passi il tuo amato, perché lo cerchiamo con te?"],
[6002,"L'amato mio è sceso nel suo giardino fra le aiuole di balsamo, a pascolare nei giardini e a cogliere gigli."],
[6003,"Io sono del mio amato e il mio amato è mio; egli pascola tra i gigli."],
[6004,"Tu sei bella, amica mia, come la città di Tirsa, incantevole come Gerusalemme, terribile come un vessillo di guerra."],
[6005,"Distogli da me i tuoi occhi, perché mi sconvolgono. Le tue chiome sono come un gregge di capre che scendono dal Galaad."],
[6006,"I tuoi denti come un gregge di pecore che risalgono dal bagno; tutte hanno gemelli, nessuna di loro è senza figli."],
[6007,"Come spicchio di melagrana è la tua tempia, dietro il tuo velo."],
[6008,"Siano pure sessanta le mogli del re, ottanta le concubine, innumerevoli le ragazze!"],
[6009,"Ma unica è la mia colomba, il mio tutto, unica per sua madre, la preferita di colei che l'ha generata. La vedono le giovani e la dicono beata. Le regine e le concubine la coprono di lodi:"],
[6010,"\"Chi è costei che sorge come l'aurora, bella come la luna, fulgida come il sole, terribile come un vessillo di guerra?\"."],
[6011,"Nel giardino dei noci io sono sceso, per vedere i germogli della valle e osservare se la vite metteva gemme e i melograni erano in fiore."],
[6012,"Senza che me ne accorgessi, il desiderio mi ha posto sul cocchio del principe del mio popolo."],
[7001,"Voltati, voltati, Sulammita, voltati, voltati: vogliamo ammirarti. Che cosa volete ammirare nella Sulammita durante la danza a due cori?"],
[7002,"Come sono belli i tuoi piedi nei sandali, figlia di principe! Le curve dei tuoi fianchi sono come monili, opera di mani d'artista."],
[7003,"Il tuo ombelico è una coppa rotonda che non manca mai di vino aromatico. Il tuo ventre è un covone di grano, circondato da gigli."],
[7004,"I tuoi seni sono come due cerbiatti, gemelli di una gazzella."],
[7005,"Il tuo collo come una torre d'avorio, i tuoi occhi come le piscine di Chesbon presso la porta di Bat-Rabbim, il tuo naso come la torre del Libano che guarda verso Damasco."],
[7006,"Il tuo capo si erge su di te come il Carmelo e la chioma del tuo capo è come porpora; un re è tutto preso dalle tue trecce."],
[7007,"Quanto sei bella e quanto sei graziosa, o amore, piena di delizie!"],
[7008,"La tua statura è slanciata come una palma e i tuoi seni sembrano grappoli."],
[7009,"Ho detto: \"Salirò sulla palma, coglierò i grappoli di datteri\". Siano per me i tuoi seni come grappoli d'uva e il tuo respiro come profumo di mele."],
[7010,"Il tuo palato è come vino squisito, che scorre morbidamente verso di me  e fluisce sulle labbra e sui denti!"],
[7011,"Io sono del mio amato e il suo desiderio è verso di me."],
[7012,"Vieni, amato mio, andiamo nei campi, passiamo la notte nei villaggi."],
[7013,"Di buon mattino andremo nelle vigne; vedremo se germoglia la vite, se le gemme si schiudono, se fioriscono i melograni: là ti darò il mio amore!"],
[7014,"Le mandragore mandano profumo; alle nostre porte c'è ogni specie di frutti squisiti, freschi e secchi: amato mio, li ho conservati per te."],
[8001,"Come vorrei che tu fossi mio fratello, allattato al seno di mia madre! Incontrandoti per strada ti potrei baciare senza che altri mi disprezzi."],
[8002,"Ti condurrei, ti introdurrei nella casa di mia madre; tu mi inizieresti all'arte dell'amore. Ti farei bere vino aromatico e succo del mio melograno."],
[8003,"La sua sinistra è sotto il mio capo e la sua destra mi abbraccia."],
[8004,"Io vi scongiuro, figlie di Gerusalemme, non destate, non scuotete dal sonno l'amore, finché non lo desideri."],
[8005,"Chi sta salendo dal deserto, appoggiata al suo amato? Sotto il melo ti ho svegliato; là dove ti concepì tua madre, là dove ti concepì colei che ti ha partorito."],
[8006,"Mettimi come sigillo sul tuo cuore, come sigillo sul tuo braccio; perché forte come la morte è l'amore, tenace come il regno dei morti è la passione: le sue vampe sono vampe di fuoco, una fiamma divina!"],
[8007,"Le grandi acque non possono spegnere l'amore né i fiumi travolgerlo. Se uno desse tutte le ricchezze della sua casa in cambio dell'amore, non ne avrebbe che disprezzo."],
[8008,"Una sorella piccola abbiamo, e ancora non ha seni. Che faremo per la nostra sorella nel giorno in cui si parlerà di lei?"],
[8009,"Se fosse un muro, le costruiremmo sopra una merlatura d'argento; se fosse una porta, la rafforzeremmo con tavole di cedro."],
[8010,"Io sono un muro e i miei seni sono come torri! Così io sono ai suoi occhi come colei che procura pace!"],
[8011,"Salomone aveva una vigna a Baal-Amon; egli affidò la vigna ai custodi. Ciascuno gli doveva portare come suo frutto mille pezzi d'argento."],
[8012,"La mia vigna, proprio la mia, mi sta davanti: tieni pure, Salomone, i mille pezzi d'argento e duecento per i custodi dei suoi frutti!"],
[8013,"Tu che abiti nei giardini, i compagni ascoltano la tua voce: fammela sentire."],
[8014,"Fuggi, amato mio, simile a gazzella o a cerbiatto sopra i monti dei balsami!"]
])
