Bib.ret([
[1001,"L'anno terzo del regno di Ioiakim, re di Giuda, Nabucodonosor, re di Babilonia, marciò su Gerusalemme e la cinse d'assedio."],
[1002,"Il Signore diede Ioiakim, re di Giuda, nelle sue mani, insieme con una parte degli arredi del tempio di Dio, ed egli li trasportò nel paese di Sinar, nel tempio del suo dio, e li depositò nel tesoro del tempio del suo dio."],
[1003,"Il re ordinò ad Asfenaz, capo dei suoi funzionari di corte, di condurgli giovani israeliti di stirpe regale o di famiglia nobile,"],
[1004,"senza difetti, di bell'aspetto, dotati di ogni sapienza, istruiti, intelligenti e tali da poter stare nella reggia, e di insegnare loro la scrittura e la lingua dei Caldei."],
[1005,"Il re assegnò loro una razione giornaliera delle sue vivande e del vino che egli beveva; dovevano essere educati per tre anni, al termine dei quali sarebbero entrati al servizio del re."],
[1006,"Fra loro vi erano alcuni Giudei: Daniele, Anania, Misaele e Azaria;"],
[1007,"però il capo dei funzionari di corte diede loro altri nomi, chiamando Daniele Baltassar, Anania Sadrac, Misaele Mesac e Azaria Abdenego."],
[1008,"Ma Daniele decise in cuor suo di non contaminarsi con le vivande del re e con il vino dei suoi banchetti e chiese al capo dei funzionari di non obbligarlo a contaminarsi."],
[1009,"Dio fece sì che Daniele incontrasse la benevolenza e la simpatia del capo dei funzionari."],
[1010,"Però egli disse a Daniele: \"Io temo che il re, mio signore, che ha stabilito quello che dovete mangiare e bere, trovi le vostre facce più magre di quelle degli altri giovani della vostra età e così mi rendereste responsabile davanti al re\"."],
[1011,"Ma Daniele disse al custode, al quale il capo dei funzionari aveva affidato Daniele, Anania, Misaele e Azaria:"],
[1012,"\"Mettici alla prova per dieci giorni, dandoci da mangiare verdure e da bere acqua,"],
[1013,"poi si confrontino, alla tua presenza, le nostre facce con quelle dei giovani che mangiano le vivande del re; quindi deciderai di fare con i tuoi servi come avrai constatato\"."],
[1014,"Egli acconsentì e fece la prova per dieci giorni,"],
[1015,"al termine dei quali si vide che le loro facce erano più belle e più floride di quelle di tutti gli altri giovani che mangiavano le vivande del re."],
[1016,"Da allora in poi il sovrintendente fece togliere l'assegnazione delle vivande e del vino che bevevano, e diede loro soltanto verdure."],
[1017,"Dio concesse a questi quattro giovani di conoscere e comprendere ogni scrittura e ogni sapienza, e rese Daniele interprete di visioni e di sogni."],
[1018,"Terminato il tempo, stabilito dal re, entro il quale i giovani dovevano essergli presentati, il capo dei funzionari li portò a Nabucodonosor."],
[1019,"Il re parlò con loro, ma fra tutti non si trovò nessuno pari a Daniele, Anania, Misaele e Azaria, i quali rimasero al servizio del re;"],
[1020,"su qualunque argomento in fatto di sapienza e intelligenza il re li interrogasse, li trovava dieci volte superiori a tutti i maghi e indovini che c'erano in tutto il suo regno."],
[1021,"Così Daniele vi rimase fino al primo anno del re Ciro."],
[2001,"Nel secondo anno del suo regno, Nabucodonosor fece un sogno e il suo animo ne fu tanto agitato da non poter più dormire."],
[2002,"Allora il re ordinò che fossero chiamati i maghi, gli indovini, gli incantatori e i Caldei a spiegargli i sogni. Questi vennero e si presentarono al re."],
[2003,"Egli disse loro: \"Ho fatto un sogno e il mio animo si è tormentato per trovarne la spiegazione\"."],
[2004,"I Caldei risposero al re: \"O re, vivi per sempre. Racconta il sogno ai tuoi servi e noi te ne daremo la spiegazione\"."],
[2005,"Rispose il re ai Caldei: \"La mia decisione è ferma: se voi non mi fate conoscere il sogno e la sua spiegazione, sarete fatti a pezzi e le vostre case saranno ridotte a letamai."],
[2006,"Se invece mi rivelerete il sogno e la sua spiegazione, riceverete da me doni, regali e grandi onori. Rivelatemi dunque il sogno e la sua spiegazione\"."],
[2007,"Essi replicarono: \"Esponga il re il sogno ai suoi servi e noi ne daremo la spiegazione\"."],
[2008,"Rispose il re: \"Comprendo bene che voi volete guadagnare tempo, perché vedete che la mia decisione è ferma."],
[2009,"Se non mi fate conoscere il sogno, una sola sarà la vostra sorte. Vi siete messi d'accordo per darmi risposte astute e false, in attesa che le circostanze mutino. Perciò ditemi il sogno e io saprò che voi siete in grado di darmene anche la spiegazione\"."],
[2010,"I Caldei risposero davanti al re: \"Non c'è nessuno al mondo che possa soddisfare la richiesta del re: difatti nessun re, per quanto potente e grande, ha mai domandato una cosa simile a un mago, indovino o Caldeo."],
[2011,"La richiesta del re è tanto difficile, che nessuno ne può dare al re la risposta, se non gli dei la cui dimora non è tra gli uomini\"."],
[2012,"Allora il re andò su tutte le furie e, acceso di furore, ordinò che tutti i saggi di Babilonia fossero messi a morte."],
[2013,"Il decreto fu pubblicato e già i saggi venivano uccisi; anche Daniele e i suoi compagni erano ricercati per essere messi a morte."],
[2014,"Ma Daniele rivolse parole piene di saggezza e di prudenza ad Arioc, capo delle guardie del re, che stava per uccidere i saggi di Babilonia,"],
[2015,"e disse ad Arioc, ufficiale del re: \"Perché il re ha emanato un decreto così severo?\". Arioc ne spiegò il motivo a Daniele."],
[2016,"Egli allora entrò dal re e pregò che gli si concedesse tempo: egli avrebbe dato la spiegazione del sogno al re."],
[2017,"Poi Daniele andò a casa e narrò la cosa ai suoi compagni, Anania, Misaele e Azaria,"],
[2018,"affinché implorassero misericordia dal Dio del cielo riguardo a questo mistero, perché Daniele e i suoi compagni non fossero messi a morte insieme con tutti gli altri saggi di Babilonia."],
[2019,"Allora il mistero fu svelato a Daniele in una visione notturna; perciò Daniele benedisse il Dio del cielo:"],
[2020,"\"Sia benedetto il nome di Dio di secolo in secolo, perché a lui appartengono la sapienza e la potenza."],
[2021,"Egli alterna tempi e stagioni, depone i re e li innalza, concede la sapienza ai saggi, agli intelligenti il sapere."],
[2022,"Svela cose profonde e occulte e sa quello che è celato nelle tenebre, e presso di lui abita la luce."],
[2023,"Gloria e lode a te, Dio dei miei padri, che mi hai concesso la sapienza e la forza, mi hai manifestato ciò che ti abbiamo domandato e ci hai fatto conoscere la richiesta del re\"."],
[2024,"Allora Daniele si recò da Arioc, al quale il re aveva affidato l'incarico di uccidere i saggi di Babilonia, si presentò e gli disse: \"Non uccidere i saggi di Babilonia, ma conducimi dal re e io gli rivelerò la spiegazione del sogno\"."],
[2025,"Arioc condusse in fretta Daniele alla presenza del re e gli disse: \"Ho trovato un uomo fra i Giudei deportati, il quale farà conoscere al re la spiegazione del sogno\"."],
[2026,"Il re disse allora a Daniele, chiamato Baltassar: \"Puoi tu davvero farmi conoscere il sogno che ho fatto e la sua spiegazione?\"."],
[2027,"Daniele, davanti al re, rispose: \"Il mistero di cui il re chiede la spiegazione non può essere spiegato né da saggi né da indovini, né da maghi né da astrologi;"],
[2028,"ma c'è un Dio nel cielo che svela i misteri ed egli ha fatto conoscere al re Nabucodonosor quello che avverrà alla fine dei giorni. Ecco dunque qual era il tuo sogno e le visioni che sono passate per la tua mente, mentre dormivi nel tuo letto."],
[2029,"O re, i pensieri che ti sono venuti mentre eri a letto riguardano il futuro; colui che svela i misteri ha voluto farti conoscere ciò che dovrà avvenire."],
[2030,"Se a me è stato svelato questo mistero, non è perché io possieda una sapienza superiore a tutti i viventi, ma perché ne sia data la spiegazione al re e tu possa conoscere i pensieri del tuo cuore."],
[2031,"Tu stavi osservando, o re, ed ecco una statua, una statua enorme, di straordinario splendore, si ergeva davanti a te con terribile aspetto."],
[2032,"Aveva la testa d'oro puro, il petto e le braccia d'argento, il ventre e le cosce di bronzo,"],
[2033,"le gambe di ferro e i piedi in parte di ferro e in parte d'argilla."],
[2034,"Mentre stavi guardando, una pietra si staccò dal monte, ma senza intervento di mano d'uomo, e andò a battere contro i piedi della statua, che erano di ferro e d'argilla, e li frantumò."],
[2035,"Allora si frantumarono anche il ferro, l'argilla, il bronzo, l'argento e l'oro e divennero come la pula sulle aie d'estate; il vento li portò via senza lasciare traccia, mentre la pietra, che aveva colpito la statua, divenne una grande montagna che riempì tutta la terra."],
[2036,"Questo è il sogno: ora ne daremo la spiegazione al re."],
[2037,"Tu, o re, sei il re dei re; a te il Dio del cielo ha concesso il regno, la potenza, la forza e la gloria."],
[2038,"Dovunque si trovino figli dell'uomo, animali selvatici e uccelli del cielo, egli li ha dati nelle tue mani; tu li domini tutti: tu sei la testa d'oro."],
[2039,"Dopo di te sorgerà un altro regno, inferiore al tuo; poi un terzo regno, quello di bronzo, che dominerà su tutta la terra."],
[2040,"Ci sarà poi un quarto regno, duro come il ferro: come il ferro spezza e frantuma tutto, così quel regno spezzerà e frantumerà tutto."],
[2041,"Come hai visto, i piedi e le dita erano in parte d'argilla da vasaio e in parte di ferro: ciò significa che il regno sarà diviso, ma ci sarà in esso la durezza del ferro, poiché hai veduto il ferro unito all'argilla fangosa."],
[2042,"Se le dita dei piedi erano in parte di ferro e in parte d'argilla, ciò significa che una parte del regno sarà forte e l'altra fragile."],
[2043,"Il fatto d'aver visto il ferro mescolato all'argilla significa che le due parti si uniranno per via di matrimoni, ma non potranno diventare una cosa sola, come il ferro non si amalgama con l'argilla fangosa."],
[2044,"Al tempo di questi re, il Dio del cielo farà sorgere un regno che non sarà mai distrutto e non sarà trasmesso ad altro popolo: stritolerà e annienterà tutti gli altri regni, mentre esso durerà per sempre."],
[2045,"Questo significa quella pietra che tu hai visto staccarsi dal monte, non per intervento di una mano, e che ha stritolato il ferro, il bronzo, l'argilla, l'argento e l'oro. Il Dio grande ha fatto conoscere al re quello che avverrà da questo tempo in poi. Il sogno è vero e degna di fede ne è la spiegazione\"."],
[2046,"Allora il re Nabucodonosor si prostrò con la faccia a terra, adorò Daniele e ordinò che gli si offrissero sacrifici e incensi."],
[2047,"Quindi, rivolto a Daniele, gli disse: \"Certo, il vostro Dio è il Dio degli dei, il Signore dei re e il rivelatore dei misteri, poiché tu hai potuto svelare questo mistero\"."],
[2048,"Il re esaltò Daniele e gli fece molti preziosi regali, lo costituì governatore di tutta la provincia di Babilonia e capo di tutti i saggi di Babilonia;"],
[2049,"su richiesta di Daniele, il re fece amministratori della provincia di Babilonia Sadrac, Mesac e Abdenego. Daniele rimase alla corte del re."],
[3001,"Il re Nabucodonosor aveva fatto costruire una statua d'oro, alta sessanta cubiti e larga sei, e l'aveva fatta erigere nella pianura di Dura, nella provincia di Babilonia."],
[3002,"Quindi il re Nabucodonosor aveva convocato i satrapi, i governatori, i prefetti, i consiglieri, i tesorieri, i giudici, i questori e tutte le alte autorità delle province, perché presenziassero all'inaugurazione della statua che il re Nabucodonosor aveva fatto erigere."],
[3003,"I satrapi, i governatori, i prefetti, i consiglieri, i tesorieri, i giudici, i questori e tutte le alte autorità delle province vennero all'inaugurazione della statua che aveva fatto erigere il re Nabucodonosor. Essi si disposero davanti alla statua fatta erigere da Nabucodonosor."],
[3004,"Un banditore gridò ad alta voce: \"Popoli, nazioni e lingue, a voi è rivolto questo proclama:"],
[3005,"Quando voi udrete il suono del corno, del flauto, della cetra, dell'arpa, del salterio, della zampogna e di ogni specie di strumenti musicali, vi prostrerete e adorerete la statua d'oro che il re Nabucodonosor ha fatto erigere."],
[3006,"Chiunque non si prostrerà e non adorerà, in quel medesimo istante sarà gettato in mezzo a una fornace di fuoco ardente\"."],
[3007,"Perciò tutti i popoli, nazioni e lingue, non appena ebbero udito il suono del corno, del flauto, della cetra, dell'arpa, del salterio e di ogni specie di strumenti musicali, si prostrarono e adorarono la statua d'oro che il re Nabucodonosor aveva fatto erigere."],
[3008,"Però in quel momento alcuni Caldei si fecero avanti per accusare i Giudei"],
[3009,"e andarono a dire al re Nabucodonosor: \"O re, vivi per sempre!"],
[3010,"Tu hai decretato, o re, che chiunque avrà udito il suono del corno, del flauto, della cetra, dell'arpa, del salterio, della zampogna e di ogni specie di strumenti musicali, deve prostrarsi e adorare la statua d'oro:"],
[3011,"chiunque non si prostrerà e non l'adorerà, sia gettato in mezzo a una fornace di fuoco ardente."],
[3012,"Ora, ci sono alcuni Giudei, che hai fatto amministratori della provincia di Babilonia, cioè Sadrac, Mesac e Abdenego, che non ti obbediscono, o re: non servono i tuoi dei e non adorano la statua d'oro che tu hai fatto erigere\"."],
[3013,"Allora Nabucodonosor, sdegnato e adirato, comandò che gli si conducessero Sadrac, Mesac e Abdenego, e questi comparvero alla presenza del re."],
[3014,"Nabucodonosor disse loro: \"È vero, Sadrac, Mesac e Abdenego, che voi non servite i miei dei e non adorate la statua d'oro che io ho fatto erigere?"],
[3015,"Ora se voi, quando udrete il suono del corno, del flauto, della cetra, dell'arpa, del salterio, della zampogna e di ogni specie di strumenti musicali, sarete pronti a prostrarvi e adorare la statua che io ho fatto, bene; altrimenti, in quel medesimo istante, sarete gettati in mezzo a una fornace di fuoco ardente. Quale dio vi potrà liberare dalla mia mano?\"."],
[3016,"Ma Sadrac, Mesac e Abdenego risposero al re Nabucodonosor: \"Noi non abbiamo bisogno di darti alcuna risposta in proposito;"],
[3017,"sappi però che il nostro Dio, che serviamo, può liberarci dalla fornace di fuoco ardente e dalla tua mano, o re."],
[3018,"Ma anche se non ci liberasse, sappi, o re, che noi non serviremo mai i tuoi dei e non adoreremo la statua d'oro che tu hai eretto\"."],
[3019,"Allora Nabucodonosor fu pieno d'ira e il suo aspetto si alterò nei confronti di Sadrac, Mesac e Abdenego, e ordinò che si aumentasse il fuoco della fornace sette volte più del solito."],
[3020,"Poi, ad alcuni uomini fra i più forti del suo esercito, comandò di legare Sadrac, Mesac e Abdenego e gettarli nella fornace di fuoco ardente."],
[3021,"Furono infatti legati, vestiti come erano, con i mantelli, i calzari, i copricapi e tutti i loro abiti, e gettati in mezzo alla fornace di fuoco ardente."],
[3022,"Poiché l'ordine del re urgeva e la fornace era ben accesa, la fiamma del fuoco uccise coloro che vi avevano gettato Sadrac, Mesac e Abdenego."],
[3023,"E questi tre, Sadrac, Mesac e Abdenego, caddero legati nella fornace di fuoco ardente."],
[3024,"Essi passeggiavano in mezzo alle fiamme, lodavano Dio e benedicevano il Signore."],
[3025,"Azaria si alzò e fece questa preghiera in mezzo al fuoco e aprendo la bocca disse:"],
[3026,"\"Benedetto sei tu, Signore, Dio dei nostri padri; degno di lode e glorioso è il tuo nome per sempre."],
[3027,"Tu sei giusto in tutto ciò che ci hai fatto; tutte le tue opere sono vere, rette le tue vie e giusti tutti i tuoi giudizi."],
[3028,"Giusto è stato il tuo giudizio per quanto hai fatto ricadere su di noi e sulla città santa dei nostri padri, Gerusalemme. Con verità e giustizia tu ci hai inflitto tutto questo a causa dei nostri peccati,"],
[3029,"poiché noi abbiamo peccato, abbiamo agito da iniqui, allontanandoci da te, abbiamo mancato in ogni modo. Non abbiamo obbedito ai tuoi comandamenti,"],
[3030,"non li abbiamo osservati, non abbiamo fatto quanto ci avevi ordinato per il nostro bene."],
[3031,"Ora, quanto hai fatto ricadere su di noi, tutto ciò che ci hai fatto, l'hai fatto con retto giudizio:"],
[3032,"ci hai dato in potere dei nostri nemici, ingiusti, i peggiori fra gli empi, e di un re iniquo, il più malvagio su tutta la terra."],
[3033,"Ora non osiamo aprire la bocca: disonore e disprezzo sono toccati a quelli che ti servono, a quelli che ti adorano."],
[3034,"Non ci abbandonare fino in fondo, per amore del tuo nome, non infrangere la tua alleanza;"],
[3035,"non ritirare da noi la tua misericordia, per amore di Abramo, tuo amico, di Isacco, tuo servo, di Israele, tuo santo,"],
[3036,"ai quali hai parlato, promettendo di moltiplicare la loro stirpe come le stelle del cielo, come la sabbia sulla spiaggia del mare."],
[3037,"Ora invece, Signore, noi siamo diventati più piccoli di qualunque altra nazione, oggi siamo umiliati per tutta la terra a causa dei nostri peccati."],
[3038,"Ora non abbiamo più né principe né profeta né capo né olocausto né sacrificio né oblazione né incenso né luogo per presentarti le primizie e trovare misericordia."],
[3039,"Potessimo essere accolti con il cuore contrito e con lo spirito umiliato, come olocausti di montoni e di tori, come migliaia di grassi agnelli."],
[3040,"Tale sia oggi il nostro sacrificio davanti a te e ti sia gradito, perché non c'è delusione per coloro che confidano in te."],
[3041,"Ora ti seguiamo con tutto il cuore, ti temiamo e cerchiamo il tuo volto, non coprirci di vergogna."],
[3042,"Fa' con noi secondo la tua clemenza, secondo la tua grande misericordia."],
[3043,"Salvaci con i tuoi prodigi, da' gloria al tuo nome, Signore."],
[3044,"Siano invece confusi quanti mostrano il male ai tuoi servi, siano coperti di vergogna, privati della loro potenza e del loro dominio, e sia infranta la loro forza!"],
[3045,"Sappiano che tu sei il Signore, il Dio unico e glorioso su tutta la terra\"."],
[3046,"I servi del re, che li avevano gettati dentro, non cessarono di aumentare il fuoco nella fornace, con bitume, stoppa, pece e sarmenti."],
[3047,"La fiamma si alzava quarantanove cubiti sopra la fornace"],
[3048,"e uscendo bruciò quei Caldei che si trovavano vicino alla fornace."],
[3049,"Ma l'angelo del Signore, che era sceso con Azaria e con i suoi compagni nella fornace, allontanò da loro la fiamma del fuoco della fornace"],
[3050,"e rese l'interno della fornace come se vi soffiasse dentro un vento pieno di rugiada. Così il fuoco non li toccò affatto, non fece loro alcun male, non diede loro alcuna molestia."],
[3051,"Allora quei tre giovani, a una sola voce, si misero a lodare, a glorificare, a benedire Dio nella fornace dicendo:"],
[3052,"\"Benedetto sei tu, Signore, Dio dei padri nostri, degno di lode e di gloria nei secoli. Benedetto il tuo nome glorioso e santo, degno di lode e di gloria nei secoli."],
[3053,"Benedetto sei tu nel tuo tempio santo, glorioso, degno di lode e di gloria nei secoli."],
[3054,"Benedetto sei tu sul trono del tuo regno, degno di lode e di gloria nei secoli."],
[3055,"Benedetto sei tu che penetri con lo sguardo gli abissi e siedi sui cherubini, degno di lode e di gloria nei secoli."],
[3056,"Benedetto sei tu nel firmamento del cielo, degno di lode e di gloria nei secoli."],
[3057,"Benedite, opere tutte del Signore, il Signore, lodatelo ed esaltatelo nei secoli."],
[3058,"Benedite, angeli del Signore, il Signore, lodatelo ed esaltatelo nei secoli."],
[3059,"Benedite, cieli, il Signore, lodatelo ed esaltatelo nei secoli."],
[3060,"Benedite, acque tutte, che siete sopra i cieli, il Signore, lodatelo ed esaltatelo nei secoli."],
[3061,"Benedite, potenze tutte del Signore, il Signore, lodatelo ed esaltatelo nei secoli."],
[3062,"Benedite, sole e luna, il Signore, lodatelo ed esaltatelo nei secoli."],
[3063,"Benedite, stelle del cielo, il Signore, lodatelo ed esaltatelo nei secoli."],
[3064,"Benedite, piogge e rugiade, il Signore, lodatelo ed esaltatelo nei secoli."],
[3065,"Benedite, o venti tutti, il Signore, lodatelo ed esaltatelo nei secoli."],
[3066,"Benedite, fuoco e calore, il Signore, lodatelo ed esaltatelo nei secoli."],
[3067,"Benedite, freddo e caldo, il Signore, lodatelo ed esaltatelo nei secoli."],
[3068,"Benedite, rugiada e brina, il Signore, lodatelo ed esaltatelo nei secoli."],
[3069,"Benedite, gelo e freddo, il Signore, lodatelo ed esaltatelo nei secoli."],
[3070,"Benedite, ghiacci e nevi, il Signore, lodatelo ed esaltatelo nei secoli."],
[3071,"Benedite, notti e giorni, il Signore, lodatelo ed esaltatelo nei secoli."],
[3072,"Benedite, luce e tenebre, il Signore, lodatelo ed esaltatelo nei secoli."],
[3073,"Benedite, folgori e nubi, il Signore, lodatelo ed esaltatelo nei secoli."],
[3074,"Benedica la terra il Signore, lo lodi e lo esalti nei secoli."],
[3075,"Benedite, monti e colline, il Signore, lodatelo ed esaltatelo nei secoli."],
[3076,"Benedite, creature tutte che germinate sulla terra, il Signore, lodatelo ed esaltatelo nei secoli."],
[3077,"Benedite, sorgenti, il Signore, lodatelo ed esaltatelo nei secoli."],
[3078,"Benedite, mari e fiumi, il Signore, lodatelo ed esaltatelo nei secoli."],
[3079,"Benedite, mostri marini e quanto si muove nell'acqua, il Signore, lodatelo ed esaltatelo nei secoli."],
[3080,"Benedite, uccelli tutti dell'aria, il Signore, lodatelo ed esaltatelo nei secoli."],
[3081,"Benedite, animali tutti, selvaggi e domestici, il Signore, lodatelo ed esaltatelo nei secoli."],
[3082,"Benedite, figli dell'uomo, il Signore, lodatelo ed esaltatelo nei secoli."],
[3083,"Benedite, figli d'Israele, il Signore, lodatelo ed esaltatelo nei secoli."],
[3084,"Benedite, sacerdoti del Signore, il Signore, lodatelo ed esaltatelo nei secoli."],
[3085,"Benedite, servi del Signore, il Signore, lodatelo ed esaltatelo nei secoli."],
[3086,"Benedite, spiriti e anime dei giusti, il Signore, lodatelo ed esaltatelo nei secoli."],
[3087,"Benedite, santi e umili di cuore, il Signore, lodatelo ed esaltatelo nei secoli."],
[3088,"Benedite, Anania, Azaria e Misaele, il Signore, lodatelo ed esaltatelo nei secoli, perché ci ha liberati dagl'inferi, e salvati dalla mano della morte, ci ha liberati dalla fiamma ardente, ci ha liberati dal fuoco."],
[3089,"Lodate il Signore, perché egli è buono, perché il suo amore è per sempre."],
[3090,"Benedite, voi tutti che temete il Signore, il Dio degli dei, lodatelo e celebratelo, perché il suo amore è per sempre\"."],
[3091,"Allora il re Nabucodonosor rimase stupito e alzatosi in fretta si rivolse ai suoi ministri: \"Non abbiamo noi gettato tre uomini legati in mezzo al fuoco?\". \"Certo, o re\", risposero."],
[3092,"Egli soggiunse: \"Ecco, io vedo quattro uomini sciolti, i quali camminano in mezzo al fuoco, senza subirne alcun danno; anzi il quarto è simile nell'aspetto a un figlio di dei\"."],
[3093,"Allora Nabucodonosor si accostò alla bocca della fornace di fuoco ardente e prese a dire: \"Sadrac, Mesac, Abdenego, servi del Dio altissimo, uscite, venite fuori\". Allora Sadrac, Mesac e Abdenego uscirono dal fuoco."],
[3094,"Quindi i satrapi, i governatori, i prefetti e i ministri del re si radunarono e, guardando quegli uomini, videro che sopra i loro corpi il fuoco non aveva avuto nessun potere, che neppure un capello del loro capo era stato bruciato e i loro mantelli non erano stati toccati e neppure l'odore del fuoco era penetrato in essi."],
[3095,"Nabucodonosor prese a dire: \"Benedetto il Dio di Sadrac, Mesac e Abdenego, il quale ha mandato il suo angelo e ha liberato i servi che hanno confidato in lui; hanno trasgredito il comando del re e hanno esposto i loro corpi per non servire e per non adorare alcun altro dio all'infuori del loro Dio."],
[3096,"Perciò io decreto che chiunque, a qualsiasi popolo, nazione o lingua appartenga, proferirà offesa contro il Dio di Sadrac, Mesac e Abdenego, sia fatto a pezzi e la sua casa sia ridotta a letamaio, poiché non c'è nessun altro dio che possa liberare allo stesso modo\"."],
[3097,"Da allora il re diede autorità a Sadrac, Mesac e Abdenego nella provincia di Babilonia."],
[3098,"Il re Nabucodonosor a tutti i popoli, nazioni e lingue, che abitano in tutta la terra: \"Abbondi la vostra pace!"],
[3099,"Mi è parso opportuno rendervi noti i prodigi e le meraviglie che il Dio altissimo ha fatto per me."],
[3100,"Quanto sono grandi i suoi prodigi e quanto potenti le sue meraviglie! Il suo regno è un regno eterno e il suo dominio di generazione in generazione\"."],
[4001,"Io, Nabucodonosor, ero tranquillo nella mia casa e felice nel mio palazzo,"],
[4002,"quando ebbi un sogno che mi spaventò. Mentre ero nel mio letto, le immaginazioni e le visioni della mia mente mi turbarono."],
[4003,"Feci un decreto con cui ordinavo che tutti i saggi di Babilonia fossero condotti davanti a me, per farmi conoscere la spiegazione del sogno."],
[4004,"Allora vennero i maghi, gli indovini, i Caldei e gli astrologi, ai quali esposi il sogno, ma non me ne potevano dare la spiegazione."],
[4005,"Infine mi si presentò Daniele, chiamato Baltassar dal nome del mio dio, un uomo in cui è lo spirito degli dei santi, e gli raccontai il sogno"],
[4006,"dicendo: \"Baltassar, principe dei maghi, poiché io so che lo spirito degli dei santi è in te e che nessun mistero ti è difficile, ecco le visioni che ho avuto in sogno: tu dammene la spiegazione."],
[4007,"Le visioni che mi passarono per la mente, mentre stavo a letto, erano queste: Io stavo guardando, ed ecco un albero di grande altezza in mezzo alla terra."],
[4008,"Quell'albero divenne alto, robusto, la sua cima giungeva al cielo ed era visibile fino all'estremità della terra."],
[4009,"Le sue foglie erano belle e i suoi frutti abbondanti e vi era in esso da mangiare per tutti. Le bestie del campo si riparavano alla sua ombra e gli uccelli del cielo dimoravano fra i suoi rami; di esso si nutriva ogni vivente."],
[4010,"Mentre nel mio letto stavo osservando le visioni che mi passavano per la mente, ecco un vigilante, un santo, scese dal cielo"],
[4011,"e gridò a voce alta: \"Tagliate l'albero e troncate i suoi rami: scuotete le foglie, disperdetene i frutti: fuggano le bestie di sotto e gli uccelli dai suoi rami."],
[4012.001,"Lasciate però nella terra il ceppo con le radici, legato con catene di ferro e di bronzo sull'erba fresca del campo;"],
[4012.002,"sia bagnato dalla rugiada del cielo"],
[4012.003,"e abbia sorte comune con le bestie sull'erba della terra."],
[4013.001,"Si muti il suo cuore e invece di un cuore umano gli sia dato un cuore di bestia;"],
[4013.002,"sette tempi passino su di lui."],
[4014,"Così è deciso per sentenza dei vigilanti e secondo la parola dei santi. Così i viventi sappiano che l'Altissimo domina sul regno degli uomini e che egli lo può dare a chi vuole e insediarvi anche il più piccolo degli uomini\"."],
[4015,"Questo è il sogno, che io, re Nabucodonosor, ho fatto. Ora tu, Baltassar, dammene la spiegazione. Tu puoi darmela, perché, mentre fra tutti i saggi del mio regno nessuno me ne spiega il significato, in te è lo spirito degli dei santi\"."],
[4016,"Allora Daniele, chiamato Baltassar, rimase per qualche tempo confuso e turbato dai suoi pensieri. Ma il re gli disse: \"Baltassar, il sogno non ti turbi e neppure la sua spiegazione\". Rispose Baltassar: \"Signore mio, valga il sogno per i tuoi nemici e la sua spiegazione per i tuoi avversari."],
[4017,"L'albero che tu hai visto, alto e robusto, la cui cima giungeva fino al cielo ed era visibile per tutta la terra"],
[4018,"e le cui foglie erano belle e i frutti abbondanti e in cui c'era da mangiare per tutti e sotto il quale dimoravano le bestie della terra e sui cui rami abitavano gli uccelli del cielo,"],
[4019,"sei tu, o re, che sei diventato grande e forte; la tua grandezza è cresciuta, è giunta al cielo e il tuo dominio si è esteso fino all'estremità della terra."],
[4020,"Che il re abbia visto un vigilante, un santo che discendeva dal cielo e diceva: \"Tagliate l'albero, spezzatelo, però lasciate nella terra il ceppo con le sue radici, legato con catene di ferro e di bronzo sull'erba fresca del campo; sia bagnato dalla rugiada del cielo e abbia sorte comune con le bestie del campo, finché sette tempi siano passati su di lui\","],
[4021,"questa, o re, ne è la spiegazione e questo è il decreto dell'Altissimo, che deve essere eseguito sopra il re, mio signore:"],
[4022,"Tu sarai cacciato dal consorzio umano e la tua dimora sarà con le bestie del campo; ti pascerai di erba come i buoi e sarai bagnato dalla rugiada del cielo; sette tempi passeranno su di te, finché tu riconosca che l'Altissimo domina sul regno degli uomini e che egli lo dà a chi vuole."],
[4023,"L'ordine che è stato dato di lasciare il ceppo con le radici dell'albero significa che il tuo regno ti sarà ristabilito, quando avrai riconosciuto che al Cielo appartiene il dominio."],
[4024,"Perciò, o re, accetta il mio consiglio: sconta i tuoi peccati con l'elemosina e le tue iniquità con atti di misericordia verso gli afflitti, perché tu possa godere lunga prosperità\"."],
[4025,"Tutto questo accadde al re Nabucodonosor."],
[4026,"Dodici mesi dopo, passeggiando sopra la terrazza del palazzo reale di Babilonia,"],
[4027,"il re prese a dire: \"Non è questa la grande Babilonia che io ho costruito come reggia con la forza della mia potenza e per la gloria della mia maestà?\"."],
[4028,"Queste parole erano ancora sulle labbra del re, quando una voce venne dal cielo: \"A te io parlo, o re Nabucodonosor: il regno ti è tolto!"],
[4029,"Sarai cacciato dal consorzio umano e la tua dimora sarà con le bestie del campo; ti pascerai di erba come i buoi e passeranno sette tempi su di te, finché tu riconosca che l'Altissimo domina sul regno degli uomini e che egli lo dà a chi vuole\"."],
[4030,"In quel momento stesso si adempì la parola sopra Nabucodonosor. Egli fu cacciato dal consorzio umano, mangiò l'erba come i buoi e il suo corpo fu bagnato dalla rugiada del cielo, i capelli gli crebbero come le penne alle aquile e le unghie come agli uccelli."],
[4031,"\"Ma finito quel tempo io, Nabucodonosor, alzai gli occhi al cielo e la ragione tornò in me e benedissi l'Altissimo; lodai e glorificai colui che vive in eterno, il cui potere è potere eterno e il cui regno è di generazione in generazione."],
[4032,"Tutti gli abitanti della terra sono, davanti a lui, come un nulla; egli tratta come vuole le schiere del cielo e gli abitanti della terra. Nessuno può fermargli la mano e dirgli: \"Che cosa fai?\"."],
[4033,"In quel tempo tornò in me la conoscenza e, con la gloria del regno, mi fu restituita la mia maestà e il mio splendore: i miei ministri e i miei dignitari mi ricercarono e io fui ristabilito nel mio regno e mi fu concesso un potere anche più grande."],
[4034,"Ora io, Nabucodonosor, lodo, esalto e glorifico il Re del cielo: tutte le sue opere sono vere e le sue vie sono giuste; egli ha il potere di umiliare coloro che camminano nella superbia\"."],
[5001,"Il re Baldassar imbandì un grande banchetto a mille dei suoi dignitari e insieme con loro si diede a bere vino."],
[5002,"Quando Baldassar ebbe molto bevuto, comandò che fossero portati i vasi d'oro e d'argento che Nabucodonosor, suo padre, aveva asportato dal tempio di Gerusalemme, perché vi bevessero il re e i suoi dignitari, le sue mogli e le sue concubine."],
[5003,"Furono quindi portati i vasi d'oro, che erano stati asportati dal tempio di Dio a Gerusalemme, e il re, i suoi dignitari, le sue mogli e le sue concubine li usarono per bere;"],
[5004,"mentre bevevano il vino, lodavano gli dei d'oro, d'argento, di bronzo, di ferro, di legno e di pietra."],
[5005,"In quel momento apparvero le dita di una mano d'uomo, che si misero a scrivere sull'intonaco della parete del palazzo reale, di fronte al candelabro, e il re vide il palmo di quella mano che scriveva."],
[5006,"Allora il re cambiò colore: spaventosi pensieri lo assalirono, le giunture dei suoi fianchi si allentarono, i suoi ginocchi battevano l'uno contro l'altro."],
[5007,"Allora il re si mise a gridare, ordinando che si convocassero gli indovini, i Caldei e gli astrologi. Appena vennero, il re disse ai saggi di Babilonia: \"Chiunque leggerà quella scrittura e me ne darà la spiegazione, sarà vestito di porpora, porterà una collana d'oro al collo e sarà terzo nel governo del regno\"."],
[5008,"Allora entrarono tutti i saggi del re, ma non poterono leggere quella scrittura né darne al re la spiegazione."],
[5009,"Il re Baldassar rimase molto turbato e cambiò colore; anche i suoi dignitari restarono sconcertati."],
[5010,"La regina, alle parole del re e dei suoi dignitari, entrò nella sala del banchetto e, rivolta al re, gli disse: \"O re, vivi in eterno! I tuoi pensieri non ti spaventino né si cambi il colore del tuo volto."],
[5011,"C'è nel tuo regno un uomo nel quale è lo spirito degli dei santi. Al tempo di tuo padre si trovò in lui luce, intelligenza e sapienza pari alla sapienza degli dei. Il re Nabucodonosor, tuo padre, lo aveva fatto capo dei maghi, degli indovini, dei Caldei e degli astrologi."],
[5012,"Fu riscontrato in questo Daniele, che il re aveva chiamato Baltassar, uno spirito straordinario, intelligenza e capacità di interpretare sogni, spiegare enigmi, risolvere questioni difficili. Si convochi dunque Daniele ed egli darà la spiegazione\"."],
[5013,"Fu allora introdotto Daniele alla presenza del re ed egli gli disse: \"Sei tu Daniele, un deportato dei Giudei, che il re, mio padre, ha portato qui dalla Giudea?"],
[5014,"Ho inteso dire che tu possiedi lo spirito degli dei santi e che si trova in te luce, intelligenza e sapienza straordinaria."],
[5015,"Poco fa sono stati condotti alla mia presenza i saggi e gli indovini per leggere questa scrittura e darmene la spiegazione, ma non sono stati capaci di rivelarne il significato."],
[5016,"Ora, mi è stato detto che tu sei esperto nel dare spiegazioni e risolvere questioni difficili. Se quindi potrai leggermi questa scrittura e darmene la spiegazione, tu sarai vestito di porpora, porterai al collo una collana d'oro e sarai terzo nel governo del regno\"."],
[5017,"Daniele rispose al re: \"Tieni pure i tuoi doni per te e da' ad altri i tuoi regali: tuttavia io leggerò la scrittura al re e gliene darò la spiegazione."],
[5018,"O re, il Dio altissimo aveva dato a Nabucodonosor, tuo padre, regno, grandezza, gloria e maestà."],
[5019,"Per questa grandezza che aveva ricevuto, tutti i popoli, nazioni e lingue lo temevano e tremavano davanti a lui: egli uccideva chi voleva e faceva vivere chi voleva, innalzava chi voleva e abbassava chi voleva."],
[5020,"Ma, quando il suo cuore si insuperbì e il suo spirito si ostinò nell'alterigia, fu deposto dal trono del suo regno e gli fu tolta la sua gloria."],
[5021,"Fu cacciato dal consorzio umano e il suo cuore divenne simile a quello delle bestie, la sua dimora fu con gli asini selvatici e mangiò l'erba come i buoi, il suo corpo fu bagnato dalla rugiada del cielo, finché riconobbe che il Dio altissimo domina sul regno degli uomini, sul quale colloca chi gli piace."],
[5022,"Tu, Baldassar, suo figlio, non hai umiliato il tuo cuore, sebbene tu fossi a conoscenza di tutto questo."],
[5023,"Anzi, ti sei innalzato contro il Signore del cielo e sono stati portati davanti a te i vasi del suo tempio e in essi avete bevuto tu, i tuoi dignitari, le tue mogli, le tue concubine: tu hai reso lode agli dei d'argento, d'oro, di bronzo, di ferro, di legno, di pietra, i quali non vedono, non odono e non comprendono, e non hai glorificato Dio, nelle cui mani è la tua vita e a cui appartengono tutte le tue vie."],
[5024,"Da lui fu allora mandato il palmo di quella mano che ha tracciato quello scritto."],
[5025,"E questo è lo scritto tracciato: Mene, Tekel, Peres,"],
[5026,"e questa ne è l'interpretazione: Mene: Dio ha contato il tuo regno e gli ha posto fine;"],
[5027,"Tekel: tu sei stato pesato sulle bilance e sei stato trovato insufficiente;"],
[5028,"Peres: il tuo regno è stato diviso e dato ai Medi e ai Persiani\"."],
[5029,"Allora, per ordine di Baldassar, Daniele fu vestito di porpora, ebbe una collana d'oro al collo e con bando pubblico fu dichiarato terzo nel governo del regno."],
[5030,"In quella stessa notte Baldassar, re dei Caldei, fu ucciso."],
[6001,"Dario il Medo ricevette il regno, all'età di circa sessantadue anni."],
[6002,"Dario volle costituire nel suo regno centoventi satrapi e ripartirli per tutte le province."],
[6003,"A capo dei satrapi mise tre funzionari, di cui uno fu Daniele, ai quali i satrapi dovevano rendere conto perché nessun danno ne soffrisse il re."],
[6004,"Ora Daniele era superiore agli altri funzionari e ai satrapi, perché possedeva uno spirito straordinario, tanto che il re pensava di metterlo a capo di tutto il suo regno."],
[6005,"Perciò tanto i funzionari che i satrapi cercavano di trovare qualche pretesto contro Daniele nell'amministrazione del regno. Ma non potendo trovare nessun motivo di accusa né colpa, perché egli era fedele e non aveva niente da farsi rimproverare,"],
[6006,"quegli uomini allora pensarono: \"Non possiamo trovare altro pretesto per accusare Daniele, se non nella legge del suo Dio\"."],
[6007,"Perciò quei funzionari e i satrapi si radunarono presso il re e gli dissero: \"O re Dario, vivi in eterno!"],
[6008,"Tutti i funzionari del regno, i governatori, i satrapi, i ministri e i prefetti sono del parere che venga pubblicato un severo decreto del re secondo il quale chiunque, per la durata di trenta giorni, rivolga supplica a qualsiasi dio o uomo all'infuori di te, o re, sia gettato nella fossa dei leoni."],
[6009,"Ora, o re, emana il decreto e fallo mettere per iscritto, perché sia immutabile, come sono le leggi di Media e di Persia, che sono irrevocabili\"."],
[6010,"Allora il re Dario ratificò il decreto scritto."],
[6011,"Daniele, quando venne a sapere del decreto del re, si ritirò in casa. Le finestre della sua stanza si aprivano verso Gerusalemme e tre volte al giorno si metteva in ginocchio a pregare e lodava il suo Dio, come era solito fare anche prima."],
[6012,"Allora quegli uomini accorsero e trovarono Daniele che stava pregando e supplicando il suo Dio."],
[6013,"Subito si recarono dal re e gli dissero riguardo al suo decreto: \"Non hai approvato un decreto che chiunque, per la durata di trenta giorni, rivolga supplica a qualsiasi dio o uomo all'infuori di te, o re, sia gettato nella fossa dei leoni?\". Il re rispose: \"Sì. Il decreto è irrevocabile come lo sono le leggi dei Medi e dei Persiani\"."],
[6014,"\"Ebbene - replicarono al re -, Daniele, quel deportato dalla Giudea, non ha alcun rispetto né di te, o re, né del tuo decreto: tre volte al giorno fa le sue preghiere\"."],
[6015,"Il re, all'udire queste parole, ne fu molto addolorato e si mise in animo di salvare Daniele e fino al tramonto del sole fece ogni sforzo per liberarlo."],
[6016,"Ma quegli uomini si riunirono di nuovo presso il re e gli dissero: \"Sappi, o re, che i Medi e i Persiani hanno per legge che qualunque decreto emanato dal re non può essere mutato\"."],
[6017,"Allora il re ordinò che si prendesse Daniele e lo si gettasse nella fossa dei leoni. Il re, rivolto a Daniele, gli disse: \"Quel Dio, che tu servi con perseveranza, ti possa salvare!\"."],
[6018,"Poi fu portata una pietra e fu posta sopra la bocca della fossa: il re la sigillò con il suo anello e con l'anello dei suoi dignitari, perché niente fosse mutato riguardo a Daniele."],
[6019,"Quindi il re ritornò al suo palazzo, passò la notte digiuno, non gli fu introdotta nessuna concubina e anche il sonno lo abbandonò."],
[6020,"La mattina dopo il re si alzò di buon'ora e allo spuntare del giorno andò in fretta alla fossa dei leoni."],
[6021,"Quando fu vicino, il re chiamò Daniele con voce mesta: \"Daniele, servo del Dio vivente, il tuo Dio che tu servi con perseveranza ti ha potuto salvare dai leoni?\"."],
[6022,"Daniele rispose: \"O re, vivi in eterno!"],
[6023,"Il mio Dio ha mandato il suo angelo che ha chiuso le fauci dei leoni ed essi non mi hanno fatto alcun male, perché sono stato trovato innocente davanti a lui; ma neppure contro di te, o re, ho commesso alcun male\"."],
[6024,"Il re fu pieno di gioia e comandò che Daniele fosse tirato fuori dalla fossa. Appena uscito, non si riscontrò in lui lesione alcuna, poiché egli aveva confidato nel suo Dio."],
[6025,"Quindi, per ordine del re, fatti venire quegli uomini che avevano accusato Daniele, furono gettati nella fossa dei leoni insieme con i figli e le mogli. Non erano ancora giunti al fondo della fossa, che i leoni si avventarono contro di loro e ne stritolarono tutte le ossa."],
[6026,"Allora il re Dario scrisse a tutti i popoli, nazioni e lingue, che abitano tutta la terra: \"Abbondi la vostra pace."],
[6027,"Per mio comando viene promulgato questo decreto: In tutto l'impero a me soggetto si tremi e si tema davanti al Dio di Daniele, perché egli è il Dio vivente, che rimane in eterno; il suo regno non sarà mai distrutto e il suo potere non avrà mai fine."],
[6028,"Egli salva e libera, fa prodigi e miracoli in cielo e in terra: egli ha liberato Daniele dalle fauci dei leoni\"."],
[6029,"Questo Daniele fu in grande onore sotto il regno di Dario e il regno di Ciro il Persiano."],
[7001,"Nel primo anno di Baldassar, re di Babilonia, Daniele, mentre era a letto, ebbe un sogno e visioni nella sua mente. Egli scrisse il sogno e ne fece la seguente relazione."],
[7002,"Io, Daniele, guardavo nella mia visione notturna, ed ecco, i quattro venti del cielo si abbattevano impetuosamente sul Mare Grande"],
[7003,"e quattro grandi bestie, differenti l'una dall'altra, salivano dal mare."],
[7004,"La prima era simile a un leone e aveva ali di aquila. Mentre io stavo guardando, le furono strappate le ali e fu sollevata da terra e fatta stare su due piedi come un uomo e le fu dato un cuore d'uomo."],
[7005,"Poi ecco una seconda bestia, simile a un orso, la quale stava alzata da un lato e aveva tre costole in bocca, fra i denti, e le fu detto: \"Su, divora molta carne\"."],
[7006,"Dopo di questa, mentre stavo guardando, eccone un'altra simile a un leopardo, la quale aveva quattro ali d'uccello sul dorso; quella bestia aveva quattro teste e le fu dato il potere."],
[7007,"Dopo di questa, stavo ancora guardando nelle visioni notturne, ed ecco una quarta bestia, spaventosa, terribile, d'una forza straordinaria, con grandi denti di ferro; divorava, stritolava e il rimanente se lo metteva sotto i piedi e lo calpestava: era diversa da tutte le altre bestie precedenti e aveva dieci corna."],
[7008,"Stavo osservando queste corna, quand'ecco spuntare in mezzo a quelle un altro corno più piccolo, davanti al quale tre delle prime corna furono divelte: vidi che quel corno aveva occhi simili a quelli di un uomo e una bocca che proferiva parole arroganti."],
[7009,"Io continuavo a guardare, quand'ecco furono collocati troni e un vegliardo si assise. La sua veste era candida come la neve e i capelli del suo capo erano candidi come la lana; il suo trono era come vampe di fuoco con le ruote come fuoco ardente."],
[7010,"Un fiume di fuoco scorreva e usciva dinanzi a lui, mille migliaia lo servivano e diecimila miriadi lo assistevano. La corte sedette e i libri furono aperti."],
[7011,"Continuai a guardare a causa delle parole arroganti che quel corno proferiva, e vidi che la bestia fu uccisa e il suo corpo distrutto e gettato a bruciare nel fuoco."],
[7012,"Alle altre bestie fu tolto il potere e la durata della loro vita fu fissata fino a un termine stabilito."],
[7013,"Guardando ancora nelle visioni notturne, ecco venire con le nubi del cielo uno simile a un figlio d'uomo; giunse fino al vegliardo e fu presentato a lui."],
[7014,"Gli furono dati potere, gloria e regno; tutti i popoli, nazioni e lingue lo servivano: il suo potere è un potere eterno, che non finirà mai, e il suo regno non sarà mai distrutto."],
[7015,"Io, Daniele, mi sentii agitato nell'animo, tanto le visioni della mia mente mi avevano turbato;"],
[7016,"mi accostai a uno dei vicini e gli domandai il vero significato di tutte queste cose ed egli me ne diede questa spiegazione:"],
[7017,"\"Le quattro grandi bestie rappresentano quattro re, che sorgeranno dalla terra;"],
[7018,"ma i santi dell'Altissimo riceveranno il regno e lo possederanno per sempre, in eterno\"."],
[7019,"Volli poi sapere la verità intorno alla quarta bestia, che era diversa da tutte le altre e molto spaventosa, che aveva denti di ferro e artigli di bronzo, che divorava, stritolava e il rimanente se lo metteva sotto i piedi e lo calpestava,"],
[7020,"e anche intorno alle dieci corna che aveva sulla testa e intorno a quell'ultimo corno che era spuntato e davanti al quale erano cadute tre corna e del perché quel corno aveva occhi e una bocca che proferiva parole arroganti e appariva maggiore delle altre corna."],
[7021,"Io intanto stavo guardando e quel corno muoveva guerra ai santi e li vinceva,"],
[7022,"finché venne il vegliardo e fu resa giustizia ai santi dell'Altissimo e giunse il tempo in cui i santi dovevano possedere il regno."],
[7023,"Egli dunque mi disse: \"La quarta bestia significa che ci sarà sulla terra un quarto regno diverso da tutti gli altri e divorerà tutta la terra, la schiaccerà e la stritolerà."],
[7024,"Le dieci corna significano che dieci re sorgeranno da quel regno e dopo di loro ne seguirà un altro, diverso dai precedenti: abbatterà tre re"],
[7025,"e proferirà parole contro l'Altissimo e insulterà i santi dell'Altissimo; penserà di mutare i tempi e la legge. I santi gli saranno dati in mano per un tempo, tempi e metà di un tempo."],
[7026,"Si terrà poi il giudizio e gli sarà tolto il potere, quindi verrà sterminato e distrutto completamente."],
[7027,"Allora il regno, il potere e la grandezza dei regni che sono sotto il cielo saranno dati al popolo dei santi dell'Altissimo, il cui regno sarà eterno e tutti gli imperi lo serviranno e gli obbediranno\"."],
[7028,"Qui finisce il racconto. Io, Daniele, rimasi molto turbato nei pensieri, il colore del mio volto cambiò e conservai tutto questo nel cuore."],
[8001,"Il terzo anno del regno del re Baldassar io, Daniele, ebbi un'altra visione dopo quella che mi era apparsa prima."],
[8002,"Quand'ebbi questa visione, mi trovavo nella cittadella di Susa, che è nella provincia dell'Elam, e mi sembrava, in visione, di essere presso il fiume Ulai."],
[8003,"Alzai gli occhi e guardai. Ecco, un montone, in piedi, stava di fronte al fiume. Aveva due corna alte, ma un corno era più alto dell'altro, sebbene fosse spuntato dopo."],
[8004,"Io vidi che quel montone cozzava verso l'occidente, il settentrione e il mezzogiorno e nessuna bestia gli poteva resistere, né alcuno era in grado di liberare dal suo potere: faceva quello che gli pareva e divenne grande."],
[8005,"Io stavo attento, ed ecco un capro venire da occidente, sulla terra, senza toccarne il suolo: aveva fra gli occhi un grande corno."],
[8006,"Si avvicinò al montone dalle due corna, che avevo visto in piedi di fronte al fiume, e gli si scagliò contro con tutta la forza."],
[8007,"Dopo averlo assalito, lo vidi imbizzarrirsi e cozzare contro di lui e spezzargli le due corna, senza che il montone avesse la forza di resistergli; poi lo gettò a terra e lo calpestò e nessuno liberava il montone dal suo potere."],
[8008,"Il capro divenne molto potente; ma al culmine della sua forza quel suo grande corno si spezzò e al posto di quello sorsero altre quattro corna, verso i quattro venti del cielo."],
[8009,"Da uno di quelli uscì un piccolo corno, che crebbe molto verso il mezzogiorno, l'oriente e verso la magnifica terra:"],
[8010,"s'innalzò fin contro l'esercito celeste e gettò a terra una parte di quella schiera e una parte delle stelle e le calpestò."],
[8011,"S'innalzò fino al capo dell'esercito e gli tolse il sacrificio quotidiano e fu rovesciata la santa dimora."],
[8012,"A causa del peccato un esercito gli fu dato in luogo del sacrificio quotidiano e la verità fu gettata a terra; ciò esso fece e vi riuscì."],
[8013,"Udii parlare un santo e un altro santo dire a quello che parlava: \"Fino a quando durerà questa visione: il sacrificio quotidiano abolito, la trasgressione devastante, il santuario e la milizia calpestati?\"."],
[8014,"Gli rispose: \"Fino a duemilatrecento sere e mattine: poi al santuario sarà resa giustizia\"."],
[8015,"Mentre io, Daniele, consideravo la visione e cercavo di comprenderla, ecco davanti a me uno in piedi, dall'aspetto d'uomo;"],
[8016,"intesi la voce di un uomo, in mezzo all'Ulai, che gridava e diceva: \"Gabriele, spiega a lui la visione\"."],
[8017,"Egli venne dove io ero e quando giunse io ebbi paura e caddi con la faccia a terra. Egli mi disse: \"Figlio dell'uomo, comprendi bene, questa visione riguarda il tempo della fine\"."],
[8018,"Mentre egli parlava con me, caddi svenuto con la faccia a terra; ma egli mi toccò e mi fece alzare."],
[8019,"Egli disse: \"Ecco, io ti faccio conoscere ciò che avverrà al termine dell'ira, poiché al tempo fissato ci sarà la fine."],
[8020,"Il montone con due corna, che tu hai visto, significa il re di Media e di Persia;"],
[8021,"il capro è il re di Iavan e il grande corno, che era in mezzo ai suoi occhi, è il primo re."],
[8022,"Che quello sia stato spezzato e quattro ne siano sorti al posto di uno, significa che quattro regni sorgeranno dalla medesima nazione, ma non con la medesima potenza di lui."],
[8023,"Alla fine del loro regno, quando l'empietà avrà raggiunto il colmo, sorgerà un re audace, esperto in enigmi."],
[8024,"La sua potenza si rafforzerà, ma non per forza propria; causerà inaudite rovine, avrà successo nelle imprese, distruggerà i potenti e il popolo dei santi."],
[8025,"Per la sua astuzia, la frode prospererà nelle sue mani, si insuperbirà in cuor suo e impunemente farà perire molti: insorgerà contro il principe dei principi, ma verrà spezzato senza intervento di mano d'uomo."],
[8026,"La visione di sere e mattine, che è stata spiegata, è vera. Ora tu tieni segreta la visione, perché riguarda cose che avverranno fra molti giorni\"."],
[8027,"Io, Daniele, rimasi sfinito e mi sentii male per vari giorni: poi mi alzai e sbrigai gli affari del re: ma ero stupefatto della visione, perché non la potevo comprendere."],
[9001,"Nell'anno primo di Dario, figlio di Serse, della progenie dei Medi, il quale era stato costituito re sopra il regno dei Caldei,"],
[9002,"nel primo anno del suo regno io, Daniele, tentavo di comprendere nei libri il numero degli anni di cui il Signore aveva parlato al profeta Geremia e che si dovevano compiere per le rovine di Gerusalemme, cioè settant'anni."],
[9003,"Mi rivolsi al Signore Dio alla ricerca di un responso con preghiera e suppliche, con il digiuno, veste di sacco e cenere"],
[9004,"e feci la mia preghiera e la mia confessione al Signore, mio Dio: \"Signore Dio, grande e tremendo, che sei fedele all'alleanza e benevolo verso coloro che ti amano e osservano i tuoi comandamenti,"],
[9005,"abbiamo peccato e abbiamo operato da malvagi e da empi, siamo stati ribelli, ci siamo allontanati dai tuoi comandamenti e dalle tue leggi!"],
[9006,"Non abbiamo obbedito ai tuoi servi, i profeti, i quali nel tuo nome hanno parlato ai nostri re, ai nostri principi, ai nostri padri e a tutto il popolo del paese."],
[9007,"A te conviene la giustizia, o Signore, a noi la vergogna sul volto, come avviene ancora oggi per gli uomini di Giuda, per gli abitanti di Gerusalemme e per tutto Israele, vicini e lontani, in tutti i paesi dove tu li hai dispersi per i delitti che hanno commesso contro di te."],
[9008,"Signore, la vergogna sul volto a noi, ai nostri re, ai nostri principi, ai nostri padri, perché abbiamo peccato contro di te;"],
[9009,"al Signore, nostro Dio, la misericordia e il perdono, perché ci siamo ribellati contro di lui,"],
[9010,"non abbiamo ascoltato la voce del Signore, nostro Dio, né seguito quelle leggi che egli ci aveva dato per mezzo dei suoi servi, i profeti."],
[9011,"Tutto Israele ha trasgredito la tua legge, si è allontanato per non ascoltare la tua voce; così si è riversata su di noi la maledizione sancita con giuramento, scritto nella legge di Mosè, servo di Dio, perché abbiamo peccato contro di lui."],
[9012,"Egli ha messo in atto quelle parole che aveva pronunciato contro di noi e i nostri governanti, mandando su di noi un male così grande, che sotto tutto il cielo mai è accaduto nulla di simile a quello che si è verificato per Gerusalemme."],
[9013,"Tutto questo male è venuto su di noi, proprio come sta scritto nella legge di Mosè. Tuttavia noi non abbiamo supplicato il Signore, nostro Dio, convertendoci dalle nostre iniquità e riconoscendo la tua verità."],
[9014,"Il Signore ha vegliato sopra questo male, l'ha mandato su di noi, poiché il Signore, nostro Dio, è giusto in tutte le cose che fa, mentre noi non abbiamo ascoltato la sua voce."],
[9015,"Signore, nostro Dio, che hai fatto uscire il tuo popolo dall'Egitto con mano forte e ti sei fatto un nome qual è oggi, noi abbiamo peccato, abbiamo agito da empi."],
[9016,"Signore, secondo la tua giustizia, si plachi la tua ira e il tuo sdegno verso Gerusalemme, tua città, tuo monte santo, poiché per i nostri peccati e per l'iniquità dei nostri padri Gerusalemme e il tuo popolo sono oggetto di vituperio presso tutti i nostri vicini."],
[9017,"Ora ascolta, nostro Dio, la preghiera del tuo servo e le sue suppliche e per amor tuo, o Signore, fa' risplendere il tuo volto sopra il tuo santuario, che è devastato."],
[9018,"Porgi l'orecchio, mio Dio, e ascolta: apri gli occhi e guarda le nostre distruzioni e la città sulla quale è stato invocato il tuo nome! Noi presentiamo le nostre suppliche davanti a te, confidando non sulla nostra giustizia, ma sulla tua grande misericordia."],
[9019,"Signore, ascolta! Signore, perdona! Signore, guarda e agisci senza indugio, per amore di te stesso, mio Dio, poiché il tuo nome è stato invocato sulla tua città e sul tuo popolo\"."],
[9020,"Mentre io stavo ancora parlando e pregavo e confessavo il mio peccato e quello del mio popolo Israele e presentavo la supplica al Signore, mio Dio, per il monte santo del mio Dio,"],
[9021,"mentre dunque parlavo e pregavo, Gabriele, che io avevo visto prima in visione, volò veloce verso di me: era l'ora dell'offerta della sera."],
[9022,"Egli, giunto presso di me, mi rivolse la parola e mi disse: \"Daniele, sono venuto per istruirti e farti comprendere."],
[9023,"Fin dall'inizio delle tue suppliche è uscita una parola e io sono venuto per annunciartela, poiché tu sei un uomo prediletto. Ora sta' attento alla parola e comprendi la visione:"],
[9024,"Settanta settimane sono fissate per il tuo popolo e per la tua santa città per mettere fine all'empietà, mettere i sigilli ai peccati, espiare l'iniquità, stabilire una giustizia eterna, suggellare visione e profezia e ungere il Santo dei Santi."],
[9025,"Sappi e intendi bene: da quando uscì la parola sul ritorno e la ricostruzione di Gerusalemme fino a un principe consacrato, vi saranno sette settimane. Durante sessantadue settimane saranno restaurati, riedificati piazze e fossati, e ciò in tempi angosciosi."],
[9026,"Dopo sessantadue settimane, un consacrato sarà soppresso senza colpa in lui. Il popolo di un principe che verrà distruggerà la città e il santuario; la sua fine sarà un'inondazione e guerra e desolazioni sono decretate fino all'ultimo."],
[9027,"Egli stringerà una solida alleanza con molti per una settimana e, nello spazio di metà settimana, farà cessare il sacrificio e l'offerta; sull'ala del tempio porrà l'abominio devastante, finché un decreto di rovina non si riversi sul devastatore\"."],
[10001,"L'anno terzo di Ciro, re dei Persiani, fu rivelata una parola a Daniele, chiamato Baltassar. Vera è la parola e la lotta è grande. Egli comprese la parola e gli fu dato d'intendere la visione."],
[10002,"In quel tempo io, Daniele, feci penitenza per tre settimane,"],
[10003,"non mangiai cibo prelibato, non mi entrò in bocca né carne né vino e non mi unsi d'unguento, finché non furono compiute tre settimane."],
[10004,"Il giorno ventiquattro del primo mese, mentre stavo sulla sponda del grande fiume, cioè il Tigri,"],
[10005,"alzai gli occhi e guardai, ed ecco un uomo vestito di lino, con ai fianchi una cintura d'oro di Ufaz;"],
[10006,"il suo corpo somigliava a topazio, la sua faccia aveva l'aspetto della folgore, i suoi occhi erano come fiamme di fuoco, le sue braccia e le sue gambe somigliavano a bronzo lucente e il suono delle sue parole pareva il clamore di una moltitudine."],
[10007,"Soltanto io, Daniele, vidi la visione, mentre gli uomini che erano con me non la videro, ma un grande terrore si impadronì di loro e fuggirono a nascondersi."],
[10008,"Io rimasi solo a contemplare quella grande visione, mentre mi sentivo senza forze; il mio colorito si fece smorto e mi vennero meno le forze."],
[10009,"Udii il suono delle sue parole, ma, appena udito il suono delle sue parole, caddi stordito con la faccia a terra."],
[10010,"Ed ecco, una mano mi toccò e tutto tremante mi fece alzare sulle ginocchia, appoggiato sulla palma delle mani."],
[10011,"Poi egli mi disse: \"Daniele, uomo prediletto, intendi le parole che io ti rivolgo, alzati in piedi, perché ora sono stato mandato a te\". Quando mi ebbe detto questo, io mi alzai in piedi tremando."],
[10012,"Egli mi disse: \"Non temere, Daniele, perché fin dal primo giorno in cui ti sei sforzato di intendere, umiliandoti davanti a Dio, le tue parole sono state ascoltate e io sono venuto in risposta alle tue parole."],
[10013,"Ma il principe del regno di Persia mi si è opposto per ventun giorni: però Michele, uno dei principi supremi, mi è venuto in aiuto e io l'ho lasciato là presso il principe del re di Persia;"],
[10014,"ora sono venuto per farti intendere ciò che avverrà al tuo popolo alla fine dei giorni, poiché c'è ancora una visione per quei giorni\"."],
[10015,"Mentre egli parlava con me in questa maniera, chinai la faccia a terra e ammutolii."],
[10016,"Ed ecco, uno con sembianze di uomo mi toccò le labbra: io aprii la bocca e parlai e dissi a colui che era in piedi davanti a me: \"Signore mio, nella visione i miei dolori sono tornati su di me e ho perduto tutte le energie."],
[10017,"Come potrebbe questo servo del mio signore parlare con il mio signore, dal momento che non è rimasto in me alcun vigore e mi manca anche il respiro?\"."],
[10018,"Allora di nuovo quella figura d'uomo mi toccò, mi rese le forze"],
[10019,"e mi disse: \"Non temere, uomo prediletto, pace a te, riprendi forza, rinfrancati\". Mentre egli parlava con me, io mi sentii ritornare le forze e dissi: \"Parli il mio signore, perché tu mi hai ridato forza\"."],
[10020,"Allora mi disse: \"Sai perché io sono venuto da te? Ora tornerò di nuovo a lottare con il principe di Persia, poi uscirò, ed ecco, verrà il principe di Iavan."],
[10021,"Io ti dichiarerò ciò che è scritto nel libro della verità. Nessuno mi aiuta in questo, se non Michele, il vostro principe."],
[11001,"E io, nell'anno primo di Dario, il Medo, mi tenni presso di lui per dargli rinforzo e sostegno."],
[11002,"E ora io ti manifesterò la verità. Ecco, vi saranno ancora tre re in Persia, poi il quarto acquisterà ricchezze superiori a tutti gli altri e, dopo essersi reso potente con le ricchezze, muoverà con tutti i suoi contro il regno di Iavan."],
[11003,"Sorgerà quindi un re potente, che dominerà sopra un grande impero e farà ciò che vuole,"],
[11004,"ma appena si sarà affermato, il suo regno verrà smembrato e diviso ai quattro venti del cielo, ma non fra i suoi discendenti né con la stessa forza che egli possedeva; il suo regno sarà infatti estirpato e dato ad altri anziché ai suoi discendenti."],
[11005,"Il re del mezzogiorno diverrà potente e uno dei suoi capitani sarà più forte di lui e il suo impero sarà grande."],
[11006,"Dopo qualche anno faranno alleanza e la figlia del re del mezzogiorno verrà al re del settentrione per fare la pace, ma non potrà conservare la forza del suo braccio e non resisterà né lei né la sua discendenza e sarà condannata a morte insieme con i suoi seguaci, il figlio e colui che l'ha sostenuta."],
[11007,"In quei tempi da un germoglio delle sue radici sorgerà uno, al posto di costui, e verrà con un esercito e avanzerà contro le fortezze del re del settentrione, le assalirà e se ne impadronirà."],
[11008,"Condurrà in Egitto i loro dei con le loro immagini e i loro preziosi oggetti d'argento e d'oro, come preda di guerra; poi per qualche anno si asterrà dal contendere con il re del settentrione."],
[11009,"Andrà nel regno del re del mezzogiorno e tornerà nella sua terra."],
[11010,"Poi suo figlio si preparerà alla guerra, raccogliendo una moltitudine di grandi eserciti, con i quali avanzerà come un'inondazione: attraverserà il paese per attaccare di nuovo battaglia e giungere sino alla sua fortezza."],
[11011,"Il re del mezzogiorno, inasprito, uscirà per combattere contro il re del settentrione, che si muoverà con un grande esercito, ma questo cadrà in potere del re del mezzogiorno,"],
[11012,"il quale, dopo aver disfatto quell'esercito, si gonfierà d'orgoglio, ma pur avendo abbattuto decine di migliaia, non per questo sarà più forte."],
[11013,"Il re del settentrione di nuovo metterà insieme un grande esercito, più grande di quello di prima, e dopo qualche anno avanzerà con un grande esercito e con grande apparato."],
[11014,"In quel tempo molti si alzeranno contro il re del mezzogiorno e uomini violenti del tuo popolo insorgeranno per dare compimento alla visione, ma cadranno."],
[11015,"Il re del settentrione verrà, costruirà terrapieni e occuperà una città ben fortificata. Le forze del mezzogiorno, con truppe scelte, non potranno resistere; mancherà loro la forza per opporre resistenza."],
[11016,"L'invasore farà ciò che vorrà e nessuno gli si potrà opporre; si stabilirà in quella magnifica terra e la distruzione sarà nelle sue mani."],
[11017,"Quindi si proporrà di occupare tutto il regno del re del mezzogiorno, stipulerà un'alleanza con lui e gli darà sua figlia per rovinarlo, ma la cosa non riuscirà e non raggiungerà il suo scopo."],
[11018,"Poi si volgerà verso le isole e ne prenderà molte, ma un comandante farà cessare la sua arroganza, facendola ricadere sopra di lui."],
[11019,"Si volgerà poi verso le fortezze del proprio paese, ma inciamperà, cadrà, scomparirà."],
[11020,"Sorgerà quindi al suo posto uno che manderà esattori nella terra che è splendore del suo regno, ma in pochi giorni sarà stroncato, non nel furore di una rivolta né in battaglia."],
[11021,"Gli succederà poi un uomo abietto, privo di dignità regale: verrà di sorpresa e occuperà il regno con la frode."],
[11022,"Le forze armate saranno annientate davanti a lui e sarà stroncato anche il capo dell'alleanza."],
[11023,"Non appena sarà stata stipulata un'alleanza con lui, egli agirà con la frode, crescerà e si consoliderà con poca gente."],
[11024,"Entrerà di sorpresa nei luoghi più fertili della provincia e farà cose che né i suoi padri né i padri dei suoi padri osarono fare; distribuirà alla sua gente preda, spoglie e ricchezze e ordirà progetti contro le fortezze, ma ciò fino a un certo tempo."],
[11025,"La sua potenza e il suo ardire lo spingeranno contro il re del mezzogiorno con un grande esercito, e il re del mezzogiorno verrà a battaglia con un grande e potente esercito, ma non potrà resistere, perché si ordiranno congiure contro di lui."],
[11026,"I suoi stessi commensali saranno causa della sua rovina; il suo esercito sarà travolto e molti cadranno uccisi."],
[11027,"I due re non penseranno che a farsi del male a vicenda e, seduti alla stessa tavola, parleranno con finzione, ma senza riuscire nei reciproci intenti, perché li attenderà la fine, al tempo stabilito."],
[11028,"Egli ritornerà nel suo paese con grandi ricchezze e con in cuore l'avversione alla santa alleanza: agirà secondo i suoi piani e poi ritornerà nel suo paese."],
[11029,"Al tempo determinato verrà di nuovo contro il paese del mezzogiorno, ma quest'ultima impresa non riuscirà come la prima."],
[11030,"Verranno contro lui navi dei Chittim ed egli si sentirà scoraggiato e tornerà indietro. Si volgerà infuriato e agirà contro la santa alleanza, e al suo ritorno se la intenderà con coloro che avranno abbandonato la santa alleanza."],
[11031,"Forze da lui armate si muoveranno a profanare il santuario della cittadella, aboliranno il sacrificio quotidiano e vi metteranno l'abominio devastante."],
[11032,"Con lusinghe egli sedurrà coloro che avranno tradito l'alleanza, ma quanti riconoscono il proprio Dio si fortificheranno e agiranno."],
[11033,"I più saggi tra il popolo ammaestreranno molti, ma cadranno di spada, saranno dati alle fiamme, condotti in schiavitù e depredati per molti giorni."],
[11034,"Mentre così cadranno, riceveranno un piccolo aiuto: molti però si uniranno a loro, ma senza sincerità."],
[11035,"Alcuni saggi cadranno perché fra loro vi siano di quelli purificati, lavati, resi candidi fino al tempo della fine, che dovrà venire al tempo stabilito."],
[11036,"Il re dunque farà ciò che vuole, s'innalzerà, si magnificherà sopra ogni dio e proferirà cose inaudite contro il Dio degli dei e avrà successo finché non sarà colma l'ira; poiché ciò che è stato decretato si compirà."],
[11037,"Egli non si curerà neppure degli dei dei suoi padri né del dio amato dalle donne né di altro dio, poiché egli si esalterà sopra tutti."],
[11038,"Onorerà invece il dio delle fortezze: onorerà, con oro e argento, con gemme e con cose preziose, un dio che i suoi padri non hanno mai conosciuto."],
[11039,"Nel nome di quel dio straniero attaccherà i bastioni delle fortezze e colmerà di onori coloro che lo riconosceranno: darà loro il potere su molti e distribuirà loro terre in ricompensa."],
[11040,"Al tempo della fine il re del mezzogiorno si scontrerà con lui e il re del settentrione gli piomberà addosso, come turbine, con carri, con cavalieri e molte navi; entrerà nel suo territorio e attraversandolo lo invaderà."],
[11041,"Entrerà anche in quella magnifica terra e molti paesi soccomberanno. Questi però scamperanno dalla sua mano: Edom, Moab e la parte migliore degli Ammoniti."],
[11042,"Metterà così la mano su molti paesi; neppure l'Egitto scamperà."],
[11043,"S'impadronirà di tesori d'oro e d'argento e di tutte le cose preziose d'Egitto: i Libi e gli Etiopi saranno al suo seguito."],
[11044,"Ma notizie dall'oriente e dal settentrione lo turberanno: egli partirà con grande ira per distruggere e disperdere molti."],
[11045,"Pianterà le tende reali fra il mare e lo splendore della santa montagna; poi giungerà alla fine e nessuno verrà in suo aiuto."],
[12001,"Ora, in quel tempo, sorgerà Michele, il gran principe, che vigila sui figli del tuo popolo. Sarà un tempo di angoscia, come non c'era stata mai dal sorgere delle nazioni fino a quel tempo; in quel tempo sarà salvato il tuo popolo, chiunque si troverà scritto nel libro."],
[12002,"Molti di quelli che dormono nella regione della polvere si risveglieranno: gli uni alla vita eterna e gli altri alla vergogna e per l'infamia eterna."],
[12003,"I saggi risplenderanno come lo splendore del firmamento; coloro che avranno indotto molti alla giustizia risplenderanno come le stelle per sempre."],
[12004,"Ora tu, Daniele, chiudi queste parole e sigilla questo libro, fino al tempo della fine: allora molti lo scorreranno e la loro conoscenza sarà accresciuta\"."],
[12005,"Io, Daniele, stavo guardando, ed ecco altri due che stavano in piedi, uno di qua sulla sponda del fiume, l'altro di là sull'altra sponda."],
[12006,"Uno disse all'uomo vestito di lino, che era sulle acque del fiume: \"Quando si compiranno queste cose meravigliose?\"."],
[12007,"Udii l'uomo vestito di lino, che era sulle acque del fiume, il quale, alzate la destra e la sinistra al cielo, giurò per colui che vive in eterno che tutte queste cose si sarebbero realizzate fra un tempo, tempi e metà di un tempo, quando fosse giunta a compimento la distruzione della potenza del popolo santo."],
[12008,"Io udii bene, ma non compresi, e dissi: \"Signore mio, quale sarà la fine di queste cose?\"."],
[12009,"Egli mi rispose: \"Va', Daniele, queste parole sono nascoste e sigillate fino al tempo della fine."],
[12010,"Molti saranno purificati, resi candidi, integri, ma gli empi agiranno empiamente: nessuno degli empi intenderà queste cose, ma i saggi le intenderanno."],
[12011,"Ora, dal tempo in cui sarà abolito il sacrificio quotidiano e sarà eretto l'abominio devastante, passeranno milleduecentonovanta giorni."],
[12012,"Beato chi aspetterà con pazienza e giungerà a milletrecentotrentacinque giorni."],
[12013,"Tu, va' pure alla tua fine e riposa: ti alzerai per la tua sorte alla fine dei giorni\"."],
[13001,"Abitava a Babilonia un uomo chiamato Ioakim,"],
[13002,"il quale aveva sposato una donna chiamata Susanna, figlia di Chelkia, di rara bellezza e timorata di Dio."],
[13003,"I suoi genitori, che erano giusti, avevano educato la figlia secondo la legge di Mosè."],
[13004,"Ioakim era molto ricco e possedeva un giardino vicino a casa, ed essendo stimato più di ogni altro, i Giudei andavano da lui."],
[13005,"In quell'anno erano stati eletti giudici del popolo due anziani; erano di quelli di cui il Signore ha detto: \"L'iniquità è uscita da Babilonia per opera di anziani e di giudici, che solo in apparenza sono guide del popolo\"."],
[13006,"Questi frequentavano la casa di Ioakim, e tutti quelli che avevano qualche lite da risolvere si recavano da loro."],
[13007,"Quando il popolo, verso il mezzogiorno, se ne andava, Susanna era solita recarsi a passeggiare nel giardino del marito."],
[13008,"I due anziani, che ogni giorno la vedevano andare a passeggiare, furono presi da un'ardente passione per lei:"],
[13009,"persero il lume della ragione, distolsero gli occhi per non vedere il Cielo e non ricordare i giusti giudizi."],
[13010,"Erano colpiti tutti e due dalla passione per lei, ma l'uno nascondeva all'altro la sua pena,"],
[13011,"perché si vergognavano di rivelare la brama che avevano di unirsi a lei."],
[13012,"Ogni giorno con maggior desiderio cercavano di vederla."],
[13013,"Un giorno uno disse all'altro: \"Andiamo pure a casa: è l'ora di desinare\". E usciti se ne andarono."],
[13014,"Ma ritornati indietro, si ritrovarono di nuovo insieme e, domandandosi a vicenda il motivo, confessarono la propria passione. Allora studiarono il momento opportuno di poterla sorprendere da sola."],
[13015,"Mentre aspettavano l'occasione favorevole, Susanna entrò, come al solito, con due sole ancelle, nel giardino per fare il bagno, poiché faceva caldo."],
[13016,"Non c'era nessun altro al di fuori dei due anziani, nascosti a spiarla."],
[13017,"Susanna disse alle ancelle: \"Portatemi l'unguento e i profumi, poi chiudete la porta, perché voglio fare il bagno\"."],
[13018,"Esse fecero come aveva ordinato: chiusero le porte del giardino e uscirono dalle porte laterali per portare ciò che Susanna chiedeva, senza accorgersi degli anziani, poiché si erano nascosti."],
[13019,"Appena partite le ancelle, i due anziani uscirono dal nascondiglio, corsero da lei"],
[13020,"e le dissero: \"Ecco, le porte del giardino sono chiuse, nessuno ci vede e noi bruciamo di passione per te; acconsenti e concediti a noi."],
[13021,"In caso contrario ti accuseremo; diremo che un giovane era con te e perciò hai fatto uscire le ancelle\"."],
[13022,"Susanna, piangendo, esclamò: \"Sono in difficoltà da ogni parte. Se cedo, è la morte per me; se rifiuto, non potrò scampare dalle vostre mani."],
[13023,"Meglio però per me cadere innocente nelle vostre mani che peccare davanti al Signore!\"."],
[13024,"Susanna gridò a gran voce. Anche i due anziani gridarono contro di lei"],
[13025,"e uno di loro corse alle porte del giardino e le aprì."],
[13026,"I servi di casa, all'udire tale rumore in giardino, si precipitarono dalla porta laterale per vedere che cosa le stava accadendo."],
[13027,"Quando gli anziani ebbero fatto il loro racconto, i servi si sentirono molto confusi, perché mai era stata detta una simile cosa di Susanna."],
[13028,"Il giorno dopo, quando il popolo si radunò nella casa di Ioakim, suo marito, andarono là anche i due anziani, pieni di perverse intenzioni, per condannare a morte Susanna."],
[13029,"Rivolti al popolo dissero: \"Si faccia venire Susanna, figlia di Chelkia, moglie di Ioakim\". Mandarono a chiamarla"],
[13030,"ed ella venne con i genitori, i figli e tutti i suoi parenti."],
[13031,"Susanna era assai delicata e bella di aspetto;"],
[13032,"aveva il velo e quei perversi ordinarono che le fosse tolto, per godere almeno così della sua bellezza."],
[13033,"Tutti i suoi familiari e amici piangevano."],
[13034,"I due anziani si alzarono in mezzo al popolo e posero le mani sulla sua testa."],
[13035,"Ella piangendo alzò gli occhi al cielo, con il cuore pieno di fiducia nel Signore."],
[13036,"Gli anziani dissero: \"Mentre noi stavamo passeggiando soli nel giardino, è venuta con due ancelle, ha chiuso le porte del giardino e poi ha licenziato le ancelle."],
[13037,"Quindi è entrato da lei un giovane, che era nascosto, e si è unito a lei."],
[13038,"Noi, che eravamo in un angolo del giardino, vedendo quella iniquità ci siamo precipitati su di loro."],
[13039,"Li abbiamo sorpresi insieme, ma non abbiamo potuto prendere il giovane perché, più forte di noi, ha aperto la porta ed è fuggito."],
[13040,"Abbiamo preso lei e le abbiamo domandato chi era quel giovane,"],
[13041,"ma lei non ce l'ha voluto dire. Di questo noi siamo testimoni\". La moltitudine prestò loro fede, poiché erano anziani e giudici del popolo, e la condannò a morte."],
[13042,"Allora Susanna ad alta voce esclamò: \"Dio eterno, che conosci i segreti, che conosci le cose prima che accadano,"],
[13043,"tu lo sai che hanno deposto il falso contro di me! Io muoio innocente di quanto essi iniquamente hanno tramato contro di me\"."],
[13044,"E il Signore ascoltò la sua voce."],
[13045,"Mentre Susanna era condotta a morte, il Signore suscitò il santo spirito di un giovanetto, chiamato Daniele,"],
[13046,"il quale si mise a gridare: \"Io sono innocente del sangue di lei!\"."],
[13047,"Tutti si voltarono verso di lui dicendo: \"Che cosa vuoi dire con queste tue parole?\"."],
[13048,"Allora Daniele, stando in mezzo a loro, disse: \"Siete così stolti, o figli d'Israele? Avete condannato a morte una figlia d'Israele senza indagare né appurare la verità!"],
[13049,"Tornate al tribunale, perché costoro hanno deposto il falso contro di lei\"."],
[13050,"Il popolo tornò subito indietro e gli anziani dissero a Daniele: \"Vieni, siedi in mezzo a noi e facci da maestro, poiché Dio ti ha concesso le prerogative dell'anzianità\"."],
[13051,"Daniele esclamò: \"Separateli bene l'uno dall'altro e io li giudicherò\"."],
[13052,"Separati che furono, Daniele disse al primo: \"O uomo invecchiato nel male! Ecco, i tuoi peccati commessi in passato vengono alla luce,"],
[13053,"quando davi sentenze ingiuste, opprimendo gli innocenti e assolvendo i malvagi, mentre il Signore ha detto: Non ucciderai il giusto e l'innocente."],
[13054,"Ora, dunque, se tu hai visto costei, di': sotto quale albero tu li hai visti stare insieme?\". Rispose: \"Sotto un lentisco\"."],
[13055,"Disse Daniele: \"In verità, la tua menzogna ti ricadrà sulla testa. Già l'angelo di Dio ha ricevuto da Dio la sentenza e ti squarcerà in due\"."],
[13056,"Allontanato questi, fece venire l'altro e gli disse: \"Stirpe di Canaan e non di Giuda, la bellezza ti ha sedotto, la passione ti ha pervertito il cuore!"],
[13057,"Così facevate con le donne d'Israele ed esse per paura si univano a voi. Ma una figlia di Giuda non ha potuto sopportare la vostra iniquità."],
[13058,"Dimmi dunque, sotto quale albero li hai sorpresi insieme?\". Rispose: \"Sotto un leccio\"."],
[13059,"Disse Daniele: \"In verità anche la tua menzogna ti ricadrà sulla testa. Ecco, l'angelo di Dio ti aspetta con la spada in mano, per tagliarti in due e così farti morire\"."],
[13060,"Allora tutta l'assemblea proruppe in grida di gioia e benedisse Dio, che salva coloro che sperano in lui."],
[13061,"Poi, insorgendo contro i due anziani, ai quali Daniele aveva fatto confessare con la loro bocca di avere deposto il falso, fece loro subire la medesima pena che avevano tramato contro il prossimo"],
[13062,"e, applicando la legge di Mosè, li fece morire. In quel giorno fu salvato il sangue innocente."],
[13063,"Chelkia e sua moglie resero grazie a Dio per la figlia Susanna, insieme con il marito Ioakim e tutti i suoi parenti, per non aver trovato in lei nulla di vergognoso."],
[13064,"Da quel giorno in poi Daniele divenne grande di fronte al popolo."],
[14001,"Il re Astiage si riunì ai suoi padri e gli succedette nel regno Ciro, il Persiano."],
[14002,"Ora Daniele era intimo del re, ed era il più onorato di tutti gli amici del re."],
[14003,"I Babilonesi avevano un idolo chiamato Bel, al quale offrivano ogni giorno dodici sacchi di fior di farina, quaranta pecore e sei barili di vino."],
[14004,"Anche il re venerava questo idolo e andava ogni giorno ad adorarlo. Daniele però adorava il suo Dio"],
[14005,"e perciò il re gli disse: \"Perché non adori Bel?\". Daniele rispose: \"Io non adoro idoli fatti da mani d'uomo, ma soltanto il Dio vivo che ha fatto il cielo e la terra e che ha potere su ogni essere vivente\"."],
[14006,"\"Non credi tu - aggiunse il re - che Bel sia un dio vivo? Non vedi quanto beve e mangia ogni giorno?\"."],
[14007,"Rispose Daniele ridendo: \"Non t'ingannare, o re: quell'idolo di dentro è d'argilla e di fuori è di bronzo e non ha mai mangiato né bevuto\"."],
[14008,"Il re s'indignò e convocati i sacerdoti di Bel disse loro: \"Se voi non mi dite chi è che mangia tutto questo cibo, morirete; se invece mi proverete che è Bel che lo mangia, morirà Daniele, perché ha insultato Bel\"."],
[14009,"Daniele disse al re: \"Sia fatto come tu hai detto\". I sacerdoti di Bel erano settanta, senza contare le mogli e i figli."],
[14010,"Il re si recò insieme con Daniele al tempio di Bel"],
[14011,"e i sacerdoti di Bel gli dissero: \"Ecco, noi usciamo di qui e tu, o re, disponi le vivande e mesci il vino temperato; poi chiudi la porta e sigillala con il tuo anello. Se domani mattina, venendo, tu riscontrerai che tutto non è stato mangiato da Bel, moriremo noi, altrimenti morirà Daniele che ci ha calunniati\"."],
[14012,"Essi però non erano preoccupati, perché avevano praticato un passaggio segreto sotto la tavola, per il quale passavano abitualmente e consumavano tutto."],
[14013,"Dopo che essi se ne furono andati, il re fece porre i cibi davanti a Bel."],
[14014,"Daniele ordinò ai servi del re di portare un po' di cenere e la sparsero su tutto il pavimento del tempio alla presenza soltanto del re; poi uscirono, chiusero la porta, la sigillarono con l'anello del re e se ne andarono."],
[14015,"I sacerdoti vennero di notte, secondo il loro consueto, con le mogli, i figli, e mangiarono e bevvero tutto."],
[14016,"Di buon mattino il re si alzò, come anche Daniele."],
[14017,"Il re domandò: \"Sono intatti i sigilli, Daniele?\". \"Intatti, o re\", rispose."],
[14018,"Aperta la porta, il re guardò la tavola ed esclamò: \"Tu sei grande, Bel, e nessun inganno è in te!\"."],
[14019,"Daniele sorrise e, trattenendo il re perché non entrasse, disse: \"Guarda il pavimento ed esamina di chi sono quelle orme\"."],
[14020,"Il re disse: \"Vedo orme di uomini, di donne e di ragazzi!\"."],
[14021,"Acceso d'ira, fece arrestare i sacerdoti con le mogli e i figli, e gli mostrarono le porte segrete per le quali entravano a consumare quanto si trovava sulla tavola."],
[14022,"Quindi il re li fece uccidere, consegnò Bel in potere di Daniele, che lo distrusse insieme con il tempio."],
[14023,"Vi era un grande drago e i Babilonesi lo veneravano."],
[14024,"Il re disse a Daniele: \"Non potrai dire che questo non è un dio vivente; adoralo, dunque\"."],
[14025,"Daniele rispose: \"Io adoro il Signore, mio Dio, perché egli è il Dio vivente; se tu me lo permetti, o re, io, senza spada e senza bastone, ucciderò il drago\"."],
[14026,"Soggiunse il re: \"Te lo permetto\"."],
[14027,"Daniele prese allora pece, grasso e peli e li fece cuocere insieme, poi preparò delle polpette e le gettò in bocca al drago che le inghiottì e scoppiò; quindi soggiunse: \"Ecco che cosa adoravate!\"."],
[14028,"Quando i Babilonesi lo seppero, ne furono molto indignati e insorsero contro il re, dicendo: \"Il re è diventato giudeo: ha distrutto Bel, ha ucciso il drago, ha messo a morte i sacerdoti\"."],
[14029,"Andarono da lui dicendo: \"Consegnaci Daniele, altrimenti uccidiamo te e la tua famiglia!\"."],
[14030,"Quando il re vide che lo assalivano con violenza, costretto dalla necessità consegnò loro Daniele."],
[14031,"Ed essi lo gettarono nella fossa dei leoni, dove rimase sei giorni."],
[14032,"Nella fossa vi erano sette leoni, ai quali venivano dati ogni giorno due cadaveri e due pecore: ma quella volta non fu dato loro niente, perché divorassero Daniele."],
[14033,"Si trovava allora in Giudea il profeta Abacuc, il quale aveva fatto una minestra e aveva spezzettato il pane in un recipiente e ora andava a portarli nel campo ai mietitori."],
[14034,"L'angelo del Signore gli disse: \"Porta questo cibo a Daniele a Babilonia nella fossa dei leoni\"."],
[14035,"Ma Abacuc rispose: \"Signore, Babilonia non l'ho mai vista e la fossa non la conosco\"."],
[14036,"Allora l'angelo del Signore lo prese per la cima della testa e sollevandolo per i capelli lo portò a Babilonia, sull'orlo della fossa dei leoni, con l'impeto del suo soffio."],
[14037,"Gridò Abacuc: \"Daniele, Daniele, prendi il cibo che Dio ti ha mandato\"."],
[14038,"Daniele esclamò: \"Dio, ti sei ricordato di me e non hai abbandonato coloro che ti amano\"."],
[14039,"Alzatosi, Daniele si mise a mangiare. L'angelo di Dio riportò subito Abacuc nella sua terra."],
[14040,"Il settimo giorno il re andò per piangere Daniele e, giunto alla fossa, guardò e vide Daniele seduto."],
[14041,"Allora esclamò ad alta voce: \"Grande tu sei, Signore, Dio di Daniele, e non c'è altro dio all'infuori di te!\"."],
[14042,"Poi fece uscire Daniele dalla fossa e vi fece gettare coloro che volevano la sua rovina, ed essi furono subito divorati sotto i suoi occhi."]
])
