Bib.ret([
[1001,"Nell'anno primo di Ciro, re di Persia, perché si adempisse la parola che il Signore aveva detto per bocca di Geremia, il Signore suscitò lo spirito di Ciro, re di Persia, che fece proclamare per tutto il suo regno, anche per iscritto:"],
[1002,"\"Così dice Ciro, re di Persia: \"Il Signore, Dio del cielo, mi ha concesso tutti i regni della terra. Egli mi ha incaricato di costruirgli un tempio a Gerusalemme, che è in Giuda."],
[1003,"Chiunque di voi appartiene al suo popolo, il suo Dio sia con lui e salga a Gerusalemme, che è in Giuda, e costruisca il tempio del Signore, Dio d'Israele: egli è il Dio che è a Gerusalemme."],
[1004,"E a ogni superstite da tutti i luoghi dove aveva dimorato come straniero, gli abitanti del luogo forniranno argento e oro, beni e bestiame, con offerte spontanee per il tempio di Dio che è a Gerusalemme\"\"."],
[1005,"Allora si levarono i capi di casato di Giuda e di Beniamino e i sacerdoti e i leviti. A tutti Dio aveva destato lo spirito, affinché salissero a costruire il tempio del Signore che è a Gerusalemme."],
[1006,"Tutti i loro vicini li sostennero con oggetti d'argento, oro, beni, bestiame e oggetti preziosi, oltre a quello che ciascuno offrì spontaneamente."],
[1007,"Anche il re Ciro fece prelevare gli utensili del tempio del Signore, che Nabucodonosor aveva asportato da Gerusalemme e aveva deposto nel tempio del suo dio."],
[1008,"Ciro, re di Persia, li fece prelevare da Mitridate, il tesoriere, e li consegnò a Sesbassar, principe di Giuda."],
[1009,"Questo è il loro inventario: bacili d'oro: trenta; bacili d'argento: mille; coltelli: ventinove;"],
[1010,"coppe d'oro: trenta; coppe d'argento di second'ordine: quattrocentodieci; altri utensili: mille."],
[1011,"Tutti gli utensili d'oro e d'argento erano cinquemilaquattrocento. Sesbassar li riportò tutti, quando gli esuli tornarono da Babilonia a Gerusalemme."],
[2001,"Questi sono gli abitanti della provincia che ritornarono dall'esilio, quelli che Nabucodonosor, re di Babilonia, aveva deportato a Babilonia e che tornarono a Gerusalemme e in Giudea, ognuno alla sua città; essi vennero"],
[2002,"con Zorobabele, Giosuè, Neemia, Seraià, Reelaià, Mardocheo, Bilsan, Mispar, Bigvai, Recum, Baanà. Questa è la lista degli uomini del popolo d'Israele."],
[2003,"Figli di Paros: duemilacentosettantadue."],
[2004,"Figli di Sefatia: trecentosettantadue."],
[2005,"Figli di Arach: settecentosettantacinque."],
[2006,"Figli di Pacat-Moab, cioè figli di Giosuè e di Ioab: duemilaottocentododici."],
[2007,"Figli di Elam: milleduecentocinquantaquattro."],
[2008,"Figli di Zattu: novecentoquarantacinque."],
[2009,"Figli di Zaccai: settecentosessanta."],
[2010,"Figli di Banì: seicentoquarantadue."],
[2011,"Figli di Bebai: seicentoventitré."],
[2012,"Figli di Azgad: milleduecentoventidue."],
[2013,"Figli di Adonikam: seicentosessantasei."],
[2014,"Figli di Bigvai: duemilacinquantasei."],
[2015,"Figli di Adin: quattrocentocinquantaquattro."],
[2016,"Figli di Ater, cioè di Ezechia: novantotto."],
[2017,"Figli di Besai: trecentoventitré."],
[2018,"Figli di Iora: centododici."],
[2019,"Figli di Casum: duecentoventitré."],
[2020,"Figli di Ghibbar: novantacinque."],
[2021,"Figli di Betlemme: centoventitré."],
[2022,"Uomini di Netofà: cinquantasei."],
[2023,"Uomini di Anatot: centoventotto."],
[2024,"Figli di Azmavet: quarantadue."],
[2025,"Figli di Kiriat-Iearim, di Chefirà e di Beerot: settecentoquarantatré."],
[2026,"Figli di Rama e di Gheba: seicentoventuno."],
[2027,"Uomini di Micmas: centoventidue."],
[2028,"Uomini di Betel e di Ai: duecentoventitré."],
[2029,"Figli di Nebo: cinquantadue."],
[2030,"Figli di Magbis: centocinquantasei."],
[2031,"Figli di un altro Elam: milleduecentocinquantaquattro."],
[2032,"Figli di Carim: trecentoventi."],
[2033,"Figli di Lod, Adid e Ono: settecentoventicinque."],
[2034,"Figli di Gerico: trecentoquarantacinque."],
[2035,"Figli di Senaà: tremilaseicentotrenta."],
[2036,"Sacerdoti: figli di Iedaià della casa di Giosuè: novecentosettantatré."],
[2037,"Figli di Immer: millecinquantadue."],
[2038,"Figli di Pascur: milleduecentoquarantasette."],
[2039,"Figli di Carim: millediciassette."],
[2040,"Leviti: figli di Giosuè e di Kadmiel, cioè figli di Odavia: settantaquattro."],
[2041,"Cantori: figli di Asaf: centoventotto."],
[2042,"Portieri: figli di Sallum, figli di Ater, figli di Talmon, figli di Akkub, figli di Catità, figli di Sobai: in tutto centotrentanove."],
[2043,"Oblati: figli di Sica, figli di Casufà, figli di Tabbaot,"],
[2044,"figli di Keros, figli di Siaà, figli di Padon,"],
[2045,"figli di Lebanà, figli di Agabà, figli di Akkub,"],
[2046,"figli di Agab, figli di Samlai, figli di Canan,"],
[2047,"figli di Ghiddel, figli di Gacar, figli di Reaià,"],
[2048,"figli di Resin, figli di Nekodà, figli di Gazzam,"],
[2049,"figli di Uzzà, figli di Paseach, figli di Besai,"],
[2050,"figli di Asna, figli dei Meuniti, figli dei Nefisiti,"],
[2051,"figli di Bakbuk, figli di Akufà, figli di Carcur,"],
[2052,"figli di Baslut, figli di Mechidà, figli di Carsa,"],
[2053,"figli di Barkos, figli di Sisara, figli di Temach,"],
[2054,"figli di Nesiach, figli di Catifà."],
[2055,"Figli degli schiavi di Salomone: figli di Sotai, figli di Assoferet, figli di Perudà,"],
[2056,"figli di Iala, figli di Darkon, figli di Ghiddel,"],
[2057,"figli di Sefatia, figli di Cattil, figli di Pocheret-Assebaim, figli di Amì."],
[2058,"Totale degli oblati e dei figli degli schiavi di Salomone: trecentonovantadue."],
[2059,"Questi sono coloro che ritornarono da Tel-Melach, Tel-Carsa, Cherub-Addan e Immer, ma non avevano potuto indicare se il loro casato e la loro discendenza fossero d'Israele:"],
[2060,"i figli di Delaià, i figli di Tobia, i figli di Nekodà: seicentocinquantadue;"],
[2061,"tra i sacerdoti, i figli di Cobaià, i figli di Akkos, i figli di Barzillai, il quale aveva preso in moglie una delle figlie di Barzillai, il Galaadita, e veniva chiamato con il loro nome."],
[2062,"Costoro cercarono il loro registro genealogico, ma non lo trovarono e furono allora esclusi dal sacerdozio."],
[2063,"Il governatore disse loro che non potevano mangiare le cose santissime, finché non si presentasse un sacerdote con urim e tummim."],
[2064,"Tutta la comunità nel suo insieme era di quarantaduemilatrecentosessanta persone,"],
[2065,"oltre i loro schiavi e le loro schiave in numero di settemilatrecentotrentasette; avevano anche duecento cantori e cantatrici."],
[2066,"I loro cavalli erano settecentotrentasei, i loro muli duecentoquarantacinque,"],
[2067,"i loro cammelli quattrocentotrentacinque e gli asini seimilasettecentoventi."],
[2068,"Alcuni capi di casato, al loro arrivo al tempio del Signore che è a Gerusalemme, fecero offerte spontanee al tempio di Dio per edificarlo al suo posto."],
[2069,"Secondo le loro possibilità diedero al tesoro della fabbrica sessantunmila dracme d'oro, cinquemila mine d'argento e cento tuniche sacerdotali."],
[2070,"Poi i sacerdoti, i leviti, alcuni del popolo, i cantori, i portieri e gli oblati si stabilirono nelle loro città e tutti gli Israeliti nelle loro città."],
[3001,"Giunse il settimo mese e gli Israeliti stavano nelle città. Il popolo si radunò come un solo uomo a Gerusalemme."],
[3002,"Allora si levarono Giosuè, figlio di Iosadak, con i suoi fratelli, i sacerdoti, e Zorobabele, figlio di Sealtiel, con i suoi fratelli, e costruirono l'altare del Dio d'Israele, per offrirvi olocausti, come è scritto nella legge di Mosè, uomo di Dio."],
[3003,"Fissarono l'altare sulle sue basi, poiché erano presi dal terrore delle popolazioni locali, e vi offrirono sopra olocausti al Signore, gli olocausti del mattino e della sera."],
[3004,"Celebrarono la festa delle Capanne, come sta scritto, e offrirono olocausti quotidiani, nel numero prescritto per ogni giorno,"],
[3005,"e poi l'olocausto perenne, per i noviluni, per tutte le solennità consacrate al Signore e per tutti coloro che volevano fare offerte spontanee al Signore."],
[3006,"Cominciarono a offrire olocausti al Signore dal primo giorno del mese settimo, benché del tempio del Signore non fossero poste le fondamenta."],
[3007,"Allora diedero denaro agli scalpellini e ai falegnami, e alimenti, bevande e olio alla gente di Sidone e di Tiro, perché inviassero il legname di cedro dal Libano per mare fino a Giaffa, secondo la concessione fatta loro da Ciro, re di Persia."],
[3008,"Nel secondo anno dal loro arrivo al tempio di Dio a Gerusalemme, nel secondo mese, diedero inizio ai lavori Zorobabele, figlio di Sealtiel, e Giosuè, figlio di Iosadak, con gli altri fratelli sacerdoti e leviti e quanti erano tornati dall'esilio a Gerusalemme. Essi incaricarono i leviti dai vent'anni in su di dirigere i lavori del tempio del Signore."],
[3009,"Giosuè, i suoi figli e i suoi fratelli, Kadmiel e i suoi figli, i figli di Giuda, si misero come un solo uomo a dirigere chi faceva il lavoro nel tempio di Dio; così pure i figli di Chenadad con i loro figli e i loro fratelli, leviti."],
[3010,"Mentre i costruttori gettavano le fondamenta del tempio del Signore, vi assistevano i sacerdoti con i loro paramenti e con le trombe, e i leviti, figli di Asaf, con i cimbali, per lodare il Signore secondo le istruzioni di Davide, re d'Israele."],
[3011,"Essi cantavano lodando e rendendo grazie al Signore, ripetendo: \"Perché è buono, perché il suo amore è per sempre verso Israele\". Tutto il popolo faceva risuonare grida di grande acclamazione, lodando così il Signore perché erano state gettate le fondamenta del tempio del Signore."],
[3012,"Tuttavia molti tra i sacerdoti e i leviti e i capi di casato anziani, che avevano visto il tempio di prima, mentre si gettavano sotto i loro occhi le fondamenta di questo tempio, piangevano forte; i più, invece, continuavano ad alzare grida di acclamazione e di gioia."],
[3013,"Così non si poteva distinguere il grido dell'acclamazione di gioia dal grido di pianto del popolo, perché il popolo faceva risuonare grida di grande acclamazione e il suono si sentiva lontano."],
[4001,"Quando i nemici di Giuda e di Beniamino vennero a sapere che gli esuli rimpatriati stavano costruendo un tempio al Signore, Dio d'Israele,"],
[4002,"si presentarono a Zorobabele e ai capi di casato e dissero: \"Vogliamo costruire anche noi insieme con voi, perché anche noi, come voi, cerchiamo il vostro Dio; a lui noi facciamo sacrifici dal tempo di Assarhaddon, re d'Assiria, che ci ha fatto salire qui\"."],
[4003,"Ma Zorobabele, Giosuè e gli altri capi di casato d'Israele dissero loro: \"Non conviene che costruiamo insieme una casa al nostro Dio; noi soltanto la costruiremo al Signore, Dio d'Israele, come Ciro, re di Persia, ci ha ordinato\"."],
[4004,"Allora la popolazione locale si mise a scoraggiare il popolo dei Giudei e a intimorirlo perché non costruisse."],
[4005,"Inoltre con denaro misero contro di loro alcuni funzionari, per far fallire il loro piano; e ciò per tutto il tempo di Ciro, re di Persia, fino al regno di Dario, re di Persia."],
[4006,"Durante il regno di Serse, al principio del suo regno, essi presentarono una denuncia contro gli abitanti di Giuda e di Gerusalemme."],
[4007,"Poi al tempo di Artaserse, Bislam, Mitridate, Tabeel e gli altri loro colleghi scrissero ad Artaserse re di Persia: il testo del documento era in caratteri aramaici e tradotto in aramaico."],
[4008,"Recum, governatore, e Simsai, scriba, scrissero al re Artaserse contro Gerusalemme la lettera seguente:"],
[4009,"\"Da parte di Recum, governatore, e Simsai, scriba, e gli altri loro colleghi giudici e prefetti, uomini di Tarpel, di Persia, di Uruc, di Babilonia e di Susa, cioè di Elam,"],
[4010,"e altri popoli che il grande e illustre Asnappar deportò e stabilì nella città di Samaria e nel resto della regione dell'Oltrefiume...\"."],
[4011,"Questa è la copia della lettera che gli mandarono:  \"Al re Artaserse i tuoi servi, uomini della regione dell'Oltrefiume."],
[4012,"Sia noto al re che i Giudei che sono partiti da te e sono venuti presso di noi, a Gerusalemme, stanno ricostruendo la città ribelle e malvagia: hanno terminato le mura e riparato le fondamenta."],
[4013,"Ora sia noto al re che, se quella città è ricostruita e le mura sono riparate, tributi, imposte e tasse non saranno più pagati e questo danneggerà i re."],
[4014,"Ora, poiché noi mangiamo il sale della reggia e per noi non è decoroso stare a guardare la spoliazione del re, mandiamo informazioni al re,"],
[4015,"perché si facciano ricerche nel libro delle memorie dei tuoi padri: tu troverai nel libro delle memorie e constaterai che quella città è una città ribelle, causa di guai per re e province, e vi hanno fatto sedizioni fin dai tempi antichi. Per questo quella città è stata distrutta."],
[4016,"Noi informiamo il re che, se quella città è ricostruita e le mura sono riparate, non avrai più possedimenti nella regione dell'Oltrefiume\"."],
[4017,"Il re inviò questa risposta:  \"A Recum, governatore, e Simsai, scriba, e agli altri loro colleghi, che risiedono in Samaria e nel resto della regione dell'Oltrefiume, salute! Ora,"],
[4018,"la lettera che ci avete mandato è stata letta davanti a me accuratamente."],
[4019,"Dietro mio ordine si sono fatte ricerche, e si è trovato che quella città fin dai tempi antichi si è sollevata contro i re e in essa sono avvenute rivolte e sedizioni."],
[4020,"A Gerusalemme vi furono re potenti che comandavano su tutto il territorio dell'Oltrefiume: a loro si pagavano tributi, imposte e tasse."],
[4021,"Date perciò ordine di fermare quegli uomini, e quella città non sia ricostruita, fino a mio ordine nuovo."],
[4022,"Badate di non essere negligenti in questo, perché non aumenti il danno arrecato al re\"."],
[4023,"Appena la copia della lettera del re Artaserse fu letta davanti a Recum e a Simsai, scriba, e ai loro colleghi, questi andarono in gran fretta a Gerusalemme dai Giudei e li fecero smettere con la forza e con la violenza."],
[4024,"Così cessò il lavoro per il tempio di Dio che è a Gerusalemme e rimase fermo fino all'anno secondo del regno di Dario, re di Persia."],
[5001,"Ma i profeti, cioè il profeta Aggeo e Zaccaria, figlio di Iddo, profetarono ai Giudei che erano in Giuda e a Gerusalemme, nel nome del Dio d'Israele, che era con loro."],
[5002,"Allora Zorobabele, figlio di Sealtiel, e Giosuè, figlio di Iosadak, si levarono e ripresero a costruire il tempio di Dio che è a Gerusalemme; con essi c'erano i profeti di Dio, che li sostenevano."],
[5003,"In quel tempo Tattenai, governatore della regione dell'Oltrefiume, Setar-Boznai e i loro colleghi vennero da loro e dissero: \"Chi vi ha dato ordine di costruire questo tempio e di preparare questo legname?"],
[5004,"Chi sono e come si chiamano gli uomini che costruiscono questo edificio?\"."],
[5005,"Ma l'occhio vigile del loro Dio era sugli anziani dei Giudei: quelli perciò non li fecero smettere, in attesa che pervenisse a Dario una relazione e poi fosse rimandato un rescritto su questo affare."],
[5006,"Ecco la copia della lettera che Tattenai, governatore dell'Oltrefiume, Setar-Boznai e i suoi colleghi, funzionari dell'Oltrefiume, mandarono al re Dario."],
[5007,"Gli mandarono un rapporto in cui era scritto:  \"Al re Dario salute perfetta!"],
[5008,"Sia noto al re che siamo andati nella provincia della Giudea, al tempio del grande Dio. Esso viene costruito con pietre squadrate e si mette legno alle pareti; quel lavoro viene fatto con diligenza e progredisce nelle loro mani."],
[5009,"Allora abbiamo interrogato quegli anziani e abbiamo detto loro: \"Chi vi ha dato ordine di costruire questo tempio e di preparare questo legname?\"."],
[5010,"Inoltre abbiamo domandato i loro nomi, per farteli conoscere, scrivendo il nome degli uomini che stanno loro a capo."],
[5011,"Essi hanno risposto: \"Noi siamo servitori del Dio del cielo e della terra e ricostruiamo il tempio che fu edificato molti anni fa. Un grande re d'Israele lo ha costruito e lo ha portato a termine."],
[5012,"Ma poiché i nostri padri hanno provocato all'ira il Dio del cielo, egli li ha messi nelle mani di Nabucodonosor, re di Babilonia, il Caldeo, che distrusse questo tempio e deportò a Babilonia il popolo."],
[5013,"Ma nel primo anno di Ciro, re di Babilonia, il re Ciro ha dato ordine di costruire questo tempio di Dio;"],
[5014,"inoltre i vasi del tempio di Dio, d'oro e d'argento, che Nabucodonosor aveva portato via dal tempio di Gerusalemme e trasferito al tempio di Babilonia, il re Ciro li ha fatti togliere dal tempio di Babilonia e li ha fatti consegnare a un tale di nome Sesbassar, che egli aveva costituito governatore."],
[5015,"Gli disse: Prendi questi vasi e va' a deporli nel tempio che è a Gerusalemme e il tempio di Dio sia costruito al suo posto."],
[5016,"Allora quel Sesbassar venne, gettò le fondamenta del tempio di Dio che è a Gerusalemme e da allora fino ad oggi esso è in costruzione, ma non è ancora finito\"."],
[5017,"Ora, se piace al re, si cerchi negli archivi del re a Babilonia se risulta che dal re Ciro sia stato emanato un decreto di costruire quel tempio di Dio a Gerusalemme, e ci venga inviata la decisione del re a questo proposito\"."],
[6001,"Allora il re Dario ordinò che si facessero ricerche nell'archivio, là dove si depongono i tesori a Babilonia,"],
[6002,"e a Ecbatana, la fortezza che è nella provincia di Media, si trovò un rotolo in cui era scritta la seguente annotazione:"],
[6003,"\"Nell'anno primo del suo regno, il re Ciro prese questa decisione riguardo al tempio di Dio a Gerusalemme: il tempio sia ricostruito come luogo in cui si facciano sacrifici; le sue fondamenta siano salde, la sua altezza sia di sessanta cubiti, la sua larghezza di sessanta cubiti."],
[6004,"Vi siano nei muri tre ordini di pietre squadrate e un ordine di legno. La spesa sia sostenuta dalla reggia."],
[6005,"E anche i vasi del tempio di Dio, d'oro e d'argento, che Nabucodonosor portò via dal tempio che è a Gerusalemme e trasferì a Babilonia, siano restituiti e vadano al tempio che è a Gerusalemme, al loro posto, e siano deposti nel tempio di Dio\"."],
[6006,"\"Quindi, Tattenai, governatore dell'Oltrefiume, Setar-Boznai e voi, loro colleghi, funzionari dell'Oltrefiume, tenetevi in disparte."],
[6007,"Lasciate che lavorino a quel tempio di Dio. Il governatore dei Giudei e i loro anziani costruiscano quel tempio di Dio al suo posto."],
[6008,"Ed ecco il mio ordine circa quello che dovrete fare con quegli anziani dei Giudei per la costruzione di quel tempio di Dio: con il denaro del re, quello delle tasse dell'Oltrefiume, siano integralmente sostenute le spese di quegli uomini, perché non vi siano interruzioni."],
[6009,"Ciò che loro occorre, giovenchi, arieti e agnelli, per gli olocausti al Dio del cielo, grano, sale, vino e olio siano loro forniti ogni giorno senza negligenza, secondo le indicazioni dei sacerdoti di Gerusalemme,"],
[6010,"perché facciano offerte di profumo gradito al Dio del cielo e preghino per la vita del re e dei suoi figli."],
[6011,"E ordino che se qualcuno trasgredirà questo decreto, sia estratta una trave dalla sua casa e venga innalzata perché vi sia appeso e la sua casa sia ridotta a letamaio per questo motivo."],
[6012,"Il Dio che ha fatto abitare lì il suo nome, rovesci qualsiasi re o popolo che osi stendere la propria mano per trasgredire e distruggere quel tempio di Dio che è a Gerusalemme. Io, Dario, ho emanato quest'ordine: sia eseguito integralmente\"."],
[6013,"Allora Tattenai, governatore dell'Oltrefiume, Setar-Boznai e i loro colleghi, fecero integralmente come il re Dario aveva comandato."],
[6014,"Gli anziani dei Giudei continuarono a costruire e fecero progressi, grazie alla profezia del profeta Aggeo e di Zaccaria, figlio di Iddo. Portarono a compimento la costruzione per ordine del Dio d'Israele e per ordine di Ciro, di Dario e di Artaserse, re di Persia."],
[6015,"Si terminò questo tempio per il giorno tre del mese di Adar, nell'anno sesto del regno del re Dario."],
[6016,"Gli Israeliti, i sacerdoti, i leviti e gli altri rimpatriati celebrarono con gioia la dedicazione di questo tempio di Dio;"],
[6017,"offrirono per la dedicazione di questo tempio di Dio cento tori, duecento arieti, quattrocento agnelli e dodici capri come sacrifici espiatori per tutto Israele, secondo il numero delle tribù d'Israele."],
[6018,"Stabilirono i sacerdoti secondo le loro classi e i leviti secondo i loro turni per il servizio di Dio a Gerusalemme, come è scritto nel libro di Mosè."],
[6019,"I rimpatriati celebrarono la Pasqua il quattordici del primo mese."],
[6020,"Infatti i sacerdoti e i leviti si erano purificati tutti insieme, come un sol uomo: tutti erano puri. Così immolarono la Pasqua per tutti i rimpatriati, per i loro fratelli sacerdoti e per se stessi."],
[6021,"Ne mangiarono gli Israeliti che erano tornati dall'esilio e quanti si erano separati dalla contaminazione del popolo del paese, unendosi a loro per cercare il Signore, Dio d'Israele."],
[6022,"Celebrarono con gioia la festa degli Azzimi per sette giorni, poiché il Signore li aveva colmati di gioia, avendo piegato a loro favore il cuore del re d'Assiria, per rafforzare le loro mani nel lavoro per il tempio di Dio, il Dio d'Israele."],
[7001,"Dopo questi avvenimenti, sotto il regno di Artaserse, re di Persia, Esdra, figlio di Seraià, figlio di Azaria, figlio di Chelkia,"],
[7002,"figlio di Sallum, figlio di Sadoc, figlio di Achitub,"],
[7003,"figlio di Amaria, figlio di Azaria, figlio di Meraiot,"],
[7004,"figlio di Zerachia, figlio di Uzzì, figlio di Bukkì,"],
[7005,"figlio di Abisua, figlio di Finees, figlio di Eleazaro, figlio di Aronne, sommo sacerdote,"],
[7006,"Esdra dunque partì da Babilonia. Egli era uno scriba esperto nella legge di Mosè, data dal Signore, Dio d'Israele. Poiché la mano del Signore, suo Dio, era su di lui, il re aveva esaudito ogni sua richiesta."],
[7007,"Partirono per Gerusalemme alcuni Israeliti, sacerdoti, leviti, cantori, portieri e oblati, nel settimo anno del re Artaserse."],
[7008,"Egli arrivò a Gerusalemme nel quinto mese: era l'anno settimo del re."],
[7009,"Egli aveva fissato la partenza da Babilonia per il primo giorno del primo mese, e il primo del quinto mese arrivò a Gerusalemme, poiché la mano benevola del suo Dio era su di lui."],
[7010,"Infatti Esdra si era dedicato con tutto il cuore a studiare la legge del Signore e a praticarla e a insegnare in Israele le leggi e le norme."],
[7011,"Questa è la copia del documento che il re Artaserse consegnò a Esdra, sacerdote, scriba ed esperto nei comandamenti del Signore e nelle leggi date a Israele:"],
[7012,"\"Artaserse, re dei re, al sacerdote Esdra, scriba della legge del Dio del cielo, salute perfetta. Ora,"],
[7013,"io ordino che, nel mio regno, chiunque del popolo d'Israele, dei suoi sacerdoti e dei leviti vuole venire a Gerusalemme, venga pure con te;"],
[7014,"infatti da parte del re e dei suoi sette consiglieri tu sei inviato a fare inchiesta in Giudea e a Gerusalemme riguardo alla legge del tuo Dio che è nelle tue mani,"],
[7015,"e a portare l'argento e l'oro che il re e i suoi consiglieri inviano come offerta spontanea al Dio d'Israele che abita a Gerusalemme,"],
[7016,"e tutto l'argento e l'oro che troverai in tutta la provincia di Babilonia, insieme con le offerte spontanee che il popolo e i sacerdoti offriranno per il tempio del loro Dio a Gerusalemme."],
[7017,"Perciò con questo argento ti prenderai cura di acquistare tori, arieti, agnelli, con le loro oblazioni e le loro libagioni, e li offrirai sull'altare del tempio del vostro Dio che è a Gerusalemme."],
[7018,"Con il resto dell'argento e dell'oro farete quello che sembrerà bene fare a te e ai tuoi fratelli, secondo la volontà del vostro Dio."],
[7019,"I vasi, che ti sono stati dati per il culto del tempio del tuo Dio, rendili al Dio di Gerusalemme."],
[7020,"Il resto di quanto occorre per il tempio del tuo Dio, e che spetta a te procurare, lo procurerai a spese del tesoro del re."],
[7021,"Io, il re Artaserse, ordino a tutti i tesorieri dell'Oltrefiume: Tutto ciò che Esdra, sacerdote e scriba della legge del Dio del cielo, vi domanderà, sia fatto integralmente,"],
[7022,"fino a cento talenti d'argento, cento kor di grano, cento bat di vino, cento bat di olio e sale a volontà."],
[7023,"Quanto è prescritto dal Dio del cielo sia fatto con diligenza per il tempio del Dio del cielo, perché non venga l'ira sul regno del re e dei suoi figli."],
[7024,"E vi comunichiamo che nessuno può imporre tasse, tributi o imposte a tutti i sacerdoti, leviti, cantori, portieri, oblati e inservienti di questo tempio."],
[7025,"Quanto a te, Esdra, secondo la sapienza del tuo Dio, che tu possiedi, stabilisci magistrati e giudici che giudichino tutto il popolo dell'Oltrefiume, cioè tutti coloro che conoscono le leggi del tuo Dio, e voi dovrete istruire chi non le conosce."],
[7026,"Contro chiunque non osserverà la legge del tuo Dio e la legge del re, si faccia con sollecitudine un processo e lo si punisca con la morte o una pena corporale o un'ammenda in denaro o il carcere\"."],
[7027,"Benedetto il Signore, Dio dei padri nostri, che ha disposto così il cuore del re a glorificare il tempio del Signore che è a Gerusalemme"],
[7028,"e si è volto verso di me con amore di fronte al re, ai suoi consiglieri e a tutti i comandanti del re. Allora io mi sono sentito incoraggiato, perché la mano del Signore, mio Dio, era su di me e ho radunato alcuni capi da Israele, perché salissero con me."],
[8001,"Questi sono, con le loro indicazioni genealogiche, i capi di casato che sono partiti con me da Babilonia, sotto il regno del re Artaserse:"],
[8002,"dei figli di Finees: Ghersom; dei figli di Itamar: Daniele; dei figli di Davide: Cattus,"],
[8003,"figlio di Secania; dei figli di Paros: Zaccaria, e con lui furono registrati centocinquanta maschi;"],
[8004,"dei figli di Pacat-Moab: Elioenai, figlio di Zerachia, e con lui duecento maschi;"],
[8005,"dei figli di Zattu: Secania, figlio di Iacaziel, e con lui trecento maschi;"],
[8006,"dei figli di Adin: Ebed, figlio di Gionata, e con lui cinquanta maschi;"],
[8007,"dei figli di Elam: Isaia, figlio di Atalia, e con lui settanta maschi;"],
[8008,"dei figli di Sefatia: Zebadia, figlio di Michele, e con lui ottanta maschi;"],
[8009,"dei figli di Ioab: Abdia, figlio di Iechiel, e con lui duecentodiciotto maschi;"],
[8010,"dei figli di Banì: Selomit, figlio di Iosifia, e con lui centosessanta maschi;"],
[8011,"dei figli di Bebai: Zaccaria, figlio di Bebai, e con lui ventotto maschi;"],
[8012,"dei figli di Azgad: Giovanni, figlio di Akkatan, e con lui centodieci maschi;"],
[8013,"dei figli di Adonikam: gli ultimi, di cui ecco i nomi: Elifelet, Ieiel e Semaià, e con loro sessanta maschi;"],
[8014,"dei figli di Bigvai: Utai e Zabbud, e con loro settanta maschi."],
[8015,"Io li ho radunati presso il fiume che scorre verso Aavà. Là siamo stati accampati per tre giorni. Ho fatto una rassegna tra il popolo e i sacerdoti e non vi ho trovato nessun levita."],
[8016,"Allora ho mandato a chiamare i capi Eliezer, Ariel, Semaià, Elnatan, Iarib, Elnatan, Natan, Zaccaria, Mesullam e gli istruttori Ioiarib ed Elnatan,"],
[8017,"e li ho mandati da Iddo, capo nella località di Casifià, e ho messo loro in bocca le parole da dire a Iddo e ai suoi fratelli oblati nella località di Casifià, perché ci mandassero dei ministri per il tempio del nostro Dio."],
[8018,"Poiché la mano benefica del nostro Dio era su di noi, ci hanno mandato un uomo assennato, dei figli di Maclì, figlio di Levi, figlio d'Israele, cioè Serebia, con i suoi figli e fratelli: diciotto persone;"],
[8019,"inoltre Casabia e con lui Isaia, dei figli di Merarì, i suoi fratelli e i loro figli: venti persone,"],
[8020,"e infine degli oblati, che Davide e i capi avevano assegnato al servizio dei leviti: duecentoventi oblati. Tutti furono registrati per nome."],
[8021,"Là, presso il fiume Aavà, ho indetto un digiuno, per umiliarci davanti al nostro Dio e implorare da lui un felice viaggio per noi, i nostri bambini e tutti i nostri averi."],
[8022,"Avevo infatti vergogna di domandare al re soldati e cavalieri per difenderci lungo il cammino da un eventuale nemico, poiché avevamo detto al re: \"La mano del nostro Dio è su quanti lo cercano, per il loro bene; ma la sua potenza e la sua ira su quanti lo abbandonano\"."],
[8023,"Così abbiamo digiunato e implorato Dio per questo ed egli ci ha esaudito."],
[8024,"Quindi ho scelto dodici tra i capi dei sacerdoti: Serebia e Casabia e con loro dieci loro fratelli;"],
[8025,"ho pesato per loro l'argento, l'oro e i vasi, l'offerta per il tempio del nostro Dio fatta dal re, dai suoi consiglieri, dai suoi capi e da tutti gli Israeliti che si trovavano da quelle parti."],
[8026,"Ho pesato dunque nelle loro mani seicentocinquanta talenti d'argento, vasi d'argento per cento talenti, cento talenti d'oro,"],
[8027,"e inoltre venti coppe d'oro per mille darici e due vasi di bronzo pregiato e lucente, preziosi come l'oro."],
[8028,"Ho detto loro: \"Voi siete consacrati al Signore e i vasi sono cosa sacra; l'argento e l'oro sono offerta spontanea al Signore, Dio dei nostri padri."],
[8029,"Abbiatene cura e custoditeli, finché non li peserete davanti ai preposti dei sacerdoti e dei leviti e ai preposti di casato d'Israele a Gerusalemme, nelle stanze del tempio del Signore\"."],
[8030,"Allora i sacerdoti e i leviti presero in consegna il carico dell'argento e dell'oro e dei vasi, per portarli a Gerusalemme nel tempio del nostro Dio."],
[8031,"Il dodici del primo mese siamo partiti dal fiume Aavà per andare a Gerusalemme e la mano del nostro Dio era su di noi: egli ci ha liberato dagli assalti dei nemici e dei briganti lungo il cammino."],
[8032,"Siamo arrivati a Gerusalemme e ci siamo rimasti tre giorni."],
[8033,"Il quarto giorno è stato pesato l'argento, l'oro e i vasi nel tempio del nostro Dio nelle mani del sacerdote Meremot, figlio di Uria, e con lui vi era Eleazaro, figlio di Finees, e con loro i leviti Iozabad, figlio di Giosuè, e Noadia, figlio di Binnui;"],
[8034,"il numero e il peso corrispondeva in tutto e il peso totale fu registrato in quel momento."],
[8035,"Quelli che venivano dall'esilio, i deportati, offrirono olocausti al Dio d'Israele: dodici tori per tutto Israele, novantasei arieti, settantasette agnelli, dodici capri per il peccato, tutto come olocausto al Signore."],
[8036,"Quindi consegnarono i decreti del re ai satrapi del re e ai governatori dell'Oltrefiume, i quali iniziarono a proteggere il popolo e il tempio di Dio."],
[9001,"Terminate queste cose, sono venuti da me i preposti per dirmi: \"Il popolo d'Israele, i sacerdoti e i leviti non si sono separati dalle popolazioni locali, per quanto riguarda i loro abomini, cioè da Cananei, Ittiti, Perizziti, Gebusei, Ammoniti, Moabiti, Egiziani, Amorrei,"],
[9002,"ma hanno preso in moglie le loro figlie per sé e per i loro figli: così hanno mescolato la stirpe santa con le popolazioni locali, e la mano dei preposti e dei governatori è stata la prima in questa prevaricazione\"."],
[9003,"All'udire questa parola, stracciai il mio vestito e il mio mantello, mi strappai i capelli del capo e la barba e mi sedetti costernato."],
[9004,"Quanti tremavano per i giudizi del Dio d'Israele su questa prevaricazione dei rimpatriati, si radunarono presso di me. Ma io sedevo costernato, fino all'offerta della sera."],
[9005,"All'offerta della sera mi alzai dal mio stato di prostrazione e, con il vestito e il mantello laceri, caddi in ginocchio e stesi le mani al Signore, mio Dio, e"],
[9006,"dissi: \"Mio Dio, sono confuso, ho vergogna di alzare la faccia verso di te, mio Dio, poiché le nostre iniquità si sono moltiplicate fin sopra la nostra testa; la nostra colpa è grande fino al cielo."],
[9007,"Dai giorni dei nostri padri fino ad oggi noi siamo stati molto colpevoli, e per le nostre colpe noi, i nostri re, i nostri sacerdoti siamo stati messi in potere di re stranieri, in preda alla spada, alla prigionia, alla rapina, al disonore, come avviene oggi."],
[9008,"Ma ora, per un po' di tempo, il Signore, nostro Dio, ci ha fatto una grazia: di lasciarci un resto e darci un asilo nel suo luogo santo, e così il nostro Dio ha fatto brillare i nostri occhi e ci ha dato un po' di sollievo nella nostra schiavitù."],
[9009,"Infatti noi siamo schiavi; ma nella nostra schiavitù il nostro Dio non ci ha abbandonati: ci ha resi graditi ai re di Persia, per conservarci la vita ed erigere il tempio del nostro Dio e restaurare le sue rovine, e darci un riparo in Giuda e a Gerusalemme."],
[9010,"Ma ora, o nostro Dio, che cosa possiamo dire dopo questo? Infatti abbiamo abbandonato i tuoi comandamenti,"],
[9011,"che tu avevi dato per mezzo dei tuoi servi, i profeti, dicendo: \"La terra che voi andate a prendere in eredità è una terra contaminata, a causa delle contaminazioni dei popoli indigeni, e delle loro nefandezze, che l'hanno colmata da un capo all'altro con le loro impurità."],
[9012,"E allora non dovete dare le vostre figlie ai loro figli, né prendere le loro figlie per i vostri figli; non dovrete mai contribuire alla loro prosperità e al loro benessere, così diventerete forti voi e potrete mangiare i beni della terra e lasciare un'eredità ai vostri figli per sempre\"."],
[9013,"Dopo ciò che è venuto su di noi a causa delle nostre cattive azioni e per le nostre grandi mancanze, benché tu, nostro Dio, sia stato indulgente nonostante la nostra colpa e ci abbia dato superstiti come questi,"],
[9014,"potremmo forse noi tornare a violare i tuoi comandamenti e a imparentarci con questi popoli abominevoli? Non ti adireresti contro di noi fino a sterminarci, senza lasciare né resto né superstite?"],
[9015,"Signore, Dio d'Israele, tu sei giusto, poiché ci è stato lasciato un resto, come oggi: eccoci davanti a te con le nostre mancanze, anche se per questo non potremmo reggere davanti a te!\"."],
[10001,"Mentre Esdra pregava e faceva questa confessione piangendo, prostrato davanti al tempio di Dio, si riunì intorno a lui un'assemblea molto numerosa d'Israeliti: uomini, donne e fanciulli; e il popolo piangeva a dirotto."],
[10002,"Allora Secania, figlio di Iechiel, uno dei figli di Elam, prese la parola e disse a Esdra: \"Abbiamo prevaricato contro il nostro Dio, sposando donne straniere, prese dalle popolazioni del luogo. Orbene, a questo riguardo c'è ancora una speranza per Israele."],
[10003,"Facciamo dunque un patto con il nostro Dio, impegnandoci a rimandare tutte le donne e i figli nati da loro, secondo la volontà del mio signore e rispettando il comando del nostro Dio. Si farà secondo la legge!"],
[10004,"Àlzati, perché a te è affidato questo compito. Noi saremo con te; sii forte e mettiti all'opera!\"."],
[10005,"Allora Esdra si alzò e fece giurare ai capi dei sacerdoti e dei leviti e a tutto Israele che avrebbero agito secondo quelle parole; essi giurarono."],
[10006,"Esdra quindi si alzò da dove si trovava, davanti al tempio di Dio, e andò nella camera di Giovanni, figlio di Eliasib, e vi andò senza prendere cibo né bere acqua, perché era in lutto a causa della prevaricazione dei rimpatriati."],
[10007,"Poi in Giuda e a Gerusalemme si comunicò a tutti i rimpatriati di radunarsi a Gerusalemme:"],
[10008,"se qualcuno non fosse venuto entro tre giorni, secondo la disposizione dei preposti e degli anziani, sarebbero stati votati allo sterminio tutti i suoi beni ed egli stesso sarebbe stato escluso dalla comunità dei rimpatriati."],
[10009,"Allora tutti gli uomini di Giuda e di Beniamino si radunarono a Gerusalemme entro tre giorni; si era al nono mese, il venti del mese. Tutto il popolo stava nella piazza del tempio di Dio, tremante per questo evento e per la gran pioggia."],
[10010,"Allora il sacerdote Esdra si levò e disse loro: \"Voi avete prevaricato sposando donne straniere: così avete accresciuto le mancanze d'Israele."],
[10011,"Ma ora rendete lode al Signore, Dio dei vostri padri, e fate la sua volontà, separandovi dalle popolazioni del paese e dalle donne straniere\"."],
[10012,"Tutta l'assemblea rispose a gran voce: \"Sì! Dobbiamo fare come tu ci hai detto."],
[10013,"Ma il popolo è numeroso e siamo al tempo delle piogge; non è possibile restare all'aperto. D'altra parte non è lavoro di un giorno o di due, perché siamo in molti ad aver peccato in questa materia."],
[10014,"I nostri preposti stiano a rappresentare tutta l'assemblea; e tutti quelli delle nostre città che hanno sposato donne straniere vengano in date determinate e con gli anziani della città, ogni città con i suoi giudici, finché non sia allontanata da noi l'ira ardente del nostro Dio, causata da questa situazione\"."],
[10015,"Soltanto Gionata, figlio di Asael, e Iaczia, figlio di Tikva, si opposero, appoggiati da Mesullam e dal levita Sabbetai."],
[10016,"I rimpatriati fecero come si era detto. Furono scelti il sacerdote Esdra e alcuni capi di casato, secondo il loro casato, tutti designati per nome. Essi iniziarono le sedute il primo giorno del decimo mese per esaminare la questione"],
[10017,"e terminarono con tutti gli uomini che avevano sposato donne straniere il primo giorno del primo mese."],
[10018,"Tra i figli dei sacerdoti, che avevano sposato donne straniere, si trovarono: dei figli di Giosuè, figlio di Iosadak, e tra i suoi fratelli: Maasia, Eliezer, Iarib e Godolia;"],
[10019,"essi si impegnarono a rimandare le loro donne e offrirono un ariete come sacrificio di riparazione per le loro mancanze;"],
[10020,"dei figli di Immer: Anani e Zebadia;"],
[10021,"dei figli di Carim: Maasia, Elia, Semaià, Iechiel e Ozia;"],
[10022,"dei figli di Pascur: Elioenai, Maasia, Ismaele, Natanel, Iozabad ed Eleasà;"],
[10023,"dei leviti: Iozabad, Simei, Kelaià, chiamato anche Kelità, Petachia, Giuda ed Eliezer;"],
[10024,"dei cantori: Eliasib; dei portieri: Sallum, Telem e Urì."],
[10025,"Quanto agli Israeliti:  dei figli di Paros: Ramia, Izzia, Malchia, Miamin, Eleazaro, Malchia e Benaià;"],
[10026,"dei figli di Elam: Mattania, Zaccaria, Iechiel, Abdì, Ieremot ed Elia;"],
[10027,"dei figli di Zattu: Elioenai, Eliasib, Mattania, Ieremot, Zabad e Azizà;"],
[10028,"dei figli di Bebai: Giovanni, Anania, Zabbai e Atlai;"],
[10029,"dei figli di Banì: Mesullam, Malluc, Adaià, Iasub, Seal e Ieramot;"],
[10030,"dei figli di Pacat-Moab: Adna, Chelal, Benaià, Maasia, Mattania, Besalel, Binnui e Manasse;"],
[10031,"dei figli di Carim: Eliezer, Issia, Malchia, Semaià, Simeone,"],
[10032,"Beniamino, Malluc, Semaria;"],
[10033,"dei figli di Casum: Mattenai, Mattattà, Zabad, Elifelet, Ieremai, Manasse e Simei;"],
[10034,"dei figli di Banì: Maadai, Amram, Uel,"],
[10035,"Benaià, Bedia, Cheluu,"],
[10036,"Vania, Meremot, Eliasib,"],
[10037,"Mattania, Mattenai e Iaasai;"],
[10038,"dei figli di Binnui: Simei,"],
[10039,"Selemia, Natan, Adaià,"],
[10040,"Macnadbai,  Sasai, Sarai,"],
[10041,"Azarel, Selemia, Semaria,"],
[10042,"Sallum, Amaria, Giuseppe;"],
[10043,"dei figli di Nebo: Ieiel, Mattitia, Zabad, Zebinà, Iaddai, Gioele, Benaià."],
[10044,"Tutti questi avevano sposato donne straniere e rimandarono le donne insieme con i figli."]
])
