Bib.ret([
[1001.01,"Nel secondo anno di regno del grande re Artaserse, il giorno primo di Nisan, Mardocheo, figlio di Giairo, figlio di Simei, figlio di Kis, della tribù di Beniamino, ebbe in sogno una visione."],
[1001.02,"Egli era [un Giudeo che abitava nella città di Susa,]  un uomo ragguardevole, che prestava servizio alla corte del re"],
[1001.03,"e proveniva dal gruppo degli esuli che Nabucodonosor, re di Babilonia, aveva deportato da Gerusalemme con Ieconia, re della Giudea."],
[1001.04,"Questo fu il suo sogno: ecco, grida e tumulto, tuoni e terremoto, sconvolgimenti sulla terra."],
[1001.05,"Ed ecco: due enormi draghi avanzarono, tutti e due pronti alla lotta, [e risuonò potente il loro grido.]"],
[1001.06,"[Al loro grido ogni nazione si preparò alla guerra, per combattere contro il popolo dei giusti.]"],
[1001.07,"Ecco, un giorno di tenebre e di caligine! Tribolazione e angustia, afflizione e grandi sconvolgimenti sulla terra! ["],
[1001.08,"Tutta la nazione dei giusti rimase sconvolta: essi, temendo la propria rovina, si prepararono a morire] e levarono a Dio il loro grido."],
[1001.09,"Ma dal loro grido, come da una piccola fonte, sorse un grande fiume con acque abbondanti."],
[1001.11,"Apparvero la luce e il sole: gli umili furono esaltati e divorarono i superbi."],
[1001.12,"Mardocheo allora si svegliò: aveva visto questo sogno e quello che Dio aveva deciso di fare; in cuor suo continuava a ripensarvi fino a notte, cercando di  comprenderlo in ogni suo particolare."],
[1001.13,"[Mardocheo alloggiava alla corte con Gabatà e Tarra, i due eunuchi del re che custodivano la corte."],
[1001.14,"Intese i loro ragionamenti, indagò sui loro disegni e venne a sapere che quelli si preparavano a mettere le mani sul re Artaserse. Allora ne avvertì il re."],
[1001.15,"Il re sottopose i due eunuchi a un interrogatorio: essi confessarono e furono tolti di mezzo."],
[1001.16,"Poi il re fece scrivere questi fatti nelle cronache e anche Mardocheo li mise per iscritto."],
[1001.17,"Il re costituì Mardocheo funzionario della corte e gli fece regali in compenso di queste cose."],
[1001.18,"Ma vi era anche Aman, figlio di Amadata, il Bugeo, che era molto stimato presso il re e cercò il modo di fare del male a Mardocheo e al suo popolo, per questa faccenda che riguardava i due eunuchi del re.]"],
[1001.19,"Dopo queste cose, al tempo di Artaserse - quell'Artaserse che regnava dall'India sopra centoventisette province -,"],
[1002,"proprio in quel tempo il re Artaserse, che regnava nella città di Susa,"],
[1003,"l'anno terzo del suo regno fece un banchetto per gli amici e per quelli delle altre nazionalità, per i nobili dei Persiani e i dei Medi e per i prefetti delle province."],
[1004,"Dopo aver mostrato loro le ricchezze del suo regno e il fasto attraente della sua ricchezza per centoottanta giorni,"],
[1005,"quando si compirono i giorni delle nozze, il re fece un banchetto per i rappresentanti delle nazioni che si trovavano nella città, per sei giorni, nella sala della reggia."],
[1006,"La sala era adornata con drappi di lino delicato e pregiato, appesi a cordoni di lino color porpora, fissati a ganci d'oro e d'argento, su colonne di marmo pario e di pietra. I divani erano d'oro e d'argento, sopra un pavimento di pietra verde smeraldo e di madreperla e di marmo pario; vi erano inoltre tappeti con ricami variegati e rose disposte in circolo."],
[1007,"Per bere c'erano coppe d'oro e d'argento, come pure un piccolo calice di turchese, del valore di trentamila talenti. Il vino era abbondante e dolce e lo stesso re ne beveva."],
[1008,"Si poteva bere senza limiti: così infatti aveva voluto il re, ordinando ai camerieri di soddisfare il desiderio suo e degli altri."],
[1009,"Anche Vasti, la regina, tenne un banchetto per le donne nella stessa reggia di Artaserse."],
[1010,"Il settimo giorno il re, euforico per il vino, ordinò ad Aman, Bazan, Tarra, Borazè, Zatoltà, Abatazà, Tarabà, i sette eunuchi che erano al servizio del re Artaserse,"],
[1011,"di far venire davanti a lui la regina per intronizzarla, ponendole sul capo il diadema, e per mostrare ai principi e alle nazioni la sua bellezza: era infatti molto bella."],
[1012,"Ma la regina Vasti rifiutò di andare con gli eunuchi. Il re ne fu addolorato e irritato"],
[1013,"e disse ai suoi amici: \"Così e così ha parlato Vasti: giudicate, dunque, secondo la legge e il diritto\"."],
[1014,"Si fecero avanti Archeseo e Sarsateo e Malesear, principi dei Persiani e dei Medi, che erano più vicini al re e che, primi, sedevano accanto al re,"],
[1015,"e gli espressero il proprio parere su che cosa si dovesse fare alla regina Vasti, secondo le leggi, perché non aveva eseguito l'ordine datole dal re Artaserse per mezzo degli eunuchi."],
[1016,"Mucheo disse in presenza del re e dei principi: \"La regina Vasti ha mancato non solo nei confronti del re, ma anche nei confronti di tutti i principi e i capi del re"],
[1017,"- infatti costui aveva riferito loro le parole della regina e come ella aveva risposto al re - e, come ella ha risposto al re Artaserse,"],
[1018,"così oggi le altre principesse dei capi dei Persiani e dei Medi, avendo udito ciò che ella ha detto al re, oseranno disprezzare allo stesso modo i loro mariti."],
[1019,"Se dunque sembra bene al re, sia emanato un decreto reale, scritto secondo le leggi dei Medi e dei Persiani e irrevocabile, secondo il quale la regina non possa più comparire davanti a lui, e il re conferisca la dignità a una donna migliore di lei."],
[1020,"E l'editto emanato dal re sia fatto conoscere nel suo regno e così tutte le donne rispetteranno i loro mariti, dal più povero al più ricco\"."],
[1021,"La proposta piacque al re e ai principi. Il re fece come aveva detto Mucheo:"],
[1022,"mandò lettere a tutto il regno, a ogni provincia secondo la sua lingua, in modo che i mariti fossero rispettati nelle loro case."],
[2001,"Dopo questi fatti, l'ira del re si placò ed egli non si ricordò più di Vasti, avendo presente quello che lei aveva detto e come egli l'aveva ormai condannata."],
[2002,"Dissero allora i servi del re: \"Si cerchino per il re fanciulle incorrotte e belle."],
[2003,"E in tutte le province del suo regno il re dia incarico ai governatori locali perché siano scelte fanciulle vergini e belle; siano portate nella città di Susa, nell'harem, e siano consegnate all'eunuco del re che è il custode delle donne e siano dati loro unguenti e ogni altra cosa necessaria,"],
[2004,"e la donna che piacerà al re diventi regina al posto di Vasti\". La proposta piacque al re, e così si fece."],
[2005,"Nella città di Susa c'era un Giudeo di nome Mardocheo, figlio di Giairo, figlio di Simei, figlio di Kis, della tribù di Beniamino,"],
[2006,"il quale era stato deportato da Gerusalemme quando fu ridotta in schiavitù da Nabucodonosor, re di Babilonia."],
[2007,"Egli aveva una figlia adottiva, figlia di Aminadab, fratello di suo padre, che si chiamava Ester. Quando erano morti i suoi genitori, egli l'aveva allevata per prenderla in moglie. La fanciulla era bella d'aspetto."],
[2008,"E quando il decreto del re fu pubblicato, molte fanciulle furono raccolte nella città di Susa sotto la sorveglianza di Gai; anche Ester fu condotta da Gai, custode delle donne."],
[2009,"La fanciulla gli piacque e trovò grazia presso di lui, ed egli si preoccupò di darle gli unguenti e la sua porzione di cibo, oltre alle sette fanciulle assegnate a lei dalla reggia, e usò verso di lei e le sue ancelle un trattamento di favore nell'harem."],
[2010,"Ester non disse nulla né del suo popolo né della sua stirpe, perché Mardocheo le aveva ordinato di non dirlo."],
[2011,"Mardocheo passeggiava ogni giorno lungo il cortile dell'harem, per vedere che cosa fosse accaduto a Ester."],
[2012,"Il momento di andare dal re giungeva per una fanciulla alla fine di dodici mesi, quando terminavano i giorni della preparazione. Il periodo della preparazione si svolgeva così: sei mesi per essere unta con olio di mirra e sei con spezie e unguenti femminili."],
[2013,"Allora veniva introdotta dal re, e quello che chiedeva le veniva dato per portarlo con sé dall'harem alla reggia."],
[2014,"Vi andava la sera e la mattina seguente passava nel secondo harem, dove Gai, l'eunuco del re, custodiva le donne; nessuna di loro poteva rientrare dal re, se non veniva chiamata per nome."],
[2015,"Quando per Ester, figlia di Aminadab, fratello del padre di Mardocheo, si compì il tempo di entrare dal re, ella nulla tralasciò di quello che le aveva ordinato l'eunuco, il custode delle donne; Ester infatti trovava grazia presso tutti quelli che la vedevano."],
[2016,"Ester entrò dal re Artaserse nel dodicesimo mese, chiamato Adar, l'anno settimo del suo regno."],
[2017,"Il re si innamorò di Ester: ella trovò grazia più di tutte le fanciulle e perciò egli pose su di lei la corona regale."],
[2018,"Poi il re fece un banchetto per tutti i suoi amici e i potenti per sette giorni, volendo solennizzare così le nozze di Ester; condonò pure i debiti a tutti quelli che erano sotto il suo dominio."],
[2019,"Mardocheo prestava servizio nel palazzo."],
[2020,"Ester non palesò la sua stirpe: Mardocheo infatti le aveva raccomandato di avere il timore di Dio e di osservare i suoi comandamenti, come quando stava con lui. Ester non cambiò il suo modo di vivere."],
[2021,"I due eunuchi del re, capi delle guardie del corpo, si rattristarono perché Mardocheo era stato promosso, e cercavano di uccidere il re Artaserse."],
[2022,"La cosa fu resa nota a Mardocheo, ed egli la fece conoscere ad Ester; ella rivelò al re la notizia della congiura."],
[2023,"Allora il re fece indagare riguardo ai due eunuchi e li impiccò; il re ordinò di prenderne nota negli archivi reali, in memoria e a lode dei buoni uffici di Mardocheo."],
[3001,"Dopo questi avvenimenti, il re Artaserse onorò grandemente Aman, figlio di Amadata, il Bugeo. Lo elevò in dignità e, fra tutti i suoi amici, lo faceva sedere al primo posto."],
[3002,"Tutti quelli che stavano al palazzo si prostravano davanti a lui, poiché il re aveva ordinato di fare così. Ma Mardocheo non si prostrava davanti a lui."],
[3003,"Allora quelli che stavano nel palazzo dissero a Mardocheo: \"Mardocheo, perché non ascolti i comandi del re?\"."],
[3004,"Essi glielo dicevano giorno dopo giorno, ma egli non li ascoltava. Allora fecero presente ad Aman che Mardocheo trasgrediva gli ordini del re. Mardocheo inoltre aveva rivelato loro di essere un Giudeo."],
[3005,"Ma Aman, accortosi che Mardocheo non si prostrava davanti a lui, si indignò grandemente"],
[3006,"e decise di sterminare tutti i Giudei che si trovavano sotto il dominio di Artaserse."],
[3007,"Fece un editto nell'anno dodicesimo del regno di Artaserse; tirò a sorte il giorno e il mese, per sterminare in un solo giorno il popolo di Mardocheo. La sorte cadde sul quattordicesimo giorno del mese di Adar."],
[3008,"Allora disse al re Artaserse: \"C'è un popolo disperso tra le nazioni in tutto il tuo regno, le cui leggi differiscono da quelle di tutte le altre nazioni; essi disobbediscono alle leggi del re e non è conveniente che il re glielo permetta."],
[3009,"Se piace al re, dia ordine di ucciderli, e io assegnerò al tesoro del re diecimila talenti d'argento\"."],
[3010,"Il re, preso il suo anello, lo dette in mano ad Aman, per mettere il sigillo sui decreti contro i Giudei."],
[3011,"Il re disse ad Aman: \"Tieni pure il denaro, e tratta questo popolo come vuoi tu\"."],
[3012,"Nel tredicesimo giorno del primo mese furono chiamati gli scribi e, come aveva ordinato Aman, scrissero ai capi e ai governatori di ogni provincia, dall'India fino all'Etiopia, a centoventisette province, e ai capi delle nazioni, secondo la loro lingua, a nome del re Artaserse."],
[3013.01,"Questa è la copia della lettera:  \"Il grande re Artaserse ai governatori delle centoventisette province, dall'India all'Etiopia, e ai funzionari loro subordinati scrive quanto segue:"],
[3013.02,"Essendo io al comando di molte nazioni e avendo il dominio di tutto il mondo, non volendo abusare della grandezza del potere, ma volendo governare sempre con moderazione e con dolcezza, mi sono proposto di rendere quieta la vita dei sudditi e di assicurare un regno tranquillo e percorribile fino alle frontiere, per far rifiorire la pace sospirata da tutti gli uomini."],
[3013.029999999999999,"Dopo aver chiesto ai miei consiglieri come si potesse attuare tutto questo, Aman, distinto presso di noi per prudenza, eccellente per inalterata devozione e sicura fedeltà ed elevato alla seconda dignità del regno,"],
[3013.039999999999999,"ci ha avvertiti che in mezzo a tutte le razze che vi sono nel mondo si è mescolato un popolo ostile il quale, vivendo con leggi diverse da quelle di ogni altra nazione, trascura sempre i decreti del re, così da compromettere la pace delle nazioni da noi consolidata."],
[3013.050000000000001,"Considerando dunque che questa nazione è l'unica ad essere in continuo contrasto con ogni essere umano, differenziandosi per uno strano regime di leggi, e che, ostile ai nostri interessi, compie le peggiori malvagità e ostacola la stabilità del regno,"],
[3013.06,"abbiamo ordinato che le persone a voi segnalate nei rapporti scritti da Aman, incaricato dei nostri affari pubblici e da noi trattato come un secondo padre, tutte, con le mogli e i figli, siano radicalmente sterminate con la spada dei loro avversari, senz'alcuna pietà né perdono, il quattordici del dodicesimo mese dell'anno corrente, cioè Adar,"],
[3013.07,"cosicché questi nostri oppositori di ieri e di oggi, precipitando violentemente negli inferi in un solo giorno, ci assicurino definitivamente per l'avvenire un governo stabile e tranquillo*\"."],
[3013.9,"Le lettere furono mandate per mezzo di corrieri nel regno di Artaserse, perché in un solo giorno del dodicesimo mese, chiamato Adar, fosse sterminata la stirpe dei Giudei e si saccheggiassero i loro beni."],
[3014,"Le copie delle lettere furono pubblicate in ogni provincia e a tutte le nazioni fu ordinato di stare pronti per quel giorno."],
[3015,"L'applicazione fu sollecitata anche nella città di Susa e, mentre il re e Aman si davano a bere smodatamente, la città era costernata.*"],
[4001,"Quando Mardocheo seppe quello che era accaduto, si stracciò le vesti, indossò un sacco e si cosparse di cenere. Precipitatosi nella piazza della città, gridava a gran voce: \"Viene distrutto un popolo che non ha fatto nulla di male\"."],
[4002,"Venne fino alla porta del re e si fermò; infatti non gli era consentito entrare nel palazzo portando sacco e cenere."],
[4003,"In ogni provincia in cui erano state pubblicate le lettere, c'erano grida e lamenti e grande afflizione tra i Giudei, i quali si stendevano sul sacco e sulla cenere."],
[4004,"Entrarono le ancelle e gli eunuchi della regina e le parlarono. All'udire quel che era accaduto, rimase sconvolta e mandò a vestire Mardocheo e a togliergli il sacco; ma egli non acconsentì."],
[4005,"Allora Ester chiamò il suo eunuco Acrateo, che stava al suo servizio, e lo mandò a chiedere informazioni precise a Mardocheo. ["],
[4006,"Atac si recò da Mardocheo sulla piazza della città, davanti alla porta del re.]"],
[4007,"Mardocheo gli fece conoscere quel che era accaduto e la promessa che Aman aveva fatto al re riguardo ai diecimila talenti per il tesoro, allo scopo di sterminare i Giudei."],
[4008,"E gli diede la copia dell'editto promulgato nella città di Susa e riguardante la loro distruzione, perché la mostrasse a Ester; gli disse di ordinarle di entrare dal re, per domandargli grazia e intercedere a favore del popolo. \"Ricordati - aggiunse - dei giorni in cui eri povera, quando eri nutrita dalle mie mani, giacché Aman, il quale ha avuto il secondo posto dopo il re, ha parlato contro di noi per farci morire. Invoca il Signore e parla al re in favore nostro, perché ci liberi dalla morte\"."],
[4009,"Acrateo entrò e le riferì tutte queste parole."],
[4010,"Ed Ester disse ad Acrateo: \"Va' da Mardocheo e digli:"],
[4011,"\"Tutte le nazioni dell'impero sanno che chiunque, uomo o donna, entri dal re, nel palazzo interno, senza essere chiamato, non avrà scampo; solo colui sul quale il re avrà steso il suo scettro d'oro sarà salvo. E io non sono più stata chiamata a entrare dal re già da trenta giorni\"\"."],
[4012,"Acrateo riferì a Mardocheo tutte queste parole di Ester."],
[4013,"Mardocheo disse ad Acrateo: \"Va' a dirle: \"Ester, non dire a te stessa che tu sola potrai salvarti nel regno, fra tutti i Giudei."],
[4014,"Perché se tu ti rifiuti in questa circostanza, da un'altra parte verranno aiuto e protezione per i Giudei. Tu e la casa di tuo padre perirete. Chi sa che tu non sia diventata regina proprio per questa circostanza?\"\"."],
[4015,"Ester mandò da Mardocheo l'uomo che era venuto da lei e gli fece dire:"],
[4016,"\"Va' e raduna i Giudei che abitano a Susa e digiunate per me: per tre giorni e tre notti non mangiate e non bevete. Anch'io e le mie ancelle digiuneremo. Allora, contravvenendo alla legge, entrerò dal re, anche se dovessi morire\"."],
[4017.010000000000002,"[Poi pregò il Signore, ricordando tutte le gesta del Signore, e disse:]"],
[4017.02,"\"Signore, Signore, re che domini l'universo, tutte le cose sono sottoposte al tuo potere e non c'è nessuno che possa opporsi a te nella tua volontà di salvare Israele."],
[4017.030000000000001,"Tu hai fatto il cielo e la terra e tutte le meraviglie che si trovano sotto il firmamento. Tu sei il Signore di tutte le cose e non c'è nessuno che possa resistere a te, Signore."],
[4017.039999999999999,"[Tu conosci tutto; tu sai, Signore, che non per orgoglio, non per superbia né per vanagloria ho fatto questo gesto, di non prostrarmi davanti al superbo Aman, perché avrei anche baciato la pianta dei suoi piedi per la salvezza d'Israele."],
[4017.050000000000001,"Ma ho fatto questo per non porre la gloria di un uomo al di sopra della gloria di Dio; non mi prostrerò mai davanti a nessuno se non davanti a te, che sei il mio Signore, e non farò così per superbia.]"],
[4017.059999999999999,"Ora, Signore Dio, re, Dio di Abramo*, risparmia il tuo popolo! Perché guardano a noi per distruggerci e desiderano ardentemente far perire quella che è la tua eredità [dai tempi antichi]."],
[4017.07,"Non trascurare il tuo possesso che hai redento per te dal paese d'Egitto."],
[4017.079999999999998,"Ascolta la mia preghiera e sii propizio alla tua eredità; cambia il nostro lutto in gioia, perché, vivi, possiamo cantare inni al tuo nome, Signore, e non far scomparire quelli che ti lodano con la loro bocca\"."],
[4017.09,"Tutti gli Israeliti gridavano con tutte le loro forze, perché la morte stava davanti ai loro occhi."],
[4017.100000000000001,"Anche la regina Ester cercò rifugio presso il Signore, presa da un'angoscia mortale. Si tolse le vesti di lusso e indossò gli abiti di miseria e di lutto; invece dei superbi profumi si riempì la testa di ceneri [e di immondizie]. Umiliò duramente *il suo corpo [e, con i capelli sconvolti, coprì ogni sua parte che prima soleva ornare a festa. Poi supplicò il Signore e disse:] ["],
[4017.109999999999999,"\"Mio Signore, nostro re, tu sei l'unico! Vieni in aiuto a me che sono sola e non ho altro soccorso all'infuori di te, perché un grande pericolo mi sovrasta."],
[4017.120000000000001,"Io ho sentito fin dalla mia nascita, in seno alla mia famiglia, che tu, Signore, hai preso Israele tra tutte le nazioni e i nostri padri tra tutti i loro antenati come tua eterna eredità, e hai fatto per loro tutto quello che avevi promesso."],
[4017.129999999999999,"Ma ora abbiamo peccato contro di te e ci hai consegnato nelle mani dei nostri nemici, perché abbiamo dato gloria ai loro dei. Tu sei giusto, Signore!"],
[4017.140000000000001,"Ma ora non si sono accontentati dell'amarezza della nostra schiavitù: hanno anche posto le mani sulle mani dei loro idoli, giurando di abolire il decreto della tua bocca, di sterminare la tua eredità, di chiudere la bocca di quelli che ti lodano e spegnere la gloria del tuo tempio e il tuo altare,"],
[4017.149999999999999,"di aprire invece la bocca delle nazioni per lodare gli idoli vani e proclamare per sempre la propria ammirazione per un re mortale."],
[4017.16,"Non consegnare, Signore, il tuo scettro a quelli che neppure esistono. Non permettere che ridano della nostra caduta; ma volgi contro di loro questi loro progetti e colpisci con un castigo esemplare chi è a capo dei nostri persecutori."],
[4017.170000000000002,"Ricordati, Signore, manifestati nel giorno della nostra afflizione e da' a me coraggio, o re degli dei e dominatore di ogni potere."],
[4017.18,"Metti nella mia bocca una parola ben misurata di fronte al leone e volgi il suo cuore all'odio contro colui che ci combatte, per lo sterminio suo e di coloro che sono d'accordo con lui."],
[4017.190000000000001,"Quanto a noi, salvaci con la tua mano e vieni in mio aiuto, perché sono sola e non ho altri che te, Signore!"],
[4017.199999999999999,"Tu hai conoscenza di tutto e sai che io odio la gloria degli empi e detesto il letto dei non circoncisi e di qualunque straniero."],
[4017.210000000000001,"Tu sai che mi trovo nella necessità e che detesto l'insegna della mia alta carica, che cinge il mio capo nei giorni in cui devo comparire in pubblico; la detesto come un panno immondo e non la porto nei giorni in cui mi tengo appartata."],
[4017.219999999999999,"La tua serva non ha mangiato alla tavola di Aman; non ha onorato il banchetto del re né ha bevuto il vino delle libagioni."],
[4017.23,"La tua serva, da quando ha cambiato condizione fino ad oggi, non ha gioito, se non in te, Signore, Dio di Abramo."],
[4017.239999999999998,"O Dio, che su tutti eserciti la forza, ascolta la voce dei disperati, liberaci dalla mano dei malvagi e libera me dalla mia angoscia!\".]"],
[4017.899999999999999,"Mardocheo andò e fece tutto quello che Ester gli aveva ordinato."],
[5001.01,"Fattasi splendida, invocò quel Dio che su tutti veglia e tutti salva, e prese con sé due ancelle. Su di una si appoggiava con apparente mollezza, mentre l'altra la seguiva sollevando il manto di lei."],
[5001.02,"Era rosea nel fiore della sua bellezza: il suo viso era lieto, come ispirato a benevolenza, ma il suo cuore era oppresso dalla paura."],
[5001.03,"Attraversate tutte le porte, si fermò davanti al re. Egli stava seduto sul suo trono regale e rivestiva i suoi ornamenti ufficiali: era tutto splendente di oro e di pietre preziose e aveva un aspetto che incuteva paura*."],
[5001.04,"Alzato il viso, [che la sua maestà rendeva fiammeggiante, al culmine della collera la guardò.] La regina cadde a terra, in un attimo di svenimento, mutò colore e si curvò sulla testa dell'ancella che l'accompagnava."],
[5001.05,"[Dio]  volse a dolcezza l'animo del re: ansioso, balzò dal trono, la prese tra le braccia, fino a quando ella non si fu rialzata, e la confortava con parole rassicuranti, dicendole:"],
[5001.0600000000000001,"\"[Che c'è, Ester?] Io sono tuo fratello; coraggio, tu non morirai, perché il nostro decreto è solo per la gente comune. Avvicinati!\"."],
[5001.8999999999999999,"Il terzo giorno, quando ebbe finito di pregare, ella si tolse gli abiti servili e si rivestì di quelli sontuosi."],
[5002.0099999999999998,"Gli disse: \"Ti ho visto, signore, come un angelo di Dio e il mio cuore è rimasto sconvolto per timore della tua gloria: tu sei ammirevole, signore, e il tuo volto è pieno d'incanto\"."],
[5002.02,"Mentre parlava, cadde svenuta; il re si turbò e tutti i suoi servi cercavano di rincuorarla."],
[5002.8999999999999999,"Alzato lo scettro d'oro, lo posò sul collo di lei, la baciò e le disse: \"Parlami!\"."],
[5003,"Allora il re le disse: \"Che cosa vuoi, Ester, e qual è la tua richiesta? Fosse pure metà del mio regno, sarà tua\"."],
[5004,"Ester rispose: \"Oggi è un giorno speciale per me: se così piace al re, venga egli con Aman al banchetto che oggi io darò\"."],
[5005,"Disse il re: \"Fate venire presto Aman, per compiere quello che Ester ha detto\". E ambedue vennero al banchetto di cui aveva parlato Ester."],
[5006,"Mentre si beveva, il re rivolto a Ester disse: \"Che cosa c'è, regina Ester? Ti sarà concesso tutto quello che chiedi\"."],
[5007,"Rispose: \"Ecco la mia domanda e la mia richiesta:"],
[5008,"se ho trovato grazia davanti al re, venga anche domani con Aman al banchetto che io darò per loro, e domani farò come ho fatto oggi\"."],
[5009,"Aman era uscito dal re, contento, euforico; ma quando nel cortile della reggia vide Mardocheo, il Giudeo, si adirò fortemente."],
[5010,"Tornato a casa sua, chiamò gli amici e Zosara, sua moglie."],
[5011,"Mostrò loro le sue ricchezze e il potere del quale il re l'aveva investito: gli aveva dato il primo posto e il governo del regno."],
[5012,"Disse Aman: \"Al banchetto la regina non ha invitato altri che me insieme al re, e io sono invitato per domani."],
[5013,"Ma questo non mi piace, fin quando vedrò Mardocheo, il Giudeo, nel cortile della reggia\"."],
[5014,"Zosara, sua moglie, e gli amici gli dissero: \"Fa' preparare un palo alto cinquanta cubiti e domani mattina dì al re di farvi impiccare Mardocheo; poi tu va' al banchetto con il re e stai allegro\". La cosa piacque ad Aman, e si preparò il palo."],
[6001,"Quella notte il Signore tolse il sonno al re, che perciò disse al suo precettore di portargli il libro delle memorie, le cronache, e di dargliene lettura."],
[6002,"Egli vi trovò scritto, riguardo a Mardocheo, che egli aveva riferito al re che due eunuchi del re, nel fare la guardia, avevano cercato di aggredire Artaserse."],
[6003,"Disse allora il re: \"Quale onore o favore abbiamo fatto a Mardocheo?\". I servi del re risposero: \"Non hai fatto nulla per lui\"."],
[6004,"Mentre il re veniva informato circa la benevolenza di Mardocheo, ecco Aman nel cortile della reggia. Allora il re disse: \"Chi c'è nel cortile?\". Aman era venuto per dire al re di fare impiccare Mardocheo al palo che egli aveva preparato per lui."],
[6005,"I servi del re dissero: \"Ecco, Aman è nel cortile della reggia\". E il re replicò: \"Chiamatelo!\"."],
[6006,"Allora il re disse ad Aman: \"Che cosa dovrò fare per l'uomo che io voglio onorare?\". Aman disse in cuor suo: \"Chi il re vuole onorare se non me?\"."],
[6007,"E rispose al re: \"Per l'uomo che il re vuole onorare,"],
[6008,"i servi del re portino una veste di lino che viene indossata dal re e un cavallo che il re suole cavalcare:"],
[6009,"siano dati a uno degli amici del re, fra i nobili, e questi ne rivesta l'uomo che il re ama; poi lo faccia salire sul cavallo e si annunci nella piazza della città: \"Così sarà per ogni uomo che il re intende onorare\"\"."],
[6010,"Il re disse ad Aman: \"Come hai detto, così fai a Mardocheo, il Giudeo, che si trova nel cortile della reggia, e non trascurare nulla di quello che hai detto\"."],
[6011,"Aman prese la veste e il cavallo, rivestì Mardocheo e lo fece salire sul cavallo, passò per la piazza della città annunciando: \"Così sarà per ogni uomo che il re intende onorare\"."],
[6012,"Mardocheo ritornò nel cortile della reggia, e Aman tornò a casa sua afflitto e con il capo coperto."],
[6013,"Poi Aman raccontò a Zosara, sua moglie, e ai suoi amici quello che era accaduto. Allora gli amici e la moglie si rivolsero a lui con queste parole: \"Se Mardocheo è della stirpe dei Giudei, comincia ad abbassarti davanti a lui, cadendo ai suoi piedi: tu non potrai resistergli, perché il Dio vivente è con lui\"."],
[6014,"Essi stavano ancora parlando, quando giunsero gli eunuchi e in fretta portarono Aman al banchetto che Ester aveva preparato."],
[7001,"Il re e Aman andarono a banchettare con la regina."],
[7002,"Il secondo giorno che si beveva, il re disse a Ester: \"Che c'è, regina Ester? Qual è la tua domanda e quale la tua richiesta? Fosse anche la metà del mio regno, ti sarà data\"."],
[7003,"Rispose: \"Se ho trovato grazia davanti al re, sia risparmiata la vita a me, secondo la mia domanda, e al mio popolo, secondo la mia richiesta."],
[7004,"Infatti siamo stati venduti, io e il mio popolo, siamo stati vendutiDisse il re: \"Chi è costui, che ha osato fare queste cose?\".  per essere distrutti, uccisi e fatti schiavi, noi e i nostri figli, per diventare servi e serve; ma io finsi di non udire, perché quel calunniatore non è degno del palazzo del re\"."],
[7005,"Disse il re: \"Chi è costui, che ha osato fare queste cose?\"."],
[7006,"Ester rispose: \"Un nemico: Aman è quel malvagio\". Aman fu preso da terrore in presenza del re e della regina."],
[7007,"Allora il re si alzò dal banchetto per andare nel giardino: Aman si mise a supplicare la regina perché avvertiva di essere nei guai."],
[7008,"Il re ritornò dal giardino, e intanto Aman si era lasciato cadere sul divano supplicando la regina. Allora il re disse: \"Vuole anche fare violenza a mia moglie in casa mia?\". Appena ebbe sentito, Aman mutò d'aspetto."],
[7009,"Bugatan, uno degli eunuchi, disse al re: \"Ecco, Aman ha preparato anche un palo per Mardocheo, il quale aveva parlato in favore del re, un palo alto cinquanta cubiti, eretto nella proprietà di Aman\". Disse il re: \"Sia impiccato su quel palo\"."],
[7010,"Allora Aman fu appeso al palo che aveva preparato per Mardocheo. E l'ira del re si placò."],
[8001,"Lo stesso giorno, il re Artaserse donò a Ester la proprietà di Aman, il calunniatore, e Mardocheo fu chiamato dal re, perché Ester aveva rivelato che egli era legato da parentela con lei.   Allora il re prese l'anello che aveva fatto ritirare ad Aman e lo diede a Mardocheo, ed Ester stabilì Mardocheo su tutte le proprietà di Aman."],
[8003,"Ester parlò di nuovo al re, cadde ai suoi piedi e lo pregava di rimuovere il male fatto da Aman, tutto quello che aveva fatto contro i Giudei."],
[8004,"Il re stese lo scettro d'oro verso Ester ed Ester si alzò per stare accanto al re."],
[8005,"Disse Ester: \"Se piace a te e ho trovato grazia, si ordini di revocare le lettere inviate da Aman, quelle che erano state scritte per sterminare i Giudei che si trovano nel tuo regno."],
[8006,"Come potrei infatti sopportare la vista dei mali del mio popolo e come potrei sopravvivere allo sterminio della mia stirpe?\"."],
[8007,"Il re rispose a Ester: \"Se ti ho dato tutti i beni di Aman e ti ho concesso la mia grazia, se l'ho fatto appendere a un palo perché aveva messo le mani sui Giudei, che cosa chiedi ancora?"],
[8008,"Potete scrivere voi a mio nome, come vi sembra, e sigillate con il mio anello: infatti tutto quello che è stato scritto su comando del re ed è stato sigillato con il mio anello reale non può essere revocato\"."],
[8009,"Il ventitré del primo mese, quello di Nisan, dello stesso anno, furono convocati i segretari e fu scritto ai Giudei tutto quello che era stato comandato ai governatori e ai capi dei satrapi, dall'India fino all'Etiopia, centoventisette satrapie, provincia per provincia, secondo le loro lingue."],
[8010,"Fu scritto a nome del re e fu posto il sigillo del suo anello, e le lettere furono mandate per mezzo di corrieri:"],
[8011,"si prescriveva loro di seguire le loro leggi in qualunque città, sia per difendersi che per trattare come volevano i loro nemici e i loro avversari,"],
[8012.01,"Quanto segue è la copia della lettera:"],
[8012.02,"\"Il grande re Artaserse ai governatori delle centoventisette satrapie, dall'India all'Etiopia, e a quelli che hanno a cuore i nostri interessi, salute."],
[8012.029999999999999,"Molti uomini, quanto più spesso vengono onorati dalla più munifica generosità dei benefattori, tanto più s'inorgogliscono e non solo cercano di fare il male ai nostri sudditi, ma, incapaci di frenare la loro superbia, tramano insidie anche contro i loro benefattori."],
[8012.039999999999999,"Non solo cancellano la riconoscenza dal cuore degli uomini, ma, esaltati dallo strepito spavaldo di chi ignora il bene, si lusingano di sfuggire a Dio, che tutto vede, e alla sua giustizia che odia il male."],
[8012.050000000000001,"Spesso poi molti di coloro che sono costituiti in autorità, per aver affidato a certi amici la responsabilità degli affari pubblici e per aver subito la loro influenza, divennero con essi responsabili del sangue innocente e furono travolti in disgrazie irreparabili,"],
[8012.06,"perché i falsi ragionamenti di nature perverse avevano sviato l'incontaminata buona fede dei governanti."],
[8012.07,"Questo si può vedere non tanto nelle storie più antiche a cui abbiamo accennato, quanto piuttosto badando alle iniquità perpetrate dal comportamento corrotto di coloro che indegnamente esercitano il potere."],
[8012.08,"Provvederemo per l'avvenire ad assicurare a tutti gli uomini un regno indisturbato e pacifico,"],
[8012.09,"operando cambiamenti opportuni e giudicando sempre con la più equa fermezza gli affari che ci vengono posti sotto gli occhi."],
[8012.1,"Questo è il caso di Aman, figlio di Amadata, il Macedone, il quale estraneo, per la verità, al sangue persiano e ben lontano dalla nostra bontà, essendo stato accolto come ospite presso di noi,"],
[8012.109999999999999,"aveva tanto approfittato dell'umanità che professiamo verso qualunque nazione, da essere proclamato nostro padre e da ottenere il secondo rango presso il trono regale, venendo da tutti onorato con la prostrazione."],
[8012.119999999999999,"Ma non reggendo al peso della sua superbia, egli si adoperò per privare noi del potere e della vita"],
[8012.130000000000001,"e, con falsi e tortuosi argomenti, richiese la pena di morte per il nostro salvatore e strenuo benefattore Mardocheo, per l'irreprensibile consorte del nostro regno Ester e per tutto il loro popolo."],
[8012.140000000000001,"Egli infatti, avendoci messo in una condizione di isolamento, pensava di trasferire l'impero dei Persiani ai Macedoni."],
[8012.15,"Ora, noi troviamo che questi Giudei, destinati da quell'uomo tre volte scellerato allo sterminio, non sono malfattori, ma sono governati da leggi giustissime,"],
[8012.16,"sono figli del Dio altissimo, massimo, vivente, il quale in favore nostro e dei nostri antenati dirige il regno nel migliore dei modi."],
[8012.17,"Farete dunque bene a non tenere conto delle lettere mandate da Aman, figlio di Amadata, perché costui, che ha perpetrato tali cose, è stato impiccato a un palo con tutta la sua famiglia alle porte di Susa, giusto castigo datogli rapidamente da Dio, dominatore di tutti gli eventi."],
[8012.18,"Esposta invece una copia della presente lettera in ogni luogo, permettete ai Giudei di valersi con tutta sicurezza delle loro leggi e prestate loro man forte per respingere coloro che volessero assalirli al momento della persecuzione, in quello stesso giorno, cioè il [tredici] del dodicesimo mese, chiamato Adar."],
[8012.19,"Infatti questo giorno, invece di segnare la rovina della stirpe eletta, Dio, dominatore di ogni cosa, lo ha cambiato per loro in giorno di gioia."],
[8012.199999999999999,"Quanto a voi, dunque, tra le vostre feste commemorative celebrate questo giorno insigne con ogni sorta di banchetti, perché, ora e in avvenire, sia salvezza per noi e per gli amici dei Persiani, ma per quelli che ci insidiano sia ricordo della loro perdizione."],
[8012.210000000000001,"Ogni città e, in generale, ogni località che non agirà secondo queste disposizioni, sarà inesorabilmente messa a ferro e fuoco; non soltanto agli uomini sarà resa inaccessibile, ma anche alle fiere e agli uccelli diventerà orribile per tutti i tempi.*"],
[8012.9,"e ciò in un solo giorno: il tredici del dodicesimo mese, quello di Adar, in tutto il regno di Artaserse.*"],
[8013,"Le copie della lettera siano esposte in chiara evidenza in tutto il regno e in quel giorno i Giudei siano pronti a combattere contro i loro nemici\"."],
[8014,"Allora i cavalieri partirono in fretta per eseguire gli ordini del re, mentre il decreto fu promulgato anche a Susa."],
[8015,"Mardocheo uscì indossando la veste regale e portando una corona d'oro e un diadema di lino purpureo. Al vederlo gli abitanti di Susa se ne rallegrarono."],
[8016,"Per i Giudei vi era luce e letizia;"],
[8017,"in ogni città e provincia dove era stato pubblicato l'editto, dovunque era stato esposto il decreto, vi erano per i Giudei gioia ed esultanza, festa e allegria. E molti pagani si fecero circoncidere e, per paura dei Giudei, si fecero Giudei."],
[9001,"Il dodicesimo mese, il tredici del mese di Adar, le lettere scritte dal re erano giunte."],
[9002,"In quel giorno i nemici dei Giudei perirono; nessuno resistette per paura di loro."],
[9003,"Infatti i capi dei satrapi, i principi e gli scribi del re onoravano i Giudei, poiché la paura di Mardocheo si era impadronita di loro."],
[9004,"In effetti l'editto del re imponeva che egli fosse onorato in tutto il regno. ["],
[9005,"I Giudei dunque colpirono tutti i nemici, passandoli a fil di spada, uccidendoli e sterminandoli; fecero dei nemici quello che vollero.]"],
[9006,"Nella città di Susa i Giudei uccisero cinquecento uomini:"],
[9007,"Farsannestain, Delfo, Fasga,"],
[9008,"Fardata, Barea, Sarbacà,"],
[9009,"Marmasimà, Arufeo, Arseo, Zabuteo,"],
[9010,"i dieci figli di Aman, figlio di Amadata, il Bugeo, nemico dei Giudei, e fecero saccheggio."],
[9011,"In quello stesso giorno il numero di quelli che perirono a Susa fu reso noto al re."],
[9012,"Allora il re disse a Ester: \"I Giudei hanno fatto perire cinquecento uomini nella città di Susa, e come pensi si siano comportati nel resto del paese? Che cosa chiedi ancora? Ti sarà dato\"."],
[9013,"Ester disse al re: \"Sia concesso ai Giudei di comportarsi allo stesso modo domani, fino a quando saranno impiccati i dieci figli di Aman\"."],
[9014,"Ed egli permise che così si facesse e consegnò ai Giudei della città i corpi dei figli di Aman per essere appesi."],
[9015,"I Giudei si radunarono nella città di Susa il quattordicesimo giorno del mese di Adar e uccisero trecento uomini, ma non fecero alcun saccheggio."],
[9016,"Il resto dei Giudei che si erano radunati nel regno, si aiutarono a vicenda ed ebbero tregua dai loro nemici: infatti ne sterminarono quindicimila nel tredicesimo giorno del mese di Adar, ma non fecero alcun saccheggio."],
[9017,"Il quattordicesimo giorno dello stesso mese si riposarono e trascorsero quel giorno di riposo con gioia ed esultanza."],
[9018,"Invece nella città di Susa i Giudei che si erano radunati anche il quattordicesimo giorno, ma senza riposarsi, trascorsero nella gioia e nell'esultanza anche il quindicesimo giorno."],
[9019,"È per questo dunque che i Giudei sparsi in ogni provincia straniera celebrano con gioia il quattordicesimo giorno del mese di Adar come giorno di festa, mandando ciascuno regali al suo prossimo. Coloro che risiedono invece nelle città principali celebrano con gioia anche il quindicesimo giorno del mese di Adar come giorno di festa, mandando ciascuno regali al suo prossimo.*"],
[9020,"Mardocheo scrisse queste cose su un libro e lo mandò ai Giudei che vivevano nel regno di Artaserse vicini e lontani,"],
[9021,"per stabilire questi giorni come festivi, da celebrare il quattordici e il quindici del mese di Adar."],
[9022,"In quei giorni infatti i Giudei ebbero tregua dai loro nemici, e quello fu il mese, Adar, nel quale essi passarono dal pianto alla gioia e dal dolore a un giorno di festa; perciò esso deve essere considerato tutto quanto come un periodo di giorni festivi, di nozze ed esultanza, in cui si inviano doni agli amici e ai poveri."],
[9023,"I Giudei approvarono il racconto che aveva scritto loro Mardocheo:"],
[9024,"come Aman, figlio di Amadata, il Macedone, li aveva combattuti, come egli aveva emesso il decreto e aveva tirato le sorti per farli scomparire"],
[9025,"e come egli era andato dal re dicendogli di impiccare Mardocheo; ma tutti i mali che egli aveva cercato di far cadere sopra i Giudei erano venuti sopra di lui, ed era stato impiccato lui e i suoi figli."],
[9026,"Perciò quei giorni furono chiamati Purim a motivo delle sorti, poiché nella loro lingua esse sono chiamate Purim, e a motivo delle parole di questa lettera, che ricordava tutto quello che avevano sofferto e che era loro capitato."],
[9027,"Mardocheo stabilì e i Giudei approvarono per sé, per i loro discendenti e per quelli che si fossero uniti a loro, che non si sarebbero comportati in modo diverso: questi giorni dovevano essere un memoriale da osservare di generazione in generazione, in ogni città, famiglia e provincia."],
[9028,"Questi giorni dei Purim saranno celebrati in ogni tempo, e il loro ricordo non sia lasciato cadere dai loro discendenti."],
[9029,"La regina Ester, figlia di Aminadab, e Mardocheo, il Giudeo, scrissero tutto quello che avevano fatto e confermarono la lettera dei Purim. ["],
[9031,"Mardocheo e la regina Ester stabilirono per sé privatamente di digiunare; imposero allora la loro volontà contro la loro salute."],
[9032,"Ester lo stabilì con un ordine che fu scritto come memoriale.]"],
[10001,"Il re impose tributi a tutto il regno sia per terra che per mare."],
[10002,"La sua potenza e il suo valore, la ricchezza e la gloria del suo regno, tutto sta scritto nel libro del re dei Persiani e dei Medi, a memoria."],
[10003.0099999999999998,"E Mardocheo disse: \"Queste cose sono avvenute per volere di Dio."],
[10003.02,"Mi ricordo infatti del sogno che ebbi circa le cose di cui sto parlando: neppure un loro dettaglio è stato tralasciato.]"],
[10003.0299999999999998,"La piccola sorgente che divenne un fiume, la luce che spuntò, il sole e l'acqua copiosa: questo fiume è Ester, che il re ha sposato e costituito regina."],
[10003.04,"I due draghi siamo io e Aman."],
[10003.0499999999999998,"Le nazioni sono quelle che si coalizzarono per distruggere il nome dei Giudei."],
[10003.0600000000000001,"La mia nazione è Israele, quelli che elevarono le loro grida a Dio e furono salvati. Sì, il Signore ha salvato il suo popolo, ci ha liberati da tutti questi mali; Dio ha operato segni e prodigi grandi, quali non sono accaduti mai tra le nazioni."],
[10003.0699999999999998,"Così egli gettò due sorti: una per il popolo di Dio e una per tutte le nazioni."],
[10003.0800000000000001,"Queste due sorti si sono realizzate nell'ora, nel momento opportuno, nel giorno del giudizio al cospetto di Dio e in tutte le nazioni."],
[10003.0899999999999999,"Dio allora si ricordò del suo popolo e rese giustizia alla sua eredità."],
[10003.1000000000000001,"Questi giorni del mese di Adar, il quattordici e il quindici dello stesso mese, saranno celebrati con riunioni, gioia e letizia davanti a Dio, di generazione in generazione, per sempre, nel suo popolo Israele\". ["],
[10003.1099999999999999,"Nell'anno quarto del re Tolomeo e di Cleopatra, Dositeo, che diceva di essere sacerdote e levita, e Tolomeo, suo figlio, portarono in Egitto la presente lettera sui Purim, e dissero che si trattava della lettera autentica tradotta da Lisimaco, figlio di Tolomeo, residente a Gerusalemme.]"],
[10003.8999999999999999,"Mardocheo era secondo rispetto al re Artaserse, era grande nel regno ed era onorato dai Giudei; trascorse la sua vita amato da tutta la sua nazione."]
])
