Bib.ret([
[1001,"Paolo, prigioniero di Cristo Gesù, e il fratello Timoteo al carissimo Filemone, nostro collaboratore,"],
[1002,"alla sorella Apfia, ad Archippo nostro compagno nella lotta per la fede e alla comunità che si raduna nella tua casa:"],
[1003,"grazia a voi e pace da Dio nostro Padre e dal Signore Gesù Cristo."],
[1004,"Rendo grazie al mio Dio, ricordandomi sempre di te nelle mie preghiere,"],
[1005,"perché sento parlare della tua carità e della fede che hai nel Signore Gesù e verso tutti i santi."],
[1006,"La tua partecipazione alla fede diventi operante, per far conoscere tutto il bene che c'è tra noi per Cristo."],
[1007,"La tua carità è stata per me motivo di grande gioia e consolazione, fratello, perché per opera tua i santi sono stati profondamente confortati."],
[1008,"Per questo, pur avendo in Cristo piena libertà di ordinarti ciò che è opportuno,"],
[1009,"in nome della carità piuttosto ti esorto, io, Paolo, così come sono, vecchio, e ora anche prigioniero di Cristo Gesù."],
[1010,"Ti prego per Onesimo, figlio mio, che ho generato nelle catene,"],
[1011,"lui, che un giorno ti fu inutile, ma che ora è utile a te e a me."],
[1012,"Te lo rimando, lui che mi sta tanto a cuore."],
[1013,"Avrei voluto tenerlo con me perché mi assistesse al posto tuo, ora che sono in catene per il Vangelo."],
[1014,"Ma non ho voluto fare nulla senza il tuo parere, perché il bene che fai non sia forzato, ma volontario."],
[1015,"Per questo forse è stato separato da te per un momento: perché tu lo riavessi per sempre;"],
[1016,"non più però come schiavo, ma molto più che schiavo, come fratello carissimo, in primo luogo per me, ma ancora più per te, sia come uomo sia come fratello nel Signore."],
[1017,"Se dunque tu mi consideri amico, accoglilo come me stesso."],
[1018,"E se in qualche cosa ti ha offeso o ti è debitore, metti tutto sul mio conto."],
[1019,"Io, Paolo, lo scrivo di mio pugno: pagherò io. Per non dirti che anche tu mi sei debitore, e proprio di te stesso!"],
[1020,"Sì, fratello! Che io possa ottenere questo favore nel Signore; da' questo sollievo al mio cuore, in Cristo!"],
[1021,"Ti ho scritto fiducioso nella tua docilità, sapendo che farai anche più di quanto ti chiedo."],
[1022,"Al tempo stesso preparami un alloggio, perché, grazie alle vostre preghiere, spero di essere restituito a voi."],
[1023,"Ti saluta Èpafra, mio compagno di prigionia in Cristo Gesù,"],
[1024,"insieme con Marco, Aristarco, Dema e Luca, miei collaboratori."],
[1025,"La grazia del Signore Gesù Cristo sia con il vostro spirito."]
])
