Bib.ret([
[1001,"Paolo, apostolo non da parte di uomini, né per mezzo di uomo, ma per mezzo di Gesù Cristo e di Dio Padre che lo ha risuscitato dai morti,"],
[1002,"e tutti i fratelli che sono con me, alle Chiese della Galazia:"],
[1003,"grazia a voi e pace da Dio Padre nostro e dal Signore Gesù Cristo,"],
[1004,"che ha dato se stesso per i nostri peccati al fine di strapparci da questo mondo malvagio, secondo la volontà di Dio e Padre nostro,"],
[1005,"al quale sia gloria nei secoli dei secoli. Amen."],
[1006,"Mi meraviglio che, così in fretta, da colui che vi ha chiamati con la grazia di Cristo voi passiate a un altro vangelo."],
[1007,"Però non ce n'è un altro, se non che vi sono alcuni che vi turbano e vogliono sovvertire il vangelo di Cristo."],
[1008,"Ma se anche noi stessi, oppure un angelo dal cielo vi annunciasse un vangelo diverso da quello che vi abbiamo annunciato, sia anatema!"],
[1009,"L'abbiamo già detto e ora lo ripeto: se qualcuno vi annuncia un vangelo diverso da quello che avete ricevuto, sia anatema!"],
[1010,"Infatti, è forse il consenso degli uomini che cerco, oppure quello di Dio? O cerco di piacere agli uomini? Se cercassi ancora di piacere agli uomini, non sarei servitore di Cristo!"],
[1011,"Vi dichiaro, fratelli, che il Vangelo da me annunciato non segue un modello umano;"],
[1012,"infatti io non l'ho ricevuto né l'ho imparato da uomini, ma per rivelazione di Gesù Cristo."],
[1013,"Voi avete certamente sentito parlare della mia condotta di un tempo nel giudaismo: perseguitavo ferocemente la Chiesa di Dio e la devastavo,"],
[1014,"superando nel giudaismo la maggior parte dei miei coetanei e connazionali, accanito com'ero nel sostenere le tradizioni dei padri."],
[1015,"Ma quando Dio, che mi scelse fin dal seno di mia madre e mi chiamò con la sua grazia, si compiacque"],
[1016,"di rivelare in me il Figlio suo perché lo annunciassi in mezzo alle genti, subito, senza chiedere consiglio a nessuno,"],
[1017,"senza andare a Gerusalemme da coloro che erano apostoli prima di me, mi recai in Arabia e poi ritornai a Damasco."],
[1018,"In seguito, tre anni dopo, salii a Gerusalemme per andare a conoscere Cefa e rimasi presso di lui quindici giorni;"],
[1019,"degli apostoli non vidi nessun altro, se non Giacomo, il fratello del Signore."],
[1020,"In ciò che vi scrivo - lo dico davanti a Dio - non mentisco."],
[1021,"Poi andai nelle regioni della Siria e della Cilicia."],
[1022,"Ma non ero personalmente conosciuto dalle Chiese della Giudea che sono in Cristo;"],
[1023,"avevano soltanto sentito dire: \"Colui che una volta ci perseguitava, ora va annunciando la fede che un tempo voleva distruggere\"."],
[1024,"E glorificavano Dio per causa mia."],
[2001,"Quattordici anni dopo, andai di nuovo a Gerusalemme in compagnia di Barnaba, portando con me anche Tito:"],
[2002,"vi andai però in seguito a una rivelazione. Esposi loro il Vangelo che io annuncio tra le genti, ma lo esposi privatamente alle persone più autorevoli, per non correre o aver corso invano."],
[2003,"Ora neppure Tito, che era con me, benché fosse greco, fu obbligato a farsi circoncidere;"],
[2004,"e questo contro i falsi fratelli intrusi, i quali si erano infiltrati a spiare la nostra libertà che abbiamo in Cristo Gesù, allo scopo di renderci schiavi;"],
[2005,"ma a loro non cedemmo, non sottomettendoci neppure per un istante, perché la verità del Vangelo continuasse a rimanere salda tra voi."],
[2006,"Da parte dunque delle persone più autorevoli - quali fossero allora non m'interessa, perché Dio non guarda in faccia ad alcuno - quelle persone autorevoli a me non imposero nulla."],
[2007,"Anzi, visto che a me era stato affidato il Vangelo per i non circoncisi, come a Pietro quello per i circoncisi -"],
[2008,"poiché colui che aveva agito in Pietro per farne un apostolo dei circoncisi aveva agito anche in me per le genti -"],
[2009,"e riconoscendo la grazia a me data, Giacomo, Cefa e Giovanni, ritenuti le colonne, diedero a me e a Barnaba la destra in segno di comunione, perché noi andassimo tra le genti e loro tra i circoncisi."],
[2010,"Ci pregarono soltanto di ricordarci dei poveri, ed è quello che mi sono preoccupato di fare."],
[2011,"Ma quando Cefa venne ad Antiochia, mi opposi a lui a viso aperto perché aveva torto."],
[2012,"Infatti, prima che giungessero alcuni da parte di Giacomo, egli prendeva cibo insieme ai pagani; ma, dopo la loro venuta, cominciò a evitarli e a tenersi in disparte, per timore dei circoncisi."],
[2013,"E anche gli altri Giudei lo imitarono nella simulazione, tanto che pure Barnaba si lasciò attirare nella loro ipocrisia."],
[2014,"Ma quando vidi che non si comportavano rettamente secondo la verità del Vangelo, dissi a Cefa in presenza di tutti: \"Se tu, che sei Giudeo, vivi come i pagani e non alla maniera dei Giudei, come puoi costringere i pagani a vivere alla maniera dei Giudei?\"."],
[2015,"Noi, che per nascita siamo Giudei e non pagani peccatori,"],
[2016,"sapendo tuttavia che l'uomo non è giustificato per le opere della Legge ma soltanto per mezzo della fede in Gesù Cristo, abbiamo creduto anche noi in Cristo Gesù per essere giustificati per la fede in Cristo e non per le opere della Legge; poiché per le opere della Legge non verrà mai giustificato nessuno."],
[2017,"Se pertanto noi che cerchiamo la giustificazione in Cristo siamo trovati peccatori come gli altri, Cristo è forse ministro del peccato? Impossibile!"],
[2018,"Infatti se torno a costruire quello che ho distrutto, mi denuncio come trasgressore."],
[2019,"In realtà mediante la Legge io sono morto alla Legge, affinché io viva per Dio. Sono stato crocifisso con Cristo,"],
[2020,"e non vivo più io, ma Cristo vive in me. E questa vita, che io vivo nel corpo, la vivo nella fede del Figlio di Dio, che mi ha amato e ha consegnato se stesso per me."],
[2021,"Dunque non rendo vana la grazia di Dio; infatti, se la giustificazione viene dalla Legge, Cristo è morto invano."],
[3001,"O stolti Galati, chi vi ha incantati? Proprio voi, agli occhi dei quali fu rappresentato al vivo Gesù Cristo crocifisso!"],
[3002,"Questo solo vorrei sapere da voi: è per le opere della Legge che avete ricevuto lo Spirito o per aver ascoltato la parola della fede?"],
[3003,"Siete così privi d'intelligenza che, dopo aver cominciato nel segno dello Spirito, ora volete finire nel segno della carne?"],
[3004,"Avete tanto sofferto invano? Se almeno fosse invano!"],
[3005,"Colui dunque che vi concede lo Spirito e opera portenti in mezzo a voi, lo fa grazie alle opere della Legge o perché avete ascoltato la parola della fede?"],
[3006,"Come Abramo  ebbe fede in Dio e gli fu accreditato come giustizia,"],
[3007,"riconoscete dunque che figli di Abramo sono quelli che vengono dalla fede."],
[3008,"E la Scrittura, prevedendo che Dio avrebbe giustificato i pagani per la fede, preannunciò ad Abramo:  In te saranno benedette tutte le nazioni ."],
[3009,"Di conseguenza, quelli che vengono dalla fede sono benedetti insieme ad Abramo, che credette."],
[3010,"Quelli invece che si richiamano alle opere della Legge stanno sotto la maledizione, poiché sta scritto:  Maledetto chiunque non rimane fedele a tutte le cose scritte nel libro della Legge per metterle in pratica ."],
[3011,"E che nessuno sia giustificato davanti a Dio per la Legge risulta dal fatto che  il giusto per fede vivrà."],
[3012,"Ma la Legge non si basa sulla fede; al contrario dice:  Chi metterà in pratica queste cose, vivrà grazie ad esse ."],
[3013,"Cristo ci ha riscattati dalla maledizione della Legge, diventando lui stesso maledizione per noi, poiché sta scritto:  Maledetto chi è appeso al legno ,"],
[3014,"perché in Cristo Gesù la benedizione di Abramo passasse ai pagani e noi, mediante la fede, ricevessimo la promessa dello Spirito."],
[3015,"Fratelli, ecco, vi parlo da uomo: un testamento legittimo, pur essendo solo un atto umano, nessuno lo dichiara nullo o vi aggiunge qualche cosa."],
[3016,"Ora è appunto ad Abramo e alla sua discendenza che furono fatte le promesse. Non dice la Scrittura: \"E ai discendenti\", come se si trattasse di molti, ma:  E alla tua discendenza,  come a uno solo, cioè Cristo."],
[3017,"Ora io dico: un testamento stabilito in precedenza da Dio stesso, non può dichiararlo nullo una Legge che è venuta quattrocentotrenta anni dopo, annullando così la promessa."],
[3018,"Se infatti l'eredità si ottenesse in base alla Legge, non sarebbe più in base alla promessa; Dio invece ha fatto grazia ad Abramo mediante la promessa."],
[3019,"Perché allora la Legge? Essa fu aggiunta a motivo delle trasgressioni, fino alla venuta della discendenza per la quale era stata fatta la promessa, e fu promulgata per mezzo di angeli attraverso un mediatore."],
[3020,"Ma non si dà mediatore per una sola persona: ora, Dio è uno solo."],
[3021,"La Legge è dunque contro le promesse di Dio? Impossibile! Se infatti fosse stata data una Legge capace di dare la vita, la giustizia verrebbe davvero dalla Legge;"],
[3022,"la Scrittura invece ha rinchiuso ogni cosa sotto il peccato, perché la promessa venisse data ai credenti mediante la fede in Gesù Cristo."],
[3023,"Ma prima che venisse la fede, noi eravamo custoditi e rinchiusi sotto la Legge, in attesa della fede che doveva essere rivelata."],
[3024,"Così la Legge è stata per noi un pedagogo, fino a Cristo, perché fossimo giustificati per la fede."],
[3025,"Sopraggiunta la fede, non siamo più sotto un pedagogo."],
[3026,"Tutti voi infatti siete figli di Dio mediante la fede in Cristo Gesù,"],
[3027,"poiché quanti siete stati battezzati in Cristo vi siete rivestiti di Cristo."],
[3028,"Non c'è Giudeo né Greco; non c'è schiavo né libero; non c'è maschio e femmina, perché tutti voi siete uno in Cristo Gesù."],
[3029,"Se appartenete a Cristo, allora siete discendenza di Abramo, eredi secondo la promessa."],
[4001,"Dico ancora: per tutto il tempo che l'erede è fanciullo, non è per nulla differente da uno schiavo, benché sia padrone di tutto, ma"],
[4002,"dipende da tutori e amministratori fino al termine prestabilito dal padre."],
[4003,"Così anche noi, quando eravamo fanciulli, eravamo schiavi degli elementi del mondo."],
[4004,"Ma quando venne la pienezza del tempo, Dio mandò il suo Figlio, nato da donna, nato sotto la Legge,"],
[4005,"per riscattare quelli che erano sotto la Legge, perché ricevessimo l'adozione a figli."],
[4006,"E che voi siete figli lo prova il fatto che Dio mandò nei nostri cuori lo Spirito del suo Figlio, il quale grida: \"Abbà! Padre!\"."],
[4007,"Quindi non sei più schiavo, ma figlio e, se figlio, sei anche erede per grazia di Dio."],
[4008,"Ma un tempo, per la vostra ignoranza di Dio, voi eravate sottomessi a divinità che in realtà non lo sono."],
[4009,"Ora invece che avete conosciuto Dio, anzi da lui siete stati conosciuti, come potete rivolgervi di nuovo a quei deboli e miserabili elementi, ai quali di nuovo come un tempo volete servire?"],
[4010,"Voi infatti osservate scrupolosamente giorni, mesi, stagioni e anni!"],
[4011,"Temo per voi di essermi affaticato invano a vostro riguardo."],
[4012,"Siate come me - ve ne prego, fratelli -, poiché anch'io sono stato come voi. Non mi avete offeso in nulla."],
[4013,"Sapete che durante una malattia del corpo vi annunciai il Vangelo la prima volta;"],
[4014,"quella che, nella mia carne, era per voi una prova, non l'avete disprezzata né respinta, ma mi avete accolto come un angelo di Dio, come Cristo Gesù."],
[4015,"Dove sono dunque le vostre manifestazioni di gioia? Vi do testimonianza che, se fosse stato possibile, vi sareste cavati anche gli occhi per darli a me."],
[4016,"Sono dunque diventato vostro nemico dicendovi la verità?"],
[4017,"Costoro sono premurosi verso di voi, ma non onestamente; vogliono invece tagliarvi fuori, perché vi interessiate di loro."],
[4018,"È bello invece essere circondati di premure nel bene sempre, e non solo quando io mi trovo presso di voi,"],
[4019,"figli miei, che io di nuovo partorisco nel dolore finché Cristo non sia formato in voi!"],
[4020,"Vorrei essere vicino a voi in questo momento e cambiare il tono della mia voce, perché sono perplesso a vostro riguardo."],
[4021,"Ditemi, voi che volete essere sotto la Legge: non sentite che cosa dice la Legge?"],
[4022,"Sta scritto infatti che Abramo ebbe due figli, uno dalla schiava e uno dalla donna libera."],
[4023,"Ma il figlio della schiava è nato secondo la carne; il figlio della donna libera, in virtù della promessa."],
[4024,"Ora, queste cose sono dette per allegoria: le due donne infatti rappresentano le due alleanze. Una, quella del monte Sinai, che genera nella schiavitù, è rappresentata da Agar"],
[4025,"- il Sinai è un monte dell'Arabia -; essa corrisponde alla Gerusalemme attuale, che di fatto è schiava insieme ai suoi figli."],
[4026,"Invece la Gerusalemme di lassù è libera ed è la madre di tutti noi."],
[4027,"Sta scritto infatti: Rallegrati, sterile, tu che non partorisci, grida di gioia, tu che non conosci i dolori del parto, perché molti sono i figli dell'abbandonata, più di quelli della donna che ha marito ."],
[4028,"E voi, fratelli, siete figli della promessa, alla maniera di Isacco."],
[4029,"Ma come allora colui che era nato secondo la carne perseguitava quello nato secondo lo spirito, così accade anche ora."],
[4030,"Però, che cosa dice la Scrittura?  Manda via la schiava e suo figlio, perché il figlio della schiava non avrà eredità col figlio  della donna libera."],
[4031,"Così, fratelli, noi non siamo figli di una schiava, ma della donna libera."],
[5001,"Cristo ci ha liberati per la libertà! State dunque saldi e non lasciatevi imporre di nuovo il giogo della schiavitù."],
[5002,"Ecco, io, Paolo, vi dico: se vi fate circoncidere, Cristo non vi gioverà a nulla."],
[5003,"E dichiaro ancora una volta a chiunque si fa circoncidere che egli è obbligato ad osservare tutta quanta la Legge."],
[5004,"Non avete più nulla a che fare con Cristo voi che cercate la giustificazione nella Legge; siete decaduti dalla grazia."],
[5005,"Quanto a noi, per lo Spirito, in forza della fede, attendiamo fermamente la giustizia sperata."],
[5006,"Perché in Cristo Gesù non è la circoncisione che vale o la non circoncisione, ma la fede che si rende operosa per mezzo della carità."],
[5007,"Correvate così bene! Chi vi ha tagliato la strada, voi che non obbedite più alla verità?"],
[5008,"Questa persuasione non viene sicuramente da colui che vi chiama!"],
[5009,"Un po' di lievito fa fermentare tutta la pasta."],
[5010,"Io sono fiducioso per voi, nel Signore, che non penserete diversamente; ma chi vi turba subirà la condanna, chiunque egli sia."],
[5011,"Quanto a me, fratelli, se predico ancora la circoncisione, perché sono tuttora perseguitato? Infatti, sarebbe annullato lo scandalo della croce."],
[5012,"Farebbero meglio a farsi mutilare quelli che vi gettano nello scompiglio!"],
[5013,"Voi infatti, fratelli, siete stati chiamati a libertà. Che questa libertà non divenga però un pretesto per la carne; mediante l'amore siate invece a servizio gli uni degli altri."],
[5014,"Tutta la Legge infatti trova la sua pienezza in un solo precetto:  Amerai il tuo prossimo come te stesso ."],
[5015,"Ma se vi mordete e vi divorate a vicenda, badate almeno di non distruggervi del tutto gli uni gli altri!"],
[5016,"Vi dico dunque: camminate secondo lo Spirito e non sarete portati a soddisfare il desiderio della carne."],
[5017,"La carne infatti ha desideri contrari allo Spirito e lo Spirito ha desideri contrari alla carne; queste cose si oppongono a vicenda, sicché voi non fate quello che vorreste."],
[5018,"Ma se vi lasciate guidare dallo Spirito, non siete sotto la Legge."],
[5019,"Del resto sono ben note le opere della carne: fornicazione, impurità, dissolutezza,"],
[5020,"idolatria, stregonerie, inimicizie, discordia, gelosia, dissensi, divisioni, fazioni,"],
[5021,"invidie, ubriachezze, orge e cose del genere. Riguardo a queste cose vi preavviso, come già ho detto: chi le compie non erediterà il regno di Dio."],
[5022,"Il frutto dello Spirito invece è amore, gioia, pace, magnanimità, benevolenza, bontà, fedeltà, mitezza, dominio di sé;"],
[5023,"contro queste cose non c'è Legge."],
[5024,"Quelli che sono di Cristo Gesù hanno crocifisso la carne con le sue passioni e i suoi desideri."],
[5025,"Perciò se viviamo dello Spirito, camminiamo anche secondo lo Spirito."],
[5026,"Non cerchiamo la vanagloria, provocandoci e invidiandoci gli uni gli altri."],
[6001,"Fratelli, se uno viene sorpreso in qualche colpa, voi, che avete lo Spirito, correggetelo con spirito di dolcezza. E tu vigila su te stesso, per non essere tentato anche tu."],
[6002,"Portate i pesi gli uni degli altri: così adempirete la legge di Cristo."],
[6003,"Se infatti uno pensa di essere qualcosa, mentre non è nulla, inganna se stesso."],
[6004,"Ciascuno esamini invece la propria condotta e allora troverà motivo di vanto solo in se stesso e non in rapporto agli altri."],
[6005,"Ciascuno infatti porterà il proprio fardello."],
[6006,"Chi viene istruito nella Parola, condivida tutti i suoi beni con chi lo istruisce."],
[6007,"Non fatevi illusioni: Dio non si lascia ingannare. Ciascuno raccoglierà quello che avrà seminato."],
[6008,"Chi semina nella sua carne, dalla carne raccoglierà corruzione; chi semina nello Spirito, dallo Spirito raccoglierà vita eterna."],
[6009,"E non stanchiamoci di fare il bene; se infatti non desistiamo, a suo tempo mieteremo."],
[6010,"Poiché dunque ne abbiamo l'occasione, operiamo il bene verso tutti, soprattutto verso i fratelli nella fede."],
[6011,"Vedete con che grossi caratteri vi scrivo, di mia mano."],
[6012,"Quelli che vogliono fare bella figura nella carne, vi costringono a farvi circoncidere, solo per non essere perseguitati a causa della croce di Cristo."],
[6013,"Infatti neanche gli stessi circoncisi osservano la Legge, ma vogliono la vostra circoncisione per trarre vanto dalla vostra carne."],
[6014,"Quanto a me invece non ci sia altro vanto che nella croce del Signore nostro Gesù Cristo, per mezzo della quale il mondo per me è stato crocifisso, come io per il mondo."],
[6015,"Non è infatti la circoncisione che conta, né la non circoncisione, ma l'essere nuova creatura."],
[6016,"E su quanti seguiranno questa norma sia pace e misericordia, come su tutto l'Israele di Dio."],
[6017,"D'ora innanzi nessuno mi procuri fastidi: io porto le stigmate di Gesù sul mio corpo."],
[6018,"La grazia del Signore nostro Gesù Cristo sia con il vostro spirito, fratelli. Amen."]
])
