Bib.ret([
[1001,"Giuda, servo di Gesù Cristo e fratello di Giacomo, a coloro che sono prediletti, amati in Dio Padre e custoditi da Gesù Cristo,"],
[1002,"a voi siano date in abbondanza misericordia, pace e carità."],
[1003,"Carissimi, avendo un gran desiderio di scrivervi riguardo alla nostra comune salvezza, sono stato costretto a farlo per esortarvi a combattere per la fede, che fu trasmessa ai santi una volta per sempre."],
[1004,"Si sono infiltrati infatti in mezzo a voi alcuni individui, per i quali già da tempo sta scritta questa condanna, perché empi, che stravolgono la grazia del nostro Dio in dissolutezze e rinnegano il nostro unico padrone e signore Gesù Cristo."],
[1005,"A voi, che conoscete tutte queste cose, voglio ricordare che il Signore, dopo aver liberato il popolo dalla terra d'Egitto, fece poi morire quelli che non vollero credere"],
[1006,"e tiene in catene eterne, nelle tenebre, per il giudizio del grande giorno, gli angeli che non conservarono il loro grado ma abbandonarono la propria dimora."],
[1007,"Così Sodoma e Gomorra e le città vicine, che alla stessa maniera si abbandonarono all'immoralità e seguirono vizi contro natura, stanno subendo esemplarmente le pene di un fuoco eterno."],
[1008,"Ugualmente anche costoro, indotti dai loro sogni, contaminano il proprio corpo, disprezzano il Signore e insultano gli angeli."],
[1009,"Quando l'arcangelo Michele, in contrasto con il diavolo, discuteva per avere il corpo di Mosè, non osò accusarlo con parole offensive, ma disse:  Ti condanni il Signore!"],
[1010,"Costoro invece, mentre insultano tutto ciò che ignorano, si corrompono poi in quelle cose che, come animali irragionevoli, conoscono per mezzo dei sensi."],
[1011,"Guai a loro! Perché si sono messi sulla strada di Caino e, per guadagno, si sono lasciati andare alle seduzioni di Balaam e si sono perduti nella ribellione di Core."],
[1012,"Essi sono la vergogna dei vostri banchetti, perché mangiano con voi senza ritegno, pensando solo a nutrire se stessi. Sono nuvole senza pioggia, portate via dai venti, o alberi di fine stagione senza frutto, morti due volte, sradicati;"],
[1013,"sono onde selvagge del mare, che schiumano la loro sporcizia; sono astri erranti, ai quali è riservata l'oscurità delle tenebre eterne."],
[1014,"Profetò anche per loro Enoc, settimo dopo Adamo, dicendo: \"Ecco, il Signore è venuto con migliaia e migliaia dei suoi angeli"],
[1015,"per sottoporre tutti a giudizio, e per dimostrare la colpa di tutti riguardo a tutte le opere malvagie che hanno commesso e a tutti gli insulti che, da empi peccatori, hanno lanciato contro di lui\"."],
[1016,"Sono sobillatori pieni di acredine, che agiscono secondo le loro passioni; la loro bocca proferisce parole orgogliose e, per interesse, circondano le persone di adulazione."],
[1017,"Ma voi, o carissimi, ricordatevi delle cose che furono predette dagli apostoli del Signore nostro Gesù Cristo."],
[1018,"Essi vi dicevano: \"Alla fine dei tempi vi saranno impostori, che si comporteranno secondo le loro empie passioni\"."],
[1019,"Tali sono quelli che provocano divisioni, gente che vive di istinti, ma non ha lo Spirito."],
[1020,"Voi invece, carissimi, costruite voi stessi sopra la vostra santissima fede, pregate nello Spirito Santo,"],
[1021,"conservatevi nell'amore di Dio, attendendo la misericordia del Signore nostro Gesù Cristo per la vita eterna."],
[1022,"Siate misericordiosi verso quelli che sono indecisi"],
[1023,"e salvateli strappandoli dal fuoco; di altri infine abbiate compassione con timore, stando lontani perfino dai vestiti, contaminati dal loro corpo."],
[1024,"A colui che può preservarvi da ogni caduta e farvi comparire davanti alla sua gloria senza difetti e colmi di gioia,"],
[1025,"all'unico Dio, nostro salvatore, per mezzo di Gesù Cristo nostro Signore, gloria, maestà, forza e potenza prima di ogni tempo, ora e per sempre. Amen."]
])
