Bib.ret([
[1001,"Nell'anno dodicesimo del regno di Nabucodonosor, che era il re degli Assiri nella grande città di Ninive, Arfacsad regnava sui Medi a Ecbatana."],
[1002,"Questi edificò intorno a Ecbatana mura con pietre tagliate della misura di tre cubiti di larghezza e sei cubiti di lunghezza, portando l'altezza del muro a settanta cubiti e la larghezza a cinquanta cubiti."],
[1003,"Alle porte della città costruì le torri murali alte cento cubiti e larghe alla base sessanta cubiti;"],
[1004,"costruì le porte portandole fino all'altezza di settanta cubiti: la larghezza di ciascuna era di quaranta cubiti, per il passaggio del suo esercito e l'uscita in parata dei suoi fanti."],
[1005,"In quel tempo il re Nabucodonosor mosse guerra al re Arfacsad nella grande pianura, cioè nella piana che si trova nel territorio di Ragau."],
[1006,"A fianco di costui si schierarono tutti gli abitanti delle montagne e quelli della zona dell'Eufrate, del Tigri e dell'Idaspe e gli abitanti della pianura soggetta ad Arioc, re degli Elamiti. Così molte genti si trovarono adunate in aiuto dei figli di Cheleud."],
[1007,"Allora Nabucodonosor, re degli Assiri, spedì messaggeri a tutti gli abitanti della Persia e a tutti gli abitanti delle regioni occidentali: a quelli della Cilicia e di Damasco, del Libano e dell'Antilibano, a tutti gli abitanti della fascia litoranea"],
[1008,"e a quelli che appartenevano alle popolazioni del Carmelo e di Galaad, della Galilea superiore e della grande pianura di Èsdrelon,"],
[1009,"a tutti gli abitanti della Samaria e delle sue città, a quelli che stavano oltre il Giordano fino a Gerusalemme, Batane, Chelus, Kades e al torrente d'Egitto, nonché a Tafni, a Ramesse e a tutto il paese di Gessen,"],
[1010,"sino alla regione al di sopra di Tanis e Menfi, e a tutti gli abitanti dell'Egitto sino ai confini dell'Etiopia."],
[1011,"Ma gli abitanti di tutte queste regioni disprezzarono l'invito di Nabucodonosor, re degli Assiri, e non volevano seguirlo nella guerra, perché non avevano alcun timore di lui, che agli occhi loro era come un uomo qualunque. Essi rimandarono i suoi messaggeri a mani vuote e con disonore."],
[1012,"Allora Nabucodonosor si accese di sdegno terribile contro tutte queste regioni e giurò per il suo trono e per il suo regno che si sarebbe vendicato, devastando con la spada i paesi della Cilicia, di Damasco e della Siria, tutte le popolazioni della terra di Moab, gli Ammoniti, tutta la Giudea e tutti gli abitanti dell'Egitto fino al limite dei due mari."],
[1013,"Quindi marciò con l'esercito contro il re Arfacsad nel diciassettesimo anno, e prevalse su di lui in battaglia, travolgendo l'esercito di Arfacsad con tutta la sua cavalleria e tutti i suoi carri."],
[1014,"S'impadronì delle sue città, giunse fino a Ecbatana e ne espugnò le torri, ne saccheggiò le piazze e ridusse il suo splendore in ludibrio."],
[1015,"Poi sorprese Arfacsad sui monti di Ragau, lo trafisse con le sue lance e lo tolse di mezzo per sempre."],
[1016,"Fece quindi ritorno a Ninive con tutto l'insieme delle sue truppe, che era una moltitudine infinita di guerrieri, e si fermò là, egli e il suo esercito, oziando e banchettando per centoventi giorni."],
[2001,"Nell'anno diciottesimo, il giorno ventidue del primo mese, corse voce nel palazzo di Nabucodonosor, re degli Assiri, che egli avrebbe fatto vendetta contro tutte quelle regioni, come aveva detto."],
[2002,"Radunò tutti i suoi ministri e tutti i dignitari, tenne con loro consiglio segreto e decise egli stesso la distruzione totale di quelle regioni."],
[2003,"Essi decisero di sterminare tutti quelli che non si erano allineati con l'ordine da lui emanato."],
[2004,"Quando ebbe finito la consultazione, Nabucodonosor, re degli Assiri, chiamò Oloferne, generale supremo del suo esercito, che teneva il secondo posto dopo di lui, e gli disse:"],
[2005,"\"Questo dice il grande re, il signore di tutta la terra: \"Ecco, partito dalla mia presenza, tu prenderai con te uomini di indiscusso valore: centoventimila fanti e un contingente di dodicimila cavalli con i loro cavalieri;"],
[2006,"quindi marcerai contro tutti i paesi di occidente, perché quelle regioni hanno disobbedito al mio comando."],
[2007,"A costoro comanderai di preparare terra e acqua, perché con collera io piomberò su di loro e coprirò tutta la faccia della terra con i piedi del mio esercito e li darò in suo potere per il saccheggio."],
[2008,"Quelli di loro che cadranno colpiti riempiranno le loro valli, e ogni torrente e fiume sarà pieno dei loro cadaveri fino a straripare;"],
[2009,"i loro prigionieri li condurrò fino agli estremi confini della terra."],
[2010,"Tu dunque va' e occupa per me tutto il loro paese e, quando si saranno arresi a te, li terrai a mia disposizione fino al giorno del loro castigo."],
[2011,"Quanto ai ribelli, il tuo occhio non li risparmierà dalla morte e dalla devastazione in tutto il territorio."],
[2012,"Come è vero che vivo io e vive la potenza del mio regno, questo ho detto e questo farò di mia mano."],
[2013,"E tu non trasgredire parola alcuna del tuo signore, ma porta a compimento con ogni cura ciò che ti ho comandato e non indugiare a eseguire queste cose\"\"."],
[2014,"Partito dalla presenza del suo signore, Oloferne convocò tutti i comandanti, gli strateghi e gli ufficiali dell'esercito assiro;"],
[2015,"quindi, come gli aveva ordinato il suo signore, contò gli uomini che aveva scelto per la spedizione in numero di centoventimila, più dodicimila arcieri a cavallo,"],
[2016,"e li dispose come si usa schierare la truppa per la guerra."],
[2017,"Prese poi cammelli e asini e muli in dotazione alle truppe, in numero grandissimo, e ancora pecore e buoi e capre, in quantità innumerevole per il loro vettovagliamento."],
[2018,"Provvide ancora razioni in abbondanza per ciascun uomo e gran rifornimento d'oro e d'argento dal tesoro del re."],
[2019,"Poi lui e tutte le sue truppe si misero in marcia, per precedere il re Nabucodonosor e coprire tutta la faccia della terra di occidente con i loro carri, i cavalieri e la fanteria scelta."],
[2020,"Con loro si mise in cammino una moltitudine varia, numerosa come le cavallette e come la polvere del suolo, che non si poteva contare per la grande quantità."],
[2021,"Partirono da Ninive camminando tre giorni in direzione della pianura di Bectilet, e da Bectilet andarono ad accamparsi vicino al monte che sta sulla sinistra della Cilicia superiore."],
[2022,"Di là, con tutto il suo esercito, fanti e cavalli e carri, Oloferne si diresse verso la montagna."],
[2023,"Devastò Fud e Lud, e depredò tutti i figli di Rassis e gli Ismaeliti, che abitavano di fronte al deserto, a sud di Cheleon."],
[2024,"Passò l'Eufrate, attraversò la Mesopotamia e demolì tutte le città che s'innalzavano sul torrente Abronà, giungendo fino al mare."],
[2025,"Invase i paesi della Cilicia, sterminò quanti gli si opponevano e arrivò ai confini meridionali di Iafet, di fronte all'Arabia."],
[2026,"Accerchiò anche tutti i Madianiti, appiccò il fuoco alle loro tende e depredò il loro bestiame."],
[2027,"Scese verso la pianura di Damasco nei giorni della mietitura del grano, diede fuoco a tutti i loro campi e votò allo sterminio le loro greggi e gli armenti, saccheggiò le loro città, devastò le loro campagne e passò a fil di spada tutti i loro giovani."],
[2028,"Allora la paura e il terrore di lui si diffusero fra tutti gli abitanti della costa, quelli che si trovavano a Sidone e a Tiro, gli abitanti di Sur e di Okinà e tutti quelli di Iamnia; anche gli abitanti di Azoto e di Àscalon furono presi da grande terrore."],
[3001,"Gli inviarono perciò messaggeri con proposte di pace:"],
[3002,"\"Ecco, noi, servi del grande re Nabucodonosor, ci mettiamo davanti a te; fa' di noi quanto ti piacerà."],
[3003,"Ecco, le nostre case e tutto il nostro territorio e tutti i campi di grano, le greggi e gli armenti e tutto il bestiame delle nostre tende sono a tua disposizione, perché te ne serva come a te piace."],
[3004,"Anche le nostre città e i loro abitanti sono tuoi servi; vieni e trattale come ti è gradito\"."],
[3005,"Si presentarono dunque a Oloferne quegli uomini e si espressero con lui in questo tono."],
[3006,"Egli scese allora con il suo esercito lungo la costa e pose presidi nelle città fortificate, poi prelevò da esse uomini scelti come ausiliari."],
[3007,"Quelle popolazioni con tutto il paese circostante lo accolsero con corone e danze e suono di tamburelli."],
[3008,"Ma egli demolì tutti i loro templi e tagliò i boschi sacri, perché aveva ordine di distruggere tutti gli dei della terra, in modo che tutti i popoli adorassero solo Nabucodonosor e tutte le lingue e le tribù lo invocassero come dio."],
[3009,"Poi giunse in vista di Èsdrelon, vicino a Dotaim, che è di fronte alle grandi montagne della Giudea."],
[3010,"Si accamparono fra Gebe e Scitopoli e Oloferne rimase là un mese intero, per raccogliere tutto il bottino delle sue truppe."],
[4001,"Quando gli Israeliti che abitavano in tutta la Giudea appresero quello che Oloferne, il comandante supremo di Nabucodonosor, aveva fatto agli altri popoli e come aveva messo a sacco tutti i loro templi e li aveva votati allo sterminio,"],
[4002,"furono presi da indicibile terrore di fronte a lui e trepidarono per Gerusalemme e per il tempio del Signore, loro Dio."],
[4003,"Essi erano tornati da poco dall'esilio e di recente tutto il popolo si era radunato in Giudea; gli arredi sacri e l'altare e il tempio erano stati consacrati dopo la profanazione."],
[4004,"Perciò mandarono messaggeri in tutto il territorio della Samaria, a Cona, a Bet-Oron, a Belmain, a Gerico, a Coba, ad Aisorà e nella valle di Salem,"],
[4005,"e disposero di occupare in anticipo tutte le cime dei monti più alti, di circondare di mura i villaggi di quelle zone e di raccogliere vettovaglie in preparazione alla guerra, poiché nelle loro campagne era appena terminata la mietitura."],
[4006,"Inoltre Ioakim, sommo sacerdote a Gerusalemme in quel tempo, scrisse agli abitanti di Betulia e di Betomestaim, situata di fronte a Èsdrelon, all'imbocco della pianura che si estende vicino a Dotaim,"],
[4007,"ordinando loro di occupare i valichi dei monti, perché di là si apriva la via d'ingresso alla Giudea e sarebbe stato facile arrestarli al valico, dove per la strettezza del passaggio tutti erano obbligati a procedere a due a due."],
[4008,"Gli Israeliti fecero come avevano loro ordinato il sommo sacerdote Ioakim e il consiglio degli anziani di tutto il popolo d'Israele, che si trovava a Gerusalemme."],
[4009,"E ogni Israelita levò il suo grido a Dio con fervida insistenza e tutti si umiliarono con grande zelo."],
[4010,"Essi con le mogli e i bambini, i loro armenti e ogni forestiero e mercenario e i loro schiavi si cinsero di sacco i fianchi."],
[4011,"Ogni uomo o donna israelita e i fanciulli che abitavano a Gerusalemme si prostrarono davanti al tempio e cosparsero il capo di cenere e, vestiti di sacco, alzarono le mani davanti al Signore."],
[4012,"Ricoprirono di sacco anche l'altare e alzarono il loro grido al Dio d'Israele, tutti insieme senza interruzione, supplicando che i loro figli non fossero destinati al bottino, le loro mogli alla schiavitù, le città di loro eredità alla distruzione, il santuario alla profanazione e al ludibrio in mano alle genti."],
[4013,"Il Signore ascoltò il loro grido e volse lo sguardo alla loro tribolazione, mentre il popolo digiunava da molti giorni in tutta la Giudea e a Gerusalemme, davanti al santuario del Signore onnipotente."],
[4014,"Il sommo sacerdote Ioakim e tutti gli altri sacerdoti che stavano davanti al Signore e tutti i ministri del culto divino, con i fianchi cinti di sacco, offrivano l'olocausto perenne, i sacrifici votivi e le offerte spontanee del popolo."],
[4015,"Avevano cosparso di cenere i loro turbanti e invocavano intensamente il Signore, perché provvedesse benignamente a tutta la casa d'Israele."],
[5001,"Frattanto a Oloferne, comandante supremo dell'esercito di Assur, fu riferito che gli Israeliti si preparavano alla guerra e avevano bloccato i valichi montani, avevano costruito fortificazioni sulle cime dei monti e avevano posto ostacoli nelle pianure."],
[5002,"Egli andò su tutte le furie e convocò tutti i capi di Moab e gli strateghi di Ammon e tutti i satrapi delle regioni marittime,"],
[5003,"e disse loro: \"Spiegatemi un po', voi figli di Canaan, che popolo è questo che dimora sui monti e come sono le città che abita, quanti sono gli effettivi del suo esercito, dove risiede la loro forza e il loro vigore, chi si è messo alla loro testa come re e condottiero del loro esercito"],
[5004,"e perché hanno rifiutato di venire incontro a me, a differenza di tutte le popolazioni dell'occidente\"."],
[5005,"Gli rispose Achior, condottiero di tutti gli Ammoniti: \"Ascolti bene il mio signore la risposta dalle labbra del tuo servo: io dirò la verità sul conto di questo popolo, che sta su queste montagne, vicino al luogo ove tu risiedi, né uscirà menzogna dalla bocca del tuo servo."],
[5006,"Questo è un popolo che discende dai Caldei."],
[5007,"Essi dapprima soggiornarono nella Mesopotamia, perché non vollero seguire gli dei dei loro padri che si trovavano nel paese dei Caldei."],
[5008,"Abbandonata la via dei loro antenati, adorarono il Dio del cielo, quel Dio che essi avevano riconosciuto; perciò quelli li scacciarono dalla presenza dei loro dei ed essi fuggirono in Mesopotamia e là soggiornarono per molto tempo."],
[5009,"Ma il loro Dio comandò loro di uscire dal paese che li ospitava e di andare nel paese di Canaan. Qui infatti si stabilirono e si arricchirono di oro e di argento e di molto bestiame."],
[5010,"Poi scesero in Egitto, perché la fame aveva invaso tutto il paese di Canaan, e vi soggiornarono finché trovarono da vivere. Là divennero anche una grande moltitudine, tanto che non si poteva contare la loro discendenza."],
[5011,"Ma contro di loro si levò il re d'Egitto, che con astuzia li costrinse a fabbricare mattoni. Li umiliarono e li trattarono come schiavi."],
[5012,"Essi alzarono suppliche al loro Dio ed egli percosse tutto il paese d'Egitto con piaghe per le quali non c'era rimedio. Perciò gli Egiziani li cacciarono via dal loro cospetto."],
[5013,"Dio prosciugò il Mar Rosso davanti a loro"],
[5014,"e li condusse sulla via del Sinai e di Kades Barne. Essi sgominarono tutti quelli che risiedevano nel deserto,"],
[5015,"dimorarono nel paese degli Amorrei e con la loro potenza sterminarono tutti gli abitanti di Chesbon; quindi, attraversato il Giordano, si impadronirono di tutta la regione montuosa."],
[5016,"Cacciarono lontano da sé il Cananeo, il Perizzita, il Gebuseo, Sichem e tutti i Gergesei, e abitarono nel loro territorio per molti anni."],
[5017,"Finché non peccarono contro il loro Dio erano nella prosperità, perché un Dio che odia il male è in mezzo a loro."],
[5018,"Quando invece si allontanarono dalla via che egli aveva disposto per loro, furono terribilmente sconfitti in molte guerre e condotti prigionieri in paese straniero; il tempio del loro Dio fu raso al suolo e le loro città furono conquistate dai loro nemici."],
[5019,"Ma ora, convertiti al loro Dio, hanno fatto ritorno dai luoghi dove erano stati dispersi, hanno ripreso possesso di Gerusalemme, dove è il loro santuario, e si sono stabiliti sulle montagne, che prima erano deserte."],
[5020,"Ora, mio sovrano e signore, se vi è qualche colpa in questo popolo perché hanno peccato contro il loro Dio, se cioè ci accorgiamo che c'è in loro questo impedimento, avanziamo e diamo loro battaglia."],
[5021,"Se invece non c'è alcuna iniquità nella loro gente, il mio signore passi oltre, perché il loro Signore e il loro Dio non si faccia scudo per loro e noi diveniamo oggetto di scherno davanti a tutta la terra\"."],
[5022,"Quando Achior cessò di pronunciare queste parole, tutta la folla che circondava la tenda e stazionava intorno alzò un mormorio, mentre gli ufficiali di Oloferne e tutti gli abitanti della costa e i Moabiti proponevano di ucciderlo."],
[5023,"\"Non avremo certo paura degli Israeliti - dicevano - perché è un popolo che non possiede né esercito né forze per un valido schieramento."],
[5024,"Dunque avanziamo, ed essi diventeranno un pasto per tutto il tuo esercito, o sovrano Oloferne\"."],
[6001,"Cessata l'agitazione della gente radunata attorno al consiglio militare, parlò Oloferne, comandante supremo dell'esercito di Assur, rivolgendosi ad Achior, alla presenza di tutta quella folla di stranieri, e a tutti i Moabiti:"],
[6002,"\"Chi sei tu, o Achior, e voi, mercenari di Èfraim, per profetare in mezzo a noi come hai fatto oggi e suggerire di non combattere il popolo d'Israele, perché il loro Dio li proteggerà dall'alto? E chi è dio se non Nabucodonosor? Questi manderà il suo esercito e li sterminerà dalla faccia della terra, né il loro Dio potrà liberarli."],
[6003,"Saremo noi suoi servi a spazzarli via come un sol uomo, perché non potranno sostenere l'impeto dei nostri cavalli."],
[6004,"Li bruceremo in casa loro, i loro monti si inebrieranno del loro sangue, i loro campi si colmeranno dei loro cadaveri, né potrà resistere la pianta dei loro piedi davanti a noi, ma saranno completamente distrutti. Questo dice Nabucodonosor, il signore di tutta la terra: così ha parlato e le sue parole non potranno essere smentite."],
[6005,"Quanto a te, Achior, mercenario di Ammon, che hai pronunciato queste parole nel giorno della tua sventura, non vedrai più la mia faccia, da oggi fino a quando farò vendetta di questa razza che viene dall'Egitto."],
[6006,"Allora il ferro dei miei soldati e la numerosa schiera dei miei ministri trapasserà i tuoi fianchi, e tu cadrai fra i loro cadaveri quando io tornerò a vederti."],
[6007,"I miei servi ora ti esporranno sulla montagna e ti lasceranno in una delle città delle alture;"],
[6008,"non morirai finché non sarai sterminato con quella gente."],
[6009,"Ma se in cuor tuo speri davvero che costoro non saranno catturati, non c'è bisogno che il tuo aspetto sia così depresso. Ho parlato: nessuna mia parola andrà a vuoto\"."],
[6010,"Allora Oloferne diede ordine ai suoi servi, che erano di turno nella sua tenda, di prendere Achior, di condurlo vicino a Betulia e di abbandonarlo nelle mani degli Israeliti."],
[6011,"I suoi servi lo presero e lo condussero fuori dell'accampamento verso la pianura, poi dalla pianura lo spinsero verso la montagna e arrivarono alle fonti che erano sotto Betulia."],
[6012,"Quando gli uomini della città li scorsero sulla cresta del monte, presero le armi e uscirono dalla città dirigendosi verso la cima del monte. Tutti i frombolieri occuparono la via di accesso e si misero a lanciare pietre su di loro."],
[6013,"Ridiscesi al riparo del monte, legarono Achior e lo abbandonarono, gettandolo a terra alle falde del monte; quindi fecero ritorno dal loro signore."],
[6014,"Scesi dalla loro città, gli Israeliti si avvicinarono a lui, lo slegarono, lo condussero a Betulia e lo presentarono ai capi della loro città,"],
[6015,"che in quel tempo erano Ozia, figlio di Mica, della tribù di Simeone, Cabrì, figlio di Gotoniel, e Carmì, figlio di Melchiel."],
[6016,"Radunarono subito tutti gli anziani della città, e tutti i giovani e le donne accorsero al luogo del raduno. Posero Achior in mezzo a tutto il popolo e Ozia lo interrogò sull'accaduto."],
[6017,"In risposta riferì loro le parole del consiglio militare di Oloferne, tutto il discorso che Oloferne aveva pronunciato in mezzo ai capi degli Assiri e quello che con arroganza aveva detto contro la casa d'Israele."],
[6018,"Allora tutto il popolo si prostrò ad adorare Dio e alzò questa supplica:"],
[6019,"\"Signore, Dio del cielo, guarda la loro superbia, abbi pietà dell'umiliazione della nostra stirpe e guarda benigno in questo giorno il volto di coloro che sono consacrati a te\"."],
[6020,"Poi confortarono Achior e gli rivolsero parole di grande lode."],
[6021,"Ozia, da parte sua, dopo il raduno lo accolse nella sua casa e offrì un banchetto a tutti gli anziani, e per tutta quella notte invocarono l'aiuto del Dio d'Israele."],
[7001,"Il giorno dopo, Oloferne diede ordine a tutto il suo esercito e a tutta la moltitudine di coloro che erano venuti come suoi alleati di mettersi in marcia contro Betulia, di occupare le vie d'accesso alla montagna e di attaccare battaglia contro gli Israeliti."],
[7002,"In quel giorno ogni uomo valido fra loro si mise in marcia. Il loro esercito si componeva di centosettantamila fanti e dodicimila cavalieri, senza contare gli addetti ai servizi e gli altri che erano a piedi con loro, una moltitudine immensa."],
[7003,"Essi si accamparono nella valle vicino a Betulia, oltre la sorgente, allargandosi dalla zona sopra Dotaim fino a Belbaim ed estendendosi da Betulia fino a Kiamon, che è di fronte a Èsdrelon."],
[7004,"Gli Israeliti, quando videro la loro moltitudine, rimasero molto costernati e si dicevano l'un l'altro: \"Ora costoro inghiottiranno la faccia di tutta la terra e neppure i monti più alti né le valli né i colli potranno resistere al loro urto\"."],
[7005,"Ognuno prese la sua armatura e, dopo aver acceso fuochi sulle torri, stettero in guardia tutta quella notte."],
[7006,"Il giorno seguente Oloferne fece uscire tutta la cavalleria contro il fronte degli Israeliti che erano a Betulia,"],
[7007,"controllò le vie di accesso alla loro città, ispezionò le sorgenti d'acqua e le occupò e, dopo avervi posto attorno guarnigioni di uomini armati, fece ritorno tra i suoi."],
[7008,"Allora gli si avvicinarono tutti i capi dei figli di Esaù e tutti i capi del popolo di Moab e gli strateghi della costa e gli dissero:"],
[7009,"\"Il nostro signore voglia ascoltare una parola, per evitare che il tuo esercito vada in rotta."],
[7010,"Questo popolo degli Israeliti non si affida alle sue lance, ma all'altezza dei monti sui quali essi vivono, e certo non è facile arrivare alle cime dei loro monti."],
[7011,"Quindi, signore, non attaccare costoro come si usa nella battaglia campale e così non cadrà un solo uomo del tuo esercito."],
[7012,"Rimani fermo nel tuo accampamento, avendo buona cura di ogni uomo del tuo esercito; invece i tuoi gregari vadano a occupare la sorgente dell'acqua che sgorga alla radice del monte,"],
[7013,"perché di là attingono tutti gli abitanti di Betulia. La sete li farà morire e consegneranno la loro città. Noi e la nostra gente saliremo sulle vicine alture dei monti e ci apposteremo su di esse per sorvegliare che nessuno possa uscire dalla città."],
[7014,"Così cadranno sfiniti dalla fame essi, le loro donne, i loro figli e, prima che la spada arrivi su di loro, saranno stesi sulle piazze fra le loro case."],
[7015,"Avrai così reso loro un terribile contraccambio, perché si sono ribellati e non hanno voluto venire incontro a te con intenzioni pacifiche\"."],
[7016,"Piacque questo discorso a Oloferne e a tutti i suoi ministri e diede ordine che si facesse come avevano proposto."],
[7017,"Si mosse quindi un distaccamento di Ammoniti e con essi cinquemila Assiri si accamparono nella vallata e occuparono gli acquedotti e le sorgenti d'acqua degli Israeliti."],
[7018,"A loro volta i figli di Esaù e gli Ammoniti salirono e si appostarono sulla montagna di fronte a Dotaim. Spinsero altri loro uomini a meridione e a oriente di fronte a Egrebel, che si trova vicino a Cus, nei pressi del torrente Mocmur. Il resto dell'esercito degli Assiri si accampò nella pianura, ricoprendo tutta l'estensione del terreno. Le tende e gli equipaggiamenti costituivano una massa imponente, perché in realtà essi erano una turba immensa."],
[7019,"Allora gli Israeliti alzarono suppliche al Signore, loro Dio, con l'animo in preda all'abbattimento, perché da ogni parte i nemici li avevano circondati e non c'era via di scampo."],
[7020,"Il campo degli Assiri al completo, fanti, carri e cavalieri, rimase fermo tutt'intorno per trentaquattro giorni e venne a mancare a tutti gli abitanti di Betulia ogni riserva d'acqua."],
[7021,"Anche le cisterne erano vuote e non potevano più bere a sazietà neppure per un giorno, perché davano da bere in quantità razionata."],
[7022,"Incominciarono a cadere sfiniti i loro bambini; le donne e i giovani venivano meno per la sete e cadevano nelle piazze della città e nei passaggi delle porte, e ormai non rimaneva più in loro alcuna energia."],
[7023,"Allora tutto il popolo si radunò intorno a Ozia e ai capi della città, con giovani, donne e fanciulli, e alzando grida dissero davanti a tutti gli anziani:"],
[7024,"\"Sia giudice il Signore tra voi e noi, perché voi ci avete recato un grave danno rifiutando di proporre la pace agli Assiri."],
[7025,"Ora non c'è più nessuno che ci possa aiutare, perché Dio ci ha venduti nelle loro mani per essere abbattuti davanti a loro dalla sete e da terribili mali."],
[7026,"Ormai chiamateli e consegnate l'intera città al popolo di Oloferne e a tutto il suo esercito perché la saccheggino."],
[7027,"È meglio per noi essere loro preda; diventeremo certo loro schiavi, ma almeno avremo salva la vita e non vedremo con i nostri occhi la morte dei nostri bambini, né le donne e i nostri figli esalare l'ultimo respiro."],
[7028,"Chiamiamo a testimone contro di voi il cielo e la terra e il nostro Dio, il Signore dei nostri padri, che ci punisce per la nostra iniquità e per le colpe dei nostri padri, perché non ci lasci più in una situazione come quella in cui siamo oggi\"."],
[7029,"Vi fu allora un pianto generale in mezzo all'assemblea e a gran voce gridarono suppliche al Signore Dio."],
[7030,"Ozia rispose loro: \"Coraggio, fratelli, resistiamo ancora cinque giorni e in questo tempo il Signore, nostro Dio, rivolgerà di nuovo la sua misericordia su di noi; non è possibile che egli ci abbandoni fino all'ultimo."],
[7031,"Ma se proprio passeranno questi giorni e non ci arriverà alcun aiuto, farò come avete detto voi\"."],
[7032,"Così rimandò il popolo, ciascuno al proprio posto di difesa, ed essi tornarono sulle mura e sulle torri della città e rimandarono le donne e i figli alle loro case; ma tutti nella città erano in grande costernazione."],
[8001,"In quei giorni Giuditta venne a conoscenza di questi fatti. Era figlia di Merarì, figlio di Os, figlio di Giuseppe, figlio di Oziel, figlio di Chelkia, figlio di Anania, figlio di Gedeone, figlio di Rafain, figlio di Achitob, figlio di Elia, figlio di Chelkia, figlio di Eliab, figlio di Natanael, figlio di Salamiel, figlio di Sarasadai, figlio di Israele."],
[8002,"Suo marito era stato Manasse, della stessa tribù e famiglia di lei; egli era morto al tempo della mietitura dell'orzo."],
[8003,"Mentre stava sorvegliando quelli che legavano i covoni nella campagna, fu colpito da insolazione. Dovette mettersi a letto e morì a Betulia, sua città, e lo seppellirono insieme ai suoi padri nel campo che sta tra Dotaim e Balamon."],
[8004,"Giuditta era rimasta nella sua casa in stato di vedovanza ed erano passati già tre anni e quattro mesi."],
[8005,"Si era fatta preparare una tenda sul terrazzo della sua casa, si era cinta i fianchi di sacco e portava le vesti della sua vedovanza."],
[8006,"Da quando era vedova digiunava tutti i giorni, eccetto le vigilie dei sabati e i sabati, le vigilie dei noviluni e i noviluni, le feste e i giorni di gioia per Israele."],
[8007,"Era bella d'aspetto e molto avvenente nella persona; inoltre suo marito Manasse le aveva lasciato oro e argento, schiavi e schiave, armenti e terreni che ora continuava ad amministrare."],
[8008,"Né alcuno poteva dire una parola maligna a suo riguardo, perché aveva grande timore di Dio."],
[8009,"Venne dunque a conoscenza delle parole esasperate che il popolo aveva rivolto al capo della città, perché erano demoralizzati a causa della mancanza d'acqua, e Giuditta seppe anche di tutte le risposte che aveva dato loro Ozia e come avesse giurato loro di consegnare la città agli Assiri dopo cinque giorni."],
[8010,"Subito mandò la sua ancella che aveva in cura tutte le sue sostanze a chiamare Cabrì e Carmì, che erano gli anziani della sua città."],
[8011,"Vennero da lei ed ella disse loro: \"Ascoltatemi, capi dei cittadini di Betulia. Non è un discorso giusto quello che oggi avete tenuto al popolo, e quel giuramento che avete pronunciato e interposto tra voi e Dio, di mettere la città in mano ai nostri nemici, se nel frattempo il Signore non verrà in vostro aiuto."],
[8012,"Chi siete voi dunque che avete tentato Dio in questo giorno e vi siete posti al di sopra di lui in mezzo ai figli degli uomini?"],
[8013,"Certo, voi volete mettere alla prova il Signore onnipotente, ma non comprenderete niente, né ora né mai."],
[8014,"Se non siete capaci di scrutare il profondo del cuore dell'uomo né di afferrare i pensieri della sua mente, come potrete scrutare il Signore, che ha fatto tutte queste cose, e conoscere i suoi pensieri e comprendere i suoi disegni? No, fratelli, non provocate l'ira del Signore, nostro Dio."],
[8015,"Se non vorrà aiutarci in questi cinque giorni, egli ha pieno potere di difenderci nei giorni che vuole o anche di farci distruggere dai nostri nemici."],
[8016,"E voi non pretendete di ipotecare i piani del Signore, nostro Dio, perché Dio non è come un uomo a cui si possano fare minacce, né un figlio d'uomo su cui si possano esercitare pressioni."],
[8017,"Perciò attendiamo fiduciosi la salvezza che viene da lui, supplichiamolo che venga in nostro aiuto e ascolterà il nostro grido, se a lui piacerà."],
[8018,"In realtà in questa nostra generazione non c'è mai stata né esiste oggi una tribù o famiglia o popolo o città tra noi, che adori gli dei fatti da mano d'uomo, come è avvenuto nei tempi passati,"],
[8019,"ed è per questo che i nostri padri furono abbandonati alla spada e alla devastazione e caddero rovinosamente davanti ai loro nemici."],
[8020,"Noi invece non riconosciamo altro Dio fuori di lui, e per questo speriamo che egli non trascurerà noi e neppure la nostra nazione."],
[8021,"Perché se noi saremo presi, resterà presa anche tutta la Giudea e saranno saccheggiate le nostre cose sante e Dio ci chiederà conto col nostro sangue di quella profanazione."],
[8022,"L'uccisione dei nostri fratelli, l'asservimento della patria, la devastazione della nostra eredità Dio le farà ricadere sul nostro capo in mezzo ai popoli tra i quali saremo schiavi, e saremo così motivo di scandalo e di disprezzo di fronte ai nostri padroni."],
[8023,"La nostra schiavitù non ci procurerà alcun favore; il Signore, nostro Dio, la volgerà a nostro disonore."],
[8024,"Dunque, fratelli, dimostriamo ai nostri fratelli che la loro vita dipende da noi, che le nostre cose sante, il tempio e l'altare, poggiano su di noi."],
[8025,"Per tutti questi motivi ringraziamo il Signore, nostro Dio, che ci mette alla prova, come ha già fatto con i nostri padri."],
[8026,"Ricordatevi quanto ha fatto con Abramo, quali prove ha fatto passare a Isacco e quanto è avvenuto a Giacobbe in Mesopotamia di Siria, quando pascolava le greggi di Labano, suo zio materno."],
[8027,"Certo, come ha passato al crogiuolo costoro con il solo scopo di saggiare il loro cuore, così ora non vuol fare vendetta di noi, ma è a scopo di correzione che il Signore castiga quelli che gli stanno vicino\"."],
[8028,"Allora Ozia le rispose: \"Quello che hai detto, l'hai proferito con cuore retto e nessuno può contraddire alle tue parole."],
[8029,"Non da oggi infatti è manifesta la tua saggezza, ma dall'inizio dei tuoi giorni tutto il popolo conosce la tua prudenza, come pure l'ottima indole del tuo cuore."],
[8030,"Però il popolo sta soffrendo duramente la sete e ci ha costretti a comportarci come avevamo detto loro e a impegnarci in un giuramento che non potremo trasgredire."],
[8031,"Piuttosto prega per noi, tu che sei donna pia, e il Signore invierà la pioggia a riempire le nostre cisterne e così non moriremo di sete\"."],
[8032,"Giuditta rispose loro: \"Ascoltatemi! Voglio compiere un'impresa che verrà ricordata di generazione in generazione ai figli del nostro popolo."],
[8033,"Voi starete di guardia alla porta della città questa notte; io uscirò con la mia ancella ed entro quei giorni, dopo i quali avete deciso di consegnare la città ai nostri nemici, il Signore per mano mia salverà Israele."],
[8034,"Voi però non fate domande sul mio progetto: non vi dirò nulla finché non sarà compiuto ciò che sto per fare\"."],
[8035,"Le risposero Ozia e i capi: \"Va' in pace e il Signore Dio sia con te per far vendetta dei nostri nemici\"."],
[8036,"Se ne andarono quindi dalla sua tenda e si recarono ai loro posti."],
[9001,"Allora Giuditta cadde con la faccia a terra, sparse cenere sul capo, mise allo scoperto il cilicio di cui era rivestita e, nell'ora in cui nel tempio di Dio a Gerusalemme veniva offerto l'incenso della sera, supplicò a gran voce il Signore:"],
[9002,"\"Signore, Dio del padre mio Simeone, tu hai messo nella sua mano una spada per fare vendetta degli stranieri, che avevano sciolto la cintura d'una vergine per contaminarla, ne avevano denudato i fianchi a sua vergogna e ne avevano contaminato il grembo per disonorarla. Tu avevi detto: \"Questo non si deve fare!\". Ma essi l'hanno fatto."],
[9003,"Per questo hai consegnato alla morte i loro capi e quel giaciglio, usato con l'inganno, con l'inganno fu bagnato del loro sangue; hai abbattuto gli schiavi insieme ai loro capi e i capi sui loro troni."],
[9004,"Hai destinato le loro mogli alla preda, le loro figlie alla schiavitù, tutte le loro spoglie alla divisione tra i figli da te prediletti, perché costoro, accesi del tuo zelo, erano rimasti inorriditi della profanazione del loro sangue e ti avevano chiamato in aiuto. O Dio, mio Dio, ascolta anche me che sono vedova."],
[9005,"Tu hai fatto ciò che precedette quelle vicende, le vicende stesse e ciò che seguì. Tu hai stabilito le cose presenti e le future e quello che tu hai progettato si è compiuto."],
[9006,"Le cose da te deliberate si sono presentate e hanno detto: \"Eccoci!\". Perché tutte le tue vie sono preparate in anticipo e i tuoi giudizi sono preordinati."],
[9007,"Ecco, infatti, gli Assiri si sono esaltati nella loro potenza, vanno in superbia per i loro cavalli e i cavalieri, si vantano della forza dei loro fanti, poggiano la loro speranza sugli scudi e sulle lance, sugli archi e sulle fionde, e non sanno che tu sei il Signore, che stronchi le guerre."],
[9008,"Signore è il tuo nome. Abbatti la loro forza con la tua potenza e rovescia la loro violenza con la tua ira: hanno deciso di profanare il tuo santuario, di contaminare la Dimora dove riposa il tuo nome glorioso, di abbattere con il ferro i corni del tuo altare."],
[9009,"Guarda la loro superbia, fa' scendere la tua ira sulle loro teste, metti nella mia mano di vedova la forza di fare quello che ho pensato."],
[9010,"Con la lusinga delle mie labbra abbatti lo schiavo con il suo padrone e il padrone con il suo servo; spezza la loro alterigia per mezzo di una donna."],
[9011,"La tua forza, infatti, non sta nel numero, né sui forti si regge il tuo regno: tu sei invece il Dio degli umili, sei il soccorritore dei piccoli, il rifugio dei deboli, il protettore degli sfiduciati, il salvatore dei disperati."],
[9012,"Sì, sì, Dio di mio padre, Dio dell'eredità d'Israele, Signore dei cieli e della terra, creatore delle acque, re di tutte le tue creature, ascolta la mia preghiera!"],
[9013,"Fa' che la mia parola lusinghiera diventi piaga e flagello di costoro, che fanno progetti crudeli contro la tua alleanza e il tuo tempio consacrato, contro la vetta di Sion e la sede dei tuoi figli."],
[9014,"Da' a tutto il tuo popolo e a ogni tribù la prova che sei tu il Signore, il Dio di ogni potere e di ogni forza, e non c'è altri, all'infuori di te, che possa proteggere la stirpe d'Israele\"."],
[10001,"Quando Giuditta ebbe cessato di supplicare il Dio d'Israele ed ebbe terminato di pronunciare tutte queste parole,"],
[10002,"si alzò da terra, chiamò la sua ancella e scese nella casa dove usava passare i giorni dei sabati e le feste."],
[10003,"Qui si tolse il cilicio di cui era rivestita, depose le vesti della sua vedovanza, si lavò il corpo con acqua e lo unse con profumo denso; spartì i capelli del capo e vi impose il diadema. Poi indossò gli abiti da festa, che aveva usato quando era vivo suo marito Manasse."],
[10004,"Si mise i sandali ai piedi, cinse le collane e infilò i braccialetti, gli anelli e gli orecchini e ogni altro ornamento che aveva e si rese molto bella, tanto da sedurre qualunque uomo l'avesse vista."],
[10005,"Poi affidò alla sua ancella un otre di vino e un'ampolla d'olio; riempì anche una bisaccia di farina tostata, di fichi secchi e di pani puri e, fatto un involto di tutte queste provviste, glielo mise sulle spalle."],
[10006,"Allora uscirono verso la porta della città di Betulia e trovarono lì presenti Ozia e gli anziani della città, Cabrì e Carmì."],
[10007,"Costoro, quando la videro trasformata nell'aspetto e con gli abiti mutati, rimasero molto ammirati della sua bellezza e le dissero:"],
[10008,"\"Il Dio dei padri nostri ti conceda di trovar favore e di portare a termine quello che hai stabilito di fare, a gloria degli Israeliti e ad esaltazione di Gerusalemme\"."],
[10009,"Essa si chinò ad adorare Dio e rispose loro: \"Fatemi aprire la porta della città e io uscirò per dare compimento alle parole che mi avete rivolto\". Quelli diedero ordine ai giovani di guardia di aprirle come aveva chiesto."],
[10010,"Così fecero e Giuditta uscì: lei sola e l'ancella che aveva con sé. Dalla città gli uomini la seguirono con gli sguardi mentre scendeva dal monte, finché attraversò la vallata e non poterono più scorgerla."],
[10011,"Esse andavano avanti diritte per la valle, quando si fecero loro incontro le sentinelle assire."],
[10012,"La fermarono e la interrogarono: \"Di quale popolo sei, da dove vieni e dove vai?\". Rispose: \"Sono figlia degli Ebrei e fuggo da loro, perché stanno per esservi consegnati per essere divorati."],
[10013,"Io quindi vengo alla presenza di Oloferne, comandante supremo dei vostri eserciti, per dargli delle informazioni sicure e mettergli sotto gli occhi la strada per cui potrà passare e impadronirsi di tutti questi monti senza che perisca uno solo dei suoi uomini\"."],
[10014,"Quegli uomini, quando sentirono queste parole e considerarono l'aspetto di lei, che appariva loro come un miracolo di bellezza, le dissero:"],
[10015,"\"Hai messo in salvo la tua vita, affrettandoti a scendere alla presenza del nostro signore. Vieni dunque alla tenda di lui; alcuni di noi ti accompagneranno, finché non ti abbiano affidato alle sue mani."],
[10016,"Quando poi sarai alla sua presenza, non temere in cuor tuo, ma riferisci a lui quanto ci hai detto ed egli ti tratterà bene\"."],
[10017,"Scelsero pertanto cento uomini tra loro, i quali si affiancarono a lei e alla sua ancella e le condussero alla tenda di Oloferne."],
[10018,"In tutto il campo ci fu un grande accorrere, essendosi sparsa la voce del suo arrivo tra gli attendamenti. Una volta sopraggiunti, la circondarono in massa mentre era fuori della tenda di Oloferne, in attesa di essere annunciata a lui."],
[10019,"Erano ammirati della sua bellezza e ammirati degli Israeliti a causa di lei e si dicevano l'un l'altro: \"Chi disprezzerà un popolo che possiede tali donne? Sarà bene non lasciarne sopravvivere neppure uno, perché se fossero risparmiati sarebbero capaci di ingannare tutto il mondo\"."],
[10020,"Vennero fuori le guardie del corpo di Oloferne e tutti gli ufficiali e la introdussero nella sua tenda."],
[10021,"Oloferne era adagiato sul suo letto, che era posto dentro una cortina intessuta di porpora ricamata d'oro, di smeraldo e di pietre preziose."],
[10022,"Gli annunciarono la presenza di lei ed egli uscì sull'ingresso della tenda, preceduto da fiaccole d'argento."],
[10023,"Quando Giuditta avanzò alla presenza di lui e dei suoi ufficiali, tutti stupirono per la bellezza del suo aspetto. Ella si prostrò con la faccia a terra per riverirlo, ma i servi la fecero rialzare."],
[11001,"Allora Oloferne le disse: \"Sta' tranquilla, o donna, non temere in cuor tuo, perché io non ho mai fatto male a nessuno che abbia accettato di servire Nabucodonosor, re di tutta la terra."],
[11002,"Quanto al tuo popolo che abita su questi monti, se non mi avesse disprezzato, non avrei levato la lancia contro di loro; ma da se stessi si sono procurati tutto questo."],
[11003,"E ora dimmi per quale motivo sei fuggita da loro e sei venuta da noi. Certamente sei venuta per trovare salvezza. Fatti animo: resterai viva questa notte e in avvenire."],
[11004,"Nessuno ti farà torto, ma sarai trattata bene, come si fa con i servi del mio signore, il re Nabucodonosor\"."],
[11005,"Giuditta gli rispose: \"Accogli le parole della tua serva e possa la tua ancella parlare alla tua presenza. Io non dirò il falso al mio signore in questa notte."],
[11006,"Certo, se vorrai seguire le parole della tua ancella, Dio condurrà a buon fine la tua impresa, e il mio signore non fallirà nei suoi progetti."],
[11007,"Viva Nabucodonosor, re di tutta la terra, e viva la potenza di colui che ti ha inviato a rimettere sul giusto cammino ogni essere vivente; per mezzo tuo infatti non solo gli uomini lo servono, ma in grazia della tua forza anche le bestie selvatiche, gli armenti e gli uccelli del cielo vivranno per Nabucodonosor e tutta la sua casa."],
[11008,"Abbiamo già conosciuto per fama la tua saggezza e l'abilità del tuo genio, ed è risaputo in tutta la terra che tu sei il migliore in tutto il regno, eccellente nel sapere e meraviglioso nelle imprese militari."],
[11009,"Circa il discorso tenuto da Achior nel tuo consiglio, noi ne abbiamo udito il contenuto, perché gli uomini di Betulia l'hanno risparmiato ed egli ha rivelato loro quanto aveva detto davanti a te."],
[11010,"Perciò, signore sovrano, non trascurare le sue parole, ma conservale nel tuo cuore perché sono vere: realmente il nostro popolo non è punito e la spada non prevale contro di esso se non quando ha peccato contro il suo Dio."],
[11011,"Ora, perché il mio signore non venga sconfitto senza poter fare nulla, la morte si avventerà contro di loro: infatti si è impossessato di loro il peccato, con il quale provocano l'ira del loro Dio ogni volta che compiono ciò che non è lecito fare."],
[11012,"Siccome sono venuti a mancare loro i viveri e tutta l'acqua è stata consumata, hanno deciso di mettere le mani sul loro bestiame e hanno deliberato di cibarsi di quello che Dio con le sue leggi ha vietato loro di mangiare."],
[11013,"Hanno perfino decretato di dare fondo alle primizie del frumento e alle decime del vino e dell'olio, che conservavano come diritto sacro dei sacerdoti che stanno a Gerusalemme e prestano servizio alla presenza del nostro Dio: tutte cose che a nessuno del popolo era permesso neppure toccare con la mano."],
[11014,"Perciò hanno mandato a Gerusalemme, dove anche quelli che vi risiedono hanno fatto altrettanto, dei messaggeri incaricati di portare loro il permesso da parte del consiglio degli anziani."],
[11015,"Ma, quando riceveranno la risposta e la eseguiranno, in quel giorno saranno consegnati in tuo potere per l'estrema rovina."],
[11016,"Per questo io, tua serva, consapevole di tutte queste cose, sono fuggita da loro e Dio mi ha mandato a compiere con te un'impresa che farà stupire tutta la terra, quanti ne sentiranno parlare."],
[11017,"La tua serva teme Dio e serve notte e giorno il Dio del cielo. Ora io rimarrò presso di te, mio signore, ma di notte la tua serva uscirà nella valle; io pregherò il mio Dio ed egli mi rivelerà quando essi avranno commesso i loro peccati."],
[11018,"Allora verrò a riferirti e tu uscirai con tutto l'esercito e nessuno di loro potrà opporti resistenza."],
[11019,"Io ti guiderò attraverso la Giudea, finché giungerò davanti a Gerusalemme e in mezzo vi porrò il tuo seggio. Tu li condurrai via come pecore senza pastore e nemmeno un cane abbaierà davanti a te. Queste cose mi sono state dette secondo la mia preveggenza, mi sono state annunciate e ho ricevuto l'incarico di comunicarle a te\"."],
[11020,"Le parole di lei piacquero a Oloferne e ai suoi ufficiali, i quali tutti ammirarono la sua sapienza e dissero:"],
[11021,"\"Da un capo all'altro della terra non esiste donna simile, per la bellezza dell'aspetto e la saggezza delle parole\"."],
[11022,"E Oloferne le disse: \"Bene ha fatto Dio a mandarti avanti al tuo popolo, perché la forza resti nelle nostre mani e coloro che hanno disprezzato il mio signore vadano in rovina."],
[11023,"Tu sei graziosa d'aspetto e abile nelle tue parole; se farai come hai detto, il tuo Dio sarà il mio Dio e tu dimorerai nel palazzo del re Nabucodonosor e sarai famosa in tutto il mondo\"."],
[12001,"Poi Oloferne ordinò che la conducessero dove erano riposte le sue argenterie e prescrisse pure che le dessero da mangiare dei suoi cibi e le dessero da bere del suo vino."],
[12002,"Ma disse Giuditta: \"Io non toccherò questi cibi, perché non me ne derivi un'occasione di caduta, ma mi saranno serviti quelli che ho portato con me\"."],
[12003,"Oloferne le disse: \"Quando verrà a mancare quello che hai con te, dove ci riforniremo di cibi simili per darteli? In mezzo a noi non c'è nessuno della tua gente\"."],
[12004,"Giuditta gli rispose: \"Per la tua vita, mio signore, ti assicuro che io, tua serva, non finirò le riserve che ho con me, prima che il Signore abbia compiuto per mano mia quello che ha stabilito\"."],
[12005,"Poi gli ufficiali di Oloferne la condussero alla tenda ed ella dormì fino a mezzanotte; poi si alzò all'alba, al cambio della guardia del mattino."],
[12006,"Mandò a dire a Oloferne: \"Comandi il mio signore che lascino uscire la tua serva per la preghiera\"."],
[12007,"Oloferne ordinò alle guardie del corpo di non impedirla.  Rimase così al campo tre giorni: usciva di notte nella valle di Betulia e si lavava nella zona dell'accampamento alla sorgente d'acqua."],
[12008,"Quando risaliva, pregava il Signore, Dio d'Israele, di dirigere la sua impresa per rialzare le sorti dei figli del suo popolo."],
[12009,"Rientrando purificata, rimaneva nella sua tenda, finché verso sera non le si portava il cibo."],
[12010,"Ed ecco, al quarto giorno, Oloferne fece preparare un banchetto riservato ai suoi servi, senza invitare nessuno dei suoi funzionari."],
[12011,"Disse a Bagoa, l'eunuco sovrintendente a tutti i suoi affari: \"Va' e persuadi la donna ebrea che è presso di te a venire con noi, per mangiare e bere con noi."],
[12012,"Sarebbe disonorevole per la nostra reputazione trascurare una donna simile senza godere della sua compagnia; perché se non la corteggiamo, si farà beffe di noi\"."],
[12013,"Bagoa, uscito dalla presenza di Oloferne, andò da lei e disse: \"Non esiti questa bella fanciulla a venire dal mio signore, per essere onorata alla sua presenza e bere con noi il vino in allegria e diventare oggi come una delle donne assire, che stanno nel palazzo di Nabucodonosor\"."],
[12014,"Giuditta gli rispose: \"Chi sono io per contraddire il mio signore? Quanto sarà gradito ai suoi occhi, mi affretterò a compierlo e sarà per me motivo di gioia fino al giorno della mia morte\"."],
[12015,"Subito si alzò e si adornò delle vesti e d'ogni altro ornamento femminile; la sua ancella l'aveva preceduta e aveva steso a terra per lei davanti ad Oloferne le pellicce che aveva avuto da Bagoa per suo uso quotidiano, per adagiarvisi sopra e prendere cibo."],
[12016,"Giuditta entrò e si distese. Il cuore di Oloferne ne rimase incantato, si turbò il suo spirito e molto intenso era il suo desiderio di unirsi a lei: dal giorno in cui l'aveva vista, cercava l'occasione di sedurla."],
[12017,"Le disse pertanto Oloferne: \"Bevi e divertiti con noi\"."],
[12018,"Giuditta rispose: \"Sì, signore, berrò perché sento che la mia vita è oggi onorata come non mai dal giorno della mia nascita\"."],
[12019,"Incominciò quindi a mangiare e a bere davanti a lui ciò che le aveva preparato l'ancella."],
[12020,"Oloferne si deliziò della presenza di lei e bevve abbondantemente tanto vino quanto non ne aveva mai bevuto in un solo giorno da quando era al mondo."],
[13001,"Quando si fece buio, i suoi servi si affrettarono a ritirarsi. Bagoa chiuse la tenda dall'esterno e allontanò le guardie dalla vista del suo signore e ognuno andò a dormire; in realtà erano tutti estenuati, perché avevano bevuto troppo."],
[13002,"Giuditta fu lasciata nella tenda e Oloferne era sprofondato sul suo letto, ubriaco fradicio."],
[13003,"Allora Giuditta ordinò all'ancella di stare fuori della camera da letto e di aspettare che uscisse, come aveva fatto ogni giorno; aveva detto infatti che sarebbe uscita per la sua preghiera, e anche con Bagoa aveva parlato in questi termini."],
[13004,"Si erano allontanati tutti dalla loro presenza e nessuno, dal più piccolo al più grande, era rimasto nella camera da letto. Giuditta, fermatasi presso il letto di lui, disse in cuor suo: \"Signore, Dio d'ogni potenza, guarda propizio in quest'ora all'opera delle mie mani per l'esaltazione di Gerusalemme."],
[13005,"È venuto il momento di pensare alla tua eredità e di far riuscire il mio progetto per la rovina dei nemici che sono insorti contro di noi\"."],
[13006,"Avvicinatasi alla sponda del letto che era dalla parte del capo di Oloferne, staccò la scimitarra di lui;"],
[13007,"poi, accostatasi al letto, afferrò la testa di lui per la chioma e disse: \"Dammi forza, Signore, Dio d'Israele, in questo giorno\"."],
[13008,"E con tutta la sua forza lo colpì due volte al collo e gli staccò la testa."],
[13009,"Indi fece rotolare il corpo giù dal giaciglio e strappò via la cortina dai sostegni. Poco dopo uscì e consegnò la testa di Oloferne alla sua ancella,"],
[13010,"la quale la mise nella bisaccia dei viveri e uscirono tutt'e due, secondo il loro uso, per la preghiera. Attraversato l'accampamento, fecero il giro della valle, salirono il monte di Betulia e arrivarono alle sue porte."],
[13011,"Giuditta gridò da lontano al corpo di guardia delle porte: \"Aprite, aprite subito la porta: è con noi Dio, il nostro Dio, per esercitare ancora la sua forza in Israele e la sua potenza contro i nemici, come ha fatto oggi\"."],
[13012,"Appena gli uomini della sua città sentirono la sua voce, corsero giù in fretta alla porta della città e chiamarono gli anziani."],
[13013,"Corsero tutti, dal più piccolo al più grande, perché non si aspettavano il suo arrivo; aprirono dunque la porta, le accolsero dentro e, acceso il fuoco per fare luce, si strinsero attorno a loro."],
[13014,"Giuditta disse loro a gran voce: \"Lodate Dio, lodatelo; lodate Dio, perché non ha allontanato la sua misericordia dalla casa d'Israele, ma in questa notte per mano mia ha colpito i nostri nemici\"."],
[13015,"Allora tirò fuori la testa dalla bisaccia e la mise in mostra dicendo loro: \"Ecco la testa di Oloferne, comandante supremo dell'esercito assiro, ed ecco la cortina sotto la quale giaceva ubriaco; il Signore l'ha colpito per mano di una donna."],
[13016,"Viva dunque il Signore, che mi ha protetto nella mia impresa, perché costui si è lasciato ingannare dal mio volto a sua rovina, ma non ha commesso peccato con me, a mia contaminazione e vergogna\"."],
[13017,"Tutto il popolo si stupì profondamente e tutti si chinarono ad adorare Dio, esclamando in coro: \"Benedetto sei tu, nostro Dio, che hai annientato in questo giorno i nemici del tuo popolo\"."],
[13018,"Ozia a sua volta le disse: \"Benedetta sei tu, figlia, davanti al Dio altissimo più di tutte le donne che vivono sulla terra, e benedetto il Signore Dio che ha creato il cielo e la terra e ti ha guidato a troncare la testa del capo dei nostri nemici."],
[13019,"Davvero il coraggio che ti ha sostenuto non sarà dimenticato dagli uomini, che ricorderanno per sempre la potenza di Dio."],
[13020,"Dio compia per te queste cose a tua perenne esaltazione, ricolmandoti di beni, in riconoscimento della prontezza con cui hai esposto la vita di fronte all'umiliazione della nostra stirpe, e ti sei opposta alla nostra rovina, comportandoti rettamente davanti al nostro Dio\". E tutto il popolo esclamò: \"Amen! Amen!\"."],
[14001,"Giuditta rispose loro: \"Ascoltatemi, fratelli: prendete questa testa e appendetela sugli spalti delle vostre mura."],
[14002,"Quando apparirà la luce del mattino e il sole sorgerà sulla terra, prenderete ciascuno le vostre armature da guerra e ogni uomo valido uscirà dalla città. Quindi date inizio all'azione contro di loro come se voleste scendere in pianura contro le prime difese degli Assiri, ma non scenderete."],
[14003,"Quelli prenderanno le loro armi e correranno nel loro accampamento a svegliare i capi dell'esercito assiro. Poi si raduneranno insieme davanti alla tenda di Oloferne, ma non lo troveranno e così si lasceranno prendere dal terrore e fuggiranno davanti a voi."],
[14004,"Allora inseguiteli voi e quanti abitano l'intero territorio d'Israele e abbatteteli nella loro fuga."],
[14005,"Ma, prima di far questo, chiamatemi Achior l'Ammonita, perché venga a vedere e riconoscere colui che ha disprezzato la casa d'Israele e che lo ha inviato qui tra noi come per destinarlo alla morte\"."],
[14006,"Chiamarono subito Achior dalla casa di Ozia ed egli, appena giunse e vide la testa di Oloferne in mano ad un uomo in mezzo al popolo radunato, cadde a terra e rimase senza respiro."],
[14007,"Quando l'ebbero sollevato, si gettò ai piedi di Giuditta pieno di riverenza per la sua persona e disse: \"Benedetta sei tu in ogni tenda di Giuda e tra tutti i popoli: quanti udranno il tuo nome saranno presi da terrore."],
[14008,"Ed ora raccontami tutto quello che hai fatto in questi giorni\". E Giuditta in mezzo al popolo gli narrò quanto aveva compiuto dal giorno in cui era partita fino al momento in cui parlava loro."],
[14009,"Quando finì di parlare, il popolo scoppiò in alte grida di giubilo e riempì la città di voci festose."],
[14010,"Allora Achior, vedendo quello che il Dio d'Israele aveva fatto, credette fermamente in Dio, si fece circoncidere e fu accolto nella casa d'Israele fino ad oggi."],
[14011,"Quando spuntò il mattino, appesero la testa di Oloferne alle mura; poi ogni uomo prese le sue armi e scesero lungo i sentieri del monte, divisi in manipoli."],
[14012,"Appena li videro, gli Assiri mandarono a informare i loro capi e questi corsero dagli strateghi, dai chiliarchi e da tutti i loro comandanti."],
[14013,"Poi si radunarono davanti alla tenda di Oloferne e dissero al suo attendente: \"Sveglia il nostro signore, perché quegli schiavi hanno osato scendere per darci battaglia e così distruggerci completamente\"."],
[14014,"Bagoa entrò e bussò alla parete della tenda, poiché pensava che egli dormisse con Giuditta."],
[14015,"Ma siccome nessuno rispondeva, aprì ed entrò nella camera da letto e lo trovò morto, steso a terra vicino all'ingresso, con la testa tagliata via dal tronco."],
[14016,"Allora diede in alte grida di dolore e di lamento, urlando con tutte le forze e stracciandosi le vesti."],
[14017,"Poi si precipitò nella tenda dove era alloggiata Giuditta e non la trovò. Allora corse fuori davanti al popolo e gridò:"],
[14018,"\"Gli schiavi ci hanno traditi! Una sola donna ebrea ha gettato la vergogna sulla casa del re Nabucodonosor! Oloferne eccolo a terra, ed è privo della testa\"."],
[14019,"I comandanti dell'esercito assiro, appena udirono questo annuncio, si stracciarono i mantelli e rimasero terribilmente sconvolti nel loro animo; entro l'accampamento si elevarono altissime le loro grida e le urla di dolore."],
[15001,"Tutti quelli che erano nelle tende, appena seppero dell'accaduto, restarono allibiti"],
[15002,"e furono presi da paura e terrore, e nessuno volle più restare a fianco dell'altro, ma tutti insieme, disperdendosi, fuggivano per ogni sentiero della pianura e della montagna."],
[15003,"Anche quelli accampati sulle montagne intorno a Betulia si diedero alla fuga. A questo punto gli Israeliti, cioè quanti tra loro erano abili alle armi, si buttarono su di loro."],
[15004,"Ozia mandò subito a Betomestaim, a Bebai, a Coba, a Cola e in tutti i territori d'Israele messaggeri ad annunciare l'accaduto e a invitare tutti a gettarsi sui nemici per sterminarli."],
[15005,"Appena gli Israeliti udirono ciò, tutti compatti piombarono su di loro e li fecero a pezzi arrivando fino a Coba. Scesero in campo anche quelli di Gerusalemme e di tutta la zona montuosa, perché anche a loro avevano riferito quello che era accaduto nell'accampamento dei loro nemici. Quelli che abitavano in Galaad e nella Galilea li accerchiarono colpendoli terribilmente, finché giunsero a Damasco e nel suo territorio."],
[15006,"Gli altri che erano rimasti a Betulia si gettarono sul campo degli Assiri, si impadronirono delle loro spoglie e si arricchirono grandemente."],
[15007,"Gli Israeliti tornati dalla strage si impadronirono del resto e le borgate e i villaggi del monte e del piano vennero in possesso di grande bottino, poiché ve n'era in grandissima quantità."],
[15008,"Allora il sommo sacerdote Ioakim e il consiglio degli anziani degli Israeliti, che abitavano a Gerusalemme, vennero a vedere i benefici che il Signore aveva operato per Israele e anche per incontrare Giuditta e salutarla."],
[15009,"Appena furono entrati in casa sua, tutti insieme le rivolsero parole di benedizione ed esclamarono verso di lei: \"Tu sei la gloria di Gerusalemme, tu magnifico vanto d'Israele, tu splendido onore della nostra gente."],
[15010,"Compiendo tutto questo con la tua mano, hai operato per Israele nobili cose: di esse Dio si è compiaciuto. Sii per sempre benedetta dal Signore onnipotente\". Tutto il popolo soggiunse: \"Amen!\"."],
[15011,"Per trenta giorni tutto il popolo continuò a saccheggiare l'accampamento. A Giuditta diedero la tenda di Oloferne, tutte le argenterie, i letti, i vasi e tutti gli arredi di lui. Ella prese tutto in consegna e caricò la sua mula; poi aggiogò anche i suoi carri e vi accatastò sopra tutte quelle cose."],
[15012,"Tutte le donne d'Israele si radunarono per vederla e la colmarono di elogi e composero tra loro una danza in suo onore. Ella prese in mano dei tirsi e li distribuì alle donne che erano con lei."],
[15013,"Insieme con loro si incoronò di fronde di ulivo: si mise in testa a tutto il popolo, guidando la danza di tutte le donne, mentre seguivano, armati, tutti gli uomini d'Israele, portando corone e inneggiando con le loro labbra."],
[15014,"Allora Giuditta intonò questo canto di riconoscenza in mezzo a tutto Israele e tutto il popolo accompagnava a gran voce questa lode."],
[16001,"Giuditta disse: \"Intonate un inno al mio Dio con i tamburelli, cantate al Signore con i cimbali, componete per lui un salmo di lode; esaltate e invocate il suo nome!"],
[16002,"Poiché il Signore è il Dio che stronca le guerre; ha posto il suo accampamento in mezzo al popolo, mi ha salvata dalle mani dei miei persecutori."],
[16003,"Assur venne dai monti, giù da settentrione, venne con migliaia dei suoi armati; la loro moltitudine ostruì i torrenti, i loro cavalli coprirono i colli."],
[16004,"Disse che avrebbe bruciato il mio paese, stroncato i miei giovani con la spada e schiacciato al suolo i miei lattanti, che avrebbe preso in ostaggio i miei fanciulli, e rapito le mie vergini."],
[16005,"Il Signore onnipotente li ha respinti con la mano di una donna!"],
[16006,"Infatti il loro capo non fu colpito da giovani, né lo percossero figli di titani, né alti giganti l'oppressero, ma Giuditta, figlia di Merarì, lo fiaccò con la bellezza del suo volto."],
[16007,"Ella depose la veste di vedova per sollievo degli afflitti in Israele, si unse il volto con aromi,"],
[16008,"cinse i suoi capelli con un diadema e indossò una veste di lino per sedurlo."],
[16009,"I suoi sandali rapirono i suoi occhi, la sua bellezza avvinse il suo cuore e la scimitarra gli troncò il collo."],
[16010,"I Persiani rabbrividirono per il suo coraggio, per la sua forza fremettero i Medi."],
[16011,"Allora i miei poveri alzarono il grido di guerra e quelli si spaventarono, i miei deboli gridarono forte, e quelli furono sconvolti; gettarono alte grida, e quelli volsero in fuga."],
[16012,"Figli di giovani donne li trafissero, li trapassarono come disertori, perirono nella battaglia del mio Signore."],
[16013,"Canterò al mio Dio un canto nuovo: Signore, grande sei tu e glorioso, mirabile nella potenza e invincibile."],
[16014,"Ti sia sottomessa ogni tua creatura: perché tu hai detto e tutte le cose furono fatte, hai mandato il tuo spirito e furono costruite, nessuno resisterà alla tua voce."],
[16015,"I monti sulle loro basi sussulteranno insieme con le acque, davanti a te le rocce si scioglieranno come cera; ma a coloro che ti temono tu sarai sempre propizio."],
[16016,"Poca cosa è per te ogni sacrificio di soave odore, e meno ancora ogni grasso offerto a te in olocausto; ma chi teme il Signore è sempre grande."],
[16017,"Guai alle genti che insorgono contro il mio popolo: il Signore onnipotente li punirà nel giorno del giudizio, metterà fuoco e vermi nelle loro carni, e piangeranno nel tormento per sempre\"."],
[16018,"Quando giunsero a Gerusalemme, si prostrarono ad adorare Dio e, appena il popolo fu purificato, offrirono i loro olocausti, le offerte spontanee e i doni."],
[16019,"Giuditta offrì in voto a Dio tutti gli oggetti di Oloferne che il popolo le aveva dato, e anche la cortina che aveva preso direttamente dalla camera da letto di lui."],
[16020,"Il popolo continuò a far festa a Gerusalemme vicino al tempio per tre mesi e Giuditta rimase con loro."],
[16021,"Dopo quei giorni ognuno tornò nella propria dimora, e anche Giuditta tornò a Betulia e rimase nella sua proprietà. Per il resto della sua vita fu famosa in tutta la terra."],
[16022,"Molti se ne invaghirono, ma nessun uomo la conobbe per tutti i giorni della sua vita, da quando suo marito Manasse morì e fu riunito al suo popolo."],
[16023,"Ella andò molto avanti negli anni, protraendo la vecchiaia nella casa del marito fino a centocinque anni. Concesse pure la libertà alla sua ancella preferita. Quando morì a Betulia, la seppellirono nella grotta sepolcrale del marito Manasse"],
[16024,"e la casa d'Israele la pianse sette giorni. Prima di morire aveva diviso i suoi beni tra i parenti più stretti di Manasse, suo marito, e tra i parenti più stretti della sua famiglia."],
[16025,"Non vi fu più nessuno che incutesse timore agli Israeliti finché visse Giuditta e per lungo tempo dopo la sua morte."]
])
