Bib.ret([
[1001,"Fu rivolta a Giona, figlio di Amittai, questa parola del Signore:"],
[1002,"\"Àlzati, va' a Ninive, la grande città, e in essa proclama che la loro malvagità è salita fino a me\"."],
[1003,"Giona invece si mise in cammino per fuggire a Tarsis, lontano dal Signore. Scese a Giaffa, dove trovò una nave diretta a Tarsis. Pagato il prezzo del trasporto, s'imbarcò con loro per Tarsis, lontano dal Signore."],
[1004,"Ma il Signore scatenò sul mare un forte vento e vi fu in mare una tempesta così grande che la nave stava per sfasciarsi."],
[1005,"I marinai, impauriti, invocarono ciascuno il proprio dio e gettarono in mare quanto avevano sulla nave per alleggerirla. Intanto Giona, sceso nel luogo più in basso della nave, si era coricato e dormiva profondamente."],
[1006,"Gli si avvicinò il capo dell'equipaggio e gli disse: \"Che cosa fai così addormentato? Àlzati, invoca il tuo Dio! Forse Dio si darà pensiero di noi e non periremo\"."],
[1007,"Quindi dissero fra di loro: \"Venite, tiriamo a sorte per sapere chi ci abbia causato questa sciagura\". Tirarono a sorte e la sorte cadde su Giona."],
[1008,"Gli domandarono: \"Spiegaci dunque chi sia la causa di questa sciagura. Qual è il tuo mestiere? Da dove vieni? Qual è il tuo paese? A quale popolo appartieni?\"."],
[1009,"Egli rispose: \"Sono Ebreo e venero il Signore, Dio del cielo, che ha fatto il mare e la terra\"."],
[1010,"Quegli uomini furono presi da grande timore e gli domandarono: \"Che cosa hai fatto?\". Infatti erano venuti a sapere che egli fuggiva lontano dal Signore, perché lo aveva loro raccontato."],
[1011,"Essi gli dissero: \"Che cosa dobbiamo fare di te perché si calmi il mare, che è contro di noi?\". Infatti il mare infuriava sempre più."],
[1012,"Egli disse loro: \"Prendetemi e gettatemi in mare e si calmerà il mare che ora è contro di voi, perché io so che questa grande tempesta vi ha colto per causa mia\"."],
[1013,"Quegli uomini cercavano a forza di remi di raggiungere la spiaggia, ma non ci riuscivano, perché il mare andava sempre più infuriandosi contro di loro."],
[1014,"Allora implorarono il Signore e dissero: \"Signore, fa' che noi non periamo a causa della vita di quest'uomo e non imputarci il sangue innocente, poiché tu, Signore, agisci secondo il tuo volere\"."],
[1015,"Presero Giona e lo gettarono in mare e il mare placò la sua furia."],
[1016,"Quegli uomini ebbero un grande timore del Signore, offrirono sacrifici al Signore e gli fecero promesse."],
[2001,"Ma il Signore dispose che un grosso pesce inghiottisse Giona; Giona restò nel ventre del pesce tre giorni e tre notti."],
[2002,"Dal ventre del pesce Giona pregò il Signore, suo Dio,"],
[2003,"e disse: \"Nella mia angoscia ho invocato il Signore ed egli mi ha risposto; dal profondo degli inferi ho gridato e tu hai ascoltato la mia voce."],
[2004,"Mi hai gettato nell'abisso, nel cuore del mare, e le correnti mi hanno circondato; tutti i tuoi flutti e le tue onde sopra di me sono passati."],
[2005,"Io dicevo: \"Sono scacciato lontano dai tuoi occhi; eppure tornerò a guardare il tuo santo tempio\"."],
[2006,"Le acque mi hanno sommerso fino alla gola, l'abisso mi ha avvolto, l'alga si è avvinta al mio capo."],
[2007,"Sono sceso alle radici dei monti, la terra ha chiuso le sue spranghe dietro a me per sempre. Ma tu hai fatto risalire dalla fossa la mia vita, Signore, mio Dio."],
[2008,"Quando in me sentivo venir meno la vita, ho ricordato il Signore. La mia preghiera è giunta fino a te, fino al tuo santo tempio."],
[2009,"Quelli che servono idoli falsi abbandonano il loro amore."],
[2010,"Ma io con voce di lode offrirò a te un sacrificio e adempirò il voto che ho fatto; la salvezza viene dal Signore\"."],
[2011,"E il Signore parlò al pesce ed esso rigettò Giona sulla spiaggia."],
[3001,"Fu rivolta a Giona una seconda volta questa parola del Signore:"],
[3002,"\"Àlzati, va' a Ninive, la grande città, e annuncia loro quanto ti dico\"."],
[3003,"Giona si alzò e andò a Ninive secondo la parola del Signore.  Ninive era una città molto grande, larga tre giornate di cammino."],
[3004,"Giona cominciò a percorrere la città per un giorno di cammino e predicava: \"Ancora quaranta giorni e Ninive sarà distrutta\"."],
[3005,"I cittadini di Ninive credettero a Dio e bandirono un digiuno, vestirono il sacco, grandi e piccoli."],
[3006,"Giunta la notizia fino al re di Ninive, egli si alzò dal trono, si tolse il manto, si coprì di sacco e si mise a sedere sulla cenere."],
[3007,"Per ordine del re e dei suoi grandi fu poi proclamato a Ninive questo decreto: \"Uomini e animali, armenti e greggi non gustino nulla, non pascolino, non bevano acqua."],
[3008,"Uomini e animali si coprano di sacco, e Dio sia invocato con tutte le forze; ognuno si converta dalla sua condotta malvagia e dalla violenza che è nelle sue mani."],
[3009,"Chi sa che Dio non cambi, si ravveda, deponga il suo ardente sdegno e noi non abbiamo a perire!\"."],
[3010,"Dio vide le loro opere, che cioè si erano convertiti dalla loro condotta malvagia, e Dio si ravvide riguardo al male che aveva minacciato di fare loro e non lo fece."],
[4001,"Ma Giona ne provò grande dispiacere e ne fu sdegnato."],
[4002,"Pregò il Signore: \"Signore, non era forse questo che dicevo quand'ero nel mio paese? Per questo motivo mi affrettai a fuggire a Tarsis; perché so che tu sei un Dio misericordioso e pietoso, lento all'ira, di grande amore e che ti ravvedi riguardo al male minacciato."],
[4003,"Or dunque, Signore, toglimi la vita, perché meglio è per me morire che vivere!\"."],
[4004,"Ma il Signore gli rispose: \"Ti sembra giusto essere sdegnato così?\"."],
[4005,"Giona allora uscì dalla città e sostò a oriente di essa. Si fece lì una capanna e vi si sedette dentro, all'ombra, in attesa di vedere ciò che sarebbe avvenuto nella città."],
[4006,"Allora il Signore Dio fece crescere una pianta di ricino al di sopra di Giona, per fare ombra sulla sua testa e liberarlo dal suo male. Giona provò una grande gioia per quel ricino."],
[4007,"Ma il giorno dopo, allo spuntare dell'alba, Dio mandò un verme a rodere la pianta e questa si seccò."],
[4008,"Quando il sole si fu alzato, Dio fece soffiare un vento d'oriente, afoso. Il sole colpì la testa di Giona, che si sentì venire meno e chiese di morire, dicendo: \"Meglio per me morire che vivere\"."],
[4009,"Dio disse a Giona: \"Ti sembra giusto essere così sdegnato per questa pianta di ricino?\". Egli rispose: \"Sì, è giusto; ne sono sdegnato da morire!\"."],
[4010,"Ma il Signore gli rispose: \"Tu hai pietà per quella pianta di ricino per cui non hai fatto nessuna fatica e che tu non hai fatto spuntare, che in una notte è cresciuta e in una notte è perita!"],
[4011,"E io non dovrei avere pietà di Ninive, quella grande città, nella quale vi sono più di centoventimila persone, che non sanno distinguere fra la mano destra e la sinistra, e una grande quantità di animali?\"."]
])
