Bib.ret([
[1001,"Come sta solitaria la città un tempo ricca di popolo! È divenuta come una vedova, la grande fra le nazioni; la signora tra le province è sottoposta a lavori forzati. Bet"],
[1002,"Piange amaramente nella notte, le sue lacrime sulle sue guance. Nessuno la consola, fra tutti i suoi amanti. Tutti i suoi amici l'hanno tradita, le sono divenuti nemici. Ghimel"],
[1003,"Giuda è deportato in miseria e in dura schiavitù. Abita in mezzo alle nazioni, e non trova riposo; tutti i suoi persecutori l'hanno raggiunto fra le angosce. Dalet"],
[1004,"Le strade di Sion sono in lutto, nessuno si reca più alle sue feste; tutte le sue porte sono deserte, i suoi sacerdoti sospirano, le sue vergini sono afflitte ed essa è nell'amarezza. He"],
[1005,"I suoi avversari sono suoi padroni, i suoi nemici prosperano, perché il Signore l'ha afflitta per i suoi misfatti senza numero; i suoi bambini sono andati in esilio, sospinti dal nemico. Vau"],
[1006,"Dalla figlia di Sion è scomparso ogni splendore. I suoi capi sono diventati come cervi che non trovano pascolo; camminano senza forze davanti agli inseguitori. Zain"],
[1007,"Gerusalemme ricorda i giorni della sua miseria e del suo vagare, tutti i suoi beni preziosi dal tempo antico, quando il suo popolo cadeva per mano del nemico e nessuno le porgeva aiuto. I suoi nemici la guardavano e ridevano della sua rovina. Het"],
[1008,"Gerusalemme ha peccato gravemente ed è divenuta un abominio. Quanti la onoravano la disprezzano, perché hanno visto la sua nudità. Anch'essa sospira  e si volge per nasconderla. Tet"],
[1009,"La sua sozzura è nei lembi della sua veste, non pensava alla sua fine; è caduta in modo inatteso e nessuno la consola. \"Guarda, Signore, la mia miseria, perché il nemico trionfa\". Iod"],
[1010,"L'avversario ha steso la mano su tutte le sue cose più preziose; ha visto penetrare  nel suo santuario i pagani, mentre tu, Signore, avevi loro proibito di entrare nella tua assemblea. Caf"],
[1011,"Tutto il suo popolo sospira  in cerca di pane; danno gli oggetti più preziosi in cambio di cibo, per sostenersi in vita. \"Osserva, Signore, e considera come sono disprezzata! Lamed"],
[1012,"Voi tutti che passate per la via, considerate e osservate se c'è un dolore simile al mio dolore, al dolore che ora mi tormenta, e con cui il Signore mi ha afflitta nel giorno della sua ira ardente. Mem"],
[1013,"Dall'alto egli ha scagliato un fuoco, nelle mie ossa lo ha fatto penetrare. Ha teso una rete ai miei piedi, mi ha fatto tornare indietro. Mi ha reso desolata, affranta da languore per sempre. Nun"],
[1014,"S'è aggravato il giogo delle mie colpe, dalla sua mano sono annodate. Sono cresciute fin sul mio collo e hanno fiaccato la mia forza. Il Signore mi ha messo nelle loro mani, non posso alzarmi. Samec"],
[1015,"Il Signore in mezzo a me ha ripudiato tutti i miei prodi,  ha chiamato a raccolta contro di me per fiaccare i miei giovani; il Signore ha pigiato nel torchio la vergine figlia di Giuda. Ain"],
[1016,"Per questo piango, e dal mio occhio scorrono lacrime, perché lontano da me è chi consola, chi potrebbe ridarmi la vita; i miei figli sono desolati, perché il nemico ha prevalso\". Pe"],
[1017,"Sion protende le mani, nessuno la consola. Contro Giacobbe il Signore ha mandato da tutte le parti i suoi nemici. Gerusalemme è divenuta  per loro un abominio. Sade"],
[1018,"\"Giusto è il Signore, poiché mi sono ribellata alla sua parola. Ascoltate, vi prego, popoli tutti, e osservate il mio dolore! Le mie vergini e i miei giovani sono andati in schiavitù. Kof"],
[1019,"Ho chiamato i miei amanti, ma mi hanno tradita; i miei sacerdoti e i miei anziani sono spirati in città, mentre cercavano cibo per sostenersi in vita. Res"],
[1020,"Guarda, Signore, quanto sono in angoscia; le mie viscere si agitano, dentro di me è sconvolto il mio cuore, poiché sono stata veramente ribelle. Di fuori la spada mi priva dei figli, dentro c'è la morte. Sin"],
[1021,"Senti come gemo, e nessuno mi consola. Tutti i miei nemici hanno saputo della mia sventura, hanno gioito, perché tu l'hai fatto. Manda il giorno che hai decretato ed essi siano simili a me! Tau"],
[1022,"Giunga davanti a te tutta la loro malvagità, trattali come hai trattato me per tutti i miei peccati. Sono molti i miei gemiti e il mio cuore si consuma\"."],
[2001,"Come il Signore ha oscurato nella sua ira la figlia di Sion! Ha scagliato dal cielo in terra la gloria d'Israele. Non si è ricordato dello sgabello dei suoi piedi nel giorno del suo furore. Bet"],
[2002,"Il Signore ha distrutto senza pietà tutti i pascoli di Giacobbe; ha abbattuto nella sua ira le fortezze della figlia di Giuda, ha prostrato a terra, ha profanato il suo regno e i suoi capi. Ghimel"],
[2003,"Con ira ardente egli ha infranto tutta la potenza d'Israele. Ha ritratto la destra davanti al nemico; ha acceso in Giacobbe come una fiamma di fuoco, che divora tutt'intorno. Dalet"],
[2004,"Ha teso il suo arco come un nemico, ha tenuto ferma la destra  come un avversario, ha ucciso quanto è delizia dell'occhio. Sulla tenda della figlia di Sion ha rovesciato la sua ira come fuoco. He"],
[2005,"Il Signore è divenuto come un nemico, ha distrutto Israele; ha demolito tutti i suoi palazzi, ha abbattuto le sue fortezze, ha moltiplicato alla figlia di Giuda lamento e cordoglio. Vau"],
[2006,"Ha devastato come un giardino la sua dimora, ha distrutto il luogo della riunione. Il Signore ha fatto dimenticare in Sion la festa e il sabato, ha rigettato nel furore della sua ira re e sacerdoti. Zain"],
[2007,"Il Signore ha rigettato il suo altare, ha aborrito il suo santuario; ha consegnato le mura dei suoi palazzi in mano ai nemici. Essi alzarono grida nel tempio del Signore come in un giorno di festa. Het"],
[2008,"Il Signore ha deciso di demolire le mura della figlia di Sion, ha steso la corda per le misure, non ritrarrà la mano dalla distruzione; ha reso desolati bastione e baluardo, ambedue sono in rovina. Tet"],
[2009,"Sono affondate nella terra le sue porte, egli ne ha rovinato e spezzato le sbarre. Il suo re e i suoi capi sono tra le genti; non c'è più legge e neppure i suoi profeti hanno ricevuto visioni dal Signore. Iod"],
[2010,"Siedono a terra in silenzio gli anziani della figlia di Sion, hanno cosparso di cenere il capo, si sono cinti di sacco; curvano a terra il capo le vergini di Gerusalemme. Caf"],
[2011,"Si sono consunti per le lacrime i miei occhi, le mie viscere sono sconvolte; si riversa per terra la mia bile per la rovina della figlia del mio popolo, mentre viene meno il bambino e il lattante nelle piazze della città. Lamed"],
[2012,"Alle loro madri dicevano: \"Dove sono il grano e il vino?\". Intanto venivano meno come feriti nelle piazze della città; esalavano il loro respiro in grembo alle loro madri. Mem"],
[2013,"A che cosa ti assimilerò? A che cosa ti paragonerò, figlia di Gerusalemme? A che cosa ti eguaglierò per consolarti, vergine figlia di Sion? Poiché è grande come il mare la tua rovina: chi potrà guarirti? Nun"],
[2014,"I tuoi profeti hanno avuto per te visioni di cose vane e insulse, non hanno svelato la tua colpa per cambiare la tua sorte; ma ti hanno vaticinato lusinghe, vanità e illusioni. Samec"],
[2015,"Contro di te battono le mani quanti passano per la via; fischiano di scherno, scrollano il capo sulla figlia di Gerusalemme: \"È questa la città che dicevano bellezza perfetta, gioia di tutta la terra?\". Pe"],
[2016,"Spalancano contro di te la bocca tutti i tuoi nemici, fischiano di scherno e digrignano i denti, dicono: \"L'abbiamo divorata! Questo è il giorno che aspettavamo, siamo arrivati a vederlo\". Ain"],
[2017,"Il Signore ha compiuto quanto aveva decretato, ha adempiuto la sua parola decretata dai giorni antichi, ha distrutto senza pietà, ha fatto gioire su di te il nemico, ha esaltato la potenza dei tuoi avversari. Sade"],
[2018,"Grida dal tuo cuore al Signore, gemi, figlia di Sion; fa' scorrere come torrente le tue lacrime, giorno e notte! Non darti pace, non abbia tregua la pupilla del tuo occhio! Kof"],
[2019,"Àlzati, grida nella notte, quando cominciano i turni di sentinella, effondi come acqua il tuo cuore, davanti al volto del Signore; alza verso di lui le mani per la vita dei tuoi bambini, che muoiono di fame  all'angolo di ogni strada. Res"],
[2020,"\"Guarda, Signore, e considera; chi mai hai trattato così? Le donne divorano i loro frutti, i bimbi che si portano in braccio! Sono trucidati nel santuario del Signore sacerdoti e profeti! Sin"],
[2021,"Giacciono a terra per le strade  ragazzi e anziani; le mie vergini e i miei giovani sono caduti di spada. Hai ucciso nel giorno della tua ira, hai trucidato senza pietà. Tau"],
[2022,"Come a un giorno di festa hai convocato i miei terrori da tutte le parti. Nel giorno dell'ira del Signore non vi fu né superstite né fuggiasco. Quelli che io avevo portati in braccio e allevato, li ha sterminati il mio nemico\"."],
[3001,"Io sono l'uomo che ha provato la miseria sotto la sferza della sua ira. Alef"],
[3002,"Egli mi ha guidato, mi ha fatto camminare nelle tenebre e non nella luce. Alef"],
[3003,"Sì, contro di me egli volge e rivolge la sua mano tutto il giorno. Bet"],
[3004,"Egli ha consumato la mia carne e la mia pelle, ha rotto le mie ossa. Bet"],
[3005,"Ha costruito sopra di me, mi ha circondato di veleno e di affanno. Bet"],
[3006,"Mi ha fatto abitare in luoghi tenebrosi come i morti da gran tempo. Ghimel"],
[3007,"Mi ha costruito un muro tutt'intorno, non posso più uscire; ha reso pesanti le mie catene. Ghimel"],
[3008,"Anche se grido e invoco aiuto, egli soffoca la mia preghiera. Ghimel"],
[3009,"Ha sbarrato le mie vie con blocchi di pietra, ha ostruito i miei sentieri. Dalet"],
[3010,"Era per me un orso in agguato, un leone in luoghi nascosti. Dalet"],
[3011,"Seminando di spine la mia via, mi ha lacerato, mi ha reso desolato. Dalet"],
[3012,"Ha teso l'arco, mi ha posto come bersaglio alle sue saette. He"],
[3013,"Ha conficcato nei miei reni le frecce della sua faretra. He"],
[3014,"Sono diventato lo scherno di tutti i popoli, la loro beffarda canzone tutto il giorno. He"],
[3015,"Mi ha saziato con erbe amare, mi ha dissetato con assenzio. Vau"],
[3016,"Ha spezzato i miei denti con la ghiaia, mi ha steso nella polvere. Vau"],
[3017,"Sono rimasto lontano dalla pace, ho dimenticato il benessere. Vau"],
[3018,"E dico: \"È scomparsa la mia gloria, la speranza che mi veniva dal Signore\". Zain"],
[3019,"Il ricordo della mia miseria e del mio vagare è come assenzio e veleno. Zain"],
[3020,"Ben se ne ricorda la mia anima e si accascia dentro di me. Zain"],
[3021,"Questo intendo richiamare al mio cuore, e per questo voglio riprendere speranza. Het"],
[3022,"Le grazie del Signore non sono finite, non sono esaurite le sue misericordie. Het"],
[3023,"Si rinnovano ogni mattina, grande è la sua fedeltà. Het"],
[3024,"\"Mia parte è il Signore - io esclamo -, per questo in lui spero\". Tet"],
[3025,"Buono è il Signore con chi spera in lui, con colui che lo cerca. Tet"],
[3026,"È bene aspettare in silenzio la salvezza del Signore. Tet"],
[3027,"È bene per l'uomo portare un giogo nella sua giovinezza. Iod"],
[3028,"Sieda costui solitario e resti in silenzio, poiché egli glielo impone. Iod"],
[3029,"Ponga nella polvere la bocca, forse c'è ancora speranza. Iod"],
[3030,"Porga a chi lo percuote la sua guancia, si sazi di umiliazioni. Caf"],
[3031,"Poiché il Signore  non respinge per sempre. Caf"],
[3032,"Ma, se affligge, avrà anche pietà secondo il suo grande amore. Caf"],
[3033,"Poiché contro il suo desiderio egli umilia e affligge i figli dell'uomo. Lamed"],
[3034,"Schiacciano sotto i loro piedi tutti i prigionieri del paese. Lamed"],
[3035,"Ledono i diritti di un uomo davanti al volto dell'Altissimo. Lamed"],
[3036,"Opprimono un altro in una causa. Forse il Signore non vede tutto questo? Mem"],
[3037,"Chi mai ha parlato e la sua parola si è avverata, senza che il Signore lo avesse comandato? Mem"],
[3038,"Dalla bocca dell'Altissimo non procedono forse le sventure e il bene? Mem"],
[3039,"Perché si rammarica un essere vivente, un uomo, per i castighi dei suoi peccati? Nun"],
[3040,"\"Esaminiamo la nostra condotta e scrutiamola, ritorniamo al Signore. Nun"],
[3041,"Innalziamo i nostri cuori al di sopra delle mani, verso Dio nei cieli. Nun"],
[3042,"Noi abbiamo peccato e siamo stati ribelli, e tu non ci hai perdonato. Samec"],
[3043,"Ti sei avvolto nell'ira e ci hai perseguitati, hai ucciso senza pietà. Samec"],
[3044,"Ti sei avvolto in una nube, perché la supplica non giungesse fino a te. Samec"],
[3045,"Ci hai ridotti a spazzatura e rifiuto in mezzo ai popoli. Pe"],
[3046,"Hanno spalancato la bocca contro di noi tutti i nostri nemici. Pe"],
[3047,"Nostra sorte sono terrore e fossa, sterminio e rovina\". Pe"],
[3048,"Rivoli di lacrime scorrono dai miei occhi, per la rovina della figlia del mio popolo. Ain"],
[3049,"Il mio occhio piange senza sosta perché non ha pace, Ain"],
[3050,"finché non guardi e non veda il Signore dal cielo. Ain"],
[3051,"Il mio occhio mi tormenta per tutte le figlie della mia città. Sade"],
[3052,"Mi hanno dato la caccia come a un passero coloro che mi odiano senza ragione. Sade"],
[3053,"Mi hanno chiuso vivo nella fossa e hanno gettato pietre su di me. Sade"],
[3054,"Sono salite le acque fin sopra il mio capo; ho detto: \"È finita per me\". Kof"],
[3055,"Ho invocato il tuo nome, o Signore, dalla fossa profonda. Kof"],
[3056,"Tu hai udito il mio grido: \"Non chiudere l'orecchio al mio sfogo\". Kof"],
[3057,"Tu eri vicino quando t'invocavo, hai detto: \"Non temere!\". Res."],
[3058,"Tu hai difeso, Signore, la mia causa, hai riscattato la mia vita. Res"],
[3059,"Hai visto, o Signore, la mia umiliazione, difendi il mio diritto! Res"],
[3060,"Hai visto tutte le loro vendette, tutte le loro trame contro di me. Sin"],
[3061,"Hai udito, Signore, i loro insulti, tutte le loro trame contro di me. Sin"],
[3062,"I discorsi dei miei oppositori e i loro pensieri sono contro di me tutto il giorno. Sin"],
[3063,"Osserva quando siedono e quando si alzano; io sono la loro beffarda canzone. Tau"],
[3064,"Ripagali, o Signore, secondo l'opera delle loro mani. Tau"],
[3065,"Rendili duri di cuore, sia su di loro la tua maledizione! Tau"],
[3066,"Perseguitali nell'ira, Signore, e distruggili sotto il cielo."],
[4001,"Come si è annerito l'oro, come si è alterato l'oro migliore! Sono disperse le pietre sante  all'angolo di ogni strada. Bet"],
[4002,"I preziosi figli di Sion,  valutati come oro fino, come sono stimati quali vasi di creta, lavoro delle mani di vasaio! Ghimel"],
[4003,"Persino gli sciacalli porgono le mammelle e allattano i loro cuccioli, ma la figlia del mio popolo è divenuta crudele come gli struzzi nel deserto. Dalet"],
[4004,"La lingua del lattante si è attaccata al palato per la sete; i bambini chiedevano il pane e non c'era chi lo spezzasse loro. He"],
[4005,"Coloro che si cibavano di leccornie languiscono lungo le strade; coloro che erano allevati sulla porpora abbracciano letame. Vau"],
[4006,"Grande è stata l'iniquità della figlia del mio popolo, più del peccato di Sodoma, la quale fu distrutta in un attimo,  senza fatica di mani. Zain"],
[4007,"I suoi giovani erano più splendenti della neve, più candidi del latte; avevano il corpo più roseo dei coralli, era zaffiro la loro figura. Het"],
[4008,"Ora il loro aspetto s'è fatto più scuro della fuliggine, non si riconoscono più per le strade; si è raggrinzita la loro pelle sulle ossa, è divenuta secca come legno. Tet"],
[4009,"Più fortunati gli uccisi di spada che i morti per fame,  caduti estenuati per mancanza dei prodotti del campo. Iod"],
[4010,"Mani di donne, già inclini a pietà, hanno cotto i loro bambini, che sono divenuti loro cibo nel disastro della figlia del mio popolo. Caf"],
[4011,"Il Signore ha esaurito la sua collera, ha rovesciato l'ira ardente; ha acceso in Sion un fuoco che ha divorato le sue fondamenta. Lamed"],
[4012,"Non credevano i re della terra e tutti gli abitanti del mondo che l'avversario e il nemico sarebbero penetrati entro le porte di Gerusalemme. Mem"],
[4013,"Fu per i peccati dei suoi profeti, per le iniquità dei suoi sacerdoti, che versarono in mezzo ad essa  il sangue dei giusti. Nun"],
[4014,"Costoro vagavano come ciechi per le strade, insozzati di sangue, e non si potevano neppure  toccare le loro vesti. Samec"],
[4015,"\"Scostatevi! Un impuro!\", si gridava per loro, \"Scostatevi! Non toccate!\". Fuggivano e andavano randagi tra le genti, non potevano trovare dimora. Pe"],
[4016,"La faccia del Signore li ha dispersi, egli non continuerà più a guardarli; non si è avuto riguardo dei sacerdoti, non si è usata pietà agli anziani. Ain"],
[4017,"Ancora si consumavano i nostri occhi, in cerca di un vano soccorso. Dal nostro osservatorio scrutavamo verso una nazione che non poteva salvarci. Sade"],
[4018,"Hanno spiato i nostri passi, impedendoci di andare per le nostre piazze. Prossima è la nostra fine, sono compiuti i nostri giorni! Certo, è arrivata la nostra fine. Kof"],
[4019,"I nostri inseguitori erano più veloci delle aquile del cielo; sui monti ci hanno inseguiti, nel deserto ci hanno teso agguati. Res"],
[4020,"Il soffio delle nostre narici, il consacrato del Signore, è stato preso in un agguato, lui, di cui dicevamo: \"Alla sua ombra vivremo fra le nazioni\". Sin"],
[4021,"Esulta pure, gioisci, figlia di Edom, che abiti nella terra di Us; anche a te arriverà il calice, ti inebrierai ed esporrai la tua nudità. Tau"],
[4022,"È completa la tua punizione, figlia di Sion, egli non ti manderà più in esilio; ma punirà la tua iniquità, figlia di Edom, svelerà i tuoi peccati."],
[5001,"Ricordati, Signore, di quanto ci è accaduto, guarda e considera la nostra umiliazione."],
[5002,"La nostra eredità è passata a stranieri, le nostre case a estranei."],
[5003,"Orfani siamo diventati, senza padre, le nostre madri sono come vedove."],
[5004,"La nostra acqua beviamo a pagamento, dobbiamo acquistare la nostra legna."],
[5005,"Con un giogo sul collo siamo perseguitati, siamo sfiniti, non c'è per noi riposo."],
[5006,"All'Egitto abbiamo teso la mano, all'Assiria per saziarci di pane."],
[5007,"I nostri padri peccarono e non sono più, noi portiamo la pena delle loro iniquità."],
[5008,"Schiavi comandano su di noi, non c'è chi ci liberi dalle loro mani."],
[5009,"A rischio della nostra vita ci procuriamo il pane, minacciati dalla spada del deserto."],
[5010,"La nostra pelle si è fatta bruciante come un forno a causa degli ardori della fame."],
[5011,"Hanno disonorato le donne in Sion, le vergini nelle città di Giuda."],
[5012,"I capi sono stati impiccati dalle loro mani, i volti degli anziani non sono stati rispettati."],
[5013,"I giovani hanno girato la mola, i ragazzi sono caduti sotto il peso della legna."],
[5014,"Gli anziani hanno disertato la porta, i giovani le loro cetre."],
[5015,"La gioia si è spenta nei nostri cuori, si è mutata in lutto la nostra danza."],
[5016,"È caduta la corona dalla nostra testa. Guai a noi, perché abbiamo peccato!"],
[5017,"Per questo è diventato mesto il nostro cuore, per tali cose si sono annebbiati i nostri occhi."],
[5018,"È perché il monte di Sion è desolato, vi scorrazzano le volpi."],
[5019,"Ma tu, Signore, rimani per sempre, il tuo trono di generazione in generazione."],
[5020,"Perché ci vuoi dimenticare per sempre, ci vuoi abbandonare per lunghi giorni?"],
[5021,"Facci ritornare a te, Signore, e noi ritorneremo, rinnova i nostri giorni come in antico."],
[5022,"Ci hai forse rigettati per sempre, e senza limite sei sdegnato contro di noi?"]
])
