Bib.ret([
[1001,"Oracolo. Parola del Signore a Israele per mezzo di Malachia."],
[1002,"Vi ho amati, dice il Signore. E voi dite: \"Come ci hai amati?\". Non era forse Esaù fratello di Giacobbe? Oracolo del Signore. Eppure ho amato Giacobbe"],
[1003,"e ho odiato Esaù. Ho fatto dei suoi monti un deserto e ho dato la sua eredità agli sciacalli del deserto."],
[1004,"Se Edom dice: \"Siamo stati distrutti, ma ci rialzeremo dalle nostre rovine!\", il Signore degli eserciti dichiara: \"Essi ricostruiranno, ma io demolirò\". Saranno chiamati \"Territorio malvagio\" e \"Popolo contro cui il Signore è adirato per sempre\"."],
[1005,"I vostri occhi lo vedranno e voi direte: \"Grande è il Signore anche al di là dei confini d'Israele\"."],
[1006,"Il figlio onora suo padre e il servo rispetta il suo padrone. Se io sono padre, dov'è l'onore che mi spetta? Se sono il padrone, dov'è il timore di me? Dice il Signore degli eserciti a voi, sacerdoti che disprezzate il mio nome. Voi domandate: \"Come lo abbiamo disprezzato il tuo nome?\"."],
[1007,"Offrite sul mio altare un cibo impuro e dite: \"In che modo te lo abbiamo reso impuro?\". Quando voi dite: \"La tavola del Signore è spregevole\""],
[1008,"e offrite un animale cieco in sacrificio, non è forse un male? Quando voi offrite un animale zoppo o malato, non è forse un male? Offritelo pure al vostro governatore: pensate che sarà soddisfatto di voi o che vi accoglierà con benevolenza? Dice il Signore degli eserciti."],
[1009,"Ora supplicate pure Dio perché abbia pietà di voi! Se fate tali cose, dovrebbe accogliervi con benevolenza? Dice il Signore degli eserciti."],
[1010,"Oh, ci fosse fra voi chi chiude le porte, perché non arda più invano il mio altare! Non mi compiaccio di voi - dice il Signore degli eserciti - e non accetto l'offerta delle vostre mani!"],
[1011,"Poiché dall'oriente all'occidente grande è il mio nome fra le nazioni e in ogni luogo si brucia incenso al mio nome e si fanno offerte pure, perché grande è il mio nome fra le nazioni. Dice il Signore degli eserciti."],
[1012,"Ma voi lo profanate quando dite: \"Impura è la tavola del Signore e spregevole il cibo che vi è sopra\"."],
[1013,"Voi aggiungete: \"Ah! che pena!\". E lo disprezzate. Dice il Signore degli eserciti. Offrite animali rubati, zoppi, malati e li portate in offerta! Posso io accettarla dalle vostre mani? Dice il Signore."],
[1014,"Maledetto il fraudolento che ha nel gregge un maschio, ne fa voto e poi mi sacrifica una bestia difettosa. Poiché io sono un re grande - dice il Signore degli eserciti - e il mio nome è terribile fra le nazioni."],
[2001,"Ora a voi questo monito, o sacerdoti."],
[2002,"Se non mi ascolterete e non vi darete premura di dare gloria al mio nome, dice il Signore degli eserciti, manderò su voi la maledizione e cambierò in maledizione le vostre benedizioni. Anzi le ho già cambiate, perché nessuno tra voi se ne dà premura."],
[2003,"Ecco, io spezzerò il vostro braccio e spanderò sulla vostra faccia escrementi, gli escrementi delle vittime immolate nelle vostre feste solenni, perché siate spazzati via insieme con essi."],
[2004,"Così saprete che io ho diretto a voi questo monito, perché sussista la mia alleanza con Levi, dice il Signore degli eserciti."],
[2005,"La mia alleanza con lui era alleanza di vita e di benessere, che io gli concessi, e anche di timore, ed egli mi temette ed ebbe riverenza del mio nome."],
[2006,"Un insegnamento veritiero era sulla sua bocca né c'era falsità sulle sue labbra; con pace e rettitudine ha camminato davanti a me e ha fatto allontanare molti dal male."],
[2007,"Infatti le labbra del sacerdote devono custodire la scienza e dalla sua bocca si ricerca insegnamento, perché egli è messaggero del Signore degli eserciti."],
[2008,"Voi invece avete deviato dalla retta via e siete stati d'inciampo a molti con il vostro insegnamento; avete distrutto l'alleanza di Levi, dice il Signore degli eserciti."],
[2009,"Perciò anche io vi ho reso spregevoli e abietti davanti a tutto il popolo, perché non avete seguito le mie vie e avete usato parzialità nel vostro insegnamento."],
[2010,"Non abbiamo forse tutti noi un solo padre? Forse non ci ha creati un unico Dio? Perché dunque agire con perfidia l'uno contro l'altro, profanando l'alleanza dei nostri padri?"],
[2011,"Giuda è stato sleale e l'abominio è stato commesso in Israele e a Gerusalemme. Giuda infatti ha osato profanare il santuario caro al Signore e ha sposato la figlia di un dio straniero!"],
[2012,"Il Signore elimini chi ha agito così, chiunque egli sia, dalle tende di Giacobbe e da coloro che offrono l'offerta al Signore degli eserciti."],
[2013,"Un'altra cosa fate ancora: voi coprite di lacrime, di pianti e di sospiri l'altare del Signore, perché egli non guarda all'offerta né l'accetta con benevolenza dalle vostre mani."],
[2014,"E chiedete: \"Perché?\". Perché il Signore è testimone fra te e la donna della tua giovinezza, che hai tradito, mentre era la tua compagna, la donna legata a te da un patto."],
[2015,"Non fece egli un essere solo dotato di carne e soffio vitale? Che cosa cerca quest'unico essere, se non prole da parte di Dio? Custodite dunque il vostro soffio vitale e nessuno tradisca la donna della sua giovinezza."],
[2016,"Perché io detesto il ripudio, dice il Signore, Dio d'Israele, e chi copre d'iniquità la propria veste, dice il Signore degli eserciti. Custodite dunque il vostro soffio vitale e non siate infedeli."],
[2017,"Voi avete stancato il Signore con le vostre parole; eppure chiedete: \"Come lo abbiamo stancato?\". Quando affermate: \"Chiunque fa il male è come se fosse buono agli occhi del Signore e in lui si compiace\", o quando esclamate: \"Dov'è il Dio della giustizia?\"."],
[3001,"Ecco, io manderò un mio messaggero a preparare la via davanti a me e subito entrerà nel suo tempio il Signore che voi cercate; e l'angelo dell'alleanza, che voi sospirate, eccolo venire, dice il Signore degli eserciti."],
[3002,"Chi sopporterà il giorno della sua venuta? Chi resisterà al suo apparire? Egli è come il fuoco del fonditore e come la lisciva dei lavandai."],
[3003,"Siederà per fondere e purificare l'argento; purificherà i figli di Levi, li affinerà come oro e argento, perché possano offrire al Signore un'offerta secondo giustizia."],
[3004,"Allora l'offerta di Giuda e di Gerusalemme sarà gradita al Signore come nei giorni antichi, come negli anni lontani."],
[3005,"Io mi accosterò a voi per il giudizio e sarò un testimone pronto contro gli incantatori, contro gli adulteri, contro gli spergiuri, contro chi froda il salario all'operaio, contro gli oppressori della vedova e dell'orfano e contro chi fa torto al forestiero. Costoro non mi temono, dice il Signore degli eserciti."],
[3006,"Io sono il Signore, non cambio; voi, figli di Giacobbe, non siete ancora al termine."],
[3007,"Fin dai tempi dei vostri padri vi siete allontanati dai miei precetti, non li avete osservati. Tornate a me e io tornerò a voi, dice il Signore degli eserciti. Ma voi dite: \"Come dobbiamo tornare?\"."],
[3008,"Può un uomo frodare Dio? Eppure voi mi frodate e andate dicendo: \"Come ti abbiamo frodato?\". Nelle decime e nelle primizie."],
[3009,"Siete già stati colpiti dalla maledizione e andate ancora frodandomi, voi, la nazione tutta!"],
[3010,"Portate le decime intere nel tesoro del tempio, perché ci sia cibo nella mia casa; poi mettetemi pure alla prova in questo - dice il Signore degli eserciti -, se io non vi aprirò le cateratte del cielo e non riverserò su di voi benedizioni sovrabbondanti."],
[3011,"Terrò indietro gli insetti divoratori, perché non vi distruggano i frutti della terra e la vite non sia sterile nel campo, dice il Signore degli eserciti."],
[3012,"Felici vi diranno tutte le genti, perché sarete una terra di delizie, dice il Signore degli eserciti."],
[3013,"Duri sono i vostri discorsi contro di me - dice il Signore - e voi andate dicendo: \"Che cosa abbiamo detto contro di te?\"."],
[3014,"Avete affermato: \"È inutile servire Dio: che vantaggio abbiamo ricevuto dall'aver osservato i suoi comandamenti o dall'aver camminato in lutto davanti al Signore degli eserciti?"],
[3015,"Dobbiamo invece proclamare beati i superbi che, pur facendo il male, si moltiplicano e, pur provocando Dio, restano impuniti\"."],
[3016,"Allora parlarono tra loro i timorati di Dio. Il Signore porse l'orecchio e li ascoltò: un libro di memorie fu scritto davanti a lui per coloro che lo temono e che onorano il suo nome."],
[3017,"Essi diverranno - dice il Signore degli eserciti - la mia proprietà particolare nel giorno che io preparo. Avrò cura di loro come il padre ha cura del figlio che lo serve."],
[3018,"Voi allora di nuovo vedrete la differenza fra il giusto e il malvagio, fra chi serve Dio e chi non lo serve."],
[3019,"Ecco infatti: sta per venire il giorno rovente come un forno. Allora tutti i superbi e tutti coloro che commettono ingiustizia saranno come paglia; quel giorno, venendo, li brucerà - dice il Signore degli eserciti - fino a non lasciar loro né radice né germoglio."],
[3020,"Per voi, che avete timore del mio nome, sorgerà con raggi benefici il sole di giustizia e voi uscirete saltellanti come vitelli dalla stalla."],
[3021,"Calpesterete i malvagi ridotti in cenere sotto le piante dei vostri piedi nel giorno che io preparo, dice il Signore degli eserciti."],
[3022,"Tenete a mente la legge del mio servo Mosè, al quale ordinai sull'Oreb precetti e norme per tutto Israele."],
[3023,"Ecco, io invierò il profeta Elia prima che giunga il giorno grande e terribile del Signore:"],
[3024,"egli convertirà il cuore dei padri verso i figli e il cuore dei figli verso i padri, perché io, venendo, non colpisca la terra con lo sterminio."]
])
