Bib.ret([
[1001,"Parola del Signore, rivolta a Michea di Moreset, al tempo di Iotam, di Acaz e di Ezechia, re di Giuda. Visione che egli ebbe riguardo a Samaria e a Gerusalemme."],
[1002,"Udite, popoli tutti! Fa' attenzione, o terra, con quanto contieni! Il Signore Dio sia testimone contro di voi, il Signore dal suo santo tempio."],
[1003,"Poiché ecco, il Signore esce dalla sua dimora e scende e cammina sulle alture della terra;"],
[1004,"si sciolgono i monti sotto di lui e le valli si squarciano come cera davanti al fuoco, come acque versate su un pendio."],
[1005,"Tutto ciò per l'infedeltà di Giacobbe e per i peccati della casa d'Israele. Qual è l'infedeltà di Giacobbe? Non è forse Samaria? Quali sono le alture di Giuda? Non è forse Gerusalemme?"],
[1006,"Ridurrò Samaria a un mucchio di rovine in un campo, a un luogo per piantarvi la vigna. Rotolerò le sue pietre nella valle, scoprirò le sue fondamenta."],
[1007,"Tutte le sue statue saranno frantumate, tutti i suoi guadagni andranno bruciati, di tutti i suoi idoli farò scempio, perché li ha messi insieme a prezzo di prostituzione e in prezzo di prostituzione torneranno."],
[1008,"Perciò farò lamenti e griderò, me ne andrò scalzo e nudo, manderò ululati come gli sciacalli, urli lamentosi come gli struzzi,"],
[1009,"perché la sua piaga è incurabile ed è giunta fino a Giuda, si estende fino alle soglie del mio popolo, fino a Gerusalemme."],
[1010,"Non l'annunciate in Gat, non piangete, a Bet-Leafrà rotolatevi nella polvere."],
[1011,"Emigra, popolazione di Safir, nuda e vergognosa; non è uscita la popolazione di Saanan. Bet-Esel è in lutto;  ha tolto a voi la sua difesa."],
[1012,"Si attendeva il benessere la popolazione di Marot, invece è scesa la sciagura da parte del Signore fino alle porte di Gerusalemme."],
[1013,"Attacca i destrieri al carro, o abitante di Lachis! Essa fu l'inizio del peccato per la figlia di Sion, poiché in te sono state trovate le infedeltà d'Israele."],
[1014,"Perciò tu darai un regalo d'addio a Moreset-Gat, le case di Aczib saranno una delusione per i re d'Israele."],
[1015,"Ti farò ancora giungere un conquistatore, o abitante di Maresà. Fino ad Adullam arriverà la gloria d'Israele."],
[1016,"Tagliati i capelli, rasati la testa per via dei tuoi figli, tue delizie; allarga la tua calvizie come un avvoltoio, perché vanno in esilio lontano da te."],
[2001,"Guai a coloro che meditano l'iniquità e tramano il male sui loro giacigli; alla luce dell'alba lo compiono, perché in mano loro è il potere."],
[2002,"Sono avidi di campi e li usurpano, di case e se le prendono. Così opprimono l'uomo e la sua casa, il proprietario e la sua eredità."],
[2003,"Perciò così dice il Signore: \"Ecco, io medito contro questa genia una sciagura da cui non potranno sottrarre il collo e non andranno più a testa alta, perché sarà un tempo di calamità."],
[2004,"In quel tempo si intonerà su di voi una canzone, si leverà un lamento e si dirà: \"Siamo del tutto rovinati; ad altri egli passa l'eredità del mio popolo, non si avvicinerà più a me, per restituirmi i campi che sta spartendo!\"."],
[2005,"Perciò non ci sarà nessuno che tiri a sorte per te, quando si farà la distribuzione durante l'assemblea del Signore\"."],
[2006,"\"Non profetizzate!\", dicono i profeti. \"Non profetizzate riguardo a queste cose, cioè che non ci raggiungerà l'obbrobrio\"."],
[2007,"È forse già cosa detta, o casa di Giacobbe? È forse stanca la pazienza del Signore o questo è il suo modo di agire? Non sono forse benefiche le sue parole per chi cammina con rettitudine?"],
[2008,"Ma voi contro il mio popolo  insorgete come nemici: strappate il mantello e la dignità a chi passa tranquillo, senza intenzioni bellicose."],
[2009,"Cacciate le donne del mio popolo fuori dalle loro piacevoli case, e togliete ai loro bambini il mio onore per sempre."],
[2010,"\"Su, andatevene, perché questo non è più luogo di riposo\". A causa della sua impurità  provoca distruzione e rovina totale."],
[2011,"Se uno che insegue il vento e spaccia menzogne dicesse: \"Ti profetizzo riguardo al vino e a bevanda inebriante\", questo sarebbe un profeta per questo popolo."],
[2012,"Certo ti radunerò tutto, o Giacobbe; certo ti raccoglierò, resto d'Israele. Li metterò insieme come pecore in un recinto sicuro, come una mandria in mezzo al pascolo, dove muggisca lontano dagli uomini."],
[2013,"Chi ha aperto la breccia li precederà; forzeranno e varcheranno la porta e usciranno per essa. Marcerà il loro re innanzi a loro e il Signore sarà alla loro testa."],
[3001,"Io dissi: \"Ascoltate, capi di Giacobbe, voi governanti della casa d'Israele: Non spetta forse a voi conoscere la giustizia?\"."],
[3002,"Nemici del bene e amanti del male, voi togliete loro la pelle di dosso e la carne dalle ossa."],
[3003,"Divorano la carne del mio popolo e gli strappano la pelle di dosso, ne rompono le ossa e lo fanno a pezzi, come carne in una pentola, come lesso in un calderone."],
[3004,"Allora grideranno al Signore, ma egli non risponderà; nasconderà loro la faccia, in quel tempo, perché hanno compiuto azioni malvagie."],
[3005,"Così dice il Signore contro i profeti che fanno traviare il mio popolo, che annunciano la pace se hanno qualcosa tra i denti da mordere, ma a chi non mette loro niente in bocca dichiarano la guerra."],
[3006,"Quindi, per voi sarà notte invece di visioni, tenebre per voi invece di responsi. Il sole tramonterà su questi profeti e oscuro si farà il giorno su di loro."],
[3007,"I veggenti saranno ricoperti di vergogna e gli indovini arrossiranno; si copriranno tutti il labbro, perché non hanno risposta da Dio."],
[3008,"Mentre io sono pieno di forza, dello spirito del Signore, di giustizia e di coraggio, per annunciare a Giacobbe le sue colpe, a Israele il suo peccato."],
[3009,"Udite questo, dunque, capi della casa di Giacobbe, governanti della casa d'Israele, che aborrite la giustizia e storcete quanto è retto,"],
[3010,"che costruite Sion sul sangue e Gerusalemme con il sopruso;"],
[3011,"i suoi capi giudicano in vista dei regali, i suoi sacerdoti insegnano per lucro, i suoi profeti danno oracoli per denaro. Osano appoggiarsi al Signore dicendo: \"Non è forse il Signore in mezzo a noi? Non ci coglierà alcun male\"."],
[3012,"Perciò, per causa vostra, Sion sarà arata come un campo e Gerusalemme diverrà un mucchio di rovine, il monte del tempio un'altura boscosa."],
[4001,"Alla fine dei giorni il monte del tempio del Signore sarà saldo sulla cima dei monti e si innalzerà sopra i colli, e ad esso affluiranno i popoli."],
[4002,"Verranno molte genti e diranno: \"Venite, saliamo sul monte del Signore e al tempio del Dio di Giacobbe, perché ci insegni le sue vie e possiamo camminare per i suoi sentieri\". Poiché da Sion uscirà la legge e da Gerusalemme la parola del Signore."],
[4003,"Egli sarà giudice fra molti popoli e arbitro fra genti potenti, fino alle più lontane. Spezzeranno le loro spade e ne faranno aratri, delle loro lance faranno falci; una nazione non alzerà più la spada contro un'altra nazione, non impareranno più l'arte della guerra."],
[4004,"Siederanno ognuno tranquillo sotto la vite e sotto il fico e più nessuno li spaventerà, perché la bocca del Signore degli eserciti ha parlato!"],
[4005,"Tutti gli altri popoli camminino pure ognuno nel nome del suo dio, noi cammineremo nel nome del Signore, nostro Dio, in eterno e per sempre."],
[4006,"\"In quel giorno - oracolo del Signore - radunerò gli zoppi, raccoglierò i dispersi e coloro che ho trattato duramente."],
[4007,"Degli zoppi io farò un resto, dei lontani una nazione forte\". E il Signore regnerà su di loro sul monte Sion, da allora e per sempre."],
[4008,"E a te, torre del gregge, colle della figlia di Sion, a te verrà, ritornerà a te la sovranità di prima, il regno della figlia di Gerusalemme."],
[4009,"Ora, perché gridi così forte? In te non c'è forse un re? I tuoi consiglieri sono forse periti, perché ti prendono i dolori come di partoriente?"],
[4010,"Spasima e gemi, figlia di Sion, come una partoriente, perché presto uscirai dalla città e dimorerai per la campagna e andrai fino a Babilonia. Là sarai liberata, là il Signore ti riscatterà dalla mano dei tuoi nemici."],
[4011,"Ora si sono radunate contro di te molte nazioni, che dicono: \"Sia profanata, e godano i nostri occhi alla vista di Sion\"."],
[4012,"Ma esse non conoscono i pensieri del Signore e non comprendono il suo consiglio, poiché le ha radunate come covoni sull'aia."],
[4013,"Àlzati e trebbia, figlia di Sion, perché renderò di ferro il tuo corno e di bronzo le tue unghie e tu stritolerai molti popoli: consacrerai al Signore i loro guadagni e le loro ricchezze al padrone di tutta la terra."],
[4014,"Ora fatti delle incisioni, o figlia guerriera; hanno posto l'assedio intorno a noi, con la verga percuotono sulla guancia il giudice d'Israele."],
[5001,"E tu, Betlemme di Èfrata, così piccola per essere fra i villaggi di Giuda, da te uscirà per me colui che deve essere il dominatore in Israele; le sue origini sono dall'antichità, dai giorni più remoti."],
[5002,"Perciò Dio li metterà in potere altrui fino a quando partorirà colei che deve partorire; e il resto dei tuoi fratelli ritornerà ai figli d'Israele."],
[5003,"Egli si leverà e pascerà con la forza del Signore, con la maestà del nome del Signore, suo Dio. Abiteranno sicuri, perché egli allora sarà grande fino agli estremi confini della terra."],
[5004,"Egli stesso sarà la pace! Se Assur entrerà nella nostra terra e metterà il piede nei nostri palazzi, noi schiereremo contro di lui sette pastori e otto capi di uomini,"],
[5005,"che governeranno la terra di Assur con la spada, la terra di Nimrod con il suo stesso pugnale. Egli ci libererà da Assur, se entrerà nella nostra terra e metterà piede entro i nostri confini."],
[5006,"Il resto di Giacobbe sarà, in mezzo a molti popoli, come rugiada mandata dal Signore e come pioggia che cade sull'erba, che non attende nulla dall'uomo e nulla spera dai figli dell'uomo."],
[5007,"Allora il resto di Giacobbe sarà in mezzo a numerose nazioni come un leone tra le belve della foresta, come un leoncello tra greggi di pecore, il quale, se entra, calpesta e sbrana e non c'è scampo."],
[5008,"La tua mano si alzerà contro tutti i tuoi nemici, e tutti i tuoi avversari saranno sterminati."],
[5009,"\"In quel giorno - oracolo del Signore - distruggerò i tuoi cavalli in mezzo a te e manderò in rovina i tuoi carri;"],
[5010,"distruggerò le città della tua terra e demolirò tutte le tue fortezze."],
[5011,"Ti strapperò di mano i sortilegi e non avrai più indovini."],
[5012,"Distruggerò in mezzo a te i tuoi idoli e le tue stele, né più ti prostrerai davanti a un'opera delle tue mani."],
[5013,"Estirperò da te i tuoi pali sacri, distruggerò le tue città."],
[5014,"Con ira e furore, farò vendetta delle nazioni che non hanno voluto obbedire\"."],
[6001,"Ascoltate dunque ciò che dice il Signore: \"Su, illustra la tua causa ai monti e i colli ascoltino la tua voce!\"."],
[6002,"Ascoltate, o monti, il processo del Signore, o perenni fondamenta della terra, perché il Signore è in causa con il suo popolo, accusa Israele."],
[6003,"\"Popolo mio, che cosa ti ho fatto? In che cosa ti ho stancato? Rispondimi."],
[6004,"Forse perché ti ho fatto uscire dalla terra d'Egitto, ti ho riscattato dalla condizione servile e ho mandato davanti a te Mosè, Aronne e Maria?"],
[6005,"Popolo mio, ricorda le trame di Balak, re di Moab, e quello che gli rispose Balaam, figlio di Beor. Ricordati di quello che è avvenuto da Sittim a Galgala, per riconoscere le vittorie del Signore\"."],
[6006,"\"Con che cosa mi presenterò al Signore, mi prostrerò al Dio altissimo? Mi presenterò a lui con olocausti, con vitelli di un anno?"],
[6007,"Gradirà il Signore migliaia di montoni e torrenti di olio a miriadi? Gli offrirò forse il mio primogenito per la mia colpa, il frutto delle mie viscere per il mio peccato?\"."],
[6008,"Uomo, ti è stato insegnato ciò che è buono e ciò che richiede il Signore da te: praticare la giustizia, amare la bontà, camminare umilmente con il tuo Dio."],
[6009,"La voce del Signore grida alla città e chi ha senno teme il suo nome: \"Ascoltate, tribù e assemblea"],
[6010,"della città. Ci sono ancora nella casa dell'empio i tesori ingiustamente acquistati e una detestabile  efa  ridotta?"],
[6011,"Potrò io giustificare le bilance truccate e il sacchetto di pesi falsi?"],
[6012,"I ricchi della città sono pieni di violenza e i suoi abitanti proferiscono menzogna; le loro parole sono un inganno!"],
[6013,"Allora anch'io ho cominciato a colpirti, a devastarti per i tuoi peccati."],
[6014,"Mangerai, ma non ti sazierai, e la tua fame rimarrà in te; metterai da parte, ma nulla salverai; e se qualcosa salverai, io lo consegnerò alla spada."],
[6015,"Seminerai, ma non mieterai; frangerai le olive, ma non ti ungerai d'olio; produrrai mosto, ma non berrai il vino."],
[6016,"Tu osservi gli statuti di Omri e tutte le pratiche della casa di Acab, e segui i loro progetti, perciò io farò di te una desolazione, i tuoi abitanti oggetto di scherno e subirai l'obbrobrio del mio popolo\"."],
[7001,"Ahimè! Sono diventato come uno spigolatore d'estate, come un racimolatore dopo la vendemmia! Non un grappolo da mangiare, non un fico per la mia voglia."],
[7002,"L'uomo pio è scomparso dalla terra, non c'è più un giusto fra gli uomini: tutti stanno in agguato per spargere sangue; ognuno con la rete dà la caccia al fratello."],
[7003,"Le loro mani sono pronte per il male: il principe avanza pretese, il giudice si lascia comprare, il grande manifesta la cupidigia, e così distorcono tutto."],
[7004,"Il migliore di loro è come un rovo, il più retto una siepe di spine. Nel giorno predetto dalle tue sentinelle, il tuo castigo è giunto, adesso è il loro smarrimento."],
[7005,"Non credete all'amico, non fidatevi del compagno. Custodisci le porte della tua bocca davanti a colei che riposa sul tuo petto."],
[7006,"Il figlio insulta suo padre, la figlia si rivolta contro la madre, la nuora contro la suocera e i nemici dell'uomo sono quelli di casa sua."],
[7007,"Ma io volgo lo sguardo al Signore, spero nel Dio della mia salvezza, il mio Dio mi esaudirà."],
[7008,"Non gioire di me, o mia nemica! Se sono caduta, mi rialzerò; se siedo nelle tenebre, il Signore sarà la mia luce."],
[7009,"Sopporterò lo sdegno del Signore perché ho peccato contro di lui, finché egli tratti la mia causa e ristabilisca il mio diritto, finché mi faccia uscire alla luce e io veda la sua giustizia."],
[7010,"La mia nemica lo vedrà e sarà coperta di vergogna, lei che mi diceva: \"Dov'è il Signore, tuo Dio?\". I miei occhi gioiranno nel vederla: sarà calpestata come fango della strada."],
[7011,"È il giorno in cui le tue mura saranno riedificate; in quel giorno più ampi saranno i tuoi confini."],
[7012,"In quel giorno si verrà a te dall'Assiria fino alle città dell'Egitto, dall'Egitto fino al Fiume, da mare a mare, da monte a monte."],
[7013,"La terra diventerà un deserto a causa dei suoi abitanti, per il frutto delle loro azioni."],
[7014,"Pasci il tuo popolo con la tua verga, il gregge della tua eredità, che sta solitario nella foresta tra fertili campagne; pascolino in Basan e in Galaad come nei tempi antichi."],
[7015,"Come quando sei uscito dalla terra d'Egitto, mostraci cose prodigiose."],
[7016,"Vedranno le genti e resteranno deluse di tutta la loro potenza. Si porranno la mano sulla bocca, i loro orecchi ne resteranno assorditi."],
[7017,"Leccheranno la polvere come il serpente, come i rettili della terra; usciranno tremanti dai loro nascondigli, trepideranno e di te avranno timore."],
[7018,"Quale dio è come te, che toglie l'iniquità e perdona il peccato al resto della sua eredità? Egli non serba per sempre la sua ira, ma si compiace di manifestare il suo amore."],
[7019,"Egli tornerà ad avere pietà di noi, calpesterà le nostre colpe. Tu getterai in fondo al mare tutti i nostri peccati."],
[7020,"Conserverai a Giacobbe la tua fedeltà, ad Abramo il tuo amore, come hai giurato ai nostri padri fin dai tempi antichi."]
])
