Bib.ret([
[1001,"Oracolo su Ninive. Libro della visione di Naum da Elkos. Alef"],
[1002,"Un Dio geloso e vendicatore è il Signore, vendicatore è il Signore, pieno di collera. Il Signore si vendica degli avversari e serba rancore verso i nemici."],
[1003,"Il Signore è lento all'ira, ma grande nella potenza e nulla lascia impunito. Bet Nell'uragano e nella tempesta è il suo cammino e le nubi sono la polvere dei suoi passi. Ghimel"],
[1004,"Minaccia il mare e lo rende asciutto, prosciuga tutti i fiumi. Dalet Basan e il Carmelo inaridiscono, anche il fiore del Libano languisce. He"],
[1005,"Davanti a lui tremano i monti, ondeggiano i colli. Vau Si leva la terra davanti a lui, il mondo e tutti i suoi abitanti. Zain"],
[1006,"Davanti al suo sdegno chi può resistere e affrontare il furore della sua ira? Het La sua collera si spande come il fuoco e alla sua presenza le rocce si spezzano. Tet"],
[1007,"Buono è il Signore, un asilo sicuro nel giorno dell'angoscia. Iod Si prende cura di chi si rifugia in lui"],
[1008,"anche quando l'inondazione avanza. Caf Distrugge chi insorge contro di lui, i suoi nemici insegue nelle tenebre."],
[1009,"Che cosa tramate voi contro il Signore? Egli distrugge: non sopravverrà due volte la sciagura,"],
[1010,"poiché, intrecciati come rovi, avvinazzati come ubriachi, saranno consunti come paglia secca."],
[1011,"Da te è uscito colui che trama il male contro il Signore."],
[1012,"Così dice il Signore: \"Siano pure potenti, siano pure numerosi, saranno falciati e spariranno. Ma se ti ho afflitto, non ti affliggerò più."],
[1013,"Ora, infrangerò il suo giogo che ti opprime, spezzerò le tue catene\"."],
[1014,"Contro di te decreta il Signore: \"Nessuna discendenza porterà il tuo nome, dal tempio dei tuoi dei farò sparire le statue scolpite e quelle fuse, preparerò il tuo sepolcro, poiché non vali nulla\"."],
[2001,"Ecco sui monti i passi d'un messaggero che annuncia la pace! Celebra le tue feste, Giuda, sciogli i tuoi voti, poiché il malvagio non passerà più su di te: egli è del tutto annientato."],
[2002,"Contro di te avanza un distruttore. \"Monta la guardia alla fortezza, sorveglia le vie, cingi i tuoi fianchi, raccogli tutte le forze\"."],
[2003,"Infatti il Signore restaura il vanto di Giacobbe, rinnova il vanto d'Israele, anche se i briganti li hanno depredati e saccheggiano i loro tralci."],
[2004,"Lo scudo dei suoi prodi rosseggia, i guerrieri sono vestiti di scarlatto, come fuoco scintillano i carri di ferro pronti all'attacco,  si brandiscono le lance."],
[2005,"Per le vie avanzano i carri, scorrazzano per le piazze, il loro aspetto è come di fiamma, guizzano come saette."],
[2006,"Si fa l'appello dei più coraggiosi, che accorrendo si urtano: essi si slanciano verso le mura, la copertura di scudi è formata."],
[2007,"Le porte dei fiumi si aprono, la reggia trema tutta."],
[2008,"La Signora è condotta in esilio, le sue ancelle gemono con voce come di colombe, percuotendosi il petto."],
[2009,"Ninive è sempre stata come una vasca piena d'acqua, ma ora le acque sfuggono. \"Fermatevi! Fermatevi!\", ma nessuno si volta."],
[2010,"\"Saccheggiate l'argento, saccheggiate l'oro\". Ci sono tesori infiniti, ammassi d'oggetti preziosi!"],
[2011,"Devastazione, spoliazione, desolazione; cuori scoraggiati, ginocchia vacillanti, brividi ai fianchi, su tutti i volti il pallore."],
[2012,"Dov'è la tana dei leoni, il luogo dove venivano nutriti i leoncelli? Là si rifugiavano il leone, la leonessa e i leoncelli e nessuno li disturbava."],
[2013,"Il leone sbranava per i suoi piccoli, azzannava per le sue leonesse; riempiva i suoi covi di preda, le sue tane di rapina."],
[2014,"\"Eccomi a te - oracolo del Signore degli eserciti -: manderò in fumo la tua moltitudine e la spada divorerà i tuoi leoncelli. Distruggerò dalla terra le tue prede, non si udrà più la voce dei tuoi messaggeri\"."],
[3001,"Guai alla città sanguinaria, piena di menzogne, colma di rapine, che non cessa di depredare!"],
[3002,"Sibilo di frusta, fracasso di ruote, scalpitio di cavalli, cigolio di carri,"],
[3003,"cavalieri incalzanti, lampeggiare di spade, scintillare di lance, feriti in quantità, cumuli di morti, cadaveri senza fine, s'inciampa nei cadaveri."],
[3004,"È per le tante seduzioni della prostituta, della bella maliarda, della maestra d'incanti, che faceva mercato dei popoli con le sue tresche e delle nazioni con i suoi incantesimi."],
[3005,"\"Eccomi a te - oracolo del Signore degli eserciti -: alzerò le tue vesti fin sulla faccia e mostrerò alle nazioni la tua nudità, ai regni le tue vergogne."],
[3006,"Ti getterò addosso immondizie, ti svergognerò, ti esporrò al ludibrio."],
[3007,"Allora chiunque ti vedrà, fuggirà da te e dirà: \"Ninive è distrutta! Chi la compiangerà? Dove cercherò chi la consoli?\"."],
[3008,"Sei forse più forte di Tebe, adagiata sui canali del Nilo, circondata dalle acque? Per baluardo aveva il mare e per bastione le acque."],
[3009,"L'Etiopia e l'Egitto erano la sua forza che non aveva limiti. Put e i Libi erano i suoi alleati."],
[3010,"Eppure anch'essa fu deportata, andò schiava in esilio. Anche i suoi bambini furono sfracellati ai crocicchi di tutte le strade. Si spartirono a sorte i suoi nobili e tutti i suoi grandi furono messi in catene."],
[3011,"Anche tu berrai fino a ubriacarti e ti sentirai venir meno, anche tu cercherai scampo dal nemico."],
[3012,"Tutte le tue fortezze sono come alberi di fico carichi di frutti primaticci: appena scossi, cadono  in bocca a chi li vuole mangiare."],
[3013,"Ecco il tuo popolo: in te vi sono solo donne; si spalanca la porta della tua terra ai nemici, il fuoco divora le tue sbarre."],
[3014,"Attingi acqua per l'assedio, rinforza le tue difese, pesta l'argilla, impasta mattoni, prendi gli stampi."],
[3015,"Eppure il fuoco divorerà te, ti sterminerà la spada, anche se ti moltiplicassi come le cavallette, se diventassi numerosa come le locuste,"],
[3016,"e moltiplicassi i tuoi mercanti più che le stelle del cielo. La cavalletta mette le ali e vola via!"],
[3017,"Quelli che ti controllano sono come le locuste, i tuoi funzionari come sciami di cavallette, che si annidano fra i muretti quando è freddo, ma quando spunta il sole si dileguano e non si sa dove siano andate."],
[3018,"Re di Assur, i tuoi pastori dormono, si riposano i tuoi eroi! Il tuo popolo è disperso per i monti e nessuno lo raduna."],
[3019,"Non c'è rimedio per la tua ferita, incurabile è la tua piaga. Chiunque sentirà tue notizie batterà le mani. Perché, su chi non si è riversata senza tregua la tua crudeltà?\"."]
])
