Bib.ret([
[1001,"Parole di Neemia, figlio di Acalia. Nel mese di Chisleu dell'anno ventesimo, mentre ero nella cittadella di Susa,"],
[1002,"Anani, uno dei miei fratelli, e alcuni altri uomini arrivarono dalla Giudea. Li interrogai riguardo ai Giudei, i superstiti che erano scampati alla deportazione, e riguardo a Gerusalemme."],
[1003,"Essi mi dissero: \"I superstiti che sono scampati alla deportazione sono là, nella provincia, in grande miseria e desolazione; le mura di Gerusalemme sono devastate e le sue porte consumate dal fuoco\"."],
[1004,"Udite queste parole, mi sedetti e piansi; feci lutto per parecchi giorni, digiunando e pregando davanti al Dio del cielo."],
[1005,"E dissi: \"O Signore, Dio del cielo, Dio grande e tremendo, che mantieni l'alleanza e la fedeltà con quelli che ti amano e osservano i tuoi comandi,"],
[1006,"sia il tuo orecchio attento, i tuoi occhi aperti per ascoltare la preghiera del tuo servo; io prego ora davanti a te giorno e notte per gli Israeliti, tuoi servi, confessando i peccati che noi Israeliti abbiamo commesso contro di te; anch'io e la casa di mio padre abbiamo peccato."],
[1007,"Abbiamo gravemente peccato contro di te e non abbiamo osservato i comandi, le leggi e le norme che tu hai dato a Mosè, tuo servo."],
[1008,"Ricordati della parola che hai affidato a Mosè, tuo servo: \"Se sarete infedeli, io vi disperderò fra i popoli;"],
[1009,"ma se tornerete a me e osserverete i miei comandi e li eseguirete, anche se i vostri esiliati si trovassero all'estremità dell'orizzonte, io di là li raccoglierò e li ricondurrò al luogo che ho scelto per farvi dimorare il mio nome\"."],
[1010,"Ora questi sono tuoi servi e tuo popolo, che hai redento con la tua grande forza e con la tua mano potente."],
[1011,"O Signore, sia il tuo orecchio attento alla preghiera del tuo servo e alla preghiera dei tuoi servi, che desiderano temere il tuo nome; concedi oggi buon successo al tuo servo e fa' che trovi compassione presso quest'uomo\". Io allora ero coppiere del re."],
[2001,"Nel mese di Nisan dell'anno ventesimo del re Artaserse, appena il vino fu pronto davanti al re, io presi il vino e glielo diedi. Non ero mai stato triste davanti a lui."],
[2002,"Ma il re mi disse: \"Perché hai l'aspetto triste? Eppure non sei malato; non può essere altro che un'afflizione del cuore\". Allora io ebbi grande timore"],
[2003,"e dissi al re: \"Viva il re per sempre! Come potrebbe il mio aspetto non essere triste, quando la città dove sono i sepolcri dei miei padri è in rovina e le sue porte sono consumate dal fuoco?\"."],
[2004,"Il re mi disse: \"Che cosa domandi?\". Allora io pregai il Dio del cielo"],
[2005,"e poi risposi al re: \"Se piace al re e se il tuo servo ha trovato grazia ai tuoi occhi, mandami in Giudea, nella città dove sono i sepolcri dei miei padri, perché io possa ricostruirla\"."],
[2006,"Il re, che aveva la regina seduta al suo fianco, mi disse: \"Quanto durerà il tuo viaggio? Quando ritornerai?\". Dunque la cosa non spiaceva al re, che mi lasciava andare, e io gli indicai la data."],
[2007,"Poi dissi al re: \"Se piace al re, mi si diano le lettere per i governatori dell'Oltrefiume, perché mi lascino passare fino ad arrivare in Giudea,"],
[2008,"e una lettera per Asaf, guardiano del parco del re, perché mi dia il legname per munire di travi le porte della cittadella del tempio, per le mura della città e la casa dove andrò ad abitare\". Il re mi diede le lettere, perché la mano benefica del mio Dio era su di me."],
[2009,"Giunsi presso i governatori dell'Oltrefiume e diedi loro le lettere del re. Il re aveva mandato con me una scorta di capi dell'esercito e di cavalieri."],
[2010,"Ma lo vennero a sapere Sanballat, il Coronita, e Tobia, lo schiavo ammonita, e furono molto contrariati per il fatto che fosse venuto un uomo a procurare il bene degli Israeliti."],
[2011,"Giunto a Gerusalemme, vi rimasi tre giorni."],
[2012,"Poi mi alzai di notte, io e pochi uomini che erano con me, senza parlare a nessuno di quello che Dio mi aveva messo in cuore di fare per Gerusalemme e non avendo altro giumento oltre quello che io cavalcavo."],
[2013,"Uscii di notte per la porta della Valle e andai verso la fonte del Drago e alla porta del Letame, osservando le mura di Gerusalemme, che erano diroccate, mentre le sue porte erano consumate dal fuoco."],
[2014,"Mi spinsi verso la porta della Fonte e la piscina del Re, ma non vi era posto per cui potesse passare il giumento che cavalcavo."],
[2015,"Allora risalii di notte lungo il torrente, sempre osservando le mura; poi, rientrato per la porta della Valle, me ne ritornai."],
[2016,"I magistrati non sapevano né dove io fossi andato né che cosa facessi. Fino a quel momento non avevo detto nulla, né ai Giudei né ai sacerdoti né ai notabili né ai magistrati né agli altri che si dovevano occupare del lavoro."],
[2017,"Allora io dissi loro: \"Voi vedete la miseria nella quale ci troviamo, poiché Gerusalemme è in rovina e le sue porte sono consumate dal fuoco. Venite, ricostruiamo le mura di Gerusalemme e non saremo più insultati!\"."],
[2018,"Narrai loro della mano del mio Dio, che era benefica su di me, e riferii anche le parole che il re mi aveva riferite. Quelli dissero: \"Su, costruiamo!\". E misero mano vigorosamente alla buona impresa."],
[2019,"Ma quando Sanballat, il Coronita, e Tobia, lo schiavo ammonita, e Ghesem, l'Arabo, seppero la cosa, ci schernirono e ci derisero dicendo: \"Che state facendo? Volete forse ribellarvi al re?\"."],
[2020,"Allora io risposi loro: \"Il Dio del cielo ci darà successo. Noi, suoi servi, ci metteremo a costruire. Ma voi non avrete né parte né diritto né ricordo in Gerusalemme\"."],
[3001,"Eliasib, sommo sacerdote, con i suoi fratelli sacerdoti si misero a costruire la porta delle Pecore. La consacrarono e vi misero i battenti; la consacrarono fino alla torre dei Cento e fino alla torre di Cananel."],
[3002,"Accanto a lui costruirono gli uomini di Gerico e accanto a lui costruì Zaccur, figlio di Imrì."],
[3003,"I figli di Senaà costruirono la porta dei Pesci, la munirono di travi e vi posero i battenti, le serrature e le sbarre."],
[3004,"Accanto a loro lavorò al restauro Meremot, figlio di Uria, figlio di Akkos; accanto a loro lavorò al restauro Mesullam, figlio di Berechia, figlio di Mesezabel; accanto a loro lavorò al restauro Sadoc, figlio di Baanà."],
[3005,"Accanto a loro lavorarono al restauro quelli di Tekoa, ma i loro notabili non piegarono il collo a lavorare all'opera del loro Signore."],
[3006,"Ioiadà, figlio di Paseach, e Mesullam, figlio di Besodia, restaurarono la porta Vecchia, la munirono di travi e vi posero i battenti, le serrature e le sbarre."],
[3007,"Accanto a loro lavorarono al restauro Melatia di Gabaon, Iadon di Meronot e gli uomini di Gabaon e di Mispa, alle dipendenze della sede del governatore dell'Oltrefiume."],
[3008,"Accanto a loro lavorò al restauro Uzziel, figlio di Caraià, uno degli orefici, e accanto a lui lavorò al restauro Anania, uno dei profumieri. Essi ricostruirono Gerusalemme fino al muro largo."],
[3009,"Accanto a loro lavorò al restauro Refaià, figlio di Cur, capo della metà del distretto di Gerusalemme."],
[3010,"Accanto a loro lavorò al restauro, di fronte alla sua casa, Iedaià, figlio di Carumaf, e accanto a lui lavorò al restauro Cattus, figlio di Casabnia."],
[3011,"Malchia, figlio di Carim, e Cassub, figlio di Pacat-Moab, restaurarono la parte seguente e la torre dei Forni."],
[3012,"Accanto a loro lavorò al restauro, insieme con le figlie, Sallum, figlio di Alloches, capo della metà del distretto di Gerusalemme."],
[3013,"Canun e gli abitanti di Zanoach restaurarono la porta della Valle; la costruirono, vi posero i battenti, le serrature e le sbarre. Fecero inoltre mille cubiti di muro fino alla porta del Letame."],
[3014,"Malchia, figlio di Recab, capo del distretto di Bet-Cherem, restaurò la porta del Letame; la costruì, vi pose i battenti, le serrature e le sbarre."],
[3015,"Sallum, figlio di Col-Cozè, preposto del distretto di Mispa, restaurò la porta della Fonte; la ricostruì, la munì di tetto, vi pose i battenti, le serrature e le sbarre. Fece inoltre il muro della piscina di Siloe, presso il giardino del re, fino alla scalinata per cui si scende dalla Città di Davide."],
[3016,"Dopo di lui Neemia, figlio di Azbuk, preposto della metà del distretto di Bet-Sur, lavorò al restauro fin davanti alle tombe di Davide, fino alla piscina artificiale e fino alla casa dei prodi."],
[3017,"Dopo di lui lavorarono al restauro i leviti, con Recum, figlio di Banì, e accanto a lui lavorò al restauro, per il suo distretto, Casabia, preposto della metà del distretto di Keila."],
[3018,"Dopo di lui lavorarono al restauro i loro fratelli, Binnui, figlio di Chenadad, preposto dell'altra metà del distretto di Keila."],
[3019,"Accanto a lui Ezer, figlio di Giosuè, preposto di Mispa, restaurò un'altra parte, di fronte alla salita dell'arsenale, sul Cantone."],
[3020,"Dopo di lui Baruc, figlio di Zabbai, restaurò con impegno un'altra parte, dal Cantone fino alla porta della casa di Eliasib, sommo sacerdote."],
[3021,"Dopo di lui Meremot, figlio di Uria, figlio di Akkos, restaurò un'altra parte, dalla porta della casa di Eliasib fino all'estremità della casa di Eliasib."],
[3022,"Dopo di lui lavorarono al restauro i sacerdoti che abitavano la periferia."],
[3023,"Dopo di loro Beniamino e Cassub lavorarono al restauro di fronte alla loro casa. Dopo di loro Azaria, figlio di Maasia, figlio di Anania, lavorò al restauro presso la sua casa."],
[3024,"Dopo di lui Binnui, figlio di Chenadad, restaurò un'altra parte delle mura, dalla casa di Azaria fino al Cantone e fino all'angolo."],
[3025,"Palal, figlio di Uzai, lavorò al restauro di fronte al Cantone e alla torre sporgente dalla parte superiore della reggia, che dà sul cortile della prigione. Dopo di lui Pedaià, figlio di Paros,"],
[3026,"e gli oblati che abitavano sull'Ofel lavorarono al restauro fin davanti alla porta delle Acque, verso oriente, e alla torre sporgente."],
[3027,"Dopo di loro quelli di Tekoa restaurarono un'altra parte, di fronte alla grande torre sporgente e fino al muro dell'Ofel."],
[3028,"I sacerdoti lavorarono al restauro sopra la porta dei Cavalli, ciascuno di fronte alla propria casa."],
[3029,"Dopo di loro lavorò al restauro Sadoc, figlio di Immer, di fronte alla sua casa, e dopo di lui Semaià, figlio di Secania, custode della porta Orientale."],
[3030,"Dopo di lui Anania, figlio di Selemia, e Canun, sesto figlio di Salaf, restaurarono un'altra parte. Dopo di loro Mesullam, figlio di Berechia, lavorò al restauro di fronte alla propria stanza."],
[3031,"Dopo di lui Malchia, uno degli orefici, lavorò al restauro fino alla casa degli oblati e dei mercanti, di fronte alla porta della Rassegna e fino al vano superiore dell'angolo."],
[3032,"Gli orefici e i mercanti lavorarono al restauro fra il vano superiore dell'angolo e la porta delle Pecore."],
[3033,"Sanballat, quando sentì che noi riedificavamo le mura, si adirò, si indignò molto, si fece beffe dei Giudei"],
[3034,"e disse in presenza dei suoi fratelli e dei soldati di Samaria: \"Che vogliono fare questi miserabili Giudei? Dobbiamo lasciarli fare? Offriranno sacrifici? Finiranno in un sol giorno? Vogliono far rivivere da mucchi di polvere delle pietre già consumate dal fuoco?\"."],
[3035,"Tobia l'Ammonita, che gli stava accanto, disse: \"Edifichino pure! Se una volpe vi salta sopra, farà crollare il loro muro di pietra!\"."],
[3036,"Ascolta, o nostro Dio, come siamo disprezzati! Fa' ricadere sul loro capo l'insulto e abbandonali al saccheggio in un paese di schiavitù!"],
[3037,"Non coprire la loro colpa e non sia cancellato dalla tua vista il loro peccato, perché hanno offeso i costruttori."],
[3038,"Noi dunque ricostruimmo le mura, che furono ben consolidate fino a metà altezza, e al popolo stava a cuore il lavoro."],
[4001,"Ma quando Sanballat, Tobia, gli Arabi, gli Ammoniti e gli Asdoditi sentirono che il restauro delle mura di Gerusalemme progrediva e che le brecce cominciavano a venir chiuse, si adirarono molto"],
[4002,"e tutti insieme congiurarono di venire ad attaccare Gerusalemme e crearvi confusione."],
[4003,"Allora noi pregammo il nostro Dio e contro di loro mettemmo sentinelle di giorno e di notte per difenderci da loro."],
[4004,"Quelli di Giuda dicevano: \"Le forze dei portatori vengono meno e le macerie sono molte; noi non potremo ricostruire le mura!\"."],
[4005,"I nostri avversari dicevano: \"Senza che s'accorgano di nulla, noi piomberemo in mezzo a loro, li uccideremo e faremo cessare i lavori\"."],
[4006,"Poiché i Giudei che dimoravano vicino a loro vennero a riferirci dieci volte: \"Da tutti i luoghi dove vi volgete saranno contro di noi\","],
[4007,"io, in luoghi bassi oltre le mura, nei punti scoperti, disposi il popolo per famiglie, con le loro spade, le loro lance, i loro archi."],
[4008,"Dopo aver considerato la cosa, mi alzai e dissi ai notabili, ai magistrati e al resto del popolo: \"Non li temete! Ricordatevi del Signore grande e tremendo; combattete per i vostri fratelli, per i vostri figli e le vostre figlie, per le vostre mogli e per le vostre case!\"."],
[4009,"Quando i nostri nemici sentirono che eravamo informati della cosa, Dio fece fallire il loro disegno e noi tutti tornammo alle mura, ognuno al suo lavoro."],
[4010,"Da quel giorno la metà dei miei giovani lavorava e l'altra metà stava armata di lance, di scudi, di archi, di corazze; i preposti stavano dietro a tutta la casa di Giuda."],
[4011,"Quelli che ricostruivano le mura e quelli che portavano o caricavano i pesi con una mano lavoravano e con l'altra tenevano la loro arma;"],
[4012,"tutti i costruttori, lavorando, portavano ciascuno la spada cinta ai fianchi. Il suonatore di corno stava accanto a me."],
[4013,"Dissi allora ai notabili, ai magistrati e al resto del popolo: \"L'opera è grande ed estesa e noi siamo sparsi sulle mura e distanti l'uno dall'altro."],
[4014,"Dovunque udrete il suono del corno, raccoglietevi presso di noi; il nostro Dio combatterà per noi\"."],
[4015,"Così continuavamo i lavori, mentre la metà di loro teneva impugnata la lancia, dal sorgere dell'alba allo spuntare delle stelle."],
[4016,"Anche in quell'occasione dissi al popolo: \"Ognuno con il suo aiutante passi la notte dentro Gerusalemme, così saranno per noi una guardia di notte e mano d'opera di giorno\"."],
[4017,"Io, poi, i miei fratelli, i miei servi e gli uomini di guardia che mi seguivano non ci togliemmo mai le vesti; ognuno teneva l'arma a portata di mano."],
[5001,"Si alzò un gran lamento da parte della gente del popolo e delle loro mogli contro i loro fratelli Giudei."],
[5002,"Alcuni dicevano: \"I nostri figli e le nostre figlie sono numerosi; prendiamoci del grano per mangiare e vivere!\"."],
[5003,"Altri dicevano: \"Dobbiamo impegnare i nostri campi, le nostre vigne e le nostre case per assicurarci il grano durante la carestia!\"."],
[5004,"Altri ancora dicevano: \"Abbiamo preso denaro a prestito sui nostri campi e sulle nostre vigne per pagare il tributo del re."],
[5005,"La nostra carne è come la carne dei nostri fratelli, i nostri figli sono come i loro figli; ecco, dobbiamo sottoporre i nostri figli e le nostre figlie alla schiavitù, e alcune delle nostre figlie sono già state ridotte schiave, e non possiamo fare nulla, perché i nostri campi e le nostre vigne sono in mano d'altri\"."],
[5006,"Quando udii i loro lamenti e queste parole, ne fui molto indignato."],
[5007,"Dopo aver riflettuto dentro di me, accusai i notabili e i magistrati e dissi loro: \"Voi esigete dunque un interesse tra fratelli?\". Convocai contro di loro una grande assemblea"],
[5008,"e dissi loro: \"Noi, secondo la nostra possibilità, abbiamo riscattato i nostri fratelli Giudei che si erano venduti agli stranieri, e ora proprio voi vendete i vostri fratelli perché siano rivenduti a noi?\". Allora quelli tacquero e non seppero che cosa rispondere."],
[5009,"Io dissi: \"Quello che voi fate non va bene. Non dovreste voi camminare nel timore del nostro Dio per non essere scherniti dagli stranieri, nostri nemici?"],
[5010,"Ma anch'io, i miei fratelli e i miei servi abbiamo dato loro in prestito denaro e grano. Condoniamo questo debito!"],
[5011,"Rendete loro oggi stesso i loro campi, le loro vigne, i loro oliveti e le loro case e l'interesse del denaro del grano, del vino e dell'olio, che voi esigete da loro\"."],
[5012,"Quelli risposero: \"Restituiremo e non esigeremo più nulla da loro; faremo come tu dici\". Allora chiamai i sacerdoti e li feci giurare di attenersi a questa parola."],
[5013,"Poi scossi la piega anteriore del mio mantello e dissi: \"Così Dio scuota dalla sua casa e dai suoi beni chiunque non manterrà questa parola e così sia egli scosso e svuotato di tutto!\". Tutta l'assemblea disse: \"Amen\" e lodarono il Signore. Il popolo si attenne a questa parola."],
[5014,"Inoltre, da quando il re mi aveva stabilito loro governatore nel paese di Giuda, dal ventesimo anno fino al trentaduesimo anno del re Artaserse, durante dodici anni, né io né i miei fratelli mangiammo la provvista assegnata al governatore."],
[5015,"I governatori che mi avevano preceduto avevano gravato il popolo, ricevendone pane e vino, oltre a quaranta sicli d'argento; perfino i loro servi angariavano il popolo, ma io non ho fatto così, per timore di Dio."],
[5016,"Anzi ho messo mano ai lavori di restauro di queste mura e non abbiamo comprato alcun podere. Tutti i miei giovani erano raccolti là a lavorare."],
[5017,"Avevo alla mia tavola centocinquanta uomini, Giudei e magistrati, oltre a quelli che venivano a noi dalle nazioni vicine."],
[5018,"Quello che si preparava ogni giorno, un bue, sei capi scelti di bestiame minuto e uccelli, veniva preparato a mie spese. Ogni dieci giorni vino per tutti in abbondanza. Tuttavia non ho mai chiesto la provvista assegnata al governatore, perché il popolo era già gravato abbastanza a causa dei lavori."],
[5019,"Mio Dio, ricordati in mio favore di quanto ho fatto a questo popolo."],
[6001,"Quando Sanballat, Tobia e Ghesem, l'Arabo, e gli altri nostri nemici sentirono che io avevo edificato le mura e che non vi era più rimasta alcuna breccia, sebbene a quel momento ancora non avessi messo i battenti alle porte,"],
[6002,"Sanballat e Ghesem mi mandarono a dire: \"Vieni, incontriamoci a Chefirim, nella valle di Ono\". Essi pensavano di farmi del male."],
[6003,"Ma io inviai loro messaggeri a dire: \"Sto facendo un gran lavoro e non posso scendere: perché dovrebbe interrompersi il lavoro, mentre io lo lascio per scendere da voi?\"."],
[6004,"Essi mandarono quattro volte a dirmi la stessa cosa e io risposi nello stesso modo."],
[6005,"Allora Sanballat, per la quinta volta, mi mandò a dire la stessa cosa per mezzo del suo servo, che aveva in mano una lettera aperta,"],
[6006,"nella quale stava scritto: \"Si sente dire fra queste nazioni, e Gasmu lo afferma, che tu e i Giudei meditate di ribellarvi e perciò tu costruisci le mura e, secondo queste voci, tu diventeresti loro re"],
[6007,"e avresti inoltre stabilito profeti, perché proclamino di te a Gerusalemme: \"Vi è un re in Giuda!\". Ora questi discorsi saranno riferiti al re. Vieni dunque e consultiamoci insieme\"."],
[6008,"Ma io gli feci rispondere: \"Non è come tu dici. Tu inventi!\"."],
[6009,"Tutta quella gente infatti ci voleva impaurire e diceva: \"Le loro mani desisteranno e il lavoro non si farà\". Io invece irrobustii le mie mani!"],
[6010,"Io andai a casa di Semaià, figlio di Delaià, figlio di Meetabel, perché era impedito; egli disse: \"Troviamoci insieme nel tempio, dentro il santuario, e chiudiamo le porte del santuario, perché verranno ad ucciderti; di notte verranno ad ucciderti\"."],
[6011,"Ma io risposi: \"Un uomo come me può darsi alla fuga? E chi nella mia condizione entrerebbe nel santuario per salvare la vita? No, non entrerò\"."],
[6012,"Compresi che non era mandato da Dio, ma aveva pronunciato quella profezia a mio danno, perché Tobia e Sanballat l'avevano pagato."],
[6013,"Era stato pagato per impaurirmi e indurmi ad agire in quel modo e a peccare, così avrebbero avuto un capo di accusa per screditarmi."],
[6014,"Mio Dio, ricordati di Tobia e di Sanballat, per queste loro opere, e anche della profetessa Noadia e degli altri profeti che cercavano di spaventarmi!"],
[6015,"Le mura furono condotte a termine il venticinquesimo giorno di Elul, in cinquantadue giorni."],
[6016,"Quando lo seppero, tutti i nostri nemici ebbero paura, tutte le nazioni che stavano intorno a noi si sentirono molto umiliate e dovettero riconoscere che quest'opera si era compiuta per l'intervento del nostro Dio."],
[6017,"In quei giorni i notabili di Giuda mandavano frequenti lettere a Tobia e da Tobia ne ricevevano;"],
[6018,"infatti molti in Giuda erano suoi alleati, perché egli era genero di Secania, figlio di Arach, e suo figlio Giovanni aveva sposato la figlia di Mesullam, figlio di Berechia."],
[6019,"Anche in mia presenza parlavano bene di lui e gli riferivano le mie parole, mentre Tobia mandava lettere per intimorirmi."],
[7001,"Quando le mura furono riedificate e io ebbi messo a posto le porte, e i portieri, i cantori e i leviti furono stabiliti nei loro uffici,"],
[7002,"affidai il governo di Gerusalemme a Anani, mio fratello, e ad Anania, comandante della cittadella, perché era un uomo fedele e temeva Dio più di tanti altri."],
[7003,"Ordinai loro: \"Le porte di Gerusalemme non si aprano finché il sole non cominci a scaldare e si chiudano e si sbarrino i battenti mentre gli abitanti sono ancora in piedi; si stabiliscano delle guardie prese fra gli abitanti di Gerusalemme, ognuno al suo turno e ognuno davanti alla propria casa\"."],
[7004,"La città era spaziosa e grande; ma dentro vi era poca gente e non c'erano case costruite."],
[7005,"Il mio Dio mi ispirò di radunare i notabili, i magistrati e il popolo, per farne il censimento. Trovai il registro genealogico di quelli che erano tornati dall'esilio la prima volta e vi trovai scritto:"],
[7006,"Questi sono gli abitanti della provincia che ritornarono dall'esilio, quelli che Nabucodonosor, re di Babilonia, aveva deportato e che tornarono a Gerusalemme e in Giudea, ognuno nella sua città;"],
[7007,"essi vennero con Zorobabele, Giosuè, Neemia, Azaria, Raamia, Nacamanì, Mardocheo, Bilsan, Misperet, Bigvai, Necum e Baanà. Questa è la lista degli uomini del popolo d'Israele."],
[7008,"Figli di Paros: duemilacentosettantadue."],
[7009,"Figli di Sefatia: trecentosettantadue."],
[7010,"Figli di Arach: seicentocinquantadue."],
[7011,"Figli di Pacat-Moab, cioè figli di Giosuè e di Ioab: duemilaottocentodiciotto."],
[7012,"Figli di Elam: milleduecentocinquantaquattro."],
[7013,"Figli di Zattu: ottocentoquarantacinque."],
[7014,"Figli di Zaccai: settecentosessanta."],
[7015,"Figli di Binnui: seicentoquarantotto."],
[7016,"Figli di Bebai: seicentoventotto."],
[7017,"Figli di Azgad: duemilatrecentoventidue."],
[7018,"Figli di Adonikam: seicentosessantasette."],
[7019,"Figli di Bigvai: duemilasessantasette."],
[7020,"Figli di Adin: seicentocinquantacinque."],
[7021,"Figli di Ater, cioè di Ezechia: novantotto."],
[7022,"Figli di Casum: trecentoventotto."],
[7023,"Figli di Besai: trecentoventiquattro."],
[7024,"Figli di Carif: centododici."],
[7025,"Figli di Gabaon: novantacinque."],
[7026,"Uomini di Betlemme e di Netofà: centoottantotto."],
[7027,"Uomini di Anatot: centoventotto."],
[7028,"Uomini di Bet-Azmavet: quarantadue."],
[7029,"Uomini di Kiriat-Iearim, di Chefirà e di Beerot: settecentoquarantatré."],
[7030,"Uomini di Rama e di Gheba: seicentoventuno."],
[7031,"Uomini di Micmas: centoventidue."],
[7032,"Uomini di Betel e di Ai: centoventitré."],
[7033,"Uomini di un altro Nebo: cinquantadue."],
[7034,"Figli di un altro Elam: milleduecentocinquantaquattro."],
[7035,"Figli di Carim: trecentoventi."],
[7036,"Figli di Gerico: trecentoquarantacinque."],
[7037,"Figli di Lod, di Adid e di Ono: settecentoventuno."],
[7038,"Figli di Senaà: tremilanovecentotrenta."],
[7039,"Sacerdoti: figli di Iedaià della casa di Giosuè: novecentosettantatré."],
[7040,"Figli di Immer: millecinquantadue."],
[7041,"Figli di Pascur: milleduecentoquarantasette."],
[7042,"Figli di Carim: millediciassette."],
[7043,"Leviti: figli di Giosuè, cioè di Kadmiel, figli di Odva: settantaquattro."],
[7044,"Cantori: figli di Asaf: centoquarantotto."],
[7045,"Portieri: figli di Sallum, figli di Ater, figli di Talmon, figli di Akkub, figli di Catità, figli di Sobai: centotrentotto."],
[7046,"Oblati: figli di Sica, figli di Casufà, figli di Tabbaot,"],
[7047,"figli di Keros, figli di Sià, figli di Padon,"],
[7048,"figli di Lebanà, figli di Agabà, figli di Salmai,"],
[7049,"figli di Canan, figli di Ghiddel, figli di Gacar,"],
[7050,"figli di Reaià, figli di Resin, figli di Nekodà,"],
[7051,"figli di Gazzam, figli di Uzzà, figli di Paseach,"],
[7052,"figli di Besai, figli dei Meuniti, figli dei Nefisesiti,"],
[7053,"figli di Bakbuk, figli di Akufà, figli di Carcur,"],
[7054,"figli di Baslit, figli di Mechidà, figli di Carsa,"],
[7055,"figli di Barkos, figli di Sisara, figli di Temach,"],
[7056,"figli di Nesiach, figli di Catifà."],
[7057,"Figli degli schiavi di Salomone: figli di Sotai, figli di Soferet, figli di Peridà,"],
[7058,"figli di Iala, figli di Darkon, figli di Ghiddel,"],
[7059,"figli di Sefatia, figli di Cattil, figli di Pocheret-Assebaim, figli di Amon."],
[7060,"Totale degli oblati e dei figli degli schiavi di Salomone: trecentonovantadue."],
[7061,"Questi sono coloro che ritornarono da Tel-Melach, Tel-Carsa, Cherub-Addon e Immer, ma non avevano potuto dichiarare se il loro casato e la loro discendenza fossero d'Israele:"],
[7062,"i figli di Delaià, i figli di Tobia, i figli di Nekodà: seicentoquarantadue;"],
[7063,"tra i sacerdoti: i figli di Cobaià, i figli di Akkos, i figli di Barzillai, il quale aveva preso in moglie una delle figlie di Barzillai, il Galaadita, e veniva chiamato con il loro nome."],
[7064,"Costoro cercarono il loro registro genealogico, ma non lo trovarono e furono quindi esclusi dal sacerdozio."],
[7065,"Il governatore disse loro che non potevano mangiare le cose santissime, finché non si presentasse un sacerdote con urim e tummim."],
[7066,"Tutta la comunità nel suo insieme era di quarantaduemilatrecentosessanta persone,"],
[7067,"oltre i loro schiavi e le loro schiave in numero di settemilatrecentotrentasette; avevano anche duecentoquarantacinque cantori e cantatrici."],
[7068,"Avevano quattrocentotrentacinque cammelli, seimilasettecentoventi asini."],
[7069,"Alcuni capi di casato fecero offerta alla fabbrica. Il governatore diede al tesoro mille dracme d'oro, cinquanta vasi per l'aspersione, cinquecentotrenta tuniche sacerdotali."],
[7070,"Alcuni capi di casato diedero al tesoro della fabbrica ventimila dracme d'oro e duemiladuecento mine d'argento."],
[7071,"Ciò che il resto del popolo diede era ventimila dracme d'oro, duemila mine d'argento e sessantasette tuniche sacerdotali."],
[7072,"Poi i sacerdoti, i leviti, i portieri, i cantori, alcuni del popolo, gli oblati e tutti gli Israeliti si stabilirono nelle loro città. Giunse il settimo mese e gli Israeliti stavano nelle loro città."],
[8001,"Allora tutto il popolo si radunò come un solo uomo sulla piazza davanti alla porta delle Acque e disse allo scriba Esdra di portare il libro della legge di Mosè, che il Signore aveva dato a Israele."],
[8002,"Il primo giorno del settimo mese, il sacerdote Esdra portò la legge davanti all'assemblea degli uomini, delle donne e di quanti erano capaci di intendere."],
[8003,"Lesse il libro sulla piazza davanti alla porta delle Acque, dallo spuntare della luce fino a mezzogiorno, in presenza degli uomini, delle donne e di quelli che erano capaci d'intendere; tutto il popolo tendeva l'orecchio al libro della legge."],
[8004,"Lo scriba Esdra stava sopra una tribuna di legno, che avevano costruito per l'occorrenza, e accanto a lui stavano a destra Mattitia, Sema, Anaià, Uria, Chelkia e Maasia, e a sinistra Pedaià, Misaele, Malchia, Casum, Casbaddana, Zaccaria e Mesullam."],
[8005,"Esdra aprì il libro in presenza di tutto il popolo, poiché stava più in alto di tutti; come ebbe aperto il libro, tutto il popolo si alzò in piedi."],
[8006,"Esdra benedisse il Signore, Dio grande, e tutto il popolo rispose: \"Amen, amen\", alzando le mani; si inginocchiarono e si prostrarono con la faccia a terra dinanzi al Signore."],
[8007,"Giosuè, Banì, Serebia, Iamin, Akkub, Sabbetai, Odia, Maasia, Kelità, Azaria, Iozabad, Canan, Pelaià e i leviti spiegavano la legge al popolo e il popolo stava in piedi."],
[8008,"Essi leggevano il libro della legge di Dio a brani distinti e spiegavano il senso, e così facevano comprendere la lettura."],
[8009,"Neemia, che era il governatore, Esdra, sacerdote e scriba, e i leviti che ammaestravano il popolo dissero a tutto il popolo: \"Questo giorno è consacrato al Signore, vostro Dio; non fate lutto e non piangete!\". Infatti tutto il popolo piangeva, mentre ascoltava le parole della legge."],
[8010,"Poi Neemia disse loro: \"Andate, mangiate carni grasse e bevete vini dolci e mandate porzioni a quelli che nulla hanno di preparato, perché questo giorno è consacrato al Signore nostro; non vi rattristate, perché la gioia del Signore è la vostra forza\"."],
[8011,"I leviti calmavano tutto il popolo dicendo: \"Tacete, perché questo giorno è santo; non vi rattristate!\"."],
[8012,"Tutto il popolo andò a mangiare, a bere, a mandare porzioni e a esultare con grande gioia, perché avevano compreso le parole che erano state loro proclamate."],
[8013,"Il secondo giorno i capi di casato di tutto il popolo, i sacerdoti e i leviti si radunarono presso lo scriba Esdra per esaminare le parole della legge."],
[8014,"Trovarono scritto nella legge data dal Signore per mezzo di Mosè che gli Israeliti dovevano dimorare in capanne durante la festa del settimo mese"],
[8015,"e dovevano proclamare e far passare questa voce in tutte le loro città e a Gerusalemme: \"Uscite verso la montagna e portate rami di ulivo, rami di olivastro, rami di mirto, rami di palme e rami di alberi ombrosi, per fare capanne, come sta scritto\"."],
[8016,"Allora il popolo uscì, portò l'occorrente e si fecero capanne, ciascuno sul tetto della propria casa, nei loro cortili, nei cortili di Dio, sulla piazza della porta delle Acque e sulla piazza della porta di Èfraim."],
[8017,"Così tutta la comunità di coloro che erano tornati dalla deportazione si fece capanne e dimorò nelle capanne. Dal tempo di Giosuè, figlio di Nun, gli Israeliti non avevano fatto così fino a quel giorno. Vi fu gioia molto grande."],
[8018,"Si lesse il libro della legge di Dio ogni giorno, dal primo giorno fino all'ultimo giorno. Fecero festa per sette giorni e all'ottavo giorno si tenne una solenne assemblea, com'è prescritto."],
[9001,"Il ventiquattro dello stesso mese, gli Israeliti si radunarono per un digiuno, vestiti di sacchi e coperti di polvere."],
[9002,"I discendenti d'Israele si separarono da tutti gli stranieri e in piedi confessarono i loro peccati e le colpe dei loro padri."],
[9003,"Si alzarono in piedi e lessero il libro della legge del Signore, loro Dio, per un quarto della giornata; per un altro quarto essi confessarono i peccati e si prostrarono davanti al Signore, loro Dio."],
[9004,"Giosuè, Banì, Kadmiel, Sebania, Bunnì, Serebia, Banì e Chenanì salirono sulla pedana dei leviti e invocarono a gran voce il Signore, loro Dio."],
[9005,"I leviti Giosuè, Kadmiel, Banì, Casabnia, Serebia, Odia, Sebania e Petachia dissero: \"Alzatevi e benedite il Signore, vostro Dio, da sempre e per sempre! Benedicano il tuo nome glorioso, esaltato al di sopra di ogni benedizione e di ogni lode!"],
[9006,"Tu, tu solo sei il Signore, tu hai fatto i cieli, i cieli dei cieli e tutto il loro esercito, la terra e quanto sta su di essa, i mari e quanto è in essi; tu fai vivere tutte queste cose e l'esercito dei cieli ti adora."],
[9007,"Tu sei il Signore Dio, che hai scelto Abram, lo hai fatto uscire da Ur dei Caldei e lo hai chiamato Abramo."],
[9008,"Tu hai trovato il suo cuore fedele davanti a te e hai stabilito con lui un'alleanza, promettendo di dare la terra dei Cananei, degli Ittiti, degli Amorrei, dei Perizziti, dei Gebusei e dei Gergesei, di darla a lui e alla sua discendenza; hai mantenuto la tua parola, perché sei giusto."],
[9009,"Tu hai visto l'afflizione dei nostri padri in Egitto e hai ascoltato il loro grido presso il Mar Rosso;"],
[9010,"hai operato segni e prodigi contro il faraone, contro tutti i suoi servi, contro tutto il popolo della sua terra, perché sapevi che li avevano trattati con durezza, e ti sei fatto un nome che dura ancora oggi."],
[9011,"Hai aperto il mare davanti a loro ed essi sono passati in mezzo al mare sull'asciutto; quelli che li inseguivano hai precipitato nell'abisso, come una pietra in acque impetuose."],
[9012,"Li hai guidati di giorno con una colonna di nube e di notte con una colonna di fuoco, per rischiarare loro la strada su cui camminare."],
[9013,"Sei sceso sul monte Sinai e hai parlato con loro dal cielo, e hai dato loro norme giuste e leggi sicure, statuti e comandi buoni;"],
[9014,"hai fatto loro conoscere il tuo santo sabato e hai dato loro comandi, statuti e una legge per mezzo di Mosè, tuo servo."],
[9015,"Hai dato loro pane del cielo per la loro fame e hai fatto scaturire acqua dalla rupe per la loro sete, e hai detto loro di andare a prendere in possesso la terra che avevi giurato di dare loro."],
[9016,"Ma essi, i nostri padri, si sono comportati con superbia, hanno indurito la loro cervice e non hanno obbedito ai tuoi comandi."],
[9017,"Si sono rifiutati di obbedire e non si sono ricordati dei tuoi prodigi, che tu avevi operato in loro favore; hanno indurito la loro cervice e nella loro ribellione si sono dati un capo per tornare alla loro schiavitù. Ma tu sei un Dio pronto a perdonare, misericordioso e pietoso, lento all'ira e ricco di amore e non li hai abbandonati."],
[9018,"Anche quando si sono fatti un vitello di metallo fuso e hanno detto: \"Ecco il tuo Dio che ti ha fatto uscire dall'Egitto!\", e ti hanno insultato gravemente,"],
[9019,"tu nella tua grande misericordia, non li hai abbandonati nel deserto, non hai ritirato da loro la colonna di nube di giorno, per guidarli nel cammino, né la colonna di fuoco di notte, per rischiarare loro la strada su cui camminare."],
[9020,"Hai concesso loro il tuo spirito buono per istruirli e non hai rifiutato la tua manna alle loro bocche e hai dato loro l'acqua per la loro sete."],
[9021,"Per quarant'anni li hai nutriti nel deserto e non è mancato loro nulla; le loro vesti non si sono logorate e i loro piedi non si sono gonfiati."],
[9022,"Poi hai dato loro regni e popoli e li hai divisi definendone i confini; essi hanno posseduto la terra di Sicon e la terra del re di Chesbon e la terra di Og, re di Basan."],
[9023,"Hai moltiplicato i loro figli come le stelle del cielo e li hai introdotti nella terra nella quale avevi comandato ai loro padri di entrare per prenderne possesso."],
[9024,"I figli sono entrati e hanno preso in possesso la terra; tu hai umiliato dinanzi a loro gli abitanti della terra, i Cananei, e li hai messi nelle loro mani con i loro re e con i popoli della terra, perché ne disponessero a loro piacere."],
[9025,"Essi si sono impadroniti di città fortificate e di una terra grassa e hanno posseduto case piene di ogni bene, cisterne scavate, vigne, oliveti, alberi da frutto in abbondanza; hanno mangiato e si sono saziati e si sono ingrassati e sono vissuti nelle delizie per la tua grande bontà."],
[9026,"Ma poi hanno disobbedito, si sono ribellati contro di te, si sono gettati la tua legge dietro le spalle, hanno ucciso i tuoi profeti, che li ammonivano per farli tornare a te, e ti hanno insultato gravemente."],
[9027,"Perciò tu li hai messi nelle mani dei loro nemici, che li hanno oppressi. Ma nel tempo della loro angoscia essi hanno gridato a te e tu hai ascoltato dal cielo e, nella tua grande misericordia, tu hai dato loro salvatori, che li hanno salvati dalle mani dei loro nemici."],
[9028,"Ma quando avevano pace, ritornavano a fare il male dinanzi a te, perciò tu li abbandonavi nelle mani dei loro nemici, che li opprimevano; poi quando ricominciavano a gridare a te, tu ascoltavi dal cielo. Così nella tua misericordia più volte li hai liberati."],
[9029,"Tu li ammonivi per farli tornare alla tua legge, ma essi si mostravano superbi e non obbedivano ai tuoi comandi; peccavano contro i tuoi decreti, che fanno vivere chi li mette in pratica, offrivano spalle ribelli, indurivano la loro cervice e non obbedivano."],
[9030,"Hai pazientato con loro molti anni e li hai ammoniti con il tuo spirito per mezzo dei tuoi profeti; ma essi non hanno voluto prestare orecchio. Allora li hai messi nelle mani dei popoli di terre straniere."],
[9031,"Però, nella tua grande compassione, tu non li hai sterminati del tutto e non li hai abbandonati, perché sei un Dio misericordioso e pietoso."],
[9032,"Ora, o nostro Dio, Dio grande, potente e tremendo, che mantieni l'alleanza e la benevolenza, non sembri poca cosa ai tuoi occhi tutta la sventura che è piombata su di noi, sui nostri re, sui nostri capi, sui nostri sacerdoti, sui nostri profeti, sui nostri padri, su tutto il tuo popolo, dal tempo dei re d'Assiria fino ad oggi."],
[9033,"Tu sei giusto per tutto quello che ci è accaduto, poiché tu hai agito fedelmente, mentre noi ci siamo comportati da malvagi."],
[9034,"I nostri re, i nostri capi, i nostri sacerdoti, i nostri padri non hanno messo in pratica la tua legge e non hanno obbedito né ai comandi né agli ammonimenti con i quali tu li ammonivi."],
[9035,"Essi, mentre godevano del loro regno, del grande benessere che tu largivi loro e della terra vasta e fertile che tu avevi messo a loro disposizione, non ti hanno servito e non hanno abbandonato le loro azioni malvagie."],
[9036,"Oggi, eccoci schiavi; e quanto alla terra che tu hai concesso ai nostri padri, perché ne mangiassero i frutti e i beni, ecco, in essa siamo schiavi."],
[9037,"I suoi prodotti abbondanti sono per i re, che hai posto su di noi a causa dei nostri peccati e dispongono dei nostri corpi e del nostro bestiame a loro piacimento, e noi siamo in grande angoscia."],
[10001,"Tuttavia noi vogliamo sancire un patto e lo mettiamo per iscritto. Sul documento sigillato figurino i nostri capi, i nostri leviti e i nostri sacerdoti\"."],
[10002,"Sui documenti sigillati figuravano Neemia, il governatore, figlio di Acalia, e Sedecia,"],
[10003,"Seraià, Azaria, Geremia,"],
[10004,"Pascur, Amaria, Malchia,"],
[10005,"Cattus, Sebania, Malluc,"],
[10006,"Carim, Meremot, Abdia,"],
[10007,"Daniele, Ghinneton, Baruc,"],
[10008,"Mesullam, Abia, Miamin,"],
[10009,"Maazia, Bilgai, Semaià; questi erano i sacerdoti."],
[10010,"Leviti: Giosuè, figlio di Azania, Binnui dei figli di Chenadad, Kadmiel"],
[10011,"e i loro fratelli Sebania, Odia, Kelità, Pelaià, Canan,"],
[10012,"Mica, Recob, Casabia,"],
[10013,"Zaccur, Serebia, Sebania,"],
[10014,"Odia, Banì, Beninu."],
[10015,"Capi del popolo: Paros, Pacat-Moab, Elam, Zattu, Banì,"],
[10016,"Bunnì, Azgad, Bebai,"],
[10017,"Adonia, Bigvai, Adin,"],
[10018,"Ater, Ezechia, Azzur,"],
[10019,"Odia, Casum, Besai,"],
[10020,"Carif, Anatot, Nebai,"],
[10021,"Magpias, Mesullam, Chezir,"],
[10022,"Mesezabel, Sadoc, Iaddua,"],
[10023,"Pelatia, Canan, Anaià,"],
[10024,"Osea, Anania, Cassub,"],
[10025,"Alloches, Pilca, Sobek,"],
[10026,"Recum, Casabna, Maasia,"],
[10027,"Achia, Canan, Anan,"],
[10028,"Malluc, Carim, Baanà."],
[10029,"Il resto del popolo, i sacerdoti, i leviti, i portieri, i cantori, gli oblati e quanti si erano separati dai popoli di terre straniere per aderire alla legge di Dio, le loro mogli, i loro figli e le loro figlie, quanti potevano intendere,"],
[10030,"si unirono ai loro fratelli più ragguardevoli e fecero un patto e un giuramento di camminare nella legge di Dio, data per mezzo di Mosè, servo di Dio, promettendo di osservare e mettere in pratica tutti i comandi del Signore, il Signore nostro, le sue norme e le sue leggi."],
[10031,"E così non daremo le nostre figlie ai popoli della regione e non prenderemo le loro figlie per i nostri figli."],
[10032,"Dai popoli della regione, che portano le mercanzie e ogni genere di grano in giorno di sabato per venderli, non faremo acquisti di sabato o in un giorno santo. Lasceremo in riposo la terra ogni settimo anno e condoneremo ogni debito."],
[10033,"Ci siamo imposti per legge di dare ogni anno il terzo di un siclo per il servizio del tempio del nostro Dio:"],
[10034,"per i pani dell'offerta, per l'oblazione perenne, per l'olocausto perenne, nei sabati, nei noviluni, nelle feste, per le cose sacre, per i sacrifici per il peccato in vista dell'espiazione in favore d'Israele, e per ogni attività del tempio del nostro Dio."],
[10035,"Sacerdoti, leviti e popolo, abbiamo tirato a sorte per l'offerta della legna da portare al tempio del nostro Dio, secondo i nostri casati, a tempi fissi, anno per anno, per bruciarla sull'altare del Signore, nostro Dio, come sta scritto nella legge,"],
[10036,"e per portare ogni anno al tempio del Signore le primizie del nostro suolo e le primizie di ogni frutto di qualunque pianta,"],
[10037,"come anche i primogeniti dei nostri figli e del nostro bestiame, secondo quanto sta scritto nella legge, e i primi parti del nostro bestiame grosso e minuto, per portarli al tempio del nostro Dio e ai sacerdoti che prestano servizio nel tempio del nostro Dio."],
[10038,"Porteremo ai sacerdoti nelle stanze del tempio del nostro Dio le primizie della nostra farina, le nostre offerte, i frutti di qualunque albero, il vino e l'olio, e porteremo la decima del nostro suolo ai leviti. I leviti stessi preleveranno le decime in tutte le città del nostro lavoro."],
[10039,"Un sacerdote, figlio di Aronne, sarà con i leviti quando i leviti preleveranno le decime e i leviti porteranno la decima della decima al tempio del nostro Dio nelle stanze del tesoro,"],
[10040,"perché in quelle stanze i figli d'Israele e i figli di Levi devono portare l'offerta prelevata sul frumento, sul vino e sull'olio; in quel luogo stanno gli utensili del santuario, i sacerdoti che prestano il servizio, i portieri e i cantori. Non trascureremo il tempio del nostro Dio."],
[11001,"I capi del popolo si stabilirono a Gerusalemme; il resto del popolo tirò a sorte per far venire uno su dieci ad abitare a Gerusalemme, la città santa, e nove nelle altre città."],
[11002,"Il popolo benedisse quanti si erano offerti spontaneamente per abitare a Gerusalemme."],
[11003,"Questi sono i capi della provincia che si stabilirono a Gerusalemme, mentre nelle città di Giuda si stabilirono nelle rispettive città, ognuno nella sua proprietà, Israeliti, sacerdoti, leviti, oblati e i figli degli schiavi di Salomone."],
[11004,"A Gerusalemme si stabilirono figli di Giuda e figli di Beniamino. Dei figli di Giuda: Ataià, figlio di Ozia, figlio di Zaccaria, figlio di Amaria, figlio di Sefatia, figlio di Maalalel, dei figli di Peres;"],
[11005,"Maasia, figlio di Baruc, figlio di Col-Cozè, figlio di Cazaià, figlio di Adaià, figlio di Ioiarib, figlio di Zaccaria, figlio del Silonita."],
[11006,"Totale dei figli di Peres che si stabilirono a Gerusalemme: quattrocentosessantotto, uomini valorosi."],
[11007,"Questi sono i figli di Beniamino: Sallu, figlio di Mesullam, figlio di Ioed, figlio di Pedaià, figlio di Kolaià, figlio di Maasia, figlio di Itiel, figlio di Isaia"],
[11008,"e, dopo di lui, Gabbai, Sallai: novecentoventotto."],
[11009,"Gioele, figlio di Zicrì, era prefetto su di loro e Giuda, figlio di Assenuà, era il secondo sulla città."],
[11010,"Dei sacerdoti: Iedaià, figlio di Ioiarib, Iachin,"],
[11011,"Seraià, figlio di Chelkia, figlio di Mesullam, figlio di Sadoc, figlio di Meraiot, figlio di Achitub, preposto del tempio di Dio,"],
[11012,"e i loro fratelli addetti al lavoro del tempio, in numero di ottocentoventidue; Adaià, figlio di Ierocam, figlio di Pelalia, figlio di Amsì, figlio di Zaccaria, figlio di Pascur, figlio di Malchia,"],
[11013,"e i suoi fratelli, preposti di casato, in numero di duecentoquarantadue; Amassai, figlio di Azarel, figlio di Aczai, figlio di Mesillemot, figlio di Immer,"],
[11014,"e i loro fratelli, uomini valorosi, in numero di centoventotto; Zabdiel, figlio di Ghedolim, era prefetto su di loro."],
[11015,"Dei leviti: Semaià, figlio di Cassub, figlio di Azrikam, figlio di Casabia, figlio di Bunnì;"],
[11016,"Sabbetai e Iozabad al servizio esterno del tempio, fra i capi dei leviti;"],
[11017,"Mattania, figlio di Mica, figlio di Zabdì, figlio di Asaf, il capo che iniziava intonando la preghiera, e Bakbukia, secondo tra i suoi fratelli; Abda, figlio di Sammua, figlio di Galal, figlio di Iedutun."],
[11018,"Totale dei leviti nella città santa: duecentoottantaquattro."],
[11019,"Portieri: Akkub, Talmon e i loro fratelli, custodi delle porte: centosettantadue."],
[11020,"Il resto d'Israele, dei sacerdoti e dei leviti si stabilì in tutte le città di Giuda, ognuno nella sua eredità."],
[11021,"Gli oblati si stabilirono sull'Ofel, con Sica e Ghispa alla testa degli oblati."],
[11022,"Il prefetto dei leviti a Gerusalemme era Uzzì, figlio di Banì, figlio di Casabia, figlio di Mattania, figlio di Mica, dei figli di Asaf, i cantori per il servizio del tempio di Dio;"],
[11023,"vi era infatti una disposizione del re a loro riguardo e un ordine per i cantori, prescrizione per ogni giorno."],
[11024,"Petachia, figlio di Mesezabel, dei figli di Zerach, figlio di Giuda, suppliva il re per tutti gli affari del popolo."],
[11025,"Nei villaggi delle campagne, alcuni figli di Giuda si stabilirono a Kiriat-Arbà e nelle sue dipendenze, a Dibon e nelle sue dipendenze, a Iekabseel e nei suoi villaggi,"],
[11026,"a Iesua, a Moladà, a Bet-Pelet,"],
[11027,"a Casar-Sual, a Bersabea e nelle sue dipendenze,"],
[11028,"a Siklag, a Meconà e nelle sue dipendenze,"],
[11029,"a En-Rimmon, a Sorea, a Iarmut,"],
[11030,"a Zanoach, ad Adullam e nei loro villaggi, a Lachis e nelle sue campagne, ad Azekà e nelle sue dipendenze. Si insediarono da Bersabea fino alla valle di Innom."],
[11031,"I figli di Beniamino si stabilirono a Gheba, Micmas, Aià, Betel e sue dipendenze,"],
[11032,"ad Anatot, Nob, Anania,"],
[11033,"Asor, Rama, Ghittaim,"],
[11034,"Adid, Seboim, Neballat,"],
[11035,"Lod e Ono, nella valle degli Artigiani."],
[11036,"Dei leviti parte si stabilì con Giuda, parte con Beniamino."],
[12001,"Questi sono i sacerdoti e i leviti che tornarono con Zorobabele, figlio di Sealtiel, e con Giosuè: Seraià, Geremia, Esdra,"],
[12002,"Amaria, Malluc, Cattus,"],
[12003,"Secania, Recum, Meremot,"],
[12004,"Iddo, Ghinneton, Abia,"],
[12005,"Miamin, Maadia, Bilga,"],
[12006,"Semaià, Ioiarib, Iedaià,"],
[12007,"Sallu, Amok, Chelkia, Iedaià. Questi erano i capi dei sacerdoti e dei loro fratelli al tempo di Giosuè."],
[12008,"Leviti: Giosuè, Binnui, Kadmiel, Serebia, Giuda, Mattania, che era preposto agli inni con i suoi fratelli."],
[12009,"Bakbukia e Unnì, loro fratelli, si alternavano con loro secondo gli incarichi."],
[12010,"Giosuè generò Ioiakim, Ioiakim generò Eliasib, Eliasib generò Ioiadà,"],
[12011,"Ioiadà generò Gionata, Gionata generò Iaddua."],
[12012,"Al tempo di Ioiakim i sacerdoti capi di casato erano: del casato di Seraià, Meraià; di quello di Geremia, Anania;"],
[12013,"di quello di Esdra, Mesullam; di quello di Amaria, Giovanni;"],
[12014,"di quello di Melikù, Gionata; di quello di Sebania, Giuseppe;"],
[12015,"di quello di Carim, Adna; di quello di Meraiot, Chelkai;"],
[12016,"di quello di Iddo, Zaccaria; di quello di Ghinneton, Mesullam;"],
[12017,"di quello di Abia, Zicrì; di quello di Miniamin, ...; di quello di Moadia, Piltai;"],
[12018,"di quello di Bilga, Sammua; di quello di Semaià, Gionata;"],
[12019,"di quello di Ioiarib, Mattenai; di quello di Iedaià, Uzzì;"],
[12020,"di quello di Sallu, Kallai; di quello di Amok, Eber;"],
[12021,"di quello di Chelkia, Casabia; di quello di Iedaià, Netanel."],
[12022,"I leviti furono registrati, quanto ai capi di casato, al tempo di Eliasib, di Ioiadà, di Giovanni e di Iaddua; e i sacerdoti sotto il regno di Dario, il Persiano."],
[12023,"I leviti capi di casato furono registrati nel libro delle Cronache fino al tempo di Giovanni, figlio di Eliasib."],
[12024,"I capi dei leviti Casabia, Serebia, Giosuè, figlio di Kadmiel, e i loro fratelli si alternavano con loro per lodare e ringraziare, secondo l'ordine di Davide, uomo di Dio, turno per turno."],
[12025,"Mattania, Bakbukia, Abdia, Mesullam, Talmon, Akkub erano portieri e facevano la guardia ai magazzini delle porte."],
[12026,"Questi vivevano al tempo di Ioiakim, figlio di Giosuè, figlio di Iosadak, e al tempo di Neemia, il governatore, e di Esdra, sacerdote e scriba."],
[12027,"Per la dedicazione delle mura di Gerusalemme si mandarono a cercare i leviti da tutti i luoghi dove si trovavano, per farli venire a Gerusalemme, per celebrare la dedicazione con gioia, con azioni di grazie, con il canto, con cimbali, arpe e cetre."],
[12028,"I cantori si radunarono dal distretto intorno a Gerusalemme, dai villaggi dei Netofatiti,"],
[12029,"da Bet-Galgala e dal territorio di Gheba e di Azmavet, poiché i cantori si erano edificati villaggi nei dintorni di Gerusalemme."],
[12030,"I sacerdoti e i leviti si purificarono e purificarono il popolo, le porte e le mura."],
[12031,"Allora io feci salire sulle mura i capi di Giuda e formai due grandi cori. Il primo s'incamminò dal lato destro, sulle mura, verso la porta del Letame;"],
[12032,"dietro a loro camminavano Osea, metà dei capi di Giuda,"],
[12033,"Azaria, Esdra, Mesullam,"],
[12034,"Giuda, Beniamino, Semaià, Geremia,"],
[12035,"e dei sacerdoti con le trombe Zaccaria, figlio di Gionata, figlio di Semaià, figlio di Mattania, figlio di Michea, figlio di Zaccur, figlio di Asaf,"],
[12036,"e i suoi fratelli Semaià, Azarel, Milalai, Ghilalai, Maai, Netanel, Giuda, Anani, con gli strumenti musicali di Davide, uomo di Dio; lo scriba Esdra era davanti a loro."],
[12037,"E alla porta della Fonte e davanti a loro salirono per le scale della Città di Davide lungo la salita del muro, oltre la casa di Davide, fino alla porta delle Acque, a oriente."],
[12038,"Il secondo coro si incamminò a sinistra e io lo seguivo, con l'altra metà del popolo, sopra le mura, dalla torre dei Forni e fino al muro largo,"],
[12039,"e dalla porta di Èfraim alla porta Vecchia e alla porta dei Pesci, alla torre di Cananel e alla torre dei Cento, fino alla porta delle Pecore, e si fermarono alla porta della Prigione."],
[12040,"I due cori si fermarono nel tempio di Dio; così feci io, con la metà dei magistrati che si trovavano con me"],
[12041,"e i sacerdoti Eliakim, Maasia, Miniamin, Michea, Elioenai, Zaccaria, Anania con le trombe,"],
[12042,"e Maasia, Semaià, Eleazaro, Uzzì, Giovanni, Malchia, Elam, Ezer. I cantori facevano sentire la voce e Izrachia ne era il direttore."],
[12043,"In quel giorno il popolo offrì numerosi sacrifici e si rallegrò, perché Dio gli aveva concesso una grande gioia. Anche le donne e i fanciulli si rallegrarono e la gioia di Gerusalemme si sentiva di lontano."],
[12044,"In quel giorno, alcuni uomini furono preposti alle stanze dei magazzini delle offerte, delle primizie e delle decime, per raccogliervi, dalle campagne di ogni località, le parti assegnate dalla legge ai sacerdoti e ai leviti, poiché i Giudei gioivano per i sacerdoti e i leviti intenti alle funzioni:"],
[12045,"essi svolgevano il servizio del loro Dio e il servizio della purificazione, come i cantori e i portieri, secondo l'ordine di Davide e di Salomone, suo figlio."],
[12046,"Infatti, al tempo di Davide e di Asaf, in antico, vi erano capi cantori e canti di lode e di ringraziamento a Dio."],
[12047,"E tutto Israele, al tempo di Zorobabele e al tempo di Neemia, ogni giorno forniva le porzioni prescritte ai cantori e ai portieri e quelle consacrate ai leviti, i quali le davano ai figli di Aronne."],
[13001,"In quel giorno si lesse in presenza del popolo il libro di Mosè e vi si trovò scritto che l'Ammonita e il Moabita non dovevano mai entrare nella comunità di Dio,"],
[13002,"perché non erano venuti incontro agli Israeliti con il pane e l'acqua e perché, contro di loro, avevano pagato Balaam per maledirli, sebbene il nostro Dio avesse mutato la maledizione in benedizione."],
[13003,"Quando ebbero udito la legge, separarono da Israele tutti gli stranieri."],
[13004,"Prima di questo il sacerdote Eliasib, assegnato alle stanze del tempio del nostro Dio, parente di Tobia,"],
[13005,"aveva preparato per lui una camera grande dove, prima di allora, si riponevano le offerte, l'incenso, gli utensili, la decima del grano, del vino e dell'olio, spettanza di legge dei leviti, dei cantori, dei portieri, e il tributo per i sacerdoti."],
[13006,"Quando si faceva tutto questo, io non ero a Gerusalemme, perché nell'anno trentaduesimo di Artaserse, re di Babilonia, ero andato dal re; ma dopo qualche tempo, chiesi di congedarmi dal re,"],
[13007,"venni a Gerusalemme e mi accorsi del male che Eliasib aveva fatto in favore di Tobia, preparando per lui una stanza nei cortili del tempio di Dio."],
[13008,"La cosa mi dispiacque molto e feci gettare fuori dalla stanza tutti gli oggetti della casa di Tobia;"],
[13009,"poi ordinai che si purificassero quelle camere e vi feci tornare gli utensili del tempio di Dio, le offerte e l'incenso."],
[13010,"Seppi anche che le porzioni fissate per i leviti non erano state consegnate e che i leviti e i cantori, che prestavano il servizio, erano fuggiti ognuno al suo paese."],
[13011,"Allora rimproverai i magistrati e dissi loro: \"Perché il tempio di Dio è stato abbandonato?\". Poi li radunai e li ristabilii nei loro uffici."],
[13012,"Allora tutto Giuda portò ai magazzini la decima del frumento, del vino e dell'olio;"],
[13013,"incaricai dei magazzini il sacerdote Selemia, lo scriba Sadoc, Pedaià, uno dei leviti, e al loro fianco Canan, figlio di Zaccur, figlio di Mattania, perché erano reputati uomini fedeli. Così stava a loro fare le parti per i loro fratelli."],
[13014,"Ricordati per questo di me, o mio Dio, e non cancellare la fedeltà con cui ho agito per il tempio del mio Dio e per il suo servizio!"],
[13015,"In quei giorni osservai in Giuda alcuni che pigiavano nei tini durante il sabato, altri che trasportavano i covoni e li caricavano sugli asini, e anche vino, uva, fichi e ogni sorta di carichi, e li portavano a Gerusalemme in giorno di sabato; io protestai a motivo del giorno in cui vendevano le derrate."],
[13016,"C'erano anche alcuni di Tiro stabiliti in città che portavano pesce e ogni sorta di merci e le vendevano durante il sabato ai figli di Giuda e a Gerusalemme."],
[13017,"Allora io rimproverai i notabili di Giuda e dissi loro: \"Che cosa è mai questo male che fate, profanando il giorno del sabato?"],
[13018,"I nostri padri non hanno fatto così? Il nostro Dio per questo ha fatto cadere su noi e su questa città tutti questi mali. Voi accrescete l'ira contro Israele, profanando il sabato!\"."],
[13019,"Non appena le porte di Gerusalemme comiciavano a essere nell'ombra, prima del sabato, io ordinai che le porte fossero chiuse e che non si riaprissero fin dopo il sabato; collocai alcuni miei uomini alle porte: non doveva entrare nessun carico durante il sabato."],
[13020,"Così i mercanti e i venditori di ogni merce una o due volte passarono la notte fuori di Gerusalemme."],
[13021,"Allora io protestai contro di loro e dissi: \"Perché passate la notte davanti alle mura? Se lo farete un'altra volta, stenderò la mano contro di voi\". Da quel momento non vennero più durante il sabato."],
[13022,"Ordinai ai leviti di purificarsi e di venire a custodire le porte per santificare il giorno del sabato. Anche per questo ricordati di me, mio Dio, e abbi pietà di me secondo il tuo grande amore!"],
[13023,"In quei giorni vidi anche che alcuni Giudei si erano ammogliati con donne di Asdod, di Ammon e di Moab;"],
[13024,"la metà dei loro figli parlava l'asdodeo, nessuno di loro sapeva parlare giudaico, ma solo la lingua di un popolo o dell'altro."],
[13025,"Io li rimproverai, li maledissi, ne picchiai alcuni, strappai loro i capelli e li feci giurare su Dio: \"Non darete le vostre figlie ai loro figli e non prenderete le loro figlie per i vostri figli o per voi stessi."],
[13026,"Salomone, re d'Israele, non ha forse peccato appunto in questo? Certo, fra le molte nazioni non ci fu un re simile a lui: era amato dal suo Dio e Dio l'aveva fatto re di tutto Israele; eppure le donne straniere fecero peccare anche lui."],
[13027,"Dovremmo dunque ascoltare voi e fare tutto questo grande male e prevaricare contro il nostro Dio sposando donne straniere?\"."],
[13028,"Uno dei figli di Ioiadà, figlio di Eliasib, il sommo sacerdote, era genero di Sanballat, il Coronita; io lo cacciai via da me."],
[13029,"Ricordati di loro, mio Dio, poiché hanno profanato il sacerdozio e l'alleanza dei sacerdoti e dei leviti."],
[13030,"Così li purificai da ogni elemento straniero e ristabilii gli incarichi dei sacerdoti e dei leviti, ognuno al suo compito,"],
[13031,"quelli dell'offerta della legna ai tempi stabiliti, e delle primizie. Ricordati di me in bene, mio Dio!"]
])
