Bib.ret([
[1001,"Parola del Signore rivolta a Osea, figlio di Beerì, al tempo di Ozia, di Iotam, di Acaz, di Ezechia, re di Giuda, e al tempo di Geroboamo, figlio di Ioas, re d'Israele."],
[1002,"Quando il Signore cominciò a parlare a Osea, gli disse: \"Va', prenditi in moglie una prostituta, genera figli di prostituzione, poiché il paese non fa che prostituirsi allontanandosi dal Signore\"."],
[1003,"Egli andò a prendere Gomer, figlia di Diblaim: ella concepì e gli partorì un figlio."],
[1004,"E il Signore disse a Osea: \"Chiamalo Izreel, perché tra poco punirò la casa di Ieu per il sangue sparso a Izreel e porrò fine al regno della casa d'Israele."],
[1005,"In quel giorno io spezzerò l'arco d'Israele nella valle di Izreel\"."],
[1006,"La donna concepì di nuovo e partorì una figlia e il Signore disse a Osea: \"Chiamala Non-amata, perché non amerò più la casa d'Israele, non li perdonerò più."],
[1007,"Invece io amerò la casa di Giuda e li salverò nel Signore, loro Dio; non li salverò con l'arco, con la spada, con la guerra, né con cavalli o cavalieri\"."],
[1008,"Quando ebbe svezzato Non-amata, Gomer concepì e partorì un figlio."],
[1009,"E il Signore disse a Osea: \"Chiamalo Non-popolo-mio, perché voi non siete popolo mio e io per voi non sono."],
[2001,"Il numero degli Israeliti sarà come la sabbia del mare, che non si può misurare né contare. E avverrà che invece di dire loro: \"Voi non siete popolo mio\", si dirà loro: \"Siete figli del Dio vivente\"."],
[2002,"I figli di Giuda e i figli d'Israele si riuniranno insieme, si daranno un unico capo e saliranno dalla terra, perché grande sarà il giorno di Izreel!"],
[2003,"Dite ai vostri fratelli: \"Popolo mio\", e alle vostre sorelle: \"Amata\"."],
[2004,"Accusate vostra madre, accusatela, perché lei non è più mia moglie e io non sono più suo marito! Si tolga dalla faccia i segni delle sue prostituzioni e i segni del suo adulterio dal suo petto;"],
[2005,"altrimenti la spoglierò tutta nuda e la renderò simile a quando nacque, e la ridurrò a un deserto, come una terra arida, e la farò morire di sete."],
[2006,"I suoi figli non li amerò, perché sono figli di prostituzione."],
[2007,"La loro madre, infatti, si è prostituita, la loro genitrice si è coperta di vergogna, perché ha detto: \"Seguirò i miei amanti, che mi danno il mio pane e la mia acqua, la mia lana, il mio lino, il mio olio e le mie bevande\"."],
[2008,"Perciò ecco, ti chiuderò la strada con spine, la sbarrerò con barriere e non ritroverà i suoi sentieri."],
[2009,"Inseguirà i suoi amanti, ma non li raggiungerà, li cercherà senza trovarli. Allora dirà: \"Ritornerò al mio marito di prima, perché stavo meglio di adesso\"."],
[2010,"Non capì che io le davo grano, vino nuovo e olio, e la coprivo d'argento e d'oro, che hanno usato per Baal."],
[2011,"Perciò anch'io tornerò a riprendere il mio grano, a suo tempo, il mio vino nuovo nella sua stagione; porterò via la mia lana e il mio lino, che dovevano coprire le sue nudità."],
[2012,"Scoprirò allora le sue vergogne agli occhi dei suoi amanti e nessuno la toglierà dalle mie mani."],
[2013,"Farò cessare tutte le sue gioie, le feste, i noviluni, i sabati, tutte le sue assemblee solenni."],
[2014,"Devasterò le sue viti e i suoi fichi, di cui ella diceva: \"Ecco il dono che mi hanno dato i miei amanti\". Li ridurrò a una sterpaglia e a un pascolo di animali selvatici."],
[2015,"La punirò per i giorni dedicati ai Baal, quando bruciava loro i profumi, si adornava di anelli e di collane e seguiva i suoi amanti, mentre dimenticava me! Oracolo del Signore."],
[2016,"Perciò, ecco, io la sedurrò, la condurrò nel deserto e parlerò al suo cuore."],
[2017,"Le renderò le sue vigne e trasformerò la valle di Acor in porta di speranza. Là mi risponderà come nei giorni della sua giovinezza, come quando uscì dal paese d'Egitto."],
[2018,"E avverrà, in quel giorno - oracolo del Signore - mi chiamerai: \"Marito mio\", e non mi chiamerai più: \"Baal, mio padrone\"."],
[2019,"Le toglierò dalla bocca i nomi dei Baal e non saranno più chiamati per nome."],
[2020,"In quel tempo farò per loro un'alleanza con gli animali selvatici e gli uccelli del cielo e i rettili del suolo; arco e spada e guerra eliminerò dal paese, e li farò riposare tranquilli."],
[2021,"Ti farò mia sposa per sempre, ti farò mia sposa nella giustizia e nel diritto, nell'amore e nella benevolenza,"],
[2022,"ti farò mia sposa nella fedeltà e tu conoscerai il Signore."],
[2023,"E avverrà, in quel giorno - oracolo del Signore - io risponderò al cielo ed esso risponderà alla terra;"],
[2024,"la terra risponderà al grano, al vino nuovo e all'olio e questi risponderanno a Izreel."],
[2025,"Io li seminerò di nuovo per me nel paese e amerò Non-amata, e a Non-popolo-mio dirò: \"Popolo mio\", ed egli mi dirà: \"Dio mio\"\"."],
[3001,"Il Signore mi disse: \"Va' ancora, ama la tua donna: è amata dal marito ed è adultera, come il Signore ama i figli d'Israele ed essi si rivolgono ad altri dei e amano le schiacciate d'uva\"."],
[3002,"Io me l'acquistai per quindici pezzi d'argento e un  homer  e mezzo d'orzo"],
[3003,"e le dissi: \"Per molti giorni starai con me, non ti prostituirai e non sarai di alcun uomo; così anch'io mi comporterò con te\"."],
[3004,"Poiché per molti giorni staranno i figli d'Israele senza re e senza capo, senza sacrificio e senza stele, senza  efod  e senza  terafim."],
[3005,"Poi torneranno i figli d'Israele, e cercheranno il Signore, loro Dio, e Davide, loro re, e trepidi si volgeranno al Signore e ai suoi beni, alla fine dei giorni."],
[4001,"\"Ascoltate la parola del Signore, o figli d'Israele, perché il Signore è in causa con gli abitanti del paese. Non c'è infatti sincerità né amore, né conoscenza di Dio nel paese."],
[4002,"Si spergiura, si dice il falso, si uccide, si ruba, si commette adulterio, tutto questo dilaga e si versa sangue su sangue."],
[4003,"Per questo è in lutto il paese e chiunque vi abita langue, insieme con gli animali selvatici e con gli uccelli del cielo; persino i pesci del mare periscono."],
[4004,"Ma nessuno accusi, nessuno contesti; contro di te, sacerdote, muovo l'accusa."],
[4005,"Tu inciampi di giorno e anche il profeta con te inciampa di notte e farò perire tua madre."],
[4006,"Perisce il mio popolo per mancanza di conoscenza. Poiché tu rifiuti la conoscenza, rifiuterò te come mio sacerdote; hai dimenticato la legge del tuo Dio e anch'io dimenticherò i tuoi figli."],
[4007,"Tutti hanno peccato contro di me; cambierò la loro gloria in ignominia."],
[4008,"Essi si nutrono del peccato del mio popolo e sono avidi della sua iniquità."],
[4009,"Il popolo e il sacerdote avranno la stessa sorte; li punirò per la loro condotta e li ripagherò secondo le loro azioni."],
[4010,"Mangeranno, ma non si sazieranno, si prostituiranno, ma non aumenteranno, perché hanno abbandonato il Signore per darsi"],
[4011,"alla prostituzione. Il vino vecchio e quello nuovo tolgono il senno."],
[4012,"Il mio popolo consulta il suo pezzo di legno e il suo bastone gli dà il responso, poiché uno spirito di prostituzione li svia e si prostituiscono, allontanandosi dal loro Dio."],
[4013,"Sulla cima dei monti fanno sacrifici e sui colli bruciano incensi sotto la quercia, i pioppi e i terebinti, perché buona è la loro ombra. Perciò si prostituiscono le vostre figlie e le vostre nuore commettono adulterio."],
[4014,"Non punirò le vostre figlie se si prostituiscono, né le vostre nuore se commettono adulterio; poiché essi stessi si appartano con le prostitute e con le prostitute sacre offrono sacrifici. Un popolo, che non comprende, va in rovina!"],
[4015,"Se ti prostituisci tu, Israele, non si renda colpevole Giuda. Non andate a Galgala, non salite a Bet-Aven, non giurate per il Signore vivente."],
[4016,"E poiché come giovenca ribelle si ribella Israele, forse potrà pascolarlo il Signore come agnello in luoghi aperti?"],
[4017,"Èfraim si è alleato agli idoli:"],
[4018,"dopo essersi ubriacati si sono dati alla prostituzione, hanno preferito il disonore alla loro gloria."],
[4019,"Un vento li travolgerà con le sue ali e si vergogneranno dei loro sacrifici."],
[5001,"Ascoltate questo, o sacerdoti, state attenti, casa d'Israele, o casa del re, porgete l'orecchio, perché a voi toccava esercitare la giustizia; voi foste infatti un laccio a Mispa, una rete tesa sul Tabor"],
[5002,"e una fossa profonda a Sittim. Ma io correggerò tutti costoro."],
[5003,"Io conosco Èfraim e non mi è ignoto Israele. Ti sei prostituito, Èfraim! Si è reso impuro Israele."],
[5004,"Le loro azioni non permettono di fare ritorno al loro Dio, perché uno spirito di prostituzione è fra loro e non conoscono il Signore."],
[5005,"L'arroganza d'Israele testimonia contro di lui, Israele ed Èfraim inciamperanno per le loro colpe e Giuda inciamperà con loro."],
[5006,"Con le loro greggi e i loro armenti andranno in cerca del Signore, ma non lo troveranno: egli si è allontanato da loro."],
[5007,"Sono stati infedeli verso il Signore, generando figli bastardi: la nuova luna li divorerà insieme con i loro campi."],
[5008,"Suonate il corno a Gabaa e la tromba a Rama, date l'allarme a Bet-Aven, all'erta, Beniamino!"],
[5009,"Èfraim sarà devastato nel giorno del castigo: per le tribù d'Israele annuncio una cosa sicura."],
[5010,"I capi di Giuda sono diventati come quelli che spostano i confini e su di loro come acqua verserò la mia ira."],
[5011,"Èfraim è schiacciato dal giudizio, da quando ha cominciato a inseguire il nulla."],
[5012,"Ma io sarò come una tignola per Èfraim, e come un tarlo per la casa di Giuda."],
[5013,"Èfraim ha visto la sua infermità e Giuda la sua piaga. Èfraim è ricorso all'Assiria e Giuda si è rivolto al gran re; ma egli non potrà curarvi, non guarirà la vostra piaga,"],
[5014,"perché io sarò come un leone per Èfraim, come un leoncello per la casa di Giuda. Io li sbranerò e me ne andrò, porterò via la preda e nessuno me la toglierà."],
[5015,"Me ne ritornerò alla mia dimora, finché non sconteranno la pena e cercheranno il mio volto, e ricorreranno a me nella loro angoscia."],
[6001,"\"Venite, ritorniamo al Signore: egli ci ha straziato ed egli ci guarirà. Egli ci ha percosso ed egli ci fascerà."],
[6002,"Dopo due giorni ci ridarà la vita e il terzo ci farà rialzare, e noi vivremo alla sua presenza."],
[6003,"Affrettiamoci a conoscere il Signore, la sua venuta è sicura come l'aurora. Verrà a noi come la pioggia d'autunno, come la pioggia di primavera che feconda la terra\"."],
[6004,"Che dovrò fare per te, Èfraim, che dovrò fare per te, Giuda? Il vostro amore è come una nube del mattino, come la rugiada che all'alba svanisce."],
[6005,"Per questo li ho abbattuti per mezzo dei profeti, li ho uccisi con le parole della mia bocca e il mio giudizio sorge come la luce:"],
[6006,"poiché voglio l'amore e non il sacrificio, la conoscenza di Dio più degli olocausti."],
[6007,"Ma essi come Adamo hanno violato l'alleanza; ecco, così mi hanno tradito."],
[6008,"Galaad è una città di malfattori, macchiata di sangue."],
[6009,"Come banditi in agguato una ciurma di sacerdoti assale e uccide sulla strada di Sichem, commette scelleratezze."],
[6010,"Orribili cose ho visto a Betel; là si è prostituito Èfraim, si è reso immondo Israele."],
[6011,"Anche a te, Giuda, io riserbo una mietitura, quando ristabilirò la sorte del mio popolo."],
[7001,"Mentre sto per guarire Israele, si scopre l'iniquità di Èfraim e la malvagità di Samaria, perché si pratica la menzogna: il ladro entra nelle case e fuori saccheggia il brigante."],
[7002,"Non pensano, dunque, che io ricordo tutte le loro malvagità? Ora sono circondati dalle loro azioni: esse stanno davanti a me."],
[7003,"Con la loro malvagità rallegrano il re, rallegrano i capi con le loro falsità."],
[7004,"Sono tutti adulteri, ardono come un forno in cui il fornaio non attizza più il fuoco, in attesa che la pasta preparata lieviti."],
[7005,"Nel giorno della festa del nostro re sommergono i capi in fiumi di vino, fino a far sì che egli si comprometta con i ribelli."],
[7006,"Perché il loro intimo è come un forno, pieno di trame è il loro cuore, tutta la notte sonnecchia il loro furore e al mattino divampa come fiamma."],
[7007,"Tutti ardono come un forno e divorano i loro governanti. Così sono caduti tutti i loro sovrani e nessuno si preoccupa di ricorrere a me."],
[7008,"Èfraim si mescola con le genti, Èfraim è come una focaccia non rivoltata."],
[7009,"Gli stranieri divorano la sua forza ed egli non se ne accorge; la canizie gli ricopre la testa ed egli non se ne accorge."],
[7010,"L'arroganza d'Israele testimonia contro di loro; non ritornano al Signore, loro Dio, e, malgrado tutto, non lo ricercano."],
[7011,"Èfraim è come un'ingenua colomba, priva d'intelligenza; ora i suoi abitanti domandano aiuto all'Egitto, ora invece corrono verso l'Assiria."],
[7012,"Dovunque si rivolgeranno stenderò la mia rete contro di loro e li abbatterò come gli uccelli dell'aria, li punirò non appena li udrò riunirsi."],
[7013,"Disgrazia per loro, perché si sono allontanati da me! Distruzione per loro, perché hanno agito male contro di me! Li volevo salvare, ma essi hanno proferito menzogne contro di me."],
[7014,"Non gridano a me con il loro cuore quando gridano sui loro giacigli. Si fanno incisioni per il grano e il vino nuovo e intanto si ribellano contro di me."],
[7015,"Eppure io ho addestrato il loro braccio, ma essi hanno tramato il male contro di me."],
[7016,"Si sono rivolti, ma non a colui che è in alto, sono stati come un arco fallace. I loro capi cadranno di spada per l'insolenza della loro lingua e nella terra d'Egitto rideranno di loro."],
[8001,"Da' fiato al corno! Come un'aquila piomba sulla casa del Signore la sciagura perché hanno trasgredito la mia alleanza e rigettato la mia legge."],
[8002,"Essi gridano verso di me: \"Noi, Israele, riconosciamo te nostro Dio!\"."],
[8003,"Ma Israele ha rigettato il bene: il nemico lo perseguiterà."],
[8004,"Hanno creato dei re che io non ho designati; hanno scelto capi a mia insaputa. Con il loro argento e il loro oro si sono fatti idoli, ma per loro rovina."],
[8005,"Ripudio il tuo vitello, o Samaria! La mia ira divampa contro di loro; fino a quando non si potranno purificare?"],
[8006,"Viene da Israele il vitello di Samaria, è opera di artigiano, non è un dio: sarà ridotto in frantumi."],
[8007,"E poiché hanno seminato vento, raccoglieranno tempesta. Il loro grano sarà senza spiga, se germoglia non darà farina e, se ne produce, la divoreranno gli stranieri."],
[8008,"Israele è stato inghiottito: si trova ora in mezzo alle nazioni come un oggetto senza valore."],
[8009,"Essi sono saliti fino ad Assur, sono come un asino selvatico, che si aggira solitario; Èfraim si è acquistato degli amanti."],
[8010,"Se ne acquistino pure fra le nazioni, io li metterò insieme e cominceranno a diminuire sotto il peso del re e dei principi."],
[8011,"Èfraim ha moltiplicato gli altari, ma gli altari sono diventati per lui un'occasione di peccato."],
[8012,"Ho scritto numerose leggi per lui, ma esse sono considerate come qualcosa di estraneo."],
[8013,"Offrono sacrifici e ne mangiano le carni, ma il Signore non li gradisce; ora ricorda la loro iniquità, chiede conto dei loro peccati: dovranno tornare in Egitto."],
[8014,"Israele ha dimenticato il suo creatore, si è costruito palazzi; Giuda ha moltiplicato le sue città fortificate. Ma io appiccherò il fuoco alle loro città e divorerà i loro palazzi."],
[9001,"Israele, non rallegrarti fino all'esultanza come gli altri popoli, perché hai praticato la prostituzione, abbandonando il tuo Dio, hai amato il compenso della tua prostituzione su tutte le aie per il grano."],
[9002,"L'aia e il tino non li nutriranno e il vino nuovo verrà loro a mancare."],
[9003,"Non potranno restare nella terra del Signore, ma Èfraim ritornerà in Egitto e in Assiria mangeranno cibi impuri."],
[9004,"Non faranno più libagioni di vino al Signore, non gli saranno graditi i loro sacrifici, saranno per loro come pane di lutto: quanti ne mangiano diventano impuri. Il loro pane sarà tutto per loro, ma non entrerà nella casa del Signore."],
[9005,"Che cosa farete nei giorni delle solennità, nei giorni della festa del Signore?"],
[9006,"Ecco, sono sfuggiti alla rovina, l'Egitto li accoglierà, Menfi sarà la loro tomba. I loro tesori d'argento passeranno alle ortiche e nelle loro tende cresceranno i cardi."],
[9007,"Sono venuti i giorni del castigo, sono giunti i giorni del rendiconto, Israele lo sappia! Il profeta diventa pazzo, l'uomo ispirato vaneggia a causa delle tue molte iniquità, per la gravità del tuo affronto."],
[9008,"Sentinella di Èfraim è il profeta con il suo Dio; ma un laccio gli è teso su tutti i sentieri, ostilità fin nella casa del suo Dio."],
[9009,"Sono corrotti fino in fondo, come ai giorni di Gabaa; ma egli si ricorderà della loro iniquità, chiederà conto dei loro peccati."],
[9010,"Trovai Israele come uva nel deserto, ebbi riguardo per i vostri padri, come per i primi fichi quando iniziano a maturare; ma essi, appena arrivati a Baal-Peor, si consacrarono a quell'infamia e divennero una cosa abominevole, come ciò che essi amavano."],
[9011,"La gloria di Èfraim volerà via come un uccello, non più nascite né gravidanze né concepimenti."],
[9012,"Anche se allevano figli, io li eliminerò dagli uomini; guai a loro, se io li abbandono."],
[9013,"Èfraim, lo vedo come una palma piantata in luoghi verdeggianti. Èfraim tuttavia condurrà i figli al macello."],
[9014,"\"Signore, da' loro. Che cosa darai?\". Un grembo infecondo e un seno arido!"],
[9015,"Tutta la loro perversità si è manifestata a Galgala, è là che ho preso a odiarli. Per la malvagità delle loro azioni li scaccerò dalla mia casa, non avrò più amore per loro; tutti i loro capi sono ribelli."],
[9016,"Èfraim è stato percosso, la loro radice è inaridita, non daranno più frutto. Anche se generano, farò perire i cari frutti del loro grembo\"."],
[9017,"Il mio Dio li respingerà, perché non gli hanno obbedito; andranno raminghi fra le nazioni."],
[10001,"Vite rigogliosa era Israele, che dava sempre il suo frutto; ma più abbondante era il suo frutto, più moltiplicava gli altari; più ricca era la terra, più belle faceva le sue stele."],
[10002,"Il loro cuore è falso; orbene, sconteranno la pena! Egli stesso demolirà i loro altari, distruggerà le loro stele."],
[10003,"Allora diranno: \"Non abbiamo più re, perché non rispettiamo il Signore. Ma anche il re, che cosa potrebbe fare per noi?\"."],
[10004,"Dicono parole vane, giurano il falso, concludono alleanze: il diritto fiorisce come pianta velenosa nei solchi dei campi."],
[10005,"Gli abitanti di Samaria trepidano per il vitello di Bet-Aven; è in lutto il suo popolo e i suoi sacerdoti ne fanno lamento, perché la sua gloria sta per andarsene."],
[10006,"Sarà portato anch'esso in Assiria come offerta al gran re. Èfraim ne avrà vergogna, Israele arrossirà per i suoi intrighi."],
[10007,"Perirà Samaria con il suo re, come un fuscello sull'acqua."],
[10008,"Le alture dell'iniquità, peccato d'Israele, saranno distrutte, spine e cardi cresceranno sui loro altari; diranno ai monti: \"Copriteci\" e ai colli: \"Cadete su di noi\"."],
[10009,"Fin dai giorni di Gabaa tu hai peccato, Israele. Là si fermarono, e la battaglia non li raggiungerà forse a Gabaa contro i figli dell'iniquità?"],
[10010,"\"Io voglio colpirli: si raduneranno i popoli contro di loro, perché sono attaccati alla loro duplice colpa."],
[10011,"Èfraim è una giovenca addestrata, cui piace trebbiare il grano. Ma io farò pesare il giogo sul suo bel collo; attaccherò Èfraim all'aratro e Giacobbe all'erpice."],
[10012,"Seminate per voi secondo giustizia e mieterete secondo bontà; dissodatevi un campo nuovo, perché è tempo di cercare il Signore, finché egli venga e diffonda su di voi la giustizia."],
[10013,"Avete arato empietà e mietuto ingiustizia, avete mangiato il frutto della menzogna. Poiché hai riposto fiducia nella tua forza e nella moltitudine dei tuoi guerrieri,"],
[10014,"un rumore di guerra si alzerà contro il tuo popolo e tutte le tue fortezze saranno distrutte. Come Salman devastò Bet-Arbel nel giorno della battaglia in cui la madre fu sfracellata sui figli,"],
[10015,"così sarà fatto a te, casa d'Israele, per la tua enorme malvagità. All'alba sarà la fine del re d'Israele."],
[11001,"Quando Israele era fanciullo, io l'ho amato e dall'Egitto ho chiamato mio figlio."],
[11002,"Ma più li chiamavo, più si allontanavano da me; immolavano vittime ai Baal, agli idoli bruciavano incensi."],
[11003,"A Èfraim io insegnavo a camminare tenendolo per mano, ma essi non compresero che avevo cura di loro."],
[11004,"Io li traevo con legami di bontà, con vincoli d'amore, ero per loro come chi solleva un bimbo alla sua guancia, mi chinavo su di lui per dargli da mangiare."],
[11005,"Non ritornerà al paese d'Egitto, ma Assur sarà il suo re, perché non hanno voluto convertirsi."],
[11006,"La spada farà strage nelle loro città, spaccherà la spranga di difesa, l'annienterà al di là dei loro progetti."],
[11007,"Il mio popolo è duro a convertirsi: chiamato a guardare in alto, nessuno sa sollevare lo sguardo."],
[11008,"Come potrei abbandonarti, Èfraim, come consegnarti ad altri, Israele? Come potrei trattarti al pari di Adma, ridurti allo stato di Seboim? Il mio cuore si commuove dentro di me, il mio intimo freme di compassione."],
[11009,"Non darò sfogo all'ardore della mia ira, non tornerò a distruggere Èfraim, perché sono Dio e non uomo; sono il Santo in mezzo a te e non verrò da te nella mia ira."],
[11010,"Seguiranno il Signore ed egli ruggirà come un leone: quando ruggirà, accorreranno i suoi figli dall'occidente,"],
[11011,"accorreranno come uccelli dall'Egitto, come colombe dall'Assiria e li farò abitare nelle loro case. Oracolo del Signore."],
[12001,"Èfraim mi raggira con menzogne e la casa d'Israele con frode. Ma Giuda è ancora con Dio e resta fedele al Santo\"."],
[12002,"Èfraim si pasce di vento e insegue il vento d'oriente, ogni giorno moltiplica menzogne e violenze; fanno alleanze con l'Assiria e portano olio in Egitto."],
[12003,"Il Signore è in causa con Giuda e punirà Giacobbe per la sua condotta, lo ripagherà secondo le sue azioni."],
[12004,"Egli nel grembo materno soppiantò il fratello e da adulto lottò con Dio,"],
[12005,"lottò con l'angelo e vinse, pianse e domandò grazia. Lo ritrovò a Betel e là gli parlò."],
[12006,"Signore, Dio degli eserciti, Signore è il nome con cui celebrarlo."],
[12007,"Tu ritorna al tuo Dio, osserva la bontà e la giustizia e poni sempre nel tuo Dio la tua speranza."],
[12008,"Canaan tiene in mano bilance false, ama frodare."],
[12009,"Èfraim ha detto: \"Sono ricco, mi sono fatto una fortuna; malgrado tutti i miei guadagni, non troveranno in me una colpa che sia peccato\"."],
[12010,"\"Eppure io sono il Signore, tuo Dio, fin dal paese d'Egitto. Ti farò ancora abitare sotto le tende, come ai giorni dell'incontro nel deserto."],
[12011,"Io parlerò ai profeti, moltiplicherò le visioni e per mezzo dei profeti parlerò con parabole\"."],
[12012,"Se Galaad è una iniquità, i suoi abitanti non sono che menzogna; in Galgala si sacrifica ai tori, perciò i loro altari saranno come mucchi di pietre nei solchi dei campi."],
[12013,"Giacobbe fuggì nella regione di Aram, Israele prestò servizio per una donna e per una donna fece il guardiano di bestiame."],
[12014,"Per mezzo di un profeta il Signore fece uscire Israele dall'Egitto, e per mezzo di un profeta lo custodì."],
[12015,"Èfraim provocò Dio amaramente, il Signore gli farà ricadere addosso il sangue versato e lo ripagherà della sua offesa."],
[13001,"Quando Èfraim parlava, incuteva terrore, era un principe in Israele. Ma si è reso colpevole con Baal ed è decaduto."],
[13002,"Tuttavia continuano a peccare e con il loro argento si sono fatti statue fuse, idoli di loro invenzione, tutti lavori di artigiani. Dicono: \"Offrite loro sacrifici\" e mandano baci ai vitelli."],
[13003,"Perciò saranno come nube del mattino, come rugiada che all'alba svanisce, come pula lanciata lontano dall'aia, come fumo che esce dalla finestra."],
[13004,"\"Eppure io sono il Signore, tuo Dio, fin dal paese d'Egitto, non devi conoscere altro Dio fuori di me, non c'è salvatore fuori di me."],
[13005,"Io ti ho protetto nel deserto, in quella terra ardente."],
[13006,"Io li ho fatti pascolare, si sono saziati e il loro cuore si è inorgoglito, per questo mi hanno dimenticato."],
[13007,"Perciò io sarò per loro come un leone, come un leopardo li spierò per la via,"],
[13008,"li assalirò come un'orsa privata dei figli, spezzerò la corazza del loro cuore, li divorerò come una leonessa; li sbraneranno le bestie selvatiche."],
[13009,"Israele, tu sei rovinata e solo io ti posso aiutare!"],
[13010,"Dov'è ora il tuo re, che ti possa salvare? Dove sono i capi in tutte le tue città e i governanti di cui dicevi: \"Dammi un re e dei capi\"?"],
[13011,"Ti ho dato un re nella mia ira e con sdegno te lo riprendo."],
[13012,"L'iniquità di Èfraim è chiusa in luogo sicuro, il suo peccato è ben custodito."],
[13013,"I dolori di partoriente lo sorprenderanno, ma egli è figlio privo di senno, non si presenterà a suo tempo pronto a uscire dal seno materno."],
[13014,"Li strapperò di mano agli inferi, li riscatterò dalla morte? Dov'è, o morte, la tua peste? Dov'è, o inferi, il vostro sterminio? La compassione è nascosta ai miei occhi\"."],
[13015,"Èfraim prosperi pure in mezzo ai fratelli: verrà il vento d'oriente, si alzerà dal deserto il vento del Signore e farà inaridire le sue sorgenti, farà prosciugare le sue fonti, distruggerà il tesoro e ogni oggetto prezioso."],
[14001,"Samaria sconterà la sua pena, perché si è ribellata al suo Dio. Periranno di spada, saranno sfracellati i bambini; le donne incinte sventrate."],
[14002,"Torna dunque, Israele, al Signore, tuo Dio, poiché hai inciampato nella tua iniquità."],
[14003,"Preparate le parole da dire e tornate al Signore; ditegli: \"Togli ogni iniquità, accetta ciò che è bene: non offerta di tori immolati, ma la lode delle nostre labbra."],
[14004,"Assur non ci salverà, non cavalcheremo più su cavalli, né chiameremo più \"dio nostro\" l'opera delle nostre mani, perché presso di te l'orfano trova misericordia\"."],
[14005,"\"Io li guarirò dalla loro infedeltà, li amerò profondamente, poiché la mia ira si è allontanata da loro."],
[14006,"Sarò come rugiada per Israele; fiorirà come un giglio e metterà radici come un albero del Libano,"],
[14007,"si spanderanno i suoi germogli e avrà la bellezza dell'olivo e la fragranza del Libano."],
[14008,"Ritorneranno a sedersi alla mia ombra, faranno rivivere il grano, fioriranno come le vigne, saranno famosi come il vino del Libano."],
[14009,"Che ho ancora in comune con gli idoli, o Èfraim? Io l'esaudisco e veglio su di lui; io sono come un cipresso sempre verde, il tuo frutto è opera mia\"."],
[14010,"Chi è saggio comprenda queste cose, chi ha intelligenza le comprenda; poiché rette sono le vie del Signore, i giusti camminano in esse, mentre i malvagi v'inciampano."]
])
