Bib.ret([
[1001,"Proverbi di Salomone, figlio di Davide, re d'Israele,"],
[1002,"per conoscere la sapienza e l'istruzione, per capire i detti intelligenti,"],
[1003,"per acquistare una saggia educazione, equità, giustizia e rettitudine,"],
[1004,"per rendere accorti gli inesperti e dare ai giovani conoscenza e riflessione."],
[1005,"Il saggio ascolti e accrescerà il sapere, e chi è avveduto acquisterà destrezza,"],
[1006,"per comprendere proverbi e allegorie, le massime dei saggi e i loro enigmi."],
[1007,"Il timore del Signore è principio della scienza; gli stolti disprezzano la sapienza e l'istruzione."],
[1008,"Ascolta, figlio mio, l'istruzione di tuo padre e non disprezzare l'insegnamento di tua madre,"],
[1009,"perché saranno corona graziosa sul tuo capo e monili per il tuo collo."],
[1010,"Figlio mio, se i malvagi ti vogliono sedurre, tu non acconsentire!"],
[1011,"Se ti dicono: \"Vieni con noi, complottiamo per spargere sangue, insidiamo senza motivo l'innocente,"],
[1012,"inghiottiamoli vivi come fa il regno dei morti, interi, come coloro che scendono nella fossa;"],
[1013,"troveremo ogni specie di beni preziosi, riempiremo di bottino le nostre case,"],
[1014,"tu tirerai a sorte la tua parte insieme con noi, una sola borsa avremo in comune\","],
[1015,"figlio mio, non andare per la loro strada, tieniti lontano dai loro sentieri!"],
[1016,"I loro passi infatti corrono verso il male e si affrettano a spargere sangue."],
[1017,"Invano si tende la rete sotto gli occhi di ogni sorta di uccelli."],
[1018,"Ma costoro complottano contro il proprio sangue, pongono agguati contro se stessi."],
[1019,"Tale è la fine di chi è avido di guadagno; la cupidigia toglie di mezzo colui che ne è dominato."],
[1020,"La sapienza grida per le strade, nelle piazze fa udire la voce;"],
[1021,"nei clamori della città essa chiama, pronuncia i suoi detti alle porte della città:"],
[1022,"\"Fino a quando, o inesperti, amerete l'inesperienza e gli spavaldi si compiaceranno delle loro spavalderie e gli stolti avranno in odio la scienza?"],
[1023,"Tornate alle mie esortazioni: ecco, io effonderò il mio spirito su di voi e vi manifesterò le mie parole."],
[1024,"Perché vi ho chiamati ma avete rifiutato, ho steso la mano e nessuno se ne è accorto."],
[1025,"Avete trascurato ogni mio consiglio e i miei rimproveri non li avete accolti;"],
[1026,"anch'io riderò delle vostre sventure, mi farò beffe quando su di voi verrà la paura,"],
[1027,"quando come una tempesta vi piomberà addosso il terrore, quando la disgrazia vi raggiungerà come un uragano, quando vi colpiranno angoscia e tribolazione."],
[1028,"Allora mi invocheranno, ma io non risponderò, mi cercheranno, ma non mi troveranno."],
[1029,"Perché hanno odiato la sapienza e non hanno preferito il timore del Signore,"],
[1030,"non hanno accettato il mio consiglio e hanno disprezzato ogni mio rimprovero;"],
[1031,"mangeranno perciò il frutto della loro condotta e si sazieranno delle loro trame."],
[1032,"Sì, lo smarrimento degli inesperti li ucciderà e la spensieratezza degli sciocchi li farà perire;"],
[1033,"ma chi ascolta me vivrà in pace e sarà sicuro senza temere alcun male\"."],
[2001,"Figlio mio, se tu accoglierai le mie parole e custodirai in te i miei precetti,"],
[2002,"tendendo il tuo orecchio alla sapienza, inclinando il tuo cuore alla prudenza,"],
[2003,"se appunto invocherai l'intelligenza e rivolgerai la tua voce alla prudenza,"],
[2004,"se la ricercherai come l'argento e per averla scaverai come per i tesori,"],
[2005,"allora comprenderai il timore del Signore e troverai la conoscenza di Dio,"],
[2006,"perché il Signore dà la sapienza, dalla sua bocca escono scienza e prudenza."],
[2007,"Egli riserva ai giusti il successo, è scudo a coloro che agiscono con rettitudine,"],
[2008,"vegliando sui sentieri della giustizia e proteggendo le vie dei suoi fedeli."],
[2009,"Allora comprenderai l'equità e la giustizia, la rettitudine e tutte le vie del bene,"],
[2010,"perché la sapienza entrerà nel tuo cuore e la scienza delizierà il tuo animo."],
[2011,"La riflessione ti custodirà e la prudenza veglierà su di te,"],
[2012,"per salvarti dalla via del male, dall'uomo che parla di propositi perversi,"],
[2013,"da coloro che abbandonano i retti sentieri per camminare nelle vie delle tenebre,"],
[2014,"che godono nel fare il male e gioiscono dei loro propositi perversi,"],
[2015,"i cui sentieri sono tortuosi e le cui strade sono distorte;"],
[2016,"per salvarti dalla donna straniera, dalla sconosciuta che ha parole seducenti,"],
[2017,"che abbandona il compagno della sua giovinezza e dimentica l'alleanza con il suo Dio."],
[2018,"La sua casa conduce verso la morte e verso il regno delle ombre i suoi sentieri."],
[2019,"Quanti vanno da lei non fanno ritorno, non raggiungono i sentieri della vita."],
[2020,"In tal modo tu camminerai sulla strada dei buoni e rimarrai nei sentieri dei giusti,"],
[2021,"perché gli uomini retti abiteranno nel paese e gli integri vi resteranno,"],
[2022,"i malvagi invece saranno sterminati dalla terra e i perfidi ne saranno sradicati."],
[3001,"Figlio mio, non dimenticare il mio insegnamento e il tuo cuore custodisca i miei precetti,"],
[3002,"perché lunghi giorni e anni di vita e tanta pace ti apporteranno."],
[3003,"Bontà e fedeltà non ti abbandonino: legale attorno al tuo collo, scrivile sulla tavola del tuo cuore,"],
[3004,"e otterrai favore e buon successo agli occhi di Dio e degli uomini."],
[3005,"Confida nel Signore con tutto il tuo cuore e non affidarti alla tua intelligenza;"],
[3006,"riconoscilo in tutti i tuoi passi  ed egli appianerà i tuoi sentieri."],
[3007,"Non crederti saggio ai tuoi occhi, temi il Signore e sta' lontano dal male:"],
[3008,"sarà tutta salute per il tuo corpo e refrigerio per le tue ossa."],
[3009,"Onora il Signore con i tuoi averi e con le primizie di tutti i tuoi raccolti;"],
[3010,"i tuoi granai si riempiranno oltre misura e i tuoi tini traboccheranno di mosto."],
[3011,"Figlio mio, non disprezzare l'istruzione del Signore e non aver a noia la sua correzione,"],
[3012,"perché il Signore corregge chi ama, come un padre il figlio prediletto."],
[3013,"Beato l'uomo che ha trovato la sapienza, l'uomo che ottiene il discernimento:"],
[3014,"è una rendita che vale più dell'argento e un provento superiore a quello dell'oro."],
[3015,"La sapienza è più preziosa di ogni perla e quanto puoi desiderare non l'eguaglia."],
[3016,"Lunghi giorni sono nella sua destra e nella sua sinistra ricchezza e onore;"],
[3017,"le sue vie sono vie deliziose e tutti i suoi sentieri conducono al benessere."],
[3018,"È un albero di vita per chi l'afferra, e chi ad essa si stringe è beato."],
[3019,"Il Signore ha fondato la terra con sapienza, ha consolidato i cieli con intelligenza;"],
[3020,"con la sua scienza si aprirono gli abissi e le nubi stillano rugiada."],
[3021,"Figlio mio, custodisci il consiglio e la riflessione né mai si allontanino dai tuoi occhi:"],
[3022,"saranno vita per te e ornamento per il tuo collo."],
[3023,"Allora camminerai sicuro per la tua strada e il tuo piede non inciamperà."],
[3024,"Quando ti coricherai, non avrai paura; ti coricherai e il tuo sonno sarà dolce."],
[3025,"Non temerai per uno spavento improvviso, né per la rovina degli empi quando essa verrà,"],
[3026,"perché il Signore sarà la tua sicurezza e preserverà il tuo piede dal laccio."],
[3027,"Non negare un bene a chi ne ha il diritto, se hai la possibilità di farlo."],
[3028,"Non dire al tuo prossimo: \"Va', ripassa, te lo darò domani\", se tu possiedi ciò che ti chiede."],
[3029,"Non tramare il male contro il tuo prossimo, mentre egli dimora fiducioso presso di te."],
[3030,"Non litigare senza motivo con nessuno, se non ti ha fatto nulla di male."],
[3031,"Non invidiare l'uomo violento  e non irritarti per tutti i suoi successi,"],
[3032,"perché il Signore ha in orrore il perverso, mentre la sua amicizia è per i giusti."],
[3033,"La maledizione del Signore è sulla casa del malvagio, mentre egli benedice la dimora dei giusti."],
[3034,"Dei beffardi egli si fa beffe e agli umili concede la sua benevolenza."],
[3035,"I saggi erediteranno onore, gli stolti invece riceveranno disprezzo."],
[4001,"Ascoltate, o figli, l'istruzione di un padre e fate attenzione a sviluppare l'intelligenza,"],
[4002,"poiché io vi do una buona dottrina; non abbandonate il mio insegnamento."],
[4003,"Anch'io sono stato un figlio per mio padre, tenero e caro agli occhi di mia madre."],
[4004,"Egli mi istruiva e mi diceva: \"Il tuo cuore ritenga le mie parole; custodisci i miei precetti e vivrai."],
[4005,"Acquista la sapienza, acquista l'intelligenza; non dimenticare le parole della mia bocca e non allontanartene mai."],
[4006,"Non abbandonarla ed essa ti custodirà, amala e veglierà su di te."],
[4007,"Principio della sapienza: acquista la sapienza; a costo di tutto ciò che possiedi, acquista l'intelligenza."],
[4008,"Stimala ed essa ti esalterà, sarà la tua gloria, se l'abbraccerai."],
[4009,"Una corona graziosa porrà sul tuo capo, un diadema splendido ti elargirà\"."],
[4010,"Ascolta, figlio mio, e accogli le mie parole e si moltiplicheranno gli anni della tua vita."],
[4011,"Ti indico la via della sapienza, ti guido per i sentieri della rettitudine."],
[4012,"Quando camminerai non saranno intralciati i tuoi passi, e se correrai, non inciamperai."],
[4013,"Attieniti alla disciplina, non lasciarla, custodiscila, perché essa è la tua vita."],
[4014,"Non entrare nella strada degli empi e non procedere per la via dei malvagi."],
[4015,"Evita quella strada, non passarvi, sta' lontano e passa oltre."],
[4016,"Essi non dormono, se non fanno del male, non si lasciano prendere dal sonno; se non fanno cadere qualcuno;"],
[4017,"mangiano il pane dell'empietà e bevono il vino della violenza."],
[4018,"La strada dei giusti è come la luce dell'alba, che aumenta lo splendore fino al meriggio."],
[4019,"La via degli empi è come l'oscurità: non sanno dove saranno spinti a cadere."],
[4020,"Figlio mio, fa' attenzione alle mie parole, porgi l'orecchio ai miei detti;"],
[4021,"non perderli di vista, custodiscili dentro il tuo cuore,"],
[4022,"perché essi sono vita per chi li trova e guarigione per tutto il suo corpo."],
[4023,"Più di ogni cosa degna di cura custodisci il tuo cuore, perché da esso sgorga la vita."],
[4024,"Tieni lontano da te la bocca bugiarda e allontana da te le labbra perverse."],
[4025,"I tuoi occhi guardino sempre in avanti e le tue pupille mirino diritto davanti a te."],
[4026,"Bada alla strada dove metti il piede e tutte le tue vie siano sicure."],
[4027,"Non deviare né a destra né a sinistra, tieni lontano dal male il tuo piede."],
[5001,"Figlio mio, fa' attenzione alla mia sapienza e porgi l'orecchio alla mia intelligenza,"],
[5002,"perché tu possa conservare le mie riflessioni e le tue labbra custodiscano la scienza."],
[5003,"Veramente le labbra di una straniera stillano miele, e più viscida dell'olio è la sua bocca;"],
[5004,"ma alla fine ella è amara come assenzio, pungente come spada a doppio taglio."],
[5005,"I suoi piedi scendono verso la morte, i suoi passi conducono al regno dei morti,"],
[5006,"perché ella non bada alla via della vita, i suoi sentieri si smarriscono e non se ne rende conto."],
[5007,"Ora, figli, ascoltatemi e non allontanatevi dalle parole della mia bocca."],
[5008,"Tieni lontano da lei il tuo cammino e non avvicinarti alla porta della sua casa,"],
[5009,"per non mettere in balia di altri il tuo onore e i tuoi anni alla mercé di un uomo crudele,"],
[5010,"perché non si sazino dei tuoi beni gli estranei, e le tue fatiche non finiscano in casa di uno sconosciuto"],
[5011,"e tu non debba gemere alla fine, quando deperiranno il tuo corpo e la tua carne,"],
[5012,"e tu debba dire: \"Perché mai ho odiato l'istruzione e il mio cuore ha disprezzato la correzione?"],
[5013,"Non ho ascoltato la voce dei miei maestri, non ho prestato orecchio a chi m'istruiva."],
[5014,"Per poco non mi sono trovato nel colmo dei mali in mezzo alla folla e all'assemblea\"."],
[5015,"Bevi l'acqua della tua cisterna e quella che zampilla dal tuo pozzo,"],
[5016,"perché non si effondano al di fuori le tue sorgenti e nelle piazze i tuoi ruscelli,"],
[5017,"ed essi siano per te solo e non per degli estranei che sono con te."],
[5018,"Sia benedetta la tua sorgente, e tu trova gioia nella donna della tua giovinezza:"],
[5019,"cerva amabile, gazzella graziosa, i suoi seni ti inebrino sempre, sii sempre invaghito del suo amore!"],
[5020,"Perché, figlio mio, perderti per la straniera e stringerti al petto di una sconosciuta?"],
[5021,"Poiché sono davanti agli occhi del Signore le vie dell'uomo, egli bada a tutti i suoi sentieri."],
[5022,"L'empio è preda delle sue iniquità, è tenuto stretto dalle funi del suo peccato."],
[5023,"Egli morirà per mancanza d'istruzione, si perderà per la sua grande stoltezza."],
[6001,"Figlio mio, se hai garantito per il tuo prossimo, se hai dato la tua mano per un estraneo,"],
[6002,"se ti sei legato con ciò che hai detto e ti sei lasciato prendere dalle parole della tua bocca,"],
[6003,"figlio mio, fa' così per liberartene: poiché sei caduto nelle mani del tuo prossimo, va', gettati ai suoi piedi, importuna il tuo prossimo;"],
[6004,"non concedere sonno ai tuoi occhi né riposo alle tue palpebre,"],
[6005,"così potrai liberartene come la gazzella dal laccio, come un uccello dalle mani del cacciatore."],
[6006,"Va' dalla formica, o pigro, guarda le sue abitudini e diventa saggio."],
[6007,"Essa non ha né capo né sorvegliante né padrone,"],
[6008,"eppure d'estate si procura il vitto, al tempo della mietitura accumula il cibo."],
[6009,"Fino a quando, pigro, te ne starai a dormire? Quando ti scuoterai dal sonno?"],
[6010,"Un po' dormi, un po' sonnecchi, un po' incroci le braccia per riposare,"],
[6011,"e intanto arriva a te la povertà, come un vagabondo, e l'indigenza, come se tu fossi un accattone."],
[6012,"Il perverso, uomo iniquo, cammina pronunciando parole tortuose,"],
[6013,"ammicca con gli occhi, stropiccia i piedi e fa cenni con le dita."],
[6014,"Nel suo cuore il malvagio trama cose perverse, in ogni tempo suscita liti."],
[6015,"Per questo improvvisa verrà la sua rovina, ed egli, in un attimo, crollerà senza rimedio."],
[6016,"Sei cose odia il Signore, anzi sette gli sono in orrore:"],
[6017,"occhi alteri, lingua bugiarda, mani che versano sangue innocente,"],
[6018,"cuore che trama iniqui progetti, piedi che corrono rapidi verso il male,"],
[6019,"falso testimone che diffonde menzogne e chi provoca litigi tra fratelli."],
[6020,"Figlio mio, osserva il comando di tuo padre e non disprezzare l'insegnamento di tua madre."],
[6021,"Fissali sempre nel tuo cuore, appendili al collo."],
[6022,"Quando cammini ti guideranno, quando riposi veglieranno su di te, quando ti desti ti parleranno,"],
[6023,"perché il comando è una lampada e l'insegnamento una luce e un sentiero di vita l'istruzione che ti ammonisce:"],
[6024,"ti proteggeranno dalla donna altrui, dalle parole seducenti della donna sconosciuta."],
[6025,"Non desiderare in cuor tuo la sua bellezza, non lasciarti adescare dai suoi sguardi,"],
[6026,"poiché, se la prostituta cerca il pane, la donna sposata ambisce una vita preziosa."],
[6027,"Si può portare il fuoco sul petto senza bruciarsi i vestiti,"],
[6028,"o camminare sulle braci senza scottarsi i piedi?"],
[6029,"Così chi si accosta alla donna altrui: chi la tocca non resterà impunito."],
[6030,"Non si disapprova un ladro, se ruba per soddisfare l'appetito quando ha fame;"],
[6031,"eppure, se è preso, dovrà restituire sette volte e consegnare tutti i beni della sua casa."],
[6032,"Chi commette adulterio è un insensato, agendo in tal modo rovina se stesso."],
[6033,"Incontrerà percosse e disonore, la sua vergogna non sarà cancellata,"],
[6034,"poiché la gelosia accende l'ira del marito, che non avrà pietà nel giorno della vendetta."],
[6035,"Egli non accetterà compenso alcuno, rifiuterà ogni dono, anche se grande."],
[7001,"Figlio mio, custodisci le mie parole e fa' tesoro dei miei precetti."],
[7002,"Osserva i miei precetti e vivrai, il mio insegnamento sia come la pupilla dei tuoi occhi."],
[7003,"Legali alle tue dita, scrivili sulla tavola del tuo cuore."],
[7004,"Di' alla sapienza: \"Tu sei mia sorella\", e chiama amica l'intelligenza,"],
[7005,"perché ti protegga dalla donna straniera, dalla sconosciuta che ha parole seducenti."],
[7006,"Mentre dalla finestra della mia casa stavo osservando dietro le inferriate,"],
[7007,"ecco, io vidi dei giovani inesperti, e tra loro scorsi un adolescente dissennato."],
[7008,"Passava per la piazza, rasente all'angolo, e s'incamminava verso la casa di lei,"],
[7009,"all'imbrunire, al declinare del giorno, all'apparire della notte e del buio."],
[7010,"Ed ecco, gli si fa incontro una donna in vesti di prostituta, che intende sedurlo."],
[7011,"Ella è irrequieta e insolente, non sa tenere i piedi in casa sua."],
[7012,"Ora è per la strada, ora per le piazze, ad ogni angolo sta in agguato."],
[7013,"Lo afferra, lo bacia e con sfacciataggine gli dice:"],
[7014,"\"Dovevo offrire sacrifici di comunione: oggi ho sciolto i miei voti;"],
[7015,"per questo sono uscita incontro a te desiderosa di vederti, e ti ho trovato."],
[7016,"Ho messo coperte soffici sul mio letto, lenzuola ricamate di lino d'Egitto;"],
[7017,"ho profumato il mio giaciglio di mirra, di aloe e di cinnamomo."],
[7018,"Vieni, inebriamoci d'amore fino al mattino, godiamoci insieme amorosi piaceri,"],
[7019,"poiché mio marito non è in casa, è partito per un lungo viaggio,"],
[7020,"ha portato con sé il sacchetto del denaro, tornerà a casa il giorno del plenilunio\"."],
[7021,"Lo lusinga con tante moine, lo seduce con labbra allettanti;"],
[7022,"egli incauto la segue, come un bue condotto al macello, come cervo adescato con un laccio,"],
[7023,"finché una freccia non gli trafigge il fegato, come un uccello che si precipita nella rete e non sa che la sua vita è in pericolo."],
[7024,"Ora, figli, ascoltatemi e fate attenzione alle parole della mia bocca."],
[7025,"Il tuo cuore non si volga verso le sue vie, non vagare per i suoi sentieri,"],
[7026,"perché molti ne ha fatti cadere trafitti ed erano vigorose tutte le sue vittime."],
[7027,"Strada del regno dei morti è la sua casa, che scende nelle dimore della morte."],
[8001,"La sapienza forse non chiama e l'intelligenza non fa udire la sua voce?"],
[8002,"In cima alle alture, lungo la via, nei crocicchi delle strade si apposta,"],
[8003,"presso le porte, all'ingresso della città, sulle soglie degli usci essa grida:"],
[8004,"\"A voi, uomini, io mi rivolgo, ai figli dell'uomo è diretta la mia voce."],
[8005,"Imparate, inesperti, la prudenza e voi, stolti, fatevi assennati."],
[8006,"Ascoltate, perché dirò cose rilevanti, dalle mie labbra usciranno sentenze giuste,"],
[8007,"perché la mia bocca proclama la verità e l'empietà è orrore per le mie labbra."],
[8008,"Tutte le parole della mia bocca sono giuste, niente in esse è tortuoso o perverso;"],
[8009,"sono tutte chiare per chi le comprende e rette per chi possiede la scienza."],
[8010,"Accettate la mia istruzione e non l'argento, la scienza anziché l'oro fino,"],
[8011,"perché la sapienza vale più delle perle e quanto si può desiderare non l'eguaglia."],
[8012,"Io, la sapienza, abito con la prudenza e possiedo scienza e riflessione."],
[8013,"Temere il Signore è odiare il male: io detesto la superbia e l'arroganza, la cattiva condotta e la bocca perversa."],
[8014,"A me appartengono consiglio e successo, mia è l'intelligenza, mia è la potenza."],
[8015,"Per mezzo mio regnano i re e i principi promulgano giusti decreti;"],
[8016,"per mezzo mio i capi comandano e i grandi governano con giustizia."],
[8017,"Io amo coloro che mi amano, e quelli che mi cercano mi trovano."],
[8018,"Ricchezza e onore sono con me, sicuro benessere e giustizia."],
[8019,"Il mio frutto è migliore dell'oro più fino, il mio prodotto è migliore dell'argento pregiato."],
[8020,"Sulla via della giustizia io cammino e per i sentieri dell'equità,"],
[8021,"per dotare di beni quanti mi amano e riempire i loro tesori."],
[8022,"Il Signore mi ha creato come inizio della sua attività, prima di ogni sua opera, all'origine."],
[8023,"Dall'eternità sono stata formata, fin dal principio, dagli inizi della terra."],
[8024,"Quando non esistevano gli abissi, io fui generata, quando ancora non vi erano le sorgenti cariche d'acqua;"],
[8025,"prima che fossero fissate le basi dei monti, prima delle colline, io fui generata,"],
[8026,"quando ancora non aveva fatto la terra e i campi né le prime zolle del mondo."],
[8027,"Quando egli fissava i cieli, io ero là; quando tracciava un cerchio sull'abisso,"],
[8028,"quando condensava le nubi in alto, quando fissava le sorgenti dell'abisso,"],
[8029,"quando stabiliva al mare i suoi limiti, così che le acque non ne oltrepassassero i confini, quando disponeva le fondamenta della terra,"],
[8030,"io ero con lui come artefice ed ero la sua delizia ogni giorno: giocavo davanti a lui in ogni istante,"],
[8031,"giocavo sul globo terrestre, ponendo le mie delizie tra i figli dell'uomo."],
[8032,"Ora, figli, ascoltatemi: beati quelli che seguono le mie vie!"],
[8033,"Ascoltate l'esortazione e siate saggi, non trascuratela!"],
[8034,"Beato l'uomo che mi ascolta, vegliando ogni giorno alle mie porte, per custodire gli stipiti della mia soglia."],
[8035,"Infatti, chi trova me trova la vita e ottiene il favore del Signore;"],
[8036,"ma chi pecca contro di me fa male a se stesso; quanti mi odiano amano la morte\"."],
[9001,"La sapienza si è costruita la sua casa, ha intagliato le sue sette colonne."],
[9002,"Ha ucciso il suo bestiame, ha preparato il suo vino e ha imbandito la sua tavola."],
[9003,"Ha mandato le sue ancelle a proclamare sui punti più alti della città:"],
[9004,"\"Chi è inesperto venga qui!\". A chi è privo di senno ella dice:"],
[9005,"\"Venite, mangiate il mio pane, bevete il vino che io ho preparato."],
[9006,"Abbandonate l'inesperienza e vivrete, andate diritti per la via dell'intelligenza\"."],
[9007,"Chi corregge lo spavaldo ne riceve disprezzo e chi riprende il malvagio ne riceve oltraggio."],
[9008,"Non rimproverare lo spavaldo per non farti odiare; rimprovera il saggio ed egli ti sarà grato."],
[9009,"Da' consigli al saggio e diventerà ancora più saggio; istruisci il giusto ed egli aumenterà il sapere."],
[9010,"Principio della sapienza è il timore del Signore, e conoscere il Santo è intelligenza."],
[9011,"Per mezzo mio si moltiplicheranno i tuoi giorni, ti saranno aumentati gli anni di vita."],
[9012,"Se sei sapiente, lo sei a tuo vantaggio, se sei spavaldo, tu solo ne porterai la pena."],
[9013,"Donna follia è irrequieta, sciocca e ignorante."],
[9014,"Sta seduta alla porta di casa, su un trono, in un luogo alto della città,"],
[9015,"per invitare i passanti che vanno diritti per la loro strada:"],
[9016,"\"Chi è inesperto venga qui!\". E a chi è privo di senno ella dice:"],
[9017,"\"Le acque furtive sono dolci, il pane preso di nascosto è gustoso\"."],
[9018,"Egli non si accorge che là ci sono le ombre e i suoi invitati scendono nel profondo del regno dei morti."],
[10001,"Proverbi di Salomone. Il figlio saggio allieta il padre, il figlio stolto contrista sua madre."],
[10002,"I tesori male acquistati non giovano, ma la giustizia libera dalla morte."],
[10003,"Il Signore non lascia che il giusto soffra la fame, ma respinge la cupidigia dei perfidi."],
[10004,"La mano pigra rende poveri, la mano operosa arricchisce."],
[10005,"Chi raccoglie d'estate è previdente e chi dorme al tempo della mietitura è uno svergognato."],
[10006,"Le benedizioni del Signore sul capo del giusto, la bocca degli empi nasconde violenza."],
[10007,"La memoria del giusto è in benedizione, il nome degli empi marcisce."],
[10008,"Chi è saggio di cuore accetta i precetti, chi è stolto di labbra va in rovina."],
[10009,"Chi cammina nell'integrità va sicuro, chi tiene vie tortuose sarà smascherato."],
[10010,"Chi chiude un occhio causa dolore, chi riprende a viso aperto procura pace."],
[10011,"Fonte di vita è la bocca del giusto,  la bocca degli empi nasconde violenza."],
[10012,"L'odio suscita litigi,  l'amore ricopre ogni colpa."],
[10013,"Sulle labbra dell'intelligente si trova la sapienza,  ma il bastone è per la schiena dello stolto."],
[10014,"I saggi fanno tesoro della scienza,  ma la bocca dello stolto è una rovina imminente."],
[10015,"I beni del ricco sono la sua roccaforte,  la rovina dei poveri è la loro miseria."],
[10016,"Il salario del giusto serve per la vita,  il guadagno dell'empio è per i vizi."],
[10017,"Cammina verso la vita chi accetta la correzione,  chi trascura il rimprovero si smarrisce."],
[10018,"Dissimulano l'odio le labbra bugiarde,  chi diffonde calunnie è uno stolto."],
[10019,"Nel molto parlare non manca la colpa,  chi frena le labbra è saggio."],
[10020,"Argento pregiato è la lingua del giusto,  il cuore degli empi vale ben poco."],
[10021,"Le labbra del giusto nutrono molti,  gli stolti invece muoiono per la loro stoltezza."],
[10022,"La benedizione del Signore arricchisce,  non vi aggiunge nulla la fatica."],
[10023,"Per lo stolto compiere il male è un divertimento, così coltivare la sapienza per l'uomo prudente."],
[10024,"Al malvagio sopraggiunge il male che teme, il desiderio dei giusti invece è soddisfatto."],
[10025,"Passa la bufera e l'empio non c'è più, il giusto invece resta saldo per sempre."],
[10026,"Come l'aceto ai denti e il fumo agli occhi, così è il pigro per chi gli affida una missione."],
[10027,"Il timore del Signore prolunga i giorni, ma gli anni dei malvagi sono accorciati."],
[10028,"L'attesa dei giusti è gioia, ma la speranza degli empi svanirà."],
[10029,"La via del Signore è una fortezza per l'uomo integro, ma è una rovina per i malfattori."],
[10030,"Il giusto non vacillerà mai, ma gli empi non dureranno sulla terra."],
[10031,"La bocca del giusto espande sapienza, la lingua perversa sarà tagliata."],
[10032,"Le labbra del giusto conoscono benevolenza, la bocca degli empi cose perverse."],
[11001,"Il Signore aborrisce la bilancia falsa,  ma del peso esatto egli si compiace."],
[11002,"Dove c'è insolenza c'è anche disonore,  ma la sapienza sta con gli umili."],
[11003,"L'integrità guida gli uomini retti,  la malvagità è la rovina dei perfidi."],
[11004,"Non giova la ricchezza nel giorno della collera,  ma la giustizia libera dalla morte."],
[11005,"La giustizia dell'uomo onesto gli spiana la via,  per la sua cattiveria cade il cattivo."],
[11006,"La giustizia salva gli onesti,  nella cupidigia restano presi i perfidi."],
[11007,"Con la morte del malvagio svanisce ogni sua speranza,  l'attesa dei ricchi scompare."],
[11008,"Il giusto è liberato dall'angoscia,  al suo posto subentra il malvagio."],
[11009,"Con la sua bocca il bugiardo rovina l'amico,  i giusti con la loro scienza si salvano."],
[11010,"Della prosperità dei giusti la città si rallegra,  per la rovina dei malvagi si fa festa."],
[11011,"La benedizione degli uomini retti fa prosperare una città,  le parole dei malvagi la distruggono."],
[11012,"Disprezza il suo prossimo chi è privo di senno,  ma l'uomo prudente tace."],
[11013,"Chi va in giro sparlando svela il segreto,  ma l'uomo fidato tiene nascosto ciò che sa."],
[11014,"Dove manca una guida il popolo va in rovina;  la salvezza dipende dal numero dei consiglieri."],
[11015,"Chi garantisce per un estraneo si troverà male,  chi rifiuta garanzie vive tranquillo."],
[11016,"La donna avvenente ottiene onore,  gli uomini laboriosi ottengono ricchezze."],
[11017,"Benefica se stesso chi è buono,  il crudele invece tormenta la sua carne."],
[11018,"L'empio realizza opere fallaci,  per chi semina giustizia il salario è assicurato."],
[11019,"Chi pratica la giustizia si procura la vita,  chi persegue il male va verso la morte."],
[11020,"Un cuore perverso il Signore lo detesta:  egli si compiace di chi ha una condotta integra."],
[11021,"Certamente non resterà impunito il malvagio,  ma la discendenza dei giusti sarà salva."],
[11022,"Un anello d'oro al naso di un maiale,  tale è la donna bella ma senza cervello."],
[11023,"La brama dei giusti è solo il bene,  la speranza degli empi è la collera."],
[11024,"C'è chi largheggia e la sua ricchezza aumenta,  c'è chi risparmia oltre misura e finisce nella miseria."],
[11025,"La persona benefica prospererà  e chi disseta sarà dissetato."],
[11026,"Chi accaparra il grano è maledetto dal popolo,  la benedizione sta sul capo di chi lo vende."],
[11027,"Chi è sollecito del bene incontra favore  e chi cerca il male, male gli accadrà."],
[11028,"Chi confida nella propria ricchezza cadrà,  i giusti invece rinverdiranno come foglie."],
[11029,"Chi crea disordine in casa erediterà vento  e lo stolto sarà schiavo dell'uomo di senno."],
[11030,"Il frutto del giusto è un albero di vita,  il saggio conquista i cuori."],
[11031,"Ecco, il giusto è ripagato sulla terra:  tanto più l'empio e il peccatore."],
[12001,"Chi ama la correzione ama la scienza,  chi odia il rimprovero è uno stupido."],
[12002,"Chi è buono ottiene il favore del Signore,  il quale condanna il malintenzionato."],
[12003,"Non si consolida l'uomo con la malvagità,  ma la radice dei giusti non sarà smossa."],
[12004,"Una donna forte è la corona del marito,  ma quella svergognata è come carie nelle sue ossa."],
[12005,"I pensieri dei giusti sono equità,  i propositi degli empi sono frode."],
[12006,"Le parole degli empi sono insidie mortali,  ma la bocca degli uomini retti li salverà."],
[12007,"Gli empi, una volta abbattuti, più non sono,  ma la casa dei giusti resta salda."],
[12008,"Un uomo è lodato in proporzione alla sua intelligenza,  ma chi ha il cuore perverso è disprezzato."],
[12009,"Un uomo di poco conto che ha un servitore  vale più di uno che si vanta, a cui manca il pane."],
[12010,"Il giusto si prende cura del suo bestiame,  ma i sentimenti degli empi sono spietati."],
[12011,"Chi coltiva la sua terra si sazia di pane,  chi insegue chimere è proprio uno stolto."],
[12012,"Le brame dell'empio sono una rete di mali,  la radice dei giusti dà molto frutto."],
[12013,"Nel peccato delle sue labbra si impiglia il malvagio,  ma il giusto sfugge a tale angoscia."],
[12014,"Con il frutto della bocca ci si sazia di beni;  ciascuno sarà ripagato secondo le sue opere."],
[12015,"La via del malvagio è retta ai propri occhi,  il saggio, invece, ascolta il consiglio."],
[12016,"Lo stolto manifesta subito la sua collera,  ma chi è avveduto dissimula l'offesa."],
[12017,"Chi dice la verità proclama la giustizia,  chi testimonia il falso favorisce l'inganno."],
[12018,"C'è chi chiacchierando è come una spada tagliente,  ma la lingua dei saggi risana."],
[12019,"Il labbro veritiero resta saldo per sempre,  quello bugiardo per un istante solo."],
[12020,"L'inganno è nel cuore di chi trama il male,  la gioia invece è di chi promuove la pace."],
[12021,"Al giusto non può accadere alcun male,  i malvagi invece sono pieni di guai."],
[12022,"Le labbra bugiarde sono un obbrobrio per il Signore:  egli si compiace di chiunque fa la verità."],
[12023,"Chi è avveduto nasconde quello che sa,  il cuore degli stolti proclama stoltezze."],
[12024,"La mano operosa ottiene il comando,  quella pigra invece è destinata a servire."],
[12025,"L'afflizione deprime il cuore dell'uomo,  una parola buona lo allieta."],
[12026,"Il giusto è guida sicura per il suo prossimo,  ma la via dei malvagi li porta fuori strada."],
[12027,"Il pigro non troverà selvaggina,  ma la persona industriosa possiede una fortuna."],
[12028,"Sui sentieri della giustizia si trova la vita,  la sua strada non va mai alla morte."],
[13001,"Il figlio saggio ama la correzione del padre,  lo spavaldo non ascolta il rimprovero."],
[13002,"Con il frutto della bocca ci si nutre di beni,  ma l'appetito dei perfidi si ciba di violenza."],
[13003,"Chi sorveglia la bocca preserva la sua vita,  chi spalanca le sue labbra va incontro alla rovina."],
[13004,"Il pigro brama, ma non c'è nulla per il suo appetito,  mentre l'appetito dei laboriosi sarà soddisfatto."],
[13005,"Il giusto odia la parola falsa,  l'empio disonora e diffama."],
[13006,"La giustizia custodisce chi ha una condotta integra,  la malvagità manda in rovina il peccatore."],
[13007,"C'è chi fa il ricco e non ha nulla,  c'è chi fa il povero e possiede molti beni."],
[13008,"Riscatto della vita d'un uomo è la sua ricchezza,  ma il povero non avverte la minaccia."],
[13009,"La luce dei giusti porta gioia,  la lampada dei malvagi si spegne."],
[13010,"L'insolenza provoca litigi,  ma la sapienza sta con chi accetta consigli."],
[13011,"La ricchezza venuta dal nulla diminuisce,  chi la accumula a poco a poco, la fa aumentare."],
[13012,"Un'attesa troppo prolungata fa male al cuore,  un desiderio soddisfatto è albero di vita."],
[13013,"Chi disprezza la parola si rende debitore,  chi rispetta un ordine viene ricompensato."],
[13014,"L'insegnamento del saggio è fonte di vita  per sfuggire ai lacci della morte."],
[13015,"Il senno procura favore,  ma il contegno dei perfidi porta alla rovina."],
[13016,"La persona avveduta prima di agire riflette,  lo stolto mette in mostra la sua stupidità."],
[13017,"Un cattivo messaggero causa sciagure,  un inviato fedele porta salute."],
[13018,"Povertà e ignominia a chi rifiuta la correzione,  chi tiene conto del rimprovero sarà onorato."],
[13019,"Desiderio appagato è dolcezza per l'anima;  fa orrore agli stolti evitare il male."],
[13020,"Va' con i saggi e saggio diventerai,  chi pratica gli stolti ne subirà danno."],
[13021,"La sventura insegue i peccatori,  il bene è la ricompensa dei giusti."],
[13022,"L'uomo buono lascia eredi i figli dei figli,  è riservata al giusto la ricchezza del peccatore."],
[13023,"Vi è cibo in abbondanza nei campi dei poveri,  ma può essere sottratto per mancanza di giustizia."],
[13024,"Chi risparmia il bastone odia suo figlio,  chi lo ama è pronto a correggerlo."],
[13025,"Il giusto mangia fino a saziarsi,  ma il ventre dei malvagi resta vuoto."],
[14001,"La donna saggia costruisce la sua casa,   quella stolta la demolisce con le proprie mani."],
[14002,"Cammina nella propria giustizia chi teme il Signore,  ma chi è traviato nelle proprie vie lo disprezza."],
[14003,"Nella bocca dello stolto c'è il germoglio della superbia,  ma le labbra dei saggi sono la loro salvaguardia."],
[14004,"Se non ci sono buoi la greppia è vuota,  l'abbondanza del raccolto sta nel vigore del toro."],
[14005,"Il testimone sincero non mentisce,  chi proferisce menzogne è testimone falso."],
[14006,"Lo spavaldo ricerca la sapienza ma invano,  la scienza è cosa facile per l'intelligente."],
[14007,"Stai lontano dall'uomo stolto:  in lui non troverai labbra sapienti."],
[14008,"Il sapiente avveduto conosce la sua strada,  ma la stoltezza degli sciocchi è inganno."],
[14009,"Tra gli stolti risiede la colpa,  tra i giusti dimora la benevolenza."],
[14010,"Il cuore conosce la propria amarezza  e alla sua gioia non partecipa l'estraneo."],
[14011,"La casa degli empi sarà abbattuta,  ma la tenda dei giusti prospererà."],
[14012,"C'è una via che sembra diritta per l'uomo,  ma alla fine conduce su sentieri di morte."],
[14013,"Anche nel riso il cuore prova dolore  e la gioia può finire in pena."],
[14014,"Il perverso si sazia della sua condotta,  l'uomo buono delle sue opere."],
[14015,"L'ingenuo crede a ogni parola,  ma chi è avveduto controlla i propri passi."],
[14016,"Il saggio teme e sta lontano dal male,  lo stolto invece è impulsivo e si sente sicuro."],
[14017,"Chi è pronto all'ira commette sciocchezze,  il malintenzionato si rende odioso."],
[14018,"Gli inesperti ereditano la stoltezza,  gli accorti si coronano di scienza."],
[14019,"I cattivi si inchinano davanti ai buoni,  i malvagi davanti alle porte del giusto."],
[14020,"Il povero è odioso anche a chi gli è pari,  ma numerosi sono gli amici del ricco."],
[14021,"Chi disprezza il prossimo pecca,  beato chi ha pietà degli umili."],
[14022,"Non errano forse quelli che compiono il male?  Amore e fedeltà per quanti compiono il bene."],
[14023,"In ogni fatica c'è un vantaggio,  ma le chiacchiere portano solo miseria."],
[14024,"Corona dei saggi è la loro ricchezza,  la follia degli stolti produce solo follia."],
[14025,"È salvezza per molti il testimone veritiero,  ma chi proferisce menzogne è un impostore."],
[14026,"Nel timore del Signore sta la fiducia del forte;  anche per i suoi figli egli sarà un rifugio."],
[14027,"Il timore del Signore è fonte di vita  per sfuggire ai lacci della morte."],
[14028,"Un popolo numeroso è la gloria del re,  ma la scarsità di gente è la rovina del principe."],
[14029,"Chi è paziente ha grande prudenza,  chi è iracondo mostra stoltezza."],
[14030,"Un cuore tranquillo è la vita del corpo,  l'invidia è la carie delle ossa."],
[14031,"Chi opprime il povero offende il suo creatore,  chi ha pietà del misero lo onora."],
[14032,"Dalla propria cattiveria è travolto il malvagio,  anche nella morte il giusto trova rifugio."],
[14033,"In un cuore intelligente risiede la sapienza,  ma in mezzo agli stolti verrà riconosciuta?"],
[14034,"La giustizia esalta una nazione,  ma il peccato è la vergogna dei popoli."],
[14035,"Il favore del re è per il ministro intelligente,  la sua ira è per l'indegno."],
[15001,"Una risposta gentile calma la collera,  una parola pungente eccita l'ira."],
[15002,"Le parole dei saggi fanno gustare la scienza,  mentre la bocca degli stolti esprime sciocchezze."],
[15003,"Gli occhi del Signore arrivano dappertutto,  scrutano i malvagi e i buoni."],
[15004,"Una parola buona è un albero di vita,  quella malevola è una ferita al cuore."],
[15005,"Lo stolto disprezza la correzione di suo padre,  chi tiene conto del rimprovero diventa prudente."],
[15006,"Nella casa del giusto c'è abbondanza di beni,  sul guadagno dell'empio incombe il dissesto."],
[15007,"Le labbra dei saggi diffondono la scienza,  non così il cuore degli stolti."],
[15008,"Il sacrificio dei malvagi è un orrore per il Signore,  la preghiera dei buoni gli è gradita."],
[15009,"Il Signore ha in orrore la condotta dei perversi,   egli ama chi pratica la giustizia."],
[15010,"Correzione severa per chi abbandona il retto sentiero;  chi rifiuta i rimproveri morirà!"],
[15011,"Abisso e regno dei morti sono palesi davanti al Signore,  quanto più i cuori degli uomini!"],
[15012,"Lo spavaldo non vuole essere corretto,  egli non va in compagnia dei saggi."],
[15013,"Un cuore lieto dà serenità al volto,  ma quando il cuore è triste, lo spirito è depresso."],
[15014,"Un cuore intelligente desidera imparare,  la bocca dello stolto si pasce della sua ignoranza."],
[15015,"Tutti i giorni sono brutti per il povero,  per un cuore felice è sempre festa."],
[15016,"È meglio aver poco con il timore di Dio  che un grande tesoro con l'inquietudine."],
[15017,"È meglio un piatto di verdura con l'amore  che un bue grasso con l'odio."],
[15018,"Chi è collerico suscita contese,  chi è paziente calma le liti."],
[15019,"La strada del pigro è come una siepe di spine,  il sentiero dei retti è scorrevole."],
[15020,"Il figlio saggio allieta il padre,  il figlio stolto disprezza sua madre."],
[15021,"La stoltezza è una gioia per chi è privo di senno;  chi è prudente cammina diritto."],
[15022,"Falliscono le decisioni prese senza consultazione,  riescono quelle suggerite da molti consiglieri."],
[15023,"È una gioia saper dare una risposta;  una parola detta al momento giusto è gradita!"],
[15024,"Per l'uomo assennato la strada della vita è verso l'alto,  per salvarlo dal regno dei morti che è in basso."],
[15025,"Il Signore abbatte la casa dei superbi,  ma consolida il confine della vedova."],
[15026,"Il Signore aborrisce i pensieri malvagi,  ma le parole benevole gli sono gradite."],
[15027,"Sconvolge la sua casa chi è avido di guadagni disonesti,  ma chi detesta i regali vivrà."],
[15028,"La mente del giusto riflette prima di rispondere,  ma la bocca dei malvagi esprime cattiveria."],
[15029,"Il Signore è lontano dai malvagi,  ma ascolta la preghiera dei giusti."],
[15030,"Uno sguardo luminoso dà gioia al cuore,  una notizia lieta rinvigorisce le ossa."],
[15031,"Chi ascolta un rimprovero salutare  potrà stare in mezzo ai saggi."],
[15032,"Chi rifiuta la correzione disprezza se stesso,  ma chi ascolta il rimprovero acquista senno."],
[15033,"Il timore di Dio è scuola di sapienza,  prima della gloria c'è l'umiltà."],
[16001,"All'uomo appartengono i progetti del cuore,  ma dal Signore viene la risposta della lingua."],
[16002,"Agli occhi dell'uomo tutte le sue opere sembrano pure,  ma chi scruta gli spiriti è il Signore."],
[16003,"Affida al Signore le tue opere  e i tuoi progetti avranno efficacia."],
[16004,"Il Signore ha fatto ogni cosa per il suo fine  e anche il malvagio per il giorno della sventura."],
[16005,"Il Signore ha in orrore ogni cuore superbo, certamente non resterà impunito."],
[16006,"Con la bontà e la fedeltà si espia la colpa, ma con il timore del Signore si evita il male."],
[16007,"Se il Signore si compiace della condotta di un uomo, lo riconcilia anche con i suoi nemici."],
[16008,"È meglio avere poco con onestà che molte rendite senza giustizia."],
[16009,"Il cuore dell'uomo elabora progetti, ma è il Signore che rende saldi i suoi passi."],
[16010,"L'oracolo è sulle labbra del re, in giudizio la sua bocca non sbaglia."],
[16011,"La stadera e le bilance giuste appartengono al Signore, sono opera sua tutti i pesi del sacchetto."],
[16012,"È un orrore per i re commettere un'azione iniqua, poiché il trono sta saldo con la giustizia."],
[16013,"Il re si compiace di chi dice la verità, egli ama chi parla con rettitudine."],
[16014,"L'ira del re è messaggera di morte, ma il saggio la placherà."],
[16015,"Se il volto del re è luminoso, c'è la vita: il suo favore è come pioggia di primavera."],
[16016,"Possedere la sapienza è molto meglio dell'oro, acquisire l'intelligenza è preferibile all'argento."],
[16017,"La strada degli uomini retti è evitare il male; conserva la vita chi controlla la sua condotta."],
[16018,"Prima della rovina viene l'orgoglio e prima della caduta c'è l'arroganza."],
[16019,"È meglio essere umili con i poveri che spartire la preda con i superbi."],
[16020,"Chi è prudente nel parlare troverà il bene, ma chi confida nel Signore è beato."],
[16021,"Chi è saggio di cuore è ritenuto intelligente; il linguaggio dolce aumenta la dottrina."],
[16022,"Fonte di vita è il senno per chi lo possiede, ma castigo degli stolti è la stoltezza."],
[16023,"Il cuore del saggio rende assennata la sua bocca e sulle sue labbra fa crescere la dottrina."],
[16024,"Favo di miele sono le parole gentili, dolce per il palato e medicina per le ossa."],
[16025,"C'è una via che sembra diritta per l'uomo, ma alla fine conduce su sentieri di morte."],
[16026,"La brama fa lavorare chi lavora, è la sua bocca che lo sprona."],
[16027,"L'uomo iniquo ordisce la sciagura, sulle sue labbra c'è come un fuoco ardente."],
[16028,"L'uomo perverso provoca litigi, chi calunnia divide gli amici."],
[16029,"L'uomo violento inganna il prossimo e lo spinge per una via non buona."],
[16030,"Chi socchiude gli occhi medita inganni, chi stringe le labbra ha già commesso il male."],
[16031,"Diadema splendido è la canizie, ed essa si trova sulla via della giustizia."],
[16032,"È meglio la pazienza che la forza di un eroe, chi domina se stesso vale più di chi conquista una città."],
[16033,"Nel cavo della veste si getta la sorte, ma la decisione dipende tutta dal Signore."],
[17001,"Meglio un tozzo di pane secco con tranquillità che una casa piena di banchetti con discordia."],
[17002,"Lo schiavo intelligente prevarrà su un figlio disonorato e avrà parte con i fratelli all'eredità."],
[17003,"Il crogiuolo è per l'argento e il forno per l'oro, ma chi prova i cuori è il Signore."],
[17004,"Il malfattore presta attenzione a un labbro maldicente, il bugiardo ascolta una lingua nociva."],
[17005,"Chi deride il povero offende il suo creatore, chi gioisce per colui che va in rovina non resterà impunito."],
[17006,"Corona dei vecchi sono i figli dei figli, onore dei figli i loro padri."],
[17007,"Non s'addice all'insensato un linguaggio elevato, ancor meno al principe un linguaggio falso."],
[17008,"Il regalo di corruzione è come un talismano per chi lo possiede: dovunque egli si volga ottiene successo."],
[17009,"Chi copre la colpa cerca l'amicizia, ma chi la divulga divide gli amici."],
[17010,"Fa più effetto un rimprovero all'assennato che cento percosse allo stolto."],
[17011,"Il malvagio non cerca altro che la ribellione, ma gli sarà mandato contro un messaggero senza pietà."],
[17012,"Meglio incontrare un'orsa privata dei figli che uno stolto in preda alla follia."],
[17013,"A chi rende male per bene non si allontanerà la sventura dalla sua casa."],
[17014,"Iniziare un litigio è come aprire una diga; prima che la lite si esasperi, troncala."],
[17015,"Assolvere il reo e condannare il giusto: ecco due cose che il Signore ha in orrore."],
[17016,"A che serve il denaro in mano allo stolto? Per comprare la sapienza, se non ha senno?"],
[17017,"Un amico vuol bene sempre, è nato per essere un fratello nella sventura."],
[17018,"È privo di senno l'uomo che dà la sua mano e si fa garante per il suo prossimo."],
[17019,"Chi ama la rissa ama il delitto, chi ingrandisce la sua porta cerca la rovina."],
[17020,"Chi ha un cuore perverso non troverà mai felicità e chi ha la lingua tortuosa cadrà in rovina."],
[17021,"Chi genera uno stolto ne avrà afflizione; non gioirà il padre di uno sciocco."],
[17022,"Un cuore lieto fa bene al corpo, uno spirito depresso inaridisce le ossa."],
[17023,"L'iniquo accetta regali sotto banco per deviare il corso della giustizia."],
[17024,"L'uomo prudente ha la sapienza davanti a sé, ma gli occhi dello stolto vagano in capo al mondo."],
[17025,"Un figlio stolto è un tormento per il padre e un'amarezza per colei che lo ha partorito."],
[17026,"Certo non è bene punire chi ha ragione, colpire gente perbene è contro la giustizia."],
[17027,"Chi è parco di parole possiede la scienza e chi è di spirito calmo è un uomo prudente."],
[17028,"Anche lo stolto, se tace, passa per saggio, e per intelligente se tiene chiuse le labbra."],
[18001,"Chi si tiene appartato cerca il suo piacere e con ogni stratagemma attacca brighe."],
[18002,"Lo stolto non ama la prudenza, ma vuole solo far mostra dei suoi sentimenti."],
[18003,"Con la malvagità viene il disprezzo, con il disonore anche l'ignominia."],
[18004,"Le parole della bocca dell'uomo sono acqua profonda, la fonte della sapienza è un torrente che straripa."],
[18005,"Non è bene usare riguardi al malvagio per far torto al giusto in un giudizio."],
[18006,"Le labbra dello stolto suscitano liti e la sua bocca gli provoca percosse."],
[18007,"La bocca dello stolto è la sua rovina e le sue labbra sono una trappola per la sua vita."],
[18008,"Le parole del calunniatore sono come ghiotti bocconi che scendono fin nel più intimo."],
[18009,"Chi è già indolente nel suo lavoro è fratello del dissipatore."],
[18010,"Torre fortificata è il nome del Signore: il giusto vi si rifugia ed è al sicuro."],
[18011,"I beni del ricco sono la sua roccaforte, sono come un'alta muraglia nella sua immaginazione."],
[18012,"Prima della caduta il cuore dell'uomo si esalta, prima della gloria c'è l'umiltà."],
[18013,"Chi risponde prima di avere ascoltato, mostra stoltezza e ne avrà vergogna."],
[18014,"Lo spirito dell'uomo lo sostiene nella malattia, ma uno spirito depresso chi lo solleverà?"],
[18015,"Il cuore intelligente acquista la scienza, l'orecchio dei saggi ricerca il sapere."],
[18016,"Il dono che l'uomo fa gli spiana la via e lo introduce alla presenza dei grandi."],
[18017,"Il primo a parlare in una lite sembra aver ragione, ma viene il suo avversario e lo confuta."],
[18018,"La sorte fa cessare le contese e decide fra i potenti."],
[18019,"Un fratello offeso è più inespugnabile d'una roccaforte, le liti sono come le sbarre di un castello."],
[18020,"Con il frutto della bocca ci si sazia il ventre, ognuno si sazia con il prodotto delle sue labbra."],
[18021,"Morte e vita sono in potere della lingua e chi ne fa buon uso ne mangerà i frutti."],
[18022,"Chi trova una moglie trova una fortuna e ottiene il favore del Signore."],
[18023,"Il povero parla con suppliche, il ricco risponde con durezza."],
[18024,"Ci sono compagni che si rovinano a vicenda, ma anche amici più affezionati di un fratello."],
[19001,"Meglio un povero dalla condotta integra di uno dalle labbra perverse e che è stolto."],
[19002,"Il desiderio ansioso senza riflessione non è cosa buona, e chi va a passi frettolosi sbaglia strada."],
[19003,"La stoltezza dell'uomo rovina la sua via, ma poi egli si adira contro il Signore."],
[19004,"Le ricchezze moltiplicano gli amici, ma il povero è abbandonato dall'amico che ha."],
[19005,"Il falso testimone non resterà impunito, chi diffonde menzogne non avrà scampo."],
[19006,"Molti sono gli adulatori dell'uomo generoso, e tutti sono amici di chi fa doni."],
[19007,"Il povero è disprezzato dai suoi stessi fratelli, tanto più si allontanano da lui i suoi amici. Egli va in cerca di parole, ma non ci sono."],
[19008,"Chi acquista senno ama se stesso e chi conserva la prudenza trova fortuna."],
[19009,"Il falso testimone non resterà impunito, chi diffonde menzogne perirà."],
[19010,"Allo stolto non conviene una vita agiata, ancor meno a un servo comandare ai principi."],
[19011,"È segno d'intelligenza per l'uomo trattenere la collera, ed è sua gloria passare sopra alle offese."],
[19012,"L'ira del re è come ruggito di leone,  come rugiada sull'erba è la sua benevolenza."],
[19013,"Un figlio stolto è una disgrazia per il padre e i litigi della moglie sono come stillicidio incessante."],
[19014,"La casa e il patrimonio si ereditano dal padre, ma una moglie assennata è dono del Signore."],
[19015,"La pigrizia fa cadere in torpore, e chi è indolente patirà la fame."],
[19016,"Chi custodisce il precetto custodisce se stesso, chi trascura la propria condotta morirà."],
[19017,"Chi ha pietà del povero fa un prestito al Signore, che gli darà la sua ricompensa."],
[19018,"Correggi tuo figlio, perché c'è speranza, ma non lasciarti andare fino a farlo morire."],
[19019,"L'iracondo deve essere punito; se lo risparmi, lo diventerà ancora di più."],
[19020,"Ascolta il consiglio e accetta la correzione, per essere saggio fino al termine della tua vita."],
[19021,"Molti sono i progetti nel cuore dell'uomo, ma solo i disegni del Signore si compiono."],
[19022,"Il pregio dell'uomo è la sua bontà; meglio un povero che un bugiardo."],
[19023,"Il timore di Dio conduce alla vita e chi ne è pieno dorme tranquillo senza essere raggiunto dalla sventura."],
[19024,"Il pigro immerge la mano nel piatto, ma non è capace di riportarla alla bocca."],
[19025,"Percuoti lo spavaldo e l'inesperto diventerà accorto, rimprovera il prudente e imparerà la lezione."],
[19026,"Rovina il padre e fa fuggire la madre un figlio disonorato e infame."],
[19027,"Figlio mio, cessa di accogliere l'istruzione se vuoi allontanarti dalle parole della sapienza."],
[19028,"Il testimone iniquo si beffa della giustizia e la bocca dei malvagi ingoia l'iniquità."],
[19029,"Per gli spavaldi sono pronte le punizioni e le percosse per la schiena degli stolti."],
[20001,"Il vino è beffardo, il liquore è tumultuoso; chiunque si perde dietro ad esso non è saggio."],
[20002,"La collera del re è come ruggito di leone; chiunque lo irrita rischia la vita."],
[20003,"È una gloria evitare le contese, attaccar briga è proprio degli stolti."],
[20004,"Il pigro non ara d'autunno: alla mietitura cerca, ma non trova nulla."],
[20005,"Acque profonde sono i consigli nel cuore umano, l'uomo accorto le sa attingere."],
[20006,"Molti proclamano la propria bontà, ma una persona fidata chi la trova?"],
[20007,"Chi cammina nella sua integrità è giusto; beati i figli che lascia dietro di sé!"],
[20008,"Il re che siede in tribunale con il suo sguardo dissipa ogni male."],
[20009,"Chi può dire: \"Ho la coscienza pulita, sono puro dal mio peccato?\"."],
[20010,"Doppio peso e doppia misura sono due cose che il Signore aborrisce."],
[20011,"Già con le sue azioni il fanciullo rivela se è puro e retto il suo comportamento."],
[20012,"L'orecchio che ascolta e l'occhio che vede: l'uno e l'altro li ha fatti il Signore."],
[20013,"Non amare il sonno per non diventare povero, tieni gli occhi aperti e avrai pane a sazietà."],
[20014,"\"Robaccia, robaccia\" dice chi compra, ma quando se ne va, allora se ne vanta."],
[20015,"C'è possesso di oro e moltitudine di perle, ma la cosa più preziosa sono le labbra sapienti."],
[20016,"Prendigli il vestito perché si è fatto garante per un estraneo e tienilo in pegno per uno sconosciuto."],
[20017,"È piacevole il pane procurato con frode, ma poi la bocca sarà piena di granelli di sabbia."],
[20018,"Pondera bene la tua strategia, consigliati, e fa' la guerra con molta riflessione."],
[20019,"Chi va in giro sparlando svela il segreto; non associarti a chi ha sempre aperte le labbra."],
[20020,"Chi maledice il padre e la madre vedrà spegnersi la sua lampada nel cuore delle tenebre."],
[20021,"Un'eredità accumulata in fretta all'inizio non sarà benedetta alla fine."],
[20022,"Non dire: \"Renderò male per male\"; confida nel Signore ed egli ti libererà."],
[20023,"Il Signore ha in orrore il doppio peso, la bilancia falsa non è cosa buona."],
[20024,"Il Signore rende sicuri i passi dell'uomo: come può l'essere umano conoscere la sua strada?"],
[20025,"È una trappola esclamare subito: \"Sacro!\" e riflettere solo dopo aver fatto il voto."],
[20026,"Un re saggio disperde i malvagi e con la ruota li stritola come paglia."],
[20027,"Lampada del Signore è lo spirito dell'uomo: essa scruta dentro, fin nell'intimo."],
[20028,"Bontà e fedeltà vegliano sul re, sulla giustizia è basato il suo trono."],
[20029,"Vanto dei giovani è la loro forza, ornamento dei vecchi è la canizie."],
[20030,"Le ferite sanguinanti leniscono il male, le percosse purificano fin nell'intimo."],
[21001,"Il cuore del re è un corso d'acqua in mano al Signore: lo dirige dovunque egli vuole."],
[21002,"Agli occhi dell'uomo ogni sua via sembra diritta, ma chi scruta i cuori è il Signore."],
[21003,"Praticare la giustizia e l'equità per il Signore vale più di un sacrificio."],
[21004,"Occhi alteri e cuore superbo, lucerna dei malvagi è il peccato."],
[21005,"I progetti di chi è diligente si risolvono in profitto, ma chi ha troppa fretta va verso l'indigenza."],
[21006,"Accumulare tesori a forza di menzogne è futilità effimera di chi cerca la morte."],
[21007,"La violenza dei malvagi li travolge, perché rifiutano di praticare la giustizia."],
[21008,"La via di un uomo colpevole è tortuosa, ma l'innocente è retto nel suo agire."],
[21009,"È meglio abitare su un angolo del tetto che avere casa in comune con una moglie litigiosa."],
[21010,"L'anima del malvagio desidera fare il male, ai suoi occhi il prossimo non trova pietà."],
[21011,"Quando lo spavaldo viene punito, l'inesperto diventa saggio; egli acquista scienza quando il saggio viene istruito."],
[21012,"Il giusto osserva la casa del malvagio e precipita i malvagi nella sventura."],
[21013,"Chi chiude l'orecchio al grido del povero invocherà a sua volta e non otterrà risposta."],
[21014,"Un dono fatto in segreto calma la collera, un regalo di nascosto placa il furore violento."],
[21015,"È una gioia per il giusto quando è fatta giustizia, mentre è un terrore per i malfattori."],
[21016,"L'uomo che si scosta dalla via della saggezza, riposerà nell'assemblea delle ombre dei morti."],
[21017,"Diventerà indigente chi ama i piaceri, chi ama vino e profumi non si arricchirà."],
[21018,"Il malvagio serve da riscatto per il giusto e il perfido per gli uomini retti."],
[21019,"Meglio abitare in un deserto che con una moglie litigiosa e irritabile."],
[21020,"Tesori preziosi e profumi sono nella dimora del saggio, ma l'uomo stolto dilapida tutto."],
[21021,"Chi ricerca la giustizia e l'amore troverà vita e gloria."],
[21022,"Il saggio assale una città di guerrieri e abbatte la fortezza in cui essa confidava."],
[21023,"Chi custodisce la bocca e la lingua preserva se stesso dalle afflizioni."],
[21024,"Il superbo arrogante si chiama spavaldo, egli agisce nell'eccesso dell'insolenza."],
[21025,"Il desiderio del pigro lo porta alla morte, perché le sue mani rifiutano di lavorare."],
[21026,"L'empio indulge tutto il giorno alla cupidigia, mentre il giusto dona senza risparmiare."],
[21027,"Il sacrificio dei malvagi è un orrore, tanto più se offerto con cattiva intenzione."],
[21028,"Il falso testimone perirà, ma chi ascolta potrà parlare sempre."],
[21029,"Il malvagio assume un'aria sfrontata, l'uomo retto controlla la propria condotta."],
[21030,"Non c'è sapienza, non c'è prudenza, non c'è consiglio di fronte al Signore."],
[21031,"Il cavallo è pronto per il giorno della battaglia, ma al Signore appartiene la vittoria."],
[22001,"Un buon nome è preferibile a grandi ricchezze e la benevolenza altrui vale più dell'argento e dell'oro."],
[22002,"Il ricco e il povero s'incontrano in questo: il Signore ha creato l'uno e l'altro."],
[22003,"L'accorto vede il pericolo e si nasconde, gli inesperti vanno avanti e la pagano."],
[22004,"Frutti dell'umiltà sono il timore di Dio, la ricchezza, l'onore e la vita."],
[22005,"Spine e tranelli sono sulla via del perverso; chi ha cura di se stesso se ne tiene lontano."],
[22006,"Indirizza il giovane sulla via da seguire; neppure da vecchio se ne allontanerà."],
[22007,"Il ricco domina sul povero e chi riceve prestiti è schiavo del suo creditore."],
[22008,"Chi semina ingiustizia raccoglie miseria e il bastone che usa nella sua collera svanirà."],
[22009,"Chi è generoso sarà benedetto, perché egli dona del suo pane al povero."],
[22010,"Scaccia lo spavaldo e la discordia se ne andrà: cesseranno i litigi e gli insulti."],
[22011,"Chi ama la schiettezza del cuore e la benevolenza sulle labbra, sarà amico del re."],
[22012,"Gli occhi del Signore custodiscono la scienza: in tal modo egli confonde le parole del perfido."],
[22013,"Il pigro dice: \"C'è un leone là fuori: potrei essere ucciso in mezzo alla strada\"."],
[22014,"La bocca delle straniere è una fossa profonda: vi cade colui che è in ira al Signore."],
[22015,"La stoltezza è legata al cuore del fanciullo, ma il bastone della correzione l'allontana da lui."],
[22016,"Chi opprime il povero non fa che arricchirlo, chi dà a un ricco non fa che impoverirsi."],
[22017,"Porgi l'orecchio e ascolta le parole dei sapienti, applica la tua mente alla mia istruzione:"],
[22018,"ti saranno piacevoli se le custodirai nel tuo intimo, se le terrai pronte sulle tue labbra."],
[22019,"Perché sia riposta nel Signore la tua fiducia, oggi le faccio conoscere a te."],
[22020,"Ecco, ho scritto per te trenta massime, in materia di consigli e di saggezza,"],
[22021,"perché tu sappia riferire in modo conveniente parole di verità e possa riportarle a quelli che ti mandano."],
[22022,"Non depredare il povero perché egli è povero, e non affliggere il misero in tribunale,"],
[22023,"perché il Signore difenderà la loro causa e spoglierà della vita coloro che li hanno spogliati."],
[22024,"Non ti associare a un collerico e non praticare un uomo iracondo,"],
[22025,"per non abituarti alle sue maniere e procurarti una trappola per la tua vita."],
[22026,"Non essere di quelli che danno la mano e si fanno garanti dei debiti altrui,"],
[22027,"perché, se poi non avrai da pagare, si dovrebbe togliere il letto di sotto a te."],
[22028,"Non spostare il confine antico, che è stato posto dai tuoi padri."],
[22029,"Hai visto un uomo sollecito nel lavoro? Egli starà al servizio del re e non al servizio di gente oscura!"],
[23001,"Quando siedi a mangiare con uno che ha autorità, bada bene a ciò che ti è messo davanti;"],
[23002,"mettiti un coltello alla gola, se hai molto appetito."],
[23003,"Non bramare le sue ghiottonerie, perché sono un cibo fallace."],
[23004,"Non affannarti per accumulare ricchezze, sii intelligente e rinuncia."],
[23005,"Su di esse volano i tuoi occhi ma già non ci sono più: perché mettono ali come aquila e volano verso il cielo."],
[23006,"Non mangiare il pane dell'avaro e non bramare le sue ghiottonerie,"],
[23007,"perché, come uno che pensa solo a se stesso, ti dirà: \"Mangia e bevi\", ma il suo cuore non è con te."],
[23008,"Vomiterai il boccone che hai mangiato e rovinerai le tue parole gentili."],
[23009,"Non parlare agli orecchi di uno stolto, perché egli disprezzerà le tue sagge parole."],
[23010,"Non spostare il confine antico, e non invadere il campo degli orfani,"],
[23011,"perché il loro vendicatore è forte e difenderà la loro causa contro di te."],
[23012,"Apri il tuo cuore alla correzione e il tuo orecchio ai discorsi sapienti."],
[23013,"Non risparmiare al fanciullo la correzione, perché se lo percuoti con il bastone non morirà;"],
[23014,"anzi, se lo percuoti con il bastone, lo salverai dal regno dei morti."],
[23015,"Figlio mio, se il tuo cuore sarà saggio, anche il mio sarà colmo di gioia."],
[23016,"Esulterò dentro di me, quando le tue labbra diranno parole rette."],
[23017,"Non invidiare in cuor tuo i peccatori, ma resta sempre nel timore del Signore,"],
[23018,"perché così avrai un avvenire e la tua speranza non sarà stroncata."],
[23019,"Ascolta, figlio mio, e sii saggio e indirizza il tuo cuore sulla via retta."],
[23020,"Non essere fra quelli che s'inebriano di vino né fra coloro che sono ingordi di carne,"],
[23021,"perché l'ubriacone e l'ingordo impoveriranno e di stracci li rivestirà la sonnolenza."],
[23022,"Ascolta tuo padre che ti ha generato, non disprezzare tua madre quando è vecchia."],
[23023,"Acquista la verità e non rivenderla, la sapienza, l'educazione e la prudenza."],
[23024,"Il padre del giusto gioirà pienamente, e chi ha generato un saggio se ne compiacerà."],
[23025,"Gioiscano tuo padre e tua madre e si rallegri colei che ti ha generato."],
[23026,"Fa' bene attenzione a me, figlio mio, e piacciano ai tuoi occhi le mie vie:"],
[23027,"una fossa profonda è la prostituta, e un pozzo stretto la straniera."],
[23028,"Ella si apposta come un ladro e fra gli uomini fa crescere il numero dei traditori."],
[23029,"Per chi i guai? Per chi i lamenti? Per chi i litigi? Per chi i gemiti? A chi le percosse per futili motivi? A chi gli occhi torbidi?"],
[23030,"Per quelli che si perdono dietro al vino, per quelli che assaporano bevande inebrianti."],
[23031,"Non guardare il vino come rosseggia, come scintilla nella coppa e come scorre morbidamente;"],
[23032,"finirà per morderti come un serpente e pungerti come una vipera."],
[23033,"Allora i tuoi occhi vedranno cose strane e la tua mente dirà cose sconnesse."],
[23034,"Ti parrà di giacere in alto mare o di giacere in cima all'albero maestro."],
[23035,"\"Mi hanno picchiato, ma non sento male. Mi hanno bastonato, ma non me ne sono accorto. Quando mi sveglierò? Ne chiederò dell'altro!\"."],
[24001,"Non invidiare le persone malvagie, non desiderare di stare con loro,"],
[24002,"poiché il loro cuore trama rovine e le loro labbra non esprimono che malanni."],
[24003,"Con la sapienza si costruisce una casa e con la prudenza la si rende salda;"],
[24004,"con la scienza si riempiono le sue stanze di tutti i beni preziosi e deliziosi."],
[24005,"Il saggio cresce in potenza e chi è esperto aumenta di forza."],
[24006,"Perché con le strategie si fa la guerra e la vittoria dipende dal numero dei consiglieri."],
[24007,"È troppo alta la sapienza per lo stolto, alla porta della città egli non potrà aprire bocca."],
[24008,"Chi trama per fare il male si chiama mestatore."],
[24009,"Il proposito dello stolto è il peccato e lo spavaldo è aborrito da tutti."],
[24010,"Se te ne stai indolente nel giorno della sventura, ben poca è la tua forza."],
[24011,"Libera quelli che sono condotti alla morte e salva quelli che sono trascinati al supplizio."],
[24012,"Se tu dicessi: \"Io non lo sapevo\", credi che non l'intenda colui che pesa i cuori? Colui che veglia sulla tua vita lo sa; egli renderà a ciascuno secondo le sue opere."],
[24013,"Mangia il miele, figlio mio, perché è buono e il favo è dolce al tuo palato."],
[24014,"Sappi che tale è la sapienza per te; se la trovi, avrai un avvenire e la tua speranza non sarà stroncata."],
[24015,"Non insidiare, come un malvagio, la dimora del giusto, non distruggere la sua abitazione,"],
[24016,"perché se il giusto cade sette volte, egli si rialza, ma i malvagi soccombono nella sventura."],
[24017,"Non ti rallegrare per la caduta del tuo nemico e non gioisca il tuo cuore, quando egli soccombe,"],
[24018,"perché il Signore non veda e se ne dispiaccia e allontani da lui la sua collera."],
[24019,"Non irritarti per i malfattori e non invidiare i malvagi,"],
[24020,"perché non ci sarà avvenire per il cattivo e la lampada dei malvagi si spegnerà."],
[24021,"Figlio mio, temi il Signore e il re, e con i ribelli non immischiarti,"],
[24022,"perché improvviso sorgerà il loro castigo e la rovina mandata da entrambi chi la conosce?"],
[24023,"Anche queste sono parole dei saggi. Avere preferenze personali in giudizio non è bene."],
[24024,"Chi dice al malvagio: \"Tu sei innocente\", i popoli lo malediranno, le genti lo detesteranno;"],
[24025,"a chi invece lo punisce tutto andrà bene, su di lui si riverserà la benedizione."],
[24026,"Dà un bacio sulle labbra chi risponde con parole giuste."],
[24027,"Cura prima il tuo lavoro di fuori e preparatelo nel tuo campo, e poi costruisciti la casa."],
[24028,"Non testimoniare senza motivo contro il tuo prossimo, non ingannare con le labbra."],
[24029,"Non dire: \"Come ha fatto a me così io farò a lui, renderò a ciascuno come si merita\"."],
[24030,"Sono passato vicino al campo di un pigro, alla vigna di un uomo insensato:"],
[24031,"ecco, ovunque erano cresciute le erbacce, il terreno era coperto di cardi e il recinto di pietre era in rovina."],
[24032,"Ho osservato e ho riflettuto, ho visto e ho tratto questa lezione:"],
[24033,"un po' dormi, un po' sonnecchi, un po' incroci le braccia per riposare,"],
[24034,"e intanto arriva a te la povertà, come un vagabondo, e l'indigenza, come se tu fossi un accattone."],
[25001,"Anche questi sono proverbi di Salomone, raccolti dagli uomini di Ezechia, re di Giuda."],
[25002,"È gloria di Dio nascondere le cose, è gloria dei re investigarle."],
[25003,"I cieli per la loro altezza, la terra per la sua profondità e il cuore dei re sono inesplorabili."],
[25004,"Togli le scorie dall'argento e l'orafo ne farà un bel vaso;"],
[25005,"togli il malvagio dalla presenza del re e il suo trono si stabilirà sulla giustizia."],
[25006,"Non darti arie davanti al re e non metterti al posto dei grandi,"],
[25007,"perché è meglio sentirsi dire: \"Sali quassù\", piuttosto che essere umiliato davanti a uno più importante. Ciò che i tuoi occhi hanno visto,"],
[25008,"non esibirlo troppo in fretta in un processo; altrimenti che farai alla fine, quando il tuo prossimo ti svergognerà?"],
[25009,"La tua causa discutila con il tuo vicino, ma non rivelare il segreto altrui,"],
[25010,"perché chi ti ascolta non ti biasimi e il tuo discredito sarebbe irreparabile."],
[25011,"Come mele d'oro su vassoio d'argento cesellato, è una parola detta a suo tempo."],
[25012,"Come anello d'oro e collana preziosa è un saggio che ammonisce un orecchio attento."],
[25013,"Come il fresco di neve al tempo della mietitura è un messaggero fedele per chi lo manda: egli rinfranca l'animo del suo signore."],
[25014,"Nuvole e vento, ma senza pioggia, tale è l'uomo che si vanta di regali che non fa."],
[25015,"Con la pazienza il giudice si lascia persuadere, una lingua dolce spezza le ossa."],
[25016,"Se hai trovato il miele, mangiane quanto ti basta, per non esserne nauseato e poi vomitarlo."],
[25017,"Metti di rado il piede in casa del tuo vicino, perché, stanco di te, non ti prenda in odio."],
[25018,"Mazza, spada e freccia acuta è colui che depone il falso contro il suo prossimo."],
[25019,"Quale dente cariato e quale piede slogato, tale è l'appoggio del perfido nel giorno della sventura."],
[25020,"Come chi toglie il mantello in un giorno di freddo e come chi versa aceto su una piaga viva, tale è colui che canta canzoni a un cuore afflitto."],
[25021,"Se il tuo nemico ha fame, dagli pane da mangiare, se ha sete, dagli acqua da bere,"],
[25022,"perché così ammasserai carboni ardenti sul suo capo e il Signore ti ricompenserà."],
[25023,"La tramontana porta la pioggia, la lingua maldicente provoca lo sdegno sul volto."],
[25024,"È meglio abitare su un angolo del tetto, che avere casa in comune con una moglie litigiosa."],
[25025,"Come acqua fresca per una gola riarsa è una buona notizia da un paese lontano."],
[25026,"Fontana torbida e sorgente inquinata, tale è il giusto che vacilla di fronte al malvagio."],
[25027,"Mangiare troppo miele non è bene, né cercare onori eccessivi."],
[25028,"Una città smantellata, senza mura, tale è chi non sa dominare se stesso."],
[26001,"Come neve d'estate e pioggia alla mietitura, così l'onore non conviene allo stolto."],
[26002,"Come passero che svolazza, come rondine che volteggia, così una maledizione immotivata non ha effetto."],
[26003,"La frusta per il cavallo, la cavezza per l'asino e il bastone per la schiena degli stolti."],
[26004,"Non rispondere allo stolto secondo la sua stoltezza, per non divenire anche tu simile a lui."],
[26005,"Rispondi allo stolto secondo la sua stoltezza, perché egli non si creda saggio."],
[26006,"Si taglia i piedi e beve amarezze chi invia messaggi per mezzo di uno stolto."],
[26007,"Come pendono le gambe da uno zoppo, così una massima sulla bocca dello stolto."],
[26008,"Come chi lega una pietra alla fionda, così chi attribuisce onori a uno stolto."],
[26009,"Come ramo spinoso in mano a un ubriaco, così una massima sulla bocca dello stolto."],
[26010,"È come un arciere che colpisce a caso chi paga lo stolto o stipendia il primo che passa."],
[26011,"Come il cane torna al suo vomito, così lo stolto ripete le sue stoltezze."],
[26012,"Hai visto un uomo che è saggio ai suoi occhi? C'è più da sperare da uno stolto che da lui."],
[26013,"Il pigro dice: \"C'è una belva per la strada, un leone si aggira per le piazze\"."],
[26014,"La porta gira sui cardini, così il pigro sul suo letto."],
[26015,"Il pigro immerge la mano nel piatto, ma dura fatica a riportarla alla bocca."],
[26016,"Il pigro si crede più saggio di sette persone che rispondono con senno."],
[26017,"È simile a chi prende un cane per le orecchie un passante che si intromette nella lite di un altro."],
[26018,"Come un pazzo che scaglia  tizzoni e frecce di morte,"],
[26019,"così è colui che inganna il suo prossimo e poi dice: \"Ma sì, è stato uno scherzo!\"."],
[26020,"Per mancanza di legna il fuoco si spegne; se non c'è il calunniatore, il litigio si calma."],
[26021,"Mantice per il carbone e legna per il fuoco, tale è l'attaccabrighe per attizzare le liti."],
[26022,"Le parole del calunniatore sono come ghiotti bocconi, che scendono fin nell'intimo."],
[26023,"Come patina d'argento su un coccio di creta sono le labbra lusinghiere con un cuore maligno."],
[26024,"Chi odia si maschera con le labbra, ma nel suo intimo cova inganni;"],
[26025,"anche se usa espressioni melliflue, non credergli, perché nel cuore egli ha sette obbrobri."],
[26026,"Chi odia si nasconde con astuzia, ma la sua malizia apparirà pubblicamente."],
[26027,"Chi scava una fossa vi cadrà dentro e chi rotola una pietra, gli ricadrà addosso."],
[26028,"Una lingua bugiarda fa molti danni, una bocca adulatrice produce rovina."],
[27001,"Non vantarti del domani, perché non sai neppure che cosa genera l'oggi."],
[27002,"Ti lodi un estraneo e non la tua bocca, uno sconosciuto e non le tue labbra."],
[27003,"La pietra è greve, la sabbia è pesante, ma più d'entrambi la collera dello stolto."],
[27004,"L'ira è crudele, il furore è impetuoso, ma alla gelosia chi può resistere?"],
[27005,"Meglio un rimprovero aperto che un amore nascosto."],
[27006,"Leali sono le ferite di un amico, ingannevoli i baci di un nemico."],
[27007,"Lo stomaco sazio disprezza il miele, per lo stomaco affamato anche l'amaro è dolce."],
[27008,"Come un uccello che vola lontano dal nido, così è l'uomo che va errando lontano da casa."],
[27009,"Profumo e incenso allietano il cuore e il consiglio dell'amico addolcisce l'animo."],
[27010,"Non abbandonare il tuo amico né quello di tuo padre, non entrare nella casa di tuo fratello nel giorno della tua disgrazia. Meglio un amico vicino che un fratello lontano."],
[27011,"Sii saggio, figlio mio, e allieterai il mio cuore; così avrò di che rispondere a colui che mi insulta."],
[27012,"L'accorto vede il pericolo e si nasconde, gli inesperti vanno avanti e la pagano."],
[27013,"Prendigli il vestito perché si è fatto garante per un estraneo, e tienilo in pegno per uno sconosciuto."],
[27014,"Chi benedice il prossimo di buon mattino ad alta voce, sarà considerato come se lo maledicesse."],
[27015,"Lo stillicidio incessante in tempo di pioggia e una moglie litigiosa si rassomigliano:"],
[27016,"chi vuole trattenerla, trattiene il vento e raccoglie l'olio con la mano destra."],
[27017,"Il ferro si aguzza con il ferro e l'uomo aguzza l'ingegno del suo compagno."],
[27018,"Chi custodisce un fico ne mangia i frutti, chi ha cura del suo padrone ne riceverà onori."],
[27019,"Come nell'acqua un volto riflette un volto, così il cuore dell'uomo si riflette nell'altro."],
[27020,"Come il regno dei morti e l'abisso non si saziano mai, così non si saziano mai gli occhi dell'uomo."],
[27021,"Come il crogiuolo è per l'argento e il forno è per l'oro, così l'uomo rispetto alla bocca di chi lo loda."],
[27022,"Anche se tu pestassi lo stolto nel mortaio tra i grani con il pestello, non si allontanerebbe da lui la sua stoltezza."],
[27023,"Preoccupati dello stato del tuo gregge, abbi cura delle tue mandrie,"],
[27024,"perché le ricchezze non sono eterne e una corona non dura per sempre."],
[27025,"Tolto il fieno, ricresce l'erba nuova e si raccolgono i foraggi sui monti;"],
[27026,"gli agnelli ti danno le vesti e i capretti il prezzo per comprare un campo,"],
[27027,"le capre ti danno latte abbondante per nutrire te, per nutrire la tua famiglia e mantenere le tue domestiche."],
[28001,"Il malvagio fugge anche se nessuno lo insegue, mentre il giusto è sicuro come un giovane leone."],
[28002,"Quando un paese è in subbuglio sono molti i suoi capi, ma con un uomo intelligente e saggio l'ordine si mantiene."],
[28003,"Un povero che opprime i miseri è come pioggia torrenziale che non porta pane."],
[28004,"Quelli che trasgrediscono la legge lodano il malvagio, quelli che la osservano gli si mettono contro."],
[28005,"I malvagi non comprendono la giustizia, ma quelli che cercano il Signore comprendono tutto."],
[28006,"Meglio un povero dalla condotta integra che uno dai costumi perversi, anche se ricco."],
[28007,"Osserva la legge il figlio intelligente, chi frequenta gli ingordi disonora suo padre."],
[28008,"Chi accresce il patrimonio con l'usura e l'interesse, lo accumula per chi ha pietà dei miseri."],
[28009,"Chi allontana l'orecchio per non ascoltare la legge, persino la sua preghiera è spregevole."],
[28010,"Chi fa deviare i giusti per la via del male, nel suo tranello lui stesso cadrà, mentre gli integri erediteranno il bene."],
[28011,"Il ricco si crede saggio, ma il povero intelligente lo valuta per quello che è."],
[28012,"Grande è l'onore quando esultano i giusti, ma se prevalgono gli empi ognuno si dilegua."],
[28013,"Chi nasconde le proprie colpe non avrà successo, chi le confessa e le abbandona troverà misericordia."],
[28014,"Beato l'uomo che sempre teme, ma chi indurisce il cuore cadrà nel male."],
[28015,"Leone ruggente e orso affamato, tale è un cattivo governatore su un popolo povero."],
[28016,"Un principe privo di senno moltiplica le angherie, ma chi odia il lucro prolungherà i suoi giorni."],
[28017,"Un uomo che è perseguito per omicidio fuggirà fino alla tomba: non lo si trattenga!"],
[28018,"Chi procede con rettitudine sarà salvato, chi va per vie tortuose cadrà all'improvviso."],
[28019,"Chi coltiva la sua terra si sazia di pane, chi insegue chimere si sazia di miseria."],
[28020,"L'uomo leale sarà colmo di benedizioni, chi ha fretta di arricchirsi non sarà esente da colpa."],
[28021,"Non è bene essere parziali, ma per un tozzo di pane si può prevaricare."],
[28022,"L'avaro è impaziente di arricchire, ma non pensa che gli piomberà addosso la miseria."],
[28023,"Chi corregge un altro troverà alla fine più favore di chi ha una lingua adulatrice."],
[28024,"Chi deruba il padre o la madre e dice: \"Non è peccato\", è simile a un assassino."],
[28025,"L'avido suscita litigi, ma chi confida nel Signore sarà arricchito."],
[28026,"Chi confida nel suo senno è uno stolto, chi cammina nella saggezza sarà salvato."],
[28027,"Per chi dona al povero non c'è indigenza, ma chi chiude gli occhi avrà grandi maledizioni."],
[28028,"Se prevalgono i malvagi, tutti si nascondono; se essi periscono, dominano i giusti."],
[29001,"Chi disprezza i rimproveri con ostinazione sarà rovinato all'improvviso, senza rimedio."],
[29002,"Quando dominano i giusti, il popolo gioisce, quando governano i malvagi, il popolo geme."],
[29003,"Chi ama la sapienza allieta il padre, ma chi frequenta prostitute dissipa il patrimonio."],
[29004,"Il re con la giustizia rende prospero il paese, quello che aggrava le imposte lo rovina."],
[29005,"L'uomo che adula il suo prossimo gli tende una rete davanti ai piedi."],
[29006,"Con la sua trasgressione l'iniquo si prepara un trabocchetto, mentre il giusto giubila e si rallegra."],
[29007,"Il giusto riconosce il diritto dei miseri, il malvagio invece non intende ragione."],
[29008,"Gli uomini senza scrupoli sovvertono una città, mentre i saggi placano la collera."],
[29009,"Se un saggio entra in causa con uno stolto, si agiti o rida, non troverà riposo."],
[29010,"Gli uomini sanguinari odiano l'onesto, mentre i giusti hanno cura di lui."],
[29011,"Lo stolto dà sfogo a tutto il suo malanimo, il saggio alla fine lo sa calmare."],
[29012,"Se un principe dà ascolto alle menzogne, tutti i suoi ministri sono malvagi."],
[29013,"Il povero e l'oppressore s'incontrano in questo: è il Signore che illumina gli occhi di tutti e due."],
[29014,"Se un re giudica i poveri con equità, il suo trono è saldo per sempre."],
[29015,"La verga e la correzione danno sapienza, ma il giovane lasciato a se stesso disonora sua madre."],
[29016,"Quando dominano i malvagi, dominano anche i delitti, ma i giusti ne vedranno la rovina."],
[29017,"Correggi tuo figlio e ti darà riposo e ti procurerà consolazioni."],
[29018,"Quando non c'è visione profetica, il popolo è sfrenato; beato invece chi osserva la legge."],
[29019,"Lo schiavo non si corregge a parole: comprende, infatti, ma non obbedisce."],
[29020,"Hai visto un uomo precipitoso nel parlare? C'è più da sperare da uno stolto che da lui."],
[29021,"Chi accarezza lo schiavo fin dall'infanzia, alla fine se lo vedrà contro."],
[29022,"Un uomo collerico suscita litigi e l'iracondo commette molte colpe."],
[29023,"L'orgoglio dell'uomo ne provoca l'umiliazione, l'umile di cuore ottiene onori."],
[29024,"Chi spartisce con un ladro odia se stesso: egli sente la maledizione, ma non rivela nulla."],
[29025,"Chi teme gli uomini si mette in una trappola, ma chi confida nel Signore è al sicuro."],
[29026,"Molti ricercano il favore di chi comanda, ma è il Signore che giudica ognuno."],
[29027,"L'iniquo è un orrore per i giusti e gli uomini retti sono un orrore per i malvagi."],
[30001,"Detti di Agur, figlio di Iakè, da Massa. Dice quest'uomo: Sono stanco, o Dio, sono stanco, o Dio, e vengo meno,"],
[30002,"perché io sono il più stupido degli uomini e non ho intelligenza umana;"],
[30003,"non ho imparato la sapienza e la scienza del Santo non l'ho conosciuta."],
[30004,"Chi è salito al cielo e ne è sceso? Chi ha raccolto il vento nel suo pugno? Chi ha racchiuso le acque nel suo mantello? Chi ha fissato tutti i confini della terra? Come si chiama? Qual è il nome di suo figlio, se lo sai?"],
[30005,"Ogni parola di Dio è purificata nel fuoco; egli è scudo per chi in lui si rifugia."],
[30006,"Non aggiungere nulla alle sue parole, perché non ti riprenda e tu sia trovato bugiardo."],
[30007,"Io ti domando due cose, non negarmele prima che io muoia:"],
[30008,"tieni lontano da me falsità e menzogna, non darmi né povertà né ricchezza, ma fammi avere il mio pezzo di pane,"],
[30009,"perché, una volta sazio, io non ti rinneghi e dica: \"Chi è il Signore?\", oppure, ridotto all'indigenza, non rubi e abusi del nome del mio Dio."],
[30010,"Non calunniare lo schiavo presso il padrone, perché egli non ti maledica e tu non venga punito."],
[30011,"C'è gente che maledice suo padre e non benedice sua madre."],
[30012,"C'è gente che si crede pura, ma non si è lavata della sua lordura."],
[30013,"C'è gente dagli occhi così alteri e dalle ciglia così altezzose!"],
[30014,"C'è gente i cui denti sono spade e le cui mascelle sono coltelli, per divorare gli umili eliminandoli dalla terra e togliere i poveri di mezzo agli uomini."],
[30015,"La sanguisuga ha due figlie: \"Dammi! Dammi!\". Tre cose non si saziano mai, anzi quattro non dicono mai: \"Basta!\":"],
[30016,"il regno dei morti, il grembo sterile, la terra mai sazia d'acqua e il fuoco che mai dice: \"Basta!\"."],
[30017,"L'occhio che guarda con scherno il padre e si rifiuta di ubbidire alla madre sia cavato dai corvi della valle e divorato dagli aquilotti."],
[30018,"Tre cose sono troppo ardue per me, anzi quattro, che non comprendo affatto:"],
[30019,"la via dell'aquila nel cielo, la via del serpente sulla roccia, la via della nave in alto mare, la via dell'uomo in una giovane donna."],
[30020,"Così si comporta la donna adultera: mangia e si pulisce la bocca e dice: \"Non ho fatto nulla di male!\"."],
[30021,"Per tre cose freme la terra, anzi quattro non può sopportare:"],
[30022,"uno schiavo che diventa re e uno stolto che si sazia di pane,"],
[30023,"una donna già trascurata da tutti che trova marito e una schiava che prende il posto della padrona."],
[30024,"Quattro esseri sono fra le cose più piccole della terra, eppure sono più saggi dei saggi:"],
[30025,"le formiche sono un popolo senza forza, eppure si provvedono il cibo durante l'estate;"],
[30026,"gli iraci sono un popolo imbelle, eppure hanno la tana sulle rupi;"],
[30027,"le cavallette non hanno un re, eppure marciano tutte ben schierate;"],
[30028,"la lucertola si può prendere con le mani, eppure penetra anche nei palazzi dei re."],
[30029,"Tre cose hanno un portamento magnifico, anzi quattro hanno un'andatura maestosa:"],
[30030,"il leone, il più forte degli animali, che non indietreggia davanti a nessuno;"],
[30031,"il gallo pettoruto e il caprone e un re alla testa del suo popolo."],
[30032,"Se stoltamente ti sei esaltato e se poi hai riflettuto, mettiti una mano sulla bocca,"],
[30033,"poiché, sbattendo il latte ne esce la panna, premendo il naso ne esce il sangue e spremendo la collera ne esce la lite."],
[31001,"Parole di Lemuel, re di Massa, che apprese da sua madre."],
[31002,"Che mai, figlio mio! Che mai, figlio del mio grembo! Che mai, figlio dei miei voti!"],
[31003,"Non concedere alle donne il tuo vigore, né i tuoi fianchi a quelle che corrompono i re."],
[31004,"Non conviene ai re, Lemuel, non conviene ai re bere il vino, né ai principi desiderare bevande inebrianti,"],
[31005,"per paura che, bevendo, dimentichino ciò che hanno decretato e tradiscano il diritto di tutti gli infelici."],
[31006,"Date bevande inebrianti a chi si sente venir meno e il vino a chi ha l'amarezza nel cuore:"],
[31007,"beva e dimentichi la sua povertà e non si ricordi più delle sue pene."],
[31008,"Apri la bocca in favore del muto, in difesa di tutti gli sventurati."],
[31009,"Apri la bocca e giudica con equità, rendi giustizia all'infelice e al povero. Alef"],
[31010,"Una donna forte chi potrà trovarla?  Ben superiore alle perle è il suo valore. Bet"],
[31011,"In lei confida il cuore del marito  e non verrà a mancargli il profitto. Ghimel"],
[31012,"Gli dà felicità e non dispiacere  per tutti i giorni della sua vita. Dalet"],
[31013,"Si procura lana e lino  e li lavora volentieri con le mani. He"],
[31014,"È simile alle navi di un mercante,  fa venire da lontano le provviste. Vau"],
[31015,"Si alza quando è ancora notte,  distribuisce il cibo alla sua famiglia  e dà ordini alle sue domestiche. Zain"],
[31016,"Pensa a un campo e lo acquista  e con il frutto delle sue mani pianta una vigna. Het"],
[31017,"Si cinge forte i fianchi  e rafforza le sue braccia. Tet"],
[31018,"È soddisfatta, perché i suoi affari vanno bene;  neppure di notte si spegne la sua lampada. Iod"],
[31019,"Stende la sua mano alla conocchia  e le sue dita tengono il fuso. Caf"],
[31020,"Apre le sue palme al misero,  stende la mano al povero. Lamed"],
[31021,"Non teme la neve per la sua famiglia,  perché tutti i suoi familiari hanno doppio vestito. Mem"],
[31022,"Si è procurata delle coperte,  di lino e di porpora sono le sue vesti. Nun"],
[31023,"Suo marito è stimato alle porte della città,  quando siede in giudizio con gli anziani del luogo. Samec"],
[31024,"Confeziona tuniche e le vende  e fornisce cinture al mercante. Ain"],
[31025,"Forza e decoro sono il suo vestito  e fiduciosa va incontro all'avvenire. Pe"],
[31026,"Apre la bocca con saggezza  e la sua lingua ha solo insegnamenti di bontà. Sade"],
[31027,"Sorveglia l'andamento della sua casa  e non mangia il pane della pigrizia. Kof"],
[31028,"Sorgono i suoi figli e ne esaltano le doti,  suo marito ne tesse l'elogio: Res"],
[31029,"\"Molte figlie hanno compiuto cose eccellenti,  ma tu le hai superate tutte!\". Sin"],
[31030,"Illusorio è il fascino e fugace la bellezza,  ma la donna che teme Dio è da lodare. Tau"],
[31031,"Siatele riconoscenti per il frutto delle sue mani  e le sue opere la lodino alle porte della città."]
])
