Bib.ret([
[1001,"Parole di Qoelet, figlio di Davide, re a Gerusalemme."],
[1002,"Vanità delle vanità, dice Qoelet, vanità delle vanità: tutto è vanità."],
[1003,"Quale guadagno viene all'uomo per tutta la fatica con cui si affanna sotto il sole?"],
[1004,"Una generazione se ne va e un'altra arriva, ma la terra resta sempre la stessa."],
[1005,"Il sole sorge, il sole tramonta e si affretta a tornare là dove rinasce."],
[1006,"Il vento va verso sud e piega verso nord. Gira e va e sui suoi giri ritorna il vento."],
[1007,"Tutti i fiumi scorrono verso il mare, eppure il mare non è mai pieno: al luogo dove i fiumi scorrono, continuano a scorrere."],
[1008,"Tutte le parole si esauriscono e nessuno è in grado di esprimersi a fondo. Non si sazia l'occhio di guardare né l'orecchio è mai sazio di udire."],
[1009,"Quel che è stato sarà e quel che si è fatto si rifarà; non c'è niente di nuovo sotto il sole."],
[1010,"C'è forse qualcosa di cui si possa dire: \"Ecco, questa è una novità\"? Proprio questa è già avvenuta  nei secoli che ci hanno preceduto."],
[1011,"Nessun ricordo resta degli antichi, ma neppure di coloro che saranno si conserverà memoria presso quelli che verranno in seguito."],
[1012,"Io, Qoelet, fui re d'Israele a Gerusalemme."],
[1013,"Mi sono proposto di ricercare ed esplorare con saggezza tutto ciò che si fa sotto il cielo. Questa è un'occupazione gravosa che Dio ha dato agli uomini, perché vi si affatichino."],
[1014,"Ho visto tutte le opere che si fanno sotto il sole, ed ecco: tutto è vanità e un correre dietro al vento."],
[1015,"Ciò che è storto non si può raddrizzare e quel che manca non si può contare."],
[1016,"Pensavo e dicevo fra me: \"Ecco, io sono cresciuto e avanzato in sapienza più di quanti regnarono prima di me a Gerusalemme. La mia mente ha curato molto la sapienza e la scienza\"."],
[1017,"Ho deciso allora di conoscere la sapienza e la scienza, come anche la stoltezza e la follia, e ho capito che anche questo è un correre dietro al vento."],
[1018,"Infatti: molta sapienza, molto affanno; chi accresce il sapere aumenta il dolore."],
[2001,"Io dicevo fra me: \"Vieni, dunque, voglio metterti alla prova con la gioia. Gusta il piacere!\". Ma ecco, anche questo è vanità."],
[2002,"Del riso ho detto: \"Follia!\" e della gioia: \"A che giova?\"."],
[2003,"Ho voluto fare un'esperienza: allietare il mio corpo con il vino e così afferrare la follia, pur dedicandomi con la mente alla sapienza. Volevo scoprire se c'è qualche bene per gli uomini che essi possano realizzare sotto il cielo durante i pochi giorni della loro vita."],
[2004,"Ho intrapreso grandi opere, mi sono fabbricato case, mi sono piantato vigneti."],
[2005,"Mi sono fatto parchi e giardini e vi ho piantato alberi da frutto d'ogni specie;"],
[2006,"mi sono fatto vasche per irrigare con l'acqua quelle piantagioni in crescita."],
[2007,"Ho acquistato schiavi e schiave e altri ne ho avuti nati in casa; ho posseduto anche armenti e greggi in gran numero, più di tutti i miei predecessori a Gerusalemme."],
[2008,"Ho accumulato per me anche argento e oro, ricchezze di re e di province. Mi sono procurato cantori e cantatrici, insieme con molte donne, delizie degli uomini."],
[2009,"Sono divenuto più ricco e più potente di tutti i miei predecessori a Gerusalemme, pur conservando la mia sapienza."],
[2010,"Non ho negato ai miei occhi nulla di ciò che bramavano, né ho rifiutato alcuna soddisfazione al mio cuore, che godeva d'ogni mia fatica: questa è stata la parte che ho ricavato da tutte le mie fatiche."],
[2011,"Ho considerato tutte le opere fatte dalle mie mani e tutta la fatica che avevo affrontato per realizzarle. Ed ecco: tutto è vanità e un correre dietro al vento. Non c'è alcun guadagno sotto il sole."],
[2012,"Ho considerato che cos'è la sapienza, la stoltezza e la follia: \"Che cosa farà il successore del re? Quello che hanno fatto prima di lui\"."],
[2013,"Mi sono accorto che il vantaggio della sapienza sulla stoltezza è come il vantaggio della luce sulle tenebre:"],
[2014,"il saggio ha gli occhi in fronte, ma lo stolto cammina nel buio. Eppure io so che un'unica sorte è riservata a tutti e due."],
[2015,"Allora ho pensato: \"Anche a me toccherà la sorte dello stolto! Perché allora ho cercato d'essere saggio? Dov'è il vantaggio?\". E ho concluso che anche questo è vanità."],
[2016,"Infatti, né del saggio né dello stolto resterà un ricordo duraturo e nei giorni futuri tutto sarà dimenticato. Allo stesso modo muoiono il saggio e lo stolto."],
[2017,"Allora presi in odio la vita, perché mi era insopportabile quello che si fa sotto il sole. Tutto infatti è vanità e un correre dietro al vento."],
[2018,"Ho preso in odio ogni lavoro che con fatica ho compiuto sotto il sole, perché dovrò lasciarlo al mio successore."],
[2019,"E chi sa se questi sarà saggio o stolto? Eppure potrà disporre di tutto il mio lavoro, in cui ho speso fatiche e intelligenza sotto il sole. Anche questo è vanità!"],
[2020,"Sono giunto al punto di disperare in cuor mio per tutta la fatica che avevo sostenuto sotto il sole,"],
[2021,"perché chi ha lavorato con sapienza, con scienza e con successo dovrà poi lasciare la sua parte a un altro che non vi ha per nulla faticato. Anche questo è vanità e un grande male."],
[2022,"Infatti, quale profitto viene all'uomo da tutta la sua fatica e dalle preoccupazioni del suo cuore, con cui si affanna sotto il sole?"],
[2023,"Tutti i suoi giorni non sono che dolori e fastidi penosi; neppure di notte il suo cuore riposa. Anche questo è vanità!"],
[2024,"Non c'è di meglio per l'uomo che mangiare e bere e godersi il frutto delle sue fatiche; mi sono accorto che anche questo viene dalle mani di Dio."],
[2025,"Difatti, chi può mangiare o godere senza di lui?"],
[2026,"Egli concede a chi gli è gradito sapienza, scienza e gioia, mentre a chi fallisce dà la pena di raccogliere e di ammassare, per darlo poi a colui che è gradito a Dio. Ma anche questo è vanità e un correre dietro al vento!"],
[3001,"Tutto ha il suo momento, e ogni evento ha il suo tempo sotto il cielo."],
[3002,"C'è un tempo per nascere e un tempo per morire, un tempo per piantare e un tempo per sradicare quel che si è piantato."],
[3003,"Un tempo per uccidere e un tempo per curare, un tempo per demolire e un tempo per costruire."],
[3004,"Un tempo per piangere e un tempo per ridere, un tempo per fare lutto e un tempo per danzare."],
[3005,"Un tempo per gettare sassi e un tempo per raccoglierli, un tempo per abbracciare e un tempo per astenersi dagli abbracci."],
[3006,"Un tempo per cercare e un tempo per perdere, un tempo per conservare e un tempo per buttar via."],
[3007,"Un tempo per strappare e un tempo per cucire, un tempo per tacere e un tempo per parlare."],
[3008,"Un tempo per amare e un tempo per odiare, un tempo per la guerra e un tempo per la pace."],
[3009,"Che guadagno ha chi si dà da fare con fatica?"],
[3010,"Ho considerato l'occupazione che Dio ha dato agli uomini perché vi si affatichino."],
[3011,"Egli ha fatto bella ogni cosa a suo tempo; inoltre ha posto nel loro cuore la durata dei tempi, senza però che gli uomini possano trovare la ragione di ciò che Dio compie dal principio alla fine."],
[3012,"Ho capito che per essi non c'è nulla di meglio che godere e procurarsi felicità durante la loro vita;"],
[3013,"e che un uomo mangi, beva e goda del suo lavoro, anche questo è dono di Dio."],
[3014,"Riconosco che qualsiasi cosa Dio fa, dura per sempre; non c'è nulla da aggiungere, nulla da togliere. Dio agisce così perché lo si tema."],
[3015,"Quello che accade, già è stato; quello che sarà, già è avvenuto. Solo Dio può cercare ciò che ormai è scomparso."],
[3016,"Ma ho anche notato che sotto il sole al posto del diritto c'è l'iniquità e al posto della giustizia c'è l'iniquità."],
[3017,"Ho pensato dentro di me: \"Il giusto e il malvagio Dio li giudicherà, perché c'è un tempo per ogni cosa e per ogni azione\"."],
[3018,"Poi, riguardo ai figli dell'uomo, mi sono detto che Dio vuole metterli alla prova e mostrare che essi di per sé sono bestie."],
[3019,"Infatti la sorte degli uomini e quella delle bestie è la stessa: come muoiono queste, così muoiono quelli; c'è un solo soffio vitale per tutti. L'uomo non ha alcun vantaggio sulle bestie, perché tutto è vanità."],
[3020,"Tutti sono diretti verso il medesimo luogo: tutto è venuto dalla polvere e nella polvere tutto ritorna."],
[3021,"Chi sa se il soffio vitale dell'uomo sale in alto, mentre quello della bestia scende in basso, nella terra?"],
[3022,"Mi sono accorto che nulla c'è di meglio per l'uomo che godere delle sue opere, perché questa è la parte che gli spetta; e chi potrà condurlo a vedere ciò che accadrà dopo di lui?"],
[4001,"Tornai poi a considerare tutte le oppressioni che si fanno sotto il sole. Ecco le lacrime degli oppressi e non c'è chi li consoli; dalla parte dei loro oppressori sta la violenza, ma non c'è chi li consoli."],
[4002,"Allora ho proclamato felici i morti, ormai trapassati, più dei viventi che sono ancora in vita;"],
[4003,"ma più felice degli uni e degli altri chi ancora non esiste, e non ha visto le azioni malvagie che si fanno sotto il sole."],
[4004,"Ho osservato anche che ogni fatica e ogni successo ottenuto non sono che invidia dell'uno verso l'altro. Anche questo è vanità, un correre dietro al vento."],
[4005,"Lo stolto incrocia le sue braccia e divora la sua carne."],
[4006,"Meglio una manciata guadagnata con calma che due manciate con tormento e una corsa dietro al vento."],
[4007,"E tornai a considerare quest'altra vanità sotto il sole:"],
[4008,"il caso di chi è solo e non ha nessuno, né figlio né fratello. Eppure non smette mai di faticare, né il suo occhio è mai sazio di ricchezza: \"Per chi mi affatico e mi privo dei beni?\". Anche questo è vanità e un'occupazione gravosa."],
[4009,"Meglio essere in due che uno solo, perché otterranno migliore compenso per la loro fatica."],
[4010,"Infatti, se cadono, l'uno rialza l'altro. Guai invece a chi è solo: se cade, non ha nessuno che lo rialzi."],
[4011,"Inoltre, se si dorme in due, si sta caldi; ma uno solo come fa a riscaldarsi?"],
[4012,"Se uno è aggredito, in due possono resistere: una corda a tre capi non si rompe tanto presto."],
[4013,"Meglio un giovane povero ma accorto, che un re vecchio e stolto, che non sa più accettare consigli."],
[4014,"Il giovane infatti può uscire di prigione ed essere fatto re, anche se, mentre quello regnava, era nato povero."],
[4015,"Ho visto tutti i viventi che si muovono sotto il sole stare con quel giovane, che era subentrato al re."],
[4016,"Era una folla immensa quella che gli stava davanti. Ma coloro che verranno dopo non si rallegreranno neppure di lui. Anche questo è vanità, un correre dietro al vento."],
[4017,"Bada ai tuoi passi quando ti rechi alla casa di Dio. Avvicinati per ascoltare piuttosto che offrire sacrifici, come fanno gli stolti, i quali non sanno di fare del male."],
[5001,"Non essere precipitoso con la bocca e il tuo cuore non si affretti a proferire parole davanti a Dio, perché Dio è in cielo e tu sei sulla terra; perciò siano poche le tue parole."],
[5002,"Infatti dalle molte preoccupazioni vengono i sogni, e dalle molte chiacchiere il discorso dello stolto."],
[5003,"Quando hai fatto un voto a Dio, non tardare a soddisfarlo, perché a lui non piace il comportamento degli stolti: adempi quello che hai promesso."],
[5004,"È meglio non fare voti che farli e poi non mantenerli."],
[5005,"Non permettere alla tua bocca di renderti colpevole e davanti al suo messaggero non dire che è stata una inavvertenza, perché Dio non abbia ad adirarsi per le tue parole e distrugga l'opera delle tue mani."],
[5006,"Poiché dai molti sogni provengono molte illusioni e tante parole. Tu, dunque, temi Dio!"],
[5007,"Se nella provincia vedi il povero oppresso e il diritto e la giustizia calpestati, non ti meravigliare di questo, poiché sopra un'autorità veglia un'altra superiore e sopra di loro un'altra ancora più alta."],
[5008,"In ogni caso, la terra è a profitto di tutti, ma è il re a servirsi della campagna."],
[5009,"Chi ama il denaro non è mai sazio di denaro e chi ama la ricchezza non ha mai entrate sufficienti. Anche questo è vanità."],
[5010,"Con il crescere delle ricchezze aumentano i profittatori e quale soddisfazione ne riceve il padrone se non di vederle con gli occhi?"],
[5011,"Dolce è il sonno del lavoratore, poco o molto che mangi; ma la sazietà del ricco non lo lascia dormire."],
[5012,"Un altro brutto guaio ho visto sotto il sole: ricchezze custodite dal padrone a suo danno."],
[5013,"Se ne vanno in fumo queste ricchezze per un cattivo affare e il figlio che gli è nato non ha nulla nelle mani."],
[5014,"Come è uscito dal grembo di sua madre, nudo ancora se ne andrà come era venuto, e dalle sue fatiche non ricaverà nulla da portare con sé."],
[5015,"Anche questo è un brutto guaio: che se ne vada proprio come è venuto. Quale profitto ricava dall'avere gettato le sue fatiche al vento?"],
[5016,"Tutti i giorni della sua vita li ha passati nell'oscurità, fra molti fastidi, malanni e crucci."],
[5017,"Ecco quello che io ritengo buono e bello per l'uomo: è meglio mangiare e bere e godere dei beni per ogni fatica sopportata sotto il sole, nei pochi giorni di vita che Dio gli dà, perché questa è la sua parte."],
[5018,"Inoltre ad ogni uomo, al quale Dio concede ricchezze e beni, egli dà facoltà di mangiarne, prendere la sua parte e godere della sua fatica: anche questo è dono di Dio."],
[5019,"Egli infatti non penserà troppo ai giorni della sua vita, poiché Dio lo occupa con la gioia del suo cuore."],
[6001,"Un altro male ho visto sotto il sole, che grava molto sugli uomini."],
[6002,"A uno Dio ha concesso beni, ricchezze, onori e non gli manca niente di quanto desidera; ma Dio non gli concede di poterne godere, anzi sarà un estraneo a divorarli. Ciò è vanità e grave malanno."],
[6003,"Se uno avesse cento figli e vivesse molti anni e molti fossero i giorni della sua vita, se egli non gode a sazietà dei suoi beni e non ha neppure una tomba, allora io dico che l'aborto è meglio di lui."],
[6004,"Questi infatti viene come un soffio, se ne va nella tenebra e l'oscurità copre il suo nome,"],
[6005,"non vede neppure il sole, non sa niente; così è nella quiete, a differenza dell'altro!"],
[6006,"Se quell'uomo vivesse anche due volte mille anni, senza godere dei suoi beni, non dovranno forse andare tutti e due nel medesimo luogo?"],
[6007,"Tutta la fatica dell'uomo è per la bocca, ma la sua fame non è mai sazia."],
[6008,"Quale vantaggio ha il saggio sullo stolto? Qual è il vantaggio del povero nel sapersi destreggiare nella vita?"],
[6009,"Meglio vedere con gli occhi che vagare con il desiderio. Anche questo è vanità e un correre dietro al vento."],
[6010,"Ciò che esiste, da tempo ha avuto un nome, e si sa che cos'è un uomo: egli non può contendere in giudizio con chi è più forte di lui."],
[6011,"Più aumentano le parole, più cresce il vuoto, e quale utilità c'è per l'uomo?"],
[6012,"Chi sa quel che è bene per l'uomo durante la sua vita, nei pochi giorni della sua vana esistenza, che passa via come un'ombra? Chi può indicare all'uomo che cosa avverrà dopo di lui sotto il sole?"],
[7001,"Un buon nome è preferibile all'unguento profumato e il giorno della morte al giorno della nascita."],
[7002,"È meglio visitare una casa dove c'è lutto che visitare una casa dove si banchetta, perché quella è la fine d'ogni uomo e chi vive ci deve riflettere."],
[7003,"È preferibile la mestizia al riso, perché con un volto triste il cuore diventa migliore."],
[7004,"Il cuore dei saggi è in una casa in lutto e il cuore degli stolti in una casa in festa."],
[7005,"Meglio ascoltare il rimprovero di un saggio che ascoltare la lode degli stolti:"],
[7006,"perché quale il crepitio dei pruni sotto la pentola tale è il riso degli stolti. Ma anche questo è vanità."],
[7007,"L'estorsione rende stolto il saggio e i regali corrompono il cuore."],
[7008,"Meglio la fine di una cosa che il suo principio; è meglio un uomo paziente che uno presuntuoso."],
[7009,"Non essere facile a irritarti in cuor tuo, perché la collera dimora in seno agli stolti."],
[7010,"Non dire: \"Come mai i tempi antichi erano migliori del presente?\", perché una domanda simile non è ispirata a saggezza."],
[7011,"Buona cosa è la saggezza unita a un patrimonio ed è utile per coloro che vedono il sole."],
[7012,"Perché si sta all'ombra della saggezza come si sta all'ombra del denaro; ma vale di più il sapere, perché la saggezza fa vivere chi la possiede."],
[7013,"Osserva l'opera di Dio: chi può raddrizzare ciò che egli ha fatto curvo?"],
[7014,"Nel giorno lieto sta' allegro e nel giorno triste rifletti: Dio ha fatto tanto l'uno quanto l'altro, cosicché l'uomo non riesce a scoprire ciò che verrà dopo di lui."],
[7015,"Nei miei giorni vani ho visto di tutto: un giusto che va in rovina nonostante la sua giustizia, un malvagio che vive a lungo nonostante la sua iniquità."],
[7016,"Non essere troppo giusto e non mostrarti saggio oltre misura: perché vuoi rovinarti?"],
[7017,"Non essere troppo malvagio e non essere stolto. Perché vuoi morire prima del tempo?"],
[7018,"È bene che tu prenda una cosa senza lasciare l'altra: in verità chi teme Dio riesce bene in tutto."],
[7019,"La sapienza rende il saggio più forte di dieci potenti che sono nella città."],
[7020,"Non c'è infatti sulla terra un uomo così giusto che faccia solo il bene e non sbagli mai."],
[7021,"Ancora: non fare attenzione a tutte le dicerie che si fanno, così non sentirai che il tuo servo ha detto male di te;"],
[7022,"infatti il tuo cuore sa che anche tu tante volte hai detto male degli altri."],
[7023,"Tutto questo io ho esaminato con sapienza e ho detto: \"Voglio diventare saggio!\", ma la sapienza resta lontana da me!"],
[7024,"Rimane lontano ciò che accade: profondo, profondo! Chi può comprenderlo?"],
[7025,"Mi sono applicato a conoscere e indagare e cercare la sapienza e giungere a una conclusione, e a riconoscere che la malvagità è stoltezza e la stoltezza è follia."],
[7026,"Trovo che amara più della morte è la donna: essa è tutta lacci, una rete il suo cuore, catene le sue braccia. Chi è gradito a Dio la sfugge, ma chi fallisce ne resta preso."],
[7027,"Vedi, questo ho scoperto, dice Qoelet, confrontando a una a una le cose, per arrivare a una conclusione certa."],
[7028,"Quello che io ancora sto cercando e non ho trovato è questo: un uomo fra mille l'ho trovato, ma una donna fra tutte non l'ho trovata."],
[7029,"Vedi, solo questo ho trovato: Dio ha creato gli esseri umani retti, ma essi vanno in cerca di infinite complicazioni."],
[8001,"Chi è come il saggio? Chi conosce la spiegazione delle cose? La sapienza dell'uomo rischiara il suo volto, ne cambia la durezza del viso."],
[8002,"Osserva gli ordini del re, per il giuramento fatto a Dio."],
[8003,"Non allontanarti in fretta da lui; non persistere in un cattivo progetto, perché egli può fare ciò che vuole."],
[8004,"Infatti, la parola del re è sovrana; chi può dirgli: \"Che cosa fai?\"."],
[8005,"Chi osserva il comando non va incontro ad alcun male; la mente del saggio conosce il tempo opportuno."],
[8006,"Infatti, per ogni evento vi è un tempo opportuno, ma un male pesa gravemente sugli esseri umani."],
[8007,"L'uomo infatti ignora che cosa accadrà; chi mai può indicargli come avverrà?"],
[8008,"Nessun uomo è padrone del suo soffio vitale tanto da trattenerlo, né alcuno ha potere sul giorno della morte. Non c'è scampo dalla lotta e neppure la malvagità può salvare colui che la compie."],
[8009,"Tutto questo ho visto riflettendo su ogni azione che si compie sotto il sole, quando un uomo domina sull'altro per rovinarlo."],
[8010,"Frattanto ho visto malvagi condotti alla sepoltura; ritornando dal luogo santo, in città ci si dimentica del loro modo di agire. Anche questo è vanità."],
[8011,"Poiché non si pronuncia una sentenza immediata contro una cattiva azione, per questo il cuore degli uomini è pieno di voglia di fare il male;"],
[8012,"infatti il peccatore, anche se commette il male cento volte, ha lunga vita. Tuttavia so che saranno felici coloro che temono Dio, appunto perché provano timore davanti a lui,"],
[8013,"e non sarà felice l'empio e non allungherà come un'ombra i suoi giorni, perché egli non teme di fronte a Dio."],
[8014,"Sulla terra c'è un'altra vanità: vi sono giusti ai quali tocca la sorte meritata dai malvagi con le loro opere, e vi sono malvagi ai quali tocca la sorte meritata dai giusti con le loro opere. Io dico che anche questo è vanità."],
[8015,"Perciò faccio l'elogio dell'allegria, perché l'uomo non ha altra felicità sotto il sole che mangiare e bere e stare allegro. Sia questa la sua compagnia nelle sue fatiche, durante i giorni di vita che Dio gli concede sotto il sole."],
[8016,"Quando mi dedicai a conoscere la sapienza e a considerare le occupazioni per cui ci si affanna sulla terra - poiché l'uomo non conosce sonno né giorno né notte -"],
[8017,"ho visto che l'uomo non può scoprire tutta l'opera di Dio, tutto quello che si fa sotto il sole: per quanto l'uomo si affatichi a cercare, non scoprirà nulla. Anche se un sapiente dicesse di sapere, non potrà scoprire nulla."],
[9001,"A tutto questo mi sono dedicato, ed ecco tutto ciò che ho verificato: i giusti e i sapienti e le loro fatiche sono nelle mani di Dio, anche l'amore e l'odio; l'uomo non conosce nulla di ciò che gli sta di fronte."],
[9002,"Vi è una sorte unica per tutti: per il giusto e per il malvagio, per il puro e per l'impuro, per chi offre sacrifici e per chi non li offre, per chi è buono e per chi è cattivo, per chi giura e per chi teme di giurare."],
[9003,"Questo è il male in tutto ciò che accade sotto il sole: una medesima sorte tocca a tutti e per di più il cuore degli uomini è pieno di male e la stoltezza dimora in loro mentre sono in vita. Poi se ne vanno fra i morti."],
[9004,"Certo, finché si resta uniti alla società dei viventi, c'è speranza: meglio un cane vivo che un leone morto."],
[9005,"I vivi sanno che devono morire, ma i morti non sanno nulla; non c'è più salario per loro, è svanito il loro ricordo."],
[9006,"Il loro amore, il loro odio e la loro invidia, tutto è ormai finito, non avranno più alcuna parte in tutto ciò che accade sotto il sole."],
[9007,"Su, mangia con gioia il tuo pane e bevi il tuo vino con cuore lieto, perché Dio ha già gradito le tue opere."],
[9008,"In ogni tempo siano candide le tue vesti e il profumo non manchi sul tuo capo."],
[9009,"Godi la vita con la donna che ami per tutti i giorni della tua fugace esistenza che Dio ti concede sotto il sole, perché questa è la tua parte nella vita e nelle fatiche che sopporti sotto il sole."],
[9010,"Tutto ciò che la tua mano è in grado di fare, fallo con tutta la tua forza, perché non ci sarà né attività né calcolo né scienza né sapienza nel regno dei morti, dove stai per andare."],
[9011,"Tornai a considerare un'altra cosa sotto il sole: che non è degli agili la corsa né dei forti la guerra, e neppure dei sapienti il pane e degli accorti la ricchezza, e nemmeno degli intelligenti riscuotere stima, perché il tempo e il caso raggiungono tutti."],
[9012,"Infatti l'uomo non conosce neppure la sua ora: simile ai pesci che sono presi dalla rete fatale e agli uccelli presi al laccio, l'uomo è sorpreso dalla sventura che improvvisa si abbatte su di lui."],
[9013,"Anche quest'altro esempio di sapienza ho visto sotto il sole e mi parve assai grave:"],
[9014,"c'era una piccola città con pochi abitanti. Un grande re si mosse contro di essa, l'assediò e costruì contro di essa grandi fortificazioni."],
[9015,"Si trovava però in essa un uomo povero ma saggio, il quale con la sua sapienza salvò la città; eppure nessuno si ricordò di quest'uomo povero."],
[9016,"Allora io dico: \"È meglio la sapienza che la forza, ma la sapienza del povero è disprezzata e le sue parole non sono ascoltate\"."],
[9017,"Le parole pacate dei sapienti si ascoltano meglio delle urla di un comandante di folli."],
[9018,"Vale più la sapienza che le armi da guerra, ma un solo errore può distruggere un bene immenso."],
[10001,"Una mosca morta guasta l'unguento del profumiere: un po' di follia ha più peso della sapienza e dell'onore."],
[10002,"Il cuore del sapiente va alla sua destra, il cuore dello stolto alla sua sinistra."],
[10003,"E anche quando lo stolto cammina per strada, il suo cuore è privo di senno e di ognuno dice: \"Quello è un pazzo\"."],
[10004,"Se l'ira di un potente si accende contro di te, non lasciare il tuo posto, perché la calma pone rimedio a errori anche gravi."],
[10005,"C'è un male che io ho osservato sotto il sole, uno sbaglio commesso da un sovrano:"],
[10006,"la stoltezza viene collocata in posti elevati e i ricchi siedono in basso."],
[10007,"Ho visto schiavi andare a cavallo e principi camminare a piedi, per terra, come schiavi."],
[10008,"Chi scava una fossa vi può cadere dentro e chi abbatte un muro può essere morso da una serpe."],
[10009,"Chi spacca pietre può farsi male e chi taglia legna può correre pericoli."],
[10010,"Se il ferro si ottunde e non se ne affila il taglio, bisogna raddoppiare gli sforzi: il guadagno sta nel saper usare la saggezza."],
[10011,"Se il serpente morde prima d'essere incantato, non c'è profitto per l'incantatore."],
[10012,"Le parole del saggio procurano stima, ma le labbra dello stolto lo mandano in rovina:"],
[10013,"l'esordio del suo parlare è sciocchezza, la fine del suo discorso pazzia funesta."],
[10014,"L'insensato moltiplica le parole, ma l'uomo non sa quello che accadrà: chi può indicargli ciò che avverrà dopo di lui?"],
[10015,"Lo stolto si ammazza di fatica, ma non sa neppure andare in città."],
[10016,"Povero te, o paese, che per re hai un ragazzo e i tuoi principi banchettano fin dal mattino!"],
[10017,"Fortunato te, o paese, che per re hai un uomo libero e i tuoi principi mangiano al tempo dovuto, per rinfrancarsi e non per gozzovigliare."],
[10018,"Per negligenza il soffitto crolla e per l'inerzia delle mani piove in casa."],
[10019,"Per stare lieti si fanno banchetti e il vino allieta la vita, ma il denaro risponde a ogni esigenza."],
[10020,"Non dire male del re neppure con il pensiero e nella tua stanza da letto non dire male del potente, perché un uccello del cielo potrebbe trasportare la tua voce e un volatile riferire la tua parola."],
[11001,"Getta il tuo pane sulle acque, perché con il tempo lo ritroverai."],
[11002,"Fanne sette o otto parti, perché non sai quale sciagura potrà arrivare sulla terra."],
[11003,"Se le nubi sono piene d'acqua, la rovesciano sopra la terra; se un albero cade verso meridione o verso settentrione, là dove cade rimane."],
[11004,"Chi bada al vento non semina mai, e chi osserva le nuvole non miete."],
[11005,"Come tu non conosci la via del soffio vitale né come si formino le membra nel grembo d'una donna incinta, così ignori l'opera di Dio che fa tutto."],
[11006,"Fin dal mattino semina il tuo seme e a sera non dare riposo alle tue mani, perché non sai quale lavoro ti riuscirà meglio, se questo o quello, o se tutti e due andranno bene."],
[11007,"Dolce è la luce e bello è per gli occhi vedere il sole."],
[11008,"Anche se l'uomo vive molti anni, se li goda tutti, e pensi ai giorni tenebrosi, che saranno molti: tutto ciò che accade è vanità."],
[11009,"Godi, o giovane, nella tua giovinezza, e si rallegri il tuo cuore nei giorni della tua gioventù. Segui pure le vie del tuo cuore e i desideri dei tuoi occhi. Sappi però che su tutto questo Dio ti convocherà in giudizio."],
[11010,"Caccia la malinconia dal tuo cuore, allontana dal tuo corpo il dolore, perché la giovinezza e i capelli neri sono un soffio."],
[12001,"Ricordati del tuo creatore nei giorni della tua giovinezza, prima che vengano i giorni tristi e giungano gli anni di cui dovrai dire: \"Non ci provo alcun gusto\";"],
[12002,"prima che si oscurino il sole, la luce, la luna e le stelle e tornino ancora le nubi dopo la pioggia;"],
[12003,"quando tremeranno i custodi della casa e si curveranno i gagliardi e cesseranno di lavorare le donne che macinano, perché rimaste poche, e si offuscheranno quelle che guardano dalle finestre"],
[12004,"e si chiuderanno i battenti sulla strada; quando si abbasserà il rumore della mola e si attenuerà il cinguettio degli uccelli e si affievoliranno tutti i toni del canto;"],
[12005,"quando si avrà paura delle alture e terrore si proverà nel cammino; quando fiorirà il mandorlo e la locusta si trascinerà a stento e il cappero non avrà più effetto, poiché l'uomo se ne va nella dimora eterna e i piagnoni si aggirano per la strada;"],
[12006,"prima che si spezzi il filo d'argento e la lucerna d'oro s'infranga  e si rompa l'anfora alla fonte e la carrucola cada nel pozzo,"],
[12007,"e ritorni la polvere alla terra, com'era prima, e il soffio vitale torni a Dio, che lo ha dato."],
[12008,"Vanità delle vanità, dice Qoelet, tutto è vanità."],
[12009,"Oltre a essere saggio, Qoelet insegnò al popolo la scienza; ascoltò, meditò e compose un gran numero di massime."],
[12010,"Qoelet cercò di trovare parole piacevoli e scrisse con onestà parole veritiere."],
[12011,"Le parole dei saggi sono come pungoli, e come chiodi piantati sono i detti delle collezioni: sono dati da un solo pastore."],
[12012,"Ancora un avvertimento, figlio mio: non si finisce mai di scrivere libri e il molto studio affatica il corpo."],
[12013,"Conclusione del discorso, dopo aver ascoltato tutto: temi Dio e osserva i suoi comandamenti, perché qui sta tutto l'uomo."],
[12014,"Infatti, Dio citerà in giudizio ogni azione, anche tutto ciò che è occulto, bene o male."]
])
