Bib.ret([
[1001,"Paolo, servo di Cristo Gesù, apostolo per chiamata, scelto per annunciare il vangelo di Dio -"],
[1002,"che egli aveva promesso per mezzo dei suoi profeti nelle sacre Scritture"],
[1003,"e che riguarda il Figlio suo, nato dal seme di Davide secondo la carne,"],
[1004,"costituito Figlio di Dio con potenza, secondo lo Spirito di santità, in virtù della risurrezione dei morti, Gesù Cristo nostro Signore;"],
[1005,"per mezzo di lui abbiamo ricevuto la grazia di essere apostoli, per suscitare l'obbedienza della fede in tutte le genti, a gloria del suo nome,"],
[1006,"e tra queste siete anche voi, chiamati da Gesù Cristo -,"],
[1007,"a tutti quelli che sono a Roma, amati da Dio e santi per chiamata, grazia a voi e pace da Dio, Padre nostro, e dal Signore Gesù Cristo!"],
[1008,"Anzitutto rendo grazie al mio Dio per mezzo di Gesù Cristo riguardo a tutti voi, perché della vostra fede si parla nel mondo intero."],
[1009,"Mi è testimone Dio, al quale rendo culto nel mio spirito annunciando il vangelo del Figlio suo, come io continuamente faccia memoria di voi,"],
[1010,"chiedendo sempre nelle mie preghiere che, in qualche modo, un giorno, per volontà di Dio, io abbia l'opportunità di venire da voi."],
[1011,"Desidero infatti ardentemente vedervi per comunicarvi qualche dono spirituale, perché ne siate fortificati,"],
[1012,"o meglio, per essere in mezzo a voi confortato mediante la fede che abbiamo in comune, voi e io."],
[1013,"Non voglio che ignoriate, fratelli, che più volte mi sono proposto di venire fino a voi - ma finora ne sono stato impedito - per raccogliere qualche frutto anche tra voi, come tra le altre nazioni."],
[1014,"Sono in debito verso i Greci come verso i barbari, verso i sapienti come verso gli ignoranti:"],
[1015,"sono quindi pronto, per quanto sta in me, ad annunciare il Vangelo anche a voi che siete a Roma."],
[1016,"Io infatti non mi vergogno del Vangelo, perché è potenza di Dio per la salvezza di chiunque crede, del Giudeo, prima, come del Greco."],
[1017,"In esso infatti si rivela la giustizia di Dio, da fede a fede, come sta scritto:  Il giusto per fede vivrà ."],
[1018,"Infatti l'ira di Dio si rivela dal cielo contro ogni empietà e ogni ingiustizia di uomini che soffocano la verità nell'ingiustizia,"],
[1019,"poiché ciò che di Dio si può conoscere è loro manifesto; Dio stesso lo ha manifestato a loro."],
[1020,"Infatti le sue perfezioni invisibili, ossia la sua eterna potenza e divinità, vengono contemplate e comprese dalla creazione del mondo attraverso le opere da lui compiute. Essi dunque non hanno alcun motivo di scusa"],
[1021,"perché, pur avendo conosciuto Dio, non lo hanno glorificato né ringraziato come Dio, ma si sono perduti nei loro vani ragionamenti e la loro mente ottusa si è ottenebrata."],
[1022,"Mentre si dichiaravano sapienti, sono diventati stolti"],
[1023,"e hanno scambiato la gloria del Dio incorruttibile con un'immagine e una figura di uomo corruttibile, di uccelli, di quadrupedi e di rettili."],
[1024,"Perciò Dio li ha abbandonati all'impurità secondo i desideri del loro cuore, tanto da disonorare fra loro i propri corpi,"],
[1025,"perché hanno scambiato la verità di Dio con la menzogna e hanno adorato e servito le creature anziché il Creatore, che è benedetto nei secoli. Amen."],
[1026,"Per questo Dio li ha abbandonati a passioni infami; infatti, le loro femmine hanno cambiato i rapporti naturali in quelli contro natura."],
[1027,"Similmente anche i maschi, lasciando il rapporto naturale con la femmina, si sono accesi di desiderio gli uni per gli altri, commettendo atti ignominiosi maschi con maschi, ricevendo così in se stessi la retribuzione dovuta al loro traviamento."],
[1028,"E poiché non ritennero di dover conoscere Dio adeguatamente, Dio li ha abbandonati alla loro intelligenza depravata ed essi hanno commesso azioni indegne:"],
[1029,"sono colmi di ogni ingiustizia, di malvagità, di cupidigia, di malizia; pieni d'invidia, di omicidio, di lite, di frode, di malignità; diffamatori,"],
[1030,"maldicenti, nemici di Dio, arroganti, superbi, presuntuosi, ingegnosi nel male, ribelli ai genitori,"],
[1031,"insensati, sleali, senza cuore, senza misericordia."],
[1032,"E, pur conoscendo il giudizio di Dio, che cioè gli autori di tali cose meritano la morte, non solo le commettono, ma anche approvano chi le fa."],
[2001,"Perciò chiunque tu sia, o uomo che giudichi, non hai alcun motivo di scusa perché, mentre giudichi l'altro, condanni te stesso; tu che giudichi, infatti, fai le medesime cose."],
[2002,"Eppure noi sappiamo che il giudizio di Dio contro quelli che commettono tali cose è secondo verità."],
[2003,"Tu che giudichi quelli che commettono tali azioni e intanto le fai tu stesso, pensi forse di sfuggire al giudizio di Dio?"],
[2004,"O disprezzi la ricchezza della sua bontà, della sua clemenza e della sua magnanimità, senza riconoscere che la bontà di Dio ti spinge alla conversione?"],
[2005,"Tu, però, con il tuo cuore duro e ostinato, accumuli collera su di te per il giorno dell'ira e della rivelazione del giusto giudizio di Dio,"],
[2006,"che  renderà a ciascuno secondo le sue opere :"],
[2007,"la vita eterna a coloro che, perseverando nelle opere di bene, cercano gloria, onore, incorruttibilità;"],
[2008,"ira e sdegno contro coloro che, per ribellione, disobbediscono alla verità e obbediscono all'ingiustizia."],
[2009,"Tribolazione e angoscia su ogni uomo che opera il male, sul Giudeo, prima, come sul Greco;"],
[2010,"gloria invece, onore e pace per chi opera il bene, per il Giudeo, prima, come per il Greco:"],
[2011,"Dio infatti non fa preferenza di persone."],
[2012,"Tutti quelli che hanno peccato senza la Legge, senza la Legge periranno; quelli invece che hanno peccato sotto la Legge, con la Legge saranno giudicati."],
[2013,"Infatti, non quelli che ascoltano la Legge sono giusti davanti a Dio, ma quelli che mettono in pratica la Legge saranno giustificati."],
[2014,"Quando i pagani, che non hanno la Legge, per natura agiscono secondo la Legge, essi, pur non avendo Legge, sono legge a se stessi."],
[2015,"Essi dimostrano che quanto la Legge esige è scritto nei loro cuori, come risulta dalla testimonianza della loro coscienza e dai loro stessi ragionamenti, che ora li accusano ora li difendono."],
[2016,"Così avverrà nel giorno in cui Dio giudicherà i segreti degli uomini, secondo il mio Vangelo, per mezzo di Cristo Gesù."],
[2017,"Ma se tu ti chiami Giudeo e ti riposi sicuro sulla Legge e metti il tuo vanto in Dio,"],
[2018,"ne conosci la volontà e, istruito dalla Legge, sai discernere ciò che è meglio,"],
[2019,"e sei convinto di essere guida dei ciechi, luce di coloro che sono nelle tenebre,"],
[2020,"educatore degli ignoranti, maestro dei semplici, perché nella Legge possiedi l'espressione della conoscenza e della verità..."],
[2021,"Ebbene, come mai tu, che insegni agli altri, non insegni a te stesso? Tu che predichi di non rubare, rubi?"],
[2022,"Tu che dici di non commettere adulterio, commetti adulterio? Tu che detesti gli idoli, ne derubi i templi?"],
[2023,"Tu che ti vanti della Legge, offendi Dio trasgredendo la Legge!"],
[2024,"Infatti sta scritto:  Il nome di Dio è bestemmiato per causa vostra tra le genti ."],
[2025,"Certo, la circoncisione è utile se osservi la Legge; ma, se trasgredisci la Legge, con la tua circoncisione sei un non circonciso."],
[2026,"Se dunque chi non è circonciso osserva le prescrizioni della Legge, la sua incirconcisione non sarà forse considerata come circoncisione?"],
[2027,"E così, chi non è circonciso fisicamente, ma osserva la Legge, giudicherà te che, nonostante la lettera della Legge e la circoncisione, sei trasgressore della Legge."],
[2028,"Giudeo, infatti, non è chi appare tale all'esterno, e la circoncisione non è quella visibile nella carne;"],
[2029,"ma Giudeo è colui che lo è interiormente e la circoncisione è quella del cuore, nello spirito, non nella lettera; la sua lode non viene dagli uomini, ma da Dio."],
[3001,"Che cosa dunque ha in più il Giudeo? E qual è l'utilità della circoncisione?"],
[3002,"Grande, sotto ogni aspetto. Anzitutto perché a loro sono state affidate le parole di Dio."],
[3003,"Che dunque? Se alcuni furono infedeli, la loro infedeltà annullerà forse la fedeltà di Dio?"],
[3004,"Impossibile! Sia chiaro invece che Dio è veritiero, mentre ogni uomo è mentitore, come sta scritto: Affinché tu sia riconosciuto giusto nelle tue parole e vinca quando sei giudicato ."],
[3005,"Se però la nostra ingiustizia mette in risalto la giustizia di Dio, che diremo? Dio è forse ingiusto quando riversa su di noi la sua ira? Sto parlando alla maniera umana."],
[3006,"Impossibile! Altrimenti, come potrà Dio giudicare il mondo?"],
[3007,"Ma se la verità di Dio abbondò nella mia menzogna, risplende di più per la sua gloria, perché anch'io sono giudicato ancora come peccatore?"],
[3008,"E non è come alcuni ci fanno dire: \"Facciamo il male perché ne venga il bene\"; essi ci calunniano ed è giusto che siano condannati."],
[3009,"Che dunque? Siamo forse noi superiori? No! Infatti abbiamo già formulato l'accusa che, Giudei e Greci, tutti sono sotto il dominio del peccato,"],
[3010,"come sta scritto: Non c'è nessun giusto, nemmeno uno,"],
[3011,"non c'è chi comprenda, non c'è nessuno che cerchi Dio !"],
[3012,"Tutti hanno smarrito la via, insieme si sono corrotti; non c'è chi compia il bene, non ce n'è neppure uno."],
[3013,"La loro gola è un sepolcro spalancato, tramavano inganni con la loro lingua, veleno di serpenti è sotto le loro labbra,"],
[3014,"la loro bocca è piena di maledizione e di amarezza."],
[3015,"I loro piedi corrono a versare sangue;"],
[3016,"rovina e sciagura è sul loro cammino"],
[3017,"e la via della pace non l'hanno conosciuta."],
[3018,"Non c'è timore di Dio davanti ai loro occhi ."],
[3019,"Ora, noi sappiamo che quanto la Legge dice, lo dice per quelli che sono sotto la Legge, di modo che ogni bocca sia chiusa e il mondo intero sia riconosciuto colpevole di fronte a Dio."],
[3020,"Infatti in base alle opere della Legge nessun vivente sarà giustificato davanti a Dio, perché per mezzo della Legge si ha conoscenza del peccato."],
[3021,"Ora invece, indipendentemente dalla Legge, si è manifestata la giustizia di Dio, testimoniata dalla Legge e dai Profeti:"],
[3022,"giustizia di Dio per mezzo della fede in Gesù Cristo, per tutti quelli che credono. Infatti non c'è differenza,"],
[3023,"perché tutti hanno peccato e sono privi della gloria di Dio,"],
[3024,"ma sono giustificati gratuitamente per la sua grazia, per mezzo della redenzione che è in Cristo Gesù."],
[3025,"È lui che Dio ha stabilito apertamente come strumento di espiazione, per mezzo della fede, nel suo sangue, a manifestazione della sua giustizia per la remissione dei peccati passati"],
[3026,"mediante la clemenza di Dio, al fine di manifestare la sua giustizia nel tempo presente, così da risultare lui giusto e rendere giusto colui che si basa sulla fede in Gesù."],
[3027,"Dove dunque sta il vanto? È stato escluso! Da quale legge? Da quella delle opere? No, ma dalla legge della fede."],
[3028,"Noi riteniamo infatti che l'uomo è giustificato per la fede, indipendentemente dalle opere della Legge."],
[3029,"Forse Dio è Dio soltanto dei Giudei? Non lo è anche delle genti? Certo, anche delle genti!"],
[3030,"Poiché unico è il Dio che giustificherà i circoncisi in virtù della fede e gli incirconcisi per mezzo della fede."],
[3031,"Togliamo dunque ogni valore alla Legge mediante la fede? Nient'affatto, anzi confermiamo la Legge."],
[4001,"Che diremo dunque di Abramo, nostro progenitore secondo la carne? Che cosa ha ottenuto?"],
[4002,"Se infatti Abramo è stato giustificato per le opere, ha di che gloriarsi, ma non davanti a Dio."],
[4003,"Ora, che cosa dice la Scrittura?  Abramo credette a Dio e ciò gli fu accreditato come giustizia ."],
[4004,"A chi lavora, il salario non viene calcolato come dono, ma come debito;"],
[4005,"a chi invece non lavora, ma crede in Colui che giustifica l'empio, la sua fede gli viene accreditata come giustizia."],
[4006,"Così anche Davide proclama beato l'uomo a cui Dio accredita la giustizia indipendentemente dalle opere:"],
[4007,"Beati quelli le cui iniquità sono state perdonate e i peccati sono stati ricoperti;"],
[4008,"beato l'uomo al quale il Signore non mette in conto il peccato!"],
[4009,"Ora, questa beatitudine riguarda chi è circonciso o anche chi non è circonciso? Noi diciamo infatti che la fede fu accreditata ad Abramo come giustizia."],
[4010,"Come dunque gli fu accreditata? Quando era circonciso o quando non lo era? Non dopo la circoncisione, ma prima."],
[4011,"Infatti egli ricevette il segno della circoncisione come sigillo della giustizia, derivante dalla fede, già ottenuta quando non era ancora circonciso. In tal modo egli divenne padre di tutti i non circoncisi che credono, cosicché anche a loro venisse accreditata la giustizia"],
[4012,"ed egli fosse padre anche dei circoncisi, di quelli che non solo provengono dalla circoncisione ma camminano anche sulle orme della fede del nostro padre Abramo prima della sua circoncisione."],
[4013,"Infatti non in virtù della Legge fu data ad Abramo, o alla sua discendenza, la promessa di diventare erede del mondo, ma in virtù della giustizia che viene dalla fede."],
[4014,"Se dunque diventassero eredi coloro che provengono dalla Legge, sarebbe resa vana la fede e inefficace la promessa."],
[4015,"La Legge infatti provoca l'ira; al contrario, dove non c'è Legge, non c'è nemmeno trasgressione."],
[4016,"Eredi dunque si diventa in virtù della fede, perché sia secondo la grazia, e in tal modo la promessa sia sicura per tutta la discendenza: non soltanto per quella che deriva dalla Legge, ma anche per quella che deriva dalla fede di Abramo, il quale è padre di tutti noi  -"],
[4017,"come sta scritto:  Ti ho costituito padre di molti popoli - davanti al Dio nel quale credette, che dà vita ai morti e chiama all'esistenza le cose che non esistono."],
[4018,"Egli credette, saldo nella speranza contro ogni speranza, e così divenne padre di molti popoli,  come gli era stato detto:  Così sarà la tua discendenza ."],
[4019,"Egli non vacillò nella fede, pur vedendo già come morto il proprio corpo - aveva circa cento anni - e morto il seno di Sara."],
[4020,"Di fronte alla promessa di Dio non esitò per incredulità, ma si rafforzò nella fede e diede gloria a Dio,"],
[4021,"pienamente convinto che quanto egli aveva promesso era anche capace di portarlo a compimento."],
[4022,"Ecco perché gli fu accreditato come giustizia."],
[4023,"E non soltanto per lui è stato scritto che  gli fu accreditato ,"],
[4024,"ma anche per noi, ai quali deve essere accreditato: a noi che crediamo in colui che ha risuscitato dai morti Gesù nostro Signore,"],
[4025,"il quale è stato consegnato alla morte a causa delle nostre colpe ed è stato risuscitato per la nostra giustificazione."],
[5001,"Giustificati dunque per fede, noi siamo in pace con Dio per mezzo del Signore nostro Gesù Cristo."],
[5002,"Per mezzo di lui abbiamo anche, mediante la fede, l'accesso a questa grazia nella quale ci troviamo e ci vantiamo, saldi nella speranza della gloria di Dio."],
[5003,"E non solo: ci vantiamo anche nelle tribolazioni, sapendo che la tribolazione produce pazienza,"],
[5004,"la pazienza una virtù provata e la virtù provata la speranza."],
[5005,"La speranza poi non delude, perché l'amore di Dio è stato riversato nei nostri cuori per mezzo dello Spirito Santo che ci è stato dato."],
[5006,"Infatti, quando eravamo ancora deboli, nel tempo stabilito Cristo morì per gli empi."],
[5007,"Ora, a stento qualcuno è disposto a morire per un giusto; forse qualcuno oserebbe morire per una persona buona."],
[5008,"Ma Dio dimostra il suo amore verso di noi nel fatto che, mentre eravamo ancora peccatori, Cristo è morto per noi."],
[5009,"A maggior ragione ora, giustificati nel suo sangue, saremo salvati dall'ira per mezzo di lui."],
[5010,"Se infatti, quand'eravamo nemici, siamo stati riconciliati con Dio per mezzo della morte del Figlio suo, molto più, ora che siamo riconciliati, saremo salvati mediante la sua vita."],
[5011,"Non solo, ma ci gloriamo pure in Dio, per mezzo del Signore nostro Gesù Cristo, grazie al quale ora abbiamo ricevuto la riconciliazione."],
[5012,"Quindi, come a causa di un solo uomo il peccato è entrato nel mondo e, con il peccato, la morte, e così in tutti gli uomini si è propagata la morte, poiché tutti hanno peccato..."],
[5013,"Fino alla Legge infatti c'era il peccato nel mondo e, anche se il peccato non può essere imputato quando manca la Legge,"],
[5014,"la morte regnò da Adamo fino a Mosè anche su quelli che non avevano peccato a somiglianza della trasgressione di Adamo, il quale è figura di colui che doveva venire."],
[5015,"Ma il dono di grazia non è come la caduta: se infatti per la caduta di uno solo tutti morirono, molto di più la grazia di Dio e il dono concesso in grazia del solo uomo Gesù Cristo si sono riversati in abbondanza su tutti."],
[5016,"E nel caso del dono non è come nel caso di quel solo che ha peccato: il giudizio infatti viene da uno solo, ed è per la condanna, il dono di grazia invece da molte cadute, ed è per la giustificazione."],
[5017,"Infatti se per la caduta di uno solo la morte ha regnato a causa di quel solo uomo, molto di più quelli che ricevono l'abbondanza della grazia e del dono della giustizia regneranno nella vita per mezzo del solo Gesù Cristo."],
[5018,"Come dunque per la caduta di uno solo si è riversata su tutti gli uomini la condanna, così anche per l'opera giusta di uno solo si riversa su tutti gli uomini la giustificazione, che dà vita."],
[5019,"Infatti, come per la disobbedienza di un solo uomo tutti sono stati costituiti peccatori, così anche per l'obbedienza di uno solo tutti saranno costituiti giusti."],
[5020,"La Legge poi sopravvenne perché abbondasse la caduta; ma dove abbondò il peccato, sovrabbondò la grazia."],
[5021,"Di modo che, come regnò il peccato nella morte, così regni anche la grazia mediante la giustizia per la vita eterna, per mezzo di Gesù Cristo nostro Signore."],
[6001,"Che diremo dunque? Rimaniamo nel peccato perché abbondi la grazia?"],
[6002,"È assurdo! Noi, che già siamo morti al peccato, come potremo ancora vivere in esso?"],
[6003,"O non sapete che quanti siamo stati battezzati in Cristo Gesù, siamo stati battezzati nella sua morte?"],
[6004,"Per mezzo del battesimo dunque siamo stati sepolti insieme a lui nella morte affinché, come Cristo fu risuscitato dai morti per mezzo della gloria del Padre, così anche noi possiamo camminare in una vita nuova."],
[6005,"Se infatti siamo stati intimamente uniti a lui a somiglianza della sua morte, lo saremo anche a somiglianza della sua risurrezione."],
[6006,"Lo sappiamo: l'uomo vecchio che è in noi è stato crocifisso con lui, affinché fosse reso inefficace questo corpo di peccato, e noi non fossimo più schiavi del peccato."],
[6007,"Infatti chi è morto, è liberato dal peccato."],
[6008,"Ma se siamo morti con Cristo, crediamo che anche vivremo con lui,"],
[6009,"sapendo che Cristo, risorto dai morti, non muore più; la morte non ha più potere su di lui."],
[6010,"Infatti egli morì, e morì per il peccato una volta per tutte; ora invece vive, e vive per Dio."],
[6011,"Così anche voi consideratevi morti al peccato, ma viventi per Dio, in Cristo Gesù."],
[6012,"Il peccato dunque non regni più nel vostro corpo mortale, così da sottomettervi ai suoi desideri."],
[6013,"Non offrite al peccato le vostre membra come strumenti di ingiustizia, ma offrite voi stessi a Dio come viventi, ritornati dai morti, e le vostre membra a Dio come strumenti di giustizia."],
[6014,"Il peccato infatti non dominerà su di voi, perché non siete sotto la Legge, ma sotto la grazia."],
[6015,"Che dunque? Ci metteremo a peccare perché non siamo sotto la Legge, ma sotto la grazia? È assurdo!"],
[6016,"Non sapete che, se vi mettete a servizio di qualcuno come schiavi per obbedirgli, siete schiavi di colui al quale obbedite: sia del peccato che porta alla morte, sia dell'obbedienza che conduce alla giustizia?"],
[6017,"Rendiamo grazie a Dio, perché eravate schiavi del peccato, ma avete obbedito di cuore a quella forma di insegnamento alla quale siete stati affidati."],
[6018,"Così, liberati dal peccato, siete stati resi schiavi della giustizia."],
[6019,"Parlo un linguaggio umano a causa della vostra debolezza. Come infatti avete messo le vostre membra a servizio dell'impurità e dell'iniquità, per l'iniquità, così ora mettete le vostre membra a servizio della giustizia, per la santificazione."],
[6020,"Quando infatti eravate schiavi del peccato, eravate liberi nei riguardi della giustizia."],
[6021,"Ma quale frutto raccoglievate allora da cose di cui ora vi vergognate? Il loro traguardo infatti è la morte."],
[6022,"Ora invece, liberati dal peccato e fatti servi di Dio, raccogliete il frutto per la vostra santificazione e come traguardo avete la vita eterna."],
[6023,"Perché il salario del peccato è la morte; ma il dono di Dio è la vita eterna in Cristo Gesù, nostro Signore."],
[7001,"O forse ignorate, fratelli - parlo a gente che conosce la legge - che la legge ha potere sull'uomo solo per il tempo in cui egli vive?"],
[7002,"La donna sposata, infatti, per legge è legata al marito finché egli vive; ma se il marito muore, è liberata dalla legge che la lega al marito."],
[7003,"Ella sarà dunque considerata adultera se passa a un altro uomo mentre il marito vive; ma se il marito muore ella è libera dalla legge, tanto che non è più adultera se passa a un altro uomo."],
[7004,"Alla stessa maniera, fratelli miei, anche voi, mediante il corpo di Cristo, siete stati messi a morte quanto alla Legge per appartenere a un altro, cioè a colui che fu risuscitato dai morti, affinché noi portiamo frutti per Dio."],
[7005,"Quando infatti eravamo nella debolezza della carne, le passioni peccaminose, stimolate dalla Legge, si scatenavano nelle nostre membra al fine di portare frutti per la morte."],
[7006,"Ora invece, morti a ciò che ci teneva prigionieri, siamo stati liberati dalla Legge per servire secondo lo Spirito, che è nuovo, e non secondo la lettera, che è antiquata."],
[7007,"Che diremo dunque? Che la Legge è peccato? No, certamente! Però io non ho conosciuto il peccato se non mediante la Legge. Infatti non avrei conosciuto la concupiscenza, se la Legge non avesse detto:  Non desiderare ."],
[7008,"Ma, presa l'occasione, il peccato scatenò in me, mediante il comandamento, ogni sorta di desideri. Senza la Legge infatti il peccato è morto."],
[7009,"E un tempo io vivevo senza la Legge ma, sopraggiunto il precetto, il peccato ha ripreso vita"],
[7010,"e io sono morto. Il comandamento, che doveva servire per la vita, è divenuto per me motivo di morte."],
[7011,"Il peccato infatti, presa l'occasione, mediante il comandamento mi ha sedotto e per mezzo di esso mi ha dato la morte."],
[7012,"Così la Legge è santa, e santo, giusto e buono è il comandamento."],
[7013,"Ciò che è bene allora è diventato morte per me? No davvero! Ma il peccato, per rivelarsi peccato, mi ha dato la morte servendosi di ciò che è bene, perché il peccato risultasse oltre misura peccaminoso per mezzo del comandamento."],
[7014,"Sappiamo infatti che la Legge è spirituale, mentre io sono carnale, venduto come schiavo del peccato."],
[7015,"Non riesco a capire ciò che faccio: infatti io faccio non quello che voglio, ma quello che detesto."],
[7016,"Ora, se faccio quello che non voglio, riconosco che la Legge è buona;"],
[7017,"quindi non sono più io a farlo, ma il peccato che abita in me."],
[7018,"Io so infatti che in me, cioè nella mia carne, non abita il bene: in me c'è il desiderio del bene, ma non la capacità di attuarlo;"],
[7019,"infatti io non compio il bene che voglio, ma il male che non voglio."],
[7020,"Ora, se faccio quello che non voglio, non sono più io a farlo, ma il peccato che abita in me."],
[7021,"Dunque io trovo in me questa legge: quando voglio fare il bene, il male è accanto a me."],
[7022,"Infatti nel mio intimo acconsento alla legge di Dio,"],
[7023,"ma nelle mie membra vedo un'altra legge, che combatte contro la legge della mia ragione e mi rende schiavo della legge del peccato, che è nelle mie membra."],
[7024,"Me infelice! Chi mi libererà da questo corpo di morte?"],
[7025,"Siano rese grazie a Dio per mezzo di Gesù Cristo nostro Signore! Io dunque, con la mia ragione, servo la legge di Dio, con la mia carne invece la legge del peccato."],
[8001,"Ora, dunque, non c'è nessuna condanna per quelli che sono in Cristo Gesù."],
[8002,"Perché la legge dello Spirito, che dà vita in Cristo Gesù, ti ha liberato dalla legge del peccato e della morte."],
[8003,"Infatti ciò che era impossibile alla Legge, resa impotente a causa della carne, Dio lo ha reso possibile: mandando il proprio Figlio in una carne simile a quella del peccato e a motivo del peccato, egli ha condannato il peccato nella carne,"],
[8004,"perché la giustizia della Legge fosse compiuta in noi, che camminiamo non secondo la carne ma secondo lo Spirito."],
[8005,"Quelli infatti che vivono secondo la carne, tendono verso ciò che è carnale; quelli invece che vivono secondo lo Spirito, tendono verso ciò che è spirituale."],
[8006,"Ora, la carne tende alla morte, mentre lo Spirito tende alla vita e alla pace."],
[8007,"Ciò a cui tende la carne è contrario a Dio, perché non si sottomette alla legge di Dio, e neanche lo potrebbe."],
[8008,"Quelli che si lasciano dominare dalla carne non possono piacere a Dio."],
[8009,"Voi però non siete sotto il dominio della carne, ma dello Spirito, dal momento che lo Spirito di Dio abita in voi. Se qualcuno non ha lo Spirito di Cristo, non gli appartiene."],
[8010,"Ora, se Cristo è in voi, il vostro corpo è morto per il peccato, ma lo Spirito è vita per la giustizia."],
[8011,"E se lo Spirito di Dio, che ha risuscitato Gesù dai morti, abita in voi, colui che ha risuscitato Cristo dai morti darà la vita anche ai vostri corpi mortali per mezzo del suo Spirito che abita in voi."],
[8012,"Così dunque, fratelli, noi siamo debitori non verso la carne, per vivere secondo i desideri carnali,"],
[8013,"perché, se vivete secondo la carne, morirete. Se, invece, mediante lo Spirito fate morire le opere del corpo, vivrete."],
[8014,"Infatti tutti quelli che sono guidati dallo Spirito di Dio, questi sono figli di Dio."],
[8015,"E voi non avete ricevuto uno spirito da schiavi per ricadere nella paura, ma avete ricevuto lo Spirito che rende figli adottivi, per mezzo del quale gridiamo: \"Abbà! Padre!\"."],
[8016,"Lo Spirito stesso, insieme al nostro spirito, attesta che siamo figli di Dio."],
[8017,"E se siamo figli, siamo anche eredi: eredi di Dio, coeredi di Cristo, se davvero prendiamo parte alle sue sofferenze per partecipare anche alla sua gloria."],
[8018,"Ritengo infatti che le sofferenze del tempo presente non siano paragonabili alla gloria futura che sarà rivelata in noi."],
[8019,"L'ardente aspettativa della creazione, infatti, è protesa verso la rivelazione dei figli di Dio."],
[8020,"La creazione infatti è stata sottoposta alla caducità - non per sua volontà, ma per volontà di colui che l'ha sottoposta - nella speranza"],
[8021,"che anche la stessa creazione sarà liberata dalla schiavitù della corruzione per entrare nella libertà della gloria dei figli di Dio."],
[8022,"Sappiamo infatti che tutta insieme la creazione geme e soffre le doglie del parto fino ad oggi."],
[8023,"Non solo, ma anche noi, che possediamo le primizie dello Spirito, gemiamo interiormente aspettando l'adozione a figli, la redenzione del nostro corpo."],
[8024,"Nella speranza infatti siamo stati salvati. Ora, ciò che si spera, se è visto, non è più oggetto di speranza; infatti, ciò che uno già vede, come potrebbe sperarlo?"],
[8025,"Ma, se speriamo quello che non vediamo, lo attendiamo con perseveranza."],
[8026,"Allo stesso modo anche lo Spirito viene in aiuto alla nostra debolezza; non sappiamo infatti come pregare in modo conveniente, ma lo Spirito stesso intercede con gemiti inesprimibili;"],
[8027,"e colui che scruta i cuori sa che cosa desidera lo Spirito, perché egli intercede per i santi secondo i disegni di Dio."],
[8028,"Del resto, noi sappiamo che tutto concorre al bene, per quelli che amano Dio, per coloro che sono stati chiamati secondo il suo disegno."],
[8029,"Poiché quelli che egli da sempre ha conosciuto, li ha anche predestinati a essere conformi all'immagine del Figlio suo, perché egli sia il primogenito tra molti fratelli;"],
[8030,"quelli poi che ha predestinato, li ha anche chiamati; quelli che ha chiamato, li ha anche giustificati; quelli che ha giustificato, li ha anche glorificati."],
[8031,"Che diremo dunque di queste cose? Se Dio è per noi, chi sarà contro di noi?"],
[8032,"Egli, che non ha risparmiato il proprio Figlio, ma lo ha consegnato per tutti noi, non ci donerà forse ogni cosa insieme a lui?"],
[8033,"Chi muoverà accuse contro coloro che Dio ha scelto? Dio è colui che giustifica!"],
[8034,"Chi condannerà? Cristo Gesù è morto, anzi è risorto, sta alla destra di Dio e intercede per noi!"],
[8035,"Chi ci separerà dall'amore di Cristo? Forse la tribolazione, l'angoscia, la persecuzione, la fame, la nudità, il pericolo, la spada?"],
[8036,"Come sta scritto: Per causa tua siamo messi a morte tutto il giorno, siamo considerati come pecore da macello ."],
[8037,"Ma in tutte queste cose noi siamo più che vincitori grazie a colui che ci ha amati."],
[8038,"Io sono infatti persuaso che né morte né vita, né angeli né principati, né presente né avvenire, né potenze,"],
[8039,"né altezza né profondità, né alcun'altra creatura potrà mai separarci dall'amore di Dio, che è in Cristo Gesù, nostro Signore."],
[9001,"Dico la verità in Cristo, non mento, e la mia coscienza me ne dà testimonianza nello Spirito Santo:"],
[9002,"ho nel cuore un grande dolore e una sofferenza continua."],
[9003,"Vorrei infatti essere io stesso anatema, separato da Cristo a vantaggio dei miei fratelli, miei consanguinei secondo la carne."],
[9004,"Essi sono Israeliti e hanno l'adozione a figli, la gloria, le alleanze, la legislazione, il culto, le promesse;"],
[9005,"a loro appartengono i patriarchi e da loro proviene Cristo secondo la carne, egli che è sopra ogni cosa, Dio benedetto nei secoli. Amen."],
[9006,"Tuttavia la parola di Dio non è venuta meno. Infatti non tutti i discendenti d'Israele sono Israele,"],
[9007,"né per il fatto di essere discendenza di Abramo sono tutti suoi figli, ma:  In Isacco ti sarà data una discendenza ;"],
[9008,"cioè: non i figli della carne sono figli di Dio, ma i figli della promessa sono considerati come discendenza."],
[9009,"Questa infatti è la parola della promessa:  Io verrò in questo tempo e Sara avrà un figlio ."],
[9010,"E non è tutto: anche Rebecca ebbe figli da un solo uomo, Isacco nostro padre;"],
[9011,"quando essi non erano ancora nati e nulla avevano fatto di bene o di male - perché rimanesse fermo il disegno divino fondato sull'elezione, non in base alle opere, ma alla volontà di colui che chiama -,"],
[9012,"le fu dichiarato:  Il maggiore sarà sottomesso al minore ,"],
[9013,"come sta scritto: Ho amato Giacobbe e ho odiato Esaù ."],
[9014,"Che diremo dunque? C'è forse ingiustizia da parte di Dio? No, certamente!"],
[9015,"Egli infatti dice a Mosè: Avrò misericordia per chi vorrò averla, e farò grazia a chi vorrò farla ."],
[9016,"Quindi non dipende dalla volontà né dagli sforzi dell'uomo, ma da Dio che ha misericordia."],
[9017,"Dice infatti la Scrittura al faraone:  Ti ho fatto sorgere per manifestare in te la mia potenza e perché il mio nome sia proclamato in tutta la terra ."],
[9018,"Dio quindi ha misericordia verso chi vuole e rende ostinato chi vuole."],
[9019,"Mi potrai però dire: \"Ma allora perché ancora rimprovera? Chi infatti può resistere al suo volere?\"."],
[9020,"O uomo, chi sei tu, per contestare Dio?  Oserà forse dire il vaso plasmato a colui che lo plasmò: \"Perché mi hai fatto  così?\"."],
[9021,"Forse il vasaio non è padrone dell'argilla, per fare con la medesima pasta un vaso per uso nobile e uno per uso volgare?"],
[9022,"Anche Dio, volendo manifestare la sua ira e far conoscere la sua potenza, ha sopportato con grande magnanimità gente meritevole di collera, pronta per la perdizione."],
[9023,"E questo, per far conoscere la ricchezza della sua gloria verso gente meritevole di misericordia, da lui predisposta alla gloria,"],
[9024,"cioè verso di noi, che egli ha chiamato non solo tra i Giudei ma anche tra i pagani."],
[9025,"Esattamente come dice Osea: Chiamerò mio popolo quello che non era mio popolo e mia amata quella che non era l'amata."],
[9026,"E avverrà che, nel luogo stesso dove fu detto loro : \"Voi non siete mio popolo\", là saranno chiamati figli del Dio vivente ."],
[9027,"E quanto a Israele, Isaia esclama: Se anche il numero dei figli d'Israele fosse come la sabbia del mare, solo il resto sarà salvato;"],
[9028,"perché con pienezza e rapidità il Signore compirà la sua parola sulla terra ."],
[9029,"E come predisse Isaia: Se il Signore degli eserciti non ci avesse lasciato una discendenza, saremmo divenuti come Sodoma e resi simili a Gomorra ."],
[9030,"Che diremo dunque? Che i pagani, i quali non cercavano la giustizia, hanno raggiunto la giustizia, la giustizia però che deriva dalla fede;"],
[9031,"mentre Israele, il quale cercava una Legge che gli desse la giustizia, non raggiunse lo scopo della Legge."],
[9032,"E perché mai? Perché agiva non mediante la fede, ma mediante le opere. Hanno urtato contro la pietra d'inciampo,"],
[9033,"come sta scritto: Ecco, io pongo in Sion una pietra d'inciampo e un sasso che fa cadere; ma chi crede in lui non sarà deluso ."],
[10001,"Fratelli, il desiderio del mio cuore e la mia preghiera salgono a Dio per la loro salvezza."],
[10002,"Infatti rendo loro testimonianza che hanno zelo per Dio, ma non secondo una retta conoscenza."],
[10003,"Perché, ignorando la giustizia di Dio e cercando di stabilire la propria, non si sono sottomessi alla giustizia di Dio."],
[10004,"Ora, il termine della Legge è Cristo, perché la giustizia sia data a chiunque crede."],
[10005,"Mosè descrive così la giustizia che viene dalla Legge:  L'uomo che la mette in pratica, per mezzo di essa vivrà ."],
[10006,"Invece, la giustizia che viene dalla fede parla così:  Non dire nel tuo cuore: Chi salirà al cielo?  - per farne cioè discendere Cristo -;"],
[10007,"oppure:  Chi scenderà nell'abisso?  - per fare cioè risalire Cristo dai morti."],
[10008,"Che cosa dice dunque?  Vicino a te è la Parola, sulla tua bocca e nel tuo cuore , cioè la parola della fede che noi predichiamo."],
[10009,"Perché se con la tua bocca proclamerai: \"Gesù è il Signore!\", e con il tuo cuore crederai che Dio lo ha risuscitato dai morti, sarai salvo."],
[10010,"Con il cuore infatti si crede per ottenere la giustizia, e con la bocca si fa la professione di fede per avere la salvezza."],
[10011,"Dice infatti la Scrittura:  Chiunque crede in lui non sarà deluso ."],
[10012,"Poiché non c'è distinzione fra Giudeo e Greco, dato che lui stesso è il Signore di tutti, ricco verso tutti quelli che lo invocano."],
[10013,"Infatti:  Chiunque invocherà il nome del Signore sarà salvato ."],
[10014,"Ora, come invocheranno colui nel quale non hanno creduto? Come crederanno in colui del quale non hanno sentito parlare? Come ne sentiranno parlare senza qualcuno che lo annunci?"],
[10015,"E come lo annunceranno, se non sono stati inviati? Come sta scritto:  Quanto sono belli i piedi di coloro che recano un lieto annuncio di bene!"],
[10016,"Ma non tutti hanno obbedito al Vangelo. Lo dice Isaia:  Signore, chi ha creduto dopo averci ascoltato?"],
[10017,"Dunque, la fede viene dall'ascolto e l'ascolto riguarda la parola di Cristo."],
[10018,"Ora io dico: forse non hanno udito? Tutt'altro: Per tutta la terra è corsa la loro voce, e fino agli estremi confini del mondo le loro parole ."],
[10019,"E dico ancora: forse Israele non ha compreso? Per primo Mosè dice: Io vi renderò gelosi di una nazione che nazione non è; susciterò il vostro sdegno contro una nazione senza intelligenza ."],
[10020,"Isaia poi arriva fino a dire: Sono stato trovato da quelli che non mi cercavano, mi sono manifestato a quelli che non chiedevano di me ,"],
[10021,"mentre d'Israele dice: Tutto il giorno ho steso le mani verso un popolo disobbediente e ribelle!"],
[11001,"Io domando dunque: Dio ha forse ripudiato il suo popolo? Impossibile! Anch'io infatti sono Israelita, della discendenza di Abramo, della tribù di Beniamino."],
[11002,"Dio non ha ripudiato il suo popolo , che egli ha scelto fin da principio. Non sapete ciò che dice la Scrittura, nel passo in cui Elia ricorre a Dio contro Israele?"],
[11003,"Signore,  hanno ucciso i tuoi profeti, hanno rovesciato i tuoi altari, sono rimasto solo e ora vogliono la mia vita."],
[11004,"Che cosa gli risponde però la voce divina? Mi sono riservato settemila uomini, che non hanno piegato il ginocchio davanti a Baal."],
[11005,"Così anche nel tempo presente vi è un resto, secondo una scelta fatta per grazia."],
[11006,"E se lo è per grazia, non lo è per le opere; altrimenti la grazia non sarebbe più grazia."],
[11007,"Che dire dunque? Israele non ha ottenuto quello che cercava; lo hanno ottenuto invece gli eletti. Gli altri invece sono stati resi ostinati,"],
[11008,"come sta scritto: Dio ha dato loro uno spirito di torpore, occhi per non vedere  e orecchi per non sentire, fino al giorno d'oggi ."],
[11009,"E Davide dice: Diventi la loro mensa un laccio, un tranello, un inciampo e un giusto castigo!"],
[11010,"Siano accecati i loro occhi in modo che non vedano e fa' loro curvare la schiena per sempre!"],
[11011,"Ora io dico: forse inciamparono per cadere per sempre? Certamente no. Ma a causa della loro caduta la salvezza è giunta alle genti, per suscitare la loro gelosia."],
[11012,"Se la loro caduta è stata ricchezza per il mondo e il loro fallimento ricchezza per le genti, quanto più la loro totalità!"],
[11013,"A voi, genti, ecco che cosa dico: come apostolo delle genti, io faccio onore al mio ministero,"],
[11014,"nella speranza di suscitare la gelosia di quelli del mio sangue e di salvarne alcuni."],
[11015,"Se infatti il loro essere rifiutati è stata una riconciliazione del mondo, che cosa sarà la loro riammissione se non una vita dai morti?"],
[11016,"Se le primizie sono sante, lo sarà anche l'impasto; se è santa la radice, lo saranno anche i rami."],
[11017,"Se però alcuni rami sono stati tagliati e tu, che sei un olivo selvatico, sei stato innestato fra loro, diventando così partecipe della radice e della linfa dell'olivo,"],
[11018,"non vantarti contro i rami! Se ti vanti, ricordati che non sei tu che porti la radice, ma è la radice che porta te."],
[11019,"Dirai certamente: i rami sono stati tagliati perché io vi fossi innestato!"],
[11020,"Bene; essi però sono stati tagliati per mancanza di fede, mentre tu rimani innestato grazie alla fede. Tu non insuperbirti, ma abbi timore!"],
[11021,"Se infatti Dio non ha risparmiato quelli che erano rami naturali, tanto meno risparmierà te!"],
[11022,"Considera dunque la bontà e la severità di Dio: la severità verso quelli che sono caduti; verso di te invece la bontà di Dio, a condizione però che tu sia fedele a questa bontà. Altrimenti anche tu verrai tagliato via."],
[11023,"Anch'essi, se non persevereranno nell'incredulità, saranno innestati; Dio infatti ha il potere di innestarli di nuovo!"],
[11024,"Se tu infatti, dall'olivo selvatico, che eri secondo la tua natura, sei stato tagliato via e, contro natura, sei stato innestato su un olivo buono, quanto più essi, che sono della medesima natura, potranno venire di nuovo innestati sul proprio olivo!"],
[11025,"Non voglio infatti che ignoriate, fratelli, questo mistero, perché non siate presuntuosi: l'ostinazione di una parte d'Israele è in atto fino a quando non saranno entrate tutte quante le genti."],
[11026,"Allora tutto Israele sarà salvato, come sta scritto: Da Sion uscirà il liberatore, egli toglierà l'empietà da Giacobbe."],
[11027,"Sarà questa la mia alleanza con loro quando distruggerò i loro peccati ."],
[11028,"Quanto al Vangelo, essi sono nemici, per vostro vantaggio; ma quanto alla scelta di Dio, essi sono amati, a causa dei padri,"],
[11029,"infatti i doni e la chiamata di Dio sono irrevocabili!"],
[11030,"Come voi un tempo siete stati disobbedienti a Dio e ora avete ottenuto misericordia a motivo della loro disobbedienza,"],
[11031,"così anch'essi ora sono diventati disobbedienti a motivo della misericordia da voi ricevuta, perché anch'essi ottengano misericordia."],
[11032,"Dio infatti ha rinchiuso tutti nella disobbedienza, per essere misericordioso verso tutti!"],
[11033,"O profondità della ricchezza, della sapienza e della conoscenza di Dio! Quanto insondabili sono i suoi giudizi e inaccessibili le sue vie!"],
[11034,"Infatti, chi mai ha conosciuto il pensiero del Signore? O chi mai è stato suo consigliere?"],
[11035,"O chi gli ha dato qualcosa per primo tanto da riceverne il contraccambio?"],
[11036,"Poiché da lui, per mezzo di lui e per lui sono tutte le cose. A lui la gloria nei secoli. Amen."],
[12001,"Vi esorto dunque, fratelli, per la misericordia di Dio, a offrire i vostri corpi come sacrificio vivente, santo e gradito a Dio; è questo il vostro culto spirituale."],
[12002,"Non conformatevi a questo mondo, ma lasciatevi trasformare rinnovando il vostro modo di pensare, per poter discernere la volontà di Dio, ciò che è buono, a lui gradito e perfetto."],
[12003,"Per la grazia che mi è stata data, io dico a ciascuno di voi: non valutatevi più di quanto conviene, ma valutatevi in modo saggio e giusto, ciascuno secondo la misura di fede che Dio gli ha dato."],
[12004,"Poiché, come in un solo corpo abbiamo molte membra e queste membra non hanno tutte la medesima funzione,"],
[12005,"così anche noi, pur essendo molti, siamo un solo corpo in Cristo e, ciascuno per la sua parte, siamo membra gli uni degli altri."],
[12006,"Abbiamo doni diversi secondo la grazia data a ciascuno di noi: chi ha il dono della profezia la eserciti secondo ciò che detta la fede;"],
[12007,"chi ha un ministero attenda al ministero; chi insegna si dedichi all'insegnamento;"],
[12008,"chi esorta si dedichi all'esortazione. Chi dona, lo faccia con semplicità; chi presiede, presieda con diligenza; chi fa opere di misericordia, le compia con gioia."],
[12009,"La carità non sia ipocrita: detestate il male, attaccatevi al bene;"],
[12010,"amatevi gli uni gli altri con affetto fraterno, gareggiate nello stimarvi a vicenda."],
[12011,"Non siate pigri nel fare il bene, siate invece ferventi nello spirito; servite il Signore."],
[12012,"Siate lieti nella speranza, costanti nella tribolazione, perseveranti nella preghiera."],
[12013,"Condividete le necessità dei santi; siate premurosi nell'ospitalità."],
[12014,"Benedite coloro che vi perseguitano, benedite e non maledite."],
[12015,"Rallegratevi con quelli che sono nella gioia; piangete con quelli che sono nel pianto."],
[12016,"Abbiate i medesimi sentimenti gli uni verso gli altri; non nutrite desideri di grandezza; volgetevi piuttosto a ciò che è umile. Non stimatevi sapienti da voi stessi."],
[12017,"Non rendete a nessuno male per male. Cercate di compiere il bene davanti a tutti gli uomini."],
[12018,"Se possibile, per quanto dipende da voi, vivete in pace con tutti."],
[12019,"Non fatevi giustizia da voi stessi, carissimi, ma lasciate fare all'ira divina. Sta scritto infatti:  Spetta a me fare giustizia, io darò a ciascuno il suo , dice il Signore."],
[12020,"Al contrario,  se il tuo nemico ha fame, dagli da mangiare; se ha sete, dagli da bere: facendo questo, infatti, accumulerai carboni ardenti sopra il suo capo ."],
[12021,"Non lasciarti vincere dal male, ma vinci il male con il bene."],
[13001,"Ciascuno sia sottomesso alle autorità costituite. Infatti non c'è autorità se non da Dio: quelle che esistono sono stabilite da Dio."],
[13002,"Quindi chi si oppone all'autorità, si oppone all'ordine stabilito da Dio. E quelli che si oppongono attireranno su di sé la condanna."],
[13003,"I governanti infatti non sono da temere quando si fa il bene, ma quando si fa il male. Vuoi non aver paura dell'autorità? Fa' il bene e ne avrai lode,"],
[13004,"poiché essa è al servizio di Dio per il tuo bene. Ma se fai il male, allora devi temere, perché non invano essa porta la spada; è infatti al servizio di Dio per la giusta condanna di chi fa il male."],
[13005,"Perciò è necessario stare sottomessi, non solo per timore della punizione, ma anche per ragioni di coscienza."],
[13006,"Per questo infatti voi pagate anche le tasse: quelli che svolgono questo compito sono a servizio di Dio."],
[13007,"Rendete a ciascuno ciò che gli è dovuto: a chi si devono le tasse, date le tasse; a chi l'imposta, l'imposta; a chi il timore, il timore; a chi il rispetto, il rispetto."],
[13008,"Non siate debitori di nulla a nessuno, se non dell'amore vicendevole; perché chi ama l'altro ha adempiuto la Legge."],
[13009,"Infatti:  Non commetterai adulterio, non ucciderai, non ruberai, non desidererai , e qualsiasi altro comandamento, si ricapitola in questa parola:  Amerai il tuo prossimo come te stesso ."],
[13010,"La carità non fa alcun male al prossimo: pienezza della Legge infatti è la carità."],
[13011,"E questo voi farete, consapevoli del momento: è ormai tempo di svegliarvi dal sonno, perché adesso la nostra salvezza è più vicina di quando diventammo credenti."],
[13012,"La notte è avanzata, il giorno è vicino. Perciò gettiamo via le opere delle tenebre e indossiamo le armi della luce."],
[13013,"Comportiamoci onestamente, come in pieno giorno: non in mezzo a orge e ubriachezze, non fra lussurie e impurità, non in litigi e gelosie."],
[13014,"Rivestitevi invece del Signore Gesù Cristo e non lasciatevi prendere dai desideri della carne."],
[14001,"Accogliete chi è debole nella fede, senza discuterne le opinioni."],
[14002,"Uno crede di poter mangiare di tutto; l'altro, che invece è debole, mangia solo legumi."],
[14003,"Colui che mangia, non disprezzi chi non mangia; colui che non mangia, non giudichi chi mangia: infatti Dio ha accolto anche lui."],
[14004,"Chi sei tu, che giudichi un servo che non è tuo? Stia in piedi o cada, ciò riguarda il suo padrone. Ma starà in piedi, perché il Signore ha il potere di tenerlo in piedi."],
[14005,"C'è chi distingue giorno da giorno, chi invece li giudica tutti uguali; ciascuno però sia fermo nella propria convinzione."],
[14006,"Chi si preoccupa dei giorni, lo fa per il Signore; chi mangia di tutto, mangia per il Signore, dal momento che rende grazie a Dio; chi non mangia di tutto, non mangia per il Signore e rende grazie a Dio."],
[14007,"Nessuno di noi, infatti, vive per se stesso e nessuno muore per se stesso,"],
[14008,"perché se noi viviamo, viviamo per il Signore, se noi moriamo, moriamo per il Signore. Sia che viviamo, sia che moriamo, siamo del Signore."],
[14009,"Per questo infatti Cristo è morto ed è ritornato alla vita: per essere il Signore dei morti e dei vivi."],
[14010,"Ma tu, perché giudichi il tuo fratello? E tu, perché disprezzi il tuo fratello? Tutti infatti ci presenteremo al tribunale di Dio,"],
[14011,"perché sta scritto: Io vivo, dice il Signore : ogni ginocchio si piegherà davanti a me e ogni lingua renderà gloria a Dio ."],
[14012,"Quindi ciascuno di noi renderà conto di se stesso a Dio."],
[14013,"D'ora in poi non giudichiamoci più gli uni gli altri; piuttosto fate in modo di non essere causa di inciampo o di scandalo per il fratello."],
[14014,"Io so, e ne sono persuaso nel Signore Gesù, che nulla è impuro in se stesso; ma se uno ritiene qualcosa come impuro, per lui è impuro."],
[14015,"Ora se per un cibo il tuo fratello resta turbato, tu non ti comporti più secondo carità. Non mandare in rovina con il tuo cibo colui per il quale Cristo è morto!"],
[14016,"Non divenga motivo di rimprovero il bene di cui godete!"],
[14017,"Il regno di Dio infatti non è cibo o bevanda, ma giustizia, pace e gioia nello Spirito Santo:"],
[14018,"chi si fa servitore di Cristo in queste cose è bene accetto a Dio e stimato dagli uomini."],
[14019,"Cerchiamo dunque ciò che porta alla pace e alla edificazione vicendevole."],
[14020,"Non distruggere l'opera di Dio per una questione di cibo! Tutte le cose sono pure; ma è male per un uomo mangiare dando scandalo."],
[14021,"Perciò è bene non mangiare carne né bere vino né altra cosa per la quale il tuo fratello possa scandalizzarsi."],
[14022,"La convinzione che tu hai, conservala per te stesso davanti a Dio. Beato chi non condanna se stesso a causa di ciò che approva."],
[14023,"Ma chi è nel dubbio, mangiando si condanna, perché non agisce secondo coscienza; tutto ciò, infatti, che non viene dalla coscienza è peccato."],
[15001,"Noi, che siamo i forti, abbiamo il dovere di portare le infermità dei deboli, senza compiacere noi stessi."],
[15002,"Ciascuno di noi cerchi di piacere al prossimo nel bene, per edificarlo."],
[15003,"Anche Cristo infatti non cercò di piacere a se stesso, ma, come sta scritto:  Gli insulti di chi ti insulta ricadano su di me ."],
[15004,"Tutto ciò che è stato scritto prima di noi, è stato scritto per nostra istruzione, perché, in virtù della perseveranza e della consolazione che provengono dalle Scritture, teniamo viva la speranza."],
[15005,"E il Dio della perseveranza e della consolazione vi conceda di avere gli uni verso gli altri gli stessi sentimenti, sull'esempio di Cristo Gesù,"],
[15006,"perché con un solo animo e una voce sola rendiate gloria a Dio, Padre del Signore nostro Gesù Cristo."],
[15007,"Accoglietevi perciò gli uni gli altri come anche Cristo accolse voi, per la gloria di Dio."],
[15008,"Dico infatti che Cristo è diventato servitore dei circoncisi per mostrare la fedeltà di Dio nel compiere le promesse dei padri;"],
[15009,"le genti invece glorificano Dio per la sua misericordia, come sta scritto: Per questo ti loderò fra le genti e canterò inni al tuo nome ."],
[15010,"E ancora: Esultate, o nazioni, insieme al suo popolo ."],
[15011,"E di nuovo: Genti tutte, lodate il Signore; i popoli tutti lo esaltino ."],
[15012,"E a sua volta Isaia dice: Spunterà il rampollo di Iesse, colui che sorgerà a governare le nazioni : in lui le nazioni spereranno ."],
[15013,"Il Dio della speranza vi riempia, nel credere, di ogni gioia e pace, perché abbondiate nella speranza per la virtù dello Spirito Santo."],
[15014,"Fratelli miei, sono anch'io convinto, per quel che vi riguarda, che voi pure siete pieni di bontà, colmi di ogni conoscenza e capaci di correggervi l'un l'altro."],
[15015,"Tuttavia, su alcuni punti, vi ho scritto con un po' di audacia, come per ricordarvi quello che già sapete, a motivo della grazia che mi è stata data da Dio"],
[15016,"per essere ministro di Cristo Gesù tra le genti, adempiendo il sacro ministero di annunciare il vangelo di Dio perché le genti divengano un'offerta gradita, santificata dallo Spirito Santo."],
[15017,"Questo dunque è il mio vanto in Gesù Cristo nelle cose che riguardano Dio."],
[15018,"Non oserei infatti dire nulla se non di quello che Cristo ha operato per mezzo mio per condurre le genti all'obbedienza, con parole e opere,"],
[15019,"con la potenza di segni e di prodigi, con la forza dello Spirito. Così da Gerusalemme e in tutte le direzioni fino all'Illiria, ho portato a termine la predicazione del vangelo di Cristo."],
[15020,"Ma mi sono fatto un punto di onore di non annunciare il Vangelo dove era già conosciuto il nome di Cristo, per non costruire su un fondamento altrui,"],
[15021,"ma, come sta scritto: Coloro ai quali non era stato annunciato, lo vedranno, e coloro che non ne avevano udito parlare, comprenderanno ."],
[15022,"Appunto per questo fui impedito più volte di venire da voi."],
[15023,"Ora però, non trovando più un campo d'azione in queste regioni e avendo già da parecchi anni un vivo desiderio di venire da voi,"],
[15024,"spero di vedervi, di passaggio, quando andrò in Spagna, e di essere da voi aiutato a recarmi in quella regione, dopo avere goduto un poco della vostra presenza."],
[15025,"Per il momento vado a Gerusalemme, a rendere un servizio ai santi di quella comunità;"],
[15026,"la Macedonia e l'Acaia infatti hanno voluto realizzare una forma di comunione con i poveri tra i santi che sono a Gerusalemme."],
[15027,"L'hanno voluto perché sono ad essi debitori: infatti le genti, avendo partecipato ai loro beni spirituali, sono in debito di rendere loro un servizio sacro anche nelle loro necessità materiali."],
[15028,"Quando avrò fatto questo e avrò consegnato sotto garanzia quello che è stato raccolto, partirò per la Spagna passando da voi."],
[15029,"So che, giungendo presso di voi, ci verrò con la pienezza della benedizione di Cristo."],
[15030,"Perciò, fratelli, per il Signore nostro Gesù Cristo e l'amore dello Spirito, vi raccomando: lottate con me nelle preghiere che rivolgete a Dio,"],
[15031,"perché io sia liberato dagli infedeli della Giudea e il mio servizio a Gerusalemme sia bene accetto ai santi."],
[15032,"Così, se Dio lo vuole, verrò da voi pieno di gioia per riposarmi in mezzo a voi."],
[15033,"Il Dio della pace sia con tutti voi. Amen."],
[16001,"Vi raccomando Febe, nostra sorella, che è al servizio della Chiesa di Cencre:"],
[16002,"accoglietela nel Signore, come si addice ai santi, e assistetela in qualunque cosa possa avere bisogno di voi; anch'essa infatti ha protetto molti, e anche me stesso."],
[16003,"Salutate Prisca e Aquila, miei collaboratori in Cristo Gesù."],
[16004,"Essi per salvarmi la vita hanno rischiato la loro testa, e a loro non io soltanto sono grato, ma tutte le Chiese del mondo pagano."],
[16005,"Salutate anche la comunità che si riunisce nella loro casa. Salutate il mio amatissimo Epeneto, che è stato il primo a credere in Cristo nella provincia dell'Asia."],
[16006,"Salutate Maria, che ha faticato molto per voi."],
[16007,"Salutate Andronico e Giunia, miei parenti e compagni di prigionia: sono insigni tra gli apostoli ed erano in Cristo già prima di me."],
[16008,"Salutate Ampliato, che mi è molto caro nel Signore."],
[16009,"Salutate Urbano, nostro collaboratore in Cristo, e il mio carissimo Stachi."],
[16010,"Salutate Apelle, che ha dato buona prova in Cristo. Salutate quelli della casa di Aristobulo."],
[16011,"Salutate Erodione, mio parente. Salutate quelli della casa di Narciso che credono nel Signore."],
[16012,"Salutate Trifena e Trifosa, che hanno faticato per il Signore. Salutate la carissima Perside, che ha tanto faticato per il Signore."],
[16013,"Salutate Rufo, prescelto nel Signore, e sua madre, che è una madre anche per me."],
[16014,"Salutate Asincrito, Flegonte, Erme, Patroba, Erma e i fratelli che sono con loro."],
[16015,"Salutate Filologo e Giulia, Nereo e sua sorella e Olimpas e tutti i santi che sono con loro."],
[16016,"Salutatevi gli uni gli altri con il bacio santo. Vi salutano tutte le Chiese di Cristo."],
[16017,"Vi raccomando poi, fratelli, di guardarvi da coloro che provocano divisioni e ostacoli contro l'insegnamento che avete appreso: tenetevi lontani da loro."],
[16018,"Costoro, infatti, non servono Cristo nostro Signore, ma il proprio ventre e, con belle parole e discorsi affascinanti, ingannano il cuore dei semplici."],
[16019,"La fama della vostra obbedienza è giunta a tutti: mentre dunque mi rallegro di voi, voglio che siate saggi nel bene e immuni dal male."],
[16020,"Il Dio della pace schiaccerà ben presto Satana sotto i vostri piedi. La grazia del Signore nostro Gesù sia con voi."],
[16021,"Vi saluta Timoteo mio collaboratore, e con lui Lucio, Giasone, Sosípatro, miei parenti."],
[16022,"Anch'io, Terzo, che ho scritto la lettera, vi saluto nel Signore."],
[16023,"Vi saluta Gaio, che ospita me e tutta la comunità. Vi salutano Erasto, tesoriere della città, e il fratello Quarto. ["],
[16024,"]"],
[16025,"A colui che ha il potere di confermarvi nel mio Vangelo, che annuncia Gesù Cristo, secondo la rivelazione del mistero,  avvolto nel silenzio per secoli eterni,"],
[16026,"ma ora manifestato mediante le scritture dei Profeti, per ordine dell'eterno Dio, annunciato a tutte le genti perché giungano all'obbedienza della fede,"],
[16027,"a Dio, che solo è sapiente, per mezzo di Gesù Cristo, la gloria nei secoli. Amen."]
])
