Bib.ret([
[1001,"Al tempo dei giudici, ci fu nel paese una carestia e un uomo con la moglie e i suoi due figli emigrò da Betlemme di Giuda nei campi di Moab."],
[1002,"Quest'uomo si chiamava Elimelec, sua moglie Noemi e i suoi due figli Maclon e Chilion; erano Efratei, di Betlemme di Giuda. Giunti nei campi di Moab, vi si stabilirono."],
[1003,"Poi Elimelec, marito di Noemi, morì ed essa rimase con i suoi due figli."],
[1004,"Questi sposarono donne moabite: una si chiamava Orpa e l'altra Rut. Abitarono in quel luogo per dieci anni."],
[1005,"Poi morirono anche Maclon e Chilion, e la donna rimase senza i suoi due figli e senza il marito."],
[1006,"Allora intraprese il cammino di ritorno dai campi di Moab con le sue nuore, perché nei campi di Moab aveva sentito dire che il Signore aveva visitato il suo popolo, dandogli pane."],
[1007,"Partì dunque con le due nuore da quel luogo ove risiedeva e si misero in cammino per tornare nel paese di Giuda."],
[1008,"Noemi disse alle due nuore: \"Andate, tornate ciascuna a casa di vostra madre; il Signore usi bontà con voi, come voi avete fatto con quelli che sono morti e con me!"],
[1009,"Il Signore conceda a ciascuna di voi di trovare tranquillità in casa di un marito\". E le baciò. Ma quelle scoppiarono a piangere"],
[1010,"e le dissero: \"No, torneremo con te al tuo popolo\"."],
[1011,"Noemi insistette: \"Tornate indietro, figlie mie! Perché dovreste venire con me? Ho forse ancora in grembo figli che potrebbero diventare vostri mariti?"],
[1012,"Tornate indietro, figlie mie, andate! Io sono troppo vecchia per risposarmi. Se anche pensassi di avere una speranza, prendessi marito questa notte e generassi pure dei figli,"],
[1013,"vorreste voi aspettare che crescano e rinuncereste per questo a maritarvi? No, figlie mie; io sono molto più amareggiata di voi, poiché la mano del Signore è rivolta contro di me\"."],
[1014,"Di nuovo esse scoppiarono a piangere. Orpa si accomiatò con un bacio da sua suocera, Rut invece non si staccò da lei."],
[1015,"Noemi le disse: \"Ecco, tua cognata è tornata dalla sua gente e dal suo dio; torna indietro anche tu, come tua cognata\"."],
[1016,"Ma Rut replicò: \"Non insistere con me che ti abbandoni e torni indietro senza di te, perché dove andrai tu, andrò anch'io, e dove ti fermerai, mi fermerò; il tuo popolo sarà il mio popolo e il tuo Dio sarà il mio Dio."],
[1017,"Dove morirai tu, morirò anch'io e lì sarò sepolta. Il Signore mi faccia questo male e altro ancora, se altra cosa, che non sia la morte, mi separerà da te\"."],
[1018,"Vedendo che era davvero decisa ad andare con lei, Noemi non insistette più."],
[1019,"Esse continuarono il viaggio, finché giunsero a Betlemme. Quando giunsero a Betlemme, tutta la città fu in subbuglio per loro, e le donne dicevano: \"Ma questa è Noemi!\"."],
[1020,"Ella replicava: \"Non chiamatemi Noemi, chiamatemi Mara, perché l'Onnipotente mi ha tanto amareggiata!"],
[1021,"Piena me n'ero andata, ma il Signore mi fa tornare vuota. Perché allora chiamarmi Noemi, se il Signore si è dichiarato contro di me e l'Onnipotente mi ha resa infelice?\"."],
[1022,"Così dunque tornò Noemi con Rut, la moabita, sua nuora, venuta dai campi di Moab. Esse arrivarono a Betlemme quando si cominciava a mietere l'orzo."],
[2001,"Noemi aveva un parente da parte del marito, un uomo altolocato della famiglia di Elimelec, che si chiamava Booz."],
[2002,"Rut, la moabita, disse a Noemi: \"Lasciami andare in campagna a spigolare dietro qualcuno nelle cui grazie riuscirò a entrare\". Le rispose: \"Va' pure, figlia mia\"."],
[2003,"Rut andò e si mise a spigolare nella campagna dietro ai mietitori. Per caso si trovò nella parte di campagna appartenente a Booz, che era della famiglia di Elimelec."],
[2004,"Proprio in quel mentre Booz arrivava da Betlemme. Egli disse ai mietitori: \"Il Signore sia con voi!\". Ed essi gli risposero: \"Ti benedica il Signore!\"."],
[2005,"Booz disse al sovrintendente dei mietitori: \"Di chi è questa giovane?\"."],
[2006,"Il sovrintendente dei mietitori rispose: \"È una giovane moabita, quella tornata con Noemi dai campi di Moab."],
[2007,"Ha detto di voler spigolare e raccogliere tra i covoni dietro ai mietitori. È venuta ed è rimasta in piedi da stamattina fino ad ora. Solo adesso si è un poco seduta in casa\"."],
[2008,"Allora Booz disse a Rut: \"Ascolta, figlia mia, non andare a spigolare in un altro campo. Non allontanarti di qui e sta' insieme alle mie serve."],
[2009,"Tieni d'occhio il campo dove mietono e cammina dietro a loro. Ho lasciato detto ai servi di non molestarti. Quando avrai sete, va' a bere dagli orci ciò che i servi hanno attinto\"."],
[2010,"Allora Rut si prostrò con la faccia a terra e gli disse: \"Io sono una straniera: perché sono entrata nelle tue grazie e tu ti interessi di me?\"."],
[2011,"Booz le rispose: \"Mi è stato riferito quanto hai fatto per tua suocera dopo la morte di tuo marito, e come hai abbandonato tuo padre, tua madre e la tua patria per venire presso gente che prima non conoscevi."],
[2012,"Il Signore ti ripaghi questa tua buona azione e sia davvero piena per te la ricompensa da parte del Signore, Dio d'Israele, sotto le cui ali sei venuta a rifugiarti\"."],
[2013,"Ella soggiunse: \"Possa rimanere nelle tue grazie, mio signore! Poiché tu mi hai consolato e hai parlato al cuore della tua serva, benché io non sia neppure come una delle tue schiave\"."],
[2014,"Poi, al momento del pasto, Booz le disse: \"Avvicinati, mangia un po' di pane e intingi il boccone nell'aceto\". Ella si mise a sedere accanto ai mietitori. Booz le offrì del grano abbrustolito; lei ne mangiò a sazietà e ne avanzò."],
[2015,"Poi si alzò per tornare a spigolare e Booz diede quest'ordine ai suoi servi: \"Lasciatela spigolare anche fra i covoni e non fatele del male."],
[2016,"Anzi fate cadere apposta per lei spighe dai mannelli; lasciatele lì, perché le raccolga, e non sgridatela\"."],
[2017,"Così Rut spigolò in quel campo fino alla sera. Batté quello che aveva raccolto e ne venne fuori quasi un'efa di orzo."],
[2018,"Se lo caricò addosso e rientrò in città. Sua suocera vide ciò che aveva spigolato. Rut tirò fuori quanto le era rimasto del pasto e glielo diede."],
[2019,"La suocera le chiese: \"Dove hai spigolato oggi? Dove hai lavorato? Benedetto colui che si è interessato di te!\". Rut raccontò alla suocera con chi aveva lavorato e disse: \"L'uomo con cui ho lavorato oggi si chiama Booz\"."],
[2020,"Noemi disse alla nuora: \"Sia benedetto dal Signore, che non ha rinunciato alla sua bontà verso i vivi e verso i morti!\". E aggiunse: \"Quest'uomo è un nostro parente stretto, uno di quelli che hanno su di noi il diritto di riscatto\"."],
[2021,"Rut, la moabita, disse: \"Mi ha anche detto di rimanere insieme ai suoi servi, finché abbiano finito tutta la mietitura\"."],
[2022,"Noemi disse a Rut, sua nuora: \"Figlia mia, è bene che tu vada con le sue serve e non ti molestino in un altro campo\"."],
[2023,"Ella rimase dunque con le serve di Booz a spigolare, sino alla fine della mietitura dell'orzo e del frumento, e abitava con la suocera."],
[3001,"Un giorno Noemi, sua suocera, le disse: \"Figlia mia, non devo forse cercarti una sistemazione, perché tu sia felice?"],
[3002,"Ora, tu sei stata con le serve di Booz: egli è nostro parente e proprio questa sera deve ventilare l'orzo sull'aia."],
[3003,"Lavati, profumati, mettiti il mantello e scendi all'aia. Ma non ti far riconoscere da lui prima che egli abbia finito di mangiare e di bere."],
[3004,"Quando si sarà coricato - e tu dovrai sapere dove si è coricato - va', scoprigli i piedi e sdraiati lì. Ti dirà lui ciò che dovrai fare\"."],
[3005,"Rut le rispose: \"Farò quanto mi dici\"."],
[3006,"Scese all'aia e fece quanto la suocera le aveva ordinato."],
[3007,"Booz mangiò, bevve e con il cuore allegro andò a dormire accanto al mucchio d'orzo. Allora essa venne pian piano, gli scoprì i piedi e si sdraiò."],
[3008,"Verso mezzanotte quell'uomo ebbe un brivido di freddo, si girò e vide una donna sdraiata ai suoi piedi."],
[3009,"Domandò: \"Chi sei?\". Rispose: \"Sono Rut, tua serva. Stendi il lembo del tuo mantello sulla tua serva, perché tu hai il diritto di riscatto\"."],
[3010,"Egli disse: \"Sii benedetta dal Signore, figlia mia! Questo tuo secondo atto di bontà è ancora migliore del primo, perché non sei andata in cerca di uomini giovani, poveri o ricchi che fossero."],
[3011,"Ora, figlia mia, non temere! Farò per te tutto quanto chiedi, perché tutti i miei concittadini sanno che sei una donna di valore."],
[3012,"È vero: io ho il diritto di riscatto, ma c'è un altro che è parente più stretto di me."],
[3013,"Passa qui la notte e domani mattina, se lui vorrà assolvere il diritto di riscatto, va bene, lo faccia; ma se non vorrà riscattarti, io ti riscatterò, per la vita del Signore! Rimani coricata fino a domattina\"."],
[3014,"Ella rimase coricata ai suoi piedi fino alla mattina e si alzò prima che una persona riesca a riconoscere un'altra. Booz infatti pensava: \"Nessuno deve sapere che questa donna è venuta nell'aia!\"."],
[3015,"Le disse: \"Apri il mantello che hai addosso e tienilo forte\". Lei lo tenne ed egli vi versò dentro sei misure d'orzo. Glielo pose sulle spalle e Rut rientrò in città."],
[3016,"Arrivata dalla suocera, questa le chiese: \"Com'è andata, figlia mia?\". Ella le raccontò quanto quell'uomo aveva fatto per lei"],
[3017,"e aggiunse: \"Mi ha anche dato sei misure di orzo, dicendomi: \"Non devi tornare da tua suocera a mani vuote\"\"."],
[3018,"Noemi disse: \"Sta' tranquilla, figlia mia, finché non sai come andrà a finire la cosa. Di certo quest'uomo non si darà pace, finché non avrà concluso oggi stesso questa faccenda\"."],
[4001,"Booz dunque salì alla porta della città e lì si sedette. Ed ecco passare colui che aveva il diritto di riscatto e del quale Booz aveva parlato. Booz lo chiamò: \"Vieni a sederti qui, amico mio!\". Quello si avvicinò e si sedette."],
[4002,"Poi Booz prese dieci degli anziani della città e disse loro: \"Sedete qui\". Quelli si sedettero."],
[4003,"Allora Booz disse a colui che aveva il diritto di riscatto: \"Il campo che apparteneva al nostro fratello Elimelec, lo mette in vendita Noemi, tornata dai campi di Moab."],
[4004,"Ho pensato bene di informartene e dirti: \"Compralo davanti alle persone qui presenti e davanti agli anziani del mio popolo\". Se vuoi riscattarlo, riscattalo pure; ma se non lo riscatti, fammelo sapere. Infatti, oltre a te, nessun altro ha il diritto di riscatto, e io vengo dopo di te\". Quegli rispose: \"Lo riscatto io\"."],
[4005,"E Booz proseguì: \"Quando acquisterai il campo da Noemi, tu dovrai acquistare anche Rut, la moabita, moglie del defunto, per mantenere il nome del defunto sulla sua eredità\"."],
[4006,"Allora colui che aveva il diritto di riscatto rispose: \"Non posso esercitare il diritto di riscatto, altrimenti danneggerei la mia stessa eredità. Subentra tu nel mio diritto. Io non posso davvero esercitare questo diritto di riscatto\"."],
[4007,"Anticamente in Israele vigeva quest'usanza in relazione al diritto di riscatto o alla permuta: per convalidare un atto, uno si toglieva il sandalo e lo dava all'altro. Questa era la forma di autenticazione in Israele."],
[4008,"Allora colui che aveva il diritto di riscatto rispose a Booz: \"Acquistatelo tu\". E si tolse il sandalo."],
[4009,"Allora Booz disse agli anziani e a tutta la gente: \"Voi siete oggi testimoni che io ho acquistato tutto quanto apparteneva a Elimelec, a Chilion e a Maclon dalle mani di Noemi,"],
[4010,"e che ho preso anche in moglie Rut, la moabita, già moglie di Maclon, per mantenere il nome del defunto sulla sua eredità, e perché il nome del defunto non scompaia tra i suoi fratelli e alla porta della sua città. Voi ne siete oggi testimoni\"."],
[4011,"Tutta la gente che si trovava presso la porta rispose: \"Ne siamo testimoni\". Gli anziani aggiunsero:     \"Il Signore renda la donna, che entra in casa tua, come Rachele e Lia, le due donne che edificarono la casa d'Israele. Procurati ricchezza in Èfrata, fatti un nome in Betlemme!"],
[4012,"La tua casa sia come la casa di Peres, che Tamar partorì a Giuda, grazie alla posterità che il Signore ti darà da questa giovane!\"."],
[4013,"Così Booz prese in moglie Rut. Egli si unì a lei e il Signore le accordò di concepire: ella partorì un figlio."],
[4014,"E le donne dicevano a Noemi: \"Benedetto il Signore, il quale oggi non ti ha fatto mancare uno che esercitasse il diritto di riscatto. Il suo nome sarà ricordato in Israele!"],
[4015,"Egli sarà il tuo consolatore e il sostegno della tua vecchiaia, perché lo ha partorito tua nuora, che ti ama e che vale per te più di sette figli\"."],
[4016,"Noemi prese il bambino, se lo pose in grembo e gli fece da nutrice."],
[4017,"Le vicine gli cercavano un nome e dicevano: \"È nato un figlio a Noemi!\". E lo chiamarono Obed. Egli fu il padre di Iesse, padre di Davide."],
[4018,"Questa è la discendenza di Peres: Peres generò Chesron,"],
[4019,"Chesron generò Ram, Ram generò Amminadab,"],
[4020,"Amminadab generò Nacson, Nacson generò Salmon,"],
[4021,"Salmon generò Booz, Booz generò Obed,"],
[4022,"Obed generò Iesse e Iesse generò Davide."]
])
