Bib.ret([
[1001,"Amate la giustizia, voi giudici della terra, pensate al Signore con bontà d'animo e cercatelo con cuore semplice."],
[1002,"Egli infatti si fa trovare da quelli che non lo mettono alla prova, e si manifesta a quelli che non diffidano di lui."],
[1003,"I ragionamenti distorti separano da Dio; ma la potenza, messa alla prova, spiazza gli stolti."],
[1004,"La sapienza non entra in un'anima che compie il male né abita in un corpo oppresso dal peccato."],
[1005,"Il santo spirito, che ammaestra, fugge ogni inganno, si tiene lontano dai discorsi insensati e viene scacciato al sopraggiungere dell'ingiustizia."],
[1006,"La sapienza è uno spirito che ama l'uomo, e tuttavia non lascia impunito il bestemmiatore per i suoi discorsi, perché Dio è testimone dei suoi sentimenti, conosce bene i suoi pensieri e ascolta ogni sua parola."],
[1007,"Lo spirito del Signore riempie la terra e, tenendo insieme ogni cosa, ne conosce la voce."],
[1008,"Per questo non può nascondersi chi pronuncia cose ingiuste, né lo risparmierà la giustizia vendicatrice."],
[1009,"Si indagherà infatti sui propositi dell'empio, il suono delle sue parole giungerà fino al Signore a condanna delle sue iniquità,"],
[1010,"perché un orecchio geloso ascolta ogni cosa, perfino il sussurro delle mormorazioni non gli resta segreto."],
[1011,"Guardatevi dunque da inutili mormorazioni, preservate la lingua dalla maldicenza, perché neppure una parola segreta sarà senza effetto; una bocca menzognera uccide l'anima."],
[1012,"Non affannatevi a cercare la morte con gli errori della vostra vita, non attiratevi la rovina con le opere delle vostre mani,"],
[1013,"perché Dio non ha creato la morte e non gode per la rovina dei viventi."],
[1014,"Egli infatti ha creato tutte le cose perché esistano; le creature del mondo sono portatrici di salvezza, in esse non c'è veleno di morte, né il regno dei morti è sulla terra."],
[1015,"La giustizia infatti è immortale."],
[1016,"Ma gli empi invocano su di sé la morte con le opere e con le parole; ritenendola amica, si struggono per lei e con essa stringono un patto, perché sono degni di appartenerle."],
[2001,"Dicono fra loro sragionando: \"La nostra vita è breve e triste; non c'è rimedio quando l'uomo muore, e non si conosce nessuno che liberi dal regno dei morti."],
[2002,"Siamo nati per caso e dopo saremo come se non fossimo stati: è un fumo il soffio delle nostre narici, il pensiero è una scintilla nel palpito del nostro cuore,"],
[2003,"spenta la quale, il corpo diventerà cenere e lo spirito svanirà come aria sottile."],
[2004,"Il nostro nome cadrà, con il tempo, nell'oblio e nessuno ricorderà le nostre opere. La nostra vita passerà come traccia di nuvola, si dissolverà come nebbia messa in fuga dai raggi del sole e abbattuta dal suo calore."],
[2005,"Passaggio di un'ombra è infatti la nostra esistenza e non c'è ritorno quando viene la nostra fine, poiché il sigillo è posto e nessuno torna indietro."],
[2006,"Venite dunque e godiamo dei beni presenti, gustiamo delle creature come nel tempo della giovinezza!"],
[2007,"Saziamoci di vino pregiato e di profumi, non ci sfugga alcun fiore di primavera,"],
[2008,"coroniamoci di boccioli di rosa prima che avvizziscano;"],
[2009,"nessuno di noi sia escluso dalle nostre dissolutezze. Lasciamo dappertutto i segni del nostro piacere,  perché questo ci spetta, questa è la nostra parte."],
[2010,"Spadroneggiamo sul giusto, che è povero, non risparmiamo le vedove, né abbiamo rispetto per la canizie di un vecchio attempato."],
[2011,"La nostra forza sia legge della giustizia, perché la debolezza risulta inutile."],
[2012,"Tendiamo insidie al giusto, che per noi è d'incomodo e si oppone alle nostre azioni; ci rimprovera le colpe contro la legge e ci rinfaccia le trasgressioni contro l'educazione ricevuta."],
[2013,"Proclama di possedere la conoscenza di Dio e chiama se stesso figlio del Signore."],
[2014,"È diventato per noi una condanna dei nostri pensieri; ci è insopportabile solo al vederlo,"],
[2015,"perché la sua vita non è come quella degli altri, e del tutto diverse sono le sue strade."],
[2016,"Siamo stati considerati da lui moneta falsa, e si tiene lontano dalle nostre vie come da cose impure. Proclama beata la sorte finale dei giusti e si vanta di avere Dio per padre."],
[2017,"Vediamo se le sue parole sono vere, consideriamo ciò che gli accadrà alla fine."],
[2018,"Se infatti il giusto è figlio di Dio, egli verrà in suo aiuto e lo libererà dalle mani dei suoi avversari."],
[2019,"Mettiamolo alla prova con violenze e tormenti, per conoscere la sua mitezza e saggiare il suo spirito di sopportazione."],
[2020,"Condanniamolo a una morte infamante, perché, secondo le sue parole, il soccorso gli verrà\"."],
[2021,"Hanno pensato così, ma si sono sbagliati; la loro malizia li ha accecati."],
[2022,"Non conoscono i misteriosi segreti di Dio, non sperano ricompensa per la rettitudine né credono a un premio per una vita irreprensibile."],
[2023,"Sì, Dio ha creato l'uomo per l'incorruttibilità, lo ha fatto immagine della propria natura."],
[2024,"Ma per l'invidia del diavolo la morte è entrata nel mondo e ne fanno esperienza coloro che le appartengono."],
[3001,"Le anime dei giusti, invece, sono nelle mani di Dio, nessun tormento li toccherà."],
[3002,"Agli occhi degli stolti parve che morissero, la loro fine fu ritenuta una sciagura,"],
[3003,"la loro partenza da noi una rovina, ma essi sono nella pace."],
[3004,"Anche se agli occhi degli uomini subiscono castighi, la loro speranza resta piena d'immortalità."],
[3005,"In cambio di una breve pena riceveranno grandi benefici, perché Dio li ha provati e li ha trovati degni di sé;"],
[3006,"li ha saggiati come oro nel crogiuolo e li ha graditi come l'offerta di un olocausto."],
[3007,"Nel giorno del loro giudizio risplenderanno, come scintille nella stoppia correranno qua e là."],
[3008,"Governeranno le nazioni, avranno potere sui popoli e il Signore regnerà per sempre su di loro."],
[3009,"Coloro che confidano in lui comprenderanno la verità, i fedeli nell'amore rimarranno presso di lui, perché grazia e misericordia sono per i suoi eletti."],
[3010,"Ma gli empi riceveranno una pena conforme ai loro pensieri; non hanno avuto cura del giusto e si sono allontanati dal Signore."],
[3011,"Infatti è infelice chi disprezza la sapienza e l'educazione. Vana è la loro speranza e le loro fatiche inutili, le loro opere sono senza frutto."],
[3012,"Le loro mogli sono insensate, cattivi i loro figli, maledetta la loro progenie."],
[3013,"Felice invece è la sterile incorrotta, che non ha conosciuto unione peccaminosa: avrà il frutto quando le anime saranno visitate."],
[3014,"E felice l'eunuco la cui mano non ha fatto nulla d'ingiusto e non ha pensato male del Signore: riceverà una ricompensa privilegiata per la sua fedeltà, una sorte più ambita nel tempio del Signore."],
[3015,"Poiché glorioso è il frutto delle opere buone e la radice della saggezza non conosce imperfezioni."],
[3016,"I figli degli adulteri non giungeranno a maturità, il seme di un'unione illegittima scomparirà."],
[3017,"Anche se avranno lunga vita, non saranno tenuti in alcun conto, e, infine, la loro vecchiaia sarà senza onore."],
[3018,"Se poi moriranno presto, non avranno speranza né conforto nel giorno del giudizio,"],
[3019,"poiché dura è la fine di una generazione ingiusta."],
[4001,"Meglio essere senza figli e possedere la virtù, perché nel ricordo di questa c'è immortalità: essa è riconosciuta da Dio e dagli uomini."],
[4002,"Presente, è imitata,  assente, viene rimpianta; incoronata, trionfa in eterno, avendo vinto, in gara, premi incontaminati."],
[4003,"La numerosa discendenza degli empi non servirà a nulla e dai suoi polloni spuri non metterà profonde radici né si consoliderà su una base sicura;"],
[4004,"anche se, a suo tempo, essa ramifica, non essendo ben piantata, sarà scossa dal vento e sradicata dalla violenza delle bufere."],
[4005,"Saranno spezzati i ramoscelli ancora deboli; il loro frutto sarà inutile, acerbo da mangiare, e non servirà a nulla."],
[4006,"Infatti i figli nati da sonni illegittimi saranno testimoni della malvagità dei genitori, quando su di essi si aprirà l'inchiesta."],
[4007,"Il giusto, anche se muore prematuramente, si troverà in un luogo di riposo."],
[4008,"Vecchiaia veneranda non è quella longeva, né si misura con il numero degli anni;"],
[4009,"ma canizie per gli uomini è la saggezza, età senile è una vita senza macchia."],
[4010,"Divenuto caro a Dio, fu amato da lui e, poiché viveva fra peccatori, fu portato altrove."],
[4011,"Fu rapito, perché la malvagità non alterasse la sua intelligenza o l'inganno non seducesse la sua anima,"],
[4012,"poiché il fascino delle cose frivole oscura tutto ciò che è bello e il turbine della passione perverte un animo senza malizia."],
[4013,"Giunto in breve alla perfezione, ha conseguito la pienezza di tutta una vita."],
[4014,"La sua anima era gradita al Signore, perciò si affrettò a uscire dalla malvagità. La gente vide ma non capì, non ha riflettuto su un fatto così importante:"],
[4015,"grazia e misericordia sono per i suoi eletti e protezione per i suoi santi."],
[4016,"Il giusto, da morto, condannerà gli empi ancora in vita; una giovinezza, giunta in breve alla conclusione, condannerà gli empi, pur carichi di anni."],
[4017,"Infatti vedranno la fine del saggio, ma non capiranno ciò che Dio aveva deciso a suo riguardo né per quale scopo il Signore l'aveva posto al sicuro."],
[4018,"Vedranno e disprezzeranno, ma il Signore li deriderà."],
[4019,"Infine diventeranno come un cadavere disonorato, oggetto di scherno fra i morti, per sempre. Dio infatti li precipiterà muti, a capofitto, e li scuoterà dalle fondamenta; saranno del tutto rovinati,  si troveranno tra dolori e il loro ricordo perirà."],
[4020,"Si presenteranno tremanti al rendiconto dei loro peccati; le loro iniquità si ergeranno contro di loro per accusarli."],
[5001,"Allora il giusto starà con grande fiducia di fronte a coloro che lo hanno perseguitato e a quelli che hanno disprezzato le sue sofferenze."],
[5002,"Alla sua vista saranno presi da terribile spavento, stupiti per la sua sorprendente salvezza."],
[5003,"Pentiti, diranno tra loro, gemendo con animo angosciato:"],
[5004,"\"Questi è colui che noi una volta abbiamo deriso e, stolti, abbiamo preso a bersaglio del nostro scherno; abbiamo considerato una pazzia la sua vita e la sua morte disonorevole."],
[5005,"Come mai è stato annoverato tra i figli di Dio e la sua eredità è ora tra i santi?"],
[5006,"Abbiamo dunque abbandonato la via della verità, la luce della giustizia non ci ha illuminati e il sole non è sorto per noi."],
[5007,"Ci siamo inoltrati per sentieri iniqui e rovinosi, abbiamo percorso deserti senza strade, ma non abbiamo conosciuto la via del Signore."],
[5008,"Quale profitto ci ha dato la superbia? Quale vantaggio ci ha portato la ricchezza con la spavalderia?"],
[5009,"Tutto questo è passato come ombra e come notizia fugace,"],
[5010,"come una nave che solca un mare agitato, e, una volta passata, di essa non si trova più traccia né scia della sua carena sulle onde;"],
[5011,"oppure come quando un uccello attraversa l'aria e non si trova alcun segno del suo volo: l'aria leggera, percossa dal battito delle ali e divisa dalla forza dello slancio, è attraversata dalle ali in movimento, ma dopo non si trova segno del suo passaggio;"],
[5012,"o come quando, scoccata una freccia verso il bersaglio, l'aria si divide e ritorna subito su se stessa e della freccia non si riconosce tragitto."],
[5013,"Così anche noi, appena nati, siamo già come scomparsi, non avendo da mostrare alcun segno di virtù; ci siamo consumati nella nostra malvagità\"."],
[5014,"La speranza dell'empio è come pula portata dal vento, come schiuma leggera sospinta dalla tempesta; come fumo dal vento è dispersa, si dilegua come il ricordo dell'ospite di un solo giorno."],
[5015,"I giusti al contrario vivono per sempre, la loro ricompensa è presso il Signore  e di essi ha cura l'Altissimo."],
[5016,"Per questo riceveranno una magnifica corona regale, un bel diadema dalle mani del Signore, perché li proteggerà con la destra, con il braccio farà loro da scudo."],
[5017,"Egli prenderà per armatura il suo zelo e userà come arma il creato per punire i nemici,"],
[5018,"indosserà la giustizia come corazza e si metterà come elmo un giudizio imparziale,"],
[5019,"prenderà come scudo la santità invincibile,"],
[5020,"affilerà la sua collera inesorabile come spada e l'universo combatterà con lui contro gli insensati."],
[5021,"Partiranno ben dirette le saette dei lampi e dalle nubi, come da un arco ben teso, balzeranno al bersaglio;"],
[5022,"dalla sua fionda saranno scagliati chicchi di grandine pieni di furore. Si metterà in fermento contro di loro l'acqua del mare e i fiumi li travolgeranno senza pietà."],
[5023,"Si scatenerà contro di loro un vento impetuoso e come un uragano li travolgerà. L'iniquità renderà deserta tutta la terra e la malvagità rovescerà i troni dei potenti."],
[6001,"Ascoltate dunque, o re, e cercate di comprendere; imparate, o governanti di tutta la terra."],
[6002,"Porgete l'orecchio, voi dominatori di popoli, che siete orgogliosi di comandare su molte nazioni."],
[6003,"Dal Signore vi fu dato il potere e l'autorità dall'Altissimo; egli esaminerà le vostre opere e scruterà i vostri propositi:"],
[6004,"pur essendo ministri del suo regno, non avete governato rettamente né avete osservato la legge né vi siete comportati secondo il volere di Dio."],
[6005,"Terribile e veloce egli piomberà su di voi, poiché il giudizio è severo contro coloro che stanno in alto."],
[6006,"Gli ultimi infatti meritano misericordia, ma i potenti saranno vagliati con rigore."],
[6007,"Il Signore dell'universo non guarderà in faccia a nessuno, non avrà riguardi per la grandezza, perché egli ha creato il piccolo e il grande e a tutti provvede in egual modo."],
[6008,"Ma sui dominatori incombe un'indagine inflessibile."],
[6009,"Pertanto a voi, o sovrani, sono dirette le mie parole, perché impariate la sapienza e non cadiate in errore."],
[6010,"Chi custodisce santamente le cose sante sarà riconosciuto santo, e quanti le avranno apprese vi troveranno una difesa."],
[6011,"Bramate, pertanto, le mie parole, desideratele e ne sarete istruiti."],
[6012,"La sapienza è splendida e non sfiorisce, facilmente si lascia vedere da coloro che la amano e si lascia trovare da quelli che la cercano."],
[6013,"Nel farsi conoscere previene coloro che la desiderano."],
[6014,"Chi si alza di buon mattino per cercarla non si affaticherà, la troverà seduta alla sua porta."],
[6015,"Riflettere su di lei, infatti, è intelligenza perfetta, chi veglia a causa sua sarà presto senza affanni;"],
[6016,"poiché lei stessa va in cerca di quelli che sono degni di lei, appare loro benevola per le strade e in ogni progetto va loro incontro."],
[6017,"Suo principio più autentico è il desiderio di istruzione, l'anelito per l'istruzione è amore,"],
[6018,"l'amore per lei è osservanza delle sue leggi, il rispetto delle leggi è garanzia di incorruttibilità"],
[6019,"e l'incorruttibilità rende vicini a Dio."],
[6020,"Dunque il desiderio della sapienza innalza al regno."],
[6021,"Se dunque, dominatori di popoli, vi compiacete di troni e di scettri, onorate la sapienza, perché possiate regnare sempre."],
[6022,"Annuncerò che cos'è la sapienza e com'è nata, non vi terrò nascosti i suoi segreti, ma fin dalle origini ne ricercherò le tracce, metterò in chiaro la conoscenza di lei, non mi allontanerò dalla verità."],
[6023,"Non mi farò compagno di chi si consuma d'invidia, perché costui non avrà nulla in comune con la sapienza."],
[6024,"Il gran numero di sapienti è salvezza per il mondo, un re prudente è la sicurezza del popolo."],
[6025,"Lasciatevi dunque ammaestrare dalle mie parole e ne trarrete profitto."],
[7001,"Anch'io sono un uomo mortale uguale a tutti, discendente del primo uomo plasmato con la terra. La mia carne fu modellata nel grembo di mia madre,"],
[7002,"nello spazio di dieci mesi ho preso consistenza nel sangue, dal seme d'un uomo e dal piacere compagno del sonno."],
[7003,"Anch'io alla nascita ho respirato l'aria comune e sono caduto sulla terra dove tutti soffrono allo stesso modo; come per tutti, il pianto fu la mia prima voce."],
[7004,"Fui allevato in fasce e circondato di cure;"],
[7005,"nessun re ebbe un inizio di vita diverso."],
[7006,"Una sola è l'entrata di tutti nella vita e uguale ne è l'uscita."],
[7007,"Per questo pregai e mi fu elargita la prudenza, implorai e venne in me lo spirito di sapienza."],
[7008,"La preferii a scettri e a troni, stimai un nulla la ricchezza al suo confronto,"],
[7009,"non la paragonai neppure a una gemma inestimabile, perché tutto l'oro al suo confronto è come un po' di sabbia e come fango sarà valutato di fronte a lei l'argento."],
[7010,"L'ho amata più della salute e della bellezza, ho preferito avere lei piuttosto che la luce, perché lo splendore che viene da lei non tramonta."],
[7011,"Insieme a lei mi sono venuti tutti i beni; nelle sue mani è una ricchezza incalcolabile."],
[7012,"Ho gioito di tutto ciò, perché lo reca la sapienza, ma ignoravo che ella è madre di tutto questo."],
[7013,"Ciò che senza astuzia ho imparato, senza invidia lo comunico, non nascondo le sue ricchezze."],
[7014,"Ella è infatti un tesoro inesauribile per gli uomini; chi lo possiede ottiene l'amicizia con Dio, è a lui raccomandato dai frutti della sua educazione."],
[7015,"Mi conceda Dio di parlare con intelligenza e di riflettere in modo degno dei doni ricevuti, perché egli stesso è la guida della sapienza  e dirige i sapienti."],
[7016,"Nelle sue mani siamo noi e le nostre parole, ogni sorta di conoscenza e ogni capacità operativa."],
[7017,"Egli stesso mi ha concesso la conoscenza autentica delle cose, per comprendere la struttura del mondo e la forza dei suoi elementi,"],
[7018,"il principio, la fine e il mezzo dei tempi, l'alternarsi dei solstizi e il susseguirsi delle stagioni,"],
[7019,"i cicli dell'anno e la posizione degli astri,"],
[7020,"la natura degli animali e l'istinto delle bestie selvatiche, la forza dei venti e i ragionamenti degli uomini, la varietà delle piante e le proprietà delle radici."],
[7021,"Ho conosciuto tutte le cose nascoste e quelle manifeste, perché mi ha istruito la sapienza, artefice di tutte le cose."],
[7022,"In lei c'è uno spirito intelligente, santo, unico, molteplice, sottile, agile, penetrante, senza macchia, schietto, inoffensivo, amante del bene, pronto,"],
[7023,"libero, benefico, amico dell'uomo, stabile, sicuro, tranquillo, che può tutto e tutto controlla, che penetra attraverso tutti gli spiriti intelligenti, puri, anche i più sottili."],
[7024,"La sapienza è più veloce di qualsiasi movimento, per la sua purezza si diffonde e penetra in ogni cosa."],
[7025,"È effluvio della potenza di Dio, emanazione genuina della gloria dell'Onnipotente; per questo nulla di contaminato penetra in essa."],
[7026,"È riflesso della luce perenne, uno specchio senza macchia dell'attività di Dio e immagine della sua bontà."],
[7027,"Sebbene unica, può tutto; pur rimanendo in se stessa, tutto rinnova e attraverso i secoli, passando nelle anime sante, prepara amici di Dio e profeti."],
[7028,"Dio infatti non ama se non chi vive con la sapienza."],
[7029,"Ella in realtà è più radiosa del sole e supera ogni costellazione, paragonata alla luce risulta più luminosa;"],
[7030,"a questa, infatti, succede la notte, ma la malvagità non prevale sulla sapienza."],
[8001,"La sapienza si estende vigorosa da un'estremità all'altra e governa a meraviglia l'universo."],
[8002,"È lei che ho amato e corteggiato fin dalla mia giovinezza, ho bramato di farla mia sposa, mi sono innamorato della sua bellezza."],
[8003,"Ella manifesta la sua nobile origine vivendo in comunione con Dio, poiché il Signore dell'universo l'ha amata;"],
[8004,"infatti è iniziata alla scienza di Dio e discerne le sue opere."],
[8005,"Se la ricchezza è un bene desiderabile in vita, che cosa c'è di più ricco della sapienza, che opera tutto?"],
[8006,"Se è la prudenza ad agire, chi più di lei è artefice di quanto esiste?"],
[8007,"Se uno ama la giustizia,  le virtù sono il frutto delle sue fatiche. Ella infatti insegna la temperanza e la prudenza, la giustizia e la fortezza, delle quali nulla è più utile agli uomini durante la vita."],
[8008,"Se uno desidera anche un'esperienza molteplice, ella conosce le cose passate e intravede quelle future, conosce le sottigliezze dei discorsi e le soluzioni degli enigmi, comprende in anticipo segni e prodigi e anche le vicende dei tempi e delle epoche."],
[8009,"Ho dunque deciso di dividere con lei la mia vita, certo che mi sarebbe stata consigliera di buone azioni e conforto nelle preoccupazioni e nel dolore."],
[8010,"Per lei avrò gloria tra le folle e, anche se giovane, onore presso gli anziani."],
[8011,"Sarò trovato perspicace nel giudicare, sarò ammirato di fronte ai potenti."],
[8012,"Se tacerò, resteranno in attesa, se parlerò, mi presteranno attenzione, e se mi dilungo nel parlare, si tapperanno la bocca."],
[8013,"Grazie a lei avrò l'immortalità e lascerò un ricordo eterno a quelli che verranno dopo di me."],
[8014,"Governerò popoli, e nazioni mi saranno soggette."],
[8015,"Sentendo parlare di me, crudeli tiranni si spaventeranno; mi mostrerò buono con il popolo e coraggioso in guerra."],
[8016,"Ritornato a casa, riposerò vicino a lei, perché la sua compagnia non dà amarezza, né dolore il vivere con lei, ma contentezza e gioia."],
[8017,"Riflettendo su queste cose dentro di me e pensando in cuor mio che nella parentela con la sapienza c'è l'immortalità"],
[8018,"e grande godimento vi è nella sua amicizia e nel lavoro delle sue mani sta una ricchezza inesauribile e nell'assidua compagnia di lei c'è la prudenza e fama nel conversare con lei, andavo cercando il modo di prenderla con me."],
[8019,"Ero un ragazzo di nobile indole, ebbi in sorte un'anima buona"],
[8020,"o piuttosto, essendo buono, ero entrato in un corpo senza macchia."],
[8021,"Sapendo che non avrei ottenuto la sapienza in altro modo, se Dio non me l'avesse concessa - ed è già segno di saggezza sapere da chi viene tale dono -, mi rivolsi al Signore e lo pregai, dicendo con tutto il mio cuore:"],
[9001,"\"Dio dei padri e Signore della misericordia, che tutto hai creato con la tua parola,"],
[9002,"e con la tua sapienza hai formato l'uomo perché dominasse sulle creature che tu hai fatto,"],
[9003,"e governasse il mondo con santità e giustizia ed esercitasse il giudizio con animo retto,"],
[9004,"dammi la sapienza, che siede accanto a te in trono, e non mi escludere dal numero dei tuoi figli,"],
[9005,"perché io sono tuo schiavo e figlio della tua schiava, uomo debole e dalla vita breve, incapace di comprendere la giustizia e le leggi."],
[9006,"Se qualcuno fra gli uomini fosse perfetto, privo della sapienza che viene da te, sarebbe stimato un nulla."],
[9007,"Tu mi hai prescelto come re del tuo popolo e giudice dei tuoi figli e delle tue figlie;"],
[9008,"mi hai detto di costruirti un tempio sul tuo santo monte, un altare nella città della tua dimora, immagine della tenda santa che ti eri preparata fin da principio."],
[9009,"Con te è la sapienza che conosce le tue opere, che era presente quando creavi il mondo; lei sa quel che piace ai tuoi occhi e ciò che è conforme ai tuoi decreti."],
[9010,"Inviala dai cieli santi, mandala dal tuo trono glorioso, perché mi assista e mi affianchi nella mia fatica e io sappia ciò che ti è gradito."],
[9011,"Ella infatti tutto conosce e tutto comprende: mi guiderà con prudenza nelle mie azioni e mi proteggerà con la sua gloria."],
[9012,"Così le mie opere ti saranno gradite; io giudicherò con giustizia il tuo popolo e sarò degno del trono di mio padre."],
[9013,"Quale uomo può conoscere il volere di Dio? Chi può immaginare che cosa vuole il Signore?"],
[9014,"I ragionamenti dei mortali sono timidi e incerte le nostre riflessioni,"],
[9015,"perché un corpo corruttibile appesantisce l'anima e la tenda d'argilla opprime una mente piena di preoccupazioni."],
[9016,"A stento immaginiamo le cose della terra, scopriamo con fatica quelle a portata di mano; ma chi ha investigato le cose del cielo?"],
[9017,"Chi avrebbe conosciuto il tuo volere, se tu non gli avessi dato la sapienza e dall'alto non gli avessi inviato il tuo santo spirito?"],
[9018,"Così vennero raddrizzati i sentieri di chi è sulla terra; gli uomini furono istruiti in ciò che ti è gradito e furono salvati per mezzo della sapienza\"."],
[10001,"Ella protesse il padre del mondo, plasmato per primo, che era stato creato solo, lo sollevò dalla sua caduta"],
[10002,"e gli diede la forza per dominare tutte le cose."],
[10003,"Ma un ingiusto, allontanatosi da lei nella sua collera, si rovinò con il suo furore fratricida."],
[10004,"La sapienza salvò di nuovo la terra sommersa per propria colpa, pilotando il giusto su un semplice legno."],
[10005,"Quando i popoli furono confusi, unanimi nella loro malvagità, ella riconobbe il giusto, lo conservò davanti a Dio senza macchia e lo mantenne forte nonostante la sua tenerezza per il figlio."],
[10006,"Mentre perivano gli empi, ella liberò un giusto che fuggiva il fuoco caduto sulle cinque città."],
[10007,"A testimonianza di quella malvagità  esiste ancora una terra desolata, fumante, alberi che producono frutti immaturi e, a memoria di un'anima incredula, s'innalza una colonna di sale."],
[10008,"Essi infatti, incuranti della sapienza, non solo subirono il danno di non conoscere il bene, ma lasciarono anche ai viventi un ricordo di insipienza, perché nelle cose in cui sbagliarono non potessero rimanere nascosti."],
[10009,"La sapienza invece liberò dalle sofferenze coloro che la servivano."],
[10010,"Per diritti sentieri ella guidò il giusto in fuga dall'ira del fratello, gli mostrò il regno di Dio e gli diede la conoscenza delle cose sante; lo fece prosperare nelle fatiche e rese fecondo il suo lavoro."],
[10011,"Lo assistette contro l'ingordigia dei suoi oppressori e lo rese ricco;"],
[10012,"lo custodì dai nemici, lo protesse da chi lo insidiava, gli assegnò la vittoria in una lotta dura, perché sapesse che più potente di tutto è la pietà."],
[10013,"Ella non abbandonò il giusto venduto, ma lo liberò dal peccato."],
[10014,"Scese con lui nella prigione, non lo abbandonò mentre era in catene, finché gli procurò uno scettro regale e l'autorità su coloro che dominavano sopra di lui; mostrò che i suoi accusatori erano bugiardi e gli diede una gloria eterna."],
[10015,"Ella liberò il popolo santo e la stirpe senza macchia da una nazione di oppressori."],
[10016,"Entrò nell'anima di un servo del Signore e con prodigi e segni tenne testa a re terribili."],
[10017,"Diede ai santi la ricompensa delle loro pene, li guidò per una strada meravigliosa, divenne per loro riparo di giorno e luce di stelle nella notte."],
[10018,"Fece loro attraversare il Mar Rosso e li guidò attraverso acque abbondanti;"],
[10019,"sommerse invece i loro nemici e li rigettò dal fondo dell'abisso."],
[10020,"Per questo i giusti depredarono gli empi e celebrarono, o Signore, il tuo nome che è santo, e lodarono concordi la tua mano che combatteva per loro,"],
[10021,"perché la sapienza aveva aperto la bocca dei muti e aveva reso chiara la lingua dei bambini."],
[11001,"La sapienza favorì le loro imprese per mezzo di un santo profeta."],
[11002,"Attraversarono un deserto inospitale, fissarono le tende in terreni impraticabili,"],
[11003,"resistettero agli avversari, respinsero i nemici."],
[11004,"Ebbero sete e ti invocarono e fu data loro acqua da una rupe scoscesa, rimedio alla sete da una dura roccia."],
[11005,"Ciò che era servito a punire i loro nemici, per loro, nel bisogno, fu strumento di favori."],
[11006,"Invece dello sgorgare perenne di un fiume, reso torbido da putrido sangue"],
[11007,"in punizione di un decreto infanticida, contro ogni speranza tu desti loro acqua abbondante,"],
[11008,"mostrando attraverso la sete di allora come avevi punito i loro avversari."],
[11009,"Difatti, messi alla prova,  sebbene puniti con misericordia, compresero come gli empi, giudicati nella collera, erano stati tormentati;"],
[11010,"perché tu provasti gli uni come un padre che corregge, mentre vagliasti gli altri come un re severo che condanna."],
[11011,"Lontani o vicini erano ugualmente tribolati,"],
[11012,"perché li colse un duplice dolore e un sospiro per i ricordi del passato."],
[11013,"Quando infatti seppero che dal loro castigo quelli erano beneficati, si accorsero della presenza del Signore;"],
[11014,"poiché colui che prima avevano esposto e poi deriso, al termine degli avvenimenti dovettero ammirarlo, dopo aver patito una sete ben diversa da quella dei giusti."],
[11015,"In cambio dei ragionamenti insensati della loro ingiustizia, in cui, errando, rendevano onori divini a rettili senza parola e a bestie spregevoli, tu inviasti contro di loro come punizione una moltitudine di animali irragionevoli,"],
[11016,"perché capissero che con le cose con cui uno pecca, con quelle viene punito."],
[11017,"Non era certo in difficoltà la tua mano onnipotente, che aveva creato il mondo da una materia senza forma, a mandare loro una moltitudine di orsi o leoni feroci"],
[11018,"o bestie molto feroci, prima sconosciute e create da poco, che esalano un alito infuocato o emettono un crepitio di vapore o sprizzano terribili scintille dagli occhi,"],
[11019,"delle quali non solo l'assalto poteva sterminarli, ma lo stesso aspetto terrificante poteva annientarli."],
[11020,"Anche senza queste potevano cadere con un soffio, perseguitati dalla giustizia e dispersi dal tuo soffio potente, ma tu hai disposto ogni cosa con misura, calcolo e peso."],
[11021,"Prevalere con la forza ti è sempre possibile; chi si opporrà alla potenza del tuo braccio?"],
[11022,"Tutto il mondo, infatti, davanti a te è come polvere sulla bilancia, come una stilla di rugiada mattutina caduta sulla terra."],
[11023,"Hai compassione di tutti, perché tutto puoi, chiudi gli occhi sui peccati degli uomini, aspettando il loro pentimento."],
[11024,"Tu infatti ami tutte le cose che esistono e non provi disgusto per nessuna delle cose che hai creato; se avessi odiato qualcosa, non l'avresti neppure formata."],
[11025,"Come potrebbe sussistere una cosa, se tu non l'avessi voluta? Potrebbe conservarsi ciò che da te non fu chiamato all'esistenza?"],
[11026,"Tu sei indulgente con tutte le cose, perché sono tue,  Signore, amante della vita."],
[12001,"Poiché il tuo spirito incorruttibile è in tutte le cose."],
[12002,"Per questo tu correggi a poco a poco quelli che sbagliano e li ammonisci ricordando loro in che cosa hanno peccato, perché, messa da parte ogni malizia, credano in te, Signore."],
[12003,"Tu hai odiato gli antichi abitanti della tua terra santa,"],
[12004,"perché compivano delitti ripugnanti, pratiche di magia e riti sacrileghi."],
[12005,"Questi spietati uccisori dei loro figli, divoratori di visceri in banchetti di carne umana e di sangue, iniziati in orgiastici riti,"],
[12006,"genitori che uccidevano vite indifese, hai voluto distruggere per mezzo dei nostri padri,"],
[12007,"perché la terra a te più cara di tutte ricevesse una degna colonia di figli di Dio."],
[12008,"Ma hai avuto indulgenza anche di costoro, perché sono uomini, mandando loro vespe come avanguardie del tuo esercito, perché li sterminassero a poco a poco."],
[12009,"Pur potendo in battaglia dare gli empi nelle mani dei giusti, oppure annientarli all'istante con bestie terribili o con una parola inesorabile,"],
[12010,"giudicando invece a poco a poco, lasciavi posto al pentimento,  sebbene tu non ignorassi che la loro razza era cattiva e la loro malvagità innata, e che la loro mentalità non sarebbe mai cambiata,"],
[12011,"perché era una stirpe maledetta fin da principio; e non perché avessi timore di qualcuno tu concedevi l'impunità per le cose in cui avevano peccato."],
[12012,"E chi domanderà: \"Che cosa hai fatto?\", o chi si opporrà a una tua sentenza? Chi ti citerà in giudizio per aver fatto perire popoli che tu avevi creato? Chi si costituirà contro di te  come difensore di uomini ingiusti?"],
[12013,"Non c'è Dio fuori di te, che abbia cura di tutte le cose, perché tu debba difenderti dall'accusa di giudice ingiusto."],
[12014,"Né un re né un sovrano potrebbero affrontarti in difesa di quelli che hai punito."],
[12015,"Tu, essendo giusto, governi tutto con giustizia. Consideri incompatibile con la tua potenza condannare chi non merita il castigo."],
[12016,"La tua forza infatti è il principio della giustizia, e il fatto che sei padrone di tutti, ti rende indulgente con tutti."],
[12017,"Mostri la tua forza quando non si crede nella pienezza del tuo potere, e rigetti l'insolenza di coloro che pur la conoscono."],
[12018,"Padrone della forza, tu giudichi con mitezza e ci governi con molta indulgenza, perché, quando vuoi, tu eserciti il potere."],
[12019,"Con tale modo di agire hai insegnato al tuo popolo che il giusto deve amare gli uomini, e hai dato ai tuoi figli la buona speranza che, dopo i peccati, tu concedi il pentimento."],
[12020,"Se infatti i nemici dei tuoi figli, pur meritevoli di morte, tu hai punito con tanto riguardo e indulgenza, concedendo tempo e modo per allontanarsi dalla loro malvagità,"],
[12021,"con quanta maggiore attenzione hai giudicato i tuoi figli, con i cui padri concludesti, giurando, alleanze di così buone promesse!"],
[12022,"Mentre dunque correggi noi, tu colpisci i nostri nemici in tanti modi, perché nel giudicare riflettiamo sulla tua bontà e ci aspettiamo misericordia, quando siamo giudicati."],
[12023,"Perciò quanti vissero ingiustamente con stoltezza tu li hai tormentati con i loro stessi abomini."],
[12024,"Essi si erano allontanati troppo sulla via dell'errore, scambiando per dei gli animali più abietti e più ripugnanti, ingannati come bambini che non ragionano."],
[12025,"Per questo, come a fanciulli irragionevoli, hai mandato un castigo per prenderti gioco di loro."],
[12026,"Ma chi non si lascia correggere da punizioni derisorie, sperimenterà un giudizio degno di Dio."],
[12027,"Infatti, soffrendo per questi animali, s'indignavano perché puniti con gli stessi esseri che stimavano dei, e capirono e riconobbero il vero Dio, che prima non avevano voluto conoscere. Per questo la condanna suprema si abbatté su di loro."],
[13001,"Davvero vani per natura tutti gli uomini che vivevano nell'ignoranza di Dio, e dai beni visibili non furono capaci di riconoscere colui che è, né, esaminandone le opere, riconobbero l'artefice."],
[13002,"Ma o il fuoco o il vento o l'aria veloce, la volta stellata o l'acqua impetuosa o le luci del cielo essi considerarono come dei, reggitori del mondo."],
[13003,"Se, affascinati dalla loro bellezza, li hanno presi per dei, pensino quanto è superiore il loro sovrano, perché li ha creati colui che è principio e autore della bellezza."],
[13004,"Se sono colpiti da stupore per la loro potenza ed energia, pensino da ciò quanto è più potente colui che li ha formati."],
[13005,"Difatti dalla grandezza e bellezza delle creature per analogia si contempla il loro autore."],
[13006,"Tuttavia per costoro leggero è il rimprovero, perché essi facilmente s'ingannano cercando Dio e volendolo trovare."],
[13007,"Vivendo in mezzo alle sue opere, ricercano con cura e si lasciano prendere dall'apparenza perché le cose viste sono belle."],
[13008,"Neppure costoro però sono scusabili,"],
[13009,"perché, se sono riusciti a conoscere tanto da poter esplorare il mondo, come mai non ne hanno trovato più facilmente il sovrano?"],
[13010,"Infelici anche coloro le cui speranze sono in cose morte e che chiamarono dei le opere di mani d'uomo, oro e argento, lavorati con arte, e immagini di animali, oppure una pietra inutile, opera di mano antica."],
[13011,"Ecco un falegname: dopo aver segato un albero maneggevole, ha tagliato facilmente tutta la corteccia intorno e, avendolo lavorato abilmente, ha preparato un oggetto utile alle necessità della vita;"],
[13012,"raccolti poi gli avanzi del suo lavoro, li consuma per prepararsi il cibo e saziarsi."],
[13013,"Quanto avanza ancora, buono proprio a nulla, legno contorto e pieno di nodi, lo prende e lo scolpisce per occupare il tempo libero; con l'abilità dei momenti di riposo gli dà una forma, lo fa simile a un'immagine umana"],
[13014,"oppure a quella di un animale spregevole. Lo vernicia con minio, ne colora di rosso la superficie e ricopre con la vernice ogni sua macchia;"],
[13015,"quindi, preparatagli una degna dimora, lo colloca sul muro, fissandolo con un chiodo."],
[13016,"Provvede perché non cada, ben sapendo che non è in grado di aiutarsi da sé; infatti è solo un'immagine e ha bisogno di aiuto."],
[13017,"Quando prega per i suoi beni, per le nozze e per i figli, non si vergogna di parlare a quell'oggetto inanimato, e per la sua salute invoca un essere debole,"],
[13018,"per la sua vita prega una cosa morta, per un aiuto supplica un essere inetto, per il suo viaggio uno che non può usare i suoi piedi;"],
[13019,"per un guadagno, un lavoro e un successo negli affari, chiede abilità a uno che è il più inabile con le mani."],
[14001,"Anche chi si dispone a navigare e a solcare onde selvagge invoca un legno più fragile dell'imbarcazione che lo porta."],
[14002,"Questa infatti fu inventata dal desiderio di guadagni e fu costruita da una saggezza artigiana;"],
[14003,"ma la tua provvidenza, o Padre, la pilota, perché tu tracciasti un cammino anche nel mare e un sentiero sicuro anche fra le onde,"],
[14004,"mostrando che puoi salvare da tutto, sì che uno possa imbarcarsi anche senza esperienza."],
[14005,"Tu non vuoi che le opere della tua sapienza siano inutili; per questo gli uomini affidano la loro vita anche a un minuscolo legno e, avendo attraversato i flutti su una zattera, furono salvati."],
[14006,"Infatti, anche in principio, mentre perivano i superbi giganti, la speranza del mondo, rifugiatasi in una zattera e guidata dalla tua mano, lasciò al mondo un seme di nuove generazioni."],
[14007,"Benedetto è il legno per mezzo del quale si compie la giustizia,"],
[14008,"maledetto invece l'idolo, opera delle mani, e chi lo ha fatto; questi perché lo ha preparato, quello perché, pur essendo corruttibile, è stato chiamato dio."],
[14009,"Perché a Dio sono ugualmente in odio l'empio e la sua empietà;"],
[14010,"l'opera sarà punita assieme a chi l'ha compiuta."],
[14011,"Perciò ci sarà un giudizio anche per gli idoli delle nazioni, perché fra le creature di Dio sono diventati oggetto di ribrezzo, e inciampo per le anime degli uomini, e laccio per i piedi degli stolti."],
[14012,"Infatti l'invenzione degli idoli fu l'inizio della fornicazione, la loro scoperta portò alla corruzione della vita."],
[14013,"Essi non esistevano dall'inizio e non esisteranno in futuro."],
[14014,"Entrarono nel mondo, infatti, per la vana ambizione degli uomini, per questo è stata decretata loro una brusca fine."],
[14015,"Un padre, consumato da un lutto prematuro, avendo fatto un'immagine del figlio così presto rapito, onorò come un dio un uomo appena morto e ai suoi subalterni ordinò misteri e riti d'iniziazione;"],
[14016,"col passare del tempo l'empia usanza si consolidò e fu osservata come una legge. Anche per ordine dei sovrani le immagini scolpite venivano fatte oggetto di culto;"],
[14017,"alcuni uomini, non potendo onorarli di persona perché distanti, avendo riprodotto le sembianze lontane, fecero un'immagine visibile del re venerato, per adulare con zelo l'assente, come fosse presente."],
[14018,"A estendere il culto anche presso quanti non lo conoscevano, spinse l'ambizione dell'artista."],
[14019,"Questi infatti, desideroso senz'altro di piacere al potente, si sforzò con l'arte di renderne più bella l'immagine;"],
[14020,"ma la folla, attratta dal fascino dell'opera, considerò oggetto di adorazione colui che poco prima onorava come uomo."],
[14021,"Divenne un'insidia alla vita il fatto che uomini, resi schiavi della disgrazia e del potere, abbiano attribuito a pietre o a legni il nome incomunicabile."],
[14022,"Inoltre non fu loro sufficiente errare nella conoscenza di Dio, ma, vivendo nella grande guerra dell'ignoranza, a mali tanto grandi danno il nome di pace."],
[14023,"Celebrando riti di iniziazione infanticidi o misteri occulti o banchetti orgiastici secondo strane usanze,"],
[14024,"non conservano puri né la vita né il matrimonio, ma uno uccide l'altro a tradimento o l'affligge con l'adulterio."],
[14025,"Tutto vi è mescolato: sangue e omicidio, furto e inganno, corruzione, slealtà, tumulto, spergiuro,"],
[14026,"sconcerto dei buoni, dimenticanza dei favori, corruzione di anime, perversione sessuale, disordini nei matrimoni, adulterio e impudicizia."],
[14027,"L'adorazione di idoli innominabili è principio, causa e culmine di ogni male."],
[14028,"Infatti coloro che sono idolatri vanno fuori di sé nelle orge o profetizzano cose false o vivono da iniqui o spergiurano con facilità."],
[14029,"Ponendo fiducia in idoli inanimati, non si aspettano un castigo per aver giurato il falso."],
[14030,"Ma, per l'uno e per l'altro motivo, li raggiungerà la giustizia, perché concepirono un'idea falsa di Dio, rivolgendosi agli idoli, e perché spergiurarono con frode, disprezzando la santità."],
[14031,"Infatti non la potenza di coloro per i quali si giura, ma la giustizia che punisce i peccatori persegue sempre la trasgressione degli ingiusti."],
[15001,"Ma tu, nostro Dio, sei buono e veritiero, sei paziente e tutto governi secondo misericordia."],
[15002,"Anche se pecchiamo, siamo tuoi, perché conosciamo la tua potenza; ma non peccheremo più, perché sappiamo di appartenerti."],
[15003,"Conoscerti, infatti, è giustizia perfetta, conoscere la tua potenza è radice d'immortalità."],
[15004,"Non ci indusse in errore né l'invenzione umana di un'arte perversa, né il lavoro infruttuoso di coloro che disegnano ombre, immagini imbrattate di vari colori,"],
[15005,"la cui vista negli stolti provoca il desiderio, l'anelito per una forma inanimata di un'immagine morta."],
[15006,"Amanti di cose cattive e degni di simili speranze sono coloro che fanno, desiderano e venerano gli idoli."],
[15007,"Un vasaio, impastando con fatica la terra molle, plasma per il nostro uso ogni vaso. Ma con il medesimo fango modella i vasi che servono per usi nobili e quelli per usi contrari, tutti allo stesso modo; quale debba essere l'uso di ognuno di essi lo giudica colui che lavora l'argilla."],
[15008,"Quindi, mal impiegando la fatica, con il medesimo fango plasma un dio vano, egli che, nato da poco dalla terra, tra poco ritornerà alla terra da cui fu tratto, quando gli sarà richiesta l'anima, avuta in prestito."],
[15009,"Tuttavia egli si preoccupa non perché sta per morire o perché ha una vita breve, ma di gareggiare con gli orafi e con gli argentieri, di imitare coloro che fondono il bronzo, e ritiene un vanto plasmare cose false."],
[15010,"Cenere è il suo cuore, la sua speranza più vile della terra, la sua vita più spregevole del fango,"],
[15011,"perché disconosce colui che lo ha plasmato, colui che gli inspirò un'anima attiva e gli infuse uno spirito vitale."],
[15012,"Ma egli considera la nostra vita come un gioco da bambini, l'esistenza un mercato lucroso. Egli dice che da tutto, anche dal male, si deve trarre profitto."],
[15013,"Costui infatti sa di peccare più di tutti, fabbricando con materia terrestre fragili vasi e statue."],
[15014,"Ma sono tutti stoltissimi e più miserabili di un piccolo bambino  i nemici del tuo popolo, che lo hanno oppresso."],
[15015,"Perché essi considerarono dei anche tutti gli idoli delle nazioni, i quali non hanno né l'uso degli occhi per vedere, né narici per aspirare aria, né orecchie per udire, né dita delle mani per toccare, e i loro piedi non servono per camminare."],
[15016,"Infatti li ha fabbricati un uomo, li ha plasmati uno che ha avuto il respiro in prestito. Ora nessun uomo può plasmare un dio a lui simile;"],
[15017,"essendo mortale, egli fabbrica una cosa morta con mani empie. Egli è sempre migliore degli oggetti che venera, rispetto ad essi egli ebbe la vita, ma quelli mai."],
[15018,"Venerano anche gli animali più ripugnanti, che per stupidità, al paragone, risultano peggiori degli altri."],
[15019,"Non sono tali da invaghirsene, come capita per il bell'aspetto di altri animali; furono persino esclusi dalla lode e dalla benedizione di Dio."],
[16001,"Per questo furono giustamente puniti con esseri simili e torturati con una moltitudine di bestie."],
[16002,"Invece di tale castigo, tu beneficasti il tuo popolo; per appagarne il forte appetito gli preparasti come cibo quaglie dal gusto insolito,"],
[16003,"perché quelli che desideravano cibo, a causa del ribrezzo per gli animali inviati contro di loro, perdessero anche l'istinto della fame, mentre questi, rimasti privi di cibo per un breve periodo, provassero un gusto insolito."],
[16004,"Era necessario che su quei tiranni si abbattesse una carestia implacabile e a questi si mostrasse soltanto  come erano tormentati i loro nemici."],
[16005,"Quando infatti li assalì il terribile furore delle bestie e venivano distrutti per i morsi di serpenti sinuosi, la tua collera non durò sino alla fine."],
[16006,"Per correzione furono turbati per breve tempo, ed ebbero un segno di salvezza a ricordo del precetto della tua legge."],
[16007,"Infatti chi si volgeva a guardarlo era salvato non per mezzo dell'oggetto che vedeva, ma da te, salvatore di tutti."],
[16008,"Anche in tal modo hai persuaso i nostri nemici che sei tu colui che libera da ogni male."],
[16009,"Essi infatti furono uccisi dai morsi di cavallette e mosconi, né si trovò un rimedio per la loro vita, meritando di essere puniti con tali mezzi."],
[16010,"Invece contro i tuoi figli neppure i denti di serpenti velenosi prevalsero, perché la tua misericordia venne loro incontro e li guarì."],
[16011,"Perché ricordassero le tue parole, venivano feriti ed erano subito guariti, per timore che, caduti in un profondo oblio, fossero esclusi dai tuoi benefici."],
[16012,"Non li guarì né un'erba né un unguento, ma la tua parola, o Signore, che tutto risana."],
[16013,"Tu infatti hai potere sulla vita e sulla morte, conduci alle porte del regno dei morti e fai risalire."],
[16014,"L'uomo uccide con la sua malvagità, ma non può far ritornare uno spirito che se n'è andato, né libera un'anima già accolta nel regno dei morti."],
[16015,"È impossibile sfuggire alla tua mano:"],
[16016,"perciò gli empi, che rifiutavano di conoscerti, furono fustigati dalla forza del tuo braccio, perseguitati da piogge strane, da grandine, da acquazzoni travolgenti, e consumati dal fuoco."],
[16017,"E, cosa più sorprendente, nell'acqua che tutto spegne il fuoco prendeva sempre più forza, perché alleato dei giusti è l'universo."],
[16018,"Talvolta la fiamma si attenuava per non bruciare gli animali inviati contro gli empi e per far loro comprendere a tale vista che erano incalzati dal giudizio di Dio."],
[16019,"Altre volte, anche in mezzo all'acqua, la fiamma bruciava oltre la potenza del fuoco per distruggere i germogli di una terra iniqua."],
[16020,"Invece hai sfamato il tuo popolo con il cibo degli angeli, dal cielo hai offerto loro un pane pronto senza fatica, capace di procurare ogni delizia e soddisfare ogni gusto."],
[16021,"Questo tuo alimento manifestava la tua dolcezza verso i figli, si adattava al gusto di chi ne mangiava, si trasformava in ciò che ognuno desiderava."],
[16022,"Neve e ghiaccio resistevano al fuoco e non si fondevano, perché sapessero che il fuoco, che ardeva nella grandine e lampeggiava nelle piogge, distruggeva i frutti dei nemici;"],
[16023,"al contrario, perché i giusti si nutrissero, dimenticava perfino la propria forza."],
[16024,"La creazione infatti, obbedendo a te che l'hai fatta, si irrigidisce per punire gli ingiusti e si addolcisce a favore di quelli che confidano in te."],
[16025,"Per questo anche allora, adattandosi a tutto, era al servizio del tuo dono che nutre tutti, secondo il desiderio di chi ti pregava,"],
[16026,"perché i tuoi figli, che hai amato, o Signore, imparassero che non le diverse specie di frutti nutrono l'uomo, ma la tua parola tiene in vita coloro che credono in te."],
[16027,"Ciò che infatti non era stato distrutto dal fuoco si scioglieva appena scaldato da un breve raggio di sole,"],
[16028,"perché fosse noto che si deve prevenire il sole per renderti grazie e incontrarti al sorgere della luce,"],
[16029,"poiché la speranza dell'ingrato si scioglierà come brina invernale e si disperderà come un'acqua inutilizzabile."],
[17001,"I tuoi giudizi sono grandi e difficili da spiegare; per questo le anime senza istruzione si sono ingannate."],
[17002,"Infatti gli ingiusti, avendo preteso di dominare il popolo santo, prigionieri delle tenebre e incatenati a una lunga notte, chiusi sotto i loro tetti, giacevano esclusi dalla provvidenza eterna."],
[17003,"Credendo di restare nascosti con i loro peccati segreti, sotto il velo oscuro dell'oblio, furono dispersi, terribilmente spaventati  e sconvolti da visioni."],
[17004,"Neppure il nascondiglio in cui si trovavano li preservò dal timore, ma suoni spaventosi rimbombavano intorno a loro e apparivano lugubri spettri dai volti tristi."],
[17005,"Nessun fuoco, per quanto intenso, riusciva a far luce, neppure le luci più splendenti degli astri riuscivano a rischiarare dall'alto quella notte cupa."],
[17006,"Appariva loro solo una massa di fuoco, improvvisa, tremenda; atterriti da quella fugace visione, credevano ancora peggiori le cose che vedevano."],
[17007,"Fallivano i ritrovati della magia, e il vanto della loro saggezza era svergognato."],
[17008,"Infatti quelli che promettevano di cacciare timori e inquietudini dall'anima malata, languivano essi stessi in un ridicolo timore."],
[17009,"Anche se nulla di spaventoso li atterriva, messi in agitazione al passare delle bestie e ai sibili dei rettili, morivano di tremore,  rifiutando persino di guardare l'aria che in nessun modo si può evitare."],
[17010,"La malvagità condannata dalla propria testimonianza è qualcosa di vile e, oppressa dalla coscienza, aumenta sempre le difficoltà."],
[17011,"La paura infatti altro non è che l'abbandono degli aiuti della ragione;"],
[17012,"quanto meno ci si affida nell'intimo a tali aiuti, tanto più grave è l'ignoranza della causa che provoca il tormento."],
[17013,"Ma essi, durante tale notte davvero impotente, uscita dagli antri del regno dei morti anch'esso impotente, mentre dormivano il medesimo sonno,"],
[17014,"ora erano tormentati da fantasmi mostruosi, ora erano paralizzati, traditi dal coraggio, perché una paura improvvisa e inaspettata si era riversata su di loro."],
[17015,"Così chiunque, come caduto là dove si trovava, era custodito chiuso in un carcere senza sbarre:"],
[17016,"agricoltore o pastore o lavoratore che fatica nel deserto, sorpreso, subiva l'ineluttabile destino, perché tutti erano legati dalla stessa catena di tenebre."],
[17017,"Il vento che sibila o canto melodioso di uccelli tra folti rami o suono cadenzato dell'acqua che scorre con forza o cupo fragore di rocce che precipitano"],
[17018,"o corsa invisibile di animali imbizzarriti o urla di crudelissime belve ruggenti o eco rimbalzante dalle cavità dei monti, tutto li paralizzava riempiendoli di terrore."],
[17019,"Il mondo intero splendeva di luce smagliante e attendeva alle sue opere senza impedimento."],
[17020,"Soltanto su di loro si stendeva una notte profonda, immagine della tenebra che li avrebbe avvolti; ma essi erano a se stessi più gravosi delle tenebre."],
[18001,"Per i tuoi santi invece c'era una luce grandissima; quegli altri, sentendone le voci, senza vederne l'aspetto, li proclamavano beati, perché non avevano sofferto come loro"],
[18002,"e li ringraziavano perché non nuocevano loro, pur avendo subito un torto,  e imploravano perdono delle passate inimicizie."],
[18003,"Invece desti loro una colonna di fuoco, come guida di un viaggio sconosciuto e sole inoffensivo per un glorioso migrare in terra straniera."],
[18004,"Meritavano di essere privati della luce e imprigionati nelle tenebre quelli che avevano tenuto chiusi in carcere i tuoi figli, per mezzo dei quali la luce incorruttibile della legge doveva essere concessa al mondo."],
[18005,"Poiché essi avevano deliberato di uccidere i neonati dei santi - e un solo bambino fu esposto e salvato -, tu per castigo hai tolto di mezzo la moltitudine dei loro figli, facendoli perire tutti insieme nell'acqua impetuosa."],
[18006,"Quella notte fu preannunciata ai nostri padri, perché avessero coraggio, sapendo bene a quali giuramenti avevano prestato fedeltà."],
[18007,"Il tuo popolo infatti era in attesa della salvezza dei giusti, della rovina dei nemici."],
[18008,"Difatti come punisti gli avversari, così glorificasti noi, chiamandoci a te."],
[18009,"I figli santi dei giusti offrivano sacrifici in segreto e si imposero, concordi, questa legge divina: di condividere allo stesso modo successi e pericoli, intonando subito le sacre lodi dei padri."],
[18010,"Faceva eco il grido discorde dei nemici e si diffondeva il lamento di quanti piangevano i figli."],
[18011,"Con la stessa pena il servo era punito assieme al padrone, l'uomo comune soffriva le stesse pene del re."],
[18012,"Tutti insieme, nello stesso modo,  ebbero innumerevoli morti, e i vivi non bastavano a seppellirli, perché in un istante fu sterminata la loro prole più nobile."],
[18013,"Quanti erano rimasti increduli a tutto per via delle loro magie, allo sterminio dei primogeniti confessarono che questo popolo era figlio di Dio."],
[18014,"Mentre un profondo silenzio avvolgeva tutte le cose, e la notte era a metà del suo rapido corso,"],
[18015,"la tua parola onnipotente dal cielo, dal tuo trono regale,  guerriero implacabile, si lanciò in mezzo a quella terra di sterminio, portando, come spada affilata, il tuo decreto irrevocabile"],
[18016,"e, fermatasi, riempì tutto di morte; toccava il cielo e aveva i piedi sulla terra."],
[18017,"Allora improvvisi fantasmi di sogni terribili li atterrivano e timori inattesi piombarono su di loro."],
[18018,"Cadendo mezzi morti qua e là, mostravano quale fosse la causa della loro morte."],
[18019,"Infatti i loro sogni terrificanti li avevano preavvisati, perché non morissero ignorando il motivo delle loro sofferenze."],
[18020,"L'esperienza della morte colpì anche i giusti e nel deserto ci fu il massacro di una moltitudine, ma l'ira non durò a lungo,"],
[18021,"perché un uomo irreprensibile si affrettò a difenderli, avendo portato le armi del suo ministero, la preghiera e l'incenso espiatorio; si oppose alla collera e mise fine alla sciagura, mostrando di essere il tuo servitore."],
[18022,"Egli vinse la collera divina non con la forza del corpo né con la potenza delle armi, ma con la parola placò colui che castigava, ricordando i giuramenti e le alleanze dei padri."],
[18023,"Quando ormai i morti erano caduti a mucchi gli uni sugli altri, egli, ergendosi là in mezzo, arrestò l'ira e le tagliò la strada che conduceva verso i viventi."],
[18024,"Sulla sua veste lunga fino ai piedi portava tutto il mondo, le glorie dei padri scolpite su quattro file di pietre preziose e la tua maestà sopra il diadema della sua testa."],
[18025,"Di fronte a queste insegne lo sterminatore indietreggiò, ebbe paura, perché bastava questa sola prova dell'ira divina."],
[19001,"Sugli empi sovrastò sino alla fine una collera senza pietà, perché Dio prevedeva anche ciò che avrebbero fatto,"],
[19002,"cioè che, dopo aver loro permesso di andarsene e averli fatti partire in fretta, cambiato proposito, li avrebbero inseguiti."],
[19003,"Mentre infatti erano ancora occupati nei lutti e piangevano sulle tombe dei morti, presero un'altra decisione insensata e inseguirono come fuggitivi quelli che già avevano pregato di partire."],
[19004,"A questo estremo li spingeva un meritato destino, che li gettò nell'oblio delle cose passate, perché colmassero la punizione che ancora mancava ai loro tormenti,"],
[19005,"e mentre il tuo popolo intraprendeva un viaggio straordinario, essi incappassero in una morte singolare."],
[19006,"Tutto il creato fu modellato di nuovo nella propria natura come prima, obbedendo ai tuoi comandi, perché i tuoi figli fossero preservati sani e salvi."],
[19007,"Si vide la nube coprire d'ombra l'accampamento, terra asciutta emergere dove prima c'era acqua: il Mar Rosso divenne una strada senza ostacoli e flutti violenti una pianura piena d'erba;"],
[19008,"coloro che la tua mano proteggeva passarono con tutto il popolo, contemplando meravigliosi prodigi."],
[19009,"Furono condotti al pascolo come cavalli e saltellarono come agnelli esultanti, celebrando te, Signore, che li avevi liberati."],
[19010,"Ricordavano ancora le cose avvenute nel loro esilio: come la terra, invece di bestiame, produsse zanzare, come il fiume, invece di pesci, riversò una massa di rane."],
[19011,"Più tardi videro anche una nuova generazione di uccelli, quando, spinti dall'appetito, chiesero cibi delicati;"],
[19012,"poiché, per appagarli, dal mare salirono quaglie."],
[19013,"Sui peccatori invece piombarono i castighi non senza segni premonitori di fulmini fragorosi; essi soffrirono giustamente per le loro malvagità, perché avevano mostrato un odio tanto profondo verso lo straniero."],
[19014,"Già altri infatti non avevano accolto gli sconosciuti che arrivavano, ma costoro ridussero in schiavitù gli ospiti che li avevano beneficati."],
[19015,"Non solo: per i primi ci sarà un giudizio, perché accolsero ostilmente i forestieri;"],
[19016,"costoro invece, dopo averli festosamente accolti, quando già partecipavano ai loro diritti, li oppressero con lavori durissimi."],
[19017,"Furono perciò colpiti da cecità, come quelli alla porta del giusto, quando, avvolti fra tenebre fitte, ognuno cercava l'ingresso della propria porta."],
[19018,"Difatti gli elementi erano accordati diversamente, come nella cetra in cui le note variano la specie del ritmo, pur conservando sempre lo stesso tono, come è possibile dedurre da un'attenta considerazione degli avvenimenti."],
[19019,"Infatti animali terrestri divennero acquatici, quelli che nuotavano passarono sulla terra."],
[19020,"Il fuoco rafforzò nell'acqua la sua potenza e l'acqua dimenticò la sua proprietà naturale di spegnere."],
[19021,"Le fiamme non consumavano le carni di fragili animali che vi camminavano sopra, né scioglievano quel celeste nutrimento di vita, simile alla brina e così facile a fondersi."],
[19022,"In tutti i modi, o Signore, hai reso grande e glorioso il tuo popolo e non hai dimenticato di assisterlo in ogni momento e in ogni luogo."]
])
