Bib.ret([
[1001,"Parola del Signore che fu rivolta a Sofonia, figlio di Cusì, figlio di Godolia, figlio di Amaria, figlio di Ezechia, al tempo di Giosia, figlio di Amon, re di Giuda."],
[1002,"\"Tutto farò sparire dalla terra. Oracolo del Signore."],
[1003,"Distruggerò uomini e bestie; distruggerò gli uccelli del cielo e i pesci del mare, farò inciampare i malvagi, eliminerò l'uomo dalla terra. Oracolo del Signore."],
[1004,"Stenderò la mano su Giuda e su tutti gli abitanti di Gerusalemme; eliminerò da questo luogo quello che resta di Baal e il nome degli addetti ai culti insieme ai sacerdoti,"],
[1005,"quelli che sui tetti si prostrano davanti all'esercito celeste e quelli che si prostrano giurando per il Signore, e poi giurano per Milcom,"],
[1006,"quelli che si allontanano dal seguire il Signore, che non lo cercano né lo consultano\"."],
[1007,"Silenzio, alla presenza del Signore Dio, perché il giorno del Signore è vicino, perché il Signore ha preparato un sacrificio, ha purificato i suoi invitati."],
[1008,"\"Nel giorno del sacrificio del Signore, io punirò i capi e i figli di re e quanti vestono alla moda straniera;"],
[1009,"punirò in quel giorno chiunque salta la soglia, chi riempie di rapine e di frodi il palazzo del suo padrone."],
[1010,"In quel giorno - oracolo del Signore - grida d'aiuto verranno dalla porta dei Pesci, ululati dal quartiere nuovo e grande fragore dai colli."],
[1011,"Urlate, abitanti del Mortaio, poiché tutta la turba dei mercanti è finita, tutti i pesatori dell'argento sono sterminati."],
[1012,"In quel tempo perlustrerò Gerusalemme con lanterne e farò giustizia di quegli uomini che, riposando come vino sulla feccia, pensano: \"Il Signore non fa né bene né male\"."],
[1013,"I loro beni saranno saccheggiati e le loro case distrutte. Costruiranno case ma non le abiteranno, pianteranno viti, ma non ne berranno il vino\"."],
[1014,"È vicino il grande giorno del Signore, è vicino e avanza a grandi passi. Una voce: \"Amaro è il giorno del Signore!\". Anche un prode lo grida."],
[1015,"Giorno d'ira quel giorno, giorno di angoscia e di afflizione, giorno di rovina e di sterminio, giorno di tenebra e di oscurità, e giorno di nube e di caligine,"],
[1016,"giorno di suono di corno e di grido di guerra sulle città fortificate e sulle torri elevate."],
[1017,"Metterò gli uomini in angoscia e cammineranno come ciechi, perché hanno peccato contro il Signore; il loro sangue sarà sparso come polvere e la loro carne come escrementi."],
[1018,"Neppure il loro argento, neppure il loro oro potranno salvarli. Nel giorno dell'ira del Signore e al fuoco della sua gelosia tutta la terra sarà consumata, poiché farà improvvisa distruzione di tutti gli abitanti della terra."],
[2001,"Radunatevi, raccoglietevi, o gente spudorata,"],
[2002,"prima che esca il decreto, prima che passi il giorno come pula, prima che piombi su di voi l'ira furiosa del Signore, prima che piombi su di voi il giorno dell'ira del Signore."],
[2003,"Cercate il Signore voi tutti, poveri della terra, che eseguite i suoi ordini, cercate la giustizia, cercate l'umiltà; forse potrete trovarvi al riparo nel giorno dell'ira del Signore."],
[2004,"Gaza infatti sarà abbandonata e Àscalon ridotta a un deserto. Asdod in pieno giorno sarà deportata ed Ekron distrutta dalle fondamenta."],
[2005,"Guai agli abitanti della costa del mare, alla nazione dei Cretei! La parola del Signore è contro di te, Canaan, paese dei Filistei: \"Io ti distruggerò privandoti di ogni abitante\"."],
[2006,"La costa del mare diventerà pascoli, prati per i pastori, recinti per le greggi."],
[2007,"La costa del mare apparterrà al resto della casa di Giuda; in quei luoghi pascoleranno e a sera nelle case di Àscalon prenderanno riposo, quando il Signore, loro Dio, li avrà visitati e avrà ristabilito le loro sorti."],
[2008,"\"Ho udito l'insulto di Moab e gli oltraggi degli Ammoniti, con i quali hanno insultato il mio popolo gloriandosi del suo territorio."],
[2009,"Perciò, com'è vero che io vivo - oracolo del Signore degli eserciti, Dio d'Israele -, Moab diventerà come Sodoma e gli Ammoniti come Gomorra: un luogo invaso dai cardi, una cava di sale, un deserto per sempre. I rimasti del mio popolo li saccheggeranno e i superstiti della mia gente ne saranno gli eredi\"."],
[2010,"Questo accadrà a loro per la loro superbia, perché hanno insultato, hanno disprezzato il popolo del Signore degli eserciti."],
[2011,"Terribile sarà il Signore con loro, poiché annienterà tutti gli dei della terra, mentre a lui si prostreranno, ognuna sul proprio suolo, tutte le isole delle nazioni."],
[2012,"\"Anche voi, Etiopi, sarete trafitti dalla mia spada\"."],
[2013,"Stenderà la mano anche al settentrione e distruggerà Assur, farà di Ninive una desolazione, arida come il deserto."],
[2014,"Si accovacceranno in mezzo ad essa, a frotte, tutti gli animali del branco. Anche il gufo, anche la civetta si appollaieranno sui suoi capitelli; ne risuonerà la voce dalle finestre e vi sarà desolazione sulla soglia, perché la casa di cedro è stata spogliata."],
[2015,"Questa è la città gaudente, che se ne stava sicura e pensava: \"Io e nessun altro\"! Come mai è diventata un deserto, un rifugio di animali? Chiunque le passa vicino fischia di scherno e agita la mano."],
[3001,"Guai alla città ribelle e impura, alla città che opprime!"],
[3002,"Non ha ascoltato la voce, non ha accettato la correzione. Non ha confidato nel Signore, non si è rivolta al suo Dio."],
[3003,"I suoi capi in mezzo ad essa sono leoni ruggenti, i suoi giudici sono lupi di sera, che non hanno rosicchiato al mattino."],
[3004,"I suoi profeti sono boriosi, uomini fraudolenti. I suoi sacerdoti profanano le cose sacre, violano la legge."],
[3005,"In mezzo ad essa il Signore è giusto, non commette iniquità; ogni mattino dà il suo giudizio, come la luce che non viene mai meno, ma l'iniquo non conosce vergogna."],
[3006,"\"Ho eliminato le nazioni, le loro torri sono state distrutte; ho reso deserte le loro strade, non c'è neppure un passante, sono state devastate le loro città e nessuno le abita più."],
[3007,"Io pensavo: \"Almeno ora mi temerà, accoglierà la correzione! Così la sua abitazione non sarà colpita da tutte le punizioni che le avevo inflitto\". Ma invece si sono affrettati a pervertire di nuovo ogni loro azione."],
[3008,"Perciò aspettatemi  - oracolo del Signore - quando mi leverò per accusare, perché ho decretato di radunare le nazioni, di convocare i regni, per riversare su di loro la mia collera, tutta la mia ira ardente; poiché dal fuoco della mia gelosia sarà consumata tutta la terra."],
[3009,"Allora io darò ai popoli un labbro puro, perché invochino tutti il nome del Signore e lo servano tutti sotto lo stesso giogo."],
[3010,"Da oltre i fiumi di Etiopia coloro che mi pregano, tutti quelli che ho disperso, mi porteranno offerte."],
[3011,"In quel giorno non avrai vergogna di tutti i misfatti commessi contro di me, perché allora allontanerò da te tutti i superbi gaudenti, e tu cesserai di inorgoglirti sopra il mio santo monte."],
[3012,"Lascerò in mezzo a te un popolo umile e povero\". Confiderà nel nome del Signore"],
[3013,"il resto d'Israele. Non commetteranno più iniquità e non proferiranno menzogna; non si troverà più nella loro bocca una lingua fraudolenta. Potranno pascolare e riposare senza che alcuno li molesti."],
[3014,"Rallegrati, figlia di Sion, grida di gioia, Israele, esulta e acclama con tutto il cuore, figlia di Gerusalemme!"],
[3015,"Il Signore ha revocato la tua condanna, ha disperso il tuo nemico. Re d'Israele è il Signore in mezzo a te, tu non temerai più alcuna sventura."],
[3016,"In quel giorno si dirà a Gerusalemme: \"Non temere, Sion, non lasciarti cadere le braccia!"],
[3017,"Il Signore, tuo Dio, in mezzo a te è un salvatore potente. Gioirà per te, ti rinnoverà con il suo amore, esulterà per te con grida di gioia\"."],
[3018,"\"Io raccoglierò gli afflitti, privati delle feste e lontani da te. Sono la vergogna che grava su di te."],
[3019,"Ecco, in quel tempo io mi occuperò di tutti i tuoi oppressori. Soccorrerò gli zoppicanti, radunerò i dispersi, li farò oggetto di lode e di fama dovunque sulla terra sono stati oggetto di vergogna."],
[3020,"In quel tempo io vi guiderò, in quel tempo vi radunerò e vi darò fama e lode fra tutti i popoli della terra, quando, davanti ai vostri occhi, ristabilirò le vostre sorti\", dice il Signore."]
])
