Bib.ret([
[1001,"Libro della storia di Tobi, figlio di Tobiel, figlio di Ananiel, figlio di Aduel, figlio di Gabael, figlio di Raffaele, figlio di Raguele, della discendenza di Asiel, della tribù di Neftali."],
[1002,"Al tempo di Salmanassar, re degli Assiri, egli fu deportato dalla città di Tisbe, che sta a sud di Kedes di Neftali, nell'alta Galilea, sopra Asor, verso occidente, a nord di Sefet."],
[1003,"Io, Tobi, passavo tutti i giorni della mia vita seguendo le vie della verità e della giustizia. Ai miei fratelli e ai miei compatrioti, che erano stati condotti con me in prigionia a Ninive, nel paese degli Assiri, facevo molte elemosine."],
[1004,"Mi trovavo ancora al mio paese, la terra d'Israele, ed ero ancora giovane, quando la tribù del mio antenato Neftali abbandonò la casa di Davide e si staccò da Gerusalemme, la sola città fra tutte le tribù d'Israele scelta per i sacrifici. In essa era stato consacrato il tempio, dove abita Dio, ed era stato edificato per tutte le generazioni future."],
[1005,"Tutti i miei fratelli e quelli della tribù del mio antenato Neftali facevano sacrifici su tutti i monti della Galilea al vitello che Geroboamo, re d'Israele, aveva fabbricato a Dan."],
[1006,"Io ero il solo che spesso mi recavo a Gerusalemme nelle feste, per obbedienza a una legge perenne prescritta a tutto Israele. Correvo a Gerusalemme con le primizie dei frutti e degli animali, con le decime del bestiame e con la prima lana che tosavo alle mie pecore."],
[1007,"Consegnavo tutto ai sacerdoti, figli di Aronne, per l'altare. Davo anche ai leviti, che prestavano servizio a Gerusalemme, le decime del grano, del vino, dell'olio, delle melagrane, dei fichi e degli altri frutti. Per sei anni consecutivi convertivo in denaro la seconda decima ogni anno e andavo a spenderla a Gerusalemme."],
[1008,"La terza decima poi era per gli orfani, le vedove e i forestieri che si trovavano con gli Israeliti. La portavo loro ogni tre anni e la si consumava insieme, come vuole la legge di Mosè e secondo le raccomandazioni di Debora, moglie di Ananiel, la madre di nostro padre, poiché mio padre, morendo, mi aveva lasciato orfano."],
[1009,"Quando divenni adulto, sposai Anna, una donna della mia parentela, e da essa ebbi un figlio che chiamai Tobia."],
[1010,"Dopo la deportazione in Assiria, quando fui condotto prigioniero e arrivai a Ninive, tutti i miei fratelli e quelli della mia gente mangiavano i cibi dei pagani;"],
[1011,"ma io mi guardai bene dal farlo."],
[1012,"Poiché restai fedele a Dio con tutto il cuore,"],
[1013,"l'Altissimo mi fece trovare il favore di Salmanassar, del quale presi a trattare gli affari."],
[1014,"Venni così nella Media, dove, finché egli visse, conclusi affari per conto suo. Fu allora che a Rage di Media, presso Gabael, fratello di Gabri, depositai in sacchetti la somma di dieci talenti d'argento."],
[1015,"Quando Salmanassar morì, gli successe il figlio Sennacherib. Allora le strade della Media divennero impraticabili e non potei più tornarvi."],
[1016,"Al tempo di Salmanassar facevo spesso l'elemosina a quelli della mia gente;"],
[1017,"davo il pane agli affamati, gli abiti agli ignudi e, se vedevo qualcuno dei miei connazionali morto e gettato dietro le mura di Ninive, io lo seppellivo."],
[1018,"Seppellii anche quelli che aveva ucciso Sennacherib, quando tornò fuggendo dalla Giudea, al tempo del castigo mandato dal re del cielo sui bestemmiatori. Nella sua collera egli uccise molti Israeliti; io sottraevo i loro corpi per la sepoltura e Sennacherib invano li cercava."],
[1019,"Ma un cittadino di Ninive andò a informare il re che io li seppellivo di nascosto. Quando seppi che il re conosceva il fatto e che mi si cercava per essere messo a morte, colto da paura mi diedi alla fuga."],
[1020,"I miei beni furono confiscati e passarono tutti al tesoro del re. Mi restò solo la moglie, Anna, con il figlio Tobia."],
[1021,"Neanche quaranta giorni dopo, il re fu ucciso da due suoi figli, i quali poi fuggirono sui monti dell'Ararat. Gli successe allora il figlio Assarhaddon. Egli diede ad Achikar, figlio di mio fratello Anael, l'incarico della contabilità del regno: egli ebbe così la direzione generale degli affari."],
[1022,"Allora Achikar prese a cuore la mia causa e potei così ritornare a Ninive. Al tempo di Sennacherib, re degli Assiri, Achikar era stato gran coppiere, ministro della giustizia, amministratore e sovrintendente della contabilità e Assarhaddon l'aveva mantenuto in carica. Egli era mio nipote e uno della mia parentela."],
[2001,"Sotto il regno di Assarhaddon ritornai dunque a casa mia e mi fu restituita la compagnia di mia moglie Anna e del figlio Tobia. Per la nostra festa di Pentecoste, cioè la festa delle Settimane, avevo fatto preparare un buon pranzo e mi posi a tavola:"],
[2002,"la tavola era imbandita di molte vivande. Dissi al figlio Tobia: \"Figlio mio, va', e se trovi tra i nostri fratelli deportati a Ninive qualche povero, che sia però di cuore fedele, portalo a pranzo insieme con noi. Io resto ad aspettare che tu ritorni, figlio mio\"."],
[2003,"Tobia uscì in cerca di un povero tra i nostri fratelli. Di ritorno disse: \"Padre!\". Gli risposi: \"Ebbene, figlio mio?\". \"Padre - riprese - uno della nostra gente è stato ucciso e gettato nella piazza; l'hanno strangolato un momento fa\"."],
[2004,"Io allora mi alzai, lasciando intatto il pranzo; tolsi l'uomo dalla piazza e lo posi in una camera in attesa del tramonto del sole, per poterlo seppellire."],
[2005,"Ritornai, mi lavai e mangiai con tristezza,"],
[2006,"ricordando le parole del profeta Amos su Betel: \"Si cambieranno le vostre feste in lutto, tutti i vostri canti in lamento\"."],
[2007,"E piansi. Quando poi calò il sole, andai a scavare una fossa e ve lo seppellii."],
[2008,"I miei vicini mi deridevano dicendo: \"Non ha più paura! Proprio per questo motivo lo hanno già ricercato per ucciderlo. È dovuto fuggire e ora eccolo di nuovo a seppellire i morti\"."],
[2009,"Quella notte, dopo aver seppellito il morto, mi lavai, entrai nel mio cortile e mi addormentai sotto il muro del cortile. Per il caldo che c'era tenevo la faccia scoperta,"],
[2010,"ignorando che sopra di me, nel muro, stavano dei passeri. Caddero sui miei occhi i loro escrementi ancora caldi, che mi produssero macchie bianche, e dovetti andare dai medici per la cura. Più essi però mi applicavano farmaci, più mi si oscuravano gli occhi, a causa delle macchie bianche, finché divenni cieco del tutto. Per quattro anni rimasi cieco e ne soffrirono tutti i miei fratelli. Achikar, nei due anni che precedettero la sua partenza per l'Elimaide, provvide al mio sostentamento."],
[2011,"In quel tempo mia moglie Anna lavorava a domicilio,"],
[2012,"tessendo la lana che rimandava poi ai padroni, ricevendone la paga. Ora nel settimo giorno del mese di Distro, quando tagliò il pezzo che aveva tessuto e lo mandò ai padroni, essi, oltre la mercede completa, le fecero dono di un capretto da mangiare."],
[2013,"Quando il capretto entrò in casa mia, si mise a belare. Chiamai allora mia moglie e le dissi: \"Da dove viene questo capretto? Non sarà stato rubato? Restituiscilo ai padroni, poiché non abbiamo nessun diritto di mangiare una cosa rubata\"."],
[2014,"Ella mi disse: \"Mi è stato dato in più del salario\". Ma io non le credevo e le ripetevo di restituirlo ai padroni e per questo mi vergognavo di lei. Allora per tutta risposta mi disse: \"Dove sono le tue elemosine? Dove sono le tue buone opere? Ecco, lo si vede bene da come sei ridotto!\"."],
[3001,"Con l'animo affranto dal dolore, sospirai e piansi. Poi iniziai questa preghiera di lamento:"],
[3002,"\"Tu sei giusto, Signore, e giuste sono tutte le tue opere. Ogni tua via è misericordia e verità. Tu sei il giudice del mondo."],
[3003,"Ora, Signore, ricordati di me e guardami. Non punirmi per i miei peccati e per gli errori miei e dei miei padri."],
[3004,"Violando i tuoi comandamenti, abbiamo peccato davanti a te. Ci hai consegnato al saccheggio; ci hai abbandonato alla prigionia, alla morte e ad essere la favola, lo scherno, il disprezzo di tutte le genti, tra le quali ci hai dispersi."],
[3005,"Ora, quando mi tratti secondo le colpe mie e dei miei padri, veri sono tutti i tuoi giudizi, perché non abbiamo osservato i tuoi comandamenti, camminando davanti a te nella verità."],
[3006,"Agisci pure ora come meglio ti piace; da' ordine che venga presa la mia vita, in modo che io sia tolto dalla terra e divenga terra, poiché per me è preferibile la morte alla vita. Gli insulti bugiardi che mi tocca sentire destano in me grande dolore. Signore, comanda che sia liberato da questa prova; fa' che io parta verso la dimora eterna. Signore, non distogliere da me il tuo volto. Per me infatti è meglio morire che vedermi davanti questa grande angoscia, e così non sentirmi più insultare!\"."],
[3007,"Nello stesso giorno a Sara, figlia di Raguele, abitante di Ecbatana, nella Media, capitò di sentirsi insultare da parte di una serva di suo padre,"],
[3008,"poiché lei era stata data in moglie a sette uomini, ma Asmodeo, il cattivo demonio, glieli aveva uccisi, prima che potessero unirsi con lei come si fa con le mogli. A lei appunto disse la serva: \"Sei proprio tu che uccidi i tuoi mariti. Ecco, sei già stata data a sette mariti e neppure di uno hai potuto portare il nome."],
[3009,"Perché vorresti colpire noi, se i tuoi mariti sono morti? Vattene con loro e che da te non dobbiamo mai vedere né figlio né figlia\"."],
[3010,"In quel giorno dunque ella soffrì molto, pianse e salì nella stanza del padre con l'intenzione di impiccarsi. Ma, tornando a riflettere, pensava: \"Che non insultino mio padre e non gli dicano: \"La sola figlia che avevi, a te assai cara, si è impiccata per le sue sventure\". Così farei precipitare con angoscia la vecchiaia di mio padre negli inferi. Meglio per me che non mi impicchi, ma supplichi il Signore di farmi morire per non sentire più insulti nella mia vita\"."],
[3011,"In quel momento stese le mani verso la finestra e pregò: \"Benedetto sei tu, Dio misericordioso, e benedetto è il tuo nome nei secoli. Ti benedicano tutte le tue opere per sempre."],
[3012,"Ora a te innalzo il mio volto e i miei occhi."],
[3013,"Comanda che io sia tolta dalla terra, perché non debba sentire più insulti."],
[3014,"Tu sai, Signore, che sono pura da ogni contatto con un uomo"],
[3015,"e che non ho disonorato il mio nome né quello di mio padre nella terra dell'esilio. Io sono l'unica figlia di mio padre. Egli non ha altri figli che possano ereditare, né un fratello vicino né un parente per il quale io possa serbarmi come sposa. Già sette mariti ho perduto: perché dovrei vivere ancora? Se tu non vuoi che io muoia, guarda a me con benevolenza: che io non senta più insulti\"."],
[3016,"In quel medesimo momento la preghiera di ambedue fu accolta davanti alla gloria di Dio"],
[3017,"e fu mandato Raffaele a guarire tutti e due: a togliere le macchie bianche dagli occhi di Tobi, perché con gli occhi vedesse la luce di Dio, e a dare Sara, figlia di Raguele, in sposa a Tobia, figlio di Tobi, e così scacciare da lei il cattivo demonio Asmodeo. Di diritto, infatti, spettava a Tobia prenderla in sposa, prima che a tutti gli altri pretendenti. Proprio allora Tobi rientrava in casa dal cortile e Sara, figlia di Raguele, stava scendendo dalla camera."],
[4001,"In quel giorno Tobi si ricordò del denaro che aveva depositato presso Gabael a Rage di Media"],
[4002,"e disse in cuor suo: \"Ecco che io ho invocato la morte: perché dunque non dovrei chiamare mio figlio Tobia e informarlo, prima di morire, di questa somma di denaro?\"."],
[4003,"Chiamò il figlio e gli disse: \"Figlio, quando morirò, dovrai darmi una sepoltura decorosa; onora tua madre e non abbandonarla per tutti i giorni della sua vita; fa' ciò che è di suo gradimento e non procurarle nessun motivo di tristezza."],
[4004,"Ricordati, figlio, che ha corso tanti pericoli per te, quando eri nel suo seno. Quando morirà, dovrai darle sepoltura presso di me, in una medesima tomba."],
[4005,"Ogni giorno, o figlio, ricordati del Signore; non peccare né trasgredire i suoi comandamenti. Compi opere buone in tutti i giorni della tua vita e non metterti per la strada dell'ingiustizia."],
[4006,"Perché se agirai con rettitudine, avrai fortuna nelle tue azioni."],
[4007,"A tutti quelli che praticano la giustizia fa' elemosina con i tuoi beni e, nel fare elemosina, il tuo occhio non abbia rimpianti. Non distogliere lo sguardo da ogni povero e Dio non distoglierà da te il suo."],
[4008,"In proporzione a quanto possiedi fa' elemosina, secondo le tue disponibilità; se hai poco, non esitare a fare elemosina secondo quel poco."],
[4009,"Così ti preparerai un bel tesoro per il giorno del bisogno,"],
[4010,"poiché l'elemosina libera dalla morte e impedisce di entrare nelle tenebre."],
[4011,"Infatti per tutti quelli che la compiono, l'elemosina è un dono prezioso davanti all'Altissimo."],
[4012,"Guardati, o figlio, da ogni sorta di fornicazione; prenditi anzitutto una moglie dalla stirpe dei tuoi padri, non prendere una donna straniera, che cioè non sia della stirpe di tuo padre, perché noi siamo figli di profeti. Ricordati di Noè, di Abramo, di Isacco e di Giacobbe, nostri padri fin da principio. Essi sposarono tutti una donna della loro parentela e furono benedetti nei loro figli e la loro discendenza avrà in eredità la terra."],
[4013,"E ora, figlio, ama i tuoi fratelli; nel tuo cuore non concepire disprezzo per i tuoi fratelli, e per i figli e le figlie del tuo popolo, e tra loro scegliti la moglie. L'orgoglio infatti è causa di rovina e di grande inquietudine. Nella pigrizia vi è povertà e miseria, perché la pigrizia è madre della fame."],
[4014,"Non trattenere presso di te la paga di chi lavora per te, ma a lui consegnala subito; se così avrai servito Dio, ti sarà data la ricompensa. Poni attenzione, o figlio, a tutto ciò che fai e sii ben educato in ogni tuo comportamento."],
[4015,"Non fare a nessuno ciò che non piace a te. Non bere vino fino all'ebbrezza e non avere per compagna del tuo viaggio l'ubriachezza."],
[4016,"Da' del tuo pane a chi ha fame e fa' parte dei tuoi vestiti agli ignudi. Da' in elemosina quanto ti avanza e quando fai elemosina il tuo occhio non abbia rimpianti."],
[4017,"Deponi il tuo pane sulla tomba dei giusti, non darne invece ai peccatori."],
[4018,"Chiedi consiglio a ogni persona che sia saggia e non disprezzare nessun buon consiglio."],
[4019,"In ogni circostanza benedici il Signore Dio e domanda che ti sia guida nelle tue vie e che i tuoi sentieri e i tuoi desideri giungano a buon fine, poiché nessun popolo possiede la saggezza, ma è il Signore che elargisce ogni bene e abbassa chi vuole fino al profondo degli inferi. E ora, figlio, ricordati di questi comandamenti, non lasciare che si cancellino dal tuo cuore."],
[4020,"Ora, figlio, ti comunico che ho depositato dieci talenti d'argento presso Gabael, figlio di Gabri, a Rage di Media."],
[4021,"Non temere, figlio, se siamo diventati poveri. Tu hai una grande ricchezza se avrai il timore di Dio, se rifuggirai da ogni peccato e farai ciò che piace al Signore, tuo Dio\"."],
[5001,"Allora Tobia rispose al padre: \"Quanto mi hai comandato io farò, o padre."],
[5002,"Ma come potrò riprendere la somma, dal momento che lui non conosce me, né io conosco lui? Che segno posso dargli, perché mi riconosca, mi creda e mi consegni il denaro? Inoltre non sono pratico delle strade da prendere per andare in Media\"."],
[5003,"Rispose Tobi a suo figlio Tobia: \"Mi ha dato un documento autografo e anch'io gli ho apposto il mio autografo: lo divisi in due parti e ne prendemmo ciascuno una parte; la sua parte la lasciai presso di lui con il denaro. Sono ora vent'anni da quando ho depositato quella somma. Cercati dunque, o figlio, un uomo di fiducia che si metta in viaggio con te. Lo pagheremo per tutto il tempo fino al tuo ritorno. Va' dunque da Gabael a ritirare il denaro\"."],
[5004,"Uscì Tobia in cerca di qualcuno pratico della strada, che lo accompagnasse nella Media. Uscì e si trovò davanti l'angelo Raffaele, non sospettando minimamente che fosse un angelo di Dio."],
[5005,"Gli disse: \"Di dove sei, o giovane?\". Rispose: \"Sono uno dei tuoi fratelli Israeliti, e sono venuto qui a cercare lavoro\". Riprese Tobia: \"Conosci la strada per andare nella Media?\"."],
[5006,"Gli disse: \"Certo, parecchie volte sono stato là e conosco bene tutte le strade. Spesso sono andato nella Media e ho alloggiato presso Gabael, un nostro fratello che abita a Rage di Media. Ci sono due giorni di cammino da Ecbatana a Rage. Rage è sulle montagne ed Ecbatana è nella pianura\"."],
[5007,"Allora Tobia gli disse: \"Aspetta, o giovane, che vada ad avvertire mio padre. Ho bisogno che tu venga con me e ti pagherò il tuo salario\"."],
[5008,"Gli rispose: \"Ecco, ti attendo; però non tardare\"."],
[5009,"Tobia andò ad informare suo padre Tobi dicendogli: \"Ecco, ho trovato un uomo tra i nostri fratelli Israeliti\". Gli rispose: \"Chiamalo, perché io sappia di che famiglia e di che tribù è e se è persona fidata per venire con te, o figlio\"."],
[5010,"Tobia uscì a chiamarlo e gli disse: \"O giovane, mio padre ti chiama\". Entrò da lui. Tobi lo salutò per primo e l'altro gli disse: \"Possa tu avere molta gioia!\". Tobi rispose: \"Che gioia posso ancora avere? Sono un uomo menomato negli occhi; non vedo la luce del cielo, ma mi trovo nell'oscurità come i morti che non contemplano più la luce. Pur vivendo, mi sento tra i morti; avverto la voce degli uomini, ma non li vedo\". Gli rispose: \"Fatti coraggio, Dio non tarderà a guarirti; fatti coraggio!\". E Tobi: \"Mio figlio Tobia vuole andare nella Media. Non potresti andare con lui e fargli da guida? Io ti pagherò, fratello!\". Rispose: \"Sì, posso accompagnarlo; conosco tutte le strade. Mi sono recato spesso nella Media. Ho attraversato tutte le sue pianure e i suoi monti e ne conosco tutte le strade\"."],
[5011,"Tobi gli disse: \"Fratello, di che famiglia e di che tribù sei? Dimmelo, fratello\"."],
[5012,"Ed egli: \"Che t'importa la tribù?\". L'altro gli disse: \"Voglio sapere con verità, fratello, di chi tu sei figlio e il tuo vero nome\"."],
[5013,"Rispose: \"Sono Azaria, figlio di Anania il grande, uno dei tuoi fratelli\"."],
[5014,"Gli disse allora: \"Sii benvenuto e in buona salute, o fratello! Non avertene a male, fratello, se ho voluto sapere la verità sulla tua famiglia. Tu dunque sei mio parente, di buona e distinta discendenza! Conoscevo Anania e Natan, i due figli di Semeia il grande. Venivano con me a Gerusalemme e là facevano adorazione insieme con me; non hanno abbandonato la retta via. I tuoi fratelli sono brava gente; tu sei di buona radice: sii benvenuto!\"."],
[5015,"Continuò: \"Ti do come ricompensa una dracma al giorno, e per quanto riguarda il tuo mantenimento lo stesso che a mio figlio."],
[5016,"Fa' dunque il viaggio con mio figlio e poi ti darò ancora qualcosa di più\"."],
[5017,"Gli disse: \"Farò il viaggio con lui. Non temere: partiremo sani, e sani ritorneremo da te, perché la strada è sicura\". Tobi gli disse: \"Sia con te la benedizione, o fratello!\". Si rivolse poi al figlio e gli disse: \"Figlio, prepara quanto occorre per il viaggio e parti con questo tuo fratello. Dio, che è nei cieli, vi conservi sani fin là e vi restituisca a me sani e salvi; il suo angelo vi accompagni e vi conduca a salvezza, o figlio!\". Tobia uscì per mettersi in cammino e baciò il padre e la madre. E Tobi gli disse: \"Fa' buon viaggio!\"."],
[5018,"Allora la madre si mise a piangere e disse a Tobi: \"Perché hai voluto che mio figlio partisse? Non è lui il bastone della nostra mano, che è sempre stato in casa con noi?"],
[5019,"Non temere di aggiungere denaro a denaro; esso non vale nulla in confronto a nostro figlio."],
[5020,"Quello che per vivere ci è stato dato dal Signore è sufficiente per noi\"."],
[5021,"Le disse: \"Non stare in pensiero: nostro figlio farà buon viaggio e tornerà in buona salute da noi. I tuoi occhi lo vedranno il giorno in cui tornerà sano e salvo da te."],
[5022,"Non stare in pensiero, non temere per loro, o sorella. Un angelo buono infatti lo accompagnerà, il suo viaggio andrà bene e tornerà sano e salvo\"."],
[5023,"Ed ella cessò di piangere."],
[6001,"Il giovane partì insieme con l'angelo, e anche il cane li seguì e s'avviò con loro. Camminarono insieme finché li sorprese la prima sera; allora si fermarono a passare la notte sul fiume Tigri."],
[6002,"Il giovane scese nel fiume per lavarsi i piedi, quand'ecco un grosso pesce balzando dall'acqua tentò di divorare il piede del ragazzo, che si mise a gridare."],
[6003,"Ma l'angelo gli disse: \"Afferra il pesce e non lasciarlo fuggire\". Il ragazzo riuscì ad afferrare il pesce e a tirarlo a riva."],
[6004,"Gli disse allora l'angelo: \"Apri il pesce e togline il fiele, il cuore e il fegato; mettili in disparte ma getta via gli intestini. Infatti il suo fiele, il cuore e il fegato possono essere utili medicamenti\"."],
[6005,"Il ragazzo squartò il pesce, ne tolse il fiele, il cuore e il fegato. Arrostì una porzione del pesce e la mangiò; l'altra parte la mise in serbo dopo averla salata."],
[6006,"Poi ambedue ripresero il viaggio, finché non furono vicini alla Media."],
[6007,"Allora il ragazzo rivolse all'angelo questa domanda: \"Azaria, fratello, che rimedio può esserci nel cuore, nel fegato e nel fiele del pesce?\"."],
[6008,"Gli rispose: \"Quanto al cuore e al fegato, ne puoi fare suffumigi in presenza di una persona, uomo o donna, invasata dal demonio o da uno spirito cattivo, e cesserà da lei ogni vessazione e non ne resterà più traccia alcuna."],
[6009,"Il fiele invece serve per spalmarlo sugli occhi di chi è affetto da macchie bianche; si soffia su quelle macchie e gli occhi guariscono\"."],
[6010,"Erano entrati nella Media e già erano vicini a Ecbatana,"],
[6011,"quando Raffaele disse al ragazzo: \"Fratello Tobia!\". Gli rispose: \"Eccomi\". Riprese: \"Questa notte dobbiamo alloggiare presso Raguele, che è tuo parente. Egli ha una figlia chiamata Sara"],
[6012,"e all'infuori di Sara non ha altro figlio o figlia. A te, come parente più stretto, spetta il diritto di sposarla più di qualunque altro uomo e di avere in eredità i beni di suo padre. È una ragazza saggia, coraggiosa, molto graziosa e suo padre è una brava persona\"."],
[6013,"E aggiunse: \"Tu hai il diritto di sposarla. Ascoltami, fratello: io parlerò della fanciulla al padre questa sera, per serbartela come fidanzata. Quando torneremo dalla città di Rage, celebreremo le sue nozze. So che Raguele non potrà rifiutarla a te o prometterla ad altri; egli incorrerebbe nella morte secondo la prescrizione della legge di Mosè, poiché egli sa che prima di ogni altro spetta a te avere sua figlia. Ascoltami, dunque, fratello. Questa sera parleremo della fanciulla e ne domanderemo la mano. Al nostro ritorno dalla città di Rage la prenderemo e la condurremo con noi a casa tua\"."],
[6014,"Allora Tobia rispose a Raffaele: \"Fratello Azaria, ho sentito dire che ella è già stata data in moglie a sette uomini ed essi sono morti nella stanza nuziale la notte stessa in cui dovevano unirsi a lei. Inoltre ho sentito dire che un demonio le uccide i mariti."],
[6015,"Per questo ho paura; il demonio a lei non fa del male, ma se qualcuno le si vuole accostare, egli lo uccide. Io sono l'unico figlio di mio padre. Ho paura di morire e di condurre così alla tomba la vita di mio padre e di mia madre per l'angoscia della mia perdita. Non hanno un altro figlio che possa seppellirli\"."],
[6016,"Ma quello gli disse: \"Hai forse dimenticato i moniti di tuo padre, che ti ha raccomandato di prendere in moglie una donna del tuo casato? Ascoltami, dunque, o fratello: non preoccuparti di questo demonio e sposala. Sono certo che questa sera ti verrà data in moglie."],
[6017,"Quando però entri nella camera nuziale, prendi il cuore e il fegato del pesce e mettine un poco sulla brace degli incensi. L'odore si spanderà, il demonio lo dovrà annusare e fuggirà per non farsi più vedere in eterno intorno a lei."],
[6018,"Poi, prima di unirti con lei, alzatevi tutti e due a pregare. Supplicate il Signore del cielo perché venga su di voi la sua grazia e la sua salvezza. Non temere: ella ti è stata destinata fin dall'eternità. Sarai tu a salvarla. Ella verrà con te e penso che da lei avrai figli che saranno per te come fratelli. Non stare in pensiero\"."],
[6019,"Quando Tobia sentì le parole di Raffaele e seppe che Sara era sua parente, della stirpe della famiglia di suo padre, l'amò molto senza poter più distogliere il suo cuore da lei."],
[7001,"Quando fu entrato in Ecbatana, Tobia disse: \"Fratello Azaria, conducimi diritto dal nostro fratello Raguele\". Egli lo condusse alla casa di Raguele, che trovarono seduto presso la porta del cortile. Lo salutarono per primi ed egli rispose: \"Salute, fratelli, siate i benvenuti!\". Li fece entrare in casa."],
[7002,"Disse a sua moglie Edna: \"Quanto somiglia questo giovane a mio fratello Tobi!\"."],
[7003,"Edna domandò loro: \"Di dove siete, fratelli?\", ed essi risposero: \"Siamo dei figli di Neftali, deportati a Ninive\"."],
[7004,"Disse allora: \"Conoscete nostro fratello Tobi?\". Le dissero: \"Lo conosciamo\"."],
[7005,"Riprese: \"Sta bene?\". Risposero: \"Sta bene e vive\". E Tobia aggiunse: \"È mio padre\"."],
[7006,"Raguele allora balzò in piedi, l'abbracciò e pianse. Poi gli disse: \"Sii benedetto, o figlio! Hai un ottimo padre. Che sventura per un uomo giusto e generoso nel fare elemosine essere diventato cieco!\". Si gettò al collo del parente Tobia e pianse."],
[7007,"Pianse anche sua moglie Edna e pianse anche la loro figlia Sara."],
[7008,"Poi egli macellò un montone del gregge e fece loro una festosa accoglienza."],
[7009,"Si lavarono, fecero le abluzioni e, quando si furono messi a tavola, Tobia disse a Raffaele: \"Fratello Azaria, domanda a Raguele che mi dia in moglie mia cugina Sara\"."],
[7010,"Raguele udì queste parole e disse al giovane: \"Mangia, bevi e sta' allegro per questa sera, poiché nessuno all'infuori di te, mio parente, ha il diritto di prendere mia figlia Sara, come del resto neppure io ho la facoltà di darla a un altro uomo all'infuori di te, poiché tu sei il mio parente più stretto. Però, figlio, voglio dirti con franchezza la verità."],
[7011,"L'ho data a sette mariti, scelti tra i nostri fratelli, e tutti sono morti la notte in cui entravano da lei. Ora, figlio, mangia e bevi; il Signore sarà con voi\"."],
[7012,"Ma Tobia disse: \"Non mangerò affatto né berrò, prima che tu abbia preso una decisione a mio riguardo\". Rispose Raguele: \"Lo farò! Ella ti viene data secondo il decreto del libro di Mosè e come dal cielo è stato stabilito che ti sia data. Abbi cura di lei, d'ora in poi tu sei suo fratello e lei tua sorella. Ti viene concessa da oggi per sempre. Il Signore del cielo vi assista questa notte, o figlio, e vi conceda la sua misericordia e la sua pace\"."],
[7013,"Raguele chiamò sua figlia Sara e, quando venne, la prese per mano e l'affidò a Tobia con queste parole: \"Prendila; secondo la legge e il decreto scritto nel libro di Mosè lei ti viene concessa in moglie. Tienila e, sana e salva, conducila da tuo padre. Il Dio del cielo vi conceda un buon viaggio e pace\"."],
[7014,"Chiamò poi la madre di lei e le disse di portare un foglio e stese l'atto di matrimonio, secondo il quale concedeva in moglie a Tobia la propria figlia, in base al decreto della legge di Mosè. Dopo di ciò cominciarono a mangiare e a bere."],
[7015,"Poi Raguele chiamò sua moglie Edna e le disse: \"Sorella mia, prepara l'altra camera e conducila dentro\"."],
[7016,"Quella andò a preparare il letto della camera, come le aveva ordinato, e vi condusse la figlia. Pianse per lei, poi si asciugò le lacrime e le disse:"],
[7017,"\"Coraggio, figlia, il Signore del cielo cambi in gioia il tuo dolore. Coraggio, figlia!\". E uscì."],
[8001,"Quando ebbero finito di mangiare e di bere, decisero di andare a dormire. Accompagnarono il giovane e lo introdussero nella camera da letto."],
[8002,"Tobia allora si ricordò delle parole di Raffaele: prese dal suo sacco il fegato e il cuore del pesce e li pose sulla brace dell'incenso."],
[8003,"L'odore del pesce respinse il demonio, che fuggì verso le regioni dell'alto Egitto. Raffaele vi si recò all'istante e in quel luogo lo incatenò e lo mise in ceppi."],
[8004,"Gli altri intanto erano usciti e avevano chiuso la porta della camera. Tobia si alzò dal letto e disse a Sara: \"Sorella, alzati! Preghiamo e domandiamo al Signore nostro che ci dia grazia e salvezza\"."],
[8005,"Lei si alzò e si misero a pregare e a chiedere che venisse su di loro la salvezza, dicendo: \"Benedetto sei tu, Dio dei nostri padri, e benedetto per tutte le generazioni è il tuo nome! Ti benedicano i cieli e tutte le creature per tutti i secoli!"],
[8006,"Tu hai creato Adamo e hai creato Eva sua moglie, perché gli fosse di aiuto e di sostegno. Da loro due nacque tutto il genere umano. Tu hai detto: \"Non è cosa buona che l'uomo resti solo; facciamogli un aiuto simile a lui\"."],
[8007,"Ora non per lussuria io prendo questa mia parente, ma con animo retto. Degnati di avere misericordia di me e di lei e di farci giungere insieme alla vecchiaia\"."],
[8008,"E dissero insieme: \"Amen, amen!\"."],
[8009,"Poi dormirono per tutta la notte."],
[8010,"Ma Raguele si alzò; chiamò i suoi servi e andarono a scavare una fossa. Diceva infatti: \"Se mai morisse, non diventeremo così motivo di scherno e di vergogna\"."],
[8011,"Quando ebbero terminato di scavare la fossa, Raguele tornò in casa; chiamò sua moglie"],
[8012,"e le disse: \"Manda una delle serve a vedere se è vivo; così, se è morto, lo seppelliremo senza che nessuno lo sappia\"."],
[8013,"Mandarono quella serva, accesero la lampada e aprirono la porta; quella entrò e trovò che dormivano insieme, immersi nel sonno."],
[8014,"La serva uscì e riferì loro che era vivo e che non era successo nulla di male."],
[8015,"Resero lode al Dio del cielo e dissero: \"Tu sei benedetto, o Dio, degno di ogni benedizione perfetta.  (Ti benedicano per tutti i secoli!"],
[8016,"Tu sei benedetto, perché mi hai ricolmato di gioia e non è avvenuto ciò che temevo, ma ci hai trattato secondo la tua grande misericordia."],
[8017,"Tu sei benedetto, perché hai avuto compassione dei due figli unici. Concedi loro, Signore, grazia e salvezza e falli giungere fino al termine della loro vita in mezzo alla gioia e alla grazia\"."],
[8018,"Allora ordinò ai servi di riempire la fossa prima che si facesse giorno."],
[8019,"Raguele ordinò alla moglie di fare pane in abbondanza; andò a prendere dalla mandria due vitelli e quattro montoni, li fece macellare e cominciarono così a preparare il banchetto."],
[8020,"Poi chiamò Tobia e gli disse: \"Per quattordici giorni non te ne andrai di qui, ma ti fermerai da me a mangiare e a bere e così allieterai l'anima già tanto afflitta di mia figlia."],
[8021,"Di quanto possiedo prenditi la metà e torna sano e salvo da tuo padre. Quando io e mia moglie saremo morti, anche l'altra metà sarà vostra. Coraggio, figlio! Io sono tuo padre ed Edna è tua madre; noi apparteniamo a te come a questa tua sorella, da ora per sempre. Coraggio, figlio!\"."],
[9001,"Allora Tobia chiamò Raffaele e gli disse:"],
[9002,"\"Fratello Azaria, prendi con te quattro servi e due cammelli e mettiti in viaggio per Rage."],
[9003,"Va' da Gabael, consegnagli il documento, riporta il denaro e conducilo con te alle feste nuziali."],
[9004,"Tu sai infatti che mio padre starà a contare i giorni e, se tarderò anche di un solo giorno, lo farò soffrire troppo. Vedi bene che cosa ha giurato Raguele e io non posso trasgredire il suo giuramento\"."],
[9005,"Partì dunque Raffaele con quattro servi e due cammelli per Rage di Media, dove presero alloggio da Gabael. Raffaele gli presentò il documento e nello stesso tempo lo informò che Tobia, figlio di Tobi, aveva preso moglie e lo invitava alle nozze. Gabael andò subito a prendere i sacchetti, ancora sigillati, e li contò in sua presenza; poi li caricarono."],
[9006,"Partirono insieme di buon mattino per andare alle nozze. Giunti da Raguele, trovarono Tobia adagiato a tavola. Egli si alzò in piedi a salutarlo e Gabael pianse e lo benedisse dicendogli: \"Figlio ottimo di ottimo padre, giusto e generoso in elemosine, conceda il Signore la benedizione del cielo a te, a tua moglie, al padre e alla madre di tua moglie. Benedetto Dio, poiché ho visto mio cugino Tobi, vedendo te che tanto gli somigli!\"."],
[10001,"Frattanto ogni giorno Tobi contava le giornate, quante erano necessarie all'andata e quante al ritorno. Quando poi i giorni furono al termine e il figlio non era ancora tornato,"],
[10002,"pensò: \"Che sia stato trattenuto là? O che sia morto Gabael e non c'è nessuno che gli dia il denaro?\"."],
[10003,"E cominciò a rattristarsi."],
[10004,"Sua moglie Anna diceva: \"Mio figlio è morto e non è più tra i vivi\". E cominciò a piangere e a lamentarsi sul proprio figlio, dicendo:"],
[10005,"\"Ahimè, figlio, ti ho lasciato partire, tu che eri la luce dei miei occhi!\"."],
[10006,"Le rispondeva Tobi: \"Taci, non stare in pensiero, sorella; egli sta bene. Certo li trattiene là qualche fatto imprevisto. Del resto l'uomo che lo accompagnava è sicuro ed è uno dei nostri fratelli. Non affliggerti per lui, sorella; tra poco sarà qui\"."],
[10007,"Ma lei replicava: \"Lasciami stare e non ingannarmi! Mio figlio è morto\". E subito usciva e osservava la strada per la quale era partito suo figlio; così faceva ogni giorno e non si fidava di nessuno. Quando il sole era tramontato, rientrava a piangere e a lamentarsi per tutta la notte e non prendeva sonno."],
[10008,"Compiuti i quattordici giorni delle feste nuziali, quelli che Raguele con giuramento aveva stabilito di organizzare per la propria figlia, Tobia andò da lui e gli disse: \"Lasciami partire. Sono certo che mio padre e mia madre non hanno più speranza di rivedermi. Ti prego dunque, o padre, di volermi congedare, perché possa tornare da mio padre. Già ti ho spiegato in quale condizione l'ho lasciato\"."],
[10009,"Rispose Raguele a Tobia: \"Resta, figlio, resta con me. Manderò messaggeri a tuo padre Tobi, perché gli portino tue notizie\". Ma egli disse: \"No, ti prego di lasciarmi andare da mio padre\"."],
[10010,"Allora Raguele, alzatosi, consegnò a Tobia la sposa Sara con metà dei suoi beni, servi e serve, buoi e pecore, asini e cammelli, vesti, denaro e suppellettili."],
[10011,"Li congedò in buona salute. A lui poi rivolse questo saluto: \"Sta' sano, figlio, e fa' buon viaggio! Il Signore del cielo vi assista, te e tua moglie Sara, e possa io vedere i vostri figli prima di morire\"."],
[10012,"Poi disse a Sara sua figlia: \"Va' dai tuoi suoceri, poiché da questo momento essi sono i tuoi genitori, come coloro che ti hanno dato la vita. Va' in pace, figlia, e possa sentire buone notizie a tuo riguardo, finché sarò in vita\". Dopo averli salutati, li congedò."],
[10013,"Edna disse a Tobia: \"Figlio e fratello carissimo, il Signore ti riconduca a casa e possa io vedere i figli tuoi e di Sara, mia figlia, prima di morire. Davanti al Signore ti affido mia figlia in custodia. Non farla soffrire in nessun giorno della tua vita. Figlio, va' in pace. D'ora in avanti io sono tua madre e Sara è tua sorella. Possiamo tutti insieme avere buona fortuna per tutti i giorni della nostra vita\". Li baciò tutti e due e li congedò sani e salvi."],
[10014,"Allora Tobia partì da Raguele in buona salute e lieto, benedicendo il Signore del cielo e della terra, il re dell'universo, perché aveva dato buon esito al suo viaggio. Raguele gli disse: \"Possa tu avere la fortuna di onorare i tuoi genitori tutti i giorni della loro vita\"."],
[11001,"Quando furono nei pressi di Kaserin, di fronte a Ninive, Raffaele disse:"],
[11002,"\"Tu sai in quale condizione abbiamo lasciato tuo padre."],
[11003,"Corriamo avanti, prima di tua moglie, e prepariamo la casa, mentre gli altri vengono\"."],
[11004,"E s'incamminarono tutti e due insieme. Poi Raffaele gli disse: \"Prendi in mano il fiele\". Il cane, che aveva accompagnato lui e Tobia, li seguiva."],
[11005,"Anna intanto sedeva scrutando la strada per la quale era partito il figlio."],
[11006,"Quando si accorse che stava arrivando, disse al padre di lui: \"Ecco, sta tornando tuo figlio con l'uomo che l'accompagnava\"."],
[11007,"Raffaele disse a Tobia, prima che si avvicinasse al padre: \"Io so che i suoi occhi si apriranno."],
[11008,"Spalma il fiele del pesce sui suoi occhi; il farmaco intaccherà e asporterà come scaglie le macchie bianche dai suoi occhi. Così tuo padre riavrà la vista e vedrà la luce\"."],
[11009,"Anna corse avanti e si gettò al collo di suo figlio dicendogli: \"Ti rivedo, o figlio. Ora posso morire!\". E si mise a piangere."],
[11010,"Tobi si alzò e, incespicando, uscì dalla porta del cortile."],
[11011,"Tobia gli andò incontro, tenendo in mano il fiele del pesce. Soffiò sui suoi occhi e lo trasse vicino, dicendo: \"Coraggio, padre!\". Gli applicò il farmaco e lo lasciò agire,"],
[11012,"poi distaccò con le mani le scaglie bianche dai margini degli occhi."],
[11013,"Tobi gli si buttò al collo e pianse, dicendo: \"Ti vedo, figlio, luce dei miei occhi!\"."],
[11014,"E aggiunse: \"Benedetto Dio! Benedetto il suo grande nome! Benedetti tutti i suoi angeli santi! Sia il suo santo nome su di noi e siano benedetti i suoi angeli per tutti i secoli. Perché egli mi ha colpito, ma ora io contemplo mio figlio Tobia\"."],
[11015,"Tobia entrò in casa lieto, benedicendo Dio con tutta la voce che aveva. Poi Tobia informò suo padre del viaggio che aveva compiuto felicemente, del denaro che aveva riportato, di Sara, figlia di Raguele, che aveva preso in moglie e che stava venendo e si trovava ormai vicina alla porta di Ninive."],
[11016,"Allora Tobi uscì verso la porta di Ninive incontro alla sposa di lui, lieto e benedicendo Dio. La gente di Ninive, vedendolo passare e camminare con tutto il vigore di un tempo, senza che alcuno lo conducesse per mano, fu presa da meraviglia. Tobi proclamava davanti a loro che Dio aveva avuto pietà di lui e che gli aveva aperto gli occhi."],
[11017,"Tobi si avvicinò poi a Sara, la sposa di suo figlio Tobia, e la benedisse dicendole: \"Sii la benvenuta, figlia! Benedetto sia il tuo Dio, che ti ha condotto da noi, figlia! Benedetto sia tuo padre, benedetto mio figlio Tobia e benedetta tu, o figlia! Entra nella casa, che è tua, sana e salva, nella benedizione e nella gioia; entra, o figlia!\"."],
[11018,"Quel giorno fu grande festa per tutti i Giudei di Ninive."],
[11019,"Anche Achikar e Nadab, suoi cugini, vennero a congratularsi con Tobi."],
[12001,"Terminate le feste nuziali, Tobi chiamò suo figlio Tobia e gli disse: \"Figlio mio, pensa a dare la ricompensa dovuta a colui che ti ha accompagnato e ad aggiungere qualcos'altro alla somma pattuita\"."],
[12002,"Gli disse Tobia: \"Padre, quanto dovrò dargli come compenso? Anche se gli dessi la metà dei beni che egli ha portato con me, non ci perderei nulla."],
[12003,"Egli mi ha condotto sano e salvo, ha guarito mia moglie, ha portato con me il denaro, infine ha guarito anche te! Quanto ancora posso dargli come compenso?\"."],
[12004,"Tobi rispose: \"Figlio, è giusto che egli riceva la metà di tutti i beni che ha riportato\"."],
[12005,"Fece dunque venire l'angelo e gli disse: \"Prendi come tuo compenso la metà di tutti i beni che hai riportato e va' in pace\"."],
[12006,"Allora Raffaele li chiamò tutti e due in disparte e disse loro: \"Benedite Dio e proclamate davanti a tutti i viventi il bene che vi ha fatto, perché sia benedetto e celebrato il suo nome. Fate conoscere a tutti gli uomini le opere di Dio, come è giusto, e non esitate a ringraziarlo."],
[12007,"È bene tenere nascosto il segreto del re, ma è motivo di onore manifestare e lodare le opere di Dio. Fate ciò che è bene e non vi colpirà alcun male."],
[12008,"È meglio la preghiera con il digiuno e l'elemosina con la giustizia, che la ricchezza con l'ingiustizia. Meglio praticare l'elemosina che accumulare oro."],
[12009,"L'elemosina salva dalla morte e purifica da ogni peccato. Coloro che fanno l'elemosina godranno lunga vita."],
[12010,"Coloro che commettono il peccato e l'ingiustizia sono nemici di se stessi."],
[12011,"Voglio dirvi tutta la verità, senza nulla nascondervi: vi ho già insegnato che è bene nascondere il segreto del re, mentre è motivo d'onore manifestare le opere di Dio."],
[12012,"Ebbene, quando tu e Sara eravate in preghiera, io presentavo l'attestato della vostra preghiera davanti alla gloria del Signore. Così anche quando tu seppellivi i morti."],
[12013,"Quando poi tu non hai esitato ad alzarti e ad abbandonare il tuo pranzo e sei andato a seppellire quel morto, allora io sono stato inviato per metterti alla prova."],
[12014,"Ma, al tempo stesso, Dio mi ha inviato per guarire te e Sara, tua nuora."],
[12015,"Io sono Raffaele, uno dei sette angeli che sono sempre pronti a entrare alla presenza della gloria del Signore\"."],
[12016,"Allora furono presi da grande timore tutti e due; si prostrarono con la faccia a terra ed ebbero una grande paura."],
[12017,"Ma l'angelo disse loro: \"Non temete: la pace sia con voi. Benedite Dio per tutti i secoli."],
[12018,"Quando ero con voi, io stavo con voi non per bontà mia, ma per la volontà di Dio: lui dovete benedire sempre, a lui cantate inni."],
[12019,"Quando voi mi vedevate mangiare, io non mangiavo affatto: ciò che vedevate era solo apparenza."],
[12020,"Ora benedite il Signore sulla terra e rendete grazie a Dio. Ecco, io ritorno a colui che mi ha mandato. Scrivete tutte queste cose che vi sono accadute\". E salì in alto."],
[12021,"Essi si rialzarono, ma non poterono più vederlo."],
[12022,"Allora andavano benedicendo e celebrando Dio e lo ringraziavano per queste grandi opere, perché era loro apparso l'angelo di Dio."],
[13001,"Allora Tobi disse:"],
[13002,"\"Benedetto Dio che vive in eterno, benedetto il suo regno; egli castiga e ha compassione, fa scendere agli inferi, nelle profondità della terra, e fa risalire dalla grande perdizione: nessuno sfugge alla sua mano."],
[13003,"Lodatelo, figli d'Israele, davanti alle nazioni, perché in mezzo ad esse egli vi ha disperso"],
[13004,"e qui vi ha fatto vedere la sua grandezza; date gloria a lui davanti a ogni vivente, poiché è lui il nostro Signore, il nostro Dio, lui il nostro Padre, Dio per tutti i secoli."],
[13005,"Vi castiga per le vostre iniquità, ma avrà compassione di tutti voi e vi radunerà da tutte le nazioni, fra le quali siete stati dispersi."],
[13006,"Quando vi sarete convertiti a lui  con tutto il cuore e con tutta l'anima per fare ciò che è giusto davanti a lui, allora egli ritornerà a voi e non vi nasconderà più il suo volto."],
[13007,"Ora guardate quello che ha fatto per voi e ringraziatelo con tutta la voce; benedite il Signore che è giusto e date gloria al re dei secoli."],
[13008,"Io gli do lode nel paese del mio esilio e manifesto la sua forza e la sua grandezza a un popolo di peccatori. Convertitevi, o peccatori,  e fate ciò che è giusto davanti a lui; chissà che non torni ad amarvi e ad avere compassione di voi."],
[13009,"Io esalto il mio Dio,  l'anima mia celebra il re del cielo ed esulta per la sua grandezza."],
[13010,"Tutti ne parlino e diano lode a lui in Gerusalemme.  Gerusalemme, città santa, egli ti castiga per le opere dei tuoi figli, ma avrà ancora pietà per i figli dei giusti."],
[13011,"Da' lode degnamente al Signore e benedici il re dei secoli; egli ricostruirà in te il suo tempio con gioia,"],
[13012,"per allietare in te tutti i deportati e per amare in te tutti gli sventurati, per tutte le generazioni future."],
[13013,"Una luce splendida brillerà sino ai confini della terra: nazioni numerose verranno a te da lontano, gli abitanti di tutti i confini della terra verranno verso la dimora del tuo santo nome, portando in mano i doni per il re del cielo. Generazioni e generazioni esprimeranno in te l'esultanza e il nome della città eletta durerà per le generazioni future."],
[13014,"Maledetti tutti quelli che ti insultano! Maledetti tutti quelli che ti distruggono, che demoliscono le tue mura, rovinano le tue torri e incendiano le tue abitazioni! Ma benedetti per sempre tutti quelli che ti temono."],
[13015,"Sorgi ed esulta per i figli dei giusti, tutti presso di te si raduneranno e benediranno il Signore dei secoli. Beati coloro che ti amano, beati coloro che esulteranno per la tua pace."],
[13016,"Beati coloro che avranno pianto per le tue sventure: gioiranno per te e vedranno tutta la tua gioia per sempre. Anima mia, benedici il Signore, il grande re,"],
[13017,"perché Gerusalemme sarà ricostruita come città della sua dimora per sempre. Beato sarò io, se rimarrà un resto della mia discendenza per vedere la tua gloria e dare lode al re del cielo. Le porte di Gerusalemme saranno ricostruite  con zaffiro e con smeraldo e tutte le sue mura con pietre preziose. Le torri di Gerusalemme saranno ricostruite con oro e i loro baluardi con oro purissimo. Le strade di Gerusalemme saranno lastricate con turchese e pietra di Ofir."],
[13018,"Le porte di Gerusalemme risuoneranno di canti di esultanza, e in tutte le sue case canteranno: \"Alleluia! Benedetto il Dio d'Israele e benedetti coloro che benedicono il suo santo nome nei secoli e per sempre!\"\"."],
[14001,"Così Tobi terminò il suo canto di ringraziamento."],
[14002,"Tobi morì in pace all'età di centododici anni e fu sepolto con onore a Ninive. Egli aveva sessantadue anni quando divenne cieco; dopo la sua guarigione visse nella prosperità, praticò l'elemosina e continuò sempre a benedire Dio e a celebrare la sua grandezza."],
[14003,"Quando stava per morire, chiamò il figlio Tobia e gli diede queste istruzioni:"],
[14004,"\"Figlio, porta via i tuoi figli e rifugiati in Media, perché io credo alla parola di Dio che Naum ha pronunciato su Ninive. Tutto dovrà accadere, tutto si realizzerà sull'Assiria e su Ninive, come hanno predetto i profeti d'Israele, inviati da Dio; non una delle loro parole andrà a vuoto. Ogni cosa si realizzerà a suo tempo. Vi sarà maggior sicurezza in Media che in Assiria o in Babilonia. Perché io so e credo che quanto Dio ha detto si compirà e avverrà, e non andrà a vuoto alcuna delle sue parole. I nostri fratelli che abitano il paese d'Israele saranno tutti dispersi e deportati lontano dalla loro amata terra e tutto il paese d'Israele sarà ridotto a un deserto. Anche Samaria e Gerusalemme diventeranno un deserto e il tempio di Dio sarà nell'afflizione e resterà bruciato fino a un certo tempo."],
[14005,"Poi di nuovo Dio avrà pietà di loro e li ricondurrà nella terra d'Israele. Essi ricostruiranno il tempio, ma non uguale al primo, fino al momento in cui si compirà il tempo stabilito. Dopo, torneranno tutti dall'esilio e ricostruiranno Gerusalemme nella sua magnificenza, e il tempio di Dio sarà ricostruito, come hanno preannunciato i profeti d'Israele."],
[14006,"Tutte le nazioni che si trovano su tutta la terra si convertiranno e temeranno Dio nella verità. Tutti abbandoneranno i loro idoli, che li hanno fatti errare nella menzogna, e benediranno il Dio dei secoli nella giustizia."],
[14007,"Tutti gli Israeliti che saranno scampati in quei giorni e si ricorderanno di Dio con sincerità, si raduneranno e verranno a Gerusalemme, e per sempre abiteranno tranquilli la terra di Abramo, che sarà data loro in possesso. Coloro che amano Dio nella verità gioiranno; coloro invece che commettono il peccato e l'ingiustizia spariranno da tutta la terra."],
[14008,"Ora, figli, vi raccomando: servite Dio nella verità e fate ciò che a lui piace. Anche ai vostri figli insegnate a fare la giustizia e l'elemosina, a ricordarsi di Dio, a benedire il suo nome in ogni tempo, nella verità e con tutte le forze."],
[14009,"Tu dunque, figlio, parti da Ninive, non restare più qui. Dopo aver sepolto tua madre vicino a me, quel giorno stesso non devi più restare entro i confini di Ninive. Vedo infatti trionfare in essa molta ingiustizia e grande perfidia, e nessuno se ne vergogna."],
[14010,"Vedi, figlio, quanto ha fatto Nadab al padre adottivo Achikar. Non è stato egli costretto a scendere ancora vivo sotto terra? Ma Dio ha rigettato l'infamia in faccia al colpevole: Achikar ritornò alla luce, mentre Nadab entrò nelle tenebre eterne, perché aveva cercato di uccidere Achikar. Per aver praticato l'elemosina, Achikar sfuggì al laccio mortale che gli aveva teso Nadab; Nadab invece cadde in quel laccio, che lo fece perire."],
[14011,"Così, figli miei, vedete dove conduce l'elemosina e dove conduce l'iniquità: essa conduce alla morte. Ma ecco, mi manca il respiro!\". Essi lo distesero sul letto; morì e fu sepolto con onore."],
[14012,"Quando morì la madre, Tobia la seppellì vicino al padre, poi partì per la Media con la moglie e i figli. Abitò a Ecbatana, presso Raguele suo suocero."],
[14013,"Curò con onore i suoceri nella loro vecchiaia e li seppellì a Ecbatana in Media. Tobia ereditò il patrimonio di Raguele e quello del padre Tobi."],
[14014,"Morì all'età di centodiciassette anni onorato da tutti."],
[14015,"Prima di morire sentì parlare della rovina di Ninive e vide i prigionieri che venivano deportati in Media per opera di Achikar, re della Media. Allora benedisse Dio per quanto aveva fatto nei confronti degli abitanti di Ninive e dell'Assiria. Prima di morire poté dunque gioire della sorte di Ninive e benedisse il Signore Dio nei secoli dei secoli."]
])
