Bib.ret([
[1001,"Paolo, servo di Dio e apostolo di Gesù Cristo per portare alla fede quelli che Dio ha scelto e per far conoscere la verità, che è conforme a un'autentica religiosità,"],
[1002,"nella speranza della vita eterna - promessa fin dai secoli eterni da Dio, il quale non mente,"],
[1003,"e manifestata al tempo stabilito nella sua parola mediante la predicazione, a me affidata per ordine di Dio, nostro salvatore -,"],
[1004,"a Tito, mio vero figlio nella medesima fede: grazia e pace da Dio Padre e da Cristo Gesù, nostro salvatore."],
[1005,"Per questo ti ho lasciato a Creta: perché tu metta ordine in quello che rimane da fare e stabilisca alcuni presbiteri in ogni città, secondo le istruzioni che ti ho dato."],
[1006,"Ognuno di loro sia irreprensibile, marito di una sola donna e abbia figli credenti, non accusabili di vita dissoluta o indisciplinati."],
[1007,"Il vescovo infatti, come amministratore di Dio, deve essere irreprensibile: non arrogante, non collerico, non dedito al vino, non violento, non avido di guadagni disonesti,"],
[1008,"ma ospitale, amante del bene, assennato, giusto, santo, padrone di sé,"],
[1009,"fedele alla Parola, degna di fede, che gli è stata insegnata, perché sia in grado di esortare con la sua sana dottrina e di confutare i suoi oppositori."],
[1010,"Vi sono infatti, soprattutto fra quelli che provengono dalla circoncisione, molti insubordinati, chiacchieroni e ingannatori."],
[1011,"A questi tali bisogna chiudere la bocca, perché sconvolgono intere famiglie, insegnando, a scopo di guadagno disonesto, quello che non si deve insegnare."],
[1012,"Uno di loro, proprio un loro profeta, ha detto: \"I Cretesi sono sempre bugiardi, brutte bestie e fannulloni\"."],
[1013,"Questa testimonianza è vera. Perciò correggili con fermezza, perché vivano sani nella fede"],
[1014,"e non diano retta a favole giudaiche e a precetti di uomini che rifiutano la verità."],
[1015,"Tutto è puro per chi è puro, ma per quelli che sono corrotti e senza fede nulla è puro: sono corrotte la loro mente e la loro coscienza."],
[1016,"Dichiarano di conoscere Dio, ma lo rinnegano con i fatti, essendo abominevoli e ribelli e incapaci di fare il bene."],
[2001,"Tu però insegna quello che è conforme alla sana dottrina."],
[2002,"Gli uomini anziani siano sobri, dignitosi, saggi, saldi nella fede, nella carità e nella pazienza."],
[2003,"Anche le donne anziane abbiano un comportamento santo: non siano maldicenti né schiave del vino; sappiano piuttosto insegnare il bene,"],
[2004,"per formare le giovani all'amore del marito e dei figli,"],
[2005,"a essere prudenti, caste, dedite alla famiglia, buone, sottomesse ai propri mariti, perché la parola di Dio non venga screditata."],
[2006,"Esorta ancora i più giovani a essere prudenti,"],
[2007,"offrendo te stesso come esempio di opere buone: integrità nella dottrina, dignità,"],
[2008,"linguaggio sano e irreprensibile, perché il nostro avversario resti svergognato, non avendo nulla di male da dire contro di noi."],
[2009,"Esorta gli schiavi a essere sottomessi ai loro padroni in tutto; li accontentino e non li contraddicano,"],
[2010,"non rubino, ma dimostrino fedeltà assoluta, per fare onore in tutto alla dottrina di Dio, nostro salvatore."],
[2011,"È apparsa infatti la grazia di Dio, che porta salvezza a tutti gli uomini"],
[2012,"e ci insegna a rinnegare l'empietà e i desideri mondani e a vivere in questo mondo con sobrietà, con giustizia e con pietà,"],
[2013,"nell'attesa della beata speranza e della manifestazione della gloria del nostro grande Dio e salvatore Gesù Cristo."],
[2014,"Egli ha dato se stesso per noi, per riscattarci da ogni iniquità e formare per sé un popolo puro che gli appartenga, pieno di zelo per le opere buone."],
[2015,"Questo devi insegnare, raccomandare e rimproverare con tutta autorità. Nessuno ti disprezzi!"],
[3001,"Ricorda loro di essere sottomessi alle autorità che governano, di obbedire, di essere pronti per ogni opera buona;"],
[3002,"di non parlare male di nessuno, di evitare le liti, di essere mansueti, mostrando ogni mitezza verso tutti gli uomini."],
[3003,"Anche noi un tempo eravamo insensati, disobbedienti, corrotti, schiavi di ogni sorta di passioni e di piaceri, vivendo nella malvagità e nell'invidia, odiosi e odiandoci a vicenda."],
[3004,"Ma quando apparvero la bontà di Dio, salvatore nostro, e il suo amore per gli uomini,"],
[3005,"egli ci ha salvati, non per opere giuste da noi compiute, ma per la sua misericordia, con un'acqua che rigenera e rinnova nello Spirito Santo,"],
[3006,"che Dio ha effuso su di noi in abbondanza per mezzo di Gesù Cristo, salvatore nostro,"],
[3007,"affinché, giustificati per la sua grazia, diventassimo, nella speranza, eredi della vita eterna."],
[3008,"Questa parola è degna di fede e perciò voglio che tu insista su queste cose, perché coloro che credono a Dio si sforzino di distinguersi nel fare il bene. Queste cose sono buone e utili agli uomini."],
[3009,"Evita invece le questioni sciocche, le genealogie, le risse e le polemiche intorno alla Legge, perché sono inutili e vane."],
[3010,"Dopo un primo e un secondo ammonimento sta' lontano da chi è fazioso,"],
[3011,"ben sapendo che persone come queste sono fuorviate e continuano a peccare, condannandosi da sé."],
[3012,"Quando ti avrò mandato Àrtema o Tichico, cerca di venire subito da me a Nicopoli, perché là ho deciso di passare l'inverno."],
[3013,"Provvedi con cura al viaggio di Zena, il giurista, e di Apollo, perché non manchi loro nulla."],
[3014,"Imparino così anche i nostri a distinguersi nel fare il bene per le necessità urgenti, in modo da non essere gente inutile."],
[3015,"Ti salutano tutti coloro che sono con me. Saluta quelli che ci amano nella fede. La grazia sia con tutti voi!"]
])
