Bib.ret([
[1001,"Nell'ottavo mese dell'anno secondo di Dario, fu rivolta questa parola del Signore al profeta Zaccaria, figlio di Berechia, figlio di Iddo:"],
[1002,"\"Il Signore si è molto sdegnato contro i vostri padri."],
[1003,"Tu dunque riferirai loro: Così dice il Signore degli eserciti: Tornate a me - oracolo del Signore degli eserciti - e io tornerò a voi, dice il Signore degli eserciti."],
[1004,"Non siate come i vostri padri, ai quali i profeti di un tempo andavano gridando: \"Dice il Signore degli eserciti: Tornate indietro dal vostro cammino perverso e dalle vostre opere malvagie\". Ma essi non vollero ascoltare e non mi prestarono attenzione, oracolo del Signore."],
[1005,"Dove sono i vostri padri? I profeti forse vivranno sempre?"],
[1006,"Le parole e le leggi che io avevo comunicato ai miei servi, i profeti, non si sono forse adempiute per i padri vostri? Essi sono tornati e hanno detto: \"Quanto il Signore degli eserciti ci aveva minacciato a causa dei nostri traviamenti e delle nostre colpe, l'ha eseguito sopra di noi\"\"."],
[1007,"Il ventiquattro dell'undicesimo mese, cioè il mese di Sebat, l'anno secondo di Dario, questa parola del Signore fu rivolta al profeta Zaccaria, figlio di Berechia, figlio di Iddo."],
[1008,"Io ebbi una visione di notte. Un uomo, in groppa a un cavallo rosso, stava fra i mirti in una valle profonda; dietro a lui stavano altri cavalli rossi, sauri e bianchi."],
[1009,"Io domandai: \"Mio signore, che cosa significano queste cose?\". L'angelo che parlava con me mi rispose: \"Io ti indicherò ciò che esse significano\"."],
[1010,"Allora l'uomo che stava fra i mirti prese a dire: \"Questi sono coloro che il Signore ha inviato a percorrere la terra\"."],
[1011,"Si rivolsero infatti all'angelo del Signore che stava fra i mirti e gli dissero: \"Abbiamo percorso la terra: è tutta tranquilla\"."],
[1012,"Allora l'angelo del Signore disse: \"Signore degli eserciti, fino a quando rifiuterai di avere pietà di Gerusalemme e delle città di Giuda, contro le quali sei sdegnato? Sono ormai settant'anni!\"."],
[1013,"E all'angelo che parlava con me il Signore rivolse parole buone, piene di conforto."],
[1014,"Poi l'angelo che parlava con me mi disse: \"Fa' sapere questo: Così dice il Signore degli eserciti: Io sono molto geloso di Gerusalemme e di Sion,"],
[1015,"ma ardo di sdegno contro le nazioni superbe, poiché, mentre io ero poco sdegnato, esse cooperarono al disastro."],
[1016,"Perciò dice il Signore: Io di nuovo mi volgo con compassione a Gerusalemme: la mia casa vi sarà riedificata - oracolo del Signore degli eserciti - e la corda del muratore sarà tesa di nuovo sopra Gerusalemme."],
[1017,"Fa' sapere anche questo: Così dice il Signore degli eserciti: Le mie città avranno sovrabbondanza di beni, il Signore consolerà ancora Sion ed eleggerà di nuovo Gerusalemme\"."],
[2001,"Poi alzai gli occhi, ed ecco, vidi quattro corna."],
[2002,"Domandai all'angelo che parlava con me: \"Che cosa sono queste?\". Ed egli: \"Sono le corna che hanno disperso Giuda, Israele e Gerusalemme\"."],
[2003,"Poi il Signore mi fece vedere quattro fabbri."],
[2004,"Domandai: \"Che cosa vengono a fare costoro?\". Mi rispose: \"Le corna hanno disperso Giuda a tal segno che nessuno osa più alzare la testa e costoro vengono a demolire e abbattere le corna delle nazioni che cozzano contro il paese di Giuda per disperderlo\"."],
[2005,"Alzai gli occhi, ed ecco un uomo con una fune in mano per misurare."],
[2006,"Gli domandai: \"Dove vai?\". Ed egli: \"Vado a misurare Gerusalemme per vedere qual è la sua larghezza e qual è la sua lunghezza\"."],
[2007,"Allora l'angelo che parlava con me uscì e incontrò un altro angelo,"],
[2008,"che gli disse: \"Corri, va' a parlare a quel giovane e digli: \"Gerusalemme sarà priva di mura, per la moltitudine di uomini e di animali che dovrà accogliere."],
[2009,"Io stesso - oracolo del Signore - le farò da muro di fuoco all'intorno e sarò una gloria in mezzo ad essa\"\"."],
[2010,"\"Su, su, fuggite dal paese del settentrione - oracolo del Signore - voi che ho disperso ai quattro venti del cielo. Oracolo del Signore."],
[2011,"Mettiti in salvo, o Sion, tu che abiti con la figlia di Babilonia!"],
[2012,"Il Signore degli eserciti, dopo che la sua gloria mi ha inviato, dice alle nazioni che vi hanno spogliato: Chi tocca voi, tocca la pupilla dei miei occhi."],
[2013,"Ecco, io stendo la mano sopra di esse e diverranno preda dei loro schiavi. E voi saprete che il Signore degli eserciti mi ha inviato."],
[2014,"Rallegrati, esulta, figlia di Sion, perché, ecco, io vengo ad abitare in mezzo a te. Oracolo del Signore."],
[2015,"Nazioni numerose aderiranno in quel giorno al Signore e diverranno suo popolo, ed egli dimorerà in mezzo a te e tu saprai che il Signore degli eserciti mi ha inviato a te."],
[2016,"Il Signore si terrà Giuda come eredità nella terra santa ed eleggerà di nuovo Gerusalemme."],
[2017,"Taccia ogni mortale davanti al Signore, poiché egli si è destato dalla sua santa dimora\"."],
[3001,"Poi mi fece vedere il sommo sacerdote Giosuè, ritto davanti all'angelo del Signore, e Satana era alla sua destra per accusarlo."],
[3002,"L'angelo del Signore disse a Satana: \"Ti rimprovera il Signore, o Satana! Ti rimprovera il Signore che ha eletto Gerusalemme! Non è forse costui un tizzone sottratto al fuoco?\"."],
[3003,"Giosuè infatti era rivestito di vesti sporche e stava in piedi davanti all'angelo,"],
[3004,"il quale prese a dire a coloro che gli stavano intorno: \"Toglietegli quelle vesti sporche\". Poi disse a Giosuè: \"Ecco, io ti tolgo di dosso il peccato; fatti rivestire di abiti preziosi\"."],
[3005,"Poi soggiunse: \"Mettetegli sul capo un turbante purificato\". E gli misero un turbante purificato sul capo, lo rivestirono di vesti alla presenza dell'angelo del Signore."],
[3006,"Poi l'angelo del Signore dichiarò a Giosuè:"],
[3007,"\"Dice il Signore degli eserciti: Se camminerai nelle mie vie e custodirai i miei precetti, tu avrai il governo della mia casa, sarai il custode dei miei atri e ti darò accesso fra questi che stanno qui."],
[3008,"Ascolta dunque, Giosuè, sommo sacerdote, tu e i tuoi compagni che siedono davanti a te, poiché essi sono un segno: ecco, io manderò il mio servo Germoglio."],
[3009,"Ecco la pietra che io pongo davanti a Giosuè: sette occhi sono su quest'unica pietra; io stesso inciderò la sua iscrizione - oracolo del Signore degli eserciti - e rimuoverò in un solo giorno l'iniquità da questo paese."],
[3010,"In quel giorno - oracolo del Signore degli eserciti - ogni uomo inviterà il suo vicino sotto la sua vite e sotto il suo fico\"."],
[4001,"L'angelo che mi parlava venne a destarmi, come si desta uno dal sonno,"],
[4002,"e mi disse: \"Che cosa vedi?\". Risposi: \"Vedo un candelabro tutto d'oro; in cima ha una coppa con sette lucerne e sette beccucci per ognuna delle lucerne."],
[4003,"Due olivi gli stanno vicino, uno a destra della coppa e uno a sinistra\"."],
[4004,"Allora domandai all'angelo che mi parlava: \"Che cosa significano, mio signore, queste cose?\"."],
[4005,"Egli mi rispose: \"Non comprendi dunque il loro significato?\". E io: \"No, mio signore\"."],
[4006,"Egli mi rispose: \"Questa è la parola del Signore a Zorobabele: \"Non con la potenza né con la forza, ma con il mio spirito\", dice il Signore degli eserciti!"],
[4007,"Chi sei tu, o grande monte? Davanti a Zorobabele diventa pianura! Egli estrarrà la pietra di vertice, mentre si acclamerà: \"Quanto è bella!\"."],
[4008,"Mi fu rivolta questa parola del Signore:"],
[4009,"Le mani di Zorobabele hanno fondato questa casa: le sue mani la compiranno e voi saprete che il Signore degli eserciti mi ha inviato a voi."],
[4010,"Chi oserà disprezzare il giorno di così modesti inizi? Si gioirà vedendo il filo a piombo in mano a Zorobabele. Le sette lucerne rappresentano gli occhi del Signore che scrutano tutta la terra\"."],
[4011,"Quindi gli domandai: \"Che cosa significano quei due olivi a destra e a sinistra del candelabro?\". E aggiunsi:"],
[4012,"\"Quei due rami d'olivo che sono a fianco dei due canaletti d'oro, che vi stillano oro dentro?\"."],
[4013,"Mi rispose: \"Non comprendi dunque il significato di queste cose?\". E io: \"No, mio signore\"."],
[4014,"\"Questi - soggiunse - sono i due consacrati con olio che assistono il dominatore di tutta la terra\"."],
[5001,"Poi alzai gli occhi e vidi un rotolo che volava."],
[5002,"L'angelo mi domandò: \"Che cosa vedi?\". E io: \"Vedo un rotolo che vola: è lungo venti cubiti e largo dieci\"."],
[5003,"Egli soggiunse: \"Questa è la maledizione che si diffonde su tutta la terra: ogni ladro sarà scacciato via di qui come quel rotolo; ogni spergiuro sarà scacciato via di qui come quel rotolo."],
[5004,"Io scatenerò la maledizione, dice il Signore degli eserciti, in modo che essa penetri nella casa del ladro e nella casa di chi giura il falso nel mio nome; rimarrà in quella casa e la consumerà insieme con le sue travi e le sue pietre\"."],
[5005,"Poi l'angelo che parlava con me si avvicinò e mi disse: \"Alza gli occhi e osserva ciò che appare\"."],
[5006,"E io: \"Che cos'è quella?\". Mi rispose: \"È un' efa!  che avanza\". Poi soggiunse: \"Non hanno occhi che per essa in tutta la terra\"."],
[5007,"Fu quindi alzato un coperchio di piombo; ecco, dentro all' efa!  vi era una donna."],
[5008,"Disse: \"Questa è l'empietà!\". Poi la ricacciò dentro l' efa!  e ricoprì l'apertura con il coperchio di piombo."],
[5009,"Alzai di nuovo gli occhi per osservare e vidi venire due donne: il vento agitava le loro ali, poiché avevano ali come quelle delle cicogne, e sollevarono l' efa!  fra la terra e il cielo."],
[5010,"Domandai all'angelo che parlava con me: \"Dove portano l' efa!  costoro?\"."],
[5011,"Mi rispose: \"Vanno nella terra di Sinar, per costruirle una casa. Appena costruita, l' efa!  sarà posta sopra il suo piedistallo\"."],
[6001,"Alzai ancora gli occhi per osservare, ed ecco quattro carri uscire in mezzo a due montagne e le montagne erano di bronzo."],
[6002,"Il primo carro aveva cavalli rossi, il secondo cavalli neri,"],
[6003,"il terzo cavalli bianchi e il quarto cavalli pezzati, screziati."],
[6004,"Domandai all'angelo che parlava con me: \"Che cosa significano quelli, mio signore?\"."],
[6005,"E l'angelo: \"Sono i quattro venti del cielo che partono dopo essersi presentati al Signore di tutta la terra."],
[6006,"I cavalli neri vanno verso la terra del settentrione, seguiti da quelli bianchi; i pezzati invece si dirigono verso la terra del mezzogiorno,"],
[6007,"quelli screziati escono e fremono di percorrere la terra\". Egli disse loro: \"Andate, percorrete la terra\". Essi partirono per percorrere la terra."],
[6008,"Poi mi chiamò e mi disse: \"Ecco, quelli che vanno verso la terra del settentrione calmano il mio spirito su quella terra\"."],
[6009,"Mi fu rivolta questa parola del Signore:"],
[6010,"\"Prendi fra i deportati, fra quelli di Cheldai, di Tobia e di Iedaià, oro e argento e va' nel medesimo giorno a casa di Giosia, figlio di Sofonia, che è ritornato da Babilonia."],
[6011,"Prendi quell'argento e quell'oro e ne farai una corona che porrai sul capo di Giosuè, figlio di Iosadak, sommo sacerdote."],
[6012,"Gli riferirai: Dice il Signore degli eserciti: Ecco un uomo che si chiama Germoglio: fiorirà dove si trova e ricostruirà il tempio del Signore."],
[6013,"Sì, egli ricostruirà il tempio del Signore, egli riceverà la gloria, egli siederà da sovrano sul suo trono. Un sacerdote siederà sul suo trono e fra i due regnerà una pace perfetta."],
[6014,"La corona resterà come gradito memoriale nel tempio del Signore, in onore di Cheldai, Tobia, Iedaià e in onore del figlio di Sofonia."],
[6015,"Anche da lontano verranno a riedificare il tempio del Signore. Così riconoscerete che il Signore degli eserciti mi ha inviato a voi. Ciò avverrà, se ascolterete la voce del Signore, vostro Dio\"."],
[7001,"L'anno quarto del re Dario, il quarto giorno del nono mese, detto Chisleu, la parola del Signore fu rivolta a Zaccaria."],
[7002,"Betel aveva inviato Sareser, alto ufficiale del re, con i suoi uomini a supplicare il Signore"],
[7003,"e a domandare ai sacerdoti addetti al tempio del Signore degli eserciti e ai profeti: \"Devo io continuare a far lutto e astinenza nel quinto mese, come ho fatto in questi anni passati?\"."],
[7004,"Allora mi fu rivolta questa parola del Signore degli eserciti:"],
[7005,"\"Parla a tutto il popolo del paese e a tutti i sacerdoti e di' loro: Quando avete fatto digiuni e lamenti nel quinto e nel settimo mese per questi settant'anni, lo facevate forse per me?"],
[7006,"Quando avete mangiato e bevuto non lo facevate forse per voi?"],
[7007,"Non è questa forse la parola che vi proclamava il Signore per mezzo dei profeti del passato, quando Gerusalemme era ancora abitata e in pace, ed erano abitate le città vicine e il Negheb e la Sefela?\"."],
[7008,"Questa parola del Signore fu rivolta a Zaccaria:"],
[7009,"\"Ecco ciò che dice il Signore degli eserciti: Praticate una giustizia vera: abbiate amore e misericordia ciascuno verso il suo prossimo."],
[7010,"Non frodate la vedova, l'orfano, il forestiero, il misero e nessuno nel cuore trami il male contro il proprio fratello."],
[7011,"Ma essi hanno rifiutato di ascoltarmi, mi hanno voltato le spalle, hanno indurito gli orecchi per non sentire."],
[7012,"Indurirono il cuore come un diamante, per non udire la legge e le parole che il Signore degli eserciti rivolgeva loro mediante il suo spirito, per mezzo dei profeti del passato. Così fu grande lo sdegno del Signore degli eserciti."],
[7013,"Come quando egli chiamava essi non vollero dare ascolto, così quando essi chiameranno io non li ascolterò, dice il Signore degli eserciti."],
[7014,"Io li ho dispersi fra tutte quelle nazioni che essi non conoscevano e il paese è rimasto deserto dietro di loro, senza che vi sia chi va e chi viene; la terra di delizie è stata ridotta a desolazione\"."],
[8001,"La parola del Signore degli eserciti fu rivolta in questi termini:"],
[8002,"\"Così dice il Signore degli eserciti: Sono molto geloso di Sion, un grande ardore m'infiamma per lei."],
[8003,"Così dice il Signore: Tornerò a Sion e dimorerò a Gerusalemme. Gerusalemme sarà chiamata \"Città fedele\" e il monte del Signore degli eserciti \"Monte santo\"."],
[8004,"Così dice il Signore degli eserciti: Vecchi e vecchie siederanno ancora nelle piazze di Gerusalemme, ognuno con il bastone in mano per la loro longevità."],
[8005,"Le piazze della città formicoleranno di fanciulli e di fanciulle, che giocheranno sulle sue piazze."],
[8006,"Così dice il Signore degli eserciti: Se questo sembra impossibile agli occhi del resto di questo popolo in quei giorni, sarà forse impossibile anche ai miei occhi? Oracolo del Signore degli eserciti."],
[8007,"Così dice il Signore degli eserciti: Ecco, io salvo il mio popolo dall'oriente e dall'occidente:"],
[8008,"li ricondurrò ad abitare a Gerusalemme; saranno il mio popolo e io sarò il loro Dio, nella fedeltà e nella giustizia."],
[8009,"Così dice il Signore degli eserciti: Riprendano forza le vostre mani. Voi in questi giorni ascoltate queste parole pronunciate dai profeti quando furono poste le fondamenta della casa del Signore degli eserciti per la ricostruzione del tempio."],
[8010,"Ma prima di questi giorni non c'era salario per l'uomo né salario per l'animale; non c'era sicurezza alcuna per chi andava e per chi veniva, a causa degli invasori: io stesso mettevo gli uomini l'uno contro l'altro."],
[8011,"Ora invece verso il resto di questo popolo io non sarò più come sono stato prima. Oracolo del Signore degli eserciti."],
[8012,"Ecco il seme della pace: la vite produrrà il suo frutto, la terra darà i suoi prodotti, i cieli daranno la rugiada: darò tutto ciò al resto di questo popolo."],
[8013,"Come foste oggetto di maledizione fra le nazioni, o casa di Giuda e d'Israele, così, quando vi avrò salvati, diverrete una benedizione. Non temete dunque: riprendano forza le vostre mani."],
[8014,"Così dice il Signore degli eserciti: Come decisi di affliggervi quando i vostri padri mi provocarono all'ira - dice il Signore degli eserciti - e non volli ravvedermi,"],
[8015,"così mi darò premura in questi giorni di fare del bene a Gerusalemme e alla casa di Giuda: Non temete!"],
[8016,"Ecco ciò che voi dovrete fare: dite la verità ciascuno con il suo prossimo; veraci e portatori di pace siano i giudizi che pronuncerete nei vostri tribunali."],
[8017,"Nessuno trami nel cuore il male contro il proprio fratello; non amate il giuramento falso, poiché io detesto tutto questo\". Oracolo del Signore."],
[8018,"Mi fu rivolta questa parola del Signore degli eserciti:"],
[8019,"\"Così dice il Signore degli eserciti: Il digiuno del quarto, quinto, settimo e decimo mese si cambierà per la casa di Giuda in gioia, in giubilo e in giorni di festa, purché amiate la verità e la pace."],
[8020,"Così dice il Signore degli eserciti: Anche popoli e abitanti di numerose città si raduneranno"],
[8021,"e si diranno l'un l'altro: \"Su, andiamo a supplicare il Signore, a trovare il Signore degli eserciti. Anch'io voglio venire\"."],
[8022,"Così popoli numerosi e nazioni potenti verranno a Gerusalemme a cercare il Signore degli eserciti e a supplicare il Signore."],
[8023,"Così dice il Signore degli eserciti: In quei giorni, dieci uomini di tutte le lingue delle nazioni afferreranno un Giudeo per il lembo del mantello e gli diranno: \"Vogliamo venire con voi, perché abbiamo udito che Dio è con voi\"\"."],
[9001,"Oracolo. \"La parola del Signore è sulla terra di Adrac e si posa su Damasco, poiché al Signore appartiene la perla di Aram e tutte le tribù d'Israele,"],
[9002,"e anche Camat sua confinante e Tiro e Sidone, ricche di sapienza."],
[9003,"Tiro si è costruita una fortezza e vi ha accumulato argento come polvere e oro come fango delle strade."],
[9004,"Ecco, il Signore se ne impossesserà, sprofonderà nel mare le sue mura ed essa sarà divorata dal fuoco."],
[9005,"Àscalon vedrà e ne sarà spaventata, Gaza sarà in grandi dolori, e così pure Ekron, perché svanirà la sua fiducia; scomparirà il re da Gaza e Àscalon rimarrà disabitata."],
[9006,"Bastardi dimoreranno ad Asdod, abbatterò l'orgoglio del Filisteo."],
[9007,"Toglierò il sangue dalla sua bocca e i suoi abomini dai suoi denti. Diventerà anche lui un resto per il nostro Dio, sarà come una famiglia in Giuda ed Ekron sarà simile al Gebuseo."],
[9008,"Mi porrò come sentinella per la mia casa contro chi va e chi viene, non vi passerà più l'oppressore, perché ora io stesso sorveglio con i miei occhi."],
[9009,"Esulta grandemente, figlia di Sion, giubila, figlia di Gerusalemme! Ecco, a te viene il tuo re. Egli è giusto e vittorioso, umile, cavalca un asino, un puledro figlio d'asina."],
[9010,"Farà sparire il carro da guerra da Èfraim e il cavallo da Gerusalemme, l'arco di guerra sarà spezzato, annuncerà la pace alle nazioni, il suo dominio sarà da mare a mare e dal Fiume fino ai confini della terra."],
[9011,"Quanto a te, per il sangue dell'alleanza con te, estrarrò i tuoi prigionieri dal pozzo senz'acqua."],
[9012,"Ritornate alla cittadella, prigionieri della speranza! Ve l'annuncio oggi stesso: vi ripagherò due volte."],
[9013,"Tendo Giuda come mio arco, faccio di Èfraim la mia arma; ecciterò i tuoi figli, Sion, contro i tuoi figli, Iavan, ti renderò come spada di un eroe."],
[9014,"Allora il Signore comparirà contro di loro, come fulmine guizzeranno le sue frecce; il Signore darà fiato al corno e marcerà fra i turbini che vengono dal mezzogiorno."],
[9015,"Il Signore degli eserciti li proteggerà: divoreranno e calpesteranno le pietre della fionda, berranno il loro sangue come vino, ne saranno pieni come bacini, come i corni dell'altare."],
[9016,"Il Signore, loro Dio, in quel giorno li salverà, come gregge del suo popolo; come gemme di un diadema brilleranno sulla sua terra."],
[9017,"Che ricchezza, che felicità! Il grano darà forza ai giovani e il vino nuovo alle fanciulle."],
[10001,"Chiedete al Signore la pioggia tardiva di primavera; è il Signore che forma i nembi, egli riversa pioggia abbondante, dona all'uomo il pane, a ognuno l'erba dei campi."],
[10002,"Poiché i terafim  dicono menzogne, gli indovini vedono il falso, raccontano sogni fallaci, danno vane consolazioni: perciò vagano come un gregge, sono oppressi, perché senza pastore."],
[10003,"Contro i pastori divampa il mio sdegno e contro i montoni dirigo lo sguardo, poiché il Signore degli eserciti visiterà il suo gregge e ne farà come un cavallo splendido in battaglia."],
[10004,"Da lui uscirà la pietra d'angolo, da lui il piolo, da lui l'arco di guerra, da lui tutti quanti i condottieri."],
[10005,"Saranno come prodi che calpestano il fango delle strade in battaglia. Combatteranno, perché il Signore è con loro, e rimarranno confusi coloro che cavalcano i destrieri."],
[10006,"Io rafforzerò la casa di Giuda e renderò vittoriosa la casa di Giuseppe: li ricondurrò, poiché ne ho avuto pietà; saranno come se non li avessi mai ripudiati, poiché io sono il Signore, loro Dio, e li esaudirò."],
[10007,"Saranno come un eroe quelli di Èfraim, gioirà il loro cuore come inebriato dal vino, i loro figli vedranno e gioiranno e il loro cuore esulterà nel Signore."],
[10008,"Con un fischio li chiamerò a raccolta, quando li avrò riscattati, e saranno numerosi come prima."],
[10009,"Dopo che li avrò dispersi fra i popoli, nelle regioni remote si ricorderanno di me, vi alleveranno figli e torneranno."],
[10010,"Li farò ritornare dalla terra d'Egitto, li raccoglierò dall'Assiria, per ricondurli nella terra di Galaad e del Libano, e non basterà per loro lo spazio."],
[10011,"Attraverseranno il mare d'Egitto, percuoteranno le onde del mare, saranno inariditi i gorghi del Nilo. Sarà abbattuto l'orgoglio dell'Assiria e rimosso lo scettro d'Egitto."],
[10012,"Li renderò forti nel Signore e cammineranno nel suo nome\". Oracolo del Signore."],
[11001,"Apri, Libano, le tue porte, e il fuoco divori i tuoi cedri."],
[11002,"Urla, cipresso, perché il cedro è caduto, gli splendidi alberi sono distrutti. Urlate, querce di Basan, perché la foresta impenetrabile è abbattuta!"],
[11003,"Si ode il lamento dei pastori, perché la loro gloria è distrutta! Si ode il ruggito dei leoncelli, perché è devastata la magnificenza del Giordano!"],
[11004,"Così parla il Signore, mio Dio: \"Pascola quelle pecore da macello"],
[11005,"che i compratori sgozzano impunemente e di cui i venditori dicono: \"Sia benedetto il Signore, mi sono arricchito\", e i loro pastori non ne hanno pietà."],
[11006,"Neppure io perdonerò agli abitanti del paese. Oracolo del Signore. Ecco, io abbandonerò gli uomini ognuno in balia del suo vicino e del suo re, perché devastino il paese, e non mi curerò di liberarli dalle loro mani\"."],
[11007,"Io dunque mi misi a pascolare le pecore da macello per conto dei mercanti di pecore. Presi due bastoni: uno lo chiamai Benevolenza e l'altro Unione, e condussi al pascolo le pecore."],
[11008,"Nel volgere di un solo mese eliminai tre pastori. Ma io mi irritai contro di esse, perché anch'esse mi detestavano."],
[11009,"Perciò io dissi: \"Non sarò più il vostro pastore. Chi vuole morire muoia, chi vuole perire perisca, quelle che rimangono si divorino pure fra loro!\"."],
[11010,"Presi il bastone chiamato Benevolenza e lo spezzai: ruppi così l'alleanza da me stabilita con tutti i popoli."],
[11011,"Lo ruppi in quel medesimo giorno; i mercanti di pecore che mi osservavano, riconobbero che quello era l'ordine del Signore."],
[11012,"Poi dissi loro: \"Se vi pare giusto, datemi la mia paga; se no, lasciate stare\". Essi allora pesarono trenta sicli d'argento come mia paga."],
[11013,"Ma il Signore mi disse: \"Porta al fonditore questa grandiosa somma, con cui sono stato da loro valutato!\". Io presi i trenta sicli d'argento e li portai al fonditore della casa del Signore."],
[11014,"Poi feci a pezzi il secondo bastone chiamato Unione, per rompere così la fratellanza fra Giuda e Israele."],
[11015,"Quindi il Signore mi disse: \"Prendi ancora gli attrezzi di un pastore insensato,"],
[11016,"poiché ecco, io susciterò nel paese un pastore che non avrà cura di quelle che si perdono, non cercherà le giovani, non curerà le malate, non nutrirà quelle ancora sane; mangerà invece le carni delle più grasse e strapperà loro persino le unghie."],
[11017,"Guai al pastore stolto che abbandona il gregge! Una spada colpisca il suo braccio e il suo occhio destro. Tutto il suo braccio si inaridisca e tutto il suo occhio destro resti accecato\"."],
[12001,"Oracolo. Parola del Signore su Israele. Oracolo del Signore che ha dispiegato i cieli e fondato la terra, che ha formato il soffio vitale nell'intimo dell'uomo:"],
[12002,"\"Ecco, io farò di Gerusalemme come una coppa che dà le vertigini a tutti i popoli vicini, e anche Giuda sarà in angoscia nell'assedio contro Gerusalemme."],
[12003,"In quel giorno io farò di Gerusalemme come una pietra pesante per tutti i popoli: quanti vorranno sollevarla ne resteranno graffiati; contro di essa si raduneranno tutte le nazioni della terra."],
[12004,"In quel giorno - oracolo del Signore - colpirò tutti i cavalli di terrore, e i loro cavalieri di pazzia; mentre sulla casa di Giuda terrò aperti i miei occhi, colpirò di cecità tutti i cavalli dei popoli."],
[12005,"Allora i capi di Giuda penseranno: \"La forza dei cittadini di Gerusalemme sta nel Signore degli eserciti, loro Dio\"."],
[12006,"In quel giorno farò dei capi di Giuda come un braciere acceso in mezzo a una catasta di legna e come una torcia ardente fra i covoni; essi divoreranno a destra e a sinistra tutti i popoli vicini. Solo Gerusalemme resterà al suo posto."],
[12007,"Il Signore salverà in primo luogo le tende di Giuda, perché la gloria della casa di Davide e la gloria degli abitanti di Gerusalemme non cresca più di quella di Giuda."],
[12008,"In quel giorno il Signore farà da scudo agli abitanti di Gerusalemme e chi tra loro vacilla diverrà come Davide e la casa di Davide come Dio, come l'angelo del Signore davanti a loro."],
[12009,"In quel giorno io mi impegnerò a distruggere tutte le nazioni che verranno contro Gerusalemme."],
[12010,"Riverserò sopra la casa di Davide e sopra gli abitanti di Gerusalemme uno spirito di grazia e di consolazione: guarderanno a me, colui che hanno trafitto. Ne faranno il lutto come si fa il lutto per un figlio unico, lo piangeranno come si piange il primogenito."],
[12011,"In quel giorno grande sarà il lamento a Gerusalemme, simile al lamento di Adad-Rimmon nella pianura di Meghiddo."],
[12012,"Farà lutto il paese, famiglia per famiglia: la famiglia della casa di Davide a parte e le loro donne a parte; la famiglia della casa di Natan a parte e le loro donne a parte;"],
[12013,"la famiglia della casa di Levi a parte e le loro donne a parte; la famiglia della casa di Simei a parte e le loro donne a parte;"],
[12014,"tutte le altre famiglie a parte e le loro donne a parte."],
[13001,"In quel giorno vi sarà per la casa di Davide e per gli abitanti di Gerusalemme una sorgente zampillante per lavare il peccato e l'impurità."],
[13002,"In quel giorno - oracolo del Signore degli eserciti - io estirperò dal paese i nomi degli idoli, né più saranno ricordati; anche i profeti e lo spirito di impurità farò sparire dal paese."],
[13003,"Se qualcuno oserà ancora fare il profeta, il padre e la madre che l'hanno generato, gli diranno: \"Non devi vivere, perché proferisci menzogne nel nome del Signore!\", e il padre e la madre che l'hanno generato lo trafiggeranno perché fa il profeta."],
[13004,"In quel giorno ogni profeta si vergognerà della visione ricevuta facendo il profeta, e non indosserà più il mantello di pelo per raccontare bugie."],
[13005,"Ma ognuno dirà: \"Non sono un profeta: sono un lavoratore della terra, ad essa mi sono dedicato fin dalla mia giovinezza\"."],
[13006,"E se gli si dirà: \"Perché quelle piaghe in mezzo alle tue mani?\", egli risponderà: \"Queste le ho ricevute in casa dei miei amici\"."],
[13007,"Insorgi, spada, contro il mio pastore, contro colui che è mio compagno. Oracolo del Signore degli eserciti. Percuoti il pastore e sia disperso il gregge, allora volgerò la mano anche contro i suoi piccoli."],
[13008,"In tutto il paese - oracolo del Signore - due terzi saranno sterminati e periranno; un terzo sarà conservato."],
[13009,"Farò passare questo terzo per il fuoco e lo purificherò come si purifica l'argento; lo proverò come si prova l'oro. Invocherà il mio nome e io l'ascolterò; dirò: \"Questo è il mio popolo\". Esso dirà: \"Il Signore è il mio Dio\"."],
[14001,"Ecco, viene un giorno per il Signore; allora le tue spoglie saranno spartite in mezzo a te."],
[14002,"Il Signore radunerà tutte le nazioni contro Gerusalemme per la battaglia; la città sarà presa, le case saccheggiate, le donne violentate, metà della città partirà per l'esilio, ma il resto del popolo non sarà strappato dalla città."],
[14003,"Il Signore uscirà e combatterà contro quelle nazioni, come quando combatté nel giorno dello scontro."],
[14004,"In quel giorno i suoi piedi si poseranno sopra il monte degli Ulivi che sta di fronte a Gerusalemme verso oriente, e il monte degli Ulivi si fenderà in due, da oriente a occidente, formando una valle molto profonda; una metà del monte si ritirerà verso settentrione e l'altra verso mezzogiorno."],
[14005,"Allora voi fuggirete attraverso la valle fra i monti, poiché la nuova valle fra i monti giungerà fino ad Asal; voi fuggirete come quando fuggiste durante il terremoto, al tempo di Ozia, re di Giuda. Verrà allora il Signore, mio Dio, e con lui tutti i suoi santi."],
[14006,"In quel giorno non vi sarà né luce né freddo né gelo:"],
[14007,"sarà un unico giorno, il Signore lo conosce; non ci sarà né giorno né notte, e verso sera risplenderà la luce."],
[14008,"In quel giorno acque vive sgorgheranno da Gerusalemme e scenderanno parte verso il mare orientale, parte verso il mare occidentale: ve ne saranno sempre, estate e inverno."],
[14009,"Il Signore sarà re di tutta la terra. In quel giorno il Signore sarà unico e unico il suo nome."],
[14010,"Tutto il paese si trasformerà in pianura, da Gheba fino a Rimmon, a meridione di Gerusalemme, che si eleverà e sarà abitata nel luogo dov'è, dalla porta di Beniamino fino al posto della prima porta, cioè fino alla porta dell'Angolo, e dalla torre di Cananel fino ai torchi del re."],
[14011,"Ivi abiteranno: non vi sarà più sterminio e Gerusalemme se ne starà tranquilla e sicura."],
[14012,"Questa sarà la piaga con cui il Signore colpirà tutti i popoli che avranno mosso guerra a Gerusalemme: imputridiranno le loro carni, mentre saranno ancora in piedi; i loro occhi marciranno nelle orbite e la lingua marcirà loro in bocca."],
[14013,"In quel giorno vi sarà, per opera del Signore, un grande tumulto tra loro: uno afferrerà la mano dell'altro e alzerà la mano sopra la mano del suo amico."],
[14014,"Anche Giuda combatterà a Gerusalemme e là si ammasseranno le ricchezze di tutte le nazioni vicine: oro, argento e vesti in grande quantità."],
[14015,"Di piaga simile saranno colpiti i cavalli, i muli, i cammelli, gli asini e tutte le bestie degli accampamenti."],
[14016,"Allora i superstiti, fra tutte le nazioni che avranno combattuto contro Gerusalemme, vi andranno ogni anno per adorare il re, il Signore degli eserciti, e per celebrare la festa delle Capanne."],
[14017,"Se qualcuna delle famiglie della terra non andrà a Gerusalemme per adorare il re, il Signore degli eserciti, su di essa non ci sarà pioggia."],
[14018,"Se la famiglia d'Egitto non salirà e non vorrà venire, sarà colpita dalla stessa pena che il Signore infliggerà alle nazioni che non saranno salite a celebrare la festa delle Capanne."],
[14019,"Questo sarà il castigo per l'Egitto e per tutte le nazioni che non saranno salite a celebrare la festa delle Capanne."],
[14020,"In quel tempo anche sopra i sonagli dei cavalli si troverà scritto: \"Sacro al Signore\", e i recipienti nel tempio del Signore saranno come i vasi per l'aspersione che sono davanti all'altare."],
[14021,"Anzi, tutti i recipienti di Gerusalemme e di Giuda saranno sacri al Signore degli eserciti; quanti vorranno sacrificare verranno e li adopereranno per cuocere le carni. In quel giorno non vi sarà neppure un mercante nella casa del Signore degli eserciti\"."]
])
