Bib.ret([
[1001, "ShîR<ShîR> HasShîRîM<ShîR> 'ăSheR<'ăSheR> LiSh:LoMoH<Sh:LoMoH>"],
[1002, "YisShāQēNî<NShQ> MinN:ShîQôT<N:ShîQâ> PîHû<PeH> .Kî<.Kî>-ThôVîM<ThôV> .DoDëKā<.DôD> MiyYāYiN<YaYiN>"],
[1003, "L:Rê,aCh<Rê,aCh> Sh:MāNëKā<SheMeN> ThôVîM<ThôV> SheMeN<SheMeN> .TûRaQ<RYQ> Sh:MeKā<ShēM> `aL<`aL>-.KēN<.KēN> `ăLāMôT<`aL:Mâ> 'ăHēVûKā<'HV>"],
[1004, "MāSh:KēNî<MShK:> 'aChăRëKā<'aChăRê> .NāRûZâ<RWZ> HĕVî'aNî<BW'> HamMeLeK:<MeLeK:> ChăDāRâv<CheDeR> NāGîLâ<.GYL> W:NiS:M:Châ<SMCh> BāK:<B> NaŹ:.KîRâ<ŹKR> DoDëKā<.DôD> MiyYaYiN<YaYiN> MêShāRîM<MêShāRîM> 'ăHēVûKā<'HV> Ś<Ś>"],
[1005, "Sh:ChôRâ<ShāChoR> 'ăNî<'ăNî> W:Nā'Wâ<Nā'WeH> B:NôT<BaT> Y:RûShāLāiM<Y:RûShāLaiM> .K:'āHŏLê<'oHeL> QēDāR<QēDāR> .KîRî`ôT<Y:Rî`â> Sh:LoMoH<Sh:LoMoH>"],
[1006, "'aL<'aL>-.TiR:'ûNî<R'H> She'ăNî<'ăNî> Sh:ChaR:ChoReT<Sh:ChaR:ChoR> ShesShĕŹāFaT:Nî<ShŹF> HasShāMeSh<SheMeSh> B:Nê<BēN> 'imMî<'ēM> NiChăRû<ChRH>-Vî<B> SāMuNî<SYM> NoThēRâ<NThR> 'eT<'ēT>-HakK:RāMîM<.KeReM> .KaR:Mî<.KeReM> ShelLî<L> Lo'<Lo'> NāThāR:.Tî<NThR>"],
[1007, "HagGîDâ<NGD> lLî<L> She'āHăVâ<'HV> NaF:Shî<NeFeSh> 'êKâ<'êKâ> TiR:`eH<R`H> 'êKâ<'êKâ> .TaR:BîZ<RVZ> BazZāHŏRāYiM<ZāHŏRaYiM> ShalLāMâ<LāmMâ> 'eH:YeH<HYH> .K:`oTh:Yâ<`ThH> `aL<`aL> `eD:Rê<`ēDeR> ChăVēRëKā<ChāVēR>"],
[1008, "'iM<'iM>-Lo'<Lo'> TēD:`î<YD`> LāK:<L> HayYāFâ<YāFeH> BanNāShîM<'isShâ> Z:'î<YZ'>-LāK:<L> B:`iQ:Vê<`āQēV> HazZo'N<Zo'N> ûR:`î<R`H> 'eT<'ēT>-.G:DiyYoTaYiK:<.G:DiyYâ> `aL<`aL> MiSh:.K:NôT<MiSh:.KāN> HāRo`îM<R`H> Ś<Ś>"],
[1009, "L:ŚuŚāTî<ŚûŚâ> B:RiK:Vê<ReKeV> FaR:`oH<PaR:`oH> .DimMîTîK:<.DMH> Ra`:YāTî<Ra`:Yâ>"],
[1010, "Nā'Wû<'WH> L:ChāYaYiK:<L:Chî> BatToRîM<.TôR> Zaûā'RēK:<Zaûā'R> BaChăRûŹîM<ChāRûŹ>"],
[1011, ".TôRê<.TôR> ŹāHāV<ŹāHāV> Na`ăSeH<`SH>-lLāK:<L> `iM<`iM> N:QudDôT<N:QudDâ> HakKāŚeF<.KeŚeF>"],
[1012, "`aD<`aD>-SheHamMeLeK:<MeLeK:> BiM:ŚiBô<MēŚaV> NiR:.Dî<NēR:.D:> NāTaN<NTN> RêChô<Rê,aCh>"],
[1013, "Z:RôR<Z:RôR> HamMoR<MoR> .DôDî<.DôD> Lî<L> BêN<BaYiN> ShāDaY<ShaD> YāLîN<LWN>"],
[1014, "'eSh:.KoL<'eSh:.KôL> HakKoFeR<.KoFeR> .DôDî<.DôD> Lî<L> B:KaR:Mê<.KeReM> `êN_gGeDî<`êN_gGeDî> Ś<Ś>"],
[1015, "HinNāK:<HinNēH> YāFâ<YāFeH> Ra`:YāTî<Ra`:Yâ> HinNāK:<HinNēH> YāFâ<YāFeH> `êNaYiK:<`aYiN> YôNîM<YôNâ>"],
[1016, "HinN:Kā<HinNēH> YāFeH<YāFeH> DôDî<.DôD> 'aF<'aF> Nā`îM<Nā`îM> 'aF<'aF>-`aR:SēNû<`eReS> Ra`ăNāNâ<Ra`ăNāN>"],
[1017, "QoRôT<QôRâ> BātTêNû<BaYiT> 'ăRāŹîM<'eReŹ> [1 RaChîThēNû<RāChîTh> 1] [2 RaHîThēNû<RāHîTh> 2] B:RôTîM<B:RôT>"],
[2001, "'ăNî<'ăNî> ChăVazZeLeT<ChăVazZeLeT> HasShāRôN<ShāRôN> ShôShanNaT<ShûShaN> Hā`ăMāQîM<`ēMeQ>"],
[2002, ".K:ShôShanNâ<ShôShāN> BêN<BaYiN> HaChôChîM<Chô,aCh> .KēN<.KēN> Ra`:YāTî<Ra`:Yâ> BêN<BaYiN> HaBāNôT<BaT>"],
[2003, ".K:TaPû,aCh<.TaPû,aCh> Ba`ăZê<`ēZ> HayYa`aR<Ya`aR> .KēN<.KēN> .DôDî<.DôD> BêN<BaYiN> HaBāNîM<BēN> B:ZilLô<ZēL> ChimMaD:.Tî<ChMD> W:YāShaV:.Tî<YShV> ûFiR:Yô<P:Rî> MāTôQ<MāTôQ> L:ChikKî<ChēK:>"],
[2004, "HĕVî'aNî<BW'> 'eL<'eL>-BêT<BaYiT> HayYāYiN<YaYiN> W:DiG:Lô<.DeGeL> `āLaY<`aL> 'aHăVâ<'aHăVâ>"],
[2005, "ŚamM:KûNî<ŚMK:> Bā'ăShîShôT<'ăShîShâ> RaP:DûNî<RFD> BatTaPûChîM<.TaPû,aCh> .Kî<.Kî>-ChôLaT<ChLH> 'aHăVâ<'aHăVâ> 'āNî<'ăNî>"],
[2006, "S:Mo'Lô<S:Mo'L> .TaChaT<.TaChaT> L:Ro'Shî<Ro'Sh> WîMîNô<YāMîN> .T:ChaB:QēNî<ChVQ>"],
[2007, "HiSh:Ba`:.Tî<ShV`> 'eT:KeM<'ēT> B:NôT<BaT> Y:RûShāLaiM<Y:RûShāLaiM> BiZ:Vā'ôT<Z:ViyYâ> 'ô<'ô> B:'aY:LôT<'ayYāLâ> HasSāDeH<SāDeH> 'iM<'iM>-.Tā`îRû<`WR> W:'iM<'iM>-.T:`ôR:Rû<`WR> 'eT<'ēT>-Hā'aHăVâ<'aHăVâ> `aD<`aD> ShetTeCh:PāZ<ChFZ> Ś<Ś>"],
[2008, "QôL<QôL> .DôDî<.DôD> HinNēH<HinNēH>-ŹeH<ŹeH> Bā'<BW'> M:DalLēG<.DLG> `aL<`aL>-HeHāRîM<HaR> M:QaPēZ<QFZ> `aL<`aL>-HagG:Vā`ôT<.GiV:`â>"],
[2009, ".DôMeH<.DMH> DôDî<.DôD> LiZ:Vî<Z:Vî> 'ô<'ô> L:`oFeR<`oFeR> Hā'ayYāLîM<'ayYāL> HinNēH<HinNēH>-ŹeH<ŹeH> `ôMēD<`MD> 'aChaR<'aChaR> .KāT:LēNû<.KoTeL> MaSh:.Gî,aCh<ShGCh> MiN<MiN>-HaChălLoNôT<ChalLôN> MēZîZ<ZWZ> MiN<MiN>-HaChăRakKîM<ChāRāK:>"],
[2010, "`āNâ<`NH> DôDî<.DôD> W:'āMaR<'MR> Lî<L> QûMî<QWM> LāK:<L> Ra`:YāTî<Ra`:Yâ> YāFāTî<YāFeH> ûL:Kî<HLK:>-LāK:<L>"],
[2011, ".Kî<.Kî>-HinNēH<HinNēH> [1 HaśŚ:TāW<Ś:TāW> 1] [2 HaśŚ:Tâv<Ś:Tâv> 2] `āVāR<`VR> HagGeSheM<.GeSheM> ChāLaF<ChLF> HāLaK:<HLK:> Lô<L>"],
[2012, "HanNizZāNîM<NizZāN> NiR:'û<R'H> Vā'āReZ<'eReZ> `ēT<`ēT> HaźŹāMîR<ŹāMîR> HigGî,a`<NG`> W:QôL<QôL> HatTôR<.TôR> NiSh:Ma`<ShM`> B:'aR:ZēNû<'eReZ>"],
[2013, "HatT:'ēNâ<.T:'ēNâ> ChāN:Thâ<ChNTh> FagGëHā<PaG> W:HagG:FāNîM<.GeFeN> Ś:MāDaR<Ś:MāDaR> NāT:Nû<NTN> Rê,aCh<Rê,aCh> QûMî<QWM> [1 L:Kî<HLK:> 1] [2 LāK:<L> 2] Ra`:YāTî<Ra`:Yâ> YāFāTî<YāFeH> ûL:Kî<HLK:>-LāK:<L> Ś<Ś>"],
[2014, "YôNāTî<YôNâ> B:ChaG:Wê<ChăGāWîM> HaśŚeLa`<ŚeLa`> B:ŚēTeR<ŚēTeR> HamMaD:RēGâ<MaD:RēGâ> HaR:'îNî<R'H> 'eT<'ēT>-MaR:'aYiK:<MaR:'eH> HaSh:Mî`îNî<ShM`> 'eT<'ēT>-QôLēK:<QôL> .Kî<.Kî>-QôLēK:<QôL> `āRēV<`āRēV> ûMaR:'êK:<MaR:'eH> Nā'WeH<Nā'WeH> Ś<Ś>"],
[2015, "'eChĕŹû<'ChŹ>-LāNû<L> Shû`āLîM<Shû`āL> Shû`āLîM<Shû`āL> Q:ThanNîM<QāThoN> M:ChaB:LîM<ChVL> .K:RāMîM<.KeReM> ûK:RāMêNû<.KeReM> Ś:MāDaR<Ś:MāDaR>"],
[2016, ".DôDî<.DôD> Lî<L> Wa'ăNî<'ăNî> Lô<L> HāRo`eH<R`H> BasShôShanNîM<ShôShāN>"],
[2017, "`aD<`aD> SheyYāFû,aCh<PWCh> HayYôM<YôM> W:NāŚû<NWŚ> HazZ:LāLîM<ZēL> ŚoV<ŚVV> .D:MēH<.DMH>-L:Kā<L> DôDî<.DôD> LiZ:Vî<Z:Vî> 'ô<'ô> L:`oFeR<`oFeR> Hā'ayYāLîM<'ayYāL> `aL<`aL>-HāRê<HaR> VāTeR<BeTeR> Ś<Ś>"],
[3001, "`aL<`aL>-MiSh:.KāVî<MiSh:.KāV> BalLêLôT<LaYLâ> BiqQaSh:.Tî<BQSh> 'ēT<'ēT> She'āHăVâ<'HV> NaF:Shî<NeFeSh> BiqQaSh:.TîW<BQSh> W:Lo'<Lo'> M:Zā'TîW<MZ'>"],
[3002, "'āQûMâ<QWM> .Nā'<Nā'> Wa'ăŚôV:Vâ<ŚVV> Vā`îR<`îR> BasSh:WāQîM<ShûQ> ûVāR:ChoVôT<R:ChôV> 'ăVaQ:Shâ<BQSh> 'ēT<'ēT> She'āHăVâ<'HV> NaF:Shî<NeFeSh> BiqQaSh:.TîW<BQSh> W:Lo'<Lo'> M:Zā'TîW<MZ'>"],
[3003, "M:Zā'ûNî<MZ'> HasShoM:RîM<ShMR> HaśŚoV:VîM<ŚVV> Bā`îR<`îR> 'ēT<'ēT> She'āHăVâ<'HV> NaF:Shî<NeFeSh> R:'îTeM<R'H>"],
[3004, ".KiM:`aTh<M:`aTh> She`āVaR:.Tî<`VR> MēHeM<MiN> `aD<`aD> ShemMāZā'Tî<MZ'> 'ēT<'ēT> She'āHăVâ<'HV> NaF:Shî<NeFeSh> 'ăChaŹ:.TîW<'ChŹ> W:Lo'<Lo'> 'aR:PenNû<RFH> `aD<`aD>-SheHăVê'TîW<BW'> 'eL<'eL>-BêT<BaYiT> 'imMî<'ēM> W:'eL<'eL>-CheDeR<CheDeR> HôRāTî<HRH>"],
[3005, "HiSh:Ba`:.Tî<ShV`> 'eT:KeM<'ēT> B:NôT<BaT> Y:RûShāLaiM<Y:RûShāLaiM> BiZ:Vā'ôT<Z:ViyYâ> 'ô<'ô> B:'aY:LôT<'ayYāLâ> HasSāDeH<SāDeH> 'iM<'iM>-.Tā`îRû<`WR> W:'iM<'iM>-.T:`ôR:Rû<`WR> 'eT<'ēT>-Hā'aHăVâ<'aHăVâ> `aD<`aD> ShetTeCh:PāZ<ChFZ> Ś<Ś>"],
[3006, "Mî<Mî> Źo'T<Źo'T> `oLâ<`LH> MiN<MiN>-HamMiD:BāR<MiD:BāR> .K:TîMăRôT<.TîMāRâ> `āShāN<`āShāN> M:QutTheReT<QThR> MôR<MoR> ûL:VôNâ<L:VôNâ> MikKoL<.KoL> 'aV:QaT<'aV:Qâ> RôKēL<RKL>"],
[3007, "HinNēH<HinNēH> MitThāTô<MitThâ> ShelLiSh:LoMoH<Sh:LoMoH> ShisShîM<ShisShîM> .GiBoRîM<.GiBôR> ŚāVîV<ŚāVîV> LāhH<L> MigGiBoRê<.GiBôR> YiS:Rā'ēL<YiS:Rā'ēL>"],
[3008, ".KulLāM<.KoL> 'ăChuŹê<'ChŹ> CheReV<CheReV> M:LumM:Dê<LMD> MiL:ChāMâ<MiL:ChāMâ> 'îSh<'îSh> ChaR:Bô<CheReV> `aL<`aL>-Y:RēKô<YāRēK:> MiPaChaD<PaChaD> BalLêLôT<LaYLâ> Ś<Ś>"],
[3009, "'aPiR:YôN<'aPiR:YôN> `āSâ<`SH> Lô<L> HamMeLeK:<MeLeK:> Sh:LoMoH<Sh:LoMoH> Mē`ăZê<`ēZ> HalL:VāNôN<L:VāNôN>"],
[3010, "`amMûDâv<`amMûD> `āSâ<`SH> KeŚeF<.KeŚeF> R:FîDāTô<R:FîDâ> ŹāHāV<ŹāHāV> MeR:.KāVô<MeR:.KāV> 'aR:.GāMāN<'aR:.GāMāN> .TôKô<.TāWeK:> RāZûF<RZF> 'aHăVâ<'aHăVâ> MiB:NôT<BaT> Y:RûShāLāiM<Y:RûShāLaiM>"],
[3011, "Z:'ëNâ<YZ'> ûR:'ëNâ<R'H> B:NôT<BaT> ZiyYôN<ZiyYôN> BamMeLeK:<MeLeK:> Sh:LoMoH<Sh:LoMoH> Bā`ăThāRâ<`ăThāRâ> She`itTh:Râ<`ThR>-lLô<L> 'imMô<'ēM> B:YôM<YôM> ChăTunNāTô<ChăTunNâ> ûV:YôM<YôM> SiM:ChaT<SiM:Châ> LiBô<LēV> Ś<Ś>"],
[4001, "HinNāK:<HinNēH> YāFâ<YāFeH> Ra`:YāTî<Ra`:Yâ> HinNāK:<HinNēH> YāFâ<YāFeH> `êNaYiK:<`aYiN> YôNîM<YôNâ> MiBa`aD<Ba`aD> L:ZamMāTēK:<ZamMâ> Sa`:RēK:<Sēa`āR> .K:`ēDeR<`ēDeR> Hā`iźŹîM<`ēŹ> ShegGāL:Shû<.GLSh> MēHaR<HaR> .GiL:`āD<.GiL:`āD>"],
[4002, "ShinNaYiK:<ShēN> .K:`ēDeR<`ēDeR> HaqQ:ZûVôT<QZV> She`āLû<`LH> MiN<MiN>-HāRaCh:Zâ<RaCh:Zâ> ShekKulLāM<.KoL> MaT:'îMôT<.T'M> W:ShakKuLâ<ShakKûL> 'êN<'aYiN> BāHeM<B>"],
[4003, ".K:ChûTh<ChûTh> HasShāNî<ShāNî> SiF:ToTaYiK:<SāFâ> ûMiD:BāRêK:<MiD:BāR> Nā'WeH<Nā'WeH> .K:FeLaCh<PeLaCh> HāRimMôN<RimMôN> RaqQāTēK:<RaqQâ> MiBa`aD<Ba`aD> L:ZamMāTēK:<ZamMâ>"],
[4004, ".K:MiG:.DaL<MiG:.DāL> .DāWîD<.DāWiD> Zaûā'RēK:<Zaûā'R> BāNûY<BNH> L:TaL:PiyYôT<.TaL:PiyYôT> 'eLeF<'eLeF> HamMāGēN<MāGēN> .TāLûY<.TLH> `āLâv<`aL> .KoL<.KoL> ShiL:Thê<SheLeTh> HagGiBôRîM<.GiBôR>"],
[4005, "Sh:Nê<Sh:NaYiM> ShāDaYiK:<ShaD> .KiSh:Nê<Sh:NaYiM> `ŏFāRîM<`oFeR> .T:'ôMê<.T:'ôMîM> Z:ViyYâ<Z:ViyYâ> HāRô`îM<R`H> BasShôShanNîM<ShôShāN>"],
[4006, "`aD<`aD> SheyYāFû,aCh<PWCh> HayYôM<YôM> W:NāŚû<NWŚ> HazZ:LāLîM<ZēL> 'ēLeK:<HLK:> Lî<L> 'eL<'eL>-HaR<HaR> HamMôR<MoR> W:'eL<'eL>-.GiV:`aT<.GiV:`â> HalL:VôNâ<L:VôNâ>"],
[4007, ".KulLāK:<.KoL> YāFâ<YāFeH> Ra`:YāTî<Ra`:Yâ> ûMûM<MûM> 'êN<'aYiN> BāK:<B> Ś<Ś>"],
[4008, "'itTî<'ēT> MilL:VāNôN<L:VāNôN> .KalLâ<.KalLâ> 'itTî<'ēT> MilL:VāNôN<L:VāNôN> .TāVô'î<BW'> .TāShûRî<ShWR> MēRo'Sh<Ro'Sh> 'ăMāNâ<'ăMāNâ> MēRo'Sh<Ro'Sh> S:NîR<S:NîR> W:CheR:MôN<CheR:MôN> MimM:`oNôT<M:`oNâ> 'ăRāYôT<'ăRî> MēHaR:Rê<HaR> N:MēRîM<NāMēR>"],
[4009, "LiBaV:.TiNî<LVV> 'ăChoTî<'āChôT> KalLâ<.KalLâ> LiBaV:.TîNî<LVV> [1 B:'aChaD<'eChāD> 1] [2 B:'aChaT<'aChaT> 2] Mē`êNaYiK:<`aYiN> B:'aChaD<'eChāD> `ăNāQ<`ăNāQ> MizZaû:RoNāYiK:<Zaû:RôNîM>"],
[4010, "MaH<Mâ>-yYāFû<YFH> DoDaYiK:<.DôD> 'ăChoTî<'āChôT> KalLâ<.KalLâ> MaH<Mâ>-.ThoVû<ThWV> DoDaYiK:<.DôD> MiyYaYiN<YaYiN> W:Rê,aCh<Rê,aCh> Sh:MāNaYiK:<SheMeN> MikKāL<.KoL>-B:SāMîM<BoSeM>"],
[4011, "NoFeT<NoFeT> .TitThoF:Nâ<NThF> SiF:TôTaYiK:<SāFâ> .KalLâ<.KalLâ> .D:VaSh<.D:VaSh> W:ChāLāV<ChāLāV> .TaChaT<.TaChaT> L:ShôNēK:<LāShôN> W:Rê,aCh<Rê,aCh> SaL:MoTaYiK:<SaL:Mâ> .K:Rê,aCh<Rê,aCh> L:VāNôN<L:VāNôN> Ś<Ś>"],
[4012, ".GaN<.GaN> Nā`ûL<N`L> 'ăChoTî<'āChôT> KalLâ<.KalLâ> .GaL<.GaL> Nā`ûL<N`L> Ma`:YāN<Ma`:YāN> ChāTûM<ChTM>"],
[4013, "Sh:LāChaYiK:<SheLaCh> PaR:.DēŚ<PaR:.DēŚ> RimMôNîM<RimMôN> `iM<`iM> P:Rî<P:Rî> M:GāDîM<MeGeD> .K:FāRîM<.KoFeR> `iM<`iM>-N:RāDîM<NēR:.D:>"],
[4014, "NēR:.D:<NēR:.D:> W:KaR:.KoM<.KaR:.KoM> QāNeH<QāNeH> W:QinNāMôN<QinNāMôN> `iM<`iM> .KāL<.KoL>-`ăZê<`ēZ> L:VôNâ<L:VôNâ> MoR<MoR> Wa'ăHāLôT<'ŏHāL> `iM<`iM> .KāL<.KoL>-Rā'Shê<Ro'Sh> V:SāMîM<BoSeM>"],
[4015, "Ma`:YaN<Ma`:YāN> .GanNîM<.GaN> B:'ēR<B:'ēR> MaYiM<MaYiM> ChayYîM<ChaY> W:NoŹ:LîM<NŹL> MiN<MiN>-L:VāNôN<L:VāNôN>"],
[4016, "`ûRî<`WR> ZāFôN<ZāFôN> ûVô'î<BW'> TêMāN<.TêMāN> HāFîChî<PWCh> GanNî<.GaN> YiźŹ:Lû<NŹL> V:SāMâv<BoSeM> YāVo'<BW'> DôDî<.DôD> L:GanNô<.GaN> W:Yo'KaL<'KL> P:Rî<P:Rî> M:GāDâv<MeGeD>"],
[5001, "Bā'Tî<BW'> L:GanNî<.GaN> 'ăChoTî<'āChôT> KalLâ<.KalLâ> 'āRîTî<'RH> MôRî<MoR> `iM<`iM>-B:SāMî<BoSeM> 'āKaL:.Tî<'KL> Ya`:Rî<Ya`aR> `iM<`iM>-.DiV:Shî<.D:VaSh> ShāTîTî<ShTH> YêNî<YaYiN> `iM<`iM>-ChăLāVî<ChāLāV> 'iK:Lû<'KL> Rē`îM<Rē,a`> Sh:Tû<ShTH> W:ShiK:Rû<ShKR> .DôDîM<.DôD> Ś<Ś>"],
[5002, "'ăNî<'ăNî> Y:ShēNâ<YāShēN> W:LiBî<LēV> `ēR<`WR> QôL<QôL> .DôDî<.DôD> DôFēQ<.DFQ> PiT:Chî<PTCh>-Lî<L> 'ăChoTî<'āChôT> Ra`:YāTî<Ra`:Yâ> YôNāTî<YôNâ> TamMāTî<.TāM> SherRo'Shî<Ro'Sh> NiM:Lā'<ML'>-ThāL<ThaL> Q:ûuzZôTaY<Q:WuzZôT> R:ŚîŚê<RāŚîŚ> LāY:Lâ<LaY:Lâ>"],
[5003, "PāShaTh:.Tî<PShTh> 'eT<'ēT>-.KutTāN:.Tî<.K:ToNeT> 'êKāKâ<'êKāKâ> 'eL:BāShenNâ<LVSh> RāChaZ:.Tî<RChZ> 'eT<'ēT>-RaG:LaY<ReGeL> 'êKāKâ<'êKāKâ> 'ăThanN:FēM<ThNF>"],
[5004, ".DôDî<.DôD> ShāLaCh<ShLCh> YāDô<YāD> MiN<MiN>-HaChoR<ChoR> ûMē`aY<Mē`aYiM> HāMû<HMH> `āLâv<`aL>"],
[5005, "QaM:.Tî<QWM> 'ăNî<'ăNî> LiF:.To,aCh<PTCh> L:DôDî<.DôD> W:YāDaY<YāD> NāTh:Fû<NThF>-MôR<MoR> W:'eZ:B:`oTaY<'eZ:Ba`> MôR<MoR> `oVēR<`VR> `aL<`aL> .KaPôT<.KaF> HamMaN:`ûL<MaN:`ûL>"],
[5006, "PāTaCh:.Tî<PTCh> 'ăNî<'ăNî> L:DôDî<.DôD> W:DôDî<.DôD> ChāMaQ<ChMQ> `āVāR<`VR> NaF:Shî<NeFeSh> YāZ:'â<YZ'> V:DaB:Rô<.DVR> BiqQaSh:.TîHû<BQSh> W:Lo'<Lo'> M:Zā'TîHû<MZ'> Q:Rā'TîW<QR'> W:Lo'<Lo'> `āNāNî<`NH>"],
[5007, "M:Zā'uNî<MZ'> HasShoM:RîM<ShMR> HaśŚoV:VîM<ŚVV> Bā`îR<`îR> HikKûNî<NKH> F:Zā`ûNî<PZ`> NāS:'û<NS'> 'eT<'ēT>-R:DîDî<R:DîD> Mē`āLaY<`aL> ShoM:Rê<ShMR> HaChoMôT<ChôMâ>"],
[5008, "HiSh:Ba`:.Tî<ShV`> 'eT:KeM<'ēT> B:NôT<BaT> Y:RûShāLāiM<Y:RûShāLaiM> 'iM<'iM>-.TiM:Z:'û<MZ'> 'eT<'ēT>-.DôDî<.DôD> MaH<Mâ>-.TagGîDû<NGD> Lô<L> SheChôLaT<ChLH> 'aHăVâ<'aHăVâ> 'āNî<'ăNî>"],
[5009, "MaH<Mâ>-.DôDēK:<.DôD> MidDôD<.DôD> HayYāFâ<YāFeH> BanNāShîM<'isShâ> MaH<Mâ>-.DôDēK:<.DôD> MidDôD<.DôD> ShekKāKâ<.KāKâ> HiSh:Ba`:.TāNû<ShV`>"],
[5010, ".DôDî<.DôD> ZaCh<ZaCh> W:'āDôM<'āDoM> .DāGûL<.DGL> MēR:VāVâ<R:VāVâ>"],
[5011, "Ro'Shô<Ro'Sh> .KeTeM<.KeTeM> PāŹ<PaŹ> Q:ûzZôTâv<Q:WuzZôT> .TaL:.TalLîM<.TaL:.TalLîM> Sh:ChoRôT<ShāChoR> .Kā`ôRēV<`oRēV>"],
[5012, "`êNâv<`aYiN> .K:YôNîM<YôNâ> `aL<`aL>-'ăFîQê<'āFîQ> MāYiM<MaYiM> RoChăZôT<RChZ> BeChāLāV<ChāLāV> YoSh:VôT<YShV> `aL<`aL>-MilLē'T<MilLē'T>"],
[5013, "L:ChāYāW<L:Chî> .Ka`ăRûGaT<`ăRûGâ> HaBoSeM<BoSeM> MiG:.D:LôT<MiG:.DāL> MeR:QāChîM<MeR:QāCh> SiF:TôTâv<SāFâ> ShôShanNîM<ShûShaN> NoTh:FôT<NThF> MôR<MoR> `oVēR<`VR>"],
[5014, "YāDâv<YāD> .G:LîLê<.GāLîL> ŹāHāV<ŹāHāV> M:MulLā'îM<ML'> BatTaR:ShîSh<.TaR:ShîSh> Mē`âv<Mē`aYiM> `eSheT<`eSheT> ShēN<ShēN> M:`ulLeFeT<`LF> ŚaPîRîM<ŚaPîR>"],
[5015, "ShôQâv<ShôQ> `amMûDê<`amMûD> ShēSh<ShēSh> M:YuśŚāDîM<YŚD> `aL<`aL>-'aD:Nê<'eDeN>-FāŹ<PaŹ> MaR:'ēHû<MaR:'eH> .KalL:VāNôN<L:VāNôN> BāChûR<BChR> .Kā'ăRāŹîM<'eReŹ>"],
[5016, "ChikKô<ChēK:> MaM:TaqQîM<MaM:TaqQîM> W:KulLô<.KoL> MaChăMadDîM<MaCh:MāD> ŹeH<ŹeH> DôDî<.DôD> W:ŹeH<ŹeH> Rē`î<Rē,a`> B:NôT<BaT> Y:RûShāLāiM<Y:RûShāLaiM>"],
[6001, "'āNâ<'āN> HāLaK:<HLK:> .DôDēK:<.DôD> HayYāFâ<YāFeH> BanNāShîM<'isShâ> 'āNâ<'āN> PāNâ<PNH> DôDēK:<.DôD> ûN:VaQ:ShenNû<BQSh> `imMāK:<`iM>"],
[6002, ".DôDî<.DôD> YāRaD<YRD> L:GanNô<.GaN> La`ăRûGôT<`ăRûGâ> HaBoSeM<BoSeM> LiR:`ôT<R`H> BagGanNîM<.GaN> W:LiL:QoTh<LQTh> ShôShanNîM<ShûShaN>"],
[6003, "'ăNî<'ăNî> L:DôDî<.DôD> W:DôDî<.DôD> Lî<L> HāRo`eH<R`H> BasShôShanNîM<ShôShāN> Ś<Ś>"],
[6004, "YāFâ<YāFeH> 'atT:<'atT:> Ra`:YāTî<Ra`:Yâ> .K:TiR:Zâ<.TiR:Zâ> Nā'Wâ<Nā'WeH> .KîRûShāLāiM<Y:RûShāLaiM> 'ăYumMâ<'āYoM> .KanNiD:.GāLôT<.DGL>"],
[6005, "HāŚēBî<ŚVV> `êNaYiK:<`aYiN> MinNeG:.Dî<NeGeD> SheHēM<HēM> HiR:HîVuNî<RHV> Sa`:RēK:<Sē`āR> .K:`ēDeR<`ēDeR> Hā`iźŹîM<`ēŹ> ShegGāL:Shû<.GLSh> MiN<MiN>-HagGiL:`āD<.GiL:`āD>"],
[6006, "ShinNaYiK:<ShēN> .K:`ēDeR<`ēDeR> HāR:ChēLîM<RāChēL> She`āLû<`LH> MiN<MiN>-HāRaCh:Zâ<RaCh:Zâ> ShekKulLāM<.KoL> MaT:'îMôT<.T'M> W:ShakKuLâ<ShakKûL> 'êN<'aYiN> BāHeM<B>"],
[6007, ".K:FeLaCh<PeLaCh> HāRimMôN<RimMôN> RaqQāTēK:<RaqQâ> MiBa`aD<Ba`aD> L:ZamMāTēK:<ZamMâ>"],
[6008, "ShisShîM<ShisShîM> HēmMâ<HēM> mM:LāKôT<MaL:.Kâ> ûSh:MoNîM<Sh:MoNîM> PîLaG:ShîM<PîLeGeSh> Wa`ăLāMôT<`aL:Mâ> 'êN<'aYiN> MiŚ:PāR<MiŚ:PāR>"],
[6009, "'aChaT<'aChaT> Hî'<Hî'> YôNāTî<YôNâ> TamMāTî<.TāM> 'aChaT<'aChaT> Hî'<Hî'> L:'imMāhH<'ēM> BāRâ<BaR> Hî'<Hî'> L:YôLaD:.TāhH<YLD> Rā'ûHā<R'H> VāNôT<BaT> WaY:'asSh:RûHā<'ShR> M:LāKôT<MaL:.Kâ> ûFîLaG:ShîM<PîLeGeSh> WaY:HaL:LûHā<HLL> Ś<Ś>"],
[6010, "Mî<Mî>-Źo'T<Źo'T> HanNiSh:QāFâ<ShQF> .K:Mô<.K>-ShāChaR<ShaChaR> YāFâ<YāFeH> KalL:VāNâ<L:VāNâ> BāRâ<BaR> .KaChamMâ<ChamMâ> 'ăYumMâ<'āYoM> .KanNiD:.GāLôT<.DGL> Ś<Ś>"],
[6011, "'eL<'eL>-.GinNaT<.GinNâ> 'ĕGôŹ<'ĕGôŹ> YāRaD:.Tî<YRD> LiR:'ôT<R'H> B:'iBê<'ēV> HanNāChaL<NaChaL> LiR:'ôT<R'H> HăFāR:Châ<PRCh> HagGeFeN<.GeFeN> HēNēZû<NZZ> HāRimMoNîM<RimMôN>"],
[6012, "Lo'<Lo'> YāDa`:.Tî<YD`> NaF:Shî<NeFeSh> SāMaT:Nî<SYM> MaR:.K:VôT<MeR:.KāVâ> `amMî<`aM>-NāDîV<NāDîV>"],
[7001, "ShûVî<ShWV> ShûVî<ShWV> HasShûLamMîT<ShûLamMîT> ShûVî<ShWV> ShûVî<ShWV> W:NeChĕŹeH<ChŹH>-BāK:<B> MaH<Mâ>-.TeChĕŹû<ChŹH> BasShûLamMîT<ShûLamMîT> .KiM:ChoLaT<M:ChoLâ> HamMaChăNāYiM<MaChăNeH>"],
[7002, "MaH<Mâ>-yYāFû<YFH> F:`āMaYiK:<Pa`aM> BanN:`āLîM<Na`aL> BaT<BaT>-NāDîV<NāDîV> ChamMûQê<ChamMûQ> Y:RēKaYiK:<YāRēK:> .K:Mô<.K> ChăLā'îM<ChăLî> Ma`ăSēH<Ma`ăSeH> Y:Dê<YāD> 'āmMāN<'āmMāN>"],
[7003, "ShāR:RēK:<ShoR> 'agGaN<'agGāN> HaśŚaHaR<ŚaHaR> 'aL<'aL>-YeCh:ŚaR<ChŚR> HamMāŹeG<MeŹeG> BiTh:NēK:<BeTheN> `ăRēMaT<`ăRēMâ> ChitThîM<ChitThâ> ŚûGâ<ŚWG> BasShôShanNîM<ShôShāN>"],
[7004, "Sh:Nê<Sh:NaYiM> ShāDaYiK:<ShaD> .KiSh:Nê<Sh:NaYiM> `ŏFāRîM<`oFeR> .Tā'ŏMê<.T:'ôMîM> Z:ViyYâ<Z:ViyYâ>"],
[7005, "Zaûā'RēK:<Zaûā'R> .K:MiG:.DaL<MiG:.DāL> HasShēN<ShēN> `êNaYiK:<`aYiN> B:RēKôT<B:RēKâ> B:CheSh:BôN<CheSh:BôN> `aL<`aL>-Sha`aR<Sha`aR> BaT-RaBîM<BaT-RaBîM> 'aPēK:<'aF> .K:MiG:.DaL<MiG:.DāL> HalL:VāNôN<L:VāNôN> ZôFeH<ZFH> P:Nê<PāNeH> DamMāSeQ<.DamMeSeQ>"],
[7006, "Ro'ShēK:<Ro'Sh> `āLaYiK:<`aL> .KakKaR:MeL<.KaR:MeL> W:DalLaT<.DalLâ> Ro'ShēK:<Ro'Sh> .Kā'aR:.GāMāN<'aR:.GāMāN> MeLeK:<MeLeK:> 'āŚûR<'ŚR> BāR:HāThîM<RaHaTh>"],
[7007, "MaH<Mâ>-yYāFîT<YFH> ûMaH<Mâ>-.Nā`aM:.T:<N`M> 'aHăVâ<'aHăVâ> BatTa`ăNûGîM<.Ta`ăNûG>"],
[7008, "Źo'T<Źo'T> QôMāTēK:<QôMâ> .DāM:Tâ<.DMH> L:TāMāR<.TāMāR> W:ShāDaYiK:<ShaD> L:'aSh:.KoLôT<'eSh:.KôL>"],
[7009, "'āMaR:.Tî<'MR> 'e`ĕLeH<`LH> V:TāMāR<.TāMāR> 'oChăŹâ<'ChŹ> B:ŚaN:ŚinNâv<ŚaN:ŚaN> W:YiH:Yû<HYH>-Nā'<Nā'> ShāDaYiK:<ShaD> .K:'eSh:.K:LôT<'eSh:.KôL> HagGeFeN<.GeFeN> W:Rê,aCh<Rê,aCh> 'aPēK:<'aF> .KatTaPûChîM<.TaPû,aCh>"],
[7010, "W:ChikKēK:<ChēK:> .K:YêN<YaYiN> HatThôV<ThôV> HôLēK:<HLK:> L:DôDî<.DôD> L:MêShāRîM<MêShāRîM> .DôVēV<.DVV> SiF:Tê<SāFâ> Y:ShēNîM<YāShēN>"],
[7011, "'ăNî<'ăNî> L:DôDî<.DôD> W:`āLaY<`aL> .T:ShûQāTô<.T:ShûQâ> Ś<Ś>"],
[7012, "L:Kâ<HLK:> DôDî<.DôD> NēZē'<YZ'> HasSāDeH<SāDeH> NāLîNâ<LWN> BakK:FāRîM<.KoFeR>"],
[7013, "NaSh:.KîMâ<ShKM> LakK:RāMîM<.KeReM> NiR:'eH<R'H> 'iM<'iM> PāR:Châ<PRCh> HagGeFeN<.GeFeN> PitTaCh<PTCh> HaśŚ:MāDaR<Ś:MāDaR> HēNēZû<NZZ> HāRimMôNîM<RimMôN> ShāM<ShāM> 'etTēN<NTN> 'eT<'ēT>-.DoDaY<.DôD> LāK:<L>"],
[7014, "HadDûDā'îM<.DûDā'îM> NāT:Nû<NTN>-Rê,aCh<Rê,aCh> W:`aL<`aL>-P:TāChêNû<PeTaCh> .KāL<.KoL>-M:GāDîM<MeGeD> ChăDāShîM<ChāDāSh> .GaM<.GaM>-Y:ShāNîM<YāShāN> .DôDî<.DôD> ZāFaN:.Tî<ZFN> LāK:<L>"],
[8001, "Mî<Mî> YitTeN:Kā<NTN> .K:'āCh<'āCh> Lî<L> YôNēQ<YNQ> Sh:Dê<ShaD> 'imMî<'ēM> 'eM:Zā'ăKā<MZ'> VaChûZ<ChûZ> 'esShāQ:Kā<NShQ> .GaM<.GaM> Lo'<Lo'>-YāVûŹû<BWŹ> Lî<L>"],
[8002, "'eN:HāGăKā<NHG> 'ăVî'ăKā<BW'> 'eL<'eL>-BêT<BaYiT> 'imMî<'ēM> .T:LamM:DēNî<LMD> 'aSh:Q:Kā<ShQH> MiyYaYiN<YaYiN> HāReQaCh<ReQaCh> Mē`ăŚîŚ<`āŚîŚ> RimMoNî<RimMôN>"],
[8003, "S:Mo'Lô<S:Mo'L> .TaChaT<.TaChaT> Ro'Shî<Ro'Sh> WîMîNô<YāMîN> .T:ChaB:QēNî<ChVQ>"],
[8004, "HiSh:Ba`:.Tî<ShV`> 'eT:KeM<'ēT> B:NôT<BaT> Y:RûShāLāiM<Y:RûShāLaiM> MaH<Mâ>-.Tā`îRû<`WR> ûMaH<Mâ>-.T:`oR:Rû<`WR> 'eT<'ēT>-Hā'aHăVâ<'aHăVâ> `aD<`aD> ShetTeCh:PāZ<ChFZ> Ś<Ś>"],
[8005, "Mî<Mî> Źo'T<Źo'T> `oLâ<`LH> MiN<MiN>-HamMiD:BāR<MiD:BāR> MiT:RaPeQeT<RFQ> `aL<`aL>-.DôDāhH<.DôD> .TaChaT<.TaChaT> HatTaPû,aCh<.TaPû,aCh> `ôRaR:.TîKā<`WR> ShāmMâ<ShāM> ChiB:LaT:Kā<ChVL> 'imMeKā<'ēM> ShāmMâ<ShāM> ChiB:Lâ<ChVL> Y:LāDaT:Kā<YLD>"],
[8006, "SîMēNî<SYM> KaChôTāM<ChôTāM> `aL<`aL>-LiBeKā<LēV> .KaChôTāM<ChôTāM> `aL<`aL>-Ź:Rô`eKā<Ź:Rô,a`> .Kî<.Kî>-`aźŹâ<`aŹ> KamMāWeT<MāWeT> 'aHăVâ<'aHăVâ> QāShâ<QāSheH> KiSh:'ôL<Sh:'ôL> QiN:'â<QiN:'â> R:ShāFëHā<ReSheF> RiSh:Pê<ReSheF> 'ēSh<'ēSh> ShaL:HeVeT:Yâ<ShaL:HeVeT:Yâ>"],
[8007, "MaYiM<MaYiM> RaBîM<RaV> Lo'<Lo'> YûK:Lû<YKL> L:KaBôT<.KVH> 'eT<'ēT>-Hā'aHăVâ<'aHăVâ> ûN:HāRôT<NāHāR> Lo'<Lo'> YiSh:Th:FûHā<ShThF> 'iM<'iM>-YitTēN<NTN> 'îSh<'îSh> 'eT<'ēT>-.KāL<.KoL>-HôN<HôN> BêTô<BaYiT> Bā'aHăVâ<'aHăVâ> BôŹ<BWŹ> YāVûŹû<BWŹ> Lô<L> Ś<Ś>"],
[8008, "'āChôT<'āChôT> LāNû<L> Q:ThanNâ<QāThoN> W:ShāDaYiM<ShaD> 'êN<'aYiN> LāhH<L> MaH<Mâ>-.Na`ăSeH<`SH> La'ăChoTēNû<'āChôT> BayYôM<YôM> SheyY:DuBaR<.DVR>-BāhH<B>"],
[8009, "'iM<'iM>-ChôMâ<ChôMâ> Hî'<Hî'> NiV:NeH<BNH> `āLëHā<`aL> ThîRaT<ThîRâ> .KāŚeF<.KeŚeF> W:'iM<'iM>-.DeLeT<.DeLeT> Hî'<Hî'> NāZûR<ZWR> `āLëHā<`aL> Lû,aCh<Lû,aCh> 'āReŹ<'eReŹ>"],
[8010, "'ăNî<'ăNî> ChôMâ<ChôMâ> W:ShāDaY<ShaD> .KamMiG:.DāLôT<MiG:.DāL> 'āŹ<'āŹ> HāYîTî<HYH> V:`êNâv<`aYiN> .K:MôZ:'ēT<MZ'> ShāLôM<ShāLôM> F<F>"],
[8011, ".KeReM<.KeReM> HāYâ<HYH> LiSh:LoMoH<Sh:LoMoH> B:Va`aL_HāMôN<Ba`aL_HāMôN> NāTaN<NTN> 'eT<'ēT>-HakKeReM<.KeReM> LanNoTh:RîM<NThR> 'îSh<'îSh> YāVi'<BW'> B:FiR:Yô<P:Rî> 'eLeF<'eLeF> .KāŚeF<.KeŚeF>"],
[8012, ".KaR:Mî<.KeReM> ShelLî<L> L:FāNāY<PāNîM> Hā'eLeF<'eLeF> L:Kā<L> Sh:LoMoH<Sh:LoMoH> ûMā'TaYiM<Mē'â> L:NoTh:RîM<NThR> 'eT<'ēT>-PiR:Yô<P:Rî>"],
[8013, "HayYôSheVeT<YShV> BagGanNîM<.GaN> ChăVēRîM<ChāVēR> MaQ:ShîVîM<QShV> L:QôLēK:<QôL> HaSh:Mî`îNî<ShM`>"],
[8014, "B:RaCh<BRCh> .DôDî<.DôD> ûD:MēH<.DMH>-L:Kā<L> LiZ:Vî<Z:Vî> 'ô<'ô> L:`oFeR<`oFeR> Hā'ayYāLîM<'ayYāL> `aL<`aL> HāRê<HaR> V:SāMîM<BoSeM>"]
])
