Bib.ret([
[1001, "WaY:Hî<HYH> .D:VaR<.DāVāR>-YHWH<YHWH> 'eL<'eL>-YôNâ<YôNâ> VeN<BēN>-'ăMitTaY<'ăMitTaY> Lē'MoR<'MR>"],
[1002, "QûM<QWM> LēK:<HLK:> 'eL<'eL>-NîN:WēH<NîN:WēH> Hā`îR<`îR> HagG:DôLâ<.GāDôL> ûQ:Rā'<QR'> `āLëHā<`aL> .Kî<.Kî>-`āL:Tâ<`LH> Rā`āTāM<Rā`â> L:FāNāY<PāNîM>"],
[1003, "WayYāQāM<QWM> YôNâ<YôNâ> LiV:Ro,aCh<BRCh> .TaR:ShîShâ<.TaR:ShîSh> MilLiF:Nê<PāNeH> YHWH<YHWH> WayYēReD<YRD> YāFô<YāFô> WayYiM:Zā'<MZ'> 'āNiyYâ<'ŏNiyYâ> Bā'â<BW'> TaR:ShîSh<.TaR:ShîSh> WayYitTēN<NTN> S:KāRāhH<SāKāR> WayYēReD<YRD> BāhH<B> LāVô'<BW'> `imMāHeM<`iM> .TaR:ShîShâ<.TaR:ShîSh> MilLiF:Nê<PāNeH> YHWH<YHWH>"],
[1004, "WaYHWâ<YHWH> HēThîL<ThWL> Rû,aCh<Rû,aCh>-.G:DôLâ<.GāDôL> 'eL<'eL>-HayYāM<YāM> WaY:Hî<HYH> Śa`aR<Śa`aR>-.GāDôL<.GāDôL> BayYāM<YāM> W:Hā'ŏNiyYâ<'ŏNiyYâ> ChisSh:Vâ<ChShV> L:HisShāVēR<ShVR>"],
[1005, "WayYîR:'û<YR'> HamMalLāChîM<MalLāCh> WayYiŹ:`ăQû<Ź`Q> 'îSh<'îSh> 'eL<'eL>-'ĕLoHâv<'ĕLoHîM> WayYāThiLû<ThWL> 'eT<'ēT>-HakKēLîM<.K:Lî> 'ăSheR<'ăSheR> Bā'ŏNiyYâ<'ŏNiyYâ> 'eL<'eL>-HayYāM<YāM> L:HāQēL<QLL> Mē`ăLêHeM<`aL> W:YôNâ<YôNâ> YāRaD<YRD> 'eL<'eL>-YaR:.K:Tê<YaR:Kâ> HaśŚ:FîNâ<Ś:FîNâ> WayYiSh:.KaV<ShKV> WayYēRāDaM<RDM>"],
[1006, "WayYiQ:RaV<QRV> 'ēLâv<'eL> RaV<RaV> HaChoVēL<ChôVēL> WayYo'MeR<'MR> Lô<L> MaH<Mâ>-lL:Kā<L> NiR:.DāM<RDM> QûM<QWM> Q:Rā'<QR'> 'eL<'eL>-'ĕLoHëKā<'ĕLoHîM> 'ûLaY<'ûLaY> YiT:`asShēT<`ShT> Hā'ĕLoHîM<'ĕLoHîM> LāNû<L> W:Lo'<Lo'> No'VēD<'VD>"],
[1007, "WayYo'M:Rû<'MR> 'îSh<'îSh> 'eL<'eL>-Rē`ēHû<Rē,a`> L:Kû<HLK:> W:NaPîLâ<NFL> GôRāLôT<.GôRāL> W:NēD:`â<YD`> B:ShelL:Mî<Mî> HāRā`â<Rā`â> HaźŹo'T<Źo'T> LāNû<L> WayYaPiLû<NFL> .GôRāLôT<.GôRāL> WayYiPoL<NFL> HagGôRāL<.GôRāL> `aL<`aL>-YôNâ<YôNâ>"],
[1008, "WayYo'M:Rû<'MR> 'ēLâv<'eL> HagGîDâ<NGD>-.Nā'<Nā'> LāNû<L> Ba'ăSheR<'ăSheR> L:Mî<Mî>-HāRā`â<Rā`â> HaźŹo'T<Źo'T> LāNû<L> MaH<Mâ>-mM:La'K:.T:Kā<M:Lā'Kâ> ûMē'aYiN<'aYiN> .TāVô'<BW'> Mâ<Mâ> 'aR:ZeKā<'eReZ> W:'ê<'ê>-MiźŹeH<ŹeH> `aM<`aM> 'ātTâ<'atTâ>"],
[1009, "WayYo'MeR<'MR> 'ăLêHeM<'eL> `iV:Rî<`iV:Rî> 'āNoKî<'āNoKî> W:'eT<'ēT>-YHWH<YHWH> 'ĕLoHê<'ĕLoHîM> HasShāMaYiM<ShāMaYiM> 'ăNî<'ăNî> YāRē'<YR'> 'ăSheR<'ăSheR>-`āSâ<`SH> 'eT<'ēT>-HayYāM<YāM> W:'eT<'ēT>-HayYaBāShâ<YaBāShâ>"],
[1010, "WayYîR:'û<YR'> Hā'ăNāShîM<'îSh> YiR:'â<YiR:'â> G:DôLâ<.GāDôL> WayYo'M:Rû<'MR> 'ēLâv<'eL> MaH<Mâ>-źŹo'T<Źo'T> `āSîTā<`SH> .Kî<.Kî>-YāD:`û<YD`> Hā'ăNāShîM<'îSh> .Kî<.Kî>-MilLiF:Nê<PāNeH> YHWH<YHWH> Hû'<Hû'> VoRē,aCh<BRCh> .Kî<.Kî> HigGîD<NGD> LāHeM<L>"],
[1011, "WayYo'M:Rû<'MR> 'ēLâv<'eL> MaH<Mâ>-.Na`ăSeH<`SH> lLāK:<L> W:YiSh:.ToQ<ShTQ> HayYāM<YāM> Mē`āLêNû<`aL> .Kî<.Kî> HayYāM<YāM> HôLēK:<HLK:> W:Śo`ēR<Ś`R>"],
[1012, "WayYo'MeR<'MR> 'ăLêHeM<'eL> Sā'ûNî<NS'> WaHăThîLuNî<ThWL> 'eL<'eL>-HayYāM<YāM> W:YiSh:.ToQ<ShTQ> HayYāM<YāM> Mē`ăLêKeM<`aL> .Kî<.Kî> YôDē,a`<YD`> 'āNî<'ăNî> .Kî<.Kî> V:ShelLî<She> HaśŚa`aR<Śa`aR> HagGāDôL<.GāDôL> HaźŹeH<ŹeH> `ăLêKeM<`aL>"],
[1013, "WayYaCh:.T:Rû<ChTR> Hā'ăNāShîM<'îSh> L:HāShîV<ShWV> 'eL<'ēL>-HayYaBāShâ<YaBāShâ> W:Lo'<Lo'> YāKoLû<YKL> .Kî<.Kî> HayYāM<YāM> HôLēK:<HLK:> W:Śo`ēR<Ś`R> `ăLêHeM<`aL>"],
[1014, "WayYiQ:R:'û<QR'> 'eL<'eL>-YHWH<YHWH> WayYo'M:Rû<'MR> 'ānNâ<'ānNā'> YHWH<YHWH> 'aL<'aL>-Nā'<Nā'> No'V:Dâ<'VD> B:NeFeSh<NeFeSh> Hā'îSh<'îSh> HaźŹeH<ŹeH> W:'aL<'aL>-.TitTēN<NTN> `āLêNû<`aL> .DāM<.DāM> NāQî'<NāQî> .Kî<.Kî>-'atTâ<'atTâ> YHWH<YHWH> .Ka'ăSheR<'ăSheR> ChāFaZ:.Tā<ChFZ> `āSîTā<`SH>"],
[1015, "WayYiS:'û<NS'> 'eT<'ēT>-YôNâ<YôNâ> WaY:ThiLuHû<ThWL> 'eL<'eL>-HayYāM<YāM> WayYa`ăMoD<`MD> HayYāM<YāM> MiźŹa`:Pô<Źa`aF>"],
[1016, "WayYîR:'û<YR'> Hā'ăNāShîM<'îSh> YiR:'â<YiR:'â> G:DôLâ<.GāDôL> 'eT<'ēT>-YHWH<YHWH> WayYiŹ:B:Chû<ŹVCh>-ŹeVaCh<ŹeVaCh> LaYHWâ<YHWH> WayYidD:Rû<NDR> N:DāRîM<NeDeR>"],
[2001, "WaY:MaN<MNH> YHWH<YHWH> .DāG<.DāG> .GāDôL<.GāDôL> LiV:Lo,a`<BL`> 'eT<'ēT>-YôNâ<YôNâ> WaY:Hî<HYH> YôNâ<YôNâ> BiM:`ê<Mē`îM> HadDāG<.DāG> Sh:LoShâ<Sh:LoShâ> YāMîM<YôM> ûSh:LoShâ<Sh:LoShâ> LêLôT<LaYLâ>"],
[2002, "WayYiT:PalLēL<PLL> YôNâ<YôNâ> 'eL<'eL>-YHWH<YHWH> 'ĕLoHâv<'ĕLoHîM> MimM:`ê<Mē`îM> HadDāGâ<.DāGâ>"],
[2003, "WayYo'MeR<'MR> QāRā'Tî<QR'> MizZāRâ<ZāRâ> Lî<L> 'eL<'eL>-YHWH<YHWH> WayYa`ăNēNî<`NH> MiBeTheN<BeTheN> Sh:'ôL<Sh:'ôL> Shiûa`:.Tî<ShW`> ShāMa`:.Tā<ShM`> QôLî<QôL>"],
[2004, "WatTaSh:LîKēNî<ShLK:> M:ZûLâ<M:ZûLâ> BiL:VaV<LēVāV> YamMîM<YāM> W:NāHāR<NāHāR> Y:ŚoV:VēNî<ŚVV> .KāL<.KoL>-MiSh:BāRëKā<MiSh:BāR> W:GalLëKā<.GaL> `āLaY<`aL> `āVāRû<`VR>"],
[2005, "Wa'ăNî<'ăNî> 'āMaR:.Tî<'MR> NiG:RaSh:.Tî<.GRSh> MinNeGeD<NeGeD> `êNëKā<`aYiN> 'aK:<'aK:> 'ôŚîF<YŚF> L:HaBîTh<NVTh> 'eL<'eL>-HêKaL<HêKāL> QāD:SheKā<QoDeSh>"],
[2006, "'ăFāFûNî<'FF> MaYiM<MaYiM> `aD<`aD>-NeFeSh<NeFeSh> .T:HôM<.T:HôM> Y:ŚoV:VēNî<ŚVV> ŚûF<ŚûF> ChāVûSh<ChVSh> L:Ro'Shî<Ro'Sh>"],
[2007, "L:QiZ:Vê<QeZeV> HāRîM<HaR> YāRaD:.Tî<YRD> Hā'āReZ<'eReZ> B:RiChëHā<B:Rî,aCh> Va`ăDî<Ba`aD> L:`ôLāM<`ôLāM> WatTa`aL<`LH> MisShaChaT<ShaChaT> ChayYaY<ChayYîM> YHWH<YHWH> 'ĕLoHāY<'ĕLoHîM>"],
[2008, "B:HiT:`atThēF<`ThF> `āLaY<`aL> NaF:Shî<NeFeSh> 'eT<'ēT>-YHWH<YHWH> ŹāKāR:.Tî<ŹKR> WatTāVô'<BW'> 'ēLëKā<'eL> .T:FilLāTî<.T:FilLâ> 'eL<'eL>-HêKaL<HêKāL> QāD:SheKā<QoDeSh>"],
[2009, "M:ShamM:RîM<ShMR> HaV:Lê<HeVeL>-ShāW:'<ShāW:'> ChaŚ:.DāM<CheŚeD> Ya`ăŹoVû<`ŹV>"],
[2010, "Wa'ăNî<'ăNî> B:QôL<QôL> .TôDâ<.TôDâ> 'eŹ:B:Châ<ŹVCh>-lLāK:<L> 'ăSheR<'ăSheR> NāDaR:.Tî<NDR> 'ăShalLēMâ<ShLM> Y:Shû`āTâ<Y:Shû`â> LaYHWâ<YHWH> Ś<Ś>"],
[2011, "WayYo'MeR<'MR> YHWH<YHWH> LadDāG<.DāG> WayYāQē'<QY'> 'eT<'ēT>-YôNâ<YôNâ> 'eL<'eL>-HayYaBāShâ<YaBāShâ> F<F>"],
[3001, "WaY:Hî<HYH> D:VaR<.DāVāR>-YHWH<YHWH> 'eL<'eL>-YôNâ<YôNâ> ShēNîT<ShēNî> Lē'MoR<'MR>"],
[3002, "QûM<QWM> LēK:<HLK:> 'eL<'eL>-NîN:WēH<NîN:WēH> Hā`îR<`îR> HagG:DôLâ<.GāDôL> ûiQ:Rā'<QR'> 'ēLëHā<'eL> 'eT<'ēT>-HaqQ:Rî'â<Q:Rî'â> 'ăSheR<'ăSheR> 'āNoKî<'āNoKî> .DoVēR<.DVR> 'ēLëKā<'eL>"],
[3003, "WayYāQāM<QWM> YôNâ<YôNâ> WayYēLeK:<HLK:> 'eL<'eL>-NîN:WeH<NîN:WēH> .KiD:VaR<.DāVāR> YHWH<YHWH> W:NîN:WēH<NîN:WēH> HāY:Tâ<HYH> `îR<`îR>-.G:DôLâ<.GāDôL> Lē'LoHîM<'ĕLoHîM> MaHăLaK:<MaHăLāK:> Sh:LoSheT<Sh:LoShâ> YāMîM<YôM>"],
[3004, "WayYāCheL<ChLL> YôNâ<YôNâ> LāVô'<BW'> Vā`îR<`îR> MaHăLaK:<MaHăLāK:> YôM<YôM> 'eChāD<'eChāD> WayYiQ:Rā'<QR'> WayYo'MaR<'MR> `ôD<`ôD> 'aR:Bā`îM<'aR:Bā`îM> YôM<YôM> W:NîN:WēH<NîN:WēH> NeH:PāKeT<HFK:>"],
[3005, "WayYa'ăMîNû<'MN> 'aN:Shê<'îSh> NîN:WēH<NîN:WēH> Bē'LoHîM<'ĕLoHîM> WayYiQ:R:'û<QR'>-ZôM<ZôM> WayYiL:B:Shû<LVSh> SaqQîM<SaQ> MigG:DôLāM<.GāDôL> W:`aD<`aD>-Q:ThanNāM<QāThoN>"],
[3006, "WayYigGa`<NG`> HadDāVāR<.DāVāR> 'eL<'eL>-MeLeK<MeLeK:> NîN:WēH<NîN:WēH> WayYāQāM<QWM> MikKiŚ:'ô<.KiśŚē'> WayYa`ăVēR<`VR> 'adDaR:.Tô<'adDeReT> Mē`āLâv<`aL> WaY:KaŚ<.KŚH> SaQ<SaQ> WayYēSheV<YShV> `aL<`aL>-Hā'ēFeR<'ēFeR>"],
[3007, "WayYaŹ:`ēQ<Ź`Q> WayYo'MeR<'MR> B:NîN:WēH<NîN:WēH> MitTha`aM<Tha`aM> HamMeLeK:<MeLeK:> ûG:DoLâv<.GāDôL> Lē'MoR<'MR> Hā'āDāM<'āDāM> W:HaB:HēMâ<B:HēMâ> HaBāQāR<BāQāR> W:HazZo'N<Zo'N> 'aL<'aL>-YiTh:`ăMû<Th`M> M:'ûMâ<M:'ûMâ> 'aL<'aL>-YiR:`û<R`H> ûMaYiM<MaYiM> 'aL<'aL>-YiSh:.Tû<ShTH>"],
[3008, "W:YiT:.KaśŚû<.KŚH> SaqQîM<SaQ> Hā'āDāM<'āDāM> W:HaB:HēMâ<B:HēMâ> W:YiQ:R:'û<QR'> 'eL<'eL>-'ĕLoHîM<'ĕLoHîM> B:ChāŹ:Qâ<ChāŹ:Qâ> W:YāShuVû<ShWV> 'îSh<'îSh> MidDaR:.Kô<.DeReK:> HāRā`â<Rā`â> ûMiN<MiN>-HeChāMāŚ<ChāMāŚ> 'ăSheR<'ăSheR> B:KaPêHeM<.KaF>"],
[3009, "Mî<Mî>-YôDē,a`<YD`> YāShûV<ShWV> W:NiChaM<NChM> Hā'ĕLoHîM<'ĕLoHîM> W:ShāV<ShWV> MēChăRôN<ChāRôN> 'aPô<'aF> W:Lo'<Lo'> No'VēD<'VD>"],
[3010, "WayYaR:'<R'H> Hā'ĕLoHîM<'ĕLoHîM> 'eT<'ēT>-Ma`ăSêHeM<Ma`ăSeH> .Kî<.Kî>-ShāVû<ShWV> MidDaR:.KāM<.DeReK:> HāRā`â<Rā`â> WayYinNāCheM<NChM> Hā'ĕLoHîM<'ĕLoHîM> `aL<`aL>-HāRā`â<Rā`â> 'ăSheR<'ăSheR>-.DiBeR<.DVR> La`ăSôT<`SH>-LāHeM<L> W:Lo'<Lo'> `āSâ<`SH>"],
[4001, "WayYēRa`<R``> 'eL<'eL>-YôNâ<YôNâ> Rā`â<Rā`â> G:DôLâ<.GāDôL> WayYiChaR<ChRH> Lô<L>"],
[4002, "WayYiT:PalLēL<PLL> 'eL<'eL>-YHWH<YHWH> WayYo'MaR<'MR> 'ānNâ<'ānNā'> YHWH<YHWH> HăLô'<Lo'>-ŹeH<ŹeH> D:VāRî<.DāVāR> `aD<`aD>-HĕYôTî<HYH> `aL<`aL>-'aD:MāTî<'ăDāMâ> `aL<`aL>-.KēN<.KēN> QidDaM:.Tî<QDM> LiV:Ro,aCh<BRCh> .TaR:ShîShâ<.TaR:ShîSh> .Kî<.Kî> YāDa`:.Tî<YD`> .Kî<.Kî> 'atTâ<'atTâ> 'ēL<'ēL>-ChanNûN<ChanNûN> W:RaChûM<RaChûM> 'eReK:<'āRēK:> 'aPaYiM<'aF> W:RaV<RaV>-CheŚeD<CheŚeD> W:NiChāM<NChM> `aL<`aL>-HāRā`â<Rā`â>"],
[4003, "W:`atTâ<`atTâ> YHWH<YHWH> QaCh<LQCh>-Nā'<Nā'> 'eT<'ēT>-NaF:Shî<NeFeSh> MimMenNî<MiN> .Kî<.Kî> ThôV<ThôV> MôTî<MāWeT> MēChayYāY<ChayYîM> Ś<Ś>"],
[4004, "WayYo'MeR<'MR> YHWH<YHWH> HaHêThēV<YThV> ChāRâ<ChRH> LāK:<L>"],
[4005, "WayYēZē'<YZ'> YôNâ<YôNâ> MiN<MiN>-Hā`îR<`îR> WayYēSheV<YShV> MiqQeDeM<QeDeM> Lā`îR<`îR> WayYa`aS<`SH> Lô<L> ShāM<ShāM> ŚukKâ<ŚukKâ> WayYēSheV<YShV> .TaCh:.TëHā<.TaChaT> BazZēL<ZēL> `aD<`aD> 'ăSheR<'ăSheR> YiR:'eH<R'H> MaH<Mâ>-yYiH:YeH<HYH> Bā`îR<`îR>"],
[4006, "WaY:MaN<MNH> YHWH<YHWH>-'ĕLoHîM<'ĕLoHîM> QîQāYôN<QîQāYôN> WayYa`aL<`LH> Mē`aL<`aL> L:YôNâ<YôNâ> LiH:YôT<HYH> ZēL<ZēL> `aL<`aL>-Ro'Shô<Ro'Sh> L:HazZîL<NZL> Lô<L> MēRā`āTô<Rā`â> WayYiS:MaCh<SMCh> YôNâ<YôNâ> `aL<`aL>-HaqQîQāYôN<QîQāYôN> SiM:Châ<SiM:Châ> G:DôLâ<.GāDôL>"],
[4007, "WaY:MaN<MNH> Hā'ĕLoHîM<'ĕLoHîM> .TôLa`aT<.TôLa`aT> Ba`ăLôT<`LH> HasShaChaR<ShaChaR> LamMāChŏRāT<MāChŏRāT> WatTaK:<NKH> 'eT<'ēT>-HaqQîQāYôN<QîQāYôN> WayYîVāSh<YVSh>"],
[4008, "WaY:Hî<HYH> .KiŹ:Ro,aCh<ŹRCh> HasSheMeSh<SheMeSh> WaY:MaN<MNH> 'ĕLoHîM<'ĕLoHîM> Rû,aCh<Rû,aCh> QāDîM<QāDîM> ChăRîShîT<ChăRîShî> WatTaK:<NKH> HasSheMeSh<SheMeSh> `aL<`aL>-Ro'Sh<Ro'Sh> YôNâ<YôNâ> WayYiT:`alLāF<`LF> WayYiSh:'aL<Sh'L> 'eT<'ēT>-NaF:Shô<NeFeSh> LāMûT<MWT> WayYo'MeR<'MR> ThôV<ThôV> MôTî<MāWeT> MēChayYāY<ChayYîM>"],
[4009, "WayYo'MeR<'MR> 'ĕLoHîM<'ĕLoHîM> 'eL<'eL>-YôNâ<YôNâ> HaHêThēV<YThV> ChāRâ<ChRH>-L:Kā<L> `aL<`aL>-HaqQîQāYôN<QîQāYôN> WayYo'MeR<'MR> HêThēV<YThV> ChāRâ<ChRH>-Lî<L> `aD<`aD>-MāWeT<MāWeT>"],
[4010, "WayYo'MeR<'MR> YHWH<YHWH> 'atTâ<'atTâ> ChaŚ:.Tā<ChWŚ> `aL<`aL>-HaqQîQāYôN<QîQāYôN> 'ăSheR<'ăSheR> Lo'<Lo'>-`āMaL:.Tā<`ML> Bô<B> W:Lo'<Lo'> GidDaL:.Tô<.GDL> SheBiN<BēN>-LaY:Lâ<LaY:Lâ> HāYâ<HYH> ûViN<BēN>-LaY:Lâ<LaY:Lâ> 'āVāD<'VD>"],
[4011, "Wa'ăNî<'ăNî> Lo'<Lo'> 'āChûŚ<ChWŚ> `aL<`aL>-NîN:WēH<NîN:WēH> Hā`îR<`îR> HagG:DôLâ<.GāDôL> 'ăSheR<'ăSheR> YeSh<YēSh>-BāhH<B> HaR:BēH<RVH> MiSh:.TêM<Sh:.TaYiM>-`eS:RēH<`eS:RēH> RiBô<RiBô> 'āDāM<'āDāM> 'ăSheR<'ăSheR> Lo'<Lo'>-YāDa`<YD`> BêN<BaYiN>-Y:MîNô<YāMîN> LiS:Mo'Lô<S:Mo'L> ûV:HēMâ<B:HēMâ> RaBâ<RaV>"]
])
