Bib.ret([
[1001, ".D:VaR<.DāVāR>-YHWH<YHWH> 'ăSheR<'ăSheR> HāYâ<HYH> 'eL<'eL>-Yô'ēL<Yô'ēL> BeN<BēN>-P:Tû'ēL<P:Tû'ēL>"],
[1002, "ShiM:`û<ShM`>-Źo'T<Źo'T> HaźŹ:QēNîM<ŹāQēN> W:Ha'ăŹîNû<'ŹN> .KoL<.KoL> YôSh:Vê<YShV> Hā'āReZ<'eReZ> HeHāY:Tâ<HYH> źŹo'T<Źo'T> BîMêKeM<YôM> W:'iM<'iM> BîMê<YôM> 'ăVoTêKeM<'āV>"],
[1003, "`āLëHā<`aL> LiV:NêKeM<BēN> ŚaPēRû<ŚFR> ûV:NêKeM<BēN> LiV:NêHeM<BēN> ûV:NêHeM<BēN> L:DôR<.DôR> 'aChēR<'aChēR>"],
[1004, "YeTeR<YeTeR> HagGāŹāM<.GāŹāM> 'āKaL<'KL> Hā'aR:BeH<'aR:BeH> W:YeTeR<YeTeR> Hā'aR:BeH<'aR:BeH> 'āKaL<'KL> HayYāLeQ<YeLeQ> W:YeTeR<YeTeR> HayYeLeQ<YeLeQ> 'āKaL<'KL> HeChāŚîL<ChāŚîL>"],
[1005, "HāQîZû<QYZ> ShikKôRîM<ShikKôR> ûV:Kû<BKH> W:HêLiLû<YLL> .KāL<.KoL>-ShoTê<ShTH> YāYiN<YaYiN> `aL<`aL>-`āŚîŚ<`āŚîŚ> .Kî<.Kî> NiK:RaT<.KRT> MiPîKeM<PeH>"],
[1006, ".Kî<.Kî>-GôY<.GôY> `āLâ<`LH> `aL<`aL>-'aR:Zî<'eReZ> `āZûM<`āZûM> W:'êN<'aYiN> MiŚ:PāR<MiŚ:PāR> ShinNâv<ShēN> ShinNê<ShēN> 'aR:YēH<'aR:YēH> ûM:TalL:`ôT<M:TalL:`â> LāVî'<LāVî'> Lô<L>"],
[1007, "SāM<SYM> .GaF:Nî<.GeFeN> L:ShamMâ<ShamMâ> ûT:'ēNāTî<.T:'ēNâ> LiQ:ZāFâ<Q:ZāFâ> ChāSoF<ChSF> ChăSāFāhH<ChSF> W:HiSh:LîK:<ShLK:> HiL:BîNû<LVN> SāRîGëHā<SāRîG>"],
[1008, "'ĕLî<'LH> .KiV:TûLâ<B:TûLâ> ChăGuRaT<ChGR>-SaQ<SaQ> `aL<`aL>-Ba`aL<Ba`aL> N:`ûRëHā<N:`ûRîM>"],
[1009, "HāK:RaT<.KRT> MiN:Châ<MiN:Châ> WāNeŚeK:<NēŚeK:> MiBêT<BaYiT> YHWH<YHWH> 'āV:Lû<'VL> HakKoHăNîM<.KoHēN> M:ShāR:Tê<ShRT> YHWH<YHWH>"],
[1010, "ShudDaD<ShDD> SāDeH<SāDeH> 'āV:Lâ<'VL> 'ăDāMâ<'ăDāMâ> .Kî<.Kî> ShudDaD<ShDD> .DāGāN<.DāGāN> HôVîSh<YVSh> .TîRôSh<.TîRôSh> 'uM:LaL<'ML> YiZ:HāR<YiZ:HāR>"],
[1011, "HoVîShû<BWSh> 'ikKāRîM<'ikKāR> HêLîLû<YLL> .KoR:MîM<.KRM> `aL<`aL>-ChitThâ<ChitThâ> W:`aL<`aL>-S:`oRâ<S:`oRâ> .Kî<.Kî> 'āVaD<'VD> Q:ZîR<QāZîR> SāDeH<SāDeH>"],
[1012, "HagGeFeN<.GeFeN> HôVîShâ<YVSh> W:HatT:'ēNâ<.T:'ēNâ> 'uM:LāLâ<'ML> RimMôN<RimMôN> .GaM<.GaM>-.TāMāR<.TāMāR> W:TaPû,aCh<.TaPû,aCh> .KāL<.KoL>-`ăZê<`ēZ> HasSāDeH<SāDeH> YāVēShû<YVSh> .Kî<.Kî>-HoVîSh<BWSh> SāSôN<SāSôN> MiN<MiN>-B:Nê<BēN> 'āDāM<'āDāM> Ś<Ś>"],
[1013, "ChiG:Rû<ChGR> W:ŚiF:Dû<ŚFD> HakKoHăNîM<.KoHēN> HêLîLû<YLL> M:ShāR:Tê<ShRT> MiŹ:Bē,aCh<MiŹ:Bē,aCh> Bo'û<BW'> LîNû<LWN> VasSaqQîM<SaQ> M:ShāR:Tê<ShRT> 'ĕLoHāY<'ĕLoHîM> .Kî<.Kî> NiM:Na`<MN`> MiBêT<BaYiT> 'ĕLoHêKeM<'ĕLoHîM> MiN:Châ<MiN:Châ> WāNāŚeK:<NēŚeK:>"],
[1014, "QadD:Shû<QDSh>-ZôM<ZôM> QiR:'û<QR'> `ăZāRâ<`ăZāRâ> 'iŚ:Fû<'ŚF> Ź:QēNîM<ŹāQēN> .KoL<.KoL> YoSh:Vê<YShV> Hā'āReZ<'eReZ> BêT<BaYiT> YHWH<YHWH> 'ĕLoHêKeM<'ĕLoHîM> W:Źa`ăQû<Ź`Q> 'eL<'eL>-YHWH<YHWH>"],
[1015, "'ăHāhH<'ăHāhH> LayYôM<YôM> .Kî<.Kî> QāRôV<QāRôV> YôM<YôM> YHWH<YHWH> ûK:ShoD<ShoD> MiShadDaY<ShadDaY> YāVô'<BW'>"],
[1016, "HăLô'<Lo'> NeGeD<NeGeD> `êNêNû<`aYiN> 'oKeL<'oKeL> NiK:RāT<.KRT> MiBêT<BaYiT> 'ĕLoHêNû<'ĕLoHîM> SiM:Châ<SiM:Châ> WāGîL<.GîL>"],
[1017, "`āV:Shû<`VSh> F:RuDôT<P:RuDôT> .TaChaT<.TaChaT> MeG:R:FoTêHeM<MeG:RāFâ> NāShamMû<ShMM> 'oZāRôT<'ôZāR> NeHeR:Śû<HRŚ> MamM:GuRôT<MamM:GûRâ> .Kî<.Kî> HoVîSh<BWSh> .DāGāN<.DāGāN>"],
[1018, "MaH<Mâ>-.Ne'eN:Châ<'NCh> V:HēMâ<B:HēMâ> NāVoKû<BWK:> `eD:Rê<`ēDeR> VāQāR<BāQāR> .Kî<.Kî> 'êN<'aYiN> MiR:`eH<MiR:`eH> LāHeM<L> .GaM<.GaM>-`eD:Rê<`ēDeR> HazZo'N<Zo'N> Ne':ShāMû<'ShM>"],
[1019, "'ēLëKā<'eL> YHWH<YHWH> 'eQ:Rā'<QR'> .Kî<.Kî> 'ēSh<'ēSh> 'āK:Lâ<'KL> N:'ôT<Nā'â> MiD:BāR<MiD:BāR> W:LeHāVâ<LeHāVâ> LiHăThâ<LHTh> .KāL<.KoL>-`ăZê<`ēZ> HasSāDeH<SāDeH>"],
[1020, ".GaM<.GaM>-BaHăMôT<B:HēMâ> SāDeH<SāDeH> .Ta`ăRôG<`RG> 'ēLëKā<'eL> .Kî<.Kî> YāV:Shû<YVSh> 'ăFîQê<'āFîQ> MāYiM<MaYiM> W:'ēSh<'ēSh> 'āK:Lâ<'KL> N:'ôT<Nā'â> HamMiD:BāR<MiD:BāR> F<F>"],
[2001, ".TiQ:`û<.TQ`> ShôFāR<ShôFāR> B:ZiyYôN<ZiyYôN> W:HāRî`û<RW`> B:HaR<HaR> QāD:Shî<QoDeSh> YiR:.G:Źû<RGŹ> .KoL<.KoL> YoSh:Vê<YShV> Hā'āReZ<'eReZ> .Kî<.Kî>-Vā'<BW'> YôM<YôM>-YHWH<YHWH> .Kî<.Kî> QāRôV<QāRôV>"],
[2002, "YôM<YôM> ChoSheK:<ChoSheK:> Wa'ăFēLâ<'ăFēLâ> YôM<YôM> `āNāN<`āNāN> Wa`ăRāFeL<`ăRāFeL> .K:ShaChaR<ShaChaR> PāRuS<PRS> `aL<`aL>-HeHāRîM<HaR> `aM<`aM> RaV<RaV> W:`āZûM<`āZûM> .KāMoHû<.K> Lo'<Lo'> NiH:Yâ<HYH> MiN<MiN>-Hā`ôLāM<`ôLāM> W:'aChăRâv<'aChăRê> Lo'<Lo'> YôŚēF<YŚF> `aD<`aD>-Sh:Nê<ShāNâ> .DôR<.DôR> WāDôR<.DôR>"],
[2003, "L:FāNâv<PāNeH> 'āK:Lâ<'KL> 'ēSh<'ēSh> W:'aChăRâv<'aChăRê> .T:LaHēTh<LHTh> LeHāVâ<LeHāVâ> .K:GaN<.GaN>-`ēDeN<`ēDeN> Hā'āReZ<'eReZ> L:FāNâv<PāNeH> W:'aChăRâv<'aChăRê> MiD:BaR<MiD:BāR> Sh:MāMâ<Sh:MāMâ> W:GaM<.GaM>-P:LêThâ<P:LêThâ> Lo'<Lo'>-HāY:Tâ<HYH> lLô<L>"],
[2004, ".K:MaR:'ēH<MaR:'eH> ŚûŚîM<ŚûŚ> MaR:'ēHû<MaR:'eH> ûK:FāRāShîM<PāRāSh> .KēN<.KēN> Y:RûZûN<RWZ>"],
[2005, ".K:QôL<QôL> MaR:.KāVôT<MeR:.KāVâ> `aL<`aL>-Rā'Shê<Ro'Sh> HeHāRîM<HaR> Y:RaqQēDûN<RQD> .K:QôL<QôL> LaHaV<LaHaV> 'ēSh<'ēSh> 'oK:Lâ<'KL> QāSh<QaSh> .K:`aM<`aM> `āZûM<`āZûM> `ĕRûK:<`RK:> MiL:ChāMâ<MiL:ChāMâ>"],
[2006, "MiPāNâv<PāNeH> YāChîLû<ChWL> `amMîM<`aM> .KāL<.KoL>-PāNîM<PāNîM> QiB:Zû<QVZ> Fā'RûR<Pā'RûR>"],
[2007, ".K:GiBôRîM<.GiBôR> Y:RuZûN<RWZ> .K:'aN:Shê<'îSh> MiL:ChāMâ<MiL:ChāMâ> Ya`ăLû<`LH> ChôMâ<ChôMâ> W:'îSh<'îSh> BiD:RāKâv<.DeReK:> YēLēKûN<HLK:> W:Lo'<Lo'> Y:`aB:ThûN<`VTh> 'oR:ChôTāM<'oRaCh>"],
[2008, "W:'îSh<'îSh> 'āChîW<'āCh> Lo'<Lo'> YiD:ChāQûN<.DChQ> .GeVeR<.GeVeR> BiM:ŚilLāTô<M:ŚilLâ> YēLēKûN<HLK:> ûV:`aD<Ba`aD> HasSheLaCh<SheLaCh> YiPoLû<NFL> Lo'<Lo'> YiV:Zā`û<BZ`>"],
[2009, "Bā`îR<`îR> YāShoqQû<ShQQ> BaChôMâ<ChôMâ> Y:RuZûN<RWZ> BaBātTîM<BaYiT> Ya`ăLû<`LH> B:`aD<Ba`aD> HaChalLôNîM<ChalLôN> YāVo'û<BW'> .KagGanNāV<.GanNāV>"],
[2010, "L:FāNâv<PāNeH> RāG:Źâ<RGŹ> 'eReZ<'eReZ> Rā`ăShû<R`Sh> ShāMāYiM<ShāMaYiM> SheMeSh<SheMeSh> W:YāRē,aCh<YāRē,aCh> QāDāRû<QDR> W:KôKāVîM<.KôKāV> 'āŚ:Fû<'ŚF> NāG:HāM<NoGahH>"],
[2011, "WaYHWâ<YHWH> NāTaN<NTN> QôLô<QôL> LiF:Nê<PāNeH> ChêLô<ChaYiL> .Kî<.Kî> RaV<RaV> M:'oD<M:'oD> MaChăNēHû<MaChăNeH> .Kî<.Kî> `āZûM<`āZûM> `oSēH<`SH> D:VāRô<.DāVāR> .Kî<.Kî>-GāDôL<.GāDôL> YôM<YôM>-YHWH<YHWH> W:NôRā'<YR'> M:'oD<M:'oD> ûMî<Mî> Y:KîLenNû<.KWL>"],
[2012, "W:GaM<.GaM>-`atTâ<`atTâ> N:'uM<N:'uM>-YHWH<YHWH> ShuVû<ShWV> `āDaY<`aD> B:KāL<.KoL>-L:VaV:KeM<LēVāV> ûV:ZôM<ZôM> ûV:V:Kî<B:Kî> ûV:MiŚ:PēD<MiŚ:PēD>"],
[2013, "W:QiR:`û<QR`> L:VaV:KeM<LēVāV> W:'aL<'aL>-BiG:DêKeM<BeGeD> W:ShûVû<ShWV> 'eL<'eL>-YHWH<YHWH> 'ĕLoHêKeM<'ĕLoHîM> .Kî<.Kî>-ChanNûN<ChanNûN> W:RaChûM<RaChûM> Hû'<Hû'> 'eReK:<'āRēK:> 'aPaYiM<'aF> W:RaV<RaV>-CheŚeD<CheŚeD> W:NiChāM<NChM> `aL<`aL>-HāRā`â<Rā`â>"],
[2014, "Mî<Mî> YôDē,a`<YD`> YāShûV<ShWV> W:NiChāM<NChM> W:HiSh:'îR<Sh'R> 'aChăRâv<'aChăRê> B:RāKâ<B:RāKâ> MiN:Châ<MiN:Châ> WāNeŚeK:<NēŚeK:> LaYHWâ<YHWH> 'ĕLoHêKeM<'ĕLoHîM> F<F>"],
[2015, ".TiQ:`û<.TQ`> ShôFāR<ShôFāR> B:ZiyYôN<ZiyYôN> QadD:Shû<QDSh>-ZôM<ZôM> QiR:'û<QR'> `ăZāRâ<`ăZāRâ>"],
[2016, "'iŚ:Fû<'ŚF>-`āM<`aM> QadD:Shû<QDSh> QāHāL<QāHāL> QiV:Zû<QVZ> Ź:QēNîM<ŹāQēN> 'iŚ:Fû<'ŚF> `ôLāLîM<`ôLāL> W:YoN:Qê<YNQ> ShāDāYiM<ShaD> YēZē'<YZ'> ChāTāN<ChāTāN> MēCheD:Rô<CheDeR> W:KalLâ<.KalLâ> MēChuPāTāhH<ChuPâ>"],
[2017, "BêN<BaYiN> Hā'ûLāM<'ûLāM> W:LamMiŹ:Bē,aCh<MiŹ:Bē,aCh> YiV:.Kû<BKH> HakKoHăNîM<.KoHēN> M:ShāR:Tê<ShRT> YHWH<YHWH> W:Yo'M:Rû<'MR> ChûŚâ<ChWŚ> YHWH<YHWH> `aL<`aL>-`amMeKā<`aM> W:'aL<'aL>-.TitTēN<NTN> NaChăLāT:Kā<NaChăLâ> L:CheR:Pâ<CheR:Pâ> LiM:ShāL<MāShāL>-BāM<B> .GôYiM<.GôY> LāmMâ<LāmMâ> Yo'M:Rû<'MR> Vā`amMîM<`aM> 'ayYēH<'ayYēH> 'ĕLoHêHeM<'ĕLoHîM>"],
[2018, "WaY:QanNē'<QN'> YHWH<YHWH> L:'aR:Zô<'eReZ> WayYaCh:MoL<ChML> `aL<`aL>-`amMô<`aM>"],
[2019, "WayYa`aN<`NH> YHWH<YHWH> WayYo'MeR<'MR> L:`amMô<`aM> HiN:Nî<HinNēH> ShoLē,aCh<ShLCh> LāKeM<L> 'eT<'ēT>-HadDāGāN<.DāGāN> W:HatTîRôSh<.TîRôSh> W:HayYiZ:HāR<YiZ:HāR> ûS:Va`:.TeM<SV`> 'oTô<'ēT> W:Lo'<Lo'>-'etTēN<NTN> 'eT:KeM<'ēT> `ôD<`ôD> CheR:Pâ<CheR:Pâ> BagGôYiM<.GôY>"],
[2020, "W:'eT<'ēT>-HazZ:FôNî<Z:FôNî> 'aR:ChîQ<RChQ> Mē`ăLêKeM<`aL> W:HidDaCh:.TîW<NDCh> 'eL<'eL>-'eReZ<'eReZ> ZiyYâ<ZiyYâ> ûSh:MāMâ<Sh:MāMâ> 'eT<'ēT>-PāNâv<PāNeH> 'eL<'eL>-HayYāM<YāM> HaqQaD:MoNî<QaD:MôNî> W:ŚoFô<ŚôF> 'eL<'eL>-HayYāM<YāM> Hā'aChăRôN<'aChăRôN> W:`āLâ<`LH> Vā':Shô<B:'oSh> W:Ta`aL<`LH> ZaChăNāTô<ZaChăNâ> .Kî<.Kî> HiG:.DîL<.GDL> La`ăSôT<`SH>"],
[2021, "'aL<'aL>-.TîR:'î<YR'> 'ăDāMâ<'ăDāMâ> .GîLî<.GYL> ûS:MāChî<SMCh> .Kî<.Kî>-HiG:.DîL<.GDL> YHWH<YHWH> La`ăSôT<`SH>"],
[2022, "'aL<'aL>-.TîR:'û<YR'> BaHăMôT<B:HēMâ> SāDaY<SāDaY> .Kî<.Kî> DāSh:'û<.DSh'> N:'ôT<Nā'â> MiD:BāR<MiD:BāR> .Kî<.Kî>-`ēZ<`ēZ> NāSā'<NS'> FiR:Yô<P:Rî> .T:'ēNâ<.T:'ēNâ> WāGeFeN<.GeFeN> NāT:Nû<NTN> ChêLāM<ChaYiL>"],
[2023, "ûV:Nê<BēN> ZiyYôN<ZiyYôN> .GîLû<.GYL> W:SiM:Chû<SMCh> BaYHWâ<YHWH> 'ĕLoHêKeM<'ĕLoHîM> .Kî<.Kî>-NāTaN<NTN> LāKeM<L> 'eT<'ēT>-HamMôReH<MôReH> LiZ:DāQâ<Z:DāQâ> WayYôReD<YRD> LāKeM<L> .GeSheM<.GeSheM> MôReH<MôReH> ûMaL:QôSh<MaL:QôSh> BāRi'ShôN<Ri'ShôN>"],
[2024, "ûMāL:'û<ML'> HagGŏRāNôT<.GoReN> BāR<BaR> W:HēShîQû<ShWQ> HaY:QāVîM<YeQeV> .TîRôSh<.TîRôSh> W:YiZ:HāR<YiZ:HāR>"],
[2025, "W:ShilLaM:.Tî<ShLM> LāKeM<L> 'eT<'ēT>-HasShāNîM<ShāNâ> 'ăSheR<'ăSheR> 'āKaL<'KL> Hā'aR:BeH<'aR:BeH> HayYeLeQ<YeLeQ> W:HeChāŚîL<ChāŚîL> W:HagGāŹāM<.GāŹāM> ChêLî<ChaYiL> HagGāDôL<.GāDôL> 'ăSheR<'ăSheR> ShilLaCh:.Tî<ShLCh> BāKeM<B>"],
[2026, "Wa'ăKaL:.TeM<'KL> 'āKôL<'KL> W:SāVô,a`<SV`> W:HilLaL:.TeM<HLL> 'eT<'ēT>-ShēM<ShēM> YHWH<YHWH> 'ĕLoHêKeM<'ĕLoHîM> 'ăSheR<'ăSheR>-`āSâ<`SH> `imMāKeM<`iM> L:HaF:Lî'<PL'> W:Lo'<Lo'>-YēVoShû<BWSh> `amMî<`aM> L:`ôLāM<`ôLāM>"],
[2027, "WîDa`:.TeM<YD`> .Kî<.Kî> V:QeReV<QeReV> YiS:Rā'ēL<YiS:Rā'ēL> 'āNî<'ăNî> Wa'ăNî<'ăNî> YHWH<YHWH> 'ĕLoHêKeM<'ĕLoHîM> W:'êN<'aYiN> `ôD<`ôD> W:Lo'<Lo'>-YēVoShû<BWSh> `amMî<`aM> L:`ôLāM<`ôLāM> Ś<Ś>"],
[3001, "W:HāYâ<HYH> 'aChăRê<'aChăRê>-KēN<.KēN> 'eSh:PôK:<ShFK:> 'eT<'ēT>-RûChî<Rû,aCh> `aL<`aL>-.KāL<.KoL>-BāSāR<BāSāR> W:NiB:'û<NV'> B:NêKeM<BēN> ûV:NôTêKeM<BaT> ŹiQ:NêKeM<ŹāQēN> ChăLoMôT<ChăLôM> YaChăLoMûN<ChLM> BaChûRêKeM<BāChûR> CheŹ:YoNôT<ChiźŹāYôN> YiR:'û<R'H>"],
[3002, "W:GaM<.GaM> `aL<`aL>-Hā`ăVāDîM<`eVeD> W:`aL<`aL>-HasSh:FāChôT<ShiF:Châ> BayYāMîM<YôM> HāHēmMâ<HēM> 'eSh:PôK:<ShFK:> 'eT<'ēT>-RûChî<Rû,aCh>"],
[3003, "W:NāTatTî<NTN> MôF:TîM<MôFēT> BasShāMaYiM<ShāMaYiM> ûVā'āReZ<'eReZ> .DāM<.DāM> Wā'ēSh<'ēSh> W:TîMăRôT<.TîMāRâ> `āShāN<`āShāN>"],
[3004, "HasSheMeSh<SheMeSh> YēHāFēK:<HFK:> L:ChoSheK:<ChoSheK:> W:HayYāRē,aCh<YāRē,aCh> L:DāM<.DāM> LiF:Nê<PāNeH> Bô'<BW'> YôM<YôM> YHWH<YHWH> HagGāDôL<.GāDôL> W:HanNôRā'<YR'>"],
[3005, "W:HāYâ<HYH> .KoL<.KoL> 'ăSheR<'ăSheR>-YiQ:Rā'<QR'> B:ShēM<ShēM> YHWH<YHWH> YimMāLēTh<MLTh> .Kî<.Kî> B:HaR<HaR>-ZiyYôN<ZiyYôN> ûVîRûShāLaiM<Y:RûShāLaiM> .TiH:YeH<HYH> F:LêThâ<P:LêThâ> .Ka'ăSheR<'ăSheR> 'āMaR<'MR> YHWH<YHWH> ûVasS:RîDîM<SāRîD> 'ăSheR<'ăSheR> YHWH<YHWH> QoRē'<QR'>"],
[4001, ".Kî<.Kî> HinNēH<HinNēH> BayYāMîM<YôM> HāHēmMâ<HēM> ûVā`ēT<`ēT> HaHî'<Hî'> 'ăSheR<'ăSheR> [1 'āShûV<ShWV> 1] [2 'āShîV<ShWV> 2] 'eT<'ēT>-Sh:VûT<Sh:VûT> Y:HûDâ<Y:HûDâ> WîRûShāLāiM<Y:RûShāLaiM>"],
[4002, "W:QiBaZ:.Tî<QVZ> 'eT<'ēT>-.KāL<.KoL>-HagGôYiM<.GôY> W:HôRaD:.TîM<YRD> 'eL<'eL>-`ēMeQ<`ēMeQ> Y:HôShāFāTh<Y:HôShāFāTh> W:NiSh:PaTh:.Tî<ShFTh> `imMāM<`iM> ShāM<ShāM> `aL<`aL>-`amMî<`aM> W:NaChăLāTî<NaChăLâ> YiS:Rā'ēL<YiS:Rā'ēL> 'ăSheR<'ăSheR> PiźŹ:Rû<PŹR> VagGôYiM<.GôY> W:'eT<'ēT>-'aR:Zî<'eReZ> ChilLēQû<ChLQ>"],
[4003, "W:'eL<'eL>-`amMî<`aM> YadDû<YDD> GôRāL<.GôRāL> WayYitT:Nû<NTN> HayYeLeD<YeLeD> BaźŹôNâ<ŹNH> W:HayYaL:.Dâ<YaL:.Dâ> MāK:Rû<MKR> VayYaYiN<YaYiN> WayYiSh:.Tû<ShTH>"],
[4004, "W:GaM<.GaM> Mâ<Mâ>-'atTeM<'atTeM> Lî<L> ZoR<ZoR> W:ZîDôN<ZîDôN> W:KoL<.KoL> .G:LîLôT<.G:LîLâ> P:LāSheT<P:LeSheT> HagG:MûL<.G:MûL> 'atTeM<'atTeM> M:ShalL:MîM<ShLM> `āLāY<`aL> W:'iM<'iM>-.GoM:LîM<.GML> 'atTeM<'atTeM> `āLaY<`aL> QaL<QaL> M:HēRâ<M:HēRâ> 'āShîV<ShWV> .G:MuL:KeM<.G:MûL> B:Ro'Sh:KeM<Ro'Sh>"],
[4005, "'ăSheR<'ăSheR>-.KaŚ:Pî<.KeŚeF> ûŹ:HāVî<ŹāHāV> L:QaCh:.TeM<LQCh> ûMaChăMadDaY<MaCh:MāD> HatThoVîM<ThôV> HăVē'TeM<BW'> L:HêK:LêKeM<HêKāL>"],
[4006, "ûV:Nê<BēN> Y:HûDâ<Y:HûDâ> ûV:Nê<BēN> Y:RûShāLaiM<Y:RûShāLaiM> M:KaR:.TeM<MKR> LiV:Nê<BēN> HayY:WāNîM<Y:WāNî> L:Ma`aN<L:Ma`aN> HaR:ChîQāM<RChQ> Mē`aL<`aL> .G:VûLāM<.G:VûL>"],
[4007, "HiN:Nî<HinNēH> M:`îRāM<`WR> MiN<MiN>-HamMāQôM<MāQôM> 'ăSheR<'ăSheR>-M:KaR:.TeM<MKR> 'oTāM<'ēT> ShāmMâ<ShāM> WaHăShiVoTî<ShWV> G:MuL:KeM<.G:MûL> B:Ro'Sh:KeM<Ro'Sh>"],
[4008, "ûMāKaR:.Tî<MKR> 'eT<'ēT>-B:NêKeM<BēN> W:'eT<'ēT>-B:NôTêKeM<BaT> B:YaD<YāD> B:Nê<BēN> Y:HûDâ<Y:HûDâ> ûM:KāRûM<MKR> LiSh:Vā'YiM<Sh:Vā'îM> 'eL<'eL>-.GôY<.GôY> RāChôQ<RāChôQ> .Kî<.Kî> YHWH<YHWH> .DiBēR<.DVR> Ś<Ś>"],
[4009, "QiR:'û<QR'>-Źo'T<Źo'T> BagGôYiM<.GôY> QadD:Shû<QDSh> MiL:ChāMâ<MiL:ChāMâ> Hā`îRû<`WR> HagGiBôRîM<.GiBôR> YigG:Shû<NGSh> Ya`ăLû<`LH> .KoL<.KoL> 'aN:Shê<'îSh> HamMiL:ChāMâ<MiL:ChāMâ>"],
[4010, ".KotTû<.KTT> 'itTêKeM<'ēT> LaChăRāVôT<CheReV> ûMaŹ:M:RoTêKeM<MaŹ:MēRâ> LiR:MāChîM<RoMaCh> HaChalLāSh<ChalLāSh> Yo'MaR<'MR> .GiBôR<.GiBôR> 'āNî<'ăNî>"],
[4011, "`ûShû<`WSh> WāVo'û<BW'> KāL<.KoL>-HagGôYiM<.GôY> MiśŚāVîV<ŚāVîV> W:NiQ:BāZû<QVZ> ShāmMâ<ShāM> HaN:ChaT<NChT> YHWH<YHWH> .GiBôRëKā<.GiBôR>"],
[4012, "Yē`ôRû<`WR> W:Ya`ăLû<`LH> HagGôYiM<.GôY> 'eL<'eL>-`ēMeQ<`ēMeQ> Y:HôShāFāTh<Y:HôShāFāTh> .Kî<.Kî> ShāM<ShāM> 'ēShēV<YShV> LiSh:PoTh<ShFTh> 'eT<'ēT>-.KāL<.KoL>-HagGôYiM<.GôY> MiśŚāVîV<ŚāVîV>"],
[4013, "ShiL:Chû<ShLCh> MagGāL<MagGāL> .Kî<.Kî> VāShaL<BShL> QāZîR<QāZîR> Bo'û<BW'> R:Dû<YRD> .Kî<.Kî>-MāL:'â<ML'> .GaT<.GaT> HēShîQû<ShWQ> HaY:QāVîM<YeQeV> .Kî<.Kî> RaBâ<RaBâ> Rā`āTāM<Rā`â>"],
[4014, "HăMôNîM<HāMôN> HăMôNîM<HāMôN> B:`ēMeQ<`ēMeQ> HeChāRûZ<ChāRûZ> .Kî<.Kî> QāRôV<QāRôV> YôM<YôM> YHWH<YHWH> B:`ēMeQ<`ēMeQ> HeChāRûZ<ChāRûZ>"],
[4015, "SheMeSh<SheMeSh> W:YāRē,aCh<YāRē,aCh> QāDāRû<QDR> W:KôKāVîM<.KôKāV> 'āŚ:Fû<'ŚF> NāG:HāM<NoGahH>"],
[4016, "WaYHWâ<YHWH> MizZiyYôN<ZiyYôN> YiSh:'āG<Sh'G> ûMîRûShāLaiM<Y:RûShāLaiM> YitTēN<NTN> QôLô<QôL> W:Rā`ăShû<R`Sh> ShāMaYiM<ShāMaYiM> Wā'āReZ<'eReZ> WaYHWâ<YHWH> MaChăŚeH<MaCh:ŚeH> L:`amMô<`aM> ûMā`ôŹ<Mā`ôŹ> LiV:Nê<BēN> YiS:Rā'ēL<YiS:Rā'ēL>"],
[4017, "WîDa`:.TeM<YD`> .Kî<.Kî> 'ăNî<'ăNî> YHWH<YHWH> 'ĕLoHêKeM<'ĕLoHîM> ShoKēN<ShKN> B:ZiyYôN<ZiyYôN> HaR<HaR>-QāD:Shî<QoDeSh> W:HāY:Tâ<HYH> Y:RûShāLaiM<Y:RûShāLaiM> QoDeSh<QoDeSh> W:ŹāRîM<ŹWR> Lo'<Lo'>-Ya`aV:Rû<`VR>-VāhH<B> `ôD<`ôD> Ś<Ś>"],
[4018, "W:HāYâ<HYH> VayYôM<YôM> HaHû'<Hû'> YitTh:Fû<NThF> HeHāRîM<HaR> `āŚîŚ<`āŚîŚ> W:HagG:Vā`ôT<.GiV:`â> .TēLaK:Nâ<HLK:> ChāLāV<ChāLāV> W:KāL<.KoL>-'ăFîQê<'āFîQ> Y:HûDâ<Y:HûDâ> YēL:Kû<HLK:> MāYiM<MaYiM> ûMa`:YāN<Ma`:YāN> MiBêT<BaYiT> YHWH<YHWH> YēZē'<YZ'> W:HiSh:Qâ<ShQH> 'eT<'ēT>-NaChaL<NaChaL> HasShitThîM<ShitThîM>"],
[4019, "MiZ:RaYiM<MiZ:RaYiM> LiSh:MāMâ<Sh:MāMâ> TiH:YeH<HYH> We'ĕDôM<'ĕDôM> L:MiD:BaR<MiD:BāR> Sh:MāMâ<Sh:MāMâ> .TiH:YeH<HYH> MēChăMaŚ<ChāMāŚ> B:Nê<BēN> Y:HûDâ<Y:HûDâ> 'ăSheR<'ăSheR>-ShāF:Kû<ShFK:> DāM<.DāM>-NāQî'<NāQî> B:'aR:ZāM<'eReZ>"],
[4020, "WîHûDâ<Y:HûDâ> L:`ôLāM<`ôLāM> .TēShēV<YShV> WîRûShāLaiM<Y:RûShāLaiM> L:DôR<.DôR> WāDôR<.DôR>"],
[4021, "W:NiqQêTî<NQH> .DāMāM<.DāM> Lo'<Lo'>-NiqQêTî<NQH> WaYHWâ<YHWH> ShoKēN<ShKN> B:ZiyYôN<ZiyYôN>"]
])
