Bib.ret([
[1001, "'êKâ<'êKâ> YāSh:Vâ<YShV> VāDāD<BāDāD> Hā`îR<`îR> RaBāTî<RaBâ> `āM<`aM> HāY:Tâ<HYH> .K:'aL:MāNâ<'aL:MāNâ> RaBāTî<RaBâ> VagGôYiM<.GôY> SāRāTî<SāRâ> BamM:DîNôT<M:DîNâ> HāY:Tâ<HYH> LāMaŚ<MaŚ> Ś<Ś>"],
[1002, "BāKô<BKH> TiV:.KeH<BKH> BalLaY:Lâ<LaY:Lâ> W:DiM:`āTāhH<.DiM:`â> `aL<`aL> LeChĕYāhH<L:Chî> 'êN<'aYiN>-LāhH<L> M:NaChēM<NChM> MikKāL<.KoL>-'oHăVëHā<'HV> .KāL<.KoL>-Rē`ëHā<Rē,a`> BāG:Dû<BGD> VāhH<B> HāYû<HYH> LāhH<L> L:'oY:VîM<'YV> Ś<Ś>"],
[1003, ".GāL:Tâ<.GLH> Y:HûDâ<Y:HûDâ> Mē`oNî<`ŏNî> ûMēRoV<RoV> `ăVoDâ<`ăVôDâ> Hî'<Hî'> YāSh:Vâ<YShV> VagGôYiM<.GôY> Lo'<Lo'> MāZ:'â<MZ'> MāNô,aCh<MāNô,aCh> .KāL<.KoL>-RoD:FëHā<RDF> HisSîGûHā<NSG> BêN<BaYiN> HamM:ZāRîM<MēZaR> Ś<Ś>"],
[1004, ".DaR:Kê<.DeReK:> ZiyYôN<ZiyYôN> 'ăVēLôT<'āVēL> MiB:Lî<B:Lî> Bā'ê<BW'> Mô`ēD<Mô`ēD> .KāL<.KoL>-Sh:`āRëHā<Sha`aR> ShôMēMîN<ShMM> .KoHăNëHā<.KoHēN> Ne'ĕNāChîM<'NCh> B:TûLoTëHā<B:TûLâ> .NûGôT<YGH> W:Hî'<Hî'> MaR<MRR>-LāhH<L> Ś<Ś>"],
[1005, "HāYû<HYH> ZāRëHā<ZaR> L:Ro'Sh<Ro'Sh> 'oY:VëHā<'YV> ShāLû<ShLH> .Kî<.Kî>-YHWH<YHWH> HôGāhH<YGH> `aL<`aL> RoV<RoV>-P:Shā`ëHā<PeSha`> `ôLāLëHā<`ôLāL> HāL:Kû<HLK:> Sh:Vî<Sh:Vî> LiF:Nê<PāNîM>-ZāR<ZaR> Ś<Ś>"],
[1006, "WayYēZē'<YZ'> [1 MiN<MiN>-VaT<BaT>- 1] [2 MiBaT<BaT>- 2]ZiyYôN<ZiyYôN> .KāL<.KoL>-HăDāRāhH<HāDāR> HāYû<HYH> SāRëHā<SaR> .K:'ayYāLîM<'ayYāL> Lo'<Lo'>-MāZ:'û<MZ'> MiR:`eH<MiR:`eH> WayYēL:Kû<HLK:> V:Lo'<Lo'>-Ko,aCh<.Ko,aCh> LiF:Nê<PāNeH> RôDēF<RDF> Ś<Ś>"],
[1007, "ŹāK:Râ<ŹKR> Y:RûShāLaiM<Y:RûShāLaiM> Y:Mê<YôM> `āN:YāhH<`ŏNî> ûM:RûDëHā<MāRûD> .KoL<.KoL> MaChăMuDëHā<MaChăMûD> 'ăSheR<'ăSheR> HāYû<HYH> MîMê<YôM> QeDeM<QeDeM> BiN:FoL<NFL> `amMāhH<`aM> B:YaD<YāD>-ZāR<ZaR> W:'êN<'aYiN> `ôŹēR<`ŹR> LāhH<L> Rā'ûHā<R'H> ZāRîM<ZaR> SāChăQû<SChQ> `aL<`aL> MiSh:BatTeHā<MiSh:BāT> Ś<Ś>"],
[1008, "ChēTh:'<ChēTh:'> ChāTh:'â<ChTh'> Y:RûShāLaiM<Y:RûShāLaiM> `aL<`aL>-.KēN<.KēN> L:NîDâ<NidDâ> HāYāTâ<HYH> .KāL<.KoL>-M:KaB:DëHā<.KVD> HiźŹîLûHā<ŹLL> .Kî<.Kî>-Rā'û<R'H> `eR:WāTāhH<`eR:Wâ> .GaM<.GaM>-Hî'<Hî'> Ne'eN:Châ<'NCh> WatTāShāV<ShWV> 'āChôR<'āChôR> Ś<Ś>"],
[1009, "ThuM:'āTāhH<ThuM:'â> B:ShûLëHā<ShûL> Lo'<Lo'> ŹāK:Râ<ŹKR> 'aChăRîTāhH<'aChăRîT> WatTēReD<YRD> P:Lā'îM<PeLe'> 'êN<'aYiN> M:NaChēM<NChM> LāhH<L> R:'ēH<R'H> YHWH<YHWH> 'eT<'ēT>-`āN:Yî<`ŏNî> .Kî<.Kî> HiG:.DîL<.GDL> 'ôYēV<'YV> Ś<Ś>"],
[1010, "YāDô<YāD> PāRaS<PRS> ZāR<ZaR> `aL<`aL> .KāL<.KoL>-MaChăMadDëHā<MaCh:MāD> .Kî<.Kî>-Rā'ăTâ<R'H> GôYiM<.GôY> Bā'û<BW'> MiQ:.DāShāhH<MiQ:.DāSh> 'ăSheR<'ăSheR> ZiûîTâ<ZWH> Lo'<Lo'>-YāVo'û<BW'> VaqQāHāL<QāHāL> LāK:<L> Ś<Ś>"],
[1011, ".KāL<.KoL>-`amMāhH<`aM> Ne'ĕNāChîM<'NCh> M:VaqQ:ShîM<BQSh> LeCheM<LeCheM> NāT:Nû<NTN> [1 MaChăMôdDêHeM<MaChăMoD> 1] [2 MaChăMadDêHeM<MaChăMaD> 2] B:'oKeL<'oKeL> L:HāShîV<ShWV> NāFeSh<NeFeSh> R:'ēH<R'H> YHWH<YHWH> W:HaBîThâ<NVTh> .Kî<.Kî> HāYîTî<HYH> ŹôLēLâ<ŹLL> Ś<Ś>"],
[1012, "Lô'<Lo'> 'ăLêKeM<'eL> .KāL<.KoL>-`oV:Rê<`VR> DeReK:<.DeReK:> HaBîThû<NVTh> ûR:'û<R'H> 'iM<'iM>-YēSh<YēSh> MaK:'ôV<MaK:'ôV> .K:MaK:'oVî<MaK:'ôV> 'ăSheR<'ăSheR> `ôLaL<`LL> Lî<L> 'ăSheR<'ăSheR> HôGâ<YGH> YHWH<YHWH> B:YôM<YôM> ChăRôN<ChāRôN> 'aPô<'aF> Ś<Ś>"],
[1013, "MimMāRôM<MāRôM> ShāLaCh<ShLCh>-'ēSh<'ēSh> B:`aZ:MoTaY<`eZeM> WayYiR:.DenNâ<RDH> PāRaS<PRS> ReSheT<ReSheT> L:RaG:LaY<ReGeL> HĕShîVaNî<ShWV> 'āChôR<'āChôR> N:TāNaNî<NTN> ShoMēMâ<ShMM> .KāL<.KoL>-HayYôM<YôM> .DāWâ<.DāWeH> Ś<Ś>"],
[1014, "NiS:QaD<SQD> `oL<`oL> P:Shā`aY<PeSha`> B:YāDô<YāD> YiS:.TāR:Gû<SRG> `āLû<`LH> `aL<`aL>-Zaûā'Rî<Zaûā'R> HiK:ShîL<.KShL> .KoChî<.Ko,aCh> N:TāNaNî<NTN> 'ăDoNāY<'ăDoNāY> BîDê<YāD> Lo'<Lo'>-'ûKaL<YKL> QûM<QWM> Ś<Ś>"],
[1015, "ŚilLâ<ŚLH> KāL<.KoL>-'aBîRaY<'aBîR> 'ăDoNāY<'ăDoNāY> B:QiR:Bî<QeReV> QāRā'<QR'> `āLaY<`aL> Mô`ēD<Mô`ēD> LiSh:BoR<ShVR> BaChûRāY<BāChûR> .GaT<.GaT> .DāRaK:<.DRK:> 'ăDoNāY<'ăDoNāY> LiV:TûLaT<B:TûLâ> BaT<BaT>-Y:HûDâ<Y:HûDâ> Ś<Ś>"],
[1016, "`aL<`aL>-'ēlLeH<'ēlLeH> 'ăNî<'ăNî> VôKiyYâ<BKH> `êNî<`aYiN> `êNî<`aYiN> YoR:Dâ<YRD> mMaYiM<MaYiM> .Kî<.Kî>-RāChaQ<RChQ> MimMenNî<MiN> M:NaChēM<NChM> MēShîV<ShWV> NaF:Shî<NeFeSh> HāYû<HYH> VāNaY<BēN> ShôMēMîM<ShMM> .Kî<.Kî> GāVaR<.GVR> 'ôYēV<'YV> Ś<Ś>"],
[1017, "PēR:Sâ<PRS> ZiyYôN<ZiyYôN> B:YāDëHā<YāD> 'êN<'aYiN> M:NaChēM<NChM> LāhH<L> Ziûâ<ZWH> YHWH<YHWH> L:Ya`ăQoV<Ya`ăQoV> Ś:VîVâv<ŚāVîV> ZāRâv<ZaR> HāY:Tâ<HYH> Y:RûShāLaiM<Y:RûShāLaiM> L:NidDâ<NidDâ> BêNêHeM<BaYiN> Ś<Ś>"],
[1018, "ZadDîQ<ZadDîQ> Hû'<Hû'> YHWH<YHWH> .Kî<.Kî> FîHû<PeH> MāRîTî<MRH> ShiM:`û<ShM`>-Nā'<Nā'> KāL<.KoL>-[1 `amMîM<`aM> 1] [2 Hā`amMîM<`aM> 2] ûR:'û<R'H> MaK:'oVî<MaK:'ôV> B:TûLoTaY<B:TûLâ> ûVaChûRaY<BāChûR> HāL:Kû<HLK:> VasSheVî<Sh:Vî> Ś<Ś>"],
[1019, "QāRā'Tî<QR'> LaM:'aHăVaY<'HV> HēmMâ<HēM> RimMûNî<RMH> .KoHăNaY<.KoHēN> ûŹ:QēNaY<ŹāQēN> Bā`îR<`îR> .GāWā`û<.GW`> .Kî<.Kî>-ViQ:Shû<BQSh> 'oKeL<'oKeL> LāMô<L> W:YāShîVû<ShWV> 'eT<'ēT>-NaF:ShāM<NeFeSh> Ś<Ś>"],
[1020, "R:'ēH<R'H> YHWH<YHWH> .Kî<.Kî>-ZaR<ZRR>-Lî<L> Mē`aY<Mē`aYiM> ChŏMaR:MāRû<ChMR> NeH:PaK:<HFK:> LiBî<LēV> B:QiR:Bî<QeReV> .Kî<.Kî> MāRô<MRH> MāRîTî<MRH> MiChûZ<ChûZ> ShikK:Lâ<ShKL>-CheReV<CheReV> BaBaYiT<BaYiT> .KamMāWeT<MāWeT> Ś<Ś>"],
[1021, "ShāM:`û<ShM`> .Kî<.Kî> Ne'ĕNāChâ<'NCh> 'āNî<'ăNî> 'êN<'aYiN> M:NaChēM<NChM> Lî<L> .KāL<.KoL>-'oY:VaY<'YV> ShāM:`û<ShM`> Rā`āTî<Rā`â> SāSû<SWS> .Kî<.Kî> 'atTâ<'atTâ> `āSîTā<`SH> HēVē'Tā<BW'> YôM<YôM>-QāRā'Tā<QR'> W:YiH:Yû<HYH> KāMôNî<.K> Ś<Ś>"],
[1022, ".TāVo'<BW'> KāL<.KoL>-Rā`āTāM<Rā`â> L:FāNëKā<PāNeH> W:`ôLēL<`LL> LāMô<L> .Ka'ăSheR<'ăSheR> `ôLaL:.Tā<`LL> Lî<L> `aL<`aL> .KāL<.KoL>-P:Shā`āY<PeSha`> .Kî<.Kî>-RaBôT<RaV> 'aN:ChoTaY<'ăNāChâ> W:LiBî<LēV> DaûāY<.DaûāY> F<F>"],
[2001, "'êKâ<'êKâ> Yā`îV<`WV> B:'aPô<'aF> 'ăDoNāY<'ăDoNāY> 'eT<'ēT>-BaT<BaT>-ZiyYôN<ZiyYôN> HiSh:LîK:<ShLK:> MisShāMaYiM<ShāMaYiM> 'eReZ<'eReZ> .TiF:'eReT<.TiF:'eReT> YiS:Rā'ēL<YiS:Rā'ēL> W:Lo'<Lo'>-ŹāKaR<ŹKR> HăDoM<HăDoM>-RaG:Lâv<ReGeL> B:YôM<YôM> 'aPô<'aF> Ś<Ś>"],
[2002, "BilLa`<BL`> 'ăDoNāY<'ăDoNāY> [1 Lo'<Lo'> 1] [2 W:Lo'<Lo'> 2] ChāMaL<ChML> 'ēT<'ēT> .KāL<.KoL>-N:'ôT<Nā'â> Ya`ăQoV<Ya`ăQoV> HāRaŚ<HRŚ> B:`eV:RāTô<`eV:Râ> MiV:Z:Rê<MiV:ZāR> VaT<BaT>-Y:HûDâ<Y:HûDâ> HigGî,a`<NG`> Lā'āReZ<'eReZ> ChilLēL<ChLL> MaM:LāKâ<MaM:LāKâ> W:SāRëHā<SaR> Ś<Ś>"],
[2003, ".GāDa`<.GD`> BāChŏRî<ChŏRî>-'aF<'aF> .KoL<.KoL> QeReN<QeReN> YiS:Rā'ēL<YiS:Rā'ēL> HēShîV<ShWV> 'āChôR<'āChôR> Y:MîNô<YāMîN> MiP:Nê<PāNeH> 'ôYēV<'YV> WayYiV:`aR<B`R> B:Ya`ăQoV<Ya`ăQoV> .K:'ēSh<'ēSh> LeHāVâ<LeHāVâ> 'āK:Lâ<'KL> ŚāVîV<ŚāVîV> Ś<Ś>"],
[2004, ".DāRaK:<.DRK:> QaSh:.Tô<QeSheT> .K:'ôYēV<'YV> NizZāV<NZV> Y:MîNô<YāMîN> .K:ZāR<ZaR> WayYaHăRoG<HRG> .KoL<.KoL> MaChăMadDê<MaCh:MāD>-`āYiN<`aYiN> B:'oHeL<'oHeL> BaT<BaT>-ZiyYôN<ZiyYôN> ShāFaK:<ShFK:> .Kā'ēSh<'ēSh> ChăMāTô<ChēMâ> Ś<Ś>"],
[2005, "HāYâ<HYH> 'ăDoNāY<'ăDoNāY> .K:'ôYēV<'YV> BilLa`<BL`> YiS:Rā'ēL<YiS:Rā'ēL> BilLa`<BL`> .KāL<.KoL>-'aR:M:NôTëHā<'aR:MôN> ShiChēT<ShChT> MiV:ZāRâv<MiV:ZāR> WayYeReV<RVH> B:VaT<BaT>-Y:HûDâ<Y:HûDâ> .Ta'ăNiyYâ<.Ta'ăNiyYâ> Wa'ăNiyYâ<'ăNiyYâ> Ś<Ś>"],
[2006, "WayYaCh:MoŚ<ChMŚ> .KagGaN<.GaN> SukKô<SoK:> ShiChēT<ShChT> Mô`ăDô<Mô`ēD> ShikKaCh<ShKCh> YHWH<YHWH> B:ZiyYôN<ZiyYôN> Mô`ēD<Mô`ēD> W:ShaBāT<ShaBāT> WayYiN:'aZ<N'Z> B:Źa`aM<Źa`aM>-'aPô<'aF> MeLeK:<MeLeK:> W:KoHēN<.KoHēN> Ś<Ś>"],
[2007, "ŹāNaCh<ŹNCh> 'ăDoNāY<'ăDoNāY> MiŹ:B:Chô<MiŹ:Bē,aCh> Ni'ēR<N'R> MiQ:.DāShô<MiQ:.DāSh> HiŚ:.GîR<ŚGR> B:YaD<YāD>-'ôYēV<'YV> ChôMoT<ChôMâ> 'aR:M:NôTëHā<'aR:MôN> QôL<QôL> NāT:Nû<NTN> B:VêT<BaYiT>-YHWH<YHWH> .K:YôM<YôM> Mô`ēD<Mô`ēD> Ś<Ś>"],
[2008, "ChāShaV<ChShV> YHWH<YHWH> L:HaSh:ChîT<ShChT> ChôMaT<ChôMâ> BaT<BaT>-ZiyYôN<ZiyYôN> NāThâ<NThH> QāW<QaW> Lo'<Lo'>-HēShîV<ShWV> YāDô<YāD> MiBalLē,a`<BL`> WayYa'ăVeL<'VL>-ChēL<ChêL> W:ChôMâ<ChôMâ> YaCh:.DāW<YaCh:.DāW> 'uM:LāLû<'ML> Ś<Ś>"],
[2009, "ThāV:`û<ThV`> Vā'āReZ<'eReZ> Sh:`āRëHā<Sha`aR> 'iBaD<'VD> W:ShiBaR<ShVR> B:RîChëHā<B:Rî,aCh> MaL:.KāhH<MeLeK:> W:SāRëHā<SaR> VagGôYiM<.GôY> 'êN<'aYiN> .TôRâ<.TôRâ> .GaM<.GaM>-N:Vî'ëHā<NāVî'> Lo'<Lo'>-MāZ:'û<MZ'> ChāŹôN<ChāŹôN> Mê:HWâ<YHWH> Ś<Ś>"],
[2010, "YēSh:Vû<YShV> Lā'āReZ<'eReZ> YidD:Mû<.DMM> ŹiQ:Nê<ŹāQēN> VaT<BaT>-ZiyYôN<ZiyYôN> He`ĕLû<`LH> `āFāR<`āFāR> `aL<`aL>-Ro'ShāM<Ro'Sh> ChāG:Rû<ChGR> SaqQîM<SaQ> HôRîDû<YRD> Lā'āReZ<'eReZ> Ro'ShāN<Ro'Sh> B:TûLoT<B:TûLâ> Y:RûShāLāiM<Y:RûShāLaiM> Ś<Ś>"],
[2011, ".KāLû<.KLH> VadD:Mā`ôT<.DiM:`â> `êNaY<`aYiN> ChŏMaR:M:Rû<ChMR> Mē`aY<Mē`aYiM> NiSh:PaK:<ShFK:> Lā'āReZ<'eReZ> .K:VēDî<.KāVēD> `aL<`aL>-SheVeR<SheVeR> BaT<BaT>-`amMî<`aM> Bē`āThēF<`ThF> `ôLēL<`ôLēL> W:YôNēQ<YNQ> BiR:ChoVôT<R:ChôV> QiR:Yâ<QiR:Yâ> Ś<Ś>"],
[2012, "L:'imMoTāM<'ēM> Yo'M:Rû<'MR> 'ayYēH<'ayYēH> .DāGāN<.DāGāN> WāYāYiN<YaYiN> B:HiT:`atTh:FāM<`ThF> .KeChāLāL<ChāLāL> BiR:ChoVôT<R:ChôV> `îR<`îR> B:HiSh:.TaPēK:<ShFK:> NaF:ShāM<NeFeSh> 'eL<'eL>-ChêQ<ChêQ> 'imMoTāM<'ēM> Ś<Ś>"],
[2013, "Mâ<Mâ>-'ă`îDēK:<`WD> Mâ<Mâ> 'ăDamMeH<.DMH>-lLāK:<L> HaBaT<BaT> Y:RûShāLaiM<Y:RûShāLaiM> Mâ<Mâ> 'aSh:WeH<ShWH>-lLāK:<L> Wa'ăNaChăMēK:<NChM> B:TûLaT<B:TûLâ> BaT<BaT>-ZiyYôN<ZiyYôN> .Kî<.Kî>-GāDôL<.GāDôL> .KayYāM<YāM> ShiV:RēK:<SheVeR> Mî<Mî> YiR:Pā'<RF'>-LāK:<L> Ś<Ś>"],
[2014, "N:Vî'aYiK:<NāVî'> ChāŹû<ChŹH> LāK:<L> ShāW:'<ShāW:'> W:TāFēL<.TāFēL> W:Lo'<Lo'>-GilLû<.GLH> `aL<`aL>-`ăWoNēK:<`āWoN> L:HāShîV<ShWV> [1 Sh:VîTēK:<Sh:VîT> 1] [2 Sh:VûTēK:<Sh:VûT> 2] WayYeChĕŹû<ChŹH> LāK:<L> MaS:'ôT<MasSā'> ShāW:'<ShāW:'> ûMadDûChîM<MadDûChîM> Ś<Ś>"],
[2015, "ŚāF:Qû<ŚFQ> `āLaYiK:<`aL> .KaPaYiM<.KaF> .KāL<.KoL>-`oV:Rê<`VR> DeReK:<.DeReK:> ShāR:Qû<ShRQ> WayYāNi`û<NW`> Ro'ShāM<Ro'Sh> `aL<`aL>-BaT<BaT> Y:RûShāLāiM<Y:RûShāLaiM> HăŹo'T<Źo'T> Hā`îR<`îR> SheyYo'M:Rû<'MR> .K:LîLaT<.KāLîL> YoFî<YŏFî> MāSôS<MāSôS> L:KāL<.KoL>-Hā'āReZ<'eReZ> Ś<Ś>"],
[2016, "PāZû<PZH> `āLaYiK:<`aL> PîHeM<PeH> .KāL<.KoL>-'ôY:VaYiK:<'YV> ShāR:Qû<ShRQ> WayYaChaR:Qû<ChRQ>-ShēN<ShēN> 'āM:Rû<'MR> BilLā`:Nû<BL`> 'aK:<'aK:> ŹeH<ŹeH> HayYôM<YôM> SheqQiûîNuHû<QWH> MāZā'Nû<MZ'> Rā'îNû<R'H> Ś<Ś>"],
[2017, "`āSâ<`SH> YHWH<YHWH> 'ăSheR<'ăSheR> ŹāMāM<ŹMM> BizZa`<BZ`> 'eM:RāTô<'eM:Râ> 'ăSheR<'ăSheR> Ziûâ<ZWH> MîMê<YôM>-QeDeM<QeDeM> HāRaŚ<HRŚ> W:Lo'<Lo'> ChāMāL<ChML> WaY:SamMaCh<SMCh> `āLaYiK:<`aL> 'ôYēV<'YV> HēRîM<RWM> QeReN<QeReN> ZāRāYiK:<ZaR> Ś<Ś>"],
[2018, "Zā`aQ<Z`Q> LiBāM<LēV> 'eL<'eL>-'ăDoNāY<'ăDoNāY> ChôMaT<ChôMâ> BaT<BaT>-ZiyYôN<ZiyYôN> HôRîDî<YRD> KanNaChaL<NaChaL> .DiM:`â<.DiM:`â> YôMāM<YôMāM> WāLaY:Lâ<LaY:Lâ> 'aL<'aL>-.TitT:Nî<NTN> FûGaT<PûGâ> LāK:<L> 'aL<'aL>-.TidDoM<.DMM> BaT<BaT>-`êNēK:<`aYiN> Ś<Ś>"],
[2019, "QûMî<QWM> RonNî<RNN> [1 ValLaYiL<LaY:Lâ> 1] [2 ValLaY:Lâ<LaY:Lâ> 2] L:Ro'Sh<Ro'Sh> 'aSh:MuRôT<'aSh:MûRâ> ShiF:Kî<ShFK:> KamMaYiM<MaYiM> LiBēK:<LēV> NoKaCh<NoKaCh> P:Nê<PāNeH> 'ăDoNāY<'ăDoNāY> S:'î<NS'> 'ēLâv<'eL> .KaPaYiK:<.KaF> `aL<`aL>-NeFeSh<NeFeSh> `ôLāLaYiK:<`ôLāL> Hā`ăThûFîM<`ThF> B:Rā`āV<Rā`āV> B:Ro'Sh<Ro'Sh> .KāL<.KoL>-ChûZôT<ChûZ> Ś<Ś>"],
[2020, "R:'ēH<R'H> YHWH<YHWH> W:HaBîThâ<NVTh> L:Mî<Mî> `ôLaL:.Tā<`LL> .KoH<.KoH> 'iM<'iM>-.To'KaL:Nâ<'KL> NāShîM<'isShâ> PiR:YāM<P:Rî> `oLăLê<`ôLēL> ThiPuChîM<ThiPûChîM> 'iM<'iM>-YēHāRēG<HRG> B:MiQ:.DaSh<MiQ:.DāSh> 'ăDoNāY<'ăDoNāY> .KoHēN<.KoHēN> W:NāVî'<NāVî'> Ś<Ś>"],
[2021, "ShāK:Vû<ShKV> Lā'āReZ<'eReZ> ChûZôT<ChûZ> Na`aR<Na`aR> W:ŹāQēN<ŹāQēN> B:TûLoTaY<B:TûLâ> ûVaChûRaY<BāChûR> NāF:Lû<NFL> VeChāReV<CheReV> HāRaG:.Tā<HRG> B:YôM<YôM> 'aPeKā<'aF> ThāVaCh:.Tā<ThVCh> Lo'<Lo'> ChāMāL:.Tā<ChML> Ś<Ś>"],
[2022, ".TiQ:Rā'<QR'> K:YôM<YôM> Mô`ēD<Mô`ēD> M:GûRaY<MāGûR> MiśŚāVîV<ŚāVîV> W:Lo'<Lo'> HāYâ<HYH> B:YôM<YôM> 'aF<'aF>-YHWH<YHWH> PāLîTh<PāLîTh> W:SāRîD<SāRîD> 'ăSheR<'ăSheR>-ThiPaCh:.Tî<ThFCh> W:RiBîTî<RVH> 'oY:Vî<'YV> KilLāM<.KLH> F<F>"],
[3001, "'ăNî<'ăNî> HagGeVeR<.GeVeR> Rā'â<R'H> `ŏNî<`ŏNî> B:ShēVeTh<ShēVeTh> `eV:RāTô<`eV:Râ>"],
[3002, "'ôTî<'ēT> NāHaG<NHG> WayYoLaK:<HLK:> ChoSheK:<ChoSheK:> W:Lo'<Lo'>-'ôR<'ôR>"],
[3003, "'aK:<'aK:> Bî<B> YāShuV<ShWV> YaHăFoK:<HFK:> YāDô<YāD> .KāL<.KoL>-HayYôM<YôM> Ś<Ś>"],
[3004, "BilLâ<BLH> V:SāRî<BāSāR> W:`ôRî<`ôR> ShiBaR<ShVR> `aZ:MôTāY<`eZeM>"],
[3005, "BāNâ<BNH> `āLaY<`aL> WayYaqQaF<NQF> Ro'Sh<Ro'Sh> ûT:Lā'â<.T:Lā'â>"],
[3006, "B:MaChăShakKîM<MaCh:ShāK:> HôShîVaNî<YShV> .K:MēTê<MWT> `ôLāM<`ôLāM> Ś<Ś>"],
[3007, ".GāDaR<.GDR> Ba`ăDî<Ba`aD> W:Lo'<Lo'> 'ēZē'<YZ'> HiK:BîD<.KVD> N:ChāSh:.Tî<N:ChoSheT>"],
[3008, ".GaM<.GaM> .Kî<.Kî> 'eŹ:`aQ<Ź`Q> Wa'ăShaûē,a`<ShW`> SāTaM<STM> .T:FilLāTî<.T:FilLâ>"],
[3009, ".GāDaR<.GDR> .D:RāKaY<.DeReK:> B:GāŹîT<.GāŹîT> N:TîVoTaY<N:TîVâ> `iûâ<`WH> Ś<Ś>"],
[3010, ".DoV<.DoV> 'oRēV<'RV> Hû'<Hû'> Lî<L> [1 'aR:YēH<'aR:YēH> 1] [2 'ăRî<'ăRî> 2] B:MiŚ:.TāRîM<MiŚ:.TāR>"],
[3011, ".D:RāKaY<.DeReK:> ŚôRēR<ŚWR> WaY:FasSh:ChēNî<PShCh> SāMaNî<SYM> ShoMēM<ShMM>"],
[3012, ".DāRaK:<.DRK:> QaSh:.Tô<QeSheT> WayYazZîVēNî<NZV> .KamMatThāRā'<MatThāRâ> LaChēZ<ChēZ> Ś<Ś>"],
[3013, "HēVî'<BW'> B:KiL:YôTāY<.KiL:Yâ> B:Nê<BēN> 'aSh:PāTô<'aSh:Pâ>"],
[3014, "HāYîTî<HYH> sS:ChoQ<S:ChôQ> L:KāL<.KoL>-`amMî<`aM> N:GîNāTāM<N:GîNâ> .KāL<.KoL>-HayYôM<YôM>"],
[3015, "HiS:Bî`aNî<SV`> VamM:RôRîM<MāRôR> HiR:WaNî<RWH> La`ăNâ<La`ăNâ> Ś<Ś>"],
[3016, "WayYaG:RēŚ<.GRŚ> BeChāZāZ<ChāZāZ> ShinNāY<ShēN> HiK:PîShaNî<.KFSh> Bā'ēFeR<'ēFeR>"],
[3017, "WatTiŹ:NaCh<ŹNCh> MisShāLôM<ShāLôM> NaF:Shî<NeFeSh> NāShîTî<NShH> ThôVâ<ThôV>"],
[3018, "Wā'oMaR<'MR> 'āVaD<'VD> NiZ:Chî<NēZaCh> W:TôChaL:.Tî<.TôCheLeT> Mê:HWâ<YHWH> Ś<Ś>"],
[3019, "Ź:KāR<ŹKR>-`āN:Yî<`ŏNî> ûM:RûDî<MāRûD> La`ăNâ<La`ăNâ> WāRo'Sh<Ro'Sh>"],
[3020, "ŹāKôR<ŹKR> .TiŹ:.KôR<ŹKR> [1 W:TāShî,aCh<ShWCh> 1] [2 W:TāShô,aCh<ShWCh> 2] `āLaY<`aL> NaF:Shî<NeFeSh>"],
[3021, "Źo'T<Źo'T> 'āShîV<ShWV> 'eL<'eL>-LiBî<LēV> `aL<`aL>-.KēN<.KēN> 'ôChîL<YChL> Ś<Ś>"],
[3022, "ChaŚ:Dê<CheŚeD> YHWH<YHWH> .Kî<.Kî> Lo'<Lo'>-TāM:Nû<.TMM> .Kî<.Kî> Lo'<Lo'>-KāLû<.KLH> RaChăMâv<RaChăMîM>"],
[3023, "ChăDāShîM<ChāDāSh> LaB:QāRîM<BoQeR> RaBâ<RaBâ> 'ĕMûNāTeKā<'ĕMûNâ>"],
[3024, "CheL:Qî<ChēLeQ> YHWH<YHWH> 'āM:Râ<'MR> NaF:Shî<NeFeSh> `aL<`aL>-.KēN<.KēN> 'ôChîL<YChL> Lô<L> Ś<Ś>"],
[3025, "ThôV<ThôV> YHWH<YHWH> L:QôāW<QWH> L:NeFeSh<NeFeSh> .TiD:R:ShenNû<.DRSh>"],
[3026, "ThôV<ThôV> W:YāChîL<YChL> W:DûMāM<.DûMāM> LiT:Shû`aT<.T:Shû`â> YHWH<YHWH>"],
[3027, "ThôV<ThôV> LagGeVeR<.GeVeR> .Kî<.Kî>-YisSā'<NS'> `oL<`oL> BiN:`ûRâv<N:`ûRîM> Ś<Ś>"],
[3028, "YēShēV<YShV> BāDāD<BāDāD> W:YidDoM<.DMM> .Kî<.Kî> NāThaL<NThL> `āLâv<`aL>"],
[3029, "YitTēN<NTN> Be`āFāR<`āFāR> PîHû<PeH> 'ûLaY<'ûLaY> YēSh<YēSh> .TiQ:Wâ<.TiQ:Wâ>"],
[3030, "YitTēN<NTN> L:MakKēHû<NKH> LeChî<L:Chî> YiS:Ba`<SV`> B:CheR:Pâ<CheR:Pâ> Ś<Ś>"],
[3031, ".Kî<.Kî> Lo'<Lo'> YiŹ:NaCh<ŹNCh> L:`ôLāM<`ôLāM> 'ăDoNāY<'ăDoNāY>"],
[3032, ".Kî<.Kî> 'iM<'iM>-HôGâ<YGH> W:RiChaM<RChM> .K:RoV<RoV> [1 ChaŚ:.Dô<CheŚeD> 1] [2 ChăŚāDâv<CheŚeD> 2]"],
[3033, ".Kî<.Kî> Lo'<Lo'> `inNâ<`NH> MilLiBô<LēV> WayYagGeH<YGH> B:Nê<BēN>-'îSh<'îSh> Ś<Ś>"],
[3034, "L:DakKē'<.DK'> .TaChaT<.TaChaT> RaG:Lâv<ReGeL> .KoL<.KoL> 'ăŚîRê<'āŚîR> 'āReZ<'eReZ>"],
[3035, "L:HatThôT<NThH> MiSh:PaTh<MiSh:PāTh>-.GāVeR<.GeVeR> NeGeD<NeGeD> P:Nê<PāNeH> `eL:YôN<`eL:YôN>"],
[3036, "L:`aûēT<`WT> 'āDāM<'āDāM> B:RîVô<RîV> 'ăDoNāY<'ăDoNāY> Lo'<Lo'> Rā'â<R'H> Ś<Ś>"],
[3037, "Mî<Mî> ŹeH<ŹeH> 'āMaR<'MR> WatTeHî<HYH> 'ăDoNāY<'ăDoNāY> Lo'<Lo'> Ziûâ<ZWH>"],
[3038, "MiPî<PeH> `eL:YôN<`eL:YôN> Lo'<Lo'> TēZē'<YZ'> HāRā`ôT<Rā`â> W:HatThôV<ThôV>"],
[3039, "MaH<Mâ>-yYiT:'ôNēN<'NN> 'āDāM<'āDāM> ChāY<ChaY> .GeVeR<.GeVeR> `aL<`aL>-[1 CheTh:'ô<ChēTh:'> 1] [2 ChăThā'âv<ChēTh:'> 2] Ś<Ś>"],
[3040, "NaCh:P:Sâ<ChFS> D:RāKêNû<.DeReK:> W:NaCh:QoRâ<ChQR> W:NāShûVâ<ShûV> `aD<`aD>-YHWH<YHWH>"],
[3041, "NisSā'<NS'> L:VāVēNû<LēVāV> 'eL<'eL>-.KaPāYiM<.KaF> 'eL<'eL>-'ēL<'ēL> BasShāMāYiM<ShāMaYiM>"],
[3042, "NaCh:Nû<NaCh:Nû> FāSha`:Nû<PSh`> ûMāRîNû<MRH> 'atTâ<'atTâ> Lo'<Lo'> ŚāLāCh:.Tā<ŚLCh> Ś<Ś>"],
[3043, "ŚakKoTâ<ŚKK:> Vā'aF<'aF> WatTiR:.D:FēNû<RDF> HāRaG:.Tā<HRG> Lo'<Lo'> ChāMāL:.Tā<ChML>"],
[3044, "ŚakKôTâ<ŚKK:> Ve`āNāN<`āNāN> LāK:<L> Mē`ăVôR<`VR> .T:FilLâ<.T:FilLâ>"],
[3045, "Ś:Chî<Ś:Chî> ûMā'ôŚ<M'Ś> .T:SîMēNû<SYM> B:QeReV<QeReV> Hā`amMîM<`aM> Ś<Ś>"],
[3046, "PāZû<PZH> `āLêNû<`aL> PîHeM<PeH> .KāL<.KoL>-'oY:VêNû<'YV>"],
[3047, "PaChaD<PaChaD> WāFaChaT<PaChaT> HāYâ<HYH> LāNû<L> HasShē'T<Shē'T> W:HasShāVeR<SheVeR>"],
[3048, "PaL:Gê<PeLeG>-MaYiM<MaYiM> .TēRaD<YRD> `êNî<`aYiN> `aL<`aL>-SheVeR<SheVeR> BaT<BaT>-`amMî<`aM> Ś<Ś>"],
[3049, "`êNî<`aYiN> NigG:Râ<NGR> W:Lo'<Lo'> TiD:MeH<.DMH> Mē'êN<'aYiN> HăFuGôT<HăFûGâ>"],
[3050, "`aD<`aD>-YaSh:QîF<ShQF> W:YēRe'<R'H> YHWH<YHWH> MisShāMāYiM<ShāMaYiM>"],
[3051, "`êNî<`aYiN> `ôL:Lâ<`LL> L:NaF:Shî<NeFeSh> MikKoL<.KoL> B:NôT<BaT> `îRî<`îR> Ś<Ś>"],
[3052, "ZôD<ZWD> ZāDûNî<ZWD> .KazZiPôR<ZiPôR> 'oY:VaY<'YV> ChinNāM<ChinNāM>"],
[3053, "ZāM:Tû<ZMT> VaBôR<BôR> ChayYāY<ChayYîM> WayYadDû<YDH>-'eVeN<'eVeN> Bî<B>"],
[3054, "ZāFû<ZWF>-MaYiM<MaYiM> `aL<`aL>-Ro'Shî<Ro'Sh> 'āMaR:.Tî<'MR> NiG:ŹāR:.Tî<.GŹR> Ś<Ś>"],
[3055, "QāRā'Tî<QR'> ShiM:Kā<ShēM> YHWH<YHWH> MiBôR<BôR> .TaCh:.TiyYôT<.TaCh:.Tî>"],
[3056, "QôLî<QôL> ShāMā`:.Tā<ShM`> 'aL<'aL>-.Ta`:LēM<`LM> 'āŹ:N:Kā<'oŹeN> L:RaW:ChāTî<R:WāChâ> L:ShaW:`āTî<ShaW:`â>"],
[3057, "QāRaV:.Tā<QRV> B:YôM<YôM> 'eQ:Rā'ekKā<QR'> 'āMaR:.Tā<'MR> 'aL<'aL>-.TîRā'<YR'> Ś<Ś>"],
[3058, "RaV:.Tā<RYV> 'ăDoNāY<'ăDoNāY> RîVê<RîV> NaF:Shî<NeFeSh> .Gā'aL:.Tā<.G'L> ChayYāY<ChayYîM>"],
[3059, "Rā'îTâ<R'H> YHWH<YHWH> `aûāTāTî<`aûāTâ> ShāF:Thâ<ShFTh> MiSh:PāThî<MiSh:PāTh>"],
[3060, "Rā'îTâ<R'H> .KāL<.KoL>-NiQ:MāTāM<N:QāMâ> .KāL<.KoL>-MaCh:Sh:VoTāM<MaChăShāVâ> Lî<L> Ś<Ś>"],
[3061, "ShāMa`:.Tā<ShM`> CheR:PāTāM<CheR:Pâ> YHWH<YHWH> .KāL<.KoL>-MaCh:Sh:VoTāM<MaChăShāVâ> `āLāY<`aL>"],
[3062, "SiF:Tê<SāFâ> QāMaY<QWM> W:HeG:YôNāM<HigGāYôN> `āLaY<`aL> .KāL<.KoL>-HayYôM<YôM>"],
[3063, "ShiV:.TāM<SheVeT> W:QîMāTāM<QîMâ> HaBîThâ<NVTh> 'ăNî<'ăNî> MaN:.GîNāTāM<MaN:.GîNâ> Ś<Ś>"],
[3064, ".TāShîV<ShWV> LāHeM<L> .G:MûL<.G:MûL> YHWH<YHWH> .K:Ma`ăSēH<Ma`ăSeH> Y:DêHeM<YāD>"],
[3065, ".TitTēN<NTN> LāHeM<L> M:GinNaT<M:GinNâ>-LēV<LēV> .Ta'ăLāT:Kā<.Ta'ăLâ> LāHeM<L>"],
[3066, ".TiR:.DoF<RDF> B:'aF<'aF> W:TaSh:MîDēM<ShMD> MitTaChaT<.TaChaT> Sh:Mê<ShāMaYiM> YHWH<YHWH> F<F>"],
[4001, "'êKâ<'êKâ> Yû`aM<`MM> ŹāHāV<ŹāHāV> YiSh:Ne'<ShNH> HakKeTeM<.KeTeM> HatThôV<ThôV> .TiSh:.TaPēK:Nâ<ShFK:> 'aV:Nê<'eVeN>-QoDeSh<QoDeSh> B:Ro'Sh<Ro'Sh> .KāL<.KoL>-ChûZôT<ChûZ> Ś<Ś>"],
[4002, "B:Nê<BēN> ZiyYôN<ZiyYôN> HaY:QāRîM<YāQāR> HaM:ŚulLā'îM<ŚL'> BaPāŹ<PaŹ> 'êKâ<'êKâ> NeCh:Sh:Vû<ChShV> L:NiV:Lê<NēVeL>-CheReS<CheReS> Ma`ăSēH<Ma`ăSeH> Y:Dê<YāD> YôZēR<YZR> Ś<Ś>"],
[4003, ".GaM<.GaM>-[1 .TanNîN<.TaN> 1] [2 .TanNîM<.TaN> 2] ChāL:Zû<ChLZ> ShaD<ShaD> HêNîQû<YNQ> .GûRêHeN<.GûR> BaT<BaT>-`amMî<`aM> L:'aK:ŹāR<'aK:ŹāR> [1 .Kî<.Kî> 1] [1 `ēNîM<Yā`ēN> 1] [2 .KaY:`ēNîM<Yā`ēN> 2] BamMiD:BāR<MiD:BāR> Ś<Ś>"],
[4004, ".DāVaQ<.DVQ> L:ShôN<LāShôN> YôNēQ<YNQ> 'eL<'eL>-ChikKô<ChēK:> BazZāMā'<ZāMā'> `ôLāLîM<`ôLāL> Shā'ăLû<Sh'L> LeCheM<LeCheM> PoRēS<PRS> 'êN<'aYiN> LāHeM<L> Ś<Ś>"],
[4005, "Hā'oK:LîM<'KL> L:Ma`ăDanNîM<Ma`ăDanNîM> NāShamMû<ShMM> BaChûZôT<ChûZ> Hā'ĕMuNîM<'MN> `ăLê<`aL> TôLā`<.TôLā`> ChiB:Qû<ChVQ> 'aSh:PatTôT<'aSh:PoT> Ś<Ś>"],
[4006, "WayYiG:.DaL<.GDL> `ăWoN<`āWoN> BaT<BaT>-`amMî<`aM> MēChatTha'T<ChatThā'T> Ś:DoM<Ś:DoM> HaHăFûKâ<HFK:> K:Mô<.K>-RāGa`<ReGa`> W:Lo'<Lo'>-ChāLû<ChWL> VāhH<B> YāDāYiM<YāD> Ś<Ś>"],
[4007, "ŹakKû<ŹKK:> N:ŹîRëHā<NāŹîR> MisSheLeG<SheLeG> ZaChû<ZChCh> MēChāLāV<ChāLāV> 'āD:Mû<'DM> `eZeM<`eZeM> MiP:NîNîM<P:NîNîM> ŚaPîR<ŚaPîR> .GiŹ:RāTāM<.GiŹ:Râ> Ś<Ś>"],
[4008, "ChāShaK:<ChShK:> MisSh:ChôR<Sh:ChôR> .Tā'ŏRāM<.To'aR> Lo'<Lo'> NikK:Rû<NKR> BaChûZôT<ChûZ> ZāFaD<ZFD> `ôRāM<`ôR> `aL<`aL>-`aZ:MāM<`eZeM> YāVēSh<YVSh> HāYâ<HYH> Kā`ēZ<`ēZ> Ś<Ś>"],
[4009, "ThôVîM<ThôV> HāYû<HYH> ChaL:Lê<ChāLāL>-CheReV<CheReV> MēChaL:Lê<ChāLāL> Rā`āV<Rā`āV> SheHēM<HēM> YāŹûVû<ŹWV> M:DuqQāRîM<.DQR> MitT:NûVoT<.T:NûVâ> SāDāY<SāDeH> Ś<Ś>"],
[4010, "Y:Dê<YāD> NāShîM<'isShâ> RaChăMāNiyYôT<RaChăMāNî> BisSh:Lû<BShL> YaL:DêHeN<YeLeD> HāYû<HYH> L:VāRôT<BRH> LāMô<L> B:SheVeR<SheVeR> BaT<BaT>-`amMî<`aM> Ś<Ś>"],
[4011, ".KilLâ<.KLH> YHWH<YHWH> 'eT<'ēT>-ChăMāTô<ChēMâ> ShāFaK:<ShFK:> ChăRôN<ChāRôN> 'aPô<'aF> WayYazZeT<YZT>-'ēSh<'ēSh> B:ZiyYôN<ZiyYôN> WatTo'KaL<'KL> Y:ŚôDoTëHā<Y:ŚôD> Ś<Ś>"],
[4012, "Lo'<Lo'> He'ĕMîNû<'MN> MaL:Kê<MeLeK:>-'eReZ<'eReZ> [1 W:KoL<.KoL> 1] [2 .KoL<.KoL> 2] YoSh:Vê<YShV> TēVēL<.TēVēL> .Kî<.Kî> YāVo'<BW'> ZaR<ZaR> W:'ôYēV<'YV> B:Sha`ăRê<Sha`aR> Y:RûShāLāiM<Y:RûShāLaiM> Ś<Ś>"],
[4013, "MēChatTho'T<ChatThā'T> N:Vî'ëHā<NāVî'> `ăWoNôT<`āWoN> .KoHăNëHā<.KoHēN> HasShoF:KîM<ShFK:> B:QiR:BāhH<QeReV> .DaM<.DāM> ZadDîQîM<ZadDîQ> Ś<Ś>"],
[4014, "Nā`û<NW`> `iW:RîM<`iûēR> BaChûZôT<ChûZ> N:Go'ăLû<.G'L> BadDāM<.DāM> B:Lo'<Lo'> YûK:Lû<YKL> YigG:`û<NG`> BiL:VuShêHeM<L:VûSh> Ś<Ś>"],
[4015, "ŚûRû<ŚWR> ThāMē'<ThāMē'> QāR:'û<QR'> LāMô<L> ŚûRû<ŚWR> ŚûRû<ŚWR> 'aL<'aL>-.TigGā`û<NG`> .Kî<.Kî> NāZû<NZH> .GaM<.GaM>-Nā`û<NW`> 'āM:Rû<'MR> BagGôYiM<.GôY> Lo'<Lo'> YôŚîFû<YŚF> LāGûR<.GWR> Ś<Ś>"],
[4016, "P:Nê<PāNeH> YHWH<YHWH> ChilL:QāM<ChLQ> Lo'<Lo'> YôŚîF<YŚF> L:HaBîThāM<NVTh> P:Nê<PāNeH> KoHăNîM<.KoHēN> Lo'<Lo'> NāSā'û<NS'> [1 Ź:QēNîM<ŹāQēN> 1] [2 ûŹ:QēNîM<ŹāQēN> 2] Lo'<Lo'> ChāNāNû<ChNN> Ś<Ś>"],
[4017, "[1 `ôDêNâ<`ôD> 1] [2 `ôDêNû<`ôD> 2] .TiK:LëNâ<.KLH> `êNêNû<`aYiN> 'eL<'eL>-`eŹ:RāTēNû<`eŹ:Râ> HāVeL<HeVeL> B:ZiPiyYāTēNû<ZiPiyYâ> ZiPîNû<ZFH> 'eL<'eL>-.GôY<.GôY> Lo'<Lo'> YôShi,a`<YSh`> Ś<Ś>"],
[4018, "ZāDû<ZWD> Z:`āDêNû<Za`aD> MilLeKeT<HLK:> BiR:ChoVoTêNû<R:ChôV> QāRaV<QRV> QizZêNû<QēZ> MāL:'û<ML'> YāMêNû<YôM> .Kî<.Kî>-Vā'<BW'> QizZêNû<QēZ> Ś<Ś>"],
[4019, "QalLîM<QaL> HāYû<HYH> RoD:FêNû<RDF> MinNiSh:Rê<NeSheR> ShāMāYiM<ShāMaYiM> `aL<`aL>-HeHāRîM<HaR> .D:LāQuNû<.DLQ> BamMiD:BāR<MiD:BāR> 'āR:Vû<'RV> LāNû<L> Ś<Ś>"],
[4020, "Rû,aCh<Rû,aCh> 'aPêNû<'aF> M:Shî,aCh<MāShî,aCh> YHWH<YHWH> NiL:.KaD<LKD> BiSh:ChîTôTāM<Sh:ChîT> 'ăSheR<'ăSheR> 'āMaR:Nû<'MR> B:ZilLô<ZēL> NiCh:YeH<ChYH> VagGôYiM<.GôY> Ś<Ś>"],
[4021, "SîSî<SWS> W:SiM:Chî<SMCh> BaT<BaT>-'ĕDôM<'ĕDôM> [1 YôShaV:.Tî<YShV> 1] [2 YôSheVeT<YShV> 2] B:'eReZ<'eReZ> `ûZ<`ûZ> .GaM<.GaM>-`āLaYiK:<`aL> .Ta`ăVāR<`VR>-.KôŚ<.KôŚ> .TiSh:.K:Rî<ShKR> W:TiT:`āRî<`RH> Ś<Ś>"],
[4022, ".TaM<.TMM>-`ăWoNēK:<`āWoN> BaT<BaT>-ZiyYôN<ZiyYôN> Lo'<Lo'> YôŚîF<YŚF> L:HaG:LôTēK:<.GLH> PāQaD<PQD> `ăWoNēK:<`āWoN> BaT<BaT>-'ĕDôM<'ĕDôM> .GilLâ<.GLH> `aL<`aL>-ChatTho'TāYiK:<ChatThā'T> F<F>"],
[5001, "Ź:KoR<ŹKR> YHWH<YHWH> MeH<Mâ>-HāYâ<HYH> LāNû<L> [1 HaBêTh<NVTh> 1] [2 HaBîThâ<NVTh> 2] ûR:'ēH<R'H> 'eT<'ēT>-CheR:PāTēNû<CheR:Pâ>"],
[5002, "NaChăLāTēNû<NaChăLâ> NeHeF:Kâ<HFK:> L:ŹāRîM<ŹWR> BātTêNû<BaYiT> L:NāK:RîM<NāK:Rî>"],
[5003, "Y:TôMîM<YāTôM> HāYîNû<HYH> [1 'êN<'aYiN> 1] [2 W:'êN<'aYiN> 2] 'āV<'āV> 'imMoTêNû<'ēM> .K:'aL:MāNôT<'aL:MāNâ>"],
[5004, "MêMêNû<MaYiM> B:KeŚeF<.KeŚeF> ShāTîNû<ShTH> `ēZêNû<`ēZ> BiM:ChîR<M:ChîR> YāVo'û<BW'>"],
[5005, "`aL<`aL> Zaûā'RēNû<Zaûā'R> NiR:.DāF:Nû<RDF> YāGa`:Nû<YG`> [1 Lo'<Lo'> 1] [2 W:Lo'<Lo'> 2] HûNaCh<NWCh>-LāNû<L>"],
[5006, "MiZ:RaYiM<MiZ:RaYiM> NāTanNû<NTN> YāD<YāD> 'asShûR<'asShûR> LiS:Bo,a`<SV`> LāCheM<LeCheM>"],
[5007, "'ăVoTêNû<'āV> ChāTh:'û<ChTh'> [1 'êNāM<'aYiN> 1] [2 W:'êNāM<'aYiN> 2] [1 'ăNaCh:Nû<'ăNaCh:Nû> 1] [2 Wa'ăNaCh:Nû<'ăNaCh:Nû> 2] `ăWoNoTêHeM<`āWoN> ŚāVāL:Nû<ŚVL>"],
[5008, "`ăVāDîM<`eVeD> MāSh:Lû<MShL> VāNû<B> PoRēQ<PRQ> 'êN<'aYiN> MiyYāDāM<YāD>"],
[5009, "B:NaF:ShēNû<NeFeSh> NāVî'<BW'> LaCh:MēNû<LeCheM> MiP:Nê<PāNeH> CheReV<CheReV> HamMiD:BāR<MiD:BāR>"],
[5010, "`ôRēNû<`ôR> .K:TanNûR<.TanNûR> NiK:MāRû<.KMR> MiP:Nê<PāNeH> ŹaL:`ăFôT<ŹaL:`āFâ> Rā`āV<Rā`āV>"],
[5011, "NāShîM<'isShâ> B:ZiyYôN<ZiyYôN> `inNû<`NH> B:TuLoT<B:TûLâ> B:`āRê<`îR> Y:HûDâ<Y:HûDâ>"],
[5012, "SāRîM<SaR> B:YāDāM<YāD> NiT:Lû<.TLH> P:Nê<PāNeH> Ź:QēNîM<ŹāQēN> Lo'<Lo'> NeH:.DāRû<HDR>"],
[5013, "BaChûRîM<BāChûR> Th:ChôN<Th:ChôN> NāSā'û<NS'> ûN:`āRîM<Na`aR> Bā`ēZ<`ēZ> .KāShāLû<.KShL>"],
[5014, "Ź:QēNîM<ŹāQēN> MisSha`aR<Sha`aR> ShāVāTû<ShVT> BaChûRîM<BāChûR> MinN:GîNāTāM<N:GîNâ>"],
[5015, "ShāVaT<ShVT> M:SôS<MāSôS> LiBēNû<LēV> NeH:PaK:<HFK:> L:'ēVeL<'ēVeL> M:ChoLēNû<MāChôL>"],
[5016, "NāF:Lâ<NFL> `ăTheReT<`ăThāRâ> Ro'ShēNû<Ro'Sh> 'ôY<'ôY>-Nā'<Nā'> LāNû<L> .Kî<.Kî> ChāThā'Nû<ChTh'>"],
[5017, "`aL<`aL>-ŹeH<ŹeH> HāYâ<HYH> DāWeH<.DāWeH> LiBēNû<LēV> `aL<`aL>-'ēlLeH<'ēlLeH> ChāSh:Kû<ChShK:> `êNêNû<`aYiN>"],
[5018, "`aL<`aL> HaR<HaR>-ZiyYôN<ZiyYôN> ShesShāMēM<ShMM> Shû`āLîM<Shû`āL> HilL:Kû<HLK:>-Vô<B> F<F>"],
[5019, "'atTâ<'atTâ> YHWH<YHWH> L:`ôLāM<`ôLāM> .TēShēV<YShV> .KiŚ:'ăKā<.KiśŚē'> L:DoR<.DôR> WāDôR<.DôR>"],
[5020, "LāmMâ<LāmMâ> LāNeZaCh<NēZaCh> .TiSh:.KāChēNû<ShKCh> .Ta`aŹ:VēNû<`ŹV> L:'oReK:<'oReK:> YāMîM<YôM>"],
[5021, "HăShîVēNû<ShWV> YHWH<YHWH> 'ēLëKā<'eL> [1 W:NāShûV<ShWV> 1] [2 W:NāShûVâ<ShWV> 2] ChadDēSh<ChDSh> YāMêNû<YôM> .K:QeDeM<QeDeM>"],
[5022, ".Kî<.Kî> 'iM<'iM>-Mā'oŚ<M'Ś> M:'aŚ:.TāNû<M'Ś> QāZaF:.Tā<QZF> `āLêNû<`aL> `aD<`aD>-M:'oD<M:'oD>"]
])
