Bib.ret([
[1001, ".D:VaR<.DāVāR>-YHWH<YHWH> 'ăSheR<'ăSheR> HāYâ<HYH> 'eL<'eL>-MîKâ<MîKâ> HamMoRaSh:.Tî<MôRaSh:.Tî> BîMê<YôM> YôTāM<YôTāM> 'āChāŹ<'āChāŹ> Y:ChiŹ:QiyYâ<Y:ChiŹ:QiyYâû> MaL:Kê<MeLeK:> Y:HûDâ<Y:HûDâ> 'ăSheR<'ăSheR>-ChāŹâ<ChŹH> `aL<`aL>-ShoM:RôN<ShoM:RôN> WîRûShāLāiM<Y:RûShāLaiM>"],
[1002, "ShiM:`û<ShM`> `amMîM<`aM> .KulLāM<.KoL> HaQ:ShîVî<QShV> 'eReZ<'eReZ> ûM:Lo'āhH<M:Lo'> WîHî<HYH> 'ăDoNāY<'ăDoNāY> Y:HWiH<YHWH> BāKeM<B> L:`ēD<`ēD> 'ăDoNāY<'ăDoNāY> MēHêKaL<HêKāL> QāD:Shô<QoDeSh>"],
[1003, ".Kî<.Kî>-HinNēH<HinNēH> YHWH<YHWH> YoZē'<YZ'> MimM:QôMô<MāQôM> W:YāRaD<YRD> W:DāRaK:<.DRK:> `aL<`aL>-[1 BāMôTê<BāMâ> 1] [2 BāMŏTê<BāMâ> 2] 'āReZ<'eReZ>"],
[1004, "W:NāMaśŚû<MŚŚ> HeHāRîM<HaR> .TaCh:.Tâv<.TaChaT> W:Hā`ăMāQîM<`ēMeQ> YiT:BaqQā`û<BQ`> .KadDôNaG<.DôNaG> MiP:Nê<PāNeH> Hā'ēSh<'ēSh> .K:MaYiM<MaYiM> MugGāRîM<NGR> B:MôRāD<MôRāD>"],
[1005, "B:FeSha`<PeSha`> Ya`ăQoV<Ya`ăQoV> .KāL<.KoL>-Źo'T<Źo'T> ûV:ChatTho'WT<ChatThā'T> BêT<BaYiT> YiS:Rā'ēL<YiS:Rā'ēL> Mî<Mî>-FeSha`<PeSha`> Ya`ăQoV<Ya`ăQoV> HăLô'<Lo'> ShoM:RôN<ShoM:RôN> ûMî<Mî> BāMôT<BāMâ> Y:HûDâ<Y:HûDâ> HăLô'<Lo'> Y:RûShāLāiM<Y:RûShāLaiM>"],
[1006, "W:SaM:.Tî<SYM> ShoM:RôN<ShoM:RôN> L:`î<`î> HasSāDeH<SāDeH> L:MatThā`ê<MatThā`> KāReM<.KeReM> W:HigGaR:.Tî<NGR> LagGaY<.GaY:'> 'ăVāNëHā<'eVeN> WîŚoDëHā<Y:ŚôD> 'ăGalLeH<.GLH>"],
[1007, "W:KāL<.KoL>-P:ŚîLëHā<PāŚîL> YukKatTû<.KTT> W:KāL<.KoL>-'eT:NanNëHā<'eT:NaN> YisSāR:Fû<SRF> Vā'ēSh<'ēSh> W:KāL<.KoL>-`ăZaBëHā<`āZāV> 'āSîM<SYM> Sh:MāMâ<Sh:MāMâ> .Kî<.Kî> Mē'eT:NaN<'eT:NaN> ŹôNâ<ŹNH> QiBāZâ<QVZ> W:`aD<`aD>-'eT:NaN<'eT:NaN> ŹôNâ<ŹNH> YāShûVû<ShWV>"],
[1008, "`aL<`aL>-Źo'T<Źo'T> 'eŚ:P:Dâ<ŚFD> W:'êLîLâ<YLL> 'êL:Kâ<HLK:> [1 ShîLaL<ShêLāL> 1] [2 ShôLāL<ShôLāL> 2] W:`āRôM<`āRôM> 'e`ĕSeH<`SH> MiŚ:PēD<MiŚ:PēD> .KatTanNîM<.TaN> W:'ēVeL<'ēVeL> .KiV:NôT<BaT> Ya`ăNâ<Ya`ăNâ>"],
[1009, ".Kî<.Kî> 'ăNûShâ<'NSh> MakKôTëHā<MakKâ> .Kî<.Kî>-Vā'â<BW'> `aD<`aD>-Y:HûDâ<Y:HûDâ> NāGa`<NG`> `aD<`aD>-Sha`aR<Sha`aR> `amMî<`aM> `aD<`aD>-Y:RûShāLāiM<Y:RûShāLaiM>"],
[1010, "B:GaT<.GaT> 'aL<'aL>-.TagGîDû<NGD> BāKô<BKH> 'aL<'aL>-.TiV:.Kû<BKH> B:VêT_L:`aF:Râ<BêT_L:`aF:Râ> `āFāR<`āFāR> [1 HiT:PalLāSh:.Tî<PLSh> 1] [2 HiT:PalLāShî<PLSh> 2]"],
[1011, "`iV:Rî<`VR> LāKeM<L> YôSheVeT<YShV> ShāFîR<ShāFîR> `eR:Yâ<`eR:Yâ>-VoSheT<BoSheT> Lo'<Lo'> YāZ:'â<YZ'> YôSheVeT<YShV> Za'ăNāN<Za'ăNāN> MiŚ:PaD<MiŚ:PēD> BêT_Hā'ēZeL<BêT_Hā'ēZeL> YiqQaCh<LQCh> MikKeM<MiN> `eM:.DāTô<`eM:.Dâ>"],
[1012, ".Kî<.Kî>-ChāLâ<ChLH> L:ThôV<ThôV> YôSheVeT<YShV> MāRôT<MāRôT> .Kî<.Kî>-YāRaD<YRD> Rā`<Ra`> Mē'ēT<'ēT> YHWH<YHWH> L:Sha`aR<Sha`aR> Y:RûShāLāiM<Y:RûShāLaiM>"],
[1013, "R:ToM<RTM> HamMeR:.KāVâ<MeR:.KāVâ> LāReKeSh<ReKeSh> YôSheVeT<YShV> LāKîSh<LāKîSh> Rē'ShîT<Rē'ShîT> ChatThā'T<ChatThā'T> Hî'<Hî'> L:VaT<BaT>-ZiyYôN<ZiyYôN> .Kî<.Kî>-VāK:<B> NiM:Z:'û<MZ'> PiSh:`ê<PeSha`> YiS:Rā'ēL<YiS:Rā'ēL>"],
[1014, "LāKēN<.KēN> .TitT:Nî<NTN> ShilLûChîM<ShilLûChîM> `aL<`aL> MôReSheT_gGaT<MôReSheT_gGaT> BātTê<BaYiT> 'aK:ŹîV<'aK:ŹîV> L:'aK:ŹāV<'aK:ŹāV> L:MaL:Kê<MeLeK:> YiS:Rā'ēL<YiS:Rā'ēL>"],
[1015, "`oD<`ôD> HayYoRēSh<YRSh> 'āVî<BW'> LāK:<L> YôSheVeT<YShV> MāRēShâ<MāRēShâ> `aD<`aD>-`ăDulLāM<`ăDulLāM> YāVô'<BW'> .K:VôD<.KāVôD> YiS:Rā'ēL<YiS:Rā'ēL>"],
[1016, "QāR:Chî<QRCh> WāGoźŹî<.GŹŹ> `aL<`aL>-B:Nê<BēN> .Ta`ăNûGāYiK:<.Ta`ăNûG> HaR:ChiVî<RChV> QāR:ChāTēK:<QāR:Châ> .KanNeSheR<NeSheR> .Kî<.Kî> GāLû<.GLH> MimMēK:<MiN> Ś<Ś>"],
[2001, "HôY<HôY> ChoSh:Vê<ChShV>-'āWeN<'āWeN> ûFo`ăLê<P`L> Rā`<Ra`> `aL<`aL>-MiSh:.K:VôTāM<MiSh:.KāV> B:'ôR<'ôR> HaBoQeR<BoQeR> Ya`ăSûHā<`SH> .Kî<.Kî> YeSh<YēSh>-L:'ēL<'ēL> YāDāM<YāD>"],
[2002, "W:ChāM:Dû<ChMD> SāDôT<SāDeH> W:GāŹāLû<.GŹL> ûVātTîM<BaYiT> W:NāSā'û<NS'> W:`āSh:Qû<`ShQ> .GeVeR<.GeVeR> ûVêTô<BaYiT> W:'îSh<'îSh> W:NaChăLāTô<NaChăLâ> F<F>"],
[2003, "LāKēN<.KēN> .KoH<.KoH> 'āMaR<'MR> YHWH<YHWH> HiN:Nî<HinNēH> ChoShēV<ChShV> `aL<`aL>-HamMiSh:PāChâ<MiSh:PāChâ> HaźŹo'T<Źo'T> Rā`â<Rā`â> 'ăSheR<'ăSheR> Lo'<Lo'>-TāMîShû<MWSh> MisShāM<ShāM> Zaû:'RoTêKeM<Zaûā'R> W:Lo'<Lo'> TēL:Kû<HLK:> RôMâ<RôMâ> .Kî<.Kî> `ēT<`ēT> Rā`â<Rā`â> Hî'<Hî'>"],
[2004, "BayYôM<YôM> HaHû'<Hû'> YisSā'<NS'> `ăLêKeM<`aL> MāShāL<MāShāL> W:NāHâ<NHH> N:Hî<N:Hî> NiH:Yâ<HYH> 'āMaR<'MR> ShāDôD<ShDD> N:ShadDuNû<ShDD> ChēLeQ<ChēLeQ> `amMî<`aM> YāMîR<MWR> 'êK:<'êK:> YāMîSh<MWSh> Lî<L> L:ShôVēV<ShôVēV> SāDêNû<SāDeH> Y:ChalLēQ<ChLQ>"],
[2005, "LāKēN<.KēN> Lo'<Lo'>-YiH:YeH<HYH> L:Kā<L> MaSh:LîK:<ShLK:> CheVeL<CheVeL> B:GôRāL<.GôRāL> BiQ:HaL<QāHāL> YHWH<YHWH>"],
[2006, "'aL<'aL>-.TatThiFû<NThF> YatThîFûN<NThF> Lo'<Lo'>-YatThiFû<NThF> Lā'ēlLeH<'ēlLeH> Lo'<Lo'> YiśŚaG<ŚWG> .K:LimMôT<.K:LimMâ>"],
[2007, "He'āMûR<'MR> BêT<BaYiT>-Ya`ăQoV<Ya`ăQoV> HăQāZaR<QZR> Rû,aCh<Rû,aCh> YHWH<YHWH> 'iM<'iM>-'ēlLeH<'ēlLeH> Ma`ăLāLâv<Ma`ăLāL> HăLô'<Lo'> D:VāRaY<.DāVāR> YêThîVû<YThV> `iM<`iM> HayYāShāR<YāShāR> HôLēK:<HLK:>"],
[2008, "W:'eT:MûL<'eT:MôL> `amMî<`aM> L:'ôYēV<'YV> Y:QôMēM<QWM> MimMûL<MûL> SaL:Mâ<SaL:Mâ> 'eDeR<'eDeR> .TaF:ShiThûN<PShTh> Mē`oV:RîM<`VR> BeThaCh<BeThaCh> ShûVê<ShWV> MiL:ChāMâ<MiL:ChāMâ>"],
[2009, "N:Shê<'isShâ> `amMî<`aM> .T:GāR:ShûN<.GRSh> MiBêT<BaYiT> .Ta`ăNuGëHā<.Ta`ăNûG> Mē`aL<`aL> `oLāLëHā<`ôLāL> .TiQ:Chû<LQCh> HăDāRî<HāDāR> L:`ôLāM<`ôLāM>"],
[2010, "QûMû<QWM> ûL:Kû<HLK:> .Kî<.Kî> Lo'<Lo'>-Źo'T<Źo'T> HamM:NûChâ<M:NûChâ> Ba`ăVûR<Ba`ăVûR> ThāM:'â<ThM'> .T:ChaBēL<ChVL> W:CheVeL<CheVeL> NiM:RāZ<MRZ>"],
[2011, "Lû<Lû>-'îSh<'îSh> HoLēK:<HLK:> Rû,aCh<Rû,aCh> WāSheQeR<SheQeR> .KiźŹēV<.KŹV> 'atThiF<NThF> L:Kā<L> LayYaYiN<YaYiN> W:LasShēKāR<ShēKāR> W:HāYâ<HYH> MatThîF<NThF> Hā`āM<`aM> HaźŹeH<ŹeH>"],
[2012, "'āŚoF<'ŚF> 'e'ĕŚoF<'ŚF> Ya`ăQoV<Ya`ăQoV> .KulLāK:<.KoL> QaBēZ<QVZ> 'ăQaBēZ<QVZ> Sh:'ēRîT<Sh:'ēRîT> YiS:Rā'ēL<YiS:Rā'ēL> YaChaD<YaChaD> 'ăSîMenNû<SYM> .K:Zo'N<Zo'N> BāZ:Râ<BāZ:Râ> .K:`ēDeR<`ēDeR> B:TôK:<.TāWeK:> HadDāV:Rô<.DoVeR> .T:HîMeNâ<HWM> Mē'āDāM<'āDāM>"],
[2013, "`āLâ<`LH> HaPoRēZ<PRZ> LiF:NêHeM<PāNîM> PāR:Zû<PRZ> WayYa`ăVoRû<`VR> Sha`aR<Sha`aR> WayYēZ:'û<YZ'> Vô<B> WayYa`ăVoR<`VR> MaL:.KāM<MeLeK:> LiF:NêHeM<PāNîM> WaYHWâ<YHWH> B:Ro'ShāM<Ro'Sh> F<F>"],
[3001, "Wā'oMaR<'MR> ShiM:`û<ShM`>-Nā'<Nā'> Rā'Shê<Ro'Sh> Ya`ăQoV<Ya`ăQoV> ûQ:ZîNê<QāZîN> BêT<BaYiT> YiS:Rā'ēL<YiS:Rā'ēL> HăLô'<Lo'> LāKeM<L> LāDa`aT<YD`> 'eT<'ēT>-HamMiSh:PāTh<MiSh:PāTh>"],
[3002, "SoN:'ê<SN'> ThôV<ThôV> W:'oHăVê<'HV> [1 Rā`â<Rā`â> 1] [2 Rā`<Ra`> 2] .GoŹ:Lê<.GŹL> `ôRāM<`ôR> Mē`ăLêHeM<`aL> ûSh:'ēRāM<Sh:'ēR> Mē`aL<`aL> `aZ:MôTāM<`eZeM>"],
[3003, "Wa'ăSheR<'ăSheR> 'āK:Lû<'KL> Sh:'ēR<Sh:'ēR> `amMî<`aM> W:`ôRāM<`ôR> Mē`ăLêHeM<`aL> HiF:ShîThû<PShTh> W:'eT<'ēT>-`aZ:MoTêHeM<`eZeM> PizZēChû<PZCh> ûFāR:Sû<PRS> .Ka'ăSheR<'ăSheR> BaśŚîR<ŚîR> ûK:VāSāR<BāSāR> B:TôK:<.TāWeK:> QalLāChaT<QalLaChaT>"],
[3004, "'āŹ<'āŹ> YiŹ:`ăQû<Ź`Q> 'eL<'eL>-YHWH<YHWH> W:Lo'<Lo'> Ya`ăNeH<`NH> 'ôTāM<'ēT> W:YaŚ:.TēR<ŚTR> PāNâv<PāNeH> MēHeM<MiN> Bā`ēT<`ēT> HaHî'<Hî'> .Ka'ăSheR<'ăSheR> HēRē`û<R``> Ma`aL:LêHeM<Ma`ăLāLîM> F<F>"],
[3005, ".KoH<.KoH> 'āMaR<'MR> YHWH<YHWH> `aL<`aL>-HanN:Vî'îM<NāVî'> HamMaT:`îM<.T`H> 'eT<'ēT>-`amMî<`aM> HanNoSh:KîM<NShK:> B:ShinNêHeM<ShēN> W:QāR:'û<QR'> ShāLôM<ShāLôM> Wa'ăSheR<'ăSheR> Lo'<Lo'>-YitTēN<NTN> `aL<`aL>-PîHeM<PeH> W:QidD:Shû<QDSh> `āLâv<`aL> MiL:ChāMâ<MiL:ChāMâ>"],
[3006, "LāKēN<.KēN> LaY:Lâ<LaY:Lâ> LāKeM<L> MēChāŹôN<ChāŹôN> W:ChāSh:Kâ<ChShK:> LāKeM<L> MiqQ:ŚoM<QŚM> ûVā'â<BW'> HasSheMeSh<SheMeSh> `aL<`aL>-HanN:Vî'îM<NāVî'> W:QāDaR<QDR> `ăLêHeM<`aL> HayYôM<YôM>"],
[3007, "ûVoShû<BWSh> HaChoŹîM<ChôŹeH> W:ChāF:Rû<ChFR> HaqQoŚ:MîM<QŚM> W:`āThû<`ThH> `aL<`aL>-SāFāM<SāFāM> .KulLāM<.KoL> .Kî<.Kî> 'êN<'aYiN> Ma`ăNēH<Ma`ăNeH> 'ĕLoHîM<'ĕLoHîM>"],
[3008, "W:'ûLāM<'ûLāM> 'āNoKî<'āNoKî> MāLē'Tî<ML'> Ko,aCh<.Ko,aCh> 'eT<'ēT>-Rû,aCh<Rû,aCh> YHWH<YHWH> ûMiSh:PāTh<MiSh:PāTh> ûG:VûRâ<.G:VûRâ> L:HagGîD<NGD> L:Ya`ăQoV<Ya`ăQoV> PiSh:`ô<PeSha`> ûL:YiS:Rā'ēL<YiS:Rā'ēL> ChatThā'Tô<ChatThā'T> Ś<Ś>"],
[3009, "ShiM:`û<ShM`>-Nā'<Nā'> Źo'T<Źo'T> Rā'Shê<Ro'Sh> BêT<BaYiT> Ya`ăQoV<Ya`ăQoV> ûQ:ZîNê<QāZîN> BêT<BaYiT> YiS:Rā'ēL<YiS:Rā'ēL> HaMăTa`ăVîM<.T`V> MiSh:PāTh<MiSh:PāTh> W:'ēT<'ēT> .KāL<.KoL>-HaY:ShāRâ<YāShāR> Y:`aqQēShû<`QSh>"],
[3010, "BoNeH<BNH> ZiyYôN<ZiyYôN> B:DāMîM<.DāM> WîRûShāLaiM<Y:RûShāLaiM> B:`aW:Lâ<`aW:Lâ>"],
[3011, "Rā'ShëHā<Ro'Sh> B:ShoChaD<ShoChaD> YiSh:PoThû<ShFTh> W:KoHăNëHā<.KoHēN> BiM:ChîR<M:ChîR> YôRû<YRH> ûN:Vî'ëHā<NāVî'> B:KeŚeF<.KeŚeF> YiQ:ŚoMû<QŚM> W:`aL<`aL>-YHWH<YHWH> YisShā`ēNû<Sh`N> Lē'MoR<'MR> HăLô'<Lo'> YHWH<YHWH> B:QiR:BēNû<QeReV> Lo'<Lo'>-TāVô'<BW'> `āLêNû<`aL> Rā`â<Rā`â>"],
[3012, "LāKēN<.KēN> BiG:LaL:KeM<BiG:LaL> ZiyYôN<ZiyYôN> SāDeH<SāDeH> TēChāRēSh<ChRSh> WîRûShāLaiM<Y:RûShāLaiM> `iyYîN<`î> .TiH:YeH<HYH> W:HaR<HaR> HaBaYiT<BaYiT> L:VāMôT<BāMâ> Yā`aR<Ya`aR> F<F>"],
[4001, "W:HāYâ<HYH> B:'aChăRîT<'aChăRîT> HayYāMîM<YôM> YiH:YeH<HYH> HaR<HaR> BêT<BaYiT>-YHWH<YHWH> NāKôN<.KWN> B:Ro'Sh<Ro'Sh> HeHāRîM<HaR> W:NisSā'<NS'> Hû'<Hû'> MigG:Vā`ôT<.GiV:`â> W:NāHăRû<NHR> `āLâv<`aL> `amMîM<`aM>"],
[4002, "W:HāL:Kû<HLK:> .GôYiM<.GôY> RaBîM<RaV> W:'āM:Rû<'MR> L:Kû<HLK:> W:Na`ăLeH<`LH> 'eL<'eL>-HaR<HaR>-YHWH<YHWH> W:'eL<'eL>-BêT<BaYiT> 'ĕLoHê<'ĕLoHîM> Ya`ăQoV<Ya`ăQoV> W:YôRēNû<YRH> MidD:RāKâv<.DeReK:> W:NēL:Kâ<HLK:> B:'oR:ChoTâv<'oRaCh> .Kî<.Kî> MizZiyYôN<ZiyYôN> .TēZē'<YZ'> TôRâ<.TôRâ> ûD:VaR<.DāVāR>-YHWH<YHWH> MîRûShāLāiM<Y:RûShāLaiM>"],
[4003, "W:ShāFaTh<ShFTh> BêN<BaYiN> `amMîM<`aM> RaBîM<RaV> W:HôKî,aCh<YKCh> L:GôYiM<.GôY> `ăZuMîM<`āZûM> `aD<`aD>-RāChôQ<RāChôQ> W:KitT:Tû<.KTT> ChaR:VoTêHeM<CheReV> L:'itTîM<'ēT> WaChăNîToTêHeM<ChăNîT> L:MaŹ:MēRôT<MaŹ:MēRâ> Lo'<Lo'>-YiS:'û<NS'> .GôY<.GôY> 'eL<'eL>-.GôY<.GôY> CheReV<CheReV> W:Lo'<Lo'>-YiL:M:DûN<LMD> `ôD<`ôD> MiL:ChāMâ<MiL:ChāMâ>"],
[4004, "W:YāSh:Vû<YShV> 'îSh<'îSh> .TaChaT<.TaChaT> .GaF:Nô<.GeFeN> W:TaChaT<.TaChaT> .T:'ēNāTô<.T:'ēNâ> W:'êN<'aYiN> MaChăRîD<ChRD> .Kî<.Kî>-Fî<PeH> YHWH<YHWH> Z:Vā'ôT<ZāVā'> .DiBēR<.DVR>"],
[4005, ".Kî<.Kî> .KāL<.KoL>-Hā`amMîM<`aM> YēL:Kû<HLK:> 'îSh<'îSh> B:ShēM<ShēM> 'ĕLoHâv<'ĕLoHîM> Wa'ăNaCh:Nû<'ăNaCh:Nû> NēLēK:<HLK:> B:ShēM<ShēM>-YHWH<YHWH> 'ĕLoHêNû<'ĕLoHîM> L:`ôLāM<`ôLāM> Wā`eD<`aD> F<F>"],
[4006, "BayYôM<YôM> HaHû'<Hû'> N:'uM<N:'uM>-YHWH<YHWH> 'oŚ:Fâ<'ŚF> HazZoLē`â<ZL`> W:HanNidDāChâ<NDCh> 'ăQaBēZâ<QVZ> Wa'ăSheR<'ăSheR> HăRē`oTî<R``>"],
[4007, "W:SaM:.Tî<SYM> 'eT<'ēT>-HazZoLē`â<ZL`> LiSh:'ēRîT<Sh:'ēRîT> W:HanNaHăLā'â<HL'> L:GôY<.GôY> `āZûM<`āZûM> ûMāLaK:<MLK:> YHWH<YHWH> `ăLêHeM<`aL> B:HaR<HaR> ZiyYôN<ZiyYôN> Mē`atTâ<`atTâ> W:`aD<`aD>-`ôLāM<`ôLāM> F<F>"],
[4008, "W:'atTâ<'atTâ> MiG:.DaL-`ēDeR<MiG:.DaL-`ēDeR> `oFeL<`oFeL> BaT<BaT>-ZiyYôN<ZiyYôN> `āDëKā<`aD> .Tē'TeH<'TH> ûVā'â<BW'> HamMeM:ShāLâ<MeM:ShāLâ> HāRi'ShoNâ<Ri'ShôNâ> MaM:LeKeT<MaM:LāKâ> L:VaT<BaT>-Y:RûShāLāiM<Y:RûShāLaiM>"],
[4009, "`atTâ<`atTâ> LāmMâ<LāmMâ> TāRî`î<RW`> Rē,a`<Rē,a`> HăMeLeK:<MeLeK:> 'êN<'aYiN>-BāK:<B> 'iM<'iM>-Yô`ăZēK:<Y`Z> 'āVāD<'VD> .Kî<.Kî>-HeChĕŹîQēK:<ChŹQ> ChîL<ChîL> .KayYôLēDâ<YLD>"],
[4010, "ChûLî<ChWL> WāGoChî<.GYCh> BaT<BaT>-ZiyYôN<ZiyYôN> .KayYôLēDâ<YLD> .Kî<.Kî>-`atTâ<`atTâ> TēZ:'î<YZ'> MiqQiR:Yâ<QiR:Yâ> W:ShāKaN:.T:<ShKN> BasSāDeH<SāDeH> ûVā'T<BW'> `aD<`aD>-BāVeL<BāVeL> ShāM<ShāM> .TinNāZēLî<NZL> ShāM<ShāM> YiG:'āLēK:<.G'L> YHWH<YHWH> MikKaF<.KaF> 'oY:VāYiK:<'YV>"],
[4011, "W:`atTâ<`atTâ> Ne'eŚ:Fû<'ŚF> `āLaYiK:<`aL> .GôYiM<.GôY> RaBîM<RaV> Hā'oM:RîM<'MR> .TeChĕNāF<ChNF> W:TaChaŹ<ChŹH> B:ZiyYôN<ZiyYôN> `êNêNû<`aYiN>"],
[4012, "W:HēmMâ<HēM> Lo'<Lo'> YāD:`û<YD`> MaCh:Sh:VôT<MaChăShāVâ> YHWH<YHWH> W:Lo'<Lo'> HēVîNû<BYN> `ăZāTô<`ēZâ> .Kî<.Kî> QiB:ZāM<QVZ> .Ke`āMîR<`āMîR> .GoR:Nâ<.GoReN>"],
[4013, "QûMî<QWM> WāDôShî<.DWSh> VaT<BaT>-ZiyYôN<ZiyYôN> .Kî<.Kî>-QaR:NēK:<QeReN> 'āSîM<SYM> BaR:ŹeL<BaR:ŹeL> ûFaR:ŚoTaYiK:<PaR:Śâ> 'āSîM<SYM> N:ChûShâ<N:ChûShâ> WaHăDiqQôT<.DQQ> `amMîM<`aM> RaBîM<RaV> W:HaChăRaM:.Tî<ChRM> LaYHWâ<YHWH> BiZ:`āM<BeZa`> W:ChêLāM<ChaYiL> La'ăDôN<'āDôN> .KāL<.KoL>-Hā'āReZ<'eReZ>"],
[4014, "`atTâ<`atTâ> .TiT:.GoD:Dî<.GDD> VaT<BaT>-.G:DûD<.G:DûD> MāZôR<MāZôR> SāM<SYM> `āLêNû<`aL> BasShēVeTh<ShēVeTh> YakKû<NKH> `aL<`aL>-HalL:Chî<L:Chî> 'ēT<'ēT> ShoFēTh<ShFTh> YiS:Rā'ēL<YiS:Rā'ēL> Ś<Ś>"],
[5001, "W:'atTâ<'atTâ> BêT_LeCheM<BêT_LeCheM> 'eF:RāTâ<'eF:RāTâ> Zā`îR<Zā`îR> LiH:YôT<HYH> B:'aL:Fê<'eLeF> Y:HûDâ<Y:HûDâ> MimM:Kā<MiN> Lî<L> YēZē'<YZ'> LiH:YôT<HYH> MôShēL<MShL> B:YiS:Rā'ēL<YiS:Rā'ēL> ûMôZā'oTâv<MôZā'â> MiqQeDeM<QeDeM> MîMê<YôM> `ôLāM<`ôLāM>"],
[5002, "LāKēN<.KēN> YitT:NēM<NTN> `aD<`aD>-`ēT<`ēT> YôLēDâ<YLD> YāLāDâ<YLD> W:YeTeR<YeTeR> 'eChâv<'āCh> Y:ShûVûN<ShWV> `aL<`aL>-B:Nê<BēN> YiS:Rā'ēL<YiS:Rā'ēL>"],
[5003, "W:`āMaD<`MD> W:Rā`â<R`H> B:`oŹ<`oŹ> YHWH<YHWH> BiG:'ôN<.Gā'ôN> ShēM<ShēM> YHWH<YHWH> 'ĕLoHâv<'ĕLoHîM> W:YāShāVû<YShV> .Kî<.Kî>-`atTâ<`atTâ> YiG:.DaL<.GDL> `aD<`aD>-'aF:Śê<'eFeŚ>-'āReZ<'eReZ>"],
[5004, "W:HāYâ<HYH> ŹeH<ŹeH> ShāLôM<ShāLôM> 'asShûR<'asShûR> .Kî<.Kî>-YāVô'<BW'> V:'aR:ZēNû<'eReZ> W:Kî<.Kî> YiD:RoK:<.DRK:> B:'aR:M:NoTêNû<'aR:MôN> WaHăQēMoNû<QWM> `āLâv<`aL> ShiV:`â<ShiV:`â> Ro`îM<R`H> ûSh:MoNâ<Sh:MoNâ> N:ŚîKê<NāŚîK:> 'āDāM<'āDāM>"],
[5005, "W:Rā`û<R`H> 'eT<'ēT>-'eReZ<'eReZ> 'asShûR<'asShûR> BaCheReV<CheReV> W:'eT<'ēT>-'eReZ<'eReZ> NiM:RoD<NiM:RoD> BiF:TāChëHā<PeTaCh> W:HizZîL<NZL> Mē'asShûR<'asShûR> .Kî<.Kî>-YāVô'<BW'> V:'aR:ZēNû<'eReZ> W:Kî<.Kî> YiD:RoK:<.DRK:> BiG:VûLēNû<.G:VûL> Ś<Ś>"],
[5006, "W:HāYâ<HYH> Sh:'ēRîT<Sh:'ēRîT> Ya`ăQoV<Ya`ăQoV> B:QeReV<QeReV> `amMîM<`aM> RaBîM<RaV> .K:ThaL<ThaL> Mē'ēT<'ēT> YHWH<YHWH> .KiR:VîVîM<R:VîVîM> `ăLê<`aL>-`ēSeV<`ēSeV> 'ăSheR<'ăSheR> Lo'<Lo'>-Y:QaûeH<QWH> L:'îSh<'îSh> W:Lo'<Lo'> Y:YaChēL<YChL> LiV:Nê<BēN> 'āDāM<'āDāM>"],
[5007, "W:HāYâ<HYH> Sh:'ēRîT<Sh:'ēRîT> Ya`ăQoV<Ya`ăQoV> BagGôYiM<.GôY> B:QeReV<QeReV> `amMîM<`aM> RaBîM<RaV> .K:'aR:YēH<'aR:YēH> B:VaHăMôT<B:HēMâ> Ya`aR<Ya`aR> .KiK:FîR<.K:FîR> B:`eD:Rê<`ēDeR>-Zo'N<Zo'N> 'ăSheR<'ăSheR> 'iM<'iM> `āVaR<`VR> W:RāMaŚ<RMŚ> W:ThāRaF<ThRF> W:'êN<'aYiN> MazZîL<NZL>"],
[5008, ".TāRoM<RWM> YāD:Kā<YāD> `aL<`aL>-ZāRëKā<ZaR> W:KāL<.KoL>-'oY:VëKā<'YV> YikKāRēTû<.KRT> F<F>"],
[5009, "W:HāYâ<HYH> VayYôM<YôM>-HaHû'<Hû'> N:'uM<N:'uM>-YHWH<YHWH> W:HiK:RatTî<.KRT> ŚûŚëKā<ŚûŚ> MiqQiR:BeKā<QeReV> W:Ha'ăVaD:.Tî<'VD> MaR:.K:VoTëKā<MeR:.KāVâ>"],
[5010, "W:HiK:RatTî<.KRT> `āRê<`îR> 'aR:ZeKā<'eReZ> W:HāRaŚ:.Tî<HRŚ> .KāL<.KoL>-MiV:ZāRëKā<MiV:ZāR>"],
[5011, "W:HiK:RatTî<.KRT> K:ShāFîM<.K:ShāFîM> MiyYāDeKā<YāD> ûM:`ôN:NîM<`NN> Lo'<Lo'> YiH:Yû<HYH>-LāK:<L>"],
[5012, "W:HiK:RatTî<.KRT> F:ŚîLëKā<PāŚîL> ûMazZēVôTëKā<MazZēVâ> MiqQiR:BeKā<QeReV> W:Lo'<Lo'>-TiSh:.TaChăWeH<ChWH> `ôD<`ôD> L:Ma`ăSēH<Ma`ăSeH> YāDëKā<YāD>"],
[5013, "W:NāTaSh:.Tî<NTSh> 'ăShêRëKā<'ăShēRâ> MiqQiR:BeKā<QeReV> W:HiSh:MaD:.Tî<ShMD> `āRëKā<`āR>"],
[5014, "W:`āSîTî<`SH> B:'aF<'aF> ûV:ChēMâ<ChēMâ> NāQāM<NāQāM> 'eT<'ēT>-HagGôYiM<.GôY> 'ăSheR<'ăSheR> Lo'<Lo'> ShāMē`û<ShM`> Ś<Ś>"],
[6001, "ShiM:`û<ShM`>-Nā'<Nā'> 'ēT<'ēT> 'ăSheR<'ăSheR>-YHWH<YHWH> 'oMēR<'MR> QûM<QWM> RîV<RYV> 'eT<'ēT>-HeHāRîM<HaR> W:TiSh:Ma`:Nâ<ShM`> HagG:Vā`ôT<.GiV:`â> QôLeKā<QôL>"],
[6002, "ShiM:`û<ShM`> HāRîM<HaR> 'eT<'ēT>-RîV<RîV> YHWH<YHWH> W:Hā'ēTāNîM<'êTāN> MoŚ:Dê<MôŚāD> 'āReZ<'eReZ> .Kî<.Kî> RîV<RîV> LaYHWâ<YHWH> `iM<`iM>-`amMô<`aM> W:`iM<`iM>-YiS:Rā'ēL<YiS:Rā'ēL> YiT:WakKāCh<YKCh>"],
[6003, "`amMî<`aM> MeH<Mâ>-`āSîTî<`SH> L:Kā<L> ûMâ<Mâ> HeL:'ēTîKā<L'H> `ăNēH<`NH> Vî<B>"],
[6004, ".Kî<.Kî> He`ĕLiTîKā<`LH> Mē'eReZ<'eReZ> MiZ:RaYiM<MiZ:RaYiM> ûMiBêT<BaYiT> `ăVāDîM<`eVeD> P:DîTîKā<PDH> Wā'eSh:LaCh<ShLCh> L:FāNëKā<PāNeH> 'eT<'ēT>-MoSheH<MoSheH> 'aHăRoN<'aHăRoN> ûMiR:YāM<MiR:YāM>"],
[6005, "`amMî<`aM> Ź:KāR<ŹKR>-Nā'<Nā'> MaH<Mâ>-yYā`aZ<Y`Z> BāLāQ<BāLāQ> MeLeK:<MeLeK:> Mô'āV<Mô'āV> ûMeH<Mâ>-`āNâ<`NH> 'oTô<'ēT> BiL:`āM<BiL:`āM> BeN<BēN>-B:`ôR<B:`ôR> MiN<MiN>-HasShitThîM<ShitThîM> `aD<`aD>-HagGiL:.GāL<.GiL:.GāL> L:Ma`aN<L:Ma`aN> .Da`aT<YD`> ZiD:QôT<Z:DāQâ> YHWH<YHWH>"],
[6006, "BamMâ<Mâ> 'ăQadDēM<QDM> YHWH<YHWH> 'ikKaF<.KFF> Lē'LoHê<'ĕLoHîM> MāRôM<MāRôM> Ha'ăQadD:MenNû<QDM> V:`ôLôT<`oLâ> Ba`ăGāLîM<`ēGeL> B:Nê<BēN> ShāNâ<ShāNâ>"],
[6007, "HăYiR:ZeH<RZH> YHWH<YHWH> B:'aL:Fê<'eLeF> 'êLîM<'aYiL> B:RiV:VôT<R:VāVâ> NaChăLê<NaChaL>-ShāMeN<SheMeN> Ha'etTēN<NTN> B:KôRî<B:KôR> PiSh:`î<PeSha`> P:Rî<P:Rî> ViTh:Nî<BeTheN> ChatTha'T<ChatThā'T> NaF:Shî<NeFeSh>"],
[6008, "HigGîD<NGD> L:Kā<L> 'āDāM<'āDāM> MaH<Mâ>-.ThôV<ThôV> ûMâ<Mâ>-YHWH<YHWH> .DôRēSh<.DRSh> MimM:Kā<MiN> .Kî<.Kî> 'iM<'iM>-`ăSôT<`SH> MiSh:PāTh<MiSh:PāTh> W:'aHăVaT<'HV> CheŚeD<CheŚeD> W:HaZ:Nē,a`<ZN`> LeKeT<HLK:> `iM<`iM>-'ĕLoHëKā<'ĕLoHîM> F<F>"],
[6009, "QôL<QôL> YHWH<YHWH> Lā`îR<`îR> YiQ:Rā'<QR'> W:TûShiyYâ<.TûShiyYâ> YiR:'eH<R'H> Sh:MeKā<ShēM> ShiM:`û<ShM`> MatTheH<MatTheH> ûMî<Mî> Y:`āDāhH<Y`D>"],
[6010, "`ôD<`ôD> Ha'iSh<'iSh> BêT<BaYiT> RāShā`<RāShā`> 'oZ:RôT<'ôZāR> ReSha`<ReSha`> W:'êFaT<'êFâ> RāŹôN<RāŹôN> Ź:`ûMâ<Ź`M>"],
[6011, "Ha'eŹ:.KeH<ŹKH> B:Mo'Ź:Nê<Mo'Ź:NaYiM> ReSha`<ReSha`> ûV:KîŚ<.KîŚ> 'aV:Nê<'eVeN> MiR:Mâ<MiR:Mâ>"],
[6012, "'ăSheR<'ăSheR> `ăShîRëHā<`āShîR> MāL:'û<ML'> ChāMāŚ<ChāMāŚ> W:YoSh:VëHā<YShV> .DiB:Rû<.DVR>-ShāQeR<SheQeR> ûL:ShôNāM<LāShôN> R:MiyYâ<R:MiyYâ> B:FîHeM<PeH>"],
[6013, "W:GaM<.GaM>-'ăNî<'ăNî> HeChĕLêTî<ChLH> HakKôTeKā<NKH> HaSh:MēM<ShMM> `aL<`aL>-ChatTho'TeKā<ChatThā'T>"],
[6014, "'atTâ<'atTâ> To'KaL<'KL> W:Lo'<Lo'> TiS:Bā`<SV`> W:YeSh:ChăKā<YeShaCh> B:QiR:BeKā<QeReV> W:TaśŚēG<ŚWG> W:Lo'<Lo'> TaF:LîTh<PLTh> Wa'ăSheR<'ăSheR> .T:FalLēTh<PLTh> LaCheReV<CheReV> 'etTēN<NTN>"],
[6015, "'atTâ<'atTâ> TiŹ:Ra`<ŹR`> W:Lo'<Lo'> TiQ:ZôR<QZR> 'atTâ<'atTâ> TiD:RoK:<.DRK:>-ŹaYiT<ŹaYiT> W:Lo'<Lo'>-TāŚûK:<ŚWK:> SheMeN<SheMeN> W:TîRôSh<.TîRôSh> W:Lo'<Lo'> TiSh:.TeH<ShTH>-yYāYiN<YaYiN>"],
[6016, "W:YiSh:.TamMēR<ShMR> ChuqQôT<ChuqQâ> `āM:Rî<`āM:Rî> W:KoL<.KoL> Ma`ăSēH<Ma`ăSeH> VêT<BaYiT>-'aCh:'āV<'aCh:'āV> WatTēL:Kû<HLK:> B:Mo`ăZôTāM<Mô`ēZâ> L:Ma`aN<L:Ma`aN> .TitTî<NTN> 'oT:Kā<'ēT> L:ShamMâ<ShamMâ> W:YoSh:VëHā<YShV> LiSh:RēQâ<Sh:RēQâ> W:CheR:PaT<CheR:Pâ> `amMî<`aM> .TisSā'û<NS'> F<F>"],
[7001, "'aL:LaY<'aL:LaY> Lî<L> .Kî<.Kî> HāYîTî<HYH> .K:'āŚ:Pê<'oŚeF>-QaYiZ<QaYiZ> .K:`oL:LoT<`ôLēLâ> BāZîR<BāZîR> 'êN<'aYiN>-'eSh:.KôL<'eSh:.KôL> Le'ĕKôL<'KL> BikKûRâ<BikKûRâ> 'iû:Tâ<'WH> NaF:Shî<NeFeSh>"],
[7002, "'āVaD<'VD> ChāŚîD<ChāŚîD> MiN<MiN>-Hā'āReZ<'eReZ> W:YāShāR<YāShāR> Bā'āDāM<'āDāM> 'āYiN<'aYiN> .KulLāM<.KoL> L:DāMîM<.DāM> Ye'ĕRoVû<'RV> 'îSh<'îSh> 'eT<'ēT>-'āChîHû<'āCh> YāZûDû<ZWD> ChēReM<ChēReM>"],
[7003, "`aL<`aL>-HāRa`<Ra`> .KaPaYiM<.KaF> L:HêThîV<YThV> HasSaR<SaR> Sho'ēL<Sh'L> W:HasShoFēTh<ShFTh> BasShilLûM<ShilLûM> W:HagGāDôL<.GāDôL> .DoVēR<.DVR> HaûaT<Haûâ> NaF:Shô<NeFeSh> Hû'<Hû'> WaY:`aB:TûHā<`VT>"],
[7004, "ThôVāM<ThôV> .K:ChēDeQ<ChēDeQ> YāShāR<YāShāR> MimM:ŚûKâ<M:ŚûKâ> YôM<YôM> M:ZaPëKā<ZFH> P:QudDāT:Kā<P:QudDâ> Vā'â<BW'> `atTâ<`atTâ> TiH:YeH<HYH> M:VûKāTāM<M:VûKâ>"],
[7005, "'aL<'aL>-.Ta'ăMîNû<'MN> V:Rē,a`<Rē,a`> 'aL<'aL>-.TiV:Th:Chû<BThCh> B:'alLûF<'alLûF> MisShoKeVeT<ShKV> ChêQeKā<ChêQ> Sh:MoR<ShMR> PiT:Chê<PeTaCh>-FîKā<PeH>"],
[7006, ".Kî<.Kî>-VēN<BēN> M:NaBēL<NVL> 'āV<'āV> BaT<BaT> QāMâ<QWM> V:'imMāhH<'ēM> .KalLâ<.KalLâ> BaChăMoTāhH<ChāMôT> 'oY:Vê<'YV> 'îSh<'îSh> 'aN:Shê<'îSh> VêTô<BaYiT>"],
[7007, "Wa'ăNî<'ăNî> BaYHWâ<YHWH> 'ăZaPeH<ZFH> 'ôChîLâ<YChL> Lē'LoHê<'ĕLoHîM> YiSh:`î<YēSha`> YiSh:Mā`ēNî<ShM`> 'ĕLoHāY<'ĕLoHîM>"],
[7008, "'aL<'aL>-.TiS:M:Chî<SMCh> 'oYaV:.Tî<'YV> Lî<L> .Kî<.Kî> NāFaL:.Tî<NFL> QāM:.Tî<QWM> .Kî<.Kî>-'ēShēV<YShV> BaChoSheK:<ChoSheK:> YHWH<YHWH> 'ôR<'ôR> Lî<L> Ś<Ś>"],
[7009, "Źa`aF<Źa`aF> YHWH<YHWH> 'esSā'<NS'> .Kî<.Kî> ChāThā'Tî<ChTh'> Lô<L> `aD<`aD> 'ăSheR<'ăSheR> YāRîV<RYV> RîVî<RîV> W:`āSâ<`SH> MiSh:PāThî<MiSh:PāTh> YôZî'ēNî<YZ'> Lā'ôR<'ôR> 'eR:'eH<R'H> B:ZiD:QāTô<Z:DāQâ>"],
[7010, "W:TēRe'<R'H> 'oYaV:.Tî<'YV> ûT:KaśŚeHā<.KŚH> VûShâ<BûShâ> Hā'oM:Râ<'MR> 'ēLaY<'eL> 'ayYô<'ayYēH> YHWH<YHWH> 'ĕLoHāYiK:<'ĕLoHîM> `êNaY<`aYiN> .TiR:'ënNâ<R'H> BāhH<B> `atTâ<`atTâ> .TiH:YeH<HYH> L:MiR:MāŚ<MiR:MāŚ> .K:ThîTh<ThîTh> ChûZôT<ChûZ>"],
[7011, "YôM<YôM> LiV:NôT<BNH> .G:DēRāYiK:<.GāDēR> YôM<YôM> HaHû'<Hû'> YiR:ChaQ<RChQ>-ChoQ<ChoQ>"],
[7012, "YôM<YôM> Hû'<Hû'> W:`āDëKā<`aD> YāVô'<BW'> L:MinNî<MiN> 'asShûR<'asShûR> W:`āRê<`îR> MāZôR<MāZôR> ûL:MinNî<MiN> MāZôR<MāZôR> W:`aD<`aD>-NāHāR<NāHāR> W:YāM<YāM> MiyYāM<YāM> W:HaR<HaR> HāHāR<HaR>"],
[7013, "W:HāY:Tâ<HYH> Hā'āReZ<'eReZ> LiSh:MāMâ<Sh:MāMâ> `aL<`aL>-YoSh:VëHā<YShV> MiP:Rî<P:Rî> Ma`aL:LêHeM<Ma`ăLāLîM> Ś<Ś>"],
[7014, "R:`ēH<R`H> `amM:Kā<`aM> V:ShiV:TheKā<ShēVeTh> Zo'N<Zo'N> NaChăLāTeKā<NaChăLâ> ShoK:Nî<ShKN> L:VāDāD<BāDāD> Ya`aR<Ya`aR> B:TôK:<.TāWeK:> .KaR:MeL<.KaR:MeL> YiR:`û<R`H> VāShāN<BāShāN> W:GiL:`āD<.GiL:`āD> .KîMê<YôM> `ôLāM<`ôLāM>"],
[7015, ".KîMê<YôM> Zē'T:Kā<YZ'> Mē'eReZ<'eReZ> MiZ:RāYiM<MiZ:RaYiM> 'aR:'enNû<R'H> NiF:Lā'ôT<PL'>"],
[7016, "YiR:'û<R'H> GôYiM<.GôY> W:YēVoShû<BWSh> MikKoL<.KoL> .G:VûRāTāM<.G:VûRâ> YāSîMû<SYM> YāD<YāD> `aL<`aL>-PeH<PeH> 'āŹ:NêHeM<'oŹeN> .TeChĕRaSh:Nâ<ChRSh>"],
[7017, "Y:LaChăKû<LChK:> `āFāR<`āFāR> .KanNāChāSh<NāChāSh> .K:ŹoChăLê<ŹChL> 'eReZ<'eReZ> YiR:.G:Źû<RGŹ> MimMiŚ:.G:RoTêHeM<MiŚ:.GeReT> 'eL<'eL>-YHWH<YHWH> 'ĕLoHêNû<'ĕLoHîM> YiF:ChāDû<PChD> W:YiR:'û<YR'> MimMekKā<MiN>"],
[7018, "Mî<Mî>-'ēL<'ēL> .KāMôKā<.K> NoSē'<NS'> `āWoN<`āWoN> W:`oVēR<`VR> `aL<`aL>-PeSha`<PeSha`> LiSh:'ēRîT<Sh:'ēRîT> NaChăLāTô<NaChăLâ> Lo'<Lo'>-HeChĕŹîQ<ChŹQ> Lā`aD<`aD> 'aPô<'aF> .Kî<.Kî>-ChāFēZ<ChFZ> CheŚeD<CheŚeD> Hû'<Hû'>"],
[7019, "YāShûV<ShWV> Y:RaChăMēNû<RChM> YiK:BoSh<.KVSh> `ăWoNoTêNû<`āWoN> W:TaSh:LîK:<ShLK:> BiM:ZuLôT<M:ZôLâ> YāM<YāM> .KāL<.KoL>-ChatTho'WTāM<ChatThā'T>"],
[7020, ".TitTēN<NTN> 'ĕMeT<'ĕMeT> L:Ya`ăQoV<Ya`ăQoV> CheŚeD<CheŚeD> L:'aV:RāHāM<'aV:RāHāM> 'ăSheR<'ăSheR>-NiSh:Ba`:.Tā<ShV`> La'ăVoTêNû<'āV> MîMê<YôM> QeDeM<QeDeM>"]
])
