Bib.ret([
[1001, "MasSā'<MasSā'> NîN:WēH<NîN:WēH> ŚēFeR<ŚēFeR> ChăŹôN<ChāŹôN> NaChûM<NaChûM> Hā'eL:QoShî<'eL:QoShî>"],
[1002, "'ēL<'ēL> QanNô'<QanNô'> W:NoQēM<NQM> YHWH<YHWH> NoQēM<NQM> YHWH<YHWH> ûVa`aL<Ba`aL> ChēMâ<ChēMâ> NoQēM<NQM> YHWH<YHWH> L:ZāRâv<ZaR> W:NôThēR<NThR> Hû'<Hû'> L:'oY:Vâv<'YV>"],
[1003, "Y:Hôâ<YHWH> 'eReK:<'āRēK:> 'aPaYiM<'aF> [1 ûG:DôL<.GāDôL>- 1] [2 ûG:DāL<.GāDôL>- 2].Ko,aCh<.Ko,aCh> W:NaqQēH<NQH> Lo'<Lo'> Y:NaqQeH<NQH> YHWH<YHWH> B:ŚûFâ<ŚûFâ> ûViS:`āRâ<S:`āRâ> .DaR:.Kô<.DeReK:> W:`āNāN<`āNāN> 'ăVaQ<'āVāQ> RaG:Lâv<ReGeL>"],
[1004, ".Gô`ēR<.G`R> BayYāM<YāM> WayYaB:ShēHû<YVSh> W:KāL<.KoL>-HanN:HāRôT<NāHāR> HeChĕRîV<ChRV> 'uM:LaL<'ML> BāShāN<BāShāN> W:KaR:MeL<.KaR:MeL> ûFeRaCh<PeRaCh> L:VāNôN<L:VāNôN> 'uM:LāL<'ML>"],
[1005, "HāRîM<HaR> Rā`ăShû<R`Sh> MimMenNû<MiN> W:HagG:Vā`ôT<.GiV:`â> HiT:MoGāGû<MWG> WatTisSā'<NS'> Hā'āReZ<'eReZ> MiPāNâv<PāNeH> W:TēVēL<.TēVēL> W:KāL<.KoL>-YoSh:Vê<YShV> VāhH<B>"],
[1006, "LiF:Nê<PāNeH> Źa`:Mô<Źa`aM> Mî<Mî> Ya`ăMôD<`MD> ûMî<Mî> YāQûM<QWM> BaChăRôN<ChāRôN> 'aPô<'aF> ChăMāTô<ChēMâ> NitT:Kâ<NTK:> Kā'ēSh<'ēSh> W:HazZuRîM<ZûRîM> NitT:Zû<NTZ> MimMenNû<MiN>"],
[1007, "ThôV<ThôV> YHWH<YHWH> L:Mā`ôŹ<Mā`ôŹ> B:YôM<YôM> ZāRâ<ZāRâ> W:YoDē,a`<YD`> ChoŚê<ChŚH> Vô<B>"],
[1008, "ûV:SheTheF<SheTheF> `oVēR<`VR> .KāLâ<.KāLâ> Ya`ăSeH<`SH> M:QôMāhH<MāQôM> W:'oY:Vâv<'YV> Y:RadDeF<RDF>-ChoSheK:<ChoSheK:>"],
[1009, "MaH<Mâ>-.T:ChasSh:VûN<ChShV> 'eL<'eL>-YHWH<YHWH> .KāLâ<.KāLâ> Hû'<Hû'> `oSeH<`SH> Lo'<Lo'>-TāQûM<QWM> Pa`ăMaYiM<Pa`aM> ZāRâ<ZāRâ>"],
[1010, ".Kî<.Kî> `aD<`aD>-ŚîRîM<ŚîR> Ś:VuKîM<ŚVK:> ûK:ŚāV:'āM<ŚoVe'> Ś:Vû'îM<ŚV'> 'ukK:Lû<'KL> .K:QaSh<QaSh> YāVēSh<YāVēSh> MāLē'<MāLē'>"],
[1011, "MimMēK:<MiN> YāZā'<YZ'> ChoShēV<ChShV> `aL<`aL>-YHWH<YHWH> Rā`â<Rā`â> Yo`ēZ<Y`Z> B:LiyYā`aL<B:LiyYa`aL> Ś<Ś>"],
[1012, ".KoH<.KoH> 'āMaR<'MR> YHWH<YHWH> 'iM<'iM>-Sh:LēMîM<ShāLēM> W:KēN<.KēN> RaBîM<RaV> W:KēN<.KēN> NāGoźŹû<.GŹŹ> W:`āVāR<`VR> W:`inNiTiK:<`NH> Lo'<Lo'> 'ă`anNēK:<`NH> `ôD<`ôD>"],
[1013, "W:`atTâ<`atTâ> 'eSh:BoR<ShVR> MoThēHû<MôTh> Mē`āLāYiK:<`aL> ûMôŚ:RoTaYiK:<MôŚēRâ> 'ăNatTēQ<NTQ>"],
[1014, "W:Ziûâ<ZWH> `āLëKā<`aL> YHWH<YHWH> Lo'<Lo'>-YiźŹāRa`<ŹR`> MisShiM:Kā<ShēM> `ôD<`ôD> MiBêT<BaYiT> 'ĕLoHëKā<'ĕLoHîM> 'aK:RîT<.KRT> PeŚeL<PeŚeL> ûMaśŚēKâ<MaśŚēKâ> 'āSîM<SYM> QiV:ReKā<QeVeR> .Kî<.Kî> QalLôTā<QLL> F<F>"],
[2001, "HinNēH<HinNēH> `aL<`aL>-HeHāRîM<HaR> RaG:Lê<ReGeL> M:VasSēR<BSR> MaSh:Mî,a`<ShM`> ShāLôM<ShāLôM> ChāgGî<ChGG> Y:HûDâ<Y:HûDâ> ChagGaYiK:<ChaG> ShalL:Mî<ShLM> N:DāRāYiK:<NeDeR> .Kî<.Kî> Lo'<Lo'> YôŚîF<YŚF> `ôD<`ôD> [1 La`ăVôR<`VR>- 1] [2 La`ăVāR<`VR>- 2]BāK:<B> B:LiyYa`aL<B:LiyYa`aL> .KulLoH<.KoL> NiK:RāT<.KRT>"],
[2002, "`āLâ<`LH> MēFîZ<PWZ> `aL<`aL>-PāNaYiK:<PāNîM> NāZôR<NZR> M:ZuRâ<M:ZûRâ> ZaPēH<ZFH>-DeReK:<.DeReK:> ChaźŹēQ<ChŹQ> MāT:NaYiM<MāT:NaYiM> 'amMēZ<'MZ> .Ko,aCh<.Ko,aCh> M:'oD<M:'oD>"],
[2003, ".Kî<.Kî> ShāV<ShWV> YHWH<YHWH> 'eT<'ēT>-.G:'ôN<.Gā'ôN> Ya`ăQoV<Ya`ăQoV> .KiG:'ôN<.Gā'ôN> YiS:Rā'ēL<YiS:Rā'ēL> .Kî<.Kî> V:QāQûM<BQQ> BoQ:QîM<BQQ> ûŹ:MoRêHeM<Ź:MôRâ> ShiChēTû<ShChT>"],
[2004, "MāGēN<MāGēN> .GiBoRêHû<.GiBôR> M:'ādDāM<'DM> 'aN:Shê<'îSh>-ChaYiL<ChaYiL> M:TulLā`îM<.TL`> B:'ēSh<'ēSh>-P:LāDôT<P:LāDâ> HāReKeV<ReKeV> B:YôM<YôM> HăKîNô<.KWN> W:HaB:RoShîM<B:RôSh> HāR:`āLû<R`L>"],
[2005, "BaChûZôT<ChûZ> YiT:HôL:Lû<HLL> HāReKeV<ReKeV> YiSh:.TaQ:Sh:QûN<ShQQ> BāR:ChoVôT<R:ChôV> MaR:'êHeN<MaR:'eH> .KalLaPîDiM<LaPîD> .KaB:RāQîM<BāRāQ> Y:RôZēZû<RWZ>"],
[2006, "YiŹ:.KoR<ŹKR> 'adDîRâv<'adDîR> YikKāSh:Lû<.KShL> [1 VaHăLiKôTāM<HăLîKâ> 1] [2 BaHăLîKāTāM<HăLîKâ> 2] Y:MaHăRû<MHR> ChôMāTāhH<ChôMâ> W:HuKaN<.KWN> HaśŚoKēK:<ŚKK:>"],
[2007, "Sha`ăRê<Sha`aR> HanN:HāRôT<NāHāR> NiF:.TāChû<PTCh> W:HaHêKāL<HêKāL> NāMôG<MWG>"],
[2008, "W:HuzZaV<NZV> .GulL:Tâ<.GLH> Ho`ăLāTâ<`LH> W:'aM:HoTëHā<'āMâ> M:NaHăGôT<NHG> .K:QôL<QôL> YôNîM<YôNâ> M:ToF:FoT<.TFF> `aL<`aL>-LiV:VēHeN<LēVāV>"],
[2009, "W:NîN:WēH<NîN:WēH> KiV:RēKaT<B:RēKâ>-MaYiM<MaYiM> MîMê<YôM> Hî'<Hî'> W:HēmMâ<HēM> NāŚîM<NWŚ> `iM:Dû<`MD> `ăMoDû<`MD> W:'êN<'aYiN> MaF:NeH<PNH>"],
[2010, "BoźŹû<BŹŹ> KeŚeF<.KeŚeF> BoźŹû<BŹŹ> ŹāHāV<ŹāHāV> W:'êN<'aYiN> QēZeH<QēZeH> LatT:KûNâ<.T:KûNâ> .KāVoD<.KāVôD> MikKoL<.KoL> .K:Lî<.K:Lî> CheM:.Dâ<CheM:.Dâ>"],
[2011, "BûQâ<BûQâ> ûM:VûQâ<M:VûQâ> ûM:VulLāQâ<BLQ> W:LēV<LēV> NāMēŚ<MŚŚ> ûFiQ<PîQ> BiR:.KaYiM<BeReK:> W:ChaL:ChāLâ<ChaL:ChāLâ> B:KāL<.KoL>-MāT:NaYiM<MāT:NaYiM> ûF:Nê<PāNeH> KulLāM<.KoL> QiB:Zû<QVZ> Fā'RûR<Pā'RûR>"],
[2012, "'ayYēH<'ayYēH> M:`ôN<Mā`ôN> 'ăRāYôT<'ăRî> ûMiR:`eH<MiR:`eH> Hû'<Hû'> LakK:FiRîM<.K:FîR> 'ăSheR<'ăSheR> HāLaK:<HLK:> 'aR:YēH<'aR:YēH> LāVî'<LāVî'> ShāM<ShāM> .GûR<.GûR> 'aR:YēH<'aR:YēH> W:'êN<'aYiN> MaChăRîD<ChRD>"],
[2013, "'aR:YēH<'aR:YēH> ThoRēF<ThRF> B:Dê<.DaY> GoRôTâv<.GôR> ûM:ChanNēQ<ChNQ> L:LiV:'oTâv<L:ViyYā'> WaY:MalLē'<ML'>-TheReF<TheReF> ChoRâv<ChoR> ûM:`oNoTâv<M:`oNâ> Th:RēFâ<Th:RēFâ>"],
[2014, "HiN:Nî<HinNēH> 'ēLaYiK:<'eL> N:'uM<N:'uM> YHWH<YHWH> Z:Vā'ôT<ZāVā'> W:HiV:`aR:.Tî<B`R> Ve`āShāN<`āShāN> RiK:BāhH<ReKeV> ûK:FîRaYiK:<.K:FîR> .To'KaL<'KL> ChāReV<CheReV> W:HiK:RatTî<.KRT> Mē'eReZ<'eReZ> ThaR:PēK:<TheReF> W:Lo'<Lo'>-YisShāMa`<ShM`> `ôD<`ôD> QôL<QôL> MaL:'āKēKēH<MaL:'āK:> Ś<Ś>"],
[3001, "HôY<HôY> `îR<`îR> .DāMîM<.DāM> .KulLāhH<.KoL> .KaChaSh<.KaChaSh> PeReQ<PeReQ> M:Lē'â<MāLē'> Lo'<Lo'> YāMîSh<MWSh> ThāReF<TheReF>"],
[3002, "QôL<QôL> ShôTh<ShôTh> W:QôL<QôL> Ra`aSh<Ra`aSh> 'ôFāN<'ôFaN> W:ŚûŚ<ŚûŚ> .DoHēR<.DHR> ûMeR:.KāVâ<MeR:.KāVâ> M:RaqQēDâ<RQD>"],
[3003, "PāRāSh<PāRāSh> Ma`ăLeH<`LH> W:LaHaV<LaHaV> CheReV<CheReV> ûV:RaQ<BāRāQ> ChăNîT<ChăNîT> W:RoV<RoV> ChāLāL<ChāLāL> W:KoVeD<.KoVeD> PāGeR<PeGeR> W:'êN<'aYiN> QēZeH<QēZeH> LagG:WiyYâ<.G:WiyYâ> [1 YiK:Sh:Lû<.KShL> 1] [2 W:KāSh:Lû<.KShL> 2] BiG:WiyYāTāM<.G:WiyYâ>"],
[3004, "MēRoV<RoV> Ź:NûNê<Ź:NûNîM> ŹôNâ<ŹNH> ThôVaT<ThôV> ChēN<ChēN> Ba`ăLaT<Ba`ăLâ> .K:ShāFîM<.K:ShāFîM> HamMoKeReT<MKRT> .GôYiM<.GôY> BiŹ:NûNëHā<Ź:NûNîM> ûMiSh:PāChôT<MiSh:PāChâ> BiK:ShāFëHā<.K:ShāFîM>"],
[3005, "HiN:Nî<HinNēH> 'ēLaYiK:<'eL> N:'uM<N:'uM> YHWH<YHWH> Z:Vā'ôT<ZāVā'> W:GilLêTî<.GLH> ShûLaYiK:<ShûL> `aL<`aL>-PāNāYiK:<PāNeH> W:HaR:'êTî<R'H> GôYiM<.GôY> Ma`:RēK:<Ma`aR> ûMaM:LāKôT<MaM:LāKâ> Q:LôNēK:<QāLôN>"],
[3006, "W:HiSh:LaK:.Tî<ShLK:> `āLaYiK:<`aL> ShiqQuZîM<ShiqQûZ> W:NiBaL:.TîK:<NVL> W:SaM:.TîK:<SYM> .K:Ro'î<Rŏ'î>"],
[3007, "W:HāYâ<HYH> KāL<.KoL>-Ro'aYiK:<R'H> YidDôD<NDD> MimMēK:<MiN> W:'āMaR<'MR> ShādD:Dâ<ShDD> NîN:WēH<NîN:WēH> Mî<Mî> YāNûD<NWD> LāhH<L> Mē'aYiN<'aYiN> 'ăVaqQēSh<BQSh> M:NaChăMîM<NChM> LāK:<L>"],
[3008, "HăTêTh:Vî<YThV> MinNo'_'āMôN<No'_'āMôN> HayYoSh:Vâ<YShV> BaY:'oRîM<Y:'ôR> MaYiM<MaYiM> ŚāVîV<ŚāVîV> LāhH<L> 'ăSheR<'ăSheR>-ChêL<ChêL> YāM<YāM> MiyYāM<YāM> ChôMāTāhH<ChôMâ>"],
[3009, ".KûSh<.KûSh> `āZ:Mâ<`āZ:Mâ> ûMiZ:RaYiM<MiZ:RaYiM> W:'êN<'aYiN> QēZeH<QēZeH> PûTh<PûTh> W:LûVîM<LûVîM> HāYû<HYH> B:`eŹ:RāTēK:<`eŹ:Râ>"],
[3010, ".GaM<.GaM>-Hî'<Hî'> LagGoLâ<.GôLâ> HāL:Kâ<HLK:> VasSheVî<Sh:Vî> .GaM<.GaM> `oLāLëHā<`ôLāL> Y:RutTh:Shû<RThSh> B:Ro'Sh<Ro'Sh> .KāL<.KoL>-ChûZôT<ChûZ> W:`aL<`aL>-NiK:BadDëHā<.KVD> YadDû<YDD> GôRāL<.GôRāL> W:KāL<.KoL>-.G:DôLëHā<.GāDôL> RutT:Qû<RTQ> VaźŹiqQîM<ŹēQ>"],
[3011, ".GaM<.GaM>-'atT:<'atT:> .TiSh:.K:Rî<ShKR> .T:Hî<HYH> Na`ăLāMâ<`LM> .GaM<.GaM>-'atT:<'atT:> .T:VaQ:Shî<BQSh> Mā`ôŹ<Mā`ôŹ> Mē'ôYēV<'YV>"],
[3012, ".KāL<.KoL>-MiV:ZāRaYiK:<MiV:ZāR> .T:'ēNîM<.T:'ēNâ> `iM<`iM>-BikKûRîM<BikKûRîM> 'iM<'iM>-YinNô`û<NW`> W:NāF:Lû<NFL> `aL<`aL>-Pî<PeH> 'ôKēL<'KL>"],
[3013, "HinNēH<HinNēH> `amMēK:<`aM> NāShîM<'isShâ> B:QiR:BēK:<QeReV> L:'oY:VaYiK:<'YV> PāTô,aCh<PTCh> NiF:.T:Chû<PTCh> Sha`ăRê<Sha`aR> 'aR:ZēK:<'eReZ> 'āK:Lâ<'KL> 'ēSh<'ēSh> B:RîChāYiK<B:Rî,aCh>"],
[3014, "Mê<MaYiM> MāZôR<MāZôR> Sha'ăVî<Sh'V>-LāK:<L> ChaźŹ:Qî<ChŹQ> MiV:ZāRāYiK:<MiV:ZāR> Bo'î<BW'> VatThîTh<ThîTh> W:RiM:Śî<RMŚ> VaChoMeR<ChoMeR> HaChăŹîQî<ChŹQ> MaL:BēN<MaL:BēN>"],
[3015, "ShāM<ShāM> .To'K:LēK:<'KL> 'ēSh<'ēSh> .TaK:RîTēK:<.KRT> CheReV<CheReV> .To'K:LēK:<'KL> .KayYāLeQ<YeLeQ> HiT:.KaBēD<.KVD> .KayYeLeQ<YeLeQ> HiT:.KaB:Dî<.KVD> .Kā'aR:BeH<'aR:BeH>"],
[3016, "HiR:BêT<RVH> RoK:LaYiK:<RKL> MikKôK:Vê<.KôKāV> HasShāMāYiM<ShāMaYiM> YeLeQ<YeLeQ> PāShaTh<PShTh> WayYā`oF<`WF>"],
[3017, "MinN:ŹāRaYiK:<MiN:ŹāR> .Kā'aR:BeH<'aR:BeH> W:ThaF:Ś:RaYiK:<ThiF:ŚāR> .K:GôV<.GôV> .GoVāY<.GôV> HaChôNîM<ChNH> BagG:DēRôT<.G:DēRâ> B:YôM<YôM> QāRâ<QāRâ> SheMeSh<SheMeSh> ŹāR:Châ<ŹRCh> W:NôDaD<NDD> W:Lo'<Lo'>-NôDa`<YD`> M:QôMô<MāQôM> 'ayYāM<'ayYēH>"],
[3018, "NāMû<NWM> Ro`ëKā<R`H> MeLeK:<MeLeK:> 'asShûR<'asShûR> YiSh:.K:Nû<ShKN> 'adDîRëKā<'adDîR> NāFoShû<PWSh> `amM:Kā<`aM> `aL<`aL>-HeHāRîM<HaR> W:'êN<'aYiN> M:QaBēZ<QVZ>"],
[3019, "'êN<'aYiN>-.KēHâ<.KēHâ> L:ShiV:ReKā<SheVeR> NaCh:Lâ<ChLH> MakKāTeKā<MakKâ> .KoL<.KoL> ShoM:`ê<ShM`> ShiM:`ăKā<ShēMa`> .TāQ:`û<.TQ`> KaF<.KaF> `āLëKā<`aL> .Kî<.Kî> `aL<`aL>-Mî<Mî> Lo'<Lo'>-`āV:Râ<`VR> Rā`āT:Kā<Rā`â> .TāMîD<.TāMîD>"]
])
