Bib.ret([
[1001, ".D:VaR<.DāVāR>-YHWH<YHWH> 'ăSheR<'ăSheR> HāYâ<HYH> 'eL<'eL>-HôShē,a`<HôShē,a`> BeN<BēN>-B:'ēRî<B:'ēRî> BîMê<YôM> `uźŹiyYâ<`uźŹiyYâ> YôTāM<YôTāM> 'āChāŹ<'āChāŹ> Y:ChiŹ:QiyYâ<Y:ChiŹ:QiyYâû> MaL:Kê<MeLeK:> Y:HûDâ<Y:HûDâ> ûVîMê<YôM> YāRāV:`āM<YāRāV:`āM> BeN<BēN>-Yô'āSh<Y:Hô'āSh> MeLeK:<MeLeK:> YiS:Rā'ēL<YiS:Rā'ēL>"],
[1002, ".T:ChilLaT<.T:ChilLâ> .DiBeR<.DVR>-YHWH<YHWH> B:HôShē,a`<HôShē,a`> F<F> WayYo'MeR<'MR> YHWH<YHWH> 'eL<'eL>-HôShē,a`<HôShē,a`> LēK:<HLK:> QaCh<LQCh>-L:Kā<L> 'ēSheT<'isShâ> Ź:NûNîM<Ź:NûNîM> W:YaL:Dê<YeLeD> Ź:NûNîM<Ź:NûNîM> .Kî<.Kî>-ŹāNoH<ŹNH> TiŹ:NeH<ŹNH> Hā'āReZ<'eReZ> Mē'aChăRê<'aChăRê> YHWH<YHWH>"],
[1003, "WayYēLeK:<HLK:> WayYiqQaCh<LQCh> 'eT<'ēT>-.GoMeR<.GoMeR> BaT<BaT>-.DiV:LāYiM<.DiV:LāYiM> WatTaHaR<HRH> WatTēLeD<YLD>-Lô<L> BēN<BēN>"],
[1004, "WayYo'MeR<'MR> YHWH<YHWH> 'ēLâv<'eL> Q:Rā'<QR'> Sh:Mô<ShēM> YiŹ:R:`e'L<YiŹ:R:`e'L> .Kî<.Kî>-`ôD<`ôD> M:`aTh<M:`aTh> ûFāQaD:.Tî<PQD> 'eT<'ēT>-.D:Mê<.DāM> YiŹ:R:`e'L<YiŹ:R:`e'L> `aL<`aL>-BêT<BaYiT> YēHû'<YēHû'> W:HiSh:BatTî<ShVT> MaM:L:KûT<MaM:L:KûT> BêT<BaYiT> YiS:Rā'ēL<YiS:Rā'ēL>"],
[1005, "W:HāYâ<HYH> BayYôM<YôM> HaHû'<Hû'> W:ShāVaR:.Tî<ShVR> 'eT<'ēT>-QeSheT<QeSheT> YiS:Rā'ēL<YiS:Rā'ēL> B:`ēMeQ<`ēMeQ> YiŹ:R:`e'L<YiŹ:R:`e'L>"],
[1006, "WatTaHaR<HRH> `ôD<`ôD> WatTēLeD<YLD> BaT<BaT> WayYo'MeR<'MR> Lô<L> Q:Rā'<QR'> Sh:MāhH<ShēM> Lo'_RuChāMâ<Lo'_RuChāMâ> .Kî<.Kî> Lo'<Lo'> 'ôŚîF<YŚF> `ôD<`ôD> 'ăRaChēM<RChM> 'eT<'ēT>-BêT<BaYiT> YiS:Rā'ēL<YiS:Rā'ēL> .Kî<.Kî>-NāSo'<NS'> 'esSā'<NS'> LāHeM<L>"],
[1007, "W:'eT<'ēT>-BêT<BaYiT> Y:HûDâ<Y:HûDâ> 'ăRaChēM<RChM> W:HôSha`:.TîM<YSh`> BaYHWâ<YHWH> 'ĕLoHêHeM<'ĕLoHîM> W:Lo'<Lo'> 'ôShî`ēM<YSh`> B:QeSheT<QeSheT> ûV:CheReV<CheReV> ûV:MiL:ChāMâ<MiL:ChāMâ> B:ŚûŚîM<ŚûŚ> ûV:FāRāShîM<PāRāSh>"],
[1008, "WatTiG:MoL<.GML> 'eT<'ēT>-Lo'_RuChāMâ<Lo'_RuChāMâ> WatTaHaR<HRH> WatTēLeD<YLD> BēN<BēN>"],
[1009, "WayYo'MeR<'MR> Q:Rā'<QR'> Sh:Mô<ShēM> Lo'_`amMî<Lo'_`amMî> .Kî<.Kî> 'atTeM<'atTeM> Lo'<Lo'> `amMî<`aM> W:'āNoKî<'āNoKî> Lo'<Lo'>-'eH:YeH<HYH> LāKeM<L> Ś<Ś>"],
[2001, "W:HāYâ<HYH> MiŚ:PaR<MiŚ:PāR> B:Nê<BēN>-YiS:Rā'ēL<YiS:Rā'ēL> .K:ChôL<ChôL> HayYāM<YāM> 'ăSheR<'ăSheR> Lo'<Lo'>-YimMaD<MDD> W:Lo'<Lo'> YiśŚāFēR<ŚFR> W:HāYâ<HYH> BiM:QôM<MāQôM> 'ăSheR<'ăSheR>-Yē'āMēR<'MR> LāHeM<L> Lo'<Lo'>-`amMî<`aM> 'atTeM<'atTeM> Yē'āMēR<'MR> LāHeM<L> B:Nê<BēN> 'ēL<'ēL>-ChāY<ChaY>"],
[2002, "W:NiQ:B:Zû<QVZ> B:Nê<BēN>-Y:HûDâ<Y:HûDâ> ûV:Nê<BēN>-YiS:Rā'ēL<YiS:Rā'ēL> YaCh:.DāW<YaCh:.DāW> W:SāMû<SYM> LāHeM<L> Ro'Sh<Ro'Sh> 'eChāD<'eChāD> W:`āLû<`LH> MiN<MiN>-Hā'āReZ<'eReZ> .Kî<.Kî> GāDôL<.GāDôL> YôM<YôM> YiŹ:R:`e'L<YiŹ:R:`e'L>"],
[2003, "'iM:Rû<'MR> La'ăChêKeM<'āCh> `amMî<`amMî> W:La'ăChôTêKeM<'āChôT> RuChāMâ<RChM>"],
[2004, "RîVû<RYV> V:'imM:KeM<'ēM> RîVû<RYV> .Kî<.Kî>-Hî'<Hî'> Lo'<Lo'> 'iSh:.Tî<'isShâ> W:'āNoKî<'āNoKî> Lo'<Lo'> 'îShāhH<'îSh> W:TāŚēR<ŚWR> Ź:NûNëHā<Ź:NûNîM> MiPāNëH<PāNeH> W:Na'ăFûFëHā<Na'ăFûFîM> MiBêN<BaYiN> ShāDëHā<ShaD>"],
[2005, "PeN<PeN>-'aF:ShîThenNâ<PShTh> `ăRumMâ<`āRôM> W:HizZaG:.TîHā<YZG> .K:YôM<YôM> HiûāL:DāhH<YLD> W:SaM:.TîHā<SYM> KamMiD:BāR<MiD:BāR> W:ShatTiHā<ShYT> .K:'eReZ<'eReZ> ZiyYâ<ZiyYâ> WaHăMitTîHā<MWT> BazZāMā'<ZāMā'>"],
[2006, "W:'eT<'ēT>-BāNëHā<BēN> Lo'<Lo'> 'ăRaChēM<RChM> .Kî<.Kî>-V:Nê<BēN> Ź:NûNîM<Ź:NûNîM> HēmMâ<HēM>"],
[2007, ".Kî<.Kî> ŹāN:Tâ<ŹNH> 'imMāM<'ēM> HoVîShâ<BWSh> HôRāTāM<HRH> .Kî<.Kî> 'āM:Râ<'MR> 'ēL:Kâ<HLK:> 'aChăRê<'aChăRê> M:'aHăVaY<'HV> NoT:Nê<NTN> LaCh:Mî<LeCheM> ûMêMaY<MaYiM> ZaM:Rî<ZeMeR> ûFiSh:.Tî<PiSh:.Tâ> ShaM:Nî<SheMeN> W:ShiqQûYāY<ShiqQûY>"],
[2008, "LāKēN<.KēN> HiN:Nî<HinNēH>-SāK:<SWK:> 'eT<'ēT>-.DaR:.KēK:<.DeReK:> BaśŚîRîM<ŚîR> W:GāDaR:.Tî<.GDR> 'eT<'ēT>-.G:DēRāhH<.GāDēR> ûN:TîVôTëHā<N:TîVâ> Lo'<Lo'> TiM:Zā'<MZ'>"],
[2009, "W:RidD:Fâ<RDF> 'eT<'ēT>-M:'aHăVëHā<'HV> W:Lo'<Lo'>-TasSîG<NSG> 'oTāM<'ēT> ûViQ:ShāTaM<BQSh> W:Lo'<Lo'> TiM:Zā'<MZ'> W:'āM:Râ<'MR> 'ēL:Kâ<HLK:> W:'āShûVâ<ShWV> 'eL<'eL>-'îShî<'îSh> HāRi'ShôN<Ri'ShôN> .Kî<.Kî> ThôV<ThôV> Lî<L> 'āŹ<'āŹ> Mē`ātTâ<`atTâ>"],
[2010, "W:Hî'<Hî'> Lo'<Lo'> YāD:`â<YD`> .Kî<.Kî> 'āNoKî<'āNoKî> NāTatTî<NTN> LāhH<L> HadDāGāN<.DāGāN> W:HatTîRôSh<.TîRôSh> W:HayYiZ:HāR<YiZ:HāR> W:KeŚeF<.KeŚeF> HiR:BêTî<RVH> LāhH<L> W:ŹāHāV<ŹāHāV> `āSû<`SH> LaBā`aL<Ba`aL>"],
[2011, "LāKēN<.KēN> 'āShûV<ShWV> W:LāQaCh:.Tî<LQCh> D:GāNî<.DāGāN> B:`itTô<`ēT> W:TîRôShî<.TîRôSh> B:Mô`ăDô<Mô`ēD> W:HizZaL:.Tî<NZL> ZaM:Rî<ZeMeR> ûFiSh:.Tî<PiSh:.Tâ> L:KaśŚôT<.KŚH> 'eT<'ēT>-`eR:WāTāhH<`eR:Wâ>"],
[2012, "W:`atTâ<`atTâ> 'ăGalLeH<.GLH> 'eT<'ēT>-NaV:LuTāhH<NaV:LûT> L:`êNê<`aYiN> M:'aHăVëHā<'HV> W:'îSh<'îSh> Lo'<Lo'>-YazZîLenNâ<NZL> MiyYāDî<YāD>"],
[2013, "W:HiSh:BatTî<ShVT> .KāL<.KoL>-M:SôSāhH<MāSôS> ChagGāhH<ChaG> ChāD:ShāhH<ChoDeSh> W:ShaBatTāhH<ShaBāT> W:KoL<.KoL> Mô`ăDāhH<Mô`ēD>"],
[2014, "WaHăShimMoTî<ShMM> .GaF:NāhH<.GeFeN> ûT:'ēNāTāhH<.T:'ēNâ> 'ăSheR<'ăSheR> 'āM:Râ<'MR> 'eT:Nâ<'eT:Nâ> HēmMâ<HēM> Lî<L> 'ăSheR<'ăSheR> NāT:Nû<NTN>-Lî<L> M:'aHăVāY<'HV> W:SaM:.TîM<SYM> L:Ya`aR<Ya`aR> Wa'ăKāLāTaM<'KL> ChayYaT<ChayYâ> HasSāDeH<SāDeH>"],
[2015, "ûFāQaD:.Tî<PQD> `āLëHā<`aL> 'eT<'ēT>-Y:Mê<YôM> HaB:`āLîM<B:`āLîM> 'ăSheR<'ăSheR> .TaQ:ThîR<QThR> LāHeM<L> WatTa`aD<`DH> NiŹ:MāhH<NeŹeM> W:CheL:YāTāhH<CheL:Yâ> WatTēLeK:<HLK:> 'aChăRê<'aChăRê> M:'aHăVëHā<'HV> W:'oTî<'ēT> ShāK:Châ<ShKCh> N:'uM<N:'uM>-YHWH<YHWH> F<F>"],
[2016, "LāKēN<.KēN> HinNēH<HinNēH> 'āNoKî<'āNoKî> M:FatTëHā<PTH> W:HoLaK:.TîHā<HLK:> HamMiD:BāR<MiD:BāR> W:DiBaR:.Tî<.DVR> `aL<`aL>-LiBāhH<LēV>"],
[2017, "W:NāTatTî<NTN> LāhH<L> 'eT<'ēT>-.K:RāMëHā<.KeReM> MisShāM<ShāM> W:'eT<'ēT>-`ēMeQ<`ēMeQ> `āKôR<`āKôR> L:FeTaCh<PeTaCh> .TiQ:Wâ<.TiQ:Wâ> W:`āN:Tâ<`NH> sShāmMâ<ShāM> .KîMê<YôM> N:`ûRëHā<N:`ûRîM> ûiK:YôM<YôM> `ăLoTāhH<`LH> Mē'eReZ<'eReZ>-MiZ:RāYiM<MiZ:RaYiM> Ś<Ś>"],
[2018, "W:HāYâ<HYH> VayYôM<YôM>-HaHû'<Hû'> N:'uM<N:'uM>-YHWH<YHWH> .TiQ:R:'î<QR'> 'îShî<'îSh> W:Lo'<Lo'>-TiQ:R:'î<QR'>-Lî<L> `ôD<`ôD> Ba`:Lî<Ba`aL>"],
[2019, "WaHăŚiRoTî<ŚWR> 'eT<'ēT>-Sh:MôT<ShēM> HaB:`āLîM<B:`āLîM> MiPîHā<PeH> W:Lo'<Lo'>-YiźŹāK:Rû<ŹKR> `ôD<`ôD> BiSh:MāM<ShēM>"],
[2020, "W:KāRatTî<.KRT> LāHeM<L> B:RîT<B:RîT> BayYôM<YôM> HaHû'<Hû'> `iM<`iM>-ChayYaT<ChayYâ> HasSāDeH<SāDeH> W:`iM<`iM>-`ôF<`ôF> HasShāMaYiM<ShāMaYiM> W:ReMeS<ReMeS> Hā'ăDāMâ<'ăDāMâ> W:QeSheT<QeSheT> W:CheReV<CheReV> ûMiL:ChāMâ<MiL:ChāMâ> 'eSh:BôR<ShVR> MiN<MiN>-Hā'āReZ<'eReZ> W:HiSh:.KaV:.TîM<ShKV> LāVeThaCh<BeThaCh>"],
[2021, "W:'ēRaS:.TîK:<'RS> Lî<L> L:`ôLāM<`ôLāM> W:'ēRaS:.TîK:<'RS> Lî<L> B:ZeDeQ<ZeDeQ> ûV:MiSh:PāTh<MiSh:PāTh> ûV:CheŚeD<CheŚeD> ûV:RaChăMîM<RaChăMîM>"],
[2022, "W:'ēRaS:.TîK:<'RS> Lî<L> Be'ĕMûNâ<'ĕMûNâ> W:YāDa`atT:<YD`> 'eT<'ēT>-YHWH<YHWH> Ś<Ś>"],
[2023, "W:HāYâ<HYH> BayYôM<YôM> HaHû'<Hû'> 'e`ĕNeH<`NH> N:'uM<N:'uM>-YHWH<YHWH> 'e`ĕNeH<`NH> 'eT<'ēT>-HasShāMāYiM<ShāMaYiM> W:HēM<HēM> Ya`ăNû<`NH> 'eT<'ēT>-Hā'āReZ<'eReZ>"],
[2024, "W:Hā'āReZ<'eReZ> .Ta`ăNeH<`NH> 'eT<'ēT>-HadDāGāN<.DāGāN> W:'eT<'ēT>-HatTîRôSh<.TîRôSh> W:'eT<'ēT>-HayYiZ:HāR<YiZ:HāR> W:HēM<HēM> Ya`ăNû<`NH> 'eT<'ēT>-YiŹ:R:`e'L<YiŹ:R:`e'L>"],
[2025, "ûŹ:Ra`:.TîHā<ŹR`> lLî<L> Bā'āReZ<'eReZ> W:RiChaM:.Tî<RChM> 'eT<'ēT>-Lo'<Lo'> RuChāMâ<RChM> W:'āMaR:.Tî<'MR> L:Lo'-`amMî<Lo'-`amMî> `amMî<`aM>-'atTâ<'atTâ> W:Hû'<Hû'> Yo'MaR<'MR> 'ĕLoHāY<'ĕLoHîM> F<F>"],
[3001, "WayYo'MeR<'MR> YHWH<YHWH> 'ēLaY<'eL> `ôD<`ôD> LēK:<HLK:> 'ĕHaV<'HV>-'isShâ<'isShâ> 'ăHuVaT<'HV> Rē,a`<Rē,a`> ûM:Nā'āFeT<N'F> .K:'aHăVaT<'HV> YHWH<YHWH> 'eT<'ēT>-B:Nê<BēN> YiS:Rā'ēL<YiS:Rā'ēL> W:HēM<HēM> PoNîM<PNH> 'eL<'eL>-'ĕLoHîM<'ĕLoHîM> 'ăChēRîM<'aChēR> W:'oHăVê<'HV> 'ăShîShê<'ăShîShâ> `ăNāVîM<`ēNāV>"],
[3002, "Wā'ekK:ReHā<.KRH> lLî<L> BaChăMisShâ<ChăMisShâ> `āSāR<`āSāR> .KāŚeF<.KeŚeF> W:ChoMeR<ChoMeR> S:`oRîM<S:`oRâ> W:LēTeK:<LēTeK:> S:`oRîM<S:`oRâ>"],
[3003, "Wā'oMaR<'MR> 'ēLëHā<'eL> YāMîM<YôM> RaBîM<RaV> .TēSh:Vî<YShV> Lî<L> Lo'<Lo'> TiŹ:Nî<ŹNH> W:Lo'<Lo'> TiH:Yî<HYH> L:'îSh<'îSh> W:GaM<.GaM>-'ăNî<'ăNî> 'ēLāYiK:<'eL>"],
[3004, ".Kî<.Kî> YāMîM<YôM> RaBîM<RaV> YēSh:Vû<YShV> B:Nê<BēN> YiS:Rā'ēL<YiS:Rā'ēL> 'êN<'aYiN> MeLeK:<MeLeK:> W:'êN<'aYiN> SāR<SaR> W:'êN<'aYiN> ŹeVaCh<ŹeVaCh> W:'êN<'aYiN> MazZēVâ<MazZēVâ> W:'êN<'aYiN> 'ēFôD<'ēFôD> ûT:RāFîM<.T:RāFîM>"],
[3005, "'aChaR<'aChaR> YāShuVû<ShWV> B:Nê<BēN> YiS:Rā'ēL<YiS:Rā'ēL> ûViQ:Shû<BQSh> 'eT<'ēT>-YHWH<YHWH> 'ĕLoHêHeM<'ĕLoHîM> W:'ēT<'ēT> .DāWiD<.DāWiD> MaL:.KāM<MeLeK:> ûFāChăDû<PChD> 'eL<'eL>-YHWH<YHWH> W:'eL<'eL>-ThûVô<ThûV> B:'aChăRîT<'aChăRîT> HayYāMîM<YôM> F<F>"],
[4001, "ShiM:`û<ShM`> D:VaR<.DāVāR>-YHWH<YHWH> B:Nê<BēN> YiS:Rā'ēL<YiS:Rā'ēL> .Kî<.Kî> RîV<RîV> LaYHWâ<YHWH> `iM<`iM>-YôSh:Vê<YShV> Hā'āReZ<'eReZ> .Kî<.Kî> 'êN<'aYiN>-'ĕMeT<'ĕMeT> W:'êN<'aYiN>-CheŚeD<CheŚeD> W:'êN<'aYiN>-.Da`aT<.Da`aT> 'ĕLoHîM<'ĕLoHîM> Bā'āReZ<'eReZ>"],
[4002, "'āLoH<'LH> W:KaChēSh<.KChSh> W:RāZo,aCh<RZCh> W:GāNoV<.GNV> W:Nā'oF<N'F> PāRāZû<PRZ> W:DāMîM<.DāM> B:DāMîM<.DāM> NāGā`û<NG`>"],
[4003, "`aL<`aL>-.KēN<.KēN> .Te'ĕVaL<'VL> Hā'āReZ<'eReZ> W:'uM:LaL<'ML> .KāL<.KoL>-YôShēV<YShV> BāhH<B> B:ChayYaT<ChayYâ> HasSāDeH<SāDeH> ûV:`ôF<`ôF> HasShāMāYiM<ShāMaYiM> W:GaM<.GaM>-.D:Gê<.DāG> HayYāM<YāM> Yē'āŚēFû<'ŚF>"],
[4004, "'aK:<'aK:> 'îSh<'îSh> 'aL<'aL>-YāRēV<RYV> W:'aL<'aL>-YôKaCh<YKCh> 'îSh<'îSh> W:`amM:Kā<`aM> .KiM:RîVê<RYV> KoHēN<.KoHēN>"],
[4005, "W:KāShaL:.Tā<.KShL> HayYôM<YôM> W:KāShaL<.KShL> .GaM<.GaM>-NāVî'<NāVî'> `imM:Kā<`iM> LāY:Lâ<LaY:Lâ> W:DāMîTî<.DMH> 'imMeKā<'ēM>"],
[4006, "NiD:Mû<.DMH> `amMî<`aM> MiB:Lî<B:Lî> HadDā`aT<.Da`aT> .Kî<.Kî>-'atTâ<'atTâ> HadDa`aT<.Da`aT> Mā'aŚ:.Tā<M'Ś> W:'eM:'āŚ:'Kā<M'Ś> MikKaHēN<.KHN> Lî<L> WatTiSh:.KaCh<ShKCh> .TôRaT<.TôRâ> 'ĕLoHëKā<'ĕLoHîM> 'eSh:.KaCh<ShKCh> BāNëKā<BēN> .GaM<.GaM>-'āNî<'ăNî>"],
[4007, ".K:RuBāM<RVV> .KēN<.KēN> ChāTh:'û<ChTh'>-Lî<L> .K:VôDāM<.KāVôD> B:QāLôN<QāLôN> 'āMîR<MWR>"],
[4008, "ChatTha'T<ChatThā'T> `amMî<`aM> Yo'KēLû<'KL> W:'eL<'eL>-`ăWoNāM<`āWoN> YiS:'û<NS'> NaF:Shô<NeFeSh>"],
[4009, "W:HāYâ<HYH> Kā`āM<`aM> .KakKoHēN<.KoHēN> ûFāQaD:.Tî<PQD> `āLâv<`aL> .D:RāKâv<.DeReK:> ûMa`ăLāLâv<Ma`ăLāL> 'āShîV<ShWV> Lô<L>"],
[4010, "W:'āK:Lû<'KL> W:Lo'<Lo'> YiS:Bā`û<SV`> HiŹ:Nû<ŹNH> W:Lo'<Lo'> YiF:RoZû<PRZ> .Kî<.Kî>-'eT<'ēT>-YHWH<YHWH> `āŹ:Vû<`ŹV> LiSh:MoR<ShMR>"],
[4011, "Ź:NûT<Ź:NûT> W:YaYiN<YaYiN> W:TîRôSh<.TîRôSh> YiqQaCh<LQCh>-LēV<LēV>"],
[4012, "`amMî<`aM> B:`ēZô<`ēZ> YiSh:'āL<Sh'L> ûMaQ:Lô<MaqQēL> YagGîD<NGD> Lô<L> .Kî<.Kî> Rû,aCh<Rû,aCh> Ź:NûNîM<Ź:NûNîM> HiT:`â<.T`H> WayYiŹ:Nû<ŹNH> MitTaChaT<.TaChaT> 'ĕLoHêHeM<'ĕLoHîM>"],
[4013, "`aL<`aL>-Rā'Shê<Ro'Sh> HeHāRîM<HaR> Y:ŹaBēChû<ŹVCh> W:`aL<`aL>-HagG:Vā`ôT<.GiV:`â> Y:QatThēRû<QThR> .TaChaT<.TaChaT> 'alLôN<'alLôN> W:LiV:NeH<LiV:NeH> W:'ēLâ<'ēLâ> .Kî<.Kî> ThôV<ThôV> ZilLāhH<ZēL> `aL<`aL>-.KēN<.KēN> .TiŹ:NëNâ<ŹNH> B:NôTêKeM<BaT> W:KalLôTêKeM<.KalLâ> .T:Nā'aF:Nâ<N'F>"],
[4014, "Lo'<Lo'>-'eF:QôD<PQD> `aL<`aL>-B:NôTêKeM<BaT> .Kî<.Kî> TiŹ:NëNâ<ŹNH> W:`aL<`aL>-.KalLôTêKeM<.KalLâ> .Kî<.Kî> T:Nā'aF:Nâ<N'F> .Kî<.Kî>-HēM<HēM> `iM<`iM>-HaźŹoNôT<ŹNH> Y:FāRēDû<PRD> W:`iM<`iM>-HaqQ:DēShôT<Q:DēShâ> Y:ŹaBēChû<ŹVCh> W:`āM<`aM> Lo'<Lo'>-YāVîN<BYN> YilLāVēTh<LVTh>"],
[4015, "'iM<'iM>-ŹoNeH<ŹNH> 'atTâ<'atTâ> YiS:Rā'ēL<YiS:Rā'ēL> 'aL<'aL>-Ye':ShaM<'ShM> Y:HûDâ<Y:HûDâ> W:'aL<'aL>-.TāVo'û<BW'> HagGiL:.GāL<.GiL:.GāL> W:'aL<'aL>-.Ta`ăLû<`LH> BêT_'āWeN<BêT_'āWeN> W:'aL<'aL>-.TisShāV:`û<ShV`> ChaY<ChaY>-YHWH<YHWH>"],
[4016, ".Kî<.Kî> .K:FāRâ<PāRâ> ŚoRēRâ<ŚRR> ŚāRaR<ŚRR> YiS:Rā'ēL<YiS:Rā'ēL> `atTâ<`atTâ> YiR:`ēM<R`H> YHWH<YHWH> .K:KeVeS<.KeVeS> BamMeR:ChāV<MeR:ChāV>"],
[4017, "ChăVûR<ChVR> `ăZaBîM<`āZāV> 'eF:RāYiM<'eF:RaYiM> HanNaCh<NWCh>-Lô<L>"],
[4018, "ŚāR<ŚWR> ŚāV:'āM<ŚoVe'> HaŹ:NēH<ŹNH> HiŹ:Nû<ŹNH> 'āHăVû<'HV> HēVû<YHV> QāLôN<QāLôN> MāGinNëHā<MāGēN>"],
[4019, "ZāRaR<ZRR> Rû,aCh<Rû,aCh> 'ôTāhH<'ēT> BiK:NāFëHā<.KāNāF> W:YēVoShû<BWSh> MiźŹiV:ChôTāM<ŹeVaCh>"],
[5001, "ShiM:`û<ShM`>-Źo'T<Źo'T> HakKoHăNîM<.KoHēN> W:HaQ:ShîVû<QShV> BêT<BaYiT> YiS:Rā'ēL<YiS:Rā'ēL> ûVêT<BaYiT> HamMeLeK:<MeLeK:> Ha'ăŹîNû<'ŹN> .Kî<.Kî> LāKeM<L> HamMiSh:PāTh<MiSh:PāTh> .Kî<.Kî>-FaCh<PaCh> HĕYîTeM<HYH> L:MiZ:Pâ<MiZ:Pâ> W:ReSheT<ReSheT> P:RûSâ<PRS> `aL<`aL>-.TāVôR<.TāVôR>"],
[5002, "W:ShaChăThâ<ShaChăThâ> SēThîM<SēTh> He`:MîQû<`MQ> Wa'ăNî<'ăNî> MûŚāR<MûŚāR> L:KulLāM<.KoL>"],
[5003, "'ăNî<'ăNî> YāDa`:.Tî<YD`> 'eF:RaYiM<'eF:RaYiM> W:YiS:Rā'ēL<YiS:Rā'ēL> Lo'<Lo'>-NiK:ChaD<.KChD> MimMenNî<MiN> .Kî<.Kî> `atTâ<`atTâ> HiŹ:NêTā<ŹNH> 'eF:RaYiM<'eF:RaYiM> NiTh:Mā'<ThM'> YiS:Rā'ēL<YiS:Rā'ēL>"],
[5004, "Lo'<Lo'> YitT:Nû<NTN> Ma`aL:LêHeM<Ma`ăLāLîM> LāShûV<ShWV> 'eL<'eL>-'ĕLoHêHeM<'ĕLoHîM> .Kî<.Kî> Rû,aCh<Rû,aCh> Ź:NûNîM<Ź:NûNîM> B:QiR:BāM<QeReV> W:'eT<'ēT>-YHWH<YHWH> Lo'<Lo'> YāDā`û<YD`>"],
[5005, "W:`āNâ<`NH> G:'ôN<.Gā'ôN>-YiS:Rā'ēL<YiS:Rā'ēL> B:FāNâv<PāNeH> W:YiS:Rā'ēL<YiS:Rā'ēL> W:'eF:RaYiM<'eF:RaYiM> YikKāSh:Lû<.KShL> Ba`ăWoNāM<`āWoN> .KāShaL<.KShL> .GaM<.GaM>-Y:HûDâ<Y:HûDâ> `imMāM<`iM>"],
[5006, "B:Zo'NāM<Zo'N> ûViV:QāRāM<BāQāR> YēL:Kû<HLK:> L:VaqQēSh<BQSh> 'eT<'ēT>-YHWH<YHWH> W:Lo'<Lo'> YiM:Zā'û<MZ'> ChāLaZ<ChLZ> MēHeM<MiN>"],
[5007, "BaYHWâ<YHWH> BāGāDû<BGD> .Kî<.Kî>-VāNîM<BēN> ŹāRîM<ŹWR> YāLāDû<YLD> `atTâ<`atTâ> Yo'K:LēM<'KL> ChoDeSh<ChoDeSh> 'eT<'ēT>-CheL:QêHeM<ChēLeQ> Ś<Ś>"],
[5008, ".TiQ:`û<.TQ`> ShôFāR<ShôFāR> BagGiV:`â<.GiV:`â> ChăZoZ:Râ<ChăZoZ:Râ> BāRāMâ<RāMâ> HāRî`û<RW`> BêT_'āWeN<BêT_'āWeN> 'aChăRëKā<'aChăRê> BiN:YāMîN<BiNeYāMiN>"],
[5009, "'eF:RaYiM<'eF:RaYiM> L:ShamMâ<ShamMâ> TiH:YeH<HYH> B:YôM<YôM> .TôKēChâ<.TôKēChâ> B:ShiV:Thê<ShēVeTh> YiS:Rā'ēL<YiS:Rā'ēL> HôDa`:.Tî<YD`> Ne'ĕMāNâ<'MN>"],
[5010, "HāYû<HYH> SāRê<SaR> Y:HûDâ<Y:HûDâ> .K:MaśŚîGê<ŚWG> .G:VûL<.G:VûL> `ăLêHeM<`aL> 'eSh:PôK:<ShFK:> .KamMaYiM<MaYiM> `eV:RāTî<`eV:Râ>"],
[5011, "`āShûQ<`ShQ> 'eF:RaYiM<'eF:RaYiM> R:ZûZ<RZZ> MiSh:PāTh<MiSh:PāTh> .Kî<.Kî> Hô'îL<Y'L> HāLaK:<HLK:> 'aChăRê<'aChăRê>-ZāW<ZaW>"],
[5012, "Wa'ăNî<'ăNî> Kā`āSh<`āSh> L:'eF:RāYiM<'eF:RaYiM> W:KāRāQāV<RāQāV> L:VêT<BaYiT> Y:HûDâ<Y:HûDâ>"],
[5013, "WayYaR:'<R'H> 'eF:RaYiM<'eF:RaYiM> 'eT<'ēT>-ChāL:Yô<ChŏLî> WîHûDâ<Y:HûDâ> 'eT<'ēT>-M:ŹoRô<MāŹôR> WayYēLeK:<HLK:> 'eF:RaYiM<'eF:RaYiM> 'eL<'eL>-'asShûR<'asShûR> WayYiSh:LaCh<ShLCh> 'eL<'eL>-MeLeK:<MeLeK:> YāRēV<YāRēV> W:Hû'<Hû'> Lo'<Lo'> YûKaL<YKL> LiR:Po'<RF'> LāKeM<L> W:Lo'<Lo'>-YiG:HeH<.GHH> MikKeM<MiN> MāŹôR<MāŹôR>"],
[5014, ".Kî<.Kî> 'āNoKî<'āNoKî> KasShaChaL<ShaChaL> L:'eF:RaYiM<'eF:RaYiM> W:KakK:FîR<.K:FîR> L:VêT<BaYiT> Y:HûDâ<Y:HûDâ> 'ăNî<'ăNî> 'ăNî<'ăNî> 'eTh:RoF<ThRF> W:'ēLēK:<HLK:> 'esSā'<NS'> W:'êN<'aYiN> MazZîL<NZL>"],
[5015, "'ēLēK:<HLK:> 'āShûVâ<ShWV> 'eL<'eL>-M:QôMî<MāQôM> `aD<`aD> 'ăSheR<'ăSheR>-Ye':Sh:Mû<'ShM> ûViQ:Shû<BQSh> FāNāY<PāNîM> BazZaR<ZaR> LāHeM<L> Y:ShaChăRuN:Nî<ShChR>"],
[6001, "L:Kû<HLK:> W:NāShûVâ<ShWV> 'eL<'eL>-YHWH<YHWH> .Kî<.Kî> Hû'<Hû'> ThāRāF<ThRF> W:YiR:Pā'ēNû<RF'> YaK:<NKH> W:YaCh:B:ShēNû<ChVSh>"],
[6002, "Y:ChayYēNû<ChYH> MiyYoMāYiM<YôM> BayYôM<YôM> HasSh:LîShî<Sh:LîShî> Y:QiMēNû<QWM> W:NiCh:YeH<ChYH> L:FāNâv<PāNeH>"],
[6003, "W:NēD:`â<YD`> NiR:.D:Fâ<RDF> LāDa`aT<YD`> 'eT<'ēT>-YHWH<YHWH> .K:ShaChaR<ShaChaR> NāKôN<.KWN> MôZā'ô<MôZā'> W:YāVô'<BW'> KagGeSheM<.GeSheM> LāNû<L> .K:MaL:QôSh<MaL:QôSh> YôReH<YRH> 'āReZ<'eReZ>"],
[6004, "Mâ<Mâ> 'e`ĕSeH<`SH>-lL:Kā<L> 'eF:RaYiM<'eF:RaYiM> Mâ<Mâ> 'e`ĕSeH<`SH>-lL:Kā<L> Y:HûDâ<Y:HûDâ> W:ChaŚ:.D:KeM<CheŚeD> .Ka`ăNaN<`āNāN>-BoQeR<BoQeR> W:KatThaL<ThaL> MaSh:.KîM<ShKM> HoLēK:<HLK:>"],
[6005, "`aL<`aL>-.KēN<.KēN> ChāZaV:.Tî<ChZV> BanN:Vî'îM<NāVî'> HăRaG:.TîM<HRG> B:'iM:Rê<'ēMeR>-Fî<PeH> ûMiSh:PāThëKā<MiSh:PāTh> 'ôR<'ôR> YēZē'<YZ'>"],
[6006, ".Kî<.Kî> CheŚeD<CheŚeD> ChāFaZ:.Tî<ChFZ> W:Lo'<Lo'>-ŹāVaCh<ŹeVaCh> W:Da`aT<.Da`aT> 'ĕLoHîM<'ĕLoHîM> Mē`oLôT<`oLâ>"],
[6007, "W:HēmMâ<HēM> .K:'āDāM<'āDāM> `āV:Rû<`VR> V:RîT<B:RîT> ShāM<ShāM> BāG:Dû<BGD> Vî<B>"],
[6008, ".GiL:`āD<.GiL:`āD> QiR:YaT<QiR:Yâ> Po`ăLê<P`L> 'āWeN<'āWeN> `ăQuBâ<`āQoV> MidDāM<.DāM>"],
[6009, "ûK:ChakKê<ChKH> 'îSh<'îSh> .G:DûDîM<.G:DûD> CheVeR<CheVeR> .KoHăNîM<.KoHēN> .DeReK:<.DeReK:> Y:RazZ:Chû<RZCh>-SheK:Mâ<Sh:KeM> .Kî<.Kî> ŹimMâ<ŹimMâ> `āSû<`SH>"],
[6010, "B:VêT<BaYiT> YiS:Rā'ēL<YiS:Rā'ēL> Rā'îTî<R'H> [1 Sha`ăRîRiyYâ<Sha`ăRûRî> 1] [2 Sha`ăRûRiyYâ<Sha`ăRûRî> 2] ShāM<ShāM> Ź:NûT<Ź:NûT> L:'eF:RaYiM<'eF:RaYiM> NiTh:Mā'<ThM'> YiS:Rā'ēL<YiS:Rā'ēL>"],
[6011, ".GaM<.GaM>-Y:HûDâ<Y:HûDâ> ShāT<ShYT> QāZîR<QāZîR> LāK:<L> B:ShûVî<ShWV> Sh:VûT<Sh:VûT> `amMî<`aM> F<F>"],
[7001, ".K:RāF:'î<RF'> L:YiS:Rā'ēL<YiS:Rā'ēL> W:NiG:Lâ<.GLH> `ăWoN<`āWoN> 'eF:RaYiM<'eF:RaYiM> W:Rā`ôT<Rā`â> ShoM:RôN<ShoM:RôN> .Kî<.Kî> Fā`ăLû<P`L> ShāQeR<SheQeR> W:GanNāV<.GanNāV> YāVô'<BW'> PāShaTh<PShTh> .G:DûD<.G:DûD> BaChûZ<ChûZ>"],
[7002, "ûVaL<BaL>-Yo'M:Rû<'MR> LiL:VāVāM<LēVāV> .KāL<.KoL>-Rā`āTāM<Rā`â> ŹāKāR:.Tî<ŹKR> `atTâ<`atTâ> Ś:VāVûM<ŚVV> Ma`aL:LêHeM<Ma`ăLāLîM> NeGeD<NeGeD> PāNaY<PāNîM> HāYû<HYH>"],
[7003, "B:Rā`āTāM<Rā`â> Y:SamM:Chû<SMCh>-MeLeK:<MeLeK:> ûV:KaChăShêHeM<.KaChaSh> SāRîM<SaR>"],
[7004, ".KulLāM<.KoL> M:Nā'ăFîM<N'F> .K:Mô<.K> TanNûR<.TanNûR> Bo`ēRâ<B`R> Mē'oFeH<'FH> YiSh:BôT<ShVT> Mē`îR<`WR> MilLûSh<LWSh> BāZēQ<BāZēQ> `aD<`aD>-ChuM:ZāTô<ChMZ>"],
[7005, "YôM<YôM> MaL:.KēNû<MeLeK:> HeChĕLû<ChLH> SāRîM<SaR> ChăMaT<ChēMâ> MiyYāYiN<YaYiN> MāShaK:<MShK:> YāDô<YāD> 'eT<'ēT>-LoZ:ZîM<LYZ>"],
[7006, ".Kî<.Kî>-QēR:Vû<QRV> KatTanNûR<.TanNûR> LiBāM<LēV> B:'āR:BāM<'oReV> .KāL<.KoL>-HalLaY:Lâ<LaY:Lâ> YāShēN<YāShēN> 'oFēHeM<'FH> BoQeR<BoQeR> Hû'<Hû'> Vo`ēR<B`R> .K:'ēSh<'ēSh> LeHāVâ<LeHāVâ>"],
[7007, ".KulLāM<.KoL> YēChamMû<ChMM> .KatTanNûR<.TanNûR> W:'āK:Lû<'KL> 'eT<'ēT>-ShoF:ThêHeM<ShFTh> .KāL<.KoL>-MaL:KêHeM<MeLeK:> NāFāLû<NFL> 'êN<'aYiN>-QoRē'<QR'> VāHeM<B> 'ēLāY<'eL>"],
[7008, "'eF:RaYiM<'eF:RaYiM> Bā`amMîM<`aM> Hû'<Hû'> YiT:BôLāL<BLL> 'eF:RaYiM<'eF:RaYiM> HāYâ<HYH> `uGâ<`uGâ> B:Lî<B:Lî> HăFûKâ<HFK:>"],
[7009, "'āK:Lû<'KL> ŹāRîM<ŹWR> .KoChô<.Ko,aCh> W:Hû'<Hû'> Lo'<Lo'> YāDā`<YD`> .GaM<.GaM>-SêVâ<SêVâ> ŹāR:Qâ<ŹRQ> Bô<B> W:Hû'<Hû'> Lo'<Lo'> YāDā`<YD`>"],
[7010, "W:`āNâ<`NH> G:'ôN<.Gā'ôN>-YiS:Rā'ēL<YiS:Rā'ēL> B:FāNâv<PāNeH> W:Lo'<Lo'>-ShāVû<ShWV> 'eL<'eL>-YHWH<YHWH> 'ĕLoHêHeM<'ĕLoHîM> W:Lo'<Lo'> ViQ:ShuHû<BQSh> B:KāL<.KoL>-Źo'T<Źo'T>"],
[7011, "WaY:Hî<HYH> 'eF:RaYiM<'eF:RaYiM> .K:YôNâ<YôNâ> FôTâ<PTH> 'êN<'aYiN> LēV<LēV> MiZ:RaYiM<MiZ:RaYiM> QāRā'û<QR'> 'asShûR<'asShûR> HāLāKû<HLK:>"],
[7012, ".Ka'ăSheR<'ăSheR> YēLēKû<HLK:> 'eF:RôS<PRS> `ăLêHeM<`aL> RiSh:.Tî<ReSheT> .K:`ôF<`ôF> HasShāMaYiM<ShāMaYiM> 'ôRîDēM<YRD> 'aY:ŚiRēM<YŚR> .K:ShēMa`<ShēMa`> La`ăDāTāM<`ēDâ> Ś<Ś>"],
[7013, "'ôY<'ôY> LāHeM<L> .Kî<.Kî>-NāD:Dû<NDD> MimMenNî<MiN> ShoD<ShoD> LāHeM<L> .Kî<.Kî>-FāSh:`û<PSh`> Vî<B> W:'āNoKî<'āNoKî> 'eF:.DēM<PDH> W:HēmMâ<HēM> .DiB:Rû<.DVR> `āLaY<`aL> .K:ŹāVîM<.KāŹāV>"],
[7014, "W:Lo'<Lo'>-Źā`ăQû<Ź`Q> 'ēLaY<'eL> B:LiBāM<LēV> .Kî<.Kî> Y:YēLîLû<YLL> `aL<`aL>-MiSh:.K:VôTāM<MiSh:.KāV> `aL<`aL>-.DāGāN<.DāGāN> W:TîRôSh<.TîRôSh> YiT:.GôRāRû<.GRR> YāŚûRû<ŚWR> Vî<B>"],
[7015, "Wa'ăNî<'ăNî> YiśŚaR:.Tî<YŚR> ChiźŹaQ:.Tî<ChŹQ> Ź:Rô`oTāM<Ź:Rô,a`> W:'ēLaY<'eL> Y:ChasSh:Vû<ChShV>-Rā`<Ra`>"],
[7016, "YāShûVû<ShWV> Lo'<Lo'> `āL<`aL> HāYû<HYH> .K:QeSheT<QeSheT> R:MiyYâ<R:MiyYâ> YiP:Lû<NFL> VaCheReV<CheReV> SāRêHeM<SaR> MiźŹa`aM<Źa`aM> L:ShôNāM<LāShôN> Źô<Źô> La`:.GāM<La`aG> B:'eReZ<'eReZ> MiZ:RāYiM<MiZ:RaYiM>"],
[8001, "'eL<'eL>-ChikK:Kā<ChēK:> ShoFāR<ShôFāR> .KanNeSheR<NeSheR> `aL<`aL>-BêT<BaYiT> YHWH<YHWH> Ya`aN<Ya`aN> `āV:Rû<`VR> V:RîTî<B:RîT> W:`aL<`aL>-.TôRāTî<.TôRâ> PāShā`û<PSh`>"],
[8002, "Lî<L> YiŹ:`āQû<Ź`Q> 'ĕLoHaY<'ĕLoHîM> Y:Da`ăNûKā<YD`> YiS:Rā'ēL<YiS:Rā'ēL>"],
[8003, "ŹāNaCh<ŹNCh> YiS:Rā'ēL<YiS:Rā'ēL> ThôV<ThôV> 'ôYēV<'YV> YiR:.D:Fô<RDF>"],
[8004, "HēM<HēM> HiM:LîKû<MLK:> W:Lo'<Lo'> MimMenNî<MiN> HēSîRû<SRR> W:Lo'<Lo'> YāDā`:.Tî<YD`> .KaŚ:PāM<.KeŚeF> ûŹ:HāVāM<ŹāHāV> `āSû<`SH> LāHeM<L> `ăZaBîM<`āZāV> L:Ma`aN<L:Ma`aN> YikKāRēT<.KRT>"],
[8005, "ŹāNaCh<ŹNCh> `eG:LēK:<`ēGeL> ShoM:RôN<ShoM:RôN> ChāRâ<ChRH> 'aPî<'aF> BāM<B> `aD<`aD>-MāTaY<MāTaY> Lo'<Lo'> YûK:Lû<YKL> NiqQāYoN<NiqQāYôN>"],
[8006, ".Kî<.Kî> MiyYiS:Rā'ēL<YiS:Rā'ēL> W:Hû'<Hû'> ChāRāSh<ChāRāSh> `āSâû<`SH> W:Lo'<Lo'> 'ĕLoHîM<'ĕLoHîM> Hû'<Hû'> .Kî<.Kî>-Sh:VāVîM<Sh:VāVîM> YiH:YeH<HYH> `ēGeL<`ēGeL> ShoM:RôN<ShoM:RôN>"],
[8007, ".Kî<.Kî> Rû,aCh<Rû,aCh> YiŹ:Rā`û<ŹR`> W:ŚûFāTâ<ŚûFâ> YiQ:ZoRû<QZR> QāMâ<QāMâ> 'êN<'aYiN>-Lô<L> ZeMaCh<ZeMaCh> B:Lî<B:Lî> Ya`ăSeH<`SH>-qQeMaCh<QeMaCh> 'ûLaY<'ûLaY> Ya`ăSeH<`SH> ŹāRîM<ŹWR> YiV:Lā`uHû<BL`>"],
[8008, "NiV:La`<BL`> YiS:Rā'ēL<YiS:Rā'ēL> `atTâ<`atTâ> HāYû<HYH> VagGôYiM<.GôY> .KiK:Lî<.K:Lî> 'êN<'aYiN>-ChēFeZ<ChēFeZ> Bô<B>"],
[8009, ".Kî<.Kî>-HēmMâ<HēM> `āLû<`LH> 'asShûR<'asShûR> PeRe'<PeRe'> BôDēD<BDD> Lô<L> 'eF:RaYiM<'eF:RaYiM> HiT:Nû<.TNH> 'ăHāVîM<'aHāVîM>"],
[8010, ".GaM<.GaM> .Kî<.Kî>-YiT:Nû<.TNH> VagGôYiM<.GôY> `atTâ<`atTâ> 'ăQaB:ZēM<QVZ> WayYāChēlLû<ChLL> mM:`āTh<M:`aTh> MimMasSā'<MasSā'> MeLeK:<MeLeK:> SāRîM<SaR>"],
[8011, ".Kî<.Kî>-HiR:Bâ<RVH> 'eF:RaYiM<'eF:RaYiM> MiŹ:B:ChoT<MiŹ:Bē,aCh> LaChăTho'<ChTh'> HāYû<HYH>-Lô<L> MiŹ:B:ChôT<MiŹ:Bē,aCh> LaChăTho'<ChTh'>"],
[8012, "[1 'eKTôV<.KTV>- 1] [2 'eK:.TāV<.KTV>- 2]Lô<L> [1 RiBô<RiBô> 1] [2 RuBê<RoV> 2] .TôRāTî<.TôRâ> .K:Mô<.K>-ŹāR<ŹWR> NeCh:ShāVû<ChShV>"],
[8013, "ŹiV:Chê<ŹeVaCh> HaV:HāVaY<HaV:HāVîM> YiŹ:B:Chû<ŹVCh> VāSāR<BāSāR> WayYo'KēLû<'KL> YHWH<YHWH> Lo'<Lo'> RāZāM<RZH> `atTâ<`atTâ> YiŹ:.KoR<ŹKR> `ăWoNāM<`āWoN> W:YiF:QoD<PQD> ChatTho'WTāM<ChatThā'T> HēmMâ<HēM> MiZ:RaYiM<MiZ:RaYiM> YāShûVû<ShWV>"],
[8014, "WayYiSh:.KaCh<ShKCh> YiS:Rā'ēL<YiS:Rā'ēL> 'eT<'ēT>-`oSēHû<`SH> WayYiVeN<BNH> HêKāLôT<HêKāL> WîHûDâ<Y:HûDâ> HiR:Bâ<RVH> `āRîM<`îR> B:ZuRôT<BZR> W:ShilLaCh:.Tî<ShLCh>-'ēSh<'ēSh> B:`āRâv<`îR> W:'āK:Lâ<'KL> 'aR:M:NoTëHā<'aR:MôN> Ś<Ś>"],
[9001, "'aL<'aL>-.TiS:MaCh<SMCh> YiS:Rā'ēL<YiS:Rā'ēL> 'eL<'eL>-.GîL<.GîL> .Kā`amMîM<`aM> .Kî<.Kî> ŹāNîTā<ŹNH> Mē`aL<`aL> 'ĕLoHëKā<'ĕLoHîM> 'āHaV:.Tā<'HV> 'eT:NāN<'eT:NaN> `aL<`aL> .KāL<.KoL>-.GāR:NôT<.GoReN> .DāGāN<.DāGāN>"],
[9002, ".GoReN<.GoReN> WāYeQeV<YeQeV> Lo'<Lo'> YiR:`ēM<R`H> W:TîRôSh<.TîRôSh> Y:KaCheSh<.KChSh> BāhH<B>"],
[9003, "Lo'<Lo'> YēSh:Vû<YShV> B:'eReZ<'eReZ> YHWH<YHWH> W:ShāV<ShWV> 'eF:RaYiM<'eF:RaYiM> MiZ:RaYiM<MiZ:RaYiM> ûV:'asShûR<'asShûR> ThāMē'<ThāMē'> Yo'KēLû<'KL>"],
[9004, "Lo'<Lo'>-YiśŚ:Kû<NŚK:> LaYHWâ<YHWH> YaYiN<YaYiN> W:Lo'<Lo'> Ye`eR:Vû<`RV>-Lô<L> ŹiV:ChêHeM<ŹeVaCh> .K:LeCheM<LeCheM> 'ôNîM<'ôN> LāHeM<L> .KāL<.KoL>-'oK:Lâv<'KL> YiThamMā'û<ThM'> .Kî<.Kî>-LaCh:MāM<LeCheM> L:NaF:ShāM<NeFeSh> Lo'<Lo'> YāVô'<BW'> BêT<BaYiT> YHWH<YHWH>"],
[9005, "MaH<Mâ>-.Ta`ăSû<`SH> L:YôM<YôM> Mô`ēD<Mô`ēD> ûL:YôM<YôM> ChaG<ChaG>-YHWH<YHWH>"],
[9006, ".Kî<.Kî>-HinNēH<HinNēH> HāL:Kû<HLK:> MisShoD<ShoD> MiZ:RaYiM<MiZ:RaYiM> .T:QaB:ZēM<QVZ> MoF<MoF> .T:QaB:RēM<QVR> MaCh:MaD<MaCh:MāD> L:KaŚ:PāM<.KeŚeF> QimMôS<QimMôS> YîRāShēM<YRSh> Chô,aCh<Chô,aCh> B:'āHŏLêHeM<'oHeL>"],
[9007, "Bā'û<BW'> Y:Mê<YôM> HaP:QudDâ<P:QudDâ> Bā'û<BW'> Y:Mê<YôM> HaShilLuM<ShilLûM> YēD:`û<YD`> YiS:Rā'ēL<YiS:Rā'ēL> 'ĕWîL<'ĕWîL> HanNāVî'<NāVî'> M:ShugGā`<ShG`> 'îSh<'îSh> HāRû,aCh<Rû,aCh> `aL<`aL> RoV<RoV> `ăWoN:Kā<`āWoN> W:RaBâ<RaBâ> MaS:ThēMâ<MaS:ThēMâ>"],
[9008, "ZoFeH<ZFH> 'eF:RaYiM<'eF:RaYiM> `iM<`iM>-'ĕLoHāY<'ĕLoHîM> NāVî'<NāVî'> PaCh<PaCh> YāQôSh<YāQôSh> `aL<`aL>-.KāL<.KoL>-.D:RāKâv<.DeReK:> MaS:ThēMâ<MaS:ThēMâ> B:VêT<BaYiT> 'ĕLoHâv<'ĕLoHîM>"],
[9009, "He`:MîQû<`MQ>-ShiChēTû<ShChT> .KîMê<YôM> HagGiV:`â<.GiV:`â> YiŹ:.KôR<ŹKR> `ăWoNāM<`āWoN> YiF:QôD<PQD> ChatTho'WTāM<ChatThā'T> Ś<Ś>"],
[9010, ".Ka`ăNāVîM<`ēNāV> BamMiD:BāR<MiD:BāR> MāZā'Tî<MZ'> YiS:Rā'ēL<YiS:Rā'ēL> .K:VikKûRâ<BikKûRâ> ViT:'ēNâ<.T:'ēNâ> B:Rē'ShîTāhH<Rē'ShîT> Rā'îTî<R'H> 'ăVôTêKeM<'āV> HēmMâ<HēM> Bā'û<BW'> Va`aL-P:`ôR<Ba`aL_P:`ôR> WayYinNāŹ:Rû<NŹR> LaBoSheT<BoSheT> WayYiH:Yû<HYH> ShiqQûZîM<ShiqQûZ> .K:'āHŏVāM<'HV>"],
[9011, "'eF:RaYiM<'eF:RaYiM> .Kā`ôF<`ôF> YiT:`ôFēF<`WF> .K:VôDāM<.KāVôD> MilLēDâ<YLD> ûMiBeTheN<BeTheN> ûMēHēRāYôN<HēRāYôN>"],
[9012, ".Kî<.Kî> 'iM<'iM>-Y:GadD:Lû<.GDL> 'eT<'ēT>-B:NêHeM<BēN> W:ShikKaL:.TîM<ShKL> Mē'āDāM<'āDāM> .Kî<.Kî>-GaM<.GaM>-'ôY<'ôY> LāHeM<L> B:SûRî<SWR> MēHeM<MiN>"],
[9013, "'eF:RaYiM<'eF:RaYiM> .Ka'ăSheR<'ăSheR>-Rā'îTî<R'H> L:ZôR<ZoR> Sh:TûLâ<ShTL> V:NāWeH<NāWeH> W:'eF:RaYiM<'eF:RaYiM> L:HôZî'<YZ'> 'eL<'eL>-HoRēG<HRG> BāNâv<BēN>"],
[9014, ".TēN<NTN>-LāHeM<L> YHWH<YHWH> MaH<Mâ>-.TitTēN<NTN> .TēN<NTN>-LāHeM<L> ReCheM<ReCheM> MaSh:.KîL<ShKL> W:ShāDaYiM<ShaD> ZoM:QîM<ZMQ>"],
[9015, ".KāL<.KoL>-Rā`āTāM<Rā`â> BagGiL:.GāL<.GiL:.GāL> .Kî<.Kî>-ShāM<ShāM> S:Nē'TîM<SN'> `aL<`aL> Ro,a`<Ro,a`> Ma`aL:LêHeM<Ma`ăLāLîM> MiBêTî<BaYiT> 'ăGāR:ShēM<.GRSh> Lo'<Lo'> 'ôŚēF<YŚF> 'aHăVāTāM<'HV> .KāL<.KoL>-SāRêHeM<SaR> ŚoR:RîM<ŚRR>"],
[9016, "HukKâ<NKH> 'eF:RaYiM<'eF:RaYiM> ShāR:ShāM<ShoReSh> YāVēSh<YVSh> P:Rî<P:Rî> [1 V:Lî<B:Lî>- 1] [2 VaL<BaL>- 2]Ya`ăSûN<`SH> .GaM<.GaM> .Kî<.Kî> YēLēDûN<YLD> W:HēMatTî<MWT> MaChăMadDê<MaCh:MāD> ViTh:NāM<BeTheN> Ś<Ś>"],
[9017, "YiM:'āŚēM<M'Ś> 'ĕLoHaY<'ĕLoHîM> .Kî<.Kî> Lo'<Lo'> ShāM:`û<ShM`> Lô<L> W:YiH:Yû<HYH> NoD:DîM<NDD> BagGôYiM<.GôY> Ś<Ś>"],
[10001, ".GeFeN<.GeFeN> BôQēQ<BQQ> YiS:Rā'ēL<YiS:Rā'ēL> P:Rî<P:Rî> Y:ShaûeH<ShWH>-lLô<L> .K:RoV<RoV> L:FiR:Yô<P:Rî> HiR:Bâ<RVH> LamMiŹ:B:ChôT<MiŹ:Bē,aCh> .K:ThôV<ThôV> L:'aR:Zô<'eReZ> HêThîVû<YThV> MazZēVôT<MazZēVâ>"],
[10002, "ChāLaQ<ChLQ> LiBāM<LēV> `atTâ<`atTâ> Ye':ShāMû<'ShM> Hû'<Hû'> Ya`ăRoF<`RF> MiŹ:B:ChôTāM<MiŹ:Bē,aCh> Y:ShoDēD<ShDD> MazZēVôTāM<MazZēVâ>"],
[10003, ".Kî<.Kî> `atTâ<`atTâ> Yo'M:Rû<'MR> 'êN<'aYiN> MeLeK:<MeLeK:> LāNû<L> .Kî<.Kî> Lo'<Lo'> YāRē'Nû<YR'> 'eT<'ēT>-YHWH<YHWH> W:HamMeLeK:<MeLeK:> MaH<Mâ>-yYa`ăSeH<`SH>-lLāNû<L>"],
[10004, ".DiB:Rû<.DVR> D:VāRîM<.DāVāR> 'āLôT<'LH> ShāW:'<ShāW:'> .KāRoT<.KRT> B:RîT<B:RîT> ûFāRaCh<PRCh> .KāRo'Sh<Ro'Sh> MiSh:PāTh<MiSh:PāTh> `aL<`aL> .TaL:Mê<.TeLeM> SāDāY<SāDeH>"],
[10005, "L:`eG:LôT<`eG:Lâ> BêT_'āWeN<BêT_'āWeN> YāGûRû<.GWR> Sh:KaN<ShāKēN> ShoM:RôN<ShoM:RôN> .Kî<.Kî>-'āVaL<'VL> `āLâv<`aL> `amMô<`aM> ûK:MāRâv<.KoMeR> `āLâv<`aL> YāGîLû<.GYL> `aL<`aL>-.K:VôDô<.KāVôD> .Kî<.Kî>-GāLâ<.GLH> MimMenNû<MiN>"],
[10006, ".GaM<.GaM>-'ôTô<'ēT> L:'asShûR<'asShûR> YûVāL<YVL> MiN:Châ<MiN:Châ> L:MeLeK:<MeLeK:> YāRēV<YāRēV> BāSh:Nâ<BāSh:Nâ> 'eF:RaYiM<'eF:RaYiM> YiqQāCh<LQCh> W:YēVôSh<BWSh> YiS:Rā'ēL<YiS:Rā'ēL> Mē`ăZāTô<`ēZâ>"],
[10007, "NiD:MeH<.DMH> ShoM:RôN<ShoM:RôN> MaL:.KāhH<MeLeK:> .K:QeZeF<QeZeF> `aL<`aL>-P:Nê<PāNîM>-MāYiM<MaYiM>"],
[10008, "W:NiSh:M:Dû<ShMD> BāMôT<BāMâ> 'āWeN<'āWeN> ChatTha'T<ChatThā'T> YiS:Rā'ēL<YiS:Rā'ēL> QôZ<QôZ> W:DaR:.DaR<.DaR:.DaR> Ya`ăLeH<`LH> `aL<`aL>-MiŹ:B:ChôTāM<MiŹ:Bē,aCh> W:'āM:Rû<'MR> LeHāRîM<HaR> .KaśŚûNû<.KŚH> W:LagG:Vā`ôT<.GiV:`â> NiF:Lû<NFL> `āLêNû<`aL> Ś<Ś>"],
[10009, "MîMê<YôM> HagGiV:`â<.GiV:`â> ChāThā'Tā<ChTh'> YiS:Rā'ēL<YiS:Rā'ēL> ShāM<ShāM> `āMāDû<`MD> Lo'<Lo'>-TasSîGēM<NSG> BagGiV:`â<.GiV:`â> MiL:ChāMâ<MiL:ChāMâ> `aL<`aL>-B:Nê<BēN> `aL:Wâ<`aL:Wâ>"],
[10010, "B:'aûāTî<'aûâ> W:'eśŚŏRēM<YŚR> W:'uśŚ:Fû<'ŚF> `ăLêHeM<`aL> `amMîM<`aM> B:'āŚ:RāM<'ŚR> LiSh:.Tê<Sh:.TaYiM> [1 `êNoTāM<`ôNôT> 1] [2 `ôNoTāM<`ôNôT> 2]"],
[10011, "W:'eF:RaYiM<'eF:RaYiM> `eG:Lâ<`eG:Lâ> M:LumMāDâ<LMD> 'oHaV:.Tî<'HV> LāDûSh<.DWSh> Wa'ăNî<'ăNî> `āVaR:.Tî<`VR> `aL<`aL>-ThûV<ThûV> Zaûā'RāhH<Zaûā'R> 'aR:.KîV<RKV> 'eF:RaYiM<'eF:RaYiM> YaChăRôSh<ChRSh> Y:HûDâ<Y:HûDâ> Y:SadDeD<SDD>-Lô<L> Ya`ăQoV<Ya`ăQoV>"],
[10012, "ŹiR:`û<ŹR`> LāKeM<L> LiZ:DāQâ<Z:DāQâ> QiZ:Rû<QZR> L:Fî<PeH>-CheŚeD<CheŚeD> NîRû<NYR> LāKeM<L> NîR<NîR> W:`ēT<`ēT> LiD:RôSh<.DRSh> 'eT<'ēT>-YHWH<YHWH> `aD<`aD>-YāVô'<BW'> W:YoReH<YRH> ZeDeQ<ZeDeQ> LāKeM<L>"],
[10013, "ChăRaSh:.TeM<ChRSh>-ReSha`<ReSha`> `aW:LāTâ<`aW:Lâ> Q:ZaR:.TeM<QZR> 'ăKaL:.TeM<'KL> P:Rî<P:Rî>-KāChaSh<.KaChaSh> .Kî<.Kî>-VāThaCh:.Tā<BThCh> V:DaR:.K:Kā<.DeReK:> B:RoV<RoV> .GiBôRëKā<.GiBôR>"],
[10014, "W:Qā'M<QWM> Shā'ôN<Shā'ôN> B:`amMeKā<`aM> W:KāL<.KoL>-MiV:ZāRëKā<MiV:ZāR> YûsShaD<ShDD> .K:ShoD<ShoD> ShaL:MaN<ShaL:MaN> BêT_'aR:Vē'L<BêT_'aR:Vē'L> B:YôM<YôM> MiL:ChāMâ<MiL:ChāMâ> 'ēM<'ēM> `aL<`aL>-BāNîM<BēN> RutThāShâ<RThSh>"],
[10015, ".KāKâ<.KāKâ> `āSâ<`SH> LāKeM<L> BêT-'ēL<BêT-'ēL> MiP:Nê<PāNeH> Rā`aT<Rā`â> Rā`aT:KeM<Rā`â> BasShaChaR<ShaChaR> NiD:MoH<.DMH> NiD:Mâ<.DMH> MeLeK:<MeLeK:> YiS:Rā'ēL<YiS:Rā'ēL>"],
[11001, ".Kî<.Kî> Na`aR<Na`aR> YiS:Rā'ēL<YiS:Rā'ēL> Wā'oHăVēHû<'HV> ûMimMiZ:RaYiM<MiZ:RaYiM> QāRā'Tî<QR'> LiV:Nî<BēN>"],
[11002, "QāR:'û<QR'> LāHeM<L> .KēN<.KēN> HāL:Kû<HLK:> MiP:NêHeM<PāNîM> LaB:`āLîM<B:`āLîM> Y:ŹaBēChû<ŹVCh> W:LaP:ŚiLîM<PāŚîL> Y:QatThēRûN<QThR>"],
[11003, "W:'āNoKî<'āNoKî> TiR:.GaL:.Tî<RGL> L:'eF:RaYiM<'eF:RaYiM> QāChāM<LQCh> `aL<`aL>-Ź:Rô`oTâv<Ź:Rô,a`> W:Lo'<Lo'> YāD:`û<YD`> .Kî<.Kî> R:Fā'TîM<RF'>"],
[11004, "B:ChaV:Lê<CheVeL> 'āDāM<'āDāM> 'eM:Sh:KēM<MShK:> Ba`ăVoTôT<`ăVôT> 'aHăVâ<'aHăVâ> Wā'eH:YeH<HYH> LāHeM<L> .KiM:RîMê<RWM> `oL<`oL> `aL<`aL> L:ChêHeM<L:Chî> W:'aTh<NThH> 'ēLâv<'eL> 'ôKîL<'KL>"],
[11005, "Lo'<Lo'> YāShûV<ShWV> 'eL<'eL>-'eReZ<'eReZ> MiZ:RaYiM<MiZ:RaYiM> W:'asShûR<'asShûR> Hû'<Hû'> MaL:.Kô<MeLeK:> .Kî<.Kî> Mē'ăNû<M'N> LāShûV<ShWV>"],
[11006, "W:ChāLâ<ChWL> CheReV<CheReV> B:`āRâv<`îR> W:KilL:Tâ<.KLH> VadDâv<BaD> W:'āKāLâ<'KL> MimMo`ăZôTêHeM<Mô`ēZâ>"],
[11007, "W:`amMî<`aM> T:Lû'îM<.TL'> LiM:ShûVāTî<M:ShûVâ> W:'eL<'eL>-`aL<`aL> YiQ:Rā'uHû<QR'> YaChaD<YaChaD> Lo'<Lo'> Y:RôMēM<RWM>"],
[11008, "'êK:<'êK:> 'etTeN:Kā<NTN> 'eF:RaYiM<'eF:RaYiM> 'ăMagGeN:Kā<MGN> YiS:Rā'ēL<YiS:Rā'ēL> 'êK:<'êK:> 'etTeN:Kā<NTN> K:'aD:Mâ<'aD:Mâ> 'ăSîM:Kā<SYM> .KiZ:Vo'YiM<Z:VôYîM> NeH:PaK:<HFK:> `āLaY<`aL> LiBî<LēV> YaChaD<YaChaD> NiK:M:Rû<.KMR> NiChûMāY<NiChûMîM>"],
[11009, "Lo'<Lo'> 'e`ĕSeH<`SH> ChăRôN<ChāRôN> 'aPî<'aF> Lo'<Lo'> 'āShûV<ShWV> L:ShaChēT<ShChT> 'eF:RāYiM<'eF:RaYiM> .Kî<.Kî> 'ēL<'ēL> 'āNoKî<'āNoKî> W:Lo'<Lo'>-'îSh<'îSh> B:QiR:B:Kā<QeReV> QāDôSh<QāDôSh> W:Lo'<Lo'> 'āVô'<BW'> B:`îR<`îR>"],
[11010, "'aChăRê<'aChăRê> YHWH<YHWH> YēL:Kû<HLK:> .K:'aR:YēH<'aR:YēH> YiSh:'āG<Sh'G> .Kî<.Kî>-Hû'<Hû'> YiSh:'aG<Sh'G> W:YeCheR:Dû<ChRD> VāNîM<BēN> MiyYāM<YāM>"],
[11011, "YeCheR:Dû<ChRD> K:ZiPôR<ZiPôR> MimMiZ:RaYiM<MiZ:RaYiM> ûK:YôNâ<YôNâ> Mē'eReZ<'eReZ> 'asShûR<'asShûR> W:HôShaV:.TîM<YShV> `aL<`aL>-BātTêHeM<BaYiT> N:'uM<N:'uM>-YHWH<YHWH> Ś<Ś>"],
[12001, "Ś:VāVuNî<ŚVV> V:KaChaSh<.KaChaSh> 'eF:RaYiM<'eF:RaYiM> ûV:MiR:Mâ<MiR:Mâ> BêT<BaYiT> YiS:Rā'ēL<YiS:Rā'ēL> WîHûDâ<Y:HûDâ> `oD<`ôD> RāD<RWD> `iM<`iM>-'ēL<'ēL> W:`iM<`iM>-Q:DôShîM<QāDôSh> Ne'ĕMāN<'MN>"],
[12002, "'eF:RaYiM<'eF:RaYiM> Ro`eH<R`H> Rû,aCh<Rû,aCh> W:RoDēF<RDF> QāDîM<QāDîM> .KāL<.KoL>-HayYôM<YôM> .KāŹāV<.KāŹāV> WāShoD<ShoD> YaR:BeH<RVH> ûV:RîT<B:RîT> `iM<`iM>-'asShûR<'asShûR> YiK:RoTû<.KRT> W:SheMeN<SheMeN> L:MiZ:RaYiM<MiZ:RaYiM> YûVāL<YVL>"],
[12003, "W:RîV<RîV> LaYHWâ<YHWH> `iM<`iM>-Y:HûDâ<Y:HûDâ> W:LiF:QoD<PQD> `aL<`aL>-Ya`ăQoV<Ya`ăQoV> .KiD:RāKâv<.DeReK:> .K:Ma`ăLāLâv<Ma`ăLāL> YāShîV<ShWV> Lô<L>"],
[12004, "BaBeTheN<BeTheN> `āQaV<`QV> 'eT<'ēT>-'āChîW<'āCh> ûV:'ôNô<'ôN> SāRâ<SRH> 'eT<'ēT>-'ĕLoHîM<'ĕLoHîM>"],
[12005, "WāyYāSaR<SRH> 'eL<'eL>-MaL:'āK:<MaL:'āK:> WayYuKāL<YKL> BāKâ<BKH> WayYiT:ChanNeN<ChNN>-Lô<L> BêT-'ēL<BêT-'ēL> YiM:Zā'enNû<MZ'> W:ShāM<ShāM> Y:DaBēR<.DVR> `imMāNû<`iM>"],
[12006, "WaYHWâ<YHWH> 'ĕLoHê<'ĕLoHîM> HazZ:Vā'ôT<ZāVā'> YHWH<YHWH> ŹiK:Rô<ŹēKeR>"],
[12007, "W:'atTâ<'atTâ> Bē'LoHëKā<'ĕLoHîM> TāShûV<ShWV> CheŚeD<CheŚeD> ûMiSh:PāTh<MiSh:PāTh> Sh:MoR<ShMR> W:QaûēH<QWH> 'eL<'eL>-'ĕLoHëKā<'ĕLoHîM> .TāMîD<.TāMîD>"],
[12008, ".K:Na`aN<.K:Na`aN> B:YāDô<YāD> Mo'Ź:Nê<Mo'Ź:NaYiM> MiR:Mâ<MiR:Mâ> La`ăShoQ<`ShQ> 'āHēV<'HV>"],
[12009, "WayYo'MeR<'MR> 'eF:RaYiM<'eF:RaYiM> 'aK:<'aK:> `āShaR:.Tî<`ShR> MāZā'Tî<MZ'> 'ôN<'ôN> Lî<L> .KāL<.KoL>-Y:Gî`aY<Y:Gî,a`> Lo'<Lo'> YiM:Z:'û<MZ'>-Lî<L> `āWoN<`āWoN> 'ăSheR<'ăSheR>-ChēTh:'<ChēTh:'>"],
[12010, "W:'āNoKî<'āNoKî> YHWH<YHWH> 'ĕLoHëKā<'ĕLoHîM> Mē'eReZ<'eReZ> MiZ:RāYiM<MiZ:RaYiM> `oD<`ôD> 'ôShîV:Kā<ShWV> Vā'ŏHāLîM<'oHeL> .KîMê<YôM> Mô`ēD<Mô`ēD>"],
[12011, "W:DiBaR:.Tî<.DVR> `aL<`aL>-HanN:Vî'îM<NāVî'> W:'āNoKî<'āNoKî> ChāŹôN<ChāŹôN> HiR:BêTî<RVH> ûV:YaD<YāD> HanN:Vî'îM<NāVî'> 'ăDamMeH<.DMH>"],
[12012, "'iM<'iM>-.GiL:`āD<.GiL:`āD> 'āWeN<'āWeN> 'aK:<'aK:>-ShāW:'<ShāW:'> HāYû<HYH> BagGiL:.GāL<.GiL:.GāL> Sh:WāRîM<ShôR> ŹiBēChû<ŹVCh> .GaM<.GaM> MiŹ:B:ChôTāM<MiŹ:Bē,aCh> .K:GalLîM<.GaL> `aL<`aL> .TaL:Mê<.TeLeM> SāDāY<SāDeH>"],
[12013, "WayYiV:RaCh<BRCh> Ya`ăQoV<Ya`ăQoV> S:DēH<SāDeH> 'ăRāM<'ăRāM> WayYa`ăVoD<`VD> YiS:Rā'ēL<YiS:Rā'ēL> B:'isShâ<'isShâ> ûV:'isShâ<'isShâ> ShāMāR<ShMR>"],
[12014, "ûV:NāVî'<NāVî'> He`ĕLâ<`LH> YHWH<YHWH> 'eT<'ēT>-YiS:Rā'ēL<YiS:Rā'ēL> MimMiZ:RāYiM<MiZ:RaYiM> ûV:NāVî'<NāVî'> NiSh:MāR<ShMR>"],
[12015, "HiK:`îŚ<.K`Ś> 'eF:RaYiM<'eF:RaYiM> .TaM:RûRîM<.TaM:RûRîM> W:DāMâv<.DāM> `āLâv<`aL> YitThôSh<NThSh> W:CheR:PāTô<CheR:Pâ> YāShîV<ShWV> Lô<L> 'ăDoNâv<'āDôN>"],
[13001, ".K:DaBēR<.DVR> 'eF:RaYiM<'eF:RaYiM> R:TēT<R:TēT> NāSā'<NS'> Hû'<Hû'> B:YiS:Rā'ēL<YiS:Rā'ēL> WayYe':ShaM<'ShM> BaBa`aL<Ba`aL> WayYāMoT<MWT>"],
[13002, "W:`atTâ<`atTâ> YôŚiFû<YŚF> LaChăTho'<ChTh'> WayYa`:Sû<`SH> LāHeM<L> MaśŚēKâ<MaśŚēKâ> MikKaŚ:PāM<.KeŚeF> .KiT:VûNāM<.T:VûNâ> `ăZaBîM<`āZāV> Ma`ăSēH<Ma`ăSeH> ChāRāShîM<ChāRāSh> .KulLoH<.KoL> LāHeM<L> HēM<HēM> 'oM:RîM<'MR> ŹoV:Chê<ŹVCh> 'āDāM<'āDāM> `ăGāLîM<`ēGeL> YisShāQûN<NShQ>"],
[13003, "LāKēN<.KēN> YiH:Yû<HYH> .Ka`ăNaN<`āNāN>-BoQeR<BoQeR> W:KatThaL<ThaL> MaSh:.KîM<ShKM> HoLēK:<HLK:> .K:MoZ<MôZ> Y:Śo`ēR<Ś`R> MigGoReN<.GoReN> ûK:`āShāN<`āShāN> Mē'ăRuBâ<'ăRuBâ>"],
[13004, "W:'āNoKî<'āNoKî> YHWH<YHWH> 'ĕLoHëKā<'ĕLoHîM> Mē'eReZ<'eReZ> MiZ:RāYiM<MiZ:RaYiM> Wē'LoHîM<'ĕLoHîM> ŹûLāTî<ŹûLaT> Lo'<Lo'> TēDā`<YD`> ûMôShî,a`<YSh`> 'aYiN<'aYiN> BiL:.Tî<BiL:.Tî>"],
[13005, "'ăNî<'ăNî> Y:Da`:.TîKā<YD`> BamMiD:BāR<MiD:BāR> B:'eReZ<'eReZ> .TaL:'uVôT<.TaL:'ûVôT>"],
[13006, ".K:MaR:`îTāM<MaR:`îT> WayYiS:Bā`û<SV`> SāV:`û<SV`> WayYāRāM<RWM> LiBāM<LēV> `aL<`aL>-.KēN<.KēN> Sh:KēChûNî<ShKCh>"],
[13007, "Wā'ĕHî<HYH> LāHeM<L> .K:Mô<.K>-ShāChaL<ShaChaL> .K:NāMēR<NāMēR> `aL<`aL>-.DeReK:<.DeReK:> 'āShûR<ShWR>"],
[13008, "'eF:.G:ShēM<PGSh> .K:DoV<.DoV> ShakKûL<ShakKûL> W:'eQ:Ra`<QR`> Ś:GôR<Ś:GôR> LiBāM<LēV> W:'oK:LēM<'KL> ShāM<ShāM> .K:LāVî'<LāVî'> ChayYaT<ChayYâ> HasSāDeH<SāDeH> .T:VaqQ:`ēM<BQ`>"],
[13009, "ShiCheT:Kā<ShChT> YiS:Rā'ēL<YiS:Rā'ēL> .Kî<.Kî>-Vî<B> V:`eŹ:ReKā<`ēŹeR>"],
[13010, "'ĕHî<'ĕHî> MaL:.K:Kā<MeLeK:> 'ēFô'<'ēFô'> W:YôShî`ăKā<YSh`> B:KāL<.KoL>-`āRëKā<`îR> W:ShoF:ThëKā<ShFTh> 'ăSheR<'ăSheR> 'āMaR:.Tā<'MR> .T:Nâ<NTN>-lLî<L> MeLeK:<MeLeK:> W:SāRîM<SaR>"],
[13011, "'etTeN<NTN>-L:Kā<L> MeLeK:<MeLeK:> B:'aPî<'aF> W:'eqQaCh<LQCh> B:`eV:RāTî<`eV:Râ> Ś<Ś>"],
[13012, "ZāRûR<ZRR> `ăWoN<`āWoN> 'eF:RāYiM<'eF:RaYiM> Z:FûNâ<ZFN> ChatThā'Tô<ChatThā'T>"],
[13013, "CheV:Lê<ChēVeL> YôLēDâ<YLD> YāVo'û<BW'> Lô<L> Hû'<Hû'>-VēN<BēN> Lo'<Lo'> ChāKāM<ChāKāM> .Kî<.Kî>-`ēT<`ēT> Lo'<Lo'>-Ya`ăMoD<`MD> B:MiSh:BaR<MaSh:BēR> BāNîM<BēN>"],
[13014, "MiyYaD<YāD> Sh:'ôL<Sh:'ôL> 'eF:.DēM<PDH> MimMāWeT<MāWeT> 'eG:'āLēM<.G'L> 'ĕHî<'ĕHî> D:VāRëKā<.DāVāR> MāWeT<MāWeT> 'ĕHî<'ĕHî> QāThāV:Kā<QeTheV> Sh:'ôL<Sh:'ôL> NoChaM<NoChaM> YiśŚāTēR<ŚTR> Mē`êNāY<`aYiN>"],
[13015, ".Kî<.Kî> Hû'<Hû'> BēN<BēN> 'aChîM<'āCh> YaF:Rî'<PRH> YāVô'<BW'> QāDîM<QāDîM> Rû,aCh<Rû,aCh> YHWH<YHWH> MimMiD:BāR<MiD:BāR> `oLeH<`LH> W:YēVôSh<BWSh> M:QôRô<MāQôR> W:YeChĕRaV<ChRV> Ma`:YāNô<Ma`:YāN> Hû'<Hû'> YiSh:ŚeH<ShŚH> 'ôZaR<'ôZāR> .KāL<.KoL>-.K:Lî<.K:Lî> CheM:.Dâ<CheM:.Dâ>"],
[14001, ".Te':ShaM<'ShM> ShoM:RôN<ShoM:RôN> .Kî<.Kî> MāR:Tâ<MRH> Bē'LoHëHā<'ĕLoHîM> BaCheReV<CheReV> YiPoLû<NFL> `oL:LêHeM<`ôLēL> Y:RutThāShû<RThSh> W:HāRiyYôTâv<HāRiyYâ> Y:VuqQā`û<BQ`> F<F>"],
[14002, "ShûVâ<ShWV> YiS:Rā'ēL<YiS:Rā'ēL> `aD<`aD> YHWH<YHWH> 'ĕLoHëKā<'ĕLoHîM> .Kî<.Kî> KāShaL:.Tā<.KShL> Ba`ăWoNeKā<`āWoN>"],
[14003, "Q:Chû<LQCh> `imMāKeM<`iM> .D:VāRîM<.DāVāR> W:ShûVû<ShWV> 'eL<'eL>-YHWH<YHWH> 'iM:Rû<'MR> 'ēLâv<'eL> .KāL<.KoL>-.TisSā'<NS'> `āWoN<`āWoN> W:QaCh<LQCh>-ThôV<ThôV> ûN:ShalL:Mâ<ShLM> FāRîM<PaR> S:FāTêNû<SāFâ>"],
[14004, "'asShûR<'asShûR> Lo'<Lo'> YôShî`ēNû<YSh`> `aL<`aL>-ŚûŚ<ŚûŚ> Lo'<Lo'> NiR:.KāV<RKV> W:Lo'<Lo'>-No'MaR<'MR> `ôD<`ôD> 'ĕLoHêNû<'ĕLoHîM> L:Ma`ăSēH<Ma`ăSeH> YāDêNû<YāD> 'ăSheR<'ăSheR>-B:Kā<B> Y:RuChaM<RChM> YāTôM<YāTôM>"],
[14005, "'eR:Pā'<RF'> M:ShûVāTāM<M:ShûVâ> 'oHăVēM<'HV> N:DāVâ<N:DāVâ> .Kî<.Kî> ShāV<ShWV> 'aPî<'aF> MimMenNû<MiN>"],
[14006, "'eH:YeH<HYH> KatThaL<ThaL> L:YiS:Rā'ēL<YiS:Rā'ēL> YiF:RaCh<PRCh> .KasShôShanNâ<ShôShāN> W:YaK:<NKH> ShāRāShâv<ShoReSh> .KalL:VāNôN<L:VāNôN>"],
[14007, "YēL:Kû<HLK:> YoN:QôTâv<YôNeQeT> WîHî<HYH> KaźŹaYiT<ŹaYiT> HôDô<HôD> W:Rê,aCh<Rê,aCh> Lô<L> .KalL:VāNôN<L:VāNôN>"],
[14008, "YāShuVû<ShWV> YoSh:Vê<YShV> V:ZilLô<ZēL> Y:ChayYû<ChYH> DāGāN<.DāGāN> W:YiF:R:Chû<PRCh> KagGāFeN<.GeFeN> ŹiK:Rô<ŹēKeR> .K:YêN<YaYiN> L:VāNôN<L:VāNôN> Ś<Ś>"],
[14009, "'eF:RaYiM<'eF:RaYiM> MaH<Mâ>-lLî<L> `ôD<`ôD> Lā`ăZaBîM<`āZāV> 'ăNî<'ăNî> `āNîTî<`NH> Wa'ăShûRenNû<ShWR> 'ăNî<'ăNî> .KiV:RôSh<B:RôSh> Ra`ăNāN<Ra`ăNāN> MimMenNî<MiN> PeR:Y:Kā<P:Rî> NiM:Zā'<MZ'>"],
[14010, "Mî<Mî> ChāKāM<ChāKāM> W:YāVēN<BYN> 'ēlLeH<'ēlLeH> NāVôN<BYN> W:YēDā`ēM<YD`> .Kî<.Kî>-Y:ShāRîM<YāShāR> .DaR:Kê<.DeReK:> YHWH<YHWH> W:ZadDiQîM<ZadDîQ> YēL:Kû<HLK:> VāM<B> ûFoSh:`îM<PSh`> YikKāSh:Lû<.KShL> VāM<B>"]
])
