Bib.ret([
[1001, ".DiV:Rê<.DāVāR> QoHeLeT<QoHeLeT> BeN<BēN>-.DāWiD<.DāWiD> MeLeK:<MeLeK:> BîRûShāLāiM<Y:RûShāLaiM>"],
[1002, "HăVēL<HeVeL> HăVāLîM<HeVeL> 'āMaR<'MR> QoHeLeT<QoHeLeT> HăVēL<HeVeL> HăVāLîM<HeVeL> HakKoL<.KoL> HāVeL<HeVeL>"],
[1003, "MaH<Mâ>-yYiT:RôN<YiT:RôN> Lā'āDāM<'āDāM> B:KāL<.KoL>-`ăMāLô<`āMāL> SheyYa`ăMoL<`ML> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[1004, ".DôR<.DôR> HoLēK:<HLK:> W:DôR<.DôR> Bā'<BW'> W:Hā'āReZ<'eReZ> L:`ôLāM<`ôLāM> `oMāDeT<`MD>"],
[1005, "W:ŹāRaCh<ŹRCh> HasSheMeSh<SheMeSh> ûVā'<BW'> HasShāMeSh<SheMeSh> W:'eL<'eL>-M:QôMô<MāQôM> Shô'ēF<Sh'F> ŹôRē,aCh<ŹRCh> Hû'<Hû'> ShāM<ShāM>"],
[1006, "HôLēK:<HLK:> 'eL<'eL>-.DāRôM<.DāRôM> W:ŚôVēV<ŚVV> 'eL<'eL>-ZāFôN<ZāFôN> ŚôVēV<ŚVV> ŚoVēV<ŚVV> HôLēK:<HLK:> HāRû,aCh<Rû,aCh> W:`aL<`aL>-Ś:VîVoTâv<ŚāVîV> ShāV<ShWV> HāRû,aCh<Rû,aCh>"],
[1007, ".KāL<.KoL>-HanN:ChāLîM<NaChaL> HoL:KîM<HLK:> 'eL<'eL>-HayYāM<YāM> W:HayYāM<YāM> 'êNenNû<'aYiN> MāLē'<MāLē'> 'eL<'eL>-M:QôM<MāQôM> SheHanN:ChāLîM<NaChaL> HoL:KîM<HLK:> ShāM<ShāM> HēM<HēM> ShāVîM<ShWV> LāLāKeT<HLK:>"],
[1008, ".KāL<.KoL>-HadD:VāRîM<.DāVāR> Y:Gē`îM<YāGē,a`> Lo'<Lo'>-YûKaL<YKL> 'îSh<'îSh> L:DaBēR<.DVR> Lo'<Lo'>-TiS:Ba`<SV`> `aYiN<`aYiN> LiR:'ôT<R'H> W:Lo'<Lo'>-TimMāLē'<ML'> 'oŹeN<'oŹeN> MisSh:Mo,a`<ShM`>"],
[1009, "MaH<Mâ>-sSheHāYâ<HYH> Hû'<Hû'> SheyYiH:YeH<HYH> ûMaH<Mâ>-sShenNa`ăSâ<`SH> Hû'<Hû'> SheyYē`āSeH<`SH> W:'êN<'aYiN> .KāL<.KoL>-ChāDāSh<ChāDāSh> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[1010, "YēSh<YēSh> .DāVāR<.DāVāR> SheyYo'MaR<'MR> R:'ēH<R'H>-ŹeH<ŹeH> ChāDāSh<ChāDāSh> Hû'<Hû'> .K:VāR<.K:VāR> HāYâ<HYH> L:`oLāMîM<`ôLāM> 'ăSheR<'ăSheR> HāYâ<HYH> MilL:FāNēNû<PāNeH>"],
[1011, "'êN<'aYiN> ŹiK:RôN<ŹikKāRôN> LāRi'ShoNîM<Ri'ShôN> W:GaM<.GaM> Lā'aChăRoNîM<'aChăRôN> SheyYiH:Yû<HYH> Lo'<Lo'>-YiH:YeH<HYH> LāHeM<L> ŹikKāRôN<ŹikKāRôN> `iM<`iM> SheyYiH:Yû<HYH> Lā'aChăRoNâ<'aChăRôN> F<F>"],
[1012, "'ăNî<'ăNî> QoHeLeT<QoHeLeT> HāYîTî<HYH> MeLeK:<MeLeK:> `aL<`aL>-YiS:Rā'ēL<YiS:Rā'ēL> BîRûShāLāiM<Y:RûShāLaiM>"],
[1013, "W:NāTatTî<NTN> 'eT<'ēT>-LiBî<LēV> LiD:RôSh<.DRSh> W:LāTûR<.TWR> BaChāK:Mâ<ChāK:Mâ> `aL<`aL> .KāL<.KoL>-'ăSheR<'ăSheR> Na`ăSâ<`SH> .TaChaT<.TaChaT> HasShāMāYiM<ShāMaYiM> Hû'<Hû'> `iN:YaN<`iN:YāN> Rā`<Ra`> NāTaN<NTN> 'ĕLoHîM<'ĕLoHîM> LiV:Nê<BēN> Hā'āDāM<'āDāM> La`ăNôT<`NH> Bô<B>"],
[1014, "Rā'îTî<R'H> 'eT<'ēT>-.KāL<.KoL>-HamMa`ăSîM<Ma`ăSeH> ShenNa`ăSû<`SH> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> W:HinNēH<HinNēH> HakKoL<.KoL> HeVeL<HeVeL> ûR:`ûT<R:`ûT> Rû,aCh<Rû,aCh>"],
[1015, "M:`uûāT<`WT> Lo'<Lo'>-YûKaL<YKL> LiT:QoN<.TQN> W:CheŚ:RôN<CheŚ:RôN> Lo'<Lo'>-YûKaL<YKL> L:HimMāNôT<MNH>"],
[1016, ".DiBaR:.Tî<.DVR> 'ăNî<'ăNî> `iM<`iM>-LiBî<LēV> Lē'MoR<'MR> 'ăNî<'ăNî> HinNēH<HinNēH> HiG:.DaL:.Tî<.GDL> W:HôŚaF:.Tî<YŚF> ChāK:Mâ<ChāK:Mâ> `aL<`aL> .KāL<.KoL>-'ăSheR<'ăSheR>-HāYâ<HYH> L:FāNaY<PāNîM> `aL<`aL>-Y:RûShāLāiM<Y:RûShāLaiM> W:LiBî<LēV> Rā'â<R'H> HaR:BēH<RVH> ChāK:Mâ<ChāK:Mâ> WāDā`aT<.Da`aT>"],
[1017, "Wā'etT:Nâ<NTN> LiBî<LēV> LāDa`aT<YD`> ChāK:Mâ<ChāK:Mâ> W:Da`aT<YD`> HôLēLôT<HôLēLôT> W:SiK:LûT<ŚiK:LûT> YāDa`:.Tî<YD`> ShegGaM<.GaM>-ŹeH<ŹeH> Hû'<Hû'> Ra`:YôN<Ra`:YôN> Rû,aCh<Rû,aCh>"],
[1018, ".Kî<.Kî> B:RoV<RoV> ChāK:Mâ<ChāK:Mâ> RāV<RoV>-.Kā`aŚ<.Ka`aŚ> W:YôŚîF<YŚF> .Da`aT<.Da`aT> YôŚîF<YŚF> MaK:'ôV<MaK:'ôV>"],
[2001, "'āMaR:.Tî<'MR> 'ăNî<'ăNî> B:LiBî<LēV> L:Kâ<HLK:>-.Nā'<Nā'> 'ăNaśŚ:Kâ<NŚH> V:SiM:Châ<SiM:Châ> ûR:'ēH<R'H> V:ThôV<ThôV> W:HinNēH<HinNēH> GaM<.GaM>-Hû'<Hû'> HāVeL<HeVeL>"],
[2002, "LiS:ChôQ<SChQ> 'āMaR:.Tî<'MR> M:HôLāL<HLL> ûL:SiM:Châ<SiM:Châ> MaH<Mâ>-źŹoH<ŹoH> `oSâ<`SH>"],
[2003, ".TaR:.Tî<.TWR> V:LiBî<LēV> LiM:ShôK:<MShK:> BayYaYiN<YaYiN> 'eT<'ēT>-B:SāRî<BāSāR> W:LiBî<LēV> NoHēG<NHG> BaChāK:Mâ<ChāK:Mâ> W:Le'ĕChoŹ<'ChŹ> B:ŚiK:LûT<ŚiK:LûT> `aD<`aD> 'ăSheR<'ăSheR>-'eR:'eH<R'H> 'ê<'ê>-ŹeH<ŹeH> ThôV<ThôV> LiV:Nê<BēN> Hā'āDāM<'āDāM> 'ăSheR<'ăSheR> Ya`ăSû<`SH> .TaChaT<.TaChaT> HasShāMaYiM<ShāMaYiM> MiŚ:PaR<MiŚ:PāR> Y:Mê<YôM> ChayYêHeM<ChayYîM>"],
[2004, "HiG:.DaL:.Tî<.GDL> Ma`ăSāY<Ma`ăSeH> BāNîTî<BNH> Lî<L> BātTîM<BaYiT> NāTha`:.Tî<NTh`> Lî<L> .K:RāMîM<.KeReM>"],
[2005, "`āSîTî<`SH> Lî<L> .GanNôT<.GanNâ> ûFaR:.DēŚîM<PaR:.DēŚ> W:NāTha`:.Tî<NTh`> VāHeM<B> `ēZ<`ēZ> .KāL<.KoL>-PeRî<P:Rî>"],
[2006, "`āSîTî<`SH> Lî<L> B:RēKôT<B:RēKâ> MāYiM<MaYiM> L:HaSh:QôT<ShQH> MēHeM<MiN> Ya`aR<Ya`aR> ZôMē,aCh<ZMCh> `ēZîM<`ēZ>"],
[2007, "QāNîTî<QNH> `ăVāDîM<`eVeD> ûSh:FāChôT<ShiF:Châ> ûV:Nê<BēN>-VaYiT<BaYiT> HāYâ<HYH> Lî<L> .GaM<.GaM> MiQ:NeH<MiQ:NeH> VāQāR<BāQāR> WāZo'N<Zo'N> HaR:BēH<RVH> HāYâ<HYH> Lî<L> MikKoL<.KoL> SheHāYû<HYH> L:FāNaY<PāNîM> BîRûShāLāiM<Y:RûShāLaiM>"],
[2008, ".KāNaŚ:.Tî<.KNŚ> Lî<L> .GaM<.GaM>-.KeŚeF<.KeŚeF> W:ŹāHāV<ŹāHāV> ûŚ:GulLaT<Ś:GulLâ> M:LāKîM<MeLeK:> W:HamM:DîNôT<M:DîNâ> `āSîTî<`SH> Lî<L> ShāRîM<ShYR> W:ShāRôT<ShYR> W:Ta`ăNûGoT<.Ta`ăNûG> B:Nê<BēN> Hā'āDāM<'āDāM> ShidDâ<ShidDâ> W:ShidDôT<ShidDâ>"],
[2009, "W:GāDaL:.Tî<.GDL> W:HôŚaF:.Tî<YŚF> MikKoL<.KoL> SheHāYâ<HYH> L:FāNaY<PāNîM> BîRûShāLāiM<Y:RûShāLaiM> 'aF<'aF> ChāK:MāTî<ChāK:Mâ> `āM:Dâ<`MD> lLî<L>"],
[2010, "W:KoL<.KoL> 'ăSheR<'ăSheR> Shā'ăLû<Sh'L> `êNaY<`aYiN> Lo'<Lo'> 'āZaL:.Tî<'ZL> MēHeM<MiN> Lo'<Lo'>-MāNa`:.Tî<MN`> 'eT<'ēT>-LiBî<LēV> MikKāL<.KoL>-SiM:Châ<SiM:Châ> .Kî<.Kî>-LiBî<LēV> SāMē,aCh<SāMē,aCh> MikKāL<.KoL>-`ăMāLî<`āMāL> W:ŹeH<ŹeH>-HāYâ<HYH> CheL:Qî<ChēLeQ> MikKāL<.KoL>-`ăMāLî<`āMāL>"],
[2011, "ûFāNîTî<PNH> 'ăNî<'ăNî> B:KāL<.KoL>-Ma`ăSaY<Ma`ăSeH> She`āSû<`SH> YāDaY<YāD> ûVe`āMāL<`āMāL> She`āMaL:.Tî<`ML> La`ăSôT<`SH> W:HinNēH<HinNēH> HakKoL<.KoL> HeVeL<HeVeL> ûR:`ûT<R:`ûT> Rû,aCh<Rû,aCh> W:'êN<'aYiN> YiT:RôN<YiT:RôN> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[2012, "ûFāNîTî<PNH> 'ăNî<'ăNî> LiR:'ôT<R'H> ChāK:Mâ<ChāK:Mâ> W:HôLēLôT<HôLēLôT> W:ŚiK:LûT<ŚiK:LûT> .Kî<.Kî> MeH<Mâ> Hā'āDāM<'āDāM> SheyYāVô'<BW'> 'aChăRê<'aChăRê> HamMeLeK:<MeLeK:> 'ēT<'ēT> 'ăSheR<'ăSheR>-.K:VāR<.K:VāR> `āSûHû<`SH>"],
[2013, "W:Rā'îTî<R'H> 'āNî<'ăNî> SheyYēSh<YēSh> YiT:RôN<YiT:RôN> LaChāK:Mâ<ChāK:Mâ> MiN<MiN>-HaśŚiK:LûT<ŚiK:LûT> .KîT:RôN<YiT:RôN> Hā'ôR<'ôR> MiN<MiN>-HaChoSheK:<ChoSheK:>"],
[2014, "HeChāKāM<ChāKāM> `êNâv<`aYiN> B:Ro'Shô<Ro'Sh> W:HakK:ŚîL<.K:ŚîL> BaChoSheK:<ChoSheK:> HôLēK:<HLK:> W:YāDa`:.Tî<YD`> GaM<.GaM>-'āNî<'ăNî> ShemMiQ:ReH<MiQ:ReH> 'eChāD<'eChāD> YiQ:ReH<QRH> 'eT<'ēT>-.KulLāM<.KoL>"],
[2015, "W:'āMaR:.Tî<'MR> 'ăNî<'ăNî> B:LiBî<LēV> .K:MiQ:RēH<MiQ:ReH> HakK:ŚîL<.K:ŚîL> .GaM<.GaM>-'ăNî<'ăNî> YiQ:RēNî<QRH> W:LāmMâ<LāmMâ> ChāKaM:.Tî<ChKM> 'ăNî<'ăNî> 'āŹ<'āŹ> YôTēR<YôTēR> W:DiBaR:.Tî<.DVR> V:LiBî<LēV> ShegGaM<.GaM>-ŹeH<ŹeH> HāVeL<HeVeL>"],
[2016, ".Kî<.Kî> 'êN<'aYiN> ŹiK:RôN<ŹikKāRôN> LeChāKāM<ChāKāM> `iM<`iM>-HakK:ŚîL<.K:ŚîL> L:`ôLāM<`ôLāM> B:ShekK:VāR<.K:VāR> HayYāMîM<YôM> HaBā'îM<BW'> HakKoL<.KoL> NiSh:.KāCh<ShKCh> W:'êK:<'êK:> YāMûT<MWT> HeChāKāM<ChāKāM> `iM<`iM>-HakK:ŚîL<.K:ŚîL>"],
[2017, "W:SāNē'Tî<SN'> 'eT<'ēT>-HaChayYîM<ChayYîM> .Kî<.Kî> Ra`<Ra`> `āLaY<`aL> HamMa`ăSeH<Ma`ăSeH> ShenNa`ăSâ<`SH> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> .Kî<.Kî>-HakKoL<.KoL> HeVeL<HeVeL> ûR:`ûT<R:`ûT> Rû,aCh<Rû,aCh>"],
[2018, "W:SāNē'Tî<SN'> 'ăNî<'ăNî> 'eT<'ēT>-.KāL<.KoL>-`ăMāLî<`āMāL> She'ăNî<'ăNî> `āMēL<`āMēL> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> She'anNîChenNû<NWCh> Lā'āDāM<'āDāM> SheyYiH:YeH<HYH> 'aChăRāY<'aChăRê>"],
[2019, "ûMî<Mî> YôDē,a`<YD`> HeChāKāM<ChāKāM> YiH:YeH<HYH> 'ô<'ô> ŚāKāL<ŚāKāL> W:YiSh:LaTh<ShLTh> B:KāL<.KoL>-`ăMāLî<`āMāL> She`āMaL:.Tî<`ML> W:SheChāKaM:.Tî<ChKM> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> .GaM<.GaM>-ŹeH<ŹeH> HāVeL<HeVeL>"],
[2020, "W:ŚaBôTî<ŚVV> 'ăNî<'ăNî> L:Ya'ēSh<Y'Sh> 'eT<'ēT>-LiBî<LēV> `aL<`aL> .KāL<.KoL>-He`āMāL<`āMāL> She`āMaL:.Tî<`ML> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[2021, ".Kî<.Kî>-YēSh<YēSh> 'āDāM<'āDāM> She`ăMāLô<`ML> B:ChāK:Mâ<ChāK:Mâ> ûV:Da`aT<.Da`aT> ûV:KiSh:RôN<.KiSh:RôN> ûL:'āDāM<'āDāM> ShelLo'<Lo'> `āMaL<`ML>-Bô<B> YitT:NenNû<NTN> CheL:Qô<ChēLeQ> .GaM<.GaM>-ŹeH<ŹeH> HeVeL<HeVeL> W:Rā`â<Rā`â> RaBâ<RaBâ>"],
[2022, ".Kî<.Kî> MeH<Mâ>-HôeH<HWH> Lā'āDāM<'āDāM> B:KāL<.KoL>-`ăMāLô<`āMāL> ûV:Ra`:YôN<Ra`:YôN> LiBô<LēV> SheHû'<Hû'> `āMēL<`āMēL> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[2023, ".Kî<.Kî> KāL<.KoL>-YāMâv<YôM> MaK:'oVîM<MaK:'ôV> WāKa`aŚ<.Ka`aŚ> `iN:YāNô<`iN:YāN> .GaM<.GaM>-BalLaY:Lâ<LaY:Lâ> Lo'<Lo'>-ShāKaV<ShKV> LiBô<LēV> .GaM<.GaM>-ŹeH<ŹeH> HeVeL<HeVeL> Hû'<Hû'>"],
[2024, "'êN<'aYiN>-ThôV<ThôV> Bā'āDāM<'āDāM> SheyYo'KaL<'KL> W:ShāTâ<ShTH> W:HeR:'â<R'H> 'eT<'ēT>-NaF:Shô<NeFeSh> ThôV<ThôV> Ba`ăMāLô<`āMāL> .GaM<.GaM>-ŹoH<ŹoH> Rā'îTî<R'H> 'āNî<'ăNî> .Kî<.Kî> MiyYaD<YāD> Hā'ĕLoHîM<'ĕLoHîM> Hî'<Hî'>"],
[2025, ".Kî<.Kî> Mî<Mî> Yo'KaL<'KL> ûMî<Mî> YāChûSh<ChWSh> ChûZ<ChûZ> MimMenNî<MiN>"],
[2026, ".Kî<.Kî> L:'āDāM<'āDāM> ShetThôV<ThôV> L:FāNâv<PāNeH> NāTaN<NTN> ChāK:Mâ<ChāK:Mâ> W:Da`aT<.Da`aT> W:SiM:Châ<SiM:Châ> W:LaChôThe'<ChTh'> NāTaN<NTN> `iN:YāN<`iN:YāN> Le'ĕŚôF<'ŚF> W:LiK:NôŚ<.KNŚ> LāTēT<NTN> L:ThôV<ThôV> LiF:Nê<PāNeH> Hā'ĕLoHîM<'ĕLoHîM> .GaM<.GaM>-ŹeH<ŹeH> HeVeL<HeVeL> ûR:`ûT<R:`ûT> Rû,aCh<Rû,aCh>"],
[3001, "LakKoL<.KoL> Ź:MāN<Ź:MaN> W:`ēT<`ēT> L:KāL<.KoL>-ChēFeZ<ChēFeZ> .TaChaT<.TaChaT> HasShāMāYiM<ShāMaYiM> Ś<Ś>"],
[3002, "`ēT<`ēT> LāLeDeT<YLD> W:`ēT<`ēT> LāMûT<MWT> `ēT<`ēT> LāTha`aT<NTh`> W:`ēT<`ēT> La`ăQôR<`QR> NāThû,a`<NTh`>"],
[3003, "`ēT<`ēT> LaHăRôG<HRG> W:`ēT<`ēT> LiR:Pô'<RF'> `ēT<`ēT> LiF:RôZ<PRZ> W:`ēT<`ēT> LiV:NôT<BNH>"],
[3004, "`ēT<`ēT> LiV:.KôT<BKH> W:`ēT<`ēT> LiS:ChôQ<SChQ> `ēT<`ēT> Ś:FôD<ŚFD> W:`ēT<`ēT> R:QôD<RQD>"],
[3005, "`ēT<`ēT> L:HaSh:LîK:<ShLK:> 'ăVāNîM<'eVeN> W:`ēT<`ēT> .K:NôŚ<.KNŚ> 'ăVāNîM<'eVeN> `ēT<`ēT> LaChăVôQ<ChVQ> W:`ēT<`ēT> LiR:ChoQ<RChQ> MēChaBēQ<ChVQ>"],
[3006, "`ēT<`ēT> L:VaqQēSh<BQSh> W:`ēT<`ēT> L:'aBēD<'VD> `ēT<`ēT> LiSh:MôR<ShMR> W:`ēT<`ēT> L:HaSh:LîK:<ShLK:>"],
[3007, "`ēT<`ēT> LiQ:Rô,a`<QR`> W:`ēT<`ēT> LiT:PôR<.TFR> `ēT<`ēT> LaChăShôT<ChShH> W:`ēT<`ēT> L:DaBēR<.DVR>"],
[3008, "`ēT<`ēT> Le'ĕHoV<'HV> W:`ēT<`ēT> LiS:No'<SN'> `ēT<`ēT> MiL:ChāMâ<MiL:ChāMâ> W:`ēT<`ēT> ShāLôM<ShāLôM>"],
[3009, "MaH<Mâ>-yYiT:RôN<YiT:RôN> Hā`ôSeH<`SH> Ba'ăSheR<'ăSheR> Hû'<Hû'> `āMēL<`āMēL>"],
[3010, "Rā'îTî<R'H> 'eT<'ēT>-Hā`iN:YāN<`iN:YāN> 'ăSheR<'ăSheR> NāTaN<NTN> 'ĕLoHîM<'ĕLoHîM> LiV:Nê<BēN> Hā'āDāM<'āDāM> La`ăNôT<`NH> Bô<B>"],
[3011, "'eT<'ēT>-HakKoL<.KoL> `āSâ<`SH> YāFeH<YāFeH> V:`itTô<`ēT> .GaM<.GaM> 'eT<'ēT>-Hā`oLāM<`ôLāM> NāTaN<NTN> B:LiBāM<LēV> MiB:Lî<B:Lî> 'ăSheR<'ăSheR> Lo'<Lo'>-YiM:Zā'<MZ'> Hā'āDāM<'āDāM> 'eT<'ēT>-HamMa`ăSeH<Ma`ăSeH> 'ăSheR<'ăSheR>-`āSâ<`SH> Hā'ĕLoHîM<'ĕLoHîM> MēRo'Sh<Ro'Sh> W:`aD<`aD>-ŚôF<ŚôF>"],
[3012, "YāDa`:.Tî<YD`> .Kî<.Kî> 'êN<'aYiN> ThôV<ThôV> BāM<B> .Kî<.Kî> 'iM<'iM>-LiS:Mô,aCh<SMCh> W:La`ăSôT<`SH> ThôV<ThôV> B:ChayYâv<ChayYîM>"],
[3013, "W:GaM<.GaM> .KāL<.KoL>-Hā'āDāM<'āDāM> SheyYo'KaL<'KL> W:ShāTâ<ShTH> W:Rā'â<R'H> ThôV<ThôV> B:KāL<.KoL>-`ăMāLô<`āMāL> MatTaT<MatTāT> 'ĕLoHîM<'ĕLoHîM> Hî'<Hî'>"],
[3014, "YāDa`:.Tî<YD`> .Kî<.Kî> .KāL<.KoL>-'ăSheR<'ăSheR> Ya`ăSeH<`SH> Hā'ĕLoHîM<'ĕLoHîM> Hû'<Hû'> YiH:YeH<HYH> L:`ôLāM<`ôLāM> `āLâv<`aL> 'êN<'aYiN> L:HôŚîF<YŚF> ûMimMenNû<MiN> 'êN<'aYiN> LiG:Ro,a`<.GR`> W:Hā'ĕLoHîM<'ĕLoHîM> `āSâ<`SH> SheyYiR:'û<YR'> MilL:FāNâv<PāNeH>"],
[3015, "MaH<Mâ>-sSheHāYâ<HYH> .K:VāR<.K:VāR> Hû'<Hû'> Wa'ăSheR<'ăSheR> LiH:YôT<HYH> .K:VāR<.K:VāR> HāYâ<HYH> W:Hā'ĕLoHîM<'ĕLoHîM> Y:VaqQēSh<BQSh> 'eT<'ēT>-NiR:.DāF<RDF>"],
[3016, "W:`ôD<`ôD> Rā'îTî<R'H> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> M:QôM<MāQôM> HamMiSh:PāTh<MiSh:PāTh> ShāmMâ<ShāM> HāReSha`<ReSha`> ûM:QôM<MāQôM> HazZeDeQ<ZeDeQ> ShāmMâ<ShāM> HāRāSha`<ReSha`>"],
[3017, "'āMaR:.Tî<'MR> 'ăNî<'ăNî> B:LiBî<LēV> 'eT<'ēT>-HazZadDîQ<ZadDîQ> W:'eT<'ēT>-HāRāShā`<RāShā`> YiSh:PoTh<ShFTh> Hā'ĕLoHîM<'ĕLoHîM> .Kî<.Kî>-`ēT<`ēT> L:KāL<.KoL>-ChēFeZ<ChēFeZ> W:`aL<`aL> .KāL<.KoL>-HamMa`ăSeH<Ma`ăSeH> ShāM<ShāM>"],
[3018, "'āMaR:.Tî<'MR> 'ăNî<'ăNî> B:LiBî<LēV> `aL<`aL>-.DiV:RaT<.DiV:Râ> B:Nê<BēN> Hā'āDāM<'āDāM> L:VāRāM<BRR> Hā'ĕLoHîM<'ĕLoHîM> W:LiR:'ôT<R'H> Sh:HeM<HēM>-B:HēMâ<B:HēMâ> HēmMâ<HēM> LāHeM<L>"],
[3019, ".Kî<.Kî> MiQ:ReH<MiQ:ReH> V:Nê<BēN>-Hā'āDāM<'āDāM> ûMiQ:ReH<MiQ:ReH> HaB:HēMâ<B:HēMâ> ûMiQ:ReH<MiQ:ReH> 'eChāD<'eChāD> LāHeM<L> .K:MôT<MāWeT> ŹeH<ŹeH> .KēN<.KēN> MôT<MāWeT> ŹeH<ŹeH> W:Rû,aCh<Rû,aCh> 'eChāD<'eChāD> LakKoL<.KoL> ûMôTaR<MôTāR> Hā'āDāM<'āDāM> MiN<MiN>-HaB:HēMâ<B:HēMâ> 'āYiN<'aYiN> .Kî<.Kî> HakKoL<.KoL> HāVeL<HeVeL>"],
[3020, "HakKoL<.KoL> HôLēK:<HLK:> 'eL<'eL>-MāQôM<MāQôM> 'eChāD<'eChāD> HakKoL<.KoL> HāYâ<HYH> MiN<MiN>-He`āFāR<`āFāR> W:HakKoL<.KoL> ShāV<ShWV> 'eL<'eL>-He`āFāR<`āFāR>"],
[3021, "Mî<Mî> YôDē,a`<YD`> Rû,aCh<Rû,aCh> B:Nê<BēN> Hā'āDāM<'āDāM> Hā`oLâ<`LH> Hî'<Hî'> L:Mā`:Lâ<Ma`aL> W:Rû,aCh<Rû,aCh> HaB:HēMâ<B:HēMâ> HayYoReDeT<YRD> Hî'<Hî'> L:MatThâ<MatThâ> Lā'āReZ<'eReZ>"],
[3022, "W:Rā'îTî<R'H> .Kî<.Kî> 'êN<'aYiN> ThôV<ThôV> Mē'ăSheR<'ăSheR> YiS:MaCh<SMCh> Hā'āDāM<'āDāM> B:Ma`ăSâv<Ma`ăSeH> .Kî<.Kî>-Hû'<Hû'> CheL:Qô<ChēLeQ> .Kî<.Kî> Mî<Mî> Y:Vî'enNû<BW'> LiR:'ôT<R'H> B:MeH<Mâ> SheyYiH:YeH<HYH> 'aChăRâv<'aChăRê>"],
[4001, "W:ShaV:.Tî<ShWV> 'ăNî<'ăNî> Wā'eR:'eH<R'H> 'eT<'ēT>-.KāL<.KoL>-Hā`ăShuQîM<`ShQ> 'ăSheR<'ăSheR> Na`ăSîM<`SH> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> W:HinNēH<HinNēH> .DiM:`aT<.DiM:`â> Hā`ăShuQîM<`ShQ> W:'êN<'aYiN> LāHeM<L> M:NaChēM<NChM> ûMiyYaD<YāD> `oSh:QêHeM<`ShQ> .Ko,aCh<.Ko,aCh> W:'êN<'aYiN> LāHeM<L> M:NaChēM<NChM>"],
[4002, "W:ShaBē,aCh<ShVCh> 'ăNî<'ăNî> 'eT<'ēT>-HamMēTîM<MWT> ShekK:VāR<.K:VāR> MēTû<MWT> MiN<MiN>-HaChayYîM<ChaY> 'ăSheR<'ăSheR> HēmMâ<HēM> ChayYîM<ChaY> `ăDeNâ<`ăDeN>"],
[4003, "W:ThôV<ThôV> MisSh:NêHeM<Sh:NaYiM> 'ēT<'ēT> 'ăSheR<'ăSheR>-`ăDeN<`ăDeN> Lo'<Lo'> HāYâ<HYH> 'ăSheR<'ăSheR> Lo'<Lo'>-Rā'â<R'H> 'eT<'ēT>-HamMa`ăSeH<Ma`ăSeH> HāRā`<Ra`> 'ăSheR<'ăSheR> Na`ăSâ<`SH> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[4004, "W:Rā'îTî<R'H> 'ăNî<'ăNî> 'eT<'ēT>-.KāL<.KoL>-`āMāL<`āMāL> W:'ēT<'ēT> .KāL<.KoL>-.KiSh:RôN<.KiSh:RôN> HamMa`ăSeH<Ma`ăSeH> .Kî<.Kî> Hî'<Hî'> QiN:'aT<QiN:'â>-'îSh<'îSh> MēRē`ēHû<Rē,a`> .GaM<.GaM>-ŹeH<ŹeH> HeVeL<HeVeL> ûR:`ûT<R:`ûT> Rû,aCh<Rû,aCh>"],
[4005, "HakK:ŚîL<.K:ŚîL> ChoVēQ<ChVQ> 'eT<'ēT>-YāDâv<YāD> W:'oKēL<'KL> 'eT<'ēT>-B:SāRô<BāSāR>"],
[4006, "ThôV<ThôV> M:Lo'<M:Lo'> KaF<.KaF> NāChaT<NaChaT> MimM:Lo'<M:Lo'> ChāF:NaYiM<ChoFeN> `āMāL<`āMāL> ûR:`ûT<R:`ûT> Rû,aCh<Rû,aCh>"],
[4007, "W:ShaV:.Tî<ShWV> 'ăNî<'ăNî> Wā'eR:'eH<R'H> HeVeL<HeVeL> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[4008, "YēSh<YēSh> 'eChāD<'eChāD> W:'êN<'aYiN> ShēNî<ShēNî> .GaM<.GaM> BēN<BēN> Wā'āCh<'āCh> 'êN<'aYiN>-Lô<L> W:'êN<'aYiN> QēZ<QēZ> L:KāL<.KoL>-`ăMāLô<`āMāL> .GaM<.GaM>-[1 `êNâv<`aYiN> 1] [2 `êNô<`aYiN> 2] Lo'<Lo'>-TiS:Ba`<SV`> `oSheR<`oSheR> ûL:Mî<Mî> 'ăNî<'ăNî> `āMēL<`āMēL> ûM:ChaśŚēR<ChŚR> 'eT<'ēT>-NaF:Shî<NeFeSh> MitThôVâ<ThôV> .GaM<.GaM>-ŹeH<ŹeH> HeVeL<HeVeL> W:`iN:YaN<`iN:YāN> Rā`<Ra`> Hû'<Hû'>"],
[4009, "ThôVîM<ThôV> HasSh:NaYiM<Sh:NaYiM> MiN<MiN>-Hā'eChāD<'eChāD> 'ăSheR<'ăSheR> YēSh<YēSh>-LāHeM<L> SāKāR<SāKāR> ThôV<ThôV> Ba`ăMāLāM<`āMāL>"],
[4010, ".Kî<.Kî> 'iM<'iM>-YiPoLû<NFL> Hā'eChāD<'eChāD> YāQîM<QWM> 'eT<'ēT>-ChăVēRô<ChāVēR> W:'îLô<'î> Hā'eChāD<'eChāD> SheyYiPôL<NFL> W:'êN<'aYiN> ShēNî<ShēNî> LaHăQîMô<QWM>"],
[4011, ".GaM<.GaM> 'iM<'iM>-YiSh:.K:Vû<ShKV> Sh:NaYiM<Sh:NaYiM> W:ChaM<ChMM> LāHeM<L> ûL:'eChāD<'eChāD> 'êK:<'êK:> YēChāM<ChMM>"],
[4012, "W:'iM<'iM>-YiT:Q:Fô<.TQF> Hā'eChāD<'eChāD> HasSh:NaYiM<Sh:NaYiM> Ya`aM:Dû<`MD> NeG:.Dô<NeGeD> W:HaChûTh<ChûTh> HaM:ShulLāSh<ShLSh> Lo'<Lo'> ViM:HēRâ<M:HēRâ> YinNāTēQ<NTQ>"],
[4013, "ThôV<ThôV> YeLeD<YeLeD> MiŚ:.KēN<MiŚ:.KēN> W:ChāKāM<ChāKāM> MimMeLeK:<MeLeK:> ŹāQēN<ŹāQēN> ûK:ŚîL<.K:ŚîL> 'ăSheR<'ăSheR> Lo'<Lo'>-YāDa`<YD`> L:HiźŹāHēR<ŹHR> `ôD<`ôD>"],
[4014, ".Kî<.Kî>-MiBêT<BaYiT> HāŚûRîM<'ŚR> YāZā'<YZ'> LiM:LoK:<MLK:> .Kî<.Kî> .GaM<.GaM> B:MaL:KûTô<MaL:KûT> NôLaD<YLD> RāSh<RWSh>"],
[4015, "Rā'îTî<R'H> 'eT<'ēT>-.KāL<.KoL>-HaChayYîM<ChaY> HaM:HalL:KîM<HLK:> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> `iM<`iM> HayYeLeD<YeLeD> HasShēNî<ShēNî> 'ăSheR<'ăSheR> Ya`ăMoD<`MD> .TaCh:.Tâv<.TaChaT>"],
[4016, "'êN<'aYiN>-QēZ<QēZ> L:KāL<.KoL>-Hā`āM<`aM> L:KoL<.KoL> 'ăSheR<'ăSheR>-HāYâ<HYH> LiF:NêHeM<PāNîM> .GaM<.GaM> Hā'aChăRôNîM<'aChăRôN> Lo'<Lo'> YiS:M:Chû<SMCh>-Vô<B> .Kî<.Kî>-GaM<.GaM>-ŹeH<ŹeH> HeVeL<HeVeL> W:Ra`:YôN<Ra`:YôN> Rû,aCh<Rû,aCh>"],
[4017, "Sh:MoR<ShMR> [1 RaG:LëKā<ReGeL> 1] [2 RaG:L:Kā<ReGeL> 2] .Ka'ăSheR<'ăSheR> .TēLēK:<HLK:> 'eL<'eL>-BêT<BaYiT> Hā'ĕLoHîM<'ĕLoHîM> W:QāRôV<QRV> LiSh:Mo,a`<ShM`> MitTēT<NTN> HakK:ŚîLîM<.K:ŚîL> ŹāVaCh<ŹeVaCh> .Kî<.Kî>-'êNāM<'aYiN> YôD:`îM<YD`> La`ăSôT<`SH> Rā`<Ra`>"],
[5001, "'aL<'aL>-.T:VaHēL<BHL> `aL<`aL>-PîKā<PeH> W:LiB:Kā<LēV> 'aL<'aL>-Y:MaHēR<MHR> L:HôZî'<YZ'> DāVāR<.DāVāR> LiF:Nê<PāNeH> Hā'ĕLoHîM<'ĕLoHîM> .Kî<.Kî> Hā'ĕLoHîM<'ĕLoHîM> BasShāMaYiM<ShāMaYiM> W:'atTâ<'atTâ> `aL<`aL>-Hā'āReZ<'eReZ> `aL<`aL>-.KēN<.KēN> YiH:Yû<HYH> D:VāRëKā<.DāVāR> M:`atThîM<M:`aTh>"],
[5002, ".Kî<.Kî> Bā'<BW'> HaChăLôM<ChăLôM> B:RoV<RoV> `iN:YāN<`iN:YāN> W:QôL<QôL> .K:ŚîL<.K:ŚîL> B:RoV<RoV> .D:VāRîM<.DāVāR>"],
[5003, ".Ka'ăSheR<'ăSheR> .TidDoR<NDR> NeDeR<NeDeR> Lē'LoHîM<'ĕLoHîM> 'aL<'aL>-.T:'aChēR<'ChR> L:ShalL:Mô<ShLM> .Kî<.Kî> 'êN<'aYiN> ChēFeZ<ChēFeZ> BakK:ŚîLîM<.K:ŚîL> 'ēT<'ēT> 'ăSheR<'ăSheR>-.TidDoR<NDR> ShalLēM<ShLM>"],
[5004, "ThôV<ThôV> 'ăSheR<'ăSheR> Lo'<Lo'>-TidDoR<NDR> MisShetTidDôR<NDR> W:Lo'<Lo'> T:ShalLēM<ShLM>"],
[5005, "'aL<'aL>-.TitTēN<NTN> 'eT<'ēT>-PîKā<PeH> LaChăThî'<ChTh'> 'eT<'ēT>-B:SāReKā<BāSāR> W:'aL<'aL>-.To'MaR<'MR> LiF:Nê<PāNeH> HamMaL:'āK:<MaL:'āK:> .Kî<.Kî> Sh:GāGâ<Sh:GāGâ> Hî'<Hî'> LāmMâ<LāmMâ> YiQ:ZoF<QZF> Hā'ĕLoHîM<'ĕLoHîM> `aL<`aL>-QôLeKā<QôL> W:ChiBēL<ChVL> 'eT<'ēT>-Ma`ăSēH<Ma`ăSeH> YāDëKā<YāD>"],
[5006, ".Kî<.Kî> V:RoV<RoV> ChăLoMôT<ChăLôM> WaHăVāLîM<HeVeL> ûD:VāRîM<.DāVāR> HaR:BēH<RVH> .Kî<.Kî> 'eT<'ēT>-Hā'ĕLoHîM<'ĕLoHîM> Y:Rā'<YR'>"],
[5007, "'iM<'iM>-`oSheQ<`oSheQ> RāSh<RWSh> W:GēŹeL<.GāŹēL> MiSh:PāTh<MiSh:PāTh> WāZeDeQ<ZeDeQ> .TiR:'eH<R'H> VamM:DîNâ<M:DîNâ> 'aL<'aL>-.TiT:MahH<.TMH> `aL<`aL>-HaChēFeZ<ChēFeZ> .Kî<.Kî> GāVo,ahH<.GāVo,ahH> Mē`aL<`aL> .GāVo,ahH<.GāVo,ahH> ShoMēR<ShMR> ûG:VoHîM<.GāVo,ahH> `ăLêHeM<`aL>"],
[5008, "W:YiT:RôN<YiT:RôN> 'eReZ<'eReZ> BakKoL<.KoL> [1 Hî'<Hî'> 1] [2 Hû'<Hû'> 2] MeLeK:<MeLeK:> L:SāDeH<SāDeH> Ne`ĕVāD<`VD>"],
[5009, "'oHēV<'HV> .KeŚeF<.KeŚeF> Lo'<Lo'>-YiS:Ba`<SV`> .KeŚeF<.KeŚeF> ûMî<Mî>-'oHēV<'HV> BeHāMôN<HāMôN> Lo'<Lo'> T:Vû'â<.T:Vû'â> .GaM<.GaM>-ŹeH<ŹeH> HāVeL<HeVeL>"],
[5010, "BiR:VôT<RVH> HatThôVâ<ThôV> RaBû<RVV> 'ôK:LëHā<'KL> ûMaH<Mâ>-.KiSh:RôN<.KiSh:RôN> LiV:`āLëHā<Ba`aL> .Kî<.Kî> 'iM<'iM>-[1 R:'iyYaT<R:'îT> 1] [2 R:'ûT<R:'ûT> 2] `êNâv<`aYiN>"],
[5011, "M:TûQâ<MāTôQ> Sh:NaT<ShēNâ> Hā`oVēD<`VD> 'iM<'iM>-M:`aTh<M:`aTh> W:'iM<'iM>-HaR:BēH<RVH> Yo'KēL<'KL> W:HasSāVā`<SāVā`> Le`āShîR<`āShîR> 'êNenNû<'aYiN> ManNî,aCh<NWCh> Lô<L> LîShôN<YShN>"],
[5012, "YēSh<YēSh> Rā`â<Rā`â> ChôLâ<ChLH> Rā'îTî<R'H> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> `oSheR<`oSheR> ShāMûR<ShMR> LiV:`āLâv<Ba`aL> L:Rā`āTô<Rā`â>"],
[5013, "W:'āVaD<'VD> Hā`oSheR<`oSheR> HaHû'<Hû'> B:`iN:YaN<`iN:YāN> Rā`<Ra`> W:HôLîD<YLD> BēN<BēN> W:'êN<'aYiN> B:YāDô<YāD> M:'ûMâ<M:'ûMâ>"],
[5014, ".Ka'ăSheR<'ăSheR> YāZā'<YZ'> MiBeTheN<BeTheN> 'imMô<'ēM> `āRôM<`āRôM> YāShûV<ShWV> LāLeKeT<HLK:> .K:SheBā'<BW'> ûM:'ûMâ<M:'ûMâ> Lo'<Lo'>-YisSā'<NS'> Va`ăMāLô<`āMāL> SheyYoLēK:<HLK:> B:YāDô<YāD>"],
[5015, "W:GaM<.GaM>-ŹoH<ŹoH> Rā`â<Rā`â> ChôLâ<ChLH> .KāL<.KoL>-`umMaT<L:`umMaT> SheBā'<BW'> .KēN<.KēN> YēLēK:<HLK:> ûMaH<Mâ>-yYiT:RôN<YiT:RôN> Lô<L> SheyYa`ăMoL<`ML> LāRû,aCh<Rû,aCh>"],
[5016, ".GaM<.GaM> .KāL<.KoL>-YāMâv<YôM> BaChoSheK:<ChoSheK:> Yo'KēL<'KL> W:Kā`aŚ<.K`Ś> HaR:BēH<RVH> W:ChāL:Yô<ChŏLî> WāQāZeF<QeZeF>"],
[5017, "HinNēH<HinNēH> 'ăSheR<'ăSheR>-Rā'îTî<R'H> 'āNî<'ăNî> ThôV<ThôV> 'ăSheR<'ăSheR>-YāFeH<YāFeH> Le'eKôL<'KL>-W:LiSh:.TôT<ShTH> W:LiR:'ôT<R'H> ThôVâ<ThôV> B:KāL<.KoL>-`ăMāLô<`āMāL> SheyYa`ăMoL<`ML> .TaChaT<.TaChaT>-HasSheMeSh<SheMeSh> MiŚ:PaR<MiŚ:PāR> Y:Mê<YôM>-[1 ChayYāW<ChayYîM> 1] [2 ChayYâv<ChayYîM> 2] 'ăSheR<'ăSheR>-NāTaN<NTN>-Lô<L> Hā'ĕLoHîM<'ĕLoHîM> .Kî<.Kî>-Hû'<Hû'> CheL:Qô<ChēLeQ>"],
[5018, ".GaM<.GaM> .KāL<.KoL>-Hā'āDāM<'āDāM> 'ăSheR<'ăSheR> NāTaN<NTN>-Lô<L> Hā'ĕLoHîM<'ĕLoHîM> `oSheR<`oSheR> ûN:KāŚîM<NeKeŚ> W:HiSh:LîThô<ShLTh> Le'ĕKoL<'KL> MimMenNû<MiN> W:LāSē'T<NS'> 'eT<'ēT>-CheL:Qô<ChēLeQ> W:LiS:Mo,aCh<SMCh> Ba`ăMāLô<`āMāL> ŹoH<ŹoH> MatTaT<MatTāT> 'ĕLoHîM<'ĕLoHîM> Hî'<Hî'>"],
[5019, ".Kî<.Kî> Lo'<Lo'> HaR:BēH<RVH> YiŹ:.KoR<ŹKR> 'eT<'ēT>-Y:Mê<YôM> ChayYâv<ChayYîM> .Kî<.Kî> Hā'ĕLoHîM<'ĕLoHîM> Ma`ăNeH<`NH> B:SiM:ChaT<SiM:Châ> LiBô<LēV>"],
[6001, "YēSh<YēSh> Rā`â<Rā`â> 'ăSheR<'ăSheR> Rā'îTî<R'H> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> W:RaBâ<RaBâ> Hî'<Hî'> `aL<`aL>-Hā'āDāM<'āDāM>"],
[6002, "'îSh<'îSh> 'ăSheR<'ăSheR> YitTeN<NTN>-Lô<L> Hā'ĕLoHîM<'ĕLoHîM> `oSheR<`oSheR> ûN:KāŚîM<NeKeŚ> W:KāVôD<.KāVôD> W:'êNenNû<'aYiN> ChāŚēR<ChāŚēR> L:NaF:Shô<NeFeSh> MikKoL<.KoL> 'ăSheR<'ăSheR>-YiT:'aûeH<'WH> W:Lo'<Lo'>-YaSh:LîThenNû<ShLTh> Hā'ĕLoHîM<'ĕLoHîM> Le'ĕKoL<'KL> MimMenNû<MiN> .Kî<.Kî> 'îSh<'îSh> NāK:Rî<NāK:Rî> Yo'KăLenNû<'KL> ŹeH<ŹeH> HeVeL<HeVeL> WāChŏLî<ChŏLî> Rā`<Ra`> Hû'<Hû'>"],
[6003, "'iM<'iM>-YôLîD<YLD> 'îSh<'îSh> Mē'â<Mē'â> W:ShāNîM<ShāNâ> RaBôT<RaV> YiCh:YeH<ChYH> W:RaV<RaV> SheyYiH:Yû<HYH> Y:Mê<YôM>-ShāNâv<ShāNâ> W:NaF:Shô<NeFeSh> Lo'<Lo'>-TiS:Ba`<SV`> MiN<MiN>-HatThôVâ<ThôV> W:GaM<.GaM>-Q:VûRâ<Q:VûRâ> Lo'<Lo'>-HāY:Tâ<HYH> lLô<L> 'āMaR:.Tî<'MR> ThôV<ThôV> MimMenNû<MiN> HanNāFeL<NēFeL>"],
[6004, ".Kî<.Kî>-VaHeVeL<HeVeL> Bā'<BW'> ûVaChoSheK:<ChoSheK:> YēLēK:<HLK:> ûVaChoSheK:<ChoSheK:> Sh:Mô<ShēM> Y:KuśŚeH<.KŚH>"],
[6005, ".GaM<.GaM>-SheMeSh<SheMeSh> Lo'<Lo'>-Rā'â<R'H> W:Lo'<Lo'> YāDā`<YD`> NaChaT<NaChaT> LāŹeH<ŹeH> MiźŹeH<ŹeH>"],
[6006, "W:'ilLû<'ilLû> ChāYâ<ChYH> 'eLeF<'eLeF> ShāNîM<ShāNâ> Pa`ăMaYiM<Pa`aM> W:ThôVâ<ThôV> Lo'<Lo'> Rā'â<R'H> HăLo'<Lo'> 'eL<'eL>-MāQôM<MāQôM> 'eChāD<'eChāD> HakKoL<.KoL> HôLēK:<HLK:>"],
[6007, ".KāL<.KoL>-`ăMaL<`āMāL> Hā'āDāM<'āDāM> L:FîHû<PeH> W:GaM<.GaM>-HanNeFeSh<NeFeSh> Lo'<Lo'> TimMāLē'<ML'>"],
[6008, ".Kî<.Kî> MaH<Mâ>-yYôTēR<YôTēR> LeChāKāM<ChāKāM> MiN<MiN>-HakK:ŚîL<.K:ŚîL> MaH<Mâ>-lLe`āNî<`āNî> YôDē,a`<YD`> LaHăLoK:<HLK:> NeGeD<NeGeD> HaChayYîM<ChaY>"],
[6009, "ThôV<ThôV> MaR:'ēH<MaR:'eH> `êNaYiM<`aYiN> MēHăLāK:<HLK:>-NāFeSh<NeFeSh> .GaM<.GaM>-ŹeH<ŹeH> HeVeL<HeVeL> ûR:`ûT<R:`ûT> Rû,aCh<Rû,aCh>"],
[6010, "MaH<Mâ>-sSheHāYâ<HYH> .K:VāR<.K:VāR> NiQ:Rā'<QR'> Sh:Mô<ShēM> W:NôDā`<YD`> 'ăSheR<'ăSheR>-Hû'<Hû'> 'āDāM<'āDāM> W:Lo'<Lo'>-YûKaL<YKL> LāDîN<.DYN> `iM<`iM> [1 SheHaT:QîF<.TQF> 1] [2 ShetTaqQîF<.TaqQîF> 2] MimMenNû<MiN>"],
[6011, ".Kî<.Kî> YēSh<YēSh>-.D:VāRîM<.DāVāR> HaR:BēH<RVH> MaR:BîM<RVH> HāVeL<HeVeL> MaH<Mâ>-yYoTēR<YôTēR> Lā'āDāM<'āDāM>"],
[6012, ".Kî<.Kî> Mî<Mî>-YôDē,a`<YD`> MaH<Mâ>-.ThôV<ThôV> Lā'āDāM<'āDāM> BaChayYîM<ChayYîM> MiŚ:PaR<MiŚ:PāR> Y:Mê<YôM>-ChayYê<ChayYîM> HeV:Lô<HeVeL> W:Ya`ăSēM<`SH> .KazZēL<ZēL> 'ăSheR<'ăSheR> Mî<Mî>-YagGîD<NGD> Lā'āDāM<'āDāM> MaH<Mâ>-yYiH:YeH<HYH> 'aChăRâv<'aChăRê> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[7001, "ThôV<ThôV> ShēM<ShēM> MisSheMeN<SheMeN> ThôV<ThôV> W:YôM<YôM> HamMāWeT<MāWeT> MiyYôM<YôM> HiûāL:Dô<YLD>"],
[7002, "ThôV<ThôV> LāLeKeT<HLK:> 'eL<'eL>-BêT<BaYiT>-'ēVeL<'ēVeL> MilLeKeT<HLK:> 'eL<'eL>-BêT<BaYiT> MiSh:.TeH<MiSh:.TeH> Ba'ăSheR<'ăSheR> Hû'<Hû'> ŚôF<ŚôF> .KāL<.KoL>-Hā'āDāM<'āDāM> W:HaChaY<ChaY> YitTēN<NTN> 'eL<'eL>-LiBô<LēV>"],
[7003, "ThôV<ThôV> .Ka`aŚ<.Ka`aŚ> MisS:ChoQ<S:ChôQ> .Kî<.Kî>-V:Ro,a`<Ro,a`> PāNîM<PāNîM> YîThaV<YThV> LēV<LēV>"],
[7004, "LēV<LēV> ChăKāMîM<ChāKāM> B:VêT<BaYiT> 'ēVeL<'ēVeL> W:LēV<LēV> .K:ŚîLîM<.K:ŚîL> B:VêT<BaYiT> SiM:Châ<SiM:Châ>"],
[7005, "ThôV<ThôV> LiSh:Mo,a`<ShM`> .Ga`ăRaT<.G:`āRâ> ChāKāM<ChāKāM> Mē'îSh<'îSh> ShoMē,a`<ShM`> ShîR<ShîR> .K:ŚîLîM<.K:ŚîL>"],
[7006, ".Kî<.Kî> K:QôL<QôL> HaśŚîRîM<ŚîR> .TaChaT<.TaChaT> HaśŚîR<ŚîR> .KēN<.KēN> S:ChoQ<S:ChôQ> HakK:ŚîL<.K:ŚîL> W:GaM<.GaM>-ŹeH<ŹeH> HāVeL<HeVeL>"],
[7007, ".Kî<.Kî> Hā`oSheQ<`oSheQ> Y:HôLēL<HLL> ChāKāM<ChāKāM> Wî'aBēD<'VD> 'eT<'ēT>-LēV<LēV> MatTāNâ<MatTāNâ>"],
[7008, "ThôV<ThôV> 'aChăRîT<'aChăRîT> .DāVāR<.DāVāR> MēRē'ShîTô<Rē'ShîT> ThôV<ThôV> 'eReK:<'āRēK:>-Rû,aCh<Rû,aCh> MigG:VahH<.GāVo,ahH>-Rû,aCh<Rû,aCh>"],
[7009, "'aL<'aL>-.T:VaHēL<BHL> B:RûChăKā<Rû,aCh> LiK:`ôŚ<.K`Ś> .Kî<.Kî> Ka`aŚ<.Ka`aŚ> B:ChêQ<ChêQ> .K:ŚîLîM<.K:ŚîL> YāNû,aCh<NWCh>"],
[7010, "'aL<'aL>-.To'MaR<'MR> MeH<Mâ> HāYâ<HYH> SheHayYāMîM<YôM> HāRi'ShoNîM<Ri'ShôN> HāYû<HYH> ThôVîM<ThôV> Mē'ēlLeH<'ēlLeH> .Kî<.Kî> Lo'<Lo'> MēChāK:Mâ<ChāK:Mâ> Shā'aL:.Tā<Sh'L> `aL<`aL>-ŹeH<ŹeH>"],
[7011, "ThôVâ<ThôV> ChāK:Mâ<ChāK:Mâ> `iM<`iM>-NaChăLâ<NaChăLâ> W:YoTēR<YôTēR> L:Ro'ê<R'H> HasShāMeSh<SheMeSh>"],
[7012, ".Kî<.Kî> B:ZēL<ZēL> HaChāK:Mâ<ChāK:Mâ> B:ZēL<ZēL> HakKāŚeF<.KeŚeF> W:YiT:RôN<YiT:RôN> .Da`aT<.Da`aT> HaChāK:Mâ<ChāK:Mâ> .T:ChayYeH<ChYH> V:`āLëHā<Ba`aL>"],
[7013, "R:'ēH<R'H> 'eT<'ēT>-Ma`ăSēH<Ma`ăSeH> Hā'ĕLoHîM<'ĕLoHîM> .Kî<.Kî> Mî<Mî> YûKaL<YKL> L:TaqQēN<.TQN> 'ēT<'ēT> 'ăSheR<'ăSheR> `iû:Tô<`WT>"],
[7014, "B:YôM<YôM> ThôVâ<ThôV> HĕYēH<HYH> V:ThôV<ThôV> ûV:YôM<YôM> Rā`â<Rā`â> R:'ēH<R'H> .GaM<.GaM> 'eT<'ēT>-ŹeH<ŹeH> L:`umMaT<L:`umMaT>-ŹeH<ŹeH> `āSâ<`SH> Hā'ĕLoHîM<'ĕLoHîM> `aL<`aL>-.DiV:RaT<.DiV:Râ> ShelLo'<Lo'> YiM:Zā'<MZ'> Hā'āDāM<'āDāM> 'aChăRâv<'aChăRê> M:'ûMâ<M:'ûMâ>"],
[7015, "'eT<'ēT>-HakKoL<.KoL> Rā'îTî<R'H> BîMê<YôM> HeV:Lî<HeVeL> YēSh<YēSh> ZadDîQ<ZadDîQ> 'oVēD<'VD> B:ZiD:Qô<ZeDeQ> W:YēSh<YēSh> RāShā`<RāShā`> Ma'ăRîK:<'RK:> B:Rā`āTô<Rā`â>"],
[7016, "'aL<'aL>-.T:Hî<HYH> ZadDîQ<ZadDîQ> HaR:BēH<RVH> W:'aL<'aL>-.TiT:ChakKaM<ChKM> YôTēR<YôTēR> LāmMâ<LāmMâ> .TisShôMēM<ShMM>"],
[7017, "'aL<'aL>-.TiR:Sha`<RSh`> HaR:BēH<RVH> W:'aL<'aL>-.T:Hî<HYH> ŚāKāL<ŚāKāL> LāmMâ<LāmMâ> TāMûT<MWT> B:Lo'<Lo'> `itTeKā<`ēT>"],
[7018, "ThôV<ThôV> 'ăSheR<'ăSheR> .Te'ĕChoŹ<'ChŹ> BāŹeH<ŹeH> W:GaM<.GaM>-MiźŹeH<ŹeH> 'aL<'aL>-.TanNaCh<NWCh> 'eT<'ēT>-YāDeKā<YāD> .Kî<.Kî>-Y:Rē'<YR'> 'ĕLoHîM<'ĕLoHîM> YēZē'<YZ'> 'eT<'ēT>-.KulLāM<.KoL>"],
[7019, "HaChāK:Mâ<ChāK:Mâ> .Tā`oŹ<`ŹŹ> LeChāKāM<ChāKāM> Mē`ăSāRâ<`ăSāRâ> ShalLîThîM<ShalLîTh> 'ăSheR<'ăSheR> HāYû<HYH> Bā`îR<`îR>"],
[7020, ".Kî<.Kî> 'āDāM<'āDāM> 'êN<'aYiN> ZadDîQ<ZadDîQ> Bā'āReZ<'eReZ> 'ăSheR<'ăSheR> Ya`ăSeH<`SH>-.ThôV<ThôV> W:Lo'<Lo'> YeChĕThā'<ChTh'>"],
[7021, ".GaM<.GaM> L:KāL<.KoL>-HadD:VāRîM<.DāVāR> 'ăSheR<'ăSheR> Y:DaBēRû<.DVR> 'aL<'aL>-.TitTēN<NTN> LiBeKā<LēV> 'ăSheR<'ăSheR> Lo'<Lo'>-TiSh:Ma`<ShM`> 'eT<'ēT>-`aV:.D:Kā<`eVeD> M:QaL:LeKā<QLL>"],
[7022, ".Kî<.Kî> .GaM<.GaM>-P:`āMîM<Pa`aM> RaBôT<RaV> YāDa`<YD`> LiBeKā<LēV> 'ăSheR<'ăSheR> .GaM<.GaM>-[1 'atT:<'atTâ> 1] [2 'atTâ<'atTâ> 2] QilLaL:.Tā<QLL> 'ăChēRîM<'aChēR>"],
[7023, ".KāL<.KoL>-ŹoH<ŹoH> NiśŚîTî<NŚH> VaChāK:Mâ<ChāK:Mâ> 'āMaR:.Tî<'MR> 'eCh:.KāMâ<ChKM> W:Hî'<Hî'> R:ChôQâ<RāChôQ> MimMenNî<MiN>"],
[7024, "RāChôQ<RāChôQ> MaH<Mâ>-sSheHāYâ<HYH> W:`āMoQ<`āMoQ> `āMoQ<`āMoQ> Mî<Mî> YiM:Zā'enNû<MZ'>"],
[7025, "ŚaBôTî<ŚVV> 'ăNî<'ăNî> W:LiBî<LēV> LāDa`aT<YD`> W:LāTûR<.TWR> ûVaqQēSh<BQSh> ChāK:Mâ<ChāK:Mâ> W:CheSh:BôN<CheSh:BôN> W:LāDa`aT<YD`> ReSha`<ReSha`> .KeŚeL<.KeŚeL> W:HaśŚiK:LûT<ŚiK:LûT> HôLēLôT<HôLēLôT>"],
[7026, "ûMôZe'<MZ'> 'ăNî<'ăNî> MaR<MaR> MimMāWeT<MāWeT> 'eT<'ēT>-Hā'isShâ<'isShâ> 'ăSheR<'ăSheR>-Hî'<Hî'> M:ZôDîM<MāZôD> WaChăRāMîM<ChēReM> LiBāhH<LēV> 'ăŚûRîM<'ēŚûR> YāDëHā<YāD> ThôV<ThWV> LiF:Nê<PāNeH> Hā'ĕLoHîM<'ĕLoHîM> YimMāLēTh<MLTh> MimMenNâ<MiN> W:ChôThē'<ChTh'> YilLāKeD<LKD> BāhH<B>"],
[7027, "R:'ēH<R'H> ŹeH<ŹeH> MāZā'Tî<MZ'> 'āM:Râ<'MR> QoHeLeT<QoHeLeT> 'aChaT<'aChaT> L:'aChaT<'aChaT> LiM:Zo'<MZ'> CheSh:BôN<CheSh:BôN>"],
[7028, "'ăSheR<'ăSheR> `ôD<`ôD>-BiQ:Shâ<BQSh> NaF:Shî<NeFeSh> W:Lo'<Lo'> MāZā'Tî<MZ'> 'āDāM<'āDāM> 'eChāD<'eChāD> Mē'eLeF<'eLeF> MāZā'Tî<MZ'> W:'isShâ<'isShâ> V:KāL<.KoL>-'ēlLeH<'ēlLeH> Lo'<Lo'> MāZā'Tî<MZ'>"],
[7029, "L:VaD<BaD> R:'ēH<R'H>-ŹeH<ŹeH> MāZā'Tî<MZ'> 'ăSheR<'ăSheR> `āSâ<`SH> Hā'ĕLoHîM<'ĕLoHîM> 'eT<'ēT>-Hā'āDāM<'āDāM> YāShāR<YāShāR> W:HēmMâ<HēM> ViQ:Shû<BQSh> ChisSh:VoNôT<ChisShāVôN> RaBîM<RaV>"],
[8001, "Mî<Mî> .K:HeChāKāM<ChāKāM> ûMî<Mî> YôDē,a`<YD`> PēSheR<PēSheR> .DāVāR<.DāVāR> ChāK:MaT<ChāK:Mâ> 'āDāM<'āDāM> .Tā'îR<'WR> PāNâv<PāNeH> W:`oŹ<`oŹ> PāNâv<PāNeH> Y:ShunNe'<ShNH>"],
[8002, "'ăNî<'ăNî> Pî<PeH>-MeLeK:<MeLeK:> Sh:MôR<ShMR> W:`aL<`aL> .DiV:RaT<.DiV:Râ> Sh:Vû`aT<Sh:Vû`â> 'ĕLoHîM<'ĕLoHîM>"],
[8003, "'aL<'aL>-.TiBāHēL<BHL> MiPāNâv<PāNeH> .TēLēK:<HLK:> 'aL<'aL>-.Ta`ăMoD<`MD> B:DāVāR<.DāVāR> Rā`<Ra`> .Kî<.Kî> .KāL<.KoL>-'ăSheR<'ăSheR> YaCh:PoZ<ChFZ> Ya`ăSeH<`SH>"],
[8004, "Ba'ăSheR<'ăSheR> .D:VaR<.DāVāR>-MeLeK:<MeLeK:> ShiL:ThôN<ShiL:ThôN> ûMî<Mî> Yo'MaR<'MR>-Lô<L> MaH<Mâ>-.Ta`ăSeH<`SH>"],
[8005, "ShôMēR<ShMR> MiZ:Wâ<MiZ:Wâ> Lo'<Lo'> YēDa`<YD`> .DāVāR<.DāVāR> Rā`<Ra`> W:`ēT<`ēT> ûMiSh:PāTh<MiSh:PāTh> YēDa`<YD`> LēV<LēV> ChāKāM<ChāKāM>"],
[8006, ".Kî<.Kî> L:KāL<.KoL>-ChēFeZ<ChēFeZ> YēSh<YēSh> `ēT<`ēT> ûMiSh:PāTh<MiSh:PāTh> .Kî<.Kî>-Rā`aT<Rā`â> Hā'āDāM<'āDāM> RaBâ<RaBâ> `āLâv<`aL>"],
[8007, ".Kî<.Kî>-'êNenNû<'aYiN> YoDē,a`<YD`> MaH<Mâ>-sSheyYiH:YeH<HYH> .Kî<.Kî> .Ka'ăSheR<'ăSheR> YiH:YeH<HYH> Mî<Mî> YagGîD<NGD> Lô<L>"],
[8008, "'êN<'aYiN> 'āDāM<'āDāM> ShalLîTh<ShalLîTh> BāRû,aCh<Rû,aCh> LiK:Lô'<.KL'> 'eT<'ēT>-HāRû,aCh<Rû,aCh> W:'êN<'aYiN> ShiL:ThôN<ShiL:ThôN> B:YôM<YôM> HamMāWeT<MāWeT> W:'êN<'aYiN> MiSh:LaChaT<MiSh:LaChaT> BamMiL:ChāMâ<MiL:ChāMâ> W:Lo'<Lo'>-Y:MalLēTh<MLTh> ReSha`<ReSha`> 'eT<'ēT>-B:`āLâv<Ba`aL>"],
[8009, "'eT<'ēT>-.KāL<.KoL>-ŹeH<ŹeH> Rā'îTî<R'H> W:NāTôN<NTN> 'eT<'ēT>-LiBî<LēV> L:KāL<.KoL>-Ma`ăSeH<Ma`ăSeH> 'ăSheR<'ăSheR> Na`ăSâ<`SH> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> `ēT<`ēT> 'ăSheR<'ăSheR> ShāLaTh<ShLTh> Hā'āDāM<'āDāM> B:'āDāM<'āDāM> L:Ra`<Ra`> Lô<L>"],
[8010, "ûV:KēN<.KēN> Rā'îTî<R'H> R:Shā`îM<RāShā`> Q:VuRîM<QVR> WāVā'û<BW'> ûMimM:QôM<MāQôM> QāDôSh<QāDôSh> Y:HalLēKû<HLK:> W:YiSh:.TakK:Chû<ShKCh> Vā`îR<`îR> 'ăSheR<'ăSheR> .KēN<.KēN>-`āSû<`SH> .GaM<.GaM>-ŹeH<ŹeH> HāVeL<HeVeL>"],
[8011, "'ăSheR<'ăSheR> 'êN<'aYiN>-Na`ăSâ<`SH> FiT:GāM<PiT:GāM> Ma`ăSēH<Ma`ăSeH> HāRā`â<Rā`â> M:HēRâ<M:HēRâ> `aL<`aL>-.KēN<.KēN> MāLē'<ML'> LēV<LēV> B:Nê<BēN>-Hā'āDāM<'āDāM> BāHeM<B> La`ăSôT<`SH> Rā`<Ra`>"],
[8012, "'ăSheR<'ăSheR> ChoThe'<ChTh'> `oSeH<`SH> Rā`<Ra`> M:'aT<Mē'â> ûMa'ăRîK:<'RK:> Lô<L> .Kî<.Kî> .GaM<.GaM>-YôDē,a`<YD`> 'āNî<'ăNî> 'ăSheR<'ăSheR> YiH:YeH<HYH>-.ThôV<ThôV> L:YiR:'ê<YR'> Hā'ĕLoHîM<'ĕLoHîM> 'ăSheR<'ăSheR> YîR:'û<YR'> MilL:FāNâv<PāNeH>"],
[8013, "W:ThôV<ThôV> Lo'<Lo'>-YiH:YeH<HYH> LāRāShā`<RāShā`> W:Lo'<Lo'>-Ya'ăRîK:<'RK:> YāMîM<YôM> .KazZēL<ZēL> 'ăSheR<'ăSheR> 'êNenNû<'aYiN> YāRē'<YR'> MilLiF:Nê<PāNeH> 'ĕLoHîM<'ĕLoHîM>"],
[8014, "YeSh<YēSh>-HeVeL<HeVeL> 'ăSheR<'ăSheR> Na`ăSâ<`SH> `aL<`aL>-Hā'āReZ<'eReZ> 'ăSheR<'ăSheR> YēSh<YēSh> ZadDîQîM<ZadDîQ> 'ăSheR<'ăSheR> MagGî,a`<NG`> 'ăLēHeM<'eL> .K:Ma`ăSēH<Ma`ăSeH> HāR:Shā`îM<RāShā`> W:YēSh<YēSh> R:Shā`îM<RāShā`> ShemMagGî,a`<NG`> 'ăLēHeM<'eL> .K:Ma`ăSēH<Ma`ăSeH> HazZadDîQîM<ZadDîQ> 'āMaR:.Tî<'MR> ShegGaM<.GaM>-ŹeH<ŹeH> HāVeL<HeVeL>"],
[8015, "W:ShiBaCh:.Tî<ShVCh> 'ăNî<'ăNî> 'eT<'ēT>-HasSiM:Châ<SiM:Châ> 'ăSheR<'ăSheR> 'êN<'aYiN>-ThôV<ThôV> Lā'āDāM<'āDāM> .TaChaT<.TaChaT> HasSheMeSh<SheMeSh> .Kî<.Kî> 'iM<'iM>-Le'ĕKôL<'KL> W:LiSh:.TôT<ShTH> W:LiS:Mô,aCh<SMCh> W:Hû'<Hû'> YiL:WenNû<LWH> Va`ăMāLô<`āMāL> Y:Mê<YôM> ChayYâv<ChayYîM> 'ăSheR<'ăSheR>-NāTaN<NTN>-Lô<L> Hā'ĕLoHîM<'ĕLoHîM> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[8016, ".Ka'ăSheR<'ăSheR> NāTatTî<NTN> 'eT<'ēT>-LiBî<LēV> LāDa`aT<YD`> ChāK:Mâ<ChāK:Mâ> W:LiR:'ôT<R'H> 'eT<'ēT>-Hā`iN:YāN<`iN:YāN> 'ăSheR<'ăSheR> Na`ăSâ<`SH> `aL<`aL>-Hā'āReZ<'eReZ> .Kî<.Kî> GaM<.GaM> BayYôM<YôM> ûValLaY:Lâ<LaY:Lâ> ShēNâ<ShēNâ> B:`êNâv<`aYiN> 'êNenNû<'aYiN> Ro'eH<R'H>"],
[8017, "W:Rā'îTî<R'H> 'eT<'ēT>-.KāL<.KoL>-Ma`ăSēH<Ma`ăSeH> Hā'ĕLoHîM<'ĕLoHîM> .Kî<.Kî> Lo'<Lo'> YûKaL<YKL> Hā'āDāM<'āDāM> LiM:Zô'<MZ'> 'eT<'ēT>-HamMa`ăSeH<Ma`ăSeH> 'ăSheR<'ăSheR> Na`ăSâ<`SH> TaChaT<.TaChaT>-HasSheMeSh<SheMeSh> B:SheL<B> 'ăSheR<'ăSheR> Ya`ăMoL<`ML> Hā'āDāM<'āDāM> L:VaqQēSh<BQSh> W:Lo'<Lo'> YiM:Zā'<MZ'> W:GaM<.GaM> 'iM<'iM>-Yo'MaR<'MR> HeChāKāM<ChāKāM> LāDa`aT<YD`> Lo'<Lo'> YûKaL<YKL> LiM:Zo'<MZ'>"],
[9001, ".Kî<.Kî> 'eT<'ēT>-.KāL<.KoL>-ŹeH<ŹeH> NāTatTî<NTN> 'eL<'eL>-LiBî<LēV> W:LāVûR<BWR> 'eT<'ēT>-.KāL<.KoL>-ŹeH<ŹeH> 'ăSheR<'ăSheR> HazZadDîQîM<ZadDîQ> W:HaChăKāMîM<ChāKāM> Wa`ăVāDêHeM<`ăVāD> B:YaD<YāD> Hā'ĕLoHîM<'ĕLoHîM> .GaM<.GaM>-'aHăVâ<'aHăVâ> GaM<.GaM>-SiN:'â<SiN:'â> 'êN<'aYiN> YôDē,a`<YD`> Hā'āDāM<'āDāM> HakKoL<.KoL> LiF:NêHeM<PāNîM>"],
[9002, "HakKoL<.KoL> .Ka'ăSheR<'ăSheR> LakKoL<.KoL> MiQ:ReH<MiQ:ReH> 'eChāD<'eChāD> LazZadDîQ<ZadDîQ> W:LāRāShā`<RāShā`> LatThôV<ThôV> W:LatThâôR<ThâôR> W:LatThāMē'<ThāMē'> W:LaźŹoVē,aCh<ŹVCh> W:La'ăSheR<'ăSheR> 'êNenNû<'aYiN> ŹoVē,aCh<ŹVCh> .KatThôV<ThôV> .KaChoThe'<ChTh'> HanNiSh:Bā`<ShV`> .Ka'ăSheR<'ăSheR> Sh:Vû`â<Sh:Vû`â> YāRē'<YR'>"],
[9003, "ŹeH<ŹeH> Rā`<Ra`> B:KoL<.KoL> 'ăSheR<'ăSheR>-Na`ăSâ<`SH> .TaChaT<.TaChaT> HasSheMeSh<SheMeSh> .Kî<.Kî>-MiQ:ReH<MiQ:ReH> 'eChāD<'eChāD> LakKoL<.KoL> W:GaM<.GaM> LēV<LēV> B:Nê<BēN>-Hā'āDāM<'āDāM> MāLē'<ML'>-Rā`<Ra`> W:HôLēLôT<HôLēLôT> BiL:VāVāM<LēVāV> B:ChayYêHeM<ChayYîM> W:'aChăRâv<'aChăRê> 'eL<'eL>-HamMēTîM<MWT>"],
[9004, ".Kî<.Kî>-Mî<Mî> 'ăSheR<'ăSheR> [1 YiBāChēR<BChR> 1] [2 Y:ChuBaR<ChVR> 2] 'eL<'eL> .KāL<.KoL>-HaChayYîM<ChaY> YēSh<YēSh> BitThāChôN<BitThāChôN> .Kî<.Kî>-L:KeLeV<.KeLeV> ChaY<ChaY> Hû'<Hû'> ThôV<ThôV> MiN<MiN>-Hā'aR:YēH<'aR:YēH> HamMēT<MWT>"],
[9005, ".Kî<.Kî> HaChayYîM<ChaY> YôD:`îM<YD`> SheyYāMuTû<MWT> W:HamMēTîM<MWT> 'êNāM<'aYiN> YôD:`îM<YD`> M:'ûMâ<M:'ûMâ> W:'êN<'aYiN>-`ôD<`ôD> LāHeM<L> SāKāR<SāKāR> .Kî<.Kî> NiSh:.KaCh<ShKCh> ŹiK:RāM<ŹēKeR>"],
[9006, ".GaM<.GaM> 'aHăVāTāM<'aHăVâ> .GaM<.GaM>-SiN:'āTāM<SiN:'â> .GaM<.GaM>-QiN:'āTāM<QiN:'â> .K:VāR<.K:VāR> 'āVāDâ<'VD> W:ChēLeQ<ChēLeQ> 'êN<'aYiN>-LāHeM<L> `ôD<`ôD> L:`ôLāM<`ôLāM> B:KoL<.KoL> 'ăSheR<'ăSheR>-Na`ăSâ<`SH> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[9007, "LēK:<HLK:> 'ĕKoL<'KL> B:SiM:Châ<SiM:Châ> LaCh:MeKā<LeCheM> ûShăTēH<ShTH> V:LeV<LēV>-ThôV<ThôV> YêNeKā<YaYiN> .Kî<.Kî> K:VāR<.K:VāR> RāZâ<RZH> Hā'ĕLoHîM<'ĕLoHîM> 'eT<'ēT>-Ma`ăSëKā<Ma`ăSeH>"],
[9008, "B:KāL<.KoL>-`ēT<`ēT> YiH:Yû<HYH> V:GāDëKā<BeGeD> L:VāNîM<LāVāN> W:SheMeN<SheMeN> `aL<`aL>-Ro'Sh:Kā<Ro'Sh> 'aL<'aL>-YeCh:ŚāR<ChŚR>"],
[9009, "R:'ēH<R'H> ChayYîM<ChayYîM> `iM<`iM>-'isShâ<'isShâ> 'ăSheR<'ăSheR>-'āHaV:.Tā<'HV> .KāL<.KoL>-Y:Mê<YôM> ChayYê<ChayYîM> HeV:LeKā<HeVeL> 'ăSheR<'ăSheR> NāTaN<NTN>-L:Kā<L> .TaChaT<.TaChaT> HasSheMeSh<SheMeSh> .KoL<.KoL> Y:Mê<YôM> HeV:LeKā<HeVeL> .Kî<.Kî> Hû'<Hû'> CheL:Q:Kā<ChēLeQ> BaChayYîM<ChayYîM> ûVa`ăMāL:Kā<`āMāL> 'ăSheR<'ăSheR>-'atTâ<'atTâ> `āMēL<`āMēL> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh>"],
[9010, ".KoL<.KoL> 'ăSheR<'ăSheR> .TiM:Zā'<MZ'> YāD:Kā<YāD> La`ăSôT<`SH> B:KoChăKā<.Ko,aCh> `ăSēH<`SH> .Kî<.Kî> 'êN<'aYiN> Ma`ăSeH<Ma`ăSeH> W:CheSh:BôN<CheSh:BôN> W:Da`aT<.Da`aT> W:ChāK:Mâ<ChāK:Mâ> BiSh:'ôL<Sh:'ôL> 'ăSheR<'ăSheR> 'atTâ<'atTâ> HoLēK:<HLK:> ShāmMâ<ShāM> Ś<Ś>"],
[9011, "ShaV:.Tî<ShWV> W:Rā'oH<R'H> TaChaT<.TaChaT>-HasSheMeSh<SheMeSh> .Kî<.Kî> Lo'<Lo'> LaqQalLîM<QaL> HamMēRôZ<MēRôZ> W:Lo'<Lo'> LagGiBôRîM<.GiBôR> HamMiL:ChāMâ<MiL:ChāMâ> W:GaM<.GaM> Lo'<Lo'> LaChăKāMîM<ChāKāM> LeCheM<LeCheM> W:GaM<.GaM> Lo'<Lo'> LanN:VoNîM<BYN> `oSheR<`oSheR> W:GaM<.GaM> Lo'<Lo'> LayYoD:`îM<YD`> ChēN<ChēN> .Kî<.Kî>-`ēT<`ēT> WāFeGa`<PeGa`> YiQ:ReH<QRH> 'eT<'ēT>-.KulLāM<.KoL>"],
[9012, ".Kî<.Kî> .GaM<.GaM> Lo'<Lo'>-YēDa`<YD`> Hā'āDāM<'āDāM> 'eT<'ēT>-`itTô<`ēT> .KadDāGîM<.DāG> ShenNe'ĕChāŹîM<'ChŹ> BiM:ZôDâ<M:ZôDâ> Rā`â<Rā`â> W:KazZiPŏRîM<ZiPôR> Hā'ăChuŹôT<'ChŹ> BaPāCh<PaCh> .KāHēM<.K> YûQāShîM<YQSh> B:Nê<BēN> Hā'āDāM<'āDāM> L:`ēT<`ēT> Rā`â<Rā`â> .K:ShetTiPôL<NFL> `ăLêHeM<`aL> PiT:'oM<PiT:'oM>"],
[9013, ".GaM<.GaM>-ŹoH<ŹoH> Rā'îTî<R'H> ChāK:Mâ<ChāK:Mâ> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> ûG:DôLâ<.GāDôL> Hî'<Hî'> 'ēLāY<'eL>"],
[9014, "`îR<`îR> Q:ThanNâ<QāThoN> Wa'ăNāShîM<'îSh> BāhH<B> M:`āTh<M:`aTh> ûVā'<BW'>-'ēLëHā<'eL> MeLeK:<MeLeK:> .GāDôL<.GāDôL> W:ŚāVaV<ŚVV> 'oTāhH<'ēT> ûVāNâ<BNH> `āLëHā<`aL> M:ZôDîM<MāZôD> .G:DoLîM<.GāDôL>"],
[9015, "ûMāZā'<MZ'> VāhH<B> 'îSh<'îSh> MiŚ:.KēN<MiŚ:.KēN> ChāKāM<ChāKāM> ûMilLaTh<MLTh>-Hû'<Hû'> 'eT<'ēT>-Hā`îR<`îR> B:ChāK:MāTô<ChāK:Mâ> W:'āDāM<'āDāM> Lo'<Lo'> ŹāKaR<ŹKR> 'eT<'ēT>-Hā'îSh<'îSh> HamMiŚ:.KēN<MiŚ:.KēN> HaHû'<Hû'>"],
[9016, "W:'āMaR:.Tî<'MR> 'āNî<'ăNî> ThôVâ<ThôV> ChāK:Mâ<ChāK:Mâ> MigG:VûRâ<.G:VûRâ> W:ChāK:MaT<ChāK:Mâ> HamMiŚ:.KēN<MiŚ:.KēN> B:ŹûYâ<BŹH> ûD:VāRâv<.DāVāR> 'êNāM<'aYiN> NiSh:Mā`îM<ShM`>"],
[9017, ".DiV:Rê<.DāVāR> ChăKāMîM<ChāKāM> B:NaChaT<NaChaT> NiSh:Mā`îM<ShM`> MiźŹa`ăQaT<Ź:`āQâ> MôShēL<MShL> BakK:ŚîLîM<.K:ŚîL>"],
[9018, "ThôVâ<ThôV> ChāK:Mâ<ChāK:Mâ> MikK:Lê<.K:Lî> Q:RāV<Q:RāV> W:ChôThe'<ChTh'> 'eChāD<'eChāD> Y:'aBēD<'VD> ThôVâ<ThôV> HaR:BēH<RVH>"],
[10001, "Ź:VûVê<Ź:VûV> MāWeT<MāWeT> YaV:'îSh<B'Sh> YaBî,a`<NV`> SheMeN<SheMeN> RôQē,aCh<RQCh> YāQāR<YāQāR> MēChāK:Mâ<ChāK:Mâ> MikKāVôD<.KāVôD> ŚiK:LûT<ŚiK:LûT> M:`āTh<M:`aTh>"],
[10002, "LēV<LēV> ChāKāM<ChāKāM> LîMîNô<YāMîN> W:LēV<LēV> .K:ŚîL<.K:ŚîL> LiS:Mo'Lô<S:Mo'L>"],
[10003, "W:GaM<.GaM>-BadDeReK:<.DeReK:> [1 .K:SheHaśŚāKāL<ŚāKāL> 1] [2 .K:SheśŚāKāL<ŚāKāL> 2] HoLēK:<HLK:> LiBô<LēV> ChāŚēR<ChāŚēR> W:'āMaR<'MR> LakKoL<.KoL> ŚāKāL<ŚāKāL> Hû'<Hû'>"],
[10004, "'iM<'iM>-Rû,aCh<Rû,aCh> HamMôShēL<MShL> .Ta`ăLeH<`LH> `āLëKā<`aL> M:QôM:Kā<MāQôM> 'aL<'aL>-.TanNaCh<NWCh> .Kî<.Kî> MaR:Pē'<MaR:Pē'> YanNî,aCh<NWCh> ChăThā'îM<ChēTh:'> .G:DôLîM<.GāDôL>"],
[10005, "YēSh<YēSh> Rā`â<Rā`â> Rā'îTî<R'H> .TaChaT<.TaChaT> HasShāMeSh<SheMeSh> .KiSh:GāGâ<Sh:GāGâ> SheyYoZā'<YZ'> MilLiF:Nê<PāNeH> HasShalLîTh<ShalLîTh>"],
[10006, "NitTaN<NTN> HaśŚeKeL<ŚeKeL> BamM:RôMîM<MāRôM> RaBîM<RaV> Wa`ăShîRîM<`āShîR> BasShēFeL<ShēFeL> YēShēVû<YShV>"],
[10007, "Rā'îTî<R'H> `ăVāDîM<`eVeD> `aL<`aL>-ŚûŚîM<ŚûŚ> W:SāRîM<SaR> HoL:KîM<HLK:> .Ka`ăVāDîM<`eVeD> `aL<`aL>-Hā'āReZ<'eReZ>"],
[10008, "ChoFēR<ChFR> .GûmMāZ<.GûmMāZ> Bô<B> YiPôL<NFL> ûFoRēZ<PRZ> .GāDēR<.GāDēR> YisSh:KenNû<NShK:> NāChāSh<NāChāSh>"],
[10009, "MaśŚî,a`<NŚ`> 'ăVāNîM<'eVeN> Yē`āZēV<`ZV> BāHeM<B> BôQē,a`<BQ`> `ēZîM<`ēZ> YiśŚāKeN<ŚKN> BāM<B>"],
[10010, "'iM<'iM>-QēHâ<QHH> HaBaR:ŹeL<BaR:ŹeL> W:Hû'<Hû'> Lo'<Lo'>-FāNîM<PāNîM> QiL:QaL<QLL> WaChăYāLîM<ChaYiL> Y:GaBēR<.GVR> W:YiT:RôN<YiT:RôN> HaK:ShêR<.KShR> ChāK:Mâ<ChāK:Mâ>"],
[10011, "'iM<'iM>-YisShoK:<NShK:> HanNāChāSh<NāChāSh> B:Lô'<Lo'>-LāChaSh<LaChaSh> W:'êN<'aYiN> YiT:RôN<YiT:RôN> L:Va`aL<Ba`aL> HalLāShôN<LāShôN>"],
[10012, ".DiV:Rê<.DāVāR> Fî<PeH>-ChāKāM<ChāKāM> ChēN<ChēN> W:SiF:TôT<SāFâ> .K:ŚîL<.K:ŚîL> .T:ValL:`enNû<BL`>"],
[10013, ".T:ChilLaT<.T:ChilLâ> .DiV:Rê<.DāVāR>-FîHû<PeH> ŚiK:LûT<ŚiK:LûT> W:'aChăRîT<'aChăRîT> PîHû<PeH> HôLēLûT<HôLēLôT> Rā`â<Rā`â>"],
[10014, "W:HaśŚāKāL<ŚāKāL> YaR:BeH<RVH> D:VāRîM<.DāVāR> Lo'<Lo'>-YēDa`<YD`> Hā'āDāM<'āDāM> MaH<Mâ>-SheyYiH:YeH<HYH> Wa'ăSheR<'ăSheR> YiH:YeH<HYH> Mē'aChăRâv<'aChăRê> Mî<Mî> YagGîD<NGD> Lô<L>"],
[10015, "`ăMaL<`āMāL> HakK:ŚîLîM<.K:ŚîL> .T:YagG:`enNû<YG`> 'ăSheR<'ăSheR> Lo'<Lo'>-YāDa`<YD`> LāLeKeT<HLK:> 'eL<'eL>-`îR<`îR>"],
[10016, "'î<'î>-LāK:<L> 'eReZ<'eReZ> ShemMaL:.KēK:<MeLeK:> Nā`aR<Na`aR> W:SāRaYiK:<SaR> BaBoQeR<BoQeR> Yo'KēLû<'KL>"],
[10017, "'aSh:RêK:<'aSh:Rê> 'eReZ<'eReZ> ShemMaL:.KēK:<MeLeK:> BeN<BēN>-ChôRîM<ChôRîM> W:SāRaYiK:<SaR> Bā`ēT<`ēT> Yo'KēLû<'KL> BiG:VûRâ<.G:VûRâ> W:Lo'<Lo'> VasSh:Tî<Sh:Tî>"],
[10018, "Ba`ăZaL:.TaYiM<`ăZaL:.TaYiM> YimMaK:<MKK:> HamM:QāReH<M:QāReH> ûV:ShiF:LûT<ShiF:LûT> YāDaYiM<YāD> YiD:LoF<.DLF> HaBāYiT<BaYiT>"],
[10019, "LiS:ChôQ<S:ChôQ> `oSîM<`SH> LeCheM<LeCheM> W:YaYiN<YaYiN> Y:SamMaCh<SMCh> ChayYîM<ChaY> W:HakKeŚeF<.KeŚeF> Ya`ăNeH<`NH> 'eT<'ēT>-HakKoL<.KoL>"],
[10020, ".GaM<.GaM> B:MadDā`ăKā<MadDā`> MeLeK:<MeLeK:> 'aL<'aL>-.T:QalLēL<QLL> ûV:ChaD:Rê<CheDeR> MiSh:.KāV:Kā<MiSh:.KāV> 'aL<'aL>-.T:QalLēL<QLL> `āShîR<`āShîR> .Kî<.Kî> `ôF<`ôF> HasShāMaYiM<ShāMaYiM> YôLîK:<HLK:> 'eT<'ēT>-HaqQôL<QôL> ûVa`aL<Ba`aL> [1 HakK:NāFaYiM<.KāNāF> 1] [2 .K:NāFaYiM<.KāNāF> 2] YagGêD<NGD> .DāVāR<.DāVāR>"],
[11001, "ShalLaCh<ShLCh> LaCh:M:Kā<LeCheM> `aL<`aL>-P:Nê<PāNeH> HamMāYiM<MaYiM> .Kî<.Kî>-V:RoV<RoV> HayYāMîM<YôM> .TiM:Zā'enNû<MZ'>"],
[11002, ".TeN<NTN>-ChēLeQ<ChēLeQ> L:ShiV:`â<ShiV:`â> W:GaM<.GaM> LiSh:MôNâ<Sh:MoNâ> .Kî<.Kî> Lo'<Lo'> TēDa`<YD`> MaH<Mâ>-yYiH:YeH<HYH> Rā`â<Rā`â> `aL<`aL>-Hā'āReZ<'eReZ>"],
[11003, "'iM<'iM>-YimMāL:'û<ML'> He`āVîM<`āV> .GeSheM<.GeSheM> `aL<`aL>-Hā'āReZ<'eReZ> YāRîQû<RYQ> W:'iM<'iM>-YiPôL<NFL> `ēZ<`ēZ> BadDāRôM<.DāRôM> W:'iM<'iM> BazZāFôN<ZāFôN> M:QôM<MāQôM> SheyYiPôL<NFL> Hā`ēZ<`ēZ> ShāM<ShāM> Y:Hû'<HWH>"],
[11004, "ShoMēR<ShMR> Rû,aCh<Rû,aCh> Lo'<Lo'> YiŹ:Rā`<ŹR`> W:Ro'eH<R'H> Ve`āVîM<`āV> Lo'<Lo'> YiQ:ZôR<QZR>"],
[11005, ".Ka'ăSheR<'ăSheR> 'êN:Kā<'aYiN> YôDē,a`<YD`> MaH<Mâ>-.DeReK:<.DeReK:> HāRû,aCh<Rû,aCh> .Ka`ăZāMîM<`eZeM> B:VeTheN<BeTheN> HamM:Lē'â<MāLē'> .KāKâ<.KāKâ> Lo'<Lo'> TēDa`<YD`> 'eT<'ēT>-Ma`ăSēH<Ma`ăSeH> Hā'ĕLoHîM<'ĕLoHîM> 'ăSheR<'ăSheR> Ya`ăSeH<`SH> 'eT<'ēT>-HakKoL<.KoL>"],
[11006, "BaBoQeR<BoQeR> Ź:Ra`<ŹR`> 'eT<'ēT>-ŹaR:`eKā<ŹeRa`> W:Lā`eReV<`eReV> 'aL<'aL>-.TanNaCh<NWCh> YāDeKā<YāD> .Kî<.Kî> 'êN:Kā<'aYiN> YôDē`<YD`> 'ê<'ê> ŹeH<ŹeH> YiK:ShāR<.KShR> HăŹeH<ŹeH> 'ô<'ô>-ŹeH<ŹeH> W:'iM<'iM>-Sh:NêHeM<Sh:NaYiM> .K:'eChāD<'eChāD> ThôVîM<ThôV>"],
[11007, "ûMāTôQ<MāTôQ> Hā'ôR<'ôR> W:ThôV<ThôV> La`êNaYiM<`aYiN> LiR:'ôT<R'H> 'eT<'ēT>-HasShāMeSh<SheMeSh>"],
[11008, ".Kî<.Kî> 'iM<'iM>-ShāNîM<ShāNâ> HaR:BēH<RVH> YiCh:YeH<ChYH> Hā'āDāM<'āDāM> B:KulLāM<.KoL> YiS:MāCh<SMCh> W:YiŹ:.KoR<ŹKR> 'eT<'ēT>-Y:Mê<YôM> HaChoSheK:<ChoSheK:> .Kî<.Kî>-HaR:BēH<RVH> YiH:Yû<HYH> .KāL<.KoL>-SheBā'<BW'> HāVeL<HeVeL>"],
[11009, "S:MaCh<SMCh> BāChûR<BāChûR> B:YaL:DûTëKā<YaL:DûT> WîThîV:Kā<YThV> LiB:Kā<LēV> BîMê<YôM> V:ChûRôTeKā<B:ChûRôT> W:HalLēK:<HLK:> B:DaR:Kê<.DeReK:> LiB:Kā<LēV> ûV:MaR:'ê<MaR:'eH> `êNëKā<`aYiN> W:Dā`<YD`> .Kî<.Kî> `aL<`aL>-.KāL<.KoL>-'ēlLeH<'ēlLeH> Y:Vî'ăKā<BW'> Hā'ĕLoHîM<'ĕLoHîM> BamMiSh:PāTh<MiSh:PāTh>"],
[11010, "W:HāŚēR<ŚWR> .Ka`aŚ<.Ka`aŚ> MilLiBeKā<LēV> W:Ha`ăVēR<`VR> Rā`â<Rā`â> MiB:SāReKā<BāSāR> .Kî<.Kî>-HayYaL:DûT<YaL:DûT> W:HasShaChăRûT<ShaChăRûT> HāVeL<HeVeL>"],
[12001, "ûŹ:KoR<ŹKR> 'eT<'ēT>-BôR:'ëKā<BR'> BîMê<YôM> B:ChûRoTëKā<B:ChûRôT> `aD<`aD> 'ăSheR<'ăSheR> Lo'<Lo'>-YāVo'û<BW'> Y:Mê<YôM> HāRā`â<Rā`â> W:HigGî`û<NG`> ShāNîM<ShāNâ> 'ăSheR<'ăSheR> .To'MaR<'MR> 'êN<'aYiN>-Lî<L> VāHeM<B> ChēFeZ<ChēFeZ>"],
[12002, "`aD<`aD> 'ăSheR<'ăSheR> Lo'<Lo'>-TeCh:ShaK:<ChShK:> HasSheMeSh<SheMeSh> W:Hā'ôR<'ôR> W:HayYāRē,aCh<YāRē,aCh> W:HakKôKāVîM<.KôKāV> W:ShāVû<ShWV> He`āVîM<`āV> 'aChaR<'aChaR> HagGāSheM<.GeSheM>"],
[12003, "BayYôM<YôM> SheyYāŹu`û<ŹW`> ShoM:Rê<ShMR> HaBaYiT<BaYiT> W:HiT:`aû:Tû<`WT> 'aN:Shê<'îSh> HeChāYiL<ChaYiL> ûVāTh:Lû<BThL> HatThoChăNôT<ThChN> .Kî<.Kî> Mi`ēThû<M`Th> W:ChāSh:Kû<ChShK:> HāRo'ôT<R'H> Bā'ăRuBôT<'ăRuBâ>"],
[12004, "W:ŚugG:Rû<ŚGR> D:LāTaYiM<.DeLeT> BasShûQ<ShûQ> BiSh:FaL<ShFL> QôL<QôL> HatThaChăNâ<ThaChăNâ> W:YāQûM<QWM> L:QôL<QôL> HazZiPôR<ZiPôR> W:YisShaChû<ShChCh> .KāL<.KoL>-B:NôT<BaT> HasShîR<ShîR>"],
[12005, ".GaM<.GaM> MigGāVo,ahH<.GāVo,ahH> YiRā'û<YR'> W:ChaT:ChatTîM<ChaT:ChaT> BadDeReK:<.DeReK:> W:YāNē'Z<NZZ> HasShāQēD<ShāQēD> W:YiŚ:.TaBēL<ŚVL> HeChāGāV<ChāGāV> W:TāFēR<PRR> Hā'ăViyYôNâ<'ăViyYôNâ> .Kî<.Kî>-HoLēK:<HLK:> Hā'āDāM<'āDāM> 'eL<'eL>-BêT<BaYiT> `ôLāMô<`ôLāM> W:ŚāV:Vû<ŚVV> VasShûQ<ShûQ> HaśŚoF:DîM<ŚFD>"],
[12006, "`aD<`aD> 'ăSheR<'ăSheR> Lo'<Lo'>-[1 YiRChaQ<RChQ> 1] [2 YēRāTēQ<RTQ> 2] CheVeL<CheVeL> HakKeŚeF<.KeŚeF> W:TāRuZ<RZZ> .GulLaT<.GulLâ> HaźŹāHāV<ŹāHāV> W:TisShāVeR<ShVR> .KaD<.KaD> `aL<`aL>-HamMaBû,a`<MaBû,a`> W:NāRoZ<RZZ> HagGaL:.GaL<.GaL:.GaL> 'eL<'eL>-HaBôR<BôR>"],
[12007, "W:YāShoV<ShWV> He`āFāR<`āFāR> `aL<`aL>-Hā'āReZ<'eReZ> .K:SheHāYâ<HYH> W:HāRû,aCh<Rû,aCh> .TāShûV<ShWV> 'eL<'eL>-Hā'ĕLoHîM<'ĕLoHîM> 'ăSheR<'ăSheR> N:TāNāhH<NTN>"],
[12008, "HăVēL<HeVeL> HăVāLîM<HeVeL> 'āMaR<'MR> HaqQôHeLeT<QoHeLeT> HakKoL<.KoL> HāVeL<HeVeL>"],
[12009, "W:YoTēR<YôTēR> SheHāYâ<HYH> QoHeLeT<QoHeLeT> ChāKāM<ChāKāM> `ôD<`ôD> LimMaD<LMD>-.Da`aT<.Da`aT> 'eT<'ēT>-Hā`āM<`aM> W:'iźŹēN<'ŹN> W:ChiqQēR<ChQR> .TiqQēN<.TQN> M:ShāLîM<MāShāL> HaR:BēH<RVH>"],
[12010, "BiqQēSh<BQSh> QoHeLeT<QoHeLeT> LiM:Zo'<MZ'> .DiV:Rê<.DāVāR>-ChēFeZ<ChēFeZ> W:KāTûV<.KTV> YoSheR<YoSheR> .DiV:Rê<.DāVāR> 'ĕMeT<'ĕMeT>"],
[12011, ".DiV:Rê<.DāVāR> ChăKāMîM<ChāKāM> .KadDāR:VoNôT<.DāR:VāN> ûK:MaS:M:RôT<MaS:MēR> N:Thû`îM<NTh`> Ba`ăLê<Ba`aL> 'ăŚuPôT<'ăŚuPâ> NitT:Nû<NTN> MēRo`eH<R`H> 'eChāD<'eChāD>"],
[12012, "W:YoTēR<YôTēR> MēHēmMâ<HēM> B:Nî<BēN> HiźŹāHēR<ŹHR> `ăSôT<`SH> Ś:FāRîM<ŚēFeR> HaR:BēH<RVH> 'êN<'aYiN> QēZ<QēZ> W:LaHaG<LaHaG> HaR:BēH<RVH> Y:Gi`aT<Y:Gî`â> BāSāR<BāSāR>"],
[12013, "ŚôF<ŚôF> .DāVāR<.DāVāR> HakKoL<.KoL> NiSh:Mā`<ShM`> 'eT<'ēT>-Hā'ĕLoHîM<'ĕLoHîM> Y:Rā'<YR'> W:'eT<'ēT>-MiZ:WoTâv<MiZ:Wâ> Sh:MôR<ShMR> .Kî<.Kî>-ŹeH<ŹeH> .KāL<.KoL>-Hā'āDāM<'āDāM>"],
[12014, ".Kî<.Kî> 'eT<'ēT>-.KāL<.KoL>-Ma`ăSeH<Ma`ăSeH> Hā'ĕLoHîM<'ĕLoHîM> YāVi'<BW'> V:MiSh:PāTh<MiSh:PāTh> `aL<`aL> .KāL<.KoL>-Ne`:LāM<`LM> 'iM<'iM>-ThôV<ThôV> W:'iM<'iM>-Rā`<Ra`>"]
])
