Bib.ret([
[1001,"`O<`o> presbùteros<presbuteros> eklektêj<eklektos> kurìaj<kuria> kaì<kai> toîs<`o> téknois<teknon> autês,<autos> `oùs<`os> egò<egō> agapô<agapaō> en<en> alētheìaj,<alētheia> kaì<kai> ouk<ou'> egò<egō> mónos<monos> allà<alla> kaì<kai> pàntes<pas> `oi<`o> egnōkótes<ginōskō> tèn<`o> alètheian,<alētheia> "],
[1002,"dià<dia> tèn<`o> alètheian<alētheia> tèn<`o> ménousan<menō> en<en> `ēmîn<egō> kaì<kai> meth'<meta> `ēmôn<egō> éstai<eimi> eis<eis> tón<`o> aiôna.<aiōn> "],
[1003,"éstai<eimi> meth'<meta> `ēmôn<egō> chàris<charis> éleos<eleos> eirènē<eirēnē> parà<para> theoû<theos> patrós<patēr> kaì<kai> parà<para> Iēsoû<Iēsous> Christoû<Christos> toû<`o> `uioû<`uios> toû<`o> patrós<patēr> en<en> alētheìaj<alētheia> kaì<kai> agàpēj.<agapē> "],
[1004,"Echàrēn<chairō> lìan<lian> `óti<`oti> `eùrēka<`euriskō> ek<ek> tôn<`o> téknōn<teknon> sou<su> peripatoûntas<peripateō> en<en> alētheìaj,<alētheia> kathòs<kathōs> entolèn<entolē> elàbomen<lambanō> parà<para> toû<`o> patrós.<patēr> "],
[1005,"kaì<kai> nûn<nun> erōtô<erōtaō> se,<su> kurìa,<kuria> ouch<ou'> `ōs<`ōs> entolèn<entolē> kainèn<kainos> gràfōn<grafō> soi<su> allà<alla> `èn<`os> eìchomen<echō> ap'<apo> archês,<archē> `ìna<`ina> agapômen<agapaō> allèlous.<allēlōn> "],
[1006,"kaì<kai> `aùtē<`outos> estìn<eimi> `ē<`o> agàpē,<agapē> `ìna<`ina> peripatômen<peripateō> katà<kata> tàs<`o> entolàs<entolē> autoû:<autos> `aùtē<`outos> `ē<`o> entolè<entolē> estin,<eimi> kathòs<kathōs> ēkoùsate<akouō> ap'<apo> archês,<archē> `ìna<`ina> en<en> autêj<autos> peripatête.<peripateō> "],
[1007,"`Óti<`oti> polloì<polus> plànoi<planos> exêlthon<exerchomai> eis<eis> tón<`o> kósmon,<kosmos> `oi<`o> mè<mē> `omologoûntes<`omologeō> Iēsoûn<Iēsous> Christón<Christos> erchómenon<erchomai> en<en> sarkì:<sarx> `oûtós<`outos> estin<eimi> `o<`o> plànos<planos> kaì<kai> `o<`o> antìchristos.<antichristos> "],
[1008,"Blépete<blepō> `eautoùs,<`eautou> `ìna<`ina> mè<mē> apolésēte<apollumi> `à<`os> eirgasàmetha<ergazomai> allà<alla> misthón<misthos> plèrē<plērēs> apolàbēte.<apolambanō> "],
[1009,"pâs<pas> `o<`o> proàgōn<proagō> kaì<kai> mè<mē> ménōn<menō> en<en> têj<`o> didachêj<didachē> toû<`o> Christoû<Christos> theón<theos> ouk<ou'> échei:<echō> `o<`o> ménōn<menō> en<en> têj<`o> didachêj,<didachē> `oûtos<`outos> kaì<kai> tón<`o> patéra<patēr> kaì<kai> tón<`o> `uión<`uios> échei.<echō> "],
[1010,"eì<ei'> tis<tis> érchetai<erchomai> prós<pros> `umâs<su> kaì<kai> taùtēn<`outos> tèn<`o> didachèn<didachē> ou'<ou'> férei,<ferō> mè<mē> lambànete<lambanō> autón<autos> eis<eis> oikìan<oikia> kaì<kai> chaìrein<chairō> autôj<autos> mè<mē> légete:<legō> "],
[1011,"`o<`o> légōn<legō> gàr<gar> autôj<autos> chaìrein<chairō> koinōneî<koinōneō> toîs<`o> érgois<ergon> autoû<autos> toîs<`o> ponēroîs.<ponēros> "],
[1012,"pollà<polus> échōn<echō> `umîn<su> gràfein<grafō> ouk<ou'> eboulèthēn<boulomai> dià<dia> chàrtou<chartēs> kaì<kai> mélanos,<melas> allà<alla> elpìzō<elpizō> genésthai<ginomai> prós<pros> `umâs<su> kaì<kai> stóma<stoma> prós<pros> stóma<stoma> lalêsai,<laleō> `ìna<`ina> `ē<`o> charà<chara> `ēmôn<egō> peplērōménē<plēroō> êj.<eimi> "],
[1013,"Aspàzetaì<aspazomai> se<su> tà<`o> tékna<teknon> tês<`o> adelfês<adelfē> sou<su> tês<`o> eklektês.<eklektos> "]
])
