Bib.ret([
[1001,"Paûlos<Paulos> désmios<desmios> Christoû<Christos> Iēsoû<Iēsous> kaì<kai> Timótheos<Timotheos> `o<`o> adelfós<adelfos> Filèmoni<Filēmōn> tôj<`o> agapētôj<agapētos> kaì<kai> sunergôj<sunergos> `ēmôn<egō> "],
[1002,"kaì<kai> Apfìaj<Apfia> têj<`o> adelfêj<adelfē> kaì<kai> Archìppōj<Archippos> tôj<`o> sustratiòtēj<sustratiōtēs> `ēmôn<egō> kaì<kai> têj<`o> kat'<kata> oîkón<oikos> sou<su> ekklēsìaj,<ekklēsia> "],
[1003,"chàris<charis> `umîn<su> kaì<kai> eirènē<eirēnē> apó<apo> theoû<theos> patrós<patēr> `ēmôn<egō> kaì<kai> kurìou<kurios> Iēsoû<Iēsous> Christoû.<Christos> "],
[1004,"Eucharistô<eucharisteō> tôj<`o> theôj<theos> mou<egō> pàntote<pantote> mneìan<mneia> sou<su> poioùmenos<poieō> epì<epi> tôn<`o> proseuchôn<proseuchē> mou,<egō> "],
[1005,"akoùōn<akouō> sou<su> tèn<`o> agàpēn<agapē> kaì<kai> tèn<`o> pìstin,<pistis> `èn<`os> écheis<echō> prós<pros> tón<`o> kùrion<kurios> Iēsoûn<Iēsous> kaì<kai> eis<eis> pàntas<pas> toùs<`o> `agìous,<`agios> "],
[1006,"`ópōs<`opōs> `ē<`o> koinōnìa<koinōnia> tês<`o> pìsteòs<pistis> sou<su> energès<energēs> génētai<ginomai> en<en> epignòsei<epignōsis> pantós<pas> agathoû<agathos> toû<`o> en<en> `ēmîn<egō> eis<eis> Christón.<Christos> "],
[1007,"charàn<chara> gàr<gar> pollèn<polus> éschon<echō> kaì<kai> paràklēsin<paraklēsis> epì<epi> têj<`o> agàpēj<agapē> sou,<su> `óti<`oti> tà<`o> splàgchna<splagchnon> tôn<`o> `agìōn<`agios> anapépautai<anapauō> dià<dia> soû,<su> adelfé.<adelfos> "],
[1008,"dió<dio> pollèn<polus> en<en> Christôj<Christos> parrēsìan<parrēsia> échōn<echō> epitàssein<epitassō> soi<su> tó<`o> anêkon<anēkō> "],
[1009,"dià<dia> tèn<`o> agàpēn<agapē> mâllon<mallon> parakalô,<parakaleō> toioûtos<toioutos> òn<eimi> `ōs<`ōs> Paûlos<Paulos> presbùtēs<presbutēs> nunì<nuni> dé<de> kaì<kai> désmios<desmios> Christoû<Christos> Iēsoû:<Iēsous> "],
[1010,"Parakalô<parakaleō> se<su> perì<peri> toû<`o> emoû<emos> téknou,<teknon> `ón<`os> egénnēsa<gennaō> en<en> toîs<`o> desmoîs,<desmos> Onèsimon,<Onēsimos> "],
[1011,"tón<`o> poté<poté> soi<su> àchrēston<achrēstos> nunì<nuni> dé<de> [kaì]<kai> soì<su> kaì<kai> emoì<egō> eùchrēston,<euchrēstos> "],
[1012,"`ón<`os> anépempsà<anapempō> soi,<su> autón,<autos> toût'<`outos> éstin<eimi> tà<`o> emà<emos> splàgchna:<splagchnon> "],
[1013,"`Ón<`os> egò<egō> eboulómēn<boulomai> prós<pros> emautón<emautou> katéchein,<katechō> `ìna<`ina> `upér<`uper> soû<su> moi<egō> diakonêj<diakoneō> en<en> toîs<`o> desmoîs<desmos> toû<`o> euaggelìou,<euaggelion> "],
[1014,"chōrìs<chōris> dé<de> tês<`o> sês<sos> gnòmēs<gnōmē> oudén<oudeis> ēthélēsa<thelō> poiêsai,<poieō> `ìna<`ina> mè<mē> `ōs<`ōs> katà<kata> anàgkēn<anagkē> tó<`o> agathón<agathos> sou<su> êj<eimi> allà<alla> katà<kata> `ekoùsion.<`ekousios> "],
[1015,"Tàcha<Tacha> gàr<gar> dià<dia> toûto<`outos> echōrìsthē<chōrizō> prós<pros> `òran,<`ōra> `ìna<`ina> aiònion<aiōnios> autón<autos> apéchējs,<apechō> "],
[1016,"oukéti<ouketi> `ōs<`ōs> doûlon<doulos> all'<alla> `upér<`uper> doûlon,<doulos> adelfón<adelfos> agapētón,<agapētos> màlista<malista> emoì,<egō> pósōj<posos> dé<de> mâllon<mallon> soì<su> kaì<kai> en<en> sarkì<sarx> kaì<kai> en<en> kurìōj.<kurios> "],
[1017,"ei'<ei'> oûn<oun> me<egō> écheis<echō> koinōnón,<koinōnos> proslaboû<proslambanō> autón<autos> `ōs<`ōs> emé.<egō> "],
[1018,"ei'<ei'> dé<de> ti<tis> ēdìkēsén<adikeō> se<su> è<ē> ofeìlei,<ofeilō> toûto<`outos> emoì<egō> ellóga.<ellogeō> "],
[1019,"egò<egō> Paûlos<Paulos> égrapsa<grafō> têj<`o> emêj<emos> cheirì,<cheir> egò<egō> apotìsō:<apotinō> `ìna<`ina> mè<mē> légō<legō> soi<su> `óti<`oti> kaì<kai> seautón<seautou> moi<egō> prosofeìleis.<prosofeilō> "],
[1020,"naì<nai> adelfé,<adelfos> egò<egō> sou<su> onaìmēn<oninamai> en<en> kurìōj:<kurios> anàpausón<anapauō> mou<egō> tà<`o> splàgchna<splagchnon> en<en> Christôj.<Christos> "],
[1021,"pepoithòs<peithō> têj<`o> `upakoêj<`upakoē> sou<su> égrapsà<grafō> soi,<su> eidòs<oida> `óti<`oti> kaì<kai> `upér<`uper> `à<`os> légō<legō> poièseis.<poieō> "],
[1022,"`àma<`ama> dé<de> kaì<kai> `etoìmazé<`etoimazō> moi<egō> xenìan:<xenia> elpìzō<elpizō> gàr<gar> `óti<`oti> dià<dia> tôn<`o> proseuchôn<proseuchē> `umôn<su> charisthèsomai<charizomai> `umîn.<su> "],
[1023,"Aspàzetaì<aspazomai> se<su> Epafrâs<Epafras> `o<`o> sunaichmàlōtós<sunaichmalōtos> mou<egō> en<en> Christôj<Christos> Iēsoû,<Iēsous> "],
[1024,"Mârkos,<Markos> Arìstarchos,<Aristarchos> Dēmâs,<Dēmas> Loukâs,<Loukas> `oi<`o> sunergoì<sunergos> mou.<egō> "],
[1025,"`Ē<`o> chàris<charis> toû<`o> kurìou<kurios> Iēsoû<Iēsous> Christoû<Christos> metà<meta> toû<`o> pneùmatos<pneuma> `umôn.<su> "]
])
