Bib.ret([
[1001,""],
[2001,""],
[3001,""],
[4001,""],
[5001,""],
[6001,""],
[7001,""],
[8001,""],
[9001,""],
[10001,""],
[11001,""],
[12001,""],
[13001,""],
[14001,""],
[15001,""],
[15002,""],
[15003,""],
[15004,""],
[15005,""],
[15006,""],
[15007,""],
[15008,""],
[15009,""],
[15010,""],
[15011,""],
[15012,""],
[15013,""],
[15014,""],
[15015,""],
[15016,""],
[15017,""],
[15018,""],
[15019,""],
[15020,""],
[15021,"egenèthēsan<ginomai> dé<de> `ai<`o> póleis<polis> autôn<autos> pólis<polis> pròtē<prōtos> fulês<fulē> `uiôn<`uios> Iouda<Ioudas> ef'<epi> `orìōn<`orion> Edōm<Edōm> epì<epi> tês<`o> erèmou<erēmos> Kabseēl<Kabseēl> kaì<kai> Edrai<Edrai> kaì<kai> Iagour<Iagour> "],
[15022,"kaì<kai> Kina<Kina> kaì<kai> Dimōna<Dimōna> kaì<kai> Adada<Adada> "],
[15023,"kaì<kai> Kedes<Kedes> kaì<kai> Ithnazif<Ithnazif> "],
[15024,"kaì<kai> Telem<Telem> kaì<kai> Balōth<Balōth> "],
[15025,"kaì<kai> pólis<polis> Aserōn<Aserōn> `aùtē<`outos> Asōr<Asōr> "],
[15026,"Amam<Amam> kaì<kai> Samaa<Samaa> kaì<kai> Mōlada<Mōlada> "],
[15027,"kaì<kai> Asergadda<Asergadda> kaì<kai> Baithfaleth<Baithfaleth> "],
[15028,"kaì<kai> Asarsoula<Asarsoula> kaì<kai> Bērsabee<Bērsabee> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> kaì<kai> `ai<`o> epaùleis<epaulis> autôn<autos> "],
[15029,"Baala<Baala> kaì<kai> Auim<Auim> kaì<kai> Asem<Asem> "],
[15030,"kaì<kai> Elthōdad<Elthōdad> kaì<kai> Chasil<Chasil> kaì<kai> Erma<Erma> "],
[15031,"kaì<kai> Sikeleg<Sikeleg> kaì<kai> Medebēna<Medebēna> kaì<kai> Sansanna<Sansanna> "],
[15032,"kaì<kai> Labōth<Labōth> kaì<kai> Sele:im<Seleim> kaì<kai> Remmōn<Remmōn> póleis<polis> eìkosi<eikosi> kaì<kai> ennéa<ennea> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[15033,"en<en> têj<`o> pedinêj<pedinos> Esthaol<Esthaol> kaì<kai> Saraa<Saraa> kaì<kai> Asna<Asna> "],
[15034,"kaì<kai> Ramen<Ramen> kaì<kai> Zanō<Zanō> kaì<kai> Adiatha:im<Adiathaim> kaì<kai> Ēna:im<Ēnaim> "],
[15035,"kaì<kai> Ierimouth<Ierimouth> kaì<kai> Odollam<Odollam> kaì<kai> Nemra<Nemra> kaì<kai> Sōchō<Sōchō> kaì<kai> Azēka<Azēka> "],
[15036,"kaì<kai> Sargarim<Sargarim> kaì<kai> Gadēra<Gadēra> kaì<kai> `ai<`o> epaùleis<epaulis> autês<autos> póleis<polis> déka<deka> téssares<tessares> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[15037,"Sennan<Sennan> kaì<kai> Adasa<Adasa> kaì<kai> Magdalgad<Magdalgad> "],
[15038,"kaì<kai> Dalaan<Dalaan> kaì<kai> Masfa<Masfa> kaì<kai> Iechthaēl<Iechthaēl> "],
[15039,"kaì<kai> Lachis<Lachis> kaì<kai> Bazkath<Bazkath> kaì<kai> Aglōn<Aglōn> "],
[15040,"kaì<kai> Chabba<Chabba> kaì<kai> Lamas<Lamas> kaì<kai> Chathlōs<Chathlōs> "],
[15041,"kaì<kai> Gadērōth<Gadērōth> kaì<kai> Bēthdagōn<Bēthdagōn> kaì<kai> Nōma<Nōma> kaì<kai> Makēda<Makēda> póleis<polis> dekaéx<dekaex> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[15042,"Lebna<Lebna> kaì<kai> Ather<Ather> "],
[15043,"kaì<kai> Ieftha<Ieftha> kaì<kai> Asenna<Asenna> kaì<kai> Nesib<Nesib> "],
[15044,"kaì<kai> Ke:ila<Keila> kaì<kai> Achzib<Achzib> kaì<kai> Marēsa<Marēsa> kaì<kai> Edōm<Edōm> póleis<polis> ennéa<ennea> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[15045,"Akkarōn<Akkarōn> kaì<kai> `ai<`o> kômai<kōmē> autês<autos> kaì<kai> `ai<`o> epaùleis<epaulis> autês<autos> "],
[15046,"kaì<kai> apó<apo> Akkarōn<Akkarōn> Iemnai<Iemnai> kaì<kai> pâsai<pas> `ósai<`osos> eisìn<eimi> plēsìon<plēsion> Asdōd<Asdōd> kaì<kai> `ai<`o> kômai<kōmē> "],
[15047,"autês<autos> kaì<kai> `ai<`o> epaùleis<epaulis> autês<autos> Gàza<Gaza> kaì<kai> `ai<`o> kômai<kōmē> autês<autos> kaì<kai> `ai<`o> epaùleis<epaulis> autês<autos> `éōs<`eōs> toû<`o> cheimàrrou<cheimarros> Aigùptou<Aiguptos> kaì<kai> `ē<`o> thàlassa<thalassa> `ē<`o> megàlē<megas> diorìzei<diorizō> "],
[15048,"kaì<kai> en<en> têj<`o> oreinêj<oreinos> Safir<Safir> kaì<kai> Iether<Iether> kaì<kai> Sōchō<Sōchō> "],
[15049,"kaì<kai> Renna<Renna> pólis<polis> grammàtōn<gramma> `aùtē<`outos> estìn<eimi> Dabir<Dabir> "],
[15050,"kaì<kai> Anōb<Anōb> kaì<kai> Esthemō<Esthemō> kaì<kai> Anim<Anim> "],
[15051,"kaì<kai> Gosom<Gosom> kaì<kai> Chilouōn<Chilouōn> kaì<kai> Gēlōn<Gēlōn> póleis<polis> déka<deka> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[15052,"Ereb<Ereb> kaì<kai> Esan<Esan> kaì<kai> Rouma<Rouma> "],
[15053,"kaì<kai> Ianoum<Ianoum> kaì<kai> Baiththapfoue<Baiththapfoue> kaì<kai> Afaka<Afaka> "],
[15054,"kaì<kai> Chammata<Chammata> kaì<kai> pólis<polis> Arbo<Arbo> `aùtē<`outos> estìn<eimi> Chebrōn<Chebrōn> kaì<kai> Siōr<Siōr> póleis<polis> ennéa<ennea> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[15055,"Maōn<Maōn> kaì<kai> Chermel<Chermel> kaì<kai> Zif<Zif> kaì<kai> Ietta<Ietta> "],
[15056,"kaì<kai> Iezrael<Iezrael> kaì<kai> Iekdaam<Iekdaam> kaì<kai> Zanōakim<Zanōakim> "],
[15057,"kaì<kai> Gabaa<Gabaa> kaì<kai> Thamna<Thamna> póleis<polis> ennéa<ennea> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[15058,"Aloul<Aloul> kaì<kai> Baithsour<Baithsour> kaì<kai> Gedōr<Gedōr> "],
[15059,"kaì<kai> Marōth<Marōth> kaì<kai> Baithanōth<Baithanōth> kaì<kai> Eltheken<Eltheken> póleis<polis> `éx<`ex> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[15059.01,"Thekō<Thekō> kaì<kai> Efratha<Efratha> `aùtē<`outos> estìn<eimi> Bēthleem<Bēthleem> kaì<kai> Fagōr<Fagōr> kaì<kai> Aitam<Aitam> kaì<kai> Koulon<Koulon> kaì<kai> Tatami<Tatami> kaì<kai> Sōrēs<Sōrēs> kaì<kai> Karem<Karem> kaì<kai> Gallim<Gallim> kaì<kai> Baithēr<Baithēr> kaì<kai> Manochō<Manochō> póleis<polis> `éndeka<`endeka> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[15060,"Kariathbaal<Kariathbaal> `aùtē<`outos> pólis<polis> Iarim<Iarim> kaì<kai> Arebba<Arebba> póleis<polis> dùo<duo> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> kaì<kai> `ai<`o> epaùleis<epaulis> autôn<autos> "],
[15061,"Baddargis<Baddargis> kaì<kai> Bētharaba<Bētharaba> kaì<kai> Madōn<Madōn> kaì<kai> Sochocha<Sochocha> "],
[15062,"kaì<kai> Nebsan<Nebsan> kaì<kai> `ai<`o> póleis<polis> `alôn<`als> kaì<kai> Ēngaddi<Ēngaddi> póleis<polis> `eptà<`epta> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[16001,""],
[17001,""],
[18001,""],
[18002,""],
[18003,""],
[18004,""],
[18005,""],
[18006,""],
[18007,""],
[18008,""],
[18009,""],
[18010,""],
[18011,""],
[18012,""],
[18013,""],
[18014,""],
[18015,""],
[18016,""],
[18017,""],
[18018,""],
[18019,""],
[18020,""],
[18021,"Bēthagla<Bēthagla> kaì<kai> Amekkasis<Amekkasis> "],
[18022,"kaì<kai> Baitharaba<Baitharaba> kaì<kai> Semrim<Semrim> kaì<kai> Bēthēl<Bēthēl> "],
[18023,"kaì<kai> Auim<Auim> kaì<kai> Afar<Afar> kaì<kai> Afra<Afra> "],
[18024,"kaì<kai> Aikaren<Aikaren> kaì<kai> Kafērammin<Kafērammin> kaì<kai> Gabaa<Gabaa> póleis<polis> dòdeka<dōdeka> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[18025,"Gabaōn<Gabaōn> kaì<kai> Rama<Rama> kaì<kai> Bērōth<Bērōth> "],
[18026,"kaì<kai> Masfa<Masfa> kaì<kai> Chefira<Chefira> kaì<kai> Amōsa<Amōsa> "],
[18027,"kaì<kai> Rekem<Rekem> kaì<kai> Ierfaēl<Ierfaēl> kaì<kai> Tharala<Tharala> "],
[18028,"kaì<kai> Sēlalef<Sēlalef> kaì<kai> Iebous<Iebous> `aùtē<`outos> estìn<eimi> Ierousalēm<Ierousalēm> kaì<kai> Gabaath<Gabaath> kaì<kai> pólis<polis> Iarim<Iarim> póleis<polis> déka<deka> treîs<treis> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> `aùtē<`outos> `ē<`o> klēronomìa<klēronomia> `uiôn<`uios> Beniamin<Beniamin> katà<kata> dèmous<dēmos> autôn<autos> "],
[19001,"kaì<kai> exêlthen<exerchomai> `o<`o> klêros<klēros> `o<`o> deùteros<deuteros> tôj<`o> Sumeōn<Sumeōn> kaì<kai> egenèthē<ginomai> `ē<`o> klēronomìa<klēronomia> autôn<autos> anà<ana> méson<mesos> klèrou<klēros> `uiôn<`uios> Iouda<Ioudas> "],
[19002,"kaì<kai> egenèthē<ginomai> `o<`o> klêros<klēros> autôn<autos> Bērsabee<Bērsabee> kaì<kai> Sabee<Sabee> kaì<kai> Mōlada<Mōlada> "],
[19003,"kaì<kai> Asersoual<Asersoual> kaì<kai> Bathoul<Bathoul> kaì<kai> Bōla<Bōla> kaì<kai> Asom<Asom> "],
[19004,"kaì<kai> Elthoulad<Elthoulad> kaì<kai> Erma<Erma> "],
[19005,"kaì<kai> Sekela<Sekela> kaì<kai> Baithammarchabōth<Baithammarchabōth> kaì<kai> Asersousim<Asersousim> "],
[19006,"kaì<kai> Baithlabath<Baithlabath> kaì<kai> `oi<`o> agroì<agros> autôn<autos> póleis<polis> déka<deka> treîs<treis> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[19007,"Ain<Ain> kaì<kai> Remmōn<Remmōn> kaì<kai> Ether<Ether> kaì<kai> Asan<Asan> póleis<polis> téssares<tessares> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[19008,"`ai<`o> perikùklōj<perikuklōj> tôn<`o> póleōn<polis> toùtōn<`outos> `éōs<`eōs> Baalethbērramōth<Baalethbērramōth> poreuoménōn<poreuomai> Iameth<Iameth> katà<kata> lìba<lips> `aùtē<`outos> `ē<`o> klēronomìa<klēronomia> fulês<fulē> `uiôn<`uios> Sumeōn<Sumeōn> katà<kata> dèmous<dēmos> autôn<autos> "],
[19009,"apó<apo> toû<`o> klèrou<klēros> Iouda<Ioudas> `ē<`o> klēronomìa<klēronomia> fulês<fulē> `uiôn<`uios> Sumeōn<Sumeōn> `óti<`oti> egenèthē<ginomai> merìs<meris> `uiôn<`uios> Iouda<Ioudas> meìzōn<megas> tês<`o> autôn<autos> kaì<kai> eklēronómēsan<klēronomeō> `oi<`o> `uioì<`uios> Sumeōn<Sumeōn> en<en> mésōj<mesos> toû<`o> klèrou<klēros> autôn<autos> "],
[19010,"kaì<kai> exêlthen<exerchomai> `o<`o> klêros<klēros> `o<`o> trìtos<tritos> tôj<`o> Zaboulōn<Zaboulōn> katà<kata> dèmous<dēmos> autôn<autos> kaì<kai> éstai<eimi> tà<`o> `ória<`orion> tês<`o> klēronomìas<klēronomia> autôn<autos> `éōs<`eōs> Sarid<Sarid> "],
[19011,"tà<`o> `ória<`orion> autôn<autos> `ē<`o> thàlassa<thalassa> kaì<kai> Marala<Marala> kaì<kai> sunàpsei<sunaptō> epì<epi> Dabasthai<Dabasthai> eis<eis> tèn<`o> fàragga<faragx> `è<`os> estin<eimi> katà<kata> prósōpon<prosōpon> Ieknam<Ieknam> "],
[19012,"kaì<kai> anastrépsei<anastrefō> apó<apo> Sarid<Sarid> ex<ek> enantìas<enantios> apó<apo> anatolôn<anatolē> Sams<Sams> epì<epi> tà<`o> `ória<`orion> Chasalōth<Chasalōth> Thabōr<Thabōr> kaì<kai> dieleùsetai<dierchomai> epì<epi> Dabrath<Dabrath> kaì<kai> prosanabèsetai<prosanabainō> epì<epi> Iafagai<Iafagai> "],
[19013,"kaì<kai> ekeîthen<ekeithen> perieleùsetai<perierchomai> ex<ek> enantìas<enantios> ep'<epi> anatolàs<anatolē> epì<epi> Geththa<Geththa> epì<epi> pólin<polis> Kasim<Kasim> kaì<kai> dieleùsetai<dierchomai> epì<epi> Remmōn<Remmōn> Ammatharim<Ammatharim> Annoua<Annoua> "],
[19014,"kaì<kai> perieleùsetai<perierchomai> epì<epi> tà<`o> `ória<`orion> borrâ<boreas> epì<epi> Ennathōth<Ennathōth> kaì<kai> éstai<eimi> `ē<`o> diéxodos<diexodos> autôn<autos> epì<epi> Gaiiefthaēl<Gaiiefthaēl> "],
[19015,"kaì<kai> Kattath<Kattath> kaì<kai> Naalōl<Naalōl> kaì<kai> Semrōn<Semrōn> kaì<kai> Iadēla<Iadēla> kaì<kai> Baithleem<Baithleem> "],
[19016,"`aùtē<`outos> `ē<`o> klēronomìa<klēronomia> tês<`o> fulês<fulē> `uiôn<`uios> Zaboulōn<Zaboulōn> katà<kata> dèmous<dēmos> autôn<autos> `ai<`o> póleis<polis> `aûtai<`outos> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[19017,"kaì<kai> tôj<`o> Issachar<Issachar> exêlthen<exerchomai> `o<`o> klêros<klēros> `o<`o> tétartos<tetartos> "],
[19018,"kaì<kai> egenèthē<ginomai> tà<`o> `ória<`orion> autôn<autos> Iezrael<Iezrael> kaì<kai> Achaselōth<Achaselōth> kaì<kai> Sounam<Sounam> "],
[19019,"kaì<kai> Afera:im<Aferaim> kaì<kai> Sian<Sian> kaì<kai> Renath<Renath> kaì<kai> Anareth<Anareth> "],
[19020,"kaì<kai> Rabbōth<Rabbōth> kaì<kai> Kesiōn<Kesiōn> kaì<kai> Aeme<Aeme> "],
[19021,"kaì<kai> Ramath<Ramath> kaì<kai> Ēngannim<Ēngannim> kaì<kai> Ēnadda<Ēnadda> kaì<kai> Baithfasēs<Baithfasēs> "],
[19022,"kaì<kai> sunàpsei<sunaptō> tà<`o> `ória<`orion> epì<epi> Thabōth<Thabōth> kaì<kai> epì<epi> Sasima<Sasima> katà<kata> thàlassan<thalassa> kaì<kai> Baithsmas<Baithsmas> kaì<kai> éstai<eimi> `ē<`o> diéxodos<diexodos> tôn<`o> `orìōn<`orion> autôn<autos> `o<`o> Iordànēs<Iordanēs> "],
[19023,"`aùtē<`outos> `ē<`o> klēronomìa<klēronomia> fulês<fulē> `uiôn<`uios> Issachar<Issachar> katà<kata> dèmous<dēmos> autôn<autos> `ai<`o> póleis<polis> kaì<kai> `ai<`o> epaùleis<epaulis> autôn<autos> "],
[19024,"kaì<kai> exêlthen<exerchomai> `o<`o> klêros<klēros> `o<`o> pémptos<pemptos> Asēr<Asēr> katà<kata> dèmous<dēmos> autôn<autos> "],
[19025,"kaì<kai> egenèthē<ginomai> tà<`o> `ória<`orion> autôn<autos> Chelkath<Chelkath> kaì<kai> Ooli<Ooli> kaì<kai> Batne<Batne> kaì<kai> Achsaf<Achsaf> "],
[19026,"kaì<kai> Amad<Amad> kaì<kai> Masal<Masal> kaì<kai> sunàpsei<sunaptō> tôj<`o> Karmèlōj<Karmēlos> katà<kata> thàlassan<thalassa> kaì<kai> tôj<`o> Siōr<Siōr> kaì<kai> Labanath<Labanath> "],
[19027,"kaì<kai> epistrépsei<epistrefō> ap'<apo> anatolôn<anatolē> `ēlìou<`ēlios> Bēthdagōn<Bēthdagōn> kaì<kai> sunàpsei<sunaptō> tôj<`o> Zaboulōn<Zaboulōn> kaì<kai> en<en> Gai<Gai> Iefthaēl<Iefthaēl> katà<kata> borrân<boreas> kaì<kai> eiseleùsetai<eiserchomai> tà<`o> `ória<`orion> Safthabēthaemek<Safthabēthaemek> kaì<kai> poreùsetai<poreuomai> tó<`o> methórion<methorion> Aniēl<Aniēl> kaì<kai> dieleùsetai<dierchomai> eis<eis> Chabōl<Chabōl> apó<apo> aristerôn<aristeros> "],
[19028,"kaì<kai> Achran<Achran> kaì<kai> Roōb<Roōb> kaì<kai> Amōn<Amōn> kaì<kai> Kana<Kana> `éōs<`eōs> Sidônos<Sidōn> tês<`o> megàlēs<megas> "],
[19029,"kaì<kai> anastrépsei<anastrefō> tà<`o> `ória<`orion> eis<eis> Rama<Rama> kaì<kai> `éōs<`eōs> póleōs<polis> ochuròmatos<ochurōma> tôn<`o> Turìōn<Turios> kaì<kai> anastrépsei<anastrefō> tà<`o> `ória<`orion> epì<epi> Ōsa<Ōsa> kaì<kai> éstai<eimi> `ē<`o> diéxodos<diexodos> autoû<autos> `ē<`o> thàlassa<thalassa> kaì<kai> apó<apo> toû<`o> schoinìsmatos<schoinisma> Achzif<Achzif> "],
[19030,"kaì<kai> Amma<Amma> kaì<kai> Afek<Afek> kaì<kai> Raōb<Raōb> póleis<polis> eìkosi<eikosi> dùo<duo> "],
[19031,"`aùtē<`outos> `ē<`o> klēronomìa<klēronomia> fulês<fulē> `uiôn<`uios> Asēr<Asēr> katà<kata> dèmous<dēmos> autôn<autos> póleis<polis> autôn<autos> kaì<kai> `ai<`o> kômai<kōmē> autôn<autos> "],
[19032,"kaì<kai> tôj<`o> Nefthali<Nefthali> exêlthen<exerchomai> `o<`o> klêros<klēros> `o<`o> `éktos<`ektos> "],
[19033,"kaì<kai> egéneto<ginomai> tà<`o> `ória<`orion> autôn<autos> Meelef<Meelef> kaì<kai> Maēlōn<Maēlōn> kaì<kai> Besenanim<Besenanim> kaì<kai> Armai<Armai> kaì<kai> Nakeb<Nakeb> kaì<kai> Iabnēl<Iabnēl> `éōs<`eōs> Lakou<Lakos> kaì<kai> egenèthēsan<ginomai> `ai<`o> diéxodoi<diexodos> autoû<autos> `o<`o> Iordànēs<Iordanēs> "],
[19034,"kaì<kai> epistrépsei<epistrefō> tà<`o> `ória<`orion> epì<epi> thàlassan<thalassa> Azanōth<Azanōth> Thabōr<Thabōr> kaì<kai> dieleùsetai<dierchomai> ekeîthen<ekeithen> eis<eis> Ikōk<Ikōk> kaì<kai> sunàpsei<sunaptō> tôj<`o> Zaboulōn<Zaboulōn> apó<apo> nótou<notos> kaì<kai> tôj<`o> Asēr<Asēr> sunàpsei<sunaptō> katà<kata> thàlassan<thalassa> kaì<kai> `o<`o> Iordànēs<Iordanēs> ap'<apo> anatolôn<anatolē> `ēlìou<`ēlios> "],
[19035,"kaì<kai> póleis<polis> teichèreis<teichērēs> tôn<`o> Turìōn<Turios> Tùros<Turos> kaì<kai> Amath<Amath> kaì<kai> Rekkath<Rekkath> kaì<kai> Chenereth<Chenereth> "],
[19036,"kaì<kai> Adami<Adami> kaì<kai> Rama<Rama> kaì<kai> Asōr<Asōr> "],
[19037,"kaì<kai> Kedes<Kedes> kaì<kai> Edra:i<Edrai> kaì<kai> Pēgè<pēgē> Asor<Asor> "],
[19038,"kaì<kai> Iariōn<Iariōn> kaì<kai> Magdaliēl<Magdaliēl> Ōram<Ōram> kaì<kai> Baithanath<Baithanath> kaì<kai> Thasmous<Thasmous> póleis<polis> déka<deka> ennéa<ennea> "],
[19039,"`aùtē<`outos> `ē<`o> klēronomìa<klēronomia> fulês<fulē> `uiôn<`uios> Nefthali<Nefthali> "],
[19040,"kaì<kai> tôj<`o> Dan<Dan> exêlthen<exerchomai> `o<`o> klêros<klēros> `o<`o> `ébdomos<`ebdomos> "],
[19041,"kaì<kai> egenèthē<ginomai> tà<`o> `ória<`orion> autôn<autos> Saraa<Saraa> kaì<kai> Esthaol<Esthaol> kaì<kai> pólis<polis> Sames<Sames> "],
[19042,"kaì<kai> Salabin<Salabin> kaì<kai> Iaalōn<Iaalōn> kaì<kai> Iethla<Iethla> "],
[19043,"kaì<kai> Ailōn<Ailōn> kaì<kai> Thamna<Thamna> kaì<kai> Akkarōn<Akkarōn> "],
[19044,"kaì<kai> Elthekō<Elthekō> kaì<kai> Gabathōn<Gabathōn> kaì<kai> Baalōn<Baalōn> "],
[19045,"kaì<kai> Iouth<Iouth> kaì<kai> Banēbarak<Banēbarak> kaì<kai> Gethremmōn<Gethremmōn> "]
])
