Bib.ret([
[1001,"ōjdè<ōjdē> Mōuséōs<Mōusēs> en<en> têj<`o> exódōj<exodos> àjsōmen<ajdō> tôj<`o> kurìōj<kurios> endóxōs<endoxōs> gàr<gar> dedóxastai<doxazō> `ìppon<`ippos> kaì<kai> anabàtēn<anabatēs> érripsen<`riptō> eis<eis> thàlassan<thalassa> "],
[1002,"boēthós<boēthos> kaì<kai> skepastès<skepastēs> egénetó<ginomai> moi<egō> eis<eis> sōtērìan<sōtēria> `oûtós<`outos> mou<egō> theós<theos> kaì<kai> doxàsō<doxazō> autón<autos> theós<theos> toû<`o> patrós<patēr> mou<egō> kaì<kai> `upsòsō<`upsoō> autón<autos> "],
[1003,"kùrios<kurios> suntrìbōn<suntribō> polémous<polemos> kùrios<kurios> ónoma<onoma> autôj<autos> "],
[1004,"`àrmata<`arma> Faraō<Faraō> kaì<kai> tèn<`o> dùnamin<dunamis> autoû<autos> érripsen<`riptō> eis<eis> thàlassan<thalassa> epiléktous<epilektos> anabàtas<anabatēs> tristàtas<tristatēs> katepóntisen<katapontizō> en<en> eruthrâj<eruthros> thalàssēj<thalassa> "],
[1005,"póntōj<Pontos> ekàlupsen<kaluptō> autoùs<autos> katédusan<kataduō> eis<eis> buthón<buthos> `ōseì<`ōsei> lìthos<lithos> "],
[1006,"`ē<`o> dexià<dexios> sou<su> kùrie<kurios> dedóxastai<doxazō> en<en> ischùi<ischus> `ē<`o> dexià<dexios> sou<su> cheìr<cheir> kùrie<kurios> éthrausen<thrauō> echthroùs<echthros> "],
[1007,"kaì<kai> tôj<`o> plèthei<plēthos> tês<`o> dóxēs<doxa> sou<su> sunétripsas<suntribō> toùs<`o> `upenantìous<`upenantios> apésteilas<apostellō> tèn<`o> orgèn<orgē> sou<su> kaì<kai> katéfagen<katesthiō> autoùs<autos> `ōs<`ōs> kalàmēn<kalamē> "],
[1008,"kaì<kai> dià<dia> pneùmatos<pneuma> toû<`o> thumoû<thumos> sou<su> diéstē<diistēmi> tó<`o> `ùdōr<`udōr> epàgē<pēgnumi> `ōseì<`ōsei> teîchos<teichos> tà<`o> `ùdata<`udōr> epàgē<pēgnumi> tà<`o> kùmata<kuma> en<en> mésōj<mesos> tês<`o> thalàssēs<thalassa> "],
[1009,"eîpen<legō> `o<`o> echthrós<echthros> diòxas<diōkō> katalèmpsomai<katalambanō> meriô<merizō> skûla<skulon> emplèsō<empiplēmi> psuchèn<psuchē> mou<egō> anelô<anaireō> têj<`o> machaìrēj<machaira> mou<egō> kurieùsei<kurieuō> `ē<`o> cheìr<cheir> mou<egō> "],
[1010,"apésteilas<apostellō> tó<`o> pneûmà<pneuma> sou<su> ekàlupsen<kaluptō> autoùs<autos> thàlassa<thalassa> édusan<duō> `ōseì<`ōsei> mólibos<molibos> en<en> `ùdati<`udōr> sfodrôj<sfodros> "],
[1011,"tìs<tis> `ómoiós<`omoios> soi<su> en<en> theoîs<theos> kùrie<kurios> tìs<tis> `ómoiós<`omoios> soi<su> dedoxasménos<doxazō> en<en> `agìois<`agios> thaumastós<thaumastos> en<en> dóxais<doxa> poiôn<poieō> térata<teras> "],
[1012,"exéteinas<ekteinō> tèn<`o> dexiàn<dexios> sou<su> kaì<kai> katépien<katapinō> autoùs<autos> `ē<`o> gê<gē> "],
[1013,"`ōdègēsas<`odēgeō> têj<`o> dikaiosùnēj<dikaiosunē> sou<su> tón<`o> laón<laos> sou<su> toûton<`outos> `ón<`os> elutròsō<lutroō> parekàlesas<parakaleō> têj<`o> ischùi<ischus> sou<su> eis<eis> katàluma<kataluma> `àgión<`agios> sou<su> "],
[1014,"èkousan<akouō> éthnē<ethnos> kaì<kai> ōrgìsthēsan<orgizō> ōdînes<ōdin> élabon<lambanō> katoikoûntas<katoikeō> Fulistiim<Fulistiim> "],
[1015,"tóte<tote> éspeusan<speudō> `ēgemónes<`ēgemōn> Edōm<Edōm> kaì<kai> àrchontes<archōn> Mōabitôn<Mōabitēs> élaben<lambanō> autoùs<autos> trómos<tromos> etàkēsan<tēkō> pàntes<pas> `oi<`o> katoikoûntes<katoikeō> Chanaan<Chanaan> "],
[1016,"epipésoi<epipiptō> ep'<epi> autoùs<autos> fóbos<fobos> kaì<kai> trómos<tromos> megéthei<megethos> brachìonós<brachiōn> sou<su> apolithōthètōsan<apolithoomai> `éōs<`eōs> àn<an> parélthēj<parerchomai> `o<`o> laós<laos> sou<su> kùrie<kurios> `éōs<`eōs> àn<an> parélthēj<parerchomai> `o<`o> laós<laos> sou<su> `oûtos<`outos> `ón<`os> ektèsō<ktaomai> "],
[1017,"eisagagòn<eisagō> katafùteuson<katafuteuō> autoùs<autos> eis<eis> óros<oros> klēronomìas<klēronomia> sou<su> eis<eis> `étoimon<`etoimos> katoikētèrión<katoikētērion> sou<su> `ó<`os> kateirgàsō<katergazomai> kùrie<kurios> `agìasma<`agiasma> kùrie<kurios> `ó<`os> `ētoìmasan<`etoimazō> `ai<`o> cheîrés<cheir> sou<su> "],
[1018,"kùrios<kurios> basileùōn<basileuō> tón<`o> aiôna<aiōn> kaì<kai> ep'<epi> aiôna<aiōn> kaì<kai> éti<eti> "],
[1019,"`óti<`oti> eisêlthen<eiserchomai> `ìppos<`ippos> Faraō<Faraō> sùn<sun> `àrmasin<`arma> kaì<kai> anabàtais<anabatēs> eis<eis> thàlassan<thalassa> kaì<kai> epègagen<epagō> ep'<epi> autoùs<autos> kùrios<kurios> tó<`o> `ùdōr<`udōr> tês<`o> thalàssēs<thalassa> `oi<`o> dé<de> `uioì<`uios> Israēl<Israēl> eporeùthēsan<poreuomai> dià<dia> xērâs<xēros> en<en> mésōj<mesos> tês<`o> thalàssēs<thalassa> "],
[2001,"[ōjdè<ōjdē> Mōuséōs<Mōusēs> en<en> tôj<`o> Deuteronomìōj]<Deuteronomion> próseche<prosechō> ourané<ouranos> kaì<kai> lalèsō<laleō> kaì<kai> akouétō<akouō> gê<gē> `rèmata<`rēma> ek<ek> stómatós<stoma> mou<egō> "],
[2002,"prosdokàsthō<prosdokaō> `ōs<`ōs> `uetós<`uetos> tó<`o> apófthegmà<apofthegma> mou<egō> kaì<kai> katabètō<katabainō> `ōs<`ōs> drósos<drosos> tà<`o> `rèmatà<`rēma> mou<egō> `ōseì<`ōsei> ómbros<ombros> ep'<epi> àgrōstin<agrōstis> kaì<kai> `ōseì<`ōsei> nifetós<nifetos> epì<epi> chórton<chortos> "],
[2003,"`óti<`oti> ónoma<onoma> kurìou<kurios> ekàlesa<kaleō> dóte<didōmi> megalōsùnēn<megalōsunē> tôj<`o> theôj<theos> `ēmôn<egō> "],
[2004,"theós<theos> alēthinà<alēthinos> tà<`o> érga<ergon> autoû<autos> kaì<kai> pâsai<pas> `ai<`o> `odoì<`odos> autoû<autos> krìsis<krisis> theós<theos> pistós<pistos> kaì<kai> ouk<ou'> éstin<eimi> adikìa<adikia> dìkaios<dikaios> kaì<kai> `ósios<`osios> kùrios<kurios> "],
[2005,"`ēmàrtosan<`amartanō> ouk<ou'> autôj<autos> tékna<teknon> mōmētà<mōmētos> geneà<genea> skolià<skolios> kaì<kai> diestramménē<diastrefō> "],
[2006,"taûta<`outos> kurìōj<kurios> antapodìdote<antapodidōmi> `oùtō<`outōs> laós<laos> mōrós<mōros> kaì<kai> ouchì<ouchi> sofós<sofos> ouk<ou'> autós<autos> `oûtós<`outos> sou<su> patèr<patēr> ektèsató<ktaomai> se<su> kaì<kai> epoìēsén<poieō> se<su> kaì<kai> éktisén<ktizō> se<su> "],
[2007,"mnèsthēte<mimnējskomai> `ēméras<`ēmera> aiônos<aiōn> sùnete<suniēmi> étē<etos> geneâs<genea> geneôn<genea> eperòtēson<eperōtaō> tón<`o> patéra<patēr> sou<su> kaì<kai> anaggeleî<anaggellō> soi<su> toùs<`o> presbutérous<presbuteros> sou<su> kaì<kai> eroûsìn<legō> soi<su> "],
[2008,"`óte<`ote> diemérizen<diamerizō> `o<`o> `ùpsistos<`upsistos> éthnē<ethnos> `ōs<`ōs> diéspeiren<diaspeirō> `uioùs<`uios> Adam<Adam> éstēsen<`istēmi> `ória<`orion> ethnôn<ethnos> katà<kata> arithmón<arithmos> aggélōn<aggelos> theoû<theos> "],
[2009,"kaì<kai> egenèthē<ginomai> merìs<meris> kurìou<kurios> laós<laos> autoû<autos> Iakōb<Iakōb> schoìnisma<schoinisma> klēronomìas<klēronomia> autoû<autos> Israēl<Israēl> "],
[2010,"autàrkēsen<autarkeō> autón<autos> en<en> têj<`o> erèmōj<erēmos> en<en> dìpsei<dipsos> kaùmatos<kauma> en<en> anùdrōj<anudros> ekùklōsen<kukloō> autón<autos> kaì<kai> epaìdeusen<paideuō> autón<autos> kaì<kai> diefùlaxen<diafulassō> autón<autos> `ōs<`ōs> kórēn<korē> ofthalmoû<ofthalmos> "],
[2011,"`ōs<`ōs> aetós<aetos> skepàsai<skepazō> nossiàn<nossia> autoû<autos> kaì<kai> epì<epi> toîs<`o> neossoîs<neossos> autoû<autos> epepóthēsen<epipotheō> dieìs<diiēmi> tàs<`o> ptérugas<pterux> autoû<autos> edéxato<dechomai> autoùs<autos> kaì<kai> anélaben<analambanō> autoùs<autos> epì<epi> tôn<`o> metafrénōn<metafrenon> autoû<autos> "],
[2012,"kùrios<kurios> mónos<monos> êgen<agō> autoùs<autos> kaì<kai> ouk<ou'> ên<eimi> met'<meta> autôn<autos> theós<theos> allótrios<allotrios> "],
[2013,"anebìbasen<anabibazō> autoùs<autos> epì<epi> tèn<`o> ischùn<ischus> tês<`o> gês<gē> epsòmisen<psōmizō> autoùs<autos> genèmata<genēma> agrôn<agros> ethèlasan<thēlazō> méli<meli> ek<ek> pétras<petra> kaì<kai> élaion<elaion> ek<ek> stereâs<stereos> pétras<petra> "],
[2014,"boùturon<bouturon> boôn<bous> kaì<kai> gàla<gala> probàtōn<probaton> metà<meta> stéatos<stear> arnôn<arnos> kaì<kai> kriôn<krios> `uiôn<`uios> taùrōn<tauros> kaì<kai> tràgōn<tragos> metà<meta> stéatos<stear> nefrôn<nefros> puroû<puros> kaì<kai> `aîma<`aima> stafulês<stafulē> épion<pinō> oînon<oinos> "],
[2015,"kaì<kai> éfagen<esthiō> Iakōb<Iakōb> kaì<kai> eneplèsthē<empiplēmi> kaì<kai> apelàktisen<apolaktizō> `o<`o> ēgapēménos<agapaō> elipànthē<lipainō> epachùnthē<pachunō> eplatùnthē<platunō> kaì<kai> egkatélipen<egkataleipō> theón<theos> tón<`o> poièsanta<poieō> autón<autos> kaì<kai> apéstē<afistēmi> apó<apo> theoû<theos> sōtêros<sōtēr> autoû<autos> "],
[2016,"paròxunàn<paroxunō> me<egō> ep'<epi> allotrìois<allotrios> en<en> bdelùgmasin<bdelugma> autôn<autos> exepìkranàn<ekpikrainō> me<egō> "],
[2017,"éthusan<thuō> daimonìois<daimonion> kaì<kai> ou'<ou'> theôj<theos> theoîs<theos> `oîs<`os> ouk<ou'> èjdeisan<oida> kainoì<kainos> kaì<kai> prósfatoi<prosfatos> `èkasin<`ēkō> `oùs<`os> ouk<ou'> èjdeisan<oida> `oi<`o> patéres<patēr> autôn<autos> "],
[2018,"theón<theos> tón<`o> gennèsantà<gennaō> se<su> egkatélipes<egkataleipō> kaì<kai> epelàthou<epilanthanomai> theoû<theos> toû<`o> tréfontós<trefō> se<su> "],
[2019,"kaì<kai> eîden<`oraō> kùrios<kurios> kaì<kai> ezèlōsen<zēloō> kaì<kai> parōxùnthē<paroxunō> di'<dia> orgèn<orgē> `uiôn<`uios> autoû<autos> kaì<kai> thugatérōn<thugatēr> "],
[2020,"kaì<kai> eîpen<legō> apostrépsō<apostrefō> tó<`o> prósōpón<prosōpon> mou<egō> ap'<apo> autôn<autos> kaì<kai> deìxō<deiknumi> tì<tis> éstai<eimi> autoîs<autos> ep'<epi> eschàtōn<eschatos> `óti<`oti> geneà<genea> exestramménē<ekstrefō> estìn<eimi> `uioì<`uios> `oîs<`os> ouk<ou'> éstin<eimi> pìstis<pistis> en<en> autoîs<autos> "],
[2021,"autoì<autos> parezèlōsàn<parazēloō> me<egō> ep'<epi> ou'<ou'> theôj<theos> paròrgisàn<parorgizō> me<egō> en<en> toîs<`o> eidòlois<eidōlon> autôn<autos> kagò<kai&egō> parazēlòsō<parazēloō> autoùs<autos> ep'<epi> ouk<ou'> éthnei<ethnos> ep'<epi> éthnei<ethnos> asunétōj<asunetos> parorgiô<parorgizō> autoùs<autos> "],
[2022,"`óti<`oti> pûr<pur> ekkékautai<ekkaiō> ek<ek> toû<`o> thumoû<thumos> mou<egō> kauthèsetai<kaiō> `éōs<`eōs> `àjdou<`ajdēs> kàtō<katō> katafàgetai<katesthiō> gên<gē> kaì<kai> tà<`o> genèmata<genēma> autês<autos> fléxei<flegō> themélia<themelion> oréōn<oros> "],
[2023,"sunàxō<sunagō> eis<eis> autoùs<autos> kakà<kakos> kaì<kai> tà<`o> bélē<belos> mou<egō> suntelésō<sunteleō> eis<eis> autoùs<autos> "],
[2024,"tēkómenoi<tēkō> limôj<limos> kaì<kai> bròsei<brōsis> ornéōn<orneon> kaì<kai> opisthótonos<opisthotonos> anìatos<aniatos> odóntas<odous> thērìōn<thērion> exapostelô<exapostellō> eis<eis> autoùs<autos> metà<meta> thumoû<thumos> suróntōn<surō> epì<epi> gês<gē> "],
[2025,"éxōthen<exōthen> ateknòsei<ateknoō> autoùs<autos> màchaira<machaira> kaì<kai> ek<ek> tôn<`o> tamieìōn<tamieion> fóbos<fobos> neanìskos<neaniskos> sùn<sun> parthénōj<parthenos> thēlàzōn<thēlazō> metà<meta> kathestēkótos<kathistēmi> presbutérou<presbuteros> "],
[2026,"eîpa<legō> diasperô<diaspeirō> autoùs<autos> paùsō<pauō> dè<dē> ex<ek> anthròpōn<anthrōpos> tó<`o> mnēmósunon<mnēmosunon> autôn<autos> "],
[2027,"ei'<ei'> mè<mē> di'<dia> orgèn<orgē> echthrôn<echthros> `ìna<`ina> mè<mē> makrochronìsōsin<makrochronizō> kaì<kai> `ìna<`ina> mè<mē> sunepithôntai<sunepitithēmi> `oi<`o> `upenantìoi<`upenantios> mè<mē> eìpōsin<legō> `ē<`o> cheìr<cheir> `ēmôn<egō> `upsēlè<`upsēlos> kaì<kai> ouchì<ouchi> kùrios<kurios> epoìēsen<poieō> taûta<`outos> pànta<pas> "],
[2028,"`óti<`oti> éthnos<ethnos> apolōlekós<apollumi> boulèn<boulē> estin<eimi> kaì<kai> ouk<ou'> éstin<eimi> en<en> autoîs<autos> epistèmē<epistēmē> "],
[2029,"ouk<ou'> efrónēsan<froneō> suniénai<suniēmi> taûta<`outos> katadexàsthōsan<katadechomai> eis<eis> tón<`o> epiónta<epeimi-2> chrónon<chronos> "],
[2030,"pôs<pôs> diòxetai<diōkō> `eîs<`eis> chilìous<chilioi> kaì<kai> dùo<duo> metakinèsousin<metakineō> muriàdas<murias> ei'<ei'> mè<mē> `o<`o> theós<theos> apédoto<apodidōmi> autoùs<autos> kaì<kai> `o<`o> kùrios<kurios> parédōken<paradidōmi> autoùs<autos> "],
[2031,"ou'<ou'> gàr<gar> eisin<eimi> `oi<`o> theoì<theos> autôn<autos> `ōs<`ōs> `o<`o> theós<theos> `ēmôn<egō> `oi<`o> dé<de> echthroì<echthros> `ēmôn<egō> anóētoi<anoētos> "],
[2032,"ek<ek> gàr<gar> ampélou<ampelos> Sodomōn<Sodoma> `ē<`o> àmpelos<ampelos> autôn<autos> kaì<kai> `ē<`o> klēmatìs<klēmatis> autôn<autos> ek<ek> Gomorras<Gomorra> `ē<`o> stafulè<stafulē> autôn<autos> stafulè<stafulē> cholês<cholē> bótrus<botrus> pikrìas<pikria> autoîs<autos> "],
[2033,"thumós<thumos> drakóntōn<drakōn> `o<`o> oînos<oinos> autôn<autos> kaì<kai> thumós<thumos> aspìdōn<aspis> anìatos<aniatos> "],
[2034,"ouk<ou'> idoù<idou> taûta<`outos> pànta<pas> sunêktai<sunagō> par'<para> emoì<egō> kaì<kai> esfràgistai<sfragizō> en<en> toîs<`o> thēsauroîs<thēsauros> mou<egō> "],
[2035,"en<en> `ēméraj<`ēmera> ekdikèseōs<ekdikēsis> antapodòsō<antapodidōmi> en<en> kairôj<kairos> `ótan<`otan> sfalêj<sfallō> `o<`o> poùs<pous> autôn<autos> `óti<`oti> eggùs<eggus> `ēméra<`ēmera> apōleìas<apōleia> autôn<autos> kaì<kai> pàrestin<pareimi> `étoima<`etoimos> `umîn<su> "],
[2036,"`óti<`oti> krineî<krinō> kùrios<kurios> tón<`o> laón<laos> autoû<autos> kaì<kai> epì<epi> toîs<`o> doùlois<doulos> autoû<autos> paraklēthèsetai<parakaleō> eîden<`oraō> gàr<gar> autoùs<autos> paraleluménous<paraluō> kaì<kai> ekleloipótas<ekleipō> en<en> epagōgêj<epagōgē> kaì<kai> pareiménous<pariēmi> "],
[2037,"kaì<kai> eîpen<legō> kùrios<kurios> poû<poû> eisin<eimi> `oi<`o> theoì<theos> autôn<autos> ef'<epi> `oîs<`os> epepoìtheisan<peithō> ep'<epi> autoîs<autos> "],
[2038,"`ôn<`os> tó<`o> stéar<stear> tôn<`o> thusiôn<thusia> autôn<autos> ēsthìete<esthiō> kaì<kai> epìnete<pinō> tón<`o> oînon<oinos> tôn<`o> spondôn<spondē> autôn<autos> anastètōsan<anistēmi> kaì<kai> boēthēsàtōsan<boētheō> `umîn<su> kaì<kai> genēthètōsan<ginomai> `umîn<su> skepastaì<skepastēs> "],
[2039,"ìdete<`oraō> ìdete<`oraō> `óti<`oti> egò<egō> eimi<eimi> kaì<kai> ouk<ou'> éstin<eimi> theós<theos> plèn<plēn> emoû<egō> egò<egō> apoktenô<apokteinō> kaì<kai> zên<zaō> poièsō<poieō> patàxō<patassō> kagò<kai&egō> iàsomai<iaomai> kaì<kai> ouk<ou'> éstin<eimi> `ós<`os> exeleîtai<exaireō> ek<ek> tôn<`o> cheirôn<cheir> mou<egō> "],
[2040,"`óti<`oti> arô<airō> eis<eis> tón<`o> ouranón<ouranos> tèn<`o> cheîrà<cheir> mou<egō> kaì<kai> omoûmai<omnumi> têj<`o> dexiâj<dexios> mou<egō> kaì<kai> erô<legō> zô<zaō> egò<egō> eis<eis> tón<`o> aiôna<aiōn> "],
[2041,"`óti<`oti> paroxunô<paroxunō> `ōs<`ōs> astrapèn<astrapē> tèn<`o> màchairàn<machaira> mou<egō> kaì<kai> anthéxetai<antechō> krìmatos<krima> `ē<`o> cheìr<cheir> mou<egō> kaì<kai> antapodòsō<antapodidōmi> dìkēn<dikē> toîs<`o> echthroîs<echthros> kaì<kai> toîs<`o> misoûsìn<miseō> me<egō> antapodòsō<antapodidōmi> "],
[2042,"methùsō<methuskō> tà<`o> bélē<belos> mou<egō> af'<apo> `aìmatos<`aima> kaì<kai> `ē<`o> màchairà<machaira> mou<egō> katafàgetai<katesthiō> kréa<kreas> af'<apo> `aìmatos<`aima> traumatiôn<traumatias> kaì<kai> aichmalōsìas<aichmalōsia> apó<apo> kefalês<kefalē> archóntōn<archōn> ethnôn<ethnos> "],
[2043,"eufrànthēte<eufrainō> ouranoì<ouranos> `àma<`ama> autôj<autos> kaì<kai> proskunēsàtōsan<proskuneō> autôj<autos> pàntes<pas> `oi<`o> àggeloi<aggelos> theoû<theos> eufrànthēte<eufrainō> éthnē<ethnos> metà<meta> toû<`o> laoû<laos> autoû<autos> kaì<kai> enischusàtōsan<enischuō> autôj<autos> pàntes<pas> `uioì<`uios> theoû<theos> `óti<`oti> tó<`o> `aîma<`aima> tôn<`o> `uiôn<`uios> autoû<autos> ekdikeîtai<ekdikeō> kaì<kai> ekdikèsei<ekdikeō> kaì<kai> antapodòsei<antapodidōmi> dìkēn<dikē> toîs<`o> echthroîs<echthros> kaì<kai> toîs<`o> misoûsin<miseō> antapodòsei<antapodidōmi> kaì<kai> ekkatharieî<ekkatharizō> kùrios<kurios> tèn<`o> gên<gē> toû<`o> laoû<laos> autoû<autos> "],
[3001,"[proseuchè<proseuchē> Annas<`Anna> mētrós<mētēr> Samouēl]<Samouēl> estereòthē<stereoō> `ē<`o> kardìa<kardia> mou<egō> en<en> kurìōj<kurios> `upsòthē<`upsoō> kéras<keras> mou<egō> en<en> theôj<theos> mou<egō> eplatùnthē<platunō> ep'<epi> echthroùs<echthros> mou<egō> tó<`o> stóma<stoma> mou<egō> ēufrànthēn<eufrainō> en<en> sōtērìaj<sōtēria> sou<su> "],
[3002,"`óti<`oti> ouk<ou'> éstin<eimi> `àgios<`agios> `ōs<`ōs> kùrios<kurios> kaì<kai> ouk<ou'> éstin<eimi> dìkaios<dikaios> `ōs<`ōs> `o<`o> theós<theos> `ēmôn<egō> ouk<ou'> éstin<eimi> `àgios<`agios> plèn<plēn> soû<su> "],
[3003,"mè<mē> kauchâsthe<kauchaomai> kaì<kai> mè<mē> laleîte<laleō> `upsēlà<`upsēlos> mēdé<mēde> exelthàtō<exerchomai> megalorēmosùnē<megalorrēmosunē> ek<ek> toû<`o> stómatos<stoma> `umôn<su> `óti<`oti> theós<theos> gnòseōn<gnōsis> kùrios<kurios> kaì<kai> theós<theos> `etoimàzon<`etoimazō> epitēdeùmata<epitēdeuma> autoû<autos> "],
[3004,"tóxon<toxon> dunatôn<dunatos> ēsthénēsen<astheneō> kaì<kai> asthenoûntes<astheneō> periezòsanto<perizōnnumi> dùnamin<dunamis> "],
[3005,"plèreis<plērēs> àrtōn<àrtos> ēlattòthēsan<elattoō> kaì<kai> `oi<`o> peinôntes<peinaō> parêkan<pariēmi> gên<gē> `óti<`oti> steîra<steira> éteken<tiktō> `eptà<`epta> kaì<kai> `ē<`o> pollè<polus> en<en> téknois<teknon> ēsthénēsen<astheneō> "],
[3006,"kùrios<kurios> thanatoî<thanatoō> kaì<kai> zōogoneî<zōjogoneō> katàgei<katagō> eis<eis> `àjdou<`ajdēs> kaì<kai> anàgei<anagō> "],
[3007,"kùrios<kurios> ptōchìzei<ptōchizō> kaì<kai> ploutìzei<ploutizō> tapeinoî<tapeinoō> kaì<kai> anupsoî<anupsoō> "],
[3008,"anistâj<anistēmi> apó<apo> gês<gē> pénēta<penēs> kaì<kai> apó<apo> koprìas<kopria> egeìrei<egeirō> ptōchón<ptōchos> toû<`o> kathìsai<kathizō> autón<autos> metà<meta> dunastôn<dunastēs> laoû<laos> kaì<kai> thrónon<thronos> dóxēs<doxa> kataklēronomôn<kataklēronomeō> autoîs<autos> "],
[3009,"didoùs<didōmi> euchèn<euchē> tôj<`o> euchoménōj<euchomai> kaì<kai> eulógēsen<eulogeō> étē<etos> dikaìou<dikaios> `óti<`oti> ouk<ou'> en<en> ischùi<ischus> dunatós<dunatos> anèr<anēr> "],
[3010,"kùrios<kurios> asthenê<asthenēs> poièsei<poieō> tón<`o> antìdikon<antidikos> autoû<autos> kùrios<kurios> `àgios<`agios> mè<mē> kauchàsthō<kauchaomai> `o<`o> sofós<sofos> en<en> têj<`o> sofìaj<sofia> autoû<autos> kaì<kai> mè<mē> kauchàsthō<kauchaomai> `o<`o> dunatós<dunatos> en<en> têj<`o> dunàmei<dunamis> autoû<autos> kaì<kai> mè<mē> kauchàsthō<kauchaomai> `o<`o> ploùsios<plousios> en<en> tôj<`o> ploùtōj<ploutos> autoû<autos> all'<alla> è<ē> en<en> toùtōj<`outos> kauchàsthō<kauchaomai> `o<`o> kauchòmenos<kauchaomai> sunìein<suniēmi> kaì<kai> ginòskein<ginōskō> tón<`o> kùrion<kurios> kaì<kai> poieîn<poieō> krìma<krima> kaì<kai> dikaiosùnēn<dikaiosunē> en<en> mésōj<mesos> tês<`o> gês<gē> kùrios<kurios> anébē<anabainō> eis<eis> ouranoùs<ouranos> kaì<kai> ebróntēsen<brontaō> autós<autos> krineî<krinō> àkra<akros> gês<gē> dìkaios<dikaios> òn<eimi> kaì<kai> dìdōsin<didōmi> ischùn<ischus> toîs<`o> basileûsin<basileus> `ēmôn<egō> kaì<kai> `upsòsei<`upsoō> kéras<keras> Christoû<Christos> autoû<autos> "],
[4001,"proseuchè<proseuchē> Ambakoum<Ambakoum> "],
[4002,"kùrie<kurios> eisakèkoa<eisakouō> tèn<`o> akoèn<akoē> sou<su> kaì<kai> efobèthēn<fobeō> katenóēsa<katanoeō> tà<`o> érga<ergon> sou<su> kaì<kai> exéstēn<existēmi> en<en> mésōj<mesos> dùo<duo> zòjōn<zōjon> gnōsthèsēj<ginōskō> en<en> tôj<`o> eggìzein<eggizō> tà<`o> étē<etos> epignōsthèsēj<epiginōskō> en<en> tôj<`o> pareînai<pareimi> tón<`o> kairón<kairos> anadeichthèsēj<anadeiknumi> en<en> tôj<`o> tarachthênai<tarassō> tèn<`o> psuchèn<psuchē> mou<egō> en<en> orgêj<orgē> eléous<eleos> mnēsthèsēj<mimnējskomai> "],
[4003,"`o<`o> theós<theos> ek<ek> Thaiman<Thaiman> `èxei<`ēkō> kaì<kai> `o<`o> `àgios<`agios> ex<ek> órous<oros> Faran<Faran> kataskìou<kataskios> daséōs<dasus> diàpsalma<diapsalma> ekàlupsen<kaluptō> ouranoùs<ouranos> `ē<`o> aretè<aretē> autoû<autos> kaì<kai> ainéseōs<ainesis> autoû<autos> plèrēs<plērēs> `ē<`o> gê<gē> "],
[4004,"kaì<kai> féggos<feggos> autoû<autos> `ōs<`ōs> fôs<fōs> éstai<eimi> kérata<keras> en<en> chersìn<cheir> autoû<autos> kaì<kai> étheto<tithēmi> agàpēsin<agapēsis> krataiàn<krataios> ischùos<ischus> autoû<autos> "],
[4005,"pró<pro> prosòpou<prosōpon> autoû<autos> poreùsetai<poreuomai> lógos<logos> kaì<kai> exeleùsetai<exerchomai> en<en> pedìlois<pedilon> `oi<`o> pódes<pous> autoû<autos> "],
[4006,"éstē<`istēmi> kaì<kai> esaleùthē<saleuō> `ē<`o> gê<gē> epéblepsen<epiblepō> kaì<kai> etàkē<tēkō> éthnē<ethnos> diethrùbē<diathruptō> tà<`o> órē<oros> bìaj<bia> etàkēsan<tēkō> bounoì<bounos> aiònioi<aiōnios> "],
[4007,"poreìas<poreia> aiōnìous<aiōnios> autoû<autos> antì<anti> kópōn<kopos> eîdon<`oraō> skēnòmata<skēnōma> Aithiópōn<Aithiops> ptoēthèsontai<ptoeō> kaì<kai> `ai<`o> skēnaì<skēnē> gês<gē> Madiam<Madiam> "],
[4008,"mè<mē> en<en> potamoîs<potamos> ōrgìsthēs<orgizō> kùrie<kurios> è<ē> en<en> potamoîs<potamos> `o<`o> thumós<thumos> sou<su> è<ē> en<en> thalàssēj<thalassa> tó<`o> `órmēmà<`ormēma> sou<su> `óti<`oti> epibèsēj<epibainō> epì<epi> toùs<`o> `ìppous<`ippos> sou<su> kaì<kai> `ē<`o> `ippasìa<`ippasia> sou<su> sōtērìa<sōtēria> "],
[4009,"enteìnōn<enteinō> enteneîs<enteinō> tó<`o> tóxon<toxon> sou<su> epì<epi> skêptra<skēptron> légei<legō> kùrios<kurios> diàpsalma<diapsalma> potamôn<potamos> `ragèsetai<`rēgnumi> gê<gē> "],
[4010,"ópsontaì<`oraō> se<su> kaì<kai> ōdinèsousin<ōdinō> laoì<laos> skorpìzōn<skorpizō> `ùdata<`udōr> poreìas<poreia> édōken<didōmi> `ē<`o> àbussos<abussos> fōnèn<fōnē> autês<autos> `ùpsos<`upsos> fantasìas<fantasia> autês<autos> epèrthē<epairō> "],
[4011,"`o<`o> `èlios<`ēlios> kaì<kai> `ē<`o> selènē<selēnē> éstē<`istēmi> en<en> têj<`o> tàxei<taxis> autês<autos> eis<eis> fôs<fōs> bolìdes<bolis> sou<su> poreùsontai<poreuomai> eis<eis> féggos<feggos> astrapês<astrapē> `óplōn<`oplon> sou<su> "],
[4012,"en<en> apeilêj<apeilē> sou<su> oligòseis<oligoō> gên<gē> kaì<kai> en<en> thumôj<thumos> katàxeis<katagō> éthnē<ethnos> "],
[4013,"exêlthes<exerchomai> eis<eis> sōtērìan<sōtēria> laoû<laos> sou<su> toû<`o> sôsai<sōjzō> toùs<`o> christoùs<Christos> sou<su> ébales<ballō> eis<eis> kefalàs<kefalē> anómōn<anomos> thànaton<thanatos> exègeiras<exegeirō> desmoùs<desmos> `éōs<`eōs> trachèlou<trachēlos> diàpsalma<diapsalma> "],
[4014,"diékopsas<diakoptō> en<en> ekstàsei<ekstasis> kefalàs<kefalē> dunastôn<dunastēs> seisthèsontai<seiō> en<en> autêj<autos> dianoìxousin<dianoigō> chalinoùs<chalinos> autôn<autos> `ōs<`ōs> ésthōn<esthō> ptōchós<ptōchos> làthraj<lathraj> "],
[4015,"kaì<kai> epebìbasas<epibibazō> eis<eis> thàlassan<thalassa> toùs<`o> `ìppous<`ippos> sou<su> taràssontas<tarassō> `ùdata<`udōr> pollà<polus> "],
[4016,"efulaxàmēn<fulassō> kaì<kai> eptoèthē<ptoeō> `ē<`o> koilìa<koilia> mou<egō> apó<apo> fōnês<fōnē> proseuchês<proseuchē> cheiléōn<cheilos> mou<egō> kaì<kai> eisêlthen<eiserchomai> trómos<tromos> eis<eis> tà<`o> ostâ<osteon> mou<egō> kaì<kai> `upokàtōthén<`upokatōthen> mou<egō> etaràchthē<tarassō> `ē<`o> `éxis<`exis> mou<egō> anapaùsomai<anapauō> en<en> `ēméraj<`ēmera> thlìpseòs<thlipsis> mou<egō> toû<`o> anabênaì<anabainō> me<egō> eis<eis> laón<laos> paroikìas<paroikia> mou<egō> "],
[4017,"dióti<dioti> sukê<sukē> ou'<ou'> karpoforèsei<karpoforeō> kaì<kai> ouk<ou'> éstai<eimi> genèmata<genēma> en<en> taîs<`o> ampélois<ampelos> pseùsetai<pseudomai> érgon<ergon> elaìas<elaia> kaì<kai> tà<`o> pedìa<pedion> ou'<ou'> poièsei<poieō> brôsin<brōsis> exélipon<ekleipō> apó<apo> bròseōs<brōsis> próbata<probaton> kaì<kai> ouch<ou'> `upàrchousin<`uparchō> bóes<bous> epì<epi> fàtnais<fatnē> exilàseōs<exilasis> autôn<autos> "],
[4018,"egò<egō> dé<de> en<en> tôj<`o> kurìōj<kurios> agalliàsomai<agalliaō> charèsomai<chairō> epì<epi> tôj<`o> theôj<theos> tôj<`o> sōtêrì<sōtēr> mou<egō> "],
[4019,"kùrios<kurios> `o<`o> theós<theos> mou<egō> dùnamìs<dunamis> mou<egō> kaì<kai> tàxei<taxis> toùs<`o> pódas<pous> mou<egō> eis<eis> suntéleian<sunteleia> epì<epi> tà<`o> `upsēlà<`upsēlos> epibibâj<epibibazō> me<egō> toû<`o> nikêsai<nikaō> en<en> têj<`o> ōjdêj<ōjdē> autoû<autos> "],
[5001,""],
[5002,""],
[5003,""],
[5004,""],
[5005,""],
[5006,""],
[5007,""],
[5008,""],
[5009,"[proseuchè<proseuchē> Ēsaiou]<Ēsaias> ek<ek> nuktós<nux> orthrìzei<orthrizō> tó<`o> pneûmà<pneuma> mou<egō> prós<pros> sé<su> `o<`o> theós<theos> dióti<dioti> fôs<fōs> tà<`o> prostàgmatà<prostagma> sou<su> epì<epi> tês<`o> gês<gē> dikaiosùnēn<dikaiosunē> màthete<manthanō> `oi<`o> enoikoûntes<enoikeō> epì<epi> tês<`o> gês<gē> "],
[5010,"pépautai<pauō> gàr<gar> `o<`o> asebès<asebēs> ou'<ou'> mè<mē> màthēj<manthanō> dikaiosùnēn<dikaiosunē> epì<epi> tês<`o> gês<gē> alètheian<alētheia> ou'<ou'> mè<mē> poièsei<poieō> arthètō<airō> `o<`o> asebès<asebēs> `ìna<`ina> mè<mē> ìdēj<`oraō> tèn<`o> dóxan<doxa> kurìou<kurios> "],
[5011,"kùrie<kurios> `upsēlós<`upsēlos> sou<su> `o<`o> brachìōn<brachiōn> kaì<kai> ouk<ou'> èjdeisan<oida> gnóntes<ginōskō> dé<de> aischunthètōsan<aischunō> zêlos<zēlos> lèmpsetai<lambanō> laón<laos> apaìdeuton<apaideutos> kaì<kai> nûn<nun> pûr<pur> toùs<`o> `upenantìous<`upenantios> édetai<esthiō> "],
[5012,"kùrie<kurios> `o<`o> theós<theos> `ēmôn<egō> eirènēn<eirēnē> dós<didōmi> `ēmîn<egō> pànta<pas> gàr<gar> apédōkas<apodidōmi> `ēmîn<egō> "],
[5013,"kùrie<kurios> `o<`o> theós<theos> `ēmôn<egō> ktêsai<ktaomai> `ēmâs<egō> kùrie<kurios> ektós<ektos> soû<su> àllon<allos> ouk<ou'> oìdamen<oida> tó<`o> ónomà<onoma> sou<su> onomàzomen<onomazō> "],
[5014,"`oi<`o> dé<de> nekroì<nekros> zōèn<zōē> ou'<ou'> mè<mē> ìdōsin<`oraō> oudé<oude> iatroì<iatros> ou'<ou'> mè<mē> anastèsousin<anistēmi> dià<dia> toûto<`outos> epègages<epagō> kaì<kai> apòlesas<apollumi> kaì<kai> êras<airō> pân<pas> àrsen<arsēn> autôn<autos> "],
[5015,"prósthes<prostithēmi> autoîs<autos> kakà<kakos> kùrie<kurios> prósthes<prostithēmi> kakà<kakos> toîs<`o> endóxois<endoxos> tês<`o> gês<gē> "],
[5016,"kùrie<kurios> en<en> thlìpsei<thlipsis> emnèsthēn<mimnējskomai> sou<su> en<en> thlìpsei<thlipsis> mikrâj<mikros> `ē<`o> paideìa<paideia> sou<su> `ēmîn<egō> "],
[5017,"kaì<kai> `ōs<`ōs> `ē<`o> ōdìnousa<ōdinō> eggìzei<eggizō> toû<`o> tekeîn<tiktō> kaì<kai> epì<epi> têj<`o> ōdîni<ōdin> autês<autos> ekékraxen<krazō> `oùtōs<`outōs> egenèthēmen<ginomai> tôj<`o> agapētôj<agapētos> sou<su> "],
[5018,"dià<dia> tón<`o> fóbon<fobos> sou<su> kùrie<kurios> en<en> gastrì<gastēr> elàbomen<lambanō> kaì<kai> ōdinèsamen<ōdinō> kaì<kai> etékomen<tiktō> pneûma<pneuma> sōtērìas<sōtēria> sou<su> epoièsamen<poieō> epì<epi> tês<`o> gês<gē> ou'<ou'> pesoùmetha<piptō> allà<alla> pesoûntai<piptō> `oi<`o> enoikoûntes<enoikeō> epì<epi> tês<`o> gês<gē> "],
[5019,"anastèsontai<anistēmi> `oi<`o> nekroì<nekros> kaì<kai> egerthèsontai<egeirō> `oi<`o> en<en> toîs<`o> mnēmeìois<mnēmeion> kaì<kai> eufranthèsontai<eufrainō> `oi<`o> en<en> têj<`o> gêj<gē> `ē<`o> gàr<gar> drósos<drosos> `ē<`o> parà<para> soû<su> ìama<iama> autoîs<autos> estin<eimi> `ē<`o> dé<de> gê<gē> tôn<`o> asebôn<asebēs> peseîtai<piptō> "],
[5020,"bàdize<badizō> laós<laos> mou<egō> eìselthe<eiserchomai> eis<eis> tà<`o> tamìeià<tamieion> sou<su> apókleison<apokleiō> tèn<`o> thùran<thura> sou<su> apokrùbēthi<apokruptō> mikrón<mikros> `óson<`osos> `óson<`osos> `éōs<`eōs> àn<an> parélthēj<parerchomai> `ē<`o> orgè<orgē> kurìou<kurios> "],
[6001,""],
[6002,""],
[6003,"[proseuchè<proseuchē> Iōna]<Iōna> ebóēsa<boaō> en<en> thlìpsei<thlipsis> mou<egō> prós<pros> kùrion<kurios> tón<`o> theón<theos> mou<egō> kaì<kai> eisèkousén<eisakouō> mou<egō> ek<ek> koilìas<koilia> `àjdou<`ajdēs> kraugês<kraugē> mou<egō> èkousas<akouō> fōnês<fōnē> mou<egō> "],
[6004,"apérripsàs<aporiptō> me<egō> eis<eis> bàthē<bathos> kardìas<kardia> thalàssēs<thalassa> kaì<kai> potamoì<potamos> me<egō> ekùklōsan<kukloō> pàntes<pas> `oi<`o> meteōrismoì<meteōrismos> sou<su> kaì<kai> tà<`o> kùmatà<kuma> sou<su> ep'<epi> emé<egō> diêlthon<dierchomai> "],
[6005,"kagò<kai&egō> eîpa<legō> apôsmai<apōtheō> ex<ek> ofthalmôn<ofthalmos> sou<su> âra<ara> prosthèsō<prostithēmi> toû<`o> epiblépsai<epiblepō> prós<pros> naón<naos> tón<`o> `àgión<`agios> sou<su> "],
[6006,"periechùthē<pericheō> moi<egō> `ùdōr<`udōr> `éōs<`eōs> psuchês<psuchē> mou<egō> àbussos<abussos> ekùklōsén<kukloō> me<egō> eschàtē<eschatos> édu<duō> `ē<`o> kefalè<kefalē> mou<egō> eis<eis> schismàs<schismē> oréōn<oros> "],
[6007,"katébēn<katabainō> eis<eis> gên<gē> `ês<`os> `oi<`o> mochloì<mochlos> autês<autos> kàtochoi<katochos> aiònioi<aiōnios> kaì<kai> anabètō<anabainō> ek<ek> fthorâs<fthora> `ē<`o> zōè<zōē> mou<egō> kùrie<kurios> `o<`o> theós<theos> mou<egō> "],
[6008,"en<en> tôj<`o> ekleìpein<ekleipō> tèn<`o> psuchèn<psuchē> mou<egō> ap'<apo> emoû<egō> toû<`o> kurìou<kurios> emnèsthēn<mimnējskomai> kaì<kai> élthoi<erchomai> prós<pros> sé<su> `ē<`o> proseuchè<proseuchē> mou<egō> eis<eis> naón<naos> `àgión<`agios> sou<su> "],
[6009,"fulassómenoi<fulassō> màtaia<mataios> kaì<kai> pseudê<pseudēs> éleos<eleos> autôn<autos> egkatélipon<egkataleipō> "],
[6010,"egò<egō> dé<de> metà<meta> fōnês<fōnē> ainéseōs<ainesis> kaì<kai> exomologèseōs<exomologēsis> thùsō<thuō> soi<su> `ósa<`osos> ēuxàmēn<euchomai> apodòsō<apodidōmi> soi<su> eis<eis> sōtērìan<sōtēria> mou<egō> tôj<`o> kurìōj<kurios> "],
[7001,""],
[7002,""],
[7003,""],
[7004,""],
[7005,""],
[7006,""],
[7007,""],
[7008,""],
[7009,""],
[7010,""],
[7011,""],
[7012,""],
[7013,""],
[7014,""],
[7015,""],
[7016,""],
[7017,""],
[7018,""],
[7019,""],
[7020,""],
[7021,""],
[7022,""],
[7023,""],
[7024,""],
[7025,""],
[7026,"[proseuchè<proseuchē> Azariou]<Azarias> eulogētós<eulogētos> eî<eimi> kùrie<kurios> `o<`o> theós<theos> tôn<`o> patérōn<patēr> `ēmôn<egō> kaì<kai> ainetón<ainetos> kaì<kai> dedoxasménon<doxazō> tó<`o> ónomà<onoma> sou<su> eis<eis> toùs<`o> aiônas<aiōn> "],
[7027,"`óti<`oti> dìkaios<dikaios> eî<eimi> epì<epi> pâsin<pas> `oîs<`os> epoìēsas<poieō> `ēmîn<egō> kaì<kai> pànta<pas> tà<`o> érga<ergon> sou<su> alēthinà<alēthinos> kaì<kai> eutheîai<euthus> `ai<`o> `odoì<`odos> sou<su> kaì<kai> pâsai<pas> `ai<`o> krìseis<krisis> sou<su> alētheîs<alēthēs> "],
[7028,"kaì<kai> krìmata<krima> alētheìas<alētheia> epoìēsas<poieō> katà<kata> pànta<pas> `à<`os> epègages<epagō> `ēmîn<egō> kaì<kai> epì<epi> tèn<`o> pólin<polis> tèn<`o> `agìan<`agios> tèn<`o> tôn<`o> patérōn<patēr> `ēmôn<egō> Ierousalēm<Ierousalēm> `óti<`oti> en<en> alētheìaj<alētheia> kaì<kai> krìsei<krisis> epègages<epagō> taûta<`outos> pànta<pas> dià<dia> tàs<`o> `amartìas<`amartia> `ēmôn<egō> "],
[7029,"`óti<`oti> `ēmàrtomen<`amartanō> kaì<kai> ēnomèsamen<anomeō> apostênai<afistēmi> apó<apo> soû<su> kaì<kai> exēmàrtomen<examartanō> en<en> pâsin<pas> kaì<kai> tôn<`o> entolôn<entolē> sou<su> ouk<ou'> ēkoùsamen<akouō> "],
[7030,"oudé<oude> sunetērèsamen<suntēreō> oudé<oude> epoièsamen<poieō> kathòs<kathōs> eneteìlō<entellomai> `ēmîn<egō> `ìna<`ina> eû<eu> `ēmîn<egō> génētai<ginomai> "],
[7031,"kaì<kai> pànta<pas> `ósa<`osos> epègages<epagō> `ēmîn<egō> kaì<kai> pànta<pas> `ósa<`osos> epoìēsas<poieō> `ēmîn<egō> en<en> alēthinêj<alēthinos> krìsei<krisis> epoìēsas<poieō> "],
[7032,"kaì<kai> parédōkas<paradidōmi> `ēmâs<egō> eis<eis> cheîras<cheir> echthrôn<echthros> anómōn<anomos> echthìstōn<echthros> apostatôn<apostatēs> kaì<kai> basileî<basileus> adìkōj<adikos> kaì<kai> ponērotàtōj<ponēros> parà<para> pâsan<pas> tèn<`o> gên<gē> "],
[7033,"kaì<kai> nûn<nun> ouk<ou'> éstin<eimi> `ēmîn<egō> anoîxai<anoigō> tó<`o> stóma<stoma> aischùnē<aischunē> kaì<kai> óneidos<oneidos> egenèthē<ginomai> toîs<`o> doùlois<doulos> sou<su> kaì<kai> toîs<`o> seboménois<sebō> se<su> "],
[7034,"mè<mē> dè<dē> paradôjs<paradidōmi> `ēmâs<egō> eis<eis> télos<telos> dià<dia> tó<`o> ónomà<onoma> sou<su> kaì<kai> mè<mē> diaskedàsējs<diaskedazō> tèn<`o> diathèkēn<diathēkē> sou<su> "],
[7035,"kaì<kai> mè<mē> apostèsējs<afistēmi> tó<`o> éleós<eleos> sou<su> af'<apo> `ēmôn<egō> di'<dia> Abraam<Abraam> tón<`o> ēgapēménon<agapaō> `upó<`upo> soû<su> kaì<kai> dià<dia> Isaak<Isaak> tón<`o> doûlón<doulos> sou<su> kaì<kai> Israēl<Israēl> tón<`o> `àgión<`agios> sou<su> "],
[7036,"`oîs<`os> elàlēsas<laleō> prós<pros> autoùs<autos> légōn<legō> plēthûnai<plēthunō> tó<`o> spérma<sperma> autôn<autos> `ōs<`ōs> tà<`o> àstra<astron> toû<`o> ouranoû<ouranos> kaì<kai> `ōs<`ōs> tèn<`o> àmmon<ammos> tèn<`o> parà<para> tó<`o> cheîlos<cheilos> tês<`o> thalàssēs<thalassa> "],
[7037,"`óti<`oti> déspota<despotēs> esmikrùnthēmen<smikrunō> parà<para> pànta<pas> tà<`o> éthnē<ethnos> kaì<kai> esmen<eimi> tapeinoì<tapeinos> en<en> pàsēj<pas> têj<`o> gêj<gē> sèmeron<sēmeron> dià<dia> tàs<`o> `amartìas<`amartia> `ēmôn<egō> "],
[7038,"kaì<kai> ouk<ou'> éstin<eimi> en<en> tôj<`o> kairôj<kairos> toùtōj<`outos> àrchōn<archōn> kaì<kai> profètēs<profētēs> kaì<kai> `ēgoùmenos<`ēgeomai> oudé<oude> `olokaùtōsis<`olokautōsis> oudé<oude> thusìa<thusia> oudé<oude> prosforà<prosfora> oudé<oude> thumìama<thumiama> ou'<ou'> tópos<topos> toû<`o> karpôsai<karpoō> enòpión<enōpion> sou<su> kaì<kai> `eureîn<`euriskō> éleos<eleos> "],
[7039,"all'<alla> en<en> psuchêj<psuchē> suntetrimménēj<suntribō> kaì<kai> pneùmati<pneuma> tapeinòseōs<tapeinōsis> prosdechtheìēmen<prosdechomai> `ōs<`ōs> en<en> `olokautòmasin<`olokautōma> kriôn<krios> kaì<kai> taùrōn<tauros> kaì<kai> `ōs<`ōs> en<en> muriàsin<murias> arnôn<arnos> piónōn<piōn> "],
[7040,"`oùtōs<`outōs> genésthō<ginomai> `ē<`o> thusìa<thusia> `ēmôn<egō> enòpión<enōpion> sou<su> sèmeron<sēmeron> kaì<kai> ektelésai<ekteleō> ópisthén<opisthen> sou<su> `óti<`oti> ouk<ou'> éstin<eimi> aischùnē<aischunē> toîs<`o> pepoithósin<peithō> epì<epi> soì<su> "],
[7041,"kaì<kai> nûn<nun> exakolouthoûmen<exakoloutheō> en<en> `ólēj<`olos> kardìaj<kardia> kaì<kai> foboùmethà<fobeō> se<su> kaì<kai> zētoûmen<zēteō> tó<`o> prósōpón<prosōpon> sou<su> mè<mē> kataischùnējs<kataischunō> `ēmâs<egō> "],
[7042,"allà<alla> poìēson<poieō> meth'<meta> `ēmôn<egō> katà<kata> tèn<`o> epieìkeiàn<epieikeia> sou<su> kaì<kai> katà<kata> tó<`o> plêthos<plēthos> toû<`o> eléou<eleos> sou<su> "],
[7043,"kaì<kai> exeloû<exaireō> `ēmâs<egō> katà<kata> tà<`o> thaumàsià<thaumasios> sou<su> kaì<kai> dós<didōmi> dóxan<doxa> tôj<`o> onómatì<onoma> sou<su> kùrie<kurios> "],
[7044,"kaì<kai> entrapeìēsan<entrepō> pàntes<pas> `oi<`o> endeiknùmenoi<endeiknumi> toîs<`o> doùlois<doulos> sou<su> kakà<kakos> kaì<kai> kataischuntheìēsan<kataischunō> apó<apo> pàsēs<pas> dunàmeōs<dunamis> kaì<kai> dunasteìas<dunasteia> kaì<kai> `ē<`o> ischùs<ischus> autôn<autos> suntribeìē<suntribō> "],
[7045,"kaì<kai> gnòtōsan<ginōskō> `óti<`oti> sù<su> eî<eimi> kùrios<kurios> `o<`o> theós<theos> mónos<monos> kaì<kai> éndoxos<endoxos> ef'<epi> `ólēn<`olos> tèn<`o> oikouménēn<oikoumenē> "],
[8001,""],
[8002,""],
[8003,""],
[8004,""],
[8005,""],
[8006,""],
[8007,""],
[8008,""],
[8009,""],
[8010,""],
[8011,""],
[8012,""],
[8013,""],
[8014,""],
[8015,""],
[8016,""],
[8017,""],
[8018,""],
[8019,""],
[8020,""],
[8021,""],
[8022,""],
[8023,""],
[8024,""],
[8025,""],
[8026,""],
[8027,""],
[8028,""],
[8029,""],
[8030,""],
[8031,""],
[8032,""],
[8033,""],
[8034,""],
[8035,""],
[8036,""],
[8037,""],
[8038,""],
[8039,""],
[8040,""],
[8041,""],
[8042,""],
[8043,""],
[8044,""],
[8045,""],
[8046,""],
[8047,""],
[8048,""],
[8049,""],
[8050,""],
[8051,""],
[8052,"[`ùmnos<`umnos> tôn<`o> triôn<treis> paìdōn]<pais> eulogētós<eulogētos> eî<eimi> kùrie<kurios> `o<`o> theós<theos> tôn<`o> patérōn<patēr> `ēmôn<egō> kaì<kai> ainetós<ainetos> kaì<kai> `uperupsoùmenos<`uperupsoō> eis<eis> toùs<`o> aiônas<aiōn> kaì<kai> eulogēménon<eulogeō> tó<`o> ónoma<onoma> tês<`o> dóxēs<doxa> sou<su> tó<`o> `àgion<`agios> kaì<kai> `uperainetón<`uperainetos> kaì<kai> `uperupsoùmenon<`uperupsoō> eis<eis> toùs<`o> aiônas<aiōn> "],
[8053,"eulogēménos<eulogeō> eî<eimi> en<en> tôj<`o> naôj<naos> tês<`o> `agìas<`agios> dóxēs<doxa> sou<su> kaì<kai> `uperumnētós<`uperumnētos> kaì<kai> `uperéndoxos<`uperendoxos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8054,"eulogēménos<eulogeō> eî<eimi> `o<`o> blépōn<blepō> abùssous<abussos> kathèmenos<kathēmai> epì<epi> cheroubin<cheroub> kaì<kai> `uperainetós<`uperainetos> kaì<kai> `uperupsoùmenos<`uperupsoō> eis<eis> toùs<`o> aiônas<aiōn> "],
[8055,"eulogēménos<eulogeō> eî<eimi> epì<epi> thrónou<thronos> tês<`o> basileìas<basileia> sou<su> kaì<kai> `uperumnētós<`uperumnētos> kaì<kai> `uperupsoùmenos<`uperupsoō> eis<eis> toùs<`o> aiônas<aiōn> "],
[8056,"eulogēménos<eulogeō> eî<eimi> en<en> tôj<`o> stereòmati<stereōma> toû<`o> ouranoû<ouranos> kaì<kai> `uperumnētós<`uperumnētos> kaì<kai> `uperéndoxos<`uperendoxos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8057,"eulogeîte<eulogeō> pànta<pas> tà<`o> érga<ergon> kurìou<kurios> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8058,"eulogeîte<eulogeō> àggeloi<aggelos> kurìou<kurios> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8059,"eulogeîte<eulogeō> ouranoì<ouranos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8060,"eulogeîte<eulogeō> `ùdata<`udōr> pànta<pas> tà<`o> `uperànō<`uperanō> tôn<`o> ouranôn<ouranos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8061,"eulogeîte<eulogeō> pâsai<pas> `ai<`o> dunàmeis<dunamis> kurìou<kurios> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8062,"eulogeîte<eulogeō> `èlios<`ēlios> kaì<kai> selènē<selēnē> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8063,"eulogeîte<eulogeō> àstra<astron> toû<`o> ouranoû<ouranos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8064,"eulogeîte<eulogeō> pâs<pas> ómbros<ombros> kaì<kai> drósos<drosos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8065,"eulogeîte<eulogeō> pànta<pas> tà<`o> pneùmata<pneuma> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8066,"eulogeîte<eulogeō> pûr<pur> kaì<kai> kaûma<kauma> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8067,"eulogeîte<eulogeō> psûchos<psuchos> kaì<kai> kaùsōn<kaiō> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8068,"eulogeîte<eulogeō> drósoi<drosos> kaì<kai> nifetoì<nifetos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8069,"eulogeîte<eulogeō> pàgos<pagos> kaì<kai> psûchos<psuchos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8070,"eulogeîte<eulogeō> pàchnai<pachnē> kaì<kai> chiónes<chiōn> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8071,"eulogeîte<eulogeō> nùktes<nux> kaì<kai> `ēmérai<`ēmera> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8072,"eulogeîte<eulogeō> fôs<fōs> kaì<kai> skótos<skotos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8073,"eulogeîte<eulogeō> astrapaì<astrapē> kaì<kai> nefélai<nefelē> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8074,"eulogeìtō<eulogeō> `ē<`o> gê<gē> tón<`o> kùrion<kurios> `umneìtō<`umneō> kaì<kai> `uperupsoùtō<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8075,"eulogeîte<eulogeō> órē<oros> kaì<kai> bounoì<bounos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8076,"eulogeîte<eulogeō> pànta<pas> tà<`o> fuómena<fuō> en<en> têj<`o> gêj<gē> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8077,"eulogeîte<eulogeō> `ai<`o> pēgaì<pēgē> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8078,"eulogeîte<eulogeō> thàlassai<thalassa> kaì<kai> potamoì<potamos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8079,"eulogeîte<eulogeō> kètē<kētos> kaì<kai> pànta<pas> tà<`o> kinoùmena<kineō> en<en> toîs<`o> `ùdasin<`udōr> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8080,"eulogeîte<eulogeō> pànta<pas> tà<`o> peteinà<peteinos> toû<`o> ouranoû<ouranos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8081,"eulogeîte<eulogeō> tà<`o> thērìa<thērion> kaì<kai> pànta<pas> tà<`o> ktènē<ktēnos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8082,"eulogeîte<eulogeō> `uioì<`uios> tôn<`o> anthròpōn<anthrōpos> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8083,"eulogeìtō<eulogeō> Israēl<Israēl> tón<`o> kùrion<kurios> `umneìtō<`umneō> kaì<kai> `uperupsoùtō<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8084,"eulogeîte<eulogeō> `iereîs<`iereus> kurìou<kurios> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8085,"eulogeîte<eulogeō> doûloi<doulos> kurìou<kurios> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8086,"eulogeîte<eulogeō> pneùmata<pneuma> kaì<kai> psuchaì<psuchē> dikaìōn<dikaios> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8087,"eulogeîte<eulogeō> `ósioi<`osios> kaì<kai> tapeinoì<tapeinos> têj<`o> kardìaj<kardia> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[8088,"eulogeîte<eulogeō> Anania<Anania> Azaria<Azaria> Misaēl<Misaēl> tón<`o> kùrion<kurios> `umneîte<`umneō> kaì<kai> `uperupsoûte<`uperupsoō> autón<autos> eis<eis> toùs<`o> aiônas<aiōn> "],
[9001,""],
[9002,""],
[9003,""],
[9004,""],
[9005,""],
[9006,""],
[9007,""],
[9008,""],
[9009,""],
[9010,""],
[9011,""],
[9012,""],
[9013,""],
[9014,""],
[9015,""],
[9016,""],
[9017,""],
[9018,""],
[9019,""],
[9020,""],
[9021,""],
[9022,""],
[9023,""],
[9024,""],
[9025,""],
[9026,""],
[9027,""],
[9028,""],
[9029,""],
[9030,""],
[9031,""],
[9032,""],
[9033,""],
[9034,""],
[9035,""],
[9036,""],
[9037,""],
[9038,""],
[9039,""],
[9040,""],
[9041,""],
[9042,""],
[9043,""],
[9044,""],
[9045,""],
[9046,"[proseuchè<proseuchē> Marias<Maria> tês<`o> theotókou]<theotokos> megalùnei<megalunō> `ē<`o> psuchè<psuchē> mou<egō> tón<`o> kùrion<kurios> "],
[9047,"kaì<kai> ēgallìasen<agalliaō> tó<`o> pneûmà<pneuma> mou<egō> epì<epi> tôj<`o> theôj<theos> tôj<`o> sōtêrì<sōtēr> mou<egō> "],
[9048,"`óti<`oti> epéblepsen<epiblepō> epì<epi> tèn<`o> tapeìnōsin<tapeinōsis> tês<`o> doùlēs<doulē> autoû<autos> idoù<idou> gàr<gar> apó<apo> toû<`o> nûn<nun> makarioûsìn<makarizō> me<egō> pâsai<pas> `ai<`o> geneaì<genea> "],
[9049,"`óti<`oti> epoìēsén<poieō> moi<egō> megaleîa<megaleios> `o<`o> dunatós<dunatos> kaì<kai> `àgion<`agios> tó<`o> ónoma<onoma> autoû<autos> "],
[9050,"kaì<kai> tó<`o> éleos<eleos> autoû<autos> eis<eis> geneàn<genea> kaì<kai> geneàn<genea> toîs<`o> fobouménois<fobeō> autón<autos> "],
[9051,"epoìēsen<poieō> kràtos<kratos> en<en> brachìoni<brachiōn> autoû<autos> dieskórpisen<diaskorpizō> `uperēfànous<`uperēfanos> dianoìaj<dianoia> kardìas<kardia> autôn<autos> "],
[9052,"katheîlen<kathaireō> dunàstas<dunastēs> apó<apo> thrónōn<thronos> kaì<kai> `ùpsōsen<`upsoō> tapeinoùs<tapeinos> "],
[9053,"peinôntas<peinaō> enéplēsen<empiplēmi> agathôn<agathos> kaì<kai> ploutoûntas<plouteō> exapésteilen<exapostellō> kenoùs<kenos> "],
[9054,"antelàbeto<antilambanomai> Israēl<Israēl> paidós<pais> autoû<autos> mnēsthênai<mimnējskomai> eléous<eleos> "],
[9055,"kathòs<kathōs> elàlēsen<laleō> prós<pros> toùs<`o> patéras<patēr> `ēmôn<egō> tôj<`o> Abraam<Abraam> kaì<kai> tôj<`o> spérmati<sperma> autoû<autos> `éōs<`eōs> aiônos<aiōn> "],
[9056,""],
[9057,""],
[9058,""],
[9059,""],
[9060,""],
[9061,""],
[9062,""],
[9063,""],
[9064,""],
[9065,""],
[9066,""],
[9067,""],
[9068,"[proseuchè<proseuchē> Zachariou]<Zacharias> eulogētós<eulogētos> kùrios<kurios> `o<`o> theós<theos> toû<`o> Israēl<Israēl> `óti<`oti> epesképsato<episkeptomai> kaì<kai> epoìēsen<poieō> lùtrōsin<lutrōsis> tôj<`o> laôj<laos> autoû<autos> "],
[9069,"kaì<kai> ègeiren<egeirō> kéras<keras> sōtērìas<sōtēria> `ēmîn<egō> en<en> tôj<`o> oìkōj<oikos> Dauid<Dauid> toû<`o> paidós<pais> autoû<autos> "],
[9070,"kathòs<kathōs> elàlēsen<laleō> dià<dia> stómatos<stoma> tôn<`o> `agìōn<`agios> tôn<`o> ap'<apo> aiônos<aiōn> profētôn<profētēs> autoû<autos> "],
[9071,"sōtērìan<sōtēria> ex<ek> echthrôn<echthros> `ēmôn<egō> kaì<kai> ek<ek> cheirós<cheir> pàntōn<pas> tôn<`o> misoùntōn<miseō> `ēmâs<egō> "],
[9072,"poiêsai<poieō> éleos<eleos> metà<meta> tôn<`o> patérōn<patēr> `ēmôn<egō> kaì<kai> mnēsthênai<mimnējskomai> diathèkēs<diathēkē> `agìas<`agios> autoû<autos> "],
[9073,"`órkon<`orkos> `ón<`os> òmosen<omnumi> prós<pros> Abraam<Abraam> tón<`o> patéra<patēr> `ēmôn<egō> "],
[9074,"toû<`o> doûnai<didōmi> `ēmîn<egō> afóbōs<afobōs> ek<ek> cheirós<cheir> tôn<`o> echthrôn<echthros> `ēmôn<egō> `rusthéntas<`ruomai> "],
[9075,"latreùein<latreuō> autôj<autos> en<en> `osiótēti<`osiotēs> kaì<kai> dikaiosùnēj<dikaiosunē> enòpion<enōpion> autoû<autos> pàsas<pas> tàs<`o> `ēméras<`ēmera> `ēmôn<egō> "],
[9076,"kaì<kai> sù<su> dé<de> paidìon<paidion> profètēs<profētēs> `upsìstou<`upsistos> klēthèsēj<kaleō> proporeùsēj<proporeuomai> gàr<gar> pró<pro> prosòpou<prosōpon> kurìou<kurios> `etoimàsai<`etoimazō> `odoùs<`odos> autoû<autos> "],
[9077,"toû<`o> doûnai<didōmi> gnôsin<gnōsis> sōtērìas<sōtēria> tôj<`o> laôj<laos> autoû<autos> en<en> afései<afesis> `amartiôn<`amartia> `ēmôn<egō> "],
[9078,"dià<dia> splàgchna<splagchnon> eléous<eleos> theoû<theos> `ēmôn<egō> en<en> `oîs<`os> epesképsato<episkeptomai> `ēmâs<egō> anatolè<anatolē> ex<ek> `ùpsous<`upsos> "],
[9079,"epifânai<epifainō> toîs<`o> en<en> skótei<skotos> kaì<kai> skiâj<skia> thanàtou<thanatos> kathēménois<kathēmai> toû<`o> kateuthûnai<kateuthunō> toùs<`o> pódas<pous> `ēmôn<egō> eis<eis> `odón<`odos> eirènēs<eirēnē> "],
[10001,"[ōjdè<ōjdē> Ēsaiou]<Ēsaias> àjsō<ajdō> dè<dē> tôj<`o> ēgapēménōj<agapaō> âjsma<ajsma> toû<`o> agapētoû<agapētos> tôj<`o> ampelônì<ampelōn> mou<egō> ampelòn<ampelōn> egéneto<ginomai> tôj<`o> ēgapēménōj<agapaō> en<en> kérati<keras> en<en> tópōj<topos> pìoni<piōn> "],
[10002,"kaì<kai> fragmón<fragmos> periéthēka<peritithēmi> kaì<kai> efùteusa<futeuō> àmpelon<ampelos> en<en> sōrēk<sōrēk> kaì<kai> ōjkodómēsa<oikodomeō> pùrgon<purgos> en<en> mésōj<mesos> autês<autos> kaì<kai> prolènion<prolēnion> òruxa<orussō> en<en> autôj<autos> kaì<kai> émeina<menō> toû<`o> poiêsai<poieō> stafulèn<stafulē> epoìēsen<poieō> dé<de> akànthas<akantha> "],
[10003,"kaì<kai> nûn<nun> ànthrōpos<anthrōpos> toû<`o> Iouda<Ioudas> kaì<kai> `oi<`o> enoikoûntes<enoikeō> en<en> Ierousalēm<Ierousalēm> krìnate<krinō> en<en> emoì<egō> kaì<kai> anà<ana> méson<mesos> toû<`o> ampelônós<ampelōn> mou<egō> "],
[10004,"tì<tis> poièsō<poieō> tôj<`o> ampelônì<ampelōn> mou<egō> éti<eti> kaì<kai> ouk<ou'> epoìēsa<poieō> autôj<autos> dióti<dioti> émeina<menō> `ìna<`ina> poièsēj<poieō> stafulèn<stafulē> epoìēsen<poieō> dé<de> akànthas<akantha> "],
[10005,"nûn<nun> dé<de> anaggelô<anaggellō> `umîn<su> tì<tis> poièsō<poieō> tôj<`o> ampelônì<ampelōn> mou<egō> afelô<afaireō> tón<`o> fragmón<fragmos> autoû<autos> kaì<kai> éstai<eimi> eis<eis> diarpagèn<diarpagē> kaì<kai> kathelô<kathaireō> tón<`o> toîchon<toichos> autoû<autos> kaì<kai> éstai<eimi> eis<eis> katapàtēma<katapatēma> "],
[10006,"kaì<kai> anèsō<aniēmi> tón<`o> ampelônà<ampelōn> mou<egō> kaì<kai> ou'<ou'> mè<mē> tmēthêj<temnō> oudé<oude> mè<mē> skafêj<skaptō> kaì<kai> anabèsetai<anabainō> eis<eis> autón<autos> `ōseì<`ōsei> eis<eis> chérson<chersos> àkanthai<akantha> kaì<kai> taîs<`o> nefélais<nefelē> enteloûmai<entellomai> toû<`o> mè<mē> bréxai<brechō> eis<eis> autón<autos> `uetón<`uetos> "],
[10007,"`o<`o> gàr<gar> ampelòn<ampelōn> kurìou<kurios> sabaōth<sabaōth> oîkos<oikos> Israēl<Israēl> estìn<eimi> kaì<kai> ànthrōpos<anthrōpos> toû<`o> Iouda<Ioudas> neófuton<neofutos> ēgapēménon<agapaō> kaì<kai> émeina<menō> toû<`o> poiêsai<poieō> krìsin<krisis> epoìēsen<poieō> dé<de> anomìan<anomia> kaì<kai> ou'<ou'> dikaiosùnēn<dikaiosunē> allà<alla> kraugèn<kraugē> "],
[10008,"ouaì<ouai> `oi<`o> sunàptontes<sunaptō> oikìan<oikia> prós<pros> oikìan<oikia> kaì<kai> agrón<agros> prós<pros> agrón<agros> eggìzontes<eggizō> `ìna<`ina> toû<`o> plēsìon<plēsion> afélōntai<afaireō> mè<mē> oikèsete<oikeō> mónoi<monos> epì<epi> tês<`o> gês<gē> "],
[10009,"ēkoùsthē<akouō> gàr<gar> taûta<`outos> pànta<pas> eis<eis> tà<`o> ôta<ous> kurìou<kurios> sabaōth<sabaōth> "],
[11001,""],
[11002,""],
[11003,""],
[11004,""],
[11005,""],
[11006,""],
[11007,""],
[11008,""],
[11009,""],
[11010,"[proseuchè<proseuchē> Ezekiou]<`Ezekias> egò<egō> eîpa<legō> en<en> tôj<`o> `ùpsei<`upsos> tôn<`o> `ēmerôn<`ēmera> mou<egō> poreùsomai<poreuomai> en<en> pùlais<pulē> `àjdou<`ajdēs> kataleìpsō<kataleipō> tà<`o> étē<etos> tà<`o> epìloipa<epiloipos> "],
[11011,"eîpa<legō> oukéti<ouketi> ou'<ou'> mè<mē> ìdō<`oraō> tó<`o> sōtèrion<sōtērion> toû<`o> theoû<theos> epì<epi> tês<`o> gês<gē> ou'<ou'> mè<mē> ìdō<`oraō> ànthrōpon<anthrōpos> metà<meta> katoikoùntōn<katoikeō> "],
[11012,"exélipon<ekleipō> ek<ek> tês<`o> suggeneìas<suggeneia> mou<egō> katélipon<kataleipō> tó<`o> loipón<loipos> tês<`o> zōês<zōē> mou<egō> exêlthen<exerchomai> kaì<kai> apêlthen<aperchomai> ap'<apo> emoû<egō> `òsper<`ōsper> `o<`o> katalùōn<kataluō> skēnèn<skēnē> pèxas<pēgnumi> tó<`o> pneûmà<pneuma> mou<egō> par'<para> emoì<egō> egéneto<ginomai> `ōs<`ōs> `istós<`istos> erìthou<erithos> eggizoùsēs<eggizō> ektemeîn<ektemnō> "],
[11013,"en<en> têj<`o> `ēméraj<`ēmera> ekeìnēj<ekeinos> paredóthēn<paradidōmi> `éōs<`eōs> prōì<prōi> `ōs<`ōs> léonti<leōn> `oùtōs<`outōs> sunétripsen<suntribō> pànta<pas> tà<`o> ostâ<osteon> mou<egō> apó<apo> gàr<gar> tês<`o> `ēméras<`ēmera> `éōs<`eōs> tês<`o> nuktós<nux> paredóthēn<paradidōmi> "],
[11014,"`ōs<`ōs> chelidòn<chelidōn> `oùtō<`outōs> fōnèsō<fōneō> kaì<kai> `ōs<`ōs> peristerà<peristera> `oùtō<`outōs> meletèsō<meletaō> exélipon<ekleipō> gàr<gar> `oi<`o> ofthalmoì<ofthalmos> mou<egō> toû<`o> blépein<blepō> eis<eis> tó<`o> `ùpsos<`upsos> toû<`o> ouranoû<ouranos> prós<pros> tón<`o> kùrion<kurios> "],
[11015,"`ós<`os> exeìlató<exaireō> me<egō> kaì<kai> afeìlató<afaireō> mou<egō> tèn<`o> odùnēn<odunē> tês<`o> psuchês<psuchē> "],
[11016,"kùrie<kurios> perì<peri> autês<autos> gàr<gar> anēggélē<anaggellō> soi<su> kaì<kai> exègeiràs<exegeirō> mou<egō> tèn<`o> pnoèn<pnoē> kaì<kai> paraklētheìs<parakaleō> ézēsa<zaō> "],
[11017,"`eìlou<`aireō> gàr<gar> mou<egō> tèn<`o> psuchèn<psuchē> `ìna<`ina> mè<mē> apólētai<apollumi> kaì<kai> apérripsas<aporiptō> opìsō<opisō> mou<egō> pàsas<pas> tàs<`o> `amartìas<`amartia> mou<egō> "],
[11018,"ou'<ou'> gàr<gar> `oi<`o> en<en> `àjdou<`ajdēs> ainésousìn<aineō> se<su> oudé<oude> `oi<`o> apothanóntes<apothnējskō> eulogèsousìn<eulogeō> se<su> oudé<oude> elpioûsin<elpizō> `oi<`o> en<en> `àjdou<`ajdēs> tèn<`o> eleēmosùnēn<eleēmosunē> sou<su> "],
[11019,"`oi<`o> zôntes<zaō> eulogèsousìn<eulogeō> se<su> `ón<`os> trópon<tropos> kagò<kai&egō> apó<apo> gàr<gar> tês<`o> sèmeron<sēmeron> paidìa<paidion> poièsō<poieō> `à<`os> anaggeloûsin<anaggellō> tèn<`o> dikaiosùnēn<dikaiosunē> sou<su> kùrie<kurios> tês<`o> sōtērìas<sōtēria> mou<egō> "],
[11020,"kaì<kai> ou'<ou'> paùsomai<pauō> eulogôn<eulogeō> se<su> metà<meta> psaltērìou<psaltērion> pàsas<pas> tàs<`o> `ēméras<`ēmera> tês<`o> zōês<zōē> mou<egō> katénanti<katenanti> toû<`o> oìkou<oikos> toû<`o> theoû<theos> "],
[12001,"[proseuchè<proseuchē> Manassē]<Manassē> kùrie<kurios> pantokràtōr<pantokratōr> `o<`o> theós<theos> tôn<`o> patérōn<patēr> `ēmôn<egō> toû<`o> Abraam<Abraam> kaì<kai> Isaak<Isaak> kaì<kai> Iakōb<Iakōb> kaì<kai> toû<`o> spérmatos<sperma> autôn<autos> toû<`o> dikaìou<dikaios> "],
[12002,"`o<`o> poièsas<poieō> tón<`o> ouranón<ouranos> kaì<kai> tèn<`o> gên<gē> sùn<sun> pantì<pas> tôj<`o> kósmōj<kosmos> autôn<autos> "],
[12003,"`o<`o> pedèsas<pedaō> tèn<`o> thàlassan<thalassa> tôj<`o> lógōj<logos> toû<`o> prostàgmatós<prostagma> sou<su> `o<`o> kleìsas<kleiō> tèn<`o> àbusson<abussos> kaì<kai> sfragisàmenos<sfragizō> tôj<`o> foberôj<foberos> kaì<kai> endóxōj<endoxos> onómatì<onoma> sou<su> "],
[12004,"`ón<`os> pànta<pas> frìttei<frittō> kaì<kai> trémei<tremō> apó<apo> prosòpou<prosōpon> dunàmeòs<dunamis> sou<su> "],
[12005,"`óti<`oti> àstektos<astektos> `ē<`o> megaloprépeia<megaloprepeia> tês<`o> dóxēs<doxa> sou<su> kaì<kai> anupóstatos<anupostatos> `ē<`o> orgè<orgē> tês<`o> epì<epi> `amartōloùs<`amartōlos> apeilês<apeilē> sou<su> "],
[12006,"amétrētón<ametrētos> te<te> kaì<kai> anexichnìaston<anexichniastos> tó<`o> éleos<eleos> tês<`o> epaggelìas<epaggelia> sou<su> "],
[12007,"`óti<`oti> sù<su> eî<eimi> kùrios<kurios> `ùpsistos<`upsistos> eùsplagchnos<eusplagchnos> makróthumos<makrothumos> kaì<kai> poluéleos<polueleos> kaì<kai> metanoôn<metanoeō> epì<epi> kakìais<kakia> anthròpōn<anthrōpos> "],
[12008,"sù<su> oûn<oun> kùrie<kurios> `o<`o> theós<theos> tôn<`o> dikaìōn<dikaios> ouk<ou'> éthou<tithēmi> metànoian<metanoia> dikaìois<dikaios> tôj<`o> Abraam<Abraam> kaì<kai> Isaak<Isaak> kaì<kai> Iakōb<Iakōb> toîs<`o> ouch<ou'> `ēmartēkósin<`amartanō> soi<su> all'<alla> éthou<tithēmi> metànoian<metanoia> emoì<egō> tôj<`o> `amartōlôj<`amartōlos> "],
[12009,"dióti<dioti> `èmarton<`amartanō> `upér<`uper> arithmón<arithmos> psàmmou<psammos> thalàssēs<thalassa> eplèthunan<plēthunō> `ai<`o> anomìai<anomia> mou<egō> kùrie<kurios> eplèthunan<plēthunō> kaì<kai> ouk<ou'> eimì<eimi> àxios<axios> atenìsai<atenizō> kaì<kai> ideîn<`oraō> tó<`o> `ùpsos<`upsos> toû<`o> ouranoû<ouranos> apó<apo> plèthous<plēthos> tôn<`o> adikiôn<adikia> mou<egō> "],
[12010,"katakamptómenos<katakamptō> pollôj<polus> desmôj<desmos> sidèrou<sidēros> eis<eis> tó<`o> ananeûsaì<ananeuō> me<egō> `upér<`uper> `amartiôn<`amartia> mou<egō> kaì<kai> ouk<ou'> éstin<eimi> moi<egō> ànesis<anesis> dióti<dioti> paròrgisa<parorgizō> tón<`o> thumón<thumos> sou<su> kaì<kai> tó<`o> ponērón<ponēros> enòpión<enōpion> sou<su> epoìēsa<poieō> stèsas<`istēmi> bdelùgmata<bdelugma> kaì<kai> plēthùnas<plēthunō> prosochthìsmata<prosochthisma> "],
[12011,"kaì<kai> nûn<nun> klìnō<klinō> gónu<gonu> kardìas<kardia> deómenos<deomai> tês<`o> parà<para> soû<su> chrēstótētos<chrēstotēs> "],
[12012,"`ēmàrtēka<`amartanō> kùrie<kurios> `ēmàrtēka<`amartanō> kaì<kai> tàs<`o> anomìas<anomia> mou<egō> egò<egō> ginòskō<ginōskō> "],
[12013,"aitoûmai<aiteō> deómenós<deomai> sou<su> ànes<aniēmi> moi<egō> kùrie<kurios> ànes<aniēmi> moi<egō> mè<mē> sunapolésējs<sunapollumi> me<egō> taîs<`o> anomìais<anomia> mou<egō> mēdé<mēde> eis<eis> tón<`o> aiôna<aiōn> mēnìsas<mēniō> tērèsējs<tēreō> tà<`o> kakà<kakos> moi<egō> mēdé<mēde> katadikàsējs<katadikazō> me<egō> en<en> toîs<`o> katōtàtois<katōtatos> tês<`o> gês<gē> `óti<`oti> sù<su> eî<eimi> kùrie<kurios> `o<`o> theós<theos> tôn<`o> metanooùntōn<metanoeō> "],
[12014,"kaì<kai> en<en> emoì<egō> deìxējs<deiknumi> tèn<`o> agathōsùnēn<agathōsunē> sou<su> `óti<`oti> anàxion<anaxios> ónta<eimi> sòseis<sōjzō> me<egō> katà<kata> tó<`o> polù<polus> éleós<eleos> sou<su> "],
[12015,"kaì<kai> ainésō<aineō> se<su> dià<dia> pantós<pas> en<en> taîs<`o> `ēmérais<`ēmera> tês<`o> zōês<zōē> mou<egō> `óti<`oti> sé<su> `umneî<`umneō> pâsa<pas> `ē<`o> dùnamis<dunamis> tôn<`o> ouranôn<ouranos> kaì<kai> soû<su> estin<eimi> `ē<`o> dóxa<doxa> eis<eis> toùs<`o> aiônas<aiōn> amēn<amēn> "],
[13001,""],
[13002,""],
[13003,""],
[13004,""],
[13005,""],
[13006,""],
[13007,""],
[13008,""],
[13009,""],
[13010,""],
[13011,""],
[13012,""],
[13013,""],
[13014,""],
[13015,""],
[13016,""],
[13017,""],
[13018,""],
[13019,""],
[13020,""],
[13021,""],
[13022,""],
[13023,""],
[13024,""],
[13025,""],
[13026,""],
[13027,""],
[13028,""],
[13029,"[proseuchè<proseuchē> Sumeōn]<Sumeōn> nûn<nun> apolùeis<apoluō> tón<`o> doûlón<doulos> sou<su> déspota<despotēs> katà<kata> tó<`o> `rêmà<`rēma> sou<su> en<en> eirènēj<eirēnē> "],
[13030,"`óti<`oti> eîdon<`oraō> `oi<`o> ofthalmoì<ofthalmos> mou<egō> tó<`o> sōtèrión<sōtērion> sou<su> "],
[13031,"`ó<`os> `ētoìmasas<`etoimazō> katà<kata> prósōpon<prosōpon> pàntōn<pas> tôn<`o> laôn<laos> "],
[13032,"fôs<fōs> eis<eis> apokàlupsin<apokalupsis> ethnôn<ethnos> kaì<kai> dóxan<doxa> laoû<laos> sou<su> Israēl<Israēl> "],
[14001,"[`ùmnos<`umnos> `eōthinós]<`eōthinos> dóxa<doxa> en<en> `upsìstois<`upsistos> theôj<theos> "],
[14002,"kaì<kai> epì<epi> gês<gē> eirènē<eirēnē> "],
[14003,"en<en> anthròpois<anthrōpos> eudokìa<eudokia> "],
[14004,"ainoûmén<aineō> se<su> "],
[14005,"eulogoûmén<eulogeō> se<su> "],
[14006,"proskunoûmén<proskuneō> se<su> "],
[14007,"doxologoûmén<doxologeō> se<su> "],
[14008,"eucharistoûmén<eucharisteō> soi<su> "],
[14009,"dià<dia> tèn<`o> megàlēn<megas> sou<su> dóxan<doxa> "],
[14010,"kùrie<kurios> basileû<basileus> "],
[14011,"epourànie<epouranios> "],
[14012,"theé<theos> patèr<patēr> pantokràtōr<pantokratōr> "],
[14013,"kùrie<kurios> `uié<`uios> monogenè<monogenēs> "],
[14014,"Iēsoû<Iēsous> Christé<Christos> "],
[14015,"kaì<kai> `àgion<`agios> pneûma<pneuma> "],
[14016,"kùrie<kurios> `o<`o> theós<theos> "],
[14017,"`o<`o> amnós<amnos> toû<`o> theoû<theos> "],
[14018,"`o<`o> `uiós<`uios> toû<`o> patrós<patēr> "],
[14019,"`o<`o> aìrōn<airō> tàs<`o> `amartìas<`amartia> toû<`o> kósmou<kosmos> "],
[14020,"eléēson<eleeō> `ēmâs<egō> "],
[14021,"`o<`o> aìrōn<airō> tàs<`o> `amartìas<`amartia> toû<`o> kósmou<kosmos> "],
[14022,"prósdexai<prosdechomai> tèn<`o> déēsin<deēsis> `ēmôn<egō> "],
[14023,"`o<`o> kathèmenos<kathēmai> en<en> dexiâj<dexios> toû<`o> patrós<patēr> "],
[14024,"eléēson<eleeō> `ēmâs<egō> "],
[14025,"`óti<`oti> sù<su> eî<eimi> mónos<monos> `àgios<`agios> "],
[14026,"sù<su> eî<eimi> mónos<monos> kùrios<kurios> "],
[14027,"Iēsoûs<Iēsous> Christós<Christos> "],
[14028,"eis<eis> dóxan<doxa> theoû<theos> patrós<patēr> amēn<amēn> "],
[14029,"kath'<kata> `ekàstēn<`ekastos> `ēméran<`ēmera> eulogèsō<eulogeō> se<su> "],
[14030,"kaì<kai> ainésō<aineō> tó<`o> ónomà<onoma> sou<su> eis<eis> tón<`o> aiôna<aiōn> "],
[14031,"kaì<kai> eis<eis> tón<`o> aiôna<aiōn> toû<`o> aiônos<aiōn> "],
[14032,"kataxìōson<kataxioō> kùrie<kurios> kaì<kai> tèn<`o> `ēméran<`ēmera> taùtēn<`outos> "],
[14033,"anamartètous<anamartētos> fulachthênai<fulassō> `ēmâs<egō> "],
[14034,"eulogētós<eulogētos> eî<eimi> kùrie<kurios> `o<`o> theós<theos> tôn<`o> patérōn<patēr> `ēmôn<egō> "],
[14035,"kaì<kai> ainetón<ainetos> kaì<kai> dedoxasménon<doxazō> tó<`o> ónomà<onoma> sou<su> eis<eis> toùs<`o> aiônas<aiōn> amēn<amēn> "],
[14036,"eulogētós<eulogētos> eî<eimi> kùrie<kurios> dìdaxón<didaskō> me<egō> tà<`o> dikaiòmatà<dikaiōma> sou<su> "],
[14037,"eulogētós<eulogētos> eî<eimi> kùrie<kurios> dìdaxón<didaskō> me<egō> tà<`o> dikaiòmatà<dikaiōma> sou<su> "],
[14038,"eulogētós<eulogētos> eî<eimi> kùrie<kurios> dìdaxón<didaskō> me<egō> tà<`o> dikaiòmatà<dikaiōma> sou<su> "],
[14039,"kùrie<kurios> katafugè<katafugē> egenèthēs<ginomai> `ēmîn<egō> en<en> geneâj<genea> kaì<kai> geneâj<genea> "],
[14040,"egò<egō> eîpa<legō> kùrie<kurios> eléēsón<eleeō> me<egō> "],
[14041,"ìasai<iaomai> tèn<`o> psuchèn<psuchē> mou<egō> `óti<`oti> `èmartón<`amartanō> soi<su> "],
[14042,"kùrie<kurios> prós<pros> sé<su> katéfuga<katafeugō> "],
[14043,"dìdaxón<didaskō> me<egō> toû<`o> poieîn<poieō> tó<`o> thélēmà<thelēma> sou<su> `óti<`oti> sù<su> eî<eimi> `o<`o> theós<theos> mou<egō> "],
[14044,"`óti<`oti> parà<para> soì<su> Pēgè<pēgē> zōês<zōē> "],
[14045,"en<en> tôj<`o> fōtì<fōs> sou<su> opsómetha<`oraō> fôs<fōs> "],
[14046,"paràteinon<parateinō> tó<`o> éleós<eleos> sou<su> toîs<`o> ginòskousìn<ginōskō> se<su> "]
])
