cbBib("grk","odes",[
[1,1,"Ö¸dè_ö¸dë Möuséös_Möusës en_en tê¸_`o exódö¸_exodos á¸sömen_a¸dö tô¸_`o kuríö¸_kurios endóxös_endoxös gàr_gar dedóxastai_doxazö `íppon_`ippos kaì_kai anabátën_anabatës érripsen_`riptö eis_eis thálassan_thalassa "],
[1,2,"boëthós_boëthos kaì_kai skepastès_skepastës egénetó_gignomai moi_egö eis_eis sötërían_sötëria `oûtós_`outos mou_egö theós_theos kaì_kai doxásö_doxazö autón_autos theós_theos toû_`o patrós_patër mou_egö kaì_kai `upsòsö_`upsoö autón_autos "],
[1,3,"kúrios_kurios suntríbön_tribö~sun polémous_polemos kúrios_kurios ónoma_onoma autô¸_autos "],
[1,4,"`ármata_`arma Faraö_Faraö kaì_kai tèn_`o dúnamin_dunamis autoû_autos érripsen_`riptö eis_eis thálassan_thalassa epiléktous_epilektos anabátas_anabatës tristátas_tristatës katepóntisen_pontizö~kata en_en eruthrâ¸_eruthros thalássë¸_thalassa "],
[1,5,"póntö¸_pontos ekálupsen_kaluptö autoús_autos katédusan_duö~kata eis_eis buthón_buthos `öseì_`ösei líthos_lithos "],
[1,6,"`ë_`o dexiá_dexios sou_su kúrie_kurios dedóxastai_doxazö en_en ischúi_ischus `ë_`o dexiá_dexios sou_su cheír_cheir kúrie_kurios éthrausen_thrauö echthroús_echthros "],
[1,7,"kaì_kai tô¸_`o plèthei_plëthos tês_`o dóxës_doxa sou_su sunétripsas_tribö~sun toùs_`o `upenantíous_`upenantios apésteilas_stellö~apo tèn_`o orgèn_orgë sou_su kaì_kai katéfagen_esthiö~kata autoùs_autos `ös_`ös kalámën_kalamë "],
[1,8,"kaì_kai dià_dia pneúmatos_pneuma toû_`o thumoû_thumos sou_su diéstë_`istëmi~dia tó_`o `údör_`udör epágë_pëgnumi `öseì_`ösei teîchos_teichos tà_`o `údata_`udör epágë_pëgnumi tà_`o kúmata_kuma en_en mésö¸_mesos tês_`o thalássës_thalassa "],
[1,9,"eîpen_eipon `o_`o echthrós_echthros diòxas_diökö katalèmpsomai_lambanö~kata meriô_merizö skûla_skulon emplèsö_pimplëmi~en psuchèn_psuchë mou_egö anelô_`aireö~ana tê¸_`o machaírë¸_machaira mou_egö kurieúsei_kurieuö `ë_`o cheír_cheir mou_egö "],
[1,10,"apésteilas_stellö~apo tó_`o pneûmá_pneuma sou_su ekálupsen_kaluptö autoùs_autos thálassa_thalassa édusan_duö `öseì_`ösei mólibos_molibos en_en `údati_`udör sfodrô¸_sfodros "],
[1,11,"tís_tis `ómoiós_`omoios soi_su en_en theoîs_theos kúrie_kurios tís_tis `ómoiós_`omoios soi_su dedoxasménos_doxazö en_en `agíois_`agios thaumastós_thaumastos en_en dóxais_doxa poiôn_poieö térata_teras "],
[1,12,"exéteinas_teinö~ek tèn_`o dexián_dexios sou_su kaì_kai katépien_pinö~kata autoùs_autos `ë_`o gê_gë "],
[1,13,"`ödègësas_`odëgeö tê¸_`o dikaiosúnë¸_dikaiosunë sou_su tón_`o laón_laos sou_su toûton_`outos `ón_`os elutròsö_luö parekálesas_kaleö~para tê¸_`o ischúi_ischus sou_su eis_eis katáluma_kataluma `ágión_`agios sou_su "],
[1,14,"èkousan_akouö éthnë_ethnos kaì_kai örgísthësan_orgizö ödînes_ödin élabon_lambanö katoikoûntas_oikeö~kata Fulistiim_Fulistiim "],
[1,15,"tóte_tote éspeusan_speudö `ëgemónes_`ëgemön Edöm_Edöm kaì_kai árchontes_archön Möabitôn_Möabitës élaben_lambanö autoùs_autos trómos_tromos etákësan_tëkö pántes_pas `oi_`o katoikoûntes_oikeö~kata Chanaan_Chanaan "],
[1,16,"epipésoi_piptö~epi ep'_epi autoùs_autos fóbos_fobos kaì_kai trómos_tromos megéthei_megethos brachíonós_brachiön sou_su apolithöthètösan_lithoö~apo `éös_`eös àn_an parélthë¸_erchomai~para `o_`o laós_laos sou_su kúrie_kurios `éös_`eös àn_an parélthë¸_erchomai~para `o_`o laós_laos sou_su `oûtos_`outos `ón_`os ektèsö_ktaomai "],
[1,17,"eisagagòn_agö~eis katafúteuson_futeuö~kata autoùs_autos eis_eis óros_oros klëronomías_klëronomia sou_su eis_eis `étoimon_`etoimos katoikëtèrión_katoikëtërion sou_su `ó_`os kateirgásö_ergazomai~kata kúrie_kurios `agíasma_`agiasma kúrie_kurios `ó_`os `ëtoímasan_`etoimazö `ai_`o cheîrés_cheir sou_su "],
[1,18,"kúrios_kurios basileúön_basileuö tón_`o aiôna_aiön kaì_kai ep'_epi aiôna_aiön kaì_kai éti_eti "],
[1,19,"`óti_`oti eisêlthen_erchomai~eis `íppos_`ippos Faraö_Faraö sùn_sun `ármasin_`arma kaì_kai anabátais_anabatës eis_eis thálassan_thalassa kaì_kai epègagen_agö~epi ep'_epi autoùs_autos kúrios_kurios tó_`o `údör_`udör tês_`o thalássës_thalassa `oi_`o dé_de `uioì_`uios Israël_Israël eporeúthësan_poreuomai dià_dia xërâs_xëros en_en mésö¸_mesos tês_`o thalássës_thalassa "],
[2,1,"ö¸dè_ö¸dë Möuséös_Möusës en_en tô¸_`o Deuteronomíö¸_Deuteronomion próseche_echö~pros ourané_ouranos kaì_kai lalèsö_laleö kaì_kai akouétö_akouö gê_gë `rèmata_`rëma ek_ek stómatós_stoma mou_egö "],
[2,2,"prosdokásthö_dokaö~pros `ös_`ös `uetós_`uetos tó_`o apófthegmá_apofthegma mou_egö kaì_kai katabètö_bainö~kata `ös_`ös drósos_drosos tà_`o `rèmatá_`rëma mou_egö `öseì_`ösei ómbros_ombros ep'_epi ágröstin_agröstis kaì_kai `öseì_`ösei nifetós_nifetos epì_epi chórton_chortos "],
[2,3,"`óti_`oti ónoma_onoma kuríou_kurios ekálesa_kaleö dóte_didömi megalösúnën_megalösunë tô¸_`o theô¸_theos `ëmôn_egö "],
[2,4,"theós_theos alëthinà_alëthinos tà_`o érga_ergon autoû_autos kaì_kai pâsai_pas `ai_`o `odoì_`odos autoû_autos krísis_krisis theós_theos pistós_pistos kaì_kai ouk_ou éstin_eimi adikía_adikia díkaios_dikaios kaì_kai `ósios_`osios kúrios_kurios "],
[2,5,"`ëmártosan_`amartanö ouk_ou autô¸_autos tékna_teknon mömëtá_mömëtos geneà_genea skolià_skolios kaì_kai diestramménë_strefö~dia "],
[2,6,"taûta_`outos kuríö¸_kurios antapodídote_didömi~antiapo `oútö_`outös laós_laos mörós_möros kaì_kai ouchì_ou sofós_sofos ouk_ou autós_autos `oûtós_`outos sou_su patèr_patër ektèsató_ktaomai se_su kaì_kai epoíësén_poieö se_su kaì_kai éktisén_ktizö se_su "],
[2,7,"mnèsthëte_mimnëskö `ëméras_`ëmera aiônos_aiön súnete_sunetos étë_etos geneâs_genea geneôn_genea eperòtëson_erötaö~epi tón_`o patéra_patër sou_su kaì_kai anaggeleî_aggellö~ana soi_su toùs_`o presbutérous_presbuteros sou_su kaì_kai eroûsín_eipon soi_su "],
[2,8,"`óte_`ote diemérizen_merizö~dia `o_`o `úpsistos_`upsistos éthnë_ethnos `ös_`ös diéspeiren_speirö~dia `uioùs_`uios Adam_Adam éstësen_`istëmi `ória_`orion ethnôn_ethnos katà_kata arithmón_arithmos aggélön_aggelos theoû_theos "],
[2,9,"kaì_kai egenèthë_gignomai merìs_meris kuríou_kurios laós_laos autoû_autos Iaköb_Iaköb schoínisma_schoinisma klëronomías_klëronomia autoû_autos Israël_Israël "],
[2,10,"autárkësen_autarkeö autón_autos en_en tê¸_`o erèmö¸_erëmos en_en dípsei_dipsos kaúmatos_kauma en_en anúdrö¸_anudros ekúklösen_kukloö autón_autos kaì_kai epaídeusen_paideuö autón_autos kaì_kai diefúlaxen_fulassö~dia autón_autos `ös_`ös kórën_korë ofthalmoû_ofthalmos "],
[2,11,"`ös_`ös aetós_aetos skepásai_skepazö nossiàn_nossia autoû_autos kaì_kai epì_epi toîs_`o neossoîs_neossos autoû_autos epepóthësen_peithö dieìs_`iëmi~dia tàs_`o ptérugas_pterux autoû_autos edéxato_dechomai autoùs_autos kaì_kai anélaben_lambanö~ana autoùs_autos epì_epi tôn_`o metafrénön_metafrenon autoû_autos "],
[2,12,"kúrios_kurios mónos_monos êgen_agö autoús_autos kaì_kai ouk_ou ên_eimi met'_meta autôn_autos theós_theos allótrios_allotrios "],
[2,13,"anebíbasen_bibazö~ana autoùs_autos epì_epi tèn_`o ischùn_ischus tês_`o gês_gë epsòmisen_psömizö autoùs_autos genèmata_genëma agrôn_agros ethèlasan_thëlazö méli_meli ek_ek pétras_petra kaì_kai élaion_elaion ek_ek stereâs_stereos pétras_petra "],
[2,14,"boúturon_bouturon boôn_bous kaì_kai gála_gala probátön_probaton metà_meta stéatos_stear arnôn_arnos kaì_kai kriôn_krios `uiôn_`uios taúrön_tauros kaì_kai trágön_tragos metà_meta stéatos_stear nefrôn_nefros puroû_puros kaì_kai `aîma_`aima stafulês_stafulë épion_pinö oînon_oinos "],
[2,15,"kaì_kai éfagen_esthiö Iaköb_Iaköb kaì_kai eneplèsthë_pimplëmi~en kaì_kai apeláktisen_laktizö~apo `o_`o ëgapëménos_agapaö elipánthë_lipainö epachúnthë_pachunö eplatúnthë_platunö kaì_kai egkatélipen_leipö~enkata theón_theos tón_`o poièsanta_poieö autón_autos kaì_kai apéstë_`istëmi~apo apó_apo theoû_theos sötêros_sötër autoû_autos "],
[2,16,"paròxunán_oxunö~para me_egö ep'_epi allotríois_allotrios en_en bdelúgmasin_bdelugma autôn_autos exepíkranán_krainö~ekepi me_egö "],
[2,17,"éthusan_thuö daimoníois_daimonion kaì_kai ou_ou theô¸_theos theoîs_theos `oîs_`os ouk_ou è¸deisan_oida kainoì_kainos kaì_kai prósfatoi_prosfatos `èkasin_`ëkö `oùs_`os ouk_ou è¸deisan_oida `oi_`o patéres_patër autôn_autos "],
[2,18,"theón_theos tón_`o gennèsantá_gennaö se_su egkatélipes_leipö~enkata kaì_kai epeláthou_lanthanö~epi theoû_theos toû_`o tréfontós_trefö se_su "],
[2,19,"kaì_kai eîden_`oraö kúrios_kurios kaì_kai ezèlösen_zëloö kaì_kai paröxúnthë_oxunö~para di'_dia orgèn_orgë `uiôn_`uios autoû_autos kaì_kai thugatérön_thugatër "],
[2,20,"kaì_kai eîpen_eipon apostrépsö_strefö~apo tó_`o prósöpón_prosöpon mou_egö ap'_apo autôn_autos kaì_kai deíxö_deiknuö tí_tis éstai_eimi autoîs_autos ep'_epi eschátön_eschatos `óti_`oti geneà_genea exestramménë_strefö~ek estín_eimi `uioí_`uios `oîs_`os ouk_ou éstin_eimi pístis_pistis en_en autoîs_autos "],
[2,21,"autoì_autos parezèlösán_zëloö~para me_egö ep'_epi ou_ou theô¸_theos paròrgisán_orgizö~para me_egö en_en toîs_`o eidòlois_eidölon autôn_autos kagò_ka:iegö parazëlòsö_zëloö~para autoùs_autos ep'_epi ouk_ou éthnei_ethnos ep'_epi éthnei_ethnos asunétö¸_asunetos parorgiô_orgizö~para autoús_autos "],
[2,22,"`óti_`oti pûr_pur ekkékautai_kaiö~ek ek_ek toû_`o thumoû_thumos mou_egö kauthèsetai_kaiö `éös_`eös `á¸dou_`a¸dës kátö_katö katafágetai_esthiö~kata gên_gë kaì_kai tà_`o genèmata_genëma autês_autos fléxei_flegö themélia_themelion oréön_oros "],
[2,23,"sunáxö_agö~sun eis_eis autoùs_autos kakà_kakos kaì_kai tà_`o bélë_belos mou_egö suntelésö_teleö~sun eis_eis autoús_autos "],
[2,24,"tëkómenoi_tëkö limô¸_limos kaì_kai bròsei_brösis ornéön_ornis kaì_kai opisthótonos_opisthotonos aníatos_aniatos odóntas_odous thëríön_thërion exapostelô_stellö~ekapo eis_eis autoùs_autos metà_meta thumoû_thumos suróntön_surö epì_epi gês_gë "],
[2,25,"éxöthen_exöthen ateknòsei_ateknoö autoùs_autos máchaira_machaira kaì_kai ek_ek tôn_`o tamieíön_tamieion fóbos_fobos neanískos_neaniskos sùn_sun parthénö¸_parthenos thëlázön_thëlazö metà_meta kathestëkótos_`istëmi~kata presbutérou_presbuteros "],
[2,26,"eîpa_eipon diasperô_speirö~dia autoús_autos paúsö_pauö dè_dë ex_ek anthròpön_anthröpos tó_`o mnëmósunon_mnëmosunon autôn_autos "],
[2,27,"ei_ei mè_më di'_dia orgèn_orgë echthrôn_echthros `ína_`ina mè_më makrochronísösin_makrochronizö kaì_kai `ína_`ina mè_më sunepithôntai_tithëmi~sunepi `oi_`o `upenantíoi_`upenantios mè_më eípösin_eipon `ë_`o cheìr_cheir `ëmôn_egö `upsëlè_`upsëlos kaì_kai ouchì_ou kúrios_kurios epoíësen_poieö taûta_`outos pánta_pas "],
[2,28,"`óti_`oti éthnos_ethnos apolölekós_olluö~apo boulèn_boulë estin_eimi kaì_kai ouk_ou éstin_eimi en_en autoîs_autos epistèmë_epistëmë "],
[2,29,"ouk_ou efrónësan_froneö suniénai_`iëmi~sun taûta_`outos katadexásthösan_dechomai~kata eis_eis tón_`o epiónta_pinö chrónon_chronos "],
[2,30,"pôs_pös diòxetai_diökö `eîs_`eis chilíous_chilioi kaì_kai dúo_duo metakinèsousin_kineö~meta muriádas_murias ei_ei mè_më `o_`o theós_theos apédoto_didömi~apo autoùs_autos kaì_kai `o_`o kúrios_kurios parédöken_didömi~para autoús_autos "],
[2,31,"ou_ou gár_gar eisin_eimi `oi_`o theoì_theos autôn_autos `ös_`ös `o_`o theós_theos `ëmôn_egö `oi_`o dé_de echthroì_echthros `ëmôn_egö anóëtoi_anoëtos "],
[2,32,"ek_ek gàr_gar ampélou_ampelos Sodomön_Sodomön `ë_`o ámpelos_ampelos autôn_autos kaì_kai `ë_`o klëmatìs_klëmatis autôn_autos ek_ek Gomorras_Gomorra `ë_`o stafulè_stafulë autôn_autos stafulè_stafulë cholês_cholë bótrus_botrus pikrías_pikria autoîs_autos "],
[2,33,"thumós_thumos drakóntön_drakön `o_`o oînos_oinos autôn_autos kaì_kai thumós_thumos aspídön_aspis aníatos_aniatos "],
[2,34,"ouk_ou idoù_idou taûta_`outos pánta_pas sunêktai_agö~sun par'_para emoì_egö kaì_kai esfrágistai_sfragizö en_en toîs_`o thësauroîs_thësauros mou_egö "],
[2,35,"en_en `ëméra¸_`ëmera ekdikèseös_ekdikësis antapodòsö_didömi~antiapo en_en kairô¸_kairos `ótan_`otan sfalê¸_sfallö `o_`o poùs_pous autôn_autos `óti_`oti eggùs_eggus `ëméra_`ëmera apöleías_apöleia autôn_autos kaì_kai párestin_eimi~para `étoima_`etoimos `umîn_su "],
[2,36,"`óti_`oti krineî_krinö kúrios_kurios tón_`o laón_laos autoû_autos kaì_kai epì_epi toîs_`o doúlois_doulos autoû_autos paraklëthèsetai_kaleö~para eîden_`oraö gàr_gar autoùs_autos paraleluménous_luö~para kaì_kai ekleloipótas_leipö~ek en_en epagögê¸_epagögë kaì_kai pareiménous_`iëmi~para "],
[2,37,"kaì_kai eîpen_eipon kúrios_kurios poû_pou eisin_eimi `oi_`o theoì_theos autôn_autos ef'_epi `oîs_`os epepoítheisan_peithö ep'_epi autoîs_autos "],
[2,38,"`ôn_`os tó_`o stéar_stear tôn_`o thusiôn_thusia autôn_autos ësthíete_esthiö kaì_kai epínete_pinö tón_`o oînon_oinos tôn_`o spondôn_spondë autôn_autos anastètösan_`istëmi~ana kaì_kai boëthësátösan_boëtheö `umîn_su kaì_kai genëthètösan_gignomai `umîn_su skepastaí_skepastës "],
[2,39,"ídete_`oraö ídete_`oraö `óti_`oti egò_egö eimi_eimi kaì_kai ouk_ou éstin_eimi theós_theos plèn_plën emoû_egö egò_egö apoktenô_kteinö~apo kaì_kai zên_zaö poièsö_poieö patáxö_patassö kagò_ka:iegö iásomai_iaomai kaì_kai ouk_ou éstin_eimi `ós_`os exeleîtai_`aireö~ek ek_ek tôn_`o cheirôn_cheir mou_egö "],
[2,40,"`óti_`oti arô_airö eis_eis tón_`o ouranón_ouranos tèn_`o cheîrá_cheir mou_egö kaì_kai omoûmai_omnumi tê¸_`o dexiâ¸_dexios mou_egö kaì_kai erô_eipon zô_zaö egò_egö eis_eis tón_`o aiôna_aiön "],
[2,41,"`óti_`oti paroxunô_oxunö~para `ös_`ös astrapèn_astrapë tèn_`o máchairán_machaira mou_egö kaì_kai anthéxetai_echö~anti krímatos_krima `ë_`o cheír_cheir mou_egö kaì_kai antapodòsö_didömi~antiapo díkën_dikë toîs_`o echthroîs_echthros kaì_kai toîs_`o misoûsín_miseö me_egö antapodòsö_didömi~antiapo "],
[2,42,"methúsö_methuö tà_`o bélë_belos mou_egö af'_apo `aímatos_`aima kaì_kai `ë_`o máchairá_machaira mou_egö katafágetai_esthiö~kata kréa_kreas af'_apo `aímatos_`aima traumatiôn_traumatias kaì_kai aichmalösías_aichmalösia apó_apo kefalês_kefalë archóntön_archön ethnôn_ethnos "],
[2,43,"eufránthëte_eufrainö ouranoí_ouranos `áma_`ama autô¸_autos kaì_kai proskunësátösan_kuneö~pros autô¸_autos pántes_pas `oi_`o ággeloi_aggelos theoû_theos eufránthëte_eufrainö éthnë_ethnos metà_meta toû_`o laoû_laos autoû_autos kaì_kai enischusátösan_ischuö~en autô¸_autos pántes_pas `uioì_`uios theoû_theos `óti_`oti tó_`o `aîma_`aima tôn_`o `uiôn_`uios autoû_autos ekdikeîtai_dikeö~ek kaì_kai ekdikèsei_dikeö~ek kaì_kai antapodòsei_didömi~antiapo díkën_dikë toîs_`o echthroîs_echthros kaì_kai toîs_`o misoûsin_miseö antapodòsei_didömi~antiapo kaì_kai ekkatharieî_katharizö~ek kúrios_kurios tèn_`o gên_gë toû_`o laoû_laos autoû_autos "],
[3,1,"proseuchè_proseuchë Annas_Anna mëtrós_mëtër Samouël_Samouël estereòthë_strereö `ë_`o kardía_kardia mou_egö en_en kuríö¸_kurios `upsòthë_`upsoö kéras_keras mou_egö en_en theô¸_theos mou_egö eplatúnthë_platunö ep'_epi echthroús_echthros mou_egö tó_`o stóma_stoma mou_egö ëufránthën_eufrainö en_en sötëría¸_sötëria sou_su "],
[3,2,"`óti_`oti ouk_ou éstin_eimi `ágios_`agios `ös_`ös kúrios_kurios kaì_kai ouk_ou éstin_eimi díkaios_dikaios `ös_`ös `o_`o theós_theos `ëmôn_egö ouk_ou éstin_eimi `ágios_`agios plèn_plën soû_su "],
[3,3,"mè_më kauchâsthe_kauchaomai kaì_kai mè_më laleîte_laleö `upsëlá_`upsëlos mëdé_mëde exelthátö_erchomai~ek megalorëmosúnë_megalorrëmosunë ek_ek toû_`o stómatos_stoma `umôn_su `óti_`oti theós_theos gnòseön_gnösis kúrios_kurios kaì_kai theós_theos `etoimázon_`etoimazö epitëdeúmata_epitëdeuma autoû_autos "],
[3,4,"tóxon_toxon dunatôn_dunatos ësthénësen_astheneö kaì_kai asthenoûntes_astheneö periezòsanto_zönnumi~peri dúnamin_dunamis "],
[3,5,"plèreis_plërës ártön_artos ëlattòthësan_alassö kaì_kai `oi_`o peinôntes_peinaö parêkan_`iëmi~para gên_gë `óti_`oti steîra_steira éteken_tiktö `eptá_`epta kaì_kai `ë_`o pollè_polus en_en téknois_teknon ësthénësen_astheneö "],
[3,6,"kúrios_kurios thanatoî_thanatoö kaì_kai zöogoneî_zöogoneö katágei_agö~kata eis_eis `á¸dou_`a¸dës kaì_kai anágei_agö~ana "],
[3,7,"kúrios_kurios ptöchízei_ptöchizö kaì_kai ploutízei_ploutizö tapeinoî_tapeinoö kaì_kai anupsoî_`upsoö~ana "],
[3,8,"anistâ¸_`istëmi~ana apó_apo gês_gë pénëta_penës kaì_kai apó_apo koprías_kopria egeírei_egeirö ptöchón_ptöchos toû_`o kathísai_`izö~kata autón_autos metà_meta dunastôn_dunastës laoû_laos kaì_kai thrónon_thronos dóxës_doxa kataklëronomôn_klëronomeö~kata autoîs_autos "],
[3,9,"didoùs_didömi euchèn_euchë tô¸_`o euchoménö¸_euchomai kaì_kai eulógësen_eulogeö étë_etos dikaíou_dikaios `óti_`oti ouk_ou en_en ischúi_ischus dunatós_dunatos anèr_anër "],
[3,10,"kúrios_kurios asthenê_asthenës poièsei_poieö tón_`o antídikon_antidikos autoû_autos kúrios_kurios `ágios_`agios mè_më kauchásthö_kauchaomai `o_`o sofós_sofos en_en tê¸_`o sofía¸_sofia autoû_autos kaì_kai mè_më kauchásthö_kauchaomai `o_`o dunatós_dunatos en_en tê¸_`o dunámei_dunamis autoû_autos kaì_kai mè_më kauchásthö_kauchaomai `o_`o ploúsios_plousios en_en tô¸_`o ploútö¸_ploutos autoû_autos all'_alla è_ë en_en toútö¸_`outos kauchásthö_kauchaomai `o_`o kauchòmenos_kauchaomai suníein_`iëmi~sun kaì_kai ginòskein_gignöskö tón_`o kúrion_kurios kaì_kai poieîn_poieö kríma_krima kaì_kai dikaiosúnën_dikaiosunë en_en mésö¸_mesos tês_`o gês_gë kúrios_kurios anébë_bainö~ana eis_eis ouranoùs_ouranos kaì_kai ebróntësen_brontaö autós_autos krineî_krinö ákra_akros gês_gë díkaios_dikaios òn_eimi kaì_kai dídösin_didömi ischùn_ischus toîs_`o basileûsin_basileus `ëmôn_egö kaì_kai `upsòsei_`upsoö kéras_keras christoû_christos autoû_autos "],
[4,1,"proseuchè_proseuchë Ambakoum_Ambakoum "],
[4,2,"kúrie_kurios eisakèkoa_akouö~eis tèn_`o akoèn_akoë sou_su kaì_kai efobèthën_fobeö katenóësa_noeö~kata tà_`o érga_ergon sou_su kaì_kai exéstën_`istëmi~ek en_en mésö¸_mesos dúo_duo zò¸ön_zö¸on gnösthèsë¸_gignöskö en_en tô¸_`o eggízein_eggizö tà_`o étë_etos epignösthèsë¸_gignöskö~epi en_en tô¸_`o pareînai_eimi~para tón_`o kairón_kairos anadeichthèsë¸_deiknuö~ana en_en tô¸_`o tarachthênai_tarassö tèn_`o psuchèn_psuchë mou_egö en_en orgê¸_orgë eléous_eleos mnësthèsë¸_mimnëskö "],
[4,3,"`o_`o theós_theos ek_ek Thaiman_Thaiman `èxei_`ëkö kaì_kai `o_`o `ágios_`agios ex_ek órous_oros Faran_Faran kataskíou_kataskios daséös_daseös diápsalma_diapsalma ekálupsen_kaluptö ouranoùs_ouranos `ë_`o aretè_aretë autoû_autos kaì_kai ainéseös_ainesis autoû_autos plèrës_plërës `ë_`o gê_gë "],
[4,4,"kaì_kai féggos_feggos autoû_autos `ös_`ös fôs_fös éstai_eimi kérata_keras en_en chersìn_cheir autoû_autos kaì_kai étheto_tithëmi agápësin_agapësis krataiàn_krataios ischúos_ischus autoû_autos "],
[4,5,"pró_pro prosòpou_prosöpon autoû_autos poreúsetai_poreuomai lógos_logos kaì_kai exeleúsetai_erchomai~ek en_en pedílois_pedilon `oi_`o pódes_pous autoû_autos "],
[4,6,"éstë_`istëmi kaì_kai esaleúthë_saleuö `ë_`o gê_gë epéblepsen_blepö~epi kaì_kai etákë_tëkö éthnë_ethnos diethrúbë_thruptö~dia tà_`o órë_oros bía¸_bia etákësan_tëkö bounoì_bounos aiònioi_aiönios "],
[4,7,"poreías_poreia aiöníous_aiönios autoû_autos antì_anti kópön_kopos eîdon_`oraö skënòmata_skënöma Aithiópön_Aithiops ptoëthèsontai_ptoeö kaì_kai `ai_`o skënaì_skënë gês_gë Madiam_Madiam "],
[4,8,"mè_më en_en potamoîs_potamos örgísthës_orgizö kúrie_kurios è_ë en_en potamoîs_potamos `o_`o thumós_thumos sou_su è_ë en_en thalássë¸_thalassa tó_`o `órmëmá_`ormëma sou_su `óti_`oti epibèsë¸_bainö~epi epì_epi toùs_`o `íppous_`ippos sou_su kaì_kai `ë_`o `ippasía_`ippasia sou_su sötëría_sötëria "],
[4,9,"enteínön_teinö~en enteneîs_teinö~en tó_`o tóxon_toxon sou_su epì_epi skêptra_skëptron légei_legö kúrios_kurios diápsalma_diapsalma potamôn_potamos `ragèsetai_`rëgnunai gê_gë "],
[4,10,"ópsontaí_`oraö se_su kaì_kai ödinèsousin_ödinö laoí_laos skorpízön_skorpizö `údata_`udör poreías_poreia édöken_didömi `ë_`o ábussos_abussos fönèn_fönë autês_autos `úpsos_`upsos fantasías_fantasia autês_autos epèrthë_airö~epi "],
[4,11,"`o_`o `èlios_`ëlios kaì_kai `ë_`o selènë_selënë éstë_`istëmi en_en tê¸_`o táxei_taxis autês_autos eis_eis fôs_fös bolídes_bolis sou_su poreúsontai_poreuomai eis_eis féggos_feggos astrapês_astrapë `óplön_`oplon sou_su "],
[4,12,"en_en apeilê¸_apeilë sou_su oligòseis_oligoö gên_gë kaì_kai en_en thumô¸_thumos katáxeis_agö~kata éthnë_ethnos "],
[4,13,"exêlthes_erchomai~ek eis_eis sötërían_sötëria laoû_laos sou_su toû_`o sôsai_sözö toùs_`o christoús_christos sou_su ébales_ballö eis_eis kefalàs_kefalë anómön_anomos thánaton_thanatos exègeiras_ageirö~ek desmoùs_desmos `éös_`eös trachèlou_trachëlos diápsalma_diapsalma "],
[4,14,"diékopsas_koptö~dia en_en ekstásei_ekstasis kefalàs_kefalë dunastôn_dunastës seisthèsontai_seiö en_en autê¸_autos dianoíxousin_oigö~diaana chalinoùs_chalinos autôn_autos `ös_`ös ésthön_esthiö ptöchós_ptöchos láthra¸_lathra "],
[4,15,"kaì_kai epebíbasas_bibazö~epi eis_eis thálassan_thalassa toùs_`o `íppous_`ippos sou_su tarássontas_tarassö `údata_`udör pollá_polus "],
[4,16,"efulaxámën_fulassö kaì_kai eptoèthë_ptoeö `ë_`o koilía_koilia mou_egö apó_apo fönês_fönë proseuchês_proseuchë cheiléön_cheilos mou_egö kaì_kai eisêlthen_erchomai~eis trómos_tromos eis_eis tà_`o ostâ_osteon mou_egö kaì_kai `upokátöthén_`upokatöthen mou_egö etaráchthë_tarassö `ë_`o `éxis_`exis mou_egö anapaúsomai_pauö~ana en_en `ëméra¸_`ëmera thlípseòs_thlipsis mou_egö toû_`o anabênaí_bainö~ana me_egö eis_eis laón_laos paroikías_paroikia mou_egö "],
[4,17,"dióti_dioti sukê_sukë ou_ou karpoforèsei_karpoforeö kaì_kai ouk_ou éstai_eimi genèmata_genëma en_en taîs_`o ampélois_ampelos pseúsetai_pseudomai érgon_ergon elaías_elaia kaì_kai tà_`o pedía_pedion ou_ou poièsei_poieö brôsin_brösis exélipon_leipö~ek apó_apo bròseös_brösis próbata_probaton kaì_kai ouch_ou `upárchousin_archö~`upo bóes_bous epì_epi fátnais_fatnë exiláseös_exilasis autôn_autos "],
[4,18,"egò_egö dé_de en_en tô¸_`o kuríö¸_kurios agalliásomai_agalliaomai charèsomai_chairö epì_epi tô¸_`o theô¸_theos tô¸_`o sötêrí_sötër mou_egö "],
[4,19,"kúrios_kurios `o_`o theós_theos mou_egö dúnamís_dunamis mou_egö kaì_kai táxei_taxis toùs_`o pódas_pous mou_egö eis_eis suntéleian_sunteleia epì_epi tà_`o `upsëlà_`upsëlos epibibâ¸_bibazö~epi me_egö toû_`o nikêsai_nikaö en_en tê¸_`o ö¸dê¸_ö¸dë autoû_autos "],
[5,1,"proseuchè_proseuchë Ësaiou_Ësaias "],
[5,9,"ek_ek nuktós_nux orthrízei_orthrizö tó_`o pneûmá_pneuma mou_egö prós_pros sé_su `o_`o theós_theos dióti_dioti fôs_fös tà_`o prostágmatá_prostagma sou_su epì_epi tês_`o gês_gë dikaiosúnën_dikaiosunë máthete_manthanö `oi_`o enoikoûntes_oikeö~en epì_epi tês_`o gês_gë "],
[5,10,"pépautai_pauö gàr_gar `o_`o asebès_asebës ou_ou mè_më máthë¸_manthanö dikaiosúnën_dikaiosunë epì_epi tês_`o gês_gë alètheian_alëtheia ou_ou mè_më poièsei_poieö arthètö_airö `o_`o asebès_asebës `ína_`ina mè_më ídë¸_`oraö tèn_`o dóxan_doxa kuríou_kurios "],
[5,11,"kúrie_kurios `upsëlós_`upsëlos sou_su `o_`o brachíön_brachiön kaì_kai ouk_ou è¸deisan_oida gnóntes_gignöskö dé_de aischunthètösan_aischunö zêlos_zëlos lèmpsetai_lambanö laón_laos apaídeuton_apaideutos kaì_kai nûn_nun pûr_pur toùs_`o `upenantíous_`upenantios édetai_esthiö "],
[5,12,"kúrie_kurios `o_`o theós_theos `ëmôn_egö eirènën_eirënë dós_didömi `ëmîn_egö pánta_pas gàr_gar apédökas_didömi~apo `ëmîn_egö "],
[5,13,"kúrie_kurios `o_`o theós_theos `ëmôn_egö ktêsai_ktaomai `ëmâs_egö kúrie_kurios ektós_ektos soû_su állon_allos ouk_ou oídamen_oida tó_`o ónomá_onoma sou_su onomázomen_onomazö "],
[5,14,"`oi_`o dé_de nekroì_nekros zöèn_zöë ou_ou mè_më ídösin_`oraö oudé_oude iatroì_iatros ou_ou mè_më anastèsousin_`istëmi~ana dià_dia toûto_`outos epègages_agö~epi kaì_kai apòlesas_olluö~apo kaì_kai êras_airö pân_pas ársen_arsën autôn_autos "],
[5,15,"prósthes_tithëmi~pros autoîs_autos kaká_kakos kúrie_kurios prósthes_tithëmi~pros kakà_kakos toîs_`o endóxois_endoxos tês_`o gês_gë "],
[5,16,"kúrie_kurios en_en thlípsei_thlipsis emnèsthën_mimnëskö sou_su en_en thlípsei_thlipsis mikrâ¸_mikros `ë_`o paideía_paideia sou_su `ëmîn_egö "],
[5,17,"kaì_kai `ös_`ös `ë_`o ödínousa_ödinö eggízei_eggizö toû_`o tekeîn_tiktö kaì_kai epì_epi tê¸_`o ödîni_ödin autês_autos ekékraxen_krazö `oútös_`outös egenèthëmen_gignomai tô¸_`o agapëtô¸_agapëtos sou_su "],
[5,18,"dià_dia tón_`o fóbon_fobos sou_su kúrie_kurios en_en gastrì_gastër elábomen_lambanö kaì_kai ödinèsamen_ödinö kaì_kai etékomen_tiktö pneûma_pneuma sötërías_sötëria sou_su epoièsamen_poieö epì_epi tês_`o gês_gë ou_ou pesoúmetha_piptö allà_alla pesoûntai_piptö `oi_`o enoikoûntes_oikeö~en epì_epi tês_`o gês_gë "],
[5,19,"anastèsontai_`istëmi~ana `oi_`o nekroí_nekros kaì_kai egerthèsontai_egeirö `oi_`o en_en toîs_`o mnëmeíois_mnëmeion kaì_kai eufranthèsontai_eufrainö `oi_`o en_en tê¸_`o gê¸_gë `ë_`o gàr_gar drósos_drosos `ë_`o parà_para soû_su íama_iama autoîs_autos estin_eimi `ë_`o dé_de gê_gë tôn_`o asebôn_asebës peseîtai_piptö "],
[5,20,"bádize_badizö laós_laos mou_egö eíselthe_erchomai~eis eis_eis tà_`o tamíeiá_tamieion sou_su apókleison_kleiö~apo tèn_`o thúran_thura sou_su apokrúbëthi_kruptö~apo mikrón_mikros `óson_`osos `óson_`osos `éös_`eös àn_an parélthë¸_erchomai~para `ë_`o orgè_orgë kuríou_kurios "],
[6,1,"proseuchè_proseuchë Iöna_Iöna "],
[6,3,"ebóësa_boaö en_en thlípsei_thlipsis mou_egö prós_pros kúrion_kurios tón_`o theón_theos mou_egö kaì_kai eisèkousén_akouö~eis mou_egö ek_ek koilías_koilia `á¸dou_`a¸dës kraugês_kraugë mou_egö èkousas_akouö fönês_fönë mou_egö "],
[6,4,"apérripsás_`riptö~apo me_egö eis_eis báthë_bathos kardías_kardia thalássës_thalassa kaì_kai potamoí_potamos me_egö ekúklösan_kukloö pántes_pas `oi_`o meteörismoí_meteörismos sou_su kaì_kai tà_`o kúmatá_kuma sou_su ep'_epi emé_egö diêlthon_erchomai~dia "],
[6,5,"kagò_ka:iegö eîpa_eipon apôsmai_ötheö~apo ex_ek ofthalmôn_ofthalmos sou_su âra_ara prosthèsö_tithëmi~pros toû_`o epiblépsai_blepö~epi prós_pros naón_naos tón_`o `ágión_`agios sou_su "],
[6,6,"periechúthë_cheö~peri moi_egö `údör_`udör `éös_`eös psuchês_psuchë mou_egö ábussos_abussos ekúklösén_kukloö me_egö eschátë_eschatos édu_duö `ë_`o kefalè_kefalë mou_egö eis_eis schismàs_schismë oréön_oros "],
[6,7,"katébën_bainö~kata eis_eis gên_gë `ês_`os `oi_`o mochloì_mochlos autês_autos kátochoi_katochos aiònioi_aiönios kaì_kai anabètö_bainö~ana ek_ek fthorâs_fthora `ë_`o zöè_zöë mou_egö kúrie_kurios `o_`o theós_theos mou_egö "],
[6,8,"en_en tô¸_`o ekleípein_leipö~ek tèn_`o psuchèn_psuchë mou_egö ap'_apo emoû_egö toû_`o kuríou_kurios emnèsthën_mimnëskö kaì_kai élthoi_erchomai prós_pros sé_su `ë_`o proseuchè_proseuchë mou_egö eis_eis naón_naos `ágión_`agios sou_su "],
[6,9,"fulassómenoi_fulassö mátaia_mataios kaì_kai pseudê_pseudës éleos_eleos autôn_autos egkatélipon_leipö~enkata "],
[6,10,"egò_egö dé_de metà_meta fönês_fönë ainéseös_ainesis kaì_kai exomologèseös_exomologësis thúsö_thuö soi_su `ósa_`osos ëuxámën_euchomai apodòsö_didömi~apo soi_su eis_eis sötërían_sötëria mou_egö tô¸_`o kuríö¸_kurios "],
[7,1,"proseuchè_proseuchë Azariou_Azarias "],
[7,26,"eulogëtós_eulogëtos eî_eimi kúrie_kurios `o_`o theós_theos tôn_`o patérön_patër `ëmôn_egö kaì_kai ainetón_ainetos kaì_kai dedoxasménon_doxazö tó_`o ónomá_onoma sou_su eis_eis toùs_`o aiônas_aiön "],
[7,27,"`óti_`oti díkaios_dikaios eî_eimi epì_epi pâsin_pas `oîs_`os epoíësas_poieö `ëmîn_egö kaì_kai pánta_pas tà_`o érga_ergon sou_su alëthiná_alëthinos kaì_kai eutheîai_euthus `ai_`o `odoí_`odos sou_su kaì_kai pâsai_pas `ai_`o kríseis_krisis sou_su alëtheîs_alëthës "],
[7,28,"kaì_kai krímata_krima alëtheías_alëtheia epoíësas_poieö katà_kata pánta_pas `à_`os epègages_agö~epi `ëmîn_egö kaì_kai epì_epi tèn_`o pólin_polis tèn_`o `agían_`agios tèn_`o tôn_`o patérön_patër `ëmôn_egö Ierousalëm_Ierousalëm `óti_`oti en_en alëtheía¸_alëtheia kaì_kai krísei_krisis epègages_agö~epi taûta_`outos pánta_pas dià_dia tàs_`o `amartías_`amartia `ëmôn_egö "],
[7,29,"`óti_`oti `ëmártomen_`amartanö kaì_kai ënomèsamen_anomeö apostênai_`istëmi~apo apó_apo soû_su kaì_kai exëmártomen_`amartanö~ek en_en pâsin_pas kaì_kai tôn_`o entolôn_entolë sou_su ouk_ou ëkoúsamen_akouö "],
[7,30,"oudé_oude sunetërèsamen_tëreö~sun oudé_oude epoièsamen_poieö kathòs_kathös eneteílö_tellomai~en `ëmîn_egö `ína_`ina eû_eu `ëmîn_egö génëtai_gignomai "],
[7,31,"kaì_kai pánta_pas `ósa_`osos epègages_agö~epi `ëmîn_egö kaì_kai pánta_pas `ósa_`osos epoíësas_poieö `ëmîn_egö en_en alëthinê¸_alëthinos krísei_krisis epoíësas_poieö "],
[7,32,"kaì_kai parédökas_didömi~para `ëmâs_egö eis_eis cheîras_cheir echthrôn_echthros anómön_anomos echthístön_echthros apostatôn_apostatës kaì_kai basileî_basileus adíkö¸_adikos kaì_kai ponërotátö¸_ponëros parà_para pâsan_pas tèn_`o gên_gë "],
[7,33,"kaì_kai nûn_nun ouk_ou éstin_eimi `ëmîn_egö anoîxai_oigö~ana tó_`o stóma_stoma aischúnë_aischunë kaì_kai óneidos_oneidos egenèthë_gignomai toîs_`o doúlois_doulos sou_su kaì_kai toîs_`o seboménois_sebomai se_su "],
[7,34,"mè_më dè_dë paradô¸s_didömi~para `ëmâs_egö eis_eis télos_telos dià_dia tó_`o ónomá_onoma sou_su kaì_kai mè_më diaskedásë¸s_skedazö~dia tèn_`o diathèkën_diathëkë sou_su "],
[7,35,"kaì_kai mè_më apostèsë¸s_`istëmi~apo tó_`o éleós_eleos sou_su af'_apo `ëmôn_egö di'_dia Abraam_Abraam tón_`o ëgapëménon_agapaö `upó_`upo soû_su kaì_kai dià_dia Isaak_Isaak tón_`o doûlón_doulos sou_su kaì_kai Israël_Israël tón_`o `ágión_`agios sou_su "],
[7,36,"`oîs_`os elálësas_laleö prós_pros autoùs_autos légön_legö plëthûnai_plëthunö tó_`o spérma_sperma autôn_autos `ös_`ös tà_`o ástra_astron toû_`o ouranoû_ouranos kaì_kai `ös_`ös tèn_`o ámmon_ammos tèn_`o parà_para tó_`o cheîlos_cheilos tês_`o thalássës_thalassa "],
[7,37,"`óti_`oti déspota_despotës esmikrúnthëmen_smikrunö parà_para pánta_pas tà_`o éthnë_ethnos kaí_kai esmen_eimi tapeinoì_tapeinos en_en pásë¸_pas tê¸_`o gê¸_gë sèmeron_sëmeron dià_dia tàs_`o `amartías_`amartia `ëmôn_egö "],
[7,38,"kaì_kai ouk_ou éstin_eimi en_en tô¸_`o kairô¸_kairos toútö¸_`outos árchön_archön kaì_kai profètës_profëtës kaì_kai `ëgoúmenos_`ëgeomai oudé_oude `olokaútösis_`olokautösis oudé_oude thusía_thusia oudé_oude prosforà_prosfora oudé_oude thumíama_thumiama ou_ou tópos_topos toû_`o karpôsai_karpoö enòpión_enöpion sou_su kaì_kai `eureîn_`euriskö éleos_eleos "],
[7,39,"all'_alla en_en psuchê¸_psuchë suntetrimménë¸_tribö~sun kaì_kai pneúmati_pneuma tapeinòseös_tapeinösis prosdechtheíëmen_dechomai~pros `ös_`ös en_en `olokautòmasin_`olokautöma kriôn_krios kaì_kai taúrön_tauros kaì_kai `ös_`ös en_en muriásin_murias arnôn_arnos piónön_piön "],
[7,40,"`oútös_`outös genésthö_gignomai `ë_`o thusía_thusia `ëmôn_egö enòpión_enöpion sou_su sèmeron_sëmeron kaì_kai ektelésai_teleö~ek ópisthén_opisthen sou_su `óti_`oti ouk_ou éstin_eimi aischúnë_aischunë toîs_`o pepoithósin_peithö epì_epi soí_su "],
[7,41,"kaì_kai nûn_nun exakolouthoûmen_akoloutheö~ek en_en `ólë¸_`olos kardía¸_kardia kaì_kai foboúmethá_fobeö se_su kaì_kai zëtoûmen_zëteö tó_`o prósöpón_prosöpon sou_su mè_më kataischúnë¸s_aischunö~kata `ëmâs_egö "],
[7,42,"allà_alla poíëson_poieö meth'_meta `ëmôn_egö katà_kata tèn_`o epieíkeián_epieikeia sou_su kaì_kai katà_kata tó_`o plêthos_plëthos toû_`o eléou_eleos sou_su "],
[7,43,"kaì_kai exeloû_`aireö~ek `ëmâs_egö katà_kata tà_`o thaumásiá_thaumasios sou_su kaì_kai dós_didömi dóxan_doxa tô¸_`o onómatí_onoma sou_su kúrie_kurios "],
[7,44,"kaì_kai entrapeíësan_trepö~en pántes_pas `oi_`o endeiknúmenoi_deiknuö~en toîs_`o doúlois_doulos sou_su kakà_kakos kaì_kai kataischuntheíësan_aischunö~kata apó_apo pásës_pas dunámeös_dunamis kaì_kai dunasteías_dunasteia kaì_kai `ë_`o ischùs_ischus autôn_autos suntribeíë_tribö~sun "],
[7,45,"kaì_kai gnòtösan_gignöskö `óti_`oti sù_su eî_eimi kúrios_kurios `o_`o theós_theos mónos_monos kaì_kai éndoxos_endoxos ef'_epi `ólën_`olos tèn_`o oikouménën_oikeö "],
[8,1,"`úmnos_`umnos tôn_`o triôn_treis paídön_pais "],
[8,52,"eulogëtós_eulogëtos eî_eimi kúrie_kurios `o_`o theós_theos tôn_`o patérön_patër `ëmôn_egö kaì_kai ainetós_ainetos kaì_kai `uperupsoúmenos_`upsoö~`uper eis_eis toùs_`o aiônas_aiön kaì_kai eulogëménon_eulogeö tó_`o ónoma_onoma tês_`o dóxës_doxa sou_su tó_`o `ágion_`agios kaì_kai `uperainetón_`uperainetos kaì_kai `uperupsoúmenon_`upsoö~`uper eis_eis toùs_`o aiônas_aiön "],
[8,53,"eulogëménos_eulogeö eî_eimi en_en tô¸_`o naô¸_naos tês_`o `agías_`agios dóxës_doxa sou_su kaì_kai `uperumnëtós_`uperumnëtos kaì_kai `uperéndoxos_`uperendoxos eis_eis toùs_`o aiônas_aiön "],
[8,54,"eulogëménos_eulogeö eî_eimi `o_`o blépön_blepö abússous_abussos kathèmenos_`ëmai~kata epì_epi cheroubin_cheroubin kaì_kai `uperainetós_`uperainetos kaì_kai `uperupsoúmenos_`upsoö~`uper eis_eis toùs_`o aiônas_aiön "],
[8,55,"eulogëménos_eulogeö eî_eimi epì_epi thrónou_thronos tês_`o basileías_basileia sou_su kaì_kai `uperumnëtós_`uperumnëtos kaì_kai `uperupsoúmenos_`upsoö~`uper eis_eis toùs_`o aiônas_aiön "],
[8,56,"eulogëménos_eulogeö eî_eimi en_en tô¸_`o stereòmati_stereöma toû_`o ouranoû_ouranos kaì_kai `uperumnëtós_`uperumnëtos kaì_kai `uperéndoxos_`uperendoxos eis_eis toùs_`o aiônas_aiön "],
[8,57,"eulogeîte_eulogeö pánta_pas tà_`o érga_ergon kuríou_kurios tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,58,"eulogeîte_eulogeö ággeloi_aggelos kuríou_kurios tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,59,"eulogeîte_eulogeö ouranoí_ouranos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,60,"eulogeîte_eulogeö `údata_`udör pánta_pas tà_`o `uperánö_`uperanö tôn_`o ouranôn_ouranos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,61,"eulogeîte_eulogeö pâsai_pas `ai_`o dunámeis_dunamis kuríou_kurios tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,62,"eulogeîte_eulogeö `èlios_`ëlios kaì_kai selènë_selënë tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,63,"eulogeîte_eulogeö ástra_astron toû_`o ouranoû_ouranos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,64,"eulogeîte_eulogeö pâs_pas ómbros_ombros kaì_kai drósos_drosos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,65,"eulogeîte_eulogeö pánta_pas tà_`o pneúmata_pneuma tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,66,"eulogeîte_eulogeö pûr_pur kaì_kai kaûma_kauma tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,67,"eulogeîte_eulogeö psûchos_psuchos kaì_kai kaúsön_kaiö tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,68,"eulogeîte_eulogeö drósoi_drosos kaì_kai nifetoí_nifetos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,69,"eulogeîte_eulogeö págos_pagos kaì_kai psûchos_psuchos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,70,"eulogeîte_eulogeö páchnai_pachnë kaì_kai chiónes_chiön tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,71,"eulogeîte_eulogeö núktes_nux kaì_kai `ëmérai_`ëmera tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,72,"eulogeîte_eulogeö fôs_fös kaì_kai skótos_skotos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,73,"eulogeîte_eulogeö astrapaì_astrapë kaì_kai nefélai_nefelë tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,74,"eulogeítö_eulogeö `ë_`o gê_gë tón_`o kúrion_kurios `umneítö_`umneö kaì_kai `uperupsoútö_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,75,"eulogeîte_eulogeö órë_oros kaì_kai bounoí_bounos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,76,"eulogeîte_eulogeö pánta_pas tà_`o fuómena_fuö en_en tê¸_`o gê¸_gë tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,77,"eulogeîte_eulogeö `ai_`o pëgaí_pëgë tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,78,"eulogeîte_eulogeö thálassai_thalassa kaì_kai potamoí_potamos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,79,"eulogeîte_eulogeö kètë_këtos kaì_kai pánta_pas tà_`o kinoúmena_kineö en_en toîs_`o `údasin_`udör tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,80,"eulogeîte_eulogeö pánta_pas tà_`o peteinà_peteinon toû_`o ouranoû_ouranos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,81,"eulogeîte_eulogeö tà_`o thëría_thërion kaì_kai pánta_pas tà_`o ktènë_ktënos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,82,"eulogeîte_eulogeö `uioì_`uios tôn_`o anthròpön_anthröpos tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,83,"eulogeítö_eulogeö Israël_Israël tón_`o kúrion_kurios `umneítö_`umneö kaì_kai `uperupsoútö_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,84,"eulogeîte_eulogeö `iereîs_`iereus kuríou_kurios tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,85,"eulogeîte_eulogeö doûloi_doulos kuríou_kurios tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,86,"eulogeîte_eulogeö pneúmata_pneuma kaì_kai psuchaì_psuchë dikaíön_dikaios tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,87,"eulogeîte_eulogeö `ósioi_`osios kaì_kai tapeinoì_tapeinos tê¸_`o kardía¸_kardia tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[8,88,"eulogeîte_eulogeö Anania_Anania Azaria_Azaria Misaël_Misaël tón_`o kúrion_kurios `umneîte_`umneö kaì_kai `uperupsoûte_`upsoö~`uper autón_autos eis_eis toùs_`o aiônas_aiön "],
[9,1,"proseuchè_proseuchë Marias_Maria tês_`o theotókou_theotokos "],
[9,46,"megalúnei_magalunö `ë_`o psuchè_psuchë mou_egö tón_`o kúrion_kurios "],
[9,47,"kaì_kai ëgallíasen_agalliaomai tó_`o pneûmá_pneuma mou_egö epì_epi tô¸_`o theô¸_theos tô¸_`o sötêrí_sötër mou_egö "],
[9,48,"`óti_`oti epéblepsen_blepö~epi epì_epi tèn_`o tapeínösin_tapeinösis tês_`o doúlës_doulë autoû_autos idoù_idou gàr_gar apó_apo toû_`o nûn_nun makarioûsín_makarizö me_egö pâsai_pas `ai_`o geneaí_genea "],
[9,49,"`óti_`oti epoíësén_poieö moi_egö megaleîa_megaleios `o_`o dunatós_dunatos kaì_kai `ágion_`agios tó_`o ónoma_onoma autoû_autos "],
[9,50,"kaì_kai tó_`o éleos_eleos autoû_autos eis_eis geneàn_genea kaì_kai geneàn_genea toîs_`o fobouménois_fobeö autón_autos "],
[9,51,"epoíësen_poieö krátos_kratos en_en brachíoni_brachiön autoû_autos dieskórpisen_skorpizö~dia `uperëfánous_`uperëfanos dianoía¸_dianoia kardías_kardia autôn_autos "],
[9,52,"katheîlen_`aireö~kata dunástas_dunastës apó_apo thrónön_thronos kaì_kai `úpsösen_`upsoö tapeinoús_tapeinos "],
[9,53,"peinôntas_peinaö enéplësen_pimplëmi~en agathôn_agathos kaì_kai ploutoûntas_plouteö exapésteilen_stellö~ekapo kenoús_kenos "],
[9,54,"antelábeto_lambanö~anti Israël_Israël paidós_pais autoû_autos mnësthênai_mimnëskö eléous_eleos "],
[9,55,"kathòs_kathös elálësen_laleö prós_pros toùs_`o patéras_patër `ëmôn_egö tô¸_`o Abraam_Abraam kaì_kai tô¸_`o spérmati_sperma autoû_autos `éös_`eös aiônos_aiön "],
[9,68,"proseuchè_proseuchë Zachariou_Zacharias eulogëtós_eulogëtos kúrios_kurios `o_`o theós_theos toû_`o Israël_Israël `óti_`oti epesképsato_skeptomai~epi kaì_kai epoíësen_poieö lútrösin_lutrösis tô¸_`o laô¸_laos autoû_autos "],
[9,69,"kaì_kai ègeiren_ageirö kéras_keras sötërías_sötëria `ëmîn_egö en_en tô¸_`o oíkö¸_oikos Dauid_Dauid toû_`o paidós_pais autoû_autos "],
[9,70,"kathòs_kathös elálësen_laleö dià_dia stómatos_stoma tôn_`o `agíön_`agios tôn_`o ap'_apo aiônos_aiön profëtôn_profëtës autoû_autos "],
[9,71,"sötërían_sötëria ex_ek echthrôn_echthros `ëmôn_egö kaì_kai ek_ek cheirós_cheir pántön_pas tôn_`o misoúntön_miseö `ëmâs_egö "],
[9,72,"poiêsai_poieö éleos_eleos metà_meta tôn_`o patérön_patër `ëmôn_egö kaì_kai mnësthênai_mimnëskö diathèkës_diathëkë `agías_`agios autoû_autos "],
[9,73,"`órkon_`orkos `ón_`os òmosen_omnumi prós_pros Abraam_Abraam tón_`o patéra_patër `ëmôn_egö "],
[9,74,"toû_`o doûnai_didömi `ëmîn_egö afóbös_afobös ek_ek cheirós_cheir tôn_`o echthrôn_echthros `ëmôn_egö `rusthéntas_`ruomai "],
[9,75,"latreúein_latreuö autô¸_autos en_en `osiótëti_`osiotës kaì_kai dikaiosúnë¸_dikaiosunë enòpion_enöpion autoû_autos pásas_pas tàs_`o `ëméras_`ëmera `ëmôn_egö "],
[9,76,"kaì_kai sù_su dé_de paidíon_paidion profètës_profëtës `upsístou_`upsistos klëthèsë¸_kaleö proporeúsë¸_poreuomai~pro gàr_gar pró_pro prosòpou_prosöpon kuríou_kurios `etoimásai_`etoimazö `odoùs_`odos autoû_autos "],
[9,77,"toû_`o doûnai_didömi gnôsin_gnösis sötërías_sötëria tô¸_`o laô¸_laos autoû_autos en_en afései_afesis `amartiôn_`amartia `ëmôn_egö "],
[9,78,"dià_dia splágchna_splagchnon eléous_eleos theoû_theos `ëmôn_egö en_en `oîs_`os epesképsato_skeptomai~epi `ëmâs_egö anatolè_anatolë ex_ek `úpsous_`upsos "],
[9,79,"epifânai_fëmi~epi toîs_`o en_en skótei_skotos kaì_kai skiâ¸_skia thanátou_thanatos kathëménois_`ëmai~kata toû_`o kateuthûnai_euthunö~kata toùs_`o pódas_pous `ëmôn_egö eis_eis `odón_`odos eirènës_eirënë "],
[10,1,"ö¸dè_ö¸dë Ësaiou_Ësaias á¸sö_a¸dö dè_dë tô¸_`o ëgapëménö¸_agapaö â¸sma_a¸sma toû_`o agapëtoû_agapëtos tô¸_`o ampelôní_ampelön mou_egö ampelòn_ampelön egéneto_gignomai tô¸_`o ëgapëménö¸_agapaö en_en kérati_keras en_en tópö¸_topos píoni_piön "],
[10,2,"kaì_kai fragmón_fragmos periéthëka_tithëmi~peri kaì_kai efúteusa_futeuö ámpelon_ampelos en_en sörëk_sörëk kaì_kai ö¸kodómësa_oikodomeö púrgon_purgos en_en mésö¸_mesos autês_autos kaì_kai prolènion_prolënion òruxa_orussö en_en autô¸_autos kaì_kai émeina_menö toû_`o poiêsai_poieö stafulèn_stafulë epoíësen_poieö dé_de akánthas_akantha "],
[10,3,"kaì_kai nûn_nun ánthröpos_anthröpos toû_`o Iouda_Iouda kaì_kai `oi_`o enoikoûntes_oikeö~en en_en Ierousalëm_Ierousalëm krínate_krinö en_en emoì_egö kaì_kai anà_ana méson_mesos toû_`o ampelônós_ampelön mou_egö "],
[10,4,"tí_tis poièsö_poieö tô¸_`o ampelôní_ampelön mou_egö éti_eti kaì_kai ouk_ou epoíësa_poieö autô¸_autos dióti_dioti émeina_menö `ína_`ina poièsë¸_poieö stafulèn_stafulë epoíësen_poieö dé_de akánthas_akantha "],
[10,5,"nûn_nun dé_de anaggelô_aggellö~ana `umîn_su tí_tis poièsö_poieö tô¸_`o ampelôní_ampelön mou_egö afelô_`aireö~apo tón_`o fragmón_fragmos autoû_autos kaì_kai éstai_eimi eis_eis diarpagèn_diarpagë kaì_kai kathelô_`aireö~kata tón_`o toîchon_toichos autoû_autos kaì_kai éstai_eimi eis_eis katapátëma_katapatëma "],
[10,6,"kaì_kai anèsö_`iëmi~ana tón_`o ampelôná_ampelön mou_egö kaì_kai ou_ou mè_më tmëthê¸_temnö oudé_oude mè_më skafê¸_skaptö kaì_kai anabèsetai_bainö~ana eis_eis autón_autos `öseì_`ösei eis_eis chérson_chersos ákanthai_akantha kaì_kai taîs_`o nefélais_nefelë enteloûmai_teleö~en toû_`o mè_më bréxai_brechö eis_eis autón_autos `uetón_`uetos "],
[10,7,"`o_`o gàr_gar ampelòn_ampelön kuríou_kurios sabaöth_sabaöth oîkos_oikos Israël_Israël estìn_eimi kaì_kai ánthröpos_anthröpos toû_`o Iouda_Iouda neófuton_neofutos ëgapëménon_agapaö kaì_kai émeina_menö toû_`o poiêsai_poieö krísin_krisis epoíësen_poieö dé_de anomían_anomia kaì_kai ou_ou dikaiosúnën_dikaiosunë allà_alla kraugèn_kraugë "],
[10,8,"ouaì_ouai `oi_`o sunáptontes_`aptö~sun oikían_oikia prós_pros oikían_oikia kaì_kai agrón_agros prós_pros agrón_agros eggízontes_eggizö `ína_`ina toû_`o plësíon_plësion afélöntai_`aireö~apo mè_më oikèsete_oikeö mónoi_monos epì_epi tês_`o gês_gë "],
[10,9,"ëkoústhë_akouö gàr_gar taûta_`outos pánta_pas eis_eis tà_`o ôta_ous kuríou_kurios sabaöth_sabaöth "],
[11,1,"proseuchè_proseuchë Ezekiou_Ezekias "],
[11,10,"egò_egö eîpa_eipon en_en tô¸_`o `úpsei_`upsos tôn_`o `ëmerôn_`ëmera mou_egö poreúsomai_poreuomai en_en púlais_pulë `á¸dou_`a¸dës kataleípsö_leipö~kata tà_`o étë_etos tà_`o epíloipa_epiloipos "],
[11,11,"eîpa_eipon oukéti_ouketi ou_ou mè_më ídö_`oraö tó_`o sötèrion_sötërion toû_`o theoû_theos epì_epi tês_`o gês_gë ou_ou mè_më ídö_`oraö ánthröpon_anthröpos metà_meta katoikoúntön_oikeö~kata "],
[11,12,"exélipon_leipö~ek ek_ek tês_`o suggeneías_suggeneia mou_egö katélipon_leipö~kata tó_`o loipón_loipos tês_`o zöês_zöë mou_egö exêlthen_erchomai~ek kaì_kai apêlthen_erchomai~apo ap'_apo emoû_egö `òsper_`ösper `o_`o katalúön_luö~kata skënèn_skënë pèxas_pëgnumi tó_`o pneûmá_pneuma mou_egö par'_para emoì_egö egéneto_gignomai `ös_`ös `istós_`istos eríthou_erithos eggizoúsës_eggizö ektemeîn_temnö~ek "],
[11,13,"en_en tê¸_`o `ëméra¸_`ëmera ekeínë¸_ekeinos paredóthën_didömi~para `éös_`eös pröì_prö:i `ös_`ös léonti_leön `oútös_`outös sunétripsen_tribö~sun pánta_pas tà_`o ostâ_osteon mou_egö apó_apo gàr_gar tês_`o `ëméras_`ëmera `éös_`eös tês_`o nuktós_nux paredóthën_didömi~para "],
[11,14,"`ös_`ös chelidòn_chelidön `oútö_`outös fönèsö_föneö kaì_kai `ös_`ös peristerá_peristera `oútö_`outös meletèsö_meletaö exélipon_leipö~ek gàr_gar `oi_`o ofthalmoí_ofthalmos mou_egö toû_`o blépein_blepö eis_eis tó_`o `úpsos_`upsos toû_`o ouranoû_ouranos prós_pros tón_`o kúrion_kurios "],
[11,15,"`ós_`os exeílató_`aireö~ek me_egö kaì_kai afeílató_`aireö~apo mou_egö tèn_`o odúnën_odunë tês_`o psuchês_psuchë "],
[11,16,"kúrie_kurios perì_peri autês_autos gàr_gar anëggélë_aggellö~ana soi_su kaì_kai exègeirás_ageirö~ek mou_egö tèn_`o pnoèn_pnoë kaì_kai paraklëtheìs_kaleö~para ézësa_zaö "],
[11,17,"`eílou_`aireö gár_gar mou_egö tèn_`o psuchèn_psuchë `ína_`ina mè_më apólëtai_olluö~apo kaì_kai apérripsas_`riptö~apo opísö_opisö mou_egö pásas_pas tàs_`o `amartías_`amartia mou_egö "],
[11,18,"ou_ou gàr_gar `oi_`o en_en `á¸dou_`a¸dës ainésousín_aineö se_su oudé_oude `oi_`o apothanóntes_thnëskö~apo eulogèsousín_eulogeö se_su oudé_oude elpioûsin_elpizö `oi_`o en_en `á¸dou_`a¸dës tèn_`o eleëmosúnën_eleëmosunë sou_su "],
[11,19,"`oi_`o zôntes_zaö eulogèsousín_eulogeö se_su `ón_`os trópon_tropos kagò_ka:iegö apó_apo gàr_gar tês_`o sèmeron_sëmeron paidía_paidion poièsö_poieö `à_`os anaggeloûsin_aggellö~ana tèn_`o dikaiosúnën_dikaiosunë sou_su kúrie_kurios tês_`o sötërías_sötëria mou_egö "],
[11,20,"kaì_kai ou_ou paúsomai_pauö eulogôn_eulogeö se_su metà_meta psaltëríou_psaltërion pásas_pas tàs_`o `ëméras_`ëmera tês_`o zöês_zöë mou_egö katénanti_katenanti toû_`o oíkou_oikos toû_`o theoû_theos "],
[12,1,"proseuchè_proseuchë Manassë_Manassë kúrie_kurios pantokrátör_pantokratör `o_`o theós_theos tôn_`o patérön_patër `ëmôn_egö toû_`o Abraam_Abraam kaì_kai Isaak_Isaak kaì_kai Iaköb_Iaköb kaì_kai toû_`o spérmatos_sperma autôn_autos toû_`o dikaíou_dikaios "],
[12,2,"`o_`o poièsas_poieö tón_`o ouranón_ouranos kaì_kai tèn_`o gên_gë sùn_sun pantì_pas tô¸_`o kósmö¸_kosmos autôn_autos "],
[12,3,"`o_`o pedèsas_pedeö tèn_`o thálassan_thalassa tô¸_`o lógö¸_logos toû_`o prostágmatós_prostagma sou_su `o_`o kleísas_kleiö tèn_`o ábusson_abussos kaì_kai sfragisámenos_sfragizö tô¸_`o foberô¸_foberos kaì_kai endóxö¸_endoxos onómatí_onoma sou_su "],
[12,4,"`ón_`os pánta_pas fríttei_frittö kaì_kai trémei_tremö apó_apo prosòpou_prosöpon dunámeòs_dunamis sou_su "],
[12,5,"`óti_`oti ástektos_astektos `ë_`o megaloprépeia_megaloprepeia tês_`o dóxës_doxa sou_su kaì_kai anupóstatos_anupostatos `ë_`o orgè_orgë tês_`o epì_epi `amartöloùs_`amartölos apeilês_apeilë sou_su "],
[12,6,"amétrëtón_ametrëtos te_te kaì_kai anexichníaston_anexichniastos tó_`o éleos_eleos tês_`o epaggelías_epaggelia sou_su "],
[12,7,"`óti_`oti sù_su eî_eimi kúrios_kurios `úpsistos_`upsistos eúsplagchnos_eusplagchnos makróthumos_makrothumos kaì_kai poluéleos_polueleos kaì_kai metanoôn_noeö~meta epì_epi kakíais_kakia anthròpön_anthröpos "],
[12,8,"sù_su oûn_oun kúrie_kurios `o_`o theós_theos tôn_`o dikaíön_dikaios ouk_ou éthou_tithëmi metánoian_metanoia dikaíois_dikaios tô¸_`o Abraam_Abraam kaì_kai Isaak_Isaak kaì_kai Iaköb_Iaköb toîs_`o ouch_ou `ëmartëkósin_`amartanö soi_su all'_alla éthou_tithëmi metánoian_metanoia emoì_egö tô¸_`o `amartölô¸_`amartölos "],
[12,9,"dióti_dioti `èmarton_`amartanö `upér_`uper arithmón_arithmos psámmou_psammos thalássës_thalassa eplèthunan_plëthunö `ai_`o anomíai_anomia mou_egö kúrie_kurios eplèthunan_plëthunö kaì_kai ouk_ou eimì_eimi áxios_axios atenísai_atenizö kaì_kai ideîn_`oraö tó_`o `úpsos_`upsos toû_`o ouranoû_ouranos apó_apo plèthous_plëthos tôn_`o adikiôn_adikia mou_egö "],
[12,10,"katakamptómenos_kamptö~kata pollô¸_polus desmô¸_desmos sidèrou_sidëros eis_eis tó_`o ananeûsaí_neuö~ana me_egö `upér_`uper `amartiôn_`amartia mou_egö kaì_kai ouk_ou éstin_eimi moi_egö ánesis_anesis dióti_dioti paròrgisa_orgizö~para tón_`o thumón_thumos sou_su kaì_kai tó_`o ponërón_ponëros enòpión_enöpion sou_su epoíësa_poieö stèsas_`istëmi bdelúgmata_bdelugma kaì_kai plëthúnas_plëthunö prosochthísmata_prosochthisma "],
[12,11,"kaì_kai nûn_nun klínö_klinö gónu_gonu kardías_kardia deómenos_deö tês_`o parà_para soû_su chrëstótëtos_chrëstotës "],
[12,12,"`ëmártëka_`amartanö kúrie_kurios `ëmártëka_`amartanö kaì_kai tàs_`o anomías_anomia mou_egö egò_egö ginòskö_gignöskö "],
[12,13,"aitoûmai_aiteö deómenós_deö sou_su ánes_`iëmi~ana moi_egö kúrie_kurios ánes_`iëmi~ana moi_egö mè_më sunapolésë¸s_ollumi~sunapo me_egö taîs_`o anomíais_anomia mou_egö mëdé_mëde eis_eis tón_`o aiôna_aiön mënísas_mëniö tërèsë¸s_tëreö tà_`o kaká_kakos moi_egö mëdé_mëde katadikásë¸s_dikazö~kata me_egö en_en toîs_`o katötátois_katötatos tês_`o gês_gë `óti_`oti sù_su eî_eimi kúrie_kurios `o_`o theós_theos tôn_`o metanooúntön_noeö~meta "],
[12,14,"kaì_kai en_en emoì_egö deíxë¸s_deiknuö tèn_`o agathösúnën_agathösunë sou_su `óti_`oti anáxion_anaxios ónta_eimi sòseis_sözö me_egö katà_kata tó_`o polù_polus éleós_eleos sou_su "],
[12,15,"kaì_kai ainésö_aineö se_su dià_dia pantós_pas en_en taîs_`o `ëmérais_`ëmera tês_`o zöês_zöë mou_egö `óti_`oti sé_su `umneî_`umneö pâsa_pas `ë_`o dúnamis_dunamis tôn_`o ouranôn_ouranos kaì_kai soû_su estin_eimi `ë_`o dóxa_doxa eis_eis toùs_`o aiônas_aiön amën_amën "],
[13,1,"proseuchè_proseuchë Sumeön_Sumeön "],
[13,29,"nûn_nun apolúeis_luö~apo tón_`o doûlón_doulos sou_su déspota_despotës katà_kata tó_`o `rêmá_`rëma sou_su en_en eirènë¸_eirënë "],
[13,30,"`óti_`oti eîdon_`oraö `oi_`o ofthalmoí_ofthalmos mou_egö tó_`o sötèrión_sötërion sou_su "],
[13,31,"`ó_`os `ëtoímasas_`etoimazö katà_kata prósöpon_prosöpon pántön_pas tôn_`o laôn_laos "],
[13,32,"fôs_fös eis_eis apokálupsin_apokalupsis ethnôn_ethnos kaì_kai dóxan_doxa laoû_laos sou_su Israël_Israël "],
[14,1,"`úmnos_`umnos `eöthinós_`eöthinos dóxa_doxa en_en `upsístois_`upsistos theô¸_theos "],
[14,2,"kaì_kai epì_epi gês_gë eirènë_eirënë "],
[14,3,"en_en anthròpois_anthröpos eudokía_eudokia "],
[14,4,"ainoûmén_aineö se_su "],
[14,5,"eulogoûmén_eulogeö se_su "],
[14,6,"proskunoûmén_kuneö~pros se_su "],
[14,7,"doxologoûmén_doxologeö se_su "],
[14,8,"eucharistoûmén_eucharisteö soi_su "],
[14,9,"dià_dia tèn_`o megálën_megas sou_su dóxan_doxa "],
[14,10,"kúrie_kurios basileû_basileus "],
[14,11,"epouránie_epouranios "],
[14,12,"theé_theos patèr_patër pantokrátör_pantokratör "],
[14,13,"kúrie_kurios `uié_`uios monogenè_monogenës "],
[14,14,"Iësoû_Iësous Christé_Christos "],
[14,15,"kaì_kai `ágion_`agios pneûma_pneuma "],
[14,16,"kúrie_kurios `o_`o theós_theos "],
[14,17,"`o_`o amnós_amnos toû_`o theoû_theos "],
[14,18,"`o_`o `uiós_`uios toû_`o patrós_patër "],
[14,19,"`o_`o aírön_airö tàs_`o `amartías_`amartia toû_`o kósmou_kosmos "],
[14,20,"eléëson_eleeö `ëmâs_egö "],
[14,21,"`o_`o aírön_airö tàs_`o `amartías_`amartia toû_`o kósmou_kosmos "],
[14,22,"prósdexai_dechomai~pros tèn_`o déësin_deësis `ëmôn_egö "],
[14,23,"`o_`o kathèmenos_`ëmai~kata en_en dexiâ¸_dexios toû_`o patrós_patër "],
[14,24,"eléëson_eleeö `ëmâs_egö "],
[14,25,"`óti_`oti sù_su eî_eimi mónos_monos `ágios_`agios "],
[14,26,"sù_su eî_eimi mónos_monos kúrios_kurios "],
[14,27,"Iësoûs_Iësous Christós_Christos "],
[14,28,"eis_eis dóxan_doxa theoû_theos patrós_patër amën_amën "],
[14,29,"kath'_kata `ekástën_`ekastos `ëméran_`ëmera eulogèsö_eulogeö se_su "],
[14,30,"kaì_kai ainésö_aineö tó_`o ónomá_onoma sou_su eis_eis tón_`o aiôna_aiön "],
[14,31,"kaì_kai eis_eis tón_`o aiôna_aiön toû_`o aiônos_aiön "],
[14,32,"kataxíöson_axioö~kata kúrie_kurios kaì_kai tèn_`o `ëméran_`ëmera taútën_`outos "],
[14,33,"anamartètous_anamartëtos fulachthênai_fulassö `ëmâs_egö "],
[14,34,"eulogëtós_eulogëtos eî_eimi kúrie_kurios `o_`o theós_theos tôn_`o patérön_patër `ëmôn_egö "],
[14,35,"kaì_kai ainetón_ainetos kaì_kai dedoxasménon_doxazö tó_`o ónomá_onoma sou_su eis_eis toùs_`o aiônas_aiön amën_amën "],
[14,36,"eulogëtós_eulogëtos eî_eimi kúrie_kurios dídaxón_didaskö me_egö tà_`o dikaiòmatá_dikaiöma sou_su "],
[14,37,"eulogëtós_eulogëtos eî_eimi kúrie_kurios dídaxón_didaskö me_egö tà_`o dikaiòmatá_dikaiöma sou_su "],
[14,38,"eulogëtós_eulogëtos eî_eimi kúrie_kurios dídaxón_didaskö me_egö tà_`o dikaiòmatá_dikaiöma sou_su "],
[14,39,"kúrie_kurios katafugè_katafugë egenèthës_gignomai `ëmîn_egö en_en geneâ¸_genea kaì_kai geneâ¸_genea "],
[14,40,"egò_egö eîpa_eipon kúrie_kurios eléësón_eleeö me_egö "],
[14,41,"íasai_iaomai tèn_`o psuchèn_psuchë mou_egö `óti_`oti `èmartón_`amartanö soi_su "],
[14,42,"kúrie_kurios prós_pros sé_su katéfuga_fugö~kata "],
[14,43,"dídaxón_didaskö me_egö toû_`o poieîn_poieö tó_`o thélëmá_thelëma sou_su `óti_`oti sù_su eî_eimi `o_`o theós_theos mou_egö "],
[14,44,"`óti_`oti parà_para soì_su pëgè_pëgë zöês_zöë "],
[14,45,"en_en tô¸_`o fötí_fös sou_su opsómetha_`oraö fôs_fös "],
[14,46,"paráteinon_teinö~para tó_`o éleós_eleos sou_su toîs_`o ginòskousín_gignöskö se._su "]
])
