Bib.ret([
[1001,"pollôn<polus> kaì<kai> megàlōn<megas> `ēmîn<egō> dià<dia> toû<`o> nómou<nómos> kaì<kai> tôn<`o> profētôn<profētēs> "],
[1002,"kaì<kai> tôn<`o> àllōn<allos> tôn<`o> kat'<kata> autoùs<autos> ēkolouthēkótōn<akoloutheō> dedoménōn<didōmi> "],
[1003,"`upér<`uper> `ôn<`os> déon<dei> estìn<eimi> epaineîn<epaineō> tón<`o> Israēl<Israēl> paideìas<paideia> kaì<kai> sofìas<sofia> "],
[1004,"kaì<kai> `ōs<`ōs> ou'<ou'> mónon<monos> autoùs<autos> toùs<`o> anaginòskontas<anaginōskō> déon<dei> estìn<eimi> epistèmonas<epistēmōn> gìnesthai<ginomai> "],
[1005,"allà<alla> kaì<kai> toîs<`o> ektós<ektos> dùnasthai<dunamai> toùs<`o> filomathoûntas<filomatheō> chrēsìmous<chrēsimos> eînai<eimi> "],
[1006,"kaì<kai> légontas<legō> kaì<kai> gràfontas<grafō> "],
[1007,"`o<`o> pàppos<pappos> mou<egō> Iēsoûs<Iēsous> epì<epi> pleîon<polus> `eautón<`eautou> doùs<didōmi> "],
[1008,"eìs<eis> te<te> tèn<`o> toû<`o> nómou<nómos> "],
[1009,"kaì<kai> tôn<`o> profētôn<profētēs> "],
[1010,"kaì<kai> tôn<`o> àllōn<allos> patrìōn<patrios> biblìōn<biblion> anàgnōsin<anagnōsis> "],
[1011,"kaì<kai> en<en> toùtois<`outos> `ikanèn<`ikanos> `éxin<`exis> peripoiēsàmenos<peripoieō> "],
[1012,"proèchthē<proagō> kaì<kai> autós<autos> suggràpsai<suggrafō> ti<tis> tôn<`o> eis<eis> paideìan<paideia> kaì<kai> sofìan<sofia> anēkóntōn<anēkō> "],
[1013,"`ópōs<`opōs> `oi<`o> filomatheîs<filomathēs> kaì<kai> toùtōn<`outos> énochoi<enochos> genómenoi<ginomai> "],
[1014,"pollôj<polus> mâllon<mallon> epiprosthôsin<epiprostithēmi> dià<dia> tês<`o> ennómou<ennomos> biòseōs<biōsis> "],
[1015,"parakéklēsthe<parakaleō> oûn<oun> "],
[1016,"met'<meta> eunoìas<eunoia> kaì<kai> prosochês<prosochē> "],
[1017,"tèn<`o> anàgnōsin<anagnōsis> poieîsthai<poieō> "],
[1018,"kaì<kai> suggnòmēn<suggnōmē> échein<echō> "],
[1019,"ef'<epi> `oîs<`os> àn<an> dokômen<dokeō> "],
[1020,"tôn<`o> katà<kata> tèn<`o> `ermēneìan<`ermēneia> pefiloponēménōn<filoponeō> tisìn<tis> tôn<`o> léxeōn<lexis> adunameîn<adunameō> "],
[1021,"ou'<ou'> gàr<gar> isodunameî<isodunameō> "],
[1022,"autà<autos> en<en> `eautoîs<`eautou> Ebra:istì<Ebraisti> legómena<legō> kaì<kai> `ótan<`otan> metachthêj<metagō> eis<eis> `etéran<`eteros> glôssan<glōssa> "],
[1023,"ou'<ou'> mónon<monos> dé<de> taûta<`outos> "],
[1024,"allà<alla> kaì<kai> autós<autos> `o<`o> nómos<nómos> kaì<kai> `ai<`o> profēteîai<profēteia> "],
[1025,"kaì<kai> tà<`o> loipà<loipos> tôn<`o> biblìōn<biblion> "],
[1026,"ou'<ou'> mikràn<mikros> échei<echō> tèn<`o> diaforàn<diafora> en<en> `eautoîs<`eautou> legómena<legō> "],
[1027,"en<en> gàr<gar> tôj<`o> ogdóōj<ogdoos> kaì<kai> triakostôj<triakostos> étei<etos> epì<epi> toû<`o> Euergétou<euergetēs> basiléōs<basileus> "],
[1028,"paragenētheìs<paraginomai> eis<eis> Aìgupton<Aiguptos> kaì<kai> sugchronìsas<sugchronizō> "],
[1029,"`euròn<`euriskō> ou'<ou'> mikrâs<mikros> paideìas<paideia> afómoion<afomoios> "],
[1030,"anagkaiótaton<anagkaios> ethémēn<tithēmi> kaì<kai> autós<autos> tina<tis> prosenégkasthai<prosferō> spoudèn<spoudē> kaì<kai> filoponìan<filoponia> toû<`o> methermēneûsai<methermēneuō> tènde<`ode> tèn<`o> bìblon<biblos> "],
[1031,"pollèn<polus> agrupnìan<agrupnia> kaì<kai> epistèmēn<epistēmē> prosenegkàmenos<prosferō> "],
[1032,"en<en> tôj<`o> diastèmati<diastēma> toû<`o> chrónou<chronos> "],
[1033,"prós<pros> tó<`o> epì<epi> péras<peras> agagónta<agō> tó<`o> biblìon<biblion> ekdósthai<ekdidōmi> "],
[1034,"kaì<kai> toîs<`o> en<en> têj<`o> paroikìaj<paroikia> bouloménois<boulomai> filomatheîn<filomatheō> "],
[1035,"prokataskeuazoménous<prokataskeuazō> tà<`o> èthē<ēthos> "],
[1036,"ennómōs<ennomōs> bioteùein<bioteuō> "]
])
