Bib.ret([
[1001,""],
[1002,""],
[1003,""],
[1004,""],
[1005,""],
[1006,"kaì<kai> èrchonto<erchomai> krìseis<krisis> ex<ek> àllōn<allos> póleōn<polis> prós<pros> autoùs<autos> "],
[1007,"`oûtoi<`outos> idóntes<`oraō> gunaîka<gunē> asteìan<asteios> tôj<`o> eìdei<eidos> gunaîka<gunē> adelfoû<adelfos> autôn<autos> ek<ek> tôn<`o> `uiôn<`uios> Israēl<Israēl> ónoma<onoma> Sousannan<Sousanna> thugatéra<thugatēr> Chelkiou<Chelkios> gunaîka<gunē> Iōakim<Iōakim> peripatoûsan<peripateō> en<en> tôj<`o> paradeìsōj<paradeisos> toû<`o> andrós<anēr> autês<autos> tó<`o> deilinón<deilinos> kaì<kai> epithumèsantes<epithumeō> autês<autos> "],
[1008,""],
[1009,"diéstrepsan<diastrefō> tón<`o> noûn<nous> autôn<autos> kaì<kai> exéklinan<ekklinō> toùs<`o> ofthalmoùs<ofthalmos> autôn<autos> toû<`o> mè<mē> blépein<blepō> eis<eis> tón<`o> ouranón<ouranos> mēdé<mēde> mnēmoneùein<mnēmoneuō> krimàtōn<krima> dikaìōn<dikaios> "],
[1010,"kaì<kai> amfóteroi<amfoteroi> êsan<eimi> katanenugménoi<katanussomai> perì<peri> autês<autos> kaì<kai> `éteros<`eteros> tôj<`o> `etérōj<`eteros> ou'<ou'> prosepoieîto<prospoieō> tó<`o> kakón<kakos> tó<`o> échon<echō> autoùs<autos> perì<peri> autês<autos> oudé<oude> `ē<`o> gunè<gunē> égnō<ginōskō> tó<`o> prâgma<pragma> toûto<`outos> "],
[1011,""],
[1012,"kaì<kai> `ōs<`ōs> egìneto<ginomai> órthros<orthros> erchómenoi<erchomai> éklepton<kleptō> allèlous<allēlōn> speùdontes<speudō> tìs<tis> fanèsetai<fainō> autêj<autos> próteros<proteros> kaì<kai> lalèsei<laleō> prós<pros> autèn<autos> "],
[1013,"kaì<kai> idoù<idou> `aùtē<`outos> katà<kata> tó<`o> eiōthós<ethō> periepàtei<peripateō> kaì<kai> `o<`o> `eîs<`eis> tôn<`o> presbutérōn<presbuteros> elēlùthei<erchomai> kaì<kai> idoù<idou> `o<`o> `éteros<`eteros> paregéneto<paraginomai> kaì<kai> `eîs<`eis> tón<`o> `éteron<`eteros> anékrine<anakrinō> légōn<legō> tì<tis> sù<su> `oùtōs<`outōs> órthrou<orthros> exêlthes<exerchomai> ou'<ou'> paralabòn<paralambanō> me<egō> kaì<kai> exōmologèsanto<exomologeō> prós<pros> allèlous<allēlōn> `ekàteros<`ekateros> tèn<`o> odùnēn<odunē> autoû<autos> "],
[1014,""],
[1015,""],
[1016,""],
[1017,""],
[1018,""],
[1019,"kaì<kai> eîpen<legō> `eîs<`eis> tôj<`o> `etérōj<`eteros> poreuthômen<poreuomai> prós<pros> autèn<autos> kaì<kai> sunthémenoi<suntithēmi> prosèlthosan<proserchomai> autêj<autos> kaì<kai> exebiàzonto<ekbiazō> autèn<autos> "],
[1020,""],
[1021,""],
[1022,"kaì<kai> eîpen<legō> autoîs<autos> `ē<`o> Ioudaìa<Ioudaia> oîda<oida> `óti<`oti> eàn<ean> pràxō<prassō> toûto<`outos> thànatós<thanatos> moì<egō> esti<eimi> kaì<kai> eàn<ean> mè<mē> pràxō<prassō> ouk<ou'> ekfeùxomai<ekfeugō> tàs<`o> cheîras<cheir> `umôn<su> "],
[1023,"kàllion<kalos> dé<de> me<egō> mè<mē> pràxasan<prassō> empeseîn<empiptō> eis<eis> tàs<`o> cheîras<cheir> `umôn<su> è<ē> `amarteîn<`amartanō> enòpion<enōpion> kurìou<kurios> "],
[1024,""],
[1025,""],
[1026,""],
[1027,""],
[1028,"`oi<`o> dé<de> parànomoi<paranomos> àndres<anēr> apéstrepsan<apostrefō> apeiloûntes<apeileō> en<en> `eautoîs<`eautou> kaì<kai> enedreùontes<enedreuō> `ìna<`ina> thanatòsousin<thanatoō> autèn<autos> kaì<kai> elthóntes<erchomai> epì<epi> tèn<`o> sunagōgèn<sunagōgē> tês<`o> póleōs<polis> `oû<`os> parōjkoûsan<paroikeō> kaì<kai> sunèdreusan<sunedreuō> `oi<`o> óntes<eimi> ekeî<ekei> pàntes<pas> `oi<`o> `uioì<`uios> Israēl<Israēl> "],
[1029,"kaì<kai> anastàntes<anistēmi> `oi<`o> dùo<duo> presbùteroi<presbuteros> kaì<kai> kritaì<kritēs> eîpan<legō> aposteìlate<apostellō> epì<epi> Sousannan<Sousanna> thugatéra<thugatēr> Chelkiou<Chelkios> `ètis<`ostis> estì<eimi> gunè<gunē> Iōakim<Iōakim> `oi<`o> dé<de> euthéōs<eutheōs> ekàlesan<kaleō> autèn<autos> "],
[1030,"`ōs<`ōs> dé<de> paregenèthē<paraginomai> `ē<`o> gunè<gunē> sùn<sun> tôj<`o> patrì<patēr> `eautês<`eautou> kaì<kai> têj<`o> mētrì<mētēr> kaì<kai> `oi<`o> paîdes<pais> kaì<kai> `ai<`o> paidìskai<paidiskē> autês<autos> óntes<eimi> tón<`o> arithmón<arithmos> pentakósioi<pentakosioi> paregénonto<paraginomai> kaì<kai> tà<`o> paidìa<paidion> Sousannas<Sousanna> téssara<tessares> "],
[1031,"ên<eimi> dé<de> `ē<`o> gunè<gunē> truferà<truferos> sfódra<sfodra> "],
[1032,"kaì<kai> prosétaxan<prostassō> `oi<`o> parànomoi<paranomos> apokalùpsai<apokaluptō> autèn<autos> `ìna<`ina> emplēsthôsi<empiplēmi> kàllous<kallos> epithumìas<epithumia> autês<autos> "],
[1033,"kaì<kai> eklaìosan<klaiō> `oi<`o> par'<para> autês<autos> pàntes<pas> kaì<kai> `ósoi<`osos> autèn<autos> èjdeisan<oida> pàntes<pas> "],
[1034,"anastàntes<anistēmi> dé<de> `oi<`o> presbùteroi<presbuteros> kaì<kai> kritaì<kritēs> epéthēkan<epitithēmi> tàs<`o> cheîras<cheir> autôn<autos> epì<epi> tês<`o> kefalês<kefalē> autês<autos> "],
[1035,"`ē<`o> dé<de> kardìa<kardia> autês<autos> epepoìthei<peithō> epì<epi> kurìōj<kurios> tôj<`o> theôj<theos> autês<autos> kaì<kai> anakùpsasa<anakuptō> éklausen<klaiō> en<en> `eautêj<`eautou> légousa<legō> "],
[1035.01,"kùrie<kurios> `o<`o> theós<theos> `o<`o> aiònios<aiōnios> `o<`o> eidòs<oida> tà<`o> pànta<pas> prìn<prin> genéseōs<genesis> autôn<autos> sù<su> oîdas<oida> `óti<`oti> ouk<ou'> epoìēsa<poieō> `à<`os> ponēreùontai<ponēreuomai> `oi<`o> ànomoi<anomos> `oûtoi<`outos> ep'<epi> emoì<egō> kaì<kai> eisèkouse<eisakouō> kùrios<kurios> tês<`o> deèseōs<deēsis> autês<autos> "],
[1036,"`oi<`o> dé<de> dùo<duo> presbùteroi<presbuteros> eîpan<legō> `ēmeîs<egō> periepatoûmen<peripateō> en<en> tôj<`o> paradeìsōj<paradeisos> toû<`o> andrós<anēr> autês<autos> "],
[1037,"kaì<kai> kukloûntes<kukloō> tó<`o> stàdion<stadion> eìdomen<`oraō> taùtēn<`outos> anapauoménēn<anapauō> metà<meta> andrós<anēr> kaì<kai> stàntes<`istēmi> etheōroûmen<theōreō> autoùs<autos> `omiloûntas<`omileō> allèlois<allēlōn> "],
[1038,"kaì<kai> autoì<autos> ouk<ou'> èjdeisan<oida> `óti<`oti> `eistèkeimen<`istēmi> tóte<tote> suneipàmetha<sumfēmi> allèlois<allēlōn> légontes<legō> màthōmen<manthanō> tìnes<tis> eisìn<eimi> `oûtoi<`outos> "],
[1039,"kaì<kai> proselthóntes<proserchomai> epégnōmen<epiginōskō> autèn<autos> `o<`o> dé<de> neanìskos<neaniskos> éfuge<feugō> sugkekalumménos<sugkaluptō> "],
[1040,"taùtēs<`outos> dé<de> epilabómenoi<epilambanō> epērōtômen<eperōtaō> autèn<autos> tìs<tis> `o<`o> ànthrōpos<anthrōpos> "],
[1041,"kaì<kai> ouk<ou'> apèggeilen<apaggellō> `ēmîn<egō> tìs<tis> ên<eimi> taûta<`outos> marturoûmen<martureō> kaì<kai> epìsteusen<pisteuō> autoîs<autos> `ē<`o> sunagōgè<sunagōgē> pâsa<pas> `ōs<`ōs> presbutérōn<presbuteros> óntōn<eimi> kaì<kai> kritôn<kritēs> toû<`o> laoû<laos> "],
[1042,""],
[1043,""],
[1044,"kaì<kai> idoù<idou> àggelos<aggelos> kurìou<kurios> ekeìnēs<ekeinos> exagoménēs<exagō> apolésthai<apollumi> kaì<kai> édōken<didōmi> `o<`o> àggelos<aggelos> kathòs<kathōs> prosetàgē<prostassō> pneûma<pneuma> sunéseōs<sunesis> neōtérōj<neos> ónti<eimi> Daniēl<Daniēl> "],
[1045,""],
[1046,""],
[1047,""],
[1048,"diasteìlas<diastellō> dé<de> Daniēl<Daniēl> tón<`o> óchlon<ochlos> kaì<kai> stàs<`istēmi> en<en> mésōj<mesos> autôn<autos> eîpen<legō> `oùtōs<`outōs> mōroì<mōros> `uioì<`uios> Israēl<Israēl> ouk<ou'> anakrìnantes<anakrinō> oudé<oude> tó<`o> safés<safēs> epignóntes<epiginōskō> apekrìnate<apokrinomai> thugatéra<thugatēr> Israēl<Israēl> "],
[1049,""],
[1050,""],
[1051,"kaì<kai> nûn<nun> diachōrìsaté<diachōrizō> moi<egō> autoùs<autos> ap'<apo> allèlōn<allēlōn> makràn<makran> `ìna<`ina> etàsō<etazō> autoùs<autos> "],
[1052,"`ōs<`ōs> dé<de> diechōrìsthēsan<diachōrizō> eîpen<legō> Daniēl<Daniēl> têj<`o> sunagōgêj<sunagōgē> nûn<nun> mè<mē> blépsēte<blepō> `óti<`oti> `oûtoì<`outos> eisi<eimi> presbùteroi<presbuteros> légontes<legō> ou'<ou'> mè<mē> pseùsōntai<pseudomai> allà<alla> anakrinô<anakrinō> autoùs<autos> katà<kata> tà<`o> `upopìptontà<`upopiptō> moi<egō> kaì<kai> ekàlese<kaleō> tón<`o> `éna<`eis> autôn<autos> kaì<kai> prosègagon<prosagō> tón<`o> presbùteron<presbuteros> tôj<`o> neōtérōj<neos> kaì<kai> eîpen<legō> autôj<autos> Daniēl<Daniēl> àkoue<akouō> àkoue<akouō> pepalaiōméne<palaioō> `ēmerôn<`ēmera> kakôn<kakos> nûn<nun> `èkasì<`ēkō> sou<su> `ai<`o> `amartìai<`amartia> `às<`os> epoìeis<poieō> tó<`o> próteron<proteros> "],
[1053,"pisteutheìs<pisteuō> akoùein<akouō> kaì<kai> krìnein<krinō> krìseis<krisis> thànaton<thanatos> epiferoùsas<epiferō> kaì<kai> tón<`o> mén<men> athôjon<athōjos> katékrinas<katakrinō> toùs<`o> dé<de> enóchous<enochos> ēfìeis<afiēmi> toû<`o> kurìou<kurios> légontos<legō> athôjon<athōjos> kaì<kai> dìkaion<dikaios> ouk<ou'> apokteneîs<apokteinō> "],
[1054,"nûn<nun> oûn<oun> `upó<`upo> tì<tis> déndron<dendron> kaì<kai> potapôj<potapos> toû<`o> paradeìsou<paradeisos> tópōj<topos> `eòrakas<`oraō> autoùs<autos> óntas<eimi> sùn<sun> `eautoîs<`eautou> kaì<kai> eîpen<legō> `o<`o> asebès<asebēs> `upó<`upo> schînon<schinos> "],
[1055,"eîpen<legō> dé<de> `o<`o> neòteros<neos> orthôs<orthōs> épseusai<pseudomai> eis<eis> tèn<`o> seautoû<seautou> psuchèn<psuchē> `o<`o> gàr<gar> àggelos<aggelos> kurìou<kurios> schìsei<schizō> sou<su> tèn<`o> psuchèn<psuchē> sèmeron<sēmeron> "],
[1056,"kaì<kai> toûton<`outos> metastèsas<methistēmi> eîpe<legō> prosagageîn<prosagō> autôj<autos> tón<`o> `éteron<`eteros> kaì<kai> toùtōj<`outos> dé<de> eîpen<legō> dià<dia> tì<tis> diestramménon<diastrefō> tó<`o> spérma<sperma> sou<su> `ōs<`ōs> Sidônos<Sidōn> kaì<kai> ouch<ou'> `ōs<`ōs> Iouda<Ioudas> tó<`o> kàllos<kallos> se<su> ēpàtēsen<apataō> `ē<`o> miarà<miaros> epithumìa<epithumia> "],
[1057,"kaì<kai> `oùtōs<`outōs> epoieîte<poieō> thugatràsin<thugatēr> Israēl<Israēl> kaì<kai> ekeînai<ekeinos> foboùmenai<fobeō> `ōmiloûsan<`omileō> `umîn<su> all'<alla> ou'<ou'> thugàtēr<thugatēr> Iouda<Ioudas> `upémeine<`upomenō> tèn<`o> nóson<nosos> `umôn<su> en<en> anomìaj<anomia> `upenegkeîn<`upoferō> "],
[1058,"nûn<nun> oûn<oun> lége<legō> moi<egō> `upó<`upo> tì<tis> déndron<dendron> kaì<kai> en<en> poìōj<poios> toû<`o> kèpou<kēpos> tópōj<topos> katélabes<katalambanō> autoùs<autos> `omiloûntas<`omileō> allèlois<allēlōn> `o<`o> dé<de> eîpen<legō> `upó<`upo> prînon<prinos> "],
[1059,"kaì<kai> eîpen<legō> Daniēl<Daniēl> `amartōlé<`amartōlos> nûn<nun> `o<`o> àggelos<aggelos> kurìou<kurios> tèn<`o> `romfaìan<`romfaia> `éstēken<`istēmi> échōn<echō> `éōs<`eōs> `o<`o> laós<laos> exolethreùsei<exolethreuō> `umâs<su> `ìna<`ina> kataprìsēj<katapriō> se<su> "],
[1060,"kaì<kai> pâsa<pas> `ē<`o> sunagōgè<sunagōgē> anebóēsen<anaboaō> epì<epi> tôj<`o> neōtérōj<neos> `ōs<`ōs> ek<ek> toû<`o> idìou<idios> stómatos<stoma> `omológous<`omologos> autoùs<autos> katéstēsen<kathistēmi> amfotérous<amfoteroi> pseudomàrturas<pseudomartus> kaì<kai> `ōs<`ōs> `o<`o> nómos<nómos> diagoreùei<diagoreuō> epoìēsan<poieō> autoîs<autos> kathòs<kathōs> eponēreùsanto<ponēreuomai> katà<kata> tês<`o> adelfês<adelfē> kaì<kai> efìmōsan<fimoō> autoùs<autos> kaì<kai> exagagóntes<exagō> érripsan<`riptō> eis<eis> fàragga<faragx> tóte<tote> `o<`o> àggelos<aggelos> kurìou<kurios> érripse<`riptō> pûr<pur> dià<dia> mésou<mesos> autôn<autos> kaì<kai> esòthē<sōjzō> `aîma<`aima> anaìtion<anaitios> en<en> têj<`o> `ēméraj<`ēmera> ekeìnēj<ekeinos> "],
[1061,""],
[1062,""],
[1063,"dià<dia> toûto<`outos> `oi<`o> neòteroi<neos> agapētoì<agapētos> Iakōb<Iakōb> en<en> têj<`o> `aplótēti<`aplotēs> autôn<autos> kaì<kai> `ēmeîs<egō> fulassòmetha<fulassō> eis<eis> `uioùs<`uios> dunatoùs<dunatos> neōtérous<neos> eusebèsousi<eusebeō> gàr<gar> neòteroi<neos> kaì<kai> éstai<eimi> en<en> autoîs<autos> pneûma<pneuma> epistèmēs<epistēmē> kaì<kai> sunéseōs<sunesis> eis<eis> aiôna<aiōn> aiônos<aiōn> "]
])
